MaterializeInc/materialize

src/dataflow-types/src/plan/mod.rs
src/expr/src/explain.rs
src/expr/src/id.rs
src/sql/src/plan.rs
src/sql/src/plan/explain.rs
src/sql/src/plan/statement/ddl.rs
src/transform/src/join_implementation.rs
src/transform/src/monotonic.rs

Removing dead code is its own reward
N/A
none

Remove some more dead code related to bare vs. transformed sources.

---

ci/test/pipeline.template.yml

* This PR fixes a previously unreported bug: a job got stuck running for an entire week.
- N/A

ci/test: add timeouts to all tests

---

src/ore/src/retry.rs

Previously if a canceling retry operation timed out the underlying
function, the error returned was always "deadline exceeded." This is not
very informative. In most cases, we can do better: if the underlying
function has previously failed with an error message, that error message
is likely quite a bit more useful than "deadline exceeded", and we
should return it instead.
* Somewhere between a bug and a feature.
- N/A

ore/retry: improve semantics of canceling retry errors

---

test/test-certs/create-certs.sh

Signed-off-by: Petros Angelatos <petrosagg@gmail.com>
-

force regenerate test certificates

---

src/coord/src/catalog/storage.rs
src/dataflow-types/src/client/controller/storage.rs
src/stash/src/lib.rs
src/stash/src/sqlite.rs
src/stash/tests/stash.rs
src/testdrive/src/action/verify_timestamp_compaction.rs

Make a Stash trait so it can be backed by other implementations.
- N/A

stash: split into trait + impl

---

src/repr/src/proto/adt/array.rs
src/repr/src/proto/mod.rs

Add a `ProtoRepr` to encapsulate specifics for converting unsupported primitive Rust types into a wider type that is supported in Protobuf message definitions.
Implement `ProtoRepr` for:
- `usize` (represented as `u64`),
- `char` (represented as `String`), and
- `Option<T>`.
At the moment the logic of representing non-Protobuf  types in prost-derived message types is inlined ad-hoc in any `From` and `TryFrom` transform between the original `$T` type and the corresponding `Proto$T` type. This aims to pull the conversions into canonical form behind the new `ProtoRepr` trait.
The first commit introduces the basic infrastructure. The second commit makes use of it in the `array.rs` conversions. See commit messages for details.
N/A

repr: add `ProtoRepr` trait

---

src/dataflow-types/src/client/controller/storage.rs

Storage workers are not smart enough right now to only report new
changes to the timestamp bindings they contain the their respective
frontiers. Consequently we need to guard advancing the stash frontier
that asserts this doesn't happen until we fix the storage workers.
This is not new behavior, we just didn't have the assertion in the
previous way we were storing timestamp bindings, but we should fix it
anyway because once we're sure this never happens the assertion might
catch real bugs.
Fixes #11594
We should do a nightly run on this commit before merging
-

storage: guard timestamp binding seal frontier from regressing

---

src/persist-client/src/impl/machine.rs
src/persist-client/src/lib.rs
src/persist/src/location.rs
src/persist/src/mem.rs
src/persist/src/sqlite.rs

Before, one Consensus would be shared between all opened shards while the state stored in Consensus was only meant to be the state of a single shard.
This adds keys to the methods of the Consensus trait so that we can differentiate between different shards.

persist-client: separate state of multiple shards in Consensus

---

src/coord/src/catalog.rs

Updates an out of date documentation comment.

sql: Update old documentation comment

---

doc/user/content/overview/api-components.md

Sources don't write data, they read data.

docs/user: fix source description

---

src/persist/src/location.rs

This commit adds two unit tests that:
1. Sanity check that calling compare_and_set with a stale version of current doesn't
work.
2. Sanity check that calling compare_and_set with a larger data size (10 KiB) works.
-

persist: add new unit tests for Consensus.

---

src/coord/src/catalog.rs
src/coord/src/coord.rs

Previously opening the catalog would return a list of log variant,
global ID pairs. The coordinator would use these pairs to help bootstrap
certain catalog tables.
This was a bit messy, and all the info that was passed from the catalog
to the coordinator could be looked up on an ad hoc basis as need. So
this commit removes that list and updates the coordinator to look up
log info in the catalog.

sql: Clean up coord bootstrapping

---

doc/developer/guide.md

Discussion [in Slack](https://materializeinc.slack.com/archives/C02KE368L8P/p1649426438086429)
none

Update guide.md's "Our Crates" section to be more explicit about our code organization philosophy

---

doc/developer/guide.md

I asked this question in slack and it was suggested I add to the repo
- n/a

[docs] Note about cargo check target dir in rust-analyzer

---

src/orchestrator-kubernetes/src/lib.rs

The code added in #11635 to force Kubernetes to replace stateful set
pods in all cases was not quite careful enough in handling the case
where the pod did not already exist. This would cause `materialized` to
crash 50% of the time when creating a new cluster, depending on how
quickly Kubernetes created the pod.
FYI @alex-hunt-materialize. Can't imagine there's anything objectionable about this, so marking for automerge.
- N/A

orchestrator-kubernetes: don't crash if pod doesn't exist

---

src/coord/src/client.rs
src/materialized/src/http.rs
src/pgwire/src/protocol.rs

Remove the obligation for the owner of a `SessionClient` to explicitly
call `terminate`. Instead, just automatically terminate the session on
drop. `SessionClient` can now be used in futures that are canceled
without requiring rigamarole like `spawn_if_canceled`.
- N/A

coord: massively simplify the client termination protocol

---

doc/developer/debugging.md
doc/developer/guide-changes.md
doc/developer/guide-testing.md
doc/developer/guide-tokio-console.md
doc/developer/guide.md
doc/developer/observing_materialize.md
doc/developer/style.md

This PR fixes minor typos and instances of outdated information in the developer docs.

doc/developer: Various minor fixes/updates

---

doc/developer/design/20220330_persist.md

Rendered: https://github.com/danhhz/materialize/blob/976834e3e6ffadcad6fa17bc4eab7e5df6ac7486/doc/developer/design/20220330_persist.md
The first commit is the exact text from the gdoc, with only changes for formatting and a few typos. I've made a few adjustments in the fixup commit. Aljsocha and Ruchir, feel free to just look at the second commit. Anyone else, just look at the rendered doc :).
- N/A

design: add initial version of persist doc

---

src/persist-client/src/impl/machine.rs
src/persist-client/src/impl/state.rs
src/persist-client/src/lib.rs
src/persist-client/src/read.rs
src/persist-client/src/write.rs

persist: small cleanups

---

src/dataflow-types/src/plan/mod.rs

Same as #11721
We'll see if it passes CI (: 
None

Use soft assert for missing delta join arrangements.

---

src/persist-client/src/lib.rs
src/persist/src/cfg.rs

- [no] This PR has adequate test coverage / QA involvement has been duly considered.

persist: fix assortment of usability issues

---

src/coord/src/catalog.rs

coord: Add clarifying comment to ComputeInstance

---

src/coord/src/coord.rs
src/materialized/src/lib.rs
src/secrets-filesystem/src/lib.rs
test/secrets/mzcompose.py
test/sqllogictest/secret.slt

Follow up to #11628. This addresses the issues found in that PR.

coord: Handle SECRETS edge-cases found by QA

---

doc/user/config.toml
doc/user/content/release-notes.md
doc/user/content/sql/types/map.md
doc/user/content/versions.md
doc/user/data/sql_funcs.yml
doc/user/layouts/shortcodes/version-header.html
doc/user/layouts/shortcodes/version-list.html

doc/user: add v0.26.0 release notes

---

Cargo.lock
ci/test/cargo-test/mzcompose.py
src/persist/Cargo.toml
src/persist/src/lib.rs
src/persist/src/location.rs
src/persist/src/mem.rs
src/persist/src/postgres.rs
src/persist/src/sqlite.rs

persist: implementation of Consensus with postgres

---

doc/user/content/third-party/docker.md

Some users might want to persist their Materialize data across container recreations, as per this discussion [here](https://materializeinc.slack.com/archives/C03648YB34N/p1649700514829269) and this issue [here](https://github.com/MaterializeInc/materialize/issues/6018).

doc: Add steps for Docker mzdata volume

---

ci/deploy/website.sh

I missed this in #11795.
- n/a

doc/user: fix unstable deployment base URL

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/create

Generating error for zero-length identifiers
Fixes #11732

sql: generating error for zero-length identifiers

---

src/materialized/src/http.rs

The CORS layer needs to be last so that it runs first, before the auth
layer, as preflight requests do not send authentication headers.
* This PR fixes a recognized bug: MaterializeInc/cloud#2761.
- n/a

materialized: run CORS first in the HTTP server

---

doc/developer/platform/formalism.md

This reapplies 87a553e08 now that #11084 has landed.
* This PR resubmits a desirable change.
- n/a

doc/developer: re-rename UpdateAndDowngrade to Append

---

src/dataflow-types/src/types.rs

* This PR removes dead code.
- n/a

dataflow-types: remove persistence-related dead code

---

demo/billing/Cargo.toml
src/compute/Cargo.toml
src/dataflow-types/Cargo.toml
src/expr/Cargo.toml
src/interchange/Cargo.toml
src/persist/Cargo.toml
src/repr/Cargo.toml
src/storage/Cargo.toml

This hopefully fixes the Protobuf compilation error that @umanwizard was
observing on his machine.
- n/a

deps: use vendored protoc with prost

---

src/coord/src/catalog/builtin.rs
test/testdrive/catalog.td

* This PR fixes a recognized bug -- closes #11874
This should be straightforward, but please confirm that viewing _all_ databases is in fact desired behavior!

sql: fix \l meta-command

---

doc/user/content/sql/create-source/pubnub.md

Normalize the sidebar name to remove "Create Source: " and align it with the other sources.

docs/user: fix PubNub sidebar

---

doc/user/content/sql/create-source/pubnub.md

docs/user: fix PubNub sidebar in lts

---

src/persist/benches/consensus.rs

```
This commit adds the postgres backed implementation of Consensus to the Consensus
microbenchmarks. Tested on a r5a.4xl machine against a Aurora Postgresql instance
backed by 2 db.r5.8xlarge instances (instance type chosen arbitrarily).
consensus/compare_and_set/postgres/64KiB
time:   [6.3041 ms 6.3679 ms 6.4322 ms]
thrpt:  [9.7167 MiB/s 9.8148 MiB/s 9.9141 MiB/s]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
```
-

persist: add microbenchmarks for Postgres-backed Consensus

---

src/persist-client/src/impl/machine.rs
src/persist/benches/consensus.rs
src/persist/src/location.rs
src/persist/src/mem.rs
src/persist/src/postgres.rs
src/persist/src/sqlite.rs
src/persist/src/unreliable.rs

We had previously decided to structure the code to always keep the deadline argument
first, but then that accidentally got changed. This commit restores that structure.
-

persist: refactor Consensus to move the deadline argument first.

---

src/avro/src/encode.rs

avro: remove transmute and ensure correct endianess

---

doc/user/content/integrations/aws-msk.md

This PR goes through the required steps including some of the more complicated bits around configuring security settings in MSK and Materialize. It lists out the configuration requirements for MSK and the steps required to connect to MSK from a Materialize instance (using a local version of Materialize.)

Guide to connect AWS MSK to Materialize

---

doc/user/content/integrations/redpanda.md
doc/user/content/sql/create-source/kafka.md

Backport #11934 to `lts-docs`.

doc/user: backport #11934

---

src/storage/src/decode/mod.rs
src/storage/src/render/debezium.rs
src/storage/src/render/sources.rs

As title.
Fixes #11666 
Existing tests should be sufficient
- just better balancing of work across workers

[dbz tx] Distribute processing across workers

---

doc/developer/design/20220411_reclocking_implementation.md

Still a bit rough, but wanted to get out for early review.
----
This design doc supplements the existing formal specification of
reclocking and the product specification with a specification focused on
the actual implementation of reclocking.
* Design document
- N/A

doc/developer: add reclocking implementation design doc

---

src/sql/src/normalize.rs

Given a `WITH` option like `WITH foo="8"`, we were interpreting the value to include the quotes, because we used `AstDisplay::to_ast_string` to interpret `WITH` options that were object names.
After some discussion, we decided that the only reason we might allow `WITH` objects to be object names anyway is to support bare identifiers here, so change this code to enforce that and then just grab the string from the ident directly.
Fixes (partially) https://github.com/MaterializeInc/materialize/issues/11968
- Fix a bug causing extra quotation marks to be inserted into some …

fix handling of bare identifiers in `with_option_type`

---

src/pgwire/src/protocol.rs

This PR is the pgwire part from #11999, except against `main`.
This keeps the connection endpoint in the dark about why authentication failed, but does alert admins that a connection attempt has been thwarted. 
We log http authentication errors, but none for pgwire; this would greatly help us in cloud e2e tests!
See #11999
- The server now logs a warning if a pgwire connection presents invalid frontegg authentication data.

Warn on frontegg authentication failures in pgwire

---

doc/user/content/integrations/docker.md

doc/user: Remove mention to `mzcompose` from Docker docs

---

doc/user/assets/sass/_content.scss
doc/user/content/integrations/_index.md
doc/user/layouts/partials/inline-svgs.html

doc/user: update "Tools and Integrations" (#12018)

---

doc/user/content/ops/troubleshooting.md
doc/user/content/sql/tail.md

Clean clone for: https://github.com/MaterializeInc/materialize/pull/11105
**Try to improve how TAIL is perceived and what is capable to do.**
Since `TAIL` now has `SNAPSHOT` enabled by default and is now able to stream updates from an arbitrary `SELECT` statement, it makes easier to experience what is possible to acchieve. 
As a side effect:
* Doing `tail table` becomes a shorthand for `tail (select * from table)` 
* Using a `tail` by default will `query` (Snapshot) and `stream` updates.
Objectives:
Only documentation changes
-

doc/user: update tail docs

---

doc/user/content/ops/troubleshooting.md
doc/user/content/sql/tail.md

Clean backport to `lts-docs` branch for : https://github.com/MaterializeInc/materialize/pull/12045
**Try to improve how TAIL is perceived and what is capable to do.**
Since `TAIL` now has `SNAPSHOT` enabled by default and is now able to stream updates from an arbitrary `SELECT` statement, it makes easier to experience what is possible to acchieve. 
As a side effect:
* Doing `tail table` becomes a shorthand for `tail (select * from table)` 
* Using a `tail` by default will `query` (Snapshot) and `stream` updates.
Objectives:
Only documentation changes
-

Backport(doc/user: update tail docs)

---

Cargo.lock
src/orchestrator-kubernetes/Cargo.toml
src/orchestrator-kubernetes/src/lib.rs
src/secrets-kubernetes/src/lib.rs

Continued work on secrets.
This PR mounts the secrets created by the coord pod to computed pods created by this process (see #11931)

orchestrator: add secrets to computed pods

---

doc/user/config.toml
doc/user/content/_index.md
doc/user/content/cloud/get-started-with-cloud.md
doc/user/content/get-started.md
doc/user/content/known-limitations.md
doc/user/content/release-notes.md
doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/functions/now_and_mz_logical_timestamp.md
doc/user/content/sql/join.md
doc/user/content/sql/patterns/manual-materialization.md
doc/user/content/sql/patterns/temporal-filters.md
doc/user/content/sql/patterns/top-k.md
doc/user/content/sql/patterns/window-functions.md
doc/user/data/sql_funcs.yml

doc/user: temporarily rename SQL Spellbook section (#12048)

---

ci/nightly/pipeline.yml
misc/python/materialize/zippy/framework.py
misc/python/materialize/zippy/scenarios.py
test/zippy/mzcompose.py

Introduce the concept of Scenarios, which encapsulate the list
of events to be generated along with their relative frequencies.
Configurable frequency of events is needed to be able to perform a wide variety of tests

zippy: Allow frequency of events to be controlled

---

src/pid-file/src/lib.rs

When a process is forked, the default behavior is for the child process
to inherit all open file descriptors from their parent.
Previously, when materialized forked storaged and computed using the
process orchestrator, storaged and computed would have open file
descriptors to the materialized.pid pid file. Therefore, whenever
materialized was restarted independently of computed/storaged, the
new materialized would mistakenly think that an old materialized was
still running, due to the open file descriptors.
This commit makes sure to set the FD_CLOEXEC flag on all pid files
after opening them, so that their children don't inherit open file
descriptors to pid files.
Fixes #11961
* `flopen.c` has the following snippet of code in the function `vflopenat`
```C …
```

materialized: Stop child proc locking pid file

---

src/coord/src/coord.rs

Use TotalOrder to correctly extract a single timestamp out of an
antichain, and ensure any timestamp type we choose in the future supports
it in CoordTimestamp.
Add a `step_back` method to CoordTimestamp to further remove arbitrary
integer math from the timestamp logic.
- n/a

coord: improve determine_timestamp with some traits

---

src/coord/src/catalog/storage.rs
src/dataflow-types/src/client/controller.rs
test/sqllogictest/cluster.slt

`materialized` changes corresponding to https://github.com/MaterializeInc/materialize/pull/12072
@teskje FYI

pass `workers` to computed

---

src/materialized/src/bin/materialized/main.rs
src/orchestrator-kubernetes/src/lib.rs

Untested (and difficult to test without just letting it go to prod), but I think this should fix one of the two issues causing us to be unable to create environments (the other is fixed by https://github.com/MaterializeInc/cloud/pull/2886 )
-

Don't try to create secrets volume if secret doesn't exist

---

src/storage/src/decode/metrics/mod.rs
src/storage/src/decode/mod.rs
src/storage/src/render/sources.rs

(broken out from https://github.com/MaterializeInc/materialize/pull/12003)
Docs
None

add module docs for mz_storage::decode

---

src/materialized/src/bin/materialized/main.rs
src/orchestrator-kubernetes/src/lib.rs

Address this comment: https://github.com/MaterializeInc/materialize/pull/12101#issuecomment-1111369001
Fixes #12103

pivot selection of secrets controller to depend on orchestrator

---

src/dataflow-types/src/types.rs
src/sql/src/plan/statement/ddl.rs

(broken out from https://github.com/MaterializeInc/materialize/pull/12003)
Docs
None

add doc comments on SourceEnvelope clarifying the variants

---

src/storage/src/render/mod.rs
src/storage/src/render/sources.rs

(broken out from https://github.com/MaterializeInc/materialize/pull/12003)
Docs
None

rename import_source to render_source

---

doc/user/content/sql/create-source/postgres.md

doc/user: Fix connection params typo

---

doc/user/content/sql/create-source/postgres.md

lts-docs of https://github.com/MaterializeInc/materialize/pull/12110

lts-docs: fix typo (#12110)

---

src/materialized/src/bin/materialized/main.rs
src/orchestrator-kubernetes/src/lib.rs

Add a new `--orchestrator-service-node-selector` argument to
`materialized`, which instructs the `KubernetesOrchestrator` to attach a
the specified node selector to all services that it creates.
- n/a

materialized: allow plumbing node selectors to Kubernetes

---

doc/user/content/integrations/dbt.md

doc/user: remove stale dbt installation instructions from guide (#12136)

---

misc/shlib/shlib.bash

These functions are no longer used.
* This PR removes unused code.
- n/a

misc/shlib: remove dead code

---

src/materialized/src/bin/materialized/main.rs
src/orchestrator-kubernetes/src/lib.rs

orchestrator-kubernetes: allow configuring the service account to use

---

doc/user/assets/sass/_content.scss

doc/user: fix copy button formatting (#12176)

---

doc/developer/setup-mysql-debezium.md

Fix JSON syntax in TPCH data generation instructions

---

src/coord/src/coord.rs
test/sqllogictest/as_of.slt

AS OF didn't check for NULL.
* This PR fixes a recognized bug. https://github.com/MaterializeInc/materialize/pull/12138#issuecomment-1114762345
- n/a

coord: gracefully handle null AS OF

---

doc/developer/reading.md

Would anyone like to suggest a set of specific chapters to focus on?
----
Per recommendation from @umanwizard.
- N/A

doc/developer: add kleppmann's book to required reading list

---

src/testdrive/src/action/sql.rs

* Make FailSqlActions subject to timeouts
* Allow for tests to also assert that 'deadline has elapsed' error
has happened.
Those fixes are needed so that testdrive can operate in situations
where a query is expected to hand, such as when the cluster it is
being executed against is not available.
At this time, a `SELECT` query may hang if a cluster is not available. Allow testdrive tests to be written that can check for this situation and handle it.

testdrive: bring timeouts to the FailSqlAction

---

src/dataflow-types/src/plan/reduce.rs

Materialize crashes if you have the query hint `option(expected_group_size=<number greater than usize::MAX/16>)`.
Repro commands:
```
create table t1(f1 int, f2 int);
select max(f1) from t1 option(expected_group_size=111311797981107522680011);
```
The reason is that we have a loop that continues multiplies a number by until it is equal than or greater than `expected_group_size`. But if `expected_group_size` is greater than `usize::MAX/16`, then doing this multiplication loop will result in integer overflow.
Fixed by capping expected_group_size to be less than or equal to `usize::MAX/16`.
Closes #11928.
Previously, proptest for `ReducePlan` would crash due to stack overflow. This gets rid of the stack …

LIR: Fix panic. Enable proptest for `ReducePlan`

---

src/storage/src/render/upsert.rs

This file (and function) are becoming increasingly unreadable. Also, rustfmt is starting to choke on lines that BEGIN well pass any reasonable indentation.
This pr does, in the first commit, some quick lil refactors that reduce some indentation. These may be reduce-able even more in the future by `let-else` blocks when they are stable. In the second commit, internal, large pieces of functionality are broken into smaller functions. These functions take lots of parameters, which is some cost, but allow us to add more clear docs, and make it clear WHY certain things are borrowed and used by the operator.
This should be pure code movement. Some things may be going from `&T` to `&&T`, (namely `CapabilityRef` usages), but there should not be any real behavior or performance changes in this pr. …

Reduce indentation in upsert operator

---

src/dataflow-types/src/client.proto
src/dataflow-types/src/client.rs
src/repr/src/proto.proto
src/repr/src/proto.rs

Address comments of #12187 : 
* Use derive for PartialEq
* Encode Uuid as ProtoU128
None

dataflow-types: Fixup Peek protobuf

---

Cargo.lock
src/persist-client/Cargo.toml
src/persist-client/src/examples/mod.rs
src/persist-client/src/examples/persistent_source_example.rs
src/persist-client/src/lib.rs

Not necessarily meant for merging, more as a discussion starter. This is still rough around the edges.

persist: add new persistent source example

---

ci/deploy/devsite.sh
doc/developer/mzcompose.md

Also delete old pydoc files so links to them will break.
* This PR fixes broken docs.
- n/a

doc: fix links to pydoc entries

---

src/persist-client/src/impl/state.rs

Sneaky optimization! It was previously proportional to the number of
batches (empty or non-empty). If there are no keys in a batch, we can
simply extend the description of the last one (assuming there is one).
This will be an absurdly common case in actual usage because empty
batches are used to communicate progress and most things will be
low-traffic.
Extension of work in https://github.com/MaterializeInc/materialize/pull/12225. After this final fix, a test writing 64_800
batches, mostly empty but with 1KiB of data every 1_000, into file blob
and sqlite consensus used 260KB (66 files, exactly one per batch) in
blob and 27KB in consensus (down from 7MB after 12225 and 80GB before
this work). The runtime of the test also went from ~800s after the
previous PR down to ~30s (unmeasured before …

persist: make state size proportional to non-empty batches

---

ci/test/pipeline.template.yml
misc/python/materialize/mzcompose/services.py
test/replica-isolation/mzcompose
test/replica-isolation/mzcompose.py

Test that queries will be served even in the presence of a replica
that has been degraded by various means.
Part of #12220

test: Dedicated test for replica isolation

---

src/coord/src/catalog.rs

This commit improves CREATE statements to include the object's full
human readable name.

sql: Improve ddl log statements

---

doc/user/content/sql/create-source/kafka.md

doc/user: remove trailing commas in Kafka examples (#12363)

---

ci/nightly/pipeline.yml
test/limits/mzcompose.py

- run the normal limits workloads against 2 replicas with 2 nodes each
- add a dedicated test to check for total Mz instance size that
creates 24 clusters with 4 replicas, 4 nodes each.
** #12220

limits: Dedicated limits test for Platform

---

src/stash/src/lib.rs
src/stash/tests/stash.rs
test/stash/mzcompose.py

stash: annotate postgres and sqlite errors

---

src/dataflow-types/src/client/controller/compute.rs
src/dataflow-types/src/client/replicated.rs

Putting this up just to see if others think it's a sane idea.
Will clean up and add tests if so.

Put tx/rx between ActiveReplicaiton and its child clients

---

README.md

Patching up the logo, which has been outdated for a while now!

Update Materialize logo

---

doc/user/config.toml
doc/user/content/integrations/_index.md

doc/user: point to Cube.js docs (#12447)

---

misc/python/materialize/mzcompose/services.py
src/coord/src/catalog.rs
src/coord/src/catalog/builtin.rs
src/coord/tests/parameters.rs
src/coord/tests/sql.rs
src/materialized/src/lib.rs
src/stash/src/postgres.rs
src/stash/tests/stash.rs
src/testdrive/src/action.rs
src/testdrive/src/action/sql.rs
src/testdrive/src/action/verify_timestamp_compaction.rs
src/testdrive/src/bin/testdrive.rs
src/testdrive/src/util/mz_data.rs
test/testdrive/mzcompose.py

Enable a postgres stash in coord, and plumb it through from the binary and into testdrive for catalog verification.
* This PR adds a known-desirable feature. #12207
- n/a

*: enable postgres stash

---

test/limits/mzcompose.py

There are some interactions between the separate scenarios of the
limits test that stretch the database in different dimensions.
Until this is sorted out, execute each scenario as a separate
testdrive invocation so that:
- DROP DATABASE is issued before each scenario
- any existing SQL connections are terminated
** Nightly limits is failing in CI due to yet-to-be diagnosed bug in Mz that happens if multiple limits scenarios are run together

test: Isolate individual scenarios of the 'limits' test

---

src/persist-client/src/lib.rs

This saves the persist user of hassle of needing to immediately expire
something they didn't need. It also saves a bit of latency and persist
traffic (the expiration).
- N/A

persist: add open_reader and open_writer for when only one is needed

---

test/feature-benchmark/mzcompose.py

After recent refactoring the KafkaRestart scenario started failing
because the post-restart portion of the scenario was running
with the latest unstable Mz container rather than the version
that was under measurement.
Fix this by extending the scope of `c.override` to cover the entire
duration of the scenario. This way the `c.kill()` and `c.up()` actions
inside `RestartMz` operate on the correct image and restart Mz
using the right version.
** The feature benchmark was failing in the Nightly CI

feature-benchmark: Fix the KafkaRestart scenario

---

src/persist/benches/benches.rs
src/persist/benches/consensus.rs

It turns out that throughput of concurrent Consensus usage will be
pretty important (e.g. 22 system tables each forwarding a frontier once
per second), so start tracking it.
On a persist benchmarking machine
MZ_PERSIST_RECORD_COUNT_SMALL=1 MZ_PERSIST_RECORD_SIZE_BYTES_SMALL=1024 MZ_PERSIST_BATCH_MAX_COUNT_SMALL=8
consensus/compare_and_set/mem/1024B
time:   [530.95 ns 531.71 ns 532.50 ns]
thrpt:  [1.7909 GiB/s 1.7936 GiB/s 1.7962 GiB/s]
consensus/compare_and_set/sqlite/1024B
time:   [6.9189 ms 7.0019 ms 7.0868 ms]
thrpt:  [141.11 KiB/s 142.82 KiB/s 144.53 KiB/s]
consensus/compare_and_set/postgres/1024B
time:   [939.85 us 947.83 us 956.79 us]
thrpt:  [1.0207 MiB/s 1.0303 MiB/s 1.0391 MiB/s]
consensus/concurrent_compare_and_set/mem/1024B
time:   [7.4000 us 7.4420 us 7.4882 us]
thrpt: …

persist: introduce a concurrent variant of the Consensus benchmark

---

src/dataflow-types/src/client.rs
src/dataflow-types/src/client/partitioned.rs
src/materialized/src/lib.rs

This should fix https://github.com/MaterializeInc/materialize/issues/12386 by the strategy discussed in https://github.com/MaterializeInc/materialize/issues/12386#issuecomment-1125625715
(Probabilistically) fixes #12386 
-

Reconnect all partitions at once

---

ci/builder/requirements.txt
misc/python/stubs/pg8000/__init__.pyi

* Weekly dependency bump PR.
- n/a

deps: amalgamate python dependency bumps

---

Cargo.lock
src/dataflow-types/Cargo.toml
src/kinesis-util/Cargo.toml
src/persist/Cargo.toml
src/s3-datagen/Cargo.toml
src/sql/Cargo.toml
src/storage/Cargo.toml
src/testdrive/Cargo.toml
test/perf-kinesis/Cargo.toml

* Amalgamates dependabot PRs.
- n/a

deps: bump to AWS SDK v0.12.0

---

src/dataflow-types/src/client/controller.rs
src/materialized/src/lib.rs

#12388 , but for storage.
Fixes #12531.
same as #12388
-

turn on http console in storaged

---

src/materialized/ci/entrypoint.sh
src/materialized/src/bin/materialized/main.rs

og commit didn't have a PR to link
unblock merging #11911 
-

Revert persist back to using sqlite

---

src/persist/src/postgres.rs

Previously, we used single statements for the various head/compare_and_set/scan/truncate
operations which crucially led to sometimes getting stale values of head back when returning
from truncate, or when updating our state in the middle of a retry loop.
-

persist: wrap all pg consensus ops in txns

---

ci/test/pipeline.template.yml

test: fix typo in cluster-isolation

---

src/materialized/ci/entrypoint.sh
src/materialized/src/bin/materialized/main.rs

persist: revert back to using postgres

---

src/repr/src/adt/datetime.rs

This PR adds a feature that has not yet been specified. In the repr/adt/datetime code, we use a `expected` variable to track how to parse date-time strings. This expected variable was allocated from scratch on every invocation. Change it to accept static references to iterators, which allows some callers to pass stack-allocated data.
- N/A

repr: Avoid some allocations for datetime parsing

---

src/dataflow-types/src/client/replicated.rs

This PR teaches the active replication compute client to eagerly apply peek cancelations so that it may avoid rehydrating replicas with the peek commands, allowing their supporting dataflows to be avoided as well. This avoids a problem where the peek itself may be the source of a restart loop, and cancelation of the peek is the appropriate remedy.
The significance of the `PeekResponse::Canceled` variant to the ADAPTER layer is reduced dramatically. It remains important for internal resource reclamation, and the active replication client still produces it as part of implementing the `GenericClient<ComputeCommand>` trait. However, when we use an active replication client, all cancelation commands are immediately responded to with the corresponding cancelation responses.
* This PR fixes a …

Eagerly apply peek cancelation to avoid rehydrating replicas

---

ci/deploy/website.sh

Our existing link [probably] expired. Generated a new one, set to never expire.

update slack join community link

---

doc/user/content/integrations/cdc-mysql.md
doc/user/content/integrations/cdc-postgres.md
doc/user/content/integrations/debezium.md
doc/user/content/sql/create-source/kafka.md
doc/user/layouts/shortcodes/debezium-json.html

doc/user: update linked issue for JSON Debezium (#12571)

---

ci/test/pipeline.template.yml

see slack: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1652940580889329

temporarily make replica isolation soft fail

---

src/coord/src/coord.rs
src/materialized/src/lib.rs
src/secrets/src/lib.rs

Pull out the secrets reader portion out of #12236 for its own review.
- I have validated the config paths in the debugger. They are correct

[coord] Create secrets reader

---

src/stash/src/lib.rs
src/stash/src/memory.rs
src/stash/src/postgres.rs
src/stash/src/sqlite.rs
src/stash/tests/stash.rs

This allows append to clean up retracted data without users caring,
and allows peek to still work.
Item 3 in #12270.
- n/a

stash: compact and consolidate on append

---

doc/developer/testdrive.md
src/testdrive/src/action.rs
src/testdrive/src/action/sql.rs
src/testdrive/src/parser.rs
test/cluster-isolation/mzcompose.py
test/kafka-sasl-plain/with-options-errors.td
test/kafka-ssl/smoketest.td
test/pg-cdc/pg-cdc-ssl.td
test/test-certs/create-certs.sh
test/testdrive/ccsr-extra-options.td
test/testdrive/csv-sources.td
test/testdrive/kafka-headers-errors.td
test/testdrive/kafka-sources.td
test/testdrive/self-test.td
test/testdrive/test-skip-if.td
test/testdrive/types.td

Needed to merge #12608 in the face of permission errors by GitHub

testdrive: fail when expected errors don't match

---

Cargo.lock
src/compute/Cargo.toml
src/compute/src/sink/kafka.rs
src/compute/src/sink/persist_sink.rs
src/persist/src/mem.rs

Fixes #12633
Fixes #12634
Fixes #12635

resolve clippy warnings for holding locks across awaits

---

Cargo.lock
src/ccsr/Cargo.toml
src/compute/Cargo.toml
src/coord/Cargo.toml
src/dataflow-types/Cargo.toml
src/materialized/Cargo.toml
src/orchestrator-kubernetes/Cargo.toml
src/ore/Cargo.toml
src/persist-client/Cargo.toml
src/pgwire/Cargo.toml
src/sql/Cargo.toml
src/sqllogictest/Cargo.toml
src/storage/Cargo.toml
src/storaged/Cargo.toml

Did another pass with `cargo machete`

Cleanup unused deps

---

doc/user/content/sql/create-index.md

doc/user: remove warning about CREATE INDEX being an advanced feature

---

src/persist-client/src/error.rs
src/persist-client/src/impl/state.rs

persist: add test coverage for bounds checks on compare_and_append.

---

src/compute/src/compute_state.rs

This PR cleans up the compute command dispatching code by factoring the command handlers into separate methods. This unclutters the dispatch code, reduces indentation in the handling code, and enables early returns from the handler methods.
I strongly recommend hiding whitespace when viewing the diff!
The command handling code is unchanged by this PR, except for `handle_peek`, where we now perform an early return if we are not the target replica, instead of nesting everything inside an `if`.

computed: clean up command dispatching

---

src/coord/src/catalog.rs

coord: remove unused Op::UpdateItem

---

src/coord/src/catalog.rs

#12235 updated the DROP CLUSTER command to remove introspection source
indexes from the on disk catalog. However, it forgot to remove the
introspection source indexes from memory as well. This commit removes
them from memory.
Identified in #12674

catalog: Remove introspection sources from memory

---

src/storage/src/source/mod.rs

Signed-off-by: Petros Angelatos <petrosagg@gmail.com>
-

make simple source cancel safe

---

src/persist/src/postgres.rs

This reverts commit 60cf8fdebf4088f1e18571e66978d41b8abbdb9b.
The bug this worked around was actually a bug in tokio-postgres for which
we'd forgotten to pick up the fix (#8738). Now that we've picked up the fix, we can
go back to the original implementation, which we believe will be a bit
faster in production because it does not involve network roundtrips.
Fixes #12487.
* This PR removes a bugfix now that that bug has been fixed a different way.
- n/a

Revert "persist: wrap all pg consensus ops in txns (#12534)"

---

src/storage/src/source/mod.rs

`SimpleSource`, and all its helper structs, are no longer used.
All functionality (and, critically, all improvements) has been
added to `SourceReader`.
None

storage: remove SimpleSource

---

test/test-certs/create-certs.sh

Let's see if this fixes the CI errors with pg-cdc.

regenerate test-certs

---

misc/python/materialize/mzcompose/services.py
src/compute/ci/Dockerfile
src/compute/ci/entrypoint.sh
src/compute/src/bin/computed.rs
src/dataflow-types/src/client/controller.rs
src/materialized/src/bin/materialized/main.rs
src/materialized/src/lib.rs
src/materialized/tests/util.rs
src/orchestrator-kubernetes/src/lib.rs
src/orchestrator-process/src/lib.rs
src/orchestrator/src/lib.rs
src/ore/Cargo.toml
src/sqllogictest/src/runner.rs
test/cluster/README.md
test/cluster/mzcompose.py

orchestrator: various simplifications

---

test/limits/mzcompose.py

The limits test is spawning additional computed containers so
it fails to run properly with the Postgres instance built in
the materialized container.
-

test: Use a dedicated Postgres instance for the limits test

---

test/test-certs/create-certs.sh

This will hopefully fix the current certificate errors in CI.

test: force regenerating test certs

---

test/limits/mzcompose.py

The mzcompose.py now accepts a --scenario argument that allows
a single scenario to be run without having to temporary patch
the file.
There are CI failures in the individual limits scenarios so the script should allow them to be reproduced in isolation.

test,limits: Allow running individual limits secenarios

---

bin/cargo-test

bin: Fix cargo-test script

---

src/storage/src/render/sources.rs
src/storage/src/server.rs
src/storage/src/storage_state.rs

Several commits to remove some now-unnecessary code in storage.
Go commit by commit, and suppress whitespace.
- n/a

storage: remove some dead code

---

doc/user/content/sql/create-materialized-view.md
doc/user/content/sql/create-sink.md
doc/user/content/sql/tail.md

doc/user: fix some minor typos in docs (#12784)

---

src/persist-client/src/impl/state.rs

The first commit adds new test coverage for multireader scenarios with downgrade_since, and the second commit is a refactor that makes `update_since` slightly easier for me personally to reason about.
-

persist: add new tests for downgrade_since

---

Cargo.toml

incremental is unreliable for everyone right now
no idea how to test if this works? ci?

turn off incremental (for now)

---

src/coord/src/coord.rs

Noticed by Joe in #12858.
- n/a

coord: remove dead variable

---

bin/cargo-test
misc/python/materialize/cli/run.py
src/materialized/tests/pgwire.rs
src/materialized/tests/sql.rs
src/materialized/tests/util.rs

* This PR (maybe) fixes a recognized bug: #12786.
- n/a

materialized/tests: try to deflake another way 

---

doc/developer/mzbuild.md
misc/python/materialize/cargo.py
misc/python/materialize/mzbuild.py

mzbuild: add support for example binaries

---

src/testdrive/src/action.rs

Use both tokio_postgres's own connection timeout and Retry
to enforce a connection timeout and retry policy. This will
make testdrive invocations more robust in cases where Mz is not
guaranteed to be fully up and responsive at the time.
** This is needed for more robust chaos testing, especially in cases
where `wait_for_materialized()` can not be called or was not called
by omission.
@benesch This covers retrying and timing out if the Mz instance can not be connected to.
The case where the Mz instance is hung and is accepting connections but is not serving them is not handled correctly. It would have been handled if `retry_async_canceling()` could be used, but the compiler is not happy:
```
error[E0277]: the trait bound …
```

testdrive: Enable retries and timeouts at connect time

---

src/testdrive/src/action/sql.rs

Make testdrive's output copy-and-pasteable in a .td file without
requiring modifications:
- use a space as a delimiter between the values
- only quote values that contain a space or a quote character
Testdrive does not provide complete diffs between what was expected and what the actual output was, which would be quite the productivity boost. As a stop-gap measure, make sure that individual lines printed by testdrive can be pasted back into a .td file.

testdrive: Make testdrive's output copy-pasteable

---

src/transform/src/reduction.rs

Should fix https://github.com/MaterializeInc/materialize/issues/12935
-

Respect `self.limit` in `FoldConstants::fold_reduce_constant`

---

misc/python/materialize/cli/run.py
misc/python/materialize/mzcompose/services.py
src/sqllogictest/src/bin/sqllogictest.rs
src/sqllogictest/src/runner.rs
test/sqllogictest/mzcompose.py

Rather than SQLite. This is the last usage of the SQLite implementations
in our codebase.
- n/a

sqllogictest: switch to using PostgreSQL as the stash/persist backend

---

src/coord/src/coord.rs

Every one second the global timeline is advanced to the current time,
if the current time is ahead of the global timeline. This puts the
global timeline in write mode, which means that the next read will have
to advance the table when it's complete. This is undesirable because
some reads need to wait for two table advancements.
This commit explicitly puts the global timeline in read mode after
periodic advancements, which prevents reads that happen after the
advancement from having to advance the table again.
Writes will always have to advance a table regardless of what mode
the global timeline is in, so there are no negative impacts on writes.
Works towards resolving #12944
* This PR improves performance.
* Look at the `read_ts()`, `write_ts()`, and `fast_forward()` methods as well as …

coord: Reduce read latency

---

test/sqllogictest/transform/constants.slt

Add test for #12939

---

doc/user/content/quickstarts/live-views-for-reverse-etl.md

We are displaying [Build Live Views for Reverse ETL](https://materialize.com/docs/quickstarts/live-views-for-reverse-etl/) draft in the [Quickstarts](https://materialize.com/docs/quickstarts/) index
One line.
-

(docs/user) mark reverse etl as draft

---

src/persist/src/postgres.rs

Neither of them are necessary and the Mutex is preventing the natural
pipelining that would happen in the pgwire connection.
- N/A

persist: remove Arc and Mutex from PostgresConsensus

---

Cargo.lock
src/coord/Cargo.toml
src/kafka-util/Cargo.toml
src/materialized/Cargo.toml
src/sql/Cargo.toml
src/testdrive/Cargo.toml
test/test-util/Cargo.toml

See commits for details.
Fix for #12401 (no test though).
- n/a

rdkafka: enable SCRAM SASL method

---

doc/user/config.toml

Pressing in `Integrations` and `Client Libraries`  redirects to `Tools and Integrations` rather than opening the section. Unexpected behavior.
Remove two simple lines.
-

doc/user: Remove unnecessary links

---

src/coord/src/coord.rs

Instead of hard coding 1s.
- n/a

coord: use timestamp_frequency for table closing

---

doc/developer/design/20220404_metadata_storage.md

I'm interested in soliciting feedback on both the definition of the requirements and the analysis of those requirements! Put another way: don't take the requirements here as ground truth. The requirements are as much up for debate as the analysis of those requirements.
----
Add design doc for the metadata storage layer.
Touches MaterializeInc/materialize#11577.
Touches MaterializeInc/cloud#2476.
* This PR adds a design doc.
- N/A

doc/developer: metadata storage layer

---

src/dataflow-types/src/types.rs

* This PR removes dead code.
- n/a

dataflow-types: remove dead SourceInstanceRequest

---

doc/developer/design/20210714_reclocking.md

This PR elaborates on the practical context for reclocking, and one of the primary reasons that we perform it (to introduce durable, consistent interpretations of input data). Much of the document was written in a simpler context where it might be sufficient to simply reclock input data and produce them as output. In more complicated settings, such as where the input data collectively determine which subset should be emitted and when, more detail was required about what might happen just after reclocking, as part of producing a definite collection.
The reclocking document did not provide sufficient detail to direct non-trivial implementations.
This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md …

Reclocking addendum

---

bin/cluster-dev

cluster-dev: fix for addition of storage-postgres-stash flag

---

ci/README.md

ci: add note about "stop agent" button

---

doc/user/content/sql/create-cluster.md

Empty cluster docs

---

ci/test/pipeline.template.yml
src/persist-client/Cargo.toml
src/persist-client/ci/.gitignore
src/persist-client/ci/Dockerfile
src/persist-client/ci/mzbuild.yml
test/persist/.gitignore
test/persist/mzcompose
test/persist/mzcompose.py

persist: hook maelstrom up to ci

---

src/dataflow-types/src/client/controller/compute.rs
src/dataflow-types/src/types.rs

This PR corrects a couple outdated comments and resolves one `TODO` in the `dataflow-types` crate.

dataflow-types: minor improvements

---

src/coord/src/coord.rs
src/materialized/tests/sql.rs
src/ore/src/task.rs

Add a test for connectors that go missing during purification due to a
concurrent `DROP CONNECTION`. The existing code in the coordinator
successfully prevented a crash but produced a confusing error message
about cached plans; this commit modifies that code a bit to produce a
better error message about the missing connection.
Fix https://github.com/MaterializeInc/materialize/issues/12983.
- n/a

coord,materialized: add test for purification race

---

src/compute/src/render/mod.rs

This PR removes the unnecessary advancing of times emitted by a `persist_source`. See for context:
* https://materializeinc.slack.com/archives/C02PPB50ZHS/p1654867986000869
* https://materializeinc.slack.com/archives/C01CFKM1QRF/p1654870427617499

compute: trust persist_source to advance times correctly

---

Cargo.lock
deny.toml
src/dataflow-types/Cargo.toml
src/kinesis-util/Cargo.toml
src/persist/Cargo.toml
src/s3-datagen/Cargo.toml
src/sql/Cargo.toml
src/storage/Cargo.toml
src/testdrive/Cargo.toml
test/perf-kinesis/Cargo.toml

* Amalgamates dependency bumps.
- n/a

deps: upgrade to AWS SDK v0.13

---

src/audit-log/src/lib.rs
src/coord/src/catalog.rs
test/sqllogictest/audit_log.slt

Fixes #13053
* This PR adds a known-desirable feature. #13053
- n/a

audit-log: use alter instead of rename

---

src/persist/src/postgres.rs

This isn't needed on cockroach, so sniff the version before running.
- n/a

persist: don't pg_advisory_xact_lock on cockroach

---

doc/developer/README.md
doc/developer/tracing.md

We need documentation on how we use tracing in mz, and what the best practices are! This is a first pass, I expect this to be an iterative process!
https://github.com/MaterializeInc/materialize/issues/13019
None

tracing: first pass at tracing docs/best practices in doc/developer

---

Cargo.lock
src/audit-log/Cargo.toml
src/orchestrator-tracing/Cargo.toml
src/orchestrator/Cargo.toml
src/repr/Cargo.toml
src/storage/Cargo.toml

*: remove unused deps

---

doc/user/content/integrations/dbt.md

docs/user: add continuous testing section to dbt integration guide (#13156)

---

src/storage/src/render/persist_sink.rs

Closes https://github.com/MaterializeInc/materialize/issues/13116
As @benesch said: "We don't need to get too fancy with the batch sizing policy to start; anything rudimentary that bounds memory usage would be acceptable.". This pr implements the most basic batching policy: we make a new batch _per-timestamp_, and use `100` as the `size_hint`. Its possible that if we KNOW a batch is empty, we can skip that batch. Its unclear to me if that still incurs an additional s3 write (cc @danhhz )
@philip-stoev may want to run zippy against this
None

storage: write source data to persist in batches

---

ci/nightly/pipeline.yml
ci/test/pipeline.template.yml
misc/python/materialize/zippy/framework.py
test/zippy/mzcompose.py

Zippy in Nighly has been catching regressions reliably.

zippy: Add a short version of Zippy to the CI

---

src/repr/src/strconv.rs

Would previously crash because the while loop would never end and width
(a u32) would panic when it needed to go negative.
- n/a

repr: fix handling of nanos < 500

---

doc/user/config.toml
doc/user/content/cli.md
doc/user/content/release-notes.md

doc/user: add release notes for v0.26.3

---

src/coord/src/coord.rs

coord: Remove unnecessary background tasks

---

src/storage/src/source/postgres.rs

As discussed in https://github.com/MaterializeInc/materialize/issues/12856, there are no good options when there is a transient failure in fetching the pg snapshot. Instead, we just crash the process, and expect the orchestration layer to restart a new storaged in place; _Note that restarting a storaged is currently not guaranteed to work_
**This codepath has never been tested. Also, this pr is untestable until we make storaged restartable, which a large lift. This is why we are deciding to merge this as is**
None

storage: crash on pg recoverable snapshot failure

---

src/orchestrator-process/src/lib.rs

Prior to this commit, the process orchestrator's status watcher would emit a status event for every existing process every 5 seconds. This is now changed to only emit events for processes we have not already emitted events for. 
This will reduce some noise that complicates debugging of performance problems in Materialize.
Initially we thought that the additional status updates were the cause for #12992, but at least from my testing, that doesn't seem to be the case.

orchestrator-process: only emit new status events

---

doc/user/assets/sass/_layout.scss
doc/user/config.toml
doc/user/content/integrations/_index.md
doc/user/content/ops/_index.md
doc/user/content/overview/_index.md
doc/user/content/sql/_index.md
doc/user/layouts/partials/sidebar.html

doc/user: improve navigation in sidebar (#13259)

---

Cargo.lock
src/dataflow-types/Cargo.toml
src/kinesis-util/Cargo.toml
src/persist/Cargo.toml
src/s3-datagen/Cargo.toml
src/sql/Cargo.toml
src/storage/Cargo.toml
src/testdrive/Cargo.toml
test/perf-kinesis/Cargo.toml

Amalgamate the dependabot dependency bump PRs.
* Weekly dependency bump.

deps: bump to AWS SDK v0.14.0

---

doc/developer/platform/ux.md

docs/platform: correct counting in ux.md

---

doc/user/content/sql/show-create-table.md

doc/user: remove stale experimental note in `SHOW CREATE TABLE`

---

src/coord/src/catalog.rs
src/coord/src/client.rs
src/coord/src/command.rs
src/coord/src/coord.rs
src/coord/src/session.rs

coord: Add type for connection ids

---

doc/user/content/integrations/aws-msk.md

Quick update of the title/description of MSK guide

doc/user: Update MSK Title and Description

---

doc/user/content/integrations/aws-msk.md

doc/user: update MSK integration guide (#12224)

---

Cargo.lock
src/testdrive/Cargo.toml
src/testdrive/src/action.rs
src/testdrive/src/action/postgres/connect.rs
src/testdrive/src/action/postgres/execute.rs
src/testdrive/src/action/postgres/verify_slot.rs
src/testdrive/src/util/postgres.rs

Teach testdrive to support ssl connection strings and use a common interface for all its connections.
- n/a

testdrive: use tls for all connections

---

doc/user/content/integrations/_index.md
doc/user/content/integrations/golang.md
doc/user/content/integrations/java-jdbc.md
doc/user/content/integrations/node-js.md
doc/user/content/integrations/php.md
doc/user/content/integrations/python.md
doc/user/content/integrations/ruby.md
doc/user/content/overview/key-concepts.md

doc/user: patch language-specific integration guides (#13389)

---

src/sql/src/plan/statement/show.rs

Fix clippy lint, use write instead appending

---

ci/README.md

Add note about target-clearing launchd agent in `ci/README.md`

---

.devcontainer/.env
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.gitignore
bin/lint
doc/developer/scratch.md
misc/python/materialize/cli/mzcompose.py
misc/scratch/remote-dev.json

Create devcontainer scaffolding and document how to use.
- n/a

devcontainer: init

---

src/adapter/src/coord.rs

The coordinator's `bootstrap` would create items and immediately relax their read holds, which mean that subsequently constructed items would inherit weaker `since` bounds than they might have expected. Previously we would just roll with it, but recorded views require more attention here, and can/should complain if they are restarted with incorrectly compacted inputs.
This change causes the bootstrap to defer the relaxing of read holds until all entries have been created, allowing each to express read holds before the relaxation occurs.
cc: @jkosh44 @teskje 
Catalog bootstrapping can now allow controller components to express read holds, whereas previously they would not necessarily be respected.
This PR includes the following …

Stage bootstrap to relax read holds after all entries

---

src/persist-client/src/impl/machine.rs
src/persist-client/src/impl/trace.rs
test/cluster/mzcompose.py

I accidentally disabled these in #13444.

test/cluster: reenable remote cluster tests

---

misc/python/materialize/checks/recorded_views.py
test/platform-checks/mzcompose.py

checks framework: Add recorded views

---

ci/cleanup/pipeline.yml

ci: cleanup us-east-1 also

---

Cargo.lock
src/adapter/src/coord.rs
src/compute-client/Cargo.toml
src/compute-client/src/controller.rs
src/compute-client/src/controller/replicated.rs
src/controller/src/lib.rs

ActiveReplication tweaks

---

doc/developer/cloudbench.md
doc/developer/debugging.md
doc/developer/fast-compiles.md
doc/developer/feature-benchmark.md
doc/developer/overview.md

Signed-off-by: Ryan Russell <git@ryanrussell.org>
Readability improvements in `doc/developer` focused around benchmark/compile/debug guides.
`doc/developer` only. No functional changes.
- no user-facing behavior changes.

docs: Improve readability

---

src/adapter/src/coord.rs
src/adapter/src/coord/dataflow_builder.rs
src/adapter/src/coord/indexes.rs
src/controller/src/lib.rs

To match the name used elsewhere in the codebase.
- n/a

adapter: rename dataflow_client to controller

---

test/feature-benchmark/mzcompose.py

feature-benchmark: teach mzcloud to filter names

---

ci/test/pipeline.template.yml
test/kafka-sasl-plain/smoketest.td
test/kafka-ssl/multi.td
test/kafka-ssl/smoketest.td
test/testdrive/negative-multiplicities.td
test/testdrive/timelines.td

Follow up to #13315 with a few more simplifications in the same vein.
This tees us up to land #13263.
- n/a

testdrive: simplify some additional ancient tests

---

src/compute-client/src/controller/replicated.rs

Fixes #13530 by holding back dataflow `as_of` in `ComputeCommandHistory::reduce` by the peek timestamps. Also, emit the dataflow commands with peeks before allowed compaction.
@philip-stoev I'm happy to try and talk through how to prompt the bug, which I think should manifest if a replica recovers / is installed while a peek is in flight. Or perhaps something further up the stack prevents this and it is not easy to manifest. Not sure.
-

Hold back compacted `as_of` by peek timestamps

---

doc/developer/101-query-compilation.md

Some links were broken after the refactoring introduced in #13396 and #13393.
Fix broken links in the docs.
N/A
Tested manually.
N/A

doc/developer: Fix broken links in the "Query Compilation 101" guide

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/replicated.rs
src/compute-client/src/service.rs

See discussion beginning [here](https://materializeinc.slack.com/archives/CM7ATT65S/p1657654154889849)

Uncopify all the things

---

misc/python/materialize/feature_benchmark/executor.py
misc/python/materialize/mzcompose/services.py
test/feature-benchmark/mzcompose.py

Move all services inside the docker container and ensure they are publicly
exposed by forcing the user to tell us the external ip address on which
they will be accessed.
- n/a

feature-benchmark: run everything in docker for mzcloud

---

src/adapter/src/coord.rs

All processing functions trace, so this enables very easy "what's the slowest message?" otel lookups.
- n/a

coord: start parent span for message processing

---

src/persist-client/src/error.rs
src/persist-client/src/impl/encoding.rs
src/persist-client/src/impl/machine.rs
src/persist-client/src/impl/metrics.rs
src/persist-client/src/impl/state.proto
src/persist-client/src/impl/state.rs
src/persist-client/src/lib.rs
src/persist-client/src/write.rs

This PR is part of https://github.com/MaterializeInc/materialize/issues/13576 and puts us on a path to identifying orphaned blobs. This adds in a WriterId to `WriteHandle` that is required for `compare_and_append` operations, and creates corresponding `register` and `expire` state transitions. 
For now, this PR does not add in writer heartbeats or modify the file names to S3, which can come in follow-up PRs (though I'm happy to add those in here if it's more useful to do all at once)
https://github.com/MaterializeInc/materialize/issues/13576
Open to ideas on how to further test this!
This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-requi …

persist: reintroduce WriterId into WriteHandle

---

doc/user/content/integrations/aws-msk.md
doc/user/content/ops/troubleshooting.md
doc/user/content/overview/key-concepts.md
doc/user/content/overview/timelines.md
doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/create-source/materialize-cdc.md
doc/user/content/sql/create-source/postgres.md
doc/user/content/sql/create-source/s3.md
doc/user/content/sql/select.md
doc/user/content/sql/show-sources.md
doc/user/layouts/partials/sql-grammar/create-source-kafka.svg
doc/user/layouts/partials/sql-grammar/create-source-kinesis.svg
doc/user/layouts/partials/sql-grammar/create-source-postgres.svg
doc/user/layouts/partials/sql-grammar/create-source-pubnub.svg
doc/user/layouts/partials/sql-grammar/create-source-s3.svg
doc/user/layouts/partials/sql-grammar/show-sources.svg
doc/user/layouts/shortcodes/create-source/syntax-connector-details.html
doc/user/sql-grammar/sql-grammar.bnf

Docs counterpart of #13571. @teskje: since #13647 was marked as `TODO`, I went ahead and cleaned things up!

doc/user: remove traces of `MATERIALIZED SOURCE` from documentation

---

src/adapter/src/coord.rs
src/storage/src/controller.rs

When creating a recorded view, initialize the target storage collection's `since` frontier by advancing it to the recorded view's `as_of`.
Advancing the `since` ensures that readers are never allowed to read from the collection at times between the minimum and `as_of`. This is desirable since we know nothing about the state of the TVC at these times.
~~Advancing the `upper` ensures that a) no writes can happen behind the recorded view dataflow's `as_of` (which would be a bug) and b) when restarting the dataflow we can always use the collection's `upper` to determine a new `as_of` to continue from.~~ Advancing the `upper` means that on restart we cannot tell if the recording has ever emitted updates to the storage collection. This is something we need to decide if we should emit the …

Initialize recording frontiers on creation

---

test/feature-benchmark/scenarios.py

Disable `ENVELOPE UPSERT` tests since that has been removed. Use new `CONNECTION` syntax for kafka.
- n/a

feature-benchmark: various updates for platform

---

Cargo.lock
deny.toml

Upgrade some transitive dependencies to get rid of some duplicated
dependencies even deeper in the dependency tree.
* Dependency management.

deps: remove some duplicate dependencies

---

src/storage/src/controller.rs

Fixes #13651
This PR copies @aljoscha's code (linked in the issue above), updates it for the current controller, and adds some insulation against overwhelming downgrade commands (specifically, it consolidates as many commands as it can acquire before applying them).
-

Downgrade read handles on new task

---

.github/ISSUE_TEMPLATE/08-blank.yml

.github: add a blank issue template for internal use

---

src/persist-client/src/read.rs

Before this commit, if a shard's since was advanced beyond the frontier
of some active listener, that listener could emit incorrect data
(compaction would also have to be quite prompt). This would be an
invalid usage by the persist user (the since shouldn't have been
advanced that far), but it's better to panic then silently emit
incorrect data. This doesn't seem to be happening in practice.
Not bothering with a regression test because the way I found this was an
upcoming branch that causes persist unit tests to deterministically
fail.
- N/A

persist: panic instead of silent incorrectness on invalid usage

---

doc/user/content/sql/create-schema.md
doc/user/content/sql/create-sink.md
doc/user/content/sql/functions/date-trunc.md
doc/user/content/sql/identifiers.md
doc/user/content/sql/select.md
doc/user/content/sql/system-catalog.md
doc/user/content/sql/tail.md
doc/user/content/sql/types/_index.md
doc/user/content/sql/types/date.md
doc/user/content/sql/types/interval.md
doc/user/content/sql/types/list.md
doc/user/content/sql/types/numeric.md
doc/user/content/sql/types/record.md

Signed-off-by: Ryan Russell <git@ryanrussell.org>
Readability improvements in `doc/user/content/sql/**/.md`
- Proof reading fixes in `doc/user/content/sql/**/.md` files
-  no user-facing behavior changes.

docs(sql): readability improvements

---

doc/user/content/sql/create-schema.md
doc/user/content/sql/create-sink.md
doc/user/content/sql/functions/date-trunc.md
doc/user/content/sql/identifiers.md
doc/user/content/sql/select.md
doc/user/content/sql/system-catalog.md
doc/user/content/sql/tail.md
doc/user/content/sql/types/_index.md
doc/user/content/sql/types/date.md
doc/user/content/sql/types/interval.md
doc/user/content/sql/types/list.md
doc/user/content/sql/types/numeric.md
doc/user/content/sql/types/record.md

Backport #13780.
Signed-off-by: Ryan Russell <git@ryanrussell.org>

doc/user: readability improvements (#13780)

---

misc/python/materialize/cli/run.py

Otherwise it's easy for lingering computed/storaged processes from a
bin/environmentd run to quietly wedge up sqllogictest.
- n/a

bin/sqllogictest: kill lingering services before running

---

doc/user/content/overview/key-concepts.md
doc/user/content/sql/types/list.md

doc/user: small typo fixes (#13792)

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/timeline.rs
src/adapter/src/coord/timestamp_selection.rs

coord: Work towards detangling coord submodules

---

Cargo.lock
Cargo.toml
deny.toml
src/kinesis-util/Cargo.toml
src/persist/Cargo.toml
src/repr/Cargo.toml
src/s3-datagen/Cargo.toml
src/sql/Cargo.toml
src/storage/Cargo.toml
src/testdrive/Cargo.toml
test/perf-kinesis/Cargo.toml

deps: weekly rust dependency prep

---

doc/developer/design/20220718_envelopes.md

[Rendered doc](https://github.com/MaterializeInc/materialize/blob/b7aae6a11e2f7b1dd3633b4cb990dd22dbcf2fd4/doc/developer/design/20220718_envelopes.md)
See doc summary for info.

Create design doc for upsert and debezium envelopes in Platform

---

Cargo.lock
Cargo.toml
deny.toml
misc/images/materialized/Dockerfile
misc/python/materialize/mzcompose/services.py
src/environmentd/tests/util.rs
src/persist-client/examples/maelstrom/txn.rs
src/persist-client/examples/source_example.rs
src/persist-client/src/cache.rs
src/persist-client/src/lib.rs
src/persist/Cargo.toml
src/persist/src/cfg.rs
src/persist/src/location.rs
src/persist/src/postgres.rs

Reverts MaterializeInc/materialize#13794
@mjibson found that selecting from tables with this change is hanging, but without this change it succeeds. I've reproduced those results locally, so let's revert now and investigate.

Revert "persist: add connection pool to consensus"

---

src/compute-client/src/controller/replicated.rs
src/storage/src/controller/rehydration.rs

While a storage host or compute replica is connecting, it cannot listen
for channel close events that indicate that the storage host or compute
replica has been dropped.
This commit fixes that by holding onto a reference to the communication
task that is aborted when the storage host or compute replica is
dropped.
Fixes #13668.
Alternative to and therefore would close #13846.
@antiguru I have not actually tested this.
- n/a

compute,storage: abort communication tasks on drop

---

src/storage/src/source/util.rs

We were seeing deadlock when a `persist_source` operator took a
`MutexGuard` (storing it in the internal Future state machine state) and
then (because the stop token was dropped) the `tick` logic never got run
again. We might want to make this shutdown protocol more graceful, but
at the very least, start by dropping the `tick` closure so anything it's
holding on to gets dropped.
Closes #13888
Opening initially as draft because there's a bunch of ways we could fix this and I'm not sure yet which is the best set of tradeoffs. This one was super simple though and I wanted to get a CI run in.
- [N/A] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md …

storage: drop tick closure in source operator when finishing up

---

doc/user/content/integrations/_index.md
doc/user/content/integrations/aws-msk.md
doc/user/content/integrations/cdc-mysql.md
doc/user/content/integrations/cdc-postgres.md
doc/user/content/overview/key-concepts.md
doc/user/content/sql/create-connection.md
doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/create-source/postgres.md
doc/user/layouts/partials/create-source/connector/kafka/syntax.html
doc/user/layouts/partials/sql-grammar/create-source-kafka.svg
doc/user/layouts/partials/sql-grammar/create-source-postgres.svg
doc/user/layouts/partials/sql-grammar/create-source-pubnub.svg
doc/user/layouts/partials/sql-grammar/format-spec.svg
doc/user/sql-grammar/sql-grammar.bnf

Fixes #13657, #13678.
Initially marked this as draft since I was still trying to figure out how to blend connections into the key concepts and main source pages; all my attempts made it feel kind of overwhelming. For now, I just placed references to connections within each dedicated connector page.

doc/user: document `CREATE CONNECTION`, pt. II

---

src/orchestrator-process/src/lib.rs

Gathering system info takes around 200ms on my machine because it needs to
read the entirety of the /proc file system. However, we only need this info
if there might be a stale process around. Change the code to only populate
the system info if it needs it.
This change reduces the end-to-end latency of spawning child processes in
most cases by around 200ms. This is a low-impact change since this code
will only be exercised in development and test environments.
This change fixes an unreported problem.
- [z] This PR has adequate test coverage / QA involvement has been duly considered.

Process orchestrator: gather system info if needed

---

doc/developer/101-query-compilation.md

#13713 moved the fast path decision up one stage.
No user facing behavior changes.
Checked the updated links in the doc.

Developer doc: Update query compilation 101.

---

src/environmentd/src/lib.rs

So that metrics are available *before* we start hydrating the adapter.
Oops!
- n/a

environmentd: start internal HTTP server before anything else

---

src/ore/src/collections.rs

Add `expect_insert` and `unwrap_insert` for associative types.

---

src/ore/src/collections.rs

Address comments on #13946

---

src/persist-client/src/usage.rs

I think this should make @jpepin's PR easier -- we can total size for all blobs by shard id in one go (and unattributable storage usage, if any, hopefully not), and then the caller can correlate those shard ids to their sources/tables afterwards.
https://materializeinc.slack.com/archives/C03NYM894GP/p1659042453673699
- N/A

persist: storage client fn to get total usage in one go

---

src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs

This is now handled by persist, so the batching here was no longer
measuring how long the application took.
- n/a

coord: remove AdvanceTables

---

doc/developer/cloudtest.md

Document the features that are available to use inside tests.
cloudtest's documentation was incomplete.

cloudtest: Add documentation

---

src/persist/src/postgres.rs

Ensures CRDB runs the `consensus` table with a low gc interval, so scans aren't stuck trawling through gigs of tombstoned rows. On Nikhil's environment, we went from >4GB of cruft to <100MB with this enabled.
Before merging, we'll want to sync with the cloud team about how this affects our backup strategy with CRDB, as it will break incremental backups which run every hour. We additionally may want to lower the GC interval even further, as there should be no long-running queries involving this table.
---
I tried enabling this on two environments in prod, and in both cases saw massive drop offs in time spent in gc / consensus::scan / consensus::truncate
Hopefully fixes https://github.com/MaterializeInc/materialize/issues/13975
- N/A

persist: set consensus table gc ttl for CRDB

---

src/persist/src/postgres.rs

Could not startup on cockroach because the table didn't exist yet. This would have been caught by a test if we tested with cockroach, but we don't. See https://github.com/MaterializeInc/materialize/pull/13954.
- n/a

persist: only modify cockroach table after creating it

---

src/persist/src/postgres.rs

@mjibson found that `tokio_postgres` creates a new prepared statement for every execution. Turns out the `deadpool-postgres` library already has a statement cache built in, so we can use it to prepare each statement only once per connection.
https://materializeinc.slack.com/archives/CM7ATT65S/p1659475861438349
-

persist: use prepared statements cache in postgres access

---

src/persist-client/src/impl/machine.rs

The determinate "could not serialize access" errors happen often enough
in dev (which uses Postgres) that it's impeding people's work. At the
same time, it's been a source of confusion for eng. The situation is
much better on CRDB and we have metrics coverage in prod, so this is
redundant enough that it's more hurtful than helpful. As a result,
intentionally ignore INFO_MIN_ATTEMPTS and always logs at debug.
- [N/A] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [N/A] This PR includes the following [user-facing behavior …

persist: always log determinate error retries at debug

---

src/persist-client/src/impl/metrics.rs

Paul did the BOE math on our prometheus usage and it seems that we
should be able to store our per-shard metrics actually tagged with
per-shard labels. This might have help tracked down an issue being
investigated today where some shard in Frank's environmentd seemed to
have gotten "stuck".
-

persist: track per-shard metrics actually per-shard

---

src/persist-client/src/read.rs

Listen used the batch lower in a sort of hack to try to come up with
some frontier strictly less than the batch upper (so that it would be
safe to use in a downgrade_since call). This interacted poorly with a
performance optimization we have that squashes empty batches together.
The result is that in a shard that is getting no updates (just frontier
progress), the Listen would see a series of batches with the same lower
and increasing uppers. The idea is still seemingly sound (though remains
quite hacky), we just wanted to use the previous call to next's
frontier, not the batch lower.
Manually tested this. Not quite sure how to regression test it.
-

persist: fix bug where Listen wasn't always advancing since

---

misc/python/materialize/checks/debezium.py
misc/python/materialize/mzcompose/services.py
test/chbench/mzcompose.py
test/platform-checks/mzcompose.py

We were missing a test for the Debezium envelope in the presence of upgrades and restarts.

platform checks: Add a check for Debezium+Postgres

---

src/expr/src/relation/mod.rs

This PR adds enumeration methods `MirRelationExpr::{children, children_mut}` capable of enumerating references and mutable references to child expressions. These are more expressive than `visit_children` in that the lifetime bounds are the same as the argument references. Also, the four implementations for `VisitChildren` are simplified into two methods.
-

Simplify and generalize `MirRelationExpr` visitor logic

---

doc/user/content/integrations/metabase.md

Part of [DevEx #156](https://github.com/MaterializeInc/developer-experience/issues/156).

doc/user: adapt Metabase integration guide

---

pyproject.toml

This is useful for people who use pyright with lsp.
- None

Add pyright settings to pyproject.toml

---

pyproject.toml

this is what actually works and what I actually wanted to merge; not sure how I submitted the wrong thing

fix incorrectly merged code in #14103

---

doc/developer/guide-testing.md

Fixes https://github.com/MaterializeInc/materialize/issues/14107

Fix reference to nonexistent "dataflow" crate

---

src/stash/src/postgres.rs

Pipeline a bunch of stuff in the append path. All of the pipelining here should be able to execute in any order, so we should not need to worry about async await scheduling details.
```
Benchmarking transact
Benchmarking transact: Analyzing
transact                time:   [94.874 ms 98.415 ms 103.23 ms]
change: [-19.380% -15.594% -11.413%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 25 measurements (4.00%)
1 (4.00%) high severe
```
* This PR fixes a recognized bug. https://github.com/MaterializeInc/materialize/issues/14018
- n/a

stash: more optimizations

---

doc/user/content/integrations/cdc-mysql.md
doc/user/content/integrations/cdc-postgres.md
doc/user/content/integrations/debezium.md

Part of [DevEx #156](https://github.com/MaterializeInc/developer-experience/issues/156).

doc/user: minor updates to CDC guides

---

src/persist-client/src/impl/machine.rs

SUBTLE! If Machine::merge_res returns false, the blobs referenced in
compaction output are deleted so we don't leak them. Naively passing
back the value returned by State::apply_merge_res might give a false
negative in the presence of retries and Indeterminate errors.
Specifically, something like the following:
- We try to apply_merge_res, it matches.
- When apply_unbatched_cmd goes to commit the new state, the
Consensus::compare_and_set returns an Indeterminate error (but
actually succeeds). The committed State now contains references to
the compaction output blobs.
- Machine::apply_unbatched_idempotent_cmd retries the Indeterminate
error. For whatever reason, this time though it doesn't match
(maybe the batches simply get grouped difference when deserialized
from state, or more …

persist: fix "unexpected missing blob" bug

---

src/stash/src/postgres.rs

Make consolidate as pipelined as safely possible. Teach many methods
to accept a since or upper instead of fetching it. This remove lots of
redundant queries.
```
Benchmarking transact
Benchmarking transact: Analyzing
transact                time:   [74.219 ms 75.907 ms 77.762 ms]
change: [-21.248% -17.165% -13.488%] (p = 0.00 < 0.05)
Performance has improved.
Found 3 outliers among 25 measurements (12.00%)
3 (12.00%) high mild
```
* This PR fixes a recognized bug. #14018
- n/a

stash: optimize consolidate and redundant queries

---

src/compute/src/communication.rs

This essentially reverts #12832, which I suspect is no longer necessary
now that we no longer use linkerd in Materialize Cloud. The easiest way
to find out is to try it while we're still in alpha. We can always
revert this PR if we rediscover the networking issue.
For good measure, this commit also removes the handshake magic, which is
not necessary now that timely communication is not multiplexed on the
same port as HTTP and SQL traffic.
* This PR removes a now-unnecessary workaround.
- n/a

compute: remove linkerd workarounds from networking

---

test/pgtest/prepare.pt

Helpful when running this in a loop.
- n/a

pgtest: make a test re-runnable

---

Cargo.lock
src/mz/Cargo.toml
src/mz/Readme.md
src/mz/src/login.rs
src/mz/src/main.rs
src/mz/src/profiles.rs
src/mz/src/regions.rs
src/mz/src/shell.rs
src/mz/src/utils.rs

feat(mz) Improve regions in CLI

---

src/testdrive/src/action/kafka/verify.rs

This has often been useful when debugging and having to recompile is annoying so seems like a useful tool to have around -- especially since it doesn't make the code much more complicated
tests
-

[testdrive] [kafka-verify] Debug option to print topic contents

---

src/storage/src/render/sources.rs
src/storage/src/render/upsert.rs

[storage] add some comments explaining upsert restarts

---

ci/test/pipeline.template.yml
misc/python/materialize/checks/actions.py
misc/python/materialize/checks/debezium.py
misc/python/materialize/checks/scenarios.py
test/platform-checks/mzcompose.py

Restart the Postgres back-end (not the Postgres used for Pg sources)
A test supporting:
- #13872

platform checks: Add a scenario that restarts the Postgres back-end

---

src/testdrive/src/action/kafka/ingest.rs

@benesch does this make sense to you as-is, or should I explain further?

Fix td bug causing the final byte to get eaten if there is no key terminator

---

doc/developer/design/20220728_persisting_introspection_data.md

Import the design doc from notion (https://www.notion.so/materialize/Persisting-introspection-data-de34958f84394a54b230d67895a83243)
Persist the design doc

Create persisting introspection data design doc

---

misc/python/materialize/checks/sink.py

Add a Check that uses large transactions on tables to drive a
table-based sink that emits a lot of records.
The Platform Checks framework needed more sinks,  including table-based ones and those that emit a lot of records.

platform checks: Add table-based sinks

---

src/storage/src/controller.rs

When someone drops a storage collection (aka downgrade_since to the
empty antichain) replace it's ReadHandle in PersistWorker with a
placeholder. This placeholder acts as no-op for any later
downgrade_since calls (which is required for idempotence in the face of
potential replays).
Before this commit, we were keeping the ReadHandle alive so that it
could no-op future downgrade_since calls, but this was causing a leak in
persist.
Touches #14251
I'm getting a borrow checker error that I don't understand. It's complaining that read_handles is mutably borrowed twice, but AFAICT the first one should be resolved at the `futs.collect::<Vec<_>>().await;` call. Any ideas?
-

storage: replace dropped ReadHandles in PersistWorker with placeholder

---

test/testdrive/roles.td

Fix flaky test in nightly builds.
- N/A

Fix nightly role.td test

---

src/compute-client/src/plan/mod.rs

This reverts the removal of the literal constraints detection code in the MIR->LIR lowering. It was moved to `CanonicalizeMfp` by d9d674b3bb567d, but then Frank said it should not be removed from the lowering:
https://materializeinc.slack.com/archives/C02PPB50ZHS/p1660314866840339?thread_ts=1660310528.321199&cid=C02PPB50ZHS
I opened an [issue](https://github.com/MaterializeInc/materialize/issues/14248) for modifying `optimize_dataflow_index_imports` to only soft delete index imports, so that the re-added code has a chance to actually act as a safety net in case `CanonicalizeMfp` doesn’t catch some literal constraint.
https://materializeinc.slack.com/archives/C02PPB50ZHS/p1660310528321199
- I tested this in two ways:
- Temporarily commenting out `optimize_dataflow_index_imports` and the …

Revert the removal of the literal constraints detection code in lowering

---

src/compute/src/render/reduce.rs
src/timely-util/src/operator.rs

This extends collections with a `ExplodeOne` operator, which is similar to the `explode` operator, but only allows the closure to return a single element. The operator consolidates the output to reduce the amount of memory.
-

Implement explode_one to consolidate explosions

---

doc/user/content/integrations/aws-msk.md

Add an extra step to the MSK guide to clarify that the user needs to create ACLs for their SASL user, otherwise they would get an authorization error.

doc add ACLs step to MSK guide

---

doc/user/content/integrations/_index.md
doc/user/content/integrations/redpanda-cloud.md

Adding the adjusted Redpanda Cloud guide for the Materialize binary.

doc: Add the Redpanda Cloud guide

---

src/adapter/src/explain_new/mir/text.rs
src/expr/src/relation/mod.rs
src/transform/src/canonicalize_mfp.rs
test/sqllogictest/explain/optimized_plan_as_text.slt

Sorry, my previous PR broke main because of a botched rebase while merging it.

Correct botched rebase

---

src/avro/src/reader.rs
src/avro/src/schema.rs
src/avro/tests/schema.rs
src/interchange/src/avro/envelope_cdc_v2.rs
src/kafka-util/src/bin/kgen.rs
src/testdrive/src/format/avro.rs

[avro] Use short names whenever possible (#14344)

---

src/storage/src/types/sources.rs

And replace them with hand-rolled implementations. This has solved the
stack overflow we're seeing in storage_command_protobuf_roundtrip in the
past. See #13667.
* This PR maybe fixes CI flakiness.
- n/a

storage: remove some derived arbitrary implementations

---

doc/user/content/overview/key-concepts.md
doc/user/content/sql/create-index.md
doc/user/content/sql/create-view.md
doc/user/content/sql/functions/_index.md
doc/user/content/sql/patterns/temporal-filters.md
doc/user/content/sql/select.md
doc/user/content/sql/show-index.md

doc/user: adapt documentation to nu-materialized views, pt. II

---

src/adapter/src/coord/sequencer.rs

When we create a table we set its initial `since` to be the current timestamp. This may not be immediately valid with the existing timeline, so we should advance the timeline up to that `since`. This removes a class of noisy error about this inconsistency, by removing the main case that prompted the noise. The inconsistency may still exist for other cases, and we should still watch for the associated error.
Fixes #14136.
-

Advance timeline when we create a table

---

src/compute/src/bin/computed.rs
src/environmentd/src/bin/environmentd/main.rs
src/storaged/src/bin/storaged.rs

See discussion [here](https://materializeinc.slack.com/archives/CM7ATT65S/p1661451127030219)

Update doc explaining justification for lack of jemalloc on macOS.

---

doc/user/content/overview/timelines.md
doc/user/content/sql/create-source/kafka.md
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/keywords.txt
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/kafka_util.rs
src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
test/testdrive/avro-registry.td
test/testdrive/timelines.td

Touches https://github.com/MaterializeInc/materialize/issues/14341. See commit messages for details.
- n/a

sql: convert the next batch of enum options

---

ci/test/pipeline.template.yml
test/cloudtest/test_secrets.py

Fixes: #14359
- #14359
- 
@sploiselle FYI

cloudtest: Fix test_secrets.py

---

src/adapter/src/command.rs
src/pgwire/src/message.rs
src/pgwire/src/protocol.rs

To improve the quality of `ok` messages from the `api/sql` end point, including the response's tag would be helpful. And, though this isn't spec'ed in the design, including non-fatal errors in the message would be nice, as well, so separated those out, as well.
@mjibson My understanding of the non-`ExecuteResponse` tags is still lacking. Very open to suggestions to make these clearer/express the semantics more clearly. If huddling is easiest to get me up to speed, please lmk.
This PR adds a known-desirable feature. The first part of #14069, actually propagating these to `ok` messages will come next. 
- there are no user-facing behavior changes

pgwire: separate ExecuteResponse tags+non-fatal errors from sending them

---

misc/python/materialize/scratch.py

Fix crash in scratch.py

---

misc/scratch/provision.bash

install cloudtest prerequisites (+k9s) in scratch boxes

---

src/storage/src/source/postgres.rs

For some reason, interleaved Postgres connections using SSL over SSH tunnels tend to cause connections to be closed almost every time.
More investigation is needed, but this change mitigates the problem to a level that allows the source to work properly.
* This PR fixes a previously unreported bug: Postgres connections using SSL over an SSH tunnel would fail to replicate data from upstream: [report on Slack](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1662021033954639).
-

storage: avoid interleaving postgres connections

---

ci/test/pipeline.template.yml

This is flaky for some reason that we don't understand, but I suspect is somehow related to either Kafka or storage. Disabling it per this discussion: https://materializeinc.slack.com/archives/CM7ATT65S/p1662060994808149?thread_ts=1662054547.119999&cid=CM7ATT65S

Temporarily disable cloudtest

---

src/adapter/src/coord/peek.rs

Previously, the Coordinator used a tokio::sync::mpsc::unbounded_channel
to receive peek responses. It would then combine all responses received
from this channel into one large response. However, only one response
would ever actually get sent on that channel, leading to unnecessary
code that was never run.
This commit converts the channel into a tokio::sync::oneshot::channel
to make it explicit that only one message will ever get sent.
- N/A

coord: Refactor peek response handling

---

src/persist-client/src/read.rs

If a Subscribe were abruptly dropped while holding leases from a
snapshot, it would panic. Instead, safely return the leases to
prevent the panic.
This PR fixes a previously unreported bug. There is a chance this caused CI flakiness seen [here](https://buildkite.com/materialize/tests/builds/40785#0182fdb5-511e-48ac-81ae-46bb28c89c38/155-536).
- there are no user-facing behavior changes

persist: safely return snapshot leases on drop

---

doc/user/content/cli.md

doc/user: fix typo in version check instructions

---

test/kafka-multi-broker/03-after-join.td
test/limits/mzcompose.py

Recent changes to the product and/or the tests themselves left them broken in  multiple aspects.
Nightly limits CI was failing.
@bkirwi @sploiselle

nightly: repair tests back to operational status

---

src/storage/src/sink/kafka.rs

This renames most references in `kafka.rs` from "consistency" to "progress". (We may want to preserve "consistency" as the name for the general idea, but we can use "progress" for everything that's about this specific implementation of it.)
This PR refactors existing code. This followup was discussed in #14526.
This is believed to be purely a rename refactor, so it shouldn't have any externally-facing impacts.

[sinks] Rename some lingering references to the consistency topic

---

src/compute/src/render/reduce.rs

This small PR (view with whitespace suppressed) adds a region around the hierarchical reductions that have a long sequence of stages. Reduces the visual clutter in cases where we use these plans.
Complicated but logically coherent dataflow fragments should be abstracted when possible for ease of understanding.
* The diff is much smaller if viewed with whitespace hidden.
Large `Reduce` dataflow fragments are now presented more compactly as a region, into which one can drill down if needed.

Abstract hierarchical reduced within region.

---

doc/user/content/sql/show-connections.md
doc/user/content/sql/show-indexes.md
doc/user/content/sql/show-materialized-views.md
doc/user/content/sql/show-objects.md
doc/user/content/sql/show-schemas.md
doc/user/content/sql/show-sources.md
doc/user/content/sql/show-tables.md
doc/user/content/sql/show-types.md
doc/user/content/sql/show-views.md
src/sql/src/plan/statement/show.rs
test/sqllogictest/materialized_views.slt
test/sqllogictest/transactions.slt
test/testdrive/catalog.td
test/testdrive/connection-create-drop.td
test/testdrive/get-started.td
test/testdrive/kafka-avro-sources.td
test/testdrive/list.td
test/testdrive/map.td
test/testdrive/materializations.td
test/testdrive/rename.td
test/testdrive/sinks.td
test/testdrive/tables.td
test/testdrive/types.td
test/upgrade/check-from-current_source-database-schema.td

sql: Remove type column from show commands

---

src/storage/src/types/connections.rs

This PR refactors existing code. Principally to remove a possible panic, but I also like that it removes an abstraction that's a bit too overpowered for how it's currently used.

[sinks] Replace ConfigKey with some constants

---

src/orchestrator-kubernetes/src/lib.rs

Prevents the cluster-autoscaler from evicting these pods in attempts to scale down and terminate nodes.
This will cost us more money, but should give us better uptime.
This does not prevent all evictions by Kubernetes, only the ones initiated by the cluster-autoscaler. Notably, eviction of pods for resource overuse is still enabled.
Resolves https://github.com/MaterializeInc/cloud/issues/3838
Related change that applies to environmentd pods is at https://github.com/MaterializeInc/cloud/pull/4010
No user-facing behavior changes (other than perhaps better uptime).

Disable eviction by the cluster-autoscaler

---

doc/user/content/sql/tail.md

Clarify TAIL documentation to be less ambiguous.
-

Update TAIL documentation

---

src/persist-client/benches/benches.rs
src/persist-client/examples/maelstrom/txn.rs
src/persist-client/examples/source_example.rs
src/persist-client/src/cache.rs
src/persist-client/src/inspect.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/gc.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/metrics.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/usage.rs
src/persist-client/tests/machine/gc
src/persist-client/tests/machine/regression_gc_behind
src/persist/src/intercept.rs
src/persist/src/lib.rs

persist: various small gc commits

---

doc/user/content/sql/system-catalog.md

There is no retention period at present. Also drop the language about "as of July 2022"; we keep the docs up to date, so we don't need to include the time of writing.
* This PR follows up on code review feedback from #13718.
- n/a

doc/user: correct documentation about storage usage retention

---

Cargo.lock
src/compute/Cargo.toml
src/environmentd/Cargo.toml
src/storaged/Cargo.toml

Bumping the versions on main to v0.27.0-dev as per the discussion [here](https://materializeinc.slack.com/archives/CTESPM7FU/p1663584867970319) in order to test sinks in prod.
-

Bump versions to v0.27.0-dev

---

src/storage/src/sink/kafka.rs

Add logging in a few places that I think will make it more clear what's happening when we run into issues.  The most impactful changes are:
- adding a print to the `bail_err` macro
- adding logging for kafka transition calls
better understanding of kafka issues
-

[sinks] Add more extensive logging

---

LICENSE

Update the additional use grant. The new additional use grant is clearer
about the definition of "cluster", as it  uses the terms of art
introduced in the latest version of Materialize.
* This PR updates the license.

LICENSE: update additional use grant

---

misc/python/materialize/cli/run.py

Corrects a minor glitch in #14868 in which a pre-existing environment ID was not tolerated. Also switches from `os` and `open` to pathlib for consistency with the rest of the file and easier access to the `exist_ok` option.
- n/a

bin/environmentd: avoid crashing if mzdata directory already exists

---

test/limits/mzcompose.py

limits test: Adjust the KafkaSinks* scenarios to reality

---

src/storage/src/controller.rs
src/storage/src/controller/rehydration.rs
src/storage/src/types/sinks.rs

Create function on `SinkAsOf` that can take a `from_since` and fast forward if necessary.  Use that both in rehydration and when calling the `create_export` command.
We could have alternatively done this _only_ within the rehydration task -- but to better mirror how sources handle the `resume_upper`, I did it this way.
This is a partial rollback of #14785 which moved the fast forwarding from `create_export` to rehydration.  We actually need it in both cases:
- rehydration: if storaged crashes, the rehydration task needs to recreate with a valid as_of
- create_export: if environmentd crashes, and we restart, we need to make sure the `create_export` commands have a valid as_of.  In this situation, we don't rehydrate in the same path (anymore?)
unreported bug mentioned in slack
- none

[sinks] Fastforward asof in storage controller and rehydration

---

ci/nightly/pipeline.yml

🙈 
https://buildkite.com/materialize/nightlies/builds/1178#01835fd0-fa5a-4811-869b-babed19f4ef8
-

persist-nightly: fix param name for maelstrom run

---

src/compute-client/src/controller.rs

Remove unused method

---

src/storage/src/render/upsert.rs

Just to be on the safe side. 😅

storage: in upsert source, be extra cautious about what we hash

---

Cargo.lock
bin/bump-version
src/compute/Cargo.toml
src/environmentd/Cargo.toml
src/storaged/Cargo.toml

This simplifies the release process.

bin/bump-version: add script to bump version during releases

---

src/storage/src/source/postgres.rs

(This pr could probably also be named: "Implement `OffsetCommitter` for pg sources")
This pr is the final bit of work to close out https://github.com/MaterializeInc/materialize/issues/13534 _for pg sources_.
It prevents us from sending status updates for lsn's that we have no yet committed durably. It does keep sending status updates for new times, with the newest committed lsn tho (cc @petrosagg I am not 100% sure if pg requires this). Also, https://www.postgresql.org/docs/current/protocol-replication.html mentions "WAL byte + 1", is that what an LSN is?
This fixes a bug that is very clear, but I don't think we EVER saw an instance of, which leads me to believe that this pr is best tested more holistically with restart testing. However, we could add a simple test that checks the …

storage: bound pg status updates within the resumption frontier

---

src/storage/src/source/antichain.rs
src/storage/src/source/reclock.rs
src/storage/src/source/source_reader_pipeline.rs

from comments and discussions i had on https://github.com/MaterializeInc/materialize/pull/14867

storage: fix some followups for the bir pr

---

doc/user/layouts/partials/sql-grammar/create-source-postgres.svg
doc/user/sql-grammar/sql-grammar.bnf

Minor update to enforce parentheses around `( PUBLICATION 'x' )`.

doc/user: update grammar for Postgres source

---

doc/user/content/integrations/http-api.md

Quite simple. Removes extra characters and strings.
-

Docs: Remove extra characters and strings in HTTP API

---

src/adapter/src/catalog.rs

Catalog transactions take a list of operations. Previously,
transactions would iterate over that list twice. Usually in the first
pass, the catalog would update the stash transaction and generate
built-in updates. Usually in the second pass, the catalog would update
a copy of the in-memory catalog state. However certain operations do
not follow this pattern precisely.
This commit updates catalog transactions to combine both passes into a
single pass. This is useful for multiple reasons:
* It is now possible to have some operation that depends on a
previous operation in the same transaction. This can unlock things
like executing multiple DDL statements in a transaction.
* It is slightly easier to understand and reason about.
* We can abstract all the logic to a method that doesn't take …

catalog: Refactor catalog transactions

---

src/testdrive/src/action.rs
src/testdrive/src/action/file.rs
src/testdrive/src/action/http.rs
src/testdrive/src/action/kafka/add_partitions.rs
src/testdrive/src/action/kafka/commit.rs
src/testdrive/src/action/kafka/create_topic.rs
src/testdrive/src/action/kafka/ingest.rs
src/testdrive/src/action/kafka/verify.rs
src/testdrive/src/action/kinesis/create_stream.rs
src/testdrive/src/action/kinesis/ingest.rs
src/testdrive/src/action/kinesis/update_shards.rs
src/testdrive/src/action/kinesis/verify.rs
src/testdrive/src/action/mysql/connect.rs
src/testdrive/src/action/mysql/execute.rs
src/testdrive/src/action/postgres/connect.rs
src/testdrive/src/action/postgres/execute.rs
src/testdrive/src/action/postgres/verify_slot.rs
src/testdrive/src/action/protobuf.rs
src/testdrive/src/action/psql.rs
src/testdrive/src/action/s3.rs
src/testdrive/src/action/schema_registry.rs
src/testdrive/src/action/set.rs
src/testdrive/src/action/skip_if.rs
src/testdrive/src/action/sleep.rs
src/testdrive/src/action/sql.rs
src/testdrive/src/action/sql_server/connect.rs
src/testdrive/src/action/sql_server/execute.rs
src/testdrive/src/action/verify_timestamp_compaction.rs
src/testdrive/src/lib.rs
test/kafka-exactly-once/mzcompose.py

Suggestion from @benesch here: https://github.com/MaterializeInc/materialize/pull/15070#issuecomment-1262395401
- there are no user-facing behavior changes

testdrive: remove undo

---

doc/user/content/overview/_index.md

Partially fixes #8663. This PR pushes the minimum changes required for the page to be valid for nu Materialize. A follow-up PR will completely rewrite the page to make the value add of Materialize more immediate.

doc/user: minimal updates to What is Materialize? page

---

doc/user/content/get-started.md

**Initial version, needs some polishing.**

doc/user: adapt get started guide

---

README.md

Updates the README to remove residual binary references. We need to do a larger rewrite, but this is hopefully good enough for tomorrow.

update readme to remove residual binary references

---

doc/user/content/install.md
doc/user/content/overview/architecture.md

Fix the link to the Materialize unbundled blog post.
-

doc: fix link to materialize unbundled blog

---

src/compute-client/src/controller/replicated.rs

Discovered in #15132
When a replica crashes during hydration, environmentd also crashes because it expects the `command_tx` channel to work. This PR changes warns + swallows the error instead. This (should be/) is correct, as the only case where the command_tx send error happens is if the [replica_task](https://github.com/lluki/materialize/blob/707079ddd5947005389281750b01c8c18cfa0a4d/src/compute-client/src/controller/replicated.rs#L68) in environmentd terminates. Thus the replica client is gone forever and we dont risk to run into a partially hydrated replica. On the next send/recv the error will cause a rehydration. We do not attempt to eagerly rehydrate to ensure we don't fall into an infinite loop during the rehydration.
This PR does not add any logic for dealing with a replica that …

compute controller: don't crash on hydration

---

src/storage/src/source/postgres.rs

This is a followup that @aljoscha mentioned to me in https://github.com/MaterializeInc/materialize/pull/14961
@petrosagg there is some subtlety on how this interacts with: https://github.com/MaterializeInc/materialize/pull/14734
Its unclear to me if we should choose the lsn before or after this correction, ill need your help making this choice and documenting it

storage: start pg status updates with initial lsn

---

src/storage/src/source/source_reader_pipeline.rs

@aljoscha and @petrosagg, this ended up being subtle, and I have some questions that should be discussed, I will inline them as comments. I did test this with `pg-cdc-resumption` with the change that removes batching of snapshots, and it seemed to work, but would like to merge that separately

storage: support non-ordered batches in reclock_operator

---

src/adapter/src/coord/ddl.rs

Reverts MaterializeInc/materialize#15146

Revert "[sinks] create sinks in storaged before in catalog"

---

doc/user/layouts/partials/head.html

Updating lts docsearch api key to fix search

lts-docs: Update docsearch api key

---

Cargo.lock
src/compute/Cargo.toml
src/environmentd/Cargo.toml
src/storaged/Cargo.toml

Automatic version bump PR post release.

release: bump to version v0.27.0-alpha.24.post

---

src/storage/src/source/source_reader_pipeline.rs

This is known to cause problems, and it may very well be related to: https://github.com/MaterializeInc/materialize/issues/15046

storage: avoid holding the remap output handle across an await

---

src/compute/src/sink/persist_sink.rs

Before, we were heartbeating the "writer" write handle, but only in response to new updates or the frontier advancing.
Now, we heartbeat both the "writer" and "appender" write handles and we make sure to do so independently of changes in operator inputs.
This fixes a bug that we observed in production where it can take a long time to read the initial snapshot of the sinked collection, leading to our write handle lease being expired.
I manually checked that this usage pattern of `async` timely operators does not cause us to go into a busy loop.
Fixes #15191
@philip-stoev I don't know if we can do much here in terms of QA. The customer env where the bug occured was restarting the compute cluster about once every 45 minutes. In general, I think it's hard to test these timeout-related bugs. …

storage: heartbeat write handles in (compute) persist_sink

---

doc/user/config.toml
doc/user/content/releases/_index.md

doc/user: fix some lingering issues with LTS switch

---

doc/user/content/ops/troubleshooting.md

SUBSCRIBE is no longer usable with the unsuffixed logging sources; instead you can only SUBSCRIBE to the suffixed logging sources. Note this in the docs.
Requested by @teskje in the review of #15261.
* This PR updates the documentation to match reality.
- n/a

doc/user: note SUBSCRIBE limitation in troubleshooting docs

---

src/storage/src/source/reclock.rs
src/storage/src/types/sources.rs

This PR is the minimum surgery required in the current code that preserves all the reclocking logic as-is but changes the remap shard to be identically typed to the one of storage collections.
Reclock bindings for kafka sources are represented with two columns. An int32 for the partition id and a uin64 for the offset.
Reclock bindings for postgres sources are represented with just one column for the offset.

storage: switch reclocking data format to rows

---

src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs

available_subsources were being constructed in two places, and the previous refactor missed that (because they happened to produce identical output, but broke when adding TPCH). Refactor to avoid differing implementations.
- n/a

sql: even more loadgen refactors

---

src/transform/src/canonicalize_mfp.rs

This is some minor tweaks in the literal constraints detection, inspired by seeing customer queries here (the multiple IN lists): https://www.notion.so/materialize/Front-d9e9f084bc9f4ccb915e231763853d7c
1. `remove_impossible_or_args` now changes the MFP only if it did deduplication inside AND arg lists or removal of complete AND arg lists, but not when it just sorted AND arg lists. This avoids later running `undo_preparation` if neither `remove_impossible_or_args` nor `detect_literal_constraints` did anything useful (which is also the case when `undo_preparation` would take the longest time, because then the expression is still big, since nothing was removed from it).
2. I changed the limit in `distribute_and_over_or`: I think it's better to have an absolute limit (rather than a limit …

Tweaks in literal constraints detection

---

src/storage/src/source/persist_source.rs

Reading from persist generates LeasedBatchParts, which cannot be arbitrarily dropped. We periodically see CI panic because something shut down while a lease was still intact.
This PR hopefully remedies this by draining the stream entirely, safely dropping all of the leases.
My best guess as to what was happening here is that final leased batch was being held in the stream while waiting to get polled, and the stream was dropped with it in place. The mechanisms by which these operators get drop eludes me, which is why I tagged the reviewers I did; maybe this hunch is bogus (but maybe the fix is sound enough anyway?).
This PR fixes a recognized bug. #14739 -- not closing the issue because I am not 100% certain that this prevents the panic.
- n/a

persist: add DropSafeLeaseStream to prevent panic when dropping persist source

---

doc/developer/design/20220819_bounded_input_reliance.md

Design for https://github.com/MaterializeInc/materialize/issues/13534
Its unclear to me how this will work exactly with https://github.com/MaterializeInc/materialize/pull/14292, so Ill need close review on that section

[design] add Bounded Input Reliance design doc

---

doc/user/content/integrations/dbt.md
doc/user/layouts/shortcodes/dbt-materializations.html

Document the `default` index configuration option.

doc/user: update dbt integration guide

---

src/mz/src/shell.rs

psql uses ctrl-c to cancel ongoing statements. Swallow the call to ctrl-c when executing psql; otherwise, it will terminate mz, stopping the shell.

fix(mz) swallow ctrl-c when executing psql

---

src/persist-client/src/internal/machine.rs
src/persist-client/src/read.rs

There might be some holdup in the next batch being produced. Perhaps we've quiesced a table or maybe a dataflow is taking a long time to start up because it has to read a lot of data. Heartbeat ourself so we don't accidentally lose our lease while we wait for things to resume.
We think this was the cause of some expired reader panics seen in production.
Closes #15396
-

persist: call maybe_heartbeat_reader in next_listen_batch loop

---

src/persist-client/src/read.rs

It's accidentally been disabled with a `cfg(WIP)` for a while. I think it got disabled because we didn't have rate limited heartbeats, but it works now out of the box (modulo some mild rot in the setup code).
-

persist: re-enable skip_consensus_fetch_optimization test

---

src/adapter/src/catalog.rs
test/sqllogictest/alter_system_objects.slt

Works towards resolving #15357
- N/A

sql: Prevent altering system objects

---

doc/developer/101-query-compilation.md

Just fixing the 404s, but not updating the line numbers for now.

Fix broken links in 101-query-compilation.md

---

src/storage/src/source/reclock.rs

Before, we were using `tokio::time::Instant::now()`, which allows advancing time via `tokio::time::advance()` but also automatically advances the time if there is now work to do AND there is a `tokio::time::sleep()` that is waiting.
The introduction of the new heartbeat tasks (for read/write handles), in a separate PR, would futz with this time, because its `tokio::time::sleep()` invocations can advance the time at indeterministic points, messing with the tests.
Now, we control time explicitly using a fully custom `NowFn`. This also changes the tests to be explicit about how the persist "cache" is shared.
@danhhz This will make the reclock tests work with #15405.
Someone could do the additional lift of putting this test helper in `mz_ore`, if we like it.
-

storage: in reclock.rs, make time control more explicit in tests

---

doc/user/content/integrations/confluent-cloud.md

To avoid user confusion and for better clarity, changing the `<your-username` reference to `<your-api-key>` and `<your-password>` reference to `<your-api-secret>`
-

doc: Confluent Cloud guide SASL details

---

doc/user/content/integrations/aws-msk.md
doc/user/content/integrations/confluent-cloud.md
doc/user/content/integrations/redpanda-cloud.md
doc/user/content/sql/create-connection.md
doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/create-source/postgres.md
doc/user/layouts/partials/sql-grammar/create-connection.svg
doc/user/sql-grammar/sql-grammar.bnf

Revert documentation changes made in #15420 until the release is out. Will open a follow-up PR that re-instantes the state of the world!

doc/user: revert unreleased syntax changes

---

src/storage/src/controller.rs

Introduce heartbeats to table writers, as per the heartbeats for table readers.
Table writing in `environmentd` can take a long time, as reported by @vmarcos when loading the scale factor 32 TPC-H data. Table writers would time out, for non-obvious-to-me reasons (some part of the INSERT process blocks table writes?).
In any case, these heartbeats should increase the odds that we keep the writers alive even when they are not piloted by regular writes.
View with whitespace ignored.
-

Heartbeat table writers in storage controller

---

doc/user/content/integrations/http-api.md

Add more details and content around the HTTP API:
* Make curls exportable to apps like Postman.
* Set single quotes for curls 
* Add details to the examples.
* Add authorization details and descriptions.
Simple PR.
-

Doc/user: small improvements to the http api

---

doc/user/content/releases/v0.27.0.md

Fix the link issue in the releases page to the LTS version. Currently points to a 404.
Simple one.
-

doc/user: fix link to lts version

---

src/stash/src/postgres.rs

When logging is disabled (most of the time), avoid some work.
- n/a

stash: only count if logging enabled

---

doc/user/content/support.md

Present full email in format and clickable.
-

doc/user: fix support email

---

src/storage/src/source/antichain.rs
src/storage/src/source/source_reader_pipeline.rs

See comments on #15477.
That pr had to merge quickly for the release.

storage: resolve various followups from #15477

---

src/storage/src/source/reclock.rs

@petrosagg noticed this was wrong
Quickly fixing for the incident. The docs explain more, but note that old behavior was fine if they were the same: https://github.com/MaterializeInc/materialize/pull/15526/files#r1000018605

storage: fix log line in common case reclock compact calls

---

doc/user/content/integrations/aws-msk.md
doc/user/content/integrations/confluent-cloud.md
doc/user/content/integrations/redpanda-cloud.md
doc/user/content/sql/create-connection.md
doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/create-source/materialize-cdc.md
doc/user/content/sql/create-source/postgres.md
doc/user/layouts/partials/sql-grammar/create-connection.svg
doc/user/sql-grammar/sql-grammar.bnf

Restoring the documentation changes in #15420.
Do **not** merge until the release has been rolled out to all environments.

doc/user: restore `CREATE CONNECTION` syntax

---

doc/user/content/sql/show-sources.md
doc/user/content/sql/system-catalog/mz_catalog.md

+ add subsource as source type
+ add some periods for consistency
-

+ Add subsource as source type

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/storage.rs
src/adapter/src/coord.rs
src/environmentd/src/lib.rs
src/stash/src/lib.rs
src/stash/tests/stash.rs

This is a very common operation (called during all CREATEs and on periodic intervals in `persist_timestamp`), and reducing the total number of external queries and amount of user-blocking work will help improve https://github.com/MaterializeInc/materialize/issues/13772.
* I'm not totally convinced the second commit is worth doing due to the increased API difficulty. But it's not used in many places, so overall I think it's good.
- n/a

stash: improve perf of upsert_key

---

src/storage/src/source/resumption.rs

The previous implementation was using the old timely integration where yielding without having seen any inputs leads to an busy loop of operator activations.
I don't know if we had noticed in production but the resumption operator was sleeping on an interval and had no inputs.
Additionally, the missed tick behaviour was set to the default which is to burst when things are missed. This maybe have caused spikes in persist calls if the dataflow was under load (e.g during an initial snapshot) and then had the timer fire rapidly as many times as were skipped.
-

storage: use async `OperatorBuilder` for resumption operator

---

doc/user/content/integrations/postgres-bastion.md
doc/user/content/integrations/postgres-ec2.md
doc/user/content/sql/create-connection.md

Provide an integration guide for connecting Materialize to Postgres through an SSH Bastion server.
Related issue: https://github.com/MaterializeInc/materialize/issues/15602
-

doc/user: ssh bastion server guide

---

src/storage/src/source/reclock.rs
src/storage/src/source/resumption.rs
src/storage/src/source/source_reader_pipeline.rs

This pr does various things to improve the situation around compaction frontier since's, until we have a fix for the bug figured out. It:
- Makes it so we ACTUALLY compact the `ReclockFollower` trace. Currently we just always compact it to the initial `resume_upper` and never again
- Avoid compacting the follower trace if the `since` hasn't moved
- Share some logic around compaction since calculation
- Add a good number of `info!` log lines around compaction and reclock initialization. As these happen once every 30 seconds and at startup, they should not be too onerous (some happen per-worker).
- Change the resumption interval to 30 seconds to make logging more reasonable.
- new output looks like this: https://gist.github.com/guswynn/7a783de31e3a4b5f845a86c72376d491
- Skip the first …

storage: fix source reader remap trace compaction, and improve logging

---

doc/user/content/overview/key-concepts.md

doc/user: improve intra-page links in Key Concepts

---

doc/user/content/integrations/confluent-cloud.md

Changing the instructions on how to get to the _API KEYs_ section in Confluent UI As per the #15629 issue.
-

doc: Confluent Cloud guide API Key steps

---

src/storage/src/source/persist_source.rs

The old macro/scheduler based timely/async integration had many footguns and was difficult to reason about so it's getting deleted in a future PR.
Disabling whitespace in the diff should make the diff smaller as the indentation changed
-

storage: move persist source to new timely/async integration

---

doc/user/content/sql/patterns/ttl.md

Port `lts` [TTLs guide](https://materialize.com/docs/lts/sql/patterns/ttl/)
Simple porting PR.
-

doc/user: port ttl pattern guide

---

src/storage/src/sink/kafka.rs

The old macro/scheduler based timely/async integration had many footguns and was difficult to reason about so it's getting deleted in a future PR.
Disabling whitespace in the diff should make the diff smaller as the indentation changed
-

storage: move kafka sink to new timely/async integration

---

src/storage/src/controller.rs

This should now reflect current behaviour/intention.
-

storage: update rustdoc for StorageController::update_write_frontiers

---

test/cluster/mzcompose.py

As a follow-up from #15671, this PR adds a regression test for the bug fixed there.
* This PR adds a regression test.
Tests #15535.
-

Add a regression test for #15535

---

doc/user/assets/sass/_railroad_diagrams.scss

Fix overflows in the documentation diagrams.
-

doc/user: fix overflow in diagrams

---

src/pgtest/src/lib.rs

The `pgwire::test_pgtest` would occasionally fail in CI with an error that said:
thread 'test_pgtest' panicked at 'called `Result::unwrap()` on an
`Err` value: Interrupted system call (os error 4): waiting for
ReadyForQuery, saw []
The error was coming from a tcp network read call. https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read According to the documentation, this call can fail with a non-fatal error of the `ErrorKind::Interrupted` kind. In this scenario we should be retrying the read.
This commit adds a retry when we see this error instead of failing the test.
Fixes #15419
- N/A

test: Fix test flake on pgwire::test_pgtest

---

doc/user/content/releases/v0.28.md
doc/user/content/releases/v0.29.md
doc/user/content/releases/v0.30.md
doc/user/content/sql/create-source/load-generator.md
doc/user/layouts/partials/sql-grammar/create-source-load-generator.svg
doc/user/layouts/partials/sql-grammar/load-generator-option.svg

Flesh out the `v0.29.0` release notes. Deliberately left out:
* https://github.com/MaterializeInc/materialize/pull/15563
* https://github.com/MaterializeInc/materialize/pull/15560
These strike me as fixes for behavior that was undesired in the first place. Let me know if you disagree, and I'll work them in, @benesch!
<hr>
⏰ Reminder to merge #15550 once we merge this PR!

doc/user: polish v0.29.0 release notes

---

src/postgres-util/src/lib.rs
test/ssh-connection/mzcompose.py
test/ssh-connection/pg-source-ingest-more.td

Resolves https://github.com/MaterializeInc/materialize/issues/15722 using https://github.com/MaterializeInc/materialize/issues/15722#issuecomment-1293554427

storage: turn off strict host checking in ssh tunnels

---

doc/developer/style.md

Provide some guidance about phrasing and leveling log messages. Part of epic #15715.
* This PR provides guidance for fixing other bugs.
- n/a

doc/developer: add a log message style guide

---

doc/user/content/ops/optimization.md
doc/user/content/overview/arrangements.md
doc/user/content/sql/create-index.md

- Updates in `optimization.md` with recent improvements around speeding up filters using indexes.
- More details about joins to `optimization.md`.
- Minor tweaks in `create-index.md`, including a new link to `optimization.md`.
- Tweaks in the warning about implicit casts in `arrangements.md`, since this is only relevant for joins now, not for literal equality filters, since https://github.com/MaterializeInc/materialize/issues/15525 is solved.
I'm using the word "collection" in several places, but this is still up for debate: https://materializeinc.slack.com/archives/CPNFV9CVB/p1666703721110309?thread_ts=1666688596.313569&cid=CPNFV9CVB.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/14645
- No, only doc changes.

Update index usage docs

---

doc/user/content/sql/functions/now_and_mz_now.md

doc: tweak mz_now() documentation

---

src/storage/src/source/persist_source.rs

Intended to address #15843.
If we create and immediately drop a dataflow with a persist source, `computed` will respond promptly announcing completion of the deed even before we have scheduled the dataflow operator. This means there is a race where the controller may learn this, allow compaction, and then .. when the dataflow operator is eventually scheduled (while under load, say) then `persist_source`'s `async_stream` operator will finally run and attempt to subscribe to a read handle at a now-invalid `as_of`.
This change guards the subscription behavior with a token that is part of the token bundle, and as long as it is held we should not yet have responded with a `FrontierUppers([])` response (this is an important invariant to uphold, and I think we happen to do so by not immediately …

Prevent persist subscribe if dataflow token has been dropped

---

src/persist-client/src/internal/state_diff.rs

Sniff out a newly inserted batch (one whose lower lines up with the current upper) and handle that now. Then fall through to the rest of the handling on whatever is left.
Touches #15493
-

persist: another special case in apply_diffs_spine

---

Cargo.lock
src/compute/Cargo.toml
src/environmentd/Cargo.toml
src/storaged/Cargo.toml

release: bump to version v0.31.0-dev

---

src/stash/src/postgres.rs

Two major improvements to postgres consolidation.
First: consolidate in a background task using a separate connection. This has the potential to unblock consolidation operations from user requests. However, based on our very slow method of consolidating (deleting and rewriting the whole dataset each consolidation), this operation could take a long time and still block user requests due to transaction contention.
Second: to reduce the overall time consolidation takes and thus reduce transaction contention time, only consolidate keys for which deletions have happened. This leaves lots of data with timestamps before the since, but that's fine. Instead, we only insert a new entry if the diff is non zero, otherwise we delete the two diff entries that now sum to 0. Theoretically we could …

stash: consolidate in a background task

---

src/stash/src/postgres.rs

Detect cockroach and set ttl if so. Matches persist.
See #15842
See https://github.com/MaterializeInc/materialize/pull/15857#issuecomment-1301697750
- n/a

stash: set cockroach gc ttl

---

src/persist-client/src/internal/trace.rs

This gets called in Spine::tidy_layers, which gets called in of Spine::introduce_batch. When we rehydrate a Spine from persist state, introduce_batch is called for each of the HollowBatches on the state. Combined, this resulted in an unintended and unnecessary repeated re-computation of this len. (I haven't thought through exactly, but it's possible this was `O(num_batches^2)` or something equally bad.)
This was significant enough to show up as the major factor during a high CPU event on prod. It's easy enough to cache this len, so do it.
-

persist: cache len on SpineBatch::Fueled

---

doc/user/content/sql/create-source/_index.md

fixed type-o

---

src/adapter/src/coord/ddl.rs
src/adapter/src/explain_new/mod.rs
src/compute/src/bin/computed.rs
src/environmentd/tests/pgwire.rs
src/expr/src/scalar/func.rs
src/interchange/src/avro/encode.rs
src/mz/src/configuration.rs
src/npm/src/lib.rs
src/persist-client/src/error.rs
src/persist-client/src/internal/encoding.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/lib.rs
src/persist/src/cfg.rs
src/persist/src/indexed/encoding.rs
src/pgcopy/src/copy.rs
src/pgwire/src/protocol.rs
src/sql/src/func.rs
src/sql/src/plan/expr.rs
src/sql/src/query_model/test/util.rs
src/storage-client/src/source/persist_source.rs
src/storage/src/bin/storaged.rs
src/storage/src/sink/kafka.rs
src/storage/src/source/source_reader_pipeline.rs
src/testdrive/src/action.rs
src/testdrive/src/action/psql.rs
src/transform/src/reduction.rs

moving forward
see https://materializeinc.slack.com/archives/CM7ATT65S/p1667586820893679

update codebase for 1.65 clippy

---

src/storage-client/src/source/persist_source.rs

Blocked by #15868. [Slack thread](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1667473791576749)
When a collection is dropped while we are trying to install a persist_sink, it is possible that it hangs forever in `subscribe` because the upper never advances. This PR fixes the problem by using select! to terminate the subscribe.
Fixes #15831
- None

persist_source: Ensure drops also stop subscribe

---

src/prof/src/http/mod.rs
src/prof/src/http/templates/prof.html
src/prof/src/lib.rs

This has confused/surprised people several times, so let's make it clearer

Show warning about RAM usage on profiler page

---

src/persist-client/src/read.rs

For #15937
* This PR adds debugging information.
Gonna see if I can get a repro in staging with this before we include it in the next release (which I worry will be spammy).
-

persist: add debugging information for unexpectedly long seqno holds

---

src/sql/src/plan/statement/show.rs

Get rid of stray debugging println

---

src/stash/benches/postgres.rs
src/stash/src/lib.rs
src/stash/src/postgres.rs
src/stash/tests/stash.rs

Use a query pattern that is more optimized for the kinds of consolidation we perform in production. Currently any consolidation we do is always a deletion because we have no operation that has a diff > 1, so any diff < 0 will always have a sum(diff) = 0, thus resulting in only the removal of data. To accommodate that reality, perform the DELETE query first, consolidate in Rust, then INSERT back anything needed (currently only exercised by tests).
The explain plan for the new query involves two indexes scans over data, compared to three scans from previously (and also one fewer index join and lookup join).
```
• delete
│ from: data
│ auto commit
│
└── • hash join (semi)
│ equality: (key) = (key)
│
├── • index join
│   │ table: data@data_pkey
│   │
│   └── • scan
│         missing stats
│ …
```

stash: optimize improve consolidation queries

---

Cargo.lock
src/compute/Cargo.toml
src/environmentd/Cargo.toml
src/storage/Cargo.toml

release: bump to version v0.32.0-dev

---

doc/user/content/releases/_index.md
doc/user/content/support.md

Adding a reference in the support documentation to the Status page API as discussed here: https://github.com/MaterializeInc/developer-experience/issues/189
-

Doc: add reference to status page API

---

src/persist-client/src/critical.rs

persist: fix "ships passing" build break

---

doc/user/content/quickstarts/_index.md

From: https://materializeinc.slack.com/archives/C015RHB3LDR/p1668116827270679

doc/user: Unpublish quickstarts index

---

src/adapter/src/client.rs
src/adapter/src/coord.rs

While here, small refactor to cleanup common use of cmd_tx.send().
See https://github.com/MaterializeInc/cloud/issues/4146
- n/a

adapter: add metrics for some adapter client ops

---

doc/developer/testdrive.md
src/testdrive/src/action/sql.rs
src/testdrive/src/parser.rs
test/kafka-ssl/smoketest.td
test/testdrive/structured-errors.td

testdrive: support DETAIL and HINT assertions

---

src/storage-client/src/source/persist_source.rs

`tokio::task::yield_now()` has a weird reputation as being related to the tokio executor, but it has effectively the same implementation as `force_yield` (https://docs.rs/tokio/latest/src/tokio/task/yield_now.rs.html#37-58), so we should just use it! Let me know if you want me to move more of the docs I deleted inline!

storage: replace force_yield with tokio::task::yield_now

---

src/orchestrator-kubernetes/src/lib.rs

Calling `orcherstrator.namespace("foo")` several times should not create several new copies of the namespaced orchestrator

Make k8s orchestrator clone Arcs, like process orchestrator.

---

src/persist-client/src/read.rs

Our `seqnos_held` calculation was backwards and was always zero, hence why we didn't see it in the logs 🙈. This updates the logic and adds a backtrace, so we can further narrow in on where the mischief is taking place.
Part of investigating https://github.com/MaterializeInc/materialize/issues/15937
-

persist: fix logging of high seqno hold + add a backtrace

---

doc/user/content/sql/create-source/load-generator.md
doc/user/content/sql/create-source/postgres.md
doc/user/layouts/partials/sql-grammar/create-source-postgres.svg
doc/user/sql-grammar/sql-grammar.bnf

doc/user: document `TEXT COLUMNS` option for the PostgreSQL source

---

src/prof/src/lib.rs

This will hopefully show people how to render them when they're being passed around in Slack

Add some commentary to the top of .mzfg files

---

test/testdrive/replica-targeted-select.td

Follow-up to https://github.com/MaterializeInc/materialize/pull/16129, addressing test cleanup that I have missed the first time around.
* This PR fixes a test.
-

Clean up in replica-targeted-select.td

---

Cargo.lock
src/ore/Cargo.toml

discussed offline: @benesch has wanted to publish this for "years"

Prepare mz-ore for publication

---

Cargo.lock
src/mz/Cargo.toml

deps: bump to open v3.2.0

---

doc/developer/reading.md

Arjun said this is required reading.
- n/a

doc: add latency talk to required reading

---

ci/release-qualification/pipeline.yml
doc/developer/zippy.md
misc/python/materialize/zippy/framework.py
misc/python/materialize/zippy/kafka_actions.py
misc/python/materialize/zippy/kafka_capabilities.py
misc/python/materialize/zippy/mz_actions.py
misc/python/materialize/zippy/scenarios.py
misc/python/materialize/zippy/sink_actions.py
misc/python/materialize/zippy/sink_capabilities.py
misc/python/materialize/zippy/source_actions.py
misc/python/materialize/zippy/source_capabilities.py
misc/python/materialize/zippy/table_actions.py
misc/python/materialize/zippy/table_capabilities.py
misc/python/materialize/zippy/view_actions.py
misc/python/materialize/zippy/view_capabilities.py
test/zippy/mzcompose.py

Zippy parameterized actions

---

src/environmentd/tests/sql.rs

test: ignore flaky test

---

src/orchestrator-kubernetes/src/lib.rs

Watching k8s services sometimes produces errors. The ones we have observed so far are:
* ["too old resource version"](https://sentry.io/organizations/materializeinc/issues/3697919489/?project=6780145)
* ["Connection refused"](https://sentry.io/organizations/materializeinc/issues/3728364110/?project=6780145)
In both cases, the errors seem to have been transient. The first ones [seem to be expected when watches are re-created](https://github.com/kubernetes/kubernetes/issues/22024#issuecomment-591814814), the second ones might be caused by networking issues.
There is not much value in showing transient k8s errors in Sentry, so this PR downgrades them to warnings.
Fixes #16205.
It is not clear whether there are any k8s errors that can be returned by the …

Downgrade k8s service watch errors to warnings

---

misc/python/materialize/cloudtest/application.py

This was added accidentally in #16209.

Remove dead constant

---

doc/user/content/ops/network-security/ssh-tunnel.md
doc/user/content/sql/create-connection.md
doc/user/layouts/partials/sql-grammar/create-connection-kafka-broker.svg
doc/user/sql-grammar/sql-grammar.bnf

I merged https://github.com/MaterializeInc/materialize/pull/16223 too early

Revert "Add examples + adapt SSH tunnel connections guide"

---

src/environmentd/tests/sql.rs

Enable test_coord_startup_blocking

---

src/environmentd/tests/sql.rs

I was unable to successfully reproduce the error, so I restructured the test to make it easier to debug in the future and increased the timeout.
-

test: Make test_no_block easier to debug

---

doc/user/content/releases/v0.27.md
doc/user/content/releases/v0.28.md
doc/user/content/releases/v0.29.md
doc/user/content/releases/v0.30.md
doc/user/content/releases/v0.31.md
doc/user/content/releases/v0.32.md
doc/user/content/releases/v0.33.md
doc/user/content/sql/explain.md

Adding release notes for v0.32.1-3. 🐞 
It'd be helpful to have some more actionable context around patch release fixes. It's a bit hard to translate these into something users can relate to, otherwise!

doc/user: polish v0.32.x release notes

---

src/storage-client/src/types/connections.rs

`tokio::net::lookup_host` requires a port, even though the port will later be ignored by `resolve_to_addrs`.
- n/a

storage-client: fix CSR PrivateLink tunneling

---

doc/user/content/sql/patterns/ttl.md

Remove the tail from the patterns. Remove all the objects for simpler introduction.
Simple PR.
-

Simple fix. Remove and rephrase

---

src/compute-client/src/controller.rs

Add a comment explaining why we poll to in a loop to get process metrics

---

doc/user/assets/sass/_content.scss

Fix the style for the `<p>` tag inside `<li>` in `<ol>` in our documentation.
Preview: https://preview.materialize.com/materialize/16352/
Any alternative is welcomed.
-

doc/user: fix style inside lists

---

doc/user/content/ops/network-security/privatelink.md

Adding a guide for the AWS MSK PrivateLink integration.

doc: Add AWS MSK PrivateLink guide

---

src/storage/src/source/reclock.rs

The logic in `ReclockOperator::reclock_time`, even though it was thoroughly documented and passed numerous tests, was not correct and could end up reclocking `FromTime` times earlier than they should. Its fatal flaw was that it was assuming that one of these two cases must always hold:
* When `src_ts` changes from being beyond the `FromTime` frontier to not beyond we will observe a triplet with a positive diff whose `from_ts` is not beyond `src_ts`.
* When the frontier represented by the remap collection advances but it `src_ts` remains beyond it we will observe a triplet with a positive diff whose `from_ts` is beyond `src_ts`.
Both of the above assumptions turn out to be incorrect.
The first assumption is not true if the `FromTime` frontier ever advances to the empty antichain. In that …

storage: correctly calculate the times to reclock to

---

doc/user/content/get-started.md
doc/user/content/integrations/sql-clients.md

Adding `psql` installation guide.
Closes #16340

doc: Add psql installation guide

---

doc/user/content/ops/network-security/ssh-tunnel.md
doc/user/content/sql/create-connection.md
doc/user/layouts/partials/sql-grammar/create-connection-kafka-broker.svg
doc/user/sql-grammar/sql-grammar.bnf

accidentally had to revert https://github.com/MaterializeInc/materialize/pull/16223

redo: doc/user: document kafka-over-ssh

---

doc/user/content/releases/v0.32.md
doc/user/content/releases/v0.33.md
doc/user/content/releases/v0.34.md

Release notes for v0.33.0. 🤲 
Reminder to merge #16257 once the release has been rolled out to production. I'll cover #16370 later today!

doc/user: polish v0.33 release notes

---

src/timely-util/src/builder_async.rs

When writing async operators that are also tokened it's easy to accidentally exit the future with data still pending on the inputs. This can cause the dataflow to be permanently in memory and never dropped because these inputs will hold back the frontier from ever advancing to the empty antichain.
This change makes it so that when a handle gets dropped it registers itself in a drainage queue that is managed by the async operator machinery. When the logic future becomes ready (which means that the user logic returned) the operator framework will automatically drain any registered handles until timely eventually cleans it up.
-

timely-util: automatically drain dropped handles

---

src/adapter/src/coord/appends.rs

Previously, when a caller wants to perform a write to a system table, each write was represented by single `BuiltinTableUpdate` which was converted to a single `PendingWriteTxn`. Each `PendingWriteTxn` is fairly large (1,896 bytes), while each `BuiltinTableUpdate` was fairly small (40 bytes). This generally caused a ballooning of memory allocated for each system table write.
This was especially bad during bootstrapping which retracts all rows in the system tables, and then re-inserts each row. This process could occasionally require in excess of 2GB of memory.
This commit allows the caller to group a `Vec` of `BuiltinTableUpdate` into a single `PendingWriteTxn`, significantly decreasing the size needed.
Fixes #16404
-

adapter: Decrease bootstrap memory requirements

---

doc/user/assets/sass/_base.scss
doc/user/assets/sass/_content.scss

| - | - |
| ![image](https://user-images.githubusercontent.com/46004116/205041733-bf4a6603-9574-4a44-9449-a8212f8b869d.png) | ![image](https://user-images.githubusercontent.com/46004116/205041595-d5bf2fb1-b85a-43f4-9315-dfec4bec964e.png) |
Relates to https://materializeinc.slack.com/archives/C044V7M4F6W/p1669814734302179
-

[doc/user]: small fixes and updates.

---

doc/user/content/sql/system-catalog/mz_internal.md

Addresses the source bit of #16370.

doc/user: document source status system catalog objects

---

src/ore/src/tracing/mod.rs

6c09ac7 introduced a major performance regression, likely by perturbing the tracing reload layer. This commit restores the old approach to reloading filters, in the hopes of restoring the old performance. (The tracing library is inscrutable enough that I didn't bother tracking down the root cause.)
Fix #16435.
- n/a

ore: fix performance regression in tracing

---

test/zippy/mzcompose.py

Remove repetitive output that had no information value.
CI logs were filling up with repetitive needless crap.

zippy: Silence docker-compose run command lines

---

src/stash/src/postgres.rs

Previously we would verify the old upper and seal (advance the upper) in separate futures. If sealing executed before the check, the check would fail. We've long had a policy to assume that futures could first-poll or execute in any order. This is the first suspected example of incorrectly violating that policy resulting in production outages.
Fixes #16425
- n/a

stash: verify and seal in known order

---

src/storage/src/source/commit.rs
src/storage/src/source/metrics.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs

https://materializeinc.slack.com/archives/C01CFKM1QRF/p1670266735619309
ci should ensure its safe!

storage: downgrade offset commit error log and add metrics

---

doc/user/assets/sass/_content.scss
doc/user/layouts/_default/baseof.html

make the copy button on the codeblocks keyboard accessible.

---

doc/user/assets/sass/_base.scss
doc/user/assets/sass/_content.scss

Fixes #16153
| Before | After | 
| - | - |
| ![image](https://user-images.githubusercontent.com/46004116/206161939-7755f5e5-95ee-4827-94c3-942783456100.png) | ![image](https://user-images.githubusercontent.com/46004116/206161479-92b97d74-4304-4800-932f-dec10e3a968d.png) |
| ![image](https://user-images.githubusercontent.com/46004116/206163278-b8e9eef9-ed90-4f66-b1ad-da1a7a2c8b5b.png) | ![image](https://user-images.githubusercontent.com/46004116/206162420-bc2a652e-18ed-4cbd-9de0-4b3c4be814a9.png) |

improve the notes design.

---

src/compute/src/sink/persist_sink.rs

Since the `AsyncOperatorBuilder` arranges for inputs to be drained after the operator logic terminated, it is no longer necessary to perform that draining manually within the operator logic. This PR makes `mint_batch_descriptions` stop doing so for inactive workers, and instead lets them return early/immediately.
Inspired by this observation from @petrosagg: https://github.com/MaterializeInc/materialize/pull/16353#discussion_r1037293358
-

persist-sink: let inactive workers return early

---

doc/developer/design/20221204_with_mutually_recursive.md

Design document for `WITH MUTUALLY RECURSIVE`.
Not supporting iteration is starting to feel a bit silly.
This is a fairly new and interesting part of the world, so feel more than welcome to ask questions.

Propose `WITH MUTUALLY RECURSIVE`

---

test/source-sink-errors/mzcompose.py

Various Postgres error scenarios were not being exercised in CI.

test: Additional tests for Postgres source errors

---

src/storage-client/src/source/persist_source.rs

storage: use the new async OperatorBuilder for persist_source stage 1

---

src/environmentd/src/telemetry.rs

Fix MaterializeInc/analytics#89.
- n/a

environmentd: add source and sink types to telemetry reporting

---

src/persist/src/indexed/columnar.rs

`ColumnarRecordsRef::get` was calling `self.validate()`, which, in `cfg(debug_assertions)`, looked at every record. Combined with `ColumnarRecordsIter` calling `get` once for each record, `ColumnarRecordsIter` was accidentally O(n^2) in the number of records.
Fix this by calling validate once when the `ColumnarRecordsRef` is constructed instead of inside `get`.
-

persist: fix accidental N^2 in debug-only validations

---

ci/nightly/pipeline.yml
test/bounded-memory/mzcompose
test/bounded-memory/mzcompose.py

Process various datasets in a memory-constrained environment in order to confirm that garbage collection is sufficient to prevent OOM or thrashing.

ci,test: Add a dedicated test for bounded memory operation

---

doc/user/content/releases/v0.33.md
doc/user/content/releases/v0.36.md
doc/user/content/releases/v0.37.md
doc/user/content/sql/system-catalog/mz_internal.md

Release notes for v0.36.0 (we skipped v0.34 and v0.35). 🤸‍♀️ 
Reminder to merge #16530 and #16480 once the release has been rolled out to production.

doc/user: polish v0.36 release notes

---

src/adapter/src/lib.rs
src/environmentd/tests/sql.rs

For some reason, GitHub didn't pick up the last commit that I intended to land as part of #16657 .

Address comments on #16657

---

src/adapter/src/catalog.rs

Our approach to the initial sync for LaunchDarkly configuration parameters appears suspect at first glance, but was actually carefull considered. Drop in a big comment explaining the approach.
* Didn't want to forget this.
- n/a

adapter: document initial config sync philosophy

---

Cargo.lock
src/adapter/src/catalog.rs
src/adapter/src/catalog/builtin.rs
src/adapter/src/coord.rs
src/adapter/src/coord/dataflows.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/lib.rs
src/adapter/src/session/vars.rs
src/adapter/tests/sql.rs
src/environmentd/Cargo.toml
src/environmentd/tests/sql.rs

Ignore all commits except the last. This is rebased on top of #16657 which is why the other commits are there.
See commit message for full explanation.
@antiguru as randomly-selected compute team reviewer.
Fixes https://github.com/MaterializeInc/materialize/issues/16357
Ignore all commits except the last. This is rebased on top of #16657 which is why the other commits are there.
See commit message for full explanation.
- None

Allow custom compaction windows on builtin tables

---

doc/user/content/sql/create-source/load-generator.md

Adding `TICK INTERVAL` examples to some of the `CREATE SOURCE` statements and leaving some without it as an example that it is not a required parameter. 
Closes #16092

Doc: load gen source tick interval example

---

src/adapter/src/catalog.rs

This fixes a regression introduced #16658 and reported in #16747.
Fixes #16747. The regression was was introduced after pulling up only 2/3 of the parameter initialization logic in the `Catalog::open` method in #16658. The remaining 1/3, which is responsible for pulling LaunchDarkly sync and was guarded by the code
```rust
if let Some(system_parameter_frontend) = ... {
// pull system parameter values from LaunchDarkly ...
}
```
should always follow immediately after the two `for` loops that initialize the system configuration state with `state.insert_system_configuration(name, value)` calls.
The `Catalog::open` method is already ~500 LOC, and the order in which we do things can be quite brittle. I factored out the entire parameter initialization logic …

adapter: fix regression introduced by 9d2acaaf4

---

src/persist-client/examples/inspect.rs
src/persist-client/src/inspect.rs

Wrote this up to debug an issue. Lets us inspect the contents of a particular batch part to see what's going on... check out the inline desc, what keys we're working over, etc.
-

persist: inspect tool for printing contents of a batch part

---

doc/user/content/sql/create-connection.md

see https://github.com/MaterializeInc/materialize/pull/16633
@morsapaes i believe this requires no `bnf` changes!

docs/user: add docs for csr-over-ssh

---

doc/user/content/releases/v0.37.md
doc/user/content/releases/v0.38.md
doc/user/content/sql/system-catalog/mz_internal.md

Release notes for v0.37.0. 🌩️ 
Reminder to merge https://github.com/MaterializeInc/materialize/pull/16646 once the release has been rolled out to production (though we're still being inconsistent about merging documentation for unreleased features ahead of the release, which is confusing but also...hard to contest).

doc/user: polish v0.37 release notes

---

src/persist-client/src/error.rs
src/persist-client/src/internal/datadriven.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/maintenance.rs
src/persist-client/src/internal/metrics.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/lib.rs
src/persist-client/src/read.rs
src/persist-client/src/write.rs
src/persist-client/tests/machine/empty_since
src/persist-client/tests/machine/empty_upper
src/persist-client/tests/machine/gc
src/persist-client/tests/machine/regression_listen_compaction

We were seeing panics in nightly. See the second commit for details on the fix.
-

Unrevert "Merge pull request #14704 from danhhz/persist_empty_antichain" 

---

doc/user/content/ops/network-security/privatelink.md
doc/user/content/ops/network-security/ssh-tunnel.md
doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/create-source/postgres.md

doc/user: improve network security documentation

---

test/feature-benchmark/scenarios_concurrency.py

The scenario was heavily bound on Cockroach CPU and I/O, and benchmarking CRDB is not the goal here.
- use 25 materialized views instead of 100
- use more data per view in order to amortize any startup costs better
- do not use a table as a source for the dataflows in order to avoid any environmentd/persist involvement
Nightly feature benchmark was failing with a performance regression which could not be bisected successfully.

feature-benchmark: Adjust the ParallelDataflows scenario

---

doc/user/assets/sass/_content.scss

Addresses the issues specified in the private thread [here on slack](https://materializeinc.slack.com/archives/C044V7M4F6W/p1671621907526429?thread_ts=1669814734.302179&cid=C044V7M4F6W).
This is how things will look with the PR changes:

fix nesting issues inside ul.

---

src/environmentd/src/telemetry.rs

Fix MaterializeInc/analytics#107.
- n/a

environmentd: add clusters and replicas by size to telemetry

---

doc/user/content/releases/v0.37.md
doc/user/content/releases/v0.38.md
doc/user/content/releases/v0.39.md

doc/user: polish v0.38 release notes

---

doc/user/content/get-started.md

Addresses this [internal request](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1672892629711019?thread_ts=1672891502.371099&cid=CU7ELJ6E9)

add the redirect.

---

src/environmentd/tests/server.rs

The delayed startup increased the existing flakiness of this test because there is now less time between ack'ing the connect and attempting to cancel. Fix twice by waiting for the CREATE to finish, and then cancelling in a loop.
Fixes #16990
- n/a

environmentd: deflake test_cancel_long_running_query

---

src/compute/src/render/reduce.rs

Each `reduce::Accum` would track its own `total: Diff` counting the number of contributing records. This total is the same across all accumulations, and shouldn't need to be maintained independently if there are multiple accumulations.
-

Extract count from each `Accum`

---

doc/user/content/get-started.md

Patching formatting issue introduced in #16966.
@nisarhassan12, please double-check that you aren't committing editor-specific formatting in the future. As a best practice, you also shouldn't merge pull requests in this repo without approval from at least one reviewer. For documentation changes, please always tag me or someone else from the DevEx team!

doc/user: minor fix in get started guide

---

src/adapter/src/config/frontend.rs
test/launchdarkly/mzcompose.py

Use a custom `environment` kind as the context type used when communicating with LaunchDarkly. The `EnvironmentId` fields are set as string-valued attributes in the created context.
Uncommenting some disabled code as we were waiting to be added to the EAP for the contexts feature before we can do this.
- The diff should be fairly straight-forward to review.
- I'll run a manual nightly build to validate that the LaunchDarkly job still works after the build image is pushed.

adapter: use `environment` context for LaunchDarkly sync

---

doc/user/assets/sass/_base.scss
doc/user/layouts/_default/baseof.html

Addresses this [internal private feedback](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1673382654510569). 
| - | - |
| ![image](https://user-images.githubusercontent.com/46004116/211670865-fa040d51-2884-4f00-a156-aa7b4de0ff7b.png) | ![image](https://user-images.githubusercontent.com/46004116/211670558-00484f30-a44d-4102-b40f-edf73b8be429.png)|

make code links distinguishable.

---

src/persist-client/src/cli/admin.rs
src/persist-client/src/critical.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/gc.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/maintenance.rs
src/persist-client/src/lib.rs
src/persist-client/src/read.rs
src/persist-client/src/write.rs
src/persist-client/tests/machine/empty_since
src/persist-client/tests/machine/empty_upper

This reverts commit 0e1aaa0dce662c48ea5be2e7a943b308be723e76.
See https://github.com/MaterializeInc/materialize/issues/17091
@bkirwi, on `main`, `src/persist-client/src/internal/gc.rs` did not revert cleanly. I believe I fixed it up correctly, but please look at it closely; I think the changes it conflicted with are yours!

Revert "[persist] Always perform routine maintenance (#16654)"

---

src/persist-client/examples/maelstrom/txn.rs

This was causing failures in nightly. We do these retries in prod codepaths, but because of Unreliable{Blob,Consensus} and Maelstrom{Blob,Consensus} this wasn't going through the same codepath. A better fix would be to figure out how to unify things here, but as a short-term fix to unbreak nightly, this is the quicker thing.
-

persist: retry Blob::open and Consensus::open in maelstrom

---

src/ore/src/retry.rs

test: Fix flaky retry test

---

doc/user/content/sql/system-catalog/mz_internal.md

Documents https://github.com/MaterializeInc/materialize/pull/16788
- Added `mz_source_statistics`, which contains useful stats about sources

doc/user: document mz_internal.mz_source_statistics

---

doc/user/assets/sass/_base.scss
doc/user/assets/sass/_layout.scss

Addresses [this private slack conversation](https://materializeinc.slack.com/archives/C048HHZ6F3P/p1673548008483249).

make the toc scrollable independent of the page.

---

doc/user/content/sql/patterns/ttl.md

Replaces `mz_now()` usage with `now()` in the TTL pattern.
-

doc/user: replace mz_now() with now() in the TTL pattern

---

test/restart/mzcompose.py

The stash test could not handle all the ways in which the Materialize container could crash when the CockroachDB database to which it is talking is wiped.
This commit restructures the test to be a bit more resilient. I ran this test in a loop on my machine for an hour with no observed failures.
The key here is keeping a connection to Materialize open during the whole test. We *know* that connection will succeed initially (Materialize is healthy); we *know* it will fail once we wipe Cockroach. Keeping the connection open the whole time means we don't have to deal with myriad failure conditions (connection refused, `docker port` failing), and can instead just look for pg8000 reporting a network error on the broken connection.
This commit also removes the "stash error" as an allowable error; …

test/restart: fortify stash test

---

doc/user/content/quickstarts/streaming-analytics.md
doc/user/content/quickstarts/streaming.md

Quick start guide for the streaming analytics demo showcasing ecommerce with soft deletes and layering BI layer over materialized view.
Based on:
* https://github.com/MaterializeInc/materialize/pull/16644
* https://github.com/MaterializeInc/materialize/pull/16533
-

Docs: Streaming BI Quickstart

---

doc/user/content/ops/network-security/privatelink.md

Adding Postgres RDS example to PrivateLink guide.
Closes #16848

Doc: add RDS to privatelink docs

---

src/storage-client/src/controller.rs

This pr makes _parts_ of `create_collections` concurrent, primarily the creation of persist handles for all collections, leaving the sections that mutate the controller state serial. Note there is a large section at the bottom that initializes actual ingestion that ALSO need to be made concurrent, but they are harder, and require some heavier refactoring. I wanted this to NOT get out of 
Also, we could make remap shard migration even more concurrent here, but I chose to not do this, because it increases complexity for a one-off migration
partially closes: https://github.com/MaterializeInc/materialize/issues/17057
- Please read the comments closely to understand the constraints I am under.
- @aljoscha please review my changes to `migrate_remap_shard` …

storage: perform some parts of create_collections concurrently

---

src/persist-client/src/operators/shard_source.rs

Ensures that the 2nd stage in `shard_source` always emits all parts within a batch to avoid downstream operators from seeing negative accumulations, and documents that the 1st stage must atomically produce batch parts. The downside is that it means we'll continue to chew over fetching parts for dataflows that have been dropped (but presumably wasted work is preferable to panics!)
Fixes https://github.com/MaterializeInc/materialize/issues/16860
-

persist: ensure shard source emits full batches

---

doc/user/content/ops/network-security/privatelink.md
doc/user/content/releases/v0.40.md
doc/user/content/releases/v0.41.md
doc/user/content/sql/create-connection.md
doc/user/layouts/partials/sql-grammar/broker-option.svg
doc/user/layouts/partials/sql-grammar/create-connection-kafka-broker.svg
doc/user/sql-grammar/sql-grammar.bnf

Release note(s) for v0.40.0. 🤔 @benesch, could you add a brief explanation to the release note about the behaviour when the option is specified vs. when it's not and there are brokers in multiple AZs? I didn't quite get how to port the blabber in the issues to how things actually translate for the user.
Also adding documentation for #17006. The `CREATE CONNECTION` page is really confusing at this point, so marking it down for a follow-up sanity check.

doc/user: polish v0.40 release notes

---

doc/user/content/quickstarts/streaming-analytics.md

Making small adjustments to the streaming analytics demo:
- Updated the topic names to have a `mysql.shop` prefix as this is how the kafka connect creates them
- Change the `where delete is false` to `where delete = 0` as view creation was failing with `ERROR: WHERE clause error: WHERE clause must have type boolean, not type integer`.

Doc: adjust streaming analytics demo

---

src/adapter/src/catalog.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer.rs

Part of the cluster unification epic (MaterializeInc/cloud#4929).
Follow the style used for dropping other types of objects by making `catalog_transact` responsible for updating the in memory state to reflect the dropped items, rather than the sequencer method.
This will make it easier to turn linked clusters into real clusters, by keeping the logic for dropping clusters and cluster replicas in one place.
I wish I could type faster.
- n/a

adapter: move drop cluster code to `catalog_transact`

---

doc/user/content/sql/create-index.md

This PR addresses:
- https://github.com/MaterializeInc/materialize/issues/15780

update description of CREATE DEFAULT INDEX

---

doc/user/content/integrations/cdc-postgres.md
doc/user/content/integrations/dbt.md
doc/user/content/sql/create-index.md

Fixups following #17238 and #16502.

doc/user: minor fixups

---

src/sqllogictest/src/bin/sqllogictest.rs

std::process::exit causes Drop impls not to be run, and part of the convenience of the process orchestrator is the KillOnDropChild wrapper around spawned children.  This is why any test failures were causing clusterd processes to remain around.
Instead, let std::process::Termination handle it.  Alas, this means we can't easily express a variety of distinct non-zero exit codes, but I didn't notice any uses of this, at least with some quick grepping around.  (If any reviewer knows that the single use of exit code 2 instead of 1 in the previous code is significant, please alert me.)
Pairs with #17295.
* This PR fixes an unreported bug. …

sqllogictest: return from main rather than exit(2)'ing

---

src/adapter/src/catalog/storage.rs

adapter: use stash txn during stash init

---

src/persist-client/src/cli/inspect.rs

Allow `persistcli` users to specify the key of the rollup they want to inspect.
Known-desirable feature, mentioned in https://github.com/MaterializeInc/materialize/issues/17214.
I've tested this against local state, and confirmed it does correctly fetch a specific rollup when requested.
-

[persist] Inspect any state rollup

---

doc/user/content/sql/system-catalog/mz_internal.md

Documents https://github.com/MaterializeInc/materialize/pull/17125
* This PR documents a feature.
I can add more info in https://github.com/MaterializeInc/materialize/pull/17088

doc/user: document mz_sink_statistics

---

src/environmentd/src/bin/environmentd/main.rs

Trace envd startup for easier debugging.
See #16531
- n/a

environmentd: trace startup

---

src/stash/src/postgres.rs
src/stash/src/transaction.rs

In bootstrap, this reduces one update from 310 updates executed to 1 (although with over 1000 arguments). In a debug build, the time for this operation went from 137ms to 31ms, an obvious improvement.
See #16531
- n/a

stash: batch update sets

---

doc/user/content/releases/v0.41.md
doc/user/content/releases/v0.42.md

Release note(s) for v0.41.0. 🚨 
Taking care of the only outstanding documentation issue next (#17307).

doc/user: polish v0.41.0 release notes

---

misc/dbt-materialize/dbt/adapters/materialize/connections.py
misc/dbt-materialize/dbt/adapters/materialize/impl.py
misc/dbt-materialize/dbt/include/materialize/macros/materializations/incremental.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/listagg.sql
misc/dbt-materialize/tests/adapter/test_basic.py

Replace deprecated exception functions in dbt adaptor
-

dbt-materialize: Replace Deprecated Exceptions

---

doc/user/content/sql/create-source/load-generator.md

Fixes an example in sources. Missing `ALL TABLES`.
-

doc/user: simple fix to command

---

misc/python/materialize/cli/run.py

Currently, sqllogictest will leave clusterd processes around when it either crashes or fails -- in the latter case, this is because it process::exit()s on failure, which causes the Drop impl (KillOnDropChild) in the process orchestrator to not fire.  (I'll fix this, too, but I figured it would be worthwhile separating that change from the change that deals with stragglers.  *edit*: #17297)
The reason sqllogictest doesn't reparent these like environmentd is that it generates a new environment-id every run; I prepared [an alternate branch](https://github.com/tokenrove/materialize/tree/julian/sqllogictest-clusterd-leak-environment-id) where I do that instead, but it seems more self-contained to just kill everything in the process group.  Note that this should still fire no matter how …

Kill all of sqllogictest's descendants

---

Cargo.lock
src/aws-s3-util/Cargo.toml
src/storage-client/Cargo.toml

These were introduced in 2271a771.

deps: remove some unused dependencies

---

src/persist-client/src/cache.rs

We meant to create one per unique blob_uri or consensus_uri, but instead were creating one per open_blob or open_consensus call.
-

persist: fix bug where too many rtt tasks were created

---

src/compute-client/src/service.rs

This PR adjusts the logic in `PartitionedComputeState` to make it stop leaking `pending_subscribes` entries. The approach taken is the same we already take for peek tracking: Once an "end-of-subscribe" message was received from each shard, we can drop the tracking state for that subscribe.
`PartitionedComputeState` leaks `pending_subscribes` entries for subscribes that have shut down.
Part of #17096.
I tested this in my staging env by opening multiple sessions and spamming `SUBSCRIBE (SELECT 1)`. Before this change, both environmentd and the target clusterd had their memory slowly growing. After this change, only the environmentd memory is slowly growing. Which means there is still a memory leak in environmentd. I think I've found it already …

compute-client: stop leaking subscribe tracking state

---

src/mz/Readme.md
src/mz/src/main.rs
src/mz/src/region.rs

Add the Postgres connection string to the output of `mz status ...`
Conv: https://materializeinc.slack.com/archives/C015RHB3LDR/p1675189107820569
New output example:
```
mz region status aws/us-east-1
Healthy:                yes
SQL address:            3szldfghjfwj1efgsblalvxhds.us-east-1.aws.materialize.cloud
HTTPS address:          https://3szldfghjfwj1efgsblalvxhds.us-east-1.aws.materialize.cloud
Connection string:      postgres://joaquin%40materialize.com@3szldfghjfwj1efgsblalvxhds.us-east-1.aws.materialize.cloud:6875/materialize?sslmode=require
```
Afterthought: It would make sense to rename `mz status` to `mz describe`
I'm using the URL crate to format and encode the URL.
-

mz: add connection details to `mz status`

---

src/storage/src/source/source_reader_pipeline.rs

This issue appeared after I merged #17452 yesterday. Previous to that PR we would never hold pending work in our operator state that was not beyond the source upper frontier, and therefore it was correct to only consult the frontier of the timestamper and the frontier of the source handle to calculate what kind of capabilities we need to keep around.
However, after that PR it is possible that we keep around batches for a little bit longer, after the source upper frontier has moved past them and so it is required that we take these held onto times into account when we calculate what is the frontier that is safe to downgrade to.
Fixes #17484
-

storage: reclock: take batches into account when downgrading

---

src/pgrepr/src/value.rs
test/lang/python/smoketest.py

This commit implements into_datum() for Value::Array types, which will
allow us to accept arrays in the extended pgwire protocol. Currently
only decoding of text into arrays is supported.
Fixes #17478
-

sql: Fix decoding of text arrays

---

src/environmentd/tests/pgwire.rs

Network errors sometimes occur here when the server kills the connection, so retry until we get the expected db error.
Fixes #16294
- n/a

environmentd: fix test_conn_user flake

---

doc/developer/platform-checks.md

doc: Minor fixes for "Platform Checks" documentation

---

src/compute-client/src/controller/instance.rs

Like with `FrontierUppers` responses, it is possible that the compute controller receives `SubscribeResponse`s for collections it doesn't track anymore, due to some unfortunate behavior during reconciliation (#16247). We need to ignore these stray responses.
Fixes #17506.
This change handles an edge-case in subscribe frontier tracking that was already handled in the frontier tracking for other collection types. It is clearly the right thing to do, and it should fix #17506, which is caused by us trying to update the write frontiers of a subscribe we no longer track. ~~That said, I don't yet understand why the error reported in #17506 only started to occur in CI recently. There might be another bug somewhere, so I'm still investigating this.~~
- N/A

compute-client: ignore stray `SubscribeResponse`s

---

src/storage/src/source/kafka.rs

Before this change, and after https://github.com/MaterializeInc/materialize/pull/16214, the logs were filled with:
```
cluster-u3-replica-5: 2023-02-08T18:48:23.270740Z TRACE mz_storage::source::kafka: timely-1 source(u4) attempting to commit kafka offsets offsets=[(0, MzOffset { offset: 9 })]
cluster-u3-replica-5: 2023-02-08T18:48:23.270763Z TRACE mz_storage::source::kafka: timely-2 source(u4) attempting to commit kafka offsets offsets=[]
cluster-u3-replica-5: 2023-02-08T18:48:23.270895Z TRACE mz_storage::source::kafka: timely-3 source(u4) attempting to commit kafka offsets offsets=[]
cluster-u3-replica-5: 2023-02-08T18:48:23.270989Z TRACE mz_storage::source::kafka: timely-0 source(u4) attempting to commit kafka offsets offsets=[]
cluster-u3-replica-5: 2023-02-08T18:48:23.374191Z ERROR …
```

storage: skip committing empty offset partition lists to kafka

---

src/compute/src/server.rs

Otherwise, logging won't hear about cleaning up peeks and will assume that they're still active. This isn't inherently bad, but causes an error message on rehydration and might leak memory.
Fixes #17568.
-

Log peek completion on reconciliation

---

src/environmentd/src/telemetry.rs

Previously, they were just reported via the group call as environment properties, but this made it difficult (impossible?) to ask questions about the historical state of environments in downstream tools--e.g., "were there any sinks active on this day?"
This commit also adds a big module doc that explains and justifies the current state of affairs.
Fix MaterializeInc/analytics#130.
- n/a

environmentd: report traits in telemetry rollup event

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.44.0-dev

---

doc/user/content/integrations/_index.md
doc/user/content/integrations/sql-clients.md

Changing the DataGrip support level status to `Beta` as we can now connect and use the SQL console as normal after [disabling automatic database introspection in Datagrip  ](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010694760-How-to-turn-off-automatic-database-introspection-in-Datagrip).
Not marking this as production ready, as for some reason no schemas are being displayed making the UI mostly unusable, as described [here](https://github.com/MaterializeInc/developer-experience/discussions/53).
Closes #17054

Doc: update DataGrip support level status

---

test/cloud-canary/mzcompose.py

Use the materialize/environmentd Docker image to query the mz_version() that we expect to see on the cloud.
In certain cases, e.g. when the documentation was modified, the materialize/materialized container will report a slightly different mz_version().
-

cloud-canary: Use environmentd image to obtain mz_version()

---

src/mz/src/bin/mz/main.rs
src/mz/src/bin/mz/utils.rs

Restrict profile names to **consist of only ASCII letters, ASCII digits, underscores, and dashes.**
https://github.com/MaterializeInc/materialize/issues/16984
-

Mz  restrict profile names

---

src/persist/src/postgres.rs

Closes https://github.com/MaterializeInc/materialize/issues/17666
Avoiding transaction contention as described in the above issue, using techniques as described here: https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference.html#retry_write_too_old

persist: create and alter consensus table in a single batch

---

src/environmentd/tests/auth.rs

It needed to retry like test_conn_user. Achieve this by adding a new error type that can retry, because some errors need to not be a dberror. Separate them even though it makes a weird enum weirder.
- n/a

environmentd: deflake test_auth_base

---

src/stash/src/postgres.rs

This allows cockroach to rebalance connections periodically.
Fixes #17703
- n/a

stash: reconnect on an interval

---

src/persist-client/src/usage.rs

It's possible, due to races, that a writer has more referenced batches in state than we saw for that writer in blob. Cap it at the number of bytes we saw in blob, otherwise we could hit the "blob inputs should be cumulative" panic below.
Ironically, I had this right in the original impl. Then, in code review, I forgot and pulled it back out. :facepalm:
Touches #17752
-

persist: fix "blob inputs should be cumulative" panic in usage.

---

src/sql-parser/src/parser.rs

Slightly improve a few comments in the parser

---

doc/user/content/get-started.md

Got a little too excited about the schema resolution fixes in `v0.44`. Reverting in the user-facing documentation until the release is rolled out to production environments.
Also adding missing URLs to the sample Kafka broker and CSR service (cc @ggnall).

doc/user: patch Get Started ahead of v0.44

---

doc/user/content/ops/network-security/privatelink.md

Adding links to the PrivateLink Terraform modules.
Closes #17212

Doc: add link to privatelink tf modules

---

misc/python/materialize/mzbuild.py

mzbuild: Ignore .mypy_cache

---

doc/developer/platform-checks.md
misc/python/materialize/checks/actions.py
misc/python/materialize/checks/checks.py
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios.py
misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/checks/uuid.py
misc/python/materialize/util.py
test/cloudtest/test_upgrade.py

to address reviewer comments in https://github.com/MaterializeInc/materialize/pull/17849

platform checks: Follow up to base_version

---

test/testdrive/load-generator.td

This adds two new tests for invalid tick interval values in load-generator.
Closes https://github.com/MaterializeInc/materialize/issues/17850
Should more invalid values be checked for here?
-

test: add tests for invalid tick interval values

---

doc/user/content/ops/network-security/privatelink.md

Updating the PrivateLink Terraform module reference note to be more specific about the services that it provisions.
Also moving the health check notice after the TCP listener creation step.

Doc: Fix Privatelink Terraform module note

---

misc/python/materialize/cli/ci_logged_errors_detect.py

https://docs.python.org/3/library/re.html#re.VERBOSE

ci: logged errors: add forgotten re.VERBOSE

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
test/upgrade/check-from-v0.27.0-kafka-source.td
test/upgrade/check-from-v0.45.0-kafka-progress.td

release: bump to version v0.46.0-dev

---

src/storage/src/source/source_reader_pipeline.rs

I reverted the code that this PR re-adds because I thought its only purpose was to provide a subtle guarantee to the decoding stage that we no longer need.
It turns out that providing this subtle guarantee was also a good performance optimization so this PR puts it back but with an updated comment saying that this is purely for performance reasons. 
-

storage: bring reclock optimization back

---

ci/nightly/pipeline.yml
doc/developer/README.md
doc/developer/ci-regexp.md
misc/python/materialize/cli/ci_logged_errors_detect.py
misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/mzcompose/services.py
test/sqlsmith/Dockerfile
test/sqlsmith/mzbuild.yml
test/sqlsmith/mzcompose
test/sqlsmith/mzcompose.py

Fixes https://github.com/MaterializeInc/materialize/issues/17864
-

Add SQLsmith to CI for nightly runs

---

doc/user/assets/sass/_content.scss
doc/user/content/releases/v0.33.md
doc/user/content/releases/v0.39.md
doc/user/content/releases/v0.45.md

The docs list styling was resulting in indentation that did not properly indent the contents of each list item. This commit fixes the issue largely by removing all the special cases. This may cause regression in some of those special cases, but I can't quite tell what they were attempting to accomplish, and this fix certainly makes the basic cases more legible.
- n/a

doc/user: fix list indentation

---

src/storage/src/source/source_reader_pipeline.rs

The remap operator has a starvation issue where if `select!` is totally fair and minting a binding takes more time than the ticker interval then the next time we go around the loop we might peel off one or two progress updates before entering the ticker again and minting a binding for a tiny slice of the available progress. In this situation we keep falling behind in minting bindings causing data to be accumulated in the reclock opreator which sits on data that need to be reclocked.
This PR makes it so if we're falling behind we will make bigger and bigger jumps in the bindings by consuming the entirety of the available progress when there is any.
-

storage: remap: keep up with progress updates

---

src/compute/src/logging/compute.rs

My skunkworks project was to see if the logging code can be made more readable (without impacting its efficiency). I started with the logging of `ComputeEvent`s because of familiarity. If we like the result, I plan to follow up with the other event types in subsequent PRs.
This is not a rewrite, but parts moved around significantly in the first commit. It might be easier to look at the final output in non-diff form, or maybe as a split diff.
Read the commit descriptions, they contain descriptions of the changes made.
- N/A

Refactor compute logging code for readability

---

src/persist-client/src/read.rs

Sometimes a snapshot will be read which consolidates really well (e.g. when the since has been heavily held back but we're reading near the upper). Doing something reasonable here in `persist_source` is complicated and tracked in https://github.com/MaterializeInc/materialize/issues/16858, but for `snapshot_and_fetch` (which is used in the controllers) it's straightforward to consolidate as we go to keep memory usage down.
The first commit is just some code movement. Look at the second commit to easily see the actual diff.
-

persist: consolidate as we go in snapshot_and_fetch

---

src/adapter/src/catalog/builtin.rs
test/sqllogictest/cluster.slt
test/sqllogictest/system-cluster.slt
test/testdrive/catalog.td
test/testdrive/indexes.td

Remove cluster replica utilization index. Fixes #18125

---

test/limits/mzcompose.py

The scenario uses 100 concurrent subscribes as running with 1000 causes a hang -- each subscribe creates a dataflow.
Closes #17689
@def- this entire file dates from before I knew about `dedent` and better organization approaches, hence the repeated use of `print`.

limits test: Add a scenario for SUBSCRIBE

---

misc/python/materialize/cli/ci_logged_errors_detect.py

Errors of the form:
WARN mz_timely_util::panic: halting process: timely communication error: flushing writer: Connection reset by peer (os error 104)
are expected and should not be reported in the Buildkite UI
-

ci: Silence timely 'flushing writer' errors

---

src/testdrive/src/action.rs

Previous commits have added partial implementations of Role Based Access Control (RBAC), and future commits will continue to add more RBAC features. As part of RBAC, ordinary roles may be prevented from executing certain actions, such as creating/destroying databases.
This commit modifies testdrive so that resetting the state of Materialize is always done with the system user. This is to ensure that we are never prevented from resetting Materialize's state due to RBAC. The system user is always a superuser and is therefore always allowed to do anything.
Part of #11579
-

testdrive: Reset Materialize with system user

---

src/persist-client/src/read.rs

Found by @pH14.
The next logic in Listen was making the downgrade_since call before leasing the batch SeqNo that it was about to emit, which is a bug. This could allow the Listen to give up its capability for the batch's SeqNo before we lease it, which could lead to blobs that it references being GC'd.
Touches #17338
Regression tests to come in a followup PR so we can sneak this into the release candidate this week.
-

persist: fix another potential cause of the missing blob panics

---

misc/python/materialize/checks/identifiers.py
misc/python/materialize/checks/roles.py

platform-checks: Add GRANT/REVOKE to existing tests

---

src/pgwire/src/protocol.rs

Add support for "-c opt=foo" by detecting if `-c` is seen and parsing the next token accordingly.
Remove support for parsing `-c\ opt=foo` as Postgres doesn't support this. (And, indeed, it doesn't seem logical to support it: the `\` should be used to _cancel_ the argument-splitting behavior of ` `).
Fixes https://github.com/MaterializeInc/materialize/issues/18233
- Fix a bug in parsing of options in connection string

Parse options strings like `-c opt=foo`

---

doc/user/assets/sass/_layout.scss
doc/user/layouts/_default/baseof.html
doc/user/layouts/partials/sidebar.html

This PR enables a new level for nesting items in our side navigation bar. It'll be useful for style/organize docs better. E..g.: https://github.com/MaterializeInc/materialize/pull/17880#discussion_r1122177040
-

doc/user: Support an additional level for nesting

---

misc/python/materialize/zippy/framework.py
test/zippy/mzcompose.py

Previously, the test ran until all planned Actions were executed, which did not allow precise control over the execution time.
The execution time of the Zippy runs is all over the place.
@def- in a follow-up commit I am going to use this new command-line option to get all the Zippy Buildkite steps to take the desired amount of time.

zippy: Allow maximum execution time of the test to be specified

---

src/ore/src/collections.rs

ore: Fix error message for into_element

---

src/storage/src/source/generator.rs

The load generator sources had a correctnes issue where upon restart they would fast foward exactly as many rows as the offset of their resumption frontier.
This only works under the assumption that each offset contains exactly one row which is true for the counter generator but not true for the TPCH generator.
The fix is to simply count the number of transactions when fast fowarding the iterator.
Fixes #16259
-

storage: fix correctness issue of load generators

---

doc/user/config.toml
doc/user/content/release-notes.md

Add release notes for v0.26.6.

doc/user: release v0.26.6

---

src/postgres-util/src/lib.rs
src/storage-client/src/types/connections.rs

We've been seing errors like
failed to close ssh tunnel: the master connection failed
in production. The actual *reason* that the SSH tunnel failed is buried inside the returned error type, and not part of the `fmt::Display` representation.
This commit adjust the logging to route through `anyhow::Error`, which can be convinced to print all underlying error causes via the `{:#}` format specifier.
* This PR improves internal debuggability of SSH tunnels.
- n/a (only helps internal debugging)

storage: improve SSH tunnel failure errors

---

Cargo.lock
deny.toml
src/sql/Cargo.toml
src/storage/Cargo.toml

remove unused dependencies

---

src/storage-client/src/controller.rs

When we know that a collection has been dropped, we can finalize its shards. Note that this approach's shortcomings (i.e. susceptibility to leaking on failure, inconsistent appearance) are known and will be mitigated by future work; this PR does not adversely affect any of that work or introduce any further inconsistencies.
This code cannot be easily tested in the storage controller's current state, which doesn't provide means of introspecting shards' state. That is something that could be covered in [#13918](https://github.com/MaterializeInc/materialize/issues/13918), which is more work than this, so wanted to see if I could slide through something easy first.
This PR adds a known-desirable feature. Part of #17320
the …

storage: finalize dropped shards

---

doc/developer/design/20230322_metrics_since_granularity.md

This is a lightweight design doc, as the feature being proposed is relatively small. Thus, I have deleted several sections from the doc. However, please feel free to ask if more details are needed.
[Rendered doc](https://github.com/umanwizard/materialize-1/blob/since_granularity/doc/developer/design/20230322_metrics_since_granularity.md)

[design] "Since granularity"

---

misc/python/materialize/mzcompose/services.py

@guswynn pointed out that this is a fruitful way to test #18307!
-

Enable some small-batch optimization in tests

---

misc/python/materialize/feature_benchmark/benchmark.py
test/feature-benchmark/mzcompose.py
test/feature-benchmark/scenarios_subscribe.py

`SUBSCRIBE` was not being exercised in the feature benchmark.

feature-benchmark: Add scenarios around SUBSCRIBE

---

test/sqlsmith/mzcompose.py

Stil going OoM, for example in https://buildkite.com/materialize/nightlies/builds/2078
-

sqlsmith ci:Reduce number of servers for explain run

---

ci/nightly/pipeline.yml
misc/python/materialize/checks/identifiers.py
misc/python/materialize/checks/scenarios_upgrade.py

- X-2 -> HEAD (without going through X-1)
- X-4 -> X-3 -> X-2 -> X-1 -> HEAD
Additional testing prompted by #18418

upgrade: Add additional upgrade scenarios to Nightly

---

Cargo.lock

Bump timely to include https://github.com/TimelyDataflow/timely-dataflow/pull/507

Bump timely

---

misc/python/materialize/checks/owners.py

Depends on #18456
Part of #17983
-

platform checks: Test object ownership privilege

---

ci/test/check-merge-with-target.sh
ci/test/pipeline.template.yml

This fixes https://github.com/MaterializeInc/materialize/issues/18320.
-

ci: Run cargo check on merge with target branch

---

README.md
doc/user/content/_index.md
doc/user/content/get-started.md
doc/user/layouts/partials/header.html

This is a small wording change to transition from "Early Access" to "Access" and "wait list" to "immediate access"

doc/user: Update access wording

---

src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs

Previously, every one second the Coordinator advanced all tables to the current time. Additionally, all writes, to user or system tables, would advance all tables to the current time. Certain system tables that track metrics were being updated at a rate of once a second. This was causing us to advance tables at a rate much faster than once per second, once from the timer and once from the system table writes.
This commit updates the Coordinator such that a write, which advances all tables, will reset the timer used to advance all tables. This will hopefully cut down on the total amount of persist calls.
-

adapter: Reduce amount of table advancements

---

Cargo.toml

https://doc.rust-lang.org/std/pin/macro.pin.html is extremely useful

bump to rust 1.68

---

ci/test/check-merge-with-target.sh
ci/test/pipeline.template.yml

ci: Run "Merge skew cargo check" with target dependencies

---

src/compute/src/render/reduce.rs

This change prevents accidentally losing error streams by collecting them and concatenating all at once. A side effect is that we also have less operators in the graph.
-

Collect errors before concatenating streams

---

doc/developer/design/20220214_create_cluster.md
doc/user/content/sql/create-cluster-replica.md
doc/user/content/sql/create-cluster.md

https://github.com/MaterializeInc/materialize/issues/18584
Adding a few notes on the availability zone assignments for clusters replicas
-

docs: add note about cluster AZ assignment

---

src/storage/src/source/postgres.rs

As noted in #18520 and experienced in [#18601](https://github.com/MaterializeInc/materialize/issues/18601), if you snapshot a source from a temporary replication slot, entering `produce_replication` for rewinding/deduplicating incurs a minimum 30-second delay if the WAL isn't currently being written to. This is painful because you often cannot serve any reads until that process is complete once you enter it.
However, we can avoid entering `produce_replication` unless it's necessary by peeking into the WAL.
This PR fixes a recognized bug. Fixes #18520 
-

pg sources: avoid "rewinding" if possible

---

ci/nightly/pipeline.yml
test/sqlsmith/mzcompose.py

Running OoM on each nightly, see https://github.com/MaterializeInc/materialize/issues/2392
-

ci: Reduce number of joins in SQLsmith

---

doc/developer/scratch.md

This is in line with what `bin/scratch mine` shows in column `Delete After`.

docs: Update scratch lifetime

---

doc/user/content/integrations/http-api.md
doc/user/content/releases/v0.50.md
doc/user/content/releases/v0.51.md
doc/user/content/sql/create-cluster-replica.md
doc/user/content/sql/create-cluster.md
doc/user/content/sql/subscribe.md

v0.50.0 release notes

---

doc/developer/platform/formalism.md

Some information in `formalism.md` relating to the adapter has become stale. This PR updates the document to contain accurate information.
Updates docs.
-

doc: Update adapter parts of formalism

---

src/adapter/src/rbac.rs

This commit is pure code movement to make rbac.rs more organized. Specifically it moves functions around so that similar functions are grouped together. It also abstracts some logic into functions and removes an unnecessary wrapper struct.
-

adapter: Reorganize rbac.rs

---

doc/developer/guide.md
doc/user/content/integrations/cdc-mysql.md

docs: Minor fixes in commands

---

.github/CODEOWNERS
src/rocksdb/src/lib.rs
src/rocksdb/tests/basic.rs

fix mz-rocksdb merge conflicts

---

test/sqllogictest/range.slt

Just a few further range slt checks I created when I was working on the platform checks for https://github.com/MaterializeInc/materialize/pull/18709 and had identified https://github.com/MaterializeInc/materialize/issues/18726.

ci: Add further range tests

---

src/testdrive/src/action/kafka/add_partitions.rs

testdrive: fix error message

---

src/storage-client/src/controller.rs

storage: assert on update_read_capabilities

---

misc/python/materialize/checks/all_checks.py
misc/python/materialize/checks/multiple_partitions.py
src/testdrive/src/action/kafka/add_partitions.rs

This fixes https://github.com/MaterializeInc/materialize/issues/18297.

ci: add multiple_partitions platform check

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.53.0-dev

---

test/sqllogictest/role_create.slt

Part of https://github.com/MaterializeInc/materialize/issues/17983
-

tests: Add role_create.slt

---

src/environmentd/tests/sql.rs

Two main improvements:
1. Make the test deterministic, by hardcoding a "now" timestamp rather than using the current system time.
2. Wait until `since` becomes nonzero.
I _hope_, but am not certain, that the latter of these will fıx https://github.com/MaterializeInc/materialize/issues/18934.
Maybe #18934
- N/A

Improve `test_utilization_hold`.

---

src/storage/src/source/source_reader_pipeline.rs

only write health statuses from the active worker

---

doc/user/content/overview/_index.md

Refresh the ["What is Materialize?" overview page](https://materialize.com/docs/overview/) to highlight
our core features.
We plan to add a visual soon, and may revisit adding brief use case summaries.
Part of: https://github.com/MaterializeInc/materialize/issues/18367

doc/user: update What is Materialize?

---

doc/user/content/sql/create-source/_index.md

docs: Add namespace info to create source

---

doc/user/content/integrations/_index.md
doc/user/content/integrations/sql-clients.md
doc/user/content/overview/_index.md

This is a small change to the What is Materialize? page to say that MZ can work with many Postgres-compatible tools, not most.
Fixes: #19035
Need to follow-up with a refresh of the full [tools and integrations page](https://materialize.com/docs/integrations/#database-management-tools). 
-

Be more precise about third-party tools support

---

src/stash/build.rs

This fixes a bug that was causing every compilation to rebuild the mz-stash crate (and therefore all its dependencies), even if nothing had changed since the last compilation. See comment within for details.
Fix #19069.
- n/a

stash: don't bust compilation cache on every compile

---

Cargo.lock
src/postgres-util/Cargo.toml
src/postgres-util/src/lib.rs
src/postgres-util/src/privileges.rs
src/postgres-util/src/tunnel.rs
src/sql/src/pure.rs
test/pg-cdc/privileges.td

This PR fixes a recognized bug. Fixes #19030
-

sql: error if lacking SELECT privileges on PG source tables

---

doc/user/content/get-started.md

This both helps us introduce the notion that objects other than clusters and replicas are namespaced
and helps us get insight into product usage based
on the guide.
-

doc/user: Add schema creation step to getting started guide

---

doc/user/content/sql/functions/cast.md
doc/user/content/sql/types/mz_aclitem.md

docs: Add docs for mz_aclitem

---

src/persist-client/src/batch.rs
src/persist-types/src/stats.rs

Given a budget, we do a couple rounds of making stats smaller, until it fits within a given budget. These are applied in order of how lossy they are (i.e. how likely in practice to increase the false positive rate).
Touches #12684 
-

persist: implement stats trimming

---

src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/sql/src/session/vars.rs
test/testdrive/session.td

Reverts MaterializeInc/materialize#19091 b/c of #19109

Revert "adapter: Limit number of concurrent connections"

---

doc/user/content/_index.md
doc/user/content/get-started.md
doc/user/layouts/partials/header.html

Use docs-specific tracking URL.
-

doc/user: Update sign up link

---

src/frontegg-client/src/client.rs

Turn the [auth() function](https://github.com/MaterializeInc/materialize/blob/71b612aba0dd19da0cc19a9d8fb3694a70abd8c1/src/frontegg-client/src/client.rs#L166) in the Frontegg Client public so other packages can use the client to manage their access token. 
E.g.: In the [`cloud-api` crate.](https://github.com/MaterializeInc/materialize/blob/7ec5abf9bb50bc78a154c2e5600bea4f0e6865c9/src/cloud-api/src/client.rs#LL71C9-L72C24)
-

frontegg-client: turn pub 'fn auth()'

---

test/sqllogictest/privileges_pg.slt

Part of https://github.com/MaterializeInc/materialize/issues/17983
Depends on https://github.com/MaterializeInc/materialize/pull/18980
-

RBAC: Add test privileges_pg.slt

---

src/environmentd/tests/sql.rs

This commit fixes the flaky test test_subscribe_on_dropped_source. Previously, the test would asynchronously start a query that never returns. Then on the main thread the test would wait for the introspection source mz_internal.mz_compute_exports to update to reflect the in-process query. However, under heavy load mz_internal.mz_compute_exports would take an extremely long time to update (maybe never?).
This commit updates the test to use mz_internal.mz_subscriptions instead to determine if there's an in-progress subscribe. As a consequence the test only works with SUBSCRIBE and not SELECT.
Fixes #19202
-

test: Fix flaky dropped source test

---

src/persist-client/src/operators/shard_source.rs

Fixes a problem uncovered via https://github.com/MaterializeInc/materialize/pull/19156
We accidentally regressed and made the eager frontier downgrade happen _after_ resolving the snapshot (which happens in the `subscribe()` call, in an earlier refactoring. And the problem is that that `subscribe()`/`snapshot()` call can take arbitrarily long.
There is more context around this in https://materializeinc.slack.com/archives/C01CFKM1QRF/p1683728275348929 (internal slack). But the gist of it is that `persist_sink` relies on the eager downgrade behaviour and will run into a lifelock when it is not there.
The bug goes sth like this:
- in persist_sink
- the batch description minter will mint an initial batch [s, d] where d is the desired frontier
- the writer operator will only write out data for …

persist: in shard_source, eagerly downgrade to as_of

---

doc/user/content/releases/v0.52.md
doc/user/content/releases/v0.53.md
doc/user/content/releases/v0.54.md
doc/user/content/sql/show.md

(Brief) Release notes for v0.53. 🧘
Skipped:
* https://github.com/MaterializeInc/materialize/pull/18822
* https://github.com/MaterializeInc/materialize/pull/18975
* https://github.com/MaterializeInc/materialize/pull/19041

doc/user: polish v0.53 release notes

---

misc/python/materialize/cli/ci_coverage_pr_report.py

Sorry for the many changes required to get coverage into a good state. https://buildkite.com/materialize/coverage/builds/96 is running to test this.
Because we have to add back lines for unit-test-only-covered, and remove lines for uncovered code, the resulting lines might not be mapped together line by line again as they were before. See https://buildkite.com/materialize/coverage/builds/93#018804a2-19fc-4696-b11d-7e86383bd1f3 for an example of how this can go wrong, surrounding the line:
> debug!("sending pubsub message: {:?}", message);
Since the surrounding lines have a mix of being uncovered and unit-test-only-covered the diff algorithm puts those blocks together differently, and we end up with a hard-to-read coverage report. For now I split this into two separate reports, one for …

coverage: Don't print out unit-test-only and uncovered in one report

---

src/buf.yaml

Prerequisite for pull request https://github.com/MaterializeInc/materialize/pull/19157#discussion_r1188821306 of https://github.com/MaterializeInc/materialize/issues/17882.
* This is necessary for https://github.com/MaterializeInc/materialize/pull/19157 and needs to be merged before that.

ci: protobuf linting (1/2): add buf config

---

src/storage/src/render/upsert.rs

Correcting the logic for diff_record, it should solely be based on whether a previous record existed or not.
-

Correcting the logic for diff_record

---

src/storage-client/src/source/persist_source.rs

Fix a JSON-stats bug introduced in a PR refactoring.
Previously-unknown bug! Introduced in #19112 - I failed to test what I thought was a safe refactoring.
-

[persist] Use the hacked version of the relationdesc to determine types

---

test/cluster/mzcompose.py

We are not 100% sure yet if the previous flakes were ok under strict serializable transaction isolation level, so there is still something left to be investigated.
Fixes #19243
-

cluster test: Make test-mv-source-sink deterministic

---

doc/user/data/sql_funcs.yml

`asin` is already defined above and the description applies to `atan`.

docs: Fix atan function entry

---

test/cloudtest/test_crash.py
test/cloudtest/test_secrets.py

When using kubectl to kill the entrypoint, kubectl may exit with a non-zero exit code because the container may exit while the kubectl command is still in progress.
cloudtest was failing sporadically in CI

cloudtest: Fortify invocations of kill via kubectl

---

ci/builder/requirements.txt
misc/python/materialize/scratch.py

](https://github.com/MaterializeInc/materialize/security/dependabot/36)
Bumping the cryptography module version by 1 to address openssl issue.

Cryptography

---

misc/python/materialize/mzcompose/services.py
test/kafka-matrix/mzcompose.py
test/pg-cdc/mzcompose.py
test/pg-cdc/pg-cdc.td
test/pg-cdc/subsource-resolution-duplicates.td
test/platform-checks/mzcompose.py
test/source-sink-errors/mzcompose.py
test/ssh-connection/kafka-source.td
test/ssh-connection/mzcompose.py
test/upgrade-matrix/mzcompose.py
test/upgrade/check-from-v0.27.0-kafka-sink.td
test/upgrade/check-from-v0.27.0-kafka-source.td
test/upgrade/mzcompose.py

- Use 4-1 storage cluster for mzcompose-based workflows
- Use a 4-4 storage cluster for Zippy
-

ci: Use SIZE '4-X' cluster for sources

---

doc/user/content/sql/alter-owner.md
doc/user/content/sql/alter-role.md
doc/user/content/sql/create-role.md
doc/user/content/sql/drop-role.md
doc/user/content/sql/grant-privilege.md
doc/user/content/sql/grant-role.md
doc/user/content/sql/revoke-privilege.md
doc/user/content/sql/revoke-role.md

doc: Update RBAC warning

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.56.0-dev

---

test/sqlancer/mzcompose.py

Fixes #19380
This is a bit awkward because the normal interface doesn't allow printing out the logs while also storing them.
-

CI: Immediate output from SQLancer

---

test/limits/mzcompose.py

Will probably not be fixed quickly, see https://github.com/MaterializeInc/materialize/issues/19327
-

ci: product-limits WhereConditionAnd with fewer conditions

---

src/persist-client/src/cache.rs
src/persist-client/src/internal/metrics.rs

Record whether the process was already up-to-date, or if we got an out-of-order message
-

persist: split out diff unsuccessfully applied metric

---

doc/user/content/releases/v0.55.md
doc/user/content/releases/v0.56.md
doc/user/content/sql/alter-owner.md
doc/user/content/sql/drop-connection.md
doc/user/content/sql/drop-database.md
doc/user/content/sql/drop-owned.md
doc/user/content/sql/drop-role.md
doc/user/content/sql/drop-schema.md
doc/user/content/sql/drop-sink.md
doc/user/content/sql/drop-source.md
doc/user/content/sql/drop-table.md
doc/user/content/sql/drop-user.md
doc/user/content/sql/drop-view.md
doc/user/content/sql/namespaces.md
doc/user/content/sql/reassign-owned.md
doc/user/content/sql/set.md
doc/user/content/sql/show-columns.md
doc/user/content/sql/show-databases.md
doc/user/content/sql/show-objects.md
doc/user/content/sql/show-schemas.md
doc/user/content/sql/show-sinks.md
doc/user/content/sql/show-sources.md
doc/user/content/sql/show-tables.md
doc/user/content/sql/show-types.md
doc/user/content/sql/show-views.md
doc/user/content/sql/system-catalog/mz_catalog.md

(Light) Release notes for v0.55. 🎐 
Skipped:
* https://github.com/MaterializeInc/materialize/pull/19364
* https://github.com/MaterializeInc/materialize/pull/19300
Ended up patching a bunch of SQL command pages that had mentions to "Materialize instances", which is stale terminology, and other minor issues. TBD if we want to use "Materialize region" consistently; standardizing on just "Materialize" for now. In general, there's some inconsistency in how these pages are organized. **cc** @MaterializeInc/docs.

doc/user: polish release notes for v0.55

---

ci/plugins/cloudtest/hooks/post-command
ci/plugins/mzcompose/hooks/post-command
ci/test/cargo-test/mzcompose.py
ci/test/pipeline.template.yml
misc/python/materialize/mzcompose/__init__.py

ci: Make cargo-test faster

---

src/adapter/src/config/frontend.rs

This was superseded by `last_cse_time_seconds` in #19201 and is now obsolete.
This was a known follow up from #19201 which was blocked on first deploying #19201 and updating our dashboards.
N/A

adapter: remove obsolete `last_known_time_seconds` metric

---

ci/test/cargo-test/mzcompose.py

Seems to cause sporadic problems
Fixes: #19520
-

cargo-test: Don't run with more CPU cores

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

https://github.com/MaterializeInc/cloud/issues/6484

bump versions to 0.57.0-dev

---

Cargo.lock
Cargo.toml
src/adapter/Cargo.toml
src/environmentd/Cargo.toml
src/orchestrator-tracing/Cargo.toml
src/ore/Cargo.toml

Details in commit messages.
* Regular dependency bump PR

deps: regular bump

---

misc/python/materialize/cli/ci_logged_errors_detect.py

We are still below the per-page limit of 100, but will probably go over it at some point soon
-

ci-logged-errors-detect: Handle pagination of Github API

---

doc/user/content/releases/v0.56.md
doc/user/content/releases/v0.57.md
doc/user/data/sql_funcs.yml

(Extra light) Release notes for v0.56. 🌬️

doc/user: polish release notes for v0.56

---

test/pg-cdc/pg-cdc.td
test/testdrive/kafka-progress.td
test/testdrive/load-generator.td
test/testdrive/testscript_source.td

tests: Expect 0 timestamp in EXPLAIN TIMESTAMP

---

misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py

Related: https://github.com/MaterializeInc/materialize/pull/19656

Output consistency tests: Fix aggregation function definitions

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

bump to version v0.58.0-dev

---

doc/user/assets/sass/_content.scss

Relates to https://materializeinc.slack.com/archives/CPNFV9CVB/p1684519120762399
| - | - |
| ![image](https://github.com/MaterializeInc/materialize/assets/46004116/104df875-2052-4f14-9122-e4e7f685b9be) | ![image](https://github.com/MaterializeInc/materialize/assets/46004116/3bacd842-293d-43f2-8d27-10c2feda4612) |
| ![image](https://github.com/MaterializeInc/materialize/assets/46004116/bfd4708c-c1ae-4d75-a76b-5065b3b6f5a4) | ![image](https://github.com/MaterializeInc/materialize/assets/46004116/6c9fce82-2c2b-477e-a161-5aed495ad794) |

fix styling for ul and ol nested withing steps.

---

misc/python/materialize/checks/pg_cdc.py

In preparation for https://github.com/MaterializeInc/materialize/issues/19715, assuming we want to keep the old PgCdc.
-

platform-checks: Add PgCdcNoWait (disabled for now)

---

doc/user/content/ingest-data/postgres-amazon-rds.md

Forgot to include a final forward slack in the alias in https://github.com/MaterializeInc/materialize/pull/19768. Adding that slash here.
-

Fix redirect for postgres direct page

---

Cargo.lock
src/storage/Cargo.toml
src/storage/src/render/mod.rs
src/storage/src/source/mod.rs
src/storage/src/source/postgres.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/reclock.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs
src/timely-util/src/builder_async.rs
src/timely-util/src/lib.rs
src/timely-util/src/operator.rs
src/timely-util/src/pact.rs
test/pg-cdc/pg-cdc.td

Previously reverted due to hitting the correctness issue fixed by https://github.com/MaterializeInc/materialize/pull/19765
-

Revert revert revert revert multi worker pg

---

doc/user/content/ingest-data/amazon-msk.md
doc/user/content/ingest-data/cdc-mysql.md
doc/user/content/ingest-data/cdc-postgres-kafka-debezium.md
doc/user/content/ingest-data/confluent-cloud.md
doc/user/content/ingest-data/debezium.md
doc/user/content/ingest-data/network-security/privatelink.md
doc/user/content/ingest-data/network-security/ssh-tunnel.md
doc/user/content/ingest-data/network-security/static-ips.md
doc/user/content/ingest-data/redpanda-cloud.md
doc/user/content/ingest-data/redpanda.md
doc/user/content/ingest-data/upstash-kafka.md

Neglected to put these in place in https://github.com/MaterializeInc/materialize/pull/19453, and it caused some 404s in the Console: https://github.com/MaterializeInc/console/pull/322.
-

doc: Add missing redirects

---

doc/user/layouts/partials/head.html

As part of migrating to GA4 before July 1, this PR updates the GA tag.
Fixes: #19750
-

doc: Update doc analytics tag

---

bin/ci-builder
ci/builder/Dockerfile
ci/builder/README.md
ci/plugins/cloudtest/README.md
ci/plugins/cloudtest/hooks/command
ci/plugins/cloudtest/hooks/post-command

This resolves https://github.com/MaterializeInc/materialize/issues/16322.

ci: introduce kail to collect cloudtest logs

---

src/stash/src/postgres.rs

We would like to both error on bad URLs during stash startup, and also allow the server to be down for a bit. Use a 30s retry loop to balance these goals.
Fixes #19814
- n/a

stash: retry initial stash connection a bit

---

src/sql/src/kafka_util.rs
src/storage-client/src/types/connections.rs

While waiting for a fix for #18491, we added a retry loop to connection validation for Kafka connections involving an SSH tunnel. Now that the issue is fixed, remove the retry loop.
We've observed that the retry loop can make connection errors worse. Some SSH servers are configured to reject repeated attempts to connect with a "connection refused" error; since the retry loop returns only the last error, this can result in a more accurate "permission denied" error becoming a "connection refused" error by the time it is reported to the user.
- n/a (too small to be worth it)

sql: improve errors when creating an SSH-tunneled kafka connection

---

src/persist-client/src/internal/state_diff.rs

Reverts MaterializeInc/materialize#19833
This 19833 has a bug in how `hostname` is updated that will break across version upgrades. We'll fix it for-real next week, in the mean time, just revert the change.

Revert "persist: fix bug where apply_diff wasn't updating some State fields"

---

src/persist-client/src/critical.rs
src/persist-client/src/stats.rs
src/storage-client/src/controller.rs
src/storage-client/src/controller/persist_handles.rs

These will be used by the optimizer's cost model, see #19260.
Initially marking as draft while we figure out how to avoid registering a handle each time this is called.
-

storage: expose aggregate statistics about shards in the controller

---

Cargo.lock

picks up some merged updates: https://github.com/MaterializeInc/timely-dataflow/commits/master

update timely git dep

---

misc/python/materialize/output_consistency/data_type/data_type_category.py
misc/python/materialize/output_consistency/data_value/data_value.py
misc/python/materialize/output_consistency/generators/expression_generator.py
misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/params/text_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/array_return_spec.py
misc/python/materialize/output_consistency/input_data/return_specs/text_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/text_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/text_values_provider.py

This implements https://github.com/MaterializeInc/materialize/issues/19669 of https://github.com/MaterializeInc/materialize/issues/18858.
* commit-wise

Output consistency tests: support text type

---

src/storage/src/sink/kafka.rs

In get_latest_ts, we rely on finding a PartitionEOF error from rdkafka to know when to stop looking for our own writes in the progress topic. However, rdkafka does not signal this error reliably, especially when the topic is also receiving writes from other sinks. (And it's an inherently best-effort mechanism, so it's probably not best to rely on in any case.)
Instead of waiting to catch up to the end, we instead try and catch up to whatever the high watermark was when we started up. Since we fence out old versions of the producer before fetching offsets, any previously-published timestamps should be ahead of that high watermark, so this should not impact correctness.
Mostly #16778.
Since that error will appear whenever the sink is slow for any reason, it's possible that we'll still see …

[sinks] Early exit when fetching progress timestamps in the Kafka sink

---

doc/user/content/ingest-data/cdc-postgres-kafka-debezium.md
doc/user/content/integrations/_index.md
doc/user/content/sql/create-source/postgres.md
doc/user/layouts/shortcodes/postgres-direct/before-you-begin.html

The min Postgres version in our Postgres/Debezium guide is out-of-date. The PR fixes that. It also make the minimum requirement language more explicit in other guides.
-

doc: Fix minimum Postgres version requirement

---

doc/user/assets/sass/_content.scss

| - | - |
| ![image](https://github.com/MaterializeInc/materialize/assets/46004116/b5398fe4-074f-4363-b0cb-fa2ba7cdebc9) | ![image](https://github.com/MaterializeInc/materialize/assets/46004116/129cc460-08e0-4153-be12-f283f0c8b2de) |
Addresses https://materializeinc.slack.com/archives/CPNFV9CVB/p1686756048874069

make the padding of the ol consistent with the ul.

---

test/sqlsmith/mzcompose.py

sqlsmith: Add expected error

---

src/sql-parser/src/parser.rs

sql: remove errant println

---

doc/developer/design/20230519_statement_logging.md

[Rendered doc](https://github.com/umanwizard/materialize-1/blob/statement_logging_doc/doc/developer/design/20230519_statement_logging.md)

Add lightweight design doc for statement logging

---

src/storage-client/src/types/sources.rs

During a refactor, I inadvertently dropped an equality comparison when determining alter compatibility. Add that back in, as well as improving logging and documentation.
This PR fixes a recognized bug. Fixes #19987
-

storage: improve alter_compatible detection

---

src/persist-client/src/internal/gc.rs

While I haven't seen any issues with it yet, an assertion I added in the incremental GC PR has been nagging me. I think it's too strict in that it may fail even if the latest GC run did everything correctly. Bubbling up an `error!` feels more accurate to me -- it's something we want to look in to, not something we ever want to see in the steady state, but is not something that should halt the process / indicate that GC failed.
-

persist: relax assertion in gc that may be triggered by prior bad state

---

doc/user/content/sql/types/mz_aclitem.md

doc: Update mz_aclitem for system privileges

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.59.0-dev

---

src/adapter/src/catalog/builtin.rs
src/sql/src/func.rs

We can now start asserting that function return types match postgres or have documented exclusions. Function arguments still have many mismatches.
- n/a

sql: correct some function return types

---

src/stash/src/upgrade/v22_to_v23.rs

A previous commit added a migration to grant the mz_introspection role USAGE privileges on all existing clusters. It set the grantor of this privilege to mz_system. This was incorrect, the grantor should have been, the owner of the cluster. This commit fixes the migration to be the owner of the cluster.

adapter: Fix mz_introspection cluster migration

---

doc/user/content/sql/create-source/kafka.md
doc/user/content/sql/types/bytea.md

Clarify usage of `convert_from` in the `bytea` docs

Clarify usage of `convert_from` in the `bytea` docs

---

src/adapter/src/rbac.rs

This commit refactors the RBAC privilege check code to use the type `SystemObjectId` instead of `ObjectId`. This has no effect on the actual logic, but is needed in preparation for checking system privileges. This is a separate commit because it's such a large amount of lines changed that it would distract from other changes if it was included in another commit.
Works towards resolving #19997
* Hiding white-space helps when viewing.

adapter: Refactor privilege checks for sys privs

---

doc/user/content/releases/_index.md

Minor improvements to how we describe our maintenance windows and what happens after the window, based on input from Nikhil.
Fixes: #18339
-

doc: Revise maintenance window language

---

src/storage/src/decode/mod.rs
src/storage/src/render/sources.rs
src/storage/src/render/upsert.rs
src/storage/src/source/source_reader_pipeline.rs

This PR wires up the healthcheck infrastructure with the decoding stage which allows us to convert some transient errors that were previously leading to panics into user reported errors and graceful restarts.
Fixes #19252
Hide whitespace because decode.rs gained an indentation level
-

storage: wire up healthchecks during decoding
