src/sql/src/func.rs

This commit fixes the schema for Materialize specific access inquiry functions, such as `has_secret_privileges`. They were previously in the pg_catalog schema, this commit moves them to the mz_catalog schema.
- Move Materialize specific access inquiry functions to the `mz_catalog` schema.

sql: Fix schema for access inquiry functions

---

src/storage-client/src/controller/persist_handles.rs

Shard finalization rarely applies today because a dropped shard won't reach an empty since due to `maybe_compare_and_downgrade_since` rate limiting. This PR special cases the empty frontier to always go through.
This doesn't completely solve issues with finalization, e.g. a process could crash between adding a shard to the finalization WAL and `compare_and_downgrade_since` completing, but it'll help as a bandaid until we roll out a new way of finalizing shards.
-

storage: always let SinceHandle downgrade since to empty

---

src/environmentd/src/bin/environmentd/main.rs

This will allow for easy version filtering in grafana.
- n/a

environmentd: add version to start time metric

---

src/storage-client/src/controller.rs

When creating new subsources, we need to install read holds on the remap collection. The easiest and best way of doing that is to simply set the since of its shard to the remap shard's since and then installing the read hold. This approach generalizes to all new collections.
However, I would like to propose that we have a more permissible migration case for the next version of Materialize and tighten up the asserts in the next-next version. Letting this code run on all ingestions will work as a migration without needing to write any special migration code to accomplish the same thing. This code did not previously downgrade the since of the shard, so I am not certain if it some collections had an in-memory since that was advanced far enough, but persist was never notified (so on reboot, …

storage: advance subsource sinces

---

src/adapter/src/catalog/storage.rs
src/testdrive/src/action/sql.rs

test: Improve testdrive error message

---

doc/user/content/releases/_index.md

To reduce customer confusion, we're going to switch maintenance windows to follow local time zone rules for daylight savings time. "Local" here means the time zone that's most representative for the region, as determined by location of the region's data center.
* This PR clarifies documentation.
- n/a

doc/user: clarify time zones for maintenance window

---

src/mz/src/api.rs

Keeps failing in nightly's cloud canary deploy
See https://materializeinc.slack.com/archives/CL68GT3AT/p1688051730829949
-

mz: Retry disable command

---

src/persist-client/src/internal/state_versions.rs

Relaxes our referenced blob validator. Rather than asserting that hollowbatches are 1:1 between incremental updates and in-mem spine (which they aren't designed to be in Description bounds, and may not even be in terms of count), we do a quick validation that the lower/upper match and that since hasn't somehow advanced
Fixes https://github.com/MaterializeInc/materialize/issues/20009
-

persist: relax referenced blob validator assertions for hollowbatches

---

doc/user/content/releases/_index.md

* Further improve the maintenance window docs.
- n/a

doc/user: more explicitly note DST rules for maintenance windows

---

test/limits/mzcompose.py

- use more materialized views and indexes for "wide" resultsets, rather than just one-off SELECTs
- test long argument lists for certain interesting functions
Relates to MaterializeInc/cloud#6763
When examining customer queries, I noticed that certain dimensions of complexity are not covered well by the limits test.

limits test: Add more scenarios based on customer workloads

---

doc/user/layouts/_default/baseof.html

Addresses https://materializeinc.slack.com/archives/C048HHZ6F3P/p1688071113701789

fix the copy to clipboard functionality on safari.

---

misc/python/materialize/cli/ci_logged_errors_detect.py

```
[2023-07-04T11:51:57Z] Traceback (most recent call last):
[2023-07-04T11:51:57Z]   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[2023-07-04T11:51:57Z]     return _run_code(code, main_globals, None,
[2023-07-04T11:51:57Z]   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[2023-07-04T11:51:57Z]     exec(code, run_globals)
[2023-07-04T11:51:57Z]   File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0d491fcddc7afa569-1/materialize/coverage/misc/python/materialize/cli/ci_logged_errors_detect.py", line 255, in <module>
[2023-07-04T11:51:57Z]     sys.exit(main())
[2023-07-04T11:51:57Z]   File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0d491fcddc7afa569-1/materialize/coverage/misc/python/materialize/cli/ci_logged_errors_detect.py", line 87, …
```

ci: logged-errors-detect: Don't fail on invalid regex

---

misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/any_operation_param.py

Nightly:  https://buildkite.com/materialize/nightlies/builds/2612 ✅

Output consistency tests: Add coalesce and nullif

---

misc/python/materialize/data_ingest/definition.py
misc/python/materialize/data_ingest/executor.py
misc/python/materialize/data_ingest/workload.py
test/data-ingest/mzcompose.py
test/postgres/setup-postgres.sh

Fixes https://github.com/MaterializeInc/materialize/issues/20333
-

data-ingest: Faster ingestion

---

misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py

Widened `NULL` ignore to also ignore more advanced stuff like `WHERE (translate(chr(int4_neg_max), upper(text_empty), split_part(text_val_w_spaces, text_val_1, int4_null)) !~ '.*');` where constant folding takes evaluation shortcuts.
This addresses the issue in https://buildkite.com/materialize/nightlies/builds/2730#01892676-2ca8-4d68-acc1-c9e3a22bdf86.

Output inconsistency test: ignore deviations caused by NULL shortcuts

---

src/persist-client/src/cfg.rs

This knob is on in staging/prod by default, so let's make it the default in code too.
-

persist: default pubsub client connections on

---

misc/python/materialize/data_ingest/executor.py

> UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'materialize.data_ingest.executor.Producer'>: <class 'cimpl.Producer'> is a built-in class
https://buildkite.com/materialize/deploy/builds/10351#01892677-9a4c-4f59-8bf0-1b0c9d495efe
Locally reproduced via `bin/pydoc`. verified in https://buildkite.com/materialize/deploy/builds/10352
-

Fix deploy step failure on data-ingest

---

doc/user/sql-grammar/keywords.txt

#20345 changed the location of the keywords.txt file. This symlink broke.
Whack-a-mole
-

fix(docs): update symlink for keyword list

---

doc/user/content/sql/system-catalog/mz_internal.md

Documents https://github.com/MaterializeInc/materialize/pull/19740
@bkirwi you may also be interested in the basic language I chose to explain offset committing.
docs

doc/user: document consumer groups and kafka offset commit behavior

---

src/adapter/src/catalog/builtin.rs
src/expr/src/scalar/func.rs

This builds on Matt's recent PR that adds `test_smoketest_all_builtins`, which runs all scalar functions with some test inputs. It adds more checks after each run of a scalar function in `test_smoketest_all_builtins`.
Check type inference and nullability inference as follows:
- MIR type inference should be consistent with the type we get from the catalog.
- The result shouldn't be null if nullability inference told us non-null.
- MIR nullability inference should be consistent with `introduces_nulls` and `propagates_nulls`.
The above allows us to remove the `unary_func_introduces_nulls` test, which is superseded by the new parts of `test_smoketest_all_builtins`. Note that this test is better than `unary_func_introduces_nulls` in several ways:
- `unary_func_introduces_nulls` depends on …

Add various checks to `test_smoketest_all_builtins`

---

doc/user/content/releases/v0.59.md
doc/user/content/releases/v0.60.md

Release notes for v0.59. 🔐 
* `ALTER SOURCE...DROP SUBSOURCE` is undocumented.
* #20350 needs review.

doc/user: polish v0.59 release notes

---

misc/python/materialize/output_consistency/execution/query_execution_manager.py
misc/python/materialize/output_consistency/execution/test_summary.py
misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
misc/python/materialize/output_consistency/output/reproduction_code_printer.py
misc/python/materialize/output_consistency/runner/test_runner.py
misc/python/materialize/output_consistency/validation/result_comparator.py
misc/python/materialize/output_consistency/validation/validation_outcome.py

Fixes issue detected in nightly: https://buildkite.com/materialize/nightlies/builds/2740#01892866-1fdc-485b-ae31-b17b263ed716
-

Output consistency tests: extend ignores, fix outcome determination

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.61.0-dev

---

ci/test/pipeline.template.yml

see https://materializeinc.slack.com/archives/CTESPM7FU/p1688765671345719

fix aarch64 build

---

doc/developer/reference/adapter/coord_interface.md

This documents some of the control flow and assupmtions between pgwire and the coordinator that I personally found non-obvious, and so hopefully it can help someone else.
The biggest deficiency of this text is that it does not discuss transactions at all. I did not feel like my knowledge of those was sufficient for documenting them properly, but it would be great if someone else added that information in the future.

Document coordinator interface.

---

doc/user/content/transform-data/patterns/rules-engine.md

Slight updates to doc for readability

docs/user: slight update to rules execution pattern

---

ci/slt/pipeline.yml
ci/slt/slt.sh
ci/test/pipeline.template.yml
misc/python/materialize/mzcompose/services.py
src/sqllogictest/src/bin/sqllogictest.rs
src/sqllogictest/src/runner.rs
test/sqllogictest/alter.slt
test/sqllogictest/cluster.slt
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/github-13857.slt
test/sqllogictest/introspection/unstable.slt
test/sqllogictest/mzcompose.py
test/sqllogictest/system-cluster.slt
test/sqllogictest/transform/predicate_pushdown.slt
test/sqllogictest/unstable.slt

SLT: Set MZ_SYSTEM_PARAMETER_DEFAULT

---

misc/python/materialize/data_ingest/executor.py
misc/python/materialize/data_ingest/transaction_def.py
misc/python/materialize/data_ingest/workload.py
test/data-ingest/mzcompose.py

Part of https://github.com/MaterializeInc/materialize/issues/20340
-

data-ingest: Implement simple RestartMz disruptions

---

ci/nightly/pipeline.yml

parallel-workload: Disable cancel test again

---

src/persist-client/src/internal/state_diff.rs

We're seeing a steady stream of these hostname mismatch errors each hour from storage usage collection. My suspicion is that it's the same set of shards each time, maybe older ones that don't otherwise get read. It's not super pressing to fix, so add some more info to the error message to help debugging it on the next release.
-

persist: wire through more debug information when hostname mismatches

---

test/sqlsmith/mzcompose.py

https://github.com/def-/sqlsmith/commit/1d793c7d84ba4b006a6f776354cbe859b4b7191f
-

SQLsmith: table functions are fixed

---

ci/test/slt-fast.sh

Remove empty select_distinct.slt

---

test/cluster/mzcompose.py

Fails for now as the issue is not fixed. Feel free to add this change when fixing the issue in #20299.
Part of #20299
-

Add test for clusterd process death detection

---

test/testdrive/kafka-avro-upsert-sinks.td
test/testdrive/materializations.td
test/testdrive/monotonic.td
test/testdrive/mz-arrangement-sharing.td
test/testdrive/top-1-monotonic.td
test/testdrive/top-k-monotonic.td

Seen in nightly: https://buildkite.com/materialize/nightlies/builds/2847#0189610b-9990-4286-8f55-43a0afd3c2b9
Comes from https://github.com/MaterializeInc/materialize/pull/20180
Will wait for nightly before submitting: https://buildkite.com/materialize/nightlies/builds/2855
-

testdrive: Fix errors with mz_arrangement_sharing

---

src/environmentd/src/http/webhook.rs
src/environmentd/tests/server.rs

Fixes: #20224
After chatting on [Slack](https://materializeinc.slack.com/archives/C02FWJ94HME/p1689348808763219) we've decided to further punt on how to handle headers that contain duplicate values. For now we're going to return a 401 and we can come back to this in the future and relax the restriction if necessary.
- Returns 401s if request headers for webhook appending has duplicate header names.

webhooks: 401 on duplicate headers

---

doc/user/content/get-started/arrangements.md
doc/user/content/get-started/quickstart.md
doc/user/content/quickstarts/streaming-analytics.md

docs: Fix some typos

---

ci/test/mkpipeline.py

Relates to #20583
Emergency hotfix releases should be given priority in the CI.
@def- A lot of `analyze` steps had elevated `priority: 1` . Do you recall why was that?
@benesch if you can edit the main Buildkite config to set the priority of the `mkpipeline.py` step to 100, this will make sure that the prioritization can actually kick in when the CI is running at capacity
@benesch should I also apply a trick to increase the prioritization of Nightly against release branches? There is no one-liner to change the prioritization of the entire pipeline, so I will need to figure something out.
-

ci: Prioritize release and main branches higher

---

doc/user/content/sql/functions/jsonb_agg.md
doc/user/content/sql/functions/jsonb_object_agg.md
doc/user/content/sql/types/jsonb.md
doc/user/data/sql_funcs.yml

closes #20258
Improve examples to various jsonb function docs and include jsonb aggregation functions under the jsonb type doc.

docs: improve jsonb function examples

---

misc/python/materialize/output_consistency/execution/evaluation_strategy.py
misc/python/materialize/output_consistency/expression/expression_with_args.py
misc/python/materialize/output_consistency/generators/query_generator.py
misc/python/materialize/output_consistency/query/query_template.py

Fixes an issue discovered in https://buildkite.com/materialize/nightlies/builds/2877#0189697f-e733-4aad-8934-a4db7b2061ce.

output consistency tests: fix storage layout handling

---

src/mz/src/configuration.rs

Little tweak to make the CLI work for the new `console` domain in staging environments.
[Discussion](https://github.com/MaterializeInc/materialize/pull/20609#discussion_r1265634353)
-

Fix: Tweak web login url

---

src/adapter/src/coord/sequencer/inner.rs

Looks like there might have been a merge conflict that made its way to main. 
-

fix merge conflict that made it to main

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/ssh-util/src/tunnel.rs
src/storage-client/src/types/connections.rs
src/storage-client/src/types/connections/aws.rs
test/ssh-connection/mzcompose.py
test/ssh-connection/setup.td
test/ssh-connection/validate-failures.td
test/ssh-connection/validate-success.td

Adds the ability to validate SSH connections. This is a known desirable feature.
Fixes #18248, Part of #20107
-

connection validation for SSH

---

doc/developer/testdrive.md
misc/python/materialize/checks/debezium.py
src/testdrive/src/action/http.rs

This fixes https://github.com/MaterializeInc/materialize/issues/20628.

tests: stabilize Postgres restart source with Debezium

---

src/persist-client/src/internal/machine.rs

Moves our background heartbeat tasks to the isolated runtime, so they should still be schedulable even if the main threads are pegged.
-

persist: move handle heartbeat tasks to isolated runtime

---

src/repr/src/adt/mz_acl_item.rs

Previously, mz_aclitem parsing allowing swapping '/' and '='
characters. This commit fixes that.
- Fixes parsing of `mz_aclitem` types.

sql: Fix parsing of mz_aclitem

---

src/storage/src/source/generator/auction.rs

Emit auctions before bids. This causes queries like:
```
subscribe (select count(distinct auctions.id), count(distinct bids.auction_id) from auctions, bids)
```
to never increment the second column before the first.
This will cause problems with any existing auction sources because the output order has changed, so there will be 1 or 2 auctions and their bids that appear twice or 0 times.
- Ensure the `AUCTION` load generator sources always emits auctions before bids. This may require dropping and recreating any such load generators to maintain consistent data.

storage: ensure auctions integrity

---

src/adapter/src/explain/optimizer_trace.rs

Currently, our `EXPLAIN OPTIMIZER TRACE` logic will emit the fast path plan for any stage that contains a `DataflowDescription<T>` instead of the plan associated with that stage.
The purpose of this behavior is to emit fast path plans when people request either `EXPLAIN FOR (OPTIMZIED|PHYSICAL) PLAN`. However, this behavior is confusing when looking at  `EXPLAIN OPTIMZIER TRACE` results.
This commit changes the behavior so now the `fast_path_plan` is emitted only for `TraceEntry<T>` instances which correspond the `OPTIMIZED` or `PHYSICAL` stages.
Fixes #19995.
See the complementing comment in #19995 for context.
-

explain: force fast path only in `(OPTIMIZED|PHYSICAL) PLAN`

---

src/cloud-api/src/client/region.rs
src/mz/src/api.rs

We are going to change the response type from a 404 on an empty region to a 204; this ensures that the CLI and internal API library can handle it!
Forward compatibility with Cloud API changes
Not 100% sure what the user-facing behavior of `ensure!()` is :smile:
- None -- user-facing behavior should be approximately the same

mz: Correctly handle 204 responses from the cloud API

---

src/storage/src/render/upsert/types.rs

From https://materializeinc.slack.com/archives/C051STBA0TC/p1690329576994699
> we only update envelope counts and sizes at the end of merging, which i think is wrong, as we cant watch progress
Updating the stats continuously instead of all at once at the end so that we can see a more gradual progress during rehydration.
-

Updating the envelope counts with every write while merging

---

src/storage/src/render/sources.rs

No idea how clippy doesnt notice these....

storage: remove some dbg lines clippy missed

---

doc/user/content/integrations/_index.md
doc/user/content/integrations/golang.md
doc/user/content/integrations/java-jdbc.md
doc/user/content/integrations/node-js.md
doc/user/content/integrations/php.md
doc/user/content/integrations/python.md
doc/user/content/integrations/ruby.md
doc/user/content/integrations/rust.md
doc/user/content/sql/subscribe.md

As suggested by @chuck-alt-delete [here](https://materializeinc.slack.com/archives/CPNFV9CVB/p1689963971373969), adding a Rust integrations guide.
The Rust guide uses the exact same structure as all of the other languages and borrows the code examples from the [connection examples repo](https://github.com/MaterializeInc/connection-examples/tree/main)

Doc: Add Rust integrations guide

---

src/storage/src/render/persist_sink.rs

The storage sink implementation can't handle the case where the upper taken from the given write handle is stale... and we've recently made changes that cause this upper to be stale more often.
Mitigation for: https://github.com/MaterializeInc/materialize/issues/20840
IMO we should make the sink robust to stale uppers; the upper can reasonably change at any time, and this will only get more important as we allow multiple source/sink replicas. However, this should make the issue much less likely for now.
-

[storage] Work around a panic in the storage persist sink

---

doc/developer/design/20230613_cloudtest_improvements.md

Part of https://github.com/MaterializeInc/materialize/issues/19626.

cloudtests: update design doc

---

misc/python/materialize/cloudtest/k8s/testdrive.py

This is a cherry-pick of https://github.com/MaterializeInc/materialize/pull/20491/commits/dc6fee8cedc1304bdf3f29b09da524e11c7c3486 from https://github.com/MaterializeInc/materialize/pull/20491.

tests: allow configuring testdrive timeout

---

misc/python/materialize/cloudtest/k8s/environmentd.py
misc/python/materialize/util.py

Needed for https://github.com/MaterializeInc/materialize/issues/19626.

cloudtests: prepare further semver imports for usage in cloud repo

---

misc/python/materialize/cloudtest/app/application.py
misc/python/materialize/cloudtest/app/materialize_application.py

Needed for https://github.com/MaterializeInc/materialize/issues/19626 to incrementally align the involved cloud resources.
Either go commit-wise (and skip 3a1ab489a5f3da59473189f569696d221d8c8781 if https://github.com/MaterializeInc/materialize/pull/20848 is already reviewed) or wait for https://github.com/MaterializeInc/materialize/pull/20848 to be merged.

cloudtests: allow more flexibility in application context

---

doc/user/content/invite-users.md
doc/user/content/manage/dbt.md
doc/user/content/manage/sso.md

Add basic documentation for saml and oidc based sso in Materialize console.

[docs] Add sso documentation

---

Cargo.lock
src/mz/Cargo.toml

This PR updates and releases `mz v0.1.1`. This new release interacts with the new Region API.
-

mz: release v0.1.1

---

src/mz/MAINTAINERS.md

This PR updates the `MAINTAINERS.md` to get the tags detected by the CI process.
-

mz: update the maintainers readme

---

Cargo.lock
bin/bump-version
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.65.0-dev

---

src/prof/src/jemalloc.rs

Discussed in Slack: https://materializeinc.slack.com/archives/CM3MUDY4B/p1691192086566579
When deactivating then reactivating the allocation profiler, allocations from previous runs are not cleared.
Hard to automated-test this, but the issue was quite easily reproducible with manual testing. Activate profiling, create an index on `generate_series(1, 100000000)`, wait for it to hydrate, deactivate profiling, reactivate profiling, generate a flamegraph. The flamegraph will show ~10 GiB worth of stuff. After this change it no longer has that behavior. 
Note: This has no test coverage, which I think is adequate, since this is only turned on in prod when attempting to debug an emergency situation. Manual local testing gives me reasonable confidence …

reset jemalloc profile on deactivate

---

misc/python/materialize/cloudtest/k8s/testdrive.py

cloudtests: allow configuring testdrive

---

src/sqllogictest/src/bin/sqllogictest.rs
src/sqllogictest/src/runner.rs

Fixes #20677, such as it is. 
See the linked issue for context, and the code comment for why this change is considered safe.
-

[testing] Share Persist state across SLT runs

---

doc/user/content/sql/system-catalog/mz_internal.md

Clarify mz_cluster_replica_statuses.reason

---

doc/user/content/ingest-data/postgres-amazon-aurora.md
doc/user/content/ingest-data/postgres-amazon-rds.md
doc/user/content/ingest-data/postgres-azure-db.md
doc/user/content/ingest-data/postgres-google-cloud-sql.md
doc/user/content/ingest-data/postgres-self-hosted.md
doc/user/content/sql/create-source/postgres.md
doc/user/layouts/shortcodes/postgres-direct/postgres-schema-changes.html

Follow-up to #20690.
Moving some content around, and blending the new blurb into the existing blurb.

doc/user: tweaks to PostgreSQL 2.0 documentation

---

doc/user/content/manage/access-control/rbac-terraform-tutorial.md

Including a tutorial (based on [rbac tutorial](https://materialize.com/docs/manage/access-control/rbac-tutorial/)) explaining how to do the same workflow using Terraform grant resources. This will cover three of the four grant resources:
* roles
* object grant
* role membership
It does not currently cover default grant resources as the rbac tutorial does not include that. Can include if we are fine with the tutorials differing.
-

docs: Terraform RBAC Tutorial

---

doc/user/content/sql/system-catalog/mz_catalog.md
test/sqllogictest/autogenerated/mz_catalog.slt

test: Fix mz_internal.slt test

---

misc/python/materialize/cloudtest/app/application.py
misc/python/materialize/cloudtest/k8s/api/k8s_cluster_role.py
misc/python/materialize/cloudtest/k8s/api/k8s_config_map.py
misc/python/materialize/cloudtest/k8s/api/k8s_deployment.py
misc/python/materialize/cloudtest/k8s/api/k8s_pod.py
misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
misc/python/materialize/cloudtest/k8s/api/k8s_role_binding.py
misc/python/materialize/cloudtest/k8s/api/k8s_secret.py
misc/python/materialize/cloudtest/k8s/api/k8s_service.py
misc/python/materialize/cloudtest/k8s/api/k8s_stateful_set.py
misc/python/materialize/cloudtest/k8s/cockroach.py
misc/python/materialize/cloudtest/k8s/debezium.py
misc/python/materialize/cloudtest/k8s/environmentd.py
misc/python/materialize/cloudtest/k8s/minio.py
misc/python/materialize/cloudtest/k8s/persist_pubsub.py
misc/python/materialize/cloudtest/k8s/postgres.py
misc/python/materialize/cloudtest/k8s/redpanda.py
misc/python/materialize/cloudtest/k8s/role_binding.py
misc/python/materialize/cloudtest/k8s/ssh.py
misc/python/materialize/cloudtest/k8s/testdrive.py
misc/python/materialize/cloudtest/k8s/vpc_endpoints_cluster_role.py

Needed for cloudtest unification.
* commit-wise
* https://github.com/MaterializeInc/materialize/pull/21062 to be merged first

cloudtests: further namespace refactorings

---

doc/user/content/releases/v0.64.md
doc/user/content/releases/v0.65.md

doc/user: polish v0.64 release notes

---

src/sql/src/session/vars.rs

This extends the `feature_flags` macro to accept a default value, and the internal flag. With this change, the macro should be usable in more situations than it currently is.
-

Expand feature_flags macro to accept default and internal flag

---

Cargo.lock
src/stash/Cargo.toml
src/stash/build.rs
src/stash/protos/hashes.json

this broke cargo check caching

Revert "stash: ensure objects and latest version protos have matching hashes"

---

src/environmentd/tests/server.rs

The previous attempt to deflake
test_storage_usage_collection_interval_timestamps did so by comparing the timestamps of storage usage collections. Since the timestamps are selected after the storage usage collection is complete, delays in storage usage collection could make the timestamps arbitrarily far apart or close together.
This commit fixes this new flake, by making sure that each collection includes all objects, and that objects aren't spread out across two collections.
Fixes #21135

test: Deflake storage collection test again

---

src/storage-client/src/source/persist_source.rs

Previously we were only unpacking columns at the top level... but nowadays the only columns at the top level are "ok" and "err", which is not so helpful.
Discovered as part of testing webhooks, which use JSON heavily.
This deserves a test!
-

[persist] Unpack the "ok" field before reading JSON stats

---

misc/python/materialize/cloudtest/app/materialize_application.py
misc/python/materialize/cloudtest/k8s/api/k8s_config_map.py
misc/python/materialize/cloudtest/k8s/api/k8s_deployment.py
misc/python/materialize/cloudtest/k8s/api/k8s_service.py
misc/python/materialize/cloudtest/k8s/cockroach.py
misc/python/materialize/cloudtest/k8s/debezium.py
misc/python/materialize/cloudtest/k8s/environmentd.py
misc/python/materialize/cloudtest/k8s/minio.py
misc/python/materialize/cloudtest/k8s/persist_pubsub.py
misc/python/materialize/cloudtest/k8s/postgres.py
misc/python/materialize/cloudtest/k8s/redpanda.py
misc/python/materialize/cloudtest/k8s/role_binding.py
misc/python/materialize/cloudtest/k8s/ssh.py
misc/python/materialize/cloudtest/k8s/testdrive.py
misc/python/materialize/cloudtest/k8s/vpc_endpoints_cluster_role.py

* Allow specifying namespaces for all resources.
* Make sure that resources access other resources with the correct namespace.
* allow configuring the path to the cockroach setup script

cloudtests: provide more flexibility with respect to namespaces

---

misc/python/materialize/checks/all_checks.py
misc/python/materialize/checks/pg_cdc.py
misc/python/materialize/checks/subsource.py
src/adapter/src/catalog.rs

This adds a test for https://github.com/MaterializeInc/materialize/pull/21185.
DO NOT MERGE BEFORE https://github.com/MaterializeInc/materialize/pull/21185.

tests: add test for "sql: adjust catalog state when updating items"

---

doc/user/content/manage/access-control/rbac-terraform-tutorial.md
doc/user/content/manage/terraform.md

Set a better required version for the TF provider in the docs
-

docs: Update Terraform Version

---

Cargo.lock
src/mz/Cargo.toml
src/mz/MAINTAINERS.md

mz: release v0.1.3

---

doc/user/assets/sass/_layout.scss

Addresses: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1691570012161079

set the max-width to fit content.

---

misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
misc/python/materialize/cloudtest/k8s/testdrive.py
src/testdrive/src/bin/testdrive.rs

Allow retrieving testdrive logs.

cloudtests: facilitate testdrive logging

---

misc/python/materialize/cloudtest/util/authentication.py
misc/python/materialize/cloudtest/util/environment.py

These are changes to util files that were conducted in the cloud repo during the move.

cloudtests: bring further changes to util files

---

misc/python/materialize/cloudtest/k8s/environmentd.py

Just a small extract-method refactoring to make `generate_stateful_set` better digestible.
Since the rendered diff is not optimal, the conducted changes were the extraction of the following methods from `generate_stateful_set`:
* `args()` returning the arguments
* `env_vars()` returning the env vars
* `claim_templates()` returning the PVCs

cloudtests: environmentd.py: extract methods

---

misc/python/materialize/cloudtest/util/environment.py
misc/python/materialize/cloudtest/util/sql.py

Will be needed for: https://github.com/MaterializeInc/cloud/pull/7114/files

cloudtests: sync changes from cloud repo

---

src/expr/src/linear.rs
src/expr/src/scalar/mod.rs
test/sqllogictest/list.slt
test/sqllogictest/transform/scalar_cse.slt
test/testdrive/subexpression-replacement.td

Draft to run CI
Slack discussion: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1692019968591399
* This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/21178
-

Fix a minor bug in MFP CSE

---

ci/deploy/deploy_util.py
ci/deploy/npm.py
ci/test/cargo-test/mzcompose.py
misc/monitoring/mzcompose.py
misc/python/materialize/__init__.py
misc/python/materialize/benches/avro_ingest.py
misc/python/materialize/ci_util/trim_pipeline.py
misc/python/materialize/cli/ci_coverage_pr_report.py
misc/python/materialize/cli/cloudbench.py
misc/python/materialize/cli/crate_diagram.py
misc/python/materialize/cli/lint-cargo.py
misc/python/materialize/cli/mzcompose.py
misc/python/materialize/cli/mzimage.py
misc/python/materialize/cli/run.py
misc/python/materialize/cli/scratch/create.py
misc/python/materialize/cloudtest/app/materialize_application.py
misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
misc/python/materialize/cloudtest/k8s/cockroach.py
misc/python/materialize/mzcompose/services.py
misc/python/materialize/scratch.py
misc/python/materialize/util.py
misc/python/materialize/version_list.py
misc/python/materialize/xcompile.py
test/sqllogictest/mzcompose.py

This is to make it distinctive when the repo is included as submodule in the cloud repo.

tests: rename ROOT constant to MZ_ROOT

---

doc/user/content/releases/v0.65.md

v0.65.2 has been released. Update the docs to reflect that.
See MaterializeInc/cloud#7251
-

Bump released v0.65 patch version

---

test/lang/python/requirements.txt
test/lang/python/smoketest.py

This fixes https://buildkite.com/materialize/tests/builds/62054#018a1704-adfa-4727-b0ac-068be2eabe61.

tests: fix psycopg3 build

---

doc/user/content/ingest-data/postgres-self-hosted.md

As discussed internally, updating the self-hosted Postgres guide to include instructions for using PrivateLink.

Doc: add PrivateLink to self-hosted PG guide

---

doc/user/content/manage/terraform.md

Adding a reference to the [secret stores Terraform demo](https://github.com/MaterializeInc/demos/tree/main/integrations/terraform/secret-stores).
Closes: #21019

Docs: Terraform secret stores demo reference

---

misc/python/materialize/checks/owners.py

An issue exists with this operation that causes the entire test to hang sporadically.
Related to #21317
A product bug causes the entire test to hang.

platform-checks: Disable ALTER CLUSTER OWNER

---

src/adapter/src/coord.rs
test/cluster/mzcompose.py

This PR fixes the way how we select `as_of`s for retained-metrics indexes.
Generally, we try to select index `as_of` as late as possible, to ensure compute reconciliation can reuse the index dataflows. This strategy makes us intentionally surrender historical detail, which is usually fine since most indexes have a compaction window of 1s, so that historical detail would have been lost very soon anyway.
However, with retained-metrics indexes we keep a way larger compaction window since we want to be able to look back at metrics from previous times. Loss of historical detail is not acceptable here, so the above `as_of` selection strategy introduces a bug.
This PR fixes the bug by subtracting the index's retention duration from the selected `as_of`. This way, not much historical detail is …

adapter: fix as_of selection for retained-metrics indexes

---

src/mz/src/command/region.rs

This PR increases the timeout of `mz enable region` and `mz disable region` from 360 to 720 seconds.
[Context](https://materializeinc.slack.com/archives/CL68GT3AT/p1692771552177569?thread_ts=1692771472.429469&cid=CL68GT3AT)
-

mz: increase region commands timeout

---

misc/python/materialize/cloudtest/util/environment.py
misc/python/materialize/cloudtest/util/kubectl.py

* Refactoring: Remove duplicated code.
* New feature: Allow waiting for a resource by its label.
✅  test in cloud repo

cloudtests: unify wait

---

misc/python/materialize/cloudtest/util/sql.py

Fix type definition.
=> Follow-up: remove temporary fix in `test_egress_ips`

cloudtests: fix type in sql_execute_ddl

---

src/sqllogictest/src/bin/sqllogictest.rs

If an SLT file is malformed or missing,  fail right away instead of continuing with the remaining files. This allows such errors to be spotted faster as one does not have to fish for them in the logs after the fact.
If there is a malformed/missing SLT file, the information about it is hidden deep in the CI logs.

sqllogictest: Fail fast on malformed or missing files

---

doc/user/content/releases/v0.66.md

0.66 was released
- no user facing changes

mark 0.66 as released

---

src/adapter/src/coord.rs
src/adapter/src/coord/introspection.rs
src/adapter/src/coord/sequencer/inner.rs
src/environmentd/tests/sql.rs
test/testdrive/explain-timestamps.td

adapter: Autoroute EXPLAIN TIMESTAMP queries

---

test/testdrive/explain-timestamps.td

Fix merge skew seen in https://buildkite.com/materialize/tests/builds/62379#018a29aa-f79d-4b65-9e96-83aab9a30b26 . The system id of the index changed
-

adapter: Fix merge skew: explain timestamp test

---

doc/user/content/sql/create-source/load-generator.md
doc/user/sql-grammar/sql-grammar.bnf
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql/src/plan/statement/ddl.rs
src/storage-client/src/types/sources.proto
src/storage-client/src/types/sources.rs
src/storage/src/source/generator.rs
src/storage/src/source/generator/clock.rs

fixes https://github.com/MaterializeInc/materialize/issues/2439
- Add `CLOCK` generator source

Add CLOCK generator source

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.68.0-dev

---

misc/python/materialize/mzcompose/services.py

Fixes [the nightlies issue.](https://buildkite.com/materialize/nightlies/builds/3543#018a3430-0fbe-44fd-b16c-7448975c87a0/205-287).
The warning message might be breaking the parser.
-

mz: fix nightlies output

---

src/mz/src/server.rs

Simple fix for https://github.com/MaterializeInc/materialize/issues/17648
Result:
-

mz: better web response

---

src/compute/src/render/mod.rs

This PR adds a workaround for an arrangement memory spike observed during dataflow hydration that happens because the arrangement merges an empty batch with the snapshot batch. The workaround is based on suppressing early progress announcements to ensure the `arrange_core` operator is not writing any empty batches before the snapshot batch.
To test that this works you can run the following simple test case and then observe the memory usage of the final `CREATE INDEX` command in a memory analyzer:
```sql
CREATE TABLE t (a int);
INSERT INTO t SELECT generate_series(1, 1000000);
CREATE DEFAULT INDEX ON t;
```
* Without this change: 
* With this change (sorry for the amateurish screenshooting work, but I hope you get the gist): 
Note that the initial and final sizes are the same in both …

compute: fix hydration memory spike in arrangements

---

src/adapter/src/client.rs
src/adapter/src/coord/introspection.rs
src/adapter/src/metrics.rs
src/adapter/src/rbac.rs
src/environmentd/tests/sql.rs
src/pgwire/src/protocol.rs
src/sql/src/session/user.rs
src/sqllogictest/src/runner.rs
test/cloudtest/test_labels.py
test/sqllogictest/materialized_views.slt
test/sqllogictest/operator.slt
test/sqllogictest/pg_catalog_matviews.slt

adapter: Remove mz_introspection user in favor of mz_support

---

src/stash/src/upgrade/v33_to_v34.rs

This PR fixes the v33->v34 audit log migration to make it more robust against edge cases in the audit log:
* missing `replica_id` fields on cluster-replica events
* cluster-replica events for system replicas
The former events are getting ignored, the latter are handled correctly now.
Ignoring cluster-replica events without `replica_id` fields is sound because in all existing catalogs all alive replicas have a create event that has a `replica_id` set. In the migration we only care about these events.
Fixes: https://github.com/MaterializeInc/materialize/issues/21430
- N/A

stash: fix v33->v34 audit log migration

---

src/adapter/src/client.rs

handle_startup was incorrectly handling the case where it successfully completed a connection startup, but the AdapterClient had gone away before the Coordinator could respond to it. This could happen if the pgwire, http, or websocket connection was closed during handle_startup's execution. When handle_startup observed that failure, it called handle_terminate. But when the AdapterClient was dropped, it also terminated the connection. This double termination caused envd to panic because that should never happen.
Fix this by not even creating an AdapterClient until after startup is complete. That way there's no Drop implementation until we have a known good session. This should also fix a previous, unsolved bug with handle_terminate that was likely happening for the same reason.
Fixes …

adapter: don't double terminate on startup fail

---

src/mz/src/command/profile.rs

Simple PR. Sets `Materialize CLI (mz)` as the description when for the app-password when running `mz profile init`:
Result:
-

mz: set Materialize CLI (mz) as the app-password description

---

doc/user/content/ingest-data/network-security/privatelink.md

This PR removes the MSK specific language from the Privatelink guide as it works for both MSK and self-managed Kafka clusters on AWS.
Closes #17213

Doc: Remove MSK language from Privatelink guide

---

src/mz/src/command/profile.rs

Simple PR to improve the error message during the login.
-

mz: improve error message during login.

---

misc/images/jobs/Dockerfile
misc/images/jobs/mzbuild.yml

Needed for upcoming cloud work.
See https://github.com/MaterializeInc/cloud/issues/5057#issuecomment-1672298587
- n/a

misc: add mz-stash-debug to jobs image

---

doc/user/content/ingest-data/network-security/privatelink.md
doc/user/content/ingest-data/network-security/ssh-tunnel.md
doc/user/content/ingest-data/postgres-amazon-aurora.md
doc/user/content/ingest-data/postgres-amazon-rds.md
doc/user/content/ingest-data/postgres-azure-db.md
doc/user/content/ingest-data/postgres-google-cloud-sql.md
doc/user/content/ingest-data/postgres-self-hosted.md
doc/user/content/sql/create-connection.md
doc/user/content/sql/validate-connection.md
doc/user/layouts/partials/sql-grammar/create-connection-aws-privatelink.svg
doc/user/layouts/partials/sql-grammar/create-connection-csr.svg
doc/user/layouts/partials/sql-grammar/create-connection-kafka.svg
doc/user/layouts/partials/sql-grammar/create-connection-postgres.svg
doc/user/layouts/partials/sql-grammar/create-connection-ssh-tunnel.svg
doc/user/layouts/partials/sql-grammar/validate-connection.svg
doc/user/sql-grammar/sql-grammar.bnf

doc: reference documentation for `VALIDATE CONNECTION`

---

src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars.rs
test/testdrive/fetch-concurrent-same-source.td
test/testdrive/fetch-concurrent-two-sources.td
test/testdrive/fetch-select-during-ingest.td
test/testdrive/fetch-tail-during-ingest.td
test/testdrive/shared-timestamp-bindings.td
test/testdrive/timestamp-interval.td
test/testdrive/top-1-monotonic.td

adapter: Add min_timestamp_interval server var

---

misc/python/materialize/cli/run.py

Reported by Gábor to me in private DM
The issue should be fully explained in the comment.
-

Fix local bin/sqllogictest

---

misc/python/materialize/cloudtest/util/authentication.py

Decouples the test user config from the args namespace.
This allows us to use multiple test users simultaneously, and parallelize the tests.
Part of https://github.com/MaterializeInc/cloud/issues/7389
The other typing changes were automatically added by my editor/linter.
- There will be an associated cloud PR, but it doesn't need to be a release-blocker, it just needs to be merged before otherwise bumping the submodule.
- https://github.com/MaterializeInc/cloud/pull/7402
- no user-facing behavior changes.

decouple test user config from args namespace

---

test/testdrive/webhook.td

Fixes the full testdrive CI flow

tests: fix full testdrive in cloudtest

---

doc/user/content/serve-results/hex.md

Steps in the Hex guide have an incorrect format. 
-

doc/user: fix hex bad formatted steps

---

misc/python/materialize/cli/ci_coverage_pr_report.py

Broken in https://github.com/MaterializeInc/materialize/commit/980de057f5c037ab4d8252a3fc7b52f9848dd828#diff-cae57535b66487fe56f48b1a3fb43afe62e731ca74403b41f80820e47ff22ec6
-

ci: Fix coverage analysis

---

doc/user/content/manage/reverse-etl/census.md

Overview guide for creating a Census sync using Materialize. Based on our [Datadog guide](https://materialize.com/docs/manage/monitor/datadog/).
-

docs: Census Guide

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/storage.rs

This commit refactors the mz_adapter::catalog::storage dependencies so that it no longer relies on mz_adapter::timeline. This will help in the effort to extract catalog::storage into its own crate.
The logic for reserving a new timestamp range is moved from mz_adapter::catalog::storage::Connection::open to
mz_adapter::catalog::Catalog::open. As a result, the timestamp used for catalog migrations may be ahead of the timestamp used for the stash initialization. This is OK because the two steps are logically different and do not happen atomically. It was already possible for this to happen due to a crash in-between the two steps.
Works towards resolving #20953

catalog: Refactor storage timeline dependencies

---

ci/deploy_mz/version.py

This file was meant to be named "mz-latest.version", not "mz.version". Also set the content type as "text/plain" so that it is visible in the browser without a download, just for convenience when debugging.
- n/a

ci/deploy_mz: fix version upload

---

Cargo.lock
src/mz/CHANGELOG.md
src/mz/Cargo.toml

mz: release v0.2.1

---

ci/deploy_mz/version.py

Remove a newline character in the S3 object containing the latest version of `mz`. Otherwise, anyone who reads this will have to remove the \n manually.
Example in `mz`:
https://github.com/MaterializeInc/materialize/blob/e2ba2b39f071d4e6e493d7a84bd8099cafd63c4d/src/mz/src/bin/mz/upgrader.rs#L128
-

mz: remove new line from latest version s3 object

---

src/storage/src/render/mod.rs
src/storage/src/render/persist_sink.rs
src/storage/src/storage_state.rs

Our current approach to dropping a source results in a race between shard finalization (which happens in the controller) and dataflow shutdown (which happens in clusterd). If a source is created and dropped fast enough -or the two commands get sufficiently delayed- then it's possible for clusterd to attempt to start writing to a shard that the controller has already finalized.
This resulted in a panic in clusterd instead of a graceful shutdown of the dataflow.
This PR implements a solution to this problem by restarting the ingestion dataflow whenever an upper mismatch is encountered in the storage persist sink implementation. This is a stopgap solution until concurrent ingestion is propertly implemented and such upper mismatches get handled inside the operators.
Fixes #21314
-

storage: gracefully handle shard finalization in persist_sink

---

src/adapter/src/coord.rs

Info seemed excessive as the default.
- n/a

adapter: change many coord init traces to debug

---

doc/user/content/sql/alter-cluster.md

Add a reference to `ALTER ... RENAME` to `ALTER CLUSTER` (took me a minute to find the right command.)
- Clarification in docs.

docs/user: Link to `ALTER ... RENAME` from `ALTER CLUSTER`.

---

doc/user/config.toml
doc/user/content/ingest-data/rudderstack.md
doc/user/content/sql/create-source/webhook.md

As discussed in #21197, adding an integration guide for RudderStack webhooks.

Doc: Add RudderStack webhook guide

---

misc/python/materialize/cloudtest/util/environment.py

Extension to https://github.com/MaterializeInc/cloud/pull/7502

cloudtests: allow configuring envd waiting timeouts

---

doc/user/content/ingest-data/rudderstack.md

Fixing some minor problems in the Rudderstack guide as discussed in #21703

Doc: minor Rudderstack guide fixes

---

src/sql/src/func.rs
test/sqlsmith/mzcompose.py

Fixes #21753. Originally comes from https://github.com/MaterializeInc/materialize/pull/18660

Fix aclitem_privileges return type

---

doc/user/content/_index.md
doc/user/content/get-started/quickstart.md
doc/user/content/integrations/_index.md
doc/user/layouts/partials/header.html

Don't love the blurb and this landing page needs to be redesigned as a whole, but pushing a minimal update to match the new positioning.

doc/user: update landing page

---

src/mz/src/context.rs

This PR removes a temporary fix and warning message. It has been out there for a couple weeks. Now is time to remove the warning.
The intention was to remove it after `v0.1.6`, we are currently at `v0.2.1`.
-

mz: remove deprecated code

---

ci/test/lint-docs-catalog.sh

This PR refactors existing code: It makes the output if `ci/test/lint-docs-catalog.sh` more friendly to CI formatting.
-

Make output of lint-docs-catalog CI-friendly

---

Cargo.toml

this still isnt reliable :( https://materializeinc.slack.com/archives/CMH6PG4CW/p1695312777976149

Revert "rust: turn back on incremental for dev builds"

---

src/storage/src/source/kafka.rs

It can happen that a source is pointed to a topic that used to have messages (i.e high watermark is non-zero) but due to compaction all messages are deleted (i.e its low watermark equals the high watermark).
The code on main unconditionally started ingesting a partition at offset 0, expecting to eventually reach the high watermark. If the topic was completely empty due to compaction this never happened, causing the source to permanently be unqueryable (or until a single message got published to the empty partition).
This PR fixes this issue by respecting the low watermark when a new partition is discovered, fast forwarding the data capability to the offset of the low watermark instead of zero.
Fixes #21860
-

kafka: respect low watermark when setting up capabilities

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml

release: bump to version v0.71.0-dev

---

src/stash/src/postgres.rs

Consolidation retries don't need to be noisy.
- n/a

stash: demote error to debug

---

doc/user/content/sql/create-source/load-generator.md

docs: Fix auction_id type in auction loadgen

---

Cargo.lock
src/mz/CHANGELOG.md
src/mz/Cargo.toml

mz release v0.2.2

---

src/mz/src/command/region.rs

Adds the `create` method inside a retry for the `mz region enable` cmd. 
[More context here](https://materializeinc.slack.com/archives/CL68GT3AT/p1695728061406689)
-

mz: add retry to the create method in the enable cmd

---

ci/test/pipeline.template.yml
misc/python/materialize/mzcompose/composition.py
test/cluster/mzcompose.py
test/crdb-restarts/mzcompose.py
test/restart/mzcompose.py
test/source-sink-errors/mzcompose.py
test/ssh-connection/mzcompose.py
test/testdrive/mzcompose.py
test/upsert/mzcompose.py

mzcompose: Sanity check restarts at the end of each test

---

misc/python/materialize/mzcompose/composition.py

mzcompose: Clarify starting sources

---

test/cluster/mzcompose.py

Had another variable i shadowing the original (and no python linter caught it?!)
Also bumped the limits as we commonly are over them in CI it seems
Fixes: #22004
Anyone found a way to warn about shadowing variables in Python? Seems like an easy mistake to make.
-

ci: Fix retry in test-concurrent-connections

---

misc/images/materialized/Dockerfile
misc/python/materialize/mzcompose/services/cockroach.py

ci: Use CRDB 23.1.10

---

misc/python/materialize/mzbuild.py

Broken in https://github.com/MaterializeInc/materialize/pull/21932
-

mzbuild: Fix local build

---

ci/test/pipeline.template.yml
src/storage-controller/src/lib.rs

Trying to get more information for https://github.com/MaterializeInc/materialize/issues/22055
-

Adding log line to get better error

---

src/timely-util/src/builder_async.rs

We don't have any guarantees about how long the `Waker` will be held for and so we must be prepared for the receiving end to have hung up when we finally do get woken. This can happen if by the time the waker is called the receiving timely worker has been shutdown. For this reason we ignore the activation error.
-

timely-util: Wakers should anticipate hung up receivers

---

src/kafka-util/src/client.rs

They are far too spammy, and generally indicate user configuration errors rather than actual bugs in Materialize that need to be reported on.
* This PR fixes an issue reported on Slack: librdkafka errors are too spammy. See: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1696256524616059?thread_ts=1696255775.857209&cid=C01CFKM1QRF
- n/a

kafka-util: don't report librdkafka errors to Sentry

---

ci/test/pipeline.template.yml

https://materializeinc.slack.com/archives/C057X0NG91B/p1696027388208299

CI: use builder-linux-x86_64 in all checks

---

src/persist/src/s3.rs

This code was written as part of an investigation, where we were trying to take some load off of the task scheduler. While it's unclear if the load on the task scheduler is _actually_ a problem, removing the tasks here seems simpler in a way we may prefer regardless.
This is functionally a noop, so the coverage by existing tests is pretty good. I've also run a full set of nightlies, which came back green. Let me know if any additional tests feel appropriate!
-

[persist] Replace the task forking in S3Blob with FuturesUnordered

---

doc/user/content/ingest-data/snowcatcloud.md

SnowcatCloud Integration with Materialize Webhook

---

src/adapter/src/coord/statement_logging.rs
src/adapter/src/statement_logging.rs
src/storage-client/src/healthcheck.rs
test/testdrive/statement-logging.td

add cluster_name and application_name columns in mz_statement_execution_history

---

src/environmentd/tests/auth.rs

This PR reduces the number of seconds that the test frontegg server
will wait before refreshing a token from 40 seconds to 2 seconds. This
has significant improvements on the speed of tests.
Starting a test server is an expensive and slow process. This PR
also updates all the environmentd auth tests so that a single test only
starts a single server. This allows us to run tests in parallel and
parallelize the cost of starting a test server.
Works towards resolving https://github.com/MaterializeInc/materialize/issues/21891
Ignore whitespace

tests: Speed up auth tests

---

ci/deploy_mz_lsp_server/README.md
ci/deploy_mz_lsp_server/deploy_util.py
ci/deploy_mz_lsp_server/linux.py
ci/deploy_mz_lsp_server/macos.py
ci/deploy_mz_lsp_server/pipeline.yml
ci/deploy_mz_lsp_server/version.py
src/lsp-server/Cargo.toml

This PR implements the CI process for the Language Server Protocol (LSP). The release process is almost identical to the [`mz`](https://github.com/MaterializeInc/materialize/tree/main/ci/deploy_mz) release process, with the following differences:
1. This process does not deploy a Docker image.
2. The Linux binary is built without using Docker ([this line](https://github.com/MaterializeInc/materialize/blob/8593e1c6731e042f24fd73d062743d9e53301695/ci/deploy_mz/linux.py#L32) is replaced by a `cargo build ..`).
-

ci/mz_lsp_server: binary release process

---

ci/nightly/pipeline.template.yml
test/cluster/mzcompose.py

Still a draft.
```
bin/mzcompose --find cluster down -v && bin/mzcompose --find cluster run test-incident-70
```

tests: test for incident 70

---

misc/python/materialize/mzcompose/composition.py

We are currently retrying `up()`, but we also call `docker-compose up` and `docker-compose pull` directly, which can both error out in case of a DockerHub glitch.
- push the retry logic from `up()` down into `invoke()`
- route all calls to `docker-compose up` through `up()`
- route all calls to `docker-compose pull` through `invoke(max_tries=2)`
I noticed a failure in Nightly that could have been retried. https://buildkite.com/materialize/tests/builds/65181#018afc27-cab9-4d51-a5d5-06028d216776
You may wish to review this with whitespace disabled.

mzcompose: Retry more docker-compose operations

---

src/compute/src/metrics.rs
src/compute/src/server.rs

In incident 70, we found that timely-driven Futures were not promptly being polled after being woken. This was presumably because some operator was not regularly yielding. Not yielding also causes issues in query interactivity (i.e. because peeks are included in this), so it's also otherwise undesirable. The introspection sources have full-fidelity data around operator run times, but we duplicate a proxy for them into prometheus so we can alert on it and easily scan it in investigations.
Concretely, a new histogram is added for step_or_park durations in compute timely clusters. This doesn't tell us anything about individual operators (and including the park time is undesirable) but it has the benefit of being very easy yet still useful by virtue of being an upper bound. In particular, …

compute: add timely_step_duration_seconds histogram

---

doc/user/content/releases/v0.71.md
doc/user/content/releases/v0.72.md

**WIP** Release notes for v0.71. 🪴 
@evanharmon @bobbyiliev: this covers the step of bumping the release version in the docs.

doc/user: polish v0.71 release notes

---

src/expr/src/scalar/func/impls/string.rs

Minor refactor opportunity I noticed when trying to figure out how our optimization for regex matching against static strings works.
I'm pretty sure both implementations are exactly the same, but maybe I'm blind!
- N/A

expr: deduplicate regexp_match_static logic

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.73.0-dev

---

doc/user/content/sql/create-sink/kafka.md

Updated docs for `NULL DEFAULTS` https://github.com/MaterializeInc/materialize/issues/21829
-

docs: updating docs for null defaults

---

src/environmentd/src/http.rs

Getting the user from the HTTPS cert has long been deprecated and was misleading in the code. For example it was always populating an Option as None. Make explicit the separation between DefaultUser (used by http) and User (used by ws) to make it explicit what's going on.
- n/a

environmentd: remove final cert user code

---

src/compute/src/logging/compute.rs

This PR reduces the allocations performed for converting `GlobalId`s into `Datum`s in compute logging by setting up scratch buffers that are reused, rather than allocating a new buffer for each `Datum` conversion.
Based on a comment from @antiguru on #21453.
- N/A

compute: reduce allocations in compute logging

---

test/sqlsmith/mzcompose.py

Following https://github.com/MaterializeInc/materialize/pull/22285
-

Expect new errors from (mz_)aclexplode

---

misc/python/materialize/checks/checks.py
misc/python/materialize/checks/replica.py
misc/python/materialize/checks/roles.py
src/testdrive/src/action.rs
src/testdrive/src/action/nop.rs
src/testdrive/src/lib.rs
test/legacy-upgrade/check-from-any_version-noop.td
test/legacy-upgrade/check-ssl-from-any_version-noop.td
test/legacy-upgrade/create-in-any_version-noop.td
test/legacy-upgrade/create-ssl-in-any_version-noop.td
test/pg-cdc/mzcompose.py
test/testdrive/github-5668.td
test/upsert/failpoint/05-reset.td
test/upsert/incident-49/03-reset.td
test/upsert/mzcompose.py
test/upsert/rehydration/04-reset.td

* Fail execution if there is no input provided.
* Log number of commands to be executed.

ci: testdrive: fail on empty input and log number of commands

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
test/sqlsmith/mzcompose.py

Now that OoMs seem to be solved
-

ci: Bump number of SQLsmith runners

---

src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars.rs
test/sqllogictest/materialized_views.slt

fixes https://github.com/MaterializeInc/materialize/issues/22336

add feature flag for `ASSERT NOT NULL`

---

Cargo.lock
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.74.0-dev

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

These are changes that I had already tested locally with https://github.com/MaterializeInc/materialize/pull/21781 but forgot to commit since they were in the other repo clone.
(I still triggered a nightly build: https://buildkite.com/materialize/nightlies/builds/4715)

postgres consistency: update ignore filter

---

src/avro/src/reader.rs

"iff" was changed to "if" in https://github.com/MaterializeInc/materialize/pull/11724 , subtly changing the meaning.

Re-fix incorrectly "corrected" comment

---

ci/builder/Dockerfile
ci/plugins/mzcompose/hooks/post-command

ci: Fix gdb installation

---

misc/python/materialize/checks/all_checks.py
misc/python/materialize/checks/statement_logging.py

This test was disabled. When enabling it, a few fixes are required.
Thanks @def- for reporting!

Fix and enable statement logging platform test

---

test/scalability/mzcompose.py

This fixes the indices of the dataframes.

scalability framework: fix dataframe handling

---

ci/test/pipeline.template.yml

ci: Group cargo & miri tests

---

ci/mkpipeline.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/22405
-

ci: Allow rerunning grouped steps

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This addresses https://buildkite.com/materialize/nightlies/builds/4760#018b4520-a430-4062-a175-51e84462a926.

postgres consistency: ignore pow inconsistencies

---

src/environmentd/tests/auth.rs

`test_refresh_task_metrics` tests to make sure that an authentication refresh task stops running when the client using that auth closes. This process of stopping though is async and while it should happen quickly it's not guaranteed to occur before our assert.
To fix this I wrapped the check in an `mz_ore::retry::Retry`. To make sure this fix works I locally added a `tokio::sleep(...)` in the auth code to add artificial latency from dropping the client to the task shutting down, and the test still passed.
Fixes https://github.com/MaterializeInc/materialize/issues/22450
- N/a

tests: Reduce flakiness in test_refresh_task_metrics

---

src/persist/src/location.rs

Looks like we severed the tracing plumbing when we introduced the Tasked wrapper wrappers.
-

persist: restore tracing Span plumbing for Tasked

---

ci/test/lint-fast.sh

* make it more explicit when buf checks are triggered
* run buf checks locally when not on branch `main`
=> check is triggered when `$IN_BUILDKITE_PR || $IN_LOCAL_NON_MAIN_BRANCH`

ci: rework condition whether to run buf checks

---

misc/python/materialize/output_consistency/operation/operation.py
misc/python/materialize/parallel_workload/action.py
test/feature-benchmark/mzcompose.py
test/scalability/mzcompose.py
test/source-sink-errors/mzcompose.py

tests: Remove useless enumerate calls

---

misc/python/materialize/scalability/regression.py
misc/python/materialize/scalability/result_analyzers.py
test/scalability/mzcompose.py

Upload a `regressions.csv` file.
Tested successfully in https://buildkite.com/materialize/nightlies/builds/4784#018b4c91-c3a2-44a9-adf0-16e733bc9378.

scalability framework: upload regressions

---

misc/python/materialize/mzbuild.py

`mzbuild` is failing on `scratch` machines. I haven't investigated in detail, but it seems like what's happening is that it does find some creds, but they don't have permissions to do the upload. This seems like another case where we should fail open.
Should be able to repro by building on any old scratch machine, if you'd like.
-

Ignore permissions errors as well as lack of permissions

---

src/kafka-util/src/client.rs

https://materializeinc.sentry.io/issues/4552749527/?environment=staging&project=6780145&query=release%3A0.74.2&referrer=release-issue-stream this should not be a sentry error, as its related to the user's broker; downgrade to a warning
Also, `message` as a field was overriding the _message_ at the end of the macro incantation, so I fixed that too
Also, I went ahead and categorized this specific error as a `BrokerTransportError`. Not sure we we want to have a separate error case for a transport error during sasl auth. i think probably we don't
-

storage: downgrade another kafka context error into a warning

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/backup_actions.py
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios_backup_restore.py
misc/python/materialize/mzcompose/services/materialized.py
misc/python/materialize/mzcompose/services/minio.py
test/platform-checks/mzcompose.py

Backup+Restore was only merged with a minimal test. It needs to be made part of as many test frameworks as possible.

platform-checks: Add a Backup+Restore scenario

---

ci/nightly/pipeline.template.yml
misc/python/materialize/scalability/endpoints.py
misc/python/materialize/scalability/workload.py
test/scalability/mzcompose.py

This solves https://github.com/MaterializeInc/materialize/issues/22307.
I will start with this, we can move it to a separate pipeline every time.
Nightlies: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aci%2Fadd-scalability-framework

ci: integrate scalability framework in CI

---

misc/python/materialize/scalability/regression.py
misc/python/materialize/scalability/result_analyzer.py
misc/python/materialize/scalability/result_analyzers.py
test/scalability/mzcompose.py

Detect regressions immediately and not at the end of the run. This will render retries possible.

scalability framework: regression detection on the fly

---

misc/python/materialize/scalability/df/df_details_cols.py
misc/python/materialize/scalability/df/df_totals_cols.py
misc/python/materialize/scalability/df/df_totals_ext_cols.py
misc/python/materialize/scalability/df/paths.py
misc/python/materialize/scalability/result_analyzers.py
test/scalability/mzcompose.py

Commits:
* 7f8a93eba0 scalability framework: extract path constants
* dc7ddbb3d0 scalability framework: extract dataframe constants

scalability framework: extract constants

---

src/compute/src/compute_state.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs

This PR avoids transits through `Row` for specialized types in join closures and during peek completion. This is achieved by employing `into_datum_iter` instead of `into_row` in these functions. To deal with lifetimes, the allocations of `RowArena` instances are moved earlier than obtaining key-value iterators in local scopes.
This PR builds on the design introduced by PR #21968.
* This PR adds a known-desirable feature. Advances https://github.com/MaterializeInc/materialize/issues/22522
This PR makes progress on avoiding row encoding/decoding when unnecessary for specialized types, but is not comprehensive in getting rid of `borrow_with*` calls. These are left to future work.
One item for discussion: I did not change the definition of `IntoRowByTypes` to actually get rid of `into_row` as …

Avoid transits through `Row` for specialized types

---

src/persist-client/src/operators/shard_source.rs
src/storage-operators/src/persist_source.rs

[persist] Clean up a duplicate struct

---

misc/python/materialize/checks/all_checks.py

See https://github.com/MaterializeInc/materialize/issues/22448#issuecomment-1776637047.

platform checks: disable failing statement_logging

---

misc/python/materialize/parallel_workload/database.py

This should help identify how https://github.com/MaterializeInc/materialize/issues/22607 can occur.

ci: parallel workload with naughty identifiers: introduce assertion

---

ci/nightly/pipeline.template.yml

Will not be part of selection with #22617
-

Uncomment currently skipped steps in nightly

---

test/sqlsmith/mzcompose.py

Referenced issue https://github.com/MaterializeInc/materialize/issues/19496 is fixed.
Nightly: https://buildkite.com/materialize/nightlies/builds/4866

ci: sqlsmith: cleanup

---

ci/mkpipeline.py

ci: test selection: do not list skipped steps

---

misc/python/materialize/scalability/regression.py
misc/python/materialize/scalability/workload_executor.py

This is based on https://github.com/MaterializeInc/materialize/pull/22611, which shall be reviewed and merged first. ✅

scalability framework: retry on regression

---

src/environmentd/tests/server.rs

Previously, the smoketest_webhook_source test would send multiple HTTP
requests to a webhook source sequentially. In CI this test would take
about 112.5 seconds. This commit updates the test so that all HTTP
requests are sent out in parallel. The test now takes roughly 14.6
seconds in CI.
Speed up test

test: Speed up smoketest_webhook_source

---

src/compute/src/render/reduce.rs

This PR changes the rendering of distinct reductions to respect the feature flag `enable_specialized_arrangements`. While it is safe to render `DistinctBy` with an empty value, it is preferable that this be strictly gated by the feature flag, just like the rendering of default indexes in that modality.
This PR builds on the design introduced by #21968.
Advances #221.
When Materialize is started with the feature flag `enable_specialized_arrangements` turned off, `DistinctBy` is specialized to include empty values regardless. Since this behavior was not the case as of `v0.74`, then it is proper that it only be introduced if the feature flag is on.
I noticed this while performing experiments to compare arrangement sizes with and without …

Only specialize `DistinctBy` if feature flag is on

---

doc/user/content/releases/v0.73.md
doc/user/content/releases/v0.74.md

**WIP** Release notes for v0.73. 🦧  
@moulimukherjee @necaris: this covers the step of bumping the release version in the docs.

doc/user: polish v0.73 release notes

---

src/environmentd/src/test_util.rs

This (mostly) disables clusterd INFO messages, which are largely spam for envd tests and have greatly decreased our ability to quickly understand test output.
This still produces occasional WARN messages I think because the test macro we use auto-inits the tracing subscriber, so we are not able to use the normal TracingCliArgs stuff. That may be a refactor for another day.
- n/a

environmentd: silence orchestrator in integration tests

---

src/stash/src/postgres.rs

stash: Use transaction priority to avoid aborts
The stash has two concurrent tasks executing transactions against
CockroachDB. One of the tasks is executing the logic for DDL and the
other is performing compaction in the background. Occasionally these
two tasks will execute transactions at the same time causing one to
abort. Executing logic for DDL is much more important than compaction,
compaction is not needed for correctness and is only used to reclaim
unused data and speed up reads.
This commit executes the main stash task as a high priority CockroachDB
transaction and compaction as a low priority CockroachDB transaction.
The result is that if there's a conflict, the compaction task is always
the one that's aborted. See:
https://www.cockroachlabs.com/docs/stable/architecture/transactio …

stash: Use transaction priority to avoid aborts

---

doc/user/content/sql/create-materialized-view.md
doc/user/content/sql/create-sink/kafka.md
doc/user/layouts/partials/sql-grammar/create-materialized-view.svg
doc/user/sql-grammar/sql-grammar.bnf

Document `ASSERT NOT NULL`

---

misc/python/materialize/scalability/endpoint.py
misc/python/materialize/scalability/endpoints.py
misc/python/materialize/scalability/result_analyzers.py
misc/python/materialize/scalability/workload_executor.py
test/scalability/mzcompose.py

This addresses the issue `assert self._port is not None` reported by @danhhz in https://materializeinc.slack.com/archives/C01LKF361MZ/p1698273931269339 and observed in [Nightly.](https://buildkite.com/materialize/nightlies/builds/4888#018b692d-3557-4354-847a-a2ec385a6c6f)
* 815765a1c0 scalability framework: fix
* 71bf057442 scalability framework: rework endpoint name

scalability framework: fix name handling

---

misc/python/materialize/output_consistency/ignore_filter/ignore_verdict.py
misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter_base.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Just moving some code around to tidy up.

output consistency: tidy up ignore class

---

doc/user/data/sql_funcs.yml

I messed up the syntax in the example...
-

Minor fix in window function docs

---

doc/user/content/sql/create-sink/kafka.md

This is adding documentation for https://github.com/MaterializeInc/materialize/issues/21557
I added the docs under private preview. Please do suggest if there's a better way to document this. I did not want to over-complicate it with too many examples but wanted to capture the standard path an user might use.
-  documentation for avro comments
cc @umanwizard @morsapaes

docs: private-preview docs for avro comments

---

doc/developer/platform-checks.md
misc/python/materialize/checks/all_checks/peek_cancellation.py
misc/python/materialize/checks/all_checks/pg_cdc.py
misc/python/materialize/checks/checks.py

Restore the possibility to ignore checks.

ci: platform checks: introduce @disabled annotation, restore ignores

---

misc/python/materialize/output_consistency/enum/enum_operation_param.py
misc/python/materialize/output_consistency/generators/expression_generator.py
misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/operation/operation.py
misc/python/materialize/output_consistency/runner/test_runner.py

Commits:
* a6d62508f8 output consistency: add util functions to support rebuilding expressions
* a7213e5e02 output consistency: allow disabling the creation of where conditions
* 33d344baae output consistency: keep order of enum constants in param

output consistency: support rebuilding expressions for analysis

---

src/storage-controller/src/persist_handles.rs

Refactoring: I need to make some changes in here and this will make them easier! (Moving code out of the select macro allows formatting and other analysis to see it, and reporting errors more clearly seems useful.)
The first commit is large, but mostly for indentation reasons; hiding whitespace might help. Aside from the structural changes there's some minor ones as rustfmt sees this code for the first time.
-

[persist] Remove a vestigial select loop

---

src/repr/src/row.rs

Limit the size of allocations to store Row regions to 2MiB. This counters the doubling effect of using columnation without any limit.
-

Limit row regions to 2MiB

---

src/adapter/src/coord.rs

This should be fully explained by the comment.

downgrade "execute context dropped" soft_assert to error.

---

doc/user/content/get-started/isolation-level.md

Adds information to the serializable isolation level docs
about the performance implications of using explicit transactions
versus auto-commit.
Updates docs
Review each commit separately. 

Isolation level docs

---

src/storage-controller/src/lib.rs

Attempt at dealing with https://github.com/MaterializeInc/materialize/issues/22725
We believe this to be the cause of https://materializeinc.slack.com/archives/C01CFKM1QRF/p1698391779182889,
as write handles can be arbitrarily delayed.
-

storage: ensure we fetch a recent upper on startup

---

src/sql/src/session/vars.rs

This will enable clients (such as the Console SQL Shell) to update presentation and behavior when a user changes their schema.

Add 'search_path' to the set of session variables to notify for.

---

Cargo.lock
src/lsp-server/CHANGELOG.md
src/lsp-server/Cargo.toml
src/lsp-server/MAINTAINER.md

Release v0.2.0 of the LSP server.

mz lsp server release

---

misc/shlib/shlib.bash

As reported in https://materializeinc.slack.com/archives/C01LKF361MZ/p1698692228888979
-

ci: Improve output for when a try-block failed

---

misc/python/materialize/scalability/result_analyzers.py
misc/python/materialize/scalability/workload_executor.py
test/scalability/mzcompose.py

Content:
* 7752e5115e scalability framework: increase regression threshold
* 11dcb217a3 scalability framework: increase number of retries
* 0585c7cbe3 scalability framework: log retries

scalability framework: regression handling

---

doc/user/content/releases/v0.74.md
doc/user/content/releases/v0.75.md
doc/user/content/sql/alter-default-privileges.md
doc/user/content/sql/copy-to.md
doc/user/content/sql/delete.md
doc/user/content/sql/grant-privilege.md
doc/user/content/sql/insert.md
doc/user/content/sql/revoke-privilege.md
doc/user/content/sql/select.md
doc/user/content/sql/show-default-privileges.md
doc/user/content/sql/show-privileges.md
doc/user/content/sql/show-role-membership.md
doc/user/content/sql/subscribe.md
doc/user/content/sql/update.md

Late release notes for v0.74. 🏜️

doc/user: polish v0.74 release notes

---

misc/python/materialize/buildkite.py
misc/python/materialize/git.py
test/scalability/mzcompose.py

Commits:
* b85573326a ci: git utils
* e3d94f8ca8 scalability framework: fetch tags to have their commit messages

scalability framework: ensure commit infos available

---

misc/python/materialize/scalability/plot/plot.py
misc/python/materialize/scalability/workload_executor.py
misc/python/materialize/scalability/workload_result.py
test/scalability/lib.py

* b5d05ed106 scalability framework: minor
* 10bbd8a433 scalability framework: result recording
* 8d6bec301b scalability framework: plots: refactor
* 1fa84cb524 scalability framework: plots: reduce endpoint offset
* 0a95c910f0 scalability framework: plots: boxplot for latency
* 7afcd3466a scalability framework: plots: use boxplot
* 549f3c4389 scalability framework: plots: rename methods
* 8339cf8a25 scalability framework: plots: set ticks

scalability framework: rework plots, introduce boxplot

---

doc/developer/guide.md

This is useful as we have run into a few issues recently with compatibility, and we do not have an explicit policy stated (as we do for Rust).
I expect some commentary and bikeshedding on this so please don't consider it final until a consensus of teams and / or @benesch has approved!

doc(developer): State Python versioning policy

---

misc/python/materialize/scalability/plot/plot.py
test/scalability/lib.py
test/scalability/mzcompose.py

Let's see... https://buildkite.com/materialize/nightlies/builds/4970

scalability framework: improve plots

---

doc/user/content/sql/create-cluster-replica.md
doc/user/content/sql/create-cluster.md

This feature has multiple users, is code complete, and checks all the public-preview pieces off.
-

spill2disk: go to public preview

---

misc/python/materialize/scalability/plot/plot.py
test/scalability/lib.py
test/scalability/mzcompose.py

Use another marker for the regression baseline in scatterplots.

scalability framework: highlight regression target

---

doc/user/content/ingest-data/snowcatcloud.md
doc/user/content/ingest-data/stripe.md

doc/user: address post-merge comments on Stripe webhook integration

---

misc/python/materialize/output_consistency/enum/enum_operation_param.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/values/date_time_values_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Nightlies: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fenum-constant-with-invalid-val

output consistency: add invalid value in enum constants

---

src/balancerd/src/service.rs

balancerd: allow DNS names in static resolver

---

doc/user/content/releases/v0.75.md
doc/user/content/releases/v0.76.md
doc/user/content/sql/explain-plan.md
doc/user/content/sql/explain-timestamp.md
doc/user/content/sql/select.md

doc/user: polish v0.75 release notes

---

misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This addresses https://buildkite.com/materialize/nightlies/builds/5015#018ba49d-0b31-4d54-9ca8-e098fd793570.
**Commits:**
58cad50e35 output consistency: update issue reference (#15186 for #19592)
757c68cc83 output consistency: update issue reference (#15816 for #19511 / #19577)
2bf069d51a postgres consistency: update issue reference (#22024 for #21584)

output consistency: update issue references

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/worker.py
misc/python/materialize/sqlsmith.py
test/parallel-workload/mzcompose.py
test/sqlsmith/Dockerfile
test/sqlsmith/mzcompose.py

parallel-workload: Integrate SQLsmith action

---

test/upgrade-matrix/mzcompose.py

Forgotten in https://github.com/MaterializeInc/materialize/pull/22937
-

random-upgrade: Fix ssh tunnel

---

doc/user/content/sql/system-catalog/mz_internal.md
test/sqllogictest/autogenerated/mz_internal.slt

add docs for mz_activity_log

---

ci/deploy/npm.py

We currently tag the newest stable version of our WASM packages as `latest`, even if the version on npm is greater. This is seen when we create a patch release for the currently-deployed version of Materialize after we cut the next release candidate.
The `latest` tag allows tooling, such as dependabot, to track the latest stable version, so it is important we keep it accurate and don't unintentionally downgrade it.
-

npm: do not tag stable builds as latest if newer versions are published

---

src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/optimize/peek.rs

Previously this would have triggered the as_of overflow warning:
```
create view v as select 1;
select * from v;
```
Because that's a query not on a timeline, so we use the MAX timestamp which overflows when incremented.
Instead, detect if we are in a timeline with no timestamp and don't even try to set the until.
- n/a

adapter: improve GlobalMirPlan until resolution

---

Cargo.lock
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.78.0-dev

---

misc/python/materialize/scalability/benchmark_executor.py
misc/python/materialize/scalability/benchmark_result.py
misc/python/materialize/scalability/df/df_details.py
misc/python/materialize/scalability/df/df_totals.py
misc/python/materialize/scalability/df/df_totals_ext_cols.py
misc/python/materialize/scalability/df/df_wrapper_base.py
misc/python/materialize/scalability/plot/plot.py
misc/python/materialize/scalability/regression.py
misc/python/materialize/scalability/regression_outcome.py
misc/python/materialize/scalability/result_analyzer.py
misc/python/materialize/scalability/result_analyzers.py
misc/python/materialize/scalability/workload_result.py
test/scalability/lib.py
test/scalability/mzcompose.py

This should make handling data frames more robust and is the base for the boxplot fix.
Nightly for me to check if I broke things: https://buildkite.com/materialize/nightlies/builds/5078

scalability framework: introduce data-frame abstraction layer

---

src/lsp-server/src/backend.rs
src/lsp-server/tests/test.rs

Adds support to execute commands in the LSP server. This is useful to ask the LSP to parse SQL code and return the statements present in it. This solution is way better than alternative approaches like using regex to detect the start and end of a statement is more fault prone.
Related issue: https://github.com/MaterializeInc/vscode-extension/issues/113
-

lsp: adds execute command

---

misc/python/materialize/cli/ci_closed_issues_detect.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5131: ✅

ci: closed issues detector: add pattern for proto files

---

doc/user/content/releases/v0.76.md
doc/user/content/releases/v0.77.md

doc/user: polish v0.76 release notes

---

misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py

This addresses https://buildkite.com/materialize/nightlies/builds/5183#018bcb3c-a601-42a5-bd56-b2197161f62f.
Discussion in Slack: https://materializeinc.slack.com/archives/C02FWJ94HME/p1699948114602509

version consistency: add ignore for array_agg and string_agg

---

misc/python/materialize/cloudtest/util/jwt_key.py

this api endpoint is flaky sometimes (https://github.com/MaterializeInc/cloud/actions/runs/6853226483/job/18634602003 for instance)
ran this against my personal stack and it passed
- no user facing changes

retry fetching jwt from frontegg

---

misc/python/materialize/sqlsmith.py

Seen in: https://buildkite.com/materialize/nightlies/builds/5185

tests: sqlsmith: add ignore

---

ci/nightly/pipeline.template.yml
test/bounded-memory/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5226

tests: bounded memory: more appropriate setup

---

src/catalog/src/durable/impls/shadow.rs

The shadow catalog is a catalog implementation used for testing. Internally it has a stash and persist catalog implementation. On every operation it compares the results of each implementation and panics if there's a difference.
The Coordinator will update the timestamps of every timeline on a set interval, currently set to 10 seconds. Timestamps are currently stored in the catalog. If the Coordinator is shut down during this interval, then it's possible that only one of the catalog implementations updated the timestamps, while the other didn't. This makes it impossible to correctly test scenarios involving restarts with the shadow catalog.
This commit fixes this issue, by removing any discrepancies in the timestamps across the stash and persist when opening the catalog. The shadow …

catalog: Fix shadow timestamp discrepancies

---

misc/python/materialize/docker.py

I have seen some occurrences of
```
mz_other Pulling
mz_other Error
Error response from daemon: manifest for materialize/materialized:devel-6075ad714a6ae27d8a27cc525c5612b601b00eb4 not found: manifest unknown: manifest unknown
```
Some of these persist, some would be resolvable with retries.
This PR introduces using the latest release version instead of the merge base if the image of latter cannot be pulled.

ci: harden resolution of ancestor image

---

misc/python/materialize/mzbuild.py

Should be self-explanatory.
Reported by @mjibson [here](https://materializeinc.slack.com/archives/C01LKF361MZ/p1700169520341729)

Don't try to extract sources if we're not going to upload them

---

src/storage/src/source/postgres/replication.rs

This reverts commit 9105f9aa25404a86d92519b4d4c63acdac8d7559.
See: https://github.com/MaterializeInc/materialize/issues/23287
Reverting while we figure out how we want to move forward on this one.
-

[sources] Revert "Don't advance nonzero timestamps in the Postgres client"

---

doc/user/content/releases/v0.77.md
doc/user/content/releases/v0.78.md
doc/user/content/sql/create-connection.md
doc/user/content/sql/system-catalog/mz_internal.md

**WIP** Release notes for v0.77. 🎋 
@rjobanp @bobbyiliev: this covers the step of bumping the release version in the docs.

doc/user: polish v0.77 release notes

---

src/balancerd/src/lib.rs

The panic was leftover from when this happened at startup. Replicate the behavior of the frontegg resolver. Again, test-only change, not prod affecting.
- n/a

balancerd: error instead of panic on static lookup failure

---

src/storage-client/src/sink.rs

When we fetch the messages of the progress topic we do so with a 10 second timeout. If we reach that timeout while waiting for a message we successfully return the frontier that we have read so far. This is incorrect because we **know** what the latest offset in the topic is (from the metadata request) and so we should produce an error if we reach the timeout without finding the message we know exists.
-

kafka-sinks: insist on reading progress messages known to exist

---

misc/python/materialize/cli/scratch/__init__.py
misc/python/materialize/scratch.py

Minor improvements: see individual commits for rationales.
Taking github's suggestions for reviewers, since there's no owner... tell me if you're the wrong person to take a look!
-

[scratch] Tweaks to the scratch launcher

---

misc/cargo-vet/config.toml

https://materializeinc.slack.com/archives/CTESPM7FU/p1700603667743439

cargo-vet: add exemptions from merge-skew

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.79.0-dev

---

doc/developer/design/20231110_aws_connections.md

Design doc for https://github.com/MaterializeInc/materialize/issues/23055
Formatted version: https://github.com/MaterializeInc/materialize/blob/5fd810f0668ee7e91025f06894d0386cf9e86abd/doc/developer/design/20231110_aws_connections.md
@benesch This is roughly same as your sketch in the linked issue, main difference that this is introducing a new table `mz_aws_connections` to query for the principal and the external_id.
-

design doc: AWS Connection

---

src/storage/src/source/postgres.rs
src/storage/src/source/postgres/replication.rs

Revert 23335

---

src/adapter/src/coord.rs

Currently we trace an error, "Coordinator is stuck" when the coordinator hasn't been able to reach the bottom of its queue for more than 60 seconds. This PR extends that error trace to include the type of the last message the Coordinator processed.
Note: I don't love having a Mutex in this path, the other idea I had was to add a method, `fn kind_int(&self)` to the coordinator's `enum Message`, and then we could use an atomic int. But I wasn't sure how much of that was maybe a pre-mature optimization, more than happy to make this change if anyone thinks we should.
It makes debugging Coordinator hangs easier, because we know what its hung on.
-

coordinator: Record last message we ran

---

misc/python/materialize/buildkite_costs/README.md
misc/python/materialize/buildkite_costs/check.py
misc/python/materialize/buildkite_costs/stats.py

In case it's going to be useful for other use cases, see for example https://materializeinc.slack.com/archives/C057X0NG91B/p1700468133619509
-

scripts: Add buildkite costs scripts

---

misc/python/materialize/cli/ci_logged_errors_detect.py

Seen in https://buildkite.com/materialize/tests/builds/69432#018bf97d-82e9-4113-91bb-f839164d65af
-

ci: Don't try to annotate > 1 MB

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/mzcompose/services/ssh_bastion_host.py
misc/python/materialize/zippy/framework.py
misc/python/materialize/zippy/scenarios.py
misc/python/materialize/zippy/source_actions.py
misc/python/materialize/zippy/source_capabilities.py
test/zippy/mzcompose.py

This adds the `AlterSourceConnection` scenario to zippy.
Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Falter-connection-for-zippy

tests: alter connection for zippy

---

src/catalog/src/durable/impls/persist.rs

This commit fixes the persist catalogs logic for applying updates. Previously, the catalog would apply updates within a single timestamp in whatever order they arrived, which in general is not correct. For example imagine the following two updates coming in at a single timestamp:
a. key, old_value, ts, -1
b. key, new_value, ts, +1
Applying them in the order (a) then (b) is correct, we first remove the old value from our in-memory map and then insert the new value. However, applying them in the order (b) then (a) is not correct, we first overwrite the old value with the new value in our in-memory map and then remove the new value. We must apply the retractions before the insertions.
Furthermore, if updates in a single timestamp are not consolidated, then it's not enough to apply the …

catalog: Fix persist update apply

---

doc/user/assets/sass/_content.scss

In the `JSON to SQL` section of the documentation, when an error occurs, it appears over the text, making it difficult to read and select the text underneath for troubleshooting.
<details>
<summary>Current</summary>
<br>
</details>
This PR changes the style to make it look as follows:
<details>
<summary>New</summary>
<br>
</details>
-

doc/user: style error json

---

src/persist-txn/src/txn_read.rs
src/storage-controller/src/lib.rs

Instead of rehydrating a TxnsCache for each of these calls, talk to a shared TxnsCache sitting in a task worker.
Touches https://github.com/MaterializeInc/materialize/issues/22173
Touches https://github.com/MaterializeInc/materialize/issues/22801
-

persist-txn: use new TxnsRead task worker to serve storage snapshots

---

src/catalog/src/durable/impls/persist.rs

While opening a persist catalog, we sometimes end up getting a snapshot multiple times at the same timestamp. This commit caches catalog snapshots during opening to avoid hitting persist multiple times for the same data.
Works towards resolving #22392

catalog: Cache persist snapshot during open

---

src/adapter/src/catalog.rs

This should allow the underlying error message to be displayed instead of the drop panic.
This should fix the specific problem found in https://github.com/MaterializeInc/materialize/issues/19931#issuecomment-1824071628 and let us discover whatever is beneath it.
- n/a

adapter: drop debug stash on error

---

misc/python/materialize/cli/ci_logged_errors_detect.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/23320
I previously assumed the entire panic message would be flushed at once, but this is not the case. Fixing this as a regex would have been messy and slow, assuming I even managed it.
Fixes: #23484
-

ci-logged-errors-detect: Handle interleaved panics

---

src/persist-txn/src/txn_cache.rs

This adds a test for the following bug, but I'm still deciding how to fix it, so marking it as ignored for now.
- Commit a write at 5
- Apply it and commit the tidy retraction at 20.
- Catch up to both of these in the TxnsHandle and call compact_to(10). The TxnsHandle knows the write has been applied and lets it CaDS the txns shard since to 10.
- Open a TxnsCache starting at the txns shard since (10) to serve a snapshot at 12. Catch it up through 12, but _not_ the tidy at 20.
- This TxnsCache gets the write with a ts compacted forward to 10, but no retraction. The snapshot resolves with an incorrect latest_write of `Some(10)`.
- The unblock read waits for this write to be applied before doing the empty CaA, but this write never existed so it hangs forever.
Touches …

persist-txn: regression test for a bug caught by higher level CI tests

---

Cargo.lock
misc/cargo-vet/audits.toml
src/compute/src/compute_state.rs
src/compute/src/extensions/arrange.rs
src/compute/src/extensions/reduce.rs
src/compute/src/logging/compute.rs
src/compute/src/render/context.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/join/mz_join_core.rs
src/compute/src/render/mod.rs
src/compute/src/render/reduce.rs
src/compute/src/render/threshold.rs
src/interchange/src/envelopes.rs
src/timely-util/src/operator.rs

Update our dependency on Differential to match upstream changes.
-

Update DD and mirror the trait reorg

---

doc/developer/design/20231110_aws_connections.md

Flesh out the design of the `mz_aws_connections` table.
Also rename `MaterializeCloudConnectionAssumeRole` to `Materialize` to be more concise and more clear from the customer's perspective.
* This PR updates an existing design document.
- n/a

doc/developer: specify design of `mz_aws_connections`

---

misc/cargo-vet/audits.toml

Explicitly maps the MZ 'maintained-and-necessary' audit criteria to 'safe-to-deploy' status.
Change fixes cargo vet behavior and allows certification of crates using only our custom audit criteria.

Map new cargo vet policy to safe-to-deploy

---

.github/workflows/slack_notify_qa_risky.yml

slack-notify: Fix before and after events

---

misc/images/jobs/.gitignore
misc/images/jobs/Dockerfile
misc/images/jobs/mzbuild.yml

Works towards resolving #23575

catalog: Add catalog-debug tool to docker image

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

for https://github.com/MaterializeInc/materialize/issues/23586

postgres consistency: add ignore

---

ci/test/pipeline.template.yml

I will try a build since we are on rust 1.74.

ci: activate CARGO_BUILD_JOBS = "default"

---

ci/nightly/pipeline.template.yml

See https://github.com/MaterializeInc/materialize/issues/23608#issuecomment-1836583778

ci: Checks + backup + rollback to previous: update referenced issue in exclude

---

misc/python/materialize/checks/all_checks/alter_connection.py

Need some adjustment, to be done with https://github.com/MaterializeInc/materialize/issues/23613.

ci: platform checks: disable alter connection tests again

---

misc/python/materialize/checks/scenarios_upgrade.py

Seen in https://buildkite.com/materialize/nightlies/builds/5466#018c2fa9-0ff3-413e-9767-036b96bca82a
-

platform-checks: Fix UpgradeEntireMzFourVersions

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml
test/pg-cdc-resumption/mzcompose.py

See individual commit messages.
Increase the speed of the CI by moving jobs around.

CI Christmas cleaning 2023

---

ci/slt/pipeline.template.yml
ci/test/pipeline.template.yml

https://buildkite.com/docs/tutorials/parallel-builds
-

buildkite: Start job numbers at 1 instead of 0

---

misc/python/materialize/cli/ci_closed_issues_detect.py
misc/python/materialize/output_consistency/data_type/data_type.py
misc/python/materialize/output_consistency/data_value/data_column.py
misc/python/materialize/output_consistency/data_value/data_value.py
misc/python/materialize/output_consistency/generators/expression_generator.py
misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/boolean_operation_param.py
misc/python/materialize/output_consistency/input_data/params/date_time_operation_param.py
misc/python/materialize/output_consistency/input_data/params/number_operation_param.py
misc/python/materialize/output_consistency/input_data/params/text_operation_param.py
misc/python/materialize/output_consistency/input_data/test_input_data.py
misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
misc/python/materialize/output_consistency/input_data/validators/number_args_validator.py
misc/python/materialize/output_consistency/operation/operation.py
misc/python/materialize/output_consistency/output_consistency_test.py
misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py

d9247496ce output consistency: print input data stats
a6d3f935fb output consistency: rename field
a50d587c50 output consistency: wrap operations in parentheses
1eae875ec0 output consistency: disable parse_ident
b482d0d1d8 postgres consistency: reformat
5dbb2ec0c7 ci: closed issues detector: add pattern

output consistency: miscellaneous adjustments

---

misc/python/materialize/output_consistency/data_type/data_type_category.py
misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/params/jsonb_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/jsonb_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/jsonb_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/jsonb_values_provider.py
misc/python/materialize/output_consistency/operation/operation_param.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5510

output consistency: add JSONB type

---

misc/python/materialize/output_consistency/data_type/data_type_category.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/bytea_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/crypto_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/bytea_operation_param.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/return_specs/bytea_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/bytea_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/bytea_values_provider.py
misc/python/materialize/output_consistency/validation/error_message_normalizer.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5513

output consistency: add BYTEA type

---

misc/python/materialize/cli/ci_logged_errors_detect.py

ci: Detect unknown system parameters

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.80.0-dev

---

doc/user/content/manage/monitor/alerting.md

This PR intends to only document alerting threshold for monitoring Materialize.
Related issue: https://github.com/MaterializeInc/materialize/issues/22921#issuecomment-1822603777
-

doc/user: alerting

---

doc/user/config.toml

This PR fixes a known issue.
-

doc/user: fix sql server index

---

doc/user/content/releases/v0.78.md
doc/user/content/releases/v0.79.md

**WIP** Release notes for v0.78. 🪨 
@edude03 @joacoc: this covers the step of bumping the release version in the docs.

doc/user: polish v0.78 release notes

---

src/adapter/src/catalog/state.rs

Materialize currently has a bug that all types are put into the `pg_catalog` schema. For example, the following query works: `SELECT 1::pg_catalog.mz_timestamp;`, but the following does not: `SELECT 1::mz_catalog.mz_timestamp;`. `mz_timestamp` is in the `mz_catalog` schema and therefore the second query should work and the first should fail.
We can fix this bug and write a migration to fix the types in all persisted views, but that will not let us know who in production is manually specifying the `pg_catalog` schema for these types in `SELECT` queries.
This commit adds a warn log to identify any time a user specifies the `pg_catalog` schema for a type that should live in a different schema.
Works towards fixing #23833
- There are no user-facing …

catalog: Add warning for specifying wrong schema

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

I will reach out to the adapter team to see if we can get the underlying cause fixed.

postgres consistency: extend ignores regarding JSONB whitespaces

---

doc/user/content/manage/troubleshooting.md

Fix documentation typo for the 'snapshot_committed' field

---

src/adapter/src/flags.rs
src/kafka-util/src/client.rs
src/postgres-util/src/tunnel.rs
src/sql/src/session/vars.rs
src/ssh-util/Cargo.toml
src/ssh-util/src/tunnel.rs
src/ssh-util/src/tunnel_manager.rs
src/storage-types/src/connections.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs

Part of https://github.com/MaterializeInc/materialize/issues/18683
(the bottom commit of https://github.com/MaterializeInc/materialize/pull/23595 made this wayyyy easier)
-

storage/ssh: make connect timeout and friends configurable

---

test/bounded-memory/mzcompose.py
test/feature-benchmark/scenarios.py

* Discussion: https://materializeinc.slack.com/archives/C01LKF361MZ/p1702302315673959
* Notion: https://www.notion.so/materialize/Memory-Attribution-in-Accumulable-Reductions-800f3625893949f189e22f289aa0e2bf#24e5aa90e5aa49c4ba4d39eb45a9c5e7
Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fmemory-attribution-accumulate-reductions

tests: add scenario "accumulate reductions" to bounded memory and feature benchmark

---

misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/output_consistency/operation/operation.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

* allow basing ignores on tags
* include two more regex operators in ignore
* rework JSONB ignore

output consistency: improve and extend ignores

---

src/mz/src/command/sql.rs

Removes the connection info on connect for `mz sql`. The info message is now embedded in the `psql` connection.
Current issue:
```
$ mz sql
Authenticated using profile 'Sandbox'.
Connected to the default cluster.
NOTICE:  connected to Materialize v0.79.1
Org ID: <Redacted>
Region: aws/us-east-1
User: joaquin@materialize.com
Cluster: default
Database: materialize
Schema: public
```
-

mz: remove comment on connect.

---

doc/user/content/manage/blue-green.md

Adds docs for the initial version of Blue/Green.
Preview: https://preview.materialize.com/materialize/23494/manage/blue-green/
-

doc/user: Add blue-green.md

---

misc/python/materialize/docker.py

ffbfaa611c ci: image check: rename (from https://github.com/MaterializeInc/materialize/pull/23893)
5edfed99d2 ci: image check: use cache for images known to exist
66dc3cfd09 ci: image check: use cache also for images known not to exist

ci: version resolution: cache image checks

---

misc/python/materialize/cli/ci_closed_issues_detect.py
src/expr/src/explain/text.rs
src/repr/src/explain/mod.rs

The ignore was introduced with https://github.com/MaterializeInc/materialize/pull/23861.
See also: https://github.com/MaterializeInc/materialize/pull/23918

ci: do not ignore closed cloud issues

---

doc/user/content/manage/blue-green.md
doc/user/content/releases/v0.78.md
doc/user/content/releases/v0.79.md
doc/user/content/releases/v0.80.md

Release notes for v0.79. 🎁 
@evanharmon @petrosagg: this covers the step of bumping the release version in the docs.

doc/user: polish v0.79 release notes

---

src/environmentd/tests/sql.rs

See newly added comment in code: as previously written this test was flaky because updating the retention interval would not propagate instantaneously.
Dan's work on enabling `persist_txn_tables=lazy` in ci/nightly seems to have tickled this test some more, likely because propagation of `uppers` can take ever so slightly longer.

envd: add retries in test_utilization_hold

---

test/bounded-memory/mzcompose.py
test/feature-benchmark/scenarios.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/23829.
Nightlies: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fmemory-attribution-accumulate-reductions-2

tests: accumulate reductions: follow-up

---

src/compute/src/logging/compute.rs

This PR fixes a memory leak in compute delay logging caused by the logging dataflow relying on the assumption that import frontiers report for a dataflow are always in advance of export frontiers reported for the same dataflow so far. This isn't always correct because dataflow operators can advance their output frontiers beyond their input frontiers, and `persist_sink` in particular is known to do this.
The wrong assumption caused us to accumulate entries in the `time_deque` when a multi-worker replica had materialized views installed.
This is fixed now by checking the export frontier first before pushing a new entry to `time_deque`. If the export frontier is advanced past the frontier we would push, we refrain from pushing it instead.
Fixes …

compute: fix memory leak in delay logging

---

misc/python/materialize/checks/all_checks/optimizer_notices.py

Optimizer notices are not available in v0.80
Nightly was failing

platform-checks: Adjust version check in optimizer_notices.py

---

test/cloudtest/test_full_testdrive.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5638

tests: allow running individual testdrive test in cloudtest

---

ci/slt/pipeline.template.yml
test/sqllogictest/materialized_views.slt
test/sqllogictest/mztimestamp.slt

Various SLT fixes/workarounds

---

ci/test/pipeline.template.yml

See https://buildkite.com/materialize/tests/builds/71536#018c81a7-9948-42d4-9045-815f946663b4
-

buildkite: Make legacy upgrade wait for build

---

misc/python/materialize/cli/run.py

When running sqllogictests in CI we use `mzcompose` which sets system defaults using the `MZ_SYSTEM_PARAMETER_DEFAULT` environment variable, but we do not set these system defaults when running via `bin/environmentd`. This causes a skew in how tests can get run locally via and how they get run in CI.
Currently on `main` running `bin/sqllogictest` for `cluster.slt` does not pass, because we expect a replica to get created with a disk, but it does not because the  system param isn't set.
- N/a, internal testing changes

test: Set MZ_SYSTEM_PARAMETER_DEFAULT when running bin/sqllogictest

---

misc/python/materialize/mzcompose/services/sql_logic_test.py

Should cause some speedup on slow disks
As discussed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1702921130517769
-

slt: Use tmpfs for /tmp

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py

parallel-workload fixes

---

Cargo.lock
ci/slt/pipeline.template.yml
src/sqllogictest/Cargo.toml
src/sqllogictest/src/runner.rs

sqllogictest: enable persist PubSub in SLT

---

misc/python/materialize/lint/lint.py

Before: https://asciinema.org/a/gMDcaKVkDU24uPt9qoBm0fbXW
After: https://asciinema.org/a/4aCpfXSKOYypI6cy3i2Id4mzv
I wanted the output to be less noisy on terminal.
-

ci: Beautify bin/lint

---

ci/nightly/pipeline.template.yml
misc/python/materialize/zippy/mz_actions.py
misc/python/materialize/zippy/scenarios.py
test/zippy/mzcompose.py

Relates to #24027
Toggling persist-txn back and forth has been identified as a potential source for bugs.

zippy: Add a scenario that toggles persist-txn

---

src/avro/src/schema.rs
test/testdrive/avro-resolution-logical-type-default.td

Automerge caused #24094 to merge with some minor outstanding feedback. This commit addresses that feedback.
* This PR addresses code review feedback.
- n/a

avro: address code review follow up from #24094

---

ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/post-command
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-txn/src/operator.rs
src/persist/src/mem.rs

Touches https://github.com/MaterializeInc/materialize/issues/22173
Touches https://github.com/MaterializeInc/materialize/issues/22801
-

persist-txn: fix and re-enable maelstrom tests

---

src/transform/src/normalize_lets.rs

Our let normalization's type refresh needs expressions to be in "letrec-major" form or it will error. This form is introduced by `let_motion::promote_let_rec`, but it is potentially undone by `inlining::inline_lets`. We should refresh types between our calls to `promote_let_rec` and `inline_lets`.
NB: There might be other undocumented reasons the code was in the other order to begin with, but putting this up to see what the tests think.
-

Refresh types while in letrec major

---

doc/user/content/sql/system-catalog/mz_internal.md
src/catalog/src/builtin.rs
src/storage-client/src/healthcheck.rs
test/sqllogictest/autogenerated/mz_internal.slt

fixes https://github.com/MaterializeInc/materialize/issues/24100

rename "statement_kind" to "statement_type"

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.82.0-dev

---

ci/nightly/pipeline.template.yml

ci: Fix typo in buildkite step id

---

src/catalog/src/durable/impls/migrate.rs
src/catalog/tests/migrate.rs

All existing environments will have an initialized stash catalog and an uninitialized persist catalog. Therefore, reading a value before opening the catalog will successfully identify the stash catalog as the source of truth and read the value from the stash. However, when opening a savepoint catalog, the `CatalogMigrator` will attempt to open both the stash and persist in savepoint mode. The stash will succeed but persist will fail because persist is uninitialized. This will mistakenly cause the upgrade checker to think that an upgrade will fail because the catalog is initialized (the result of a read from the stash), but opening the catalog in savepoint mode fails.
This commit fixes this issue by allowing the `CatalogMigrator` implementation to open a savepoint catalog when persist is …

catalog: Fix migrate savepoint implementation

---

ci/mkpipeline.py

https://buildkite.com/docs/pipelines/controlling-concurrency
-

ci: Use concurrency groups to prevent duplicate builds

---

misc/python/materialize/version_list.py

ci: Ignore v0.81.[0-2]

---

doc/user/content/ingest-data/warpstream.md
doc/user/content/releases/v0.81.md
doc/user/content/releases/v0.82.md
doc/user/content/sql/create-connection.md
doc/user/content/sql/system-catalog/mz_internal.md

Release notes for v0.81. 🎆
@jpepin @bobbyiliev: this covers the step of bumping the release version in the docs.

doc/user: polish v0.81 release notes

---

doc/user/content/sql/system-catalog/mz_internal.md
src/adapter/src/catalog/state.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/statement_logging.rs
src/adapter/src/statement_logging.rs
src/catalog/src/builtin.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs
src/sql/src/session/vars.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
test/cluster/mzcompose.py
test/cluster/statement-logging/statement-logging.td
test/sqllogictest/autogenerated/mz_internal.slt
test/sqllogictest/information_schema_tables.slt
test/sqllogictest/privilege_grants.slt
test/testdrive/catalog.td

Note: this is not ready to merge, as I have still not figured out a good strategy for testing it. However, itt should be ready for review.
Fixes https://github.com/MaterializeInc/materialize/issues/23314
@MaterializeInc/testing , I'd appreciate your help with a testing strategy for this. Any ideas?
https://github.com/MaterializeInc/materialize/pull/23670
- None yet since we have not turned on the feature flag

Statement lifecycle logging

---

misc/python/materialize/mzcompose/composition.py

As noticed in https://materializeinc.slack.com/archives/C05SLRXKNGN/p1704364232485329?thread_ts=1704209739.747349&cid=C05SLRXKNGN
Hopefully this is the final fix. I can't think of a better way to solve it yet, but this is probably my third attempt.
-

mzcompose: One compose file per thread

---

test/cluster/mzcompose.py

To make tests pipeline less flaky.
-

cluster test: Expect error in blue-green-deployment test 

---

ci/mkpipeline.py

Since default might have bad autoscaling. See also https://github.com/MaterializeInc/i2/pull/1507
-

ci: Set linux-x86_64 agents queue by default

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.83.0-dev

---

misc/python/materialize/checks/all_checks/materialized_views.py
misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/zippy/sink_actions.py
misc/python/materialize/zippy/view_actions.py
test/sqllogictest/materialized_views.slt
test/sqlsmith/mzcompose.py

Additional tests for REFRESH option in MVs

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

https://github.com/MaterializeInc/materialize/issues/22024 was implemented.
Nightly: https://buildkite.com/materialize/nightlies/builds/5879

postgres consistency: remove #22024 ignore (min/max for time)

---

doc/user/content/manage/blue-green.md

Hugo incorrectly formats the code in the blue/green deployments section, so I added two tabs to fix the issue.
I updated the hydration section to reference the new view mentioned in the notes (`mz_hydration_statuses`). I changed 'Blue/Green' to the lowercase version 'blue/green.' If this was intentional and I am making a mistake, I will revert it immediately.
-

doc/user: b/g deployments

---

src/ccsr/tests/client.rs

to unflake tests pipeline, see https://github.com/MaterializeInc/materialize/issues/22557
-

 unit tests: disable test_client_errors

---

misc/python/materialize/cloudtest/app/materialize_application.py
test/cloudtest/test_storage.py

This extracts some refactoring logic from https://github.com/MaterializeInc/materialize/pull/20491 to uncrowd that PR and land the changes.
The changes have already been reviewed in that PR.

cloudtests: pull methods into mz_application

---

ci/nightly/pipeline.template.yml
test/persist-txn-fencing/mzcompose.py
test/rqg/mzcompose.py

Misc fixes to the rqg mzcompose and adding a new workload.
The RQG allows some concurrency + correctness testing so I wanted to get this into Buildkite in order to confirm that it runs green for the remainder of the month.
This PR can be reviewed commit by commit.

rqg: Add the banking workload to the CI

---

misc/python/materialize/buildkite_insights/costs/extract_stats.py

buildkite-insights: Update instances in costs script

---

test/rqg/mzcompose.py

This is needed so that a grammar that habitually generates `SELECT`s can be used to generate `EXPLAIN SELECT`s without changing anything else about the workload.
The grammar needs to define a rule like this:
```
explain:
select
;
select:
SELECT ...
;
```
and then you can call the mzcompose file with `--starting-rule=explain`

rqg: Allow the grammar and grammar starting rule to be overridden

---

test/cluster/blue-green-deployment/deploy.td
test/cluster/blue-green-deployment/setup.td
test/cluster/mzcompose.py

As suggested in https://materializeinc.slack.com/archives/C05SLRXKNGN/p1704793458904549
-

blue-green deployment test: Exclude sources

---

ci/test/pipeline.template.yml

OoM in https://buildkite.com/materialize/tests/builds/72756#018cf40f-ff86-41f1-be56-8bee7ea8e2cc
-

ci: Increase agent size for chbench smoke test again

---

src/adapter/src/coord.rs

This PR adds a Drop impl to the `LastMessage` struct that we use for slow message tracking, to also print stderr if we're panicking while getting dropped.
When the Coordinator panics it is very likely that we will not record the last run statement as part of statement logging. This is a last ditch effort to capture debug info about what the Coordinator was doing when we panicked.
- N/a, internal debugging change

coord: Dump the LastMessage to stderr if the Coordinator panics

---

test/rqg/Dockerfile
test/rqg/mzcompose.py

- Also, attempt query simplification on any problematic queries
-

rqg: Update to the latest simple-aggregates.yy scenario

---

test/upsert/rocksdb-cleanup/drop-source.td

This addresses https://buildkite.com/materialize/nightlies/builds/5940#018cf881-467f-4dba-bd67-e4e9151be981.
Nightly: https://buildkite.com/materialize/nightlies/builds/5941

tests: fix merge skew

---

test/cluster/mzcompose.py
test/pg-cdc/pg-cdc.td

ci: Unflake tests pipeline

---

src/environmentd/src/lib.rs

Joe did the hard work in #24334 of making this available at boot time, so may as well use it for persist-txn too.
Touches #22173
-

persist-txn: use latest LD value at boot if available

---

doc/developer/design/20231204_query_lifecycle_events_logging.md

This mostly just restates the work @chaas did writing https://github.com/MaterializeInc/materialize/issues/23314 .

Add short design doc for query lifecycle events

---

doc/user/content/manage/access-control/rbac.md
doc/user/content/sql/alter-role.md
doc/user/content/sql/alter-system-set.md
doc/user/layouts/partials/sql-grammar/alter-role-attributes.svg
doc/user/layouts/partials/sql-grammar/alter-role-variables.svg
doc/user/layouts/partials/sql-grammar/alter-role.svg
doc/user/layouts/shortcodes/session-variables.html
doc/user/layouts/shortcodes/system-variables.html
doc/user/sql-grammar/sql-grammar.bnf

This PR adds docs for the `ALTER ROLE ... SET ...` feature and documents that `ALTER SYSTEM SET ...` can be used to change the defaults for session variables.
Fixes https://github.com/MaterializeInc/materialize/issues/22107
- Updates user documentation for the `ALTER ROLE ... SET ...` feature, and documents the session defaults can be modified via `ALTER SYSTEM SET ...`

docs: Add docs for `ALTER ROLE ... SET ...` and `ALTER SYSTEM SET` for session variables

---

doc/developer/design/20231117_copy_to_s3.md

Rendered version: https://github.com/moulimukherjee/materialize/blob/design-doc-copy-to-s3/doc/developer/design/20231117_copy_to_s3.md
We want to support a one time export of a snapshot to s3 https://github.com/MaterializeInc/materialize/issues/7256
-

Design doc copy to s3

---

.config/nextest.toml

cargo test: Increase timeout for storage_command_protobuf_roundtrip

---

misc/python/materialize/checks/scenarios_persist_txn.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/zippy/scenarios.py
test/persist-txn-fencing/mzcompose.py

Switch between `off`, `eager` and `lazy` either randomly or in this particular order.
-

persist-txn: Add scenarios around the `lazy` setting

---

misc/python/materialize/cli/mzcompose.py

mzcompose: Remove non-existant links

---

test/rqg/Dockerfile

I had some changes to the RQG's query simplification algorithm that were sitting locally.

rqg: Use the latest simplification algorithm

---

.config/nextest.toml

#24381 is fixed.
https://buildkite.com/materialize/nightlies/builds/5962#018cfda7-870b-4c95-8cbd-c962cb928423

cargo test config: remove temporary fix

---

test/feature-benchmark/mzcompose.py
test/feature-benchmark/scenarios.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5961

feature benchmark: fix ExactlyOnce scenario

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release v0.83 is happening this week

release: bump to version v0.84.0-dev

---

src/persist-client/src/operators/shard_source.rs

Cap the amount of auditing work a persist_source does by introducing a "budget", which is only increased when we choose to fetch a part. This means that, in the ~worst case, we'll spend as much effort auditing as we do decoding data we expect to care about.
https://github.com/MaterializeInc/materialize/issues/22470#:~:text=Constant%2Doverhead%20auditing
There are lots of different ways you could interpret the requirement, but this was the simplest one that seemed good enough to me. (And this doesn't feel like somewhere we want to spend a ton of complexity.)
I'll run this through staging and confirm that this limits resource use even when the audit percentage is high.
-

Limit the number of bytes we're willing to audit

---

misc/python/materialize/sqlsmith.py

sqlsmith: Expect new create-mv error

---

doc/user/content/releases/v0.82.md
doc/user/content/releases/v0.83.md
doc/user/content/sql/create-cluster.md

v0.82 release
- no user facing changes

doc/user: polish v0.82 release notes

---

misc/python/materialize/mzcompose/__init__.py

030d85f020 ci: enable enable_cc_cluster_sizes
3cc3b5ea77 ci: enable wait_catalog_consolidation_on_startup
39bfb43c41 ci: enable enable_statement_lifecycle_logging
https://github.com/MaterializeInc/materialize/pull/24423 needs special attention.
https://buildkite.com/materialize/nightlies/builds/5993

ci: enable new feature flags

---

misc/python/materialize/mzcompose/__init__.py
test/cloudtest/test_compute.py
test/cloudtest/test_system_clusters.py

Nightly: https://buildkite.com/materialize/nightlies/builds/5986

ci: enable cluster_always_use_disk

---

src/timely-util/src/builder_async.rs

It's beneficial to consolidate two consecutive progress statements into one if the operator hasn't seen the previous progress yet. This also avoids accumulation of progress statements in the queue if the operator only conditionally checks its input.
Fixes https://github.com/MaterializeInc/materialize/issues/24452
-

timely-util: consolidate consecutive progress statements

---

misc/python/materialize/scalability/endpoint.py
misc/python/materialize/scalability/endpoints.py
test/scalability/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6002

scalability framework: communicate through balancerd

---

src/persist-txn/src/operator.rs

No matter how many times we step the dataflow, it's not enough to guarantee that it doesn't pause while holding some critical mutex/semaphore. Instead keep it constantly stepping in the background by moving it into a task.
Touches #22173
-

persist-txn: deflake data_subscribe unit test

---

src/mysql-util/src/schemas.rs

This was slightly bothering me :sweat_smile: 
-

mysql-util: validate the expected row shape

---

src/persist/src/postgres.rs

Previously, connecting to persist required a CRDB user with enough privileges to alter the `consensus` table in CRDB. The ALTER statement is meant as a performance improvement and is a no-op for every user except the first user that connects to persist. This requirement prevented users who only wanted to read from persist and only had CRDB users with SELECT privileges from connecting to persist. Connecting as a read-only user would be especially useful for the catalog-debug and persist-cli tools.
This commit updates the persist connection process, so that CRDB users without the privileges to run ALTER can still connect and read from persist.

persist: Allow read-only users to connect to persist

---

test/rqg/mzcompose.py

Certain options are useful for tackling RQG failures.

rqg: Expose additional troubleshooting options

---

src/environmentd/src/lib.rs

Previously, if catalog implementation A was initialized, implementation B was uninitialized, we tried to open a savepoint catalog using the `CatalogMigrator` implementation, and our target implementation was B, then the savepoint would fail to open. The savepoint catalog is unable to work with uninitialized catalogs and is therefore unable to perform an upgrade check when a migration/rollback is needed. Instead of failing startup, this commit will not attempt to perform an upgrade check in this scenario.
Works towards resolving #24218

catalog: Fix upgrade check during migrations

---

Cargo.lock
src/tracing/Cargo.toml

https://buildkite.com/materialize/nightlies/builds/6020#018d1767-6247-4a14-aa69-50c0c7ca90a1

dependencies: mz-tracing: remove proptest-derive

---

src/catalog-debug/src/main.rs

catalog-debug: Add timing to upgrade check

---

test/cluster/blue-green-deployment/deploy.td
test/cluster/blue-green-deployment/setup.td

cluster tests: Use REFRESH EVERY with blue/green deployment

---

test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt

This fixes https://buildkite.com/materialize/sql-logic-tests/builds/5808.
Build: https://buildkite.com/materialize/sql-logic-tests/builds/5809

tests: fix 3_number_aggfns_dataflow.slt

---

misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/values/jsonb_values_provider.py

Builds: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fadd-jsonb-fun

output consistency: add jsonb operations

---

misc/python/materialize/output_consistency/input_data/operations/date_time_operations_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6070
Identified and ignored issue: https://github.com/MaterializeInc/materialize/issues/24578

output consistency: add date-time operations

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs

So far the compute controller considered a collection dropped when its read frontier has advanced to the empty frontier. This had the defect that we might remove a collection's state from the controller in response to a client setting a `ReadPolicy::ValidFrom([])`. A client might still expect to be able to query information about a collection even when it is not interested in reading data from it anymore.
To remove this defect, a `CollectionState::dropped` flag is introduced and used to explicitly mark collections as dropped when `drop_collections` is called. Only collections that have the `dropped` flag set are then considered for having their controller state dropped.
Figuring out the right places in which to check the collection state removal conditions becomes a bit of a hassle with …

compute-client: add an explicit drop flag for collections

---

misc/python/materialize/output_consistency/data_value/data_column.py
misc/python/materialize/output_consistency/enum/enum_constant.py
misc/python/materialize/output_consistency/expression/expression.py
misc/python/materialize/output_consistency/expression/expression_with_args.py
misc/python/materialize/output_consistency/query/query_template.py
misc/python/materialize/output_consistency/validation/result_comparator.py

Needed to have more flexibility when the Postgres syntax differs.

output consistency: provide SqlDialectAdjuster to to_sql

---

src/compute/src/render/reduce.rs

This PR performs improvements to the spine types in selected type-based dispatch calls in reduce. Most improvements are concentrated in bucketed reductions, where only the first level of a hierarchy of arrangements is left at `RowValSpine`, while all remaining levels can use `RowRowSpine`. Additionally, a refactoring envisioning reuse is done on
merges and splits of `(key, hash)` pairs.
The first commit is from #24375 and can be ignored. Only the fourth commit is relevant here.
You probably want to hide whitespace when reviewing, as `cargo fmt` changed  indentation of a code block.
-

Improve bucketed negated spine

---

doc/user/content/releases/v0.83.md
doc/user/content/releases/v0.84.md
doc/user/content/sql/system-catalog/mz_internal.md

doc: set `v0.83.4` as released

---

src/catalog/src/durable/transaction.rs

This commit is a follow up to 91aed6f6e2363749b682b9cb0ae89f111a18a307, that removes two unnecessary allocations.
Perf optimization.

catalog: Remove allocations

---

src/catalog/src/durable/impls/shadow.rs

The timestamp collection and the storage usage collection are updated on a regular frequency. As a result, if the shadow catalog happens to stop after updating one catalog but not the other, those two collections can diverge. To fix this, the shadow catalog has a reconciliation process on boot that fixes any discrepancies found in these collections.
This commit fixes on off by one error in the storage usage collection reconciliation and adds tests for both reconciliation processes.
Fixes #24523

catalog: Fix shadow catalog reconciliation

---

ci/release-qualification/pipeline.template.yml

ci: Group release qualification pipeline

---

misc/python/materialize/output_consistency/data_type/data_type.py
misc/python/materialize/output_consistency/enum/enum_constant.py
misc/python/materialize/output_consistency/enum/enum_data_type.py
misc/python/materialize/output_consistency/execution/sql_dialect_adjuster.py
misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/postgres_consistency/execution/pg_dialect_adjuster.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6098

output consistency: add cast operation

---

src/compute-client/src/service.rs

This PR makes the following changes to `PartitionedComputeState`, following up on the addition of `max_result_size` checking:
* It moves the state updating in response to `UpdateConfiguration` into `observe_command`.
* It changes the state updating logic to interpret `max_result_size = None` to mean the absence of an update, since these are the documented semantics of the `ComputeParameters`.
* It makes the `max_result_size` field a `u64` rather than an `Option`, for simplicity and for consistency with the same field in `ComputeState`.
* It adds a comment referencing #24629, which is a known defect with the current implementation of the limit.
- N/A

compute-client: follow-ups for #24619

---

misc/python/materialize/output_consistency/execution/query_execution_manager.py
misc/python/materialize/output_consistency/execution/test_summary.py
misc/python/materialize/output_consistency/validation/result_comparator.py
misc/python/materialize/output_consistency/validation/validation_message.py
misc/python/materialize/output_consistency/validation/validation_outcome.py
test/output-consistency/mzcompose.py
test/postgres-consistency/mzcompose.py
test/version-consistency/mzcompose.py

Demo build: https://buildkite.com/materialize/nightlies/builds/6072

output consistency: provide failures to mzcompose for junit.xml

---

doc/user/content/releases/v0.84.md
doc/user/content/releases/v0.85.md

Release notes for v0.84. 🪴 
@arusahni @aalexandrov: this covers the step of bumping the release version in the docs.

doc/user: polish v0.84 release notes

---

ci/test/cargo-test/mzcompose.py

Reverts MaterializeInc/materialize#24637
Unfortunately failed again once: https://buildkite.com/materialize/tests/builds/73901

Revert "ci: Try speeding up cargo test again"

---

src/compute-client/src/protocol/command.rs
src/compute-client/src/service.rs
src/compute/src/server.rs

This PR makes the `PartitionedComputeState` broadcast `UpdateConfiguration` commands to all shards, not just the first one. The purpose is to ensure that all parts of the compute networking stack are able to observe configuration updates.
Unfortunately, this makes the compute protocol more complex by introducing another special case. We now have this situation:
* `CreateTimely` is broadcast and accepted by all worker threads.
* `UpdateConfiguration` is broadcast but only accepted by the first worker thread (and ignored by the others).
* All other commands are only sent to the first worker thread.
I still think that one day we should look into #16271 to remove these edge cases.
Fixes #24629
The first commit belongs to …

compute: broadcast `UpdateConfiguration` commands

---

ci/deploy_website/website.sh

website: Update chat short link

---

misc/python/materialize/parallel_workload/action.py

I included https://github.com/MaterializeInc/materialize/pull/24628 because otherwise this panics instantly.
-

parallel-workload: Mix SELECT-1 and INSERT, add RETURNING 0

---

doc/user/content/sql/system-catalog/mz_internal.md
src/adapter/src/coord.rs
src/adapter/src/coord/statement_logging.rs
src/catalog/src/builtin.rs
src/environmentd/tests/server.rs
src/ore/src/cast.rs
src/ore/src/now.rs
src/repr/src/row.rs
src/sql/src/session/vars.rs
src/storage-client/src/healthcheck.rs
test/sqllogictest/autogenerated/mz_internal.slt

Not ready to merge yet, needs tests first.

Add throttling for statement log

---

src/adapter/src/coord/sequencer/inner/peek.rs

Another possible fix for the continued `SinceViolation` errors observed in  CI.
Another fix for #24130. This basically reverts the threading model to the state before #24569. If we are still seeing issues with this fix, I really think we should start looking at other PRs or the recent CI machine architecture switch as possible root causes for introducing / revealing this bug.
Even without spawning a thread in `peek_stage_optimize_lir`, we are still seeing `SinceViolation` errors.
The reason could be that `peek_stage_optimize_lir` uses the passed `ctx: ExecuteContext` to send a `PeekStageReady` and relies on a hop through the `Coordinator::handle_message` before continuing with the next stage.
This commit makes the state machine advancement from the …

adapter: short-circuit `peek_stage_optimize_lir` state advancement

---

test/sqllogictest/mz_introspection_index_accounting.slt

This PR updates an SLT test that somehow didn't get caught in https://github.com/MaterializeInc/materialize/pull/24706
Fixes a test that is broken on main
- N/a

tests: update SLT test

---

misc/python/materialize/mzcompose/__init__.py
src/environmentd/src/test_util.rs

persist-txn: make "lazy" the default in CI

---

src/persist-client/src/internal/cache.rs

Bug fix. If the weight of a single blob is greater than the capacity of the cache, it will push out everything in the cache and then immediately get evicted itself, leaving the cache empty. Skip adding it in that case.
-

persist: fix bug where large blobs would clear out the in-mem blob cache

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Seen in https://buildkite.com/materialize/nightlies/builds/6181#018d45c0-6d93-4afa-87d1-730e702a35fb.
Filed https://github.com/MaterializeInc/materialize/issues/24736.

postgres inconsistency: add ignore for empty time string

---

src/adapter/src/error.rs
test/sqllogictest/system-cluster.slt
test/sqllogictest/transactions.slt

Improve an error message about auto routing.
See https://github.com/MaterializeInc/materialize/issues/24718#issuecomment-1912342691
- n/a

adapter: improve routing hints

---

doc/user/content/releases/v0.84.md

Reflect the latest currently-release version of v0.84 in production.
-

Bump v0.84 patch to 4

---

ci/nightly/pipeline.template.yml
test/upgrade-matrix/mzcompose.py

This is the check that currently takes most time in Nightly.
Inspired by https://github.com/MaterializeInc/materialize/pull/24749.

ci: parallelize checks-upgrade-matrix

---

doc/developer/tracing.md
src/storage/src/render/debezium.rs

These issues were closed with "no further work planned":
* https://github.com/MaterializeInc/materialize/issues/11664
* https://github.com/MaterializeInc/materialize/issues/11669
* https://github.com/MaterializeInc/materialize/issues/13019

cleanup: remove obsolete TODOs

---

src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner/peek.rs

Restore optimize lir and fix read hold acquiring.
- n/a

adapter: restore optimize lir and fix read holds

---

ci/builder/Dockerfile
ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/command
ci/test/pipeline.template.yml
misc/python/materialize/checks/all_checks/boolean_type.py
misc/python/materialize/checks/all_checks/insert_select.py
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios_migration.py
misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/mzcompose/composition.py
misc/python/materialize/mzcompose/service.py
misc/python/materialize/mzcompose/services/kafka.py
misc/python/materialize/mzcompose/services/materialized.py
misc/python/materialize/mzcompose/services/metabase.py
misc/python/materialize/mzcompose/services/schema_registry.py
misc/python/materialize/mzcompose/services/sql_server.py
misc/python/materialize/mzcompose/services/zookeeper.py
test/kafka-matrix/mzcompose.py
test/platform-checks/mzcompose.py

I'll wait for nightly to finish with the changed jobs: https://buildkite.com/materialize/nightlies/builds/6204
-

platform-checks: Add migration scenarios, ci: Switch remaining jobs to ARM

---

src/storage/src/source/kafka.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres/replication.rs

Just formatting
had to make some strings multilined
-

storage: fix rustfmt in various mz_storage::source modules

---

misc/python/materialize/buildkite.py
test/cluster/mzcompose.py
test/feature-benchmark/mzcompose.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/24823.

tests: simplify and align parallelism handling (2)

---

src/environmentd/tests/server.rs

The comments in the `test_leader_promotion` were not accurately describing what the code was doing and half of the test was in an unjoined thread which resulted in a lot of dead code. This commit cleans up the test so the code matches the comments and it is actually run.

test: Fix test_leader_promotion test

---

misc/python/materialize/checks/all_checks/materialized_views.py

tests: add explain timestamp statements to materialized_views.py

---

ci/deploy/npm.py

We have an issue where, if we have already cut the release for the next minor version before cutting a hotfix release for an existing production version, the corresponding npm packages would be erroneously tagged as latest. This is because npm infers the `latest` tag if one is not supplied.
Now, releases can receive a second tag that marks them as the latest in a specific branch (e.g., `latest-0.84`).
-

Apply a branch-specific NPM tag to release builds that are not `latest`

---

src/adapter/tests/testdata/timestamp_selection

adapter: Add Strong Session Serializable tests

---

src/storage-types/src/sources/mysql.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs

- Renames `GTIDState` to `GtidState` to follow codebase convention
- Adds docstrings to the MySQL source modules
- Switches MySQL configuration errors from transient to definite errors to avoid continually retrying if the MySQL server is configured incorrectly for replication 
-

storage: Assorted minor MySQL source improvements

---

src/environmentd/tests/sql.rs

https://github.com/MaterializeInc/materialize/issues/24957

tests: disable cargo test test_retain_history due to #24957

---

src/fivetran-destination/src/destination/dml.rs

This PR refactors the `replace_files` method in the Fivetran Destination to use the `COPY FROM` protocol instead of issuing individual `DELETE` and `INSERT` statements.
Progress towards: https://github.com/MaterializeInc/materialize/issues/24665
- N/a

fivetran-destination: refactor `replace_files` to use COPY FROM

---

misc/python/materialize/mzcompose/composition.py

See discussion in https://materializeinc.slack.com/archives/C01LKF361MZ/p1706740088673749
-

mzcompose: Support capture_and_print

---

src/storage/src/sink/kafka.rs

storage/sinks: handle QueueFull error when sending progress records

---

misc/python/materialize/mzcompose/composition.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/worker.py
misc/python/materialize/parallel_workload/worker_exception.py

Before: https://buildkite.com/materialize/nightlies/builds/6219#018d567d-6fb7-4566-96ef-8372e166d0ce
After: https://buildkite.com/materialize/nightlies/builds/6293

ci: improve error extraction for parallel workload

---

misc/python/materialize/checks/all_checks/retain_history.py

* increase history span
* add further time points
* add comments
* <s>try to enable the tests</s>
https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fretain-history-revisited

tests: retain history: follow-up

---

doc/user/content/ingest-data/postgres-amazon-aurora.md
doc/user/content/ingest-data/postgres-amazon-rds.md
doc/user/content/ingest-data/postgres-azure-db.md
doc/user/content/ingest-data/postgres-self-hosted.md
doc/user/content/sql/create-connection.md
doc/user/layouts/shortcodes/network-security/ssh-tunnel.md

Improve the docs by instructing users to lookup the keys of the SSH tunnel connection they just created in the previous step of the workflow.
-

doc/user: refine `SSH TUNNEL` setup instructions

---

misc/python/materialize/cli/ci_logged_errors_detect.py

Demo: https://buildkite.com/materialize/tests/builds?branch=nrainer-materialize%3Aci%2Fsanitize-log-output-demo

ci: sanitize error messages

---

src/adapter/src/catalog.rs

Should help with gathering enough information in order to reproduce and fix #24884.
I'm printing more info in the panic, so hopefully the next time this happens in prod I can recreate the condition based on the error message and the logs.
-

adapter: more detailed soft panic in `drop_plans_and_metainfos`

---

src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-txn/src/operator.rs

This both exercises more edge cases as well as more directly models the OCC protocol we're planning to use for Pv2 Use Case Isolation. We restart all of them at the beginning of each request, so that we continue to test starting a new read reasonably frequently.
-

persist-txn: do incremental reads in the maelstrom test

---

src/storage-controller/src/persist_handles.rs

Mark the otel context as a parent (so the spawns show up in tracing) but not as trace children, so that the spawns don't display as blocking the parent span.
- n/a

storage-controller: detach spawned tasks from current span

---

doc/user/assets/sass/_content.scss
doc/user/content/ingest-data/webhook-quickstart.md
doc/user/content/sql/create-source/webhook.md
doc/user/layouts/partials/head.html
doc/user/layouts/shortcodes/plugins/webhooks-datagen.html

Adding a webhooks datagen plugin to the docs. This will allow us to create a variety of use cases by generating demo data and simulating real-world scenarios without asking the users to install anything.
This can also be reused in different pages with:
```
{{% plugins/webhooks-datagen %}}
```
Example:

Docs: webhook datagen plugin

---

misc/python/materialize/version_list.py

This fixes https://github.com/MaterializeInc/materialize/issues/25099.
🙈

tests: version resolution: fix

---

misc/python/materialize/build_context.py
misc/python/materialize/git.py
misc/python/materialize/version_list.py

This was notified in https://github.com/MaterializeInc/materialize/issues/25099 as well.

tests: introduce build_context as facade to buildkite and (local) git, fix branch name resolution

---

ci/nightly/pipeline.template.yml

To be addressed with https://github.com/MaterializeInc/materialize/issues/25108 on occasion.

ci: retry k8s node recovery tests

---

doc/user/content/sql/system-catalog/mz_internal.md
test/sqllogictest/autogenerated/mz_internal.slt

sorry for missing this earlier!

document mz_recent_activity_log

---

misc/monitoring/tempo.yml

misc: increase max tempo size during local monitoring

---

doc/user/layouts/shortcodes/private-preview.html

doc/user: add private preview disclaimer

---

src/kafka-util/src/client.rs

This is the suggestion by @benesch in https://github.com/MaterializeInc/materialize/issues/24901#issuecomment-1926437860.
Nightly: https://buildkite.com/materialize/nightlies/builds/6313

tests: fix mz E2E test

---

doc/user/content/ingest-data/amazon-eventbridge.md
doc/user/content/ingest-data/hubspot.md
doc/user/content/ingest-data/rudderstack.md
doc/user/content/ingest-data/segment.md
doc/user/content/ingest-data/snowcatcloud.md
doc/user/content/ingest-data/stripe.md

As discussed internally, adding a HubSpot Webhooks integration guide.

Doc: Add HubSpot webhook guide

---

src/storage-types/src/connections.rs

See comment within for details.
I _think_ this prevents the bad "Error: Local: Broker thread shutting down" error message we saw originally in https://github.com/MaterializeInc/materialize/issues/24901. It's hard to say for sure because it's timing dependent and I was never able to reproduce the bad error message locally. 
https://github.com/MaterializeInc/materialize/pull/24959 ensures that SASL authentication failures always take precedence over broker thread shutdown errors, but I think this PR is still worthwhile because it will (hopefully) prevent other errors we haven't special cased from getting drowned out by broker thread shutdown errors.
* This PR (likely) fixes a recognized bug.
- n/a

storage-types: improve Kafka error messages by adjusting shutdown order

---

src/adapter/src/coord/command_handler.rs

This is more readable to me.
- n/a

adapter: factor out common calls to plan_statement

---

misc/python/materialize/feature_benchmark/executor.py
misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/mzcompose/services/mysql.py
test/feature-benchmark/mzcompose.py
test/feature-benchmark/scenarios.py
test/mysql-cdc/10-create-connection.td
test/mysql-cdc/mzcompose.py
test/ssh-connection/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6403

feature benchmark: add MySQL scenarios

---

src/adapter/src/catalog/open.rs
src/adapter/src/coord.rs
src/catalog-debug/src/main.rs
src/catalog/src/durable/impls/stash.rs
src/stash-debug/src/main.rs

catalog: take boot_ts into account when chosing initial oracle timestamps

---

src/sql-parser/tests/testdata/create
src/sql-parser/tests/testdata/select

Some further tests for https://github.com/MaterializeInc/materialize/pull/25175.

tests: extend tests for row as identifier

---

test/pg-cdc/mzcompose.py

I inadvertently discovered that several of the workflows in `pg-cdc` were not being run in CI,
context in slack: https://materializeinc.slack.com/archives/C0246GEHL8N/p1707766464058939
3 out of the 4 workflows were fine to enable, but the `ceased-status` workflow currently fails with:
```
>> ALTER TABLE t DROP COLUMN a;
>> ALTER TABLE t ADD COLUMN a int;
>> INSERT INTO t VALUES (2);
> SELECT true FROM mz_internal.mz_source_statuses WHERE name = 't' AND status = 'ceased' AND error ILIKE 'incompatible schema change%';
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms
rows match; continuing at ts 1707835325.5340664
Connecting to PostgreSQL server at postgres://postgres:postgres@postgres...
>> DROP PUBLICATION mz_source;
>> INSERT INTO t VALUES (1);
> SELECT true
FROM …
```

storage/qa: Enable non-default workflows in pg-cdc tests

---

test/cluster/mzcompose.py

Seen in https://buildkite.com/materialize/tests/builds/75656#018da698-ac1c-47bb-a8a4-62b438fc40b8
-

cluster tests: Unflake blue-green-deployment test

---

src/adapter/src/coord/command_handler.rs

This hopefully mitigates https://github.com/MaterializeInc/materialize/issues/24288#issuecomment-1931856361
It would successfully mitigate it if the root cause is that some input object is sometimes a little bit ahead of the oracle read ts. It wouldn't mitigate it if the root cause is any of the following:
- A successfully acquired read hold is not honored, or we are losing a read hold somehow.
- A bug around bootstrapping, where somehow we advance the `since` to the next refresh before acquiring the oracle read holds.
(During the initial debugging of https://github.com/MaterializeInc/materialize/issues/24288#issuecomment-1931856361, I mistakenly thought that the root cause can't be that some input object is just a little bit ahead of the oracle read ts, because the timestamp difference …

Advance REFRESH `mz_now` resolution to `least_valid_read`

---

src/environmentd/tests/server.rs

This commit fixes the
test_old_storage_usage_records_are_reaped_on_restart test so that it's no longer flakey. Previously, the test would query the timestamp from the mz_storage_usage_by_shard table with the following query, `SELECT EXTRACT(EPOCH FROM MAX(collection_timestamp))::integer FROM mz_internal.mz_storage_usage_by_shard;`. The issue is that `EXTRACT(EPOCH FROM <timestamp>)` returns a float8 that represents seconds since the epoch, where the fractional component is sub-second. When we cast to an integer, we were truncating the sub-second component. Additionally, we were then treating the truncated value as a milliseconds measurement when it was in fact a seconds measurement. This commit fixes the issue, by multiplying the seconds by 1000 (the number of milliseconds per second) …

test: Fix flaky storage usage reap test

---

src/ore/src/lib.rs

I missed this dependency in #25086.
-

ore: add a missing cfg feature on the new lgbytes module

---

test/testdrive/mz-arrangement-sharing.td

testdrive: Add comment explaining mz-arrangement-sharing.td

---

misc/python/materialize/feature_benchmark/scenario.py
misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
test/feature-benchmark/mzcompose.py

Laying the base for enabling a scenario in the feature benchmark from a certain version on. Not yet enabling `MySqlStreaming`.

feature benchmark: allow skipping scenarios in certain versions

---

doc/developer/project-management.md

Minor patches as I read through.

doc/developer: minor patches to project management

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.89.0-dev

---

misc/python/materialize/version_list.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/25315.

ci: version handling: fix parameter names

---

ci/test/lint-main/checks/check-python-discouraged.sh
misc/python/materialize/mzcompose/composition.py
misc/python/materialize/mzexplore/extract.py
misc/python/materialize/parallel_workload/action.py
pyproject.toml
test/feature-benchmark/mzcompose.py

I first thought `== None` does not work (which is not the case) but I think the check still does not hurt.

lint: python: comparison with None

---

test/canary-load/mzcompose.py

canary load: Fix restarting after network error

---

doc/user/content/sql/create-source/postgres.md
doc/user/layouts/shortcodes/postgres-direct/before-you-begin.html
doc/user/layouts/shortcodes/postgres-direct/check-the-ingestion-status.html
doc/user/layouts/shortcodes/postgres-direct/create-an-ingestion-cluster.html
doc/user/layouts/shortcodes/postgres-direct/ingesting-data/allow-materialize-ips.html
doc/user/layouts/shortcodes/postgres-direct/ingesting-data/use-ssh-tunnel.html
doc/user/layouts/shortcodes/postgres-direct/right-size-the-cluster.html

Partly addresses [user feedback](https://materializeinc.slack.com/archives/C05EF5QV93M/p1708060330683909). Fixes #24804.

doc/user: improvements to PostgreSQL docs

---

misc/python/materialize/version_list.py

Fixes: #25383
Expected according to Jan
-

feature-benchmark: Ignore increased number of messages

---

src/compute-client/src/controller/instance.rs

This PR makes three smaller refactors in the compute controller:
* The first commit rewrites `update_read_capabilities` for readability.
* The second commit changes the type of `updates` passed to `update_*_write_frontiers` to a `BTreeMap`, to rule out the possibility of duplicate entries.
* The third commit fixes error handling in `set_read_policy`, to avoid leaving the controller in an inconsistent state.
* The fourth commit adds panics to `add_collection` methods, to ensure we are alerted about bugs where we try to overwrite existing collections.
Look at the commits separately!
- N/A

Compute controller cleanup

---

bin/ci-builder
bin/ci-failure-also-on-main
ci/plugins/mzcompose/hooks/pre-exit
misc/python/materialize/buildkite.py
misc/python/materialize/buildkite_insights/step_durations/analysis.py
misc/python/materialize/buildkite_insights/step_durations/build_step.py
misc/python/materialize/buildkite_insights/util/buildkite_api.py
misc/python/materialize/cli/ci_failure_also_on_main.py
misc/python/materialize/cli/ci_logged_errors_detect.py

Demo: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aci%2Fannotate-error-also-on-main

ci: annotate when an error also occurred on main

---

misc/python/materialize/cli/ci_closed_issues_detect.py

For stuff like:
```
// TODO #12345 / #23456
```

ci: closed issue detector: support multiple issues on the same line

---

misc/python/materialize/mzcompose/composition.py

mzcompose: Separate stdout and stderr handling

---

doc/user/content/sql/grant-privilege.md

doc: Add doc for GROUP keyword in GRANT statement

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.90.0-dev

---

misc/python/materialize/mzcompose/composition.py

See discussion in https://materializeinc.slack.com/archives/C01LKF361MZ/p1708636374393499
-

mzcompose: Retry up command more often

---

doc/user/layouts/shortcodes/json-parser.html

Doc: Fix json parser doc widget bug

---

ci/nightly/pipeline.template.yml

This addresses https://github.com/MaterializeInc/materialize/issues/25265.

tests: aws-real: retry once

---

misc/python/materialize/zippy/source_actions.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6608

tests: zippy: no alter connection on upsert sources

---

src/compute/src/render/mod.rs

If the `CollectionBundle` of a rendered `Plan` node contains an arrangement, attach the hydration logging operator to that arrangement's stream rather than the stream of the unarranged collection. The rationale is that attaching to the unarranged collection will produce additional forks in the dataflow graph, and therefore unnecessary cloning of data, which attaching to an arrangement avoids.
Hydration logging operators can cause unnecessary cloning of data on dataflow edges.
Relevant [Slack thread](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1708552792784519).
- N/A

compute: attach hydration logging operators to arrangements first

---

test/mysql-cdc/privileges.td

tests: mysql-cdc: minor consistency improvement

---

src/orchestrator-tracing/src/lib.rs

Currently sentry tags use `--opentelemetry-resource`, which does not include region (and doesn't need to). This also means clusters miss these tags if `--opentelemetry-endpoint` isn't set. 
This adds `--sentry-tags` so I can (after this releases) add `--sentry-tag=region={region}` to environmentd's. Currently its very unclear what region an error is coming from!
-

tracing: add --sentry-tags

---

misc/python/materialize/checks/all_checks/mysql_cdc.py
test/cloudtest/test_upgrade.py
test/platform-checks/mzcompose.py

Part of https://github.com/MaterializeInc/materialize/issues/24927.
Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fmysql-platform

tests: mysql: add MySQL platform checks

---

misc/python/materialize/buildkite_insights/segfaults/find.py
misc/python/materialize/buildkite_insights/util/buildkite_api.py

buildkite_insights: Add script for finding segfaults

---

doc/user/content/manage/terraform.md

docs: update terraform provider configuration

---

misc/python/materialize/buildkite_insights/costs/extract_stats.py

See https://docs.google.com/spreadsheets/d/1QEPoy1poVPtwGwFj7mH_5E6oTl8d-ygEtLBStfRd0oU/edit#gid=1431245639
-

buildkite_insights: Also extract % of test failures

---

ci/nightly/pipeline.template.yml
misc/python/materialize/mysql.py
misc/python/materialize/mzcompose/services/mysql.py
test/mysql-cdc/alter-table-after-source.td
test/mysql-cdc/data-utf8.td
test/mysql-cdc/mysql-cdc.td
test/mysql-cdc/mzcompose.py
test/mysql-cdc/types-character.td
test/mysql-cdc/types-temporal.td
test/mysql-matrix/mzcompose
test/mysql-matrix/mzcompose.py

Nightlies:
* with only `8.3.0`: https://buildkite.com/materialize/nightlies/builds/6643 ✅ 
* with additional `5.7.x`: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fmysql-version-matrix ✅

 tests: mysql: add mysql version-matrix test 

---

src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs

I encountered a spurious bug when working on another issue that can happen if the mysql server is restarted or experiences a network issue when we validate system settings. We were blindly reporting all errors as 'Definite Errors' in these instances, even though transient network errors can be retried.
I captured the source statuses when this happened, and you can see the error state `mysql server configuration error: Input/output error: Input/output error` is the message from the `DefiniteError::ServerConfigurationError` value wrapped around a transient network error.
```
materialize=> SELECT * FROM mz_internal.mz_source_statuses;
id  |             name             |   type    |   last_status_change_at    |  status  | …
```

storage/mysql: Fix transient errors being reported as definite when validating system config

---

test/mysql-cdc/mysql-cdc-ssl.td

Part of https://github.com/MaterializeInc/materialize/issues/24927.

tests: mysql-cdc: SSL tests

---

test/mysql-cdc/mysql-cdc-ssl.td

Incorporating the feedback from https://github.com/MaterializeInc/materialize/issues/25673 and https://github.com/MaterializeInc/materialize/issues/25679.

tests: mysql-cdc-ssl: cleanup

---

doc/user/content/releases/v0.85.md
doc/user/content/releases/v0.89.md
doc/user/content/releases/v0.90.md

Polish release notes
This is a stub!
-

 doc/user: polish 89.2 release notes

---

misc/python/materialize/cli/mzcompose.py

Makes it easier to find what you were looking for
-

mzcompose: Sort compositions in hint

---

src/sql/src/func.rs

`mz_name_rank`, which powers our in-SQL catalog lookups relied on the `rank` window function, which has a complex and "expensive" implementation. However, we can instead nominally simplify the implementation by:
- hoisting the class of object we are searching for into input of the function (removing the need to partition the result set)
- use a simple aggregate window function (i.e. `min`) as opposed to the more complex `rank` function because we only care whether or not the name value is the "best-ranked" option.
I had hoped that this simplification would be enough to stop the stack from overflowing in #25545, but even removing the rank calculation entirely isn't enough to resolve the issue. However, this seems like a small win that might move the needle elsewhere.
This PR refactors …

sql: mz_name_rank simplification

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs

See [here](https://github.com/MaterializeInc/materialize/pull/24117#pullrequestreview-1878641233) for context.

Address a few comments by Moritz on statement lifecycle logging

---

test/limits/mzcompose.py

Following #25666
As seen in https://buildkite.com/materialize/nightlies/builds/6733#018dfc94-0e5c-46b9-bafb-327da00d84ef
-

product-limits test: Increase number of connections

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml
misc/python/materialize/mzcompose/services/postgres.py
test/limits/mzcompose.py
test/testdrive/webhook.td

limits test: Test higher number of sources for pg, mysql, webhook

---

src/storage/src/source/generator.rs

Fixes: https://github.com/MaterializeInc/materialize/issues/25576
I was unable to reproduce this issue, so left existing tests as is. Load generators are weird, so I went with a simple route: 
- `offset_known` == `offset_committed`, because load gen sources don't let us recover the former on restart
- Avoid a logic bug reporting `0` on restart in a race condition.
- Simplify some of the subtraction/etc logic.
Releasing this pr may cause this error log: https://materializeinc.sentry.io/issues/5014335637/?project=6780145&referrer=github_integration once more on the next upgrade of mz, but then we should be fine.
-

storage: fix offset stats for loadgen sources

---

test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt

slt: Adapt explain plan result to reality

---

misc/python/materialize/buildkite_insights/step_durations/analysis.py
misc/python/materialize/buildkite_insights/step_durations/build_step.py
misc/python/materialize/cli/ci_annotate_errors.py

95f5357f40 buildkite insights: merge shared steps
27df111daf buildkite insights: rename
6bd8b2ea30 buildkite insights: fix
3624eb2d0f buildkite insights: fix
01d70d0a73 buildkite insights: resolve TODO
1258ba8d78 buildkite insights: rework filter
921190a901 buildkite insights: introduce BuildStepMatcher
0b208b19a2 buildkite insights: split BuildStepOutcome and BuildJobOutcome
77cf18127c buildkite insights: output formatting

buildkite insights: merge shared steps

---

test/canary-environment/mzcompose.py
test/canary-load/mzcompose.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/25731
-

tests: Skip consistency check in tests that connect to real Mz instance

---

test/pg-cdc/mzcompose.py

pg-cdc test: Fix replication-slot workflow

---

src/adapter/src/coord/sequencer/inner/subscribe.rs

Previously subscribe was releasing read holds before shipping its dataflow, allowing a slight possibility of the since advancing in the intervening time.
Fixes #25375
- n/a

adapter: delay subscribe read hold releases

---

misc/python/materialize/cli/ci_annotate_errors.py

Seen in https://buildkite.com/materialize/nightlies/builds/6802 that it can currently duplicate
-

ci: Only annotate errors once

---

test/cluster/mzcompose.py

cluster tests: Temporarily disable test-refresh-mv-restart

---

misc/python/materialize/cli/ci_annotate_errors.py

Since junit.xml will already contain the panic from the failing test case. Seen in https://buildkite.com/materialize/tests/builds/77926
-

ci-annotate-errors: Less spammy and no duplicate panic messages

---

misc/python/materialize/mzcompose/test_result.py

Seen in https://buildkite.com/materialize/tests/builds/77939.
This is not relevant and hides the actual error when the error message gets cropped.

ci: error extraction: exclude PEM content

---

test/mysql-cdc/alter-source.td
test/mysql-cdc/mysql-cdc.td
test/mysql-cdc/types-enum.td

This addresses https://buildkite.com/materialize/nightlies/builds/6824#018e1e0b-fba1-4f0b-8cae-af7c249c43e6 and replaces https://github.com/MaterializeInc/materialize/pull/25871.

tests: mysql-cdc: handle closed issues

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

*: bump version to 0.92.0-dev

---

doc/user/content/integrations/http-api.md
doc/user/static/materialize-openapi.yml

Adds an openapi v3 spec and links it in the docs.
Which of the following best describes the motivation behind this PR?
This is something we want for the console, but hopefully it will also be useful for customers.
This was a quick draft, we could probably improve the documentation in the spec and the wording in the docs page.

docs: add openapi spec for http interface

---

test/sqlsmith/mzcompose.py

Was reduced by moving the job to buildkite-aarch64-small
-

sqlsmith: Set correct amount of memory

---

misc/python/materialize/cli/ci_annotate_errors.py

Otherwise looks slightly confusing, see https://buildkite.com/materialize/nightlies/builds/6812
-

ci: Add retry count when annotating errors

---

misc/python/materialize/cli/ci_annotate_errors.py

Seen not matching in https://buildkite.com/materialize/tests/builds/78022#018e2ad7-9eb9-4de8-b7b5-9f07b1153a1f
-

ci-annotate-errors: Make multi-line matching easy

---

src/transform/src/fusion/join.rs

Create a dedicated issue for tracking follow-ups unblocked by merging `EquivalencePropagation`.
Make the closed references issues check in Nightlies happy agian.
N/A
-

Update TODO issue in `fusion/join.rs`

---

misc/python/materialize/mzcompose/__init__.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6841

ci: activate enable_compute_chunked_stack

---

misc/python/materialize/checks/all_checks/multiple_partitions.py

platform-checks: Disable status check in MultiplePartitions check

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Seen in https://buildkite.com/materialize/nightlies/builds/6841#018e2cae-ca1b-4224-820f-c064f67c3859.
Filed https://github.com/MaterializeInc/materialize/issues/25937.

postgres consistency: add ignore for decode with special whitespace chars

---

src/environmentd/tests/auth.rs

This PR attempts to deflake the auth deduplication test some more by also moving the metrics check above the possibly long running queries, and relax the metrics check a bit
Hopefully fix https://github.com/MaterializeInc/materialize/issues/25705
- N/a

test: Deflake auth test, again

---

misc/python/materialize/buildkite_insights/failure_search/search.py
misc/python/materialize/buildkite_insights/failure_search/search_result_presentation.py

buildkite search: refactoring

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This addresses https://buildkite.com/materialize/nightlies/builds/6855#018e2fdb-374c-4e85-a759-fcc58e61ed92 tracked by https://github.com/MaterializeInc/materialize/issues/25959.

postgres consistency: add ignore for min/max on time

---

test/mysql-cdc-resumption/alter-source-connection.td
test/mysql-cdc-resumption/alter-table-fix.td
test/mysql-cdc-resumption/alter-table.td
test/mysql-cdc-resumption/configure-materialize.td
test/mysql-cdc-resumption/configure-mysql.td
test/mysql-cdc-resumption/configure-replica-with-delay.td
test/mysql-cdc-resumption/configure-replica.td
test/mysql-cdc-resumption/create-source.td
test/mysql-cdc-resumption/delete-rows-t1.td
test/mysql-cdc-resumption/delete-rows-t2.td
test/mysql-cdc-resumption/mysql-disable-select-permission.td
test/mysql-cdc-resumption/mzcompose.py
test/mysql-cdc-resumption/populate-tables.td
test/mysql-cdc-resumption/reset-master.td
test/mysql-cdc-resumption/verify-mysql-select.td
test/mysql-cdc-resumption/verify-source-running.td

4ced7f0877 tests: mysql-cdc-resumption: refactor initialization
7c159aa9d6 tests: mysql-cdc-resumption: make host configurable
18a3ea95cf tests: mysql-cdc-resumption: add workflow "master-changes"
c3f6368d6b tests: mysql-cdc-resumption: add workflow "switch-to-replica-and-kill-master"
60d3509590 tests: mysql-cdc-resumption: add workflow "switch-to-lagging-replica"
ff00446c2b tests: mysql-cdc-resumption: give replica some time

tests: mysql-cdc-resumption with replicas

---

misc/python/materialize/mzcompose/composition.py

By-product of another PR where it is no longer needed.

tests: composition: introduce is_running

---

test/testdrive/materialized-view-refresh-options.td

Trying to address the flake in https://buildkite.com/materialize/nightlies/builds/6862#018e33b8-1805-417b-beb4-07da35e9c0b2.

tests: materialized-view-refresh-options.td: add sleep

---

test/mysql-cdc/alter-source.td

This addresses https://buildkite.com/materialize/nightlies/builds/6868#018e3504-2d9c-42c6-b350-ad4afa60c8c3.
#25882 is captured by #24975.

closed issues: remove TODO

---

test/testdrive/materialized-view-refresh-options.td

This reverts https://github.com/MaterializeInc/materialize/pull/25978.

Revert "tests: materialized-view-refresh-options.td: add sleep (#25978)"

---

test/postgres/Dockerfile
test/rqg/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6869

tests: upgrade Postgres to 16.2

---

src/balancerd/tests/server.rs

balancerd: retry metrics test

---

misc/python/materialize/cli/ci_upload_heap_profiles.py

before:
prof-materialized-clusterd1-2024-03-14_09:36:43.pb.gz
now:
prof-materialized-cluster-s1-replica-s1-2024-03-14_09:36:43.pb.gz
-

ci-upload-heap-profiles: Nicer cluster names

---

misc/python/materialize/mzcompose/composition.py

Still failing sometimes: https://buildkite.com/materialize/nightlies/builds/6906#018e3d44-e2e9-4127-99ae-bbf1b244cb11
-

mzcompose: Increase number of retries even more

---

test/mysql-cdc/types-enum.td

This exposes https://github.com/MaterializeInc/materialize/issues/26022.
MySQL 5.7: https://buildkite.com/materialize/nightlies/builds/6909

tests: mysql-cdc: enum reordering

---

misc/python/materialize/mzbuild.py

To support use from the cloud repo, which wants to publish their mzbuild images to a ECR registry that's shared among many personal stacks.
- n/a

mzbuild: support configuring image registry and prefix

---

src/storage/src/source/source_reader_pipeline.rs

storage: take `as_of` into account when reclocking committed upper

---

test/sqlsmith/mzcompose.py

sqlsmith: Fix auction generator not supporting scale factor

---

misc/python/materialize/docker.py

mzcompose: Fall back to docker manifest inspect when api fails

---

doc/user/content/ingest-data/mysql/amazon-aurora.md
doc/user/content/ingest-data/mysql/amazon-rds.md
doc/user/content/ingest-data/mysql/self-hosted.md
doc/user/content/sql/create-connection.md

Following up on feedback from @nrainer-materialize and @bobbyiliev in #25990. 🙇‍♀️

doc/user: misc fixes to MySQL documentation

---

misc/python/materialize/version_ancestor_overrides.py

https://materializeinc.slack.com/archives/CTESPM7FU/p1710515885432429?thread_ts=1710508402.711129&cid=CTESPM7FU

feature benchmark: add ignore for store flatmap execution

---

src/adapter/src/catalog/open.rs

This PR should fix a panic in the recently added migration for builtin objects.
Fix a panic found with the upgrade checks
- N/a

migration: Derive list of IDs from catalog_state

---

doc/developer/platform-checks.md

docs: Explain how to handle changed syntax in platform-checks

---

misc/python/materialize/cli/ci_annotate_errors.py

ci-annotate-errors: Count number of runs from 1

---

misc/python/materialize/parallel_workload/action.py

Seen in https://buildkite.com/materialize/nightlies/builds/6933
-

parallel-workload: Handle role missing

---

test/mysql-cdc-resumption/mzcompose.py

Part of https://github.com/MaterializeInc/materialize/issues/24927. Added this test after I stumbled upon the following in your demo:
> Binary logging is done immediately after a statement or transaction completes but before locks are released or any commit is done.

tests: mysql-cdc-resumption: rollback in MySQL

---

doc/user/layouts/partials/sql-grammar/format-spec.svg
doc/user/sql-grammar/sql-grammar.bnf

While playing around with Materialize I noticed the railroad diagram for`FORMAT PROTOBUF` for an inline schema was incorrect. Quick fix to the grammar to add in `FORMAT PROTOBUF MESSAGE 'foo' USING SCHEMA 'bar'`
-

minor fixes: fix railroad diagram grammar for FORMAT PROTOBUF

---

src/compute/src/render/context.rs
src/compute/src/render/flat_map.rs
src/compute/src/render/mod.rs

Change the implementation of `render_flat_map` to use the consolidating buffer, and to avoid multiplexing data and errors.
-

flat_map: Inline operator to avoid muxing data and errors

---

test/mysql-cdc/move-table.td
test/mysql-cdc/table-in-mysql-schema.td
test/mysql-cdc/temporary-tables.td
test/mysql-cdc/views.td

Some further ideas I got when reading the docs.

tests: mysql-cdc: some further special tables

---

misc/python/materialize/mzcompose/composition.py

Otherwise it can take a while to receive a full line, especially when a result is (temporarily) wrong and testdrive is waiting for it to converge
-

mzcompose: Immediate output in capture_and_print

---

misc/python/materialize/version_list.py

See https://materializeinc.slack.com/archives/CTESPM7FU/p1710454593196629
-

tests: Ignore v0.93.0

---

ci/plugins/mzcompose/hooks/post-command
misc/python/materialize/mzcompose/composition.py

ci: Don't capture same log lines twice

---

misc/python/materialize/mzcompose/test_result.py
test/cloudtest/node_recovery/test_k8s_node_recovery.py
test/output-consistency/mzcompose.py
test/postgres-consistency/mzcompose.py
test/version-consistency/mzcompose.py

This is work towards https://github.com/MaterializeInc/materialize/issues/25108.

tests: k8s node recovery: increase timeout, improve logging

---

test/mysql-cdc/alter-table-after-source.td
test/mysql-cdc/generated-columns.td
test/mysql-cdc/invisible-columns.td
test/mysql-cdc/types-boolean.td
test/mysql-cdc/types-character.td
test/mysql-cdc/types-json.td
test/mysql-cdc/types-set.td
test/mysql-cdc/types-spatial.td

This is to have covered all types to avoid incidents like #incident-101.
Nightly with MySQL 5.7: https://buildkite.com/materialize/nightlies/builds/6977
See also: https://github.com/MaterializeInc/materialize/pull/26104

tests: mysql: further types and special cases

---

src/orchestrator-kubernetes/src/lib.rs

orchestrator-kubernetes: handle more edge cases in disk usage reporting

---

misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6980
Identified issues:
* https://github.com/MaterializeInc/materialize/issues/26177

output consistency: LIKE / ILIKE: fix operator specification

---

doc/user/content/releases/v0.92.md
doc/user/content/releases/v0.93.md
doc/user/content/sql/system-catalog/mz_internal.md

Release notes for v0.92. 🌧️ 
@petrosagg @evanharmon: this covers the step of bumping the release version in the docs.

doc/user: polish v0.92 release notes

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.94.0-dev

---

src/timestamp-oracle/src/postgres_oracle.rs

We've observed `advance_timelines` take 2h. Adding traces here should help us understand what's going on.
Bump up the retry debug to an info so we get trace events and know how many retries there were.
- n/a

timestamp-oracle: trace timeline operations

---

ci/mkpipeline.py

Nightly: https://buildkite.com/materialize/nightlies/builds/7021

ci: remove test selection block

---

misc/python/materialize/output_consistency/validation/result_comparator.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6984

output consistency: fix validation

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Checking whether https://github.com/MaterializeInc/materialize/issues/22000 is fixed.
Nightly: https://buildkite.com/materialize/nightlies/builds/7018

postgres consistency: remove ignore for regex with linebreaks

---

test/aws-localstack/copy-to-s3/copy-to-s3.td
test/testdrive/copy-to-s3-minio.td

Fixes: #26218
If this doesn't fix it, then a product issue, not test issue
-

copy-to-s3 tests: Hopefully fix flakiness

---

src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/timestamp_selection.rs
src/adapter/tests/timestamp_selection.rs

At least for me it's clearer what the code does now. I did this refactor as part of preparation work for #24845 
-

adapter: simplify code around timelines/timestamp oracle

---

src/adapter/src/coord/sequencer/inner.rs

This is not a problem right now, but I discovered this as a concurrency bug in my PR that pulls ownership of collections out into a shareable/concurrent `StorageCollections`: https://github.com/MaterializeInc/materialize/pull/24816.
See comment in the code.
-

adapter: only initialize read policies once all related sources are created

---

test/mysql-cdc/transactions-multi-conn.td
test/mysql-cdc/transactions.td

Add tests with transactions as requested in https://github.com/MaterializeInc/materialize/pull/26223.

tests: mysql-cdc: transactions

---

ci/test/cargo-test/mzcompose.py

Seen in https://buildkite.com/materialize/tests/builds/79043#018e7653-aef8-415e-92d1-40974e584c13
-

cargo-test: Reduce number of threads again to combat flakiness

---

doc/developer/guide.md
src/environmentd/src/bin/environmentd/main.rs

Since we now have a few different ways to connect to a local Materialize instance, each with a different set of constraints and permissions, lets provide a sample connection string so someone can quickly get started.
-

Add local Mz connection instructions to the dev guide

---

test/pg-cdc/transactions-multi-conn.td
test/pg-cdc/transactions.td

Port transaction tests of MySQL CDC to Postgres CDC.

tests: pg-cdc: transactions

---

doc/developer/guide.md

My previous PR had this sneaky typo: it is `--unsafe-mode`, not `--unsafe mode`.
-

Correct dev guide `--unsafe-mode` typo.

---

misc/python/materialize/output_consistency/execution/query_execution_manager.py
misc/python/materialize/output_consistency/generators/query_generator.py
misc/python/materialize/output_consistency/query/query_template.py
misc/python/materialize/output_consistency/selection/randomized_picker.py

This closes https://github.com/MaterializeInc/materialize/issues/19824.
Nightly: https://buildkite.com/materialize/nightlies/builds/7068
Issues:
* https://github.com/MaterializeInc/materialize/issues/26272

output-consistency: support OFFSET and LIMIT

---

test/crdb-restarts/mzcompose.py
test/limits/mzcompose.py
test/sql-feature-flags/mzcompose.py

Only review the 2nd commit, the 1st is https://github.com/MaterializeInc/materialize/pull/25798 and I didn't want to conflict with the change.
-

tests: Parallel up and testdrive calls without temp files

---

test/testdrive/load-generator-key-value.td

fix merge-skew with https://github.com/MaterializeInc/materialize/commit/268ef5c3456716b972ecfaa242c8ef0d966b32fa
https://buildkite.com/materialize/nightlies/builds/7132#018e861d-b756-4f4b-a368-0804f6a95073
-

storage: fix load generator testdrive test

---

misc/python/materialize/output_consistency/input_data/operations/number_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

postgres consistency: optimize and add ignores

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

https://github.com/MaterializeInc/cloud/issues/9036
-

release: bump to version v0.95.0-dev

---

test/bounded-memory/mzcompose.py

Nightlies: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fbounded-memory-w-tx
Nightlies based on https://github.com/MaterializeInc/materialize/pull/26267: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fbounded-memory-w-tx-on-pr

tests: bounded memory: add pg-cdc-large-tx

---

src/storage/src/source/statistics.rs

Closes: https://github.com/MaterializeInc/materialize/issues/25969
- covered by the existing tests 
-

storage: prevent offset_known < offset_committed

---

src/adapter/src/catalog/open.rs

4d6f907b9714bae1f06c3958bff2a147d11a660e temporarily commented out an assert that is part of the builtin migrations because some prod and staging environments had previously violated what the assert was trying to protect against. Now that v0.94.X has been released, previously deleted objects have been removed from all environments and they won't trigger the assert. So this commit brings back the assert to protect against dropping builtin objects outside `mz_internal` in the future.

adapter: Re-enable migration assert

---

src/sqllogictest/src/bin/sqllogictest.rs

sqllogictest requires that the disk_cluster_replicas_default system variable is set to true, or it will fail. This can be confusing on not obvious if someone is running sqllogictest outside mzcompose.This commit automatically sets this variable to true if it's unset and panics if it's set to the wrong value. Additionally, it adds some structure to add more required default system variables in the future.

sql: Set disk_cluster_replicas_default sys var

---

test/aws-localstack/copy-to-s3/copy-to-s3.td

https://github.com/MaterializeInc/materialize/pull/25785/ changed the `test/aws-localstack/copy-to-s3/copy-to-s3.td` file without fixing the query check in the same file. Verified this fix locally.
-

Fix copy-to-s3.td test-case bug introduced in 25785

---

src/sql/src/plan/statement/show.rs

As part of #17957, we can just remove the `DETAILS` value from being printed. Given that this string contained no other useful information for users, we can treat subsequent requests to extract information that is otherwise present here as new requests.
This PR adds a known-desirable feature. Fixes #17957
- Remove an opaque implementation detail from the output of `SHOW CREATE SOURCE` for PostgreSQL and MySQL sources.

sql: remove hex-encoded protobuf DETAILS string from SHOW CREATE SOURCE

---

misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/boolean_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/equality_operations_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Raised in https://github.com/MaterializeInc/materialize/pull/26265#issuecomment-2024123870.
Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fadd-lt-gt-ops
Issues:
* generalized #22002
* created #26309
* created #26323

output consistency: add equality and inequality operators

---

misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
test/feature-benchmark/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/7171

feature benchmark: add SwapSchema scenario

---

ci/test/docs-widgets/docs-widgets.sh
ci/test/docs-widgets/json-parser.test.js
ci/test/docs-widgets/package-lock.json
ci/test/docs-widgets/package.json
ci/test/pipeline.template.yml
doc/user/layouts/shortcodes/json-parser.html

Adding tests for the JSON parser docs JS widget.
-

Doc: Add vitest tests for docs JS widgets

---

doc/user/content/releases/v0.93.md
doc/user/content/releases/v0.94.md
doc/user/data/sql_funcs.yml

doc/user: polish v0.93 release notes

---

misc/python/materialize/mzcompose/composition.py
test/skip-version-upgrade/mzcompose.py

This reverts https://github.com/MaterializeInc/materialize/pull/26318 as discussed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1712125443473179?thread_ts=1711757768.329099&cid=C01LKF361MZ.

Revert "mzcompose: Only retry docker pulls (2nd attempt)"

---

src/persist-client/src/operators/shard_source.rs

This PR makes the `shard_source` acquire a reader on the source shard _before_ possibly suspending itself until the start signal is triggered. This is to work around a current bug where the compute controller will release read holds for inputs to REFRESH MVs too early (https://github.com/MaterializeInc/materialize/issues/16275).
[Slack thread.](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1712052300467749)
Compute replicas sometimes panic when trying to instantiate `persist_source`s for dataflows, because the requested `as_of` is not available.
```
thread 'timely:work-1' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-013aa1a3c9c9261fc-1/materialize/tests/src/persist-client/src/operators/shard_source.rs …
```

shard_source: suspend with read hold

---

test/bounded-memory/mzcompose.py

This is helpful because the search might get stuck when hitting the OOM.

bounded memory: allow searching only for one memory limit

---

test/bounded-memory/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fbounded-memory-w-mysql

tests: bounded memory: add MySql scenarios

---

src/compute/src/render/mod.rs
src/compute/src/sink/persist_sink.rs
src/storage-operators/src/persist_source.rs
src/storage/src/render/sinks.rs
src/storage/src/render/sources.rs

storage: more descriptive logging for persist_source/shard_source

---

misc/python/materialize/cloudtest/k8s/api/k8s_pod.py
test/cloudtest/test_full_testdrive.py

Disable the test until we have the setup in cloudtest ready (https://github.com/MaterializeInc/materialize/issues/26392).
Nightly: https://buildkite.com/materialize/nightlies/builds/7218

tests: disable fivetran dest in cloudtests

---

misc/python/materialize/output_consistency/output/reproduction_code_printer.py
misc/python/materialize/output_consistency/validation/result_comparator.py
misc/python/materialize/output_consistency/validation/validation_message.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Seen in https://buildkite.com/materialize/nightlies/builds/7229.

postgres consistency: fix ignore

---

src/controller-types/src/lib.rs

We only have arm disk instances right now so mz_probe size should be disk enabled like all other v2 cluster sizes. 
-

treat mz_probe as a v2 size so that it works with disk instances

---

misc/python/materialize/data_ingest/executor.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/executor.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/worker.py

This should fix https://github.com/MaterializeInc/materialize/issues/26422.
8620aa8090 tests: parallel workload: rename executor classes
594b6635b7 tests: parallel workload: assign IDs to workers
e8e4bfad7a tests: parallel workload: add counter to ParallelWorkloadExecutor
ab1bd00381 tests: parallel workload: use unique S3 key
https://buildkite.com/materialize/nightlies/builds/7239

tests: fix parallel-workload with 100 threads

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.96.0-dev

---

src/testdrive/src/action/sql.rs

This helps in particular when envd or clusterd get stuck due to an OOM.

testdrive: apply timeout to query as well

---

misc/python/materialize/version_ancestor_overrides.py

Tracked in https://github.com/MaterializeInc/materialize/issues/26481
-

feature-benchmark: Ignore regression

---

doc/developer/command-and-response-binary-encoding.md
doc/developer/design/20210406_mapfilterproject.md
doc/developer/design/20220511_command_and_response_binary_encoding.md
doc/developer/design/20230903_avro_doc.md
doc/developer/design/20240205_cluster_specific_optimization.md
doc/developer/platform/ux.md
doc/user/content/ingest-data/postgres/amazon-rds.md
src/adapter/src/config/frontend.rs
src/adapter/src/config/mod.rs
src/adapter/src/error.rs
src/adapter/src/optimize/copy_to.rs
src/adapter/src/optimize/peek.rs
src/compute-types/src/plan/interpret/api.rs
src/expr/src/scalar/func.rs
src/lsp-server/tests/test.rs
src/ore/src/netio/socket.rs
src/persist-client/src/internal/metrics.rs
src/repr/src/explain/tracing.rs
src/repr/src/row.rs
src/storage-types/src/sources/mysql.rs
src/transform/src/union_cancel.rs

chore: remove repetitive words

---

misc/python/materialize/output_consistency/enum/enum_constant.py
misc/python/materialize/output_consistency/execution/evaluation_strategy.py
misc/python/materialize/output_consistency/execution/query_execution_manager.py
misc/python/materialize/output_consistency/expression/expression.py
misc/python/materialize/output_consistency/expression/expression_with_args.py
misc/python/materialize/output_consistency/generators/expression_generator.py
misc/python/materialize/output_consistency/generators/query_generator.py
misc/python/materialize/output_consistency/input_data/test_input_data.py
misc/python/materialize/output_consistency/input_data/test_input_operations.py
misc/python/materialize/output_consistency/input_data/test_input_types.py
misc/python/materialize/output_consistency/output/reproduction_code_printer.py
misc/python/materialize/output_consistency/output_consistency_test.py
misc/python/materialize/output_consistency/query/query_template.py
misc/python/materialize/output_consistency/runner/test_runner.py

2c8e9e713a output consistency: Expression: fix unimplemented method
71a849579e output consistency: Expression: add default param values
a3762dc4c3 output consistency: allow more options in QueryTemplate
90c0e90ce4 output consistency: allow overriding input data
c990db545d output consistency: rework input data to avoid circular dependency
cbd69ef136 output consistency: support predefined queries
efc60784d6 output consistency: improve test reporting
7864a8c7b9 output consistency: limit number of reproduction queries
7536e298dc output consistency: introduce StringConstant
4362ada49d output consistency: order by expressions

output consistency: support predefined queries

---

doc/user/content/customer-responsibilities.md

PR adds a new page to our customer docs explicitly outlining our shared responsibility model., 
Internal review identified the need for an SRM docs page.
Should only modify /docs by adding a new markdown page.

Add customer-facing docs

---

misc/python/materialize/feature_benchmark/benchmark.py
misc/python/materialize/feature_benchmark/scenario.py
misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
test/feature-benchmark/mzcompose.py

Nightly: https://buildkite.com/materialize/nightly/builds/7305

feature benchmark: add scenarios ManySmallInserts and ManySmallUpdates

---

misc/python/materialize/output_consistency/expression/expression_with_args.py
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Nightly: https://buildkite.com/materialize/nightly/builds/7297

output consistency: text operations: support regex flags

---

misc/python/materialize/checks/all_checks/explain_catalog_item.py

As seen in https://buildkite.com/materialize/nightly/builds/7336#018ec7c9-1388-403f-97eb-d9514a48cd70
Follow-up to https://github.com/MaterializeInc/materialize/pull/26460
-

platform-checks: Fix explain

---

src/environmentd/tests/server.rs

tests: Add retries to test_storage_usage_collection_interval

---

test/testdrive/divergent-dataflow-cancellation.td

Seen failing in https://buildkite.com/materialize/test/builds/80390#018ec8f0-fdf4-4a72-9f61-a8de4a7369c8
-

testdrive: Adapt divergent-dataflow-cancellation.td

---

src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/lib.rs
src/persist-client/src/read.rs
src/persist-client/src/write.rs

persist: fix clippy lints and --release warns

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.97.0-dev

---

doc/user/content/releases/v0.95.md
doc/user/content/releases/v0.96.md

doc/user: polish v0.95 release notes

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml

ci: Add some further cases for automatic retries

---

src/adapter/src/explain/optimizer_trace.rs

Large plans can hit recursion limits. Instead of erroring the entire statement, convert the plan into an error object that the console can detect.
- n/a

adapter: handle insight json errors

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs
src/catalog/src/durable/transaction.rs

Previously, when an introspection source was removed from Materialize, all introspection source indexes in the Introspection Source Index catalog collection corresponding to the dropped introspection source would get leaked and never cleaned up. If someone were to go through all persisted introspection source indexes, they would see that there were some invalid indexes persisted and likely get confused or panic.
This commit fixes the described issue by removing all old introspection source indexes on startup. This is similar to what we do for builtin items. There is still no clean up for builtin roles, clusters, and cluster replicas.

catalog: Clean up old introspection sources

---

src/testdrive/src/action/consistency.rs

Preparatory work for https://github.com/MaterializeInc/materialize/issues/24845, where we want to introduce more concurrency to the Coordinator and Controllers.
The heuristic of only retrying when there is no more critical handle registered is not always correct. With the refactored StorageController/StorageCollections the handle can be expired early but the append to the empty upper antichain _or_ the downgrade to the empty since can take a bit longer. This makes the test action more lenient, giving more time to converge on the expected state.
-

tests: always retry in check-shard-tombstone

---

src/adapter/src/catalog/consistency.rs

This commit adds a consistency check for role membership in the catalog consistency checks.
Works towards resolving #26622

catalog: Add role membership consistency check

---

misc/python/materialize/zippy/mz_actions.py
test/zippy/mzcompose.py

Fixes: https://github.com/MaterializeInc/materialize/issues/26643
-

zippy: Try disabling toxiproxy

---

doc/user/content/ingest-data/fivetran.md

Fix destiniation typo

---

test/bounded-memory/mzcompose.py

Fixes: https://github.com/MaterializeInc/materialize/issues/26514
-

bounded-memory: Reduce memory for large transactions again

---

src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/timestamp_selection.rs

We should not look to the controller for information about frontiers,
the only thing we can be certain about is the read holds that we got,
and it is sufficient to report those in case we can't determine a good
timestamp.
Motivated by this discussion: https://materializeinc.slack.com/archives/C058H9MH8P3/p1713360462650749?thread_ts=1713345943.820959&cid=C058H9MH8P3.
There will be some more PRs where I change the adapter to look at read holds instead of asking the controller(s) about sinces.
-

adapter: look at ReadHolds instead of sinces when reporting timestamp error

---

doc/user/content/free-trial-faqs.md
doc/user/content/sql/show-cluster-replicas.md

* This PR refactors existing documentation.
- n/a

doc/user: reflect new quickstart cluster size of 25cc

---

doc/user/content/sql/create-cluster.md

Update quickstart cluster size to 25cc

---

misc/python/materialize/cli/ci_upload_heap_profiles.py

ci-upload-heap-profiles: Improve file format

---

doc/user/content/releases/v0.96.md
doc/user/content/sql/system-catalog/mz_catalog.md

**WIP** Release notes for v0.96. 👀 
@evanharmon @petrosagg: this covers the step of bumping the release version in the docs.

doc/user: polish v0.96 release notes

---

doc/user/content/ingest-data/redpanda-cloud.md

Updating the Redpanda Cloud guide to be compatible with the new Redpanda Cloud v2 platform.

Doc: Update Redpanda Cloud guide

---

src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres/snapshot.rs

This reverts commit 85464f10d388bed324dd80a557264ac4bfc4787f from PR #26691 
Fixes https://github.com/MaterializeInc/materialize/issues/26725
-

Revert "storage/{pg,mysql}: serialize snapshot and replication phases"

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/imports.lock
src/aws-secrets-controller/Cargo.toml
test/aws-localstack/mzcompose.py

Fixes https://github.com/MaterializeInc/materialize/issues/26751
draft PR to trigger nightly tests
-

Fix AWS issue after recent nightly update

---

doc/user/content/ingest-data/amazon-eventbridge.md
doc/user/content/sql/create-source/webhook.md

See slack convo. Added the batching call out for eventbridge.
https://materializeinc.slack.com/archives/C04LQV4KUR4/p1711441695111639?thread_ts=1711392803.126359&cid=C04LQV4KUR4

Added eventbridge batching link to our docs.

---

src/compute/src/render.rs

This PR makes compute replicas suspend index imports until the dataflow start signal is fired (i.e. the dataflow is scheduled). Suspension works by adding an operator after the `import_frontier` operator that holds back any emitted data until it observes the start signal. The data needs to be buffered in the time between, but it consists only of references to batches, so this should be efficient.
Resolves a limitation in the original implementation of sequential hydration (#25271).
- N/A

compute: suspend index imports

---

src/aws-util/src/s3_uploader.rs
src/storage-operators/src/s3_oneshot_sink/parquet.rs
src/storage-operators/src/s3_oneshot_sink/pgcopy.rs

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/26740
The main change is simply to run the `client.upload_part()` call in `s3_uploader.rs` inside a tokio spawned task to upload in the background as other parts are prepared. However this allowed simplification of other bits in `s3_uploader.rs` and `pgcopy.rs` / `parquet.rs` since the `upload_part_internal` method no longer needed to be async.
The existing tests in `test/copy-to-s3`, `test/testdrive/copy-to-s3-minio.td`, and `test/aws-localstack/copy-to-s3/copy-to-s3.td` should validate this change
-

storage/copy-to-s3: Upload parts in s3 uploader concurrently

---

Cargo.lock
src/arrow-util/src/builder.rs
src/sql/Cargo.toml
src/sql/src/plan/statement/dml.rs
test/testdrive/copy-to-s3-minio.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/26697
-

storage/copy-to-s3: Validate copy configuration before writing to S3

---

doc/user/content/releases/v0.96.md
doc/user/content/releases/v0.97.md
doc/user/content/releases/v0.98.md
doc/user/content/sql/system-catalog/mz_internal.md

**WIP** Release notes for v0.97. 🌧️
@jpepin @aalexandrov: this covers the step of bumping the release version in the docs.

doc/user: polish v0.97 release notes

---

doc/user/content/sql/create-source/webhook.md

doc: fix typo, DISCINCT to DISTINCT

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This resolves https://github.com/MaterializeInc/materialize/issues/26754.

postgres consistency: add ignore for LIMIT 0

---

src/compute/src/sink/persist_sink.rs

This PR changes the compute persist_sink to handle `Ok` streams (i.e. `Row`s) separately from `Err` streams (i.e. `DataflowError`s). This lets us avoid storing and passing around `Result<Row, DataflowError>` values, which introduce 8 bytes of overhead each for the `Result` tag.
* This PR implements a memory optimization.
In this workload, the rehydration peak memory usage decreased from 11.8 GiB to 9.8 GiB with this PR. So I think making this change is worthwhile even though it increases the amount of boilerplate in `persist_sink`. Lmk if you have ideas for making the implementation nicer!
```sql
create table t (a int);
insert into t select generate_series(1, 10000);
create materialized view cross as select t1.a x, t2.a y from t t1, t t2;
```
- N/A

compute: persist_sink: separate `Ok`s and `Err`s

---

misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py

Nightly: https://buildkite.com/materialize/nightly/builds/7583 ✅ (failure is unrelated and addressed with https://github.com/MaterializeInc/materialize/pull/26841)

output consistency: add initcap function

---

src/storage/src/storage_state.rs

We used to hold a handle in the sink to help "ride out" environmentd downtime. Critical handles now handle this case more definitively.
Previously-unspecified cleanup.
-

[storage] Remove the now-useless sink handle

---

misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/26841.
Nightly: https://buildkite.com/materialize/nightly/builds/7593

postgres consistency: fix ignore entry

---

misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/values/bytea_values_provider.py
misc/python/materialize/output_consistency/input_data/values/text_values_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Nightly: https://buildkite.com/materialize/nightly/builds/7603
Identified issues:
* https://github.com/MaterializeInc/materialize/issues/26846

output consistency: add some further values

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios.py
test/platform-checks/mzcompose.py

Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fconf-prop-scenario

tests: platform checks: support changing system vars, add scenario TogglePersistRoundtripSpine
