MaterializeInc/materialize

- Cargo.lock
- src/materialized/Cargo.toml
I also have a pending todo to update the release checklist, will follow up with that.
> v0.1.3-* -> v0.1.4-dev

- Cargo.lock
- ci/test/catalog-compat.compose.yml
- ci/test/catalog-compat/Dockerfile
- ci/test/catalog-compat/catcompatck
- ci/test/pipeline.yml
- src/catalog/Cargo.toml
- src/catalog/sql.rs
> catalog: reintroduce and validate backwards compatibility

- doc/user/sql/create-source.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2367)
> fix broken doc internal link

- bin/resync-submodules
resync-submodules runs the Git incantations that fix 99% of problems
with submodules.
> bin: add resync-submodules command

- src/expr/scalar/func.rs
- src/repr/scalar/mod.rs
- src/sql/query.rs
- test/sqllogictest/cockroach/extract.slt
- www/layouts/partials/sql-grammar/bnf/func-extract.bnf
> sql: support EXTRACT(epoch FROM ...)

- src/expr/scalar/func.rs
- src/sql/query.rs
Fixes https://github.com/MaterializeInc/materialize/issues/2388
> Check types are comparable in USING

- ci/slt/slt.sh
> Wait for postgres

- src/materialized/bin/materialized.rs
- src/materialized/lib.rs
- src/materialized/tests/util.rs
> Allow user to specify the address to bind to

- src/avro/decode.rs
- src/avro/encode.rs
- src/avro/schema.rs
- src/avro/types.rs
- src/interchange/avro.rs
- src/repr/scalar/jsonb.rs
- src/testdrive/src/format/avro.rs
- test/testdrive/basic.td
> Support ingesting JSON-values fields in Avro

- src/sql-parser/src/parser.rs
- src/sql-parser/tests/sqlparser_common.rs
- test/sqllogictest/subquery.slt
Fix #2440. Thanks for catching @sploiselle!
> sql-parser: support IN (VALUES ...)

- www/data/sql_funcs.json
> docs: add scalar and subquery operators

- src/dataflow/sink/kafka.rs
- src/interchange/avro.rs
> WIP: Accurately converting Differential records to Debezium

- demo/chbench/dc.sh
- demo/chbench/docker-compose.yml
* Expose more materialize options via dc.sh/docker-compose
* Fix `clean-load-test` prometheus startup
> dc.sh fixes for load tests

- src/coord/coord.rs
- src/expr/explain.rs
- src/sql-parser/src/ast/mod.rs
- src/sql-parser/src/ast/visit_macro.rs
- src/sql-parser/src/keywords.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/sqlparser_common.rs
- src/sql/lib.rs
- src/sql/statement.rs
- test/sqllogictest/explain.slt
See the test at the end of explain.slt for an example.
> Implement EXPLAIN TYPED

- src/coord/coord.rs
No changes; just code movement. This is necessary to facilitate another
refactor; plus this method was way too large.
> coord: split sequence_plan into multiple methods

- Cargo.lock
- src/coord/Cargo.toml
- src/coord/command.rs
- src/coord/coord.rs
- src/coord/tests/noblock.rs
- src/pgwire/protocol.rs
- src/sql/lib.rs
- src/sql/statement.rs
- src/sqllogictest/src/fuzz.rs
- src/sqllogictest/src/runner.rs
Just some minor housekeeping for the coord package.
> coord: small cleanups

- Cargo.lock
- src/coord/coord.rs
- src/dataflow-types/logging.rs
- src/dataflow/logging/materialized.rs
- src/dataflow/sink/kafka.rs
- src/testdrive/Cargo.toml
- src/testdrive/src/action/kafka/verify.rs
- test/testdrive/avro-sinks.td
- test/testdrive/catalog.td
- test/testdrive/show.td
- test/testdrive/sinks.td
> dataflow,testdrive: various kafka sink fixes

- src/avro/examples/benchmark.rs
- src/avro/lib.rs
- src/avro/writer.rs
- src/catalog/lib.rs
- src/coord/sink_connector.rs
- src/dataflow-types/types.rs
- src/dataflow/render/mod.rs
- src/dataflow/sink/avro_ocf.rs
- src/dataflow/sink/mod.rs
- src/interchange/avro.rs
- src/materialized/tests/sql.rs
- src/sql-parser/src/ast/mod.rs
- src/sql-parser/src/ast/visit_macro.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/sqlparser_common.rs
- src/sql/statement.rs
- src/testdrive/src/action/avro_ocf.rs
Ready for review -- have manually tested against billing demo and it looks like its working
> Avro OCF sinks

- Cargo.lock
- Cargo.toml
- deny.toml
- misc/editor/vscode/syntaxes/testdrive.tmLanguage.json
- src/avro/reader.rs
- src/avro/writer.rs
- src/materialized/tests/sql.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/avro_ocf.rs
- src/testdrive/src/action/file.rs
- src/testdrive/src/parser.rs
- test/testdrive/avro-ocf.td
- test/testdrive/avro-sources.td
- test/testdrive/csv-sources.td
- test/testdrive/regex-sources.td
- test/testdrive/sinks.td
CSV and Avro OCF sources are very elegantly tested with testdrive.
@umanwizard I figured you could review the Avro stuff and @sploiselle could review the CSV test stuff?
> testdrive: absorb a bunch more tests

- doc/user/sql/types/text.md
- doc/user/sql/types/timestamp.md
> doc/user: fix cast documentation for timestamps

- doc/user/overview/api-components.md
- doc/user/sql/create-source/kinesis-source.md
Also removed a technically harmless extra space.
> Fix broken links in kinesis docs.

- src/billing-demo/resources/views/billing_monthly_statement_export.sql.in
- src/billing-demo/src/main.rs
- src/billing-demo/src/mz_client.rs
- src/interchange/avro.rs
- test/testdrive/avro-ocf.td
- test/testdrive/avro-sinks.td
This isn't fully complete yet - needs a few more tests + currently if we ingest back the data we put in the sink topic its converted to a int8 (the correct int8 fwiw)
> WIP: Fix issues with encoding timestamps / a few other logical types

- src/expr/transform/reduction.rs
We now update the type of constant relations to reflect the nullability of the constant values found therein. If all values in a column are non-null, the column is announced as non-nullable.
I really don't understand SQL's type system, and if nullability is actually part of the *static type* rather than a dynamic property of data, we possibly should not do this.
Fixes #2529 
cc @ruchirK
> Establish nullability of constant relations

- doc/user/release-notes.md
- doc/user/sql/create-source/text-source.md
- doc/user/sql/functions/cast.md
A lot of small changes including release notes and some minor stuff like updating valid casts
> docs: misc. docs cleanup

- Cargo.lock
The new version supports vendoring libsasl.
> deps: bump rdkafka

- Cargo.lock
- deny.toml
This removes a duplicated copy of tokio-util.
> deps: bump h2

- doc/user/monitoring/_index.md
- www/config.toml
@quodlibetor I wanted to get something minimal up here that we can work forward from. Can I get your suggestions for additional content here, or do you think this is fine for a v0?
> docs: create sketch for monitoring docs

- doc/user/_index.md
- www/layouts/_default/baseof.html
Resolves issue with page title unearthed in #2483
> set html title tag to page title by default

- src/materialized/tests/sql.rs
Adds a test for tails of a non-materialized source. It's the same as the materialized case, except not materialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2587)
> Add unmaterialized tail test

- doc/developer/assets/demo/utils.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2594)
> Set database for mtrlz-shell

- src/interchange/avro.rs
- src/pgrepr/src/types.rs
- src/pgwire/message.rs
- src/repr/scalar/mod.rs
- src/sql/lib.rs
- src/sql/statement.rs
This will probably cause merge conflicts, so getting it in ahead of the rest of the array stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2600)
> Add ScalarType::Array

- src/coord/timestamp.rs
I changed Avro decoding to be synchronous, which broke the build when I landed it. I need to also update some call sites.
If no one reviews, I will land this without review once tests pass. Just tagging some relevant people in case they care to look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2604)
> Fix merge skew

- doc/developer/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2605)
> Fix typo in release documentation

- demo/chbench/dc.sh
This doesn't emit possibly 10s of thousands of lines of chbench logs, just the last 50.
The changes to dc_logs are ugly, the right thing to do is to more formally support
--tail, but that requires changine the external api and doesn't seem like it's worth it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2612)
> dc.sh: Improve log output on load test, make sure prometheus is up

- demo/chbench/dc.sh
The behavior is basically undefined, and if you happen to be on a shared ec2 instance
with multiple people working simultaneously (or with the automation) it can cause serious
problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2611)
> Don't allow running dc.sh in parallel

- Cargo.lock
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2624)
> Bump master to v0.2.1-dev

- doc/user/release-notes.md
- www/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2625)
> Update docs for v0.2.0

- doc/user/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2626)
> doc/user: copyedit 0.2 release notes

- doc/user/demos/business-intelligence.md
Close #2627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2628)
> docs: reword metabase guidance for surfacing views' embedded queries

- ci/test/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2655)
> ci/test: unbrick deb build (hopefully)

- LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2662)
> update version and change date

- doc/developer/release-checklist.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2664)
> doc/developer: add note about updating LICENSE terms

- ci/test/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2668)
> ci/test: actually fix deb publishing

- src/materialized/tests/pgwire.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2669)
> bump wait time in `test_conn_params`

- src/dataflow/render/mod.rs
Requested by @frankmcsherry in #2441. @frankmcsherry, how's this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2640)
> dataflow: describe error handling approach

- src/repr/row.rs
Adds `finish_and_reuse` which copies out of the `RowPacker` rather than taking its allocation. The intent is to reduce the number of allocations in situations where a long-lived `RowPacker` makes sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2680)
> Add non-dropping finish to RowPacker

- ci/plugins/mzcompose/hooks/command
- src/testdrive/src/action/kinesis.rs
- src/testdrive/src/action/kinesis/create_stream.rs
- src/testdrive/src/action/kinesis/update_shards.rs
- src/testdrive/src/action/kinesis/verify.rs
- src/testdrive/src/util.rs
- src/testdrive/src/util/kinesis.rs
- test/testdrive/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2693)
> testdrive: hopefully fix some kinesis-related flakiness

- bin/mypy
- bin/mzcompose
- bin/mzimage
- bin/pyactivate
- bin/pyfmt
- ci/test/build.sh
- doc/developer/mzbuild.md
This makes paths much easier to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2692)
> python: reorganize python activation code

- ci/test/pipeline.yml
- test/testdrive/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2697)
> testdrive: temporarily disable flaky tests

- misc/www/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2701)
> www: fix link to python api docs

- src/dataflow/source/kinesis.rs
Our newest testdrive test ([ci-only/kinesis.td](https://github.com/MaterializeInc/materialize/blob/master/test/testdrive/ci-only/kinesis.td)) has repeatedly hit the Kinesis `ListShards` rate limit: https://github.com/MaterializeInc/materialize/issues/2694.
The PR introduces a new `KINESIS_SHARD_REFRESH_RATE` constant. Moving forward, we will only hit the `ListShards` API if it's been longer than 60 seconds (an initial guess at what a reasonable rate would be). This should avoid the rate limit issue and improve Kinesis source performance overall.
NOTE: I am going to start performance testing our Kinesis source this week, so I'll keep an eye on if this seems reasonable and helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Introduce shard refresh rate

- misc/python/materialize/mzbuild.py
mzbuild was including the entire file mode in the fingerprint, when it
meant to do what Git does, and include only the executable bit and the
symlink bit. The other bits often vary from environment to environment,
but not in a way meaningful to Git or mzbuild.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2720)
> mzbuild: fingerprint file modes appropriately

- src/coord/coord.rs
- src/dataflow-types/types.rs
- src/dataflow/decode/csv.rs
- src/dataflow/decode/mod.rs
- src/dataflow/render/mod.rs
- src/repr/relation.rs
A revision of #2598 without merge conflicts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2658)
> WIP Inter-dataflow optimization, pushed to sources

- bin/ci-builder
- ci/deploy/linux.py
- ci/test/build.py
- misc/python/materialize/ci_util.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2728)
> ci: fix deploy build

- bin/pyactivate
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2734)
> pyactivate: install CI python deps on macOS

- src/expr/transform/projection_extraction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2731)
> Update column reference to an input column

- src/expr/relation/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2733)
> Add notes on memory requirements

- Cargo.toml
- ci/deploy/linux.py
- doc/developer/mzbuild.md
- misc/python/bin/mzcompose.py
- misc/python/bin/mzimage.py
- misc/python/materialize/cargo.py
- misc/python/materialize/ci_util.py
- misc/python/materialize/mzbuild.py
See commits for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2737)
> mzbuild: finer-grained rust dependency tracking

- misc/python/bin/mzimage.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2738)
> mzimage: print usage on `-h/--help`

- doc/user/release-notes.md
- doc/user/sql/create-source/_index.md
- doc/user/sql/create-source/avro-file.md
- doc/user/sql/create-source/avro-kafka.md
- doc/user/sql/create-source/csv-file.md
- doc/user/sql/create-source/json-kinesis.md
- doc/user/sql/create-source/protobuf-kafka.md
- doc/user/sql/create-source/text-file.md
- www/layouts/partials/sql-grammar/bnf/create-source-avro-file.bnf
- www/layouts/partials/sql-grammar/rr-diagrams/create-source-avro-file.html
Picking up documentation from #2497
@quodlibetor Can you PTAL @ `doc/user/sql/create-source/avro-file.md` ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2567)
> docs: avro files + create source filename restructure

- src/expr/relation/mod.rs
- src/expr/transform/mod.rs
- test/sqllogictest/chbench.slt
- test/sqllogictest/joins.slt
- test/sqllogictest/tpch.slt
I believe this is semantically correct, but potentially causes problems downstream in the optimizer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2727)
> Proposed fix for #2724

- src/materialized/bin/materialized.rs
- www/static/_redirects
We would much rather receive GitHub issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2723)
> materialized: don't ask for emailed bug reports

- bin/ci-builder
- ci/test/mkpipeline.py
- ci/test/mkpipeline.sh
- ci/test/pipeline.template.yml
- misc/python/bin/mzimage.py
- misc/python/materialize/mzbuild.py
Avoid rebuilding unnecessary jobs. See commits for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2746)
> ci: speed things up

- ci/test/pipeline.template.yml
I missed this in #2746.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2750)
> ci: test miri when src/repr changes

- src/coord/coord.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2756)
> Refer to issue re: CREATE TABLE persistence

- demo/chbench/mzcompose.yml
So that it can write to the WAL that it generates on startup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2757)
> Propagate uid-gid for prometheus

- bin/lint
- demo/chbench/grafana/conf/dashboards/.gitattributes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2758)
> Hide dashboard .json files in GitHub code review UI

- Cargo.lock
- demo/chbench/grafana/conf/dashboards/overview.json
- src/coord/Cargo.toml
- src/coord/timestamp.rs
- src/dataflow/source/kafka.rs
- src/expr/id.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2745)
> Add "messages distance behind kafka" prometheus metrics

- src/dataflow-types/types.rs
- src/dataflow/render/mod.rs
- src/dataflow/source/file.rs
- src/dataflow/source/kafka.rs
- src/dataflow/source/kinesis.rs
- src/dataflow/source/mod.rs
- src/ore/iter.rs
Put a few more parameters into the shared source configuration, so more
logic can be shared between source configurations.
This doesn't change any sematics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2764)
> dataflow: rework source configuration

- Cargo.lock
- src/catalog/Cargo.toml
- src/coord/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2774)
> bump rusqlite version

- demo/chbench/dc.sh
- misc/shlib/shlib.bash
- src/peeker/args.rs
- src/peeker/config.toml
- src/peeker/peeker.rs
Running dc.sh demo-load --up will now create sources as materialized (and work from a clean slate).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2769)
> dc.sh and peeker now support creating materialized sources

- ci/deploy/linux.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2791)
> disable materialized-unstable uploads.

- misc/python/materialize/bintray.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2793)
> fix `publish_wait_for_secs` spelling

- misc/python/bin/mzimage.py
- misc/python/materialize/mzbuild.py
Discovered by @quodlibetor. See the comment within for the full story.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2782)
> mzbuild: don't panic on unstaged deletions

- src/dataflow/render/mod.rs
This PR updates source creation to respect the `as_of` component of a `DataflowDesc`. This was previously used for index imports, but not for sources. This may not have been a problem, as it was not clear that you could create a `DataflowDesc` that had an `as_of` set and used bare sources, but it is becoming possible so we should fix it up.
@wangandi do you mind checking the code around upserts? I believe the only thing that needed to be fixed was advancing the timely timestamp associated with each message, but if there is time information stashed in any records (I didn't see any) we would want to advance that too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize …
> Implement `as_of` for sources

- src/sql/statement.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2459)
> Quick check that a file exists when creating a source interactively 

- Cargo.lock
- deny.toml
- src/ccsr/Cargo.toml
- src/ccsr/lib.rs
- src/ccsr/tests/client.rs
- src/coord/sink_connector.rs
- src/dataflow-types/Cargo.toml
- src/dataflow-types/types.rs
- src/dataflow/decode/avro.rs
- src/dataflow/decode/mod.rs
- src/interchange/avro.rs
- src/sql/Cargo.toml
- src/sql/kafka_util.rs
- src/sql/statement.rs
- src/testdrive/src/action.rs
@benesch Have a number of questions:
- Generating the certs for testing in a Docker container requires Java and
OpenSSL, creating a 100+mb image for some small text files. Generating the certs
w/ 10-year expiration and storing them in an image seems much more efficient. Is
there a way to accomplish that? [Locally I'm able to invoke the shell script to
generate the certs and go from there](https://github.com/MaterializeInc/materialize/compare/master...sploiselle:client-ssl-support#diff-7bc9447f8ceba3c041abea8b729cfd0fR5-R11), but is there a way to propagate that image
that you'd find satisfactory? Like, is there a `publish privately` option?
- I need to ensure that my certificates are valid before creating `ccsr::AsyncClient`.
My code tests that in …
> Support SSL auth for Kafka clusters

- src/coord/coord.rs
- src/sql-parser/src/ast/mod.rs
- src/sql-parser/src/ast/query.rs
- src/sql-parser/src/ast/visit_macro.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/sqlparser_common.rs
- src/sql/normalize.rs
- src/sql/query.rs
- src/sql/transform.rs
- test/testdrive/jsonb.td
This is some groundwork for the name resolution refactoring I'm planning. Definitely review commit by commit, because the last commit is pure code movement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2829)
> sql,sql-parser: assorted cleanups

- doc/user/known-limitations.md
- doc/user/release-notes.md
FYI @cuongdo, thanks for the ping!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2843)
> Release notes: Kinesis multi-shard support

- src/aws-util/kinesis.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2853)
> Add each shard id individually

- src/catalog/lib.rs
Fixes #2522
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2850)
> catalog: suppress log output for placeholder sink entries

- src/dataflow/sink/kafka.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2855)
> dataflow: improve sink responsiveness and perf

- src/materialized/tests/pgwire.rs
- src/pgwire/protocol.rs
Use the new support for multi-statement execution requests to clean up
some of our test code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2775)
> materialized: use new multi-statement execute support

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
Closes #2722
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2863)
> Update LICENSE and materialized version post 0.2.1

- src/ccsr/tls.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2867)
> ccsr: fix broken documentation comment

- src/coord/timestamp.rs
- src/dataflow-types/errors.rs
- src/dataflow-types/lib.rs
- src/dataflow/arrangement/manager.rs
- src/dataflow/decode/mod.rs
- src/dataflow/operator.rs
- src/dataflow/render/context.rs
- src/dataflow/render/delta_join.rs
- src/dataflow/render/mod.rs
- src/dataflow/render/reduce.rs
- src/dataflow/server.rs
- src/dataflow/source/file.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/file.rs
- test/testdrive/csv-sources.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2841)
> Use RTEs to handle I/O errors in file sources

- doc/developer/release-checklist.md
Most importantly this says that we should create an issue for the checklist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2859)
> Update release checklist

- doc/user/monitoring/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2885)
> Improve dashboard documentation

- src/dataflow/render/mod.rs
- src/expr/explain.rs
- src/expr/lib.rs
- src/expr/relation/func.rs
- src/expr/relation/mod.rs
- src/expr/transform/column_knowledge.rs
- src/expr/transform/demand.rs
- src/expr/transform/nonnull_requirements.rs
- src/expr/transform/projection_lifting.rs
- src/expr/transform/reduction.rs
- src/sql/explain.rs
- src/sql/expr.rs
- src/sql/query.rs
- test/sqllogictest/table_func.slt
- www/data/sql_funcs.yml
This change required generalizing FlatMapUnary to take multiple
arguments.
This commit does not add support for either of the three-argument
versions of generate_series.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2857)
> Basic support for generate_series

- doc/user/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2897)
> release notes: Kafka SSL & krb5 auth

- ci/deploy/linux.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2901)
> re-enable publishing of materialized-unstable

- src/expr/scalar/func.rs
- test/sqllogictest/arithmetic.slt
There's still some lingering unchecked operations, at least in the
interval codepath, but I figured I'd do these simpler ones first to make
sure this is the right change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2896)
> Use checked_* for integer addition/subtraction

- www/layouts/partials/sql-grammar/bnf/create-source-text-kafka.bnf
- www/layouts/partials/sql-grammar/rr-diagrams/create-source-text-kafka.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2902)
> docs: fix RR diagram for text over Kafka

- ci/test/pipeline.template.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2905)
> fix typo in pipeline.template.yml

- src/coord/sink_connector.rs
- src/dataflow-types/types.rs
- src/sql-parser/src/ast/mod.rs
- src/sql-parser/src/ast/visit_macro.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/sqlparser_common.rs
- src/sql/normalize.rs
- src/sql/statement.rs
This change does not address the fact that not all producer errors are being sent back - I'll put that in a separate PR
Touches #2903
Default to replication factor = 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2906)
> sql: add WITH option for users to specify sink replication factor

- src/dataflow/sink/kafka.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2909)
> dataflow: print error logs when message production fails

- demo/billing/src/config.rs
- demo/billing/src/kafka_client.rs
- demo/billing/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2922)
> Multipartition billing demo

- www/layouts/partials/create-source/connector/kafka/with-options.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2926)
> docs: add group_id_prefix Kafka config

- src/sql/kafka_util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2939)
> bug: remove errant println

- doc/user/sql/create-source/json-kinesis.md
- src/aws-util/kinesis.rs
- src/coord/timestamp.rs
- src/dataflow-types/types.rs
- src/dataflow/source/kinesis.rs
- src/sql/statement.rs
- src/testdrive/src/action.rs
- test/testdrive/ci-only/kinesis.td
- test/testdrive/kinesis.td
- www/layouts/partials/create-source/connector/kinesis/with-options.html
Closes #2837 
@JLDLaughlin I updated the docs regarding this, but can you handle any user communicating who will need to know about this change?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2941)
> refactor: rename Kinesis access_key to access_key_id

- .editorconfig
- Cargo.lock
- src/ore/fmt.rs
- src/pgrepr/Cargo.toml
- src/pgrepr/src/value.rs
- src/pgwire/protocol.rs
- src/repr/Cargo.toml
- src/repr/benches/strconv.rs
- src/repr/scalar/strconv.rs
- src/repr/tests/strconv.rs
- src/sql-parser/src/parser.rs
- src/sqllogictest/src/runner.rs
- test/lang/js/params.test.ts
- test/sqllogictest/list.slt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2776)
> repr,pgrepr: tweak list encoding and decoding

- doc/user/monitoring/_index.md
- misc/monitoring/dashboard/Dockerfile
- misc/monitoring/dashboard/bin/snapshot-prom
- misc/monitoring/dashboard/conf/supervisord.conf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2950)
> dashboard: Allow snapshots from prometheus

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2963)
> version: bump for 0.2.3-dev cycle

- Cargo.lock
- src/materialized/Cargo.toml
- src/materialized/bin/materialized.rs
- src/materialized/http.rs
- src/materialized/lib.rs
- src/materialized/mux.rs
- src/materialized/tests/pgwire.rs
- src/materialized/tests/util.rs
- src/ore/netio/stream.rs
- src/pgwire/Cargo.toml
- src/pgwire/codec.rs
- src/pgwire/id_alloc.rs
- src/pgwire/lib.rs
- src/pgwire/message.rs
- src/pgwire/protocol.rs
- src/pgwire/secrets.rs
- src/pgwire/server.rs
~This still needs a test, but the required refactorings are rather large, so figured I'd throw it up sooner rather than later.~
Fix #739.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2900)
> materialized: support tls pgwire encryption

- ci/test/pipeline.template.yml
Resubmitting #2985. Turns out the proper fix is taking a while.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2988)
> ci/test: actually disable chbench job

- doc/user/monitoring/_index.md
@quodlibetor This looks like it's supposed to link to Docker Hub; is that right? If so, please feel free to merge on your review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2980)
> docs: fix broken link

- bin/ci-builder
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2990)
> bin/ci-builder: explain subcommands in --help text

- src/dataflow/source/kafka.rs
**The problem**
Source timestamping was not initially designed to support compacted topics. It consequently assumed that the operator would receive a message for every offset. This is no longer true for compacted topics
**The solution**
Given Kafka consumers continue to process topics in monotonically increasing order, this PR modifies the timestamp-closing logic to close out timestamps when a source observes the first offset greater than the highest offset associated with that timestamp (as opposed to equal)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2968)
> Fix timestamp closing logic for compacted topics

- netlify.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2992)
> docs: fix deploy job

- netlify.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2993)
> netlify: fix blog overlay

- doc/user/config.toml
- doc/user/content/known-limitations.md
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/2998)
> doc/user: add release notes for v0.2.2

- doc/user/assets/sass/_content.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3002)
> doc/user: one more minor spacing fix

- src/dataflow-types/types.rs
- src/repr/relation.rs
- test/testdrive/avro-registry.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3011)
> Make sure to add keys to `DataEncoding` when using non-Upsert format.

- Cargo.lock
- doc/user/assets/sass/_content.scss
- doc/user/content/cli/_index.md
- doc/user/content/release-notes.md
- doc/user/layouts/partials/create-source/connector/kinesis/with-options.html
- doc/user/layouts/partials/toc.html
- src/materialized/Cargo.toml
- src/materialized/bin/materialized.rs
Details in individual commit messages!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3004)
> doc/user: document TLS encryption + Kinesis credential changes

- doc/user/content/release-notes.md
- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3013)
> some doc updates

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/musing.md
- .github/ISSUE_TEMPLATE/refactoring.md
- .github/ISSUE_TEMPLATE/release.md
Fix #2748.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3016)
> github: rework issue templates for external contributors

- README.md
- doc/user/content/_index.md
- doc/user/content/overview/api-components.md
- misc/dist/materialized.service
Marketing asked that we change some copy to reflect new product positioning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3021)
> docs: reflect marketing copy

- ci/test/mkpipeline.py
- demo/billing/mzcompose.yml
- misc/python/bin/mzimage.py
- misc/python/materialize/cargo.py
- misc/python/materialize/git.py
- misc/python/materialize/mzbuild.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3017)
> demo: run billing demo on multipartition kafka topics in ci

- bin/mzconduct
- demo/chbench/mzcompose.yml
- misc/python/bin/mzconduct.py
- misc/python/materialize/spawn.py
- misc/python/materialize/ui.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3030)
> Several improvements to mzconduct error handling

- misc/monitoring/dashboard/mzbuild.yml
This one claims to have memory and on-disk storage size improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3032)
> Bump version of prometheus in the dashboard

- demo/chbench/mzcompose.yml
- doc/developer/metabase-demo.md
- doc/developer/mzbuild.md
- doc/user/content/demos/business-intelligence.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3025)
> Fix public docs for chbench business intelligence demo

- Cargo.lock
- demo/billing/src/kafka_client.rs
- src/testdrive/src/action/kafka/ingest.rs
- src/testdrive/src/action/sleep.rs
There are several breaking changes in the latest version of
rust-rdkafka. Upgrade early to shake out any problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3049)
> deps: upgrade to latest rdkafka

- src/sql-parser/tests/sqlparser_common.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3064)
> Use one_statement_parses_to

- doc/user/content/sql/create-source/_index.md
- doc/user/content/sql/create-source/json-kinesis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3066)
> Add Beta status to Kinesis docs

- doc/user/content/sql/create-source/json-kinesis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3067)
> clarify Beta status

- misc/python/bin/mzcompose.py
- misc/python/bin/mzconduct.py
For example it becomes possible with this to do:
mzconduct:
workflows:
ci-pg:
include_compose:
- pg.yml
steps:
- step: start-services
services: postgres
Allowing us to share all or almost all of the configuration, while:
* Having mutually conflicting services
* Not breaking the expectation that `mzcompose up` by itself works
* Making it easy to use the same configuration pattern between all our demos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3072)
> mzconduct: Support specifying compose files per workflow

- doc/user/content/sql/create-index.md
Reworks some details in the CREATE INDEX docs. This stops short of explaining how compaction works (the original goal) but is able to be more specific about the memory implications of creating indexes. Other minor changes that may or may not be contentious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3073)
> Rework some details

- src/sql/query.rs
- test/sqllogictest/subquery.slt
Suggested in #3045. Sometimes results in a bad outcome still, but I
think never worse than before, and I think it's actually a good bit
cleaner now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3081)
> Always plan ANY/ALL with EXISTS

- src/dataflow/logging/timely.rs
- src/dataflow/metrics/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3084)
> Add mz_scheduling_elapsed log to prometheus metrics

- src/dataflow/source/kafka.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3085)
> dataflow: add new metric for messages ingested per kafka source

- README.md
We probably also need a process for regularly checking in with the readme to see if its desynchronized/needs updating.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3076)
> update feature support in readme

- src/dataflow/source/kafka.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3088)
> dataflow: add new metrics for kafka source scheduled / metadata refresh

- src/dataflow/logging/timely.rs
- src/dataflow/metrics/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3092)
> Improve scheduling metrics

- src/sql-parser/src/parser.rs
- src/sql-parser/tests/sqlparser_common.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3087)
> Some precedence refactoring+fixes

- misc/monitoring/dashboard/Dockerfile
- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3094)
> dashboard: Adde new panels for several new metrics

- src/coord/timestamp.rs
@nacrooks apologies if this interferes with any diffs you have out; I noticed this and wrote up the diff to see if I my hunch was correct, and didn't want to forget about it.
The real time Kafka timestamper never polls the consumer, so all
creating a consumer group and subscription serves to do is to ensure
that we see timeouts every time we hit the max.poll.interval.ms
interval.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3095)
> coord: don't subscribe the timestamper to rt topics

- misc/monitoring/dashboard/conf/grafana/dashboards/meta.json
- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
- src/dataflow/logging/timely.rs
- src/dataflow/metrics/mod.rs
- src/materialized/http.rs
- src/materialized/lib.rs
This should definitely be reviewed commit by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3106)
> Add a meta-prometheus dashboard panel, delete some problematic metrics

- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3108)
> dashboard: Add new source scheduled count panel

- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3113)
> dashboard: add rate and description to source scheduled counts

- ci/test/slt-fast.sh
- test/sqllogictest/cockroach/subquery_correlated.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3116)
> Enable subquery_correlated file

- src/dataflow/source/kafka.rs
The source operator should only add an entry for the TimestampUpdate update if it is on a worker that is actively reading the source and downgrading the capability. Otherwise this will cause the hashmap to grow unbounded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3119)
> Fixes memory leak in TimestampUpdate table

- src/dataflow/source/kafka.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3103)
> dataflow: use inc() instead of inc_by(1)

- src/dataflow/decode/mod.rs
- src/dataflow/render/mod.rs
This PR quickly moves capability information for data from sources into payload data. This allows us to manipulate it more casually without blocking computation. We replace the use of the `aggregate` operator with one that aggregates by payload time (rather than capability).
There are various performance weaknesses in this implementation, and a more complete implementation would look like the `MergeBatcher` in differential which more carefully manages arbitrarily large numbers of distinct times.
The intended behavior of this PR is that we can now load arbitrarily large batches of source data at the same timestamp with a working footprint that more closely resembles the number of distinct keys.
It is not yet tested, so while it is good to start looking at there may be bugs!
---
This change …
> Treat source timestamps as data

- doc/user/content/demos/business-intelligence.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3135)
> doc/user: fix business intelligence deployment diagram

- ci/www/.gitignore
- ci/www/public/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3153)
> www: fix broken link checker

- misc/python/materialize/cli/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3158)
> py: Add docs and copyright notice to materialize.cli

- src/dataflow/decode/avro.rs
- src/dataflow/decode/mod.rs
- src/interchange/avro.rs
- src/interchange/benches/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3161)
> print Kafka offset in Debezium dedupe error message

- src/dataflow/decode/avro.rs
- src/dataflow/decode/mod.rs
- src/dataflow/render/mod.rs
- src/interchange/avro.rs
- src/interchange/benches/avro.rs
This involves piping a debug name through a bunch of places. It's only used in the Debezium case, but it doesn't hurt to have it in those other places; we might use it in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3163)
> Add topic name to warning message; change "position" to "offset".

- src/coord/catalog.rs
- test/testdrive/temporary-views.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3166)
> Temporary view name collisions

- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
It gained a bunch of debugging panels interspersed with things that are perhasps more
user-interesting. This doesn't delete any panels, but it does reorganize them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3162)
> Clean up dashboard for users again

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3169)
> chbench: update load test to start dashboard earlier

- misc/python/materialize/ui.py
The automation user does not have a HOME
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3173)
> mzconduct: Just log to /tmp in automation

- ci/plugins/mzconduct/README.md
- ci/plugins/mzconduct/hooks/command
- ci/plugins/mzconduct/hooks/pre-exit
- ci/plugins/mzconduct/plugin.yml
- ci/test/mkpipeline.py
- ci/test/pipeline.template.yml
- demo/billing/ci/Dockerfile
- demo/billing/mzcompose.yml
- demo/chbench/mzcompose.yml
- misc/python/materialize/cli/mzconduct.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3168)
> Add mzconduct buildkite integration, use it for chbench and billing

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3185)
> Update to v0.3.1-dev

- test/performance/perf-kinesis/src/kinesis.rs
- test/performance/perf-kinesis/src/mz.rs
Addressing a comment from https://github.com/MaterializeInc/materialize/pull/3180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3186)
> Compare durations directly

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3187)
> Update billing-demo instructions on release checklist

- misc/python/materialize/cli/mzconduct.py
- test/performance/perf-kinesis/mzcompose.yml
Next steps: update the `load_test_instances` template in the `infra` repo, update the release checklist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3188)
> Update perf-kinesis to use mzconduct

- test/performance/perf-kinesis/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3191)
> Fix perf-kinesis mzconduct command

- src/dataflow/decode/avro.rs
- src/dataflow/decode/mod.rs
- src/dataflow/render/mod.rs
- src/interchange/avro.rs
- src/interchange/benches/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3197)
> More debug info

- Cargo.lock
- demo/billing/Cargo.toml
- demo/billing/mzcompose.yml
- demo/billing/resources/views/check_sink.sql.in
- demo/billing/resources/views/invalid_sink_rows.sql.in
- demo/billing/src/config.rs
- demo/billing/src/main.rs
- demo/billing/src/mz_client.rs
Specifically, this change validates that after inserting the specified number of
messages into the source kafka topic, creating a sink, and reingesting the entire
sink, the contents of the view built from reingesting the sink match the contents
of the view that the sink was built off of.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3194)
> demo: edit billing-demo to validate that sink contains expected data

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3201)
> Remove prometheus backup step from release checklist

- src/expr/scalar/mod.rs
- test/sqllogictest/boolean.slt
- test/sqllogictest/chbench.slt
Adds some comments, and additional transformations in `ScalarExpr::reduce` for `If` variants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3199)
> Work around if statements

- doc/user/config.toml
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3215)
> v0.3.0 docs

- ci/test/slt-fast.sh
- src/sql/src/query.rs
- test/sqllogictest/cockroach/aggregate.slt
- test/sqllogictest/cockroach/apply_join.slt
Probably not gonna do any more of this, but it did give me a better feel for the landscape and I opened a couple issues as a result, so I don't think it was without value!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3198)
> Enable a couple additional logic tests

- src/repr/scalar/jsonb.rs
Follow-up comment from a review of #3195.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3217)
> repr: add some notes about possible JSON serialization panics

- demo/billing/src/config.rs
- demo/billing/src/main.rs
- demo/billing/src/mz_client.rs
Adds the option to specify --batch-size to created sources (defaults to 0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3202)
> Adding Batch size option for billing demo

- misc/python/materialize/cli/mzconduct.py
- test/performance/perf-kinesis/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3235)
> add a nightly workflow for perf-kinesis

- src/repr/src/scalar/datetime.rs
- src/repr/tests/strconv.rs
- test/sqllogictest/interval.slt
Follow-up changes from #3156.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3226)
> repr: copyedit some datetime errors

- demo/chbench/peeker-config/materialized-sources.toml
It was being ignored by the .gitignore file in that directory, making it work for me and
no one else.
Fixes #3238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3239)
> Correctly include materialized-sources.toml for the BI demo

- src/sql/src/func.rs
These two macros always need to be used together, so I think it's a bit
simpler if we merge them into just one macro!
@sploiselle what do you think of this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3247)
> sql: merge func_impls and impls macros

- src/avro/src/decode.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3253)
> Make a comment about bad code less optimistic

- src/repr/src/scalar.rs
Datum::from(UnderlyingType::constructor) is the preferred way to
construct a Datum, and indeed, no code uses these older methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3260)
> repr: remove dead Datum constructors

- src/sql/src/plan/func.rs
Less typing when adding function implementations for common (i.e. almost all) cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3270)
> sql: improve macros for function selection

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3269)
> Silence a warning from docker-compose for unset variable

- ci/test/pipeline.template.yml
- test/performance/perf-kinesis/mzcompose.yml
- test/performance/perf-kinesis/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3275)
> Add perf-kinesis to ci

- src/interchange/src/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3278)
> add trace message with full rows to Avro decode

- src/repr/src/adt/regex.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3261)
> repr: improve regex docs

- bin/lint
- demo/kafka-transactions/README.md
- demo/kafka-transactions/pom.xml
- demo/kafka-transactions/src/main/java/demo/materialize/Config.java
- demo/kafka-transactions/src/main/java/demo/materialize/StartDemo.java
- demo/kafka-transactions/src/main/java/demo/materialize/TransactionalProducer.java
- src/dataflow/src/source/kafka.rs
This PR creates a demo for generating transactions in Kafka. The demo includes a workload generator that can be configured as follows:
```
[usage: TrxKafkaDemo [-a <Producer Abort Rate>] [-b <Bootstrap Servers>]
[-d <Payload Size>] -j <Producer Transaction Id> [-k <Key Size>] -n
<Topic Name> [-o <Operation Count>] [-p <Partition Count>] [-r
<Schema Registry URL>] [-t <Transaction Mode>] [-w <Writes per
Partition>]
-a,--producer-abort <Producer Abort Rate>      Default: 0
-b,--bootstrap-servers <Bootstrap Servers>     Default: localhost:9092
-d,--payload-size <Payload Size>               Default: 100
-j,--producer-id <Producer Transaction Id>     MUST SPECIFY - This is
used to identify the same
producer instance across
process restarts
-k,--key-size <Key Size> …
```
> Transactional Producer Kafka Demo

- src/coord/src/sink_connector.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/sink/kafka.rs
- src/dataflow/src/sink/mod.rs
- src/dataflow/src/sink/util.rs
- src/sql/src/plan/statement.rs
- test/testdrive/sinks.td
Touches #2806
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3246)
> dataflow: fuel tank for sinks

- src/expr/src/scalar/mod.rs
@umanwizard The underlying issue in #3299 is that:
- Coalesce needs > 0 arguments
- If the only argument was null, we were removing it
This PR fixes that by not removing any arguments if all arguments are null.
Closes #3299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3304)
> sql: support COALESCE(null)

- doc/user/content/release-notes.md
- src/expr/src/scalar/func.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3310)
> sql: add overflow errors for length functions + release notes

- src/expr/src/scalar/mod.rs
improving comments as requested in #3304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3309)
> sql: improve comments on reudce implementation for coalesce

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3307)
> version bump: v0.3.2-dev

- src/dataflow/src/sink/kafka.rs
Touches #2860
This change is meant to be functionality preserving, just a refactor so that we don't spawn a new thread that we can't really interact with. Instead, lets not destroy the sink operator until we know that the kafka send queue is empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3315)
> dataflow: avoid spawning new thread when we drop sinks

- Cargo.lock
- src/aws-util/Cargo.toml
- src/coord/Cargo.toml
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/sql/Cargo.toml
- src/testdrive/Cargo.toml
- test/performance/perf-kinesis/Cargo.toml
Closes #3290.
Closes #3291.
Closes #3297.
Closes #3298.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3316)
> deps: bump rusoto ecosystem to v0.44.0

- src/coord/src/coord.rs
- src/materialized/src/lib.rs
Booting the coordinator can involve sending enough data to the workers
that the `comm` channel buffer fills up, stalling startup permanently.
The fix is easy: start the workers before the coordinator, so they can
drain the commands from the buffer as the coordinator puts them in.
Fix #3280.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3284)
> materialized: start dataflow workers before coordinator

- misc/python/materialize/cli/mzconduct.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3320)
> Fix ChaosDockerWorkflowStep string

- src/dataflow/src/server.rs
- src/dataflow/src/server/metrics.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3328)
> Add prometheus metrics for rate of command processing

- src/sql/src/plan/cast.rs
- src/sql/src/plan/query.rs
Refactors `plan_homogeneous_exprs` to use all our new type info.
- Replaces the old style of planning exprs with the new style of using `CoercibleScalarExpr`.
- Replaces `best_target_type` with `cast::determine_best_common_type`, which brings `best_target_type` into `cast` and verifies that its suggestion works before returning them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3330)
> Tidy up `plan_homogenous_exprs`

- Cargo.lock
- src/pgrepr/Cargo.toml
- src/pgrepr/src/format.rs
- src/pgrepr/src/types.rs
- src/pgrepr/src/value.rs
- src/pgrepr/src/value/interval.rs
- src/pgrepr/src/value/jsonb.rs
- src/pgrepr/src/value/numeric.rs
- src/pgwire/src/codec.rs
Just a bit of housekeeping to prepare for record types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3345)
> pgrepr: tidy up

- src/sql/src/plan/func.rs
@sploiselle consider this just a proposal! Wasn't sure if the fact that repeating parameters couldn't use `params!` was by design or just an emergent property.
Allow specifying repeating parameters with a natural variadic syntax
`(a, b, c)...`.
Also tweak the macro_rules! calls to use the more conventional braced
syntax, rather than parentheses. By convention, macros that expand to
statements use braces, while macros that expand to expressions use
paramentheses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3350)
> sql: minorly improve ergonomics of params! macro

- src/dataflow/src/sink/kafka.rs
Closes #2956
This should hopefully make debugging sinks easier and help us measure sink performance over time better
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3336)
> dataflow: add grafana metrics for sinks

- src/expr/src/scalar/func.rs
- test/sqllogictest/arithmetic.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3354)
> Use checked_mul for multiplying integers

- src/dataflow/src/source/kafka.rs
In order to support transactions, we have to call consumer.positions() in `downgrade_capabality`. Unfortunately, this call is expensive as it 1) makes allocations 2) acquires locks. It caused a substantial performance downgrade in our Kafka ingestion.
This PR batches downgrade_capability calls to once per invocation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3349)
> Addresses Kafka performance regression testing

- doc/user/content/sql/tail.md
@rjnn Here's a quick POC for the `TAIL` request you had. Pretty straightforward in that it actually just mocks out `COPY TO` semantics. I imagine this is a lot of the info folks actually need. We could turn this into a larger guide, but it feels like 90% of the meaningful content is just parsing the diff envelope.
@benesch I heard you like Python, so maybe you have a better sense of how to make this code run more smoothly? e.g. if you run it without receiving any data, it never returns control of your terminal window.
Makes progress on #2919, MaterializeInc/marshallwace#30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3373)
> docs: describe using TAIL with a driver

- src/sql/src/plan/cast.rs
- test/sqllogictest/type-promotion.slt
Closes #2232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3386)
> Valid type cast, promotion tests

- doc/user/assets/sass/_content.scss
- doc/user/content/_index.md
- doc/user/content/get-started.md
- doc/user/content/install.md
- doc/user/layouts/shortcodes/cta.html
- doc/user/layouts/shortcodes/promo.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3389)
> docs: marketingize the install page

- test/sqllogictest/tpch.slt
Some issues in our TPCH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3394)
> TPCH query errors

- doc/user/content/monitoring/_index.md
Explain how to setup Datadog monitoring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3374)
> Add Datadog monitoring configuration

- doc/user/content/known-limitations.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3415)
> update known limitations for 0.3.0 release

- demo/billing/resources/views/billing_batches.sql.in
- demo/billing/resources/views/billing_records.sql.in
- demo/billing/src/config.rs
- demo/billing/src/main.rs
- demo/billing/src/mz_client.rs
- demo/billing/src/randomizer.rs
* Proper type casts for timestamps
* Print out start time and seed values to make reproducing a billing demo run easier
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3411)
> Billing demo improvements

- src/dataflow/src/render/mod.rs
- src/dataflow/src/sink/kafka.rs
- src/dataflow/src/sink/util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3353)
> dataflow: add a shutdown button for kafka sinks

- test/chaos/connector/Dockerfile
- test/chaos/connector/docker-entrypoint.sh
- test/chaos/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3420)
> Test out updating connector for chaos testing

- doc/developer/develop.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3425)
> Update cargo run command in docs

- doc/user/content/release-notes.md
- doc/user/content/sql/create-index.md
- doc/user/content/sql/create-materialized-view.md
- doc/user/layouts/partials/sql-grammar/create-index.svg
- doc/user/layouts/partials/sql-grammar/create-source-avro-file.svg
- doc/user/layouts/partials/sql-grammar/create-source-avro-kafka.svg
- doc/user/layouts/partials/sql-grammar/create-source-csv-file.svg
- doc/user/layouts/partials/sql-grammar/create-source-csv-kafka.svg
- doc/user/layouts/partials/sql-grammar/create-source-csv-kinesis.svg
- doc/user/layouts/partials/sql-grammar/create-source-json-kafka.svg
- doc/user/layouts/partials/sql-grammar/create-source-json-kinesis.svg
- doc/user/layouts/partials/sql-grammar/create-source-protobuf-kafka.svg
- doc/user/layouts/partials/sql-grammar/create-source-protobuf-kinesis.svg
- doc/user/layouts/partials/sql-grammar/create-source-text-kafka.svg
- doc/user/layouts/partials/sql-grammar/create-source-text-kinesis.svg
- doc/user/layouts/partials/sql-grammar/create-source-text.svg
- doc/user/layouts/partials/sql-grammar/create-source.svg
- doc/user/layouts/shortcodes/create-source/syntax-details.html
- doc/user/sql-grammar/sql-grammar.bnf
Closes #2335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3431)
> Default index + materialized source docs

- misc/python/materialize/cli/mzconduct.py
- test/chaos/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3443)
> Add wait param to chaos-confirm step

- LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3446)
> update expected v0.3.2 release date

- src/dataflow/src/sink/kafka.rs
Closes #1539
I think the biggest open question for me is -- is it worth it to have both a shutdown button and a arc<atomicbool>?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3419)
> dataflow: shut down sinks after irrecoverable errors

- misc/dist/deb-scripts/postinst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3450)
> Properly suppress systemctl output in .deb postinstall script

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/normalize.rs
- src/sql/src/plan/statement.rs
- test/testdrive/sinks.td
This PR contains the changes to accept a new, optional `AS OF` parameter to a `CREATE SINK` statement, but leaves it otherwise unimplemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3459)
> Add unimplemented AS OF to CREATE SINK

- test/chaos/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3454)
> Chaos README

- doc/user/content/install.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3462)
> mention how to get the latest developer builds

- doc/user/content/third-party/debezium.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3463)
> explain how to use Materialize without Kafka

- doc/user/content/sql/show-create-index.md
- doc/user/layouts/partials/sql-grammar/show-create-index.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/show
- src/sql/src/plan/statement.rs
- test/testdrive/indexes.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3464)
> sql: add SHOW CREATE INDEX

- Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3470)
> deps: upgrade to sasl2-sys v0.1.10

- demo/billing/mzcompose.yml
And also make a non-cloud load-test straightforward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3489)
> billing-demo: Correctly inherit MZ_THREADS

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3487)
> Add CREATE SINK updates to release notes

- src/peeker/src/main.rs
- src/pgwire/src/protocol.rs
Part of #3485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3494)
> Remove expose_decumulated from histograms

- bin/dashboard-clean
- misc/monitoring/dashboard/README.md
- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
- misc/python/materialize/cli/dashboard_clean.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3492)
> Add a script and docs for updating dashboard from grafana.mz

- Cargo.lock
Resolves #3485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3497)
> Update rust-prometheus to latest upstream

- src/expr/src/scalar/func.rs
- test/sqllogictest/bytea.slt
- test/testdrive/bytes.td
Also fix a nullability bug this exposed.
Fix #2281.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3499)
> test: add SLTs for convert_from

- src/materialized/tests/sql.rs
- test/testdrive/sinks.td
Addresses the testing concerns of this issue: (https://github.com/MaterializeInc/materialize/issues/3468).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3500)
> Test TAILs on sources with empty frontiers

- src/dataflow/src/arrangement/manager.rs
- src/dataflow/src/server.rs
Records time spent in maintenance per worker, per arrangement. 
How do I update the dashboard to show these metrics? Alternatively, we can hold off on updating the dashboard until we test how useful this is?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3498)
> Add metrics to measure time spent in maintenance.

- src/sqllogictest/src/runner.rs
This is just reorganization to eliminate the number of special cases and
make it easier to see how a given (datum, type) pair will be formatted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3503)
> sqllogictest: clean up formatting code

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3506)
> Update 0.3.1 release status

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3507)
> Correct 0.3.1 title so it's in-line with the rest

- Cargo.lock
- LICENSE
- doc/user/config.toml
- doc/user/content/release-notes.md
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3508)
> Add v0.3.1 to website and update in-progress version to 0.4.0

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3509)
> fix WITH SNAPSHOT urls

- Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3511)
> update sasl2, to fix the build on freebsd

- src/repr/src/scalar.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/jsonb.slt
Fix #2414.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3515)
> sql: support to_jsonb(record)

- src/materialized/src/lib.rs
The default name exceeds Linux's 15 character limit on thread names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3531)
> materialized: improve tokio thread name

- doc/user/content/get-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3537)
> Add link to Katacoda, fix incomplete sentence

- demo/chbench/grafana/conf/load-test.json
- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/mod.rs
- src/materialized/src/http.rs
This PR changes prometheus metrics to not be specific to Kafka.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3539)
> Prometheus fixes post unified source ingestion framework

- doc/user/content/get-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3549)
> test different demo CTA copy

- doc/user/content/install.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3552)
> Document the docker "install" method

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3564)
> docs: release note for cross-schema db drop bug fix

- Cargo.lock
- test/smith/Cargo.toml
- test/smith/ci/Dockerfile
- test/smith/src/main.rs
- test/smith/src/mz_client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3560)
> Changes to test/smith to reflect changes to upstream API

- src/avro/src/reader.rs
- src/avro/tests/io.rs
Decimals are a "logical" type that is actually either Fixed or Bytes under the hood. Allow them to be resolved as each other during schema resolution.
TODO: Also do the same for the other logical types (UUID, date, etc.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3572)
> Resolve decimals against bytes/fixed

- src/avro/src/schema.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3574)
> fix some wrong comments

- src/avro/src/decode.rs
In the first case, when we read an incorrect index, we crash. Return an error instead.
In the second case, we _tried_ to do a bounds check, but there is an off-by-one error (`<=` instead of `<`), so fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3581)
> Fix two unchecked array accesses in decode

- src/avro/src/schema.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3582)
> fix a wrong comment

- src/avro/src/decode.rs
- src/avro/src/reader.rs
- src/avro/src/schema.rs
- src/avro/tests/io.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3585)
> Allow default values in Avro enums

- src/avro/src/decode.rs
- src/avro/src/reader.rs
- src/avro/src/schema.rs
- src/avro/tests/io.rs
In the case of resolved unions some of whose branches failed to match or resolve: Carry around the actual error message, instead of just `None`. In the case of resolved enums where some of the writer variants are missing in the reader, carry around the name of the missing symbol.
This will let us print an actually useful error message in the case when decoding a row fails for one of these reasons.
In the union case it would arguably make more sense to hold on to `failure::Error` instead of `String`, but `failure::Error` doesn't implement `Clone`, and schemas need to be clonable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3587)
> Improve error messages when decoding missing avro enum or union variants

- ci/deploy/devsite.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3588)
> devsite: use an explicit branch for updating the repo

- ci/deploy/pipeline.yml
- ci/test/build.py
- ci/test/mkpipeline.py
- ci/test/pipeline.template.yml
- ci/www/changed.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3589)
> simplify test configs by getting rid of support for master branch

- src/avro/src/reader.rs
- src/avro/src/schema.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3591)
> rename some more "resolve_" functions in UnionSchema to "match_"

- src/avro/src/schema.rs
For example, the union type `["null", {"type": "decimal", "precision": 19, "scale": 5 } ]` should be able to resolve against `["null", "bytes"]`.
The corresponding types can already be resolved, outside of unions.
This wasn't working before because of the way unions work: there is supposed to be at most one of each non-named type in a union, which is then used to try resolution against the corresponding non-named type in the other union.
But we were storing these by _logical_ type in unions (DateTime, Date, Decimal), instead of actual underlying type, so if e.g. the writer had "Decimal" and the reader had "Bytes", we wouldn't even try to resolve them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Allow logical types in unions to resolve against raw types.

- src/avro/src/schema.rs
If `SchemaPiece::Decimal::fixed_size` is Some, then the decimal is actually a named type, and a logical typedef on top of "fixed" (instead of "bytes"). Handle this case when serializing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3607)
> Properly serialize decimal fixed types

- src/avro/src/schema.rs
- src/avro/tests/schema.rs
More avro tests (with more to come!). Submitting a PR at this point because I found a bug with `parse_fixed`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3610)
> Add Avro tests, fix decimal logical type panic

- src/avro/src/decode.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3614)
> fix off-by-one error

- README.md
Fix #3620.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3621)
> README: fix link to Rust API docs

- src/coord/src/session/session.rs
- src/sql-parser/src/parser.rs
- test/testdrive/session.td
Just pretend to be serializable for now, since we don't actually support
transactions.
Fixes #3593.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3619)
> coord,sql-parser: support SHOW TRANSACTION ISOLATION LEVEL

- src/coord/src/coord.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3501)
> Remove errant commented line

- src/avro/src/decode.rs
- src/avro/tests/io.rs
- src/interchange/src/avro.rs
Forgot to add as part of #3568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3626)
> remove stray todos

- ci/nightly/pipeline.yml
- test/smith/mzcompose.yml
- test/smith/src/main.rs
Closes #1722
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3609)
> ci/nightly: Add nightly tests for smith fuzzer

- src/avro/tests/schema.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3631)
> Add tests for more Avro logical types

- doc/user/content/cli/_index.md
- doc/user/content/get-started.md
- src/coord/src/catalog.rs
- src/coord/src/catalog/error.rs
- src/coord/src/catalog/storage.rs
- src/coord/src/coord.rs
- src/materialized/src/bin/materialized.rs
- src/materialized/src/lib.rs
- src/materialized/tests/pgwire.rs
- src/materialized/tests/server.rs
- src/materialized/tests/util.rs
- src/sql/src/catalog.rs
- src/sql/src/plan/statement.rs
- src/sqllogictest/src/runner.rs
Adds the toggle for `experimental_mode`, which doesn't do anything meaningful yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3634)
> catalog: add experimental mode

- src/avro/src/lib.rs
- src/avro/src/reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3653)
> a few doc fixes

- src/expr/src/scalar/func.rs
- test/sqllogictest/funcs.slt
Closes #3651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3656)
> expr: fix underflow in date_trunc week

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3674)
> Update release issue template with preparation steps

- src/expr/src/scalar/func.rs
- src/expr/src/scalar/mod.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/funcs.slt
@ruchirK as part of the stability push I'm trying to make sure we don't introduce any new panics. I know you're busy with the CDC docs so didn't want to interrupt you on that!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3676)
> expr: don't panic if date_trunc('week', ...) is out of range

- src/avro/src/schema.rs
- src/avro/tests/schema.rs
Adds tests from [here](https://github.com/apache/avro/tree/master/lang/c/tests/schema_tests) that were not present in the Python tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3678)
> Add C lang Avro schema tests

- Cargo.lock
- src/dataflow-types/Cargo.toml
- src/dataflow-types/src/types.rs
- test/testdrive/avro-registry.td
- test/testdrive/avro-sources.td
Fixes #3677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3679)
> Gracefully handle key schemas that are not subsets of value schemas

- doc/user/content/release-notes.md
- doc/user/content/sql/alter-rename.md
- doc/user/layouts/partials/sql-grammar/alter-rename.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3681)
> docs: document ALTER ... RENAME

- .github/ISSUE_TEMPLATE/release.md
- bin/mkrelease
- misc/python/materialize/cli/mkrelease.py
- misc/python/materialize/git.py
Part of #3018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3693)
> Add a mkrelease script

- doc/user/content/overview/api-components.md
- doc/user/content/release-notes.md
- doc/user/content/sql/create-sink.md
Closes #3541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3673)
> docs: Document kafka sink cdc output

- doc/user/content/sql/create-sink.md
not sure if the grammar is clear
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3698)
> Add AS OF examples

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3695)
> Prepare next phase of development: v0.4.1-dev

- doc/user/content/release-notes.md
- src/expr/src/scalar/func.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/cast.slt
closes #3700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3704)
> sql: make casting to int consistent with pg

- Cargo.lock
- Cargo.toml
- ci/test/pipeline.template.yml
- demo/billing/src/main.rs
- test/chaos/src/main.rs
- test/performance/perf-upsert/Cargo.toml
- test/performance/perf-upsert/ci/.gitignore
- test/performance/perf-upsert/ci/Dockerfile
- test/performance/perf-upsert/ci/mzbuild.yml
- test/performance/perf-upsert/mzcompose
- test/performance/perf-upsert/mzcompose.yml
- test/performance/perf-upsert/src/config.rs
- test/performance/perf-upsert/src/main.rs
- test/performance/perf-upsert/src/mz_client.rs
- test/test-util/src/kafka/kafka_client.rs
Closes #3699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3701)
> test: add new upsert performance test

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3706)
> Add a current status banner to the release issue template

- ci/deploy/linux.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3716)
> Fix semver check for deploys

- doc/user/content/monitoring/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3717)
> local -> localhost

- ci/plugins/mzconduct/hooks/command
- test/performance/perf-upsert/src/main.rs
Touches #3719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3722)
> ci: properly invoke mzcompose to exfiltrate logs

- src/transform/src/nonnull_requirements.rs
Our non-null requirements logic did not ensure that it chased references to columns generated in the same operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3730)
> Propagate all non-null requirements in map

- Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3733)
> Bump our rust-prometheus to get thread-level cpu usage

- Cargo.lock
- src/avro/Cargo.toml
- src/avro/src/schema.rs
- src/aws-util/Cargo.toml
- src/coord/Cargo.toml
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/interchange/Cargo.toml
- src/sql/Cargo.toml
- src/sqllogictest/Cargo.toml
- src/sqllogictest/src/runner.rs
- src/testdrive/Cargo.toml
- src/testdrive/src/action/sql.rs
- test/chaos/Cargo.toml
- test/chaos/src/main.rs
- test/performance/perf-kinesis/Cargo.toml
We'll need to wait for ~postgres-protocol and~ rusoto to bump in order to avoid duplicate dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3372)
> deps: bump to latest versions of crypto crates

- .github/ISSUE_TEMPLATE/release.md
- misc/python/materialize/cli/mkrelease.py
This matches load-test steps that you have to actually take (all the load tests spin up
at the same time.
It also uses mkrelease for the last step, which simplifies everything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3731)
> Simplify description of release process

- Cargo.lock
- test/performance/perf-upsert/mzcompose.yml
- test/test-util/Cargo.toml
- test/test-util/src/kafka/kafka_client.rs
Touches #3719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3737)
> test: stop automatically creating topics for the perf-upsert test

- doc/user/config.toml
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3760)
> Update docs to reflect that 0.4.0 is released

- bin/lint
- demo/kafka-transactions/pom.xml
- misc/lint/copyright.awk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3764)
> lint: clean up copyright detection rules

- test/sqllogictest/topk.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3765)
> test: add plan + test for idiomatic top-k-in-group query

- src/transform/src/join_elision.rs
Key equivalence classes no longer need to be updated, I think as a
result of the switch to using ScalarExprs for equivalences, so this code
can get a lot simpler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3767)
> transform: simplify join elision

- src/interchange/src/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3772)
> Avoid cloning the MySQL binlog filename on every row

- .github/ISSUE_TEMPLATE/release.md
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3769)
> Verify that release notes match Release Announcement

- src/interchange/src/avro.rs
- test/testdrive/avro-sources.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3771)
> Support deduplicating based on Postgres LSN

- Cargo.lock
- Cargo.toml
- src/kafka-util/Cargo.toml
- src/kafka-util/src/bin/kgen.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3775)
> Add `kgen` utility to dump random data into Kafka

- src/interchange/src/avro.rs
- test/testdrive/avro-sources.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3780)
> Look through union for LSN

- test/performance/perf-upsert/ci/Dockerfile
- test/performance/perf-upsert/mzcompose.yml
Closes #3708
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3781)
> test/perf-upsert: misc cleanups

- doc/user/content/monitoring/_index.md
Fixes #3755. Note that I don't plan on merging this PR until we (@umanwizard ?) gets a better handle on  #1344 (identifying why some performance paths degrade when using swap).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3761)
> Recommend swap file to deal with OOMs

- demo/billing/mzcompose.yml
- demo/billing/src/config.rs
- demo/billing/src/main.rs
- demo/billing/src/mz.rs
Closes #3776
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3784)
> demo/billing: saner handling of csv file name args

- src/kafka-util/src/bin/kgen.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3788)
> kgen: allow generating messages with random keys

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3801)
> Update release instructions to start checking relnotes earlier

- doc/user/content/get-started.md
- doc/user/content/overview/what-is-materialize.md
We were quite consistent with this rule, with just two exceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3805)
> doc/user: use Title Case for all page titles

- doc/user/content/.gitattributes
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3796)
> doc/user: 0.4.1 release notes draft

- doc/user/content/release-notes.md
- src/avro/src/codec.rs
- src/coord/Cargo.toml
- src/dataflow/Cargo.toml
- src/interchange/Cargo.toml
- src/sql/Cargo.toml
- src/testdrive/Cargo.toml
- test/testdrive/avro-ocf.td
Closes #3811 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3815)
> Allow snappy-encoded OCF files

- doc/user/content/release-notes.md
- doc/user/content/sql/types/boolean.md
- src/expr/src/scalar/func.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/boolean.slt
- test/sqllogictest/type-promotion.slt
Fix #3812.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3814)
> sql: support casting bool to int4

- doc/user/content/sql/create-materialized-view.md
note that i haven't tested that the SQL still works
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3837)
> Replace VIEW with MATERIALIZED VIEW

- src/expr/src/relation/mod.rs
Replaces #3839.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3840)
> Break negate keys

- demo/billing/mzcompose.yml
- demo/billing/src/config.rs
- demo/billing/src/main.rs
- test/chaos/src/main.rs
- test/test-util/src/kafka/kafka_client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3779)
> faster load gen in billing demo + better ux

- bin/ci-builder
- ci/slt/upload.sh
We need to pass through the "BUILDKITE_BUILD_ID" environment variable
too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3847)
> ci: fix slt upload

- src/materialized/src/http.rs
- src/prof/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3848)
> Fix name of global; fix two comments

- bin/lint
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3850)
> lint: exclude ico from copyright/trailing-newline checks

- src/dataflow-types/src/types.rs
- src/dataflow/src/render/mod.rs
- src/transform/src/dataflow.rs
Just some tiny cleanups I spotted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3851)
> Linear operator helpers

- doc/user/content/release-notes.md
- doc/user/content/sql/idioms.md
- doc/user/content/sql/join.md
- doc/user/content/sql/namespaces.md
- doc/user/layouts/partials/sql-grammar/join-expr.svg
- doc/user/layouts/partials/sql-grammar/join-type.svg
- doc/user/layouts/partials/sql-grammar/table-ref.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3849)
> doc/user: document LATERAL joins

- README.md
we'll also have to leave a final adios message in the gitter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3862)
> switch gitter chat to slack chat

- doc/user/content/sql/create-table.md
- doc/user/content/sql/insert.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3865)
> Add warning that INSERT/CREATE TABLE are ephemeral

- src/materialized/src/http/prof.rs
- src/materialized/src/http/templates/base.html
- src/materialized/src/http/templates/flamegraph.html
Also fix a few visual glitches in the UI rendering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3874)
> materialized: remove bootstrap from flamegraph template

- Cargo.lock
- src/dataflow/src/source/file.rs
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/kinesis.rs
- src/dataflow/src/source/mod.rs
Builds on #3866, but would require a potentially scary change to timely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3870)
> dataflow: try even harder not to wrap the SyncActivator in a mutex

- doc/user/content/ops/deployment.md
Fixes #3669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3890)
> Point out that swap isn't automatically created

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan/statement.rs
- test/testdrive/tables.td
Addresses https://github.com/MaterializeInc/materialize/issues/3876
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3891)
> Implement SHOW CREATE TABLE

- doc/user/content/ops/deployment.md
fixes #3669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3892)
> Instructions on swap setup for Linux and Docker

- src/sql/src/plan/statement.rs
- test/testdrive/tables.td
Fixes https://github.com/MaterializeInc/materialize/issues/3903
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3910)
> Don't support INSERT statements that specify columns

- src/prof_common/src/lib.rs
- src/prof_common/src/time.rs
- src/prof_jemalloc/src/lib.rs
This should hopefully be explained by the comments in prof_jemalloc/src/lib.rs , which I will copy into the commit message when landing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3915)
> Unbias jemalloc samples

- src/materialized/src/http/prof.rs
- src/materialized/src/http/templates/flamegraph.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3916)
> Use size in bytes for heap flamegraph tooltips

- src/materialized/src/http/prof.rs
will land without review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3925)
> Fix comment

- doc/user/content/sql/insert.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3927)
> fix warning closing tag

- doc/user/content/sql/show-create-table.md
- doc/user/content/sql/show-sources.md
- doc/user/content/sql/show-tables.md
- doc/user/layouts/partials/sql-grammar/show-create-table.svg
- doc/user/layouts/partials/sql-grammar/show-tables.svg
- doc/user/sql-grammar/sql-grammar.bnf
Fixes https://github.com/MaterializeInc/materialize/issues/3923
New grammars:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3928)
> Add documentation for SHOW TABLES and SHOW CREATE TABLE

- test/chaos/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3934)
> Chaos test message-count 10_000 -> 1_000_000

- doc/user/data/sql_funcs.yml
Fixes: https://github.com/MaterializeInc/materialize/issues/3893
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3937)
> Add docs for split_part

- src/sql/src/plan/query.rs
- src/sql/src/plan/statement.rs
- test/testdrive/mzcompose.yml
Tables are a bit buggy at the moment, due to some longstanding
coordinator bugs. Mark them as experimental to unblock the forthcoming
v0.4.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3947)
> sql: experimentalize tables

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3949)
> .github: copyedit release issue template

- src/peeker/src/args.rs
- src/peeker/src/main.rs
See the individual commits for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3953)
> Add some conveniences for debugging workflows that depend on peeker

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3956)
> Prepare next phase of development: v0.5.0-dev

- demo/billing/src/main.rs
- test/performance/perf-upsert/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3958)
> demo,test: Rework tests to respect the message-count parameter

- src/coord/src/coord.rs
Follow up from #3963.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3972)
> coord: add commentary about logging index special case

- Cargo.lock
- demo/billing/Cargo.toml
- deny.toml
- src/interchange/Cargo.toml
- src/protoc/Cargo.toml
- src/testdrive/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3974)
> deps: upgrade to protobuf 2.17 ecosystem

- doc/user/content/release-notes.md
- src/coord/src/sink_connector.rs
- src/coord/src/timestamp.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/sink/kafka.rs
- src/dataflow/src/source/kafka.rs
- src/kafka-util/src/addr.rs
- src/kafka-util/src/lib.rs
- src/sql/src/plan/statement.rs
- test/kafka-ssl/mzcompose.yml
- test/kafka-ssl/smoketest.td
- test/test-certs/create-certs.sh
This regressed in #3797. Add an integration test for connecting to
multiple Kafka brokers to ensure this doesn't regress in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3986)
> kafka-util: support multiple Kafka broker addresses

- doc/user/config.toml
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3988)
> doc/user: mark v0.4.1 as published

- doc/user/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3989)
> doc/user: correct release version

- src/coord/src/coord.rs
Follow up from #3982.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3990)
> coord: fix typo in comment

- src/coord/src/coord.rs
- src/dataflow/src/server.rs
- test/testdrive/tables.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/3955)
> Musing: try using wall clock time

- doc/developer/guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4022)
> doc/dev: note that symbiosis mode is on the way out

- misc/monitoring/dashboard/conf/prometheus-sql-exporter/mz/arrangement.collector.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4036)
> Add mz_records_per_dataflow_global metric to prometheus

- src/coord/src/persistence.rs
- src/materialized/src/bin/materialized.rs
Also change the number of parameters to just one that's hopefully much easier to
understand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4034)
> coord: change the way persister decides when to write

- demo/chbench/mzcompose.yml
@quodlibetor I'm trying to control which port gets exposed for MZ and Kafka; it seems to me like this works, but not sure if there are further-reaching implications that I should be aware of.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4045)
> demo/chbench: set exposed ports manually

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4046)
> demo/chbench: lengthen timeouts for cloud benchmarks

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4048)
> demo/chbench: make schema registry port deterministically accessible

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4066)
> demo/chbench: propagate Kafka + SR ambient env vars into image

- misc/python/materialize/cli/mzconduct.py
Before this only the error messages ever got pushed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4067)
> mzconduct: add success messages after retries

- src/peeker/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4068)
> demo/chbench: fix typo in config

- misc/python/materialize/cli/mzconduct.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4072)
> mzconduct: handle null port entries

- demo/chbench/mzcompose.yml
- src/peeker/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4075)
> demo/chbench: create second, publicly accessible kafka listener

- src/coord/src/catalog.rs
- src/coord/src/coord.rs
(In the first commit message I meant OpStatus::DroppedDatabase, not Action::DropDatabase)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4080)
> Tidy up recent mz_* system table work

- doc/user/content/sql/create-source/csv-kafka.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4081)
> docs: fix CSV kafka code sample

- demo/chbench/mzcompose.yml
- src/peeker/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4082)
> demo/chbench: move peeker to infra machine

- doc/user/layouts/partials/create-source/format/csv/details.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4083)
> docs: explain how to get typed data from CSV source

- doc/user/content/sql/create-source/json-kafka.md
Closes #4027.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4099)
> doc: remove kinesis alpha warning on kafka page

- src/sql/src/plan/statement.rs
Generates a sql_parser::ast::Expr from a ShowStatementFilter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4102)
> Create filter_expr function

- src/sql/src/plan/statement.rs
- test/testdrive/show.td
Fixes https://github.com/MaterializeInc/materialize/issues/4084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4101)
> Order SHOW COLUMNS output in source order

- doc/developer/sqllogictest.md
- test/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4109)
> doc: fix testing testing guide links

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4111)
> Prepare v0.4.3 dev

- src/coord/src/catalog/builtin.rs
- src/coord/src/coord.rs
Part of: #4086 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4114)
> Int64 schema_id

- doc/user/content/release-notes.md
fixes #4113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4115)
> add relnotes for 0.4.2

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4112)
> Update release checklist for new release blocker label

- demo/chbench/mzcompose.yml
Adding environment logging for benchmark workflows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4126)
> demo/chbench: add environment logging for benchmark workflows

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4128)
> demo/chbench: assert default number of threads through env var

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4121)
> Update testing instructions in release process

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4133)
> demo/chbench: propagate NUM_WAREHOUSES to cloud-benchmark-infra

- Cargo.lock
- src/kafka-util/Cargo.toml
- src/kafka-util/src/bin/kgen.rs
WIP as not all schema nodes are implemented, but should be OK to land since this is not going into the production binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4136)
> Random avro data in kgen

- src/dataflow/src/decode/avro.rs
- src/dataflow/src/decode/mod.rs
- src/dataflow/src/decode/protobuf.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4137)
> Fix messages decoded metric for upsert sources

- doc/user/content/sql/functions/length.md
- doc/user/data/sql_funcs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4138)
> docs: correct descriptions of string length function

- src/avro-derive/src/lib.rs
- src/avro/src/decode.rs
- src/avro/src/lib.rs
- src/interchange/src/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4148)
> Allow deriving avro decoders that require state.

- doc/user/content/overview/what-is-materialize.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4149)
> docs: remove extra word

- doc/user/config.toml
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4152)
> v0.4.2 has been released!

- src/interchange/src/avro.rs
Fixes merge skew present in build: https://buildkite.com/materialize/tests/builds/10722#01cf55db-d0f7-4a70-ae25-bc07c147461e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4154)
> Add UUID type to build_row_schema_json match

- test/performance/perf-upsert/src/config.rs
- test/performance/perf-upsert/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4156)
> test/perf-upsert: run lots of select count(*)s on mz

- src/sqllogictest/src/runner.rs
Since I added the `mz_catalog.mz_columns` system table in #4085, the sqllogictest runner
has been hanging locally. Adding the mz_columns table meant that we were broadcasting
a new insert for every builtin column in a Materialize instance.
Because the sqllogictest runner tried to instantiate a Coordinator before it
launched its dataflow workers, the Coordinator was sending tons of messages into the
comm channel without anything to read them back out. This issue was fixed for actual
Materialize instances with #3284 by simply launching the dataflow workers first. However,
this fix was not applied to the sqllogictest runner at that time.
This PR updates the sqllogictest runner to launch its dataflow workers before it attempts
to instantiate the Coordinator, mirroring the fix in #3284.
--- …
> Fix hanging sqllogictest runner

- src/prof/src/jemalloc.rs
Export `malloc_conf` as a `&[u8]` rather than a `Option<&c_char>`. This
seems a good bit less magical.
Based on my read of the Rust reference's "Type Layout" chapter, pointers
and references have the same layout, and obviously a u8/i8s have the
same layout, so a symbol of type `&[u8]` should be exactly equivalent to
a symbol of type `*c_char`. The use of an option type in the old
approach actually strikes me as kind of sketchy; not sure what the
representational guarantees of `Option` are.
I've manually verified that this new approach works on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4168)
> prof: simplify installation of malloc_conf

- src/coord/src/catalog.rs
- src/coord/src/catalog/builtin.rs
- src/coord/src/coord.rs
- src/sql/src/plan/statement.rs
- test/testdrive/catalog.td
Fixes: https://github.com/MaterializeInc/materialize/issues/4086
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4173)
> Database id should be an i64 in builtin tables

- src/coord/src/coord.rs
Now they match the original `report_catalog_update` function (and are easier to read).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4175)
> Rename catalog update functions

- doc/developer/guide-testing.md
- doc/developer/mzbuild.md
- misc/python/materialize/mzbuild.py
- test/testdrive/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4119)
> testing: improvements

- doc/user/content/sql/create-source/json-kafka.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4184)
> fix missing 'FROM' in docs

- Cargo.lock
- src/avro/Cargo.toml
- src/avro/src/decode.rs
- src/avro/src/encode.rs
- src/avro/src/schema.rs
- src/avro/src/types.rs
- src/interchange/Cargo.toml
- src/interchange/src/avro.rs
- src/kafka-util/src/bin/kgen.rs
- src/testdrive/src/format/avro.rs
- test/testdrive/uuid.td
Fixes #3577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4166)
> avro: add UUID support

- src/coord/src/catalog.rs
- src/sql/src/plan/statement.rs
- test/testdrive/catalog.td
Fixes #4187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4188)
> SHOW DATABASES should work even if current database has been dropped

- demo/chbench/mzcompose.yml
- src/peeker/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4208)
> peeker: add benchmark query group + thread lever

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
Versioning updates for 0.4.3-rc1 and 0.4.4-dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4214)
> Prepare v0.4.4 dev

- src/dataflow-types/src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4217)
> fix minor typo

- src/peeker/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4220)
> peeker: add olap_thread env var to loadtest group

- src/materialized/tests/pgwire.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4221)
> pgwire: address comments from previous pgtest PR

- src/dataflow/src/render/context.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4222)
> Remove unnecessary annotation

- src/dataflow/src/render/mod.rs
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/mod.rs
- src/dataflow/src/source/persistence.rs
- src/sql/src/plan/statement.rs
Tried to break this out into commits that all individually make sense and make the review easier
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4209)
> Change how Materialize reads in persisted data

- src/materialized/tests/pgwire.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement.rs
- src/sql/src/plan/transform_ast.rs
- test/testdrive/tables.td
Fix #3941.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4227)
> sql: support prepared INSERT statements

- src/sql/src/plan/statement.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4235)
> sql: fix merge skew on boxing of SelectStatement::query

- src/dataflow/src/source/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4236)
> dataflow: lower log verbosity for unimplemented persistence function

- doc/user/content/cli/_index.md
- doc/user/content/ops/deployment.md
- doc/user/content/release-notes.md
- doc/user/content/sql/alter-index.md
- doc/user/content/sql/types/uuid.md
- doc/user/layouts/partials/sql-grammar/alter-index.svg
- doc/user/layouts/partials/sql-grammar/type-uuid.svg
- doc/user/sql-grammar/sql-grammar.bnf
@sploiselle @awang could you do your usual review of these? @benLogN you should sign off too as release manager. 
Unfortunately there were a few features that slipped through without docs, so I've added the docs here as well. Those will need additional review:
* @mjibson can you review the `uuid` docs?
* @ruchirK @frankmcsherry can you review the logical compaction docs?
🍻
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4232)
> doc: add release notes for 0.4.3

- doc/user/layouts/partials/sql-grammar/alter-rename.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/coord/src/coord.rs
- src/sql-parser/src/parser.rs
- src/sql/src/ast/transform.rs
- test/testdrive/rename.td
Fixes #4234 
The new railroad diagram will look like:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4239)
> Support ALTER TABLE .. RENAME

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4241)
> doc/user: linkify mz_cluster_id in release notes

- doc/user/content/sql/create-table.md
- doc/user/content/sql/insert.md
- src/sql/src/plan/statement.rs
- test/testdrive/mzcompose.yml
@JLDLaughlin is there anything else outstanding that should get fixed for tables? #3975 was the last outstanding issue that I knew of!
----
All known issues with tables have been fixed, so stabilize `CREATE
TABLE` and `INSERT`.
h/t to @JLDLaughlin for doing all of the heavy lifting for tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4246)
> sql: stabilize tables

- demo/chbench/mzcompose.yml
- test/chaos/mzcompose.yml
- test/tb/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4247)
> demo,test: upgrade to Debezium v1.2

- doc/user/content/cli/_index.md
- doc/user/content/ops/deployment.md
- doc/user/content/sql/create-source/avro-kafka.md
- doc/user/content/sql/create-source/csv-kafka.md
- doc/user/content/sql/create-source/json-kafka.md
- doc/user/content/sql/create-source/protobuf-kafka.md
- doc/user/content/sql/create-source/text-kafka.md
- doc/user/layouts/partials/create-source/connector/kafka/details.html
- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
- src/materialized/src/bin/materialized.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4224)
> docs: add documentation for source persistence

- src/coord/src/coord.rs
Fixes: https://github.com/MaterializeInc/materialize/issues/4248
@benesch - happy to change this if you have a nicer way to loop through twice!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4249)
> Insert catalog items into coordinator in two loops

- demo/billing/src/main.rs
- test/chaos/src/main.rs
- test/performance/perf-upsert/src/main.rs
- test/test-util/src/kafka/kafka_client.rs
MBTA demo might create more than one topic. Also, without null payload support, we can't test upsert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4251)
> test-util: have KafkaClient support multiple topics + null payload

- doc/user/content/demos/business-intelligence.md
Follow up from: https://github.com/MaterializeInc/materialize/issues/4223#issuecomment-696938020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4276)
> Add BI demo note for Mac users

- src/dataflow/src/source/kafka.rs
Closes #4174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4288)
> dataflow: more verbose error messages for Kafka sources

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4295)
> doc/user: add release notes for qualified function names

- src/coord/src/coord.rs
@ruchirK there's a ton of code movement here so the diff is unfortunately more complicated than you might hope—lmk if it'd be helpful to hop on a call to quickly walk through this verbally instead.
Refactor the coordinator's startup flow to avoid passing ownership via
`Option`s. This makes the startup flow much easier to follow.
As suggested by @ruchirK in #4287.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4294)
> coord: refactor startup flow

- Cargo.lock
- src/coord/src/persistence.rs
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/persistence.rs
- src/expr/src/relation/func.rs
- src/repr/Cargo.toml
- src/repr/src/lib.rs
- src/repr/src/persistence.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/table_func.slt
A little loose at the moment since I think it's a bit of a pain to
thread through the configured persistence directory, but should enable
some amount of testing. I tried to factor out the behaviour here as much
as I could but it was a bit of a pain. I'm a bit unsure about the
package boundaries in general here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4259)
> Add a table function to view persisted records

- Cargo.lock
- doc/developer/guide.md
- src/materialized/Cargo.toml
- src/materialized/src/http/root.rs
- src/materialized/src/http/static/css/flamegraph.css
- src/materialized/src/http/static/js/flamegraph.js
- src/materialized/src/http/templates/flamegraph.html
Add a development feature to allow hot-reloading static assets, like
CSS/JS files. This makes developing the web UI much more pleasant, as
changing CSS/JS no longer requires a recompile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4315)
> materialized: hot reload web static assets in development

- test/sqllogictest/transform/join_index.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4321)
> Fix merge skew from merging #4192. Id of `baz` has changed as a result of #4292.

- bin/pyactivate
- bin/pycheck
- ci/cleanup/pipeline.yml
- ci/deploy/pipeline.yml
- ci/test/mkpipeline.sh
- ci/test/pipeline.template.yml
- misc/python/requirements-ci.txt
- misc/python/requirements-dev.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4317)
> bin/pycheck: fix bugs + simplify

- src/interchange/src/avro.rs
"Confluent-style Avro" is a term we have invented that means a string of bytes formatted as follows:
1. The literal byte \0 
2. A four-byte big-endian schema ID pointing to the schema with which the Avro payload was encoded (stored separately in Schema Registry)
3. The Avro payload itself.
`interchange::avro::Decode` is doing way too many different, only tangentially related things. One of those is extracting an Avro payload from a Confluent-style Avro payload, and determining the schema to decode it with. We break that part out into its own piece of code, both to make the `Decode` struct slightly less complicated, and because we might want to reuse it in other places (for example: the CDCv2 decoder, which will be awkward to shoehorn into the already-spaghettiish …
> Break Confluent-style Avro parsing into its own chunk of code, separate from the main Avro decoder

- src/sql-parser/src/ast/defs/expr.rs
- src/sql-parser/src/ast/defs/value.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/error
- src/sql-parser/tests/testdata/literal
- src/sql-parser/tests/testdata/scalar
- src/sql/src/plan/query.rs
Split out from #1248. Important for PostgreSQL compatability work.
Touches #1248.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4323)
> sql-parser: learn to parse array literals and data types

- doc/user/assets/sass/_content.scss
- doc/user/content/release-notes.md
- doc/user/layouts/shortcodes/version-header.html
Just minor cleanups here; going to merge without review since @sploiselle is off for the day, but @sploiselle please take a look tomorrow and shout if anything seems wrong!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4336)
> doc/user: small fixups for release notes

- doc/developer/guide-changes.md
- doc/developer/guide.md
- doc/developer/style.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4244)
> doc/dev: add guide about submitting/reviewing PRs

- misc/python/materialize/cli/mkrelease.py
- misc/python/materialize/ui.py
----
spawned from this conversation: https://github.com/MaterializeInc/materialize/pull/4153#discussion_r497157033
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4337)
> mkrelease: Prompt to push the tag if we know how to

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4352)
> Prepare next phase of development: v0.4.5-dev

- doc/user/assets/sass/_content.scss
- doc/user/content/ops/monitoring.md
- doc/user/content/sql/system-tables.md
- doc/user/content/versions.md
- doc/user/layouts/shortcodes/version-list.html
Fix #3985.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4349)
> doc/user: add notes about versioning and backwards compatibility

- demo/billing/README.md
- demo/billing/src/config.rs
- demo/billing/src/main.rs
- demo/billing/src/mz.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4360)
> Add a lateral join query + persistence to the billing demo

- doc/user/content/ops/deployment.md
remove reference to "problems"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4379)
> adjust persistence copy

- src/transform/src/predicate_pushdown.rs
- test/sqllogictest/joins.slt
Resubmission of https://github.com/MaterializeInc/materialize/pull/4362 which is in some CLA sad state.
Fixes #4361.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4365)
> Clear predicates for bare `Get` expressions

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4363)
> release: Update checklist for clarity and new infrastructure

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4386)
> doc/user: add relnote for inter-view predicate pushdown bug (#4361)

- Cargo.lock
- src/transform/Cargo.toml
- src/transform/src/lib.rs
- src/transform/tests/test_runner.rs
- src/transform/tests/testdata/arrange
- src/transform/tests/testdata/constant
- src/transform/tests/testdata/join-implementation
- src/transform/tests/testdata/let-get
- src/transform/tests/testdata/scalar
- src/transform/tests/testdata/steps
- src/transform/tests/testdata/t
This is still in a pretty early stage but I am throwing it up here since
we recently had a case that was hard to test directly from SQL. Thoughts
welcome! The implementation could probably use some cleaning up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4369)
> Add transform testing framework

- demo/simple/mzcompose.yml
Small thing - makes it easier to look at prometheus metrics for kafka sources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4387)
> expose materialize port in 'simple' demo

- src/coord/src/sink_connector.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/sink/kafka.rs
- src/sql/src/plan/statement.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/kafka/verify.rs
- test/kafka-ssl/smoketest.td
Fixes #4382 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4388)
> Allow SSL sinks

- src/sql/src/plan/query.rs
- src/testdrive/src/action/sql.rs
- test/testdrive/array.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4390)
> sql: learn to invent column names for array literals

- src/transform/src/projection_extraction.rs
- test/sqllogictest/tpch.slt
Port of [this PR](https://github.com/MaterializeInc/materialize/pull/4368) with a nit applied since Frank is out. Will merge this and close that once CI passes. Signed off offline by @wangandi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4396)
> Deduplicate reduce keys

- demo/chbench/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4403)
> chbench: propagate default_progress_mode setting

- src/dataflow/src/source/mod.rs
It's not 100% clear to me why a source operator needs to return SourceStatus::Alive in this case, nor is it 100% clear to me if the operator needs to be reactivated (it seems like everything around downgrading capabilities is guarded by `if active { .... `
throwing this up to better understand both points and potentially simplify some of the source code. its pretty hard to read when theres so many levels of nesting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4189)
> Early exit when a dataflow operator is not active for a source

- doc/user/content/cli/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4405)
> fix a doc typo

- doc/user/content/ops/deployment.md
- doc/user/content/release-notes.md
- doc/user/content/sql/show-create-table.md
- doc/user/content/sql/types/_index.md
- doc/user/content/sql/types/array.md
- doc/user/data/sql_funcs.yml
- doc/user/layouts/shortcodes/cta.html
- doc/user/layouts/shortcodes/experimental.html
- doc/user/layouts/shortcodes/figure.html
- doc/user/layouts/shortcodes/fnlist.html
- doc/user/layouts/shortcodes/promo.html
- doc/user/layouts/shortcodes/version-changed.html
- doc/user/layouts/shortcodes/warning.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4392)
> doc/user: add documentation of array types

- src/expr/src/scalar/func.rs
- src/sql-parser/src/ast/defs/expr.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/scalar
- src/sql/src/plan/query.rs
- src/sql/src/plan/transform_ast.rs
- test/sqllogictest/arrays.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4410)
> sql: support ANY() array comparison function

- demo/billing/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4416)
> demo/billing: document how to create the billing topic

- src/sql/src/plan/expr.rs
- src/sql/src/plan/func.rs
- test/testdrive/tables.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4418)
> sql: support pg_catalog.pg_table_is_visible

- .editorconfig
- src/materialized/src/http.rs
- src/materialized/src/http/memory.rs
- src/materialized/src/http/static/css/memory.css
- src/materialized/src/http/static/js/memory.jsx
- src/materialized/src/http/templates/home.html
- src/materialized/src/http/templates/memory.html
This is a rudimentary but useful memory visualization page. It easily
lists indexes and can graphviz them with record counts per operator. UI
and feature improvements will come over time.
Closes #4226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4420)
> materialized: memory visualization page

- src/interchange/src/avro.rs
With this change we only emit `warn` logs when Debezium guarantees are violated.
This preserves an info log when we see a surprising but legal message -- something behind
the Debezium event frontier.
This increases the state size for the track-full case, but a future PR will allow us to
only temporarily enable full-id tracking, permanently flattening memory usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4422)
> Improve Debezium duplicate-detection diagnostics

- src/materialized/src/http/static/js/memory.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4425)
> materialized: display elapsed operator time in memory viz

- misc/monitoring/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4431)
> Fix links in misc/monitoring/README.md

- doc/user/content/sql/create-sink.md
Fixes #4391 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4468)
> SSL sink docs to match source docs

- src/coord/src/coord.rs
This PR changes the behavior of `determine_timestamp` on `PeekWhen::Immediately` to identify query timestamps that will not pass the validity check, and to advance the timestamp to one that will pass. This should have the effect of turning error messages about invalid timestamps into query delays (the query will be executed, but at a later logical timestamp than otherwise proposed). It should have no effect on timestamps that would have been valid.
Noteworthy: this may advance timestamps chosen by `self.get_read_ts()` so as to preserve linearizability. In principle this shouldn't be a problem, as the query infrastructure is clear about the times at which a system-involved query executed. In practice, we are relying on something about the order in which we return results to the client …
> [coord] Determine only valid timestamps

- src/coord/src/coord.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4434)
> coord: explicitly copy instead of clone GlobalIds

- demo/chbench/mzcompose.yml
Helps with debugging to query Prometheus for metrics directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4482)
> Expose prometheus ports in chbench

- src/coord/src/coord.rs
This should make the code clearer for the next reader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4479)
> coord: document antichain assumption

- doc/user/content/release-notes.md
- doc/user/content/sql/show-columns.md
- doc/user/content/sql/show-create-index.md
- doc/user/content/sql/show-create-sink.md
- doc/user/content/sql/show-databases.md
- doc/user/content/sql/show-index.md
- doc/user/content/sql/show-schemas.md
- doc/user/content/sql/show-sinks.md
- doc/user/content/sql/show-sources.md
- doc/user/content/sql/show-tables.md
- doc/user/content/sql/show-views.md
- src/coord/src/catalog.rs
- src/materialized/src/http/sql.rs
- src/sql/src/plan.rs
- src/sql/src/plan/statement.rs
- src/sql/src/plan/statement/show.rs
- test/sqllogictest/aggregates.slt
- test/testdrive/avro-ocf.td
- test/testdrive/avro-unions.td
- test/testdrive/bytes.td
- test/testdrive/catalog.td
- test/testdrive/dependencies.td
- test/testdrive/indexes.td
- test/testdrive/materializations.td
- test/testdrive/pg-catalog.td
- test/testdrive/regex-sources.td
- test/testdrive/rename.td
- test/testdrive/sinks.td
- test/testdrive/tables.td
- test/testdrive/uuid.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4491)
> sql: minor cleanups

- doc/user/content/sql/types/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4503)
> docs: row code sample typo

- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/cli/mzconduct.py
- misc/python/materialize/ui.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4488)
> mzcompose: minor fixes

- doc/user/content/sql/system-catalog.md
Fix #4499.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4507)
> doc/user: document column types for system catalog tables

- src/expr/src/scalar/func.rs
- src/repr/src/scalar.rs
- src/sql/src/plan/query.rs
- test/sqllogictest/arrays.slt
Fixes: https://github.com/MaterializeInc/materialize/issues/4472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4504)
> sql: support accessing elements in arrays

- src/expr/src/scalar/func.rs
- src/repr/src/row.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/list.slt
Includes:
- Casting between two list types
- Casting lists to text (seems like most of this work was already done?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4511)
> List casts

- ci/www/public/memory-visualization/index.html
- src/coord/src/coord.rs
- src/materialized/src/http/static/js/memory.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4512)
> materialized: memory page improvements

- src/dataflow/src/render/reduce.rs
Touches #4325
Previously, reduce operations for hierarchical, inaccumulable reductions (think
non-monotonic mins and maxs) go through a staged reduction where initially,
very fine subsets of the group being reduced are handled separately, and slowly
those reductions are merged together to yield the final reduction.
In a lot of the initial stages, the number of buckets is so large that the reduction
ends up being a no-op. The number of buckets has to be large because we might have to
reduce a enourmous data set, and we can't change the structure of the "reduction tree"
dynamically.
These changes make it so that we don't arrange both the input and the output at each stage
of the reduction. Instead, we arrange the input, and the elements not in the output. To give
a little bit of color with …
> dataflow: optimize reduce memory usage.

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4521)
> Prepare next phase of development: v0.5.1-dev

- src/dataflow/src/decode/avro.rs
- src/dataflow/src/decode/csv.rs
- src/dataflow/src/decode/mod.rs
- src/dataflow/src/decode/protobuf.rs
- src/dataflow/src/decode/regex.rs
- src/dataflow/src/render/upsert.rs
- src/dataflow/src/source/file.rs
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/kinesis.rs
- src/dataflow/src/source/mod.rs
- src/interchange/benches/avro.rs
- src/interchange/src/avro.rs
- test/testdrive/avro-sources.td
This will allow folks to create windows of Debezium fallibility as part of the plan
in #4172
----
This is still wip inasmuch as it still needs tests, but other than that it is ready to be reviewed, I think.
It's also best to be reviewed commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4522)
> Add the time that kafka events were created to deduplication logs

- .github/ISSUE_TEMPLATE/release.md
----
Revealed by https://github.com/MaterializeInc/materialize/issues/4552#issuecomment-712987678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4557)
> The test results section in the release checklist is test-specific

- src/testdrive/src/parser.rs
- test/testdrive/testdrive.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4560)
> testdrive: permit comment lines in command bodies

- doc/user/config.toml
- doc/user/content/cli/_index.md
- doc/user/content/ops/monitoring.md
- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- doc/user/layouts/shortcodes/fnlist.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4565)
> doc/user: polish docs for v0.5.0

- test/chaos/mzcompose.yml
The default is correct now!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4561)
> chaos: fix mysql password

- src/interchange/src/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4570)
> Extra logging when encountering a duplicate snapshot

- src/sql/src/plan/func.rs
- `ParamType::accepts_type_directly` incorrectly identified a few
pseudotypes as accepting any `ScalarType` without casting, when
they did, in fact, require casts.
- `ParamType::accepts_type_implicitly` maintained its own version
of which implicit casts were allowed, irrespective of the actual
supported casts. To remove that potential inconsistency,
`accepts_type_implicitly` now queries the cast dictionary directly
with the assistance of `ParamType::get_cast_to_for_type`, which
tracks the approrpriate `CastTo` value for each `ParamType`.
Note that this is just a tiny, incontrovertible refactor I stumbled across as part of polymorphic types. There weren't many of them that were so neatly contained, so wanted to splinter it off to ease the burden of that review.
---
This change is [<img …
> sql: improve ParamType methods

- doc/developer/guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4581)
> update confluent install instructions for macos

- src/coord/src/coord.rs
- src/coord/src/lib.rs
- src/dataflow-types/src/logging.rs
- src/dataflow/src/server.rs
- src/materialized/src/bin/materialized.rs
- src/materialized/src/lib.rs
- src/materialized/tests/util.rs
- src/sqllogictest/src/runner.rs
The first commit is a functionality preserving refactor and the second commit adds the option
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4563)
> Add a command line option to log the logging dataflows

- src/repr/src/scalar.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/arrays.slt
- test/sqllogictest/funcs.slt
This PR lays the groundwork for supporting list concatenation by introducing polymorphic types. I wanted to see if I could slightly reduce the size of this diff by not including the actual list concat work, so will add that as a fast-follow once this gets merged.
Note that the first commit is just noisy code movement, but I tried to split everything else up into reasonable commits.
Glad to walk through this in more detail; know that there's a lot going on here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4582)
> sql: polymorphic types

- src/coord/src/coord.rs
The "slow path" for queries where we need to build a dataflow kept certain post-processing (filters, projections) out of the dataflow, which had the effect of materializing substantially more data than we actually required. This situation only happened when directly querying a non-materialized source (e.g. a view, or a source with AS OF set), as other more complex situations would not strip off the post-processing in the first place.
This PR re-introduces those two finishing actions into the dataflow, so that the resulting arrangement can use fewer resources.
I saw a reduction from about 18s -> 13s on a query of the form
```
select * from view where <constraint>
```
for an unmaterialized `view`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Reintroduce filter and projection in dataflow

- src/dataflow/src/server.rs
Our logic for handling `order by .. limit ..` in the fast path does two allocations for each comparison, unpacking the `Row` into a `Vec<Datum>`. This PR allocates two vectors and repeatedly unpacks the rows into the same allocations, avoiding per-comparison allocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4631)
> re-use allocation for quickselect

- doc/user/content/sql/create-table.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4634)
> doc/user: fix formatting in CREATE TABLE doc

- bin/pyactivate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4635)
> pyactivate: squash some macOS bugs

- src/expr/src/scalar/func.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/list.slt
Includes what it says on the tin plus:
- Some more function selection refactoring around types to support the concat operator; this might stop shifting quite as much now
- Made formatting in `list.slt` more consistent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4637)
> List concat

- src/repr/src/row.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4646)
> Separate tags for Bytes/String depending on the length of their length

- src/expr/src/relation/func.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/list.slt
Closes #3800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4639)
> sql: support unnest(listany)

- Cargo.lock
- misc/python/materialize/cargo.py
- misc/python/materialize/mzbuild.py
- src/materialized/Cargo.toml
- src/materialized/src/bin/materialized/main.rs
- src/materialized/src/bin/materialized/sys.rs
- src/materialized/src/bin/materialized/tracing.rs
- src/materialized/src/lib.rs
Details in individual commit messages. Lots of code movement, so much easier to review commit by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4647)
> materialized: fix + tweak startup logging

- src/materialized/src/bin/materialized/main.rs
This makes the --log-file option work more like --data-directory.
Also, add some context to an error that occurs when trying to open the
log file for writing.
Fix #4598.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4650)
> materialized: create log file directory if it doesn't exist

- src/dataflow/src/server.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4638)
> remove unnecessary vec alloc in frontier reporting

- doc/developer/diagnostic-queries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4652)
> Diagnostic queries doc: Add section for looking for skewed operators.

- src/ccsr/src/client.rs
- src/coord/src/coord.rs
- test/testdrive/sinks.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4658)
> Small fixes to sink creation

- doc/developer/README.md
- doc/developer/diagnostic-queries.md
- doc/developer/diagnostic-questions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4656)
> Developer docs: Add diagnostic checklist

- Cargo.lock
- src/materialized/Cargo.toml
- src/materialized/src/bin/materialized/main.rs
Make the "invoked as" log line a copy/pastable shell command for ease of
debugging.
Requested by @ruchirK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4662)
> materialized: prettify invocation output

- src/dataflow/src/render/reduce.rs
successor to #4089 
Closes #4359 
I'm still not convinced that this is 100% bug free, going to go through and add more comments and tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4633)
> combine accumulable reductions in one dataflow fragment

- README.md
We are no longer planning on doing either of these, or at least not "soon".
(Reviewers are the product people, so you guys can speak up if these are indeed on the roadmap and I'm just misinformed)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4679)
> Remove inaccurate "coming soon" section from README.md

- src/sql/src/pure.rs
- test/testdrive/csv-sources.td
fixes #4674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4676)
> Fail fast when trying to create a file source from a directory

- src/coord/src/sink_connector.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/sink/avro_ocf.rs
- src/dataflow/src/sink/kafka.rs
- src/interchange/src/avro.rs
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement.rs
- src/testdrive/src/action/avro_ocf.rs
- src/testdrive/src/action/kafka/verify.rs
- src/testdrive/src/format/avro.rs
- test/testdrive/avro-sinks.td
Docs to follow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4668)
> Keys in sinks

- bin/xcompile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4695)
> xcompile: fix bootstrap command when not run from root

- test/testdrive/sinks.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4698)
> Don't attempt to connect to Twitter on 8080, which hangs forever

- src/sql-parser/tests/testdata/ddl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4700)
> Fix merge skew in ddl test

- src/ore/src/lex.rs
- src/ore/src/lib.rs
- src/sql-parser/src/lexer.rs
- src/sql-parser/src/lexer/buf.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4703)
> sql-parser: generalize lexing code

- src/sql/src/plan/query.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4707)
> sql: remove stray dbg!

- doc/user/content/release-notes.md
- doc/user/content/sql/copy-to.md
- src/pgwire/src/message.rs
- src/pgwire/src/protocol.rs
- test/pgtest/copy.pt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4711)
> pgwire: support COPY TO BINARY

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4719)
> flag that TAIL has a breaking change

- bin/check
- src/repr/src/row.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4708)
> Make the dbg! macro fail CI

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4706)
> Prepare v0.5.2 dev

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4723)
> Prepare v0.5.2 dev on top of v0.5.1

- doc/user/config.toml
Part of #4684 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4725)
> Mark 0.5.1 as released in the docs config

- doc/user/content/cli/_index.md
- doc/user/content/release-notes.md
- doc/user/content/sql/create-sink.md
- doc/user/content/sql/select.md
- doc/user/content/sql/tail.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4724)
> doc/user: polish release notes for v0.5.1

- src/expr/src/scalar/func.rs
- src/ore/src/lex.rs
- src/pgrepr/src/value.rs
- src/repr/src/strconv.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/list.slt
Closes #4627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4687)
> text -> list cast

- .github/ISSUE_TEMPLATE/release.md
- misc/python/materialize/cli/mkrelease.py
- misc/python/materialize/git.py
This should be reviewed commit-by-commit.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4726)
> Various improvements to the release process and release script

- src/materialized/src/bin/materialized/main.rs
The old messages didn't say which value to set it to
(I know any "truthy" value works, but `1` seems to be the most idiomatic)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4743)
> Make it clearer how to set MZ_DEV

- src/interchange/src/avro.rs
- test/testdrive/avro-sinks.td
Fixes #4722
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4744)
> Set `connect.name=io.debezium.data.Json` for JSON fields in sink output

- doc/user/content/sql/copy-to.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4741)
> docs: fix copy-to option docs

- src/avro/src/schema.rs
This should make error messages involving schemas slightly less horrible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4745)
> Debug-serialize Avro schemas as Json

- src/pgwire/src/codec.rs
- src/pgwire/src/message.rs
- src/pgwire/src/protocol.rs
The present design of the error reporting interface in the pgwire crate
makes it very convenient to report errors that use the default fields
(code and message), but impossible to report errors that use additional
fields like hint and detail. Forthcoming commits will add even more
additional fields, like the position in the query at which the error
occurred.
Rework the API so that reporting an error requires building up an
ErrorResponse manually, with whatever fields they like. But add builder
methods to ErrorResponse so cut down on the verbosity. This results in a
slight hit to ergonomics in exchange for a big increase in flexibility.
Also, match PostgreSQL in using exactly the same type to represent
errors and notices. No point in enforcing a separation that doesn't
exist.
---
This …
> pgwire: prepare for more error response fields

- Cargo.lock
This reduces/updates some of the nested dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4757)
> Update for rust-prometheus having merged from upstream

- .github/ISSUE_TEMPLATE/release.md
Part of #3978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4754)
> release: Document how to determine billing demo container status

- src/sql-parser/src/ast/defs/query.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql-parser/tests/testdata/error
- src/sql-parser/tests/testdata/select
- src/sql/src/plan/query.rs
- test/sqllogictest/cockroach/order_by.slt
- test/sqllogictest/cockroach/tuple.slt
- test/sqllogictest/distinct_on.slt
- test/sqllogictest/funcs.slt
- test/sqllogictest/postgres/join-lateral.slt
- test/testdrive/persistence.td
- test/testdrive/tables.td
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4761)
> sql: various fixes for zero-column tables

- demo/billing/mzcompose.yml
- doc/user/content/demos/microservice.md
Fix #4765.
Update the docs to use mzconduct instead of mzcompose and add a new workflow for testing locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4778)
> demo/billing: default to creating a topic always in Docker

- doc/user/content/release-notes.md
- doc/user/content/sql/discard.md
- doc/user/layouts/partials/sql-grammar/discard.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/coord/src/command.rs
- src/coord/src/coord.rs
- src/coord/src/session.rs
- src/pgtest/src/lib.rs
- src/pgwire/src/protocol.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/show
- src/sql/src/plan.rs
- src/sql/src/plan/statement.rs
- test/lang/csharp/SmokeTest.cs
- test/pgtest/prepare.pt
- test/testdrive/temporary-views.td
First add support for `DISCARD ALL`. Then add a test that verifies Npgsql actually works with our `COPY` implementation. (It does!) ~with one wrinkle: it's impossible to cancel the `COPY` with public API, at least as far as I could find.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4783)
> Shake out bugs with Npgsql and COPY

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4788)
> docs: Fix link tag syntax

- Cargo.lock
- src/interchange/Cargo.toml
- src/interchange/src/avro.rs
- test/testdrive/avro-sources.td
If we don't have source coordinates, just do our best rather than refusing to ingest the message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4762)
> Ingest SQL Server Debezium data; Don't refuse to ingest messages with unrecognized source coordinates

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4805)
> Prepare v0.6.0

- .github/ISSUE_TEMPLATE/release.md
- misc/python/materialize/cli/mkrelease.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4808)
> release: Add a note about never preparing minor version bumps

- misc/python/materialize/cli/mkrelease.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4811)
> mkrelease: allow preparing dev

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This reverts commit 882266b6218d5f088da041c596653ef7228507b1.
This is necessary for #4810 to apply cleanly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4812)
> Revert "Prepare v0.6.0 (#4805)"

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
----
Clone of #4809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4810)
> Prepare next phase of development: v0.5.3-dev

- doc/user/content/sql/tail.md
As mentioned in #4790. Didn't get around to these improvements before
landing that PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4821)
> doc/user: further clarify the meaning of AS OF/SNAPSHOT in tail

- doc/user/assets/sass/_content.scss
- doc/user/content/demos/_index.md
- doc/user/layouts/_default/baseof.html
- doc/user/layouts/partials/breadcrumbs.html
@benesch Just tagging you bc of your love of Hugo partials.
closes #4591
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4789)
> Breadcrumbs

- doc/user/assets/sass/_content.scss
- doc/user/content/sql/functions/_index.md
- doc/user/content/sql/functions/cast.md
- doc/user/content/sql/types/_index.md
- doc/user/content/sql/types/list.md
- doc/user/data/sql_funcs.yml
- doc/user/layouts/partials/sql-grammar/type-list.svg
- doc/user/layouts/shortcodes/list-operators.html
- doc/user/sql-grammar/sql-grammar.bnf
- src/sql/src/plan/query.rs
- test/sqllogictest/list.slt
@msudberg ty for offering to review. I'm looking mostly for a copy edit, but lmk if you need help setting up a tinkering environment to go through the examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4739)
> docs: document list type

- doc/user/content/sql/types/array.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4826)
> doc/user: link to newly-published list docs in array docs

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4824)
> Continue v0.5.3 dev

- doc/user/config.toml
- doc/user/content/release-notes.md
Required by: https://github.com/MaterializeInc/materialize/issues/4804
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4830)
> docs: update user-facing docs with release information

- Cargo.lock
see security check: https://buildkite.com/materialize/security/builds/234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4835)
> update time to v0.2.23

- src/sql-parser/src/parser.rs
This should fix the broken build!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4838)
> sql-parser: peek_prev_range -> peek_prev_pos

- src/dataflow/src/source/mod.rs
Updates to the source_info are written once we are caught up with the
source to avoid incurring overhead on every source message. However,
during bootstrap it can take a long time until we're caught up with the
source, and that's exactly when a customer likely wants to view
progress.
Source will now flush source_info metrics every N messages to still show
progress in such cases.
Thanks to @krishmanoh2 for noticing this!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4831)
> periodically flush source_info metrics

- play/mbta/ci/mbta-demo-cmd.sh
- play/mbta/doc/mbta-setup.md
- play/mbta/examples/all-frequent-routes-config-weekday.csv
- play/mbta/examples/all-frequent-routes-config-weekend.csv
- play/mbta/examples/all-frequent.sql
- play/mbta/mzcompose.yml
- play/mbta/src/main.rs
This involves re-reading the log and sending delete events for every insert before the last reset.
There's also a bunch of minor improvements, which are described in the commit messages.
Also, I decreased the number of layers of nesting in the log reading code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4837)
> play/mbta: Support the reset event

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4834)
> .github: update release template with v0.5.2 learnings

- src/expr/src/scalar/func.rs
- src/sql/src/plan/func.rs
- src/sql/src/plan/typeconv.rs
@JLDLaughlin Had some free time tonight and wanted to tinker around with this to see if I could get the iterative casts into the more standard casts (I couldn't), but had this nominal refactor sitting on my machine so figured I'd throw it up. If you already started this, glad to cede to your work and sorry if I stepped on your toes!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4851)
> sql/plan: unify iterative casts

- Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4870)
> Update several dependencies that have been left behind by dependabot

- src/dataflow/src/arrangement/manager.rs
We added the `mz_arrangement_maintenance_active_info` metric to track whether
any specific arrangement is spending all of its time in maintenance.
Unfortunately that means that it grows with the number of arrangements,
possibly to hundreds or thousands of metrics.
With this new metric we will only see one metric per worker. It is still possible to determine
which arrangement is spending all its time in mainenance by looking at the
`mz_arrangement_maintenance_seconds_total` metric, which will have more detail about which
arrangements are actually taking up time for any given interval.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4863)
> Reduce the number of metrics we send for tracking "in maintenance"

- misc/python/materialize/cli/mzconduct.py
This fixes an occasional source of bugs, And one explicit bug that I ran into.
More importantly brings mzconduct more inline with the conventions of
mzcompose, and is thus a step on the way to #4769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4877)
> mzconduct: Use relative paths instead of changing directory

- src/sql/src/plan/func.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4879)
> sql: fix grammar in comment in func selection code

- src/repr/src/strconv.rs
- test/sqllogictest/map.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4874)
> sql: support empty maps

- doc/user/content/demos/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4894)
> docs: add redirect from /demo to /demos

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4896)
> Update Slack Link

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4897)
> README: move getting started to the top

- doc/developer/diagnostic-queries.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4917)
> Correct link

- src/interchange/src/avro.rs
- src/testdrive/src/format/avro.rs
- test/testdrive/avro-decode.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4916)
> interchange: add map to AvroFlatDecoder

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4923)
> Prepare v0.5.4 dev

- ci/test/build.py
- misc/python/materialize/bintray.py
Fix #4850.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4860)
> ci/test: ignore existing files when uploading .deb

- doc/user/layouts/shortcodes/json-operators.html
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4933)
> Fix typo in docs link

- doc/user/content/release-notes.md
- doc/user/content/sql/functions/to_char.md
- doc/user/data/sql_funcs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4882)
> Add documentation for to_char and the specification language

- src/dataflow/src/render/reduce.rs
- test/sqllogictest/aggregates.slt
Touches #4669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4895)
> dataflow: fuse non-monotonic min and max

- src/interchange/src/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4944)
> more verbose error message for CCSR failures

- doc/user/assets/sass/_content.scss
This PR is intended to force a redeploy from netlify
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4968)
> Add a newline to force netlify redeploy

- misc/civiz/templates/slt.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4971)
> civiz: attempt to fix after column rename

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4966)
> Continue v0.5.4 dev

- doc/user/content/get-started.md
- doc/user/content/katacoda/_index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4975)
> doc/user: fix katacoda link and improve error message

- misc/civiz/migrate/versions/3da7700dba2d_rename_inference_failure_to_wrong_.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4972)
> civiz: add migration for inference_failure rename

- doc/user/config.toml
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4979)
> update files for v0.5.4

- misc/python/materialize/cli/mzconduct.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4993)
> Remove a debug statement from mzconduct

- src/kafka-util/src/bin/kgen.rs
With a cursory look at the assembly output in the Rust playground the extend version should be at least as fast if not faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4992)
> kafka-util: implement unsafe sections in safe Rust

- src/pgrepr/src/types.rs
- src/pgrepr/src/value.rs
This is pure code movement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4995)
> pgrepr: order Value enum consistently

- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
Fix #4988.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5001)
> doc/user: try to clarify group_id_prefix option

- src/dataflow/src/render/reduce.rs
- test/testdrive/monotonic.td
Still needs testing + another pass through all of the comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4978)
> dataflow: teach renderer to fuse monotonic hierarchical aggregates + clean up code

- src/coord/src/coord.rs
- src/coord/src/session.rs
- src/pgwire/src/protocol.rs
It was previously needed but no more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5011)
> coord: remove error return from set_portal

- doc/user/content/sql/close.md
- doc/user/content/sql/declare.md
- doc/user/content/sql/fetch.md
- doc/user/content/sql/tail.md
- doc/user/layouts/partials/sql-grammar/close.svg
- doc/user/layouts/partials/sql-grammar/declare.svg
- doc/user/layouts/partials/sql-grammar/fetch.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5019)
> doc: document new cursor stuff

- misc/monitoring/dashboard/conf/grafana/dashboards/materialize-basic.json
Simple Dashboard for users starting with materialize
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5014)
> Materialize basic dashboard

- .github/ISSUE_TEMPLATE/release.md
Issue to investigate and add the test back: https://github.com/MaterializeInc/materialize/issues/5043
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5042)
> github: remove flakey test from release

- doc/user/content/release-notes.md
- doc/user/content/sql/close.md
- doc/user/content/sql/declare.md
- doc/user/content/sql/fetch.md
I'm trying to move away from the stability-through-obscurity approach we've taken to new features in the past. If there are bugs my goal is to either document them or hide them behind experimental mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5044)
> doc/user: note known issue with FETCH in v0.5.3

- src/expr/src/scalar/func.rs
- src/interchange/src/avro.rs
- src/pgrepr/src/types.rs
- src/pgrepr/src/value.rs
- src/repr/src/scalar.rs
- src/sql/src/plan/typeconv.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5047)
> Allow record fields to be non-nullable

- src/dataflow/src/source/mod.rs
Motivation is https://github.com/MaterializeInc/materialize/issues/5024
This logic has grown over time and is very difficult to follow. There
need to be some deeper refactorings, but taking a first pass to at least
straighten this portion out a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5050)
> reorganize source reading loop

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5061)
> Prepare v0.6.1 dev

- src/dataflow/src/render/reduce.rs
- test/sqllogictest/jsonb.slt
Touches #4991
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5002)
> dataflow: even more refactors on reduce rendering

- doc/user/content/ops/diagnosing-using-sql.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5066)
> docs: add link to memory visualization tool

- misc/python/materialize/cli/mzcompose.py
These helpers commands from mzconduct and are simple ports from their
previous implementations. They are useful for determining the high
numbered ports that Docker Compose allocates for services when they are
not bound to well-known ports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5075)
> Add web and list-port commands to mzcompose

- doc/user/content/versions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5016)
> Document that unstable builds are also available in Docker

- src/repr/src/adt/datetime.rs
- src/repr/tests/strconv.rs
Adds support for dates like `700203`, `0010203` and `200102031`
cc @quodlibetor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4889)
> repr: add support for all compacted date formats

- misc/python/materialize/mzcompose.py
This causes the logs to be things like `stopping chaos_kafka_1` instead of
`stopping c0ff33` which is a bit nicer when debugging.
For example:
```
$ docker exec -t chaos_kafka_1 tc qdisc del dev eth0 root netem
$ docker kill chaos_materialized_1
chaos_materialized_1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5094)
> chaos: Use container names instead of IDs for operations

- Cargo.lock
- LICENSE
- misc/python/materialize/cli/mkrelease.py
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5099)
> Continue v0.6.1 dev

- src/materialized/src/http/metrics.rs
- src/mz-process-collector/src/process_collector.rs
Resolves #5093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5097)
> mz-process-collector: Report total system swap and swap free

- misc/python/materialize/mzcompose.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5101)
> stderr should still go to stderr if it is not captured

- src/mz-process-collector/src/process_collector.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5106)
> You need to multiply to convert KiB to B

- misc/python/materialize/cli/mkrelease.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5102)
> mkrelease: fix accidentally commented-out code

- doc/user/content/release-notes.md
- doc/user/content/sql/create-table.md
- doc/user/layouts/partials/sql-grammar/col-option.svg
- doc/user/layouts/partials/sql-grammar/create-table.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5063)
> docs: v0.6.0 release notes

- doc/user/config.toml
- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5113)
> Update released versions to include 0.6.0

- ci/nightly/pipeline.yml
- ci/slt/pipeline.yml
Fallout from https://github.com/MaterializeInc/materialize/pull/5072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5123)
> ci: Fix two remaining pipeline configs for new mzcompose API

- ci/nightly/pipeline.yml
- test/smith/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5124)
> Fix smith ci mzcompose

- .github/ISSUE_TEMPLATE/release.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5062)
> release: Update with new experimental split cloud/db process

- .github/ISSUE_TEMPLATE/release.md
- misc/python/materialize/cli/mkrelease.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5126)
> mkrelease: Update user doc config as part of final tagging

- doc/user/content/get-started.md
PTAL @sploiselle @benesch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5136)
> doc/user: Fix minor grammar

- src/dataflow/src/server.rs
- src/dataflow/src/source/mod.rs
- src/interchange/src/avro.rs
Previously:
> Toavoid unnecessary blocking, Materialize will not attempt to downgrade the capability. Pleaseconsider resetting your system time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5138)
> fix missing spaces in a few log messages

- src/materialized/tests/sql.rs
CI's a bit slow, frequently this shows 0 rows after 1s. Dump it in a loop to make it more resilient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5140)
> fix flakiness in test_tail_fetch_timeout

- Cargo.lock
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/mod.rs
- src/repr/Cargo.toml
- src/repr/src/adt/datetime.rs
- src/repr/src/scalar.rs
- src/repr/src/strconv.rs
- src/repr/tests/strconv.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/dates-times.slt
- test/sqllogictest/timezone.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5130)
> sql: add timezone()/AT TIME ZONE, implement named time zones with chrono-tz

- src/ore/src/test.rs
- src/sqllogictest/src/main.rs
- src/sqllogictest/src/runner.rs
Defaulting to WARN and ERROR logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5162)
> Configure SLTs to emit console logs

- src/sql/src/plan/func.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/list.slt
redo of #5145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5147)
> sql: support polymorphic functions with decimal elements

- src/coord/src/catalog.rs
- src/expr/src/scalar/func.rs
- src/interchange/src/avro.rs
- src/pgrepr/src/types.rs
- src/pgrepr/src/value.rs
- src/repr/src/scalar.rs
- src/sql-parser/tests/testdata/create
- src/sql/src/plan/func.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/list.slt
- test/sqllogictest/map.slt
- test/testdrive/list.td
- test/testdrive/map.td
- test/testdrive/types.td
Fixes #4953 
Note that this PR prohibits casting between custom types or using custom types in polymorphic functions. I have commits lined up to support both features, but wanted to reduce the scope of each PR to make them more grokkable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5167)
> sql: resolve custom types to scalar types

- src/sql/src/plan/statement.rs
- test/sqllogictest/list.slt
- test/sqllogictest/map.slt
just cleaning up a TODO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5142)
> sql: improve CREATE TYPE option validation

- src/expr/src/scalar/func.rs
- src/repr/src/scalar.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/cast.slt
Note that I also have a commit lined up for returning less-lame results from `pg_typeof` but it's tangled up behind my commit for polymorphic custom type support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5168)
> sql: allow casts between custom types

- src/repr/src/row.rs
`test_datum_sizes` used `if !x == y` which is not the same as `if x != y`. Consequently, it wasn't testing what it meant to be testing, and was passing instances of mis-sized data (related to our variable-width lengths for slices).
This fixes that, and correct `datum_sizes`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5171)
> Correct test_datum_sizes, and datum_sizes

- test/sqllogictest/postgres/subselect.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5186)
> sql: enable more PG subselect tests

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5190)
> move release note to the correct version

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/expr/src/scalar/func.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/funcs.slt
Required for https://github.com/MaterializeInc/materialize/issues/5086.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5192)
> sql: add upper string function

- doc/user/content/release-notes.md
- doc/user/content/sql/create-sink.md
- doc/user/content/sql/create-source/avro-kafka.md
- doc/user/layouts/partials/create-source/connector/kafka/details.html
- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5133)
> 4955: Added details for using SHA-256 and SHA-512 encryption with SASL.

- demo/billing/Cargo.toml
- src/expr/Cargo.toml
- src/sql/Cargo.toml
- src/sqllogictest/Cargo.toml
- test/correctness/Cargo.toml
- test/test-util/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5205)
> Depend on the clock feature in chrono where we are depending on it

- src/materialized/src/bin/materialized/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5197)
> mention the special `--log-file=stderr` value in `--help`

- src/dataflow/src/source/file.rs
Before this we were creating one file reader per materialized worker, which
would read the entire file into memory, put it into a queue that was not
getting read from.
The queues were bounded to 10,000 records, so this was unlikely to cause an OOM
but it is a bit unfortunate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5196)
> file-sources: Only create a file reader if the source is active

- src/peeker/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5211)
> Peeker also depends on chrono/clock

- src/sqllogictest/src/main.rs
- src/sqllogictest/src/runner.rs
Fix #5208.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5209)
> sqllogictest: introduce --workers option

- src/sql/src/plan/func.rs
I'm adding OIDs to functions and rather than introduce ambiguity around which OID maps to which implementation, I'm availing to reduce the number of functionally identical implementations to 1. In this case, it's easier to do a runtime check on the number of parameters on `concat` than have duplicate implementations of some `json` functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5212)
> sql: more easily allow 0 argument variadic functions

- misc/python/materialize/mzcompose.py
The intended command is `docker ps`, but when
34f31dcbde1e1894491259e38941c71634d669bd was committed, the command
changed from `mzcompose_wait` to `spawn.runv`. This dropped the call to
docker. Call `composition.run` to run the desired docker command.
Fixes #5215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5216)
> Fixup mzcompose WaitStep

- src/interchange/src/avro.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5210)
> Improve docs on DebeziumDeduplicationState

- src/sql/src/plan/func.rs
@benesch––No rush on this at all, but here is the alternative take on custom type polymorphism I mentioned that doesn't need `Option<Option<u32>>`. I realized as I was falling asleep last night this approach will actually be necessary once we support arbitrary types for maps' keys, so wanted to at least jot it down as a reference while it was top of mind. lmk if you prefer this approach and I can clean up the docs and merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5207)
> sql: reference for other possible custom polymorphic resolution

- src/avro/src/decode.rs
- src/avro/src/types.rs
- src/interchange/src/avro.rs
- test/testdrive/avro-sources.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5230)
> Check postgres total_order field for Debezium dedupe

- misc/kafka-util/scripts/print_archive.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5239)
> Be robust to null values in print_archive.py

- doc/developer/diagnostic-questions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5229)
> doc: add version check items to checklist

- doc/developer/README.md
- doc/developer/fast-compiles.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5261)
> doc: write up learnings for faster compiles

- misc/python/materialize/git.py
@cirego I'm not convinced that this is the simplest way to coax the desired information out of Git, but it has the appropriate behavior AFAICT!
mzbuild goes to great lengths to contend with Git's working directory
and ignore rules when auto-discovering mzbuild images. But it wasn't
properly handling *new* mzbuild images whose files were not yet added to
Git's index. Update the logic for finding files to account for this
case.
Fix #5020.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5270)
> mzbuild: try even harder to find mzbuild files

- src/dataflow/src/sink/kafka.rs
This adds the necessary state machine and kafka calls to write
transactionally to sinks and their respective consistency topics.
The plumbing to enable this is not hooked up, so this code is currently
inactive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5260)
> add transactional writing to kafka sinks

- src/coord/src/coord.rs
- src/coord/src/timestamp.rs
In a few places some of the messages handled by the coord serve loop
would "return", expecting that this would go on to handle the next
message. However return here exited the entire coord loop causing
materialize to exit completely.
In order to prevent us from making this mistake again, refactor the
serve loop so that each message type is handled in its own function. This
does the correct thing for return (stop the current message processing
and proceed), which is sometimes needed in error paths. The serve loop
is now easily scannable by the eye and it's much easier to understand
what's going on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5296)
> coord: refactor serve loop to be safer

- demo/chbench/mzcompose.yml
Forgot to change the name of the database to restart :-/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5305)
> Fixup service to restart in ingest-bench

- src/dataflow/src/render/reduce.rs
- test/sqllogictest/jsonb.slt
Closes #5304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5306)
> dataflow: correctly render multiple basic aggs

- test/sqllogictest/postgres/subselect.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5312)
> lower timestamp frequency for subselect test

- Cargo.lock
- src/aws-util/Cargo.toml
- src/aws-util/src/aws.rs
- src/aws-util/src/kinesis.rs
- src/aws-util/src/lib.rs
- src/aws-util/src/s3.rs
- src/coord/src/timestamp.rs
- src/dataflow-types/Cargo.toml
- src/dataflow-types/src/types.rs
- src/dataflow/Cargo.toml
- src/dataflow/src/render/mod.rs
- src/dataflow/src/source/kinesis.rs
- src/dataflow/src/source/mod.rs
- src/dataflow/src/source/s3.rs
- src/expr/src/id.rs
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql/Cargo.toml
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/with_options.rs
- src/testdrive/src/action.rs
- test/performance/perf-kinesis/src/main.rs
Part of #4914 , this should **definitely** be reviewed commit-by-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5202)
> s3 sources: support reading an entire bucket
