MaterializeInc/materialize

src/compute/src/render/mod.rs
src/compute/src/render/reduce.rs
src/compute/src/render/top_k.rs

This PR improves the representation of `(key, hash)` pairs used in top-k arrangement stacks to use `Row` instead of `(Row, u64)`. The latter allows us to use spine types that specialize the representation of rows by `DatumContainer`. Additionally, the PR also improves the type-based dispatch to form arrangement stacks in top-k, thereby allowing us to use a spine type relying on `DatumContainer` for values in addition to keys in all but the first level of the stack.
* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/24337
The commits can be looked at individually. This is the final PR in the series of #24307, #24375, and #24388.
-

Improve representation in top-k

---

src/adapter/src/coord.rs
src/sql/src/session/vars.rs

This PR makes it such that we always trace a `warn!` for slow coordinator messages, even if we don't have a valid OTEL context. It also adds a LaunchDarkly configurable threshold for tracing them.
Chatted about this in our team weekly
- N/a

coord: Update warn! tracing of slow coordinator messages

---

src/catalog/src/durable.rs
src/catalog/src/durable/impls/migrate.rs
src/catalog/tests/migrate.rs

This commit cleans the durable catalog tests so that they initialize catalogs via test constructor methods. This significantly reduces the number of callers to the non-test constructor, making it easier to change in the future.

catalog: Cleanup durable catalog tests

---

src/storage/src/sink/kafka.rs

An interim solution until we figure out https://github.com/MaterializeInc/materialize/issues/24864 and revert this revert https://github.com/MaterializeInc/materialize/pull/24865.
-

storage: handle librdkafka queue saturation in sinks

---

src/adapter/src/coord.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/explain/optimizer_trace.rs
src/adapter/src/optimize/mod.rs
src/adapter/src/optimize/peek.rs
src/repr/src/explain/tracing.rs
src/sql-parser/src/ast/defs/statement.rs

First of a series of commits that will substantially minimize of the `EXPLAIN` related code that needs to live in the `Coordinator` methods. This should make it pretty easy to add and maintain `EXPLAIN` for the missing statement types (`VIEW`, `SUBSCRIBE`) in the future.
Until now `FastPath` selection was modeled as a side effect of an optimizer pipeline run. This PR refactor the code so now
1. The optimizer trace will contain a dedicated `optimize/fast_path` stage which will follow `optimize/global` instead of `optimize/finalize_dataflow` when fast path is selected.
2. The `fast_path_plan` parameter disappears from a bunch of structs and methods related to `EXPLAIN` handling (as due to (1) it is now treated as just another `OptimizerTrace` entry).
3. …

explain: rework `FastPath` handling

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml

We have been seeing segfaults in CI after the upgrade of `rust-rdkafka` including when using what seems to be correct drop logic in https://github.com/MaterializeInc/materialize/pull/24899. It's unclear if it's a general bug in `rust-rdkafka` that is made more likely by destroying the client in a different thread, a bug in our drop code, or something else. For now the best course of action is to revert the codebase to the prior stable state and live with the small risk of deadlocking while we try to figure out what is causing the memory corruption.
This reverts commit c7ecf05abc3e06bf7d3630ea4c4aef90a8c368da.
-

Revert "deps: upgrade to rust-rdkafka with non-blocking drop"

---

src/adapter/src/flags.rs
src/sql/src/session/vars.rs
src/storage-controller/src/lib.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs

We have a customer whose collection's frontiers are known to be incompatible with the asserts in install_dependency_read_holds; we want to disable these assertions for this env specifically. To do this, introduce an LDF flag.
-

storage: add LD flag to disable asserts in install_dependency_read_holds

---

src/compute/src/render/context.rs
src/compute/src/render/mod.rs
src/compute/src/render/reduce.rs
src/compute/src/render/top_k.rs
src/repr/src/row.rs

We have a lot of boilerplate around packing rows, which makes our code harder to read and reason about. This PR introduces two convenience methods, on `SharedRow` and `Row`, that allow row packing with fewer lines and symbols.
-

Streamline row packing

---

Cargo.lock
misc/cargo-vet/audits.toml
src/compute/src/render/join/delta_join.rs

Update dogs3 dependency

---

src/compute/src/row_spine.rs
test/testdrive/introspection-sources.td

This PR starts the batching for `row_spine` at 2 << 20, and grows geometrically up to 128 << 20. These are made up numbers that I heard before. It also switches to binary search to determine in which batch an index lies, and this should generally be fine even with relatively smaller batch that do not grow geometrically, though it's a bit of a smell if it ends up doing too much work.
cc: @antiguru 
-

Use more robust row batch sizing

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.87.0-dev

---

src/compute/src/row_spine.rs

Tidy non-idiomatic code

---

Cargo.lock
misc/cargo-vet/audits.toml
src/compute/src/render/mod.rs

This picks up a DD version that canonicalizes `PointStamp` to drop trailing `T::minimum()` values, to ensure a canonical representation.
-

Update PointStamp canonicalization

---

src/adapter/src/coord/sequencer/inner.rs
src/catalog/src/memory/objects.rs
src/environmentd/tests/sql.rs
src/storage-types/src/sources.rs

For PG sources, we allow setting a custom compaction window on the primary source, but it should really take effect on the subsources.
To do this, we need to set the compaction policy whenever we create the PG source or add subsources.
cc @mjibson 
@mjibson I think this is a little easier to accomplish than the idea of propagating the option to the subsource statement itself. Namely, if we ever allow users to change this setting on the source, it's preferable if we just get the latest version of this value, rather than trying to maintain consistency across all of the objects.
The downside here is that for subsources, the compaction window is never read, which is goofy.
wdyt?
(Sorry not including more detail am running to catch a plane).
-

sql: propagate primary source logical compaction to subsources

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml

The upgraded rdkafka incorporates MaterializeInc/rust-rdkafka@ed2a45d, which fixes a memory error in MaterializeInc/rust-rdkafka@c729f89. It does *not* include the upgrade to librdkafka v2.3.0, as the latest version of librdkafka seems to have other unsoundness.
Please scrutinize my librdkafka change since I clearly got it wrong the first time.
- n/a

deps: upgrade to rdkafka with background drop

---

ci/test/pipeline.template.yml
src/ore/src/retry.rs

Quite expensive when the failure is just broken code and we retry 3 times
Seen in https://buildkite.com/materialize/tests/builds/74721
-

ci: Disable auto retries again, cargo-test: Disable flaky test_retry_async_fail_max_duration

---

misc/dbt-materialize/setup.py

Point the support address used in the dbt adapter to the new dedicated mailing list.

dbt-materialize: update address for support

---

src/fivetran-destination/README.md

Updated the build instructions to assume a fresh clone of the MZ repo.
Emrah reached out because he hit an issue with the `misc/fivetran_sdk` submodule not being cloned.
- N/a

fivetran-destination: Update build instructions

---

src/fivetran-destination/src/destination/config.rs
src/sql/src/session/hint.rs

This PR sets the application name of the client the Fivetran destination uses to send requests to Materialize to `mz_fivetran_destination`. It also adds the name to the set of application names we tag Prometheus metrics with.
More easily debug and track usage of the Fivetran destination
- N/a

fivetran-destination: Set application name for SQL client

---

src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars.rs
test/legacy-upgrade/create-in-v0.71.0-role-var.td

We've release Role Default variables to 100% of users, and the feature flag has a default value of `true`. We no longer need this feature flag so get rid of it!
Clean up a 100% released feature flag
- N/a

ld: Remove `enable_role_vars` feature flag

---

ci/nightly/pipeline.template.yml
ci/plugins/cloudtest/hooks/post-command

OoM seen in https://buildkite.com/materialize/nightlies/builds/6301#018d6ef6-1a6a-4b3e-a83c-41adb2163e72
-

ci: Increase agent size for platform-checks in cloudtest

---

src/buf.yaml
src/compute-types/src/dataflows.rs
src/compute-types/src/explain/text.rs
src/compute-types/src/plan.proto
src/compute-types/src/plan/interpret/api.rs
src/compute-types/src/plan/lowering.rs
src/compute-types/src/plan/mod.rs
src/compute/src/render/mod.rs
test/sqllogictest/explain/physical_plan_as_json.slt

This PR extends all `Plan` variants with `node_id` fields and makes the MIR->LIR lowering assign node IDs as `Plan`s are created. Making use of the new IDs is left as follow-up work.
This is part of the Operator Hydration Status Tracking design (https://github.com/MaterializeInc/materialize/pull/24265).
Part of https://github.com/MaterializeInc/materialize/issues/23859.
Commits can be reviewed separately.
There is some duplication involved here that comes from the `node_id` field being repeated in every `Plan` variant. An alternative implementation that avoids this would be to wrap the `Plan` enum into a struct, like this:
```rust
struct Plan {
node_id: NodeId,
inner: PlanInner,
}
enum PlanInner {
Constant { ... },
...
}
```
I tried out this …

compute: add node IDs to `Plan`s

---

doc/user/content/manage/terraform.md

Removes a vestigial `size` left behind in one of the examples in the Terraform docs.

doc/user: update Terraform example

---

src/mysql-util/src/replication.rs
test/mysql-cdc/mzcompose.py
test/mysql-cdc/override/10-replica-connection.td

Only enforce the `replica_preserve_commit_order` setting when creating a MySQL Source if connected to a replica server.
The `replica_preserve_commit_order` setting on MySQL is used to ensure that when connected to a MySQL replica, the original order of transactions received from the primary is respected, to ensure data consistency between the primary and replica. This has been highlighted as a cause of data-inconsistency issues in a recent Jepsen [report](https://jepsen.io/analyses/mysql-8.0.34) on MySQL.
cc @nrainer-materialize - there are some additions to the `mysql-cdc` test config here that might be interesting for other test scenarios (setting up a primary-replica cluster and connecting to the replica).
-

storage: (MySQL) Only enforce replica_preserve_commit_order setting if connected to a replica

---

.config/nextest.toml
src/stash/src/tests.rs

See https://github.com/MaterializeInc/materialize/issues/24961
-

cargo-test: Disable test_stash_fail_after_commit

---

bin/ci-builder
ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios.py
misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/mzcompose/composition.py
misc/python/materialize/mzcompose/services/materialized.py

See https://www.notion.so/materialize/platform-v2-Persist-Catalog-Forward-Compatibility-6eaecaaa767e4860b6bd257471b985c4
-

platform-checks: Add preflight check scenarios

---

ci/mkpipeline.py

As noticed by Nikhil in https://materializeinc.slack.com/archives/C01LKF361MZ/p1707070177405639
-

ci: Always add concurrency group for aarch64

---

src/storage/src/sink/kafka.rs

It turns out that `librdkafka` can send messages to the broker on its own volition (probably on a timer from a background thread or something like that), and those messages are counted by `in_flight_count`.
This means that we'll have to take `librdkafka`'s word for it and not assert its claim ourselves. I have also manually audited its code and it indeed flushes everything before committing.
Fixes #24721
-

storage: remove flaky assertion

---

misc/python/materialize/scratch.py

This fixes errors like
```
$ git push --no-verify ubuntu@i-042bfd431ce875866:materialize/.git 2b71f8ff2b7cdcb8d49845ab8ad890fab5e99823:refs/heads/scratch --force
Pushing submodule 'misc/fivetran-sdk'
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use
git push origin HEAD:<name-of-remote-branch>
Unable to push submodule 'misc/fivetran-sdk'
fatal: failed to push all needed submodules
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/nrainer/Workspaces/mz-repo-2/misc/python/materialize/cli/scratch/__main__.py", line 81, in <module>
main()
File "/Users/nrainer/Workspaces/mz-repo-2/misc/python/materialize/cli/scratch/__main__.py", …
```

scratch: fix errors occurring with submodules

---

src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/compute-client/src/controller.rs
test/cluster/mzcompose.py

The flag `enable_compute_aggressive_readhold_downgrades` was meant to make it possible to disable aggressive readhold downgrading for MVs and revert back to the old behavior where read holds are kept at the current system time. As it turns out, the flag doesn't work as advertised because adapter doesn't install read policies for MVs anymore, so when you disable the flag, read frontiers of MVs and their inputs simply become stuck.
This is fixed in this PR by making adapter also check the feature flag and installing read policies if it is not set.
Note that adapter queries the flag's value from the compute controller, rather than the system config. That's to ensure we don't run into inconsistencies when the system config changes (i.e. someone runs `ALTER SYSTEM SET`). Changing the system …

compute: fix non-aggressive readhold downgrades

---

misc/python/materialize/checks/all_checks/alter_index.py
src/adapter-types/src/compaction.rs
src/adapter/src/catalog/state.rs
src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/environmentd/tests/sql.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/rbac.rs
src/sql/src/session/vars.rs
test/pgtest-mz/notice.pt
test/retain-history/mzcompose.py
test/sqllogictest/object_ownership.slt
test/sqllogictest/transactions.slt
test/testdrive/consolidation.td

We already supported `LOGICAL COMPACTION WINDOW` behind a feature flag, but it has bit-rotted over the years and needed to be plumbed through to a few more places.
Fixes: https://github.com/MaterializeInc/materialize/issues/24824
NOTE: we are still iterating on some questions like whether it's okay that retaining history on one object implicitly retains history on its dependencies. This PR just punts on that question.

Fix implementation of RETAIN HISTORY for indexes

---

ci/test/lint-main/checks/check-python-discouraged.sh

Follow-up to https://github.com/MaterializeInc/materialize/pull/24542.
Not sure if we want this or whether we have better ways to ensure this.

ci: check testdrive usages

---

src/postgres-util/src/desc.proto
src/postgres-util/src/desc.rs
src/postgres-util/src/schemas.rs
src/sql/src/pure/postgres.rs

When introducing col_num, we needed to introduce it as an option because existing sources did not have the field and it needed to be backfilled. However, any subsources that did not have this value backfilled by a migration would have errored as soon as it produced data (we would have seen the schemas as incompatible).
This has been the case for 11 months now, so I suggest that this is safe to remove because, for it to be an issue, customers would have had a source stuck in an errored state for that duration of time.
-

sql: remove Option wrapper around PostgresColumnDesc col_num

---

src/storage/src/sink/kafka.rs

Since #24864 has been fixed. via https://buildkite.com/materialize/nightlies/builds/6316#018d7940-69f7-4163-9359-6990c01ed1e0
-

storage: Remove rdkafka full queue workaround

---

src/environmentd/src/http/webhook.rs
test/testdrive/webhook.td

This PR implements support for newline delimited JSON for webhooks by using [`serde_json::StreamDeserializer`](https://docs.rs/serde_json/latest/serde_json/struct.StreamDeserializer.html). There are no syntax changes, newline delimited JSON will get parsed as an array by any `BODY FORMAT JSON` webhook request.
Newline delimited JSON are batches of JSON objects that are presented as individual objects separated by newlines. It's a fairly popular format is supported by other products like [DuckDB](https://duckdb.org/docs/extensions/json.html#json-table-functions) and [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/create-file-format#required-parameters).
Fixes https://github.com/MaterializeInc/materialize/issues/24913
- Adds support for newline delimited JSON to webhooks.

webhooks: Support `NDJSON`

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs

Refactor peek timestamps. The previous problems were:
- Optimize stats determined their own timestamp early on, and was possibly not the final timestamp. This doesn't matter hugely, but also duplicated a bit of work.
- We were not able to fill in the final timestamp until very late in LIR optimization, missing potential optimization opportunities and doing the scalar walk twice.
- It was generally confusing when timestamps were acquired because we also have realtime and linear timestamps.
Fix these by adding a new stage, and moving and
renaming other stages. The new stage does the
final timestamp determination and acquires read
holds. Now all three timestamp stages happen first (linearization, realtime recency, final
determination and read holds), then both optimizer stages, then final …

adapter: refactor peek timestamps

---

src/stash/src/postgres.rs
src/stash/src/tests.rs

Try harder to drop the debug stash factory and reenable the ignored test. Maybe this will let us see the underlying error for #24961.
- n/a

stash: improve debug factor dropping

---

doc/developer/project-lifecycle.md

Minor patches as I read through.

doc/developer: minor patches to project lifecycle

---

src/adapter-types/src/compaction.rs
src/adapter/src/coord.rs

Avoid passing around `Option<Timestamp>` in favor
of passing around a `CompactionWindow` and
teaching that type how to do various operations.
This allows DEFAULT_LOGICAL_COMPACTION_WINDOW_TS
to be referenced in only a single file.
- n/a

adapter: refactor to use compaction window type more

---

ci/nightly/pipeline.template.yml

ci: Run K8s recovery tests on aarch64 too

---

misc/python/materialize/checks/all_checks/alter_index.py

Follow-up to #24855
Seen in https://buildkite.com/materialize/nightlies/builds/6323#018d7a89-dce2-4f91-9761-9a2b47d5dffb
-

platform-checks: Fix retain history for indexes during upgrade

---

Cargo.lock
src/fivetran-destination/Cargo.toml
src/fivetran-destination/src/bin/mz-fivetran-destination.rs
src/fivetran-destination/src/crypto.rs
src/fivetran-destination/src/destination.rs
src/fivetran-destination/src/destination/config.rs
src/fivetran-destination/src/destination/ddl.rs
src/fivetran-destination/src/destination/dml.rs
src/fivetran-destination/src/error.rs
src/fivetran-destination/src/lib.rs
src/fivetran-destination/src/utils.rs
test/fivetran-destination/test-no-database/02-verify.json
test/fivetran-destination/test-no-permissions/02-verify.json

This PR refactors the error handling in the Fivetran Destination to do a few things:
1. We define a custom `OpError` that uses `thiserror` instead of returning `anyhow::Error`
2. Refactors the gRPC interface, "flattening" it a bit, to log on errors and automatically retry transient errors upto 3 times
Make our Fivetran Destination more resilient to temporary failures
- N/a

fivetran-destination: Refactor errors, automatically retry on some

---

Cargo.lock
src/fivetran-destination/Cargo.toml
src/fivetran-destination/build.rs
src/fivetran-destination/src/destination/config.rs

Since Fivetran's environment does not have a system CA bundle for us to reference.
* This PR fixes an issue reported by Fivetran.
- n/a

fivetran-destination: compile in CA bundle

---

misc/python/materialize/mzcompose/services/fivetran_destination_tester.py
src/fivetran-destination/src/destination.rs
src/fivetran-destination/src/destination/ddl.rs
src/fivetran-destination/src/destination/dml.rs
test/fivetran-destination/mzcompose.py

When responding to a `DescribeTableRequest` do not strip out the `_fivetran_*` system columns. Also update the Fivetran provider Docker image for testing to re-enable the truncate test.
Bug report from Emrah, https://materializeinc.slack.com/archives/C060KAR4802/p1707202803646169
- N/a

fivetran-destination: Small fix and test updates

---

test/canary-environment/models/loadgen/sales_product_product_category.sql
test/canary-environment/models/pg_cdc/wmr.sql
test/canary-environment/models/simple_table/table_mv.sql
test/canary-environment/models/tpch/tpch_q01.sql
test/canary-environment/models/tpch/tpch_q18.sql

The `materializedview` materialization name is deprecated and will be
removed in a future release of dbt-materialize. Please use
`materialized_view` instead, which is built-in from dbt v1.6:
{{ config( materialized = 'materialized_view' )}}
-

canary-environment: materialized_view has been renamed

---

ci/plugins/mzcompose/hooks/post-command
misc/python/materialize/checks/all_checks/jsonb_type.py
misc/python/materialize/checks/all_checks/nested_types.py
misc/python/materialize/checks/all_checks/top_k.py
test/persistence/user-tables/table-persistence-before-large-transaction.td
test/replica-isolation/mzcompose.py

Based on the failures seen in https://buildkite.com/materialize/coverage/builds/348
-

ci coverage: Make runs greener

---

src/environmentd/src/test_util.rs

Previously a race condition between a client and server drop could cause the connection half of the client to get `Some(Err(_))` messages, and then choose to panic on those. However errors can happen here when the server side goes away, and it's not necessarily panic-worthy (and perhaps should never panic). If the server's ListenHandle dropped before the connection noticed that the client dropped, this would cause panics.
This was happening for me locally. I'm confused why it is not happening in CI.
- n/a

environmentd: improve test connection polling

---

src/persist-client/src/fetch.rs

Instead of collecting an iterator into a `Vec` and then handing it to `Antichain::from`, we can construct the Antichain directly from the iterator. I did a quick audit and none of these seem to be on a particularly hot path, but this is so easy that may as well.
h/t Moritz for the idea
-

persist: remove some unnecessary intermediate Vecs

---

misc/python/materialize/cli/run.py

This is needed when run.py does the --reset stuff into cockroachdb, where some of the .psqlrc commands might not apply cleanly and leave lots of useless error messages in the console.
- n/a

misc: disable .psqlrc in python-invoked psql

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/explain/mod.rs
src/adapter/src/explain/optimizer_trace.rs
src/adapter/src/optimize/index.rs
src/adapter/src/optimize/materialized_view.rs
src/adapter/src/optimize/peek.rs
src/adapter/src/optimize/subscribe.rs
src/repr/src/explain/mod.rs
src/repr/src/explain/tracing.rs
src/sql-parser/src/ast/defs/statement.rs
src/transform/src/dataflow.rs
src/transform/tests/test_runner.rs
src/transform/tests/test_transforms.rs
test/sqllogictest/explain/physical_plan_as_text.slt

The code is littered with instances of the same pattern:
```rust
// Collect the list of indexes used by the dataflow at this point
let used_indexes = {
let df_desc = global_mir_plan.df_desc();
let df_meta = global_mir_plan.df_meta();
UsedIndexes::new(
df_desc
.index_imports
.iter()
.map(|(id, _index_import)| {
(*id, df_meta.index_usage_types.get(id).expect("prune_and_annotate_dataflow_index_imports should have been called already").clone())
})
.collect(),
)
};
```
Simplify the code of the various `sequence_` methods that currently have this code duplicated and move it to its own method. In addition, change the `OptimizerTrace` implementation so `UsedIndexes` structs can be directly recorded there, which should alleviate the need to pass `used_indexes: UsedIndexes` parameters around.
* …

explain: move `used_indexes` computation deeper in the call stack

---

src/compute-client/src/controller/instance.rs
test/testdrive/replica-targeting.td

This PR changes how the compute controller handles frontier updates for replica-targeted subscribes. Previously, each replica could advance the global frontier of a subscribe, targeted or not. With this commit, only the targeted replica can cause a global frontier advancement.
This fixes the following error scenario:
* A non-targeted replica advances to the empty frontier.
* The compute controller downgrades the subscribe's global frontier to the empty frontier.
* The compute controller sends an `AllowCompaction([])` command to all replicas.
* The targeted replica receives the `AllowCompaction([])` and considers the subscribe dropped.
* The compute controller never receives a subscribe response from the targeted replica.
Fixes #24981
- N/A

compute: fix advancement of replica-targeted subscribe frontiers

---

test/sqllogictest/github-24506.slt

This adds a dedicated SLT test to avoid the regression of #24506.
I confirmed manually that this SLT fails (with values `(1, 11)`) at 62c6f9dd899e0d722f6fd7177892504fab6defe2 (right before @frankmcsherry fix) but succeeds with his fix at 626ed59b51fa95bc0dd39c25c868dc992ac079e4.
This is slightly redundant with `with_mutually_recursive.slt`, but: belt and suspenders.
Test for the fix to #24506, missing test from #24728.
-

test: add SLT test case to avoid regression of #24506

---

Cargo.lock
src/persist-cli/Cargo.toml
src/persist-cli/src/maelstrom/services.rs
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/timestamp-oracle/src/lib.rs

This hooks up the production impl of ShareableTimestampOracle to the persist-txn maelstrom tests. It also adds an in-mem impl of that trait for convenience when running a single-node test.
It should be possible to also make the MaelstromOracle implement this trait (I think I have it working locally) but it's just tricky enough that I didn't feel great about it and seems like that doesn't need to hold up this PR (we just lose the fancy graphs).
-

persist-txn: use real timestamp oracle in maelstrom tests

---

doc/user/content/sql/system-catalog/mz_internal.md
src/adapter/src/catalog/builtin_table_updates.rs
src/catalog/src/builtin.rs
test/sqllogictest/autogenerated/mz_internal.slt
test/testdrive/mz-kafka-sources.td

Closes #24996
The fingerprint of the table is changing, so this change is backward compatible.
- add `topic` column to `mz_internal.mz_kafka_sources`

storage: add topic column to mz_kafka_sources

---

src/persist-txn/src/operator.rs

Instead of emitting the raw txns shard data, switch to a new protocol
based on mapping a "physical" upper to the "logical" upper that is known
to have exactly the same contents. Ideally, this would be exactly the
existing mz remap protocol (which has a nice formal definition), but we
can't quite get there yet, so that's left as a TODO.
The immediate motivation is to set up using TxnsRead in the first
operator (in a followup PR). This will greatly reduce our sensitivity to
things like the compaction of the txns shard because we'll go from one
(filtered) txns shard subscription per table input in a dataflow to one
(unfiltered) txns shard subscription total.
However, this does get us an immediate benefit of moving the
`unblock_reads` call from the second operator (which is run on each …

persist-txn: switch to a new operator protocol for lazy

---

Cargo.lock
Cargo.toml
src/ccsr/Cargo.toml
src/ccsr/src/tls.rs
src/ccsr/tests/client.rs
src/storage-types/Cargo.toml
src/storage-types/src/connections.rs
src/tls-util/src/lib.rs
src/workspace-hack/Cargo.toml
test/mysql-cdc/15-create-connection-tls.td
test/mysql-cdc/mzcompose.py

Implements the TLS options for the MySQL Source in the `CREATE CONNECTION` command:
```
CREATE CONNECTION ... TO MYSQL
[SSL MODE  <DISABLED|REQUIRED|VERIFY_CA|VERIFY_IDENTITY>]
[SSL CERTIFICATE AUTHORITY <server ca>]
[SSL CERTIFICATE <client cert>]
[SSL KEY <client key>]
```
NOTE:
To implement this without having to temporarily create files for the CA cert and client cert/keys, I had to fork `mysql_async` to add support for providing the cert/key values directly: https://github.com/blackbeam/mysql_async/pull/288
That PR is now the latest on the `master` branch of our fork repo: https://github.com/MaterializeInc/mysql_async
Part of the work in https://github.com/MaterializeInc/materialize/issues/15901
There was a convenient function in `src/ccsr/src/tls.rs` for generating a PKCS12 archive …

storage: MySQL Source TLS/SSL support

---

src/adapter/src/catalog/state.rs
src/adapter/src/coord/sequencer/inner.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/create
src/sql-parser/tests/testdata/ddl
src/sql/src/normalize.rs
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
test/retain-history/mzcompose.py

This adds `RETAIN HISTORY` for tables, which has the same semantics as it does for MVs, sources, indexes, etc.
Fixes #25033

Add `RETAIN HISTORY` for tables.

---

Cargo.lock
src/ccsr/src/tls.rs
src/mysql-util/Cargo.toml
src/mysql-util/src/lib.rs
src/mysql-util/src/tunnel.rs
src/sql/src/plan/statement/ddl/connection.rs
src/storage-types/src/connections.rs
src/storage/src/source/mysql/replication.rs
src/tls-util/src/lib.rs
test/ssh-connection/mysql-source-after-ssh-failure.td
test/ssh-connection/mysql-source-after-ssh-restart.td
test/ssh-connection/mysql-source.td
test/ssh-connection/mzcompose.py

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/24923 and https://github.com/MaterializeInc/materialize/issues/25027
I added some tests to validate SSH tunnel connections, but for PrivateLink we've decided to punt on adding automated tests until after Private Preview (prioritized behind other more important tasks) ([discusson](https://www.notion.so/MySQL-Source-Prototype-8838b49eb2124e3580a4e9922761d423?d=afa0c42c2a61400180cdb82ce90874a1&pvs=4#5ab6ed833c5244739c2aa280c918c379)).
You'll also notice that I had to create a wrapper `MySqlConn` around `mysql_async::Conn` so that we can maintain a reference to the handle of a possible SSH tunnel associated with the connection. This seemed more elegant than spawning a tokio task to keep the …

storage: SSH Tunnel & PrivateLink support for MySQL connections

---

src/kafka-util/src/client.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/names.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/ddl/connection.rs
src/sql/src/plan/with_options.rs
src/sql/src/session/vars.rs
src/storage-types/src/connections.rs
test/cloudtest/test_privatelink_connection.py
test/testdrive/connection-alter.td
test/testdrive/connection-create-drop.td

add feature to allow for default aws privatelink
setting for kafka connections. This will set a
static host re-rewite for all kafka brokers while
maintaining their ports. The connection and port
specified in the default connection will be used
as the bootstrap server.
adjusts parsers to enable top level privatelink
to take in a port
adds static host rewrite option for kakfa
adjusts kafka source connections to use
privatelink connection if specified
adds tests to validate new syntax and
ensure new option conflicts are respected
https://github.com/MaterializeInc/materialize/issues/24712
-

feature kafka connection default aws privatelink

---

misc/python/materialize/mzcompose/__init__.py
src/persist-client/src/cfg.rs
src/persist-client/src/internal/machine.rs
src/persist-txn/src/operator.rs
src/persist-txn/src/txns.rs
src/persist/src/retry.rs

We currently have a bit of unresolvable tension with our retry tunings between the following:
- When a shard is not advancing (the cluster maintaining it is down, rehydrating, etc) and so the upper is not doing its normal pattern of advancing once per second, minimize the traffic of CRDB retries.
- When pubsub fails, continue to serve queries promptly, ideally within a few hundred ms.
This adds the ability to produce the following set of retry timings, which _does_ satisfy both of the above: 1200ms, 100ms, 200ms, 400ms, ...
I haven't tested this particularly extensively yet, wanted to get your thoughts on the approach before I spent too much more time on it.
-

persist: add flexibility to persist retry timings

---

test/kafka-resumption/mzcompose.py
test/kafka-resumption/sink-queue-full/cleanup.td
test/kafka-resumption/sink-queue-full/during.td
test/kafka-resumption/sink-queue-full/setup.td
test/kafka-resumption/sink-queue-full/toxiproxy-close-connection.td
test/kafka-resumption/sink-queue-full/toxiproxy-limit-connection.td
test/kafka-resumption/sink-queue-full/toxiproxy-restore-connection.td
test/kafka-resumption/sink-queue-full/toxiproxy-timeout-hold.td
test/kafka-resumption/sink-queue-full/toxiproxy-timeout.td
test/kafka-resumption/sink-queue-full/verify-success.td

To trigger queue full in sink
Verified on top of #24360 that this would have caught the error
Fixes: #24936
-

kafka-resumption test: Add workflow with large amount of data

---

misc/python/materialize/mzexplore/common.py
src/adapter/src/catalog/state.rs
src/adapter/src/coord.rs
src/adapter/src/coord/indexes.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/optimize/copy_to.rs
src/adapter/src/optimize/dataflows.rs
src/adapter/src/optimize/index.rs
src/adapter/src/optimize/materialized_view.rs
src/adapter/src/optimize/mod.rs
src/adapter/src/optimize/peek.rs
src/adapter/src/optimize/subscribe.rs
src/repr/src/explain/mod.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/explain
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/rbac.rs
test/sqllogictest/explain/enable_eager_delta_joins.slt
test/sqllogictest/explain/replan_catalog_items.slt

I don't think we have an issue for that, but currently there is no way to inspect how a plan would differ if we enable an optimizer feature flag and then restart `environmentd`. A naive solution might be to lookup the `CREATE` statement for a catalog item from the catalog and then run
```sql
EXPLAIN CREATE <catalog item>
```
However, this doesn't work because:
1. The catalog state considered when we run `EXPLAIN CREATE <catalog item>` might be different from the catalog state available when re-planning during `bootstrap`.
2. Our external tooling soon won't be able to lookup valid `CREATE` statements for all catalog items because they are not redacted (and the redacted versions are not valid SQL).
To solve both issues we introduce …

Support `EXPLAIN REPLAN [INDEX | MATERIALIZED VIEW]`

---

src/stash/src/tests.rs
src/stash/src/transaction.rs

test_stash_batch_large_number_updates was added in dad4ed8c7124f5a5dd2e47f3597c7f98004407a0 to test the max number of args in a CRDB update statement. Previously, we were testing a number of updates that was order of magnitudes larger than the max number of args in a CRDB update statement. That caused the test to be slow and sometimes hang forever. This commit updates the test to lower the number of updates while still ensuring that we end up with more than the max number of args.
Works towards resolving #25003

stash: Speed up large batch test

---

misc/python/materialize/checks/all_checks/create_table.py

Seen in https://buildkite.com/materialize/nightlies/builds/6354#018d8802-fd33-4d90-abdc-6d905929f57a
-

platform-checks: Increase timeout for migration test

---

misc/python/materialize/mzcompose/__init__.py
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars.rs
test/testdrive/cc_cluster_sizes.td

Turns out it was redundant with the existing allowed_cluster_replica_sizes feature flag.
- n/a

sql: remove enable_cc_cluster_sizes feature flag

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/open.rs
src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/consistency.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/timeline.rs
src/controller/src/clusters.rs
src/controller/src/lib.rs
src/environmentd/src/lib.rs
src/storage-controller/src/lib.rs

Move to some new standards:
- `tracing::instrument` -> `instrument`
- omit `level = "info"` as it's the default
- improve names
Add INFO tracing to most queries. Plans that spawn tasks (create source, select, create index/mv) partially work. They will be hooked up to their parent in a later PR.
- n/a

adapter: improve various tracing

---

test/fivetran-destination/test-multi-table/02-verify.td

Turns out the value passed to `_fivetran_synced` to different operations but within a single test run could be the same, which breaks some current assertions.
Fix main
- N/a

fivetran-destination: Deflake recently added test

---

ci/mkpipeline.py
ci/release-qualification/pipeline.template.yml

and test rollbacks with 0.86.1
-

ci: Don't demand timeouts in trigger jobs

---

src/sql/src/pure.rs
src/storage-types/src/sources/mysql.proto
src/storage-types/src/sources/mysql.rs
src/storage/src/source/mysql/replication.rs

Fixes https://github.com/MaterializeInc/materialize/issues/24982
See the attached issue for a description of the correctness bug. @petrosagg I _think_ this addresses the issue but I may have missed something important so would appreciate your close eye!
I'm also not sure how to test this but all the existing mysql source tests pass, so we can at least confirm it didn't break the nominal case.
-

storage/mysql: Fix correctness issue when snapshot is interrupted

---

misc/python/materialize/version_list.py

This adds an ignore to the feature benchmark for https://github.com/MaterializeInc/materialize/pull/24918.
Needed on main once https://github.com/MaterializeInc/materialize/pull/25104 lands.

feature benchmark: add ignore for persist-txn message count change

---

misc/python/materialize/checks/all_checks/peek_persist.py

Seen in migration in https://buildkite.com/materialize/nightlies/builds/6361#018d89fc-ed03-4181-8f76-b7d5075c90f7
-

platform-checks: Increase timeout in peek_persist

---

misc/python/materialize/checks/scenarios_persist_txn.py

platform-checks: No shadow catalog in persit-txn restart tests

---

src/adapter/src/command.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/statement_logging.rs
src/environmentd/src/http/sql.rs
src/pgwire/src/protocol.rs

Previously, the adapter could either send the client an Ok(ExecuteResponse::Canceled) response or an
Err(AdapterError::Canceled) response. After
aa34c5b117e1c363fb0c6f1b0a724fe9f0775df7 the
Ok(ExecuteResponse::Canceled) is never used so this commit removes it.
Looking through the code it seems like Ok(ExecuteResponse::Canceled) and Err(AdapterError::Canceled) are handled identically. However, when querying Materialize through rust-postgres, when Materialize sends an Ok(ExecuteResponse::Canceled) response the rust client receives an Ok(_) result. When Materialize sends an Err(AdapterError::Canceled) response the rust client receives an Err(_) result. Err(_) is the correct result since canceling a statement causes it to have no effect and matches the PostgreSQL result. For example, imagine …

adapter: Remove Canceled execute response

---

src/fivetran-destination/src/destination/config.rs
src/fivetran-destination/src/destination/ddl.rs
src/fivetran-destination/src/destination/dml.rs

We set up our Fivetran destination for the first time and found a few small issues, which this PR addresses.
1. The permissions check did not consider superuser status.
2. `TruncateRequest`s can occur even if the table hasn't been created yet, so we need to no-op in that scenario.
3. The `_fivetran_deleted` column is always required, but not always provided, so we make sure to include it when missing.
Also if we ever get an `AlterTableRequest` we make sure to include the debug representation in the error message, so it's easier to debug.
Note: I tried to add tests for these scenarios but it's not possible at the moment. The tester seemed to ignore truncate requests for tables that didn't exist and the tester always provides the `_fivetran_deleted` columns I couldn't exercise either of …

fivetran-destination: Fix issues we found in dogfooding

---

src/expr/src/explain/mod.rs
src/expr/src/linear.rs
src/expr/src/relation/canonicalize.rs
src/expr/src/relation/join_input_mapper.rs
src/expr/src/relation/mod.rs
src/expr/src/scalar/mod.rs
src/sql/src/plan/explain/mod.rs
src/transform/src/dataflow.rs
src/transform/src/demand.rs
src/transform/src/fusion/filter.rs
src/transform/src/fusion/join.rs
src/transform/src/fusion/map.rs
src/transform/src/fusion/negate.rs
src/transform/src/fusion/project.rs
src/transform/src/fusion/reduce.rs
src/transform/src/fusion/top_k.rs
src/transform/src/literal_constraints.rs
src/transform/src/literal_lifting.rs
src/transform/src/movement/projection_lifting.rs
src/transform/src/movement/projection_pushdown.rs
src/transform/src/non_null_requirements.rs
src/transform/src/nonnullable.rs
src/transform/src/normalize_lets.rs
src/transform/src/predicate_pushdown.rs
src/transform/src/redundant_join.rs

An attempt to minimize postorder traversal requiring recursion, to reduce the amount of potentially erroring traversals.
The methodology here is to identify recursive traversals that could be converted to iterative traversals, by shifting from post-order traversal to pre-order traversal. Many traversals are fine as pre-order, for example traversal that count the number of certain AST nodes, or ones that want to rewrite column identifiers, etc. Others are not obviously fine, for example when replacing some AST nodes by others (where pre- vs post-order determines whether the traversal should enter the substituted AST node). I made an effort to avoid swapping out post-order traversal in cases where I could not tell whether it would be a correct change, but I may have made errors and we …

Minimize postorder traversal

---

doc/user/content/sql/create-source/webhook.md
doc/user/layouts/partials/sql-grammar/create-source-webhook.svg
doc/user/sql-grammar/sql-grammar.bnf

Add docs for https://github.com/MaterializeInc/materialize/pull/24753
Will not merge until that PR gets released to users.
- Documents the new `BODY FORMAT JSON ARRAY` for webhook sources

docs: Add `BODY FORMAT JSON ARRAY`

---

src/storage/src/source/mysql.rs
src/storage/src/source/mysql/snapshot.rs
test/mysql-cdc/mzcompose.py
test/mysql-cdc/schema-restart/after-restart.td
test/mysql-cdc/schema-restart/before-restart.td

* This PR adds a known-desirable feature. Fixes #25091 
This is a basic check to validate the mysql table schemas remain consistent between purification and snapshot time in the source.
I expect the test will be refactored once we also detect DDL changes in the replication stream (my next task).
We also plan to implement a check to detect backwards-compatible schema changes and avoid erroring (in `verify_schema`), but I wanted to implement that logic at a future time. 
-

storage/mysql: Detect schema changes before performing snapshot and put subsource into error state

---

src/storage/src/source/mysql/snapshot.rs

This PR removes the coordination of the snapshot phase and makes each worker independently lock and snapshot its assigned tables. This has the effect of simplifying the code and potentially being more gentle to the database by requiring locks of fewer tables for less amount of time at any given point.
I also added a whole bunch of additional documentation on the mechanics of how the snapshot phase works.
-

storage/mysql: leaderless snapshot

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/optimize/copy_to.rs
src/adapter/src/optimize/materialized_view.rs
src/adapter/src/optimize/mod.rs
src/adapter/src/optimize/peek.rs
src/adapter/src/optimize/subscribe.rs
src/adapter/src/optimize/view.rs
src/adapter/src/session.rs

Simplify `coord::sequencer::inner::peek`, `optimize::peek`, and `optimize::copy_to`.
Simplify various code bits unblocked by the reorganization of the `PeekStage` variant in #24567. More specifically, this PR achieves he following:
1. Fuse the adjacent `PeekStageOptimizeMir` and `PeekStageOptimizeMir` stages into a single stage `PeekStageOptimize` that runs the entire optimizer pipeline for `COPY TO` and `SELECT` statements off-thread.
2. Move timestamp resolution earlier in the `peek` and `copy_to` optimizer pipelines (after `LocalMirPlan` creation). ~In particular, this entails that `prep_relation_expr` and `prep_scalar_expr` need to be called only once~ (reverted the last bit for now because of `*.slt` failures).
3. Fuse the adjacent `LocalMirPlan ⇒ …

adapter: simplify `peek` and `copy_to` sequencing and optimization

---

src/catalog-debug/src/main.rs

Previously, the catalog-debug tool would hard-code replica sizes of `1` in multiple places for the upgrade checker. This isn't always valid because the size `1` is not valid for all environments (really for any prod environments). This commit removes these hard coded values and replaces them with more sensible values.
`default_cluster_replica_size` is only used for initializing new environments. Specifically it is used for the size of the `quickstart` cluster. The upgrade checker should never be used in non-existent environments. So this commit replaces the size with the string "DEFAULT CLUSTER REPLICA SIZE IS ONLY USED FOR NEW ENVIRONMENTS", so that we'll get a meaningful error message if the value is ever used in the upgrade checker.
`builtin_cluster_replica_size` is used as the size …

catalog-debug: Remove hard coded replica sizes

---

Cargo.lock
Cargo.toml
src/mysql-util/src/tunnel.rs
src/sql/src/plan/statement/ddl/connection.rs
src/workspace-hack/Cargo.toml
test/ssh-connection/mysql-source-ssl.td
test/ssh-connection/mzcompose.py

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/25048
This is now possible since I made the corresponding change to our fork of `mysql-async` - the upstream PR is here: https://github.com/blackbeam/mysql_async/pull/289
I did add tests to validate SSL when using an SSH tunnel, but I still couldn't get the verify_identity test to work with the auto-generated mysql certs. At some point I'll probably switch to generating the certs ourselves and then make that test to work.
-

storage/mysql: Allow SSL MODE verify_identity with SSH and Privatelink tunnels

---

src/fivetran-destination/src/destination/ddl.rs
src/fivetran-destination/src/error.rs
test/fivetran-destination/test-alter-table-no-op/00-README
test/fivetran-destination/test-alter-table-no-op/01-in_order.json
test/fivetran-destination/test-alter-table-no-op/02-out_of_order.json

This PR changes `DescribeTableRequest`s to make sure the list of columns we return is in the order that they exist on the table itself. It also adds no-op support to `AlterTableRequest`.
When testing we found that Fivetran would send us `AlterTableRequest`s that appear to be a no-op. They're only supposed to send us an `AlterTableRequest` if the table returned from a `DescribeTableRequest` doesn't match their expected state. Our current describe table API doesn't sort the columns, and in at least one example returned a different ordering than what was provided in the `AlterTableRequest`.
- N/a

fivetran-destination: Order columns in describe, handle no-op alter tables

---

Cargo.lock
Cargo.toml

There is a cap of 128 frames in our jemalloc profiling, so switching this impl from recursive to iterative _greatly_ increases the usefulness of PolarSignals memory profiles for looking at where parquet allocations are coming from.
Example (not directly comparable):
- [before](https://pprof.me/39589b07486ad05625193a74ed8a2a02)
- [after](https://pprof.me/314438fae57a108439222bbfc23254eb)
-

persist: patch in arrow2 iterative next impl

---

src/adapter/src/coord/sequencer/inner.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs
test/testdrive/materialized-view-refresh-options.td

This PR introduces warmup capabilities held by the controller for compute collections. These capabilities hold back their collections' read frontiers, and therefore the as-ofs of new dataflows installed for collections, to a time that is immediately available in all inputs.
This is done to enable warming up dataflows, particularly REFRESH materialized views that have their next refresh time in the future. By holding back the as-ofs of dataflows we ensure that they can begin hydration immediately and don't have to wait for a future time (like the next refresh time) to do so.
This solves the same issue as https://github.com/MaterializeInc/materialize/pull/24979 and https://github.com/MaterializeInc/materialize/pull/25019, but with the benefit that we don't need to introduce a notion of …

Enable warm up of REFRESH materialized views (warmup capabilities)

---

src/sql-parser/src/parser.rs
src/sql/src/plan/statement/ddl.rs
test/testdrive/kafka-json-sinks.td
test/testdrive/source-format-json.td

This type of format was added for webhook sources but the planner accidentally accepts it for sources and sinks even though it is ignored. This PR changes the planner to error on these statements so that when we eventually support it it's not a breaking change. 
-

storage: disallow `JSON ARRAY` format in sources

---

src/repr/src/strconv.rs
test/sqllogictest/float.slt

This commit fixes float parsing of zero so that `0.` and `.0` are valid.
Fixes #22748
- Fix float parsing of certain zero values such as `0.` and `.0`.

sql: Fix float parsing of zero

---

src/environmentd/src/bin/environmentd/main.rs
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/Cargo.toml
src/persist-client/benches/benches.rs
src/persist-client/src/async_runtime.rs
src/persist-client/src/cache.rs
src/persist-client/src/cfg.rs
src/persist-client/src/cli/admin.rs
src/persist-client/src/cli/inspect.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/read.rs

This PR makes the number of worker threads we create for an `IsolatedRuntime` configurable, with the default being the number of threads on a machine. Currently the only place we use a non-default value is in environmentd, which can be configured via a CLI argument.
The goal of this change is to prevent the `IsolatedRuntime` from starving other critical tasks if it gets a ton of work pushed onto it. For example, if `environmentd` is asked to do compaction work we don't want to pin its CPU to 100% and starve the Coordinator thread.
Note: this does not limit the number of threads the runtime will create for [blocking work](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.max_blocking_threads). The `IsolatedRuntime` does not use `spawn_blocking`.
We saw an instance of …

persist: Make number of threads in `IsolatedRuntime` configurable

---

ci/test/pipeline.template.yml
misc/python/materialize/checks/all_checks/error.py

Seen in https://buildkite.com/materialize/tests/builds/75317, docker seems to be slower at fetching today
-

ci: Bump timeouts

---

doc/user/layouts/shortcodes/json-parser.html

Adding a small fix to the JSON widget as @morsapaes caught the following bug:
>  The JSON parsing widget currently chokes on `null` (forces you to correct to "null", but the error is unintuitive).

Doc: Handle nulls in JSON widget

---

src/sql/src/session/vars.rs

Local executions of Mz were still using idle arrangement merge effort instead of the new proportionality-based merging.
This PR brings changes the default configuration to bring it in line with production and CI.
* This PR changes a configuration default.
- N/A

vars: disable idle arrangement merge effort by default

---

misc/python/materialize/version_list.py

Assuming the following is correct:
> ["persist-txn: switch to a new operator protocol for lazy"](https://github.com/MaterializeInc/materialize/pull/24918)
> * was introduced in 0.87.0 with [b648576b](https://github.com/MaterializeInc/materialize/commit/b648576b52b8ba9bb3a4732f7022ab5c06ebed32)
> * was reverted in 0.87.1 with [c0384b20](https://github.com/MaterializeInc/materialize/commit/c0384b20a40f6c406c38a4722db6ea88e8e28430)
> * was not reverted on main
> * so that 0.88.0 will be the first version shipping this functionality
(https://materializeinc.slack.com/archives/C01LKF361MZ/p1707744548965469?thread_ts=1707727135.871749&cid=C01LKF361MZ)

feature benchmark: update ignore entry to account for PR#24918 being reverted in 0.87.1

---

ci/nightly/pipeline.template.yml

Since we currently have x86-64 and aarch64 (unfortunately)
-

ci: Group builds in nightly pipeline

---

misc/python/materialize/cli/ci_logged_errors_detect.py

Only panics with this layout are matched:
```
launchdarkly-materialized-1  | thread 'coordinator' panicked at src/catalog/src/durable/impls/stash.rs:1201:13:
launchdarkly-materialized-1  | global timestamp must always go up
```
Additionally supported layouts:
```
[pod/environmentd-0/environmentd] thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-04d4e39675bda911c-1/materialize/tests/src/storage-controller/src/lib.rs:1468:17:
[pod/environmentd-0/environmentd] Unknown collection identifier u2082
```
(seen in `kubectl-get-logs-previous.log` of [builds/6376](https://buildkite.com/materialize/nightlies/builds/6376#018d8df9-aa16-429d-9801-67a596dfdf8f))
and
```
thread 'coordinator' panicked at 'forced panic', …
```

ci: improve panic matching

---

src/catalog-debug/src/main.rs
src/catalog/src/durable/debug.rs

This commit adds the --ignore and --ignore-large-collections command line arguments to the dump command in the catalog debug tool. Often times when debugging, the user only cares about a handful of collections, and the other collections can be annoying noise. The --ignore flag allows the user to specify collections to ignore. The --ignore-large-collections flag is a convenience flag to ignore both audit_log and storage_usage, which are both extremely large and usually not helpful.

catalog-debug: Add ignore cmnd line args to dump

---

src/prof-http/templates/prof.html

Joe pointed out that nowadays, the hit from symbolization can be significantly higher than 1G which it was int he past.

Update profiler warning.

---

src/ore/src/lgbytes.rs
src/ore/src/lib.rs

To set up moving allocations from our s3 library into lgalloc, we introduce a copy of `bytes::Bytes` backed by lgalloc but with the same API. Crucially, this also implements `bytes::Buf`. We could expand the subset of the `bytes::Bytes` API that this implements, but start with the bare minimum for doing something useful.
If we end up needing to fork our s3 client to push usage of this earlier, we'll likely need to pull this out into a separate crate, but for now start it in mz_ore.
This is intentionally not used anywhere yet. It's pulled into a separate PR to keep code reviewer responsibilities less muddled.
Touches #23332
-

ore: add a clone of bytes::Bytes but backed by lgalloc

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select

Unless it is followed by a `(` token, in which case it is an explicit row constructor. The new behavior matches PostgreSQL.
Fix #23827.
- Allow using `row` in scalar expression contexts outside of explicit row constructors.

sql-parser: allow using `row` in expressions

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs

Make a new requirement that all stages but the last must return a JoinHandle<Stage> or an ExecuteResponse. This allows us to remove the loop (since it will never trigger) currently in use in all of the sequence stage fns, and instead *only* have the final response or the next stage that can be sent as a message.
Because of this, we can now omit a lot of passing of the vars down through the various inner stage fns, and instead concentrate those in a common handling function.
Additionally, plumb through spans and easy tracing for nicely formatted trees.
Start with CREATE VIEW for now as the smallest possible demonstration.
- n/a

adapter: general framework for off thread coordinator stages and spans

---

test/cluster/mzcompose.py
test/feature-benchmark/mzcompose.py
test/parallel-workload/mzcompose.py
test/platform-checks/mzcompose.py
test/scalability/mzcompose.py
test/upgrade-matrix/mzcompose.py

There are some tests that cannot use the shadow catalog for various
reasons. Previously, those tests defaulted to using the stash catalog,
because that is the catalog used in production. We are actively working
on switching the stash catalog to the persist catalog in production,
and we're not changing the stash catalog at all. Therefore, we'd prefer
to test the persist catalog over the stash catalog.
Works towards resolving #24218
Update tests

test: Change default catalog to persist

---

ci/nightly/pipeline.template.yml

Disabling RQG WMR until https://github.com/MaterializeInc/materialize/issues/24904 is fixed.

ci: temporarily disable rqg-wmr

---

misc/python/materialize/checks/all_checks/array_type.py
misc/python/materialize/checks/all_checks/boolean_type.py
misc/python/materialize/checks/all_checks/create_table.py
misc/python/materialize/checks/all_checks/error.py
misc/python/materialize/checks/all_checks/float_types.py
misc/python/materialize/checks/all_checks/insert_select.py
misc/python/materialize/checks/all_checks/jsonb_type.py
misc/python/materialize/checks/all_checks/large_tables.py
misc/python/materialize/checks/all_checks/nested_types.py
misc/python/materialize/checks/all_checks/peek_persist.py
misc/python/materialize/checks/all_checks/ranges.py
misc/python/materialize/checks/all_checks/sink.py
misc/python/materialize/checks/all_checks/text_bytea_types.py
misc/python/materialize/checks/all_checks/top_k.py
test/platform-checks/mzcompose.py

Mostly for migration tests, see for example https://buildkite.com/materialize/nightlies/builds/6417#018da273-ec60-42c9-bb85-449500a48acd
-

platform-checks: Set higher statement_timeout

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select

sql-parser: teach join constraints about AS OF

---

misc/python/materialize/version_list.py
src/persist-txn/src/operator.rs

Introduce a performance optimization that skips re-emitting
`DataRemapEntry` when only the logical_upper has changed, instead
indicating that by the frontier progress of the Stream.
This fixes a notable regression in the number of messages sent in
various Feature Benchmark scenarios.
-

persist-txn: reduce messages sent by new operator protocol

---

src/adapter/src/coord/sequencer/cluster.rs
test/sqllogictest/cluster.slt

This adds a check that users cannot create replicas overriding the internal and billed-as properties.
Fixes https://github.com/MaterializeInc/accounts/issues/50
-

Validate replicas of unmanaged clusters for internal/billing

---

Cargo.lock
src/catalog-debug/Cargo.toml
src/catalog-debug/src/main.rs

catalog-debug: Add logging

---

ci/nightly/pipeline.template.yml
ci/qa-canary/pipeline.template.yml

ci: Put QA Canary Load into its own pipeline

---

test/cluster/mzcompose.py

See https://github.com/MaterializeInc/materialize/issues/25214
-

cluster tests: Disable test-compute-controller-metrics

---

Cargo.lock
misc/python/materialize/mzcompose/__init__.py
src/clusterd/src/bin/clusterd.rs
src/controller-types/src/lib.rs
src/controller/src/clusters.rs
src/ore/src/bytes.rs
src/ore/src/lgbytes.rs
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/src/cache.rs
src/persist-client/src/cfg.rs
src/persist-client/src/cli/args.rs
src/persist/Cargo.toml
src/persist/src/cfg.rs
src/persist/src/mem.rs
src/persist/src/metrics.rs
src/persist/src/s3.rs
src/sql/src/plan/statement/ddl.rs

This will reduce rehydration memory spikes by moving the data fetched
from s3 into file-backed mapped allocations.
Ideally, we'd read directly from the network into these allocs, but that
requires maintaining a fork of our s3 client library and/or hyper. We
appear to get a meaningful improvement by moving the data in at the very
first place it touches mz code, and that's a much easier place to start.
It would probably be more lgalloc-friendly to copy in a full s3 blob at
the end of the fetch, but initial testing on a staging env indicates
this is measurably worse than moving in each s3 multipart as it comes
in.
On its own, this seems to be sufficient to make parquet allocations the
limiting factor in rehydration spikes in practice. However, we may want
to supplement it with a semaphore …

persist: use lgalloc to back data fetched from s3

---

src/catalog/src/memory/objects.rs
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/storage-controller/src/lib.rs
src/storage-types/src/sources.proto
src/storage-types/src/sources.rs
src/storage/tests/setup.rs

This `source_imports` field on `IngestionDescription` was unused––it occasionally confuses me (and maybe others), so remove it for the time being.
Note that this does not preclude this concept from being reintroduced as we e.g. unify the description of how storage dataflows run with compute.
-

storage: remove unused source_imports on IngestionDescription

---

src/pgtz/src/timezone.rs
test/pg-cdc/pg-cdc.td
test/sqllogictest/dates-times.slt
test/sqllogictest/range.slt

PG allows errant punctuation marks in the timezone field, just as it allows them in the timestamp string itself. We didn't support that, it turns out.
This PR fixes a recognized bug. Discovered by a customer ([Slack](https://materializeinc.slack.com/archives/C03REC5MEKU/p1707857381021219)).
- Fix a bug that potentially prevented `timestamp with timezone data` from being correctly parsed when ingested through PostgreSQL sources.

pgtz: allow errant punctuation as delimiters when tokenizing timezones

---

doc/user/README.md
doc/user/assets/sass/_content.scss
doc/user/data/sql_funcs.yml
doc/user/layouts/shortcodes/fnlist.html
doc/user/layouts/shortcodes/if-released.html
doc/user/layouts/shortcodes/if-unreleased.html
doc/user/layouts/shortcodes/warn-if-unreleased-inline.html
doc/user/layouts/shortcodes/warn-if-unreleased.html

We've had a lot of trouble lately with folks either:
1. Not writing documentation for their changes.
2. Writing documentation for their changes, but merging it in the PR that implements that change, before the change has rolled out to production.
Attempt to solve both of those problems by introducing new rollout shortcodes. These shortcodes add a user-visible warning that indicates a feature may not yet be available. The warning automatically disappears when the version containing the feature is marked as released.
This will "bless" the approach of updating docs for a change in the same PR that implements the change. This hopefully encourages developers to write more documentation, without confusing end users with documentation for features that do not yet exist.
* This PR improves the …

doc/user: add shortcodes for in-progress rollouts

---

src/environmentd/tests/pgwire.rs
src/expr/src/relation/mod.rs
src/sql/src/plan/expr.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement/dml.rs

When the `enable_expressions_in_limit_syntax` feature flag is enabled, this commit teaches Materialize to allow parameters in LIMIT expressions.
The trick is to allow a `RowSetFinishing` to be generic over the type of the limit, so that the planner can hold the finishing's limit as an `HirScalarExpr` long enough to call `bind_parameters` on it.
Fix https://github.com/MaterializeInc/materialize/issues/24893.
- Allow `LIMIT` expressions to contain parameters.

sql: support parameters in LIMIT expressions

---

.cargo/config
ci/test/cargo-test/mzcompose.py
ci/test/pipeline.template.yml
doc/developer/guide.md

Seems to be ~10% faster for cargo-test.
-

builds: Enable lld, optimize linking more, faster cargo-test build

---

test/cluster/mzcompose.py

The compute controller now only refreshed its metrics once per second, which makes it more likely that test-compute-controller-metrics, which runs some SQL and then checks for that to be reflected in the metrics, gets to see outdated values.
The only way we can solve this is by sleeping before querying the metrics. Given the 1s refresh interval, sleeping for 2s should be enough.
Fixes https://github.com/MaterializeInc/materialize/issues/25214
- N/A

test/cluster: unflake test-compute-controller-metrics

---

misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This was reported by @teskje in https://buildkite.com/materialize/nightlies/builds/6418#018da6e2-e722-4573-9a9a-ba7c4341b15e.
Identified issue: https://github.com/MaterializeInc/materialize/issues/25228 (no regression)

postgres consistency: add ignore for #25228 (date parsing)

---

test/feature-benchmark/mzcompose.py

This reverts commit 5cff5a64e75434a0d736c19c46afd6dd9e35dc21.
https://github.com/MaterializeInc/materialize/issues/25124 was observed again on `main` in [builds/6429](https://buildkite.com/materialize/nightlies/builds/6429#018da79c-1476-4cd9-928a-a4971a8b29ce) since enabling it with https://github.com/MaterializeInc/materialize/pull/25180.

Revert "ci: reenable MySqlStreaming"

---

src/compute/src/row_spine.rs

This avoids a common performance problem where `extend_from_slice` is faster than `extend` and passing a slice iterator. I don't have measurements to back this up, and we're not CPU-bound, but it's good habit to use the more specific `extend_from_slice` API.
-

Use extend_from_slice to copy rows

---

src/compute/src/row_spine.rs
test/testdrive/introspection-sources.td

This PR reverts https://github.com/MaterializeInc/materialize/pull/24330 because there is some evidence that it regresses memory usage.
We observed a large memory regression (from ~4.8 to ~8 GiB) in one cluster in our canary environments, going from version 0.86 to 0.87. We identified #24330 as the most likely cause of the regression from among the PRs merged in 0.87.
I attempted to reproduce the memory regression on staging and was partially successful. The increased memory usage is visible, although the difference is not nearly as big as what we see on that canary cluster.
(The lines are, in order: v0.86.1, v0.87.1, v0.87.1 with this revert applied.)
We also have ~~some suspicion~~ [pretty good evidence](https://github.com/MaterializeInc/materialize/issues/25153#issuecomment-1943661451) …

Revert "Use more robust row batch sizing (#24330)"

---

misc/scratch/ci-aarch64.json

scratch: add ci-aarch64 profile

---

ci/plugins/mzcompose/hooks/post-command

ci: Don't upload coredumps, still huge

---

misc/python/materialize/parallel_workload/action.py
src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/sql.rs
src/adapter/src/lib.rs
src/adapter/src/notice.rs
src/adapter/src/subscribe.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/protocol/response.rs
src/controller/src/lib.rs
src/environmentd/src/http/sql.rs
src/environmentd/tests/sql.rs
src/pgwire/src/protocol.rs
test/cluster/cluster-drop-concurrent/run.td
test/cluster/cluster-drop-concurrent/setup.td
test/cluster/mzcompose.py

This commit implements the simplification to subscribe lifecycle identified by @teskje in [0]. Highlights:
* The adapter now immediately removes its state about a subscribe when it aborts a subscribe, thus eliminating the need for `ActiveSubscription::dropping`.
* The logic for dropping subscribes is no longer semi-circular. The `drop_compute_sinks` method triggers a call to `drop_collections`, which triggers `SubscribeResponse::DroppedAt`, which does *not* cause another call to `drop_compute_sinks`. The only way that adapter and controller state gets cleaned up now is via a call to `drop_compute_sinks`.
* The separate cancellation channel between the adapter and the protocol layers is no more. Cancellation is now *only* communicated via the peek and subscribe response protocol. This …

adapter: simplify subscribe cancelation

---

misc/python/materialize/ci_util/__init__.py
misc/python/materialize/cli/mzcompose.py

This closes https://github.com/MaterializeInc/materialize/issues/25233.

ci: no second, superfluous junit.xml for SLT tests

---

src/controller/src/lib.rs

Otherwise they could stay around forever.
- n/a

controller: remove empty watch sets

---

src/environmentd/tests/server.rs

This commit cleans up the
test_storage_usage_collection_interval_timestamps test, by removing a cast to integer from a SQL query. Previously we were executing the query `SELECT EXTRACT(EPOCH FROM collection_timestamp)::integer ...`. `SELECT EXTRACT(EPOCH FROM <timestamp>)` returns a `float8` representing the epoch seconds. Casting to an integer would truncate the subsecond part of the epoch. This commit removes the cast which removes the truncation for more accuracy.
The cast may have caused false positives which is why the cast never led to test failures.

test: Fix storage usage test timestamp extraction

---

misc/python/materialize/mzcompose/__init__.py
src/ore/src/lgbytes.rs
src/persist-client/src/batch.rs
src/persist-client/src/cfg.rs
src/persist-client/src/cli/inspect.rs
src/persist-client/src/fetch.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/metrics.rs
src/persist-client/src/lib.rs
src/persist/src/cfg.rs
src/persist/src/indexed/columnar.rs
src/persist/src/indexed/columnar/arrow.rs
src/persist/src/indexed/columnar/parquet.rs
src/persist/src/indexed/encoding.rs
src/persist/src/metrics.rs
src/persist/src/s3.rs
src/persist/src/workload.rs
src/repr/benches/row.rs
src/storage/examples/upsert_open_loop/workload.rs

This will reduce rehydration memory spikes by moving the data decoded
from arrow/parquet into file-backed mapped allocations.
Ideally, we'd read decode into these allocs, but that
requires maintaining a fork of our arrow client library. We
appear to get a meaningful improvement by moving the data in at the very
first place it touches mz code, and that's a much easier place to start.
Mechanically, this is accomplished by replacing the arrow2-provided
`*Buffer` structs (morally an `Arc<Vec<T>>`) with lgalloc-backed
`Regions`. On the decode path, we attempt to use `Region::Mmap` (only on
cc clusters). On the encode path, we assume the data will shortly be
encoded and don't bother, instead just using `Region::Heap`. This diff
is pretty small, most of the PR is generalizing `MetricsRegion` to …

persist: use lgalloc to back data decoded from arrow/parquet

---

src/adapter/src/coord/sequencer/inner.rs

I didn't realize when I implemented this that I could return an `AdapterError::Canceled` directly.
h/t @moulimukherjee
- n/a

adapter: simplify pg_cancel_backend

---

misc/python/materialize/cli/mzcompose.py

`args.find` is not set if you invoke tests like this:
```
cd test/canary-environment
./mzcompose run test
```

ci: fix junit.xml exclude for SLT tests

---

Cargo.lock
src/interchange/Cargo.toml

Reported in [builds/6448](https://buildkite.com/materialize/nightlies/builds/6448#018daa2c-f023-46a4-988d-74331dd5e7c5).

cargo: remove mz-avro-derive from src/interchange

---

misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py

This addresses the failure in [builds/6448](https://buildkite.com/materialize/nightlies/builds/6448#018daa2c-f13a-410f-96c9-b385859de342).

version consistency: add ignore for date_trunc

---

bin/ci-builder
misc/python/materialize/version_list.py

Demo: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aci%2Foverride-common-ancestor (supposed to run the scalability framework against `v0.85.0`)

ci: allow overriding common-ancestor with COMMON_ANCESTOR_OVERRIDE

---

src/catalog/src/durable/impls/persist/state_update.rs
src/catalog/src/durable/objects/serialization.rs

This commits fixes a panic that can happen in persist data migrations. Before running migrations the catalog attempts to read the epoch and config collection by calling `try_from` on the raw data to convert it into structured data. This should fail on un-migrated collections by returning an `Err`, not by panicking. However, the `try_from` implementation was calling a `to_serde` method that panics when it fails. This commit fixes the panic by adding a `try_to_serde` method that returns an `Err` which can be propagated to `try_from`.

catalog: Fix persist data migration panics

---

src/sql/src/pure.rs
test/testdrive/kafka-alter-source.td

* This PR fixes a recognized bug. Fixes: https://github.com/MaterializeInc/materialize/issues/25124
-

Fix error message for ALTER SOURCE on non-postgres sources

---

src/sql/src/func.rs
test/sqllogictest/regclass.slt
test/sqllogictest/regproc.slt

This commit fixes text to reg* casting (such as text to regclass) so that items in a system schema can be correctly resolved when the active database is invalid.
Fixes #25080
- Allow users to cast text to `reg*` types (such as `regclass`) for items in system schemas when the active database is invalid. This also fixes any function that uses `reg*` casting such as access privilege inquiry functions.

sql: Update reg* casting to support invalid DBs

---

bin/environmentd-debug-zip

This slurps up everything necessary to recreate the state of a local bin/environmentd. Hopefully will be helpful if someone has a sticky repro of a rare bug.
-

bin: add an environmentd-debug-zip command

---

src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/catalog/src/memory/objects.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql-parser/tests/testdata/explain
src/sql/src/normalize.rs
src/sql/src/plan.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/show.rs

This PR fixes a bootstrap as-of selection bug for materialized views: If environmentd crashed after having committed a new MV to the catalog but before having created the storage collection, bootstrapping would initialize the storage collection with a `since` of `[0]`, making the MV readable for times at which it didn't have valid contents.
The fix consists of writing the as-of selected during MV creation into the `create_sql` that gets stored in the catalog. Then, during bootstrap, the coordinator can pass that as-of value when creating the storage collection, ensuring that it always gets a `since` of at least the previously selected as-of.
Storing the as-of to the `create_sql` requires parser support, which is added here as well (first commit). The parser support is kept intentionally …

adapter: use initial MV as-of during bootstrap

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/id_bundle.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/sql.rs
src/adapter/src/coord/timeline.rs
src/adapter/src/error.rs
src/storage-controller/src/lib.rs
test/sqllogictest/materialized_views.slt

This makes the changes discussed [here](https://materializeinc.slack.com/archives/C02FWJ94HME/p1707767919719259?thread_ts=1707333434.781239&cid=C02FWJ94HME):
The main thing is that we'll try to acquire precise read holds for `REFRESH AT`, and error out the MV creation if this is not possible. This brings us closer to figuring out what is happening in https://github.com/MaterializeInc/materialize/issues/24288#issuecomment-1931856361, because if we'll now see this error instead of the one from sequencing, that means that the read hold acquisition is failing. (The other possibility is that we are somehow losing the read holds after successfully acquiring them.)
Additionally it fixes a bug where `acquire_read_holds_auto_cleanup` could previously leak read holds when duplicate read holds were …

Acquire precise read holds for `REFRESH AT`s

---

src/adapter/src/catalog.rs
src/catalog/src/durable.rs
src/catalog/src/durable/impls/migrate.rs
src/catalog/src/durable/impls/persist.rs
src/catalog/src/durable/impls/persist/tests.rs
src/catalog/src/durable/impls/shadow.rs
src/catalog/src/durable/impls/stash.rs
src/catalog/src/durable/initialize.rs
src/catalog/tests/open.rs

This commit renames the `boot_ts` parameter of the open family of method in `OpenableDurableCatalogState` to `initial_ts`. `initial_ts` is more accurate because the timestamp is only used to initialize the catalog if it's a new environment. Additionally, `boot_ts` is used in other places and is linearized against the timestamp oracle. In the open family of methods, `boot_ts` wasn't linearized, so the name may have mistakenly led people to people that this `boot_ts` was also linearized.
Additionally, `initial_ts` is removed as a parameter from `open_readonly`, because `open_readonly` cannot initialize a new environment, so it doesn't make sense to require a `initial_ts`.

catalog: Clean up boot_ts usage in open

---

src/environmentd/tests/server.rs

@nrainer-materialize do you mind following up on getting this re-enabled?
-

disable failing test that request objects from vercel, to unblock ci

---

doc/user/content/sql/create-sink/kafka.md
src/environmentd/tests/server.rs
src/interchange/Cargo.toml
src/interchange/src/json.rs
test/testdrive/kafka-json-sinks.td

storage/format/json: encode nested arrays correctly

---

src/buf.yaml
src/storage-client/build.rs
src/storage-client/src/client.proto
src/storage-client/src/client.rs
src/storage-client/src/lib.rs
src/storage-client/src/statistics.proto
src/storage-client/src/statistics.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/statistics.rs
src/storage/src/internal_control.rs
src/storage/src/statistics.rs

storage: move some stuff from mz_storage_client::client to mz_storage_client::statistics

---

src/environmentd/tests/server.rs

* This PR fixes a recognized bug
The filename `styles.css` is not part of Console's external-facing contract. Instead, let's test for an HTML response from the base internal path.
Fixes #25294 
:+1:
-

Test for a HTML file being served from the envd proxy instead of CSS.

---

src/adapter/src/active_compute_sink.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/sql.rs

Refactoring to keep `ctx` as non-optional in `ActiveCopyTo`, and `process_response` now consumes `self` instead of `&mut self`.
Follow up from https://github.com/MaterializeInc/materialize/pull/25042. 
- 
cc @benesch @mjibson

adapter: refactor `ActiveCopyTo` to have a non-optional `ctx`

---

ci/plugins/cloudtest/hooks/post-command
ci/plugins/mzcompose/hooks/command
ci/plugins/mzcompose/hooks/post-command

ci: Upload heap profiles profiles continuously

---

misc/python/materialize/version_list.py

Broken in https://github.com/MaterializeInc/materialize/pull/25117
Our major version has always been 0, so there is no way to find a version.
-

ci: Fix comparison against previous MINOR version

---

ci/plugins/mzcompose/hooks/command

Otherwise we spam too many files
-

ci: Only upload heap profiles when requested via CI_HEAP_PROFILES=1

---

ci/release-qualification/pipeline.template.yml

If this test turns out to be useful I think I have to automate this in mkpipeline.py
-

release-qualification pipeline: Against 0.87.2 and skip upgrade

---

test/feature-benchmark/mzcompose.py

https://buildkite.com/materialize/release-qualification/builds/428#018daf74-d96d-4583-92c0-04c7db281b1f
This feature-benchmark scenario was failing due to the release qualification build for 0.88.0. This PR is to disable the test to unblock the release qual until we can diagnose what went wrong.
-

Disable spuriously failing MySqlInitialLoad feature-benchmark scenario

---

doc/user/data/sql_funcs.yml
src/pgrepr-consts/src/oid.rs
src/sql/src/func.rs
test/sqllogictest/mz_schema_oid.slt
test/sqllogictest/parse_ident.slt
test/sqllogictest/privilege_grants.slt
test/sqllogictest/regclass.slt
test/sqllogictest/regtype.slt

This commit makes mz_schema_oid more robust by only searching for schemas in the current database of the session when a database is not explicitly specified. Additionally, this commit allows callers to specify the database of a schema when calling mz_schema_oid. As a result other functions that call mz_schema_oid, such as has_schema_privilege, also are more robust.
Fixes #21490
- Make has_schema_privileges more robust by taking into account the current database and any specified database.

sql: Make mz_schema_oid more robust

---

src/compute-client/src/controller/instance.rs

Turns out that the Compute controller has the same bug that d3feba8c6f3403be78f251a4d4a9ee6dd50b8da1 fixed in the Storage controller.
* This PR fixes a previously unreported bug: See commit msg of d3feba8c6f3403be78f251a4d4a9ee6dd50b8da1
-

Fix `set_read_policy` also in the Compute controller

---

ci/release-qualification/pipeline.template.yml

Seen in https://buildkite.com/materialize/release-qualification/builds/428#018daf74-d96d-4583-92c0-04c7db281b1f.
The feature benchmark compared `v0.88.0 (ea142299b)` against `latest`, which is the same version. It should compare against the previous release, which can be achieved by specifying `common-ancestor`. When in CI and on a release branch, `common-ancestor` will return the preceding major release.
```
_bk;t=1708047244247The version of the 'THIS' Mz instance is: environmentd v0.88.0 (ea142299b)
[...]
_bk;t=1708045896008The version of the 'OTHER' Mz instance is: environmentd v0.88.0 (ea142299b)
```

ci: release qualification: feature benchmark should compare against the previous release

---

ci/test/pipeline.template.yml
test/legacy-upgrade/mzcompose.py

This legacy upgrade test will skip versions when testing certain upgrade paths. The persist catalog will panic if a version is skipped when upgrading. Even when using the stash catalog implementation we open the persist catalog during boot, which will cause the panic. To avoid this, this commit uses the emergency-stash catalog implementation, which doesn't even attempt to open the persist catalog.
Fixes #25321
This PR fixes a known bug.

test: Fix legacy upgrade tests catalog impl

---

src/storage/src/render/upsert.rs
src/storage/src/render/upsert/autospill.rs
src/storage/src/render/upsert/memory.rs
src/storage/src/render/upsert/types.rs

- fix rustfmt
- move autospill/memory impls into their own files
- break things into functions
broken out from: https://github.com/MaterializeInc/materialize/pull/24663
-

storage: refactor upsert code

---

src/compute-client/src/controller/instance.rs
test/sqllogictest/materialized_views.slt

`downgrade_warmup_capabilities` was calling `step_back()` on each input collection's write frontier, and ignoring the case when `step_back()` returned None (which happens when the given timestamp is 0). This meant that if all input collection's write frontier was still at 0 (which can happen for a short time after the creation of a Storage collection, or even not for a not so short time, when the cluster that's feeding a Storage collection doesn't have any replicas), then we didn't keep a warmup capability.
-

Fix the stepping back in `downgrade_warmup_capabilities`

---

src/compute-client/src/controller/instance.rs

This PR fixes a bug in the compute controller where global write frontiers could regress by being overwritten with the write frontiers of lagging replicas.
The `maybe_update_global_write_frontiers` method did contain a check to ensure that frontier regressions are ignored. However, this check was applied only _after_ `CollectionState::write_frontier` was already unconditionally updated to the new frontier, making it quite useless.
The fix is of course to check for regressions before updating the collection state.
The bug was introduced in #25005 which changed `update_global_write_frontiers` from panicking on regressions to handling them gracefully (by ignoring them). The previous code was correct because the regression in `ComputeState::write_frontier` didn't matter when the processed …

compute-client: avoid regressing global write frontier

---

Cargo.lock
src/persist-txn/src/txns.rs
src/storage-controller/Cargo.toml
src/storage-controller/src/collection_mgmt.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/persist_handles.rs
test/testdrive/tables.td

This PR finalizes the Persist shard for a table, after the table gets dropped.
Previously when dropping a table we would leak the shard, and only during a restart of environmentd would we notice the shard has been leaked and schedule it for finalization. Now after a table gets dropped we do the following:
1. Wait for the since of the shard to get downgraded to the empty Antichain, which is triggered by the Coordinator when the table is dropped.
2. Ask and wait for `PersistTxn` to forget the handle.
3. Emit a `DroppedIds` event which triggers shard finalization.
Note: I wrote a consistency check that would check for leak shards and automatically run after a testdrive test. I wanted to include this but unfortunately subsources also leak their shards, and fixing that is non-trivial, so we'll …

tables: Finalize shards after a table is dropped

---

src/mysql-util/src/schemas.rs
src/sql/src/pure.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/schemas.rs
src/storage/src/source/mysql/snapshot.rs
test/mysql-cdc/15-create-source.td
test/mysql-cdc/20-source-replication.td
test/mysql-cdc/mzcompose.py
test/mysql-cdc/override/10-replica-connection.td
test/mysql-cdc/schema-restart/after-restart.td
test/mysql-cdc/schema-restart/before-restart.td

The source snapshot code was inadvertently dropping the transaction it intended to use on the floor, leading to the correctness issue observed in #25124.
Specifically, the SELECT query to load the table's snapshot was running outside of any transaction. This allowed it to observe the handful of transactions that committed *after* the snapshot's consistent point was constructed but before the SELECT query began executing. The replication stream (correctly) did not rewind this data, resulting in the data from that handful of transactions getting ingested into Materialize twice.
As far as I can tell, the code's approach to locking is (now) sound, so we don't need any of the changes to the locking scheme proposed in #25300. In particular, FLUSH TABLES only seems relevant if you need the data …

storage/source/mysql: fix snapshot transaction

---

misc/python/materialize/cli/ci_closed_issues_detect.py
src/transform/src/normalize_lets.rs
test/sqllogictest/cockroach/join.slt

As suggested by Rainer
I pinged Sean and Parker about two of the issues which look legitimate, and ignored all so that nightly should be green.
-

ci: Also detect references to closed issues across comment blocks

---

misc/python/materialize/cli/ci_logged_errors_detect.py
test/persist-catalog-migration/mzcompose.py

This commit adds a test to assert that upgrading by skipping versions will fail.
Works toward resolving #24218
Adds a test.

test: Verify that skipping versions fails

---

misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py

Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Abenchmark%2Fenable-mysql-streaming
with `COMMON_ANCESTOR_OVERRIDE="v0.88.0-dev"`
✅ Running `v0.89.0-dev` (`v0.88.0-dev` was no longer available) and `v0.88.1` succeeded.

feature benchmark: enable MySqlStreaming

---

test/feature-benchmark/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Abenchmark%2Fenable-mysql-initial-load
with `COMMON_ANCESTOR_OVERRIDE="v0.88.0-dev"`
✅ Running `v0.89.0-dev` (`v0.88.0-dev` was no longer available) and `v0.88.1` succeeded. Not sure if this means that #25323 is no longer an issue or whether the seen failure was a flake. We will see that in the coming CI runs.

feature benchmark: enable MySqlInitialLoad

---

src/adapter/src/coord.rs
src/adapter/src/metrics.rs

This commit adds a metric for the total number of messages processed by the Coordinator and the total number of watchdog messages processed by the Coordinator. These are helpful for determining when the Coordinator is stuck.

adapter: Add metrics for Coord message processing

---

src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/sql/src/plan/expr.rs
test/sqllogictest/temporal.slt

The problem was that `contains_temporal` was just calling `visit_children`, which doesn't do a visitation in the entire subtree, but merely visits the scalar expressions in the top-level relation expr node. This PR changes `contains_temporal` to do a visitation of all relation expr nodes, and for each of them do what we were doing before for just the top-level node.
The issue description mentions that we should be able to find temporal expressions also in referenced view definitions. This already works: `peek_stage_validate` calls `validate_timeline_context`, which calls `get_timeline_contexts`, which transitively visits view definitions and calls `MirRelationExpr::contains_temporal()` on their optimized expressions.
* This PR partially fixes a recognized bug: …

Fix visitation in `HirRelationExpr::contains_temporal`

---

ci/nightly/pipeline.template.yml

ci: Don't detect closed issues on release branches (but on PRs)

---

src/compute-client/src/controller/instance.rs

When installing write frontiers for a new replica, we should not attempt to install empty read holds for dataflow dependencies with the storage controller. If a collection has advanced to the empty frontier, this means we don't have read holds on its inputs anymore, so the storage controller has been free to drop these input collections. If we try to update the storage read capabilities for an object the storage controller doesn't know about, it panics, so we must avoid that.
Fixes https://github.com/MaterializeInc/materialize/issues/25366
I don't think we can write a reliable regression test for #25366. The panic only happens when the various cleanup steps happen in a specific order (shard finalization, replica creation, compute collection cleanup) and …

compute-client: fix replica write frontier initialization

---

Cargo.lock
misc/cargo-vet/audits.toml
src/persist-client/src/read.rs
src/storage-types/src/sources/load_generator.rs
src/storage/src/source/generator.rs
src/storage/src/source/generator/auction.rs
src/storage/src/source/generator/counter.rs
src/storage/src/source/generator/datums.rs
src/storage/src/source/generator/marketing.rs
src/storage/src/source/generator/tpch.rs

Update our timely dependency. This includes a change to remove the async operator builder, which causes a bunch of changes around the now-missing `Event` struct. All changes in https://github.com/MaterializeInc/timely-dataflow/commit/9208396d1d86becbcc91c76e780ffe61fd51e65e.
-

Update dependency on timely

---

Cargo.toml
bin/lint-versions
misc/wasm/Cargo.toml

Fixes: https://github.com/MaterializeInc/materialize/issues/24818
Release notes: https://releases.rs/docs/1.74.1/
The fix we need for aarch64 compilation is https://github.com/rust-lang/rust/pull/118464
-

Bump Rust version to 1.74.1

---

.github/workflows/slack_notify_opened.yml

We have a workflow to detect issues opened by external users that...doesn't work. It turns out that there's [some subtleties around how GH Actions handles booleans](https://github.com/actions/runner/issues/1483).
Didn't notice until now because there was a parallel workflow running via Zapier.

.github: Fix external user notification workflow

---

doc/user/content/sql/create-connection.md

Per the AWS Foundational Technical Review, we need to mark the use of credentials-based authentication as deprecated, in favor of role assumption-based authentication.
More context: https://github.com/MaterializeInc/cloud/issues/8548
* This PR updates documentation.
- n/a

doc/user: deprecate credentials-based authentication

---

src/storage/src/render/upsert.rs

A few months ago we accidentally shipped a protobuf incompatible change which was persisted in various collection shards. In order to handle this we shipped a version of MZ[1] that automatically detects the incompatible protobufs and heals the shards by retracting the incompatible representation and inserting the correct one. The idea was that eventually shard compaction would lead to the incompatible protobufs getting deleted. As part of that work we also added metrics tha tracked the occurances of legacy errors with the expection of that metric dropping to zero after enough time had passed.
The metrics for the legacy representation of errors have indeed dropped to zero for all environments in production. While this could be considered enough evidence to finally remove the healing code I …

storage: report an error when observing a legacy error

---

src/adapter/src/optimize/copy_to.rs
src/buf.yaml
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-types/src/dataflows.rs
src/compute-types/src/sinks.proto
src/compute-types/src/sinks.rs
src/compute/src/render/sinks.rs
src/compute/src/sink/copy_to_s3_oneshot.rs
src/compute/src/sink/mod.rs

Follow up from https://github.com/MaterializeInc/materialize/pull/25042, renaming the `s3_oneshot` sink to `copy_to_s3_oneshot` to make the naming consistent with `CopyTo` prefix used elsewhere.
- 
cc @teskje

compute: rename s3_oneshot sink to copy_to_s3_oneshot

---

doc/developer/design/20231213_compute_operator_hydration_status_tracking.md

This PR adds a design doc about Operator Hydration Status Tracking in Compute.
I reduced the scope from the initial draft in three ways:
* Instead of logging operator frontiers, only log operator hydration status. This is the information we need for the planned Console features and collecting it is way less expensive than keeping track of frontiers.
* Remove the parts that are only about exposing dataflow graphs to users. We don't plan to do so currently, so there is no need to include it in this design.
* Remove the part about rendering dataflow regions for LIR nodes. Those are useful for showing dataflow graphs but this design doesn't need them.
Part of https://github.com/MaterializeInc/materialize/issues/23859
- N/A

design: Compute Operator Hydration Status Tracking

---

src/catalog/src/durable/impls/persist.rs
src/catalog/tests/open.rs

When processing updates in the persist catalog, retractions need to be processed before insertions for a given timestamp, so we retract the old value and not the newly inserted value. The savepoint persist catalog was not sorting updates properly for a given timestamp and not processing updates correctly. This commit fixes the issue by sorting updates within a timestamp.
Fixes #25363

catalog: Fix persist savepoint updates

---

src/adapter/src/active_compute_sink.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/sql.rs

This is a minor follow up to the `COPY ... TO` response protocol implementation PRs (#25179, #25042, and #25311) that attempts to leave the compute sink cleanup code in the best state possible.
Details are in the individual commit messages, but the gist is that functions are now named and documented as consistently as possible, and subscribe and copy to are handled as symmetrically as possible.
Go commit by commit and suppress whitespace. The diff isn't actually that large, and is mostly code movement!
- n/a

adapter: minor refactorings to compute sink cleanup

---

Cargo.lock
src/mysql-util/src/schemas.rs
src/storage/Cargo.toml
src/storage/src/source/mysql.rs
src/workspace-hack/Cargo.toml
test/mysql-cdc/mzcompose.py
test/mysql-cdc/types-temporal.td

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/25149
Relevant MySQL docs:
- https://dev.mysql.com/doc/refman/8.0/en/datetime.html
- https://dev.mysql.com/blog-archive/mysql-8-0-removing-support-for-old-temporal-datatypes/
The tests validate the decoding in both the snapshot and replication operators (since one is based on query results, and the other is based on decoding binlog events). I stole this idea from the pg-cdc type tests and it helped catch that the encoding for `timestamp` is different between query/binlog in `rust-mysql-common`!
I also switched all the decoding to using the fallible `from_value_opt` method from `mysql-async` rather than panicking on a failure, which seems better :)
-

storage/mysql: Add mysql support for date, time, datetime, timestamp data types

---

src/adapter/src/coord.rs
src/adapter/src/metrics.rs
src/sql/src/session/vars.rs

This commit removes the mz_coord_messages_processed metric that counts the total number of messages processed by the Coordinator. This metric was added in 57a56d6f46681ec25cf5592930396a2f4c70c5cf. It is redundant with the slow_message_handling metric. As of
02bb658a445ffb87d3c8d28872f2aee08c5f2144, slow_message_handling counts all messages not just the slow ones.

adapter: Remove redundant message count metric

---

test/sqllogictest/dates-times.slt

When the --auto-index flag is passed to SQL Logic Tests, the test will perform the following for each SELECT:
1. Execute the SQL and check that the response matches the expected response.
2. Create an indexed view with the SELECT as the definition and check that the response matches the expected response.
3. Compare the response from steps (1) and (2) and see if they differ.
Currently, the error message from raw SELECTs and the error message from SELECTing an indexed view differ slightly. Specifically, indexed views will prepend `Evaluation error: ` to the error. As a result, if the expected error message provided to an SLT test (which is treated as a regex) is too specific, then step (2) will fail and result in a false negative test result.
This commit fixes some failing tests, due to …

SLT: Fix dates-times expected errors

---

.github/CODEOWNERS
Cargo.lock
Cargo.toml
src/clusterd/Cargo.toml
src/clusterd/src/bin/clusterd.rs
src/dyncfgs/Cargo.toml
src/dyncfgs/src/lib.rs
src/environmentd/Cargo.toml
src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/test_util.rs
src/persist-client/src/cfg.rs
src/persist-client/src/cli/admin.rs
src/persist-txn/src/lib.rs
src/sql/Cargo.toml
src/sql/src/session/vars.rs
src/sqllogictest/Cargo.toml
src/sqllogictest/src/runner.rs

This deduplicates the two existing copies into one.
On on hand, it seems silly to have a whole crate just for this. On the other hand, there are some tricky dependency issues involved.
For dyncfgs to work, this list needs to be the same in both `clusterd` and `environmentd`. (Technically, I think it would be okay for the `clusterd` list to be a subset of the `environmentd` list, but that's pretty subtle to reason about to let's avoid it if possible.) This means we need to find a home for it that can depend on all crates that use dyncfgs (initially persist-client and persist-txn, but hopefully more soon) and that can be depended on by both `clusterd` and `environmentd` main files. The initial location (in mz-sql) already fails the latter requirement, which is why it had to be duplicated. …

dyncfg: extract list of all dyncfgs in the system into a new crate

---

src/adapter/src/coord/sequencer/inner/peek.rs
src/catalog/src/durable/impls/stash.rs
src/environmentd/src/bin/environmentd/main.rs
src/expr/src/interpret.rs
src/service/src/boot.rs
src/stash/src/lib.rs
src/stash/src/tests.rs
src/stash/src/upgrade.rs
src/storage-controller/src/lib.rs

Lots of unused extra futures that its now catching
-

*: fix clippy for 1.76

---

src/adapter/src/catalog/state.rs

I turned on debug logging locally and it was immediately unusable because we end up tracing the whole catalog when calling `parse_plan`.
- N/a

tracing: Don't trace the whole catalog

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml

ci: Disable automatic retries for aarch builds

---

src/mysql-util/src/desc.rs
src/storage/src/source/mysql/schemas.rs
test/mysql-cdc/25-schema-changes.td
test/mysql-cdc/schema-restart/before-restart.td

* This PR adds a known-desirable feature: https://github.com/MaterializeInc/materialize/issues/25072
This completes the above task by allowing compatible changes to occur without putting the source into an error state.
Most of this logic is based on the same compatibility checks in the postgres source. We decided not to allow column renames, since it'll be impossible for us to differentiate between a re-order and a rename of the columns in a table.
-

storage/mysql: Ignore added columns to tables we're ingesting

---

src/transform/src/join_implementation.rs

While trying to understand how difficult it would be to migrate away from the `Attribute` framework, I realized that `JoinImplementation` doesn't need to modify the attributes (at the price of a single `.clone()`.)
Code used a mutable API when a by-reference API would have worked.
-

compute:`JoinImplementation` can use `Attribute` non-mutably

---

src/persist-txn/src/txn_cache.rs

This debug assertion was getting tickled by the following sequence of events (`A < B < C < D`):
- At time `A`, a data shard is registered
- At time `B`, it is written to via txns
- At time `C`, it is forgotten
- We then open the txns cache with an as_of time `D`
- We read the register and write into the cache. The pushing the write into the cache triggers a call to `compact_data_times`, which advances the register ts from `A` to `D`
- We then read the forget into the cache, the advanced register ts `D` is not less_equal the forget ts `C` and boom
I can't think of any reason for us to advance the register ts. It's likely a holdover from before we kept around the original timestamps of things. So, fix the bug by removing the advancement from `A` -> `D`, leaving the register ts in the cache …

persist-txn: fix "register ts ... not less_equal forget ts" bug

---

Cargo.lock
src/mysql-util/Cargo.toml
src/mysql-util/src/decoding.rs
src/mysql-util/src/lib.rs
src/mysql-util/src/schemas.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/snapshot.rs
test/mysql-cdc/types-decimal.td

* This PR adds a known-desirable feature. Adds Decimal / Numeric type support.
Part of the work in https://github.com/MaterializeInc/materialize/issues/15901
The first commit is entirely just a refactor to move the row decoding logic from `src/storage/src/source/mysql.rs` to `src/mysql-util/src/decoding.rs`. Some of the error messages were updated, but otherwise this should have no functional differences.
The second commit implements decoding of Decimal / Numeric types (https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html) and a test to validate them.
-

storage/mysql: Add Decimal/Numeric support; move decoding code to mz-mysql-util

---

src/storage-client/src/statistics.rs
src/storage/src/source/generator.rs
src/storage/src/source/mysql/statistics.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/statistics.rs
test/cluster/storage/01-create-sources.td
test/cluster/storage/02-after-environmentd-restart.td
test/cluster/storage/04-after-clusterd-restart.td
test/mysql-cdc/statistics.td
test/pg-cdc/privileges.td
test/pg-cdc/statistics.td
test/pg-cdc/subsource-resolution-empty.td
test/testdrive/steady-state-source-statistics.td

This consolidates all my prior art, and finishes publishing the _steady-state metrics_ (as defined here: https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20240108_source_metrics_2.md) in the `mz_source_statistics_raw` table.
This is the last big pr for this work, other than snapshot progress, which will have a similar shape as this one.
Note that I tested this pr (though don't really care about the accuracy of the metrics for loadgen sources). 
These are now populating the `_raw` table, but not the user-facing view on top.

storage: collect new steady-state statistics in mz_source_statistics_raw

---

test/pg-cdc/ceased/after-mz-restart.td
test/pg-cdc/ceased/before-mz-restart.td
test/pg-cdc/mzcompose.py

test: fix pg-cdc ceased-status test

---

Cargo.lock
src/fivetran-destination/Cargo.toml
src/fivetran-destination/src/destination/dml.rs
src/fivetran-destination/src/error.rs

This PR changes the Fivetran destination to reuse scratch tables for syncing, instead of creating a TEMPORARY table for every action.
After dropping a temporary table we keep a record of the shard's tombstone. If we're syncing multiple tables, creating a temporary table for each action, and syncing every few minutes, we can end up with millions of tombstones in a few months.
It's on the Persist roadmap to look into shard tombstones, but for now reusing scratch tables reduces the time pressure.
- N/a

fivetran-destination: Reuse scratch tables instead of creating TEMPORARY tables

---

src/catalog/src/builtin.rs
src/storage-client/src/client.rs
test/pg-cdc/mzcompose.py
test/pg-cdc/status/01-setup.td
test/pg-cdc/status/02-after-mz-restart.td
test/pg-cdc/status/03-toxiproxy-interrupt.td
test/pg-cdc/status/04-drop-publication.td

I think there were some very mild deficiencies in how we reported subsource statuses:
- If the subsource was in `ceased` and the parent source was `stalled`, the subsource would report `stalled` which is goofy.
- If a subsource encounters multiple definite errors, it reports the most recent of them. We should mirror this in the status collection.
-

pg: subsource status reporting tidy up

---

ci/security/pipeline.template.yml

Dockerhub seems to have gotten slow
-

ci: Increase timeout for security pipeline

---

src/sql/src/plan/statement/ddl.rs
test/testdrive/kafka-avro-sinks-defaults.td

While waiting to implement #25417, we should remove the footgun of letting users alter upsert sources.
Users have not reported this failure to us, so I don't think it's very common, which is why I don't think it's worth threading the needle with the error reporting.
This PR patches a previously reported bug.
- Temporarily disallow `ALTER CONNECTION` on sources using the `UPSERT` envelope.

sql: disallow ALTER CONNECTION on UPSERT sources

---

src/frontegg-auth/src/auth.rs
src/frontegg-auth/src/lib.rs

Easy split out from https://github.com/MaterializeInc/materialize/pull/25409.
- n/a

frontegg-auth: remove dead code

---

misc/python/materialize/checks/all_checks/statement_logging.py

Seen in https://buildkite.com/materialize/nightlies/builds/6561#018dccef-ef30-4f63-824c-ff8d982392d8
Broken by https://github.com/MaterializeInc/materialize/pull/25276/files
This scenario is slightly annoying because it is the only one that ends up running the verify step in the old version. I'm not sure if this will be too much effort in the future to maintain.
-

platform-checks: Fix preflight and rollback scenario

---

ci/plugins/mzcompose/hooks/command

Before:
Running `bin/mzcompose --find "platform-checks" run default --scenario=PreflightCheckContinue`
Now
Running `bin/mzcompose --find platform-checks run default --scenario=PreflightCheckContinue`
-

ci: No useless quotes in repro output

---

src/adapter/src/coord.rs
src/adapter/src/coord/timestamp_selection.rs
test/cluster/mzcompose.py

This PR changes the `as_of` bootstrapping of MVs and indexes to allow for REFRESH warmup:
- Instead of moving an MV `as_of` to the write frontier of the Storage collection (which would be at the next refresh), we move it to just `least_valid_write - 1`. (Except if this would be past the write frontier of the Storage collection, in which case we use that.) This is also consistent with the `warmup_capabilities` that the Compute controller is normally holding.
- The PR removes the special logic that we had for REFRESH MVs, because it was also making the `as_of` go to the next refresh, preventing warmups.
- The PR also slightly changes the `as_of` bootstrapping of indexes: Instead of `least_valid_write`, we now consider `least_valid_write - 1`. This makes the code consistent with the MV …

Change MV bootstrapping to enable REFRESH warmup

---

ci/mkpipeline.py

Needed for example if you only run "Detect closed issues".
Demo: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Aci%2Fdummy-junit-xml-for-nightly

ci: generate dummy junit.xml also for nightly

---

Cargo.lock
src/adapter/Cargo.toml
src/adapter/src/coord/statement_logging.rs
src/adapter/src/statement_logging.rs

md5 is known to be broken.
This causes an extra 16 bytes per row in MPSH and MST, but I think the increased memory usage is worth not having to worry about possible security bugs due to md5 collisions.

Use sha256 for statement log instead of md5

---

doc/developer/testdrive.md
misc/python/materialize/cloudtest/k8s/testdrive.py
misc/python/materialize/feature_benchmark/executor.py
misc/python/materialize/mzcompose/services/testdrive.py
src/testdrive/src/action.rs
src/testdrive/src/action/consistency.rs
src/testdrive/src/action/sql.rs
src/testdrive/src/bin/testdrive.rs
src/testdrive/src/lib.rs
test/testdrive/connection-alter.td
test/testdrive/connection-create-drop.td
test/testdrive/connection-validation.td
test/testdrive/mz-depends.td
test/testdrive/mzcompose.py
test/testdrive/tables.td
test/testdrive/webhook.td

This spun out of https://github.com/MaterializeInc/materialize/pull/25173
This PR refactors the consistency checks in testdrive and changes them to run at the end of every test, instead of after every DDL statement, this speeds up testdrive execution. For example, "Testdrive 1" goes from ~15m to ~8m, "Testdrive 6" goes from ~16m to ~14m, and "🐼🏎️ testdrive" in nightly goes from ~1hour 30m to ~1hour. We could miss some inconsistent state, if a later DDL statement corrects the inconsistency of a previous, but I think is worth it for how much faster testdrive runs.
If there is a scenario which a user wants to assert consistency after a statement they can call the new `$ check-consistency` action. Alternatively we can also run the checks after every statement by specifying the …

testdrive: Refactor consistency checks, add leaked shard check

---

Cargo.toml
ci/test/cargo-test/mzcompose.py
ci/test/lint-deps.sh
misc/python/materialize/mzbuild.py

Many folks will run `cargo check` from the root of the workspace to make sure everything builds successfully. Often they hit an issue where the `fivetran-destination` fails to build because it depends on the `/misc/fivetran-sdk` submodule, and then they have to figure out how to update the submodule which isn't the best experience. The `fivetran-destination` is touched by very few people (only me at the moment) so forcing everyone to build it adds unnecessary friction.
The crates specified in `default-members` are the ones that will get built when running `cargo` commands from the root of our workspace when a target is not specified. Currently the list of `default-members` are all binaries that are referenced from `mzbuild.yml` files which should encompass everything.
Note: This also …

fivetran-destination: Specify workspace default-members to make building easier

---

src/storage-client/src/statistics.rs
src/storage/src/metrics/source/mysql.rs
src/storage/src/metrics/source/postgres.rs
src/storage/src/source/generator.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/mysql/statistics.rs
src/storage/src/source/postgres.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/statistics.rs
src/storage/src/source/types.rs
src/storage/src/statistics.rs
test/cluster/storage/01-create-sources.td
test/mysql-cdc/statistics.td
test/pg-cdc/statistics.td
test/testdrive/snapshot-source-statistics.td
test/testdrive/statistics-maintenance.td

Implements the final pieces of the [source metrics design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20240108_source_metrics_2.md).
This pr hooks up the already-partially-collected snapshot statistics and hooks it up to the `mz_source_statistics_raw` table.
It implements this for mysql/pg/kafka (I am skipping generators for now, because they have annoying semantics), and tests them. After this, the final piece is indexing the data in the user-facing view. That will be a followup pr 
-

storage: hook up snapshot_records_known/staged

---

src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/create
src/sql/src/plan/statement/ddl.rs
test/testdrive/webhook.td

This PR changes webhook sources so you no longer need to specify `IN CLUSTER`, which aligns them with all of our other kinds of sources.
Fixes https://github.com/MaterializeInc/materialize/issues/25428
- Removes the need for users to specify `IN CLUSTER` for webhooks

sql: No longer require webhook sources specify IN CLUSTER

---

src/adapter/src/client.rs
src/adapter/src/config/backend.rs
src/adapter/src/session.rs
src/environmentd/src/http.rs
src/pgwire/src/protocol.rs

Easy split out from https://github.com/MaterializeInc/materialize/pull/25409.
Rather than allowing registration of an external metadata receiver at any point after a session's construction, require it as part of the construction of the session. This allows us to statically remove the possibility of double registration.
- n/a

adapter: require Session's external metadata rx at construction

---

src/storage-client/src/statistics.rs

We MIGHT want to leave these null (instead of 0) before the snapshot is committed, so do this now so we don't lose history in the future to change this.
-

storage: make offset_known/offset_committed nullable

---

src/adapter/src/flags.rs
src/kafka-util/src/client.rs
src/sql/src/session/vars.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/statistics.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs
src/storage/src/source/kafka.rs
test/mysql-cdc/statistics.td
test/pg-cdc/statistics.td
test/testdrive/snapshot-source-statistics.td
test/testdrive/statistics-maintenance.td
test/testdrive/steady-state-source-statistics.td

This also required some annoying stuff in the controller to dynamically update the statistics interval after it has started.
Fixes: https://github.com/MaterializeInc/materialize/issues/25458
-

storage: speed up statistics tests

---

misc/python/materialize/mzcompose/composition.py

in capture_and_print mode. Seen in https://buildkite.com/materialize/tests/builds/76472#_
Just broken in https://github.com/MaterializeInc/materialize/pull/25459
-

mzcompose: Don't drop last few lines

---

src/expr/src/relation/mod.rs
src/transform/src/analysis.rs
src/transform/src/attribute/arity.rs

Improves our bespoke `arity()` call for cases of `Project` and `Reduce`, which do not need to descend to their children.
-

Streamline arity() for Project, Reduce

---

test/cluster/mzcompose.py

compute tests: Unflake test-invalid-compute-reuse

---

doc/user/content/releases/v0.88.md
doc/user/content/releases/v0.89.md

Release notes for v0.88. 🌻 
@alex-hunt-materialize @petrosagg: this covers the step of bumping the release version in the docs.

doc/user: polish v0.88 release notes

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs

adapter: remove async_trait from Staged after 1.76 bump

---

test/testdrive/webhook.td

Just introduced with #25467
Failed in https://buildkite.com/materialize/nightlies/builds/6581#018dd217-bb4f-40fe-a2f7-7dd741b87314
-

testdrive: Ignore part of webhook that only works with 1 replica

---

ci/test/pipeline.template.yml
test/persist-catalog-migration/mzcompose.py

Both failures seen in https://buildkite.com/materialize/tests/builds/76524
Started failing because of v0.90.0-dev
-

ci: Make tests pipeline green again

---

test/testdrive/audit-log.td
test/testdrive/blue-green.td
test/testdrive/cc_cluster_sizes.td
test/testdrive/controller-frontiers.td
test/testdrive/correctness-property-2.td
test/testdrive/dataflow-cleanup.td
test/testdrive/github-15095.td
test/testdrive/github-23037.td
test/testdrive/github-24310.td
test/testdrive/hydration-status.td
test/testdrive/materialized-view-refresh-options.td
test/testdrive/privilege_checks.td
test/testdrive/quickstart.td
test/testdrive/replica-targeting.td
test/testdrive/source-sink-clusters.td
test/testdrive/system-cluster.td
test/testdrive/webhook.td

Testdrive automatically cleans up resources like sources and clusters
-

testdrive: Remove useless cleanup

---

misc/python/materialize/cli/ci_logged_errors_detect.py

This removes testdrive entries from the box below (with incomplete data from logs) because these entries should already be covered by the box above (with data from the junit.xml file).

ci: error-extraction from logs: remove testdrive entries already captured by junit.xml error extraction

---

test/mysql-cdc/correctness-property-2.td
test/pg-cdc/correctness-property-2.td
test/testdrive/correctness-property-2.td

Fix correctness-property-2 tests

---

ci/release-qualification/pipeline.template.yml

and fix skip message being too long, seen in https://buildkite.com/materialize/release-qualification/builds/440#018dd2db-5612-4d38-840e-a364d5be31dc
-

release-qualification: bump pipeline to v0.88.1

---

misc/python/materialize/mzcompose/test_result.py

Seen in https://buildkite.com/materialize/nightlies/builds/6589#018dd35f-5e0d-4fcc-81de-b2b7a1236fb2
-

ci: Don't show useless "workflow-default" failure for testdrive

---

test/mysql-cdc/correctness-property-2.td
test/pg-cdc/correctness-property-2.td
test/testdrive/correctness-property-2.td

Since timestamp 0 is actually Unix TS 0, so 1970
Fixes: #25507
-

tests: Increase history retention

---

ci/test/pipeline.template.yml
misc/python/materialize/cli/ci_closed_issues_detect.py
src/sql/src/plan/statement/ddl/connection.rs

As suggested by https://buildkite.com/materialize/nightlies/builds/6592#018dd5f2-e81f-4b68-bdeb-b9dd9db69379
-

ci: Smaller agent for pg-cdc

---

misc/python/materialize/cloudtest/k8s/testdrive.py
misc/python/materialize/mzcompose/composition.py
misc/python/materialize/mzcompose/test_result.py
src/testdrive/src/error.rs

testdrive: More deterministic output order, no duplicated output

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/environmentd/tests/server.rs
test/cluster/mzcompose.py

Previously we would go off thread during optimization, allowing sinces to compact past the determined as_of.
Fixes #25375
- n/a

adapter: acquire subscribe read holds

---

src/transform/src/analysis.rs
src/transform/src/reduce_elision.rs

This PR starts out trying to use the new `Analysis` framework, porting over first `ReduceElision`, which requires type information and is currently just calling `.typ()` over and over again (potentially quadratic). This turns the code into two linear passes.
cc: @aalexandrov 
-

Analysis use

---

src/expr/src/linear.rs

This PR has `MFP::optimize` continue as long as the AST complexity strictly decreases.
-

Iterate MFP optimization

---

Cargo.lock
misc/cargo-vet/audits.toml
src/cluster/src/server.rs

Update our dependency on differential dataflow to include the latest upstream changes. All changes are in https://github.com/MaterializeInc/differential-dataflow/commit/8797bfb01101db2168e0007aa7aa606bbd2deda5.
The change includes changes to avoid a heap allocation for every invocation of the exert logic.
-

Update differential dataflow

---

src/adapter/src/flags.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute/src/compute_state.rs
src/compute/src/containers/array.rs
src/compute/src/containers/mod.rs
src/compute/src/containers/stack.rs
src/compute/src/extensions/arrange.rs
src/compute/src/row_spine.rs
src/compute/src/typedefs.rs
src/sql/src/session/vars.rs
test/testdrive/introspection-sources.td

Chunked and fixed-length columnar containers.
This PR tries to replace `TimelyStack` with a type that regions-allocates the `local` portion of the timely stack to allow it being paged to disk. Currently, `TimelyStack` only allows regions that explicitly get their allocations from `lgalloc` to be spilled to disk, but nothing else. The types introduced in the PR additionally allow the local portion of the stack to go to disk.
For this, it introduces several new types:
* A *FixedStack* is similar to a TimelyStack, but can only absorb a fixed number of copies. We use it within the merge batcher.
* A *ChunkedStack* is similar to a TimelyStack but stores the local portion in *Array*, moving the local vector to spillable memory.
Additionally, we upgrade `lgalloc` and cease using its `Region` …

Chunked columnar stack

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select
src/sql/src/plan/transform_ast.rs
test/sqllogictest/arrays.slt

For PostgreSQL compatibility.
Fix #25530.
- Support using the `LIKE`, `NOT LIKE`, `ILIKE`, and `NOT ILIKE` as operators within `ANY`, `SOME`, and `ALL` expressions.

sql: support [NOT] [I]LIKE operators with ANY/ALL

---

src/expr/src/scalar.proto
src/expr/src/scalar/func.rs
src/expr/src/scalar/func/impls/array.rs
src/expr/src/scalar/func/impls/list.rs
src/sql/src/plan/typeconv.rs
test/sqllogictest/jsonb.slt

Materialize was not correctly handling arrays in `to_jsonb`. Instead of converting the arrays to JSON arrays, Materialize was converting them to a JSON string of the array's textual representation. This behavior was at variance with PostgreSQL.
The implementation is somewhat irritating, as the size of the array is not known at plan time. So the planner has to construct an expression to cast the array's element type and plumb that through to the dataflow layer, so that each value in the array can be cast to JSON at runtime.
This commit also adjust the implementation for lists in the same way, for symmetry, even though it's not required for PostgreSQL compatibility, as lists are a custom Materialize type.
Fix #12181.
- Fix the implementation of `to_jsonb` …

expr,sql: fix `to_jsonb` implementation for arrays

---

ci/qa-canary/pipeline.template.yml
ci/test/pipeline.template.yml

Seen in https://buildkite.com/materialize/qa-canary-environment-base-load/builds/14#018dd86c-5b30-4687-9458-ca55e0cb4f83
-

ci: Wait for build before starting QA canary base load

---

ci/mkpipeline.py
ci/release-qualification/pipeline.template.yml

in release qualification. Also use iterator in mkpipeline.py to reduce duplicate code
-

ci: Automatically fill commit and branch for preflight checks

---

misc/python/materialize/mzcompose/__init__.py
src/adapter/src/coord/ddl.rs
src/adapter/src/flags.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute/src/compute_state.rs
src/sql/src/session/vars.rs
test/cluster/mzcompose.py

Jemalloc profiling has been switched on for months now without a hitch, so it seems fine to remove the feature flag.
* This PR removes an old feature flag.
- N/A

*: remove the enable_jemalloc_profiling flag

---

test/sqlsmith/Dockerfile

Follow-up to https://github.com/MaterializeInc/materialize/pull/25373
-

SQLsmith: Support new explain syntax

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
src/balancerd/Cargo.toml
src/balancerd/src/lib.rs
src/balancerd/src/service.rs
src/balancerd/tests/server.rs
src/environmentd/src/lib.rs
src/server-core/src/lib.rs
src/workspace-hack/Cargo.toml

Teach server-core about a reloading ssl context. Use channels to request a reload and return the response. Situations where only one of the new cert or key is present and one previous file still present will return an error but not interrupt active serving.
Fixes #25059
- n/a

balancerd: reload ssl certs every hour

---

src/pgcopy/src/copy.rs
src/pgcopy/src/lib.rs
src/pgwire/src/protocol.rs

Adds a method for encoding a `Row` to csv. The actual encoding logic is taken from [here](https://github.com/MaterializeInc/materialize/compare/v0.68.3...benesch:materialize:copy-more?expand=1#diff-7a9592753ee463a8c8b47910f19f2ed6dd0c76d533831dd86b629b255d61a376R101). 
The encode method will be used for copying csv to S3 as part of #7256 
I have added some TODOs. The existing `CopyTextFormatParams` and the `Binary` formats can do with some refactors. I will do those in separate PRs to keep this PR as specific to the changes required for handling CSV.
cc @benesch @mjibson @petrosagg 
-

adapter: csv encoder for copy csv to s3

---

Cargo.lock
ci/test/cargo-test/mzcompose.py
src/aws-util/Cargo.toml
src/aws-util/src/lib.rs
src/aws-util/src/s3_uploader.rs
src/aws-util/src/setup_test_env_mz.sh
src/workspace-hack/Cargo.toml

This is a s3 multi part uploader helper. Eventually the goal is, this will be used by the CopyToS3Oneshot compute sink to upload the snapshot to s3 ([design doc reference](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20231117_copy_to_s3.md#multi-part-uploads-to-s3)). 
This is specifically written in a way, where the total number of parts of a file is not known beforehand. As data arrives, the uploader will buffer the data to a configured `part_size_limit` before uploading a part.
S3 multi part uploader to be used by https://github.com/MaterializeInc/materialize/issues/7256
Have commented inline.
I kept this in existing mz_aws_util crate. Happy to move it to a new or a different crate if required.
cc @guswynn @petrosagg @benesch 
-

S3 multi part uploader

---

src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/statement_logging.rs

This PR ensures that:
* If the coordinator detects that several "watch sets" finished at the same time, then they are recorded at the same time
* A statement ended execution event is recorded at the same time as the corresponding `finished_at` time in the activity log
Possibly inconsistent timestamps between various statement events
- None

Lifecycle logging: reduce opportunities for timestamp inconsistency

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_await.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_wait.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/await_cluster_ready.sql
misc/dbt-materialize/tests/adapter/test_deploy.py

Extract the await logic from `deploy_wait` to it's own macro. I also added some test cleanups to remove flakes. 
-

dbt-materialize: extract await logic from deploy_wait

---

src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
test/sqllogictest/materialized_views.slt

There is no need to acquire any read holds when EXPLAINing a materialized view. In fact, it was causing a problem when using `EXPLAIN REPLAN`: For MVs with `REFRESH AT CREATION`, we tried to acquire a read hold at the original creation time, which was not possible, and therefore we were failing the `EXPLAIN REPLAN`.
Note that the read hold acquisition in `resolve_mz_now_for_create_materialized_view` already had this behavior that it's not acquiring read holds if we are in an EXPLAIN, so this PR just modifies `create_materialized_view_validate` to have the same behavior.
-

Don't acquire read holds when EXPLAINing a REFRESH MV

---

misc/python/materialize/checks/scenarios.py
misc/python/materialize/checks/scenarios_upgrade.py

This fixes https://buildkite.com/materialize/nightlies/builds/6624#018dea8e-d281-438a-aaa2-d2e389db6db4.
Nightly: https://buildkite.com/materialize/nightlies/builds/6626
@umanwizard:
> it's expected that we lose history whenever a new column is added to the objects. We recently added the mz_version column to mz_statement_execution_history

tests: preflight check with continue upgrade: exclude StatementLogging for 0.89.2

---

src/environmentd/tests/testdata/http/post
src/environmentd/tests/testdata/http/ws
src/interchange/src/json.rs
test/testdrive/kafka-json-sinks.td

Previously, the HTTP and WS API would return TIMESTAMPs and TIMESTAMPTZs with only millisecond precision, even though internally and via the pgwire API we represent these types with microsecond precision. This commit updates the HTTP and WS API to return microsecond precision.
To avoid issues of compatibility with current users, the microsecond portion of the timestamp is stored as a decimal. For example, previously `TIMESTAMP '2023-12-19T06:50:37.123456 '` would return `"1703011837123"`, now it returns `"1703011837123.456"`.
An alternative implementation that used arbitrary precision decimals (the `Numeric` type in mz_repr) was explored, but the performance was 2-4x slower than the current implementation.
Fixes #24026
- Add microsecond precision to …

sql: Fix timestamp precision in HTTP API

---

Cargo.lock
src/adapter/src/config/params.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/error.rs
src/adapter/src/session.rs
src/sql/Cargo.toml
src/sql/src/session/vars.rs
src/sql/src/session/vars/constraints.rs
src/sql/src/session/vars/definitions.rs
src/sql/src/session/vars/errors.rs
src/sql/src/session/vars/polyfill.rs
src/sql/src/session/vars/value.rs

This PR refactors Session and System variables to remove the generic parameter `V` from their definition, which should make them a bit easier to work with because we remove a layer of indirection by no longer needing the `SessionVarMut` and `SystemVarMut` traits that we'd use to create trait objects.
The main idea here is `VarDefinition` (formerly known as `ServerVar<V>`) is no longer generic over a type `V` and hides away all of the generic-ness using static function pointers. `VarDefinition::new<V:Value>` is generic over some type `V: Value`, and at construction time we store a function pointer to `V`'s parse method. This prevents the need for `VarDefinition` to be generic over some type `V`, while retaining the ability to guarantee all of the values we parse are the correct type. Also …

sql: Refactor Variables

---

doc/user/content/sql/create-source/webhook.md
src/sql/src/lib.rs

This PR increase the default limit for concurrent webhook requests to 500. Note, I'll also make this change via LaunchDarkly so the docs can get updated immediately.
We've made perf improvements since releasing webhooks and this is a reasonable limit.
- Increases the rate limit at which users can send us webhook requests

webhooks: Bump default limit to 500 concurrent requests

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Release dbt-materialize v1.7.4, which supports automatic blue/green deployments.
See `CHANGELOG.md` for an overview of the release.

dbt-materialize: release 1.7.4

---

doc/developer/guide-changes.md

As we no longer release the binary off `main`, remove the reference from the changes developer guide.
I think mentioning the binary here could result in a confusion from engineers who are just getting started with Materialize. Additionally, the referenced URL was broken.
- There are no user facing behavior changes

Remove a reference to the binary distribution from the dev guide

---

src/catalog/src/durable/impls/persist.rs
src/catalog/src/durable/upgrade.rs

Previously, when a savepoint persist catalog would run data schema migrations, the migrations were incorrectly applied to disk instead of just being applied in memory. This commit fixes the issue by only applying the migrations in memory.

catalog: Fix persist savepoint upgrades

---

src/adapter/src/command.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/util.rs
src/environmentd/src/http/sql.rs
src/sql/src/plan.rs
src/sql/src/plan/statement.rs

Possibly useless refactor, but I saw it and got annoyed.
- n/a

adapter: don't allocate vecs for response kinds

---

test/canary-environment/README.md
test/canary-environment/dbt_project.yml
test/canary-environment/models/mysql_cdc/mysql_cdc.sql
test/canary-environment/models/mysql_cdc/mysql_wmr.sql
test/canary-environment/models/mysql_cdc/schema.yml
test/canary-environment/mzcompose.py
test/canary-load/mzcompose.py

Currently fails because enable_mysql_source isn't set for the Canary environment @rjobanp Can we already enable it or are there concerns?
Part of https://github.com/MaterializeInc/materialize/issues/24927
-

qa canary env: Add MySQL source

---

misc/python/materialize/sqlsmith.py

Seen in https://buildkite.com/materialize/nightlies/builds/6630#018ded1f-b19b-4996-a09f-9603a652c86c.
Reduced to
```
materialize=> SELECT pg_catalog.to_timestamp('NaN'::float8);
ERROR:  timestamp cannot be NaN
```
Same behavior in Postgres:
```
postgres=# SELECT pg_catalog.to_timestamp('NaN'::float8);
ERROR:  timestamp cannot be NaN
```

tests: sqlsmith: add ignore for NaN timestamp

---

doc/user/content/integrations/cube.md

With https://github.com/cube-js/cube/pull/7773 now merged, updating the Cube.js integration guide to add the newly added `CUBEJS_DB_MATERIALIZE_CLUSTER` environment variable.

Doc: Add cluster name conf to Cube.js guide

---

misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
misc/python/materialize/cloudtest/k8s/testdrive.py

Seen in https://buildkite.com/materialize/nightlies/builds/6627#018debd5-c1bd-4a12-8bac-19cc5efa7368:
```
Traceback (most recent call last):
File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-0a856e4a363f16ab9-1/materialize/nightlies/test/cloudtest/test_full_testdrive.py", line 29, in test_full_testdrive
mz.testdrive.run(f"testdrive/{file_pattern}")
File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-0a856e4a363f16ab9-1/materialize/nightlies/misc/python/materialize/cloudtest/k8s/testdrive.py", line 82, in run
self._run_internal(
File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-0a856e4a363f16ab9-1/materialize/nightlies/misc/python/materialize/cloudtest/k8s/testdrive.py", line 167, in _run_internal
error_chunks = …
```

tests: testdrive in cloudtests: capture output for error extraction

---

src/expr/src/linear.rs
src/transform/src/canonicalize_mfp.rs
test/sqllogictest/not-null-propagation.slt
test/sqllogictest/transform/aggregation_nullability.slt
test/sqllogictest/transform/column_knowledge.slt
test/sqllogictest/transform/is_null_propagation.slt
test/sqllogictest/transform/threshold_elision.slt
test/sqllogictest/transform/union.slt
test/testdrive/primary-key-optimizations.td

This PR modifies MFP canonicalization, pushing them through Negate (and often lifting the Negate to a Union). This should come at no cost, as Negate does not modify the collection of records, and the intent is to open up better MFP reasoning by consolidating more together.
-

Canonicalize MFPs below Negates

---

Cargo.lock
src/adapter/src/coord/sequencer/cluster.rs
src/ore-instrument-macro/Cargo.toml
src/ore-instrument-macro/src/lib.rs
src/storage-controller/src/lib.rs

Uses `quote!` to make sure we get good error locations
tested with a real compilation error locally, as well as ensured with `cargo expand` that `fields()` get kept
@mjibson we probably want to add an assert on a field value being passed through in your tracing testing pr!
-

ore: fix error locations with mz_ore::instrument

---

src/persist-client/src/internal/state_versions.rs

https://github.com/MaterializeInc/materialize/issues/25015
I'm not confident that this is actually the issue from that ticket, but I have low enough confidence in the old assertions that I don't feel like they're especially indicative of a bug, so I think it's worth updating them regardless.
- The empty antichain is sorted lower than any other antichain, not higher as you'd expect. (The lower is never the empty antichain, but this can happen for the upper.)
- The second block of tests would look at the upper of the largest batch, which is not guaranteed to be the batch with the largest upper. (Particularly given the above!)
Additionally, the result of the `PartialOrder` call in these tests was unused. It was unclear to me what the intent of those calls was; I've removed them here.
-

[persist] Track the actual upper in validations

---

src/storage/src/source/mysql.rs
test/mysql-cdc/mysql-cdc.td
test/mysql-cdc/schema-restart/after-restart.td

Seed the mysql source health status as running to avoid user confusion.
This PR is the same implementation as the corresponding postgres source PR: https://github.com/MaterializeInc/materialize/pull/24471
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/25416
-

storage/mysql: Set MySQL source to running on render

---

src/expr/src/linear.rs

`MFP::optimize` had set up the wrong initial condition to perform more than one iteration, which is now fixed.
-

MFP::optimize failed to iterate

---

Cargo.lock
src/balancerd/Cargo.toml
src/balancerd/src/lib.rs
src/balancerd/src/service.rs
src/balancerd/tests/server.rs

Use a specified directory to which files containing DNS addresses will be written for cancellation.
See https://github.com/MaterializeInc/materialize/issues/24081#issuecomment-1942928294
- n/a

balancerd: use configmap-based cancellation scheme

---

ci/test/pipeline.template.yml

ci: Add shard number for "Checks without restart or upgrade"

---

ci/test/pipeline.template.yml

To reduce memory consumption from many clusterds. More clusters are implicitly created by the new sources introduced in https://github.com/MaterializeInc/materialize/pull/25564
-

platform-checks: More parallelism to reduce memory consumption

---

src/mysql-util/src/decoding.rs
test/mysql-cdc/alter-table-after-source.td
test/mysql-cdc/alter-table-irrelevant.td

* This PR fixes a recognized bug. Fixes: https://github.com/MaterializeInc/materialize/issues/25066 and https://github.com/MaterializeInc/materialize/issues/25451
@nrainer-materialize I uncommented all the test cases that correspond to those 2 issues ^. The first one is fixed by the code change here to ignore additional columns that we don't need to ingest, and the other seemed to work once I uncommented it too.
-

storage/mysql: Alter table fixes; don't error if ignored column is detected

---

misc/python/materialize/data_ingest/data_type.py
misc/python/materialize/data_ingest/executor.py
misc/python/materialize/data_ingest/workload.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
test/data-ingest/mzcompose.py
test/parallel-workload/mzcompose.py

Part of https://github.com/MaterializeInc/materialize/issues/24927
-

mysql tests: Add in data-ingest and parallel-workload test frameworks

---

src/adapter/benches/catalog.rs
src/adapter/src/catalog.rs
src/adapter/src/catalog/open.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/error.rs
src/adapter/tests/sql.rs

In preparing for the storage collection metadata being moved to the persist catalog, I want to have maximum flexibility in exploring the catalog transaction API.
I noticed that it was possible to entire factor away `CatalogTxn` by moving the DDL dry run into an `Op`. I think `CatalogTxn` was heavily used before to ensure dataflow descriptions were valid, but the code has since moved away from that pattern, making the method mostly vestigial.
-

adapter: refactor some catalog txn APIs

---

src/catalog/src/builtin.rs

I used https://materialize.com/docs/sql/system-catalog/mz_internal/#mz_dataflow_arrangement_sizes to check typical sizes for these 2 indexes without retained history, and they were < 1 MB. If a user recreates their sources/indexes everyday, we can expect these numbers to be multiplied by 60ish, which should be totally fine.
This partially unblocks https://github.com/MaterializeInc/materialize/issues/25501, as users can subscribe to a join between these tables to aggregate client-side.
-

storage/catalog: retain mz_sources and mz_object_dependencies for 30 days

---

src/environmentd/src/bin/environmentd/main.rs

The persist catalog has been rolled out to all environments, so this commit updates the default catalog store to persist.
Part of #24218

adapter: Update default catalog store to persist

---

Cargo.lock
misc/cargo-vet/config.toml
src/adapter/src/flags.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute/Cargo.toml
src/compute/src/compute_state.rs
src/compute/src/row_spine.rs
src/metrics/Cargo.toml
src/metrics/src/lgalloc.rs
src/ore/Cargo.toml
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs

Update lgalloc to 0.2.0. This allows us to:
* Expose metrics about physical and virtual memory related to files, giving us more insights about what portion of the memory managed by lgalloc is in memory, and what portion is in use.
* Eager returning of physical memory (eager_return) without punching holes into files. This is a significantly cheaper approach than always punching holes into files.
Fixes #24271.
-

Update lgalloc, expose metrics, conditionally enable eager_return

---

src/adapter/src/flags.rs
src/environmentd/tests/server.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/storage-controller/src/collection_mgmt.rs
src/storage-controller/src/lib.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs

The storage controller manages the collections that back webhooks, as well as some system collections, e.g. builtin sources. These collections each have a `tokio::task` that pulls updates off of a channel and then pushes the writes to a Persist handle. We currently have a "batch interval" where we'll wait 1 second from the start of a write before pulling more updates off the channel. This PR makes that interval configurable for user owned collections, which currently are just webhooks.
Note: we only apply this dynamic interval to user collections because there is currently no need to decrease the latency for system collections.
Have the ability to reduce latency for webhooks, with the tradeoff of increased CRDB traffic.
- Gives us a knob to tune webhook latency

webhooks: Make batch interval configurable via LaunchDarkly

---

Cargo.lock
misc/python/materialize/cloudtest/util/authentication.py
misc/python/materialize/cloudtest/util/jwt_key.py
misc/python/materialize/cloudtest/util/sql.py
misc/python/materialize/cloudtest/util/web_request.py
misc/python/materialize/mzcompose/services/frontegg.py
src/balancerd/tests/server.rs
src/environmentd/tests/auth.rs
src/frontegg-auth/src/auth.rs
src/frontegg-mock/Cargo.toml
src/frontegg-mock/src/lib.rs
src/frontegg-mock/src/main.rs
test/balancerd/mzcompose.py

* Ports frontegg-mock to axum.
* Adds support for more frontegg endpoints, which are used by the cloud repo's tests.
* Adds support for verifying TLS against a different hostname, which will be used in the cloud repo tests.
* Improves consistency between Kind and non-Kind configurations.
Pre-requisites for tests in the cloud repo.
https://github.com/MaterializeInc/cloud/issues/7522
Not a release blocker, but is required for the tests in https://github.com/MaterializeInc/cloud/pull/8824
- no user-facing behavior changes.

Port frontegg-mock to axum, and implement features needed for kind tests in the cloud repo

---

misc/python/materialize/data_ingest/executor.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py

Noticed here that we are missing some data-ingest logs: https://materializeinc.slack.com/archives/C01LKF361MZ/p1709222602231569
-

data-ingest: Accept logger from parallel-workload

---

test/mysql-cdc/alter-table-after-source.td

See https://github.com/MaterializeInc/materialize/issues/25660 for details of the issue. This recently flaked in https://buildkite.com/materialize/tests/builds/77168#018df70d-b789-403d-ad26-281d4b4e743c
-

Disable flaky mysql test case around detecting column drop/recreates

---

src/aws-util/Cargo.toml

Remove unused features from deps in aws-util.
Things are pulling extra unused stuff. This causes problems for the cloud repo, when trying to bump our submodule.
- No user-facing behavior changes.

remove unused features from deps in aws-util

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

Bumps the version on main to `v0.91.0-dev`
v0.90 release
- N/a

release: bump to version v0.91.0-dev

---

src/storage-client/src/statistics.rs
test/cluster/gh-25633/01-create-source.td
test/cluster/gh-25633/02-after-environmentd-restart.td
test/cluster/mzcompose.py

When we unpack `rehydration_latency_ms`, we accidentally don't divide it back into micros. _This means everytime envd restarts, we multiply the rehydration latency by 1000._ This is overridden by the next time a source is rehydrated.
This is not unsafe because:
- It doesn't cause negative multiplicities or break the 
- In release mode, we won't panic after restarting enough times and overflowing during multiplication
For this reason I don't think we need a backport, but we do want to fix this before the next release. Working on a test now.
Fixes https://github.com/MaterializeInc/materialize/issues/25633
-

storage/statistics: fix rehydration latency being multiplied by 1000

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py

parallel-workload: Remove mz_sleeps again

---

src/adapter/src/coord/sequencer/inner.rs
src/repr/src/explain/tracing.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/explain
src/sql/src/plan.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/rbac.rs
test/sqllogictest/explain/bad_explain_statements.slt

Add parser and planner support for the following `EXPLAIN ... VIEW` statements:
- `EXPLAIN CREATE VIEW ...`
- `EXPLAIN REPLAN VIEW ...`
- `EXPLAIN VIEW ...`
https://github.com/MaterializeInc/materialize/issues/25273
As part of the changes I:
1. Rename `ExplainStage::{OptimizedPlan ⇒ GlobalPlan}` and `NamedPlan::{Optimized ⇒ Global}`.
1. Introduce new enum variants `ExplainStage::LocalPlan` and `NamedPlan::Local` that correspond to the `optimize/local` stage and teach the parser to support this stage for the variants introduced above.
The implementations will be included in a follow-up PR.

explain,sql: support `EXPLAIN ... VIEW` variants

---

misc/python/materialize/mzcompose/composition.py

`str(type(e))` resulted in `<class pg8000.exceptions.InterfaceError>`, which is suppressed by Buildkite due to the angle brackets as can be seen in
This change should improve the output.

ci: improve exception name extraction

---

src/adapter/src/coord/timeline.rs

adapter: fix clippy lint (merge skew related to removal of legacy timestamp oracle)

---

test/mysql-cdc/truncate-table.td

* This PR fixes a recognized bug. Fixes: https://github.com/MaterializeInc/materialize/issues/25051
Close the following issue by enabling the test to validate that we put the source into an error state on truncation. In the future we will attempt to support the truncate command: https://github.com/MaterializeInc/materialize/issues/25122
-

storage/mysql: Enable truncate table test

---

misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
misc/python/materialize/output_consistency/input_data/values/date_time_values_provider.py
misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py

> 02e3d4b6e1 output consistency: date-time: add leap year values
3fe5153054 output consistency: date-time: DST values
Inspired by https://github.com/MaterializeInc/materialize/issues/25642.
Nightly: https://buildkite.com/materialize/nightlies/builds/6716

output consistency: special date values

---

ci/nightly/pipeline.template.yml
misc/python/materialize/cloudtest/app/materialize_application.py
misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
misc/python/materialize/cloudtest/k8s/mysql.py
test/cloudtest/test_upgrade.py
test/mysql/Dockerfile
test/mysql/mzbuild.yml

Part of https://github.com/MaterializeInc/materialize/issues/24927.
Nightly: https://buildkite.com/materialize/nightlies/builds?branch=nrainer-materialize%3Atests%2Fmysql-platform-in-cloudtests

 cloudtests: enable MySql tests in upgrade test 

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/scenarios_upgrade.py

As noted by @jkosh44 in https://github.com/MaterializeInc/materialize/pull/25636
-

platform-checks: Remove scenario that skips a version

---

src/adapter/src/catalog/open.rs

adapter: Remove old migration

---

bin/mzexplore
misc/python/materialize/cli/mzexplore.py
misc/python/materialize/mzexplore/__init__.py
misc/python/materialize/mzexplore/common.py
misc/python/materialize/mzexplore/extract.py
test/persist-catalog-migration/mzcompose.py

`bin/mzexplore` can extract `EXPLAIN PLAN` output as text.
This PR adds a flag `--format [FORMAT]` that lets you get JSON output.
Along the way, there are a few minor bugfixes.
This is take 2; I messed up the history of #25435.
See the first two commits: there was a copypasta mistake in docs; the help text for `bin/mzexplore extract --help` gave incorrect output for `plans`. The third commit and also fixes an issue that led to `..txt` suffixes in generated plans.
Running `bin/mzexplore extract plans --format json ...` will extract plans in JSON format.
-

compute: add JSON explain output for bin/mzexplore (take 2)

---

misc/python/materialize/version_list.py

This commit marks version v0.89.7 as broken since CI failed and it was never deployed on docker.

test: Fix broken upgrade tests

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/explain/mod.rs
src/adapter/src/optimize/view.rs
test/sqllogictest/explain/view.slt

Add coordinator support for sequencing the following `EXPLAIN ... VIEW`
statements:
- `EXPLAIN CREATE VIEW ...`
- `EXPLAIN REPLAN VIEW ...`
- `EXPLAIN VIEW ...`
Part of #25273.
Review one commit at a time. The bulk of the work for this PR is in the first commit, followed by three commits that move code around and expand the set of stages supported by `EXPLAIN MATERIALIZED VIEW`. The final commit adds an `EXPLAIN VIEW` test.
- Added support for explaining view-related statements: `EXPLAIN ... VIEW`, `EXPLAIN ... REPLAN VIEW`, `EXPLAIN ... CREATE VIEW`.

explain,coord: implement `EXPLAIN ... VIEW` variants

---

Cargo.lock
misc/cargo-vet/config.toml

Bump decnumber-sys from 0.1.5 to 0.1.6

---

misc/python/materialize/version_list.py
test/persist-catalog-migration/mzcompose.py

This uses versions from docs instead of git tags, which makes the build reproducible regardless of any build tags, which might change over time.

tests: persist catalog migration: use versions from docs

---

ci/nightly/pipeline.template.yml
ci/slt/pipeline.template.yml
ci/test/lint-main/checks/check-mzcompose-files.sh
ci/test/pipeline.template.yml
test/chbench/mzcompose.py
test/cloud-canary/mzcompose.py
test/debezium/mzcompose.py
test/limits/mzcompose.py
test/mz-e2e/mzcompose.py
test/persistence/mzcompose.py
test/sqllogictest/mzcompose.py

98bfd51467 lint: check mzcompose files: add logic
8ccc3c164e lint: check mzcompose files: add ignores
0f0c76696d tests: cloud-canary: rename function
60d352bc77 tests: mz-e2e: rename function
21a42a7bdd tests: persistence: align default workload
b1e672c166 tests: limits: new default entry point
e89deaf387 tests: chbench: new default entry point
9164e2d71c tests: debezium: new default entry point
a8c1d8ae04 tests: slt: new default entry point
```
--- check_default_workflow_references_others
./test/sqllogictest/mzcompose.py contains more than one workflow but does not seem to loop over the workflows
Use this pattern in the default workflow:
for name in c.workflows:
if name == "default":
continue
with c.test_case(name):
c.workflow(name)
^^^ 🚨 Failed: check_default_workflow_references_others …
```

lint: decrease risk of unused mzcompose workflows

---

doc/user/layouts/partials/head.html

Deleting a deactivated user caused the docs search to stop working, since the API key used was associated with the user. Replacing with a working key, in the meantime — though we should add a service account to Algolia and generate keys through that account instead of individual users.

doc/user: patch search

---

src/ccsr/src/client.rs
src/ccsr/src/config.rs
src/interchange/src/avro/schema.rs
src/ore/src/future.rs
src/storage/src/decode/mod.rs

Part of: https://github.com/MaterializeInc/materialize/issues/25707
-

storage: perform csr operations off the timely thread

---

LICENSE
README.md
doc/user/content/integrations/python.md

We've had several reports of users getting confused by our README and come away thinking that Materialize is primarily a single node system with no fault tolerance or horizontal scalability.
This commit is a small reconfiguration of our README to minimize that confusion.
It also bundles some other small improvements:
* More links to contact us and join our Slack
* A fix to the contact us link in the LICENSE file
* Clarification that `HAVING` is not an aggregate function
* Use of the correct "good for external contributors" label
* Less dire warnings about using ORMs, since we've gotten increasingly good at supporting ORMs over the years
* This PR refactors existing documentation.
- n/a

README: update wording to feature cloud more heavily

---

src/storage-operators/src/persist_source.rs

https://github.com/MaterializeInc/cloud/issues/8791
I don't love this, since I think it will make any errors quite hard to debug in practice. But it seems like all the contents of this log might report more data than we're comfortable with without additional redactions.
-

[persist/storage] Remove some specific data from the filter-pushdown log

---

src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/schemas.rs
src/storage/src/source/mysql/snapshot.rs
test/mysql-cdc/mysql-cdc.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/25415
In MySQL backticks ` are used to quote system identifiers with special characters, unlike Postgres/MZ which uses double-quotes ".
I originally tried to implement a fix using the `mz_sql_parser::ast` `Ident` and `UnresolvedItemName` types but found it difficult to modify the behavior to support the different quoting style and realized that we don't need a lot of the functionality provided by those types. To keep things simple, I switched to a mysql-specific type for describing and serializing the schema/table names.
-

storage/mysql: Support special characters in mysql table names

---

src/environmentd/tests/server.rs

Fix some merge skew introduced by https://github.com/MaterializeInc/materialize/pull/25664
```
error[E0061]: this function takes 9 arguments but 8 arguments were supplied
--> src/environmentd/tests/server.rs:1987:27
|
1987 |     let frontegg_server = FronteggMockServer::start(
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^
...
1993 |         SYSTEM_TIME.clone(),
|         ------------------- an argument of type `std::option::Option<BTreeMap<std::string::String, Vec<std::string::String>>>` is missing
|
```
- No user-facing behavior changes.

Fix frontegg-mock merge skew in the tests

---

src/environmentd/src/lib.rs
src/pgwire/src/metrics.rs
src/pgwire/src/server.rs

Needed to disambiguate external and balancer connections, so we can tell when folks are using the balancer.
- n/a

environmentd: add balancer label to mz_connection_status

---

misc/python/materialize/sqlsmith.py

seen in https://buildkite.com/materialize/nightlies/builds/6733#018dfc94-0f69-4087-b0e6-1c60a54d1fe1
-

parallel-workload test: Ignore recursion limit error in SQLsmith

---

doc/developer/testdrive.md
misc/python/materialize/feature_benchmark/executor.py
misc/python/materialize/mzcompose/services/testdrive.py
src/testdrive/src/action.rs
src/testdrive/src/action/consistency.rs
src/testdrive/src/action/sql.rs
src/testdrive/src/bin/testdrive.rs
src/testdrive/src/lib.rs
test/cluster-isolation/mzcompose.py
test/pg-cdc/status/04-drop-publication.td
test/testdrive/connection-alter.td
test/testdrive/connection-create-drop.td
test/testdrive/connection-validation.td
test/testdrive/mz-depends.td
test/testdrive/mzcompose.py
test/testdrive/tables.td
test/testdrive/webhook.td

I think we should get this in again, even if we don't understand the test flakiness. So I added two sleeps for now, but will keep the issue open for a proper fix.
-

Revert "Revert "testdrive: Refactor consistency checks, add leaked shard check (#25306)""

---

src/compute/src/compute_state.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/snapshot.rs

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/25582
The bug was caused by a `table_id_map` I had created to store a cache of binlog-table-ids (u64 value) --> table-schema/name (vec of strings) to avoid a couple of extra string clones on each event we receive on the replication stream. 
It turns out that the table-id mappings will change after mysql rotates its binary logs, even during the course of long-running replication connection.
This removes that unnecessary optimization and adds some additional tracing that was used during debugging.
I was replicating the issue using `bin/mzcompose --find zippy down -v && bin/mzcompose --find zippy --dev run default --scenario=MySqlCdc` and confirmed that this fix allows that test scenario to continue …

storage/mysql: Fix non-positive accumulation bug caused by incorrect caching behavior

---

src/storage/src/metrics/source/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/replication/partitions.rs

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/25725
I'm not sure how to test this -- when I run the mysql-cdc tests and look at the metrics at `localhost:6878/metrics` I don't see any of the storage metrics included. Any ideas?
-

storage/mysql: Add metrics to mysql source

---

src/compute/src/compute_state.rs
src/sql/src/session/vars.rs

Update the `enable_compute_chunked_stack` flag when it changes.
Previously, we didn't notify the replica of changes to the chunked stack flag,
meaning it would not be picked up consistently. This fixes an unreported issue
-

Update chunked stack setting on flag change

---

misc/python/materialize/version_ancestor_overrides.py

Seen in https://buildkite.com/materialize/nightlies/builds/6765#018e0e98-e523-44a8-8f9a-367739d2d9dd
-

feature-benchmark: Ignore performance regressions from JoinFusion

---

src/adapter/src/coord.rs
src/adapter/src/util.rs
src/compute-client/src/controller/error.rs
src/compute-client/src/controller/instance.rs
test/cluster/mzcompose.py

To prevent rehydration of MVs after their last refresh (https://github.com/MaterializeInc/materialize/issues/25380), this PR allows `bootstrap_materialized_view_as_of` to create an MV dataflow with an empty `as_of` (which is the state of MVs after their last refresh). It also tweaks `create_dataflow` to entirely skip creating a dataflow in this case (as per @teskje), to avoid [issues](https://github.com/MaterializeInc/materialize/pull/25353) with actually running a dataflow that has an empty `as_of`.
Note that, surprisingly, the original issue is no longer occurring on main! However, I think we should still go through with this PR, because it's probably brittle whether the issue is happening on main or not. (It might depend on little details of how exactly the Persist source gives us the …

For an MV with empty `as_of`, don't even create a dataflow

---

doc/user/content/ingest-data/postgres-alloydb.md
doc/user/content/sql/create-source/postgres.md

And use some fancy CSS to wrap the list to three columns, to avoid taking up too much vertical space in the docs.
* This PR adds a feature requested twice on Slack recently.
- n/a

doc/user: document supported PostgreSQL types

---

src/environmentd/src/http.rs
src/environmentd/src/http/metrics.rs
src/environmentd/src/lib.rs
src/environmentd/tests/server.rs

Add a metric label for the http server source so we can tell apart balancer from external traffic.
- n/a

environmentd: disambiguate external vs balancer in http metrics

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/ci_utils.sql
misc/dbt-materialize/tests/adapter/test_deploy.py

By default, `deploy_init` will fail if the schema or cluster already exists and contains user defined objects. However, we don't want this check to run if someone is working on a PR and pushing to the same branch multiple times. Unforunately, github actions are not expressive enough to only run a command once. So instead, we tag each schema and cluster with a comment based on a CI environment variable on creation. If set, the checks will be skipped on subsequent invocations. 
-

dbt-materialize: skip deploy_init checks if under CI and pushing to the same PR

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
src/adapter/src/client.rs
src/adapter/src/notice.rs
src/environmentd/Cargo.toml
src/environmentd/tests/server.rs
src/sql/src/session/vars.rs
src/workspace-hack/Cargo.toml

This PR adds a notice that gets emitted at the time of connection/session startup if the default cluster does not exist, the logic is as follows:
1. If the user already has a session variable set for cluster (e.g. via connection params) do not emit a notice
2. If the active cluster does not exist, and the user does not have a role default, suggest they set one. If they already have a role default, suggest they modify it.
It also updates the welcome message to include `(does not exist)` next to the cluster name. For example, after dropping the "quickstart" cluster and connecting with a regular user:
```
$ psql "postgres://materialize@localhost:6875/materialize"
NOTICE:  connected to Materialize v0.91.0-dev
Org ID: 42df3f87-3067-4f2f-9052-274b340c5379
Region: local/az1
User: materialize …
```

sql: Emit notice if default cluster for role does not exist

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
src/balancerd/src/lib.rs
src/balancerd/src/service.rs
src/balancerd/tests/server.rs
src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/http.rs
src/environmentd/src/lib.rs
src/environmentd/tests/auth.rs
src/environmentd/tests/server.rs
src/frontegg-auth/Cargo.toml
src/frontegg-auth/src/app_password.rs
src/frontegg-auth/src/auth.rs
src/frontegg-auth/src/client/tokens.rs
src/frontegg-auth/src/error.rs
src/frontegg-auth/src/lib.rs
src/frontegg-auth/src/metrics.rs
src/frontegg-mock/src/lib.rs
src/ore/Cargo.toml
src/ore/src/lib.rs
src/ore/src/time.rs
src/pgwire/src/protocol.rs
src/pgwire/src/server.rs

This PR refactors our Frontegg authentication code, it's based on https://github.com/MaterializeInc/materialize/pull/25409.
We make a few notable changes here:
1. We stop using Refresh Tokens, instead use the initially provided App Password to continuously check if the auth session is still valid.
* Previously our authentication flow would get a JWT which would provide a refresh token that we would periodically send to Frontegg to keep the session alive and make sure the user wasn't deleted. These refresh tokens were fragile though and caused incident-98.
2. Further de-duplicate authentication requests by allowing new sessions to attach to an existing auth session.
* Whenever we exchange an App Password for a token, we create an "authentication session" and if another SQL session is …

auth: Refactor Frontegg Auth to not use refresh tokens

---

src/storage-controller/src/lib.rs
test/pg-cdc/statistics.td

Closes: https://github.com/MaterializeInc/materialize/issues/22235
-

storage: correctly initialize source statistics on ALTER SOURCE ADD SUBSOURCE

---

src/storage-client/src/client.rs
src/storage/src/healthcheck.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/source_reader_pipeline.rs
test/mysql-cdc/alter-table-after-source.td
test/mysql-cdc/schema-restart/after-restart.td
test/pg-cdc/mzcompose.py
test/testdrive/kafka-recreate-topic.td

The design of the ceased status was predicated on definite errors from sources being irretractable. However, in the case of definite but not "fatal" errors, such as ingesting an value that overflows its target type in decoding, we want to let users retract the value to reveal the successful values.
Because some users might still have the ceased status in their status collections, we cannot remove it wholesale. Instead, no longer issue the ceased status and do not privilege it in the status FSM.
This PR refactors existing code. I filed an issue to re-design this feature in #25768
-

storage: gently remove ceased status

---

misc/python/materialize/cli/ci_annotate_errors.py

Seen in https://buildkite.com/materialize/coverage/builds/385
-

ci: Improve annotation for code coverage

---

Cargo.lock
src/adapter/src/flags.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute-types/Cargo.toml
src/compute-types/src/dataflows.proto
src/compute-types/src/dataflows.rs
src/compute-types/src/dyncfgs.rs
src/compute-types/src/lib.rs
src/compute/Cargo.toml
src/compute/src/compute_state.rs
src/compute/src/render/context.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/join/mod.rs
src/compute/src/render/mod.rs
src/dyncfgs/Cargo.toml
src/dyncfgs/src/lib.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs

This PR takes the dyncfg already plumbed through to `clusterd` processes and generalizes it so that it can be used by compute workers, in addition to persist. It then migrates some of the compute config parameters to dyncfg.
Some compute parameters are not ported here, for various reasons:
* `max_result_size` is a public `ServerVar` are the current dyncfg infrastructure support only internal ones.
* `compute_dataflow_max_inflight_bytes` has type `Option<usize>` and there is not `ConfigType` implementation for `Option` values.
I recommend looking at the commits separately!
- N/A

Start using dyncfg for compute configuration

---

Cargo.lock
misc/cargo-vet/config.toml
src/workspace-hack/Cargo.toml

As seen in https://buildkite.com/materialize/security/builds/1160#018e0f32-9491-4dfe-bd12-6056c38c1213
-

Bump mio version from 0.8.8 to 0.8.11

---

src/persist-client/src/internal/state_versions.rs

This comes up often enough during dev and testing that it's worth making it more self-service.
Closes #25460.
-

persist: add context to the "expects earliest live diff to advance" log

---

src/dyncfg/Cargo.toml
src/dyncfg/src/dyncfg.proto
src/dyncfg/src/lib.rs
src/sql/src/session/vars.rs

While I'm in here, fix the Shared type for `usize` to `AtomicUsize` instead of `AtomicU64`. Not sure how that happened.
-

dyncfg: add support for `Option<usize>` configs

---

src/compute-types/src/dyncfgs.rs
src/compute/src/compute_state.rs
src/compute/src/render/mod.rs
src/compute/src/sink/persist_sink.rs

Replicas in cc sizes use lgalloc with persist, which is intended to replace this backpressure. Use a separate dyncfg, so existing users of the backpressure, don't rely on it when re-sizing to the cc sizes.
It's possible that this has already happened, but given that cc sizes are prpr, we're okay with that. This new config can be used to get them working again, but we'll have to get them to resize.
-

compute: use a separate dyncfg for persist_source backpressure on cc

---

Cargo.lock
src/storage-operators/Cargo.toml
src/storage-operators/src/persist_source.rs

This will make alerts for instances of audit failures less brittle (i.e. not based on the panic message).
Closes #25776
The tag(s) used is just a strawman. Gonna hash out the exact set in slack.
-

persist: add a sentry tag to the pushdown audit panic

---

src/mysql-util/src/decoding.rs
src/mysql-util/src/schemas.rs
test/mysql-cdc/types-json.td

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/24796
-

storage/mysql: Add support for real json type

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/persist-client/src/read.rs
src/persist-client/src/stats.rs
src/persist-txn/src/txn_read.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
src/storage-types/src/stats.rs
test/sqllogictest/explain-pushdown.slt

Implements an initial version of the explain-pushdown feature.
#24498 
For example, querying against the auction house load generator:
```
materialize=> explain filter pushdown for select * from bids where bid_time + '300 seconds' > mz_now();
Source          | Total Bytes | Selected Bytes | Total Parts | Selected Parts 
-------------------------+-------------+----------------+-------------+----------------
materialize.public.bids | 605556      | 27374          | 19          | 13
(1 row)
```
This is still behind a flag; I may ask to take larger requests or extensions as followup PRs.
-

[persist/explain] Explain pushdown

---

doc/user/content/sql/alter-default-privileges.md

docs: Fix ALTER DEFAULT PRIVILEGES privileges

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
ci/test/pipeline.template.yml

Seen in
https://buildkite.com/materialize/tests/builds/77783#018e1537-d1e7-46bf-8c81-6abf76b6934e, just leads to duplicate uploads now, so not really harmful
-

ci: Remove useless junit_*xml uploads in mysql tests

---

test/legacy-upgrade/mzcompose.py

This commit updates the legacy upgrade tests to use the persist catalog when possible instead of the stash catalog.
Works towards resolving #24218

test: Use persist catalog in legacy upgrade tests

---

src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/catalog/src/memory/objects.rs
test/testdrive/materialized-view-refresh-options.td

To allow REFRESH MVs to warm up before their first refresh (when the first refresh is in the future), we tweak the `as_of` selection of REFRESH MVs: for the Storage collection, we use the same `as_of` as before (the first refresh, so that the MV is not readable before the first refresh), but for the dataflow we just select `least_valid_read`, so that hydration can start immediately.
The added test currently relies on `mz_compute_operator_hydration_statuses`, but we can change it to `mz_hydration_statuses` after we do the tweak described [here](https://github.com/MaterializeInc/materialize/issues/25518#issuecomment-1980891837) in a later PR. Btw. here we have a different problem in `mz_hydration_statuses` from what is described in that issue. Here, the problem is that …

Refresh MV warmup before first refresh

---

src/adapter/src/coord/command_handler.rs
src/adapter/src/webhook.rs
src/environmentd/src/http/webhook.rs
src/storage-client/src/controller.rs
src/storage-client/src/statistics.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/statistics.rs
test/cluster/storage/01-create-sources.td
test/cluster/storage/02-after-environmentd-restart.td
test/testdrive/webhook-statistics.td

Closes: https://github.com/MaterializeInc/materialize/issues/24868
-

storage: add source statistics for webhooks

---

src/storage/src/metrics/source.rs
src/storage/src/source/reclock.rs
src/storage/src/source/source_reader_pipeline.rs

This PR replaces the raw async stream of committed uppers that was previously being supplied to source implementations with a stream that monitors a tokio `Watch`, which is itself updated by a timely operator.
With this approach every committed upper notification is replacing the previous one in the `Watch` instead of piling up and causing issues with accumulating reclock bindings.
This is a stop gap fix for the reclock CPU bug until the full re-implementation is merged.
-

storage: compact committed upper stream if source is slow to report it

---

src/buf.yaml
src/mysql-util/src/decoding.rs
src/mysql-util/src/desc.proto
src/mysql-util/src/desc.rs
src/mysql-util/src/lib.rs
src/mysql-util/src/schemas.rs
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/mysql.rs
src/storage-types/src/sources/mysql.proto
src/storage-types/src/sources/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/schemas.rs
src/storage/src/source/mysql/snapshot.rs
test/mysql-cdc/35-ignore-columns.td

* This PR fixes a recognized bug. Fixes: https://github.com/MaterializeInc/materialize/issues/24952
cc @morsapaes - I wasn't sure whether to go with `IGNORE COLUMNS` or `IGNORED COLUMNS`, but went with `IGNORE` since there is already a keyword defined for it :) Happy to change as desired.
-

storage/mysql: Add support for IGNORE COLUMNS to ignore columns of types we can't decode

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_permission_validation.sql
misc/dbt-materialize/tests/adapter/test_deploy.py

Validate the dbt user has the right permissions to execute a deployment. 
-

dbt-materialize: check dbt has the proper permissions to execute a deployment

---

.config/nextest.toml
ci/test/cargo-test/mzcompose.py

Since stash catalog is removed we don't expect failures
Fixes: #19931 
-

cargo-test: Try more parallelism in CI again

---

misc/python/materialize/cli/ci_annotate_errors.py

Mistake seen in https://buildkite.com/materialize/nightlies/builds/6821#_
-

ci: Improve ci-annotate-errors message

---

ci/nightly/pipeline.template.yml

ci: Disable rqg lateral join test for now

---

test/cluster/mzcompose.py

This test fetches metrics which are refreshed asynchronously, so we need to wait a bit to ensure we always see the current state reflected.
Additionally, we run a query against the inspected replica in the beginning, to ensure it has successfully started up.
Fixes #25861.
- N/A

test/cluster: unflake test_github_15531

---

src/transform/src/normalize_lets.rs

The `normalize_lets` logic would refresh type information before inlining let bindings that are used only once. Our unique key determination logic .. is not invariant under inlining, and in particular can learn more once it has inlined terms. This PR moves the type refreshing after inlining, which I think is where it used to be until we learned that inlining may violate letrec-major form.
PR up to see if this dramatically alters anything, but probably we want to land this or something like it (perhaps with an explainer about why inlining violates letrec-major, to be totally certain we must re-establish it, or a fix that maintains it while inlining, instead).
-

Normalize type information better

---

test/canary-load/mzcompose.py

Seen in https://buildkite.com/materialize/qa-canary-environment-base-load/builds/27#018e1ebf-afb6-41ce-9d0c-f7ebae08056b
-

canary-load: subscribe can return multiple results

---

misc/python/materialize/buildkite.py

hash() is not stable across runs
-

mzcompose: Hash sharded job in a stable way

---

misc/python/materialize/mzcompose/__init__.py
src/persist-client/src/cfg.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/read.rs

These streaming impls have been enabled in our staging and sandbox envs for a long time with no issues.
We don't expect (or observe) huge improvements from making these streaming, since they both read all the data into memory. (They are _probably_ a bit more memory-efficient, but it's hard to measure.) However, this does let us avoid duplicating a bunch of code for the streaming and non-streaming cases.
-

[persist] Make the streaming consolidate impls the default

---

src/adapter/src/optimize/copy_to.rs
src/adapter/src/optimize/index.rs
src/adapter/src/optimize/materialized_view.rs
src/adapter/src/optimize/mod.rs
src/adapter/src/optimize/peek.rs
src/adapter/src/optimize/subscribe.rs
src/adapter/src/optimize/view.rs
src/transform/src/dataflow.rs
src/transform/src/fusion/filter.rs
src/transform/src/join_implementation.rs
src/transform/src/lib.rs
src/transform/src/literal_constraints.rs
src/transform/src/predicate_pushdown.rs
src/transform/src/typecheck.rs
src/transform/tests/test_runner.rs
src/transform/tests/test_transforms.rs

Make `OptimizerConfig` available in all parts of the MIR optimizations defined in `mz_transform` (local and global).
Part of #25273.
To follow what is happening it's best to review this one commit at a time.

transform: plumb through `OptimizerFeatures`

---

doc/user/layouts/partials/sql-grammar/create-cluster-replica.svg
doc/user/layouts/partials/sql-grammar/create-managed-cluster.svg
doc/user/sql-grammar/sql-grammar.bnf

I failed to update this in #23434.
* This PR fixes documentation.
- n/a

doc/user: fix CREATE CLUSTER [REPLICA] railroad diagrams

---

misc/python/materialize/mzcompose/__init__.py
src/adapter/src/optimize/mod.rs
src/repr/src/optimize.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
src/transform/src/analysis.rs
src/transform/src/analysis/equivalences.rs
src/transform/src/attribute/mod.rs
src/transform/src/equivalence_propagation.rs
src/transform/src/fusion/filter.rs
src/transform/src/lib.rs
src/transform/src/predicate_pushdown.rs
test/rqg/mzcompose.py
test/sqllogictest/explain/view.slt
test/sqllogictest/github-9782.slt
test/sqllogictest/transform/column_knowledge.slt
test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
test/sqllogictest/transform/lifting.slt
test/sqllogictest/transform/predicate_pushdown.slt
test/sqllogictest/uniqueness_propagation_filter.slt
test/testdrive/mz-arrangement-sharing.td

Transformation that propagates "equivalence" information, of the form `expr1 = expr2` under Rust's `=`. This allows us to communicate arbitrary predicates (`expr = true`) but also compactly represent normalizing equivalences that equate classes of expressions (and allow substitution by the simplest representatives).
At the moment, it optimizes away queries like
```sql
-- Demonstrates absence of cross-join input sharing.
SELECT COUNT(*) FROM 
(SELECT * FROM foo WHERE foo.a = 7) foo,
(SELECT * FROM bar WHERE bar.a < 5) bar
WHERE foo.a = bar.a;
```
but should be more fully explored to see what it does to expressions, and whether it mis-optimizes any. This PR is meant to read out any test failures in that regard.
The longer term goal is to consolidate places where we try and reason about …

Equivalence propagation

---

src/balancerd/src/lib.rs
src/balancerd/tests/server.rs

balancerd: add metrics

---

test/cluster/mzcompose.py

[The last unflake attempt](https://github.com/MaterializeInc/materialize/pull/25876) introduced a new slow-path SELECT, which caused the creation of a new dataflow, which had the potential to reflect in the dataflow count metrics and make the test fail. Fixed by making the initial dataflow count check more lenient.
Fixes https://github.com/MaterializeInc/materialize/issues/25917
- N/A

test/cluster: unflake test-github-15531

---

misc/python/materialize/feature_benchmark/scenario.py
misc/python/materialize/feature_benchmark/scenarios/optbench.py
test/feature-benchmark/mzcompose.py

As discussed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1710150069800399, might be useful in the future.
-

feature-benchmark: Allow specifying the relative threshold per scenario

---

src/catalog/src/durable.rs
src/catalog/src/durable/impls/persist.rs

This commit moves the implementation of allocate_id to `DurableCatalogState` since it's implementation is generic over the `Transaction` type.

catalog: Refactor allocate_id

---

doc/user/content/transform-data/troubleshooting.md

Update docs to get rid of inaccurate "computationally-intensive queries" section, replace with a new "Result filtering" section that discusses limit queries and filter pushdown in the context of efficient data exploration. 
Reflecting the outcome of the slack thread https://materializeinc.slack.com/archives/CPNFV9CVB/p1709568585539399

Replace "computationally-intensive queries" section of troubleshooting docs with new "result filtering" section

---

ci/release-qualification/pipeline.template.yml

ci: Disable preflight checks in release qualification

---

Cargo.lock
src/adapter-types/Cargo.toml
src/adapter-types/src/dyncfgs.rs
src/adapter-types/src/lib.rs
src/adapter/src/coord/statement_logging.rs
src/dyncfgs/Cargo.toml
src/dyncfgs/src/lib.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs

Switch over just a single var for now to ensure plumbing is correct, then can do more.
- n/a

adapter: start using dyncfg

---

src/mysql-util/src/decoding.rs
src/mysql-util/src/schemas.rs
src/sql/src/pure.rs
src/storage/src/source/mysql/schemas.rs

Addresses nit comments from https://github.com/MaterializeInc/materialize/pull/25830 (it was merged before addressing to ensure it got in before today's release cut).
-

storage/mysql: Address nits from IGNORE COLUMNS PR

---

Cargo.lock
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/mysql.rs
src/storage-types/Cargo.toml
src/storage-types/src/sources/mysql.rs
test/mysql-cdc/mysql-cdc.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/25884 and Fixes https://github.com/MaterializeInc/materialize/issues/25883
Fix 2 issues related to MySQL `TEXT COLUMNS` and `IGNORE COLUMNS` purification/planning.
The first issue was when encountering column names with special characters -- we were inadvertently storing a postgres-style-escaped string for the column name in our source connection options which later led to errors when verifying the schema in the source operator.
The second issue was ignoring any column references that didn't match -- this change just propagates those up as an error to the user during sql purification.
The 2 commits correspond to each of the issues fixed.
-

storage/mysql: Fix 2 mysql TEXT COLUMNS bugs

---

src/transform/src/analysis/equivalences.rs

A diagnostic `assert!` was left in that I believe we want to weaken to a `soft_assert` (it is not wrong to be not idempotent, just unexpected).
-

Weaken `assert` to `soft_assert`

---

test/cluster/mzcompose.py
test/testdrive/materialized-view-refresh-options.td

This finally adds lots of restart tests for REFRESH MVs. It's both envd restarts (in `mzcompose.py`) and just turning replicas on/off (in `materialized-view-refresh-options.td`).
For `workflow_test_refresh_mv_restart`, I'm not really sure where is it gonna be executed in CI. Is it the normal CI, or Nightlies? Note that it takes almost 3 minutes to run (on my laptop, in release mode), so maybe it should be in Nightlies? Or what do you think, @def- ?
Btw. the new tests didn't turn up any unknown bugs.
* This PR adds known-desirable tests: https://github.com/MaterializeInc/materialize/issues/25875
-

REFRESH tests with restarts

---

src/sql/src/func.rs

Requested in the review of #25941.
* This PR adds documentation.
- n/a

sql: add comment about JSON nulls to jsonb_object_agg implementation

---

test/sqllogictest/table_func.slt

Seen in https://buildkite.com/materialize/sql-logic-tests/builds/5864#018e333a-4c06-4edc-a45b-15571f16b0ec
-

slt: Fix table_func.slt (following jsonb null fixes)

---

doc/user/content/sql/system-catalog/mz_internal.md
src/compute-client/src/controller/instance.rs
src/compute-client/src/protocol/response.rs
src/compute-types/src/dataflows.rs
src/compute-types/src/explain/text.rs
src/compute-types/src/plan/flat_plan.rs
src/compute-types/src/plan/interpret/api.rs
src/compute-types/src/plan/lowering.rs
src/compute-types/src/plan/mod.rs
src/compute/src/compute_state.rs
src/compute/src/render/mod.rs
test/sqllogictest/explain/physical_plan_as_json.slt

This PR renames the `NodeId` type to `LirId` and any `node_id` variables to `lir_id`. This is meant to remove some ambiguity when these IDs are used outside the `Plan` context, in which case the term "node" is probably too general to be obvious.
This is a follow-up to #24906 where @antiguru pointed out that the term "node ID" can be ambiguous as a lot of things are called "nodes". There is not much ambiguity in the context of `Plan` and its methods, but we also use this ID outside of this context (e.g. when reporting hydration information), so a more specific name seems like a good idea.
This takes the approach of renaming all `node_id` fields to `lir_id`. We could alternatively leave the ones in `Plan` and `FlatPlan` called `node_id` because the meaning …

compute: rename `NodeId` to `LirId`

---

ci/nightly/pipeline.template.yml
test/rqg/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6861 ✅

tests: RQG: use Postgres 16.2, re-enable test

---

src/sql/src/pure.rs
test/mysql-cdc-resumption/alter-mz.td
test/mysql-cdc-resumption/cleanup.td
test/mysql-cdc-resumption/mzcompose.py
test/mysql-cdc-resumption/verify-data.td
test/mysql-cdc/alter-source.td
test/testdrive/kafka-alter-source.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/25826 and Fixes https://github.com/MaterializeInc/materialize/issues/25882
Context for this PR is here https://github.com/MaterializeInc/materialize/issues/25826#issuecomment-1988816031
-

storage/purification: Correctly error on ALTER SOURCE .. DROP SUBSOURCE statements for unsupported source types

---

doc/user/content/sql/create-source/postgres.md
doc/user/content/sql/system-catalog/mz_internal.md
src/adapter/src/catalog/builtin_table_updates.rs
src/catalog/src/builtin.rs
test/pg-cdc/pg-cdc.td
test/sqllogictest/autogenerated/mz_internal.slt

Used to help debug things like: https://github.com/MaterializeInc/materialize/issues/25802
- adds `timeline_id` to `mz_internal.mz_postgres_sources`

storage: add timeline_id to mz_postgres_sources

---

src/adapter/src/coord/appends.rs
src/adapter/src/coord/ddl.rs

Needed to debug a slow coord message. Notably, this commit detaches the spawned task from the span but attaches the otel ctx as a parent because the coordinator is able to progress after the spawn.
- n/a

adapter: improve traces for group_commit_initiate

---

src/adapter/src/coord.rs

This will help us track down slow coord messages, at the increased risk of overwhelming our tracing infra or envd resources to trace everything. If that happens, we can decrease the otel levels in LD until this commit is reverted.
- n/a

adapter: bump all coord messages to INFO

---

ci/test/lint-main/before/can-lint.sh

The shellcheck version check expected a version of the form `d.d.d` where `d` is a digit; the stable version of shellcheck has a two-digit minor version number (0.10.0).
`can-lint.sh` spuriously fails for shellcheck versions that involve multi-digit numbers.
-

ci: fix shellcheck version check to support 0.10.0

---

misc/python/materialize/cli/mzimage.py

Expose the mzbuild "ensure" operation, which builds and pushes an image if it does not already exist in the remote registry, to the mzimage CLI.
- n/a

mzbuild: add ensure subcommand to bin/mzimage

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/state.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/testdrive/src/action.rs
src/testdrive/src/action/consistency.rs

When Testdrive validates the in-memory state of the catalog against its on disk state, in needs to take any system parameter defaults that were overridden by the `--system-parameter-default` environmentd argument into consideration.
The approach taken here is to have the internal /catalog/dump return system parameter defaults as part of the catalog state. They're then readily available to Testdrive when it loads the on-disk catalog.
Alternative to https://github.com/MaterializeInc/materialize/pull/25946.
Alternative to https://github.com/MaterializeInc/materialize/pull/25924.
- n/a

adapter,testdrive: respect overridden defaults when validating catalog

---

misc/python/materialize/mzcompose/services/toxiproxy.py

With linux/arm images. Should make CI faster
The shopify images have had no updates in the last 5 years(!)
This might explain https://github.com/MaterializeInc/materialize/issues/22486
-

testing: Use newer toxiproxy dockerhub image

---

bin/ci-python-imports
ci/mkpipeline.py

instead of not trimming pipelines whenever any file in there way touched
-

ci: Track misc/python dependencies

---

src/sqllogictest/src/bin/sqllogictest.rs
src/testdrive/src/bin/testdrive.rs

Shard: 1/1 is not all that interesting
-

tests: Only print shard when it's not all

---

test/testdrive/materialized-view-refresh-options.td

Use less memory:
- drop old MV with `generate_series` that's not needed for later tests
- smaller `generate_series`
- 2 replicas instead of 3
I'm sorry for the flake!
* This PR fixes a recognized test issue: #25983
-

Minor adjustments in REFRESH tests to not use so much memory

---

src/expr/src/relation/mod.rs

Rewrites a recursive traversal as an iterative traversal, removing stack pressure and simplifying.
-

Rewrite recursion as iteration

---

src/compute-types/src/dyncfgs.rs
src/compute/src/sink/persist_sink.rs

This PR makes the compute `persist_sink` more efficiently handle updates for future times by moving received updates into a stash first and then moving them into the `correction` buffer only when the input frontier has passed their times. The result is that we can ignore updates for future times in the process of determining which updates need to be sinked to persist. This has the potential for avoiding a large amount of unnecessary work, particularly in dataflows that contain temporal filters.
Fixes https://github.com/MaterializeInc/materialize/issues/25844
I think long-term we want to move to some more sophisticated merge batcher implementation that also enables us to spill to lgalloc, but this seems like a good short-term fix for the temporal filter …

compute/persist_sink: efficient handling of future updates

---

misc/images/fivetran-destination-tester/Dockerfile
misc/images/fivetran-destination-tester/mzbuild.yml
misc/python/materialize/mzcompose/services/fivetran_destination_tester.py

Wraps the fivetran-destination-tester Docker image with mzimage to mirror it.
Decouples our CI from the upstream Fivetran Dockerhub
- Testing only change

fivetran-destination: Mirror tester image

---

doc/developer/testdrive.md
src/testdrive/src/action.rs
src/testdrive/src/action/kafka/ingest.rs
src/testdrive/src/action/set.rs

The argument defaults can be added directly to the vars map if the var is not already set. This avoids needing to keep track of argument defaults separately from other variable values.
Also add some documentation for the command.
- n/a

testdrive: simplify implementation of arg defaults

---

bin/ci-upload-heap-profiles
ci/plugins/mzcompose/hooks/command
misc/python/materialize/cli/ci_upload_heap_profiles.py

ci: Detect all clusterds instead of only the first

---

test/testdrive/materialized-view-refresh-options.td

The test was still OOMing, see discussion [here](https://materializeinc.slack.com/archives/C01LKF361MZ/p1710405419068639?thread_ts=1710351761.364519&cid=C01LKF361MZ). This PR makes the test's mem usage about 10x less but keeps CPU time roughly the same as before, by having a 10x smaller `generate_series` but exercising the CPU with a series of `*2/2` at each output element of the `generate_series`.
I also added a cleanup at the end of the `.td`.
-

Use less memory in `materialized-view-refresh-options.td`

---

Cargo.lock
misc/cargo-vet/config.toml

Update lgalloc to better clear background memory.
Changes in lgalloc: https://github.com/antiguru/rust-lgalloc/compare/v0.3.0...v0.3.1
-

Update lgalloc, fix background reclamation

---

misc/python/materialize/checks/all_checks/cluster_unification.py
misc/python/materialize/checks/all_checks/owners.py
misc/python/materialize/checks/all_checks/privileges.py
src/adapter/src/catalog/migrate.rs
src/sql/src/plan/statement/ddl.rs
test/testdrive/load-generator.td

We accidentally didn't do this check, so we need a migration as well!
-

storage: prevent load generators with unused options

---

misc/scratch/provision.bash
src/repr/build.rs
src/repr/src/row/encoding.rs

Small win and irrelevant once we change the blob format, but easy.
roundtrip_bytes_decode_legacy
time:   [2.8988 ms 2.8990 ms 2.8993 ms]
change: [-3.9216% -3.9051% -3.8878%] (p = 0.00 < 0.05)
-

repr: remove an alloc in the Datum::Bytes decode path

---

src/adapter/src/catalog/open.rs
src/adapter/src/client.rs
src/adapter/src/coord/sql.rs
src/adapter/src/coord/statement_logging.rs
src/adapter/src/session.rs
src/catalog/src/durable/transaction.rs
src/environmentd/tests/server.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/ast/display.rs
test/cluster/statement-logging/statement-logging.td

Refactor statement logging history to do a bit of cleanup, and adds a (somewhat hacky) one time migration that should clear the necessary tables of their existing data.
Refactor/cleanup
This PR is separated into two commits:
1. The refactor to statement history
2. Introducing a one-time "migration" that should clear the existing sources
- N/a

sql: Refactor to statement logging history

---

src/mysql-util/src/desc.rs
test/mysql-cdc/types-enum.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/26022
-

storage/mysql: Fix detection of mysql enum column value changes

---

src/compute/src/render/flat_map.rs

Our implementation of flatmap completely evaluates all extensions as it goes, and only then applies its `MfpPlan` which may reduce the data back down. In no case does it consolidate anything, shipping a large volume of data for e.g.
```sql
select count(*) from generate_series(1, 1000000000)
```
This PR draws data out of the `TableFunc::eval` iterator, consolidating as it goes and when necessary applying the `MfpPlan` and consolidating the results. On the query above it keeps a buffer of at most four elements (bumped up a bit because we set some minimums, but it is four when we do not).
cc: @ggevay 
-

Stage flatmap execution to consolidate as it goes

---

src/storage-controller/src/lib.rs
src/storage-controller/src/persist_handles.rs

This persist_table_worker.register call is idempotent and re-run on envd restart, so it's ~fine if it doesn't succeed before a crash, but also probably feels better to await on it anyway. This was discovered while eyeballing traces.
While I'm in here, also clean up the name of the span: PersistTableWorkerInner::Send -> PersistTableWriteCmd::Register
Closes #25742
Before:
After:
-

storage: await on table register call in create_collections

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/stash-debug/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.93.0-dev

---

src/fivetran-destination/src/destination.rs
src/fivetran-destination/src/destination/ddl.rs
src/fivetran-destination/src/destination/dml.rs
test/fivetran-destination/test-supported-data-types/01-setup.json
test/fivetran-destination/test-supported-data-types/02-verify.td

This PR changes the Fivetran Destination to mark primary key columns as `NOT NULL`. Primary keys are not allowed to be `NULL` and adding this constraint allows us to plan queries that are currently a three-way join as a two-way join.
```
CREATE TABLE logs      (id text, ts int);
CREATE TABLE logs_temp (id text, ts int);
EXPLAIN SELECT FROM logs WHERE (id, ts) IN (SELECT id, ts FROM logs_temp);
Explained Query:
Project () // { arity: 0 }
Join on=(#0{id} = #2{id} = #4{id} AND #1{ts} = #3{ts} = #5{ts}) type=delta // { arity: 6 }
ArrangeBy keys=[[#0{id}, #1{ts}]] // { arity: 2 }
ReadStorage materialize.parker_timmerman.logs // { arity: 2 }
ArrangeBy keys=[[#0{id}, #1{ts}]] // { arity: 2 }
Distinct project=[#0{id}, #1{ts}] // { arity: 2 }
Filter (#0{id}) IS NOT NULL AND (#1{ts}) IS NOT NULL // …
```

fivetran-destination: Mark primary_key columns as `NOT NULL`

---

misc/python/materialize/checks/all_checks/cluster_unification.py
misc/python/materialize/checks/all_checks/owners.py
misc/python/materialize/checks/all_checks/privileges.py
src/adapter/src/catalog/migrate.rs
src/sql/src/plan/statement/ddl.rs
test/testdrive/load-generator.td

This reverts commit 3d9437258de68906e14e39a5cf35a6c833ef8cd4, reversing changes made to 1caee1ca6e5a57f4a56e9efee9d902de9b4d09ea.
The migration written for this doesn't work so we have to revert it.
- Add `SCALE FACTOR` back to load generator sources.

Revert "Merge pull request #26006 from guswynn/loadgen-outstanding"

---

misc/python/materialize/mzcompose/__init__.py
src/compute-types/src/dyncfgs.rs
src/compute/src/compute_state.rs
src/compute/src/render/mod.rs
src/compute/src/render/sinks.rs
src/compute/src/server.rs
src/compute/src/sink/copy_to_s3_oneshot.rs
src/compute/src/sink/persist_sink.rs
src/compute/src/sink/subscribe.rs
src/persist-client/src/operators/shard_source.rs
src/persist-txn/src/operator.rs
src/storage-operators/src/persist_source.rs
src/storage/src/render/sinks.rs
src/storage/src/render/sources.rs

Implement sequential dataflow hydration in compute by arranging for dataflow sources to be suspended after rendering and allowing them to resume only if there is hydration capacity. 
The available capacity is controlled by a new dyncfg option, `compute_hydration_concurrency`.
Part of #25271.
* The first commit is relevant for @MaterializeInc/storage. It wires a new `start_signal` argument through `persist_source` and `shard_source` that the latter awaits before it starts ingesting any data. The plan is to not keep this around forever, but to replace it after the `persist_source`-internal backpressure has been removed, as discussed [in Slack](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1709827468354719).
* The second commit is relevant …

compute: sequential dataflow hydration

---

src/adapter/src/catalog/state.rs

This commit improves the error message that is displayed when a GlobalId is missing from the catalog by including the missing ID.

adapter: Improve error message for missing key

---

src/environmentd/tests/server.rs

This PR asserts we return the correct format for double-encoded JSON values from the HTTP and websocket endpoints.
A customer tripped over this recently, just want to make sure we return the correct values so the Console can render them appropriately.
Console issue: https://github.com/MaterializeInc/console/issues/1928
- Adds a new test

tests: Assert correct values for double-encoded JSON

---

.github/CODEOWNERS

Maybe this is going overboard? Mainly motivated by https://materializeinc.slack.com/archives/C01CFKM1QRF/p1710512681174499?thread_ts=1710505017.833349&cid=C01CFKM1QRF
-

code owners: Add testing team as owners for some misc directories

---

doc/user/content/ingest-data/redpanda-cloud.md
doc/user/content/sql/create-connection.md
src/sql/src/plan/statement/ddl/connection.rs
src/sql/src/session/vars/definitions.rs
test/cloudtest/test_privatelink_connection.py
test/ssh-connection/setup.td

Removes the feature flag gating on the privatelink default connection for kafka syntax.
This feature is working and we do not wish to gate it per organization, per https://github.com/MaterializeInc/materialize/issues/25468
Fixes #25468.
Fixes #26011.
-

remove default privatelink kafka flag

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_cleanup.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_permission_validation.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/ci_utils.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/exists.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/is_cluster_ready.sql
misc/dbt-materialize/tests/adapter/test_deploy.py

Assign permissions to newly created schemas and clusters that match those of the schemas and clusters we are copying.  
-

dbt-materialize: copy grants and default privileges in deploy_init

---

misc/python/materialize/buildkite.py

This is needed for Python < 3.11 (used in scratch).

ci: sharding: specify byteorder

---

src/transform/src/reduction_pushdown.rs
src/transform/tests/test_transforms.rs
src/transform/tests/test_transforms/reduction_pushdown.spec
test/rqg/Dockerfile
test/sqllogictest/github-25015.slt

Our `ReductionPushdown` transform would lose track of join equivalences that involve only one input. In principle they could have been pushed down to that input, but if they have not for some reason, we still need to handle them.
-

Push down predicates even if only one input

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Release dbt-materialize 1.7.5 with support for copying grants and default privileges 
-

dbt-materialize: release 1.7.5

---

src/compute/src/render/flat_map.rs

This follows up #26020 with some light renaming, but an important consideration: consolidating and doubling the table function output seems not especially helpful. Yes if we had to produce it all as output, but no because we are moving it through `drain_through_mfp`. In that case, we really just want to bite off large enough chunks to amortize decoding `input_row`. This simplifies the code a bit, and should reduce its memory footprint for table functions with large outputs that nonetheless consolidate down (e.g. the `select count(*) from generate_series` this was meant to address).
-

Respond to further discussion

---

src/compute/src/compute_state.rs
src/compute/src/render/context.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/reduce.rs
src/compute/src/row_spine.rs
src/repr/src/fixed_length.rs

This PR removes some RTTI infrastructure that was introduced when we had potential ambiguities in the representation of information. We do not have those ambiguities now, and there is no plan (at the moment) to continue towards them. The likely outcome is that the compressed representation they meant to support will emerge through containers that wrap specialization, rather than through exposing new containers.
-

Remove some RTTI

---

misc/python/materialize/version_list.py
test/legacy-upgrade/mzcompose.py

Nightly: https://buildkite.com/materialize/nightlies/builds/6923

tests: do not use v0.92.0 (in upgrade checks)

---

ci/plugins/mzcompose/hooks/post-command

Seen in https://buildkite.com/materialize/nightlies/builds/6933#018e439d-e26a-4f01-b7b0-39fa665ee25c
-

ci: Try to wait for core dumps

---

misc/python/materialize/cli/mzcompose.py
misc/python/materialize/mzcompose/composition.py

I'm guessing BUILDKITE_TAG is better since BUILDKITE_BRANCH can be manually set to anything
This should save us some resources in CI and locally since restarting Mz is already so slow (~20 seconds!)
(The preferred fix would be to make restarting Mz faster)
-

mzcompose: Run sanity check only on release branches

---

misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/version_list.py
test/platform-checks/mzcompose.py

As this is (mostly) not what we want to test, but the upgrade from the previous minor. See https://materializeinc.slack.com/archives/CTESPM7FU/p1710542034279119?thread_ts=1710518433.695219&cid=CTESPM7FU
-

upgrade checks: Skip current minor version

---

misc/python/materialize/checks/all_checks/cluster_unification.py
misc/python/materialize/checks/all_checks/owners.py
misc/python/materialize/checks/all_checks/privileges.py
src/adapter/src/catalog/migrate.rs
src/sql/src/plan/statement/ddl.rs
test/testdrive/load-generator.td

This is https://github.com/MaterializeInc/materialize/pull/26006, but with tests fixed with version checks (thanks @def- for the good docs!), as well as a fixed migration. Because some migrations want to happen pre-planning, but some need a catalog connection, we split the migration code into two phases.
-

storage: prevent load generators with unused options, try #2

---

src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
test/pg-cdc/types-reg.td

Fixes #26100
- Error when trying to set up a PostgreSQL source asking MZ to ingest `regtype`, `regclass`, or `regproc` data. MZ does not yet offer enough support for those types to let us ingest them and, additionally, user-specified objects' OIDs cannot be meaningfully used in Materialize.

sql: error instead of panic when failing to lower casts

---

Cargo.lock
misc/cargo-vet/audits.toml
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/environmentd/Cargo.toml
src/environmentd/src/test_util.rs
src/environmentd/tests/tracing.rs
src/orchestrator-tracing/Cargo.toml
src/orchestrator-tracing/src/lib.rs
src/ore/Cargo.toml
src/ore/src/tracing.rs
src/pgwire/Cargo.toml
src/pgwire/src/codec.rs
src/pgwire/src/message.rs
src/pgwire/src/protocol.rs
src/sql-parser/src/parser.rs
src/sql/src/rbac.rs

Add tracing tests to assert certain traces do or don't happen. For normal queries, assert that some do. For secrets, assert that we don't leak bad raw sql in any trace or event.
Supersedes #25181
- n/a

enviromentd: tracing tests

---

src/catalog/src/durable/metrics.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/persist.rs

This commit adds a metric to the durable catalog that tracks how many total entries, after consolidation, exist in each catalog collection

catalog: Add metrics on total size

---

src/persist-client/src/cli/inspect.rs
src/persist-client/src/internal/state_versions.rs

Motivated by the investigation into whether catalog migration retractions are working correctly. This would pretty directly indicate yes vs no and seems like a reasonable thing to have around.
-

persist: add cli tool for unconsolidated vs consolidated size

---

src/persist-client/src/lib.rs
src/persist-txn/src/lib.rs
src/storage-controller/src/lib.rs

In #25992, we discovered that persist-txn forget records do not
consolidate out of the raw shard as intended (they work fine in-mem).
This combined with the forget_all call as part of boot creates a risk
that a crashlooping envd process will quickly increase the physical size
of the txns shard.
Luckily, the forget_all call was only needed as part of the story for
rollback back to the old tables implementation, which has since been
removed. We can now get away with a lesser set of invariants at boot.
Put this behind a dyncfg because it's occasionally useful to have the
forget_all.
Mechanically, I add the dyncfg with a default of the previous behavior
in this commit. In the next, I'll switch the default. This allows us to
potentially cherry-pick just this commit into the currently …

persist-txn: add dyncfg to apply_eager on init instead of forget_all

---

src/catalog/src/durable/metrics.rs
src/catalog/src/durable/persist.rs

This commit renames the mz_catalog_collection_count metric to mz_catalog_collection_entries since `_count` is a reserved suffix in Grafana/Prometheus.

catalog: Rename collection entry count metric

---

src/catalog/src/durable/persist.rs

This commit refactors the persist catalog implementation to store a trace of all catalog updates in memory instead of a map of all catalog contents. This simplifies the persist implementation slightly and will allow further refactors to combine the pre and post open catalog implementations.

catalog: Refactor persist catalog to use traces

---

test/mysql-cdc/mzcompose.py

Collapse all those log lines:
```
>> SET @i:=0;
>> INSERT INTO many_inserts (f2) SELECT @i:=@i+1 FROM mysql.time_zone t1, mysql.time_zone t2 LIMIT 100;
>> SET @i:=0;
>> INSERT INTO many_inserts (f2) SELECT @i:=@i+1 FROM mysql.time_zone t1, mysql.time_zone t2 LIMIT 100;
>> SET @i:=0;
>> INSERT INTO many_inserts (f2) SELECT @i:=@i+1 FROM mysql.time_zone t1, mysql.time_zone t2 LIMIT 100;
>> SET @i:=0;
>> INSERT INTO many_inserts (f2) SELECT @i:=@i+1 FROM mysql.time_zone t1, mysql.time_zone t2 LIMIT 100;
>> SET @i:=0;
>> INSERT INTO many_inserts (f2) SELECT @i:=@i+1 FROM mysql.time_zone t1, mysql.time_zone t2 LIMIT 100;
>> SET @i:=0;
[...]
```

tests: mysql concurrent inserts: collapse log

---

Cargo.lock
misc/python/materialize/checks/all_checks/mysql_cdc.py
src/mysql-util/Cargo.toml
src/mysql-util/src/lib.rs
src/mysql-util/src/privileges.rs
src/mysql-util/src/replication.rs
src/sql/src/plan/error.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/mysql.rs
test/mysql-cdc-resumption/configure-mysql.td
test/mysql-cdc/privileges.td

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/26071 , Fixes https://github.com/MaterializeInc/materialize/issues/25412 , Fixes https://github.com/MaterializeInc/materialize/issues/25519
This also removes the need for the `SELECT` privilege on `performance_schema.replication_connection_configuration` which seems like a weird permission to ask for, when we can approximate the same thing by being smarter about the replica settings (see comment in code for details).
-

storage/mysql: Implement privilege checks on MySQL tables, replication permissions

---

src/environmentd/src/test_util.rs
src/orchestrator-tracing/src/lib.rs
src/ore/src/tracing.rs

Allow specifying different values for handling of opentelemetry trace span batches. Specifically, during periods of dysfunction when traces can't be sent, we sometimes see spans being dropped due to the buffer queue being full. Allow optionally increasing the size for debugging purposes.
The argument defaults are the defaults currently set for these values by [BatchConfig](https://docs.rs/opentelemetry_sdk/0.21.2/opentelemetry_sdk/trace/struct.BatchConfig.html)
-  None

Allow configuring opentelemetry batch settings

---

Cargo.lock
src/catalog-debug/Cargo.toml
src/catalog-debug/src/main.rs
src/catalog/src/durable.rs
src/catalog/src/durable/persist.rs
src/catalog/tests/debug.rs

This commit adds a `--consolidate` option to the dump functionality of the catalog-debug tool. This option returns a consolidated dump instead of an unconsolidated dump, which is the default.
This is a mitigation for #26109 since a consolidated catalog can always be deserialized by a single protobuf version.

catalog-debug: Add consolidate option to dump

---

doc/user/content/sql/create-source/postgres.md

We don't currently support the `timetz` type, removing it from our docs [until we do](https://github.com/MaterializeInc/materialize/blame/77e15f543b754e1f410f97a8d0189ad717475513/test/sqllogictest/cockroach/alter_column_type.slt#L42)!
h/t to @ParkMyCar for [noticing this](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1710883553354169).

doc: remove timetz from list of supported PostgreSQL types

---

misc/python/materialize/checks/all_checks/mysql_cdc.py

Since old versions won't implicitly run the grant implemented in https://github.com/MaterializeInc/materialize/pull/26074 we have to still run it manually for these versions.
Fixes: #26146
-

platform-checks: Fix MySQL upgrade tests

---

misc/scratch/ci-aarch64-large.json

At least once I've used this to repro/investigate ci failures.
-

misc: add ci-aarch64-large scratch box

---

misc/python/materialize/mzcompose/__init__.py

Now that #26016 is merged we can further reduce the hydration concurrency in CI to stress-test sequential hydration more.
Part of #25271
- N/A

ci: reduce `compute_hydration_concurrency`

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/metrics.rs
src/compute-client/src/protocol.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute-client/src/protocol/history.rs
src/compute-types/src/dyncfgs.rs
src/compute/src/compute_state.rs
test/testdrive/sequential-hydration.td

This PR adds a new `Schedule` compute command that allows the controller to control when dataflows should be started, independently from their creation. The controller uses this ability to delay the starting of dataflows that don't have their input data available yet, fixing an issue with sequential hydration where replicas could become stuck waiting for input data even when the hydration queue contained dataflows that were ready to hydrate.
On the replica-side, transient dataflows are still handled specially in that the replica doesn't wait for `Schedule` commands before unsuspending them. This is a bit of a smell as ideally, replicas would just verbatim apply `Schedule` commands they receive. I think we can fix this in a follow-up by moving the sequential hydration logic out of the …

compute: controller-controlled sequential hydration

---

src/adapter-types/src/compaction.rs
src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/consistency.rs
src/adapter/src/coord/id_bundle.rs
src/adapter/src/coord/read_policy.rs
src/environmentd/src/http.rs
src/environmentd/src/http/catalog.rs
src/repr/src/user.rs
src/sql/src/session/user.rs
src/storage-types/src/read_policy.rs
src/testdrive/src/action/consistency.rs

Follow up to an incident, it would be nice to be able to dump some of the Coordinator's state so we can determine what read holds are currently outstanding. This PR adds a new endpoint to the internal HTTP server `/api/coordinator/dump` that will return part of the Coordinator's state as a JSON object.
It also updates the read holds consistency check to make sure the connection exists for all txn related read holds.
Debugging tool
- N/a

coord: Make it possible to dump state for debugging

---

src/compute/src/server.rs

Hopefully this will help us debug issues with reconciliation in the future.
Part of #26155 
- N/A

compute: add warning for unsuccessful reconciliation

---

src/stash-debug/src/main.rs
src/storage-controller/src/command_wals.rs
src/storage-controller/src/lib.rs

Fix stash-debug tool

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
misc/python/materialize/mzcompose/services/balancerd.py
src/balancerd/Cargo.toml
src/balancerd/src/lib.rs
src/workspace-hack/Cargo.toml
test/balancerd/mzcompose.py

Extract the tenant from the CNAME.
- n/a

balancerd: per-tenant metrics for http

---

src/mz/tests/local.rs

As discussed in #25976 the `mz::local tests::test_local` fails in coverage CI but works locally as expected.
The only way that I was able to make the test fail was by running the test simultaneously in a few different terminals, eg. running the following in 2/3 different terminals:
```
for i in {1..100} ;do cargo test --package mz --test local -- tests --nocapture ;done
```
The idea behind this change is that the `mz` config file will no longer be shared between different tests, but a unique config file will be created which will only be used for the specific test.
Open to suggestions here.
Closes #25976
-

mz: Fix coverage CI failing cargo-test mz::local

---

src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/controller/src/clusters.rs
src/storage-client/src/client.rs

This PR resolves some old `TODO(teskje)`s I've found lying around.
- N/A

*: resolve some old TODOs

---

misc/python/materialize/cli/run.py

only add sanitizer options when needed

---

ci/builder/Dockerfile
ci/nightly/pipeline.template.yml
misc/python/materialize/xcompile.py

As reported in https://materializeinc.slack.com/archives/C01LKF361MZ/p1711029258676969
Follow-up to https://github.com/MaterializeInc/materialize/pull/26047
I believe this should fix it and keep Sanitizers working, but have to wait for ci-builder to be built first.
-

ci-builder: Fix static linking on macOS

---

src/storage-controller/src/lib.rs
src/storage/src/storage_state.rs

In #26186 I found that the dyncfg implementation for storage was broken and `ALTER SYSTEM SET <flag> <val>` commands would not work since the dyncfg option field in `StorageParameters` was mistakenly 'taken' before being propagated through downstream storage configuration update commands.
This is a cherry-pick of the first commit in that PR to make the fix in for the release. The tests in that PR confirm the fix.
-

storage: fix dyncfg implementation

---

Cargo.lock
misc/cargo-vet/config.toml
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
src/expr/Cargo.toml
src/expr/src/scalar/like_pattern.rs
src/repr/src/adt/regex.proto
src/repr/src/adt/regex.rs
test/sqllogictest/explain/optimized_plan_as_json.slt
test/sqllogictest/like.slt

`serde_regex`, the serialization library that we were originally using for serializing `Regex` is broken (see https://github.com/tailhook/serde-regex/issues/14). Some time ago, https://github.com/MaterializeInc/materialize/pull/20602 made us stop using it in certain places. Unfortunately, `MatcherImpl` was still using it, impacting `ILIKE` for multiprocess clusters.
This PR makes `MatcherImpl` also use our wrapper class around `Regex`. (Our wrapper class has manually written serializers, both for `Serialize`/`Deserialize` and Protobuf, which don't attempt to serialize the `Regex` object itself, but just serializes the information that is necessary to rebuild the `Regex` object upon deserialization.) Additionally, it records in `cargo-vet/audits.toml` that `serde_regex` is _not_ …

Fix ILIKE with multiprocess clusters

---

src/expr/src/scalar/like_pattern.rs
src/repr/src/adt/regex.rs
test/sqllogictest/explain/optimized_plan_as_json.slt
test/sqllogictest/regex.slt

Make `.` in regexes match newlines, to match the default in Postgres.
Note that this is on top of https://github.com/MaterializeInc/materialize/pull/26183, so just the last 2 commits are new.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/26188
-

Fix newline handling in regexes

---

src/adapter/src/flags.rs
src/storage-controller/src/lib.rs
src/storage-types/src/configuration.rs
src/storage-types/src/parameters.rs
src/storage/src/storage_state.rs

I was being wrong with this option:
Roshan found #26189, and https://github.com/MaterializeInc/materialize/pull/26131 made me realize that future clusters wont get the new updates. 
-

storage: fix dyncfg updates for future clusters

---

src/persist-client/src/internal/trace.rs

Refactoring, motivated by: #16607. In the short term, simplifying the structure of Spine means I have fewer cases to account for when roundtripping the structure. In the medium term, having fewer cases to account for in the Spine structure should make future work on Compaction 2.0 easier to reason about.
This is structured as a series of smallish changes, one per commit, in case it's easier to review that way also.
It was slightly trickier to remove the `None` case than I expected, even though we are not introducing structurally-empty batches, because it was also used as a placeholder value in some cases. Let me know if anything doesn't make sense!
`cargo bench` suggests that this is performance-neutral. I'll give nightlies a go at it as well.
I appreciate that this takes us away from the …

[persist] Remove some unused code & cases in Persist's Spine

---

Cargo.lock
Cargo.toml
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
src/mysql-util/Cargo.toml
src/mysql-util/src/tunnel.rs
src/sql/Cargo.toml
src/storage-types/Cargo.toml
src/storage-types/src/connections.rs
src/storage/Cargo.toml
src/testdrive/Cargo.toml
src/workspace-hack/Cargo.toml

Our upstream PRs were merged and new versions issued for the repos https://github.com/blackbeam/mysql_async and https://github.com/blackbeam/rust_mysql_common , so we can stop using our fork of `mysql-async`.
This will also allow us to work on #24630 since our [PR](https://github.com/blackbeam/rust_mysql_common/pull/126) to expose flags on the rows-events received from mysql is available in the new version.
-

storage/mysql: Switch back to upstream mysql-async and mysql-common crates

---

misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py

This addresses https://buildkite.com/materialize/nightlies/builds/7000#018e6211-1221-423e-bf1e-bf81e0b6c139 and https://buildkite.com/materialize/nightlies/builds/7012#018e635a-7374-4148-8fb7-732f2ce950f0. It fixes https://github.com/MaterializeInc/materialize/issues/26204.
It replaces https://github.com/MaterializeInc/materialize/pull/26205.

version consistency: add ignores

---

src/dyncfg/src/dyncfg.proto
src/dyncfg/src/lib.rs

This is causing a slow memory leak in both the storage and compute controllers. (Also it seems like a good thing to do.)
The original reason for the vec instead of the map was [to save a level of nesting in the proto encoding](https://github.com/MaterializeInc/materialize/pull/24416#discussion_r1454035582), so no particular stress about switching back to the map.
Closes #26196
-

dyncfg: deduplicate updates in ConfigUpdates::extend

---

Cargo.lock
src/adapter/src/catalog.rs
src/adapter/src/util.rs
src/catalog/Cargo.toml
src/catalog/src/durable.rs
src/catalog/src/durable/error.rs

Previously, there were a couple of places in the code where the adapter should have halted in response to a fence error from the catalog, but instead was returning a user error. This commit fixes those spots by halting the adapter in response to a fencing error from the catalog.

adapter: Make fencing more robust

---

src/persist-cli/src/maelstrom/services.rs
src/persist-client/benches/plumbing.rs
src/persist-client/src/batch.rs
src/persist-client/src/cli/args.rs
src/persist-client/src/internal/cache.rs
src/persist-client/src/internal/metrics.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/usage.rs
src/persist/src/file.rs
src/persist/src/indexed/encoding.rs
src/persist/src/intercept.rs
src/persist/src/location.rs
src/persist/src/mem.rs
src/persist/src/s3.rs
src/persist/src/unreliable.rs

This is an artifact from the single-binary persist days, which only used Blob, not Consensus. It was introduced so that data blobs could be written without the file rename trick, and state blobs could be written atomically. Since the only way to find out about a blob key was through state, we didn't have to worry about partial writes for data blobs.
In single-binary persist, File was a reasonably supported production option, so we cared more about the performance. But in platform persist, we only use s3 for Blob, which is naturally atomic. Additionally, we've now added things like Blob::list_keys_and_metadata, which have introduced a way to find blobs that does not come via state.
I don't see us switching to non-atomic writes for data blobs, since it would add yet another thing to think …

persist: remove Blob::set atomicity argument

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs

Storage usage updates takes the following steps:
1. Collect new storage usage metrics.
2. Update the catalog with new metrics.
3. Update the builtin tables with new metrics.
4. Schedule the next storage usage collection.
Most expensive operations are run off of the main coordinator task. Previously, step (3), updating the builtin tables, happened on the main coordinator task. The storage usage updates can sometimes be huge and updating the builtin tables would end up blocking the main coord task for a long time. This commit mitigates this issue by running step (3) in an async task.
Resolves #26172

adapter: Update storage usage tables off task

---

src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
test/sqllogictest/alter.slt

Fix `SET` syntax for `ALTER MATERIALIZED VIEW`. Implement `RESET` parsing. Add tests for `ALTER RETAIN HISTORY`.
* Can review commit-by-commit.
- n/a

sql-parser: improve various RETAIN HISTORY parsing

---

misc/python/materialize/checks/all_checks/copy_to_s3.py
misc/python/materialize/cloudtest/k8s/minio.py
misc/python/materialize/cloudtest/k8s/testdrive.py
test/cloud-canary/mzcompose.py
test/cloudtest/test_upgrade.py

Seen in https://buildkite.com/materialize/nightlies/builds/7000
-

cloudtest: Make copy-to-s3 with minio work

---

src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/ast/defs/query.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/ast/display.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/copy
src/sql-parser/tests/testdata/ddl
src/sql/src/names.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/with_options.rs
src/sql/src/session/vars/definitions.rs
test/sqllogictest/redacted.slt

As part of fixing the inverted subsource dependency structure, I plan to use `UnresolvedItemName` as a `WITH` option value. However, this conflicted with the previous use of `Ident` as a `WithOptionValue`, so I refactored the code to support the more complex type.
However, in doing this, I encountered some odd behavior with how we redacted values––literal values in `WITH` options could be redacted. In digging into this, I believe the right call is not to always redact values, but instead redact them strategically––this lets us reveal them in uncontroversial contexts (i.e. in `WITH` options).
Most of the code is boilerplate. The code to read is in `src/sql-parser/src/ast/display.rs`.
-

sql: refactor REDACTED logic for `WITH` options

---

ci/nightly/pipeline.template.yml
test/version-consistency/mzcompose.py

The current behavior, which randomly chooses a strategy, confused me a bit today during an analysis.
I suggest to either test only
* against one fixed strategy (would be perfectly sufficient if there were no ignores between both strategies)
* or against both (more comprehensive but not sure if necessary / worthy / justified).

version consistency: test both DFR and CTF

---

test/sqllogictest/pg_catalog_timezone_abbrevs.slt

I haven't figured out the reason yet, seems strange. But let's unblock main branch at least. It seems kind of flaky(?), but we do always seem to run the same tests in SLT's shards, in a deterministic order. I will try to bisect, but in CI when it started failing nothing relevant was changed: https://github.com/MaterializeInc/materialize/compare/488e5ecb490f...442d2bcf8076
-

slt: Disable currently failing test

---

test/sqllogictest/pg_catalog_timezone_abbrevs.slt

The reason this failed is that in SLT we have an `INCONSISTENT_VIEW_OUTCOME_WARNING_REGEXPS` that fails when an indexed view fails to be created with a `"cannot materialize call to"`, which happens because of `now()` in `pg_timezone_abbrevs` definition. The strange part is that sometimes we fail with a different error: `cannot use wildcard expansions or NATURAL JOINs in a view that depends on system objects`. This fix should reenable the test by not using a wildcard (`*`) in the query and thus always failing the same way as before.
@MaterializeInc/compute It is unexpected to me that creating a view throws a different error sometimes. Do we have an explanation for that, for example using parallelism during query planning/optimization? This could cause a bunch of test flakiness where we …

slt: Make pg_catalog_timezone_abbrevs work again 

---

src/storage/src/storage_state.rs
test/cluster/mzcompose.py

Storage replicas only report frontiers of collections that are present in `reported_frontiers`. Entries for subsources are inserted there when a replica receives the `RunIngestions` command that creates them. However, the reconciliation logic would only retain the entries of top-level sources and remove entries of subsources from `reported_frontiers`, regardless of whether or not these subsources were still expected. The correct behavior is to keep around the entries for expected subsources as well.
Fixes #26215 
- N/A

storage: fix subsource frontier reconciliation

---

test/cloud-canary/mzcompose.py

Since this test uses materialize/environmentd instead of materialize/materialized MZ_ORCHESTRATOR=process is not set by default in the entrypoint.
Follow-up to https://github.com/MaterializeInc/materialize/pull/26178
Seen failing in https://buildkite.com/materialize/nightlies/builds/7038
-

canary-cloud-deploy: Set orchestrator process manually

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/worker.py
src/adapter/src/client.rs
src/ore/src/channel.rs
test/cluster/mzcompose.py

This PR should guard against a race condition where the `Coordinator` responds to a request successfully, but a `SessionClient` never observes the response and thus never gets back the `Session` for termination, effectively leaking the `Session`.
~~I haven't tried reproducing this race, but I think if we put a sleep [here](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/client.rs#L818) on `main`, and then close the resulting connection, we should see the Session get leaked.~~
Was able to repro the original issue with Nikhil's test script after running for ~1 minute. After running the same script for ~10 minutes with this PR I could not reproduce the issue.
```
#!/usr/bin/env bash
while :; do
timeout=$(python3 -c 'import random; print(random.uniform(0.01, 1.0))') …
```

coord: Guard against race condition between Coordinator and SessionClient

---

src/adapter/src/coord.rs

Collection of MVs depending on compute indexes had a bug where it uses `Iterator::any` to determine if any of a number of inserts into a `BTreeSet` changed the contents of the set. This didn't consider the fact that `any` is short-circuiting, so if any one insert would return `true`, subsequent ones would be skipped.
This is fixed here by replacing the use of `any` with a `for` loop.
- N/A

bootstrap: fix collection of dependent MVs

---

doc/user/content/get-started/isolation-level.md
doc/user/content/sql/functions/now_and_mz_now.md

I was noodling on this during our meeting and figured I'd just clean it up and send it y'alls way for review.
----
As part of the mz_now() improvements project [0], we agreed to lightly improve the documentation of logical timestamp selection. This PR is an attempt at those improvements.
There's still quite a bit more to explain about how logical timestamp selection works and its implications for performance, but, with this PR, at least we have *something* to point users at when they ask about how the logical timestamp is related to wall clock time.
[0]: https://www.notion.so/materialize/mz_now-braindump-3acde85e02d84cb09808d7c63dab009a#00a22a93afc24c468400bf0e656969ee
* This PR improves documentation.
- n/a

doc/user: MVP documentation for logical timestamp selection

---

src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/names.rs
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/with_options.rs
test/sqllogictest/cluster.slt
test/sqllogictest/materialized_views.slt

This PR just adds the 
`SCHEDULE = {MANUAL | ON REFRESH}`
option to `CREATE CLUSTER` and `ALTER CLUSTER`.
`REFRESH` is not yet implemented, so we just error if the user tries to specify it.
Discussion on whether to have `REFRESH` or `ON REFRESH` [here](https://materializeinc.slack.com/archives/C063H5S7NKE/p1710355545343079).
* This PR is the first step towards adding a known-desirable feature: https://github.com/MaterializeInc/materialize/issues/25712
-

Parsing for REFRESH's automated cluster scheduling

---

src/adapter/src/coord.rs
src/environmentd/src/http/catalog.rs
src/testdrive/src/action/consistency.rs

@teskje pointed out that the Coordinator's new `.../dump` endpoint breaks in practice because a few maps have keys that are not `String`s, which breaks the JSON serialization. I added a check for this in testdrive which didn't work because even on errors we would return a 200.
This PR changes the endpoint to return a 500 if we fail to serialize the state, which should fix the check. It also updates the dump impl to use the `Debug` format for fields to prevent this method from silently breaking in the future
Fix the Coordinator's new state dump API
- N/a

coord: Fix the new dump endpoint

---

test/mysql-cdc-resumption/mzcompose.py

Seen in https://buildkite.com/materialize/tests/builds/79036#018e7632-5a5e-481a-b5f4-396ad2b9f994 (again)
-

mysql-cdc tests: Disable bin-log-manipulations workflow

---

ci/plugins/mzcompose/hooks/post-command

Seen in https://buildkite.com/materialize/nightlies/builds/7039#018e7561-c7fd-4010-be99-4deb5aa9a3b6
Follow-up to https://github.com/MaterializeInc/materialize/pull/26211
-

ci: Ignore services.log missing in output consistency

---

Cargo.lock
src/fivetran-destination/Cargo.toml
src/fivetran-destination/src/destination/dml.rs
src/fivetran-destination/src/error.rs
src/fivetran-destination/src/utils.rs

This PR updates the Fivetran Destination to handle the case when the column ordering of a provided CSV does not match the ordering of the destination table.
Fixes https://github.com/MaterializeInc/materialize/issues/25940
- N/a

fivetran-destination: Map CSV column ordering to Table column ordering

---

src/fivetran-destination/src/destination/config.rs
src/fivetran-destination/src/utils.rs
test/fivetran-destination/data/configuration.json
test/fivetran-destination/mzcompose.py

This PR updates the Fivetran Destination to add a 'cluster' option to the configuration page as an optional parameter. This will change the cluster that the Fivetran Destination uses to update the destination tables.
Fixes https://github.com/MaterializeInc/materialize/issues/24662
- N/a

fivetran-destination: Allow users to specify `cluster` to connect to

---

doc/third-party/fivetran/overview.md
doc/third-party/fivetran/setup-guide.md

I do not intend to merge this PR, just receive edits.
Fivetran requested we write some brief docs on how to setup a Materialize destination. They [provided templates](https://materializeinc.slack.com/archives/C060KAR4802/p1709130386216599) that I more or less did a find-replace with the name "Materialize".
Currently the only blocker from moving the Fivetran Destination from "Closed Private Preview" to "Open Private Preview" on their end.
Makes progress towards: https://github.com/MaterializeInc/materialize/issues/25143
- N/a, these docs would be given to Fivetran

docs: Fivetran Destination User Docs (for Fivetran)

---

misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py

Seen in https://buildkite.com/materialize/nightlies/builds/7050#018e76aa-9017-44a9-919d-de12edfe3b5e
Via documentation: https://materialize.com/docs/sql/functions/
```
regexp_replace(source: str, pattern: str, replacement: str [, flags: str]]) -> str
```
-

output-consistency: Fix regexp_replace return type

---

misc/images/fivetran-destination-tester/Dockerfile
test/fivetran-destination/test-deletes-no-primary/01-setup.json
test/fivetran-destination/test-multi-table/01-workflow.json
test/fivetran-destination/test-multi-table/02-verify.td
test/fivetran-destination/test-writes/02-verify.td
test/fivetran-destination/test-writes/04-verify.td
test/fivetran-destination/test-writes/07-soft-truncate.json
test/fivetran-destination/test-writes/08-verify.td
test/fivetran-destination/test-writes/10-verify.td
test/fivetran-destination/test-writes/11-truncate.json
test/fivetran-destination/test-writes/12-verify.td

This PR upgrades the Fivetran Destination tester to the latest one provided, updates our tests based on changes to the tester, and adds a new hard truncate test case.
Note: This PR is stacked on top of https://github.com/MaterializeInc/materialize/pull/26230, will wait for that to merge first
Better testing of the Fivetran Destination
Fixes https://github.com/MaterializeInc/materialize/issues/26176
- N/a

fivetran-destination: Upgrade tester

---

test/mysql-cdc/alter-table-after-source.td

mysql-cdc: Temporarily disable flaky check

---

ci/test/cargo-test-miri.sh

All fail with
> error: unsupported operation: can't call foreign function `pipe2` on OS `linux`
Seen in https://buildkite.com/materialize/nightlies/builds/7059#018e7a87-8673-4505-a140-db6e24fc3106
-

miri test: Disable fivetran-destination tests

---

src/mz/tests/local.rs

Increasing the `mz` local test timeout as discussed in #25976.
-

mz: Increase timeout for failing coverage CI

---

doc/user/content/sql/create-source/postgres.md

Documents a known limitation of PostgreSQL sources.
-

doc: add known limitation around PG source publication membership

---

src/persist-client/src/batch.proto
src/persist-client/src/fetch.rs
src/persist-client/src/read.rs

SerdeLeasedBatchPart was causing us to invent two serializations for a bunch of things. Instead, base the ExchangeData impl on the proto serialization that already exists.
Pulled out of the inline writes branch, but seemed worthwhile on its own. That said, just as happy to close in favor of keeping it as a commit in the inline writes PR if you'd find the context helpful!
-

persist: replace SerdeLeasedBatchPart internals with a proto

---

test/mysql-cdc-resumption/mzcompose.py

Seen in https://buildkite.com/materialize/tests/builds/79209#018e7dbe-7715-4391-aef3-c2278b5e8b66
To keep tests pipeline green
-

mysql-cdc-resumption test: Disable short-bin-log-retention workflow temporarily

---

ci/nightly/pipeline.template.yml

Seen in https://buildkite.com/materialize/nightlies/builds/7082#018e7d1a-8333-4683-a3af-6cf8b2fc4802
-

ci: Fix depends_on condition in migration checks

---

ci/plugins/cloudtest/hooks/command

Seen in https://buildkite.com/materialize/nightlies/builds/7059#018e7a9e-0717-4cf3-9ef0-0a4261e3a50f
-

cloudtest: Restart docker before tests

---

src/fivetran-destination/src/destination/dml.rs
src/fivetran-destination/src/utils.rs
test/fivetran-destination/test-odd-writes/00-README
test/fivetran-destination/test-odd-writes/01-setup.json
test/fivetran-destination/test-odd-writes/02-verify.td
test/fivetran-destination/test-writes/00-README

Previously I had assumed that a `ByteRecord` contained the raw bytes of a row from a CSV file, specifically that it contained escaped values, this is not the case.
This PR changes how we write mapped `ByteRecord`s into the `COPY FROM` sink, instead of manually adding `,` and newlines we create a `csv_async::AsyncWriter` and use that to serialize the records, which properly escapes all necessary values (e.g. `,`s).
Note: I think this highlights a larger need for more testing of the Fivetran Destination. I have a local branch that adds support for the Fivetran Destination to testdive, and will reach out to the QA team about support.
The Fivetran Destination currently fails to sync data that contains a `,` since it doesn't get properly escaped.
- Fixes an issue with the Fivetran Destination

fivetran-destination: Use AsyncWriter to serialize mapped ByteRecords

---

src/adapter/src/catalog/open.rs
src/sql/src/catalog.rs
test/sqllogictest/managed_cluster.slt
test/sqllogictest/system-cluster.slt
test/testdrive/system-cluster.td

switches the cluster creation from
unmanaged to managed for builtin
internal clusters.
removes explicit replica creation for
mz_system and mz_introspection clusters
https://github.com/MaterializeInc/materialize/issues/22326
-

move initial builtin clusters to be managed

---

src/adapter/src/catalog/open.rs

adapter: fix cluster schedule merge skew

---

src/adapter/src/coord.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs

This PR extends the dump returned by the coordinator's state dump API to also include compute controller state.
* This PR extends our diagnostic abilities.
I mirrored what the coordinator's `dump` method is doing, i.e. formatting the top level as JSON and deferring to `Debug` formatting for the values. Which fields to include is chosen mostly by gut. I tried to include fields that are most likely to have data valuable for debugging common issues and exclude fields that have static data or data that's not likely to be be valuable for debugging. 
Possible follow-ups if we agree that this approach is a good one:
* Also include storage controller state.
* Provide a dump endpoint on `clusterd` as well.
- N/A

Make compute controller state dumpable

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/parallel_workload.py

parallel-workload: Make sure to close all connections

---

misc/python/materialize/output_consistency/validation/result_comparator.py

This is to avoid that the value does not get compared if the type does not match.

output consistency: prioritize value check over type check

---

misc/python/materialize/mzcompose/composition.py
test/skip-version-upgrade/mzcompose.py

https://materializeinc.slack.com/archives/C01LKF361MZ/p1711452276830939
-

mzcompose: Only retry docker pulls

---

src/catalog/src/builtin.rs

Fixes https://github.com/MaterializeInc/materialize/issues/26292, see https://materializeinc.slack.com/archives/CUCF68PEV/p1711551244343709
Is there anything else I need to do to make sure this doesn't break anything? These catalog views are in `mz_internal` so we're able to make breaking changes. I notified the console team, and they are making a fix on their side to stop querying for this column.
-

Remove error_message from mz_recent_activity_log_redacted and mz_statement_execution_history_redacted

---

src/adapter/src/coord.rs
src/compute-types/src/dataflows.rs
test/cluster/mzcompose.py

This PR fixes another issue with dataflow as-of bootstrapping that could disable compute reconciliation. The oversight here was that an envd restart can make index write frontiers regress (since they are reset to their newly selected read frontiers), which makes it likely that using these frontiers to determine an as-of for compute dataflows will produce an as-of that is earlier than the frontiers already installed dataflows have been allowed to compact to.
The solution to this issue is to select as-ofs based on the frontiers of (transitive) storage dependencies instead. Storage frontiers cannot regress, so they are guaranteed to provide an as-of that is far enough advanced for reconciliation to succeed.
The knowledge about transitive storage dependencies was not yet available during …

bootstrap: fix as-of selection for compute reconciliation

---

misc/python/materialize/mzcompose/composition.py
test/cluster/mzcompose.py
test/skip-version-upgrade/mzcompose.py

This caused problems, see https://materializeinc.slack.com/archives/C01LKF361MZ/p1711635515718939 I'll work on fixing them.
This reverts commit 5deaad2e880413a27ebf9f9385371b92e85b9f72.
-

Revert "mzcompose: Only retry docker pulls"

---

misc/python/materialize/mzcompose/composition.py
test/skip-version-upgrade/mzcompose.py

Maybe it's smarter to do this way, no additional `docker pull` calls, just check the error messages
-

mzcompose: Only retry docker pulls (2nd attempt)

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
src/adapter/Cargo.toml
src/environmentd/Cargo.toml
src/expr-parser/Cargo.toml
src/expr-test-util/Cargo.toml
src/expr/Cargo.toml
src/lowertest/Cargo.toml
src/persist-client/Cargo.toml
src/persist-client/src/internal/datadriven.rs
src/pgtest/Cargo.toml
src/repr-test-util/Cargo.toml
src/sql-lexer/Cargo.toml
src/sql-parser/Cargo.toml
src/sql-pretty/Cargo.toml
src/sql/Cargo.toml
src/storage/Cargo.toml
src/transform/Cargo.toml
src/walkabout/Cargo.toml

We've got a lot of datadriven checks now; this helps narrow down which one is causing a panic.
(We could probably try and catch the panic / log more judiciously, but I'll leave that for future work unless someone feels strongly.)
-

[testing] Upgrade datadriven and log the filename in some persist tests

---

src/adapter/src/coord/sequencer/inner.rs
src/storage-types/src/connections.rs
src/storage-types/src/connections/aws.rs
src/storage-types/src/connections/inline.rs
src/storage-types/src/lib.rs
src/storage-types/src/sinks.rs
src/storage-types/src/sources.rs
src/storage-types/src/sources/encoding.rs
src/storage-types/src/sources/kafka.rs
src/storage-types/src/sources/mysql.rs
src/storage-types/src/sources/postgres.rs
test/mysql-cdc-resumption/alter-source-connection.td

Discovered a few issues:
- We were not properly checking if the `SourceDesc` in an `IngestionDescription` was alter compatible. We were instead inadvertently checking whether a the field was equal to itself. Fixing this necessitated building out more implementations of `alter_compatible`.
- MySQL connection were not altered whatsoever in any test, which would have failed if they had been.
- I realized that the `ConnectionAccess` types could also be tested for alter compatibility somewhat easily.
The only real harm that could have been done with this bug was a user changing their Kafka connection's progress topic, which we've already disallowed in planning. This change is just adding safeguards.
- This PR fixes a previously unreported bug.
- Altering a source's connection should have …

storage: fix + extend alter_compatible API

---

.github/CODEOWNERS
src/sql/src/plan/lowering/variadic_left.rs

Support trivial `true` conjuncts, which occur when planning `USING(...)` clauses.
Builds up on #24345 by expanding the set of cases supported in #25340.
TODO
-

sql: expand `variadic_left::decompose_equations` coverage

---

src/adapter/src/catalog/open.rs

a88879f21c942bf8cd81464ea12b81fe29952035 fixed a bug to remove builtin objects from the durable catalog if they've been removed from Materialize. Previously, the objects would leak and sit around in the durable catalog after they were removed from Materialize.
As part of that commit, we added an assert to make sure all deleted objects were in the `mz_internal` schema. Deleting system objects that are not in the `mz_internal` schema is a breaking change and can result in losing user data.
As it turns out, at multiple points in the past we have deleted system objects that weren't in the `mz_internal` schema. All production (and staging) environments that have been around long enough to have those deleted non-`mz_internal` objects will trigger the added assert and fail to upgrade.
This …

adapter: Temporarily remove migration assert

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/optimize/copy_to.rs
src/compute-types/src/sinks.proto
src/compute-types/src/sinks.rs
src/compute/src/sink/copy_to_s3_oneshot.rs
src/controller/src/clusters.rs
src/storage-operators/src/s3_oneshot_sink.rs
src/testdrive/src/action/s3.rs
test/aws-localstack/copy-to-s3/copy-to-s3.td
test/aws-localstack/mzcompose.py
test/testdrive/copy-to-s3-minio.td

Changes to write to s3 from multiple workers, part of https://github.com/MaterializeInc/materialize/issues/7256
Opening this PR to get some early feedback. I will try to get the changes to make the bucket size configurable by tomorrow.
@benesch If I am not able to get this merged by this week, somebody else will have to pick this up.
cc @petrosagg @guswynn 
-

storage, compute: copy to s3 with multiple workers

---

src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/lib.rs

The real win here is removing `parent: None` so that the printed `Root trace ID` is hooked up to catalog init. That span does exit after full envd bootstrap (not a long-running span).
This will be used to make envd startup faster.
- n/a

environmentd: improve bootstrap tracing

---

src/catalog/src/durable/initialize.rs

The default cluster should be created with disk if it is using a cc size. This brings the logic in line with how all other clusters are created.
- n/a

catalog: give default cluster disk if cc size

---

src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/events.rs
test/mysql-cdc/alter-table-after-source.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/24630
After we realized #26223 wouldn't work, @benesch [discovered](https://github.com/MaterializeInc/materialize/issues/24630#issuecomment-2018082249) that the [`Xid` ](https://dev.mysql.com/doc/dev/mysql-server/latest/classXid__log__event.html)event should be more reliable for signifying the end of the current transaction. So we can now use this in addition to the heartbeat-event to know that we are done receiving updates for the current GTID, avoiding the heartbeat delay in most cases (when using the common mysql storage engine).
I plan to trigger the nightlies on this PR to ensure it behaves correctly with the zippy tests, etc.
-

storage/mysql: Use transaction Xid event to advance frontier beyond current GTID

---

src/storage-client/src/sink.rs

custer should be cluster
fixes typo
-

fix typo in sink.rs

---

Cargo.lock
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/kafka-util/src/client.rs
src/mysql-util/src/tunnel.rs
src/ore/src/future.rs
src/postgres-util/src/tunnel.rs
src/sql/src/pure.rs
src/ssh-util/src/tunnel_manager.rs
src/storage-client/src/sink.rs
src/storage-operators/src/s3_oneshot_sink.rs
src/storage-types/Cargo.toml
src/storage-types/src/connections.rs
src/storage-types/src/connections/aws.rs
src/storage/src/decode/mod.rs
src/storage/src/sink/kafka.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/mysql/statistics.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs

Partially closes: https://github.com/MaterializeInc/materialize/issues/25707
We have seen erroneous timeouts and pathological behavior when IO futures that expects to be polled promptly is starved from busy timely threads. This pr addresses, and ensures that ALL IO performed from storage (with the exception of mysql queries, which is tracked here: https://github.com/MaterializeInc/materialize/issues/25390) is performed in a tokio task. This is already true for persist, but we have (many) leftover spots.
I went through a couple iterations here, and even tried to create a single trait that defined and `async connect` method for all storage connections. However, in practice, the various connections have very different interactions at their callsites, so I went with a single boolean.
The pr …

storage: avoid connecting to upstream services from timely threads as a stopgap

---

src/dyncfg/src/lib.rs
src/persist-client/src/cfg.rs
src/sql/src/session/vars.rs

Split out from #25912. This PR is the foundational refactors that are believed to be unobjectionable. 
- n/a

dyncfg: minor ergonomic improvements to API

---

src/storage-client/src/metrics.rs
src/storage-client/src/statistics.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/statistics.rs
src/storage/src/statistics.rs

There is a long-form justification of this choice and implementation inline within the code. I recommend reviewing the commits separately, as the first commit is cleanup!
Closes https://github.com/MaterializeInc/materialize/issues/25802

storage: avoid sentry errors on known offset_known regressions

---

src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs

This commit adds the initial infrastructure for the in-memory catalog to update itself in reaction to changes made by the durable catalog. Additionally, it implements the update logic for databases. Future commits will add the update logic for all catalog objects.
The update logic is used when opening the catalog to initialize the in-memory catalog. A more obvious place to use the update logic might have been during catalog transactions. However, currently catalog transactions update both the in-memory catalog state and a durable transaction for each operation. The end goal is to have the catalog transaction only update a durable transaction and then update the in-memory state using the update logic after the durable transaction commits. Using the update logic in a catalog transaction …

catalog: Add infrastructure for listening catalog

---

src/adapter/src/catalog.rs

This PR slightly refactors the `RenameSchema` op to update the durable transaction with the new items all at once instead of calling `tx.update_item(...)` for each item. `update_item(...)` iterates through the entire catalog every time it's called so it can be quite slow.
Creating two schemas with 100 views each, and then 500 views depending on the 100 views in a schema we exhibit the following performance.
`main`
```
materialize=> ALTER SCHEMA blue SWAP WITH green;
ALTER SCHEMA
Time: 37301.170 ms (00:37.301)
```
This PR
```
materialize=> ALTER SCHEMA blue SWAP WITH green;
ALTER SCHEMA
Time: 470.736 ms
```
_Greatly_ improves the speed of `ALTER SCHEMA ... SWAP WITH ...`
- Performance improvement for `ALTER SCHEMA ... SWAP WITH ...`

blue/green: Update items in the transaction all at once

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/adapter/src/coord.rs
src/adapter/src/coord/timeline.rs
src/catalog-debug/src/main.rs
src/catalog/src/config.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/sql/src/session/vars/value.rs

Previously, we would provide a non-linearizable boot timestamp to `Catalog::open`. A non-linearizable timestamp is not written down, and therefore it's possible that a later environment boots up with a lower timestamp. We were unable to provide a linearizable timestamp due to a bootstrapping problem. We needed to look in the catalog to see what timestamp oracle implementation to use, but we needed to know which timestamp oracle implementation to use to get a linearizable timestamp to open the catalog.
Now that there's only a single timestamp oracle implementation, this bootstrapping problem has gone away. This commit updates the bootstrap process so that a linearizable timestamp is passed to `Catalog::open`. This is useful for things like adding audit log events in a migration, which …

adapter: Provide linearizable boot timestamp

---

misc/python/materialize/buildkite.py
test/bounded-memory/mzcompose.py

Allow running bounded-memory with parallelization (e.g., in special builds searching for closer memory limits) but do not enable it by default since the build only takes 30 minutes.

bounded memory: allow parallelization

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs

Refactor to simplify some calling.
- n/a

adapter: change parse_item to take a &str

---

src/fivetran-destination/src/destination/config.rs

The Fivetran Destination has an optional `cluster` param, sometimes ([maybe always?](https://materializeinc.slack.com/archives/C060KAR4802/p1712066689976429?thread_ts=1712066017.988619&cid=C060KAR4802)) optional parameters get provided as an empty string which is meant to indicate `None`. This PR adds handling to map the empty string for the `cluster` param to `None`.
Note: I locally rebased this on top of https://github.com/MaterializeInc/materialize/pull/26334 and manually made sure the empty string case gets correctly handled.
Fixes a bug in the destination
- N/a

fivetran: Update handling of optional params

---

src/compute/src/compute_state.rs
src/persist-client/src/cfg.rs
src/persist-client/src/rpc.rs
src/storage-controller/src/lib.rs
src/storage/src/storage_state.rs

Alternative to https://github.com/MaterializeInc/materialize/pull/25912.
This commit keeps `clusterd` from establishing its persist PubSub
connection until `environmentd` sends over its initial batch of
configuration values. This ensures that any parameters that should apply
to the connection (e.g., timeouts) actually take effect.
The implementation is kept as simple as possible: a boolean value in
`PersistConfig` indicating whether at least once sync with
`environmentd` has taken place.
Fix https://github.com/MaterializeInc/materialize/issues/23869.
This is an alternative to https://github.com/MaterializeInc/materialize/pull/25912. The implementation is simpler, but plausibly more error prone, as it relies on users of `PersistConfig` to set …

clusterd: ensure system vars apply to persist PubSub connection (redux)

---

ci/nightly/pipeline.template.yml

Follow-up to https://github.com/MaterializeInc/materialize/pull/26372. Still parallelize bounded-memory because of recent issues (gets sometimes stuck due to increased load with additional scenarios).

bounded memory: parallelize

---

ci/nightly/pipeline.template.yml

A successful build passes within 30 minutes.

ci: set timeout of bounded-memory to a reasonable value

---

src/storage/src/render/upsert.rs
src/storage/src/render/upsert/autospill.rs
src/storage/src/render/upsert/memory.rs
src/storage/src/render/upsert/rocksdb.rs
src/storage/src/render/upsert/types.rs
src/storage/src/statistics.rs
test/upsert/autospill/01-setup.td
test/upsert/mzcompose.py

This is broken out of: https://github.com/MaterializeInc/materialize/pull/24663
Fundamentally, fixing https://github.com/MaterializeInc/materialize/issues/23998 requires that the upsert state backends are able to _ingest data that arrives before a progress update_. This requires we store and _order key_ alongside that data, so that we can order values for the same key that occurred at the same _source time_, but within the same mz timestamp. This includes tombstones for keys that were deleted. This pr adds this functionality to the upsert state backend, but does not make use of it yet.
Tombstones unfortunately take up permanent space in the state. There is no easy way around this (other than doing a full range scan of the state on `Progress` updates), and our choice to avoid doing so will …

storage: support order keys in upsert state api

---

src/persist-client/src/cfg.rs
src/persist-client/src/cli/admin.rs
src/persist-client/src/internal/apply.rs
src/persist-client/src/internal/diff.proto
src/persist-client/src/internal/encoding.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/metrics.rs
src/persist-client/src/internal/restore.rs
src/persist-client/src/internal/state.proto
src/persist-client/src/internal/state_diff.rs
src/persist-client/src/internal/trace.rs
src/proto/src/lib.rs

Previously, while we'd write down the _contents_ of the spine, we did not write down the _structure_ -- including any details about fuel or the level that various batches were at.
This PR adds some new state metadata that preserves this information -- while also taking care to keep the "legacy" hollow batches stored in the same way to preserve compat and avoid large diffs.
This is the foundational change for: #16607 
This is mostly organized commit-by-commit, in case that helps with review.
There were a lot of degrees of freedom with this change; please let me know what doesn't feel obvious, and I'll either change it to make more sense or add some comments. (`FlatTrace` certainly needs more comments, and I'll follow up with those.) 
-

[persist] Roundtrip spine structure through state

---

Cargo.lock
src/fivetran-destination/Cargo.toml
src/fivetran-destination/README.md
src/fivetran-destination/build.rs
src/lowertest-derive/Cargo.toml
src/lowertest/Cargo.toml
src/persist-types/Cargo.toml
src/persist-types/build.rs
src/pgrepr-consts/Cargo.toml
src/pgrepr/Cargo.toml
src/pgtz/Cargo.toml
src/pgtz/build.rs
src/pgwire-common/Cargo.toml
src/proto/Cargo.toml
src/proto/build.rs
src/repr/Cargo.toml
src/repr/build.rs
src/server-core/Cargo.toml

This PR aims to make the dependency of `protobuf-src` optional for the Fivetran Destination, it also has the benefit of reducing the number of dependencies by removing the dependency on `workspace-hack`. Mostly this entailed hunting down the transitive dependencies that also used `protobuf-src` and making `protobuf-src` optional their too, but enabled by default. Relevant [Slack convo](https://materializeinc.slack.com/archives/CMH6PG4CW/p1712153228671109) with how we landed on this approach.
Fivetran hit some issues when building related to compiling `protoc` and to work around them we don't build the vendored version of `protoc` and rely on the version present in their path.
Fix build issues for Fivetran, reduce the time required to build.
-

fivetran: Make dependency on `protobuf-src` optional

---

doc/user/content/ingest-data/fivetran.md
doc/user/content/integrations/_index.md

Under the `/ingest-data/` section, but not listed in the "Ingest Data" sidebar.
Linked in the `/integrations/` overview page.
Closes https://github.com/MaterializeInc/materialize/issues/25143
-

Add docs integration guide on Fivetran

---

src/sql/src/names.rs

adapter: Fix system replica ID check

---

src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs

This commit teaches the in-memory catalog how to listen to role and
comment updates.

catalog: Listen to role and comment updates

---

src/compute/src/render/mod.rs
src/compute/src/sink/persist_sink.rs
src/storage-operators/src/persist_source.rs
src/storage/src/render/sinks.rs
src/storage/src/render/sources.rs

This reverts commit 718224fd2b63449cdafe4cb7b96aadf046137bd1.
Turns out this changes the name in more places than I expected: https://github.com/MaterializeInc/materialize/pull/26402#issuecomment-2035246080
-

Revert "storage: more descriptive logging for persist_source/shard_source"

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/sql.rs
src/adapter/src/coord/timeline.rs
src/adapter/src/coord/timestamp_selection.rs
src/adapter/src/lib.rs
src/adapter/tests/timestamp_selection.rs

This is preparatory work for #24845, where we
factor a `StorageCollections` out of present-day `StorageController`.
And this `StorageCollections` will be shareable and will come with the
possibility of fontiers advancing concurrently.
We therefore need to guard places where we make assumptions about
frontiers by first acquiring read holds. This will "lock" sinces in
place where they currently are and then look at those sinces.
**NOTE:** There's a known bug with dropping `ReadHolds` that I still have to figure out, and I have to rebase across a slightly more involved conflict. But I wanted to get the basic structure out for review now, to see how you like and and if you prefer one of the approaches I mention below.
I implemented two solutions which I'll call _static read holds_ and …

adapter: acquire read holds before making assumptions about collection sinces

---

src/environmentd/src/http/sql.rs
src/environmentd/tests/testdata/http/ws

So that notices about e.g. a cluster restarting, or other things that might indicate a query is going to take a long time to complete, can be emitted while the query is running, instead of after it completes.
Fix #22739.
Still working on a test for this, but I verified manually that it works as expected, so putting up for review.
- n/a

environmentd: eagerly emit notices in WebSocket protocol

---

src/pgwire/src/protocol.rs

This PR changes the handling for statement logging in `COPY FROM`. Previously we asserted the returned statement logging context was trivial (i.e. no statement UUID) but this isn't the case if statement logging is enabled.
Fixes https://github.com/MaterializeInc/materialize/issues/26432
- Fixes a panic with COPY FROM

sql: Don't panic in statment logigng with COPY FROM

---

src/fivetran-destination/src/destination/dml.rs
src/testdrive/src/action/fivetran.rs
test/testdrive/fivetran-destination.td

This PR updates the Fivetran Destination to change how it copies data into temporary tables within Materialize.
* Fixes an unspecified bug
Previously we would copy all CSV files via a single `COPY ... FROM` statement. This was sub-optimal because Materialize has a maximum buffer size when copying files. For example, if the maximum buffer size is 100MiB, you should be able to copy 2 80MiB files, you just need to use an individual `COPY ... FROM` for each. We were not doing this though so we would fail when trying to sync a large enough volume of data.
- Improves the amount of data that can be synced with the Fivetran Destination

fivetran-destination: Start separate `COPY FROM` sinks for each file

---

src/persist-types/src/codec_impls.rs
src/persist-types/src/columnar.rs
src/persist-types/src/dyn_col.rs
src/persist-types/src/stats.proto
src/persist-types/src/stats.rs
src/repr/src/lib.rs
src/repr/src/row/encoding.rs
src/repr/src/stats.rs
src/storage-types/src/sources.rs
src/storage-types/src/stats.rs

This PR adds a V0 Arrow encoding for the following `Datum`s:
* `Array`
* `List`
* `Record`
* `Map`
* `Int2Vector`
* `Range`
* `MzAclItem`
* `AclItem`
The V0 format is a `BinaryArray` that contains an encoded ProtoDatum` and does not collect any stats other than `null_count`.
TODO: I'll benchmark the performance to make sure this doesn't slowdown the stats collection codepath too much.
Unblocks writing structured columnar data because now we have _a_ way to encode all datums.
I split this PR into three separate commits which could be reviewed independently:
1. Add `NoneStats` type
2. Implement the `Data` trait for a new `OpaqueData` type.
3. Update `Datum` encoding for above listed types.
- N/a

persist/columnar: Add Data impl for "OpaqueData"

---

src/sqllogictest/ci/Dockerfile

The sqllogictest image was previously starting from ubuntu-base and using apt-get to install llvm. We've already got several images that install llvm, so reuse one of them. This should save a couple minutes in the aarch64 build in CI (and 45s-1m in x86_64).
-

sqllogictest: use an existing Dockerfile base

---

test/bounded-memory/mzcompose.py

It failed in the nightly build of the release: https://buildkite.com/materialize/nightlies/builds/7249#018eabb1-4abd-4b10-957e-6229981f5a6d
See also: https://github.com/MaterializeInc/materialize/pull/26267#issuecomment-2039085008

tests: bounded memory: stabilize pg-cdc-large-tx by increasing clusterd memory

---

misc/python/materialize/mzcompose/__init__.py
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/cluster-client/src/client.proto
src/cluster-client/src/client.rs
src/cluster/src/server.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/replica.rs
src/controller/src/lib.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/storage-controller/src/rehydration.rs

This PR removes the internal `idle_arrangement_merge_effort` option, which has been supplanted by `arrangement_exert_proportionality`. The SQL-level cluster/replica option has been removed previously in #26319, so this option was only accessible through a feature flag and has been switched off everywhere for months now.
This PR also renames the feature flag `default_arrangement_exert_proportionality` to just `arrangement_exert_proportionality`, stripping the misleading "default" prefix. It was added when we were still planning to have a cluster/replica option that could override the feature flag, but we are not planning this now.
Follow-up to https://github.com/MaterializeInc/materialize/issues/17002
Once we have wired up the compute controller to …

*: remove the internal `idle_arrangement_merge_effort` option

---

src/environmentd/tests/pgwire.rs
src/pgcopy/src/copy.proto
src/pgcopy/src/copy.rs
src/pgcopy/src/lib.rs
src/pgwire/src/protocol.rs
src/sql-parser/tests/testdata/copy
src/storage-operators/src/s3_oneshot_sink.rs
test/pgtest/copy.pt

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/4982
Somewhat of a side-quest to the copy-to-s3 work, this completes some `TODO`s that were enabled by the work in https://github.com/MaterializeInc/materialize/pull/25521 which gave us the pieces to implement `COPY .. TO STDOUT (FORMAT CSV)`.
-

Support for FORMAT CSV in COPY TO STDOUT

---

src/fivetran-destination/Cargo.toml

As it says in the title, enable the `native-tls-vendored` feature.
Prevent the build process from trying to link openSSL
- N/a

fivetran: Enable the `native-tls-vendored` feature for reqwest

---

src/compute/src/compute_state.rs
src/compute/src/render/context.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/reduce.rs
src/compute/src/row_spine.rs
src/repr/src/fixed_length.rs

We don't use the type information, and at the moment it is only a run-time validation of something that should be enforced by the type system / partial validation that we aren't shipping around malformed rows. No urgency to merge, but also complexity that results from needing to carry the correct arguments around.
-

Tidy `IntoRowByTypes` and `FromRowByTypes`

---

src/compute-types/src/dyncfgs.rs
src/compute/src/sink/persist_sink.rs

This config was added as a failsafe to derisk the introduction of the `UpdateStash` in the `persist_sink`. The `UpdateStash` has been deployed in production without issues, so the failsafe is not needed anymore.
* This PR removes a feature flag.
- N/A

compute: remove `enable_persist_sink_stash` config

---

test/sqllogictest/pg_catalog_timezone_abbrevs.slt

If this happens again (for a third time), we should probably just stop checking the actual timezone values. It's an obvious source of tests breaking without code changes.
Seen in https://buildkite.com/materialize/tests/builds/80005#018eb3ed-e09b-4907-b7cc-5cf1943adc81
-

slt: Fix expected timezones

---

test/bounded-memory/mzcompose.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/26450
Still failed in https://buildkite.com/materialize/nightlies/builds/7266
-

bounded-memory test: Increased clusterd memory for pg-cdc-large-tx

---

misc/python/materialize/data_ingest/executor.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/executor.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/worker.py

Fixes #26422
@nrainer-materialize I reverted your previous fix, I hope that's ok for you. I think your fix was too complex, we don't require having the worker id since the parallel-workload.log will already contain the command and which worker copied to each s3 path. The renaming of the executors I didn't understand, did they conflict in some file? If so they can be imported under a different name in that file. Otherwise I don't want to add the name of the testing framework to each class, otherwise we'll have a lot of `FeatureBenchmarkAction`, `ParallelWorkloadAction`, `ZippyAction`, etc.. Since they don't usually interact with each other I think each of them just being called `Action` is fine.
Tip for reviewers: Only the last commit does anything, the rest is just a revert.
-

parallel-workload: Simpler fix for copy-to-s3 contention

---

src/ccsr/tests/client.rs

Fixes #18269
So far no failures locally, but I'll keep it running for a bit before submitting: `while true; do cargo nextest run -p mz-ccsr test_client_subject_and_references || break; done`
-

cargo test: Reenable test_client_subject_and_references

---

ci/test/lint-main/checks/check-cargo.sh

`cargo install --list` does not work in ci-builder.
Previous output:
```
lint: cargo-about is not installed
hint: install it with: cargo install cargo-about
lint: cargo-hakari is not installed
hint: install it with: cargo install cargo-hakari
lint: cargo-deplint is not installed
hint: install it with: cargo install cargo-deplint
```
-

lint: More reliably detect if cargo tools are available

---

Cargo.lock
deny.toml
misc/cargo-vet/imports.lock

and mark not-so-easy to upgrade dependencies to be ignored. As seen in https://buildkite.com/materialize/security/builds/1179#018e99f9-79d7-4b6d-926e-1697e87d4c7e This started failing following the Rust 1.77 upgrade.
These are not new warnings, they were previously just ignored as warnings, and are now considered errors.
-

build: Update h2 0.3.24 -> 0.3.26, unsafe-libyaml 0.2.9 -> 0.2.11, openssl-src

---

test/canary-environment/macros/create_loadgen_source.sql
test/canary-environment/models/loadgen/customer.sql
test/canary-environment/models/loadgen/product.sql
test/canary-environment/models/loadgen/product_category.sql
test/canary-environment/models/loadgen/region.sql
test/canary-environment/models/loadgen/sales.sql
test/canary-environment/models/loadgen/store.sql
test/canary-environment/models/loadgen/supplier.sql
test/canary-environment/models/mysql_cdc/mysql_cdc.sql
test/canary-environment/models/pg_cdc/pg_cdc.sql
test/canary-environment/models/tpch/tpch.sql

Follow-up to https://github.com/MaterializeInc/materialize/pull/25405
-

canary-environment: Adapt to v2 dbt sources

---

misc/python/materialize/cloudtest/util/jwt_key.py
test/canary-environment/dbt_project.yml
test/canary-load/mzcompose.py

Requires new infra+qacanaryload@materialize.io user to allow using that endpoint without having to go through SSO: https://github.com/MaterializeInc/i2/pull/1780
-

canary-load: Add api/sql load

---

src/adapter/src/catalog.rs
src/catalog/src/memory/error.rs
src/sql/src/rbac.rs
test/sqllogictest/alter.slt
test/sqllogictest/cluster.slt
test/sqllogictest/default_privileges.slt
test/sqllogictest/system-cluster.slt
test/sqllogictest/unstable.slt
test/testdrive/system-cluster.td

The system relies on many system objects not being modified by users,
even superusers and even when RBAC is turned off. This has required us
to layer additional checks for system objects on top of RBAC, since
it's possible for superusers (and users with RBAC turned off) to skip
RBAC checks on system objects. This commit updates RBAC checks so that
even if RBAC is turned off or the caller is a superuser, checks against
system objects are still performed, so that we can remove many of the
additional checks against system objects.
Unfortunately, there are some modifications that even `mz_system`
shouldn't make, such as deleting a catalog table, or else the system
will break. So, we need to keep additional checks that prevent those
modifications to safeguard `mz_system` from accidentally …

RBAC: Make system object privileges more robust

---

src/environmentd/tests/auth.rs
src/frontegg-auth/src/auth.rs

Handing this one off to @ParkMyCar. We need to add a test to validate the new behavior here.
----
Discovered during part of incident 103.
Fix https://github.com/MaterializeInc/materialize/issues/26477.
- n/a

frontegg-auth: avoid caching error responses

---

src/persist-client/src/internal/metrics.rs

Seems useful to have in traces.
-

persist: include size in blob::set and consensus:cas tracing spans

---

src/persist/src/indexed/columnar/arrow.rs
src/persist/src/location.rs

This PR deletes some unused code for an Arrow-based columnar encoding that theoretically could be used for a local blob file cache. If we want to re-add this format in the future I'll be more than happy to do so :)
AFAICT this code hasn't been touched in a couple years and is currently unused, as we make changes to the Parquet columnar format it makes things a bit easier to reason about if we don't need to handle this currently unused case. 
- N/a

persist: Delete unused code

---

ci/test/docs-widgets/webhooks-datagen.test.js

Adding some basic tests for the webhooks datagen docs JS widget.
-

Doc: Add tests for the datagen webhook js docs widget

---

bin/ci-builder
test/canary-load/mzcompose.py

Forgotten in https://github.com/MaterializeInc/materialize/pull/26277
Test run: https://buildkite.com/materialize/qa-canary-environment-base-load/builds/65
-

ci-builder: Pass through new canary loadtest passwords

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

As noticed in https://github.com/MaterializeInc/materialize/issues/26323#issuecomment-2044133655
-

postgres-consistency: Also ignore equality operators

---

Cargo.lock
src/compute-client/Cargo.toml
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/replica.rs
src/compute-client/src/controller/sequential_hydration.rs
src/compute/src/compute_state.rs
src/compute/src/render/mod.rs
src/compute/src/server.rs

This PR moves the sequential hydration logic out of the replica code and into a new `SequentialHydration` compute client that sits between the compute controller and the `PartitionedState` client. The benefit of this is that the sequential hydration code is encapsulated in a single module that has no other responsibilities and can therefore be reasoned about more easily.
Part of #25271 
The commits can be reviewed separately.
- N/A

compute: `SequentialHydration` client

---

src/compute-types/src/dataflows.rs

`DataflowDescription::is_imported` was failing to check if the given ID was exported as an index, so it would only detect imported views and sources. Fixed by checking for membership in `index_imports` as well.
`DataflowDescription::is_imported` always returns `false` for index imports.
This is no big deal since `is_imported` is currently only used in `DataflowBuilder::import_into_dataflow` where it allows us to avoid redundant work. Importing an index twice only makes the new import overwrite the old one and does no harm.
- N/A

compute: fix `DataflowDescription::is_imported`

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
misc/python/materialize/feature_benchmark/scenarios/concurrency.py
misc/python/materialize/zippy/scenarios.py

Trial run (of an older state, I already disabled the three failing tests): https://buildkite.com/materialize/release-qualification/builds/467#_
-

ci: Make Release Qualification green again

---

test/sqllogictest/introspection/unstable.slt

Following https://github.com/MaterializeInc/materialize/pull/26434
Fixes https://github.com/MaterializeInc/materialize/issues/26522
-

slt: Adapt unstable.slt to new reality

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl

The following is currently accepted in the Console:
```
CREATE CLUSTER c1 (SIZE = '3xsmall';
```
(In psql, this is prevented due to some psql-specific mechanism.)
This PR makes it so that if the `(` is there, then we also expect the `)`. (But still allows for leaving out both `(` and `)` at the same time, for historical reasons.)
-

Expect matching parens around cluster options

---

src/testdrive/src/action/sql.rs

This applies a fix to https://github.com/MaterializeInc/materialize/pull/26496.
Use the `timeout` instead of `default_timeout`, which takes `set-sql-timeout` into account.

testdrive: fix query timeout

---

src/storage/src/metrics/sink/kafka.rs
src/storage/src/sink/kafka.rs
test/source-sink-errors/mzcompose.py

storage: add sink metric for number of partitions

---

src/adapter/src/coord/ddl.rs
test/cloudtest/test_privatelink_connection.py

use run_in_task_if for vpc endpoint drop
and add span to task
Drop vpc is an external call that should be moved to a task rather than blocking the coordinator. This particular call has been known to lead to a stall and envd crash. 
inspiration from https://github.com/MaterializeInc/materialize/pull/25795
-

drop vpc endpoint in task

---

src/persist-client/src/batch.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/paths.rs

Noticed an uptick in noop deletes in our staging environment. This would cause an increase in the number of unreferenced blobs that would need to be cleaned up out of band.
It turns out that this bug was the only user of the `Deref` impl on partial keys, and I feel like that impl is probably kind of a footgun since it makes it very easy to use the partial key as a blob key... so I've deleted that too. Let me know if that sounds wrong!
-

[persist] Delete from blob with the full key

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/message_handler.rs
src/sql/src/pure.rs

Certain statements must be purified off thread before they are planned. Previously, after purification we were correctly checking that the statement's `GlobalId` dependencies were still valid, but we were not checking other dependencies, such as cluster dependencies. This commit fixes the described issue by using the existing `PlanValidity` struct to track and re-validate the statement's dependencies.
Fixes #26538

adapter: Validate off-thread purification

---

misc/python/materialize/mzcompose/__init__.py
src/sql/src/func.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
test/sqllogictest/filter-pushdown.slt
test/sqllogictest/try_parse_monotonic_iso8601_timestamp.slt

These are now in GA and on everywhere. Remove the flags.
Touches #26545
-

persist: remove unconditionally enabled configs

---

Cargo.lock
src/storage-types/Cargo.toml
src/storage-types/src/connections.rs
src/storage-types/src/dyncfgs.rs
src/storage-types/src/sinks.rs
src/storage-types/src/sources/kafka.rs
src/storage/src/sink/kafka.rs
src/storage/src/source/kafka.rs

Fixes https://github.com/MaterializeInc/cloud/issues/8316.
I've tested this manually and it works as expected. It's hard to write an automated test for this, though, as Kafka brokers don't readily expose the `client.id`s of connected clients. I think that's fine, given that this feature is purely for analytics, and has no bearing on the Materialize's observable behavior.
Skip the first two commits. Those are #26470.
See LaunchDarkly to preview the enrichment rule we plan to enable in production: https://app.launchdarkly.com/default/production/features/kafka_client_id_enrichment_rules/variations.
- n/a

storage: allow dynamically enriching Kafka client IDs

---

ci/nightly/pipeline.template.yml

Seen timing out in https://buildkite.com/materialize/nightly/builds/7310#018ec3ea-65a0-4dd5-bd65-58653edbfb2a
-

ci: Increase timeout for RQG Banking scenario

---

misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/values/bytea_values_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

postgres-consistency test: Ignore translate function

---

src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/replica.rs
src/compute-client/src/controller/sequential_hydration.rs
src/compute-client/src/metrics.rs
test/cluster/mzcompose.py

This PR adds two metrics in support of the sequential hydration feature:
* `mz_compute_controller_collections_unscheduled_count` counts the number of collections for which the controller has not yet sent a `Schedule` command.
* `mz_compute_controller_hydration_queue_size` counts the size of the hydration queue in the `SequentialHydration` client.
Part of https://github.com/MaterializeInc/materialize/issues/25271
- N/A

compute-client: metrics for sequential hydration

---

src/orchestrator-tracing/src/lib.rs
src/sql/src/session/vars/definitions.rs

We've now rolled out "info" to all of staging and prod. Change the default in code so that we pick it up in things in bin/environmentd.
-

*: set opentelemetry-filter default to 'info'

---

misc/python/materialize/mzcompose/__init__.py
src/adapter/src/coord.rs
src/adapter/src/coord/cluster_scheduling.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/cluster.rs
src/adapter/src/coord/timeline.rs
src/adapter/src/metrics.rs
src/catalog/src/memory/objects.rs
src/sql/src/catalog.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/sql/src/session/vars/value.rs
test/cluster/mzcompose.py
test/sqllogictest/materialized_views.slt
test/testdrive/materialized-view-refresh-options.td

This is the main PR of implementing the automated cluster scheduling for REFRESH MVs (https://github.com/MaterializeInc/materialize/issues/25712), i.e., automatically turning on clusters when the time comes for a refresh. (Earlier PRs: https://github.com/MaterializeInc/materialize/pull/25998, https://github.com/MaterializeInc/materialize/pull/26242.) 
I've tagged @ParkMyCar and @benesch, because I had some design discussions with both of you.
[Meeting notes](https://www.notion.so/materialize/Compute-meeting-on-automatic-cluster-scheduling-ce353b8af52e449d8784241c4a1c0585) where we sketched some aspects of the design.
I've put most of the implementation in a separate file: `src/adapter/src/coord/cluster_scheduling.rs` (rather than e.g., `message_handler.rs` or `coord.rs`); I hope that's …

REFRESH's automated cluster scheduling

---

misc/python/materialize/data_ingest/workload.py

As noticed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1712759442116639
-

data-ingest test: Print comparator that fails

---

doc/user/content/transform-data/troubleshooting.md

Add a new section "How can I see which queries were slow?" to the transform-data troubleshooting docs, which points users to the query history page in the console and mentions the `mz_recent_activity_log` catalog table.

Reference the query history UI in the transform data troubleshooting docs

---

src/compute-types/src/dataflows.rs
src/compute-types/src/plan/flat_plan.rs
test/cluster/mzcompose.py

When the optimizer produces a `DataflowDescription` it sometimes needs to allocate transient `GlobalId`s to make objects referenceable internally. The IDs it receives when doing so depend on which commands have previously been run against the Mz instance since its last restart, so they are not deterministic. Compute reconciliation that compares `DataflowDescription`s as-is may thus fail and unnecessarily recreate dataflows because the compared `DataflowDescription`s contain different internal transient IDs, even though they might be semantically equivalent.
This PR fixes the described defect by normalizing internal transient IDs before comparing `DataflowDescription`s during reconciliation.
Fixes #26155
- N/A

compute: reconcile dataflows with transient IDs

---

src/adapter/src/optimize/copy_to.rs
src/aws-util/src/s3.rs
src/aws-util/src/s3_uploader.rs
src/pgcopy/src/copy.rs
src/storage-operators/src/s3_oneshot_sink.rs
src/storage-types/src/sinks.proto
src/storage-types/src/sinks.rs
src/testdrive/src/action.rs
src/testdrive/src/action/postgres/execute.rs
src/testdrive/src/action/s3.rs
test/testdrive/copy-to-s3-minio.td

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/26403
I've left a TODO for implementing a manifest file -- this just implements the INCOMPLETE sentinel such that it's possible to know when the copy is done.
The diff is large since I refactored the s3 sink operator to extract most of the upload logic into a separate function (`handle_inputs_and_upload`) that returns a `Result` to allow use of `?` and simplify the error handling verbosity.
I also centralized the logic on how we create keys for the s3 objects we're uploading since it was otherwise spread around in a few places. I also renamed a few misleading fields related to S3 URIs and paths/object-keys.
-

storage/copy-to-s3: Implement a sentinel file to indicate whether copy is completed

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/catalog/src/builtin.rs
src/catalog/src/durable.rs
src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs
src/compute-client/src/controller.rs
src/controller/src/clusters.rs

This commit teaches the in-memory catalog how to listen to all cluster related updates. This includes clusters, cluster replicas, and introspection source indexes.

catalog: Listen to cluster updates

---

src/persist-client/src/cli/admin.rs
src/persist-client/src/internal/apply.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/internal/trace.rs

Primarily providing more-efficient iterators over batches, plus some other odds & ends.
Previously-unspecified refactoring. (I think most of these are valuable on their own, but efficiently iterating over spine batches looks like it will be useful for some upcoming changes.)
Unsolicited refactoring PR, so feel free to push back on whatever. In particular, I wasn't sure how far to go with migrating `map_batches`; all of the usages can be easily ported to a for loop, so I just picked the ones that either seemed simpler with iterator methods or got to save a little work.
-

[persist] Minor fixups

---

doc/user/content/sql/subscribe.md
src/sql/src/plan/statement/dml.rs
test/testdrive/subscribe-output.td

This PR fixes the description of a subscribe using envelope upsert with multiple keys. 
For example, consider the following scenario:
```
CREATE TABLE t1 (a int, b text, c uuid);
SUBSCRIBE TO t1 ENVELOPE UPSERT (KEY (c, a));
```
We pack the [keys into the returned `Row`](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/active_compute_sink.rs#L243-L246) in the order in which they're specified in the `SUBSCRIBE` statement, e.g. `[c, a]`. But the `describe_subscribe` function was creating the returned `RelationDesc` with the order that they're specified on the source, e.g. `[a, c]`.
Fixes a panic that would occur when sending a `Row` because we assumed the wrong `Datum` type.
Fixes https://github.com/MaterializeInc/cloud/issues/9139
- Fixes a panic related to `ENVELOPE …

adapter: Fix description of subscribe using envelope upsert with multiple keys

---

misc/python/materialize/buildkite.py
test/bounded-memory/mzcompose.py
test/cluster/mzcompose.py
test/feature-benchmark/mzcompose.py

Based on discussion in https://materializeinc.slack.com/archives/C057X0NG91B/p1712739384730909
Usage is then through command line:
```bash
$ curl --silent -H "Authorization: Bearer $BUILDKITE_TOKEN" "https://api.buildkite.com/v2/organizations/materialize/pipelines/test/builds/80456" | jq ".meta_data"
{
"buildkite:git:commit": "commit 9d6f79d657580573f6dc8a80f364112d98de868c\nabbrev-commit 9d6f79d657\nAuthor: Dennis Felsing <dennis@felsing.org>\n\n    ci: Upload metadata about shard lists",
"Shard for Cluster tests 1": "test-compute-controller-metrics, test-compute-reconciliation-reuse, test-concurrent-connections, test-github-23246, test-github-26215, test-incident-70, test-replica-metrics, test-replica-targeted-subscribe-abort, test-single-time-monotonicity-enforcers, test-smoke, …
```

ci: Upload metadata about shard lists

---

test/bounded-memory/mzcompose.py

This is based on a memory search conducted with https://github.com/MaterializeInc/materialize/pull/26312.
In order not to introduce (too much) flakiness, I changed values rather conservatively:
* I never underexceeded `4.5Gb` for `materialized_memory` and `3.5Gb` for `clusterd_memory` (though, instances exist, which pass with a `clusterd_memory` with as little as `0.2Gb`)
* I added about 20% margin where more memory was required (lower margin for very high values)
**Happy to discuss if there are any concerns or if we want to take a more aggressive approach.**
e40014e3d0 bounded memory: specify lower bound for minimal memory search
e9f039ee0e bounded memory: update memory specifications
1b0b77cf38 bounded memory: require explicit specification for each scenario …

bounded memory: update memory specs

---

.github/pull_request_template.md

trigger-ci now uses the referer to auto-fill the PR. Locally this seems to work for me on Firefox and Google
- 
[trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/) (<- Please try out if this works for you too)

github PR template: Add reference to trigger-ci

---

misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py

This addresses https://buildkite.com/materialize/nightly/builds/7344#018ec8aa-5406-4fdb-a4df-8b83b6e20d22.
Nightly: https://buildkite.com/materialize/nightly/builds/7363 ✅

postgres consistency: extend timezone ignores

---

misc/python/materialize/checks/all_checks/explain_catalog_item.py
misc/python/materialize/checks/mzcompose_actions.py

Have to set the current mz version after promoting Mz
-

platform-checks: Proper EXPLAIN fix

---

src/adapter/src/catalog.rs
src/adapter/src/coord/sequencer/cluster.rs
test/cloudtest/test_managed_cluster.py

Currently mz_system can only create cluster sizes in the allowed_cluster_sizes list. This change lets mz_system create any cluster size configured in the system, not just those allowed by envd. This should allow us to better test or deploy replicas which have not yet been allowed.
Currently it's impossible for mz_system to spin up cc sized replicas on system clusters for environments that do not have cc sizes in their allowed cluster sizes. This is a significant limitation to rolling out cc sizes on internal clusters. 
-

let mz_system create any configured cluster size

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
src/expr/src/scalar/func.rs
test/sqllogictest/string.slt

Fixes #26553
- Fix `translate` when used with multibyte chars.

expr: correctly support multibyte chars in translate

---

src/compute/src/sink/persist_sink.rs
src/ore/src/iter.rs
src/persist-client/src/internal/metrics.rs

This PR removes the `CorrectionBuffer` type from the compute `persist_sink` and instead makes `persist_sink` keep all pending updates in the `UpdateStash`. This makes it possible to continuously consolidate `desired` and `persist` updates as they arrive, rather than only doing so once a new batch is about to be emitted.
The hope is that this change will significantly reduce `persist_sink`'s hydration memory spike. For this very simple workload:
```sql
CREATE TABLE t (a int);
CREATE MATERIALIZED VIEW mv AS SELECT t1.a AS a, t2.a AS b FROM t t1, t t2;
INSERT INTO t SELECTgenerate_series(1, 5000);
```
... this PR reduces the hydration memory spike from 5.6 GiB to 3.1 GiB.
The compute `persist_sink` only performs consolidation of `desired` and …

compute: early consolidation in `persist_sink`

---

src/adapter/src/lib.rs
src/adapter/src/util.rs
src/environmentd/src/http/sql.rs
src/pgwire/src/protocol.rs

pgwire had runtime protection against mismatching desc and rows. Extend that to http and websocket. This would have protected against the panic in the linked issue. Adding a test for this results in panic without this patch, and an error output with it. Not adding the test because the underlying issue is getting fixed which will prevent the test from working.
See #26549
- n/a

environmentd: detect malformed rows

---

src/persist-client/src/internal/state.rs
src/persist-client/src/internal/state_serde.json
src/persist-client/src/internal/trace.rs

In service of #16607 - this makes it easier to visually inspect the state.
-

[persist] Add the new spine info to the serde representation

---

Cargo.lock
src/compute-types/src/dyncfgs.rs
src/dyncfg/Cargo.toml
src/dyncfg/src/dyncfg.proto
src/dyncfg/src/lib.rs
src/persist-client/src/stats.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/value.rs
src/storage-types/src/connections.rs
src/storage-types/src/dyncfgs.rs

These will be used in a forthcoming commit to support a particularly complex feature flag.
@danhhz I need a JSON-valued configuration flag to support https://github.com/MaterializeInc/cloud/issues/8316. Turned out to be a rabbit hole to allow `json!({})` as a default value, but it didn't end up being too deep, thankfully.
- n/a

dyncfg: support JSON-valued configuration variables

---

misc/python/materialize/checks/all_checks/pg_cdc.py

See https://materializeinc.slack.com/archives/C01LKF361MZ/p1712759792742669 for context
I'm not sure if this is the proper fix. But I couldn't find anything suspicious in services.log
-

platform-checks: Increase timeout for validation

---

test/canary-load/mzcompose.py

Seen in https://buildkite.com/materialize/qa-canary/builds/68#018ecf9d-7b83-49f0-9725-0a00c9840d38
-

canary-load test: Bump timeout

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml

I'm really not happy with this. Is there a better way to avoid https://github.com/MaterializeInc/materialize/issues/19097 without cutting out lots of tests? CC @aljoscha 
But this is failing in every Nightly run, and many Test pipeline runs.
-

ci: Retry testdrive tests

---

ci/nightly/pipeline.template.yml
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/settings.py

parallel-workload: Support ddl-only complexity

---

src/adapter/src/coord.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/timeline.rs
src/adapter/src/lib.rs
src/adapter/tests/timestamp_selection.rs

Preparatory work for https://github.com/MaterializeInc/materialize/issues/24845, where we
want to introduce more concurrency to the Coordinator and Controllers.
The code/comments/docs explain the motivation and how/why they are used.
The overarching motivation is that future work around introducing more
concurrency in the adapter/Coordinator will make this necessary, but it
also feels correct to make this distinction that has always been there
explicit in the code and interfaces. A previous refactoring was not
going far enough.
It's nice to see how the previous
acquire_read_holds/update_read_holds/release_read_holds were actually
used for disjoint purposes, we don't have to duplicate those methods
now.
Also, this moves initialize_read_holds inside the methods where it's
used because its …

 adapter: clearer distinction between TimelineReadHolds and ephemeral ReadHolds

---

ci/builder/requirements.txt
ci/nightly/pipeline.template.yml
misc/python/materialize/data_ingest/data_type.py
misc/python/materialize/data_ingest/query_error.py
misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/executor.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/worker.py
test/parallel-workload/mzcompose.py

To be able to catch #26549 and similar issues in the future. Works to reproduce: https://buildkite.com/materialize/nightly/builds/7326
```
+++ [worker_0] Query failed: FETCH 554 c WITH (timeout='6s'); {'S': 'ERROR', 'C': 'XX000', 'M': 'internal error: column 2 is not of expected type ColumnType { scalar_type: Bytes, nullable: false }: Map({"accept": String("*/*"), "accept-encoding": String("gzip, deflate"), "connection": String("keep-alive"), "content-length": String("100"), "host": String("localhost:6976"), "signature": String("\\"4QLnAMIyXDs3m0vIjhGfKWiVclfu300OPlsvSsdbMxvopvhWLfzr8V5H4yuJL6sF1T677tk9gfwkACjo8vZmtwmNlmlZCxDUN5Ie\\""), "user-agent": String("python-requests/2.28.1"), "x-event-type": String("\\"1oRuv0KljwxiOpvyMZXyxEWyqeQVvJwu8zhxDYxP5PqRoBlBBHR3cMVx6Fi8avEA4M5gAp8kXxPhtT5D …
```

parallel-workload: UUID types, ENVELOPE subscribes, Allow HTTP for most actions, Support websockets, Disable SQLsmith, faster startup always

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/transact.rs

This commit teaches the in-memory catalog how to generate builtin table
updates from changes to the durable catalog state.

catalog: Listen and generate builtin table update

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs
src/catalog/src/durable.rs
src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs

This commit teaches the in-memory catalog how to listen to storage
metadata updates.

catalog: Listen to storage metadata updates

---

src/storage-types/src/dyncfgs.rs
src/storage/src/render/upsert.rs
test/bounded-memory/mzcompose.py
test/testdrive/pr-24663-regression.td
test/testdrive/source-statistics-view.td
test/testdrive/source-statistics.td

Closes: https://github.com/MaterializeInc/materialize/issues/23998
This turned out to be a significant change, with several tradeoffs, so I will discuss the intrinsic complexity and decisions on tradeoffs here.
The core change is in the 4th commit. Fundamentally, solving this problem requires that _we are able to record batches of records in the upsert state backend before a frontier covering them has appeared_. This is a significant change to the `UpsertState` contract, and requires that we record an _order key_ alongside the data inside the upsert state. This order key allows us to ensure we correctly record that _final_ value in the output state.
This _order key_ is the `FromTime` of the data, that we were previously only using to order values in-memory before committing them to the …

storage: avoid buffering entire upsert snapshot in memory

---

src/sql/src/rbac.rs

Previously, RBAC would check that a users role was still valid (i.e. not concurrently dropped) before doing anything else. 4db9a3cf24b2dc7454a9eeafa9644ab2ca305441 moved this check so that it happened after collecting the role membership. As a result, it was possible to try and look up a role in the catalog before checking that the role exists. This would cause a panic instead of a user error.
This commit fixes the described issue by moving the valid role check back to being the first thing that RBAC does.
Fixes #26622

RBAC: Fix concurrent role drop check

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/optimize/copy_to.rs
src/aws-util/src/s3_uploader.rs
src/buf.yaml
src/mysql-util/src/desc.proto
src/pgwire/src/protocol.rs
src/sql-parser/tests/testdata/copy
src/sql/src/plan.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/rbac.rs
src/storage-operators/src/s3_oneshot_sink.rs
src/storage-operators/src/s3_oneshot_sink/parquet.rs
src/storage-operators/src/s3_oneshot_sink/pgcopy.rs
src/storage-types/src/sinks.proto
src/storage-types/src/sinks.rs
test/testdrive/copy-to-s3-minio.td

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/26491
This adds support for `COPY <> TO 's3://path/' WITH (FORMAT = parquet)` in sql parsing / planning.
It also splits out the logic for uploading CSV formatted files into a trait implementation to allow different logic for the arrow/parquet implementation, which will be fairly different since we need to translate rows into a columnar format.
This PR is mostly just preparation for the actual parquet format implementation - taking care of all the boilerplate, etc.
The diff looks large but it's mostly just moving code out of `s3_oneshot_sink.rs` into a submodule
All of this is currently behind a feature flag (`enable_copy_to_expr`) so will not be available to users
-

storage/copy-to-s3: parquet format option & upload implementation stub

---

src/compute/src/render/sinks.rs
src/compute/src/sink/copy_to_s3_oneshot.rs
src/compute/src/sink/persist_sink.rs
src/compute/src/sink/subscribe.rs
src/storage/src/render/sinks.rs
src/storage/src/sink/kafka.rs

This PR makes two minor changes to the `SinkRender` traits:
* Removes a redundant trait bound.
* Renames `render_continuous_sink` to just `render_sink`.
Just something I stumble over from time to time.
I have done my research to find out why the method was called `render_continuous_sink` in the first place:
Meanwhile we have the `copy_to_s3` sink which _is_ a one-shot sink and uses the same render method, so that reasoning doesn't apply anymore.
- N/A

compute,storage: cleanup `SinkRender` trait

---

src/compute/src/sink/copy_to_s3_oneshot.rs
src/storage-operators/src/s3_oneshot_sink.rs

Addresses feedback from @antiguru on some copy-to-s3 timely usage:
1. I originally addressed the timely ordering assumption this operator contains in https://github.com/MaterializeInc/materialize/pull/26340 but we decided that the performance cost of that PR was not desirable so it was closed.
The current PR instead notes the ordering assumption and adds an `assert` to detect if the ordering of rows received by the storage operator is unsorted, which would indicate a potential regression in the behavior. Fixes https://github.com/MaterializeInc/materialize/issues/25835
2. We are currently distributing errors across all workers such that some workers might proceed to start their uploads even if another worker receives an error in its error stream. This is undesirable since we end up …

storage/copy-to-s3: Rework error handling in copy-to-s3 operator, add assert for assumption about timely FIFO semantics

---

misc/python/materialize/feature_benchmark/benchmark.py
misc/python/materialize/mzcompose/test_result.py
test/feature-benchmark/mzcompose.py

I did not have the time to check the annotation on a real build but the generated junit xml file looked reasonable.
```
<testsuite disabled="0" errors="1" failures="0" name="feature-benchmark" skipped="0" tests="1" time="0">
<testcase name="GroupBy" classname="feature-benchmark">
<error type="error" message="New regression">NAME                                | TYPE      |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
GroupBy                             | wallclock |           0.682 |           0.680 |    !!YES!!    | 0.3 pct   more/slower
GroupBy                             | messages  |            None |            None |      no       | N/A
GroupBy …
```

ci: feature benchmark: annotate regressions

---

bin/cloud-push

Both envd and clusterd run on ARM in staging nowadays, so images pushed without this change will not be deployable in staging.
* This PR fixes a utility script.
- N/A

cloud-push: use aarch64 images

---

src/storage/src/source/postgres/replication.rs
src/storage/src/source/source_reader_pipeline.rs

This PR makes a slight modification to the capability management logic of the postgres source such that the capability that governs the minting of reclock bindings is advanced eagerly, before a transaction is ingested. This has the effect that the data of the transaction will not accumulate in the reclock operator and will instead be passed downstream, where the persist sink operator can stream it to S3 batches.
Fixes #26257
-

storage/pg: stream large transactions to persist

---

src/compute/src/sink.rs
src/compute/src/sink/correction.rs
src/compute/src/sink/persist_sink.rs

This PR moves the `UpdateStash` and its internals to a new `correction` module, to remove some noise from the `persist_sink` operator implementation code. It also renames `UpdateStash` to `Correction`, to make it clear that this is not a generic collection type but one purpose-built for `persist_sink`.
- N/A

compute: factor out `sink::correction` module

---

test/aws-localstack/copy-to-s3/copy-to-s3.td

Follow-up to https://github.com/MaterializeInc/materialize/pull/26495
Seen failing in https://buildkite.com/materialize/nightly/builds/7416
-

aws test: Adapt S3 error messages

---

.github/CODEOWNERS

codeowners: Fix typo

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs
src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/memory/objects.rs

This commit teaches the in-memory catalog how to listen to audit log
updates.

catalog: Listen to audit log updates

---

src/adapter/src/catalog/open.rs

provide replica.cluster_name instead of replica.name to builtin_cluster_sizes.get_size fn
-

fix bad arg in builtin cluster replica creation

---

test/upsert/autospill/03-rocksdb.td

Fixes https://github.com/MaterializeInc/materialize/issues/26636
@guswynn Does this make sense?
-

upsert test: Adapt test results to new reality

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/catalog/src/builtin.rs
src/sql/src/func.rs

Install builtin views in parallel by dependency order, greatly speeding envd startup.
- n/a

adapter: parse and optimize builtin views in parallel

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/memory/objects.rs

This commit teaches the in-memory catalog how to listen to storage
usage updates.

catalog: Listen to storage usage updates

---

test/upsert/autospill/03-rocksdb.td

storage: cleanup autospill test

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/executor.py

parallel-workload: On HTTP read timeout don't assume the action succeeded

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/timestamp_selection.rs
src/adapter/tests/timestamp_selection.rs

Preparatory work for https://github.com/MaterializeInc/materialize/issues/24845, where we want to introduce more concurrency to the Coordinator and Controllers.
Before, we were acquiring read holds and then looking at the since/implied capability of collections.
If/when the controller can advance its frontiers concurrently, the only safe/defensive thing we can do is look at our ReadHolds for determining a least valid read.
@MaterializeInc/testing You might want to know about this, look at it, just because it futzes with how we determine a read timestamp. In practice, this should not affect the determined timestamp, though, but it will make it so it continues working in a more concurrent future.
@teskje You might be interested!
-

adapter: use ReadHolds to determine least valid read

---

test/ssh-connection/validate-failures.td

Seen in https://buildkite.com/materialize/nightly/builds/7438
Caused by https://github.com/MaterializeInc/materialize/pull/26186
-

ssh-connection test: Adapt expected error msg

---

deny.toml

Deny any dependencies on `protobuf-src`, folks should depend on `protoc` via `mz-build-tools`.
- N/a

build: deny `protobuf-src`

---

misc/python/materialize/mzcompose/__init__.py
src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/explain/optimizer_trace.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
test/sqllogictest/explain/broken_statements.slt
test/tracing/mzcompose.py

Fixes a regression in #23124 
See the changed test for an example of how the tracing fast path would be broken until another change rebuilt the cache.
@aalexandrov I also took this time to completely remove the `BROKEN` references everywhere!
-

explain: fix tracing fast path regression

---

src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-types/Cargo.toml
src/persist-types/src/codec_impls.rs
src/persist-types/src/columnar.rs
src/persist-types/src/dyn_col.rs
src/persist-types/src/dyn_struct.rs
src/persist-types/src/part.rs
src/persist-types/src/stats.rs
src/repr/benches/row.rs
src/repr/src/row/encoding.rs
src/repr/src/stats.rs
src/storage-types/src/sources.rs

This PR refactored `PartDecoder` to have owned values, instead of references to the columns in a `Part`. This is required for efficiently working with structured columnar data.
Note: this PR originally included a change for `PartEncoder` as well, but it was split out into a separate PR.
A `Part` is our structured columnar representation of data. Currently to decode a `Part` we take references to the contained columns and downcast them from a `dyn Array` trait object, to a concrete column type. This downcasting is relatively expensive so we want to do it as infrequently as possible, ideally once per-`Part`.
The problem is when iterating over a `Part` (i.e. with `FetchedPart`) we own the underlying data, and the lexical scope for which we would be able to borrow is a single iteration. This …

columnar: Refactor `PartDecorder`

---

src/compute/src/arrangement/manager.rs
src/compute/src/compute_state.rs
src/compute/src/logging/compute.rs
src/compute/src/render.rs
src/compute/src/server.rs

This PR unifies compute logging of both output and input frontiers.
It first introduces a `CollectionLogging` type which emits per-collection `ComputeEvent`s and takes care of producing retraction events as necessary when frontiers update or collections are dropped.
It then moves input frontier logging to use the `CollectionLogging` type as well. For this, the purpose-built input frontier logging operators are replaced by probes, which are then queried between worker steps to receive updated frontiers to be logged.
Overall, this change has two benefits:
* It introduces more structure to the frontier logging, making it easier to reason about.
* It makes input frontiers available to the `ComputeState`, which is a precondition for [reporting them to the …

compute: unify frontier logging

---

misc/python/materialize/version_ancestor_overrides.py

feature-benchmark: Ignore new OptbenchTPCH regression on main

---

doc/user/content/free-trial-faqs.md
doc/user/content/get-started/quickstart.md
doc/user/content/sql/show-clusters.md

We seem to frequently point prospects to the free trial FAQ page, which is slightly outdated. Please double-check my math!
Also took the chance to patch a few related typos.

doc/user: patch free trial FAQs

---

src/adapter/src/coord.rs
src/adapter/src/coord/cluster_scheduling.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/timestamp_selection.rs
src/adapter/tests/timestamp_selection.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs

Preparatory work for https://github.com/MaterializeInc/materialize/issues/24845, where we
want to introduce more concurrency to the Coordinator and Controllers.
We restrict access to `CollectionState`, because we plan to move that
out of `StorageController`. But it's good in general to hide this
internal detail of the controller.
Access to `CollectionState` is replaced by more targeted methods, this
means there's now more methods but they return "smaller" things.
Additionally, the new methods return owned data rather than references
into controller state. This would not be necessary for how the
controller and calling code work now, but future refactoring will make
it so that state inside the controller is behind a shareable mutex, so
we start handing out owned data now in preparation for …

adapter,controller: restrict access to innards of storage controller

---

src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/mysql/replication/partitions.rs

In the same vein as #26267, we allow the progress upper to front run the data frontier so that the reclocking infrastructure can start working on reclocking a big transaction immediately instead of waiting for the transaction to first be emitted completely 
-

storage/mysql: stream mysql transactions to persist

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

https://github.com/MaterializeInc/materialize/issues/26323 can also happen with IN operator, see https://buildkite.com/materialize/nightly/builds/7464#018eebef-0763-4a28-9f82-1a2ee1e1e7aa
-

postgres-consistency test: Ignore REAL/DECIMAL difference in IN

---

doc/user/content/sql/create-source/webhook.md

See discussion here: https://materializeinc.slack.com/archives/CQM08AP9V/p1713297032865449. We have decided to GA the webhook source as-is. The feature flag has already been removed from the code, so we just needed to remove the public preview warning in the webhook source docs.
-

GA the webhook source - remove public preview warning in docs

---

doc/user/assets/sass/_layout.scss
doc/user/data/sql_funcs.yml
doc/user/layouts/shortcodes/fnlist.html

Our functions tables have gotten increasingly unreadable over the years due to support for functions with long signatures and description. Restore the tables' readability using the same trick as the PostgreSQL docs to display the function names and descriptions on separate lines of one column, rather than in two columns.
Before:
After
- n/a

doc/user: make fnlist tables readable

---

src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres/snapshot.rs

This PR makes it so pg and mysql sources don't start reading their replication streams before finishing with the snapshot. We have observed that doing so leads to a lot of updates being emitted into the dataflow that can't be fully forgotten until the frontier advances. If the snapshot is large that can be a long time and a lot of data.
-

storage/{pg,mysql}: serialize snapshot and replication phases

---

test/testdrive/catalog.td
test/testdrive/char-varchar-distinct.td
test/testdrive/char-varchar-joins.td
test/testdrive/char-varchar-multibyte.td
test/testdrive/connection-alter.td
test/testdrive/load-generator-key-value.td

It seems to always fail after this sink is dropped, see for example https://buildkite.com/materialize/test/builds/80870#018ef022-3eac-48d5-a5cc-96295b158dc6
-

testdrive: Alternative workaround for #19097

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml

Seen in https://buildkite.com/materialize/test/builds/80850#018eede2-01b4-4bd1-bf03-58f34860c426
-

ci: Bump cloudtest timeout (again)

---

doc/user/content/sql/alter-role.md

Role configuration parameters are already turned on for all customers and the feature flag has been removed. We just wrapped the final ergonomic improvements https://github.com/MaterializeInc/materialize/issues/26503 and https://github.com/MaterializeInc/materialize/issues/26228 so it's ready to GA, which just means removing the public preview warning in docs.
-

GA role configuration parameters - remove public preview warning in docs

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Release `dbt-materialize` v1.7.6. See `CHANGELOG.md` for an overview of the release.
Should wait for #26653 to merge, and for the Changelog post.

dbt-materialize: release v1.7.6

---

src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/copy
src/sql-pretty/src/doc.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement/dml.rs
test/testdrive/copy-to-s3-minio.td

@def- discovered in https://github.com/MaterializeInc/materialize/pull/26688 that `COPY <source> TO "s3://.....` would fail with an obscure error `ERROR: cannot insert into source '<source>'`.
This led me to discover that `COPY TO .. S3` was only working for select statements and tables but no other catalog item types (mat views, views, sources, etc).
It turns out we were using the `query::plan_copy_from` method to describe all copy statements that referenced an item directly (rather than a SELECT expression). This meant that `plan_copy_from` asserted that the item was a table, since we can't copy into other item types, which has no relevance to `copy-to`. 
This fix just pulls out the logic we need for generating copy statement-descriptions in `plan_copy_from` into a `plan_copy_item` …

storage/copy-to-s3: Support `COPY <item> TO ..` for all data-producing item types

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs

This reverts commit 2b73f7f0494c15a7ceda92d4aa122bf0f1027e8c.
See #26685 
- n/a

Revert "adapter: parse and optimize builtin views in parallel"
