MaterializeInc/materialize

src/sql/src/plan/typeconv.rs

Some typecasts are implemented with SQL. Previously we would silently fail to produce those if there was some programming error in the SQL (or the catalog was not properly instantiated). Instead loudly complain about the failure.
- n/a

sql: don't allow silent errors on func impls

---

src/storage/src/render/upsert.rs

Fixes https://github.com/MaterializeInc/materialize/issues/26655
#26655 is just about as close to dataloss you can get without actually causing dataloss. There are 2 cases to think about in `drain_staged_input` here. Both require a key shows up in a single batch to be processed under 2 different mz timestamps:
order key existing in upsert state: `key1: 10`
batch being processed in `drain_staged_input` (`(key, ts, order key)`):
`(key1, 1, 8), (key1, 2, 11)`
This is the case that currently panics!
existing order key: `key1: 10`
batch being processed:
`(key1, 1, 11), (key1, 2, 9)`
The above would cause dataloss as the value at ts 2 would remove the `11`-order-key value that should be written. This is not possible because currently, because of how kafka and reclocking work, if ts2 > ts1, then …

storage: fix edge-case panic in order-key upsert

---

src/catalog/src/builtin.rs
src/sql/src/func.rs
src/sql/src/plan/typeconv.rs

Clearly these aren't necessary, but seems good to follow convention. Maybe one day we can enforce this, and having them in place will help that.
- n/a

sql: specify schemas for more builtins

---

Cargo.toml
test/pgtest-mz/notice.pt

pgtest: ignore some flakey notice messages

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select
test/sqllogictest/interval.slt

To match PostgreSQL, treat `interval` as a non-reserved keyword. This allows it to be used as a column name without quoting.
This actually was very nearly already the case. When we implemented general typed string literals (77811560), we got this behavior "for free" for intervals, but failed to remove the *old* implementation for parsing interval values. So all we need to do in this commit is remove that old implementation, to allow the parsing of intervals to be entirely handled by the new general typed string literal parser, which correctly allows type names to *not* be treated as reserved keywords.
- n/a

sql-parser: correct parsing of `interval` keyword

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/26686
Seen in https://buildkite.com/materialize/nightly/builds/7486#018ef243-28ef-4504-bce4-31242ab12c1c
-

postgres-consistency test: Ignore IN without position too

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

bumps the version to v0.98.0
Database Release
- N/a

release: bump to version v0.98.0-dev

---

src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/src/fetch.rs
src/persist-client/src/read.rs
src/persist-client/src/stats.rs
src/persist-txn/src/txn_read.rs
src/persist-types/src/codec_impls.rs
src/persist-types/src/columnar.rs
src/persist-types/src/dyn_col.rs
src/persist-types/src/dyn_struct.rs
src/persist-types/src/lib.rs
src/persist-types/src/parquet.rs
src/persist-types/src/part.rs
src/persist-types/src/txn.rs
src/repr/benches/row.rs
src/repr/src/row/encoding.rs
src/repr/src/stats.rs
src/storage-types/benches/row.rs
src/storage-types/src/sources.rs
src/storage-types/src/stats.rs

This PR was split out from https://github.com/MaterializeInc/materialize/pull/26605
This refactors `PartEncoder` to take ownership of the columns it's encoding into, rather than just mutable references. More detail is provided in https://github.com/MaterializeInc/materialize/pull/26605 but the tl;dr is we only want to downcast `dyn Array`s once, and there isn't any lifetime that we can associate with the borrows to achieve this.
It also renames the existing `PartDecoder::decode(idx, &mut V)` method to `PartDecoder::decode_into(...)` and adds a new `PartDecoder::decode(idx) -> V` method. The goal of `decode_into(...)` is it allows you to re-use allocations where possible, but that isn't currently applicable when decoding from our structured columnar data. When decoding with `Codec` we go …

columnar: Refactor `PartEncoder`, add `decode_into(...)` to `PartDecoder`

---

Cargo.lock
clippy.toml
misc/cargo-vet/audits.toml
src/compute/src/extensions/arrange.rs
src/compute/src/extensions/reduce.rs
src/compute/src/logging.rs
src/compute/src/logging/compute.rs
src/compute/src/logging/differential.rs
src/compute/src/logging/timely.rs
src/compute/src/render.rs
src/compute/src/render/context.rs
src/compute/src/render/flat_map.rs
src/compute/src/render/join/mz_join_core.rs
src/compute/src/render/reduce.rs
src/compute/src/render/threshold.rs
src/compute/src/render/top_k.rs
src/persist-txn/src/operator.rs
src/storage-operators/src/persist_source.rs
src/storage/src/render/upsert.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/source_reader_pipeline.rs
src/timely-util/src/buffer.rs
src/timely-util/src/builder_async.rs
src/timely-util/src/capture.rs
src/timely-util/src/event.rs
src/timely-util/src/operator.rs
src/timely-util/src/pact.rs
src/timely-util/src/replay.rs

Update to latest timely and differential versions. The changes reflect upstream changes, but no new functionality. There are two main classes of changes:
* We define more timely operators in terms of containers instead of elements. This causes several changes where previously we had a `D` to become a `Vec<D>`. In the future, this opens the possibility to supply a different container type.
* The arrangement APIs in differential have streamlined trait bounds, which we need to reflect in Materialize. Part of this is that `MzArrange` cannot call the `Arrange` implementation for `Collection`, but instead calls the freestanding function that sits underneath the `Arrange` trait.
-

Update to latest timely and differential

---

src/persist-client/src/cfg.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/iter.rs
src/persist-client/src/read.rs

In the distant past, we wrote some >1-length runs that aren't actually consolidated: due to bugs or to ordering changes. This is annoying because the Consolidator requires its inputs to be consolidated to produce consolidated output. So: we have code that will re-sort parts that it discovers were written by old versions of Materialize.
However, even if all parts are consolidated, runs might not be! (Oops!) So it's safest to treat runs written using these old versions as though they were a bunch of single-part runs instead.
Known bug: #26170 
This assert has only fired once ever in production, and we didn't have enough debugging info enabled at the time to know for sure that this is the exact issue we hit.
I started work on a unit test for this, but it is tedious to write because it …

[persist] Split up runs that might not truly be consolidated

---

src/adapter/src/catalog/state.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/sql/src/plan.rs

The planning_id field was never read, so can be removed.
`Some(PlanContext::zero())` is the same as `None` during startup, so simplify one calling site to use None instead.
- n/a

adapter: remove PlanContext usage and fields

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_permission_validation.sql

For whatever reason, `IS FALSE` breaks autorouting to mz_introspection. Instead of digging deeper, we remove this clause and negate the result in jinja.
-

dbt-materialize: ensure superuser check is autoroute-able

---

src/persist-client/src/internal/metrics.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/internal/trace.rs

For #16607, it would be useful to know exactly how "compact" a particular spine is.
-

[persist] Add some metrics that track the current state of a spine

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Patch release to fix blue/green deployment workflows, which hits #26738 in environments that dropped the pre-installed default cluster.

dbt-materialize: release v1.7.7

---

src/arrow-util/Cargo.toml

Seen in https://buildkite.com/materialize/nightly/builds/7516#018ef8b5-8b1e-4fd8-9096-86b5089ec3da
-

cargo: Ignore mz-arrow-util workspace hack unused dependency

---

ci/builder/requirements.txt
ci/nightly/pipeline.template.yml
test/copy-to-s3/copy-to-s3-minio.td
test/copy-to-s3/mzcompose
test/copy-to-s3/mzcompose.py
test/copy-to-s3/setup.td
test/copy-to-s3/tpch10gb.td
test/copy-to-s3/tpch10mb.td
test/copy-to-s3/tpch1gb.td

This is now in a good state, just blocked until the 2 PRs it depends on merge.
Edit: Now good to go: Nightly is green with it: https://buildkite.com/materialize/nightly/builds/7517
-

Copy-to-S3 TPCH testing with CSV and Parquet 

---

src/orchestrator-kubernetes/src/lib.rs

We see frequently that a cluster's disk capacity is greater than its limit. This is odd, but not usually a cause for concern. The impact is that we may display that the disk is 100% full before the disk is actually 100% full. As long as the delta is small, the discrepency is basically unnoticeable.
So, downgrade the warning! log to an info! log, and also indicate the expected impact in the log message.
- n/a

orchestrator-kubernetes: downgrade disk capacity warning

---

ci/nightly/pipeline.template.yml
src/sql/src/plan/lowering/variadic_left.rs
test/rqg/Dockerfile
test/rqg/datasets/star_schema.sql
test/rqg/grammars/left_join_stacks.yy
test/rqg/mzcompose.py
test/sqllogictest/github-26707.slt

This is a fix for #26707 that works by further restricting the set of supported `ON` predicates. In particular, we skip variadic left join lowering for predicates of the form `lhs.x  = rhs.z AND lhs.y = rhs.z` which imply `x = y`.
Fixes #26707.
The fix is in the following commit
* sql: prevent `variadic_left` from pushing incorrect lhs filters
The first commit adds some more comments to `variadic_left.rs`, and the remaining commits add `*.slt` and `*.rqg` tests (those have been reviewed by @def- already).
To validate a proposed fix, run
```bash
RUST_BACKTRACE=full bin/sqllogictest -- test/sqllogictest/github-26707.slt
```
and
```bash
bin/mzcompose --find rqg run default left-join-stacks --queries 1000 --duration 3600
```
-

sql: restrict variadic left join lowering #26707

---

test/rqg/datasets/star_schema.sql
test/rqg/grammars/left_join_stacks.yy

- Add a `WHERE` clause to the `query` rule in `left_join_stacks.yy`.
- Tweak the `star_schema.sql` sample data so filtered rows have more non-NULL results.
Something that I was planning to add to #26709, but I merged the PR before that.
I tested with 1000 queries and inspected the (still identical) results sets to ensure that we don't get a lot of empty rows.
-

rqg: evolve `left-join-stacks` workload grammar (v3)

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/timestamp_selection.rs

Previous refactorings removed the need for acquiring read holds at a specific time or with a guarantee of acquiring a "precise" read hold. We can now remove this recently-introduced change again.
All remaining usage of the method has `time = MIN` and `precise = false`.
-

adapter: simplify acquire_read_holds, remove time/precise arguments

---

src/adapter/src/coord/sequencer.rs

This PR adds logging for queries that explicitly select the `mz_introspection` cluster. This is in preparation of renaming said cluster, to gauge how much of a breaking change doing so would be.
[Slack thread.](https://materializeinc.slack.com/archives/C063H5S7NKE/p1713368560676129)
Preparation for #26731 
This seems to work as intended (skips system users, works with both `SET cluster` and connection string options), but there might be a better place to put the logging.
The log message is tagged with a `github_26731` field so it can be disabled if it turns out too noisy with this log filter:
```
[{github_26731}]=error,info
```
- N/A

adapter: log manual uses of mz_introspection

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/mzcompose.py
misc/dbt-materialize/tests/adapter/test_deploy.py

In no particular order:
* `internal_copy_schema_default_privs` was not escaping object names
in its `ALTER DEFAULT PRIVILEGES` query.
* The same query was missing a space after the role name (in the case
that the privilege was granted to a specific role, rather than all
roles).
* `internal_copy_schema_default_privs` was not accounting for the
return value of `run_query` to be a row containing a single column.
(It was expecting the column directly.)
* `internal_copy_cluster_grants` was determining what grants to revoke
by looking at the grants on the `from` cluster when it needs to look
at the `to` cluster.
* `deploy_init` was invoking `internal_copy_cluster_grants` with
variables referencing schemas rather than clusters (likely due to a
copy/paste error).
* `TestApplyGrantsAndPrivileges` …

 dbt-materialize: correct several issues with permission copying

---

src/controller/src/lib.rs
src/storage-controller/src/lib.rs

Changes
`T: Into<mz_repr::Timestamp>`
to
`for<'a> T: Into<Datum<'a>>`
This is a tighter bound, but it still works for how this bound is currently used as well as for what I want to use it for (all uses are just creating Datums for putting timestamps into introspection tables). This change would fix my biggest issue with these trait bounds, which is that `T: Into<mz_repr::Timestamp>` makes the whole generic effort almost meaningless, because anyone can just make a `mz_repr::Timestamp` from `T` at any moment. If we make this change, I won't feel so bad about adding this trait bound to the Compute Controller.
* This PR refactors existing code in preparation for adding this trait bound to the Compute Controller. See discussion [here](https://materializeinc.slack.com/archives/C02PPB50ZHS/p17137 …

Change the Controller timestamp bounds to allow only Datum conversion

---

doc/user/content/ingest-data/mysql/amazon-rds.md

Chuck and I ran through the RDS MySQL setup. Updated the documentation as needed. [Here's the slack thread for reference.](https://materializeinc.slack.com/archives/C04LQV4KUR4/p1710795795051679)
Updated the parameter table to include the AWS Console column as 2 of the fields are different to make the call out more explicit.
`binlog retention hours` requires a MySQL Database connection and SQL to modify the values. Made this its own step.
Moved the parameter table to be below Step 3 as multiple testers blew past the first 2 required steps and jumped to step 3 without realizing.
Added a validation step with SQL to be ran on the MySQL database.

RDS Mysql docs update

---

src/expr/src/scalar/func.rs

Should address: https://github.com/MaterializeInc/cloud/issues/9251
In particular, if we can assume that these functions will never raise errors, then the abstract interpreter can reason more precisely about whether a filter expression might throw. (This is important since we always need to fetch parts with rows that may error during evaluation.)
While I was here, I tagged a number of other functions as infallible. I chose a subset that were both:
- structurally unable to return errors in the code: `eval` was implemented as `Ok(impl_fn(...))`.
- "clearly" infallible: there were easy-to-explain reasons why those functions _ought_ to be infallible.
I haven't attempted to investigate literally every function, so many functions that never throw in practice will still return `true` here.
-

[expr] Tag some binary / variadic functions as infallible

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/replica.rs
src/compute-client/src/controller/sequential_hydration.rs
src/compute-client/src/service.rs
src/controller/src/clusters.rs
src/controller/src/lib.rs

1. commit:
- Encapsulates trait bounds needed by the Compute Controller in a new composite trait `ComputeControllerTimestamp` (as suggested by @antiguru and @aalexandrov). This makes life easier if we ever need to add or remove trait bounds in the Compute Controller, because we'd need to do it at only one place.
- Note that I also removed `: Lattice` from a bunch of places, because `Lattice` is included through `TimestampManipulation`.
- Note that I changed the trait bounds also in `service.rs`, but those changes wouldn't be strictly needed.
- Removes a few `timely::progress::Timestamp` imports, to make it more explicit which `Timestamp` are we referring to.
- Makes `TimestampManipulation` and `Into<Datum>` uniformly accessible throughout the Compute Controller by including them in …

Reorganize controller timestamp trait bounds

---

misc/python/materialize/mzcompose/__init__.py
src/repr/src/optimize.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
src/transform/src/lib.rs

Remove the `enable_equivalence_propagation` feature flag from the optimizer and SQL-level integrations (`EXPLAIN`, `CREATE CLUSTER`).
Removes the feature flag introduced for the rollout of #24155.
Should be easy to review, as this is just removing code.
-

sql,optimizer: remove `enable_equivalence_propagation` feature flag

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/sequential_hydration.rs
src/compute-client/src/metrics.rs
src/compute-client/src/protocol/command.rs
src/compute-client/src/protocol/response.proto
src/compute-client/src/protocol/response.rs
src/compute-client/src/service.rs
src/compute/src/compute_state.rs
src/compute/src/server.rs
src/persist-client/src/operators/shard_source.rs
test/cluster/mzcompose.py

This PR renames the `FrontierUpper` response to `Frontiers` and adds to is a new `read_capability` field that reports for each compute collection the least time that the replica still needs to read from the collection inputs. Replicas emit read capability updates based on dataflow input frontiers they observe through the existing probes. The controller then uses this new information to maintain the per-replica read holds. Doing so fixes a bug where the controller would release read holds too early because they were based on the reported write frontiers, which can jump into the future for `REFRESH` materialized views.
This is an alternative version of https://github.com/MaterializeInc/materialize/pull/26594, which introduces a new `ReadCapability` response instead. The advantages of having …

compute: read capability reporting to fix per-replica read holds

---

src/adapter/src/catalog/transact.rs
src/catalog/src/durable/transaction.rs
src/ore/src/vec.rs

This commit adds sub-operations to catalog transactions. This allows callers to logically group operations within a catalog transaction. This feature will be useful when the catalog is structured to listen to durable changes, because it will allow the catalog to extract durable changes for a single logical operation and apply just those changes to it's in-memory state.
All of the interesting changes are in `TableTransaction` the rest is mostly plumbing.

catalog: Add sub-operations to transactions

---

src/adapter/src/catalog/state.rs

User compaction windows come from the catalog SQL. This comment was referring to the system compaction window for retain metrics relations which we do not want here.
- n/a

adapter: remove outdated comment

---

src/adapter-types/src/compaction.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/error.rs
test/sqllogictest/retain_history.slt

When creating or altering the retain history of an index, check for an invariant that downstream indexes have a retain history at least that of any upstream index.
- n/a

adapter: cascading indexes must share retain history

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/open.rs
src/sql/src/plan/error.rs
src/sql/src/plan/typeconv.rs

Use a slower but more correct method to determine dependencies by sniffing out errors.
This reverts commit a1a2ad4e7b5e56f7a8f3055fdba5f894a594e460.
Fixes #26685
- n/a

adapter: parse and optimize builtin views in parallel v2

---

src/compute/src/sink/correction.rs

This PR fixes the reporting of `Correction` size metrics. Previously we'd forget updating the reported sizes when the `Correction` data was consolidated, which was an oversight.
The reported `Correction` size metrics are wrong because they don't take into account consolidation that happens when collection updates for a given time range.
- N/A

compute: persist_sink: fix size metrics reporting

---

src/compute-types/src/dyncfgs.rs
src/compute/src/compute_state.rs
src/compute/src/render.rs
src/compute/src/render/context.rs

This PR removes two feature flags that were introduced to reduce the risk of rolling out their respective features, which have been successfully rolled out in the meantime:
* `enable_compute_operator_hydration_status_logging`
* `enable_compute_controller_dataflow_scheduling`
Also adjusts the default value of `compute_hydration_concurrency` to the same value that's configured in all cloud environments.
* This PR cleans up feature flags.
- N/A

compute: remove unneeded feature flags

---

src/catalog/src/durable/persist.rs
src/compute/src/compute_state.rs
src/dyncfg/src/lib.rs
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/benches/porcelain.rs
src/persist-client/src/cfg.rs
src/persist-client/src/critical.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/lib.rs
src/persist-client/src/operators/shard_source.rs
src/persist-client/src/read.rs
src/persist-txn/src/lib.rs
src/persist-txn/src/txn_cache.rs
src/persist-txn/src/txn_read.rs
src/storage-controller/src/lib.rs
src/storage/src/source/reclock.rs
src/storage/src/storage_state.rs
src/storage/src/storage_state/async_storage_worker.rs

- Allow read-lease-creators to opt in to having their initial since set to the least critical handle, instead of the shards overall since.
- Opt the txns code into this feature, behind a default-on flag.
Previously-unreported bug. (While the general risk was known, this new instance of it is I think new?)
Briefly: every new source that reads a txns shard subscribes with an as-of of the global since. Since we throttle since downgrades, this will prevent the global since from advancing for a few minutes. If the rate at which we create new txn-backed dataflows is faster than the rate at which these downgrades go through, we can hold back the since indefinitely.
A way around is to have the initial since of the handle based on the shard's critical handle. Since that doesn't depend on the since …

[persist/txn] Use the "critical" since when creating new read leases in the txns code

---

src/postgres-util/src/lib.rs
src/postgres-util/src/tunnel.rs

Postgres connections over AWS PrivateLink were broken by https://github.com/MaterializeInc/materialize/pull/26186/ which introduced a runtime error because `tokio::net::lookup_host` here requires a port provided:
https://github.com/MaterializeInc/materialize/blob/80e3fe9561c8d6849b16cbb7bfa4a6305a278916/src/postgres-util/src/tunnel.rs#L305-L306
We unfortunately did not have a PrivateLink + Postgres Source test in CI. This work is tracked here https://github.com/MaterializeInc/cloud/issues/8238 and will be prioritized for implementation during the next 2 weeks (cc @jubrad @pH14 @benesch )
I [reproduced](https://materializeinc.sentry.io/issues/5255681995/?environment=staging&project=6780145&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0) this error on my staging …

storage: Fix for runtime invalid-socket-address error

---

src/expr/src/interpret.rs
test/sqllogictest/explain-pushdown.slt

WIP, to see what CI has to say. But: why _was_ it fallible before. The worst you can get is a `NULL`, is Parker and mine's naive (and likely wrong!) understanding.
The logging is not meant to stay in, this PR is not meant to be merged like this in general.
cc @ParkMyCar 
-

persist: in range-based stats interpretation, make jsonb_get_string infallible

---

test/testdrive/copy-to-s3-minio.td

We're seeing an intermittent test failure on main because this PR #26740 sped up the upload process so much that we now sometimes don't detect the `INCOMPLETE` sentinel file fast enough https://buildkite.com/materialize/test/builds/81180#_:
```
copy-to-s3-minio.td:166:1: error: Did not find matching files in bucket copytos3 prefix test/5
```
This just increases the test copy by an order of magnitude such that there should be enough time for the test to see the sentinel file during the copy
-

storage/copy-to-s3: Make test copy more data due to upload speedup

---

src/adapter/src/coord.rs

Decrease the threshold for "coordinator is stuck" message from 60 seconds to 30 seconds
The Coordinator has gotten faster, so we should tighten our bounds on what we report on
- N/a

coord: Tighten bounds on "slow coordinator" message

---

Cargo.lock
src/arrow-util/Cargo.toml
src/arrow-util/src/builder.rs
test/testdrive/copy-to-s3-minio.td

Part of the work towards private-preview for copy-to-s3: https://github.com/MaterializeInc/materialize/issues/7256
See the code-comments for an explanation of handling related to numeric values that that cannot fit in the arrow/parquet representation.
-

storage/copy-to-s3: Implement parquet decimal/numeric, jsonb, uuid types

---

ci/release-qualification/pipeline.template.yml
misc/python/materialize/zippy/source_actions.py
src/rocksdb/src/lib.rs
src/rocksdb/tests/basic.rs
src/sql/src/plan/statement/ddl.rs
src/storage-types/src/dyncfgs.rs
src/storage/src/upsert.rs
src/storage/src/upsert/autospill.rs
test/testdrive/kafka-avro-sinks-defaults.td
test/upsert/kafka-upsert-debezium-sources.td

Possibly resolves #19999 and #25417
The past way of doing this ALLOWED us to skip errors on destruction of the db, and then panic on creation of the db; this is not only less flaky (we hope, at least in my local testing it isnt as flaky), but also safer, with us never trying to build a db before successfully deleting it.
-

storage: retry cleaning up rocksdb db's on startup

---

misc/python/materialize/parallel_workload/action.py

This addresses failures in the parallel workload tests like, for example, in https://buildkite.com/materialize/nightly/builds/7572#018f29a2-0c37-43c4-887e-d711b629f08a.
Nightly: https://buildkite.com/materialize/nightly/builds/7573

tests: parallel workload: add ignore

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/state.rs
src/adapter/src/coord.rs
src/adapter/src/coord/read_policy.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/catalog/src/memory/objects.rs
test/sqllogictest/retain_history.slt

If a subsource has not set its retain history but the parent source has, use the parent source's retain history.
Fixes #26650
- n/a

adapter: subsource retain history propagation

---

misc/python/materialize/version_ancestor_overrides.py

I think we should keep old ancestor overrides. This fixes https://github.com/MaterializeInc/materialize/pull/26674.

feature benchmark: restore ancestor-override for older version

---

src/persist-txn/src/txn_cache.rs
src/persist-txn/src/txn_read.rs

Using the example history I came up with to try to exercise all the interesting edge cases.
Touches https://github.com/MaterializeInc/materialize/issues/22173
Touches https://github.com/MaterializeInc/materialize/issues/22801
I'd love to go over the answers in this test with the two of you before trying to fix up the impl to pass it :D. (I think all the disagreements with the current impl are places where we're being too conservative, plus "eager" doesn't use this.)
-

persist-txn: rewrite data_snapshot and data_listen_next unit tests

---

src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-client/src/batch.rs
src/persist-client/src/internal/state.rs
src/persist-txn/src/lib.rs
src/persist-txn/src/txn_cache.rs
src/persist-txn/src/txn_write.rs
src/persist-txn/src/txns.rs
src/storage-controller/src/lib.rs

This is because we need to be able to verify that the contained data,
after the rewrite forward operation, still respects the new upper. It
turns out that, given the metadata persist currently collects during
batch collection, this is possible for totally ordered times, but it's
known to be _not possible_ for partially ordered times. It is believed
that we could fix this by collecting different metadata in batch
creation (e.g. the join of or an antichain of the original contained
timestamps), but the experience of this bug has shaken our confidence in
our own abilities to reason about partially ordered times and anyway all
the initial uses have totally ordered times.
Closes #26384
I've included a revert of the revert of the persist-txn usage of this …

persist: require a TotalOrder Timestamp for rewrite_ts

---

src/transform/src/lib.rs

Add a convenience macro that should allow us to minimize the code diff when gating a `Transform` inside a `transforms` vector behind a feature flag.
The macro is added with a `#[allow(unused_macros)]` annotation because it won't be used all the time. See the macro documentation for details.
Here is an example diff for gating `EquivalencePropagation` behind a feature flag
```diff
diff --git a/src/transform/src/lib.rs b/src/transform/src/lib.rs
index 767a20acbe..bcf9bb88d5 100644
--- a/src/transform/src/lib.rs
+++ b/src/transform/src/lib.rs
@@ -526,10 +526,10 @@ impl Optimizer {
Box::new(Fixpoint {
name: "fixpoint01",
limit: 100,
-                transforms: vec![
+                transforms: transforms![
// Predicate pushdown sets …
```

transform: add `transforms!` macro

---

ci/builder/requirements.txt

This PR bumps the version of `confluent-kafka` that we use to `2.3.0`, which fixes the build. Currently `bin/environmentd` can fail on a fresh checkout because we fail to build the wheel for the `confluent-kafka` package. Bumping to `2.3.0` allows us to rely on the pre-built wheel.
Fixes the build
- N/a

build: Bump version of confluent-kafka

---

misc/python/materialize/mzcompose/__init__.py

These were complaining on startup about not being present. They no longer exist in envd.
- n/a

misc: remove vars that have been removed

---

src/catalog/src/builtin.rs
test/sqllogictest/cluster.slt
test/sqllogictest/mz_introspection_index_accounting.slt
test/sqllogictest/oid.slt
test/sqllogictest/web-console.slt
test/testdrive/indexes.td
test/testdrive/mz-arrangement-sharing.td

This was missed when defining it.
- n/a

catalog: install kafka sources index

---

ci/nightly/pipeline.template.yml
test/cloudtest/test_storage_shared_fate.py

* Move long running cloudtest to nightly.
* <s>Reduce number of shards for cloudtests in tests pipeline since the setup takes most of their time.</s>
Duration of moved cloudtests (the first testcase includes the setup):
```
<testcase classname="test.cloudtest.test_storage_shared_fate" name="test_kill_all_storage_clusterds" time="884.014"/>
<testcase classname="test.cloudtest.test_storage_shared_fate" name="test_kill_one_storage_clusterd" time="99.838"/>
<testcase classname="test.cloudtest.test_storage_shared_fate" name="test_kill_first_storage_clusterd" time="97.356"/>
<testcase classname="test.cloudtest.test_storage_shared_fate" name="test_kill_all_but_one_storage_clusterd" time="107.586"/>
<testcase classname="test.cloudtest.test_storage_shared_fate" …
```

ci: cloudtests execution

---

src/adapter/src/coord/sequencer/inner.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs

There were some unnecessary and noisy changes to the storage controller I wanted to make during the fix for subsource dependency inversion. Now that it's landed, we can tidy up the interface a bit.
- This PR adds a known-desirable feature. Closes #26767
- This PR refactors existing code.
- The `alter_ingestion_source_desc` methods took collections but were only ever called with single elements.
- The API to alter a sink's connection used a different verb than I think it should.
- Review commit by commit
- Reviewing without whitespace is probably easier
-

storage: refactor storage controller API for ALTER SOURCE, ALTER CONNECTION

---

src/adapter/src/coord.rs
src/sql/src/session/vars/definitions.rs

We decided to move to caring about individual slow messages because we largely have control over how long they take to execute. We want to have an SLO/SLI around these. Decide on 30s as the initial starting goal and send to entry when they occur.
Demote the busy log to a warning. We care less about this because many messages is workload dependent and thus can vary a lot by user. We initially will have a lower importance to this metric until the slow individual messages metric is improved.
Fixes #26861
- n/a

adapter: error for slow coord messages

---

misc/python/materialize/mzcompose/__init__.py

This reverts https://github.com/MaterializeInc/materialize/pull/26863.
I fear that we cannot just remove this variables. The reason for that is that some tests start materialize in an older version where they are required. An example are upgrade checks, which are failing now: https://buildkite.com/materialize/nightly/builds/7612#018f3915-29d2-47bb-b5cb-a2c3e2062687
While we could specify these variables for the upgrade checks, there are numerous other steps which start up older versions (e.g., feature benchmark, scalability framework) and may fail on other removed variables.
@maddyblue: Can you point me to the warning you got? Then, I can try to find other ways to suppress it.

Revert "misc: remove vars that have been removed"

---

Cargo.lock
src/persist-client/src/batch.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/lib.rs
src/persist-types/Cargo.toml
src/persist-types/src/codec_impls.rs

Given that we've been talking about persist's handling of partial orders recently, seems like a reasonable thing to have around for tests and such.
All credit to Petros for the idea and impl.
https://github.com/petrosagg/materialize/commit/0145c428f59b4888b5370c531e256458310dfc70
-

persist: impl Codec64 for Product<u32, u32>

---

ci/nightly/pipeline.template.yml

[Timed out yesterday](https://buildkite.com/materialize/nightly/builds/7616#018f3a5c-3787-437d-9463-1a6fa3792dbc) once, average duration is probably close to 30 minutes.

ci: slow cloudtests: increase timeout

---

ci/nightly/pipeline.template.yml

Use a larger machine to avoid OOMs.

ci: testdrive 4 replicas: use larger machine

---

misc/python/materialize/data_ingest/executor.py
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/optimize/dataflows.rs
src/catalog/src/memory/objects.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/create
src/sql-parser/tests/testdata/ddl
src/sql/src/catalog.rs
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/show.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/mysql.rs
src/storage-types/src/sources.rs
src/storage-types/src/sources/mysql.rs
test/mysql-cdc/subsource-resolution-duplicates.td

Fixes #26764, #26769, #26772, #26768
The code touched is very disparate, probably go commit-by-commit and look for the crates that interest you.
-

sql + storage: cleanup subsource dependency inversion code

---

src/adapter/benches/catalog.rs
src/repr/tests/strconv.rs

These keep popping up in my editor.
-

tests: fix deprecation warnings and unused imports

---

test/testdrive/kafka-sink-headers.td

Without this, nightly testdrive tests that run on clusters with more
than one replica are failing.
It's the fix for
```
kafka-sink-headers.td:61:1: error: executing query failed: db error: ERROR: cannot create sink in cluster with more than one replica: ERROR: cannot create sink in cluster with more than one replica
```
-

tests: fix kafka-sink-headers.td by always using a single-replica cluster

---

src/adapter/src/coord/read_policy.rs
src/adapter/tests/timestamp_selection.rs
src/compute-client/src/controller/instance.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
src/storage-types/src/lib.rs
src/storage-types/src/read_holds.rs

Preparatory work for https://github.com/MaterializeInc/materialize/issues/24845, where we want to introduce more concurrency
to the Coordinator and Controllers.
Before, adapter would track outstanding `ReadHolds` in its own state and
continually update the `ReadPolicy` of storage collections based on a base
policy and outstanding read holds.
Now, we go directly to STORAGE for acquiring ephemeral `ReadHolds`. Note
that the adapter still keeps `TimelineReadHolds` for collections, which
control the `ReadPolicy` that we continually update. This is so that
timeline-dependent collections remain readable at the oracle read
timestamp even when there are no outstanding other (ephemeral) read
holds.
This leaves the COMPUTE part of `ReadHolds` untouched.
-

adapter: use STORAGE ReadHold instead of custom hold tracking in adapter

---

ci/builder/requirements.txt
misc/python/materialize/cli/scratch/create.py

* This PR brings some dependencies up-to-date.
I noticed that a few of the Python dependencies are a little bit outdated. In particular pydantic is still on the old major version ([`1.10.4` from 2022](https://pypi.org/project/pydantic/#history)). This PR updates it to the latest version, including tiny adaptations for the major version bump.
The currently pinned version of `typing_extensions==4.7.0` is blacklisted by `pydantic-core` due to an issue in that version. Thus, I had to bump its version as well to unblock the pydantic update. Keeping `typing_extensions` up-to-date is typically a good idea anyway.
-

python: update `pydantic` and `typing_extensions`

---

test/cloudtest/node_recovery/test_k8s_node_recovery.py

This fixes the error reporting observed in https://buildkite.com/materialize/nightly/builds/7638#annotation-018f4361-d5af-4a9e-a2c8-66a6b6267182-error.

tests: node recovery: fix

---

ci/nightly/pipeline.template.yml

rqg-left-join-stacks still failed with the slightly increased timeout. Adjusting it to the same value as most other RQG steps use.

ci: align timeout for rqg-left-join-stacks

---

misc/python/materialize/buildkite_insights/step_analysis/README.md
misc/python/materialize/buildkite_insights/step_analysis/analysis.py
misc/python/materialize/buildkite_insights/steps/build_step.py

Introducing the parameter `--include-commit-hash`, which is helpful when bisecting.
```
nrainer@mz-nrainer mz-repo % bin/buildkite-step-insights nightly --build-step-key persist-txn-fencing --include-commit-hash
Using existing data: /Users/nrainer/Workspaces/mz-repo/temp/builds-nightly-params-3a3630f2.json
Loaded data from /Users/nrainer/Workspaces/mz-repo/temp/builds-nightly-params-3a3630f2.json
persist-txn-fencing, #7639, 2024-05-05 11:33:54 +0000, 42.13 min, https://buildkite.com/materialize/nightly/builds/7639, 83b7a87ac5ab480f3d1fde4b5d867e66e2c97b4a, SUCCESS
persist-txn-fencing, #7638, 2024-05-04 11:33:56 +0000, 121.14 min, https://buildkite.com/materialize/nightly/builds/7638, eec4e9ac8ef68ffce6c8fafa10f18e9d3503608c, FAIL
persist-txn-fencing, #7636, 2024-05-03 23:33:56 +0000, …
```

buildkite insights: optionally include commit hash in step analysis

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Patch release to fix blue/green deployment workflows for non-admin Materialize users.

dbt-materialize: release v1.7.8

---

src/arrow-util/src/builder.rs
src/pgwire/src/protocol.rs
src/testdrive/src/action/s3.rs
test/testdrive/copy-to-s3-minio.td

Part of the work towards copy-to-s3 private-preview: https://github.com/MaterializeInc/materialize/issues/7256
Map and List types are handled in a fairly straightforward way, but Array types are tricky due to their nature in PG/MZ.
I've chosen to represent them as a Struct with two fields - one containing the array elements and the other containing the number of dimensions in the array.
There were also some slight API differences between the StructBuilder, ListBuilder, and MapBuilder as compared to the primitive-type builders. If you'd like to learn more about those, see:
https://docs.rs/arrow/latest/arrow/array/builder/struct.StructBuilder.html
https://docs.rs/arrow/latest/arrow/array/builder/struct.MapBuilder.html
https://docs.rs/arrow/latest/arrow/array/builder/struct.GenericListBuilder …

storage/copy-to-s3: Parquet format support for nested types: array, list, map

---

src/persist-txn/src/txn_cache.rs
src/persist-txn/src/txn_read.rs
src/persist-txn/src/txns.rs

This commit cleans up the txn_cache.rs file, and some related files, by taking the following actions:
- Correct comments that have rotted over time.
- Add new comments that explain potentially confusing parts.
- Add some comments around a known bug.
- Add explicit asserts for requirements that were previously implicit.
- Update `validate()` methods to include all invariants.
Touches #26893

persist-txn: Clean up txn_cache.rs

---

src/persist-client/src/read.rs

persist: Remove stale comments

---

src/balancerd/src/lib.rs

Counts the # of pgwire TLS connections that do / do not send along SNI. Long term there are a number of benefits in exclusively relying on SNI / connection options, rather than using Frontegg resolution, so I'm curious where we stand today.
-

metric coverage for # of pgwire TLS connections with and without SNI

---

src/expr/src/linear.rs
src/persist-client/src/cfg.rs
src/persist-client/src/fetch.rs
src/persist-client/src/lib.rs
src/storage-operators/src/persist_source.rs

Reviving #25994
Avoid decoding data when the `MfpPlan` tells us we will not read the results. This is a total hack, pending columnar data representations, but at the moment it reduces `main` from (release, local not cloud)
```
materialize=> select count(*) from bar;
count   
----------
10000000
(1 row)
Time: 2719.868 ms (00:02.720)
materialize=> 
```
to (in this branch)
```
materialize=> select count(*) from bar;
count   
----------
10000000
(1 row)
Time: 1153.915 ms (00:01.154)
materialize=> 
```
Touches #20618
The first commit is exactly Frank's original PR, except rebased.
-

persist: avoid decoding persist data when data are ignored

---

src/adapter/src/catalog/builtin_table_updates.rs
src/catalog/src/builtin.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/rehydration.rs
src/storage/src/storage_state.rs
test/mysql-cdc/mysql-cdc.td
test/mysql-cdc/subsource-resolution-duplicates.td
test/pg-cdc/pg-cdc.td
test/pg-cdc/subsource-resolution-duplicates.td
test/testdrive/get-started.td
test/testdrive/load-generator.td
test/testdrive/quickstart.td
test/testdrive/tpch.td

Now that we understand which ingestion an ingestion export belongs to, we can:
- Announce the cluster that it's running on in introspection tables (#24235)
- Propagate drop commands for individual subsources down to the clusters on which they run. This, in turn, means that we will get `DroppedIds` responses from the cluster containing ingestion export `GlobalId`s and can then retire its data shard. (#8185)
Fixes #24235
Progresses #8185; not closing it because we should add a test.
Fixes #24773
-

storage: understand which cluster ingestion exports run on

---

Cargo.lock
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/client.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/telemetry.rs
src/environmentd/src/telemetry.rs
src/orchestrator/src/lib.rs
src/segment/Cargo.toml
src/segment/src/lib.rs

One of the cloud team's SLIs this quarter is the amount of time between the commit of a `CREATE CLUSTER` or `ALTER CLUSTER` command and when the cluster becomes ready. So, add a Segment event every time a cluster becomes ready or becomes not ready.
It will then be straightforward to write an analytics query that joins these new events against the existing "Cluster Replica Created" events to determine the cluster startup delay. (Under the hood, an `ALTER CLUSTER` is converted into a sequence of replica drop/creation events.)
Touches MaterializeInc/cloud#9311.
Following is an example of the Segment events that get issued when creating a new cluster. Since I was running this off my local machine, clusters become ready nearly instantly. 
```json
{
"context": {
"group_id": …
```

adapter: instrument cluster readiness

---

test/bounded-memory/mzcompose.py

Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fbounded-memory-mysql-tx
If the nightly build fails, the merge will need to await the merge of https://github.com/MaterializeInc/materialize/pull/26382.

tests: bounded memory: enable mysql-cdc-large-tx

---

src/sql-parser/src/ident.rs

Closes #26904
This implements the "minimal solution" solution described in the issue.
- I'm using doctests with `compile_fail` to check for the failing compilation (they would pass, or rather fail, on `main`).
- The compile time error isn't perfect, because it would e.g. say `provided string literal FORBIDDEN is an invalid identifier` when not passing in a direct literal but rather a `const`. But it is the same for the other compile error, and probably good enough.
-

sql-parser: make `ident!` and `Ident::new` consistent

---

test/testdrive/copy-to-s3-minio.td

The test is timing-dependent and thus can cause false test failures. To be fixed in #26963.
-

Disable copy-to-s3 sentinel test

---

src/adapter/src/catalog/migrate.rs

For some reason (I am sure it's good!), `Visit` doesn't recurse into `AstInfo::ColumnName`, which is treacherous because that means we don't visit all `GlobalId`s when traversing the AST and it requires manual intercession. We should fix the root issue (#26945) but I think this is fine to unblock the release.
-

sql: manually visit item name in ID migration

---

doc/user/content/sql/copy-to.md
doc/user/content/sql/types/_index.md
src/arrow-util/src/builder.rs

* This PR adds a known-desirable feature: https://github.com/MaterializeInc/materialize/issues/26884
I've added a section to the `copy-to` doc page that explains how materialize types are converted during copy-to-s3 with `FORMAT = 'parquet'`. Since the main copy-to-s3 docs are being worked on by @morsapaes this is all commented out so it's not yet rendered in the html output, and Marta can uncomment when putting up a PR for the full documentation.
This also adds the missing `uuid` type to the materialize top-level `types` doc page : https://materialize.com/docs/sql/types/
And it fixes the names of the 'extension types' we put into the arrow metadata to correspond more closely to external-facing materialize type-names.
-

storage/copy-to-s3: Document parquet format type conversions and fix extension type names

---

src/persist-txn/src/txn_cache.rs
src/persist-txn/src/txn_read.rs

The `TxnsCacheState` has an invariant, that is written in the `compact_to()` method but not the struct definition, that states `self.since_ts <= self.progress_exclusive`. Previously, when initializing the cache, `progress_exclusive` was always initialized to `T::minimum()` while `since_ts` was always initialized to the since of the txns shard. As a result, almost all caches were initialized in a broken state. This led to the confusing scenario where the cache may be learning about new entries that should have already been compacted.
This commit fixes the issue by always initializing the cache s.t. both the initial `since_ts` and the initial progress_exclusive` are advanced to the since of the txn shard.
Touches #26893
- There are no user-facing …

persist-txn: Fix since_ts invariant

---

ci/plugins/mzcompose/hooks/post-command

Not sure yet if this is helpful as it is.
Future work:
* We should collect the stream (instead of the snapshot at the end) in a proper way.
* Furthermore, we might want to trigger this directly from the bounded-memory check to capture data per scenario.
* Moritz suggested to read the `max-rss` property.

ci: save docker stats as artifact

---

Cargo.lock
ci/nightly/pipeline.template.yml
deny.toml
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
misc/python/materialize/checks/scenarios.py
misc/python/materialize/parallel_workload/action.py
src/ore/Cargo.toml
src/ore/src/bytes.rs
src/persist-client/benches/plumbing.rs
src/persist-client/src/batch.rs
src/persist-client/src/internal/metrics.rs
src/persist-proc/src/lib.rs
src/persist/Cargo.toml
src/persist/src/cfg.rs
src/persist/src/error.rs
src/persist/src/indexed/columnar/arrow.rs
src/persist/src/indexed/columnar/parquet.rs
src/persist/src/indexed/encoding.rs
src/persist/src/metrics.rs
src/workspace-hack/Cargo.toml

This PR adds new encoding and decoding methods for our existing `ColumnarRecords` type that uses the newer `arrow-rs` and `parquet-rs` crates. These methods are behind a dyncfg "persist_use_arrow_rs_library" and we add a new Prometheus metric "mz_persist_arrow_operations" to track how often we're using one library over the other.
While working on writing structured Row data into S3 (https://github.com/MaterializeInc/materialize/issues/24830) I hit a bug related to `arrow2`/`parquet2` and nested struct fields. If there is a nested struct column and one of the inner most child columns is marked as not nullable, but its parent struct is nullable, then `parquet2` loses data on encoded and fails to decode.
For example, the following schema is similar to what we'd use in production:
```
{
"k": …
```

persist: Add `arrow-rs` methods behind a dyncfg

---

src/persist-client/src/internal/state.rs
src/persist-client/src/lib.rs

Please see comments in code/tests. I noticed this while working on my PR that factors out a `StorageCollections` from the controller, which might do finalization with slightly different timing/at a different moment. But this might have been weird before.
The tests would fail without this fix, because `is_finalized` returns `false`.
-

persist: fix finalize_shard/tombstoning

---

src/persist-client/src/cli/inspect.rs
src/persist/src/indexed/encoding.rs
src/persist/src/metrics.rs

New command for `persist-cli` that checks if all blobs for an environment return the same values when deserialized by `arrow2` and `arrow-rs`. Then we re-encode with `arrow-rs` and check again.
We recently merged https://github.com/MaterializeInc/materialize/pull/26968 which allows us to encode and decode blobs with the new arrow-rs library.
- N/a

persist-cli: check if values roundtrip though `arrow-rs`

---

src/sql/src/plan/statement/show.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/rehydration.rs
src/storage/src/storage_state.rs

#26826 introduced an issue with frontier advancement that shows up in at least some nightly tests (https://buildkite.com/materialize/nightly/builds/7697#018f5565-d7e6-4d28-84e4-e83085ba29ec). I tried gracefully fixing the issue in #26983 but that approach introduced a different class of failure. I need some more time to fully resolve this, so I am tactically reverting the bits in #26826 that are most likely to have caused the regression.
Closes #26976
Unfixes #24773
This PR fixes a recognized bug. #26976
-

storage: revert `IngestionExport`/cluster correlation from storage controller

---

src/metrics/src/lgalloc.rs
src/metrics/src/rusage.rs

Collecting the lgalloc file/memory statistics can take a significant amount of time for processes with large page tables. This change reduces the collection interval from 10s to 30s, which should still provide up-to-date data to prometheus as we're scraping only once a minute.
This fixes high CPU utilization in `lgalloc_stats`. Overall, this seems to be less than 2% of our CPU utilization, but in my staging account it was closer to 10%. https://pprof.me/78678452f12318493381a9cf6b213f34 shows the cost of walking the page tables.
This should really be a flag, but we're instantiating the metrics tasks before having access to any flags. In the long run, we can make the tasks configurable. Reducing the interval itself is a safe change and immediately removes the issue we're observing.
-

Reduce metrics collection from 10 to 30 seconds

---

misc/python/materialize/scalability/comparison_outcome.py
misc/python/materialize/scalability/endpoints.py
misc/python/materialize/scalability/regression_assessment.py
test/scalability/mzcompose.py

This shows an annotation in CI when a regression occurs. Previously, nothing was shown and logs had to be searched.
https://buildkite.com/materialize/nightly/builds/7722

scalability framework: failure reporting

---

misc/python/materialize/parallel_workload/action.py
src/persist-client/src/cfg.rs
src/persist-client/src/fetch.rs
src/persist-client/src/internal/metrics.rs
src/persist-client/src/lib.rs
src/persist-client/src/operators/shard_source.rs
src/persist-client/src/project.rs
src/persist-client/src/read.rs
src/persist-txn/src/operator.rs
src/storage-operators/src/persist_source.rs
test/sqllogictest/shard_errors.slt

Motivation (h/t bkirwi): it's empirically very common for users to do
`select count(*) from x` queries to explore a brand new relation `x`.
These queries run in time proportional to the number of triples in `x`,
which can be slow when `x` is large. However, users prefer when their
queries are fast.
Persist recently started storing in metadata the sum of diffs for each
hollow part in a shard. In `persist_source`, if a part contains data
from entirely before the query `as_of`, and the pushed-down MFP projects
to an empty list of columns, and we can prove that the part is error
free, then we can use the count from stats instead of loading the data.
- Summing the diffs in a part is equivalent to projecting the row in
each tuple to an empty row and then consolidating. (Which is pretty
much how …

persist: speed up `select count(*) from persist`

---

src/mysql-util/src/decoding.rs
src/mysql-util/src/desc.proto
src/mysql-util/src/desc.rs
src/mysql-util/src/schemas.rs
test/mysql-cdc/30-text-columns.td

Supports a new MySQL Source trial whose upstream data includes invalid `0000-00-00` dates that are currently causing ingestion of those date columns to fail. This adds support for specifying the date and datetime columns containing invalid dates to be rendered as `TEXT COLUMNS` instead.
In the future we may add user-facing options to allow casting invalid dates to NULL or some other value, but that work needs scoping and more time to implement.
-

storage/mysql: Support specifying date/datetime columns as text

---

.github/CODEOWNERS

storage: add mysql-util CODEOWNER

---

src/ore/src/bytes.rs

ore: fix some unused lints when parquet feature is disabled

---

src/timely-util/src/capture.rs
src/timely-util/src/lib.rs
src/timely-util/src/reclock.rs

Implement a new reclock operator which has asymptotically better performance than the existing one by taking advantage of a new technique and a new assumption.
The technique exploited by this implementation is maintaining the pile of data waiting to be reclocked in runs of updates that are mutually comparable in their partial order. Maintaining those runs (called chains[1]) allows for very efficient extraction of new batches of data as we can leverage binary search within each chain. Furthermore, for all the concrete timestamp types used for reclocking the linear extension order implemented by `Ord` leads to an optimal number of chains for a given subset.
The new assumption exploited by this implementation is assuming that the timestamp we're reclocking onto is totally ordered. This is by …

storage: reclocking with better asymptotic performance

---

doc/user/content/releases/v0.100.md
doc/user/content/sql/types/map.md
src/repr/src/scalar.rs
src/sql-lexer/src/lexer.rs
src/sql-parser/src/ast/defs/expr.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select
src/sql/src/plan/query.rs
test/sqllogictest/map.slt

Add support for long desired map constructors, akin to list and array constructors. Maps can now be constructed with the `MAP` literal:
MAP['a' => 1, 'b' => 2]
Or from a subquery:
MAP(VALUES ('a', 1), ('b', 2))
See the documentation within for details.
- Add a `MAP` expression that can construct a map from a list of key–value pairs or a subquery.

sql: add support for map constructors

---

src/compute-client/src/protocol/command.rs
src/dyncfg/build.rs
src/dyncfg/src/dyncfg.proto
src/dyncfg/src/lib.rs
src/sql/src/session/vars.rs

Shared via to_bits/from_bits so we can use atomics instead of Arc+Mutex.
-

dyncfg: add support for f64 configs

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/coord.rs

#26556 had a bug in that it did not properly determine the final dependency order of all IDs.
The bug was caused by [this line](https://github.com/MaterializeInc/materialize/pull/26556/commits/b9ba4afbd184918b13ca1ffe639b14a3f69d7f89#diff-8d2fe0db05338dd8df0efaffc2dbdeb4075ccf16e70f98ffa5911c75b0900974R388-R397), which @guswynn describes [on Slack](https://materializeinc.slack.com/archives/CTESPM7FU/p1715370762843559?thread_ts=1715285852.486319&cid=CTESPM7FU):
> this is because `.rev` has`I: DoubleEndedIterator` requirement. The iterator returned by `Filter` is double-ended (because its build on top of a double-ended one), so it just reverses the whole stack. basically, `.rev` doesnt buffer the values and then reverse them after the `filter`.
This means we just need to try again, but with …

v.0.99: global id migration fix

---

src/adapter-types/src/compaction.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/error.rs
test/sqllogictest/retain_history.slt

We incorrectly understood an internal investigation and believed that indexes cause dependent indexes to also increase their compaction window. This is not the case: only the arrangement created by the index has its compaction increased. Thus we can remove this restriction since it was designed only to prevent silent memory increases by users.
Fixes #27017
Partial revert of commit 844fa219ec5d3522e6add5d4af8afd8d7ff1e3e4.
- n/a

adapter: remove cascade index retain history requirement

---

misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel

I got the build rule for `snappy` from tensorflow, but forgot to include the license.
- N/a

bazel: Add license for snappy

---

test/canary-load/mzcompose.py

Chasing down https://buildkite.com/materialize/qa-canary/builds/101.

cloud canary: better error output

---

src/prof-http/src/lib.rs

`stats.resident` is actually the closest to physical memory, which is how ooms happen. Its nice to compare this to `stats.active`!
-

jemalloc: add resident stat to profile page

---

WORKSPACE
ci/builder/Dockerfile
ci/nightly/pipeline.template.yml

This PR gets Bazel running in CI. Specifically it does the following:
1. Adds `bazel` to the `ci-builder` image
2. Tweaks `rules_foreign_cc` so we can bootstrap `make` on Linux
3. Adds a new test group to the Nightly pipeline that invokes `bazel test //...` and uses the remote cache introduced in https://github.com/MaterializeInc/i2/pull/1847
* The only tests we have right now are a `build_test` to make sure our C dependencies successfully build.
[Nightly run](https://buildkite.com/materialize/nightly/builds/7739#018f64f9-8e46-467c-bd1a-cb4ef2a964f8), if you look at the retries you'll see the tests weren't actually run, Bazel returned cached results!
This isn't yet testing hermeticy of our builds, to do that we need to [add a sysroot](https://steven.casagrande.io/articles/sysroot-generatio …

bazel: Add `bazel` to ci-builder, add Nightly test target

---

Cargo.lock
deny.toml
misc/cargo-vet/audits.toml
src/persist-client/Cargo.toml
src/persist-client/src/internal/trace.rs

This changes Persist's spine implementation from a binary tree to an N-ary tree where N=2.
Obviously this should have no actual impact on its behaviour -- but it sets us up to vary N more easily in the future.
#16607 
I pulled in `arrayvec` here - a new dep, but I think it's a good one, and it's tailor-made for this sort of case.
I think this is correct for N=2; while I've made some effort to make it more likely to work for N>2, I haven't tested it, and would prefer to take that as a followup. (Though if you notice anything obviously wrong here I'm happy to shake that out early of course!)
-

[persist] Generalize some spine internals

---

src/sql-parser/src/ast/defs/expr.rs
src/sql/src/func.rs
src/sql/src/plan/expr.rs
src/sql/src/plan/query.rs
src/sql/src/plan/transform_ast.rs
src/sql/src/plan/typeconv.rs
test/sqllogictest/funcs.slt
test/sqllogictest/map.slt

Previously, the following query would fail to plan in Materialize:
SELECT LIST[('a', 1), ('b', 2)]
The issue was in our selection of a best common type for the list elements. `guess_best_common_type` would assess that there were no list elements with a known (i.e., coerced) type and fall back to using `text`. The query would then fail to plan, since the record literals are not coercible to `text`.
If all list elements are uncoerced record literals, the best common type is some sort of record type. This commit adjusts
`guess_best_common_type` accordingly. The new implementation detects this situation and constructs a record type as the best common type, where the type of each field is the result of guessing the best common type for that field.
The specific motivation for this change is to …

sql: improve coercion of record literals

---

doc/user/content/sql/alter-system-reset.md
doc/user/content/sql/alter-system-set.md

Context: slack thread https://materializeinc.slack.com/archives/CU7ELJ6E9/p1715623121851309
-

docs: add note that superuser are privileges required for `ALTER SYSTEM SET` and `ALTER SYSTEM RESET`

---

src/rocksdb/src/lib.rs
src/rocksdb/tests/basic.rs
src/storage/src/upsert.rs
src/storage/src/upsert/autospill.rs
src/storage/src/upsert/rocksdb.rs

Initial work towards enabling https://github.com/MaterializeInc/materialize/issues/26003
This adds support for the "merge" operation in rocksdb (https://github.com/facebook/rocksdb/wiki/Merge-Operator) by allowing a user of `mz-rocksdb-util` to provide an 'associative merge function' and to provide 'merge' updates for a key in addition to 'put' and 'delete' updates to a key.
There are 4 semantic changes done to the rocksdb util:
- `bincode::Options` are now part of `InstanceOptions` since they are necessary for use in the merge function
- `InstanceOptions` optionally accepts a `merge_operator` function that can be treated as an 'associative merge operator'
- the `multi_put` command has been renamed `multi_update`, and rather than using an `Option` to demarcate whether the operation should …

storage/rocksdb: Add support for specifying merge operator fn and merge commands

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This addresses failures in https://buildkite.com/materialize/nightly/builds/7756#018f734a-8a08-4f65-9d73-9600b10b89ea.
0d7121d719 postgres consistency: extend ignore regarding eszett uppercasing
323b4082ff postgres consistency: add ignore for timestamp extraction
* https://github.com/MaterializeInc/materialize/issues/27078
* https://github.com/MaterializeInc/materialize/issues/26846

postgres consistency: add ignores

---

misc/python/materialize/scalability/schema.py

Please see comments in the code.
-

tests,scalability: wait for indexes to be hydrated

---

src/persist-client/src/fetch.rs
src/persist-client/src/iter.rs
src/persist-client/src/lib.rs
src/persist-client/src/operators/shard_source.rs
src/persist-client/src/read.rs
src/persist-txn/src/txn_cache.rs

This swaps out Persist's leasing mechanism: instead of explicitly returning leases to the reader that issued them, we generate a lease token that keeps the lease alive as long as it's held.
This works transparently for most `LeasedBatchPart` usage... the only difference is that there's no need to return the part explicitly. However, we need some other way to do lease management in the shard source, since we still can't send leases across process boundaries. This code makes serializing a part also spit out the lease, and makes the source hold on to the lease until a frontier advances.
This is useful for #26939 - eg. it would be convenient if I could turn a single `LeasedBatchPart` (which actually represents a list of hollow parts stored elsewhere) into a bunch of `LeasedBatchPart`s …

[persist] Replace the lease returner with an Arc-based count

---

src/compute/src/render/top_k.rs

Change the rendering of topk plans to avoid an intermediate consolidate. At the moment, we render plans by forking the inputs, arranging and reducing once side, then concatenating the inputs with negated reduction output, and consolidating the result. This makes sure that we consolidate eagerly, but at the same time does duplicate work: The next operator forms an arrangement, so we could just reuse that instead.
Ths PR implements this pattern, removing one consolidate from each topk stage, and adding it back after the final stage to ensure the topk output itself is consolidated. Note that we now apply the hash modulus on uncompacted data, whereas it previously was guaranteed to be consolidated. This might increase the cost of the …

Avoid explicit consolidation in topk rendering

---

doc/user/content/sql/system-catalog/mz_internal.md
src/catalog/src/builtin.rs
test/sqllogictest/autogenerated/mz_internal.slt

The console often ends up joining mz_databases and mz_schemas manually, because we need the database and or schema IDs.
- No public facing changes

adapter: mz_object_fully_qualified_names includes database and schema IDs

---

misc/python/materialize/output_consistency/data_type/data_type_category.py
misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/params/map_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/map_return_spec.py
misc/python/materialize/output_consistency/input_data/return_specs/map_value_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/map_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/map_values_provider.py
misc/python/materialize/output_consistency/operation/operation.py

Support maps in the output-consistency test framework and test the new map constructor (https://github.com/MaterializeInc/materialize/pull/27006) amongst other things.
This is based on https://github.com/MaterializeInc/materialize/pull/27082.
014cac903a output consistency: support map type
d88426d2bd output consistency: add map operations
507f8f3bef output consistency: add new map constructor as operation
631ae9c859 postgres consistency: disable map type for Postgres (does not support maps)
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fmaps

output consistency: support for maps

---

misc/python/materialize/mzcompose/test_result.py

ci: fix junit.xml reporting

---

src/environmentd/src/test_util.rs
src/environmentd/tests/sql.rs

I discovered this with my PR that adds more concurrency to the controllers, where upper updates can sometimes be delayed. But it's a potential problem already today, where upper updates from sources can also be delayed.
The first commit is renaming and clearing up some things. The second commit is the actual fix.
-

 adapter,tests: make test_session_linearizability resistant to slow propagation of source uppers

---

misc/python/materialize/cli/ci_annotate_errors.py

* Get rid of "Unknown error in" phrase
* Split error message and error details block
(with slightly different data)
* https://buildkite.com/materialize/nightly/builds/7782
* https://buildkite.com/materialize/nightly/builds/7777
* https://buildkite.com/materialize/test/builds/82062

ci: improve error annotations

---

src/storage-types/src/dyncfgs.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/statistics.rs
src/storage/src/source/postgres.rs
src/storage/src/source/postgres/replication.rs

I had to do it for the `offset_known` ones, so I did it for all non-trivial (I think) `Duration`'s in `mz_storage::source`. 
-

storage: dyncfg-ify various mz_storage::source durations

---

src/clusterd/src/bin/clusterd.rs
src/persist-client/src/cfg.rs
src/persist-client/src/fetch.rs
src/persist-client/src/internal/metrics.rs
src/persist-txn/src/operator.rs
src/storage-operators/src/persist_source.rs

Unblock the transition to cc replicas by reintroducing physical
persist_source flow control. We introduce a new mechanism to improve a
couple deficiencies in the previous one:
- (1) Our product principle of any dataflow that works in the steady
state should be able to rehydrate (see below).
- (2) More directly model the constrained resource.
Thought experiment for (1): A single dataflow has N inputs, each a
unique shard. One by one, a 128 MiB part is written to each of them. If
we want this to rehydrate, the unavoidable conclusion is that we need
cross-persist_source flow control.
- This has historically been stressful because the old mechanism worked
on granular timely timestamps, which could easily lead to deadlocks if
used across multiple inputs (thus each was totally isolated).
- We …

persist: use semaphore-based physical flow control in cc replica fetches

---

ci/deploy/pypi.py

pyright fails to understand that distutils comes from brew on macos
-

ci: fix bin/lint on macos

---

src/compute/src/render/reduce.rs
src/compute/src/render/top_k.rs
src/compute/src/row_spine.rs
src/repr/src/row.rs

Previously, copying the contents of a DatumSeq would require iterating the datums in the DatumSeq and copying each item individually. With this change, we exploit the fact that the row encoding in DatumSeq is a correct row encoding, which allows us to copy the contents directly, without going through their datum representation.
-

Efficient copy of DatumSeq

---

misc/python/materialize/cli/ci_annotate_errors.py

CI should report the failed test.
https://buildkite.com/materialize/nightly/builds/7789

ci: annotate failed miri test cases

---

ci/test/pipeline.template.yml
test/skip-version-upgrade/mzcompose.py

To avoid such issues: https://materializeinc.slack.com/archives/C01LKF361MZ/p1715867464383909

tests: run upgrade checks on release docs update, fail on forgotten release bump

---

misc/python/materialize/checks/all_checks/alter_index.py
src/environmentd/tests/sql.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars/definitions.rs
test/retain-history/mzcompose.py
test/sqllogictest/alter.slt
test/sqllogictest/object_ownership.slt
test/sqllogictest/redacted.slt
test/sqllogictest/retain_history.slt
test/sqllogictest/transactions.slt
test/testdrive/consolidation.td

Error if RETAIN HISTORY is less than the default (1s) or disabled. Less than 1s
is bad because 0 is known to be broken and sub 1s compaction is almost always
harmful to users (their queries will likely have always wait 1s) without
benefit. 0 used to mean disabled (i.e., no compaction ever) and is bad because
it'll eventually cause OOMs. Users can specify a very high number if they want
that.
Fixes #27083
- n/a

sql: disallow retain history 0 or less than the default

---

src/compute/src/render/context.rs
src/expr/src/scalar.rs

MZ avoids DD's `Arranged::flat_map_ref` which could consolidate updates before producing them, and we should apply the same transformation to our code as DD would: consolidate updates before feeding them to the `logic` that takes them and runs with them. This has the potential to substantially reduce work (in particular, `Row` manipulation work) that happens for large volumes of updates that consolidate well.
-

Consolidate on dowork

---

Cargo.lock
src/persist-types/Cargo.toml
src/persist-types/src/codec_impls.rs
src/persist-types/src/columnar.rs
src/persist-types/src/dyn_col.rs
src/persist-types/src/dyn_struct.rs
src/persist-types/src/parquet.rs
src/persist-types/src/part.rs
src/persist-types/src/stats.rs
src/repr/Cargo.toml
src/repr/src/row/encoding.rs
src/repr/src/stats.rs

This PR refactors all of the `Part`/statistics related Persist code to use `arrow-rs` instead of `arrow2`.
Because of the switch there are a few mechanical changes that I needed to make:
1. Non-optional primitive types (e.g. `u32`) now use Arrow arrays instead of buffers. This is because `arrow-rs` has both [`ArrowNativeType`](https://docs.rs/arrow/latest/arrow/datatypes/trait.ArrowNativeType.html) (e.g. `u32`) and [`ArrowPrimitiveType`](https://docs.rs/arrow/latest/arrow/array/trait.ArrowPrimitiveType.html) (e.g. [`UInt32Type`](https://docs.rs/arrow/latest/arrow/datatypes/struct.UInt32Type.html)). A [`ScalarBuffer`](https://docs.rs/arrow/latest/arrow/buffer/struct.ScalarBuffer.html) is generic over a native type, while a `PrimitiveArray` is generic over a primitive type. Trying to bridge …

persist: Migrate stats code to `arrow-rs`

---

src/adapter/src/coord/sequencer/inner/peek.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
test/testdrive/explain-pushdown.td

- Split the work for stats snapshotting into two parts: one that needs access to the controller but is fast, and one that doesn't need access to the controller but may be slow.
- Run the possibly-slow half in a task, to avoid blocking a coordinator thread.
See: https://github.com/MaterializeInc/incidents-and-escalations/issues/24
I'm working on a test for this, but figured I'd better get this up for review in the meantime! Let me know if you have suggestions.
-

[explain] Do the heavy lifting for `explain filter pushdown` in a task

---

doc/user/content/free-trial-faqs.md
doc/user/content/sql/create-cluster.md

Docs follow up for https://github.com/MaterializeInc/materialize/issues/26026, now that it's releasing.
-

Update user docs that reference mz_cluster_replica_sizes to use the new mz_catalog repo for this table

---

src/compute/src/render/join/mz_join_core.rs

Changes how we evaluate the join closure for linear joins: Instead of evaluating it for every `(time, diff)`, we only evaluate it once and then clone the output for each `(time, diff)`. We special-case the logic for no output, or single datum, single `(time, diff)` to avoid clones.
-

Only evaluate the join closure once

---

src/rocksdb/src/lib.rs
src/rocksdb/tests/basic.rs
src/storage-types/src/dyncfgs.rs
src/storage/src/upsert.rs
src/storage/src/upsert/autospill.rs
src/storage/src/upsert/memory.rs
src/storage/src/upsert/rocksdb.rs
src/storage/src/upsert/types.rs
test/upsert/mzcompose.py

* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/26003
The diff isn't huge to review all as one, but you can also review commit-by-commit to understand the semantic changes if that's easier.
I also need to do some performance testing on staging to compare both rehydration methods.
-

storage/upsert: Use RocksDB merge operator during snapshot rehydration

---

src/arrow-util/src/builder.rs
src/storage-operators/src/s3_oneshot_sink/parquet.rs
test/copy-to-s3/mzcompose.py
test/copy-to-s3/nightly/tpch1gb.td
test/testdrive/copy-to-s3-minio.td

3 issues motivate this PR:
- On a previous PR, @guswynn suggested that the parquet uploader structure would be simpler if the `ParquetFile` owned the `ArrowBuilder` object, so this implements that change (and it is indeed simpler)
- This PR fixes a recognized bug. Fixes: https://github.com/MaterializeInc/materialize/issues/27126 Previously we had a nested `if let Some(blah) = Option<ParquetFile>.take()` operation that meant the second call would not match since the value was already 'taken', but this has been switched to use a mutable ref instead. This was not being caught by the tests since we had used large `MAX FILE SIZE` values, so I lowered these to ensure we always split to more than 1 file in the tpch1gb tests.
-  Fix an issue handling timestamp-with-timezone columns -- this was …

storage/copy-to-s3: Fix bugs; refactor ParquetFile / ArrowBuilder structure

---

src/adapter/src/coord/peek.rs
src/repr/src/row/collection.rs
test/cluster/statement-logging/statement-logging.td

This PR fixes the rows returned metric reported in statement logging to consider any `OFFSET` and `LIMIT` in a query, previously it was not.
Fixes an unreported bug, we discovered this today, [Slack](https://materializeinc.slack.com/archives/C053EPHMU05/p1715868779558259?thread_ts=1715851171.213429&cid=C053EPHMU05)
- Changes the "rows returned" metric in statement logging to consider the `OFFSET` and `LIMIT` provided to a query.

statement-logging: "Rows returned" should consider `OFFSET` and `LIMIT`

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

bump to version v0.101.0-dev
-

release: bump to version v0.101.0-dev

---

test/canary-load/mzcompose.py

Based on result in https://buildkite.com/materialize/qa-canary/builds/104.

qa canary: ignore read timeout, improve test case infos

---

ci/release-qualification/pipeline.template.yml

`mysql-cdc-5_7_44` [is stuck in the release qualification](https://buildkite.com/materialize/release-qualification/builds/499#018f8390-b511-4fb3-9fc9-4c5ed0f61506) pipeline:
This is because of the `depends_on` relationship to `build-x86_64`, which does not exist in this pipeline.
I will add the build step but am not sure if the single tests warrants it. We could also move the check into another pipeline.

ci: release qualification: add x86 build step (which is referenced as dependency)

---

misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/params/collection_operation_param.py
misc/python/materialize/output_consistency/input_data/params/map_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/collection_return_spec.py
misc/python/materialize/output_consistency/input_data/return_specs/map_return_spec.py
misc/python/materialize/output_consistency/input_data/return_specs/map_value_return_spec.py
misc/python/materialize/output_consistency/input_data/types/collection_type_provider.py
misc/python/materialize/output_consistency/input_data/types/map_type_provider.py
misc/python/materialize/output_consistency/input_data/values/map_values_provider.py

This is a preparation for https://github.com/MaterializeInc/materialize/pull/27125, which adds the list type and can re-use some of the logic. It will also be helpful when adding the array type.
d22107e6b5 output consistency: map type: generalize return spec
9490691987 output consistency: map type: generalize type
8576dd38c5 output consistency: map type: generalize characteristic
85b5b6e30c output consistency: map type: generalize operation param
285eaa6e5f output consistency: map type: add further generalized operation params
https://buildkite.com/materialize/nightly/builds/7792 ✅ (failure unrelated)

output consistency: generalize map type structures

---

doc/user/content/manage/dbt/_index.md

We're missing an example for webhook sources in the dbt reference documentation, which [can mislead users](https://materializeinc.slack.com/archives/CURH4E75W/p1715795184798159) into thinking these are not supported.

doc/user: add webhook example to dbt reference documentation

---

ci/builder/Dockerfile
src/persist-cli/ci-base/Dockerfile

This commit adds the graphviz package to our CI docker images, which is needed by the maelstrom tests.

persist-txn: Add graphviz maelstrom dependency

---

src/adapter/src/coord/ddl.rs
src/adapter/src/coord/in_memory_oracle.rs
src/adapter/src/coord/timestamp_selection.rs
src/arrow-util/src/builder.rs
src/compute/src/containers/stack.rs
src/compute/src/render/top_k.rs
src/fivetran-destination/src/utils.rs
src/frontegg-auth/src/auth.rs
src/sql/src/session/vars/polyfill.rs
src/storage-operators/src/s3_oneshot_sink/parquet.rs

`cargo doc` seems to produce no warnings now.
- n/a

*: fix various broken rust docs

---

src/catalog/src/builtin.rs
test/sqllogictest/information_schema_columns.slt
test/sqllogictest/pg_catalog_class.slt
test/testdrive/pg-catalog.td

Improvements to our Postgres compatibility story. More context: https://materializeinc.slack.com/archives/C073KLQ0QHM/p1715968613948499
* ~Adds in `pg_catalog.pg_user`~ Moved to another PR.
* Adds `reltuples` column to `pg_catalog.pg_class`
* Adds `column_default` column to `information_schema.columns`
-

pgcompat: add some missing columns for Metaplane

---

src/persist-client/src/cli/admin.rs
src/persist-client/src/cli/inspect.rs

This PR adds two new options to the `persistcli admin finalize` subcommand, `--force-downgrade-since` and `--force-downgrade-upper`. This will allow us to forcibly finalize shards.
I tested this manually by starting environmentd locally, creating a table, then CTRL+C the process and waiting for the leased readers to expire. I was then able to successfully tombstone the related shard.
Cleanup unnecessary shards
- N/a

persist-cli: Add `force_downgrade_since` and `force_downgrade_upper` options to finalize shard

---

doc/developer/guide.md

This commit updates the CRDB version in the developer guide so that it matches our docker image.
Updates doc

doc: Update CRDB version in dev guide

---

src/persist-client/src/cli/admin.rs

Fix clippy merge skew

---

misc/python/materialize/checks/all_checks/materialized_views.py
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select

`SELECT AS OF ...` is a valid SQL query that produces a zero-column, zero-row relation at the specified as-of time. Not very useful, but a semantically valid thing to do nonetheless.
@aalexandrov noticed in #27167 that this query was being misparsed in a way which did not roundtrip, which could result in a broken catalog if such a query were used as the definition of a materialized view.
Fix #27167.
- Not worthy of a release note.

sql-parser: correct parsing of `SELECT AS OF ...`

---

misc/python/materialize/output_consistency/data_type/data_type_category.py
misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/params/list_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/list_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/list_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/list_values_provider.py

This is based on:
* https://github.com/MaterializeInc/materialize/pull/27129
* https://github.com/MaterializeInc/materialize/pull/27128
1b33e4d6f1 output consistency: list type: add type and return spec
47d675708d output consistency: list type: add operation params
16a90193e2 output consistency: list type: add list values
d3659a7edf output consistency: list type: add operations
* https://buildkite.com/materialize/nightly/builds/7791 ✅ (failure is unrelated and fixed on main)
* https://buildkite.com/materialize/nightly/builds/7825 ✅

output consistency: add list type

---

misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/text_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/array_operation_param.py
misc/python/materialize/output_consistency/input_data/params/collection_operation_param.py
misc/python/materialize/output_consistency/input_data/params/list_operation_param.py
misc/python/materialize/output_consistency/input_data/params/map_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/array_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/array_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/array_values_provider.py
misc/python/materialize/postgres_consistency/execution/pg_dialect_adjuster.py

https://buildkite.com/materialize/nightly/builds/7808 ✅

output consistency: add array type

---

src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/cluster.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs
src/catalog/tests/read-write.rs

This PR refactors `mz_catalog::Op::DropObject` to take a `Vec<ObjectId>` instead of a single `ObjectId`.
Previously a `DROP ... CASCADE` would result in a `Op::DropObject` for every object we needed to drop. This had poor performance because removing a batch of items from a durable catalog transaction is `O(n)`, where `n` is the number of objects in the catalog. But because we would issue an `Op::DropObject` for every item we're dropping, we would have a batch size of 1 and the runtime of `DROP ... CASCADE` became `O(m * n)`, where `m` is the number of objects we're dropping. With this refactoring the runtime of `DROP ... CASCADE` is `O(n)`.
Concretely I tested creating a schema with 1 table and 1,000 views then running `DROP SCHEMA a CASCADE`:
* `main`: ~28 seconds
* This PR: ~700ms …

adapter: Refactor `DROP ... CASCADE` into a single `catalog::Op`

---

misc/python/materialize/checks/all_checks/materialized_views.py

This fixes platform check failures in https://buildkite.com/materialize/nightly/builds/7828 introduced by https://github.com/MaterializeInc/materialize/pull/27181 and https://github.com/MaterializeInc/materialize/pull/27185.

platform checks: fix upgrade checks

---

misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
misc/python/materialize/output_consistency/query/query_template.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py

Just refactorings. Extracted from https://github.com/MaterializeInc/materialize/pull/27194 to make that PR less crowded.
846fac5ce9 output consistency: move is_any_date_time_expression
845a86a508 output consistency: add matches_specific_select_or_filter_expression
6ec10945f2 postgres consistency: extract constants

output consistency: ignore entries refactoring

---

src/storage/src/upsert.rs

This was an oversight in https://github.com/MaterializeInc/materialize/pull/24663
- Observant readers will realize this is the first flow control related pr!
- ~I am going to see if this lets us shrink the `upsert-snapshot` `bounded-memory` test (I suspect it won't, because the `persist_sink` buffers quite a bit of data.)~
- I'll run nightly (upsert and zippy I think)
-

storage: dont buffer intermediate values in upsert

---

src/orchestrator-kubernetes/src/lib.rs
test/cloudtest/test_compute.py

We want to be able to schedule non-disk clusters on nodes with and without disk. This allows us to binpack all workloads onto the same nodes by omitting the selector from clusters w/o disk.
https://github.com/MaterializeInc/materialize/issues/27200
-

orchestrator: omit node selector when disk is not required

---

src/adapter/src/optimize.rs
src/environmentd/tests/testdata/http/post

It could previously give incorrect advice.
- n/a

adapter: improve mznow hint

---

Cargo.lock
Cargo.toml
ci/nightly/pipeline.template.yml
misc/python/materialize/checks/scenarios.py
misc/python/materialize/parallel_workload/action.py
src/ore/Cargo.toml
src/persist-client/src/cli/inspect.rs
src/persist-proc/src/lib.rs
src/persist-types/src/columnar.rs
src/persist-types/src/dyn_struct.rs
src/persist-types/src/part.rs
src/persist/Cargo.toml
src/persist/src/cfg.rs
src/persist/src/error.rs
src/persist/src/indexed/columnar.rs
src/persist/src/indexed/columnar/arrow.rs
src/persist/src/indexed/columnar/parquet.rs
src/persist/src/indexed/encoding.rs
src/persist/src/metrics.rs
test/sqllogictest/explain/pushdown.slt

This PR removes `arrow2` from our dependency tree entirely, and the feature gate that enabled switching between `arrow2` and `arrow-rs`.
Note: I'm not expecting any issues, but to be on the safe side I would like to keep our `arrow2` fork around for a few weeks, just in case we need to revert this PR.
We already migrated all of our stats collection to `arrow-rs` and today I moved the feature flag `persist_use_arrow_rs_library` to 100% of users. Removing `arrow2` simplifies our code and makes it easier to rebase https://github.com/MaterializeInc/materialize/pull/26561, introducing structured data into Persist.
- N/a

persist: Delete `arrow2` and 'persist_use_arrow_rs_library' dyncfg

---

misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This is based on https://github.com/MaterializeInc/materialize/pull/27194.
No adjustments to internal output-consistency and version-consistency were necessary because they currently do not implement this ignore function.
Nightly: https://buildkite.com/materialize/nightly/builds/7829 ✅

postgres consistency: fix ignore logic of content mismatches

---

src/adapter/src/optimize/index.rs
src/transform/src/notice/index_already_exists.rs
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/explain/replan_catalog_items.slt
test/sqllogictest/transform/notice/index_already_exists.slt

Include the name of the exported index in the index already exists notice.
* This PR fixes a previously unreported bug: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1716231408100059
-

Include name of export in index already exists notice

---

src/compute/src/render/context.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/reduce.rs
src/compute/src/render/sinks.rs
src/compute/src/render/top_k.rs
src/storage/src/source/source_reader_pipeline.rs
src/timely-util/src/operator.rs

This change adds support for specifying the container builder to the various variants of `flat_map` and adjusts the call sites. Most use the default capacity-based builder, but some switch to the consolidating variant. I selected places that apply scalar expressions to rows for the consolidating variant, which have the chance to change rows sufficiently that it enables further consolidation.
Best viewed with whitespace changes hidden!
-

Support container builders for flat_map variants

---

src/compute-client/src/controller/instance.rs
src/compute-client/src/protocol/response.rs
src/compute/src/compute_state.rs

#26665 introduced a new input frontier reported by replicas to the controller, which required some changes to the frontier reporting code on both sides. This introduced two bugs, both of which could result in a "frontier updates for unknown collection" error being logged by the controller when it received a `Frontiers` response for a collection whose state it had already dropped. This PR fixes both of these bugs.
1. Replicas would incorrectly send final `Frontiers` responses for dropped subscribe and copy-to collections.
For these collection types the compute protocol does not expect `Frontiers` responses. The buggy code therefore checked in `report_dropped_collections` whether a dropped collection was a subscribe (or copy-to) by calling `CollectionState::is_subscribe`. That method was …

compute: fix "frontier updates for unknown collection" error

---

src/compute/src/render/context.rs

Fix merge skew introduced by #27107 by providing the required type parameters to `flat_map`.
-

Fix merge skew, add container builder arguments to flat_map

---

src/expr/src/scalar/func/impls/float32.rs
src/expr/src/scalar/func/impls/float64.rs

this exists now since 1.77 @sploiselle

get rid of unsafe code for float rounding

---

src/ore/Cargo.toml
src/ore/benches/bytes.rs
src/ore/src/bytes.rs

This PR refactors `SegmentedBytes`, specifically the `SegmentedReader`, to generally improve performance.
Previously the `SegmentedReader` would create a `BTreeMap` and precompute the segment offsets, and when reading, lookup the correct segment from this map. This allowed for very fast seek time, but made reading slower than necessary, and creating a `SegmentedReader` _extremely_ slow.
We refactor `SegmentedBytes` and `SegmentedReader` in a few ways:
1. `SegmentedReader` now maintains a pointer, tracking the current segment that we'd read from, eliminating the logarithmic lookup in the `std::io::Read` path.
2. `SegmentedReader` does a logarithmic lookup of the correct segment when seeking. This slows down the `std::io::Seek` code path, but from our profiling we don't appear to seek …

ore: Make `SegmentedBytes` overall faster

---

src/persist-cli/src/main.rs
src/persist-client/src/cli/args.rs
src/persist-client/src/cli/bench.rs
src/persist-client/src/lib.rs

This adds a persistcli subcommand which grabs the set of blobs currently in a shard and fetches them all N times. It also optionally decodes them.
- Intended to be run with `bin/mzadmin environment job` against a shard in a real environment.
- This grabs the blobs out of state directly, instead of registering a leased reader, so that it can be read-only. This means there's a possibility that a blob is removed out from under it, resulting in a panic, but it seems to have been pretty rare in my experiments so far.
- Each round is fully finished before starting the next one (no pipelining across rounds).
- The timing and size of each fetch are printed in csv to stdout for followup processing.
I had initially planned to not bother …

persist: add basic s3 throughput bench tool to persistcli

---

src/expr/src/scalar/func/impls/string.rs
src/repr/src/adt/varchar.rs

While working with @frankmcsherry, we noticed that `text_to_varchar` was allocating a fresh string every time, even though `VarChar<S>` accepts `&str`.
Even when the text fits in the varchar limit, we would allocate a new string. There's no need to do this: just pass a reference.
-

compute: avoid needless allocations of strings in text-to-varchar conversion

---

misc/buildkite/git.bash

My `bin/lint` was failing the protobuf check. I narrowed it down to a case sensitivity issue in `misc/buildkite/git.bash`.
```ShellSession
$ sh -x ci/test/lint-main/checks/check-protobuf.sh 
+ set -euo pipefail
++ dirname ci/test/lint-main/checks/check-protobuf.sh
+ cd ci/test/lint-main/checks/../../../..
+ . misc/shlib/shlib.bash
++ try_last_failed=false
++ ci_try_passed=0
++ ci_try_total=0
+ . misc/buildkite/git.bash
++ set -euo pipefail
++ . misc/shlib/shlib.bash
+++ try_last_failed=false
+++ ci_try_passed=0
+++ ci_try_total=0
++ MZ_REPO_REF=origin
++ MZ_REPO_PULL_REQUEST_BASE_BRANCH=main
++ [[ '' != \t\r\u\e ]]
+++ git remote -v
+++ grep MaterializeInc/materialize
+++ grep fetch
+++ head -n1
+++ cut -f1
++ MZ_REPO_REF=
$ echo $?
1
```
-

qa: be case insensitive when finding the mzinc remote

---

misc/mzexplore/defs.jq
misc/mzexplore/depth.jq

Some `jq` hacking for computing AST depth.
New analysis of customer queries, as part of optimizer work.
-

mzexplore: compute maximum depth of ASTs in the wild

---

src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/metrics.rs
src/environmentd/src/http/sql.rs
src/pgwire/src/protocol.rs

Add cluster id, increase number of buckets, add execution strategy.
Fixes #25482
Fixes #20917
- n/a

adapter: improve mz_time_to_first_row_seconds metric

---

src/expr/src/scalar/func.rs
src/expr/src/scalar/func/impls/int16.rs
src/expr/src/scalar/func/impls/int32.rs
src/expr/src/scalar/func/impls/int64.rs
src/expr/src/scalar/func/impls/string.rs
src/expr/src/scalar/func/impls/uint16.rs
src/expr/src/scalar/func/impls/uint32.rs
src/expr/src/scalar/func/impls/uint64.rs
src/repr/src/adt/char.rs

As it stands, `LazyUnaryFunc` has a blanket implementation on `::could_error()` that looks at `Self::Output`. But some operations---`text_to_varchar`---may or may not fail depending on parameters.
This PR gives a little more flexibility.
- This PR adds a feature that has not yet been specified.
More fine-grained metadata on unary operations.
-

compute: allow `EagerUnaryFunc`s to identify when they might not error

---

src/storage-controller/src/lib.rs
test/testdrive/kafka-sink-statistics.td

We never want to reset statistics, it just makes client's lives harder! Sources don't seem to have the same issue, but I hardened some code anyways!
-

storage: avoid resetting sink statistics when using ALTER CONNECTION

---

src/persist-client/src/cache.rs
src/persist-client/src/cfg.rs
src/persist-txn/src/lib.rs
src/persist-txn/src/operator.rs
src/persist-txn/src/txn_cache.rs
src/persist-txn/src/txn_read.rs
src/persist-txn/src/txns.rs
src/storage-controller/src/lib.rs
src/storage-operators/src/persist_source.rs

Previously, each time the persist-txn operator was rendered, we'd crate
a (filtered) subscribe to the txns shard. This replaces it with a
process-singleton (unfiltered) subscribe.
There is a notable tradeoff here between N filtered vs 1 unfiltered
subscriptions. However, in staging envs when there was a bug that held
back the txns since, it caused a _very_ :nervous-laughter: and linearly
increasing amount of cpu, memory, and network use. Because of this, I
believe it's worth selecting the option that bounds the worst case over
the option that optimizes the case of a few tables.
We could later get the "optimizes the case of a few tables" back, if
necessary, with a decent amount of elbow grease: making TxnsRead more
sophisticated about quiescing as well as dynamically changing the set of …

persist-txn: use TxnsRead worker task in operator

---

doc/user/content/manage/dbt/_index.md
doc/user/content/manage/dbt/development-workflows.md
misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/Dockerfile
misc/dbt-materialize/dbt/adapters/materialize/__init__.py
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/dbt/adapters/materialize/connections.py
misc/dbt-materialize/dbt/adapters/materialize/exceptions.py
misc/dbt-materialize/dbt/adapters/materialize/impl.py
misc/dbt-materialize/dbt/adapters/materialize/relation.py
misc/dbt-materialize/dbt/include/materialize/macros/materializations/unit.sql
misc/dbt-materialize/dbt/include/materialize/macros/tests/helpers.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/cast.sql
misc/dbt-materialize/dbt/include/starter_project/dbt_project.yml
misc/dbt-materialize/dbt/include/starter_project/models/example/schema.yml
misc/dbt-materialize/setup.py
misc/dbt-materialize/tests/adapter/fixtures.py
misc/dbt-materialize/tests/adapter/test_constraints.py
misc/dbt-materialize/tests/adapter/test_dbt_clone.py
misc/dbt-materialize/tests/adapter/test_empty.py
misc/dbt-materialize/tests/adapter/test_unit_testing.py
misc/dbt-materialize/tests/adapter/test_utils.py

Fixes #26226.
Initial PR to update the required dependencies for the dbt v1.8.0 migration.

dbt-materialize: v1.8.0 migration

---

misc/dbt-materialize/CHANGELOG.md

Updating the changelog for the release of `dbt-materialize` v1.8.0.
See `CHANGELOG.md` for an overview of the release.

dbt-materialize: update changelog for v1.8.0

---

src/compute/src/render/reduce.rs

Like #27068 but for MinxMaxesHierarchical.
Change the rendering of mins-maxes-hierarchical plans to avoid an intermediate consolidate. At the moment, we render plans by forking the inputs, arranging and reducing once side, then concatenating the inputs with negated reduction output, and consolidating the result. This makes sure that we consolidate eagerly, but at the same time does duplicate work: The next operator forms an arrangement, so we could just reuse that instead.
Ths PR implements this pattern, removing one consolidate from each stage, and adding it back after the final stage to ensure the stage's output itself is consolidated. Note that we now apply the hash modulus on uncompacted data, whereas it previously was guaranteed to be consolidated. This might increase the cost of the …

Avoid consolidate in minsmaxes hierarchical

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py

There's a known Kafka sink bug; let's make things a little less noisy as we track that down.
Bug: https://github.com/MaterializeInc/materialize/issues/27219
-

[persist/sinks] Temporarily disable source since holds in CI

---

src/storage-controller/src/lib.rs

I added an assert that all SourceDesc changes should actually change the SourceDesc. However, I had overlooked the impossible to detect case where:
1. User creates PG source foo with tables a, b.
2. User drops subsource b. This does not update the SourceDesc.
3. User re-adds subsource b without having changed its schema.
In this case, the actual source desc will not have changed whatsoever and spuriously trip the assert. Unclear how to really detect this case, and in light of this use, the assert is of questionable value.
This PR fixes a recognized bug. Fixes #27246
-

storage: rm misguided soft assert when altering SourceDesc

---

test/testdrive/kafka-sink-statistics.td

@nrainer-materialize lets let this bake for a bit!
may help: https://github.com/MaterializeInc/materialize/issues/27255
-

storage: attempt to reduce flakiness of kafka-sink-statistics.td

---

misc/python/materialize/checks/all_checks/ssh.py
src/sql/src/plan/statement/ddl/connection.rs
test/mysql-cdc/mysql-cdc-ssl.td

Based https://materializeinc.slack.com/archives/C04LQV4KUR4/p1716405259031939
Also changed some random tests to test the change
-

storage: accept require/required interchangeably

---

src/persist-client/src/internal/gc.rs

Looks like these have been inverted from the intended meaning.
Previously-unreported bug.
-

[persist] Fix up some reversed metrics etc.

---

doc/user/README.md
doc/user/content/releases/v0.101.md
doc/user/content/sql/create-source/load-generator.md
doc/user/layouts/partials/sql-grammar/load-generator-option.svg
doc/user/sql-grammar/sql-grammar.bnf
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan/statement/ddl.rs
src/storage-types/src/sources/load_generator.proto
src/storage-types/src/sources/load_generator.rs
src/storage/src/source/generator.rs
test/testdrive/load-generator.td

Add new `AS OF` and `UP TO` options to all simple (non-KV) load generators. The former option controls the size of the initial snapshot, while the latter option controls the maximum amount of data generated by the load generator. Both are measured in number of ticks.
For example, with the default tick interval of 1s, setting `AS OF` to 300 and `UP TO` to 420 will create a load generator that starts with 5m worth of data and runs for 2m before ceasing.
This will be useful in the console's quickstart, which falls a little flat at the moment because building an index on a half dozen rows doesn't demonstrate how much faster the index makes queries. With these new load generator options, the console quickstart will be able to use a load generator that starts off with much more data and makes …

storage: allow configuring load generator as of and up to

---

src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/ident.rs
src/sql-parser/src/lib.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql-parser/tests/testdata/explain
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs

Teach some statements to preserve what the user typed so they can fully roundtrip their to_string impls.
- n/a

adapter: improve statement roundtripping of various statements

---

src/persist-client/src/fetch.rs
src/persist-client/src/iter.rs

This in theory should be more memory-efficient, since we only keep a couple indices per entry instead of allocating a fresh Vec.
This is also probably more friendly to our upcoming structured-data future, where we want to keep indices into a columnar representation instead of the data itself.
In #27157, @antiguru helpfully pointed out that we're doing quite a bit of allocation in this codepath under some circumstances. (Roughly, the first time we compact a very large batch.) In particular, we end up taking a columnar representation of the data and turning it into a long list of tiny allocations, which is not great for various reasons... replacing those small allocations with an inline index should reduce both total memory use and the sheer number of allocations.
Deploying this change in …

[persist] Store a vector of cursors instead of a vector of vecs

---

misc/python/materialize/checks/all_checks/ssh.py
test/mysql-cdc/mysql-cdc-ssl.td

Removes some test changes introduced in https://github.com/MaterializeInc/materialize/pull/27238 to fix nightly
Fix nightly for better signal in the release
- N/a

tests: Fix nightly

---

Cargo.lock
doc/user/content/releases/v0.102.md
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

We just cut the release of v0.101 so we need to bump our internal version number.
`v0.101` release
- N/a

build: Bump version number to v0.102.0-dev

---

src/storage-controller/src/lib.rs
src/storage-types/src/sources.proto
src/storage-types/src/sources.rs
src/storage-types/src/sources/kafka.rs
src/storage-types/src/sources/load_generator.rs
src/storage-types/src/sources/mysql.rs
src/storage-types/src/sources/postgres.rs
src/storage/src/render.rs
src/storage/src/render/sources.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/source_reader_pipeline.rs

There are a number of places where it will be nice to provide a simple and consistent API for resolving subsource references in a source. To demo this approach, I've implemented #26766
- Canonicalize subsource references
- Determine the schema of subources
Another way to look at this is as a generalization of the current [`SubsourceCatalog`](https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/catalog.rs#L1300), which this can replace. I haven't done that work but if this looks good, that will be the next step.
- Closes #26766
- Additional uses of `SubsourceResolver` are obliquely discussed in [Notion](https://www.notion.so/materialize/Generate-subsources-after-planning-sources-683772c62d8e46e1a0c8945fe789f545?pvs=4).
-

storage: add SubsourceResolver

---

src/persist-client/src/cli/admin.rs
src/testdrive/src/action/persist.rs

This PR adds a flag to `AdminArgs` that allows specifying an expected `applier_version` so we can relatively safely edit shards whose `applier_version` differs from the current build.
Cleanup old shards whose applier version has fallen behind the current build.
- N/a

persist-cli: Allow operating on old shards by specifying an expected `applier_version`

---

test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt

This fixes https://buildkite.com/materialize/slt/builds/5933#018fa53a-8458-4b9b-8d5e-1e5cf7cb9521 after the merge of https://github.com/MaterializeInc/materialize/pull/26856.

tests fix: index_too_wide_for_literal_constraints.slt

---

misc/python/materialize/output_consistency/enum/enum_constant.py
misc/python/materialize/output_consistency/enum/enum_operation_param.py
misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/string_type_provider.py
misc/python/materialize/output_consistency/input_data/values/string_values_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

Adding these types when I learned about `BPCHAR` and noticed that it is not behaving like in Postgres: https://github.com/MaterializeInc/materialize/issues/27247
This is based on https://github.com/MaterializeInc/materialize/pull/27248.
080e6f63dd output consistency: string type: add VARCHAR, CHAR, BPCHAR
9cd438580d output consistency: explicitly specify the length of BPCHAR
27f1d0cdaf postgres consistency: add ignores
eefa3dde4c postgres consistency: use different length for CHAR type to make it more diverse to BPCHAR(8)
b7e36d8d46 postgres consistency: add further ignores
be166595c8 output consistency: improve is_known_to_involve_exact_data_types expression matcher
1820ef6f6a postgres consistency: extend ignore
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3 …

output consistency: add further string types

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs

Previously, the catalog would discover dependencies between user items as the items were loaded. However, a recent change guaranteed that the order of item GlobalIds matches the dependency order. This commit takes advantage of that fact by loading items in GlobalId order and assuming they are being loaded in dependency order.

catalog: Simplify loading user items

---

src/adapter/src/coord/sequencer.rs

This reverts #26732.
The warning has fulfilled its purpose: It has been active in production for a time and informed us that there are plenty of users that manually target the `mz_introspection` cluster. Which means that when we implement #26731 we need to include some kind of automatic name translation to ensure that the old name will continue to work until all users have migrated.
* This PR removes an exploratory warning.
- N/A

Revert "adapter: log manual uses of mz_introspection"

---

misc/python/materialize/buildkite_insights/annotation_search/annotation_match.py
misc/python/materialize/buildkite_insights/annotation_search/annotation_search.py
misc/python/materialize/buildkite_insights/annotation_search/annotation_search_presentation.py

https://github.com/MaterializeInc/materialize/pull/27257 to be merged first.

buildkite search: annotation title

---

src/adapter/src/coord/peek.rs
src/expr/src/explain/text.rs
src/expr/src/relation/func.rs
src/transform/src/analysis.rs
src/transform/tests/test_transforms/column_names.spec
src/transform/tests/test_transforms/humanized_exprs.spec
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
test/sqllogictest/explain/physical_plan_as_text.slt
test/sqllogictest/explain/physical_plan_as_text_redacted.slt
test/sqllogictest/filter-pushdown.slt
test/sqllogictest/ldbc_bi.slt
test/sqllogictest/ldbc_bi_eager.slt
test/sqllogictest/limit.slt
test/sqllogictest/outer_join_lowering.slt
test/sqllogictest/tpch_create_index.slt
test/sqllogictest/tpch_create_materialized_view.slt
test/sqllogictest/tpch_select.slt
test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt

This brings the following minor improvements to MIR-based `EXPLAIN` output:
- Infer aggregate function names—we now infer names for columns that bind to aggregate computations in `Reduce` operators based on the aggregate function.
- Humanize `Project` lists—the project columns now appear in humanized `#c{name}` form. We still abbreviate runs of more then three successive columns, though.
These minor suggestions came during a face-to-face discussion.
Should be straight-forward to review.

explain: minor fixes

---

src/ore/src/vec.rs

This commit adds the `#[must_use]` annotation to the `drain_filter_swapping` function. `drain_filter_swapping` is evaluated lazily, so if the result is not used then it has no effect, and it is almost certainly a mistake. The annotation helps avoid this mistake by emitting a compiler warning.

ore: Add must_use to drain_filter_swapping

---

doc/user/assets/sass/_layout.scss
doc/user/layouts/_default/baseof.html
doc/user/layouts/shortcodes/fnlist.html

Also swapping the &lt;p> for a &lt;div>, which should fix Algolia's scraping of function names.
- n/a

doc/user: add anchor links to functions in docs

---

src/txn-wal/src/lib.rs

This commits adds more tests that test the snapshot functionality directly.
Touches #22173
Adds tests

txn-wal: Add more snapshot tests

---

src/compute/src/render/top_k.rs

Push negation in `build_topk_negated_stage` down into reducer.
This PR refactors existing code. The negation was being performed at a higher level, so that more work was done than necessary.
-

push top_k negations down into reducer

---

Cargo.lock
src/clusterd/src/bin/clusterd.rs
src/service/Cargo.toml
src/service/src/grpc.rs
test/cluster/mzcompose.py

This will make it possible to write an alert to detect clusters that haven't heard from envd in a while, like we saw in MaterializeInc/incidents-and-escalations#28. Envd should be continually chatting with all clusters via the compute protocol, so any stall in communication is usually indicative of a severe problem.
- n/a

clusterd: add metric for receipt of last envd command

---

src/compute/src/render.rs
src/compute/src/sink/persist_sink.rs
src/persist-client/src/operators/shard_source.rs
src/storage-operators/src/persist_source.rs
src/storage/src/render/sinks.rs
src/storage/src/render/sources.rs
src/txn-wal/src/operator.rs

storage,persist: allow callers of persist_source to handle "cannot serve..." errors
Partially fixes #19097
Most callers will panic, as before, but they now include their purpose
in the panic message.
For storage sinks, we now trigger a graceful suspend-and-restart, which
will get rid of at least one scenario where we previously were seeing
this panic in CI.
The machanism of the panic for sinks was:
1. We create the source/sink, sending render commands to the cluster.
2. Cluster does not start rendering yet, for reasons… delays and
whatnot.
3. We drop the database which immediately drops the source/sinks,
releases critical since handles and the like.
4. **Now the cluster wakes up and tries to render the sink. This fails
with a panic!**
With this fix, we would trigger a suspend-and-restart …

storage,persist: allow callers of persist_source to handle "cannot serve..." errors

---

test/testdrive/catalog.td

This addresses 
> Issue is referenced in comment but already closed: [#19097](https://github.com/MaterializeInc/materialize/issues/19097)
test/testdrive/catalog.td:313:
> \# TODO: Remove skip when #19097 is fixed
in https://buildkite.com/materialize/nightly/builds/7919#018fc420-c542-4ca7-b809-be9eeaa98bbd.

tests: enable and adjust catalog.td

---

src/compute/src/server.rs
src/persist-client/src/internal/metrics.rs
test/cluster/mzcompose.py

The `SinkMetrics::update_sink_correction_peak_metrics` method assumed "quiescence", i.e. the temporary ceasing of updates to sink metrics while it was executing. While the method was correct under that assumption, the calling code unfortunately was not able to uphold it. Specifically, `step_or_park` is invoked per worker, so when `update_sink_correction_peak_metrics` is invoked it can only assume that the current worker won't update the sink metrics, but it cannot assume anything about other workers.
As a result of the violated assumption, "Negative aggregate length for persist sink correction" could be logged even when nothing was actually wrong with the persist sink implementation.
This is solved here by removing the problematic peak metrics entirely. Stopping all workers regularly to …

persist-client: remove sink_correction_peak metrics

---

misc/python/materialize/cloudtest/util/kubectl.py

Add kubectl apply func for use in tests that need to make server-side changes.
-

kubectl util: add server-side apply

---

src/repr/Cargo.toml
src/repr/benches/packed.rs
src/repr/src/adt/datetime.rs
src/repr/src/adt/interval.rs
src/repr/src/scalar.rs

This PR implements "packed" encodings for `Interval` and `Time` that will be used for writing structured data in Persist.
The packed encodings are designed to be as fast as possible and have the same sort order as the original types. They're based on discussion from https://github.com/MaterializeInc/materialize/pull/26175. I added benchmarks that measure throughput and locally I get the following results:
type    | encode              | decode
---------|---------------------|--------
interval | ~1.5 billion/second | ~1.6 billion/second
time     | ~2.5 billion/second | ~1.3 billion/second
I believe the implementations can be optimized further with SIMD, but right now that requires `inline_asm!` or the `Nightly` compiler.
Note: The code placement feels a bit weird since these impls should …

persist: "packed" encodings for `Interval` and `Time`

---

doc/user/content/ingest-data/redpanda-cloud.md

Update references to the Redpanda API to efectively use the latest and greates Redpanda cloud API version
Simply want to ensure the latest and greatest version of Redpanda Cloud API is being used.
- Removed references to NAMESPACE since it's not necessary for the calls 
- Update to version v1beta2 in tha reference, the spec was updated accordingly.
-

docs: update Redpanda cloud api version ref

---

src/transform/src/analysis.rs
test/sqllogictest/cardinality.slt

The `Analysis` framework reveals the results of expression children as part of the ongoing derivation, but this means that information about non-children may not be available, and in particular information about future bindings in a `LetRec` are not available. This means that implementors must themselves guard against out-of-bounds access based on these identifiers, using e.g. `results.get(id)` rather than `results[id]`.
There seemed to be only one instance of this, in our cardinality computation. It seems localized to `Get` expression handling.
-

Guard access to analysis results

---

misc/python/materialize/buildkite_insights/annotation_search/README.md
misc/python/materialize/buildkite_insights/annotation_search/annotation_search.py
misc/python/materialize/buildkite_insights/annotation_search/annotation_search_presentation.py
misc/python/materialize/buildkite_insights/artifact_search/artifact_search_presentation.py
misc/python/materialize/buildkite_insights/util/search_utility.py

Helpful to concisely filter matches.
```
Match in build #7887 (pipeline nightly on main):
URL: https://buildkite.com/materialize/nightly/builds/7887
Annotation: Feature benchmark against merge base or 'latest' 3 (#2)
----------
Failure in Scenario 'FullOuterJoin': New regression against v0.101.0
-------------------------------------------------------------------------------------
Match in build #7862 (pipeline nightly on v0.101.0):
URL: https://buildkite.com/materialize/nightly/builds/7862
Annotation: Feature benchmark against merge base or 'latest' 1
----------
Failure in Scenario 'FastPathLimit': New regression against v0.100.1
-------------------------------------------------------------------------------------
Match in build #7862 (pipeline nightly on v0.101.0):
URL: …
```

buildkite search: single line result

---

src/persist-types/src/columnar.rs
src/repr/benches/packed.rs
src/repr/src/adt/datetime.rs
src/repr/src/adt/interval.rs
src/repr/src/adt/mz_acl_item.rs

This PR does a few things:
1. Introduces a `ColumnarCodec` trait that is defines how to encode a type `T` so it can be durably persisted in an `arrow::array::FixedSizeBinaryArray`.
2. Refactors the impls of `PackedInterval` and `PackedNaiveTime` (introduced in https://github.com/MaterializeInc/materialize/pull/27336) to use `ColumnarCodec`.
3. Add `PackedAclItem` and `PackedMzAclItem` which implement `ColumnarCodec`
4. Refactor existing and add more benchmarks to measure the throughput of encoding and decoding for all of the "packed" types vs the existing `ProtoDatum` types.
The existing benchmarks have been reworked a bit to include encoding into an existing buffer and reading from a slice. Also included are benchmarks for the same workflow but using the existing protobuf types, since …

persist: add `trait ColumnarCodec` and "packed" encodings for `AclType` and `MzAclType`

---

src/persist-types/src/codec_impls.rs
src/persist-types/src/parquet.rs
src/repr/src/row/encoding.rs
src/storage-types/src/sources.rs

Currently for a few non-nullable columnar types we assert that there are no nulls when reading from the column. This fails when roundtripping through Parquet with batch of `SourceData` that contains both `Ok` and `Err` values. When deserializing, Parquet appears to set the validity bitmap for child arrays to the validity bitmap of the top-level `StructArray`. For `SourceData` when there is an `Err` value we set the corresponding entry in the `Ok` column to null. This then results in those non-nullable columns, within `Ok`, having nulls.
Nothing in production, including our stats handling, roundtrips structured data through Parquet. The existing `parquet::validate_roundtrip` helper creates batches of size 1, so we never exercise the scenario of an `Err` and `Ok` in the same batch. I …

persist: Don't assert the `logical_nulls` are `None` for non-nullable columns

---

misc/python/materialize/cli/ci_annotate_errors.py

This is a follow-up to https://github.com/MaterializeInc/materialize/pull/27120 to also capture such entries
```
Summary [2929.930s] 393 tests run: 392 passed, 1 timed out, 307 skipped
TIMEOUT [2400.058s] mz-repr adt::mz_acl_item::proptest_packed_mz_acl_item_sorts
error: test run failed
```
as seen in https://buildkite.com/materialize/nightly/builds/7933#018fcd39-ec86-432e-8839-2f0cb382681a.
Nightly: https://buildkite.com/materialize/nightly/builds/7936

ci: improve annotating failed miri test cases

---

src/repr/src/adt/mz_acl_item.rs

Disabling this test for now. To be fixed with https://github.com/MaterializeInc/materialize/issues/27370.

tests: ignore proptest_packed_mz_acl_item_sorts

---

src/adapter/src/catalog/state.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner.rs
src/catalog/src/memory/objects.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/storage-controller/src/lib.rs
src/storage-types/src/sinks.proto
src/storage-types/src/sinks.rs
src/storage/src/sink/kafka.rs
src/storage/src/source/reclock.rs
test/testdrive/kafka-sinks.td

This is the first part of implementing `ALTER SINK`. As @bkirwi pointed out in the design doc the implementation of `ALTER SINK` needs to defend against a zombie cluster attempting to resume sinking a collection on an older sink version. In order to accomplish this this PR adds a `version` field to the sink metadata stored in the catalog which is threaded all the way to the sink timely operator in `clusterd`. The intention is to bump the version counter up every time a sink is altered.
The way this version fencing works is by piggybacking on the pre-existing frontier fencing mechanism. Namely, we extend the metadata that is written to the progress topic to be not just the frontier up to which we've written, but also the version of the sink that did those writes. On startup, each sinks …

storage: wire up a sink version to be recorded in the progress topic

---

src/expr/src/scalar.proto
src/expr/src/scalar.rs
src/expr/src/scalar/func.rs
test/sqllogictest/mzcompose.py
test/sqllogictest/regex.slt

Mirroring the `regexp_match` sql function, this PR pre-processes static regexes for `regexp_replace`.
Fixes #22172 
The `Regex` object is now constructed from their string representation only once when possible, instead of constructing the same object repeatedly across multiple rows.
- The implementation follows the style of `regexp_match`, except we need a binary function here.
- Because of the `g` flag, we need to carry around an extra integer. I created a new proto object `ProtoRegexReplace` to be able to represent this.
- I've extended the tests to ensure the fast and slow paths are taken appropriately. 
-

sql: optimize regexp_replace for static regexes

---

ci/nightly/pipeline.template.yml

Now that we've added the Rust setup for Bazel, the nightly test job will break whenever someone updates the dependencies of a crate in our workspace because we're not re-pinning Bazel's Rust dependencies. We've gotten enough signal from CI that the Bazel caching works, so for now I'm opting to disable the Bazel test target until the auto-gen of BUILD.bazel files merges to prevent Nightly from being unnecessarily red.
Make nightly green
- N/a

bazel: Disable nightly test target

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.103.0-dev

---

src/persist-client/src/operators/shard_source.rs
src/storage-operators/src/persist_source.rs
src/storage-types/src/dyncfgs.rs
src/storage/src/render/sinks.rs
src/storage/src/render/sources.rs

This PR attempts to strike a balance between getting a useful signal out of invariant violations and reducing false positive rates. When a source attempts to rehydrate on a cluster that has been dropped there is the possibility that it panics before we have a chance to shut the process down. This PR adds a grace period such that the panic is suppressed if the to-be-dropped cluster is actually dropped within a reasonable time frame. If a cluster is still alive after the grace period then the panic happens as usual and will be reported in the usual places.
-

storage: delay panics by a cluster shutdown grace period

---

test/sqllogictest/regex.slt

(It happened due to https://github.com/MaterializeInc/materialize/pull/27300 adding some tests with EXPLAIN plans and at the same time https://github.com/MaterializeInc/materialize/pull/27332 enhancing EXPLAIN plans.)
Fixes minor merge skew in tests.
-

Fix merge skew in regex.slt

---

doc/user/layouts/partials/head.html

By default, segment looks at localstorage first, which doesn't cross subdomains. This causes the logged in user ID from console to be overwritten in some cases. Instead, we will look at cookies first and fall back to localstorage if the cookie is not set.
https://materializeinc.slack.com/archives/C06GZ7GBKB5/p1717091663493629

docs: segment uses cookies for storage

---

.config/nextest.toml

Also remove outdated threads=8 we probably don't need anymore. They were originally required because of CRDB contention which should be fixed by now. (But I will verify: https://buildkite.com/materialize/nightly/builds/7946)
Failure seen in https://buildkite.com/materialize/test/builds/83013
-

unit tests: Wait longer for all_datums_parquet_roundtrip

---

misc/python/materialize/checks/all_checks/materialized_views.py

Since this scenario runs the verification code in an older version
Started failing with https://github.com/MaterializeInc/materialize/pull/27332
Seen in https://buildkite.com/materialize/nightly/builds/7940#018fcfbd-0d5c-48d8-abe8-415277ea161a
Test run: https://buildkite.com/materialize/nightly/builds/7948
-

platform-checks: Fix MV explain in preflight rollback scenario

---

test/kafka-rtr/simple/verify-rtr.td

See https://github.com/MaterializeInc/materialize/issues/27393
-

tests: Temporarily disable failing Kafka RTR test

---

src/controller/src/lib.rs
src/storage-client/src/controller.rs
src/storage-client/src/storage_collections.rs
src/storage-controller/src/lib.rs

This will make it easier to share a StorageCollections within a process.
-

storage: Arc-ify StorageCollections

---

misc/bazel/c_deps/repositories.bzl
misc/bazel/c_deps/rust-sys/BUILD.protobuf-native.bazel
misc/bazel/rules/rust_cxx_bridge.bzl

This PR updates the `rust_cxx_bridge` macro and the additive build file for `protobuf-native` so it all works.
When building the higher level `sql` crate which depends on `protobuf-native` we hit linking errors because the generated `cxx` bindings for protobuf-native were not correctly depending on one another. Specifically the `io.cc`, `compiler.cc`, and `lib.cc` files all depend on `internal.cc`, we need to make sure we include the `cxx` generated `internal.h.rs` and `internal.c.rs` files for these targets.
It also updates the version of `protobuf` that we're using so it's the same as the `protobuf-src` Rust crate.
- N/a

bazel: Update `rust_cxx_bridge` and `protobuf-native` build

---

Cargo.lock
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
src/ore/Cargo.toml
src/repr/Cargo.toml

This PR updates the `compact_bytes` dependency to `v0.1.2` to pickup this PR https://github.com/ParkMyCar/compact_bytes/pull/2.
@antiguru noticed when looking at some profiles that the call to `ComapctBytes::extend_from_slice(...)` was not getting inlined. While inlining is a relatively small performance gain, `extend_from_slice(...)` is an extremely hot code path so even a small improvement here could be nice.
-

.*: Upgrade `compact_bytes` to  `v0.1.2`

---

src/storage/src/metrics/source.rs
src/storage/src/source/reclock.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs
src/storage/src/storage_state/async_storage_worker.rs

With the new reclock implementation now merged, this PR integrates it into the ingestion pipeline and deletes the old one
-

storage: wire up new reclock implementation

---

Cargo.lock
Cargo.toml
MODULE.bazel.lock
WORKSPACE
misc/bazel/Cargo.crates_io.lock
misc/bazel/rust_deps/BUILD.bazel
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml

The `launchdarkly-server-sdk` crate depends on [`built`](https://github.com/lukaslueg/built) to get some info about the current crate, which in turn requires a few environment variables to be set. Ideally the `cargo_build_script` rules would already be setting these, I made an issue for that: https://github.com/bazelbuild/rules_rust/issues/2677
Note: we also need to upgrade the version of `built`, which is done in this PR https://github.com/MaterializeInc/rust-server-sdk/pull/6
Build `launchdarkly-server-sdk` with Bazel
-

bazel: Set a few env variables for `launchdarkly-server-sdk`

---

src/storage/src/source/reclock/compat.rs
src/storage/src/storage_state/async_storage_worker.rs

- Choose the "as-of" for the source as a function of the output uppers, not the input since. (While the since is normally in advance of the uppers, this does not appear to be the case when the source is being created or shutting down.)
- This is morally similar to how the controller places advances its read holds on upstream collections based on the progress of the upper in downstream collections.
- When we open a read handle for a shard, start from whatever since is available. (And take care to ensure that we don't expose any insufficiently-advanced data to downstreams.)
For: #26940.
The previous code depends on brittle details of the way that the since is chosen, including leaking a handle briefly to temporarily prevent compaction. The result is... still brittle, frankly; but it's …

[persist/sources] Choose a resumption frontier in the source based on the output upper, not the input since

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/controller-types/src/lib.rs
src/controller/src/lib.rs
src/ore/src/id_gen.rs

The adapter currently installs watchsets in the controller but they are only removed if they finish. If a watchset is installed on a collection whose upper is stuck (e.g a failing source) then we will eventually timeout the connection (or the user will abort it) and leak the installed watchset for the remaining lifetime of the process (or until the source gets unstuck).
This PR adds the ability to cancel a pending watchset and wires up the coordinator to automatically cancel pending watchsets when a connection is terminated or cancelled.
-

adapter: per connection watchset tracking and cancellation

---

src/ore/src/vec.rs

Followup to dbecc3cf78d5cc6ebfd6ac64e3815e529365d7e9 that adds documentation explaining why the `#[must_use]` exists.

ore: Update docs for drain_filter_swapping

---

misc/python/materialize/parallel_workload/action.py

Even in DML workloads it can happen, see https://buildkite.com/materialize/nightly/builds/7961#018fe071-6fd9-476c-9e57-e153435bd12d
-

parallel-workload: Ignore result size error

---

misc/python/materialize/parallel_workload/executor.py

Seen in https://buildkite.com/materialize/nightly/builds/7954#018fddde-545e-43d0-aaa0-22ac6a8f8378
-

parallel-workload: Query result can be ok and error at once

---

doc/user/content/serve-results/s3.md

We got some great feedback from one of our early testers that the placeholders in our documentation were not sufficiently obvious.
Also correct the step numbering.
- n/a

doc/user: make placeholders more obvious in COPY TO S3 docs

---

misc/scratch/provision.bash

This is needed for aarch64 instances (but I don't know why).
This fixes https://github.com/MaterializeInc/materialize/issues/26052.

scratch: install python3-dev

---

misc/python/materialize/checks/all_checks/aws.py
misc/python/materialize/checks/all_checks/copy_to_s3.py
misc/python/materialize/mzcompose/__init__.py
src/environmentd/tests/pgwire.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars/definitions.rs
test/aws-localstack/aws-connection/aws-connection.td
test/aws-localstack/copy-to-s3/copy-to-s3.td
test/aws/mzcompose.py
test/copy-to-s3/http/setup.td
test/copy-to-s3/nightly/setup.td
test/copy-to-s3/s3-auth-checks.td
test/sqllogictest/default_privileges.slt
test/testdrive/copy-to-s3-minio.td

Fixes https://github.com/MaterializeInc/materialize/issues/27404
AWS Connections are now in PuPr
-

Remove AWS connections LD flag

---

misc/python/materialize/version_ancestor_overrides.py
test/feature-benchmark/mzcompose.py

I anticipated that we might need this for the feature benchmark running in the release-qualification pipeline.

feature benchmark: provide scale to ancestor overrides

---

misc/python/materialize/mz_env_util.py
test/canary-load/mzcompose.py

Needed for https://github.com/MaterializeInc/materialize/pull/27432.
c80a668e89 test: utils: add get_cloud_hostname
2872b5671c canary-load: use get_cloud_hostname from utils
444f9ce10d canary-load: remove composition override
34af5bb3ba canary-load: fix
Please advise whether 444f9ce10d is valid or whether this change needs to be reverted.

test utils: host name for cloud-env connection

---

src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs

storage: Remove unnecessary mut

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/state.rs

Previously, the enable_storage_shard_finalization flag controlled whether we stored newly deleted but unfinalized shards in the in-memory catalog. When the flag was disabled, we would not store them in memory. This could cause the on-disk catalog state to diverge from the in-memory catalog state which is confusing. Additionally, there are some parts of the code that assume that if a shard is missing from the in-memory catalog, it must have been finalized. There is a careful but fragile dance in the code that prevents leaking shards when enable_storage_shard_finalization is off. Furthermore, on startup all unfinalized shards are loaded into the in-memory catalog regardless of the flag.
This commit simplifies the code by always storing unfinalized shards in the in-memory catalog.
Maybe but …

catalog: Always store unfinalized shards

---

src/sql/src/plan/statement/dml.rs
test/testdrive/copy-to-s3-minio.td

These were being silently ignored.
- n/a

sql: support cvs format options in copy-to-s3

---

src/sql/src/plan/statement/dml.rs
test/testdrive/copy-to-s3-minio.td

* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/27101
This leaves the default as TEXT for all other COPY statements, but requires the FORMAT option is provided for the copy-to-expr statement.
-

storage/copy-to-s3: Require format option

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

See https://github.com/MaterializeInc/materialize/issues/27457
-

postgres-inconsistency test: Ignore array order

---

ci/plugins/mzcompose/hooks/post-command

Fixes: https://github.com/MaterializeInc/materialize/issues/26957
Demo: https://buildkite.com/materialize/coverage/builds/421
-

coverage: Improve profraw corruption workarounds

---

src/adapter/src/catalog/apply.rs
src/adapter/src/coord/indexes.rs
src/catalog/src/memory/objects.rs
src/compute-client/src/logging.rs

This PR removes `DEFAULT_LOG_VARIANTS` and `Log::has_storage_collection`, two pieces of code related to compute introspection that are not used anymore.
- N/A

compute-client: remove unused code

---

src/adapter/src/coord/sequencer/inner.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/mysql.rs
src/storage-types/src/sources/mysql.rs
test/mysql-cdc/alter-source.td
test/mysql-cdc/mysql-cdc.td

Fixes https://github.com/MaterializeInc/materialize/issues/24975
Enables the `ALTER SOURCE .. ADD SUBSOURCE` statement and `DROP SOURCE <subsource>` for MySQL Sources, with equivalent semantics to the Postgres Source (except MySQL also supports the `IGNORE COLUMNS` option in addition to `TEXT COLUMNS`).
- Would recommend reviewing with whitespace removed.
- 2 of the commits are just refactors to allow the purification & sequencing of `ALTER SOURCE` statements to allow more than just Postgres sources.
- The `Implement purification for mysql alter source` commit has a large diff since I moved most of the mysql-specific subsource purification logic to a common method that can be shared between create & alter source.
-

storage/mysql: ALTER SOURCE for MySQL Sources

---

about.toml
deny.toml

This PR adds the `Apache 2.0 WITH LLVM-exception` and `Unicode-DFS-2016` licenses as accepted. @benesch took an initial look and it should be fine to add these, waiting on a final stamp from legal before merging.
https://github.com/MaterializeInc/materialize/pull/27346 adds transitive dependencies with these licenses.
- N/a

.*: Add `Apache 2.0 WITH LLVM-exception` and `Unicode-DFS-2016` licenses as accepted

---

src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/gc.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/internal/state_diff.rs
src/persist-client/src/internal/state_versions.rs
src/persist-client/src/iter.rs
src/persist-client/src/read.rs
src/persist-client/src/usage.rs

Refactorings in support of a prototype for: https://github.com/MaterializeInc/materialize/issues/26939
We're setting that aside temporarily (hit the timebox) but I think these changes are either mildly positive or neutral, so I'm hoping to land them soon and avoid some bitrot.
I've outlined the reasoning in the commit messages, but let me know if you have questions!
-

[persist] Refactorings to support bounded state size

---

src/cloud-resources/Cargo.toml
src/orchestrator-kubernetes/Cargo.toml
src/workspace-hack/Cargo.toml

bump k8s-openapi feature to v1_28
We're upgrading the k8s clusters to kubernetes 1.28, so we should update our clients to match.
I tried also updating the kube and k8s-openapi versions, but that pulled in a new tokio, which has a new method on their mpsc channels which conflicts with an extension we made to add a method with the same name (`recv_many`). This is sufficient for now, but we should upgrade tokio and switch to their method eventually.
- Not a release blocker, but we'll need to update the cloud Cargo.toml files the same way when updating the submodule. That PR will come after this is merged, as we don't know the commit to bump the submodule to until then.
- No user-facing behavior changes.

bump k8s-openapi feature to v1_28

---

test/sqllogictest/mztimestamp.slt

Seen in https://buildkite.com/materialize/slt/builds/5947#018fe8ed-2cb6-4002-bd45-e7911dc7d916
Necessary because with --auto-index-selects the error message prefix is different.
-

slt: Fix mztimestamp conversion errors

---

misc/python/materialize/data_ingest/data_type.py
misc/python/materialize/data_ingest/executor.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py

Verification: https://buildkite.com/materialize/nightly/builds/7983
-

data-ingest/parallel-workload: Support more Mz types

---

doc/developer/guide-changes.md

See also https://materializeinc.slack.com/archives/CQY8LN96Y/p1713536183221339
-

dev docs: Encourage git pushfwl

---

test/kafka-rtr/simple/verify-rtr.td

Based on discussion in
https://github.com/MaterializeInc/materialize/issues/27393 there seems to be no product issue.
The transaction's first SELECT will determine the timestamp for the rest of the transaction, so we have to run the ingestions before that. The SELECT+FETCH pattern is not useful at all.
Fixes: https://github.com/MaterializeInc/materialize/issues/27393
-

kafka-rtr test: Fix up verification

---

src/adapter/src/command.rs
src/adapter/src/coord.rs
src/adapter/src/coord/catalog_serving.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/error.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/rbac.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
src/testdrive/src/action/sql.rs
test/testdrive/alter-sink.td

The implementation of `ALTER SINK` as described in the [design document here](https://www.notion.so/materialize/ALTER-SINK-MVP-ffa7e969830a49eb979043510425e3b0).
`ALTER SINK` currently only supports swapping out the relation the sink is reading from. Every other detail of the sink (envelope, format, etc) stays the same and must be compatible with the new relation. Here compatible means that a `CREATE SINK` statement would have succeeded had it be submitted with the new `FROM` collection. This is precisely how the planner chooses to plan an `ALTER SINK` as well. It generates the equivalent `CREATE SINK` statement where all but the from collection is the same and if that plans successfully we move ahead.
After we obtain an `ALTER SINK` plan successfully the coordinator takes a read hold on …

adapter: implement alter sink

---

misc/mzexplore/variadic_outer_joins.jq

Takes `bin/mzexplore --explainee-type catalog_item --stage raw_plan --format json` output and produces a per-file summary of innner/left-join stack sizes and predicate types.
Per compute discussion today.
After extracting raw plans in JSON, run:
```ShellSession
$ find /path/to/extracted/data -name \*.json | xargs jq -f variadic_outer_joins.jq
```
I'm not certain I correctly characterized complex equalities.
I'm using `level` as a proxy for "local column" but I'm not certain that's correct, either.
I only identify left-stacked joins... will be build more complex ones?
-

mzexplore: analysis of variadic outer joins

---

misc/python/materialize/version_ancestor_overrides.py
src/timely-util/src/reclock.rs

The current version of the reclock operator maintains a stash vector whose capacity only ratchets upwards as it's being used. This means that if the operator processes a spike of input the memory of that vector will spike too and will never be reclaimed.
This PR recycles the stash buffer every time the operator gets scheduled. A more complicated buffer management strategy might need to be considered in the future but for now all benchmarks seem happy with this change.
Fixes #27425
-

timely-util: reclaim memory used for stash vec

---

test/kafka-rtr/simple/verify-rtr.td

Real time recency does not play well with interactive transactions where the system must commit to a timestamp to run statements at upfront but the set of sources on which the user intends to run queries on is revealed as the queries come in.
If a source that was not known at the time of the first query of a transaction is used in a subsequent query we have two options:
1. Run RTR and continue with the transaction if the timestamp we have already committed to is compatible (i.e contains all upstream changes)
2. Ignore RTR completely and run all queries at the timestamp determined in the beginning of the transaction.
Materialize currently does option 2, which may be surprising to users that have RTR enabled. We should think about whether option 1 would be preferable from a product …

RTR is not guaranteed in transactions

---

misc/python/materialize/output_consistency/expression/expression.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This
* fixes https://buildkite.com/materialize/nightly/builds/7998#018fe974-4dab-4ed1-9001-7edbc2eee8fb
* improves other ignores
* adds likely needed additional ignores
As for the build failure with expression `(coalesce(right(varchar_8_val_2, int4_max)) < varchar_8_val_w_spaces)`, the ignore pattern for `TEXT < TEXT` was present but did not match because the first argument (`coalesce`) resolved to `DynamicReturnTypeSpec` while the filter was working on `StringReturnTypeSpec`.
2bbce31225 postgres consistency: improve ignore to work properly with types only known at runtime
8578912c54 postgres consistency: extend ignore to also apply on less accurate type information
d63d41950c postgres consistency: rework other ignore
562001b20d postgres consistency: add likely needed ignores
b24e3d3886 …

postgres consistency: improve ignores, add likely needed ones

---

misc/python/materialize/cli/ci_annotate_errors.py

This must not cause the build fail, in particular in the test pipeline.

ci: annotate errors: uploading build results should not cause the build to fail

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner.rs
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/ddl/connection.rs
src/sql/src/rbac.rs
src/storage-types/src/connections.proto
src/storage-types/src/connections.rs

Previously, SSH connection public keys were stored in memory in the
`CatalogState` struct. However, this information is not stored durably
in the durable catalog. The actual source of truth is an opaque
`SecretsController`. This presents a challenge for having a
multi-subscriber catalog that listens to durable updates. The catalog
has no way of learning about changes to the public keys. The in-memory
public keys will likely become inconsistent after any changes and
present incorrect information to anyone subscribing to the catalog.
This commit fixes the above issue by removing the public keys from
the `CatalogState` struct.
An alternative, and possibly better, approach would be to store the
public keys in the durable catalog directly. Unfortunately, the
public keys are owned by …

catalog: Remove public key from catalog state

---

Cargo.lock
misc/cargo-vet/audits.toml
src/storage/Cargo.toml
src/storage/src/upsert/types.rs
test/upsert/mzcompose.py

Follow up improvement to #27064 - this uses https://docs.rs/serde_bytes/latest/serde_bytes/ to improve serialization performance of the snapshot state in the upsert operator. The merge operator added for RocksDB uses this implicitly when values are serialized using https://docs.rs/bincode/latest/bincode/ when written to and read from RocksDB.
I also discovered and fixed the upsert load generator mzcompose workflow, and ran a few test cases to do a rough performance test:
```
***On present main:***
repeat = 100 * 1024
updates_count = 20
Scenario default took [datetime.timedelta(seconds=11, microseconds=774000)] ms
Scenario RocksDB Merge Operator took [datetime.timedelta(seconds=11, microseconds=112000)] ms
***On this branch:***
repeat = 100 * 1024
updates_count = 20
Scenario default took …
```

storage/upsert: improve perf of upsert merge operator for rocksdb

---

src/storage/src/metrics/source.rs
src/storage/src/source/reclock.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs
src/storage/src/storage_state/async_storage_worker.rs

#27058 is the most likely culprit for the issues we're seeing in #27455, so better to revert it and investigate the failures off the critical path.
-

revert "storage: wire up new reclock implementation"

---

.github/CODEOWNERS

Replace @MaterializeInc/compute and @MaterializeInc/storage with @MaterializeInc/cluster.

codeowners: cluster team replaces compute and storage

---

src/adapter/src/catalog/transact.rs

This commit extracts the logic for processing a single Op in a catalog transaction to a separate method. This is pure code movement.
- Hide white-space when reviewing.

catalog: Extract transact op method

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.104.0-dev

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/state.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/coord.rs
src/adapter/src/coord/consistency.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/catalog/src/memory/objects.rs

Previously, cluster replica statuses were stored in memory in the
`CatalogState` struct. However, this information is not stored durably
in the durable catalog, it's ephemeral information. This presents a
challenge for having a multi-subscriber catalog that listens to durable
updates. The catalog has no way of learning about changes to the
replica statuses. The in-memory statuses will likely become
inconsistent after any changes and present incorrect information to
anyone subscribing to the catalog.
This commit fixes the above issue by removing the statuses from
the `CatalogState` struct and moving to to the `Coordinator`. These
statuses are only used in two places:
1. In the `Coordinator` when processing cluster status update
messages.
2. To update the builtin table …

catalog: Remove replica statuses from state

---

Cargo.lock
misc/bazel/cargo-gazelle/Cargo.toml

Unused dependency
Seen in https://buildkite.com/materialize/nightly/builds/8007#018fed53-d15a-491e-9ab3-951a87d41c46
-

bazel build: Remove insta dev dependency

---

src/environmentd/tests/server.rs

As reported in https://materializeinc.slack.com/archives/C01LKF361MZ/p1717407989364929 Seen in https://buildkite.com/materialize/test/builds/83039
I'd be happier with a not-time-dependent way of testing this @parkmycar any ideas?
-

cargo test: Bump timeouts in test_webhook_source_batch_interval

---

test/testdrive/alter-sink.td

testdrive: Retry alter sink test for longer

---

misc/python/materialize/data_ingest/data_type.py

Seen failing in https://buildkite.com/materialize/nightly/builds/8015#018fef49-ff6e-4092-a643-d54fe45bdfc6
-

data-ingest: Ignore NUMERIC(38,3) type in Kafka comparisons

---

misc/python/materialize/version_ancestor_overrides.py

See https://github.com/MaterializeInc/materialize/issues/27478
-

feature-benchmark: Ignore MySqlInitialLoad regression

---

test/mysql-cdc-resumption/alter-mz.td
test/mysql-cdc-resumption/mzcompose.py
test/mysql-cdc-resumption/verify-data.td
test/mysql-cdc/alter-column-irrelevant.td

Since #24975 landed: https://buildkite.com/materialize/nightly/builds/7998#018fe974-4cd3-4db0-bcaa-61f44cbaff61
-

mysql-cdc tests: Enable ALTER SOURCE depending scenarios

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/impl.py
misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_await.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_cleanup.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
misc/dbt-materialize/dbt/include/materialize/macros/utils/generate_cluster_name.sql

Fixes #27159
This PR introduces a couple of things:
* A new `generate_deploy_cluster_name` macro responsible for appending the `_dbt_deploy` suffix for the blue/green deployments.
* A new `generate_final_cluster_name` adapter method.
* Users can define their own `generate_cluster_name` macro in their dbt project to override the cluster name generation logic, like one that automatically prefixes each cluster with the target name:
```jinja
{% macro generate_cluster_name(custom_cluster_name, node) -%}
{%- set default_cluster = target.cluster -%}
{%- if custom_cluster_name is none -%}
{{ default_cluster }}
{%- else -%}
{{target.name}}_{{ custom_cluster_name }}
{%- endif -%}
{%- endmacro %}
```

dbt-materialize: support overriding generate_cluster_name

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/sql-parser/tests/testdata/explain
src/storage-client/src/storage_collections.rs
test/sqllogictest/explain/pushdown.slt
test/sqllogictest/materialized_views.slt

#24498
In particular, it can be helpful to see the statistics for an existing materialized view -- to know what the level of pushdown would be like if the view was re-bootstrapping now.
I think the diciest part of this PR is the timestamp selection code... please check my work!
-

[explain] Support materialized views in `explain filter pushdown`

---

.bazelrc
Cargo.lock
misc/bazel/cargo-gazelle/src/config.rs
misc/bazel/cargo-gazelle/src/lib.rs
misc/bazel/cargo-gazelle/src/targets.rs
src/storage-types/Cargo.toml

This PR adds the `env` field as a configuration `cargo-gazelle` can auto-generate, which allows us to set environment variables for test executions. It also sets the default `test_output` to `streamed`, which mimics what `cargo test` does.
Progress towards https://github.com/MaterializeInc/materialize/issues/27381
- N/a

bazel: Support setting `env` for `rust_test`

---

src/balancerd/tests/server.rs
src/environmentd/tests/auth.rs
src/environmentd/tests/server.rs
src/frontegg-mock/src/lib.rs
src/frontegg-mock/src/main.rs

Currently there are two Frontegg Mock services maintained, one written in Go which lives in the Terraform repo and one written in Rust which lives in the main Materialize repo.
As per the discussion [here](https://github.com/MaterializeInc/terraform-provider-materialize/issues/461), it will be nice to carry over the logic from the Go mock to the Rust mock and deprecate it so that we could only have 1 complete mock service.
This PR is mainly intended as a PoC and only transfers over the following endpoints:
```
/identity/resources/users/v1/{id}
/identity/resources/users/v2"
/identity/resources/roles/v2"
```
-

Frontegg mock additional user endpoints

---

src/adapter/src/catalog/open.rs
src/catalog/src/durable/transaction.rs

Previously the `get_op_updates` function in `Transaction` did not return updates for audit logs and storage usage events. This commit fixes that issue.

catalog: Fix get_op_updates transaction method

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/relation.py
misc/dbt-materialize/tests/adapter/test_empty.py

As per this bug [here](https://github.com/dbt-labs/dbt-adapters/issues/124), the `--empty` flag doesn't work with relation that are already named and fails.
A quick repro:
* Create a simple model with: `SELECT * FROM {{ ref('my_upstream_model')}} some_alias`
* The generated SQL when using the `--empty` flag, looks like this:
```sql
as (
SELECT * FROM (
select * from "my_upstream_model" where false limit 0) _dbt_limit_subq_my_upstream_model alias
);
```
-

dbt-materialize: Stop adding aliases to subqueries with --empty

---

test/testdrive/alter-sink.td

test: force redpanda to produce an incompatible schema error

---

src/adapter-types/src/dyncfgs.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/error.rs
src/environmentd/src/http.rs
src/environmentd/tests/server.rs
test/restart/mzcompose.py

Introduce a new `allow_user_sessions` feature flag which, when false, blocks new user sessions (i.e., sessions for users other than mz_support or mz_system).
This flag be used to prevent expired trials and churned customers from accessing their Materialize region.
Discussed on Slack here: https://materializeinc.slack.com/archives/CL68GT3AT/p1717655925489429
- n/a

adapter: allow blocking user sessions via feature flag

---

misc/python/materialize/test_analytics/setup/structures/01-base-tables.sql
misc/python/materialize/test_analytics/test_analytics_db.py

because
* we likely don't need semantic versioning
* it easens comparisons

test analytics: data version should be a number

---

src/storage-controller/src/lib.rs
src/storage-controller/src/rehydration.rs
src/storage/src/storage_state.rs

Now that we can identify subsource clusters, we should be sending them compaction commands.
The approach we take here is unfortunately circuitous.
- Ingestion exports don't have a storage dependency on the primary collection (though they have a catalog dependency), but the primary collection identifies which cluster the ingestion runs on.
- Because there is no storage dependency, the primary collection can be dropped before the ingestion exports. This means we lose the ability to look up the cluster using the storage controller's collection API.
- We cannot simply have the export depend on the primary source––it's possible that the primary source's since is too far advanced because we haven't previously asserted a dependency should exist. This would also be a short-lived dependency as …

storage: send pending compaction commands for subsources

---

Cargo.lock
ci/nightly/pipeline.template.yml
misc/python/materialize/mzcompose/services/materialized.py
src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/metrics.rs
src/compute-client/src/protocol.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute-client/src/protocol/history.rs
src/compute-types/src/dyncfgs.rs
src/compute/Cargo.toml
src/compute/src/compute_state.rs
src/compute/src/sink/persist_sink.rs
src/controller/src/lib.rs
src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/http.rs
src/environmentd/src/http/control.rs
src/environmentd/src/lib.rs
src/environmentd/src/test_util.rs
src/sqllogictest/src/runner.rs
test/read-only-cluster/mzcompose.py

A part of delivering https://github.com/MaterializeInc/materialize/issues/27406
> [!NOTE]  
> The orchestration via commandline flag and `CONTROLLER ALLOW WRITE` is for demonstration and during local development of zero-downtime related features. Later, with proper 0dt upgrades implemented, the coordinator would start the controller in read-only mode when doing an upgrade and decide when to take a controller out of read-only mode.
> 
> I think we can get a lot of mileage out of this command, though: we can use it to mock upgrade orchestration while we develop many of the other features required for the initial zero-downtime upgrades milestone.
First, start `envd` with controllers in read-only mod:
```
$ bin/environmentd --reset -- --read-only-controllers
```
Then, create a table, index, …

compute: add read-only mode for controller/clusters

---

ci/test/lint-main/checks/check-mzcompose-files.sh
misc/python/materialize/mz_env_util.py
misc/python/materialize/mzcompose/composition.py
test/get-cloud-hostname/README.md
test/get-cloud-hostname/mzcompose
test/get-cloud-hostname/mzcompose.py

This replaces parts of https://github.com/MaterializeInc/materialize/pull/27512.
This will be tested in https://github.com/MaterializeInc/materialize/pull/27514 through https://buildkite.com/materialize/test/builds?branch=nrainer-materialize%3Atest-analytics%2Fstore-build-annotations-demo (build is expected to fail but the question is whether annotate-stuff will succeed).

test utils: provide cloud hostname

---

misc/bazel/cargo-gazelle/src/bin/main.rs
misc/bazel/cargo-gazelle/src/config.rs
misc/bazel/cargo-gazelle/src/rules.rs
misc/bazel/cargo-gazelle/src/targets.rs

This PR adds support for auto-generating `rust_binary` rules in `cargo-gazelle`. 
Progress towards https://github.com/MaterializeInc/materialize/issues/27381
- N/a

bazel: Support `rust_binary` in cargo-gazelle

---

src/adapter/src/catalog/transact.rs

catalog: Remove unused result

---

src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/read_policy.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/clusters.rs
src/controller/src/lib.rs
src/storage-client/src/controller.rs

This PR removes the `ActiveComputeController` and `ActiveInstance` types which existed solely to wrap compute controller functionality that needs access to the storage controller.
Now that the shareable `StorageCollections` exists, the `ComputeController` and `Instance` types can each own an `Arc<StorageCollections>`, so the `activate` dance becomes unnecessary.
The only place where access to a `&mut StorageController` is still needed for now is when the `ComputeController` wants to record introspection updates. This is solved by passing a `&mut StorageController` into the `ComputeController::process` call and down to `record_introspection_updates`.
Apart from simplifying things this is also a precondition for moving the `Instance` controllers into their …

compute: remove `Active*` controller types

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sql.rs
src/catalog-debug/src/main.rs
src/catalog/src/memory/objects.rs

Previously, opening the catalog did the following two steps in order (among many other omitted steps):
1. Load in-memory state from durable state.
2. Generate builtin table updates from durable state.
Ideally these would be done at the same time; for each change to durable state we load it into memory and generate the corresponding builtin table update(s). It's much more obvious that the builtin table update(s) exactly reflect the durable change that caused it, instead of some other later durable change that overwrote the value (Note: builtin table updates are generated by looking at the in-memory catalog).
However, during startup there is a chicken and egg problem. We don't know what table to write to until we've loaded that table. For example when loading a schema, we don't know what …

catalog: Refactor builtin table update generation

---

Cargo.lock
misc/cargo-vet/config.toml
src/sql/Cargo.toml

This PR upgrades our `protobuf-native` dependency
Pull in https://github.com/MaterializeInc/rust-protobuf-native/pull/16 for Bazel
- N/a

.*: Upgrade `protobuf-native` dependency

---

misc/bazel/Cargo.crates_io.lock
misc/bazel/build-info/gen_rust_module.py
misc/bazel/cargo-gazelle/src/config.rs
misc/bazel/cargo-gazelle/src/targets.rs
misc/bazel/rust_deps/cxxbridge-cmd/Cargo.cxxbridge-cmd.lock
src/build-info/Cargo.toml
src/build-tools/Cargo.toml
src/frontegg-mock/Cargo.toml

Updates `cargo-gazelle`, the tool we use to auto generate `BUILD.bazel` files from `Cargo.toml`s to allow skipping generation of certain targets.
It also updates the Bazel test sizes of lib tests to `Medium` and integration tests to `Large`. FWIW the test size doesn't really matter for us at the moment, it comes into play when the tests get distributed over multiple workers.
Progress towards https://github.com/MaterializeInc/materialize/issues/27381
- N/a

bazel: Update `cargo-gazelle` to support skipping targets

---

src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/transaction.rs

Previously, the `DurableType` trait had two generic types, one for the key and one for the value. This often caused unconstrained type issues when using this trait that were annoying to work around. This commit fixes the issue by updating the trait to have associated types instead of generic types. This also matches the mental model of durable types nicely; for each types there's a single associated key and value.

catalog: Make DurableType more ergonomic

---

src/adapter/src/catalog/transact.rs
src/catalog/src/memory/objects.rs

catalog: Clean up unnecessary schema method

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs

This commit adds the enum `StateDiff` which describes all valid diffs that may accompany a catalog state update diff. Specifically those are 1 (`StateDiff::Addition`) and -1 (`StateDiff::Retraction`). The numeric diff is converted to a `StateDiff` as early as possible to help avoid constantly checking that the diff is valid.

catalog: Make diffs more ergonomic

---

doc/developer/testdrive.md
src/sqllogictest/src/runner.rs
src/testdrive/src/action.rs
src/testdrive/src/action/sql.rs
src/testdrive/src/bin/testdrive.rs
src/testdrive/src/lib.rs
src/testdrive/src/parser.rs

See also https://github.com/MaterializeInc/materialize/pull/6404 for previous attempt
Fixes: #17223
Only supports rewriting basic SQL commands. We'll have to see if
extending it beyond this is worth it. Some commands will be impossible
to rewrite of course.
Easy way to test is break something in get-started.td, then run: `cargo run --bin testdrive -- --default-max-tries 10 --rewrite-results test/testdrive/get-started.td`
-

Testdrive auto-rewriting

---

ci/nightly/pipeline.template.yml

Since the issue was closed
Seen in https://buildkite.com/materialize/nightly/builds/8058#019009a4-576f-4d0c-92f5-b3208346afc5
Verification in https://buildkite.com/materialize/nightly/builds/8060
-

ci: Disable automatic retries for k8s node recovery

---

src/balancerd/tests/server.rs
src/environmentd/src/http.rs
src/environmentd/tests/auth.rs
src/environmentd/tests/server.rs
src/frontegg-auth/src/auth.rs
src/frontegg-auth/src/error.rs
src/frontegg-auth/src/lib.rs
src/frontegg-mock/src/lib.rs
src/frontegg-mock/src/main.rs
src/mz/src/command/region.rs
src/mz/src/command/secret.rs
src/mz/src/command/sql.rs
src/mz/src/error.rs
src/mz/src/sql_client.rs

This commit teaches Materialize to authenticate service app passwords, as described in #20894.
Under the hood, a service app password is a tenant API token with the `user` claim set in its metadata. Authenticating with such an API token functions as a login to the specified user. To prevent impersonating Frontegg users, the `user` claim must not contain an `@` character.
Database privileges for service app passwords are managed by issuing the normal `GRANT` and `REVOKE` commands against the user associated with the app password.
Touches #20894.
* This PR adds (part of) a known-desirable feature.
- n/a (will write a dedicated changelog post when ready)

frontegg-auth: support service app passwords

---

misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/feature_benchmark/benchmark_versioning.py
misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py

Thanks to @bkirwi for noticing
Verification in https://buildkite.com/materialize/nightly/builds/8061
-

feature-benchmark: Reduce scale for ManySmallUpdates

---

src/compute-client/src/controller/instance.rs
src/compute-client/src/protocol/command.proto
src/compute-client/src/protocol/command.rs
src/compute-client/src/protocol/history.rs
src/compute/src/compute_state.rs

This PR fixes a bug in `ComputeCommandHistory::reduce`. It contained this code:
```rust
// Determine the required antichains to support live peeks;
let mut live_peek_frontiers = std::collections::BTreeMap::new();
for Peek {
target, timestamp, ..
} in live_peeks.values()
{
// Introduce `time` as a constraint on the `as_of` frontier of `id`.
live_peek_frontiers
.entry(target.id())
.or_insert_with(Antichain::new)
.insert(timestamp.clone());
}
```
`live_peek_frontiers` would then be used to hold back the as-ofs of `CreateDataflow` commands, to ensure that the peeks can be fulfilled by the respective created dataflows. The bug here is the missing differentiation between index peeks and persist peeks. Persist peeks are not reading from the compute dataflow with the same ID, but from the persist …

compute: prevent as-of regressions by persist peeks

---

src/compute-types/src/plan/join/delta_join.rs
src/repr/src/explain.rs
src/transform/src/dataflow.rs
test/sqllogictest/explain/optimized_plan_as_json.slt
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/ldbc_bi.slt
test/sqllogictest/ldbc_bi_eager.slt
test/sqllogictest/mzcompose.py
test/sqllogictest/tpch_create_index.slt
test/sqllogictest/tpch_create_materialized_view.slt
test/sqllogictest/tpch_select.slt

Fixes https://github.com/MaterializeInc/materialize/issues/27324: Now we figure out which of the arrangements on the first input of a Delta join we'll scan, and which we'll just do lookups into.
* This PR fixes a recognized bug: Fixes https://github.com/MaterializeInc/materialize/issues/27324
The first commit is just a minor test change, discussed [here](https://github.com/MaterializeInc/materialize/pull/27279#issuecomment-2129315229) with @nrainer-materialize.
-

Fix Delta join 1st input index usage annotation

---

doc/user/content/ingest-data/amazon-eventbridge.md
doc/user/content/ingest-data/hubspot.md
doc/user/content/ingest-data/rudderstack.md
doc/user/content/ingest-data/segment.md
doc/user/content/ingest-data/snowcatcloud.md
doc/user/content/ingest-data/stripe.md
doc/user/content/ingest-data/webhook-quickstart.md
doc/user/content/sql/create-source/webhook.md

Docs counterpart to https://github.com/MaterializeInc/console/pull/2537.
Tested this example out in staging and it worked.
cc @arusahni 
The CHECK statement syntax can be confusing to people. One aspect that is challenging is that you cannot use a fully qualified name for the secret in the constant_time_eq call. Let's encourage users to alias the secret, then use the alias in the constant_time_eq call. 
-

Update user docs on webhook source creation to use an alias for the CHECK statement secret

---

src/sql/src/session/vars/definitions.rs

This is the value present in some testing envs. Turn it on locally so we get more use during local dev.
- n/a

sql: update persist_fast_path_limit to 25

---

doc/user/content/integrations/_index.md

Everywhere else the user is identified by a UUID, either the segment anonymous ID, or the frontegg ID. Instead, we can include the email as an attribute on the track call, so it's still accessible to analytics, but not polluting the user ID field.
I discovered this while investigating an issue Matt [reported](https://materializeinc.slack.com/archives/C06GZ7GBKB5/p1717091663493629), which was fixed here: https://github.com/MaterializeInc/materialize/pull/27385.
- Not user facing

docs: don't identify users by email

---

doc/user/layouts/partials/head.html

I broke segment in https://github.com/MaterializeInc/materialize/pull/27385 🤦 
- Not user facing

docs: Fix segment load

---

test/balancerd/mzcompose.py
test/limits/mzcompose.py

id became a required parameter in https://github.com/MaterializeInc/materialize/pull/27533 Tests are now failing: https://buildkite.com/materialize/nightly/builds/8065
```
frontegg-mock: fatal: decoding --users: missing field `id` at line 1 column 324
```
Relevant test run: https://buildkite.com/materialize/nightly/builds/8078
-

tests: Fix frontegg-mock parameters

---

misc/python/materialize/cli/ci_annotate_errors.py

Noticed in https://buildkite.com/materialize/nightly/builds/8065
-

ci-annotate: Detect frontegg-mock fatals

---

src/repr/src/row/encoding2.rs

Seen in https://buildkite.com/materialize/nightly/builds/8075#01900eca-bc86-4acc-a626-990373d2636c
Started failing with https://github.com/MaterializeInc/materialize/pull/27084
-

miri: Ignore proptest_datums test

---

src/sql/src/catalog.rs
src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/sql/src/pure/mysql.rs
src/sql/src/pure/postgres.rs
src/storage-controller/src/lib.rs
src/storage-types/src/sources.rs
test/pg-cdc/alter-source.td
test/pg-cdc/pg-cdc.td
test/pg-cdc/publication-for-table.td
test/pg-cdc/replica-identity.td
test/pg-cdc/two-source-schemas.td

`SubsourceResolver` is meant to deprecate `SubsourceCatalog`, and this PR does that. The drive here is to provide an API that lets all sources of all types resolve subsource references to the source's local details about that subsource (e.g. looking up `PgTableDesc` from an `UnresolvedItemName`). This will eventually also be used to look up subsources when determining the subsource schemas and that PR will be up next.
-

sql: replace SubsourceCatalog with SubsourceResolver

---

src/orchestrator-kubernetes/src/lib.rs

The code detecting an OOM-kill when reporting a replica status update would unconditionally check the replicas `last_state` before checking its current state. It could thus incorrectly report an OOM-kill when the replica oom'd previously, even when the current crash was due to something else than an OOM.
This is fixed here by adjusting the logic to only look at `last_state` if the current state is something else than "terminated" (i.e. "waiting" or "running").
This PR also changes to logic to detect exit code 135 (SIGBUS, observed during OOD kills) as an OOM-kill as well.
Fixes #27602 
- N/A

k8s: fix detection of OOM kills

---

misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

This addresses
* https://buildkite.com/materialize/nightly/builds/8083#019011c6-9f22-46fa-bd99-484a37f78cb7
* https://buildkite.com/materialize/nightly/builds/8084#019011ca-54f6-4321-a1a3-50eb934b2a32
Nightly: https://buildkite.com/materialize/nightly/builds/8085

postgres consistency: extend and adjust ignores

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/secret.rs

Move create, alter, and rotate keys for secrets off of the coordinator thread. This allows the possibly slow k8s calls to read or ensure the secrets to not block the coord thread.
- n/a

adapter: move various secrets work into off-thread tasks

---

ci/plugins/mzcompose/hooks/command

Verification: https://buildkite.com/materialize/nightly/builds/8089
-

ci: Exclude two tests from heap profiles

---

Cargo.lock
src/sql/Cargo.toml

Seen in https://buildkite.com/materialize/nightly/builds/8088#019012a7-a173-416f-851b-5323804ce64e
Verification: https://buildkite.com/materialize/nightly/builds/8097
-

mz-sql build: Remove unused postgres_array dependency

---

ci/plugins/mzcompose/hooks/command

ci: Disable heap profiling for all benchmarks

---

misc/python/materialize/test_analytics/data/build_data_storage.py
misc/python/materialize/test_analytics/test_analytics_db.py

Aaaaaaahhhhh
This is the cause of
```
select count(*) from build_step;
Results
count
10485776
```

test analytics: build step: fix upload

---

misc/python/materialize/cli/ci_upload_heap_profiles.py

ci: Silence upload heap profile prints

---

misc/python/materialize/cli/ci_annotate_errors.py

ci: Also annotate junit errors with associated issues

---

ci/test/pipeline.template.yml

Sometimes goes OoM, for example in https://buildkite.com/materialize/test/builds/83845
-

ci: Increase agent size for Kafka resumption test

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/state.rs
src/catalog/src/durable/objects.rs
src/catalog/src/memory/objects.rs

The in-memory `CatalogState` maintains denormalized data for certain object types. For example, items maintain a list of all dependent items (other items that depend on it). Updates to an object, for example, updating the privileges on an object, is represented as a retraction of the object in its previous state, followed by an addition of the object in its new state, within a single timestamp.
Naively, we would apply these by removing the object from `CatalogState` when applying the retraction and then re-inserting it when applying the addition. The issue with this approach is that we lose all the denormalized state, which can be prohibitively expensive to regenerate.
This commit resolves this issue via the following process:
1. When applying retractions, stash all removed objects in …

catalog: Correctly handle matching updates

---

misc/python/materialize/checks/all_checks/load_generator.py
src/adapter/src/catalog/migrate.rs

This also fixes #27638 which is caused by this migration deleting the `AS OF` and `UP TO` options from load generator sources.
Fixes https://github.com/MaterializeInc/incidents-and-escalations/issues/45#issuecomment-2167043869.
-

adapter: remove already applied loadgen source migration

---

misc/python/materialize/checks/all_checks/sink.py

Locally I'm seeing wrong results: (Edit: Also in CI: https://buildkite.com/materialize/nightly/builds/8101)
```
> SELECT before IS NULL, (after).x, (after).y FROM sink_alter_source
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 76s
^^^ +++
9:1: error: non-matching rows: expected:
[["true", "0", "a"], ["true", "102", "ccc"], ["true", "11", "bb"]]
got:
[["true", "0", "a"], ["true", "10", "aa"], ["true", "101", "bbb"]]
Poor diff:
+ true 10 aa
+ true 101 bbb
- true 102 ccc
- true 11 bb
```
Adding sleeps seems to fix them. But I'm worried because it looks like without the sleep the old data can end up in the sink even though we previously altered the sink to switch to a new table. @petrosagg Is this …

platform-checks: Add ALTER SINK test

---

src/adapter/src/flags.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs

🧹 - looks like the usage of this was removed back in April.
-

[cluster] Remove a dead system var

---

ci/plugins/mzcompose/hooks/command
ci/plugins/mzcompose/hooks/post-command
misc/python/materialize/cli/ci_upload_heap_profiles.py

This reverts commit 41cc32278897c87026cd47b10fbff40f330b1e3a.
I feel like tests and nightly have been slightly more flaky since this merged and I'm out next week. So more prudent to revert this for now.
-

Revert "ci: Always upload collection of heap profiles at the end"

---

misc/python/materialize/cli/run.py

This regressed during a refactoring at some point.
- n/a

bin/cargo-test: fix passing of COCKROACH_URL

---

src/adapter/src/catalog/apply.rs
src/catalog/src/memory/objects.rs

Updating an item through the `apply_updates` machinery requires
updating the item durably, reading it back in from disk, and finally
parsing, planning, and optimizing the item's CREATE SQL. The parsing,
planning, and optimizing is potentially wasteful for updates that don't
modify the item's SQL such as privilege updates. This commit optimizes
item updating by skipping parsing, planning, and optimizing when the
SQL has not changed. Applying items no longer fits nicely into the
`UpdateFrom` trait, so the code's a bit uglier, but the structure is
still the same.

catalog: Optimize item updates

---

misc/python/materialize/github.py

Seen failing in https://buildkite.com/materialize/test/builds/83914#01901791-e03e-454c-8b41-5a0d8b2c1edd
-

ci: Fix github invalid regex detection

---

misc/python/materialize/cli/ci_annotate_errors.py

Nightly: https://buildkite.com/materialize/nightly/builds/8117

ci: capture and annotate errors in RQG log

---

doc/developer/fast-compiles.md

mold on Linux is more efficient (05:01 vs 05:04 for me, 05:34 for ld), Xcode 15 ld on macOS (08:03 vs 08:04 with lld)
-

dev docs: Update fast compile guide

---

misc/images/materialized/entrypoint.sh
misc/python/materialize/cli/run.py
misc/python/materialize/cloudtest/k8s/environmentd.py
misc/python/materialize/mzcompose/services/materialized.py
src/controller/src/lib.rs
src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/test_util.rs
src/sqllogictest/src/runner.rs
test/crdb-restarts/mzcompose.py

We folded the storage stash into the catalog, but never cleaned up the now-unused storage stash URL argument.
- n/a

controller: remove disused storage stash URL argument

---

misc/python/materialize/mzcompose/services/materialized.py
src/environmentd/src/bin/environmentd/main.rs

This argument dates from the times before cluster unification. It is no longer used.
Touches MaterializeInc/cloud#5344.
* This PR removes dead code.
- n/a

environmentd: remove vestigial default storage host size argument

---

ci/builder/Dockerfile
doc/user/content/stylesheet.md
doc/user/layouts/_default/_markup/render-image.html
doc/user/layouts/_default/_markup/render-link.html
doc/user/layouts/partials/footer.html
doc/user/layouts/partials/relative-link.html
doc/user/layouts/shortcodes/callout.html
doc/user/layouts/shortcodes/cta.html
doc/user/layouts/shortcodes/fnlist.html

Our current version of Hugo is fairly out of date, and engineers are encountering issues trying to author docs. This upgrades us to a recent version of Hugo and makes the necessary changes to make the generated docs functional. Beyond the version bump this includes:
- Fixing a build issue around the footer object format changing
- Updating our path generation to account for a change in relative pathing. Newer versions of Hugo generate URLs relative to the host, not subdirectory, even when hosted within a subdirectory. Add logic to our templates shortcodes to read the path from the Hugo config and prepend it to any relative URL.
-

Upgrade hugo

---

src/compute/src/logging/compute.rs
src/compute/src/logging/differential.rs
src/compute/src/logging/reachability.rs
src/compute/src/logging/timely.rs
src/timely-util/src/replay.rs

Adds a container builder generic argument to `MzReplay::mz_replay` to allow callers to express how and what containers they'd like to receive. The container builder is a parameter on `mz_replay` instead of the trait so that callers can specify it as part of the function call instead of needing to specify it as part of the trait. This limits flexibility, but is acceptable because we're in control over all implementations.
This is in support of enabling more advanced containers in logging dataflows.
-

Extend MzReplay with container builder

---

src/environmentd/src/bin/environmentd/main.rs

to BOOTSTRAP_BUILTIN_CATALOG_SERVER_CLUSTER_REPLICA_SIZE
Follow-up to https://github.com/MaterializeInc/materialize/issues/26731
- N/A

envd: Rename BOOTSTRAP_BUILTIN_INTROSPECTION_CLUSTER_REPLICA_SIZE

---

src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/sequencer/inner/secret.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/sql.rs

Allow safe off-thread tasks to listen for cancellation events from the coordinator.
- n/a

adapter: support cancellation in sequence_staged

---

src/adapter/src/flags.rs
src/postgres-util/src/lib.rs
src/postgres-util/src/tunnel.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/storage-types/src/connections.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs
src/storage/src/source/postgres/replication.rs
test/pg-cdc/pg-cdc.td

Details in commit messages.
Slack context: https://materializeinc.slack.com/archives/C0761MZ3QD9/p1718382044937969
Update the naming of the keepalives parameters in LD.
- n/a

storage: make PostgreSQL source more robust to silent connection drops

---

misc/bazel/cargo-gazelle/src/lib.rs
misc/bazel/cargo-gazelle/src/platforms.rs
misc/bazel/cargo-gazelle/src/targets.rs

This PR updates cargo-gazelle to generate `crate-features` and `dependencies` based on platform. For example, the [`mz-alloc-default` crate](https://github.com/MaterializeInc/materialize/blob/main/src/alloc-default/Cargo.toml#L30-L31) enables the `jemalloc` feature on `alloc` if the platform is not `macos`.
After this PR we'll generate a `rust_library` target like:
```
rust_library(
name = "mz_alloc",
srcs = glob(["src/**/*.rs"]),
crate_features = ["default"] + select({
"@//misc/bazel/platforms:linux_arm": [
"jemalloc",
"mz-prof",
"tikv-jemallocator",
],
"@//misc/bazel/platforms:linux_x86_64": [
"jemalloc",
"mz-prof",
"tikv-jemallocator",
],
"//conditions:default": [],
}),
aliases = aliases(
normal = True,
proc_macro = True,
),
deps = [
"//src/ore:mz_ore",
"//src/prof-http:mz_prof_http", …
```

bazel: Update cargo-gazelle to generate platform specific features and dependencies

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/explain_timestamp.rs

With the new support of cancelling for sequence staged, we can remove the detour that explain timestamp took through into the RTR handler.
* First commit is #27682
-

adapter: move explain timestamp to sequence staged

---

.cargo/config.toml
Cargo.lock
bin/ci-builder
ci/builder/Dockerfile
ci/test/lint-slow.sh
misc/cargo-vet/audits.toml
misc/cargo-vet/config.toml
misc/cargo-vet/imports.lock
misc/python/materialize/xcompile.py
src/cluster/Cargo.toml
src/mysql-util/Cargo.toml
src/rocksdb/Cargo.toml
src/rocksdb/src/config.rs
src/rocksdb/tests/basic.rs
src/storage/Cargo.toml
src/workspace-hack/Cargo.toml

This PR upgrades our `rust-rocksdb` dependency to use the upstream version instead of our fork since the changes in our fork related to the `WriteBufferManager` have been released. 
Note: we do lose the changes to `rust-rocksdb` that [specify the CPU type](https://github.com/MaterializeInc/rust-rocksdb/pull/2) when building `librocksdb`, but there was never any concrete evidence that this improved performance. It's also something we can easily re-introduce with Bazel if need be. If this is deemed important, I did make branch of our fork that [merges upstream](https://github.com/MaterializeInc/rust-rocksdb/pull/3).
To prevent a duplicate dependency of `bindgen` I also upgraded `mysql_common` which also resulted in various `postgres` crates getting updated with changes @benesch recently …

.*: Upgrade `rust-rocksdb`, `mysql_common`, and `postgres*` dependencies

---

src/adapter/src/catalog/apply.rs

This commit moves a helper function from the top of the file to the bottom of the file to match all the other helper functions in that file. This is 100% code movement.

catalog: Move function position

---

Cargo.lock
misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/cloudtest/util/cluster.py
src/adapter/benches/catalog.rs
src/adapter/src/catalog.rs
src/catalog-debug/src/main.rs
src/catalog/src/durable.rs
src/catalog/src/durable/initialize.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/persist/tests.rs
src/catalog/tests/debug.rs
src/catalog/tests/open.rs
src/catalog/tests/read-write.rs
src/compute-client/src/controller.rs
src/controller-types/Cargo.toml
src/controller-types/src/dyncfgs.rs
src/controller-types/src/lib.rs
src/controller/src/clusters.rs
src/controller/src/lib.rs
src/dyncfgs/Cargo.toml
src/dyncfgs/src/lib.rs
src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/lib.rs
src/environmentd/src/test_util.rs
src/environmentd/tests/server.rs
src/orchestrator-process/src/lib.rs
src/sqllogictest/src/runner.rs
test/cloudtest/test_crash.py
test/cloudtest/test_system_clusters.py

Touches https://github.com/MaterializeInc/materialize/issues/27406.
This is one of the things that we need in order to locally test read-only mode and eventually zero-downtime upgrades. After this change, you cannot run multiple deploy generations of `bin/environmentd` in parallel, but it is one of the necessary steps. We are now failing because of fencing and other things having to do with access to shared resources, like writing to tables and whatnot.
The change makes it so that multiple deploy generations of a single (local) environment can peacefully co-exist. Each one can spin up their cluster processes and their scratch directories (if any) don't clash.
~Crucially, this only changes the Process Orchestrator, which is used for local testing. The Kubernetes Orchestrator which is used …

orchestrator: in Process Orchestrator, disambiguate processes by deploy generation

---

misc/python/materialize/cloudtest/k8s/environmentd.py
test/upsert/mzcompose.py

* Fix some nightly tests that I broke.
- n/a

Various fixes to nightlies

---

test/cloudtest/test_full_testdrive.py
test/testdrive/kafka-sink-topic-config.td
test/testdrive/mzcompose.py

This should fix https://github.com/MaterializeInc/materialize/issues/27648.
Nightly: https://buildkite.com/materialize/nightly/builds/8133

tests: kafka-sink-topic-config.td: disable status check when using Redpanda

---

src/adapter/src/active_compute_sink.rs
src/adapter/src/coord.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/environmentd/tests/tracing.rs

This required changing the RTR and ActiveCopyTo APIs to no longer take full ownership of the `ExecuteContext`. In the RTR case, this was the last usage of that API and it could be removed completely.
* Last commit only, others are from #27689.
- n/a

adapter: refactor select to sequence staged

---

ci/nightly/pipeline.template.yml

Observed two failures in https://buildkite.com/materialize/nightly/builds/8142.

ci: re-enable one automatic retry for k8s node recovery tests

---

Cargo.lock
ci/release-qualification/pipeline.template.yml
src/adapter/Cargo.toml
src/cluster/Cargo.toml
src/compute/Cargo.toml
src/controller/Cargo.toml
src/environmentd/Cargo.toml
src/ore/Cargo.toml
src/ore/src/lib.rs
src/ore/src/process.rs
src/persist-client/Cargo.toml
src/storage-client/Cargo.toml
src/timely-util/Cargo.toml
src/txn-wal/Cargo.toml

This PR fixes a soundness hole introduced by multiple threads calling `halt!` at the same time, thereby invoking thread-unsafe the libc `exit` function concurrently, which would lead to use-after-frees and segfaults. The fix is to call `_exit` instead, which is thread-safe.
Fixes #21751
- N/A

ore: make `halt!` use `_exit` to avoid exit handler races

---

doc/user/content/sql/create-materialized-view.md
doc/user/layouts/partials/sql-grammar/with-options.svg
doc/user/sql-grammar/sql-grammar.bnf

Follow-up to #27325.
@ggevay, I missed adding the shortcode that pulled in the `WITH` options `.svg` — thanks for noticing it! Here's what it'll look like after this PR:

doc/user: patch CREATE MATERIALIZED VIEW grammar

---

src/adapter/src/catalog/transact.rs
test/sqllogictest/rename.slt

Previously, renaming a non-temporary object with temporary dependents failed with a cryptic error. This commit fixes the issue, allowing users to rename non-temporary objects with temporary dependents.

sql: Fix renames with temporary dependents

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/state.rs
src/testdrive/src/action/consistency.rs

Testdrive has a feature where it compares the state of the in-memory catalog to the state of the on-disk catalog and throws an error if there is a difference. The set of unfinalized shards in the catalog are updated asynchronously by background processes. As a result, the value may legitimately change after fetching the memory catalog but before fetching the disk catalog, causing the testdrive comparison to fail. This commit fixes the issue by ignoring the unfinalized shards in the catalog comparison to ignore false negatives. Unfortunately, we also end up ignoring true negatives.
Specifically the implementation sets the value of the disk catalog's unfinalized shards equal to the value of the memory catalog's unfinalized shards, so that the comparison never fails.
Fixes #27196
This PR …

testdrive: Ignore unfinalized shards in catalog

---

misc/python/materialize/version_ancestor_overrides.py
src/adapter/src/catalog.rs
src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/coord/ddl.rs
src/adapter/tests/sql.rs
src/catalog/src/builtin.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs
src/catalog/tests/read-write.rs
src/sql/src/session/vars.rs

This commit updates the catalog transaction logic such that updates to
the in-memory catalog are made using the `apply_update` function. In
theory this puts us in a state where all updates to the in-memory
catalog that can be derived from the durable catalog, are done via the
`apply_update` function.

catalog: Listen for updates in transactions

---

src/compute/src/arrangement/manager.rs
src/compute/src/compute_state.rs
src/compute/src/logging/initialize.rs
src/compute/src/render/context.rs
src/compute/src/server.rs

Upon reconnecting to a replica, the compute controller expects the logging collections to be uncompacted and readable from the minimum time. To ensure that we introduce the ability to "pad" traces in the `TraceManager` by filling up their compacted times with empty contents. This is implemented as a thin `TraceReader` wrapper that intercepts accesses to the trace's logical compaction frontier and otherwise passes requests through to the inner trace.
This is an alternative proposal to https://github.com/MaterializeInc/materialize/pull/27532 that does not remove the `SpecializedTraceHandle` type but works around it instead.
Compute reconciliation introduces a mismatch between the controller's expectation of the read frontiers of logging …

compute: reconciliation of logging collections (preserving `SpecializedTraceHandle`)

---

doc/developer/design/20240610_unified_compute_introspection.md

This PR adds a design for Unified Compute Introspection (https://github.com/MaterializeInc/materialize/issues/26730). The design is for an MVP that can be quickly implemented by the cluster team/me, and many of the design decisions reflect that, e.g., by preferring the simpler approach over the more flexible one.
Part of #26730.
- N/A

design: Unified Compute Introspection

---

src/repr/src/adt/numeric.rs

Seen failing in https://buildkite.com/materialize/nightly/builds/8158#01902c67-2c5e-4569-a48d-aa5a33d8a10b.

tests: disable smoketest_packed_numeric_roundtrips in miri

---

src/adapter/src/catalog.rs
src/adapter/src/coord.rs
src/adapter/src/coord/statement_logging.rs
src/compute-client/src/controller.rs
src/controller/src/lib.rs
src/storage-controller/src/collection_status.rs

Work towards https://github.com/MaterializeInc/materialize/issues/27406
Please see individual commits for the reason behind the change.
cc @benesch this changes something that you recently added, around `allow_writes()` and cleanup of cluster processes/pods.
-

adapter,controller: refactorings that facilitate more read-only work

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select
test/sqllogictest/cockroach/limit.slt
test/sqllogictest/limit_expr.slt
test/sqllogictest/order_by.slt

Fixes #27765
I've checked also the Monte Carlo query from the issue, and it works.
* This PR adds a known-desirable feature: https://github.com/MaterializeInc/materialize/issues/27765
-

Accept OFFSET and LIMIT/FETCH in any order

---

src/controller/src/lib.rs

I snuck in this annoying last-minute mistake in my PR that I just merged. 🙈 
-

controller: fix read_only bit

---

misc/python/materialize/version_ancestor_overrides.py

This addresses the build failure in https://buildkite.com/materialize/nightly/builds/8174#0190356c-8398-400c-beab-ea7b3b68d451.
```
Docker compose failed: docker compose -f/dev/fd/3 --project-directory /var/lib/buildkite-agent/builds/buildkite-large-aarch64-e5872a3-i-082fa1e5905b9baf9-1/materialize/nightly/test/feature-benchmark up --detach --wait cockroach materialized clusterd
```
I learnt that the override commit needs to be directly on the main line (otherwise no image will exist).

feature benchmark: fix ignore entry

---

misc/python/materialize/test_analytics/data/build/build_data_storage.py
misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
misc/python/materialize/test_analytics/data/scalability_framework/scalability_framework_result_storage.py
misc/python/materialize/test_analytics/setup/tables/00-config.sql
misc/python/materialize/test_analytics/setup/tables/02-build-step.sql
misc/python/materialize/test_analytics/setup/tables/10-feature-benchmark.sql
misc/python/materialize/test_analytics/setup/tables/11-scalability-framework.sql
misc/python/materialize/test_analytics/setup/views/02-build-job.sql
misc/python/materialize/test_analytics/setup/views/10-feature-benchmark.sql
misc/python/materialize/test_analytics/setup/views/11-scalability-framework.sql
misc/python/materialize/test_analytics/test_analytics_db.py

This information can either be computed on the fly from other data or retrieved through joins.
425c362c61 test analytics: remove build job url
e7fa4714e7 test analytics: feature benchmark: drop build_id column
82e87398fe test analytics: feature benchmark: add table aliases to views
3583daea10 test analytics: scalability framework: drop build_id column
caeeee84dd test analytics: scalability framework: add table aliases to views
83aff341e1 test analytics: increase current and minimal supported data version

test analytics: remove superfluous data in tables

---

src/persist-client/src/batch.rs
src/persist-types/src/stats.rs
src/persist-types/src/stats/bytes.rs
src/persist-types/src/stats/json.rs
src/persist-types/src/stats/primitive.rs
src/persist-types/src/stats/structured.rs

This PR is _pure code movement_. `persist-types/src/stats.rs` has grown quite large with a number of different trait implementations and I found it hard to model in my head what types implemented what traits, and what was the right way to organize code when adding new implementations. This PR breaks apart `stats.rs`, moving the 4 trait types, primitive, bytes, json, and structured into their own modules.
@bkirwi feel free to push back if you prefer the current layout!
- N/a

persist: break apart `stats.rs`

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.106.0-dev

---

ci/test/cargo-test/mzcompose.py

This addresses -- if it works -- https://buildkite.com/materialize/nightly/builds/8174#0190356c-8390-40cd-80fd-e7416e5d0ddc, which references https://github.com/MaterializeInc/materialize/issues/19931.
* This build ❌ ✅ ✅
* https://buildkite.com/materialize/test/builds/84244 ✅ ✅ ✅
* https://buildkite.com/materialize/test/builds/84245 ✅ ✅ ✅
* https://buildkite.com/materialize/test/builds/84246 ✅ ✅ ✅
* https://buildkite.com/materialize/test/builds/84247 ❌ ✅ ✅

cargo tests: use higher concurrency

---

src/persist-client/src/internal/cache.rs

The flag takes effect immediately, not on restart
- N/a

persist: Update description on dyn cfg

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/adapter/src/catalog/transact.rs
src/catalog/src/durable/objects/state_update.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/transaction.rs
src/catalog/src/memory/objects.rs

The in-memory catalog state updates are only processed for a single
timestamp at a time. Due to this, we previously omitted the timestamps
for convenience. Soon, we will want to be able to process updates for
multiple timestamps at once. In preparation for that, this commit
starts plumbing timestamps into the in-memory state updates.
The diff is much smaller if viewed with whitespace hidden.

catalog: Plumb timestamps into state updates

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Release `dbt-materialize` `v1.8.2`. See `CHANGELOG.md` for an overview of the release.

dbt-materialize: release v1.8.2

---

src/adapter/src/coord/timestamp_selection.rs
test/kafka-rtr/simple/verify-rtr.td
test/testdrive/explain-timestamps.td

adapter: show RTR timestamp in EXPLAIN TIMESTAMP

---

src/adapter/benches/catalog.rs
src/adapter/src/catalog.rs
src/adapter/src/catalog/open.rs
src/adapter/tests/parameters.rs
src/adapter/tests/sql.rs

Ignore for now. This failed CI when it was in a slightly different form (using `NOW_ZERO` instead of `SYSTEM TIME`). I'm hoping this form works better.
----
All of these tests are fine with using `SYSTEM_TIME` as the `NowFn`.
- n/a

catalog: simplify open_debug_catalog implementation

---

doc/user/content/sql/show-clusters.md

This brings the descriptions of the builtin clusters in line with what we're putting in the console (MaterializeInc/console#2587).
* This PR refactors existing documentation.
- n/a

doc/user: improve builtin cluster descriptions

---

misc/python/materialize/cli/ci_annotate_errors.py

Seen in https://buildkite.com/materialize/nightly/builds/8192
> zippy-ssh-bastion-host-1  | ssh_dispatch_run_fatal: Connection from 172.16.16.9 port 51480: Broken pipe [preauth]
-

ci: Don't annotate expected ssh_dispatch_run_fatal messages

---

test/testdrive/load-generator-key-value.td

testdrive: Disable flaky load-generator-key-value part

---

test/mysql-cdc-resumption/alter-source-add-subsource.td
test/mysql-cdc-resumption/mzcompose.py
test/mysql-cdc-resumption/populate-table-t3.td
test/mysql-cdc-resumption/verify-t3.td

>  Create a source, purge the bin log, add a sub source?
This adds testing for https://github.com/MaterializeInc/materialize/pull/27507.

tests: mysql-cdc: test add sub source after corruption

---

src/compute-client/src/controller.rs
src/storage-client/src/controller.rs
src/storage-controller/src/collection_mgmt.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/statistics.rs

This PR extends the storage controller with support for deleting contents of differential storage-managed collections. Instead of a list of updates to append, the storage controller now accepts a `StorageWriteOp` in its APIs to update these collections. In addition to the existing append functionality, a `StorageWriteOp` can also specify a deletion request based on a `Row` filter.
At the moment deletions are implemented simply by utilizing the `desired` state that is kept in memory for differential collections, making additional persist reads unnecessary. This will have to change once the `CollectionManager` becomes smart enough to only keep the diff between `desired` and the persisted collection contents.
Part of #26730
Design: #27548 
The new …

storage: deletion from differential storage-managed collections

---

test/kafka-rtr/simple/verify-rtr.td

Seen in https://buildkite.com/materialize/test/builds/84402
-

RTR test: Fix waiting for explain timestamp

---

src/timely-util/src/containers/stack.rs

This PR adds a container builder wrapper that keeps track of the heap allocated bytes produced so far. This information can be used by operators to decide when it is a good time to yield.
-

timely-util: implement an accounting container builder

---

test/testdrive/load-generator-key-value.td

Still failing in https://buildkite.com/materialize/test/builds/84427#019049f0-5909-45b8-990f-4b6bf440c750
-

testdrive: Disable entire loadgen query

---

src/environmentd/src/deployment.rs
src/environmentd/src/deployment/preflight.rs
src/environmentd/src/deployment/state.rs
src/environmentd/src/http.rs
src/environmentd/src/lib.rs
src/environmentd/tests/server.rs
src/ore/src/channel.rs
src/ore/src/channel/trigger.rs
src/server-core/src/lib.rs
src/sqllogictest/src/runner.rs

Various refactorings that will allow the cloud orchestration layer to perform a 0dt upgrade if a feature flag is enabled for the environment.
Go commit by commit.
If it's helpful, here's the commit that I'm working on that stacks on top of this refactoring to actually perform the 0dt preflight checks: https://github.com/MaterializeInc/materialize/pull/27819/commits/99c9367d899bc36ae6f2604a281a494a6642d288
- n/a

environmentd: prepare to integrate 0dt upgrades with deploy generations

---

src/persist-types/src/dyn_col.rs
src/persist-types/src/stats.rs
src/persist-types/src/stats/bytes.rs
src/persist-types/src/stats/json.rs
src/persist-types/src/stats/primitive.rs
src/persist-types/src/stats/structured.rs
src/repr/src/row/encoding.rs
src/repr/src/stats.rs
src/storage-types/src/controller.rs
src/storage-types/src/stats.rs

This PR refactors stats handling away from using `Box<dyn DynStats>` and to using a concrete type called `ColumnarStats`, which is structured very similar to the `ProtoDynStats` message type, i.e. it has an inner `enum` of all the stats types that we can match against.
It should not result in _any_ behavioral change, the `statistics_stability` test that asserts the generated statistics match a snapshot, is still passing.
Previously the flow worked like `ProtoDynStats` -> `Box<dyn DynStats>` -downcast-> `T::Stats`. The flow in this PR is still very similar, `ProtoDynStats` -> `ColumnarStats` -> `T::Stats`, but now `ColumnarStats` contains an enum `ColumnStatsKind` that we can match against in a follow up PR.
Related to https://github.com/MaterializeInc/materialize/issues/24830
Related to …

persist: Refactor stats away from `Box<dyn DynStats>` and instead use an enum

---

src/storage-types/src/errors.proto
src/storage-types/src/errors.rs
src/storage/src/source.rs
src/storage/src/source/generator.rs
src/storage/src/source/generator/key_value.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs

This change enables storage dataflows to make use of columnated/lgalloced containers when moving data between operators. We could have gone the other way and implemented a columnation region for the `SourceReaderError` type but since there aren't any actual downsides to switching to `DataflowError` we go for this simpler approach.
-

storage: switch sources to columnated `DataflowError`

---

src/timely-util/src/containers/stack.rs

As discussed here https://github.com/MaterializeInc/materialize/pull/27811#discussion_r1651119804
-

timely-util: use the same preferred capacity regardless of variant

---

Cargo.toml
bin/ci-builder
bin/lint-versions
src/adapter/Cargo.toml
src/adapter/src/catalog/open.rs
src/adapter/tests/sql.rs
src/avro/src/reader.rs
src/catalog/src/durable/transaction.rs
src/expr/src/scalar/func/impls/string.rs
src/orchestrator-process/Cargo.toml
src/orchestrator/Cargo.toml
src/repr/src/adt/numeric.rs
src/repr/src/explain/tracing.rs
src/storage-types/src/stats.rs
src/timely-util/Cargo.toml

This PR updates the version of Rust we use to v1.79 and fixes a few clippy lints.
Upgrade to the latest stable version of Rust
- Materialize is now built with v1.79 of Rust

.*: Upgrade Rust to v1.79

---

doc/user/content/sql/system-catalog/mz_catalog.md
src/adapter/src/catalog/builtin_table_updates.rs
src/catalog/src/builtin.rs
test/sqllogictest/autogenerated/mz_catalog.slt
test/sqllogictest/mz_catalog_server_index_accounting.slt
test/sqllogictest/system-cluster.slt

We should show these as they may cause replicas to be redeployed on `alter cluster` if changed.
-

Mz clusters add introspection columns

---

src/adapter/src/optimize/dataflows.rs

Inspired by https://github.com/MaterializeInc/materialize/pull/27806.
Webhook sources can only be appended to, which AFAIU makes them monotonic. Marking them as such unlocks some downstream optimizations in compute.
Mark webhook sources as monotonic to improve performance
- N/a

compute: Mark webhook sources as monotonic

---

src/adapter/src/coord.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/repr/src/adt/numeric.rs
test/sqllogictest/updates.slt

Avoid max_query_result_size in the read portion of read-then-write plans. Previously that session var would limit the size of the updates to its setting. This would cause, for example, a `DELETE` issued from the console to fail if there were more than 1MB of rows in a table.
Fixes #27428
- n/a

adapter: don't use max_query_result_size in RTW plans

---

ci/nightly/pipeline.template.yml
misc/python/materialize/mzcompose/services/materialized.py
src/adapter-types/src/dyncfgs.rs
src/adapter/src/catalog/transact.rs
src/catalog/src/durable.rs
src/catalog/src/durable/initialize.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/transaction.rs
src/environmentd/src/bin/environmentd/main.rs
src/environmentd/src/deployment.rs
src/environmentd/src/deployment/preflight.rs
src/environmentd/src/deployment/state.rs
src/environmentd/src/lib.rs
src/environmentd/src/test_util.rs
src/sqllogictest/src/runner.rs
test/0dt/mzcompose
test/0dt/mzcompose.py

Introduce a new `enable_0dt_deployment` feature flag. When enabled,
environments booted with a new deploy generation follow a zero-downtime
deployment flow:
1. The new environment loads the catalog in savepoint mode and
starts the controllers in read only mode.
2. The new environment announces itself as `Initializing` while it
waits to be ready. For now, we use a fixed 30s timer, but in the
future we will use a far stricter definition of ready that checks
cluster hydration status.
3. When the new environment is promoted by the external orchestrator,
it halts. When it is restarted, it will restart with writes allowed
and begin serving traffic.
* This PR adds a known desirable feature.
- n/a

environmentd: add 0dt preflight checks behind feature flag

---

pyproject.toml

Seen locally:
```
reformatted /home/deen/git/materialize/target/debug/build/tikv-jemalloc-sys-281cfa09aba54ee0/out/build/src/ticker.py reformatted /home/deen/git/materialize/target/debug/build/tikv-jemalloc-sys-281cfa09aba54ee0/out/build/scripts/gen_run_tests.py reformatted /home/deen/git/materialize/target/debug/build/tikv-jemalloc-sys-281cfa09aba54ee0/out/build/scripts/gen_travis.py
```
-

black formatter: Ignore target(-xcompile) directory

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/cluster.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/cluster.rs
src/sql/src/plan.rs

This refactor should have no functional change, but will prepare us to implement [graceful reconfigure](https://github.com/MaterializeInc/materialize/issues/20010) using `sequence_staged`
Graceful reconfiguration will require sleeps or long running checks inside of the `alter cluster` ddl. We want these waits to be
cancelable and moved off the main coord thread. This is perfect for `sequence_staged` to handle.
-

use sequence_staged for alter cluster ddl

---

test/sqllogictest/mzcompose.py

Seen failing in https://buildkite.com/materialize/slt/builds/5961#01904a03-82ac-4484-a8df-26c97ad17fe3
-

slt: Fix some types in tests

---

test/testdrive/explain-timestamps.td

We don't care for responsability in this case
Fixes: #27748
-

testdrive: Ignore whether queries can respond immediately

---

src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/storage-client/src/controller.rs
src/storage-client/src/storage_collections.rs
src/storage-controller/src/lib.rs
src/txn-wal/src/lib.rs

The preconditions of the TODO to remove it are met: we can't run without the txn system anymore.
The immediate motivation is that it will make adding read-only support for the StorageController easier, which is work towards zero-downtime upgrades: https://github.com/MaterializeInc/materialize/issues/27406.
The tricky part with this is not the code, but thinking hard about whether it's correct to remove this.
-

storage: remove init_txns()

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/impl.py
misc/dbt-materialize/dbt/include/materialize/macros/relations.sql
misc/dbt-materialize/mzcompose.py
misc/dbt-materialize/tests/adapter/fixtures.py
misc/dbt-materialize/tests/adapter/test_persist_docs.py

This PR fixes the documentation generation for cross-db objects used as sources in models.

dbt-materialize: allow docs generation for cross-db sources

---

src/storage/src/healthcheck.rs
src/storage/src/source/source_reader_pipeline.rs
src/timely-util/src/builder_async.rs

This PR enables using the `.give()` API for any container builder that supports it. Only the first commit needs to be reviewed, the second one is a mechanical change since more type annotations are now needed that were previously inferred.
-

timely-util: make `AsyncOutputHandle::give` generic over the container builder

---

misc/python/materialize/cli/run.py

Bring the behavior of bin/environmentd more in line with Kubernetes and auto-restart envd after it halts. This facilitates demos and local testing of the new 0dt deployment flow, which involves a halt-and-restart when the new generation takes over.
Kubernetes will also restart envd after a panic, but we choose not to do so here, to avoid papering over panics during local development.
* This PR adds a known-desirable feature: works towards 0dt.
- n/a

bin/environmentd: auto-restart on halt

---

src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/sequential_hydration.rs
src/compute-client/src/protocol/response.proto
src/compute-client/src/protocol/response.rs
src/compute-client/src/service.rs
src/compute/src/compute_state.rs
src/compute/src/server.rs
src/compute/src/sink/persist_sink.rs
test/testdrive/materialized-view-refresh-options.td

This PR adds a new `output_frontier` to `ComputeResponse::Frontiers`, which is used to report a frontier of times the dataflow has fully processed. This frontier is usable for tracking dataflow progress even for dataflows that jump their write frontier into the future. The new output frontier is then used instead of the write frontier in the hydration status tracking, resolving existing defects we have with `REFRESH` MVs.
Fixes https://github.com/MaterializeInc/materialize/issues/25518
Can we find a better term than "output frontier"? I chose it because it is consistent with the use of "input frontier" as the frontier of times we have finished at the inputs. But perhaps it is too ambiguous?
I think medium-term we want to report the hydration status …

compute: hydration status based on output frontiers

---

src/mysql-util/src/replication.rs

I wrote a bug 😮‍💨 -- this is causing the `is_multi_threaded` flag to always be set to `true` which is enforcing the `replica_preserve_commit_order` even when unnecessary. See the docstring on this method for context on this setting.
-

storage/mysql: fix bad boolean logic causing unnecessary enforcement of 'replica_preserve_commit_order' config

---

doc/user/content/transform-data/troubleshooting.md

We want to add "waiting for hydration" as a query plan insight, and I realized there's nothing in our troubleshooting docs around it currently, so decided to add a section.
-

Docs: Add section in troubleshooting user docs on hydration

---

src/transform/src/reduction_pushdown.rs
src/transform/tests/test_transforms/reduction_pushdown.spec
test/sqllogictest/transform/reduction_pushdown.slt

Fixes #27702
The problem was that `=` has a different meaning in `Join` than in `Filter`: in `Filter` null won't be equal to anything, but in `Join` null is equal to null.
* This PR fixes a recognized bug: #27702
-

Fix null equality handling in ReductionPushdown

---

Cargo.lock
misc/cargo-vet/audits.toml
src/compute/Cargo.toml
src/compute/src/extensions/arrange.rs
src/compute/src/logging.rs
src/compute/src/logging/compute.rs
src/compute/src/logging/differential.rs
src/compute/src/logging/initialize.rs
src/compute/src/logging/reachability.rs
src/compute/src/logging/timely.rs
src/compute/src/typedefs.rs
src/ore/Cargo.toml
src/ore/src/flatcontainer.rs
src/ore/src/lib.rs
src/repr/Cargo.toml
src/repr/src/timestamp.rs
src/timely-util/src/replay.rs

Introduce a `MzContainerized` trait that associates types to regions, while allowing to specify a owned type that is different to `Self`. Switches reachability logging to send flat containers over dataflow edges. Changes `mz_replay` to accept a closure to produce data.
Related: #27741
Part of #13038
-

Introduce MzContainerized, use in reachability logging

---

doc/user/layouts/partials/head.html

This addresses two issues following the Hugo upgrade.
- The `BaseURL` parameter has a trailing slash, so concatenation for favicon paths was generating invalid URLs.
- The `og:url` property was generating duplicated `/docs/docs/` paths. Let's always rely on the permalink.
-

Fix page header URL interpolation following Hugo upgrades

---

ci/deploy/devsite.sh

To help with SEO for our marketing content.
- n/a

ci/deploy: exclude rustdoc from search engines

---

test/pg-cdc/mzcompose.py
test/pg-cdc/override/silent-connection-drop-part-1.td
test/pg-cdc/override/silent-connection-drop-part-2.td

This adds tests for https://github.com/MaterializeInc/materialize/pull/27692.

tests: pg-cdc: resume after silent connection drop

---

src/adapter/src/explain/insights.rs
src/adapter/src/explain/optimizer_trace.rs
test/sqllogictest/explain/plan_insights.slt

adapter: use Name struct for plan insights names

---

ci/builder/Dockerfile

The latest version (v2.17.2) has a weird glitch that causes the website deploy job to occasionally fail to find EC2 instance role credentials. Downgrade to an older version of the AWS CLI that was working properly. Pinning the version in the CI builder is also just a healthy thing to do, so this doesn't change on us unexpectedly the next time we have to rebuild the CI builder image.
- n/a

ci/builder: pin to known good version of AWS CLI

---

test/testdrive/load-generator-key-value.td

testdrive: Disable load generator key value test

---

test/kafka-rtr/simple/verify-rtr.td

Seen in https://buildkite.com/materialize/test/builds/84646
-

Kafka RTR tests: Ignore can respond immediately too

---

src/compute/src/sink/persist_sink.rs
src/persist-client/src/operators/shard_source.rs
src/storage-operators/src/persist_source.rs
src/storage-operators/src/s3_oneshot_sink.rs
src/storage/examples/upsert_open_loop.rs
src/storage/src/decode.rs
src/storage/src/healthcheck.rs
src/storage/src/render/persist_sink.rs
src/storage/src/sink/kafka.rs
src/storage/src/source/generator.rs
src/storage/src/source/generator/key_value.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/mysql/statistics.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/upsert.rs
src/timely-util/src/builder_async.rs
src/timely-util/src/containers/stack.rs
src/txn-wal/src/operator.rs

This PR offers a fueled give API that automatically yields back to timely after certain number of bytes have been emitted into the dataflow. The value is currently capped at 128MB, which is the size of a persist part. This API is only available for operators that make use of `StackWrapper` containers which can accurately track their heap size.
As part of this PR I also made the original `give` and `give_container` methods synchronous. The only reason they were async in the first place was because I had initially envisioned this auto-yield API to be the default and so the async-ness was reserved. Since I no longer think this is a good idea I removed the async keyword.
The diff is big due to the last commit that contains all the removed `.await` calls. Only the changes in `timely-util` need …

timely-util/builder_async: offer automatically yielding give API

---

src/catalog/src/memory/objects.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars/definitions.rs
src/storage-types/src/sources/envelope.proto
src/storage-types/src/sources/envelope.rs
src/storage/src/render/sources.rs
test/testdrive/kafka-upsert-sources.td

Implements the inline-errors component of https://github.com/MaterializeInc/materialize/pull/27540
Partially fixes https://github.com/MaterializeInc/materialize/issues/22430
The linked design doc is not yet ratified so there is a chance the SQL syntax and behavior might need to be adjusted.
-

storage/sources: Add new 'VALUE DECODING ERRORS' option to ENVELOPE UPSERT sources

---

misc/python/materialize/data_ingest/executor.py

Seen in https://buildkite.com/materialize/nightly/builds/8232#019051bf-b62f-4b07-98e7-bb5d985778cf
-

parallel-workload: Fix publication reuse in PG

---

src/adapter/src/client.rs
src/sql/src/session/hint.rs

Was chatting with @materializekatrina about our SLOs and we want to alert on adapter errors from the web console and ideally we'd be able to figure out what the error was. To solve for this we `tracing::warn` adapter errors if the application name is `web_console`. I confirmed with console folks this is internal only queries and `web_console_shell` are user queries from the shell.
At the same time Katrina queried our segment data (which contains all application names) and this PR adds a few of the most common ones we see.
Metrics and SLO
- Improves some internal metrics

adapter: Update application names we log in Prometheus, warn for some adapter errors

---

src/ore/src/channel/trigger.rs

Seen failing in https://buildkite.com/materialize/nightly/builds/8234#01905450-71cd-445f-9ae3-5e39e9d27122
-

miri test: Ignore test_trigger_channel test

---

src/adapter/src/coord/message_handler.rs

Now, they are regular builtin table updates. This will make them easier to work with in future changes where I introduce support for read-only mode in the adapter.
I'm not 100% sure what protections the previous path through `catalog_transact` gave us. But we produce builtin table updates in other places where we don't go through `catalog_transact` and those seem to be fine.
-

adapter: cluster status updates don't go through catalog_transact()

---

src/cloud-api/src/client/cloud_provider.rs
src/cloud-api/src/client/region.rs
src/cloud-api/src/lib.rs
src/mz/src/command/region.rs
src/mz/src/context.rs
src/mz/src/error.rs

I fat-fingered the region name, and mz appeared stuck saying "Retrieving information". After looking at the code I realized it was retrying the request with backoff. This behavior is important for the actual disable request, but the region fetch should fail fast. I also updated the error message and names of functions and the error enum to be more clear.
First mz contribution, all feedback appreciated!
- No user facing changes

mz: faster feedback on invalid region names

---

WORKSPACE
misc/bazel/cargo-gazelle/src/targets.rs

It's relatively common for Rust library targets and binary targets to have the same name, e.g. when you have a `lib.rs` and a `main.rs`. `cargo-gazelle` had some automatic detection for this, but it looks like it broke after the most recent Rust upgrade because Cargo changed from a snake_case default to kebab-case. 
This PR changes the name collision detection to explicitly use snake_case. It also updates the version of Rust that Bazel uses to be the same as the default one we build with.
Fixes `cargo-gazelle`
- N/a

bazel: `cargo-gazelle` fix `rust_binary` name collision, upgrade Rust version

---

src/persist-types/src/parquet.rs
src/repr/src/lib.rs
src/repr/src/relation.rs
src/repr/src/row/encoding2.rs
src/repr/src/scalar.rs
src/storage-types/src/sources.rs

We encode `Row`s in Arrow with a `StructArray`, but Arrow doesn't support a `StructArray` with no fields. To handle this case [we use a `NullArray`](https://github.com/MaterializeInc/materialize/blob/main/src/persist-types/src/dyn_struct.rs#L97) on encode, but on decode we don't consider this case and [always expect a `StructArray`](https://github.com/MaterializeInc/materialize/blob/main/src/persist-types/src/dyn_struct.rs#L241).
This PR adds support for columnar encoding an empty `RelationDesc` in the new columnar encoder at the `SourceData` level. What makes this problem a little tricky is differentiating between an empty `Row` and a null entry. There are two approaches we could take to solve this problem:
1. Handle this in `RowColumnarEncoder`. We could add a special "internal" column …

persist: Handle the special case of columnar encoding an empty `RelationDesc`

---

.github/workflows/slack_notify_design_doc.yml
.github/workflows/slack_notify_mz_introspection.yml
.github/workflows/slack_notify_sql_parser.yml
doc/developer/design/README.md

Must merge this PR in coordination with applying the slack channel name changes, to avoid interruption to the Github Actions.
-

Replace all uses of #epd- slack channels with their new #rnd- names in our docs and github actions

---

src/catalog/src/memory/objects.rs

This confused me when I was looking at catalog code related to source ingestions -- it appears left behind and isn't used anywhere.
-

Remove left behind Ingestion catalog struct

---

ci/builder/Dockerfile
ci/deploy_website/website.sh

Perhaps this will work around the issues we've been seeing withe deploy_website job.
* This PR maybe fixes a recognized bug.
- n/a

ci/deploy_website: try clearing credential cache

---

src/persist-client/src/batch.proto
src/persist-client/src/internal/diff.proto
src/persist-client/src/internal/service.proto
src/persist-client/src/internal/state.proto
src/persist-types/src/stats.proto
src/persist/src/persist.proto

It's come up a few times recently; no harm in adding a warning close to where it matters.
-

[persist] Compat warning for persist protos

---

doc/developer/design/20240609_error_handling.md

Rendered: https://github.com/benesch/materialize/blob/source-errors-design-doc/doc/developer/design/20240609_error_handling.md
I've not been able to spend as much time on this as I hoped, but I promised I'd spill some ink on this subject this weekend. Please pardon any typos or half-finished thoughts. Leaving in draft to better capture the state.
We'll need to find someone else to pick this up—I won't have time to drive the review and iteration on the design myself.
* This PR adds a design doc for a problem that is known to be desirable to solve.
- n/a

design: write design doc for bad data breaking sources

---

ci/builder/Dockerfile

The upgrade to Hugo v0.124.1 in #27679 has broken the deploy_website build. The issue appears to be a bug in the Go AWS SDK version that Hugo v0.124.1 uses that causes credential refreshing to sporadically fail. The latest version of Hugo (v0.128) incoporates a Go AWS SDK upgrade that hopefully fixes the issue.
- n/a

ci/builder: upgrade to Hugo v0.128

---

Cargo.lock
src/storage-types/Cargo.toml
src/storage-types/src/sources.rs
src/storage/Cargo.toml
src/storage/src/source/generator.rs
src/storage/src/source/generator/key_value.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/replication/context.rs
src/storage/src/source/mysql/replication/events.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs
src/timely-util/Cargo.toml
src/timely-util/src/capture.rs
src/timely-util/src/order.rs

This PR makes it so that sources produce collections backed by `StackWrapper<T>` timely containers as opposed to `Vec<T>` containers. The `StackWrapper` container stores its data into flat regions (currently backed by `Columnation`) which allow us to easily measure the heap size of the data produced so far. Currently these container survive until the reclocking boundary where they turn back to normal `Vec<T>` containers in the mz scope. We will probably want to use those region allocated containers throughout the storage dataflows but I didn't want to implement a bigger change than required for this feature.
Creating an output in an async operator with `StackWrapper` container and [the newly introduced](https://github.com/MaterializeInc/materialize/pull/27866) `AccountedStackBuilder` …

storage: use fueled output handles in sources

---

src/persist-types/src/codec_impls.rs
src/persist-types/src/columnar.rs
src/persist-types/src/lib.rs
src/persist-types/src/part.rs
src/persist-types/src/stats.rs
src/persist-types/src/stats/bytes.rs
src/persist-types/src/stats2.rs
src/repr/Cargo.toml
src/repr/benches/row.rs
src/repr/src/adt/jsonb.rs
src/repr/src/lib.rs
src/repr/src/relation.rs
src/repr/src/row/encoding2.rs
src/repr/src/stats2.rs
src/storage-types/src/sources.rs

This PR adds statistics to the `DatumColumnarEncoder` in `repr/src/row/encoding2.rs`, and maintains parity with the existing statistics.
There is two functional changes in this PR.
First is we add a new trait `ColumnarStatisticsBuilder` which allows us to _incrementally_ collect statistics on a column, the only type we do this for at the moment is `jsonb`. Currently to collect stats on a `jsonb` column we decode all of the data through protobuf then collect stats. Incrementally collecting stats while we encode prevents the need to do this.
Second, it makes stats collection eager. This isn't that big of a change because we do always compute stats, this just changes the functional flow a bit.
Progress towards https://github.com/MaterializeInc/materialize/issues/24830
This PR is split into …

persist: Stats for the new Columnar encoders

---

.config/nextest.toml

See https://github.com/MaterializeInc/materialize/issues/27916
-

cargo-test: Bump timeout for all_source_data_roundtrips

---

src/storage-controller/src/collection_mgmt.rs

Fixes #27853
Before, we were assuming that the shutdown code paths can never be reached in production or CI, but that turns out to be wrong: https://github.com/MaterializeInc/materialize/issues/27853
-

storage: in CollectionManager, _do_ gracefully handle shutdown

---

misc/python/materialize/test_analytics/connector/test_analytics_connector.py
misc/python/materialize/test_analytics/data/base_data_storage.py
misc/python/materialize/test_analytics/search/test_analytics_search_logic.py
misc/python/materialize/test_analytics/search/test_analytics_search_source.py

034ae9e294 test analytics: improve logging
b84e099a52 test analytics: log duration of DML statements
d8bbda8e2a test analytics: log duration of queries
4c253a0dd1 test analytics: enable verbose mode for queries for now
8f583586c9 test analytics: search: extract function
b77fb1320b test analytics: search: print duration
a4f531116d test analytics: search: non-verbose mode for queries

test analytics: add logging

---

src/storage-types/src/sources.rs

Otherwise this test timesout in CI
Fix CI timeout
Closes: https://github.com/MaterializeInc/materialize/issues/27916
- N/a

test: reduce test cases for `all_source_data_roundtrips`

---

ci/deploy_website/website.sh
doc/user/config.toml

We already do this ourselves in deploy_website.sh to pick up redirect URLs, and in recent versions of Hugo the CloudFront invalidation inexplicably sporadically fails to refresh AWS credentials.

doc/user: don't use Hugo's CloudFront invalidation feature

---

.config/nextest.toml

Seen in https://buildkite.com/materialize/test/builds/84788#01905aa0-c374-42ea-a74c-3dd9b6d880e9
@jkosh44 Any idea why this would start timing out now?
-

cargo test: Bump timeout for test_smoketest_all_builtins

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/include/materialize/macros/ci/create_cluster.sql
misc/dbt-materialize/dbt/include/materialize/macros/ci/drop_cluster.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/tests/adapter/test_ci.py

Abstracting the cluster create logic into its own macro which can later on be used in CI/CD workflows similar to what has already been outlined in the [dbt-ci-templates](https://github.com/morsapaes/dbt-ci-templates) project.
As a follow-up, we can update the `dbt-cli-templates` project and include an example using these macros for an end-to-end CI workflow.

dbt-materialize: add create/drop cluster macros

---

src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/statement_logging.rs
src/adapter/src/util.rs
src/controller/src/lib.rs
src/storage-client/src/controller.rs
src/storage-controller/src/collection_mgmt.rs
src/storage-controller/src/lib.rs
src/storage-types/src/controller.rs

We don't yet check the read-only bit when writing to tables!
As of this change, components further up the stack are not yet aware of
read-only mode, so they will attempt to write and will then error or
panic. Follow-up commits will introduce read-only mode for those
components as well.
I have a branch that threads read-only mode through more things, and actually makes an `envd` bootable in read-only mode. For reference when reviewing this PR: https://github.com/MaterializeInc/materialize/pull/27841
@MaterializeInc/testing I'm afraid this is not yet testable, only the full thing in https://github.com/MaterializeInc/materialize/pull/27841 will be testable: there you can bring up and environment …

storage: read-only mode for (most of) storage

---

src/compute-types/src/plan/flat_plan.proto
src/compute-types/src/plan/flat_plan.rs
src/compute/src/render.rs

`Let` nodes introduce structure into rendered dataflow graphs, which is valueable for making sense of them, especially when they become large. Previously the `Plan`-to-`FlatPlan` translation would remove `Let` nodes because the flat representation didn't require them. This commit re-introduces them and adds the required corresponding rendering logic.
[Slack discussion.](https://materializeinc.slack.com/archives/C0761MZ3QD9/p1719218068134629)
Closes #27837
-

compute: leave `Let` nodes in `FlatPlan`s

---

src/adapter/src/catalog.rs

Seen in https://buildkite.com/materialize/nightly/builds/8261#01905c0c-70cd-4319-bae3-07a364e8fbd4
-

miri test: Disable test_mz_introspection_builtins

---

src/storage-operators/src/s3_oneshot_sink.rs

When testing compatibility of copy-to-s3 against GCS's XML API which is meant to be API-compatible with the S3 API, we noticed that the GCS API will respond with a 404 if a `DeleteObject` request object does not exist, whereas S3 will respond with a success error code.
From https://cloud.google.com/storage/docs/xml-api/delete-object:
-

storage/copy-to-s3: Allow 404 errors for DeleteObject permissions test returned when using GCS instead of S3

---

ci/test/cargo-test/mzcompose.py
ci/test/pipeline.template.yml

Timeout seen in https://buildkite.com/materialize/test/builds/84858#01905f7a-52f7-468e-b540-ac238ef7a64a
-

ci: Bump cargo-test timeout and reduce flakiness (hopefully)

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/persist-client/src/internal/state.rs

Progress on #16607! In particular, since we're now running only versions with the proper Proto definitions, we can start rolling out the flag by default.
Nightlies: https://buildkite.com/materialize/nightly/builds/8258
-

[persist] Roll out compaction-y flags more widely in CI

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/persist-client/src/operators/shard_source.rs
src/persist-client/src/read.rs
src/storage-client/src/storage_collections.rs

- Now all creators of leased readers can be configured to use the critical handles' since, and all are enabled in CI.
- Fix two lingering issues:
- It's possible for ALTER SOURCE to add subsources that start behind the since of the remap shard, breaking our invariant. This branch advances the since to be past its input's since on collection create, which should always be safe and signals the correct thing to the source pipeline.
- @aljoscha recently added code to restart the persist source in the Kafka sink on an as-of error, but the new check I added was an assert. Switch over to using the cool new error-reporting mechanism.
#26940
There are a ton of different ways to fix the sources issue, but this one seemed like the most principled. It may slow down collection creation, though - I …

[persist] Allow using the critical since across the board

---

test/0dt/mzcompose.py

Seen failing in
https://buildkite.com/materialize/nightly/builds/8260#01905bf7-5892-4aa4-bad3-720e1cd51b68 with "halting process: this deployment has been fenced out"
-

tests: Disable sanity restart in 0dt test

---

bin/gen-chroma-syntax
doc/developer/chroma-syntax-generation.md
misc/python/materialize/cli/gen-chroma-syntax.py

Hugo uses Chroma for syntax highlighting. We upstreamed a Materialize-specific syntax to ensure our dialect's keywords are recognized as such. Now that the end-to-end change is in prod, let's automate the process of generating updates for the dialect lexer.
[I have a PR filed against the Chroma repo](https://github.com/alecthomas/chroma/pull/978) that uses a version of the lexer generated by this script.
- 
no user facing behavior changes

Introduce Chroma syntax-generation script

---

doc/user/content/manage/dbt/_index.md
misc/dbt-materialize/README.md

Adding an example for overriding the `generate_cluster_name` macro, and updating the installation instructions. As of v1.8, `dbt-core` needs to be explicitly installed with any adapter.

doc/user: document `generate_cluster_name` dbt macro

---

Cargo.lock
misc/cargo-vet/audits.toml
test/cloudtest/test_secrets.py
test/kafka-auth/test-kafka-sasl-plaintext.td
test/kafka-auth/test-kafka-sasl-ssl.td
test/kafka-auth/test-kafka-ssl.td
test/testdrive/connection-alter.td

Trying the upgrade to librdkafka v2.3.0 in isolation, on top of the current main.
* This PR upgrades dependencies.
- n/a

deps: upgrade to librdkafka v2.4.0

---

Cargo.lock
src/adapter/src/catalog/open.rs
src/catalog-debug/Cargo.toml
src/catalog-debug/src/main.rs

Previously, the function body of `initialize_state` was wrapped in an async block. For some reason this block broke `rustfmt` and prevented automatic formatting. The async block was used to box the returned future since it was very large, and we didn't want it on the stack.
This commit removes the async block and instead updates callers of `initialize_state` to box the returned future which fixes formatting. In release mode, the optimizer *should* create the future in the heap instead of creating it on the stack and moving it to the heap.
The non-whitespace characters of `initialize_state` are completely unchanged, however the indentation has been changed which makes the diff large.
The diff is much smaller if viewed with whitespace hidden.
- There are no …

catalog: Fix formatting in initialize_state

---

src/compute/src/compute_state.rs
src/compute/src/logging/compute.rs

The dropping of collections happens in two phases, to ensure that dataflow sources can stop reading from the inputs before we announce the relinquishing of their read holds to the controller. Previously this was done by keeping the `CollectionState` alive until `report_dropped_collections`, so that method could inspect the reported frontiers. Keeping the `CollectionState` alive also meant keeping its `CollectionLogging` alive.
This made it possible for two `CollectionLogging` instances to be alive for the same collection after reconciliation. When reconciliation drops and reinstalls a collection, it makes sure that the `AllowCompaction` command is handled before the `CreateDataflow` command. Handling `AllowCompaction` results in a `drop_collection` call, but intentionally not in a …

compute: drop `CollectionState` eagerly

---

src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/error.rs
test/sqllogictest/cluster.slt

Fix "no cluster replicas available" adapter sql hint to be conditional based on managed or unmanaged cluster, as reported in https://github.com/MaterializeInc/materialize/issues/20000#issuecomment-2197198856.
-

Fix "no replicas available" sql hint to be conditional based on managed or unmanaged cluster

---

Cargo.lock
misc/cargo-vet/audits.toml
src/kafka-util/src/client.rs
src/storage-types/src/connections.rs

The last piece of the puzzle for denying connections to local IPs (MaterializeInc/console#1635) is to intercept DNS calls made by librdkafka and reject any DNS responses that contain local IPs.
This commit upgrades to a version of rdkafka that permits overriding the DNS resolution callback in full. The previous version permitted rewriting the hostname and port prior to DNS resolution, but not inspecting the resolved addresses.
Actually wiring up the DNS resolution callback to use the `ore::net::lookup_host` function that rejects local IPs is left to a future commit to ease the review of this commit. There should be no behavior changes as a result of this commit.
~Note to self: depends on merging https://github.com/MaterializeInc/rust-rdkafka/pull/17.~ ✅ 
* This PR makes progress towards a …

deps: upgrade to a rdkafka with DNS resolution callback

---

Cargo.lock
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/cluster.rs
src/controller/src/clusters.rs
src/orchestrator-kubernetes/Cargo.toml
src/orchestrator-kubernetes/src/lib.rs
src/orchestrator-process/src/lib.rs
src/orchestrator-tracing/src/lib.rs
src/orchestrator/src/lib.rs

This PR makes the `ensure_service` and `drop_service` orchestrator calls non-async and non-blocking. It achieves that by introducing an orchestrator task that runs in the background and asynchronously handles requests for creating and removing services.
Fixes https://github.com/MaterializeInc/materialize/issues/17414
Fixes #24813
The diff is unfortunately pretty gnarly, particularly in the second commit. I recommend reviewing with whitespace ignored. The changes to `mz-orchestrator-kubernetes` are actually not that bad, mostly splitting the implementations of the `NamespacedOrchestrator` methods in two and moving parts down into the `OrchestratorWorker`. But somehow the Github diff gets utterly confused about the movement of `get_metrics` and produces a …

orchestrator: move orchestrator calls off the coordinator main thread

---

src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/error.rs
src/controller/src/lib.rs
src/sql/src/plan.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs

The approach, while in read-only mode, is roughly:
- don't do things that we do periodically but don't carry semantic
meaning:
- periodic upper advancement
- stash changes to builtin tables and defer bootstrapping them to when
we come out of read-only mode
- report an error back to the client when attempting things that require
writing: table writes, DDL, things that would change the catalog
The code that allows us to stash changes and come out of read-only mode
gracefully (in process) is not strictly required because we plan on
using the halt!-then-restart (aka. crash-and-burn) approach for coming
out of read-only mode. However, the code was easy enough to add and
might come in handy in the …

adapter/storage: read-only mode for tables

---

src/storage/src/sink/kafka.rs

Now that we're on librdkafka v2.4.0, we don't need to catch and retry QueueFull errors, but can instead disable the queue limit.
This commit is a combination of:
* Reverting the QueueFull workaround from #24871
* Reapplying Petros's original implementation in #24784
- n/a

storage/sink/kafka: prevent queue full by disabling buffering

---

src/adapter/src/catalog/apply.rs
src/adapter/src/catalog/migrate.rs
src/catalog/src/durable/objects.rs
src/catalog/src/durable/objects/serialization.rs
src/catalog/src/durable/transaction.rs
src/storage-client/src/controller.rs
src/storage-client/src/storage_collections.rs
src/storage-controller/src/lib.rs
src/storage-types/src/controller.rs

Refactoring! More efficient and less error-prone to handle (de)serialization at the edges.
There are some comments that suggest that some of these values were meant to be treated as opaque. If this seems too "transparent" I could introduce a newtype wrapper...
-

[skunk] Use typed shard ids instead of bare strings

---

src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/introspection.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/cluster.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/sequencer/inner/explain_timestamp.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/coord/sequencer/inner/secret.rs
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/validity.rs
src/adapter/src/session.rs
src/sql/src/session/user.rs

PlanValidity may be changing in the near future to no longer track anything beyond the transient revision. Refactor places where parts of the plan validity were used for various SQL logic by explicitly requiring and passing that data instead.
- n/a

adapter: disallow using inner PlanValidity fields for SQL logic

---

src/testdrive/src/action/sql.rs
test/testdrive/mzcompose.py

testdrive: Fix auto-rewriting with spaces in strings

---

doc/developer/design/20240411_graceful_reconfiguration_of_managed_clusters_v1.md

Design doc for graceful reconfiguration of managed clusters.
Currently limited to timeout based reconfiguration delay (v1).
https://github.com/MaterializeInc/materialize/issues/20010
-

graceful reconfiguration v1 design doc

---

src/adapter/src/coord/validity.rs

Seen in https://buildkite.com/materialize/nightly/builds/8322#019075c9-59f9-4e83-949f-d394ae5ba847
-

miri test: Disable test_plan_validity test

---

misc/python/materialize/output_consistency/data_type/data_type_category.py
misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/range_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/range_operation_param.py
misc/python/materialize/output_consistency/input_data/return_specs/collection_entry_return_spec.py
misc/python/materialize/output_consistency/input_data/return_specs/range_return_spec.py
misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
misc/python/materialize/output_consistency/input_data/types/range_type_provider.py
misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
misc/python/materialize/output_consistency/input_data/values/range_values_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py

9d54bc0c58 output consistency: generalize DynamicMapValueReturnTypeSpec to CollectionEntryReturnTypeSpec
bd421ed753 output consistency: CollectionEntryReturnTypeSpec: require explicit type source
774624f477 output consistency: list operations: fix return type specification
3fa00e640b output consistency: range type: add type
5fd701ce0a output consistency: range type: add type and return type spec
2019b7471a output consistency: range type: add values
5119d61293 output consistency: range type: add operations
25d8f62b56 output consistency: range type: add ignore
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fsupport-range-type

output consistency: support range type

---

.github/CODEOWNERS

This PR makes the Cluster team a code owner of `/src/adapter/src/coord/introspection.rs`. This file contains the definition of the introspection subscribes, which can affect cluster performance.
* This PR makes changes to CODEOWNERS.
- N/A

CODEOWNERS: make Cluster team an owner for unified introspection code

---

src/adapter/src/catalog.rs
src/adapter/src/coord.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs

This PR makes the compute controller stop holding a reference to the transient ID generator. The reference was added to support creation of introspection subscribes by the compute controller, but we reconsidered and are now creating them in the coordinator instead.
* This PR resolves a leftover TODO.
Part of #26730
- N/A

controller: remove transient_id_gen

---

misc/python/materialize/test_analytics/setup/views/02-build-job.sql

This addresses https://materializeinc.slack.com/archives/C01LKF361MZ/p1719911926469159.
```
materialize=> select * from mz_internal.mz_expected_group_size_advice;
dataflow_id |                   dataflow_name                   | region_id |    region_name     | levels | to_cut |  savings   | hint
-------------+---------------------------------------------------+-----------+--------------------+--------+--------+------------+-------
6           | Dataflow: raw.test_analytics.mv_build_job_success | 753       | ReduceHierarchical |      8 |      4 | 6400884191 | 65535
(1 row)
```
Let's see how much this brings. If the optimization is not sufficient I can also consider reducing the number of collected build predecessors (currently `d.predecessor_index < 10`).

test analytics: materialized views: add query hint to mv_build_job_success

---

src/sql/src/plan.rs
test/0dt/mzcompose.py

A previous change that added an allow-list for queries in read-only mode was too restrictive.
This fixes a problem discovered in
https://github.com/MaterializeInc/materialize/pull/28008.
-

adapter: allow (re-)setting session variables in read-only mode

---

src/controller/src/lib.rs
src/persist-client/src/read.rs
src/storage-client/src/storage_collections.rs
src/txn-wal/src/txn_read.rs

The thing that StorageCollections does which is considered a "write" is
acquiring `SinceHandles`, by bringing them into our own epoch and
downgrading their sinces. We can't be doing that in read-only mode but
we still need a way of holding back frontiers.
The approach is to instead use leased `ReadHandles` while in read-only
mode:
- they _can_ hold back the overall shard frontier, which allows reading
collections, installing dataflows, etc.
- they _can_ time out, in which case things would panic
We would not get into incorrect situations when handles time out.
Clusters would panic, potentially an `environmentd` would panic, but we
can always "restart" our way out of those situations.
We also …

storage: read-only mode for StorageCollections

---

misc/python/materialize/parallel_workload/parallel_workload.py
test/lang/python/smoketest.py

Following https://github.com/MaterializeInc/materialize/pull/27967
Seen in https://buildkite.com/materialize/nightly/builds/8332
-

parallel-workload: Fix id -> connection_id

---

doc/user/content/sql/create-sink/kafka.md

These numbers include a fractional component with microsecond precision, which was not previously clear from the wording.
* This PR improves documentation.
- n/a

doc/user: clarify documentation of timestamp JSON format

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.108.0-dev

---

src/adapter/src/catalog.rs

This commit adds the functionality for a read-only catalog to run
concurrently with a writer catalog, and have the read-only catalog
subscribe to changes made by the writer. The state of read-only catalog
is kept up to date with the durable catalog via the changes.
This functionality is only used in tests currently.

catalog: Add multi-subscriber catalog

---

src/adapter/src/optimize/dataflows.rs
test/cluster/index-source-stuck/run.td
test/sqllogictest/transform/monotonic.slt
test/testdrive/introspection-sources.td
test/testdrive/monotonic.td

Every materialized view has at its output a self-correcting persist sink that reserves the right to insert "corrections" whenever it notices that its output collection differs from the desired state. Across releases this can happen (e.g. when we fix a bug in the optimizer or rendering), so we always need to assume that a persist sink can emit retractions into the MV collection. This makes all MVs non-monotonic, and treating them as monotonic would be a mistake.
-

adapter: always declare MV imports non-monotonic

---

test/cloudtest/test_storage_shared_fate.py

Seen flaking in https://buildkite.com/materialize/nightly/builds/8354#01907af0-211b-4937-919c-517c5b9dc008
-

cloudtest: Await key schema too

---

src/storage-client/src/statistics.rs
src/storage-controller/src/lib.rs
src/storage-controller/src/statistics.rs
test/testdrive/source-statistics.td

Closes https://github.com/MaterializeInc/materialize/issues/26829
cc @RobinClowers 
- N/A

storage: initialize source/sink statistics with zero/null values.

---

misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/range_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/range_operation_param.py

This PR ...
* adds the contains operation for the array and list type
* disables the contains operation for the array and list type to address [failure in nightly/8360](https://buildkite.com/materialize/nightly/builds/8360#01907d83-4877-4dd5-8c8a-c162117df7c0) until https://github.com/MaterializeInc/materialize/pull/28044 is merged
* fixes the specification of the contains and concat operations for the range type (https://github.com/MaterializeInc/materialize/issues/28035 was discovered because the range's type function specification was accidentally applied with lists.)
b035fa90ae output consistency: range: rename RangeLikeOtherRangeOperationParam
8f70874cd1 output consistency: range: fix operation definitions
447103992e output consistency: array and list: add contains operator …

output consistency: contains operation

---

misc/python/materialize/util.py
test/cluster-isolation/mzcompose.py
test/crdb-restarts/mzcompose.py
test/pubsub-disruption/mzcompose.py
test/replica-isolation/mzcompose.py
test/source-sink-errors/mzcompose.py

tests: Support running a subset of disruptions

---

test/cloudtest/test_storage_shared_fate.py

Reverts MaterializeInc/materialize#28041
Apparently this didn't work, I'm still not sure why the test is failing now though.

Revert "cloudtest: Await key schema too"

---

test/sqllogictest/materialized_views.slt
test/testdrive/materialized-view-refresh-options.td

Moves a flaky slt test to td, where it will be retried.
* This PR fixes a test flake, discussed here: https://materializeinc.slack.com/archives/C0761MZ3QD9/p1720098448900609?thread_ts=1720097407.946299&cid=C0761MZ3QD9
-

De-flake a REFRESH introspection test

---

Cargo.lock
src/balancerd/Cargo.toml
src/balancerd/src/main.rs

Bring balancerd into alignment with our other production binaries and use jemalloc by default on Linux.
- n/a

balancerd: enable jemalloc

---

test/replica-isolation/mzcompose.py

The c.overwrite would make us lose them, see also discussion in https://materializeinc.slack.com/archives/C0761MZ3QD9/p1720102448448759
-

tests: Keep clusterd logs in replica-isolation test

---

src/storage-types/src/dyncfgs.rs
src/storage/src/source/kafka.rs

This commit fixes a flake observed in the source-sink-errors test
(#28016).
Here's what was happening:
* The source would read the message with offset 1 from Kafka.
* The source would emit the message to its data output.
* The test would turn Redpanda off.
* librdkafka would notice the broken connection and, incorrectly,
redeliver the message with offset 1. (This is a known problem with
librdkafka, and something the code already protects against.)
* The source would seek to offset 2, thus marking its position within
librdkafka as "invalid".
* The source would fail to downgrade its capability to offset 2
because librdkafka was no longer reporting a valid offset.
* The test would turn Redpanda on.
* librdkafka would successfully reconnect but not update the offset
for the partition.
* The …

storage/source/kafka: don't seek

---

doc/user/content/sql/copy-to.md
src/pgcopy/src/copy.rs
src/pgcopy/src/lib.rs
src/storage-operators/src/s3_oneshot_sink/pgcopy.rs
test/testdrive/copy-to-s3-minio.td

We were ignoring the `header` option for the CSV format option in copy-to-s3. This fixes the docs since the header is default-off and fixes the implementation to write a header row when `header = true` is provided.
-

storage/copy-to-s3: Support including a header on csv files if specified

---

src/storage/src/source/kafka.rs

Since 3ae934db81, we no longer fast forward. We just skip messages one at a time. Correct a comment that was claiming otherwise.
h/t @rjobanp for the eagle eyes
* This PR fixes a stale comment.
- n/a

storage/source/kafka: correct stale comment about fast forwarding

---

src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/catalog/src/durable.rs
src/catalog/src/durable/persist.rs
src/catalog/tests/read-write.rs
src/sql/src/session/vars/definitions.rs

This commit removes the unused server configuration parameter, "wait_catalog_consolidation_on_startup". This was used for the legacy stash catalog implementation.

catalog: Remove unused server config param

---

src/environmentd/src/test_util.rs

This addresses https://buildkite.com/materialize/nightly/builds/8396#0190921c-c663-401b-ba11-3b4682ef7c3a.
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Ffix-miri

tests: fix miri compilation

---

doc/user/layouts/shortcodes/json-parser.html

This PR updates the JSON to SQL widget to replace characters "special characters", i.e. anything not in the character class `[a-zA-Z _]` with an `_`. It then de-dupes column aliases by appending a number. For example:
```
{
"%foo": 1,
"^foo": 1
}
CREATE VIEW my_view AS SELECT
(json_column->>'%foo')::numeric AS _foo,
(json_column->>'^foo')::numeric AS _foo1
FROM my_source;
```
Fixes https://github.com/MaterializeInc/materialize/issues/27995
- Updates the JSON to SQL widget to better handle special characters

docs: Handle special characters in JSON to SQL widget

---

src/ore/src/tracing.rs

Any errors returned by MySQL are automatically logged at the error level in the `mysql_async` crate, which is causing them to be reported to Sentry. The library already bubbles up the errors such that we handle them in our code appropriately.
In this specific instance we are seeing sentry errors (https://materializeinc.sentry.io/issues/5518110161/?project=6780145) for a query that we know will error on older versions of MySQL and are handling ourselves:
https://github.com/MaterializeInc/materialize/blob/81a865349c7d1acf0c7a279f0bd3733420718cc5/src/mysql-util/src/replication.rs#L66-L73
As far as I can tell we are not overriding the `SENTRY_FILTERS` system variable anywhere else, so it should be based on this `SENTRY_DEFAULTS` vector, but if either of you are aware of some other place I …

storage/mysql: Disable sentry errors from noisy mysql_async crate

---

src/adapter/src/catalog/open.rs
src/catalog/src/durable.rs
src/catalog/src/durable/persist.rs
src/catalog/src/memory/objects.rs
src/catalog/tests/read-write.rs

Previously, storage usage pruning worked by taking the following steps:
1. Durably write retractions for old storage usage events.
2. Listen for all changes to the durable catalog.
3. Generate builtin table updates from the changes.
This approach does not work for savepoint catalogs, because they only pretend to write things durably but don't actually commit the write. Therefore, listening for changes always returns an empty result. This commit fixes the issue by returning the updates from the durable transaction before commit. This matches the behavior of all other catalog writes.
While we're modifying storage usage pruning, the read-only case is optimized to return immediately.
This commit has the added benefit that read-only and savepoint catalogs will not see unrelated updates in step …

catalog: Fix savepoint storage usage pruning

---

src/repr/src/explain.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql/src/plan/statement/dml.rs

https://github.com/MaterializeInc/materialize/pull/28018 added a feature flag, but forgot to wire it up to EXPLAIN. This PR does this.
Additionally, it removes the blanket default initializer `..Default::default()`, so that this can't happen in the future with new flags.
* This PR wires up an already-existing feature flag to EXPLAIN.
-

Wire up `enable_outer_join_null_filter` to `EXPLAIN`

---

test/sqllogictest/transform/fold_constants.slt
test/sqllogictest/window_funcs.slt

This PR does 3 things (in 3 commits):
1. Adjust `window_funcs.slt` to not run window functions on constant inputs. Running them on constant inputs executes the window functions on different code paths, because constant folding kicks in early in the optimizer pipeline. These are straightforward changes: just replacing the constant cte with an actual table.
2. Copy-paste the constant-input version of the tests to `fold_constants.slt`, so that we keep testing also the constant folding code path for window functions.
3. Uncomment an old test and adjust some comments.
* This PR adjusts window function testing.
-

Adjust window func tests

---

src/catalog/src/durable.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/transaction.rs
src/catalog/tests/read-write.rs

Savepoint catalogs are able to accept writes without erroring, but the writes are never committed durably. The main usage of savepoint catalogs is to validate an upgrade in-memory before actually executing the upgrade.
Previously, savepoint catalogs would update their in-memory state based on the savepoint transactions committed by themselves AND by listening to durable changes made by any writer catalog. This is NOT correct because there is no attempt to check for conflicts or reconcile the writes made by the two separate catalogs.
This commit fixes the issue by ignoring all durable catalog updates in savepoint catalogs after the initial snapshot. A correct mental model for this is that creating a savepoint catalog is like creating a new branch of catalog state. This branch does not …

catalog: Fix savepoint catalog listen behavior

---

WORKSPACE
misc/bazel/c_deps/rust-sys/BUILD.decimal.bazel
misc/bazel/c_deps/rust-sys/BUILD.decnumber.bazel

This PR adds a `BUILD.decnumber.bazel` file to build the libdecimal C dependency with Bazel.
Building libdecimal with Bazel means we'll get better caching and optimizations like specifying the CPU type or cross language inlining, "for free".
- N/a

bazel: Build `decnumber-sys`

---

src/sql/src/func.rs

The `has_cluster_privilege` function errors through `mz_unsafe.mz_error_if_null`, but it then uses the result in an `IS NULL` test, which is able to be optimized away (as `mz_unsafe.mz_error_if_null` cannot return `NULL`).
This PR changes the logic to test the condition explicitly and error if the test fails, rather than rely on the optimizer not noticing that the potentially erroring test can be pruned.
-

Rework `has_cluster_privilege` to error intentionally

---

doc/user/content/sql/types/list.md
doc/user/layouts/shortcodes/list-operators.html

Add documentation for `@>` and `<@` introduced in #27959

user/docs: add documentation for @> and <@ for lists

---

misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/mzcompose/composition.py
test/cluster-isolation/mzcompose.py
test/cluster/mzcompose.py
test/cluster/pg-snapshot-partial-failure/02-create-sources.td
test/cluster/pg-snapshot-resumption/02-create-sources.td
test/cluster/sink-failure/01-configure-sinks.td
test/feature-benchmark/mzcompose.py
test/get-cloud-hostname/mzcompose.py
test/limits/mzcompose.py
test/pg-cdc/mzcompose.py
test/rqg/mzcompose.py
test/scalability/mzcompose.py
test/source-sink-errors/mzcompose.py
test/version-consistency/mzcompose.py

As the documentation notes:
> Lest you are tempted to change this function to allow dynamically
> injecting new services: do not do this! These services will not be
> visible to other commands, like `mzcompose run`, `mzcompose logs`, or
> `mzcompose down`, which makes debugging or inspecting the composition
> challenging.
Following a discussion in https://materializeinc.slack.com/archives/C0761MZ3QD9/p1720102448448759
-

mzcompose: Check for service existence when overriding

---

misc/python/materialize/cli/ci_annotate_errors.py

A newline character got lost in https://github.com/MaterializeInc/materialize/pull/28098.

ci: annotate errors: fix layout

---

misc/python/materialize/output_consistency/execution/query_execution_manager.py
misc/python/materialize/output_consistency/generators/expression_generator.py
misc/python/materialize/output_consistency/generators/query_generator.py
misc/python/materialize/output_consistency/operation/operation.py
misc/python/materialize/output_consistency/output/output_printer.py
misc/python/materialize/output_consistency/output_consistency_test.py
misc/python/materialize/output_consistency/runner/test_runner.py
misc/python/materialize/output_consistency/status/consistency_test_logger.py
misc/python/materialize/output_consistency/status/test_summary.py
misc/python/materialize/output_consistency/validation/result_comparator.py
misc/python/materialize/output_consistency/validation/validation_outcome.py

This helps to identify operations and functions that were not part of any successfully executed query. These operations and functions may have an incorrect specification. This was for example the case in https://github.com/MaterializeInc/materialize/pull/28089/commits/af680d428f8c59f5b97404d98a3a65b9a091435a.
Furthermore, this PR improves statistics by differenting between different variants of the same functions that differ in the number of parameters.
94f95a5a7b output consistency: statistics: split and move files
52ef385d50 output consistency: statistics: use dataclasses
5a68eb9c96 output consistency: statistics: move collection of generation result
8964cfa0b8 output consistency: expression generation: number of args decision
**02bdd92357 output consistency: statistics: collect info …

output consistency: improve statistics

---

src/storage/src/metrics/sink/kafka.rs
src/storage/src/sink/kafka.rs

We want a metric that reveals whether compaction is working on users' progress topics.
The outstanding_progress_records metric is close, but the low water mark of a topic may get stuck arbitrarily far in the past if a sink is dropped, so the delta between a progress topic's high and low water marks is not a good measure of whether a user has enabled compaction.
Instead, introduce a consumed_progress_records metric, which directly records the number of messages in a progress topic for each sink. If this number ever ticks up into the hundreds of thousands or millions, that is a clear sign that compaction is not working.
* This PR adds a known desirable feature.
- n/a

storage/sink/kafka: record number of consumed progress records

---

test/aws/mzcompose.py

This addresses
```
botocore.errorfactory.LimitExceededException: An error occurred (LimitExceeded) when calling the CreateRole operation: Cannot exceed quota for RolesPerAccount: 1000
```
observed in [nightly/8417](https://buildkite.com/materialize/nightly/builds/8417#019094af-8f5d-403c-9dcd-487207e70ab1).
I did a manual cleanup using `list_roles` and `delete_role` to delete all roles having a name starting with `testdrive-` (https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aaws%2Fcleanup).
https://buildkite.com/materialize/nightly/builds/8432 ✅

tests: aws-real: cleanup aws roles after test

---

misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/cli/mzcompose.py
misc/python/materialize/mzcompose/test_result.py

This is the base for https://github.com/MaterializeInc/materialize/pull/28067.
e5b6de2da0 ci: junit.xml: store additional details
cbb2684333 ci: annotate errors: make error message not nullable
31b87213e6 ci: annotate errors: extract functions
d035b2ebd8 ci: annotate errors: minor
6dbfce9e1c ci: annotate errors: include additional details in annotations
The section will be collapsed by default.

ci:annotate errors: support additional collapsible section for further details

---

misc/python/materialize/mzbuild.py

Reported in https://materializeinc.slack.com/archives/C01LKF361MZ/p1720469094875789
-

mzbuild: Print output on failure

---

src/balancerd/src/main.rs
src/clusterd/src/bin/clusterd.rs
src/environmentd/src/bin/environmentd/main.rs

This PR changes the error behavior of the Mz binaries to panic instead of printing to stderr and then exiting. This is to ensure that these errors end up in Sentry and we don't miss them.
[Relevant Slack thread.](https://materializeinc.slack.com/archives/CTESPM7FU/p1720468349254209)
When a binary, like `environmentd`, encounters an error that gets bubbled up to its `main` function, it exists the process in a way that prevents Sentry from observing the error.
- N/A

binaries: panic in response to errors in `main`

---

doc/developer/design/00000000_template.md
doc/developer/design/20231027_refresh_every_mv.md
doc/developer/design/20231027_refresh_mvs.md

This is a design document for the `REFRESH` feature for materialized views.
Overall tracking issue: https://github.com/MaterializeInc/materialize/issues/26010
[Rendered.](https://github.com/ggevay/materialize/blob/refresh-every-design-doc/doc/developer/design/20231027_refresh_mvs.md)
TLDR: Users should be able to configure materialized views to compute result changes less frequently, but cheaper. It turns out that we can do this by simply
- turning on a replica only when we want a result refresh, and
- rounding up the timestamps of data and frontiers that go into the Persist sink to the time of the next result refresh.
Explained in the design doc. Note that [there is a major customer](https://materializeinc.slack.com/archives/C053EPHMU05/p1698173967255099) who needs this feature ASAP.
-

Design doc for `REFRESH` MVs

---

src/catalog/src/durable/persist.rs

This commit is a followup to cef629e91d81eab91a7f200e7e72c056d8fabe27 that adds the following fixup features:
- Commits in savepoint catalogs increment the in-memory catalog upper. This isn't strictly necessary in savepoint mode since the upper isn't used for anything, however it matches the behavior of write mode.
- Sync sets the current upper to the max of the target upper and the current upper, instead of blindly setting it to the target upper. This protects against a caller trying to sync in the past and causing the upper to decrease, which should be impossible. There is no current code path where a caller would pass a timestamp less than the current upper, but it's better to protect against it.

catalog: Fixup savepoint catalog commit and sync

---

doc/user/content/_index.md
doc/user/content/get-started/quickstart.md
doc/user/content/ingest-data/webhook-quickstart.md

Various copyedits to trial account references in our user docs:
- Sometimes, we don't specifically mention that it's a free trial account but just a Materialize account.
- Sometimes referred to as playground account
See https://github.com/MaterializeInc/materialize/issues/28071
Changes:
- Update playground account/account to free trial account.
- Remove reference to upgrading playground account to trial account since only trial account.
- Somewhat unrelated but ... fix small typo in quickstart SQL statement.

Docs: copyedits trial account statements

---

src/storage-client/src/storage_collections.rs

This commit prevents shard finalization in read-only mode. Read-only mode should not affect changes to external systems. Previously, if a shard was present in the unfinalized/finalizable shard list on a read only instance, which could happen as a result of a well-timed startup, the read-only instance would attempt to forcibly downgrade the shard's upper and since and finalize the shard.
Works towards resolving #27981

storage: Prevent finalization in read-only mode

---

src/storage-types/src/errors.rs
src/storage/src/source/mysql.rs
src/storage/src/source/postgres.rs

A user was confused about recoverability when encountering a DefiniteError in a MySQL source due to an invalid system configuration. This PR updates the error string to indicate that source DefiniteErrors cannot be retracted and will require a source to be dropped and recreated.
-

storage/sources: Update definite error messaging to indicate source must be recreated to user

---

test/testdrive/source-statistics.td

Because the environment is not reset between testdrive runs, and we are querying retained-metrics collections with `AS OF AT LEAST 0`, there is a risk that we are seeing contents from previously run testdrive files. Avoid this possibility by using a unique name for the load generator source we filter on.
`source-statistics.td` is flaky: https://buildkite.com/materialize/nightly/builds/8406#01909368-2a7c-4932-ac32-463f8e28a97e
Not sure how to reproduce the flake, so this fix might or might not be the correct one to prevent the flake.
- N/A

test: attempt to deflake source-statistics.td

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml
misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/mzcompose/services/materialized.py
test/0dt/mzcompose.py

This is largely following https://materializeinc.slack.com/archives/C058H9MH8P3/p1719925704433379?thread_ts=1719921187.025859&cid=C058H9MH8P3
This is still with long hydration after restart since we don't have https://github.com/MaterializeInc/materialize/pull/27997 yet. After that lands could check if hydration has already occurred.
I'll work on platform-checks and parallel-workload support next.
-

Explicit 0dt upgrade test

---

misc/python/materialize/output_consistency/execution/query_execution_manager.py
misc/python/materialize/output_consistency/output/base_output_printer.py
misc/python/materialize/output_consistency/output/output_printer.py
misc/python/materialize/output_consistency/output/reproduction_code_printer.py
misc/python/materialize/output_consistency/status/test_summary.py
misc/python/materialize/output_consistency/validation/validation_outcome.py

e54c0dcabc output consistency: output printer: allow redirecting output to collection
369d124d3b output consistency: output printer: provide reproduction code as string
b6d1db5982 output consistency: junit.xml: provide reproduction code
dab909d8e3 output consistency: improve output
https://buildkite.com/materialize/nightly/builds/8447

output consistency: provide reproduction code in collapsible part of annotation

---

doc/user/content/sql/alter-sink.md
doc/user/content/sql/create-sink/_index.md
src/sql/src/plan/statement/ddl.rs
test/testdrive/alter-sink.td

This commit prohibits users from creating sinks directly on catalog objects. Sinks sink out all columns of an object, but builtin migrations may cause the set of columns of a builtin object to change. So after an upgrade a sink may start emitting additional columns, which has the potential to break whatever is downstream. Until this issue is fixed it's better to prohibit sinking catalog objects, than to potentially have sinks break after an upgrade.
As a workaround, users can create materialized views over a catalog object and sink the materialized view. Though it's likely to be rare that a user wants to sink catalog objects directly.
Additionally, prohibiting this feature makes certain aspects of zero-downtime upgrades easier with respect to builtin migrations.
Works towards resolving …

adapter: Prohibit sinks on catalog objects

---

src/postgres-util/src/replication.rs
src/postgres-util/src/schemas.rs
src/sql/src/pure.rs
src/sql/src/pure/postgres.rs
src/storage-types/src/sources/postgres.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs

The first commit refactors postgres source purification to share the same client connection across the various methods that verify postgres settings and permissions.
The second commit pulls all the common postgres logic used in both `purify_create_source` and `purify_alter_source` methods into a shared method in the `pure::postgres` module. This new structure matches what we did for the MySQL logic here https://github.com/MaterializeInc/materialize/pull/27416/commits/96e904f22c2d8badca33294ba6e3ea6f9d63611a and should help simplify my next task to refactor subsource planning. There should be no functional differences with this commit.
-

storage/postgres: Clean up postgres purification

---

misc/python/materialize/cli/ci_annotate_errors.py
src/transform/src/lib.rs

In https://github.com/MaterializeInc/materialize/pull/27977 we removed erroring behavior from the `Fixpoint` transform when we detect a cycle, but it seems there is no fundamental reason to error even when we do not detect a cycle (and just run out of iterations).
-

Remove erroring behavior when transform fixedpoint not found

---

Cargo.lock
ci/nightly/pipeline.template.yml
misc/python/materialize/checks/scenarios.py
misc/python/materialize/parallel_workload/action.py
src/persist-cli/Cargo.toml
src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/Cargo.toml
src/persist-client/src/batch.rs
src/persist-client/src/fetch.rs
src/persist-client/src/stats.rs
src/persist-types/src/codec_impls.rs
src/persist-types/src/columnar.rs
src/persist-types/src/lib.rs
src/persist-types/src/stats.proto
src/persist-types/src/stats.rs
src/persist-types/src/stats/bytes.rs
src/persist-types/src/stats/primitive.rs
src/persist-types/src/stats/structured.rs
src/persist/src/indexed/columnar.rs
src/persist/src/indexed/columnar/arrow.rs
src/persist/src/indexed/columnar/parquet.rs
src/persist/src/indexed/encoding.rs
src/repr/Cargo.toml
src/repr/benches/packed.rs
src/repr/src/adt/timestamp.rs
src/repr/src/row/encoding2.rs
src/repr/src/stats2.rs
src/storage-types/src/sources.rs
src/storage-types/src/stats.rs

This PR adds a "V2" of columnar encoding to Persist, behind the dyncfg `persist_batch_columnar_format` with the value `both_v2`.
Note: today we have a "V1" columnar encoding which encodes non-trivial types (e.g. Array or JSON) into its `ProtoDatum` representation. This PR uses the new encodings introduced in https://github.com/MaterializeInc/materialize/pull/27084 which don't rely on `ProtoDatum` at all.
These changes are in commit 2.
With the new columnar encodings, the types we persist for some statistics have changed, e.g. for columns of type `Timestamp` we collect `PrimitiveStats<i64>` instead of `AtomicByteStats`. To handle this change we introduce a new method on [`RelationPartStats`](https://github.com/MaterializeInc/materialize/blob/main/src/storage-types/src/stats.rs#L34), `fn …

persist: Columnar Encoding V2

---

src/expr/src/lib.rs
src/expr/src/relation.rs

Our `MirRelationExpr`s have historically had stack overflow challenges, and we've steered away from methods that might overflow. I *think* one example is `PartialEq::eq`, among others (pretty much everything we derive?). So, this tries out using a form of structured diffing to support a stack-free equality test, as well as providing the basis for other comparisons (`PartialOrd` and `Ord`, except they are tedious to write without a derived implementation).
One thing this calls out is that our approach to ASTs which commingles the tree structure (e.g. `input`) with the AST node structure .. is annoying. It's also annoying for flat representations which would prefer to pivot the representation. Perhaps we should revisit this and have a abstract AST generic over node metadata, which would …

Use structured diff for MRE equality

---

misc/python/materialize/mzcompose/composition.py

```
WARN[0000] /dev/fd/3: `version` is obsolete
```
-

mzcompose: Don't use deprecated version

---

misc/python/materialize/cli/ci_annotate_errors.py

Otherwise we might never hear about them since the run probably fails anyway because an actual test/problem issue. See https://materializeinc.slack.com/archives/C01LKF361MZ/p1720648897088559
-

ci annotations: Ignore empty XML files & warn about failed runs

---

misc/python/materialize/zippy/scenarios.py

zippy: Try reenabling Sinks in KafkaSourcesLarge

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios.py
misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/checks/scenarios_zero_downtime.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/settings.py
test/platform-checks/mzcompose.py

with two Mz instances running in parallel during upgrade
-

platform-checks: Add zero-downtime upgrade scenarios

---

misc/python/materialize/parallel_workload/action.py

parallel-workload: Disable mysql sources

---

ci/nightly/pipeline.template.yml

ci: Try parallel-workload with 50 threads on large agent

---

.gitignore

This should also help with fingerprinting
-

git: Ignore protobuf-bin/include directories

---

doc/developer/design/20231027_refresh_mvs.md
doc/user/content/sql/alter-cluster.md
doc/user/content/sql/create-cluster.md
doc/user/content/sql/create-materialized-view.md
doc/user/content/sql/system-catalog/mz_internal.md
misc/dbt-materialize/dbt/include/materialize/macros/ci/create_cluster.sql
misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
misc/dbt-materialize/tests/adapter/test_ci.py
misc/dbt-materialize/tests/adapter/test_deploy.py
src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/coord/cluster_scheduling.rs
src/audit-log/src/lib.rs
src/catalog/src/builtin.rs
src/catalog/src/durable/objects/serialization.rs
src/catalog/tests/read-write.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
test/sqllogictest/autogenerated/mz_internal.slt
test/sqllogictest/materialized_views.slt
test/testdrive/materialized-view-refresh-options.td

Discussed with Marta and Nikhil [here](https://materializeinc.slack.com/archives/C075QPD99PV/p1720532814941859?thread_ts=1720530181.988819&cid=C075QPD99PV).
This changes the `REHYDRATION TIME ESTIMATE` cluster option to `HYDRATION TIME ESTIMATE`. The parser still accepts the old version. Eventually, the old version will be completely removed, once users move to the new version. They'll move to the new syntax automatically when they start using a new dbt adapter version. Created an issue: https://github.com/MaterializeInc/materialize/issues/28140
I think I changed the dbt adapter (`misc/dbt-materialize/dbt/include/materialize/macros/ci/create_cluster.sql`). @morsapaes, can you confirm?
(I changed the `mz_internal.mz_cluster_schedules.refresh_hydration_time_estimate` column. This is in …

Change `REHYDRATION TIME ESTIMATE` to `HYDRATION TIME ESTIMATE`

---

src/adapter/src/coord/introspection.rs
src/repr/src/fixed_length.rs
src/storage/src/render/sources.rs
src/transform/src/fold_constants.rs

Instead of decoding and encoding each `Row` entry, directly copy the entire `Row` into a `RowPacker` where possible. 
Fixes #27976 
* Are there any specific tests to run for these changes?
-

RowPacker: directly copy Rows instead of using iterators

---

misc/python/materialize/parallel_workload/action.py

See https://github.com/MaterializeInc/materialize/issues/28166#issuecomment-2222581726
-

parallel-workload: Don't drop cluster replicas

---

src/storage-types/src/dyncfgs.rs
src/storage/src/healthcheck.rs
src/storage/src/render.rs
test/kafka-auth/test-schema-registry-ssl-basic.td

https://github.com/MaterializeInc/materialize/issues/26139 + https://github.com/MaterializeInc/cloud/issues/8965 have the full context, but the tl;dr is that sources can take a long time reconnect after momentary network blips. This means <1s of network downtime can turn into >60s of actual source/sink unavailability. One of the primary sources of downtime is the fixed 30s `SUSPEND_AND_RESTART_DELAY`.
This PR makes two small changes to this knob:
1. Makes it configurable
2. Drops the default to 5s, down from 30s
A more advanced solution would be using exponential backoff, but it's not quite clear to me how to make that work within the healthcheck operator. Tossing this up as a proposal, and will let a member of @MaterializeInc/storage determine whether it's sufficient 😄 
In part addresses …

storage: make suspend and restart delay configurable, drop to 5s from 30s

---

src/sql/src/session/vars/constraints.rs
src/sql/src/session/vars/definitions.rs
test/launchdarkly/mzcompose.py
test/sqllogictest/max_result_size.slt
test/sqllogictest/persist-fast-path.slt
test/sqllogictest/updates.slt
test/testdrive/oom.td

This PR enforces a lower bound of 1MB for the `max_result_size` parameter. This parameter is meant to prevent environmentd OOMs and should therefore be set to a value proportional to environmentd's available memory size. It's save to assume that we'll never try to run environmentd with available memory in the order of megabytes.
Enforcing a lower bound ensures that nobody can accidentially set `max_result_size` to a value that is small enough to interfere with system queries, like introspection subscribes or those performed by our metrics infrastructure.
Fixes #28113 
-

adapter: enforce a lower bound for max_result_size

---

misc/python/materialize/output_consistency/generators/expression_generator.py
misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/record_operations_provider.py
misc/python/materialize/output_consistency/input_data/params/any_operation_param.py
misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
misc/python/materialize/output_consistency/input_data/params/same_operation_param.py
misc/python/materialize/output_consistency/validation/error_message_normalizer.py
misc/python/materialize/output_consistency/validation/result_comparator.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py

This actually enables the record type; it was not really active before because the value generation had failed.
76a615638d output consistency: record type: fix function definitions
856f273da2 output consistency: record type: extend record field param
cb7df343dd output consistency: record type: disable .* on row(...)
3e9c4c251c output consistency: record type: normalize error messages
4e38f99791 output consistency: record type: allow disabling record in AnyOperationParam
1323c80874 output consistency: add matcher function variant
ae9211cfcf output consistency: introduce SameOperationParam
0b4fb964b4 output consistency: order string_agg, array_agg, and map_agg additionally by the value itself
b7b4b274eb output consistency: value comparison: compare tuples value by value
ed4af0ebc9 postgres …

output consistency: record type: fix function definition, add ignore entry

---

src/ore/src/lgbytes.rs
src/persist-client/src/batch.rs
src/persist/src/indexed/columnar.rs
src/persist/src/indexed/columnar/arrow.rs
src/persist/src/workload.rs
src/repr/src/row/encoding2.rs
src/storage/examples/upsert_open_loop/workload.rs

- Allow shifting arrow arrays to lgalloc-backed storage.
- Switch to using arrow abstractions instead of lgalloc-flavoured abstractions in `ColumnarRecords` using the new helpers.
Known desirable: https://github.com/MaterializeInc/materialize/issues/27571
In particular, using these for `ColumnarRecords` avoids some conversion costs and some duplicate validations. (Some of the properties we manually validated are guaranteed in arrow by construction.)
The main incentive is to allow re-allocating `StructArrays` and other complex types, but I plan to leave that for a future PR.
Nightlies: https://buildkite.com/materialize/nightly/builds/8437#_. Any errors also seem to happen on `main`.
-

[persist] Reallocate arrow arrays via lgalloc and use them in ColumnarRecords

---

src/persist-client/src/stats.rs
src/persist-types/src/lib.rs

This PR updates the `encode_updates(...)` function to re-use instances of `K` and `V` when calculating stats, which reduce allocations and through benchmarking is shown to improve performance.
Improves throughput of Persist encoding.
- N/a

persist: re-use allocations when computing stats

---

doc/user/content/sql/create-source/kafka.md
src/storage-types/src/sources/envelope.rs
src/storage/src/render/sources.rs
test/testdrive/kafka-upsert-sources.td

This is a follow-on to https://github.com/MaterializeInc/materialize/pull/27802, as discussed in https://github.com/MaterializeInc/materialize/issues/28127, to switch back to flattening the value schema into the top-level of the source to remain consistent with normal upsert source semantics.
NOTE that with this implementation source creation will error if the value or key contain a column named `error` and there is no way to modify that column name. I will add an option to configure this but since I'm OOO tomorrow I figured we could potentially get this in ahead of time to make it in for the release cut. If we don't merge in time, I'll just add the rename option to this PR.
-

storage/sources: Flatten values when using the value decoding errors inline option

---

doc/user/content/transform-data/dataflow-troubleshooting.md

See comment in https://github.com/MaterializeInc/console/issues/1127#issuecomment-2216922251.
Removes inaccurate guidance that restarting a cluster will force a re-plan after dropping an index. It turns out the coordinator is what needs to restart, which the user cannot control.

Update orphaned dataflow docs to remove inaccurate information

---

Cargo.lock
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

release: bump to version v0.109.0-dev

---

src/transform/src/analysis.rs
src/transform/src/threshold_elision.rs
test/sqllogictest/transform/threshold_elision.slt
test/sqllogictest/transform/union_cancel.slt

Our `threshold_elision.rs` transform uses the `NonNegative` analysis, but adds a bit more. That bit more could just be part of the `NonNegative` analysis, simplifying the threshold elision transform. Once simplified, we no longer need the ability to mutate derived analysis results.
The prior behavior should be preserved, but I think it has a bug. The `is_superset_of` function should require `lhs` be non-negative for some of its rules, but we only verify it for the `lhs` with which it first gets called (which isn't strictly required). I think we should fix this too, but I'm starting with a direct translation of the existing logic.
-

Consolidate threshold elision logic into `NonNegative` analysis

---

misc/python/materialize/cli/ci_annotate_errors.py

In Python RE . doesn't match newlines, but ^ does. https://docs.python.org/3/library/re.html#re.MULTILINE
-

ci annotations: Fix regex for RESULT COMPARSION ISSUE

---

misc/python/materialize/parallel_workload/parallel_workload.py

parallel-workload: Try failing on stuck queries (except in rename scenario)

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/open.rs
src/adapter/src/coord.rs
src/catalog/src/builtin.rs
src/storage-client/src/storage_collections.rs
src/storage-controller/src/lib.rs

One of the responsibilities of StorageCollectionsImpl::initialize_state is to take all the global IDs known by the adapter catalog and ensure that it is included in the storage metadata. Previously, there was an assert that asserted that all IDs known by the catalog but not known by storage MUST be system objects. The likely intuition of this assert is that catalog data and storage metadata are always updated atomically, so any IDs not know by storage must be new system objects added as part of a version upgrade. However, this is not correct. Builtin item migrations may also create new user objects (after dropping the old ones).
This commit removes the assert, which is not always correct as described above. Investigation into the surrounding code seems to indicate that this assertion was …

storage: Remove invalid assert from startup

---

src/adapter/src/catalog/apply.rs

This commit improves the error message associated with invalid persisted SQL to print the SQL.

catalog: Improve invalid SQL error message

---

src/adapter/src/coord/sequencer/inner/cluster.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/names.rs
src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/with_options.rs
src/sql/src/rbac.rs
src/sql/src/session/vars/definitions.rs

The SQL implementation for v1 of graceful reconfiguration
https://github.com/MaterializeInc/materialize/issues/20010
This is was originally part of https://github.com/MaterializeInc/materialize/pull/27904, but has been split off for easier review.
-

Implement SQL parsing for graceful reconfig

---

src/sql/src/plan/scope.rs
test/sqllogictest/scoping.slt

sql: improve column and table ambiguity errors

---

src/adapter/src/coord/ddl.rs
test/cloudtest/test_secrets.py

This PR moves getting the config for a Postgres connection later into the drop flow. Without this, if the upstream Postgres database doesn't exist then it's not possible to drop the corresponding `CONNECTION`.
Fixes https://github.com/MaterializeInc/materialize/issues/28185
-

adapter: move getting the Config for `PostgresConnection` later in the drop flow

---

src/storage-types/src/connections.rs
src/storage-types/src/dyncfgs.rs

Renames the dyncfg introduced in https://github.com/MaterializeInc/materialize/pull/28178 to `kafka_default_aws_privatelink_endpoint_identification_algorithm`.
Slack: https://materializeinc.slack.com/archives/C06CQC8LW4V/p1720800069242729
- N/a

kafka: Rename a dyncfg/LaunchDarkly flag

---

src/adapter/src/catalog/open.rs
src/catalog/src/durable.rs
src/catalog/src/durable/persist.rs
src/catalog/tests/read-write.rs

Previously, we would keep two copies of each storage usage event in memory during startup. One copy was used to generate builtin table updates while the other copy was used to prune old storage usage events. In some environments, storage usage events are so large, that this duplication had significant memory impacts during startup.
This commit fixes the issue by condensing the two copies into a single copy that is used for both pruning and generating builtin table updates.
As a consequence, catalogs will not receive any storage usage event updates while subscribing to the durable catalog. For now this is fine, because we only use the subscription during startup, which special cases storage usage events. In the future we'll likely have to resolve this somehow.
The duplication was …

catalog: Reduce memory usage during startup

---

src/catalog/src/durable.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/transaction.rs

Previously, the `sync_updates` function in the durable catalog claimed to return all updates up to and including the provided timestamp. In reality, it was only returning all updates up to (not including) the provided timestamp.
This commit fixes the documentation of `sync_updates` and all callers. This function only has a single caller, which uses its output for a soft_assert. Fixing the function itself to include the timestamp would be much more useful, but much harder to implement. Since it's not heavily used, we opt for the easy route.

catalog: Fix off by one error in sync_updates

---

src/expr/src/scalar.rs
test/sqllogictest/funcs.slt

We had a guard in place to not apply one optimization to a potentially erroring expression, because we relied on not optimizing a potentially erroring expression in our SQL. That SQL was changed in https://github.com/MaterializeInc/materialize/pull/28034 to not rely on this behavior, and potentially we can remove that guard (and lock in the ability to perform this optimization).
-

Remove a guard against optimizing potentially erroring expressions

---

misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
misc/python/materialize/output_consistency/operation/operation.py
misc/python/materialize/output_consistency/validation/result_comparator.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py

9bf1bcea06 output consistency: jsonb: add jsonb_agg and jsonb_object_agg
b03424fe48 output consistency: jsonb: add additional overloadings for jsonb_agg and jsonb_object_agg
2e3474685f output consistency: jsonb: specify jsonb_agg and jsonb_object_agg as aggregations
75cd9604a6 output consistency: jsonb: use jsonb_agg and jsonb_object_agg with order
22c031baf1 output consistency: jsonb: limit generic jsonb_agg variant
fa99381d0d output consistency: jsonb: add ignore entry
fd901e430b output consistency: value comparison: provide expression
1051e95021 output consistency: value comparison: dict comparison
5381fb0c30 output consistency: value comparison: allow ignoring the order in returned collections
8df01cb51c postgres consistency: value comparison: improve detection of decimal string …

output consistency: add jsonb_agg and jsonb_object_agg

---

test/replica-isolation/mzcompose.py

See https://github.com/MaterializeInc/materialize/issues/28046
-

replica-isolation test: Disable restart-environmentd disruption

---

test/cloudtest/test_replica_restart.py

See https://github.com/MaterializeInc/materialize/issues/28235
-

cloudtest: Disable failing test

---

ci/nightly/pipeline.template.yml

OoM in https://buildkite.com/materialize/nightly/builds/8534#0190abde-b0be-42b3-b3be-400ed5df8cb5
-

parallel-workload: Don't run on small agent

---

test/cloudtest/test_compute.py

Flakes in CI, not sure why:
https://buildkite.com/materialize/test/builds/85883#0190b684-8296-4385-9e3d-352a502d73fb
-

cloudtest: Print node selectors error value

---

src/storage/src/upsert.rs
test/testdrive/load-generator-key-value.td

When selecting between multiple async streams it's important that a `Some(_)` pattern is used so that when one of the streams finishes and yields `None` that branch of `select!` is marked as disabled and another one is waited for.
This problematic pattern in `upsert_inner` could trigger a busy loop where when the `input` stream finished it would continously yield `None`, which prevented the thread from running anything else and eventually existing the loop.
Fixes #27835
-

storage/upsert: fix `select!`/`Stream` bug

---

src/storage/src/source/kafka.rs

Assign kafka partitions to workers in a round-robin fashion, starting at an arbitrary worker based on the hash of the source id. This leads to an even distribution of partitions to workers
[Discussed here](https://materializeinc.slack.com/archives/C0761MZ3QD9/p1719945086325879)
-

storage/kafka: round-robin partition/worker assignment

---

src/storage-client/src/storage_collections.rs

This can happen because we don't lock `self.collections` before we call
`update_write_frontiers`, so we don't hold that lock for too long. And
the warning logs can be misleading/annoying.
Fixes #28151
-

storage: downgrade warn! about absent collection

---

.github/CODEOWNERS

https://github.com/MaterializeInc/materialize/pull/28206 wrongly auto-requested a review from Adapter, when in fact HIR-to-MIR lowering is owned by the Cluster team. I'm guessing this is because of CODEOWNERS not having the full file name.
-

Correct lowering.rs codeowners

---

src/adapter/src/client.rs
src/adapter/src/coord/peek.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/validity.rs
src/adapter/src/metrics.rs
src/adapter/src/session.rs
src/expr/src/relation.rs

This PR adds a Prometheus histogram to instrument `RowSetFinishing::finish`.
It also adds a `SessionMetrics` struct which is a new field on `Session` as a way to pass around this new metric. `RowSetFinishing::finish` is not always run from the context that has access to a `Coordinator` or `AdapterClient`, adding `SessionMetrics` seemed like the cleanest way to move this metric around.
This is an action item that came out of the Incident Response Working Group. From a product quality perspective though we also don't have much visibility into how long this `RowSetFinishing::finish` currently takes.
Hide whitespace
- N/a

adapter: Record the amount of time it takes to run RowSetFinishing

---

misc/bazel/c_deps/rust-sys/BUILD.librdkafka.bazel
misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel

This allows cmake to pick the most up-to-date version of the macOS SDK that is available. It avoids some edge cases where we get errors for APIs being unsupported on an old version of macOS.
Note: even though macOS 14 is fairly new, Electric is good at keeping our machines up-to-date so internally we should all be running a version > 14
- N/a

bazel: Enforce minimum macOS version for `cmake` builds

---

src/sql/src/plan/lowering.rs
test/sqllogictest/github-28174.slt
test/sqllogictest/outer_join_lowering.slt

Fixes #28174. There was a very tricky bug introduced in https://github.com/MaterializeInc/materialize/pull/28018: I was adding null filters also for those equality conditions that were not part of the original ON clause, but were coming from equating outer columns, where "outer" is meant in the subquery sense, not in the outer join sense. These equalities are different from join equalities, in that they allow nulls to match nulls, so filtering out nulls for these was wrong. (See the last sentence of the doc comment of `eq_lhs`.)
I also refactored the `OnPredicate` enum: Now we more clearly separate the different kinds of predicates, so hopefully there is less room for mixing up what is coming from where and where could/should predicates be applied.
I've added the test from the issue.
All …

Fix null filter in outer join lowering to include the outer columns

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/scenarios.py
misc/python/materialize/parallel_workload/action.py
src/persist-client/src/internal/apply.rs
src/persist-client/src/internal/trace.rs

This has been enabled globally for a few weeks; lock in the default in preparation for removing the old path.
-

[default] Default the `roundtrip_spine` flag to true

---

bin/ci-builder
misc/python/materialize/cli/ci_closed_issues_detect.py

Test run: https://buildkite.com/materialize/nightly/builds/8566#0190b748-414f-41db-bfab-5cbe75f33c82
-

ci: Detect issues in cloud/incidents-and-escalations repo being closed

---

src/storage/src/render.rs
src/storage/src/source/source_reader_pipeline.rs

This PR makes sure that we log important information (e.g resume uppers) of dataflow initialization at `INFO` level and that we additionally log at `INFO` level notable events. At the moment advancing to the empty frontier is considered a notable event and is recorded by various parts of the pipeline.
-

storage: increase the information written to logs on initialization

---

Cargo.lock
src/storage-operators/src/s3_oneshot_sink.rs
src/storage-types/src/dyncfgs.rs
src/storage/Cargo.toml
src/storage/examples/upsert_open_loop.rs
src/storage/src/decode.rs
src/storage/src/healthcheck.rs
src/storage/src/render.rs
src/storage/src/render/persist_sink.rs
src/storage/src/render/sources.rs
src/storage/src/sink/kafka.rs
src/storage/src/source/generator.rs
src/storage/src/source/generator/key_value.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/statistics.rs
src/storage/src/source/types.rs
src/storage/src/upsert.rs
src/timely-util/src/builder_async.rs
src/txn-wal/src/operator.rs

Traditionally, the mechanism by which timely operators prevent upstream operators from producing more data while they are processing their current batch of input is by actively working on the data and blocking the worker thread. This approach is a poor fit when the kind of processing is asynchronous and not CPU bound because the worker might have other useful things to do and blocking it prevents it from doing so.
This PR adds the ability for an operator in a storage dataflow to yield control back to timely but prevent upstream operators **of the same dataflow** from producing more work for it until it finishes. This allows timely to schedule **other** dataflows running concurrently that may have useful work to do.
The mechanism by which this is accomplished is using a semaphore …

storage: infrastructure for suspendable sources

---

misc/python/materialize/version_ancestor_overrides.py

See https://github.com/MaterializeInc/materialize/issues/28270
-

feature-benchmark: Ignore wallclock increase

---

src/adapter/src/coord/command_handler.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/ddl.rs

Initial scaffolding for the work described in https://github.com/MaterializeInc/materialize/pull/27907 in service of https://github.com/MaterializeInc/materialize/issues/20208
This just implements parsing of the new statement and will return an error during planning if this statement is actually used. In a follow on PR I'll be working on the planning bits.
-

Implement SQL parsing for CREATE TABLE .. FROM SOURCE

---

ci/nightly/pipeline.template.yml
misc/python/materialize/cloudtest/k8s/redpanda.py
misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/mzcompose/services/redpanda.py
src/storage/src/sink/kafka.rs
test/kafka-matrix/mzcompose.py
test/kafka-resumption/mzcompose.py
test/kafka-resumption/sink-kafka-restart/cleanup.td
test/kafka-resumption/sink-kafka-restart/setup.td
test/kafka-resumption/sink-kafka-restart/verify.td

Maybe I'm missing something. This currently works with --redpanda. I followed the description from https://materializeinc.slack.com/archives/C01LKF361MZ/p1720682554959769
-

tests: Add sink-kafka-restart test

---

test/canary-load/mzcompose.py

This addresses
```
File "/var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-063725630d802b460-1/materialize/qa-canary/misc/python/materialize/cli/mzcompose.py", line 682, in append_to_junit_suite
error.test_case_name_override
AttributeError: 'str' object has no attribute 'test_case_name_override'
```
observed in https://buildkite.com/materialize/qa-canary/builds/165#0190b3b5-9434-4a76-b6d8-540cb204f00d.

qa canary: fix error collection

---

src/expr/src/relation.rs
src/transform/src/lib.rs

https://github.com/MaterializeInc/materialize/pull/27977 introduced a memory regression, which turned out to be non-trivial: https://github.com/MaterializeInc/materialize/issues/28244
This PR makes `Fixpoint` save the hashes of plans rather than the full plans.
Additionally, I factored out the limit of FoldConstants in a constant, in case we want to change it in the future (and for experimentation with changing it). I haven't actually changed the limit, though. 
* This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/28244
* This PR refactors existing code: The limit of FoldConstants was given 4 times, making it annoying to experiment with different values. This PR factors it out.
-

Save plan hashes in `Fixpoint` rather than full plans

---

ci/plugins/mzcompose/hooks/post-command
test/get-cloud-hostname/mzcompose.py

Ran OoM: https://buildkite.com/materialize/test/builds/85985#0190bbaa-19d0-459d-a762-351b5ee83138
It is unfortunate how few tests we can run on small agents (again)
-

ci: Reduce memory consumption in post-command hook

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/metrics.rs
src/controller/src/lib.rs
src/repr/src/timestamp.rs

This PR adds a new Prometheus metric, `mz_dataflow_wallclock_lag_seconds`, that exposes a histogram describing the lag of compute collections behind the system wallclock time.
Part of https://github.com/MaterializeInc/materialize/issues/28097
I have this deployed in my staging env, if you want to play around. [Here is a dashboard](https://grafana.dev.materialize.com/d/ddrjiac717qpsf/jan-freshness?orgId=1&from=now-1h&to=now&var-datasource=JKT0Oh1Vk&var-namespace=environment-df0c80c6-2467-41a8-9ca9-caece68c4d60-0&var-cluster_id=All&var-replica_id=All&var-collection_id=All&var-freshold=2) showing some views of the metric.
- N/A

compute: dataflow wallclock lag metric

---

doc/user/content/sql/system-catalog/mz_catalog.md
src/catalog/src/builtin.rs
test/sqllogictest/autogenerated/mz_catalog.slt
test/sqllogictest/mz_catalog_server_index_accounting.slt

Adds a `cluster_id` column to `mz_objects` and `mz_relations`. 
~It's not clear to me if this warrants a release note or not. It is part of stable interface, so probably?~
We discussed this a couple of times ([Slack](https://materializeinc.slack.com/archives/C063H5S7NKE/p1715900705840139)). There was some concern about confusion since only some object types are installed on clusters, but the utility seems to outweigh the possible confusion IMO.
- Add `cluster_id` to [`mz_relations`](/sql/system-catalog/mz_catalog/#mz_relations) and [`mz_objects`](/sql/system-catalog/mz_catalog/#mz_objects).

adapter: mz_objects includes cluster_id

---

doc/user/content/sql/create-source/kafka.md
doc/user/layouts/partials/sql-grammar/create-source-kafka.svg
doc/user/layouts/partials/sql-grammar/sink-definition.svg
doc/user/layouts/partials/sql-grammar/sink-format-spec.svg
doc/user/sql-grammar/sql-grammar.bnf
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/plan/statement/ddl.rs
src/storage-types/src/sources/envelope.proto
src/storage-types/src/sources/envelope.rs
src/storage/src/render/sources.rs
test/testdrive/kafka-upsert-sources.td

Next step of https://github.com/MaterializeInc/materialize/issues/28127.
Follow up to #28152 :
- Add a test that validates the new `VALUE DECODING ERRORS = INLINE` option for Avro format source
- Allow choosing an alternative name for the 'error' column when using the inline error feature.
The syntax I've implemented adds an optional ` AS <alias>` to the `INLINE` option such that a user can do:
```
ENVELOPE UPSERT (VALUE DECODING ERRORS = INLINE AS new_error_column)
```
-

storage/sources: allow aliasing name of error column when using 'value decoding errors = inline'

---

src/catalog/src/durable/persist.rs

Catalog persist fixup

---

src/persist-client/benches/plumbing.rs
src/persist-client/src/batch.rs
src/persist-client/src/fetch.rs
src/persist-client/src/internal/encoding.rs
src/persist-client/src/iter.rs
src/persist-client/src/lib.rs
src/persist-client/src/stats.rs
src/persist/src/indexed/columnar.rs
src/persist/src/indexed/columnar/parquet.rs
src/persist/src/indexed/encoding.rs

In practice we write down just a single batch of records per part, but the code carried around a `Vec` of batches. Flattening the vec into a single batch at the edge makes a bunch of the code that manages batches simpler, and reduces the difference between the old and new encoding path.
Previously-unspecified refactoring.
-

[persist] Enforce the one-batch expectation in BlobTraceUpdates

---

.github/CODEOWNERS

Turns out there is both a `lowering.rs` and a `lowering` directory. Both should be owned by the Cluster team.
-

CODEOWNERS: Correct hir-to-mir lowering

---

ci/nightly/pipeline.template.yml

Seen in https://buildkite.com/materialize/nightly/builds/8599#0190bc9a-05c6-4300-8572-a38db6398696
-

ci: Reduce parallel-workload-kill threads to prevent OoMs

---

misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
misc/python/materialize/output_consistency/output/reproduction_code_printer.py
misc/python/materialize/output_consistency/query/query_template.py

This addresses
```
ValidationErrorType.ERROR_MISMATCH: Error message differs.
Value 1 (Dataflow rendering): 'function casting double precision to numeric is only defined for finite arguments' (type: <class 'str'>)
Value 2 (Constant folding): 'numeric field overflow' (type: <class 'str'>)
Query 1: SELECT jsonb_object_agg(char_6_val, double_val ORDER BY row_index, char_6_val) FROM t_dfr_vert WHERE (row_index IN (1, 3, 8, 11, 13));
Query 2: SELECT jsonb_object_agg(char_6_val, double_val ORDER BY row_index, char_6_val) FROM v_ctf_vert WHERE (row_index IN (1, 3, 8, 11, 13));
```
seen in https://buildkite.com/materialize/nightly/builds/8591#0190bbf1-dc3f-4456-adb0-04cb49a00f6f and also in https://buildkite.com/materialize/nightly/builds/8599.

output consistency: add ignore for order

---

misc/python/materialize/output_consistency/expression/expression_characteristics.py
misc/python/materialize/output_consistency/input_data/types/date_time_types_provider.py
misc/python/materialize/output_consistency/input_data/values/date_time_values_provider.py
misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py

Seen in https://materializeinc.slack.com/archives/C02FWJ94HME/p1721109385290219.
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fdate-values

output consistency: further date values

---

src/storage/src/render.rs
src/storage/src/render/persist_sink.rs
src/timely-util/src/builder_async.rs

This PR integrates the persist sink in storage dataflows with the suspendable source mechanism introduced in #28226. The general idea is that the persist sink operator peels off the chunk of input that is currently available in its input handle synchronously, takes the busy signal permit, and then proceeds to work on that chunk of input asynchronously. While that chunk of input is being processed the upstream source operators won't be allowed to make progress, preventing the machine from running out of memory.
This PR also has indentation changes so it's better reviewed with whitespace hidden.
-

storage/persist-sink: suspend sources while processing a chunk of input

---

doc/developer/feature-benchmark.md

dev docs: Link to trigger-ci for feature-benchmark runs

---

test/kafka-resumption/mzcompose.py

Even Kafka seems not able to reliably recover in 20s
Seen in https://buildkite.com/materialize/test/builds/86096#0190c07e-0c96-47ca-8cd7-9a0167f79cad
I'm checking logs and running the test locally in an endless loop locally to see if this is something more serious.
-

sink-kafka-restart test: Bump timeout to 40s

---

misc/python/materialize/parallel_workload/parallel_workload.py

Seen in https://buildkite.com/materialize/nightly/builds/8615#0190c076-9e37-4374-b0d0-c94b86885fc6
-

parallel-workload: Expect still-running queries with many threads

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml

It is flaky becuase of https://github.com/MaterializeInc/materialize/issues/28216
Seen in https://buildkite.com/materialize/test/builds/85992#0190bbc0-338c-4a69-a314-207c445fd437
-

ci: Move 0dt test back to nightly

---

test/cloudtest/test_compute.py

Can take a bit to have the values available
Failed in https://buildkite.com/materialize/test/builds/85929#0190b7a5-5a20-4b3a-87a9-f0f3bb388c26
-

cloudtest: Fix node selector getting

---

misc/python/materialize/parallel_workload/action.py
src/persist-client/src/batch.rs
src/persist-client/src/cfg.rs

While we work on rolling out Columnar V2 it would be great to rollout the statistics collection separately from durably recording the data.
Faster rollout
- N/a

persist: Add stats only override

---

Cargo.lock
misc/cargo-vet/audits.toml
src/persist/Cargo.toml
src/workspace-hack/Cargo.toml

Recent benchmarking revealed that we spend a significant amount of CPU time computing SHA256 hashes which can be accelerated a lot by using assembly implementations that can take advantage of specialized CPU instructions.
-

*: enable `asm` feature for the `sha2` crate

---

src/adapter/src/catalog/apply.rs

This commit removes the `[]` operator for indexing a collection from all catalog apply methods. It is instead replaced with `.get(_).unwrap_or_else(|| panic!(_))`, which provides a much more useful error message.

catalog: Remove [] operator from apply

---

src/transform/src/analysis/equivalences.rs
src/transform/src/equivalence_propagation.rs
test/sqllogictest/cardinality.slt
test/sqllogictest/explain/physical_plan_as_text.slt
test/sqllogictest/explain/physical_plan_as_text_redacted.slt
test/sqllogictest/ldbc_bi.slt
test/sqllogictest/ldbc_bi_eager.slt
test/sqllogictest/outer_join_simplification.slt
test/sqllogictest/transform/column_knowledge.slt
test/sqllogictest/transform/non_null_requirements.slt
test/sqllogictest/transform/normalize_lets.slt
test/sqllogictest/transform/relation_cse.slt
test/sqllogictest/with_mutually_recursive.slt

This PR provides the `Equivalences` analysis with a lattice describing its state (and providing a "top" element). It also corrects many shortcomings of the analysis that assumed pessimistic execution (and in particular, that the `results` vector would have a shape that it generally does not; oops!).
~TBD: What to do about all the tests that the analysis deletes.~
We concluded that we would annotate these tests with a reference to https://github.com/MaterializeInc/materialize/issues/28308 which is the rendezvous point for tests that were wiped out by this PR, with the goal of triaging them to see which ones should be tested, and how to best do that. 
-

Endow `Equivalence` with a lattice

---

README.md

We might want to wait for MySQL sources to be out of private preview first?
-

README: Add reference to MySQL and make code sample work standalone

---

src/adapter/src/catalog/open.rs
src/adapter/src/catalog/state.rs
src/adapter/src/catalog/transact.rs
src/catalog/src/durable/initialize.rs
src/catalog/src/durable/transaction.rs
src/catalog/tests/open.rs
src/catalog/tests/read-write.rs

To allocate a unique OID, the durable catalog compares potential OIDs against all known OIDs. The issue with that approach is that the durable catalog does not know about any OIDs allocated to a temporary object, since temporary objects are not stored in the catalog. Therefore, it's possible to allocate a new OID that was already allocated to a temporary object.
This commit resolves this issue by requiring callers to pass the durable catalog a set of existing temporary OIDs before a new one can be allocated.
Fixes #27719

catalog: Resolve temp OID collisions

---

test/cluster/mzcompose.py
test/testdrive/index-source-stuck.td

and fix issue
Fixes: #28328
See https://materializeinc.slack.com/archives/C01LKF361MZ/p1721252573742609
-

tests: Move index-source-stuck to testdrive

---

ci/nightly/pipeline.template.yml

Seen in https://buildkite.com/materialize/nightly/builds/8631#_
Proof: https://buildkite.com/materialize/nightly/builds/8633
-

ci: Fix reference to moved incident

---

bin/ci-builder
ci/plugins/cloudtest/hooks/post-command
ci/plugins/mzcompose/hooks/post-command
doc/developer/feature-benchmark.md
misc/python/materialize/buildkite.py
misc/python/materialize/cli/mzcompose.py
test/feature-benchmark/mzcompose.py

Tested locally with `CI_EXTRA_ARGS='{"feature-benchmark": "--scenario=Foasdb"}' BUILDKITE_STEP_KEY=feature-benchmark bin/mzcompose --find feature-benchmark run default`
Looks like this in trigger-ci: 
Code: https://github.com/MaterializeInc/trigger-ci/commit/eb9c9f686a1bddd8a56f3575f9fdb2eb5dc3ab09 (not live yet)
Proof that this works: https://buildkite.com/materialize/nightly/builds/8639
-

mzcompose: Support CI_EXTRA_ARGS

---

test/cloudtest/test_compute.py

cloudtest: Disable test_cluster_replica_sizes

---

Cargo.lock
doc/user/content/releases/v0.110.md
src/balancerd/Cargo.toml
src/catalog-debug/Cargo.toml
src/clusterd/Cargo.toml
src/environmentd/Cargo.toml
src/persist-client/Cargo.toml
src/testdrive/Cargo.toml

Bumps the version on main to `v0.110.0-dev`
Database release
- N/a

release: Bump version to `v0.110.0-dev`

---

ci/deploy/pipeline.template.yml
ci/deploy_mz/pipeline.template.yml
ci/deploy_mz_lsp_server/pipeline.template.yml
ci/deploy_website/pipeline.template.yml
ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
ci/test/pipeline.template.yml
misc/python/materialize/feature_benchmark/benchmark_versioning.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/scalability/scalability_versioning.py

Also don't use builder-* agents just because something is built in the deploy steps!
So far so green:
https://buildkite.com/materialize/test/builds/86215
https://buildkite.com/materialize/nightly/builds/8645
https://buildkite.com/materialize/release-qualification/builds/552
I'll wait for results from RQ before submitting, shouldn't be any worse than our current state hopefully.
-

ci: Reduce agent sizes, using the new medium size

---

.config/nextest.toml

See timing out in https://buildkite.com/materialize/test/builds/86273
-

cargo test: Increase timeout for mz-storage-types stats::tests::all_datums_produce_valid_stats

---

src/adapter/src/catalog/open.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/transaction.rs

The savepoint catalog mode creates a logical branch of catalog state. Previously, savepoint catalogs would look at the upper of the catalog persist shard to determine the current catalog upper. Looking at the persist shard gives us the upper of the "main" catalog state branch, but not the current savepoint branch upper. Instead, we should be looking at the upper saved in memory.
This commit fixes the issue by updating the fetch upper logical and adds some sanity asserts to various related spots in the code.
Fixes #28326

catalog: Fix savepoint upper calculation

---

misc/dbt-materialize/CHANGELOG.md
misc/dbt-materialize/dbt/adapters/materialize/__version__.py
misc/dbt-materialize/setup.py

Release dbt-materialize v1.8.3 to pick up https://github.com/MaterializeInc/materialize/pull/28138#pullrequestreview-2170292577
-

dbt-materialize: release v1.8.3

---

ci/builder/requirements.txt

Twine is the library used to deploy dbt-materialize to PyPi. Recent versions are broken with missing metadata keys. The issue has been resolved in the latest release.
Example failure: https://buildkite.com/materialize/deploy/builds/15079#0190cc52-c16a-4ea4-8020-e1df5daed947
Twine issue: https://github.com/pypa/twine/issues/977
-

ci: upgrade twine

---

src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sequencer/inner/cluster.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/create_view.rs
src/adapter/src/coord/sql.rs
src/adapter/src/coord/validity.rs
src/adapter/src/session.rs
src/environmentd/tests/sql.rs
src/sql/src/plan.rs
src/sql/src/plan/statement.rs
test/sqllogictest/serial-ddl.slt

Serialize all DDL by queueing DDL while another is executing.
Fixes #27821
- n/a

adapter: serialize DDL

---

src/storage-types/src/stats.rs

Reduces the number of test cases for `all_datums_produce_valid_stats` from the default of 256 to 80. The aim here is to prevent timeouts.
Non-flaky tests
- N/a

tests: Reduce number of proptest cases for `all_datums_produce_valid_stats`

---

src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer/inner.rs
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/ddl
src/sql/src/normalize.rs
src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/show.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/mysql.rs
src/sql/src/pure/postgres.rs
src/storage-controller/src/lib.rs
src/storage-types/src/sources.rs
src/storage-types/src/sources/kafka.rs
src/storage-types/src/sources/load_generator.rs
src/storage-types/src/sources/mysql.rs
src/storage-types/src/sources/postgres.rs

Inspired by & replaces Sean's draft PR https://github.com/MaterializeInc/materialize/pull/27320/  to shuffle when subsource statements are generated.
This PR is prep work for the implementation described in https://github.com/MaterializeInc/materialize/pull/27907
This PR shouldn't introduce any functional changes -- it is a refactor of subsource purification such that we now generate `CreateSubsourceStatement`s after purification and using the same method in both 'create source' and 'alter source' statements.
The intent is to tease apart the purification logic (obtaining state from external systems) from the statement generation logic, such that I can re-use as much of the subsource purification logic as possible to purify & plan `CREATE TABLE .. FROM SOURCE` statements in subsequent PRs. …

storage/sql: Refactor subsource purification (prep for source-fed table purification)

---

src/storage-types/src/sources.rs

Reduces the size of the generated state, and the number of test cases for `all_source_data_roundtrips` with the goal of preventing timeouts.
More stable tests.
Fixes https://github.com/MaterializeInc/materialize/issues/27916
- N/a

test: reduce test size and test cases for `all_source_data_roundtrips`

---

.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-feature.yml
.github/ISSUE_TEMPLATE/03-documentation.yml
.github/ISSUE_TEMPLATE/07-ci-flake.yml

Allows prefilling the texts in links using query parameters
To be used for https://github.com/MaterializeInc/materialize/issues/26727
-

GitHub templates: add ids

---

src/sqllogictest/src/bin/sqllogictest.rs
test/sqllogictest/rbac_views.slt
test/sqllogictest/transform/predicate_pushdown.slt

Seen in https://buildkite.com/materialize/slt/builds/5987
Fallout from https://github.com/MaterializeInc/materialize/pull/28346
-

SLT: In no-fail mode don't add failures to junit.xml

---

ci/deploy/pipeline.template.yml

Seen failing in https://buildkite.com/materialize/deploy/builds/15089#0190d8ac-8f5b-4e86-a5f3-708ff203f679
-

ci: Larger agent for dev site deploy

---

WORKSPACE

The `proc` crate was recently deleted but Bazel was trying to find it.
Fix nightly
- N/a

bazel: Fix build

---

misc/python/materialize/parallel_workload/parallel_workload.py

parallel-workload: Ignore 28400

---

src/sql/src/func.rs
test/sqllogictest/table_func.slt

regexp_extract produces one column per capture group. If there are no capture groups, error.
Fixes #23805
Fixes #20533
- n/a

sql: error on invalid use of regexp_extract

---

src/sql-pretty/src/doc.rs
src/sql-pretty/src/lib.rs
test/sqllogictest/redacted.slt

Add pretty support for CREATE SOURCE.
- n/a

sql-pretty: CREATE SOURCE

---

src/transform/src/equivalence_propagation.rs

The action of `EquivalencePropagation` on `LetRec` seems to be wrong, descending into `values` (which is fine) presenting the `outer_equivalences` that will be applied to the `LetRec` (which is not fine). These outer equivalences apply to the `LetRec`, and can only be propagated to the `body` of the `LetRec`. For example, if `#1 > 3` is a thing that must be true of the `LetRec`, it must be true of `body` but needn't be true of any binding, because .. they have totally unrelated columns.
A more advanced analysis could present more information about what equivalences will be applied, but it seems like it would need to be a top-down analogue of the bottom-up `Analysis`. I.e. it would need to iterate around `LetRec` until fixed point reached, all that stuff. Not in the cards at the moment, so …

Do not descend into LetRec::values with outer equivalences

---

src/sql-pretty/src/doc.rs

sql-pretty: CREATE SOURCE merge skew fix

---

Cargo.lock
src/frontegg-mock/Cargo.toml
src/frontegg-mock/src/lib.rs

As per the discussions [here](https://github.com/MaterializeInc/terraform-provider-materialize/issues/461) for consolidating the two existing Frontegg mock services, this PR transfers over another batch of endpoints:
- `/frontegg/team/resources/sso/v1/configurations`
- `GET`, `POST`: Handle SSO configuration requests
- `/frontegg/team/resources/sso/v1/configurations/{id}`
- `GET`, `PATCH`, `DELETE`: Handle specific SSO configuration and domain requests
- `/frontegg/team/resources/sso/v1/configurations/{id}/domains`
- `GET`, `POST`: Handle domain requests for a specific SSO configuration
- `/frontegg/team/resources/sso/v1/configurations/{id}/domains/{domainId}`
- `GET`, `PATCH`, `DELETE`: Handle requests for a specific domain
- `/frontegg/team/resources/sso/v1/configurations/{id}/groups`
- …

[WIP] frontegg-mock: implement SSO config endpoints

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/timeline.rs
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/timestamp-oracle/src/batching_oracle.rs
src/timestamp-oracle/src/postgres_oracle.rs

Before, we were doing some write_ts/apply_write calls when
bootstrapping. This is technically okay, because the timestamp oracle is
designed to be used from multiple processes. But for the time being we
don't want a read-only/upgrade environmentd to futz with the oracle.
We now panic when attempting to to write operations in read-only mode.
This will make it so we immediately notice when we accidentally
introduce calls that would cause writes.
We noticed this was problematic while working on https://github.com/MaterializeInc/materialize/pull/27997.
-

adapter: make Postgres TimestampOracle aware of read-only mode

---

src/transform/src/equivalence_propagation.rs

The `EquivalencePropagation` transform was pushing down predicates through `Join`, but was not applying expression simplification to expressions in `Join::equivalences` as it went. This meant that e.g. columns that were known to be constants weren't being substituted, and non-trivial but pointless equivalences (and the columns on which they depend) were retained.
This PR fixes this by reducing expressions in `equivalences` by the implied input equivalences (permuted to point their column references at the right things). It continues to minimize these equivalences (i.e. reduce them relative to themselves), but that might have a different effect with more information introduced into them.
This missing behavior prevents the removal of `ColumnKnowledge`, as that transform performs this …

Reduce `Join::equivalences` in EQProp

---

doc/developer/testdrive.md

dev docs: Mention system parameters for testdrive

---

Cargo.lock
deny.toml
misc/cargo-vet/config.toml
src/workspace-hack/Cargo.toml

https://buildkite.com/materialize/security/builds/1261
```
ID: RUSTSEC-2024-0357
Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0357
Previously, `MemBio::get_buf` called `slice::from_raw_parts` with a null-pointer, which violates the functions invariants, leading to undefined behavior. In debug builds this would produce an assertion failure. This is now fixed.
Announcement: https://github.com/sfackler/rust-openssl/pull/2266
Solution: Upgrade to >=0.10.66 (try `cargo update -p openssl`)
```
* `cargo update -p openssl` doesn't do anything (as of now)
* updated `tokio-openssl` but this did not fix the issue
```
warning[advisory-not-detected]: advisory was not encountered
┌─ /var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-0aebb6f13f5cf4383-1/materialize/security/deny.toml:23 …
```

security: fix security pipeline

---

src/adapter-types/src/dyncfgs.rs
src/adapter/src/catalog/transact.rs
src/adapter/src/coord.rs
src/catalog/src/durable.rs
src/catalog/src/durable/initialize.rs
src/catalog/src/durable/persist.rs
src/catalog/src/durable/transaction.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/environmentd/src/deployment/preflight.rs
src/environmentd/src/lib.rs
src/ore/src/channel/trigger.rs

I'm not sure I like this approach, especially with always having a check interval and adding another branch to the coordinator main loop. But opening now to get early feedback. This should be the last piece before we can think about rolling 0dt deployment out to staging. :fire: 
-

adapter: wire up cluster hydration check to 0dt deployment preflight

---

src/transform/src/analysis.rs

The `Analysis` framework assumed that it would be called on let-normalized expressions, but this doesn't have to be the case. Add a defensive check to make sure that if it is called on unnormalized expressions it bails out and enters the pessimistic case instead (while logging an error so we can track this down).
Future work: figure out how to route around the problem, and perform the optimistic analysis on non-normalized expressions.
-

Bail out of optimistic analysis if assumptions not upheld

---

test/bounded-memory/mzcompose.py

This fixes a regression introduced by a previous commit[1] which caused workloads to be scheduled on a cluster that is not actually memory constrained.
[1] https://github.com/MaterializeInc/materialize/commit/c6f2bc50#diff-aaf1582f6a06e65692e924ba44caee78cb45758df8b247084b50267710593181
-

test/bounded-memory: use the correct cluster

---

misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/github.py
misc/python/materialize/test_analytics/connector/test_analytics_connector.py
misc/python/materialize/test_analytics/data/known_issues/known_issues_storage.py
misc/python/materialize/test_analytics/setup/tables/40-issues.sql
misc/python/materialize/test_analytics/setup/views/01-build.sql
misc/python/materialize/test_analytics/setup/views/100-data-integrity.sql
misc/python/materialize/test_analytics/setup/views/30-ci-failures.sql
misc/python/materialize/test_analytics/setup/views/31-ci-issues.sql
misc/python/materialize/test_analytics/test_analytics_db.py
misc/python/materialize/test_analytics/util/mz_sql_util.py
test/sqlancer/mzcompose.py

test-analytics: Add tables and view for ci-failures, Store known issues

---

misc/python/materialize/parallel_workload/parallel_workload.py

parallel-workload: Also allow stuck threads in DDL complexity

---

misc/wasm/Cargo.lock
misc/wasm/src/sql-pretty-wasm/src/lib.rs

The existing sql-pretty wasm signatures didn't match the build output. I also moved to automatically generating the typescript signature, rather than overriding it manually.
- NA

sql-pretty: Improve sql-pretty-wasm types

---

ci/plugins/cloudtest/hooks/post-command

cloudtest: Fail on empty kubectl-get-logs-previous.log

---

src/repr/src/row/encoding2.rs

This PR tightens up the assertions we make for the `RowColumnarEncoder`, asserting that the number of Datums in a Row matches the number of column encoders. FWIW this would have panicked before but when finishing the `RowColumnarEncoder`, not when encoding.
@danhhz encountered a case of the Row we're trying to encode had fewer Datums then our columnar encoders.
- N/a

persist: Assert number of datums matches number of column encoders

---

misc/python/materialize/buildkite.py
misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/output_consistency/output_consistency_test.py
test/feature-benchmark/mzcompose.py
test/scalability/mzcompose.py

ci: Notify QA about infra failures
