MaterializeInc/materialize

- Cargo.lock
- src/balancerd/Cargo.toml
- src/catalog-debug/Cargo.toml
- src/clusterd/Cargo.toml
- src/environmentd/Cargo.toml
- src/persist-client/Cargo.toml
- src/testdrive/Cargo.toml
> release: bump to version v0.99.0-dev

- test/cloudtest/node_recovery/test_k8s_node_recovery.py
Raising a `FailedTestExecutionError` does not work well because we are not in an mzcompose workflow.
> tests: node recovery: improve output

- ci/nightly/pipeline.template.yml
This job was failing frequently due to a timeout.
```
rqg-left-join-stacks, #7612, 2024-05-02 11:33:59 +0000, 30.25 min, https://buildkite.com/materialize/nightly/builds/7612, FAIL
rqg-left-join-stacks, #7611, 2024-05-01 23:33:14 +0000, 29.29 min, https://buildkite.com/materialize/nightly/builds/7611, SUCCESS
rqg-left-join-stacks, #7607, 2024-05-01 17:33:51 +0000, 26.11 min, https://buildkite.com/materialize/nightly/builds/7607, SUCCESS
rqg-left-join-stacks, #7600, 2024-05-01 13:38:49 +0000, 30.15 min, https://buildkite.com/materialize/nightly/builds/7600, SUCCESS (RETRY)
rqg-left-join-stacks, #7600, 2024-05-01 11:33:55 +0000, 30.47 min, https://buildkite.com/materialize/nightly/builds/7600, FAIL
rqg-left-join-stacks, #7599, 2024-04-30 23:30:57 +0000, 30.36 min, …
```
> ci: increase timeout of rqg-left-join-stacks

- misc/python/materialize/data_ingest/executor.py
Nightly: https://buildkite.com/materialize/nightly/builds/7655
> tests: fix parallel-workload, data-ingest

- test/bounded-memory/mzcompose.py
This is the migrated scenario from https://github.com/MaterializeInc/materialize/issues/15044.
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Abounded-memory%2Fgh15044
> bounded memory: add scenario from #15044

- misc/python/materialize/parallel_workload/action.py
- misc/python/materialize/parallel_workload/parallel_workload.py
Extension to https://github.com/MaterializeInc/materialize/pull/26837.
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aparallel-workload%2Ffeature-flag-flips
> parallel workload: feature-flag flips

- test/bounded-memory/mzcompose.py
The search did not terminate and stay on the same value.
Tested successfully with https://buildkite.com/materialize/nightly/builds/7665#018f51b0-f1f6-4698-892b-1e842480b177.
> bounded memory: fix memory search

- src/adapter/src/coord.rs
Fixes [Sentry issue](https://materializeinc.sentry.io/issues/5312906613/?project=6780145)
-
> adapter: loosen GlobalId dependency ordering invariant for system objects

- doc/user/content/sql/create-connection.md
- doc/user/content/sql/create-source/mysql.md
Follow-up to user feedback on [Slack](https://materializeinc.slack.com/archives/C06UCSE9K0T/p1715104771041009).
> doc/user: minor patch to MySQL documentation

- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/test_result.py
- test/bounded-memory/mzcompose.py
- test/feature-benchmark/mzcompose.py
- test/pg-cdc-resumption/mzcompose.py
- test/platform-checks/mzcompose.py
- test/source-sink-errors/mzcompose.py
Demo: https://buildkite.com/materialize/nightly/builds/7684
Provide info about the current scenario (where applicable) to Buildkite annotation.
f1809f5f9b tests: composition: add comments
9b0ad2685b tests: composition: allow specifying the current test case name
2affe0b8ab ci: apply test case name override
1ca7d8d639 bounded memory: specify current scenario as context
10e98add1f tests: provide better test case information
> ci: better test case information

- test/canary-load/mzcompose.py
Extract some functions to make the code more readable.
> cloud canary: refactor code

- ci/nightly/pipeline.template.yml
> ci: nightly: move cloudtest-slow

- ci/builder/requirements.txt
- misc/python/materialize/buildkite_insights/artifact_search/README.md
- misc/python/materialize/buildkite_insights/artifact_search/artifact_search.py
- misc/python/materialize/buildkite_insights/buildkite_api/artifacts_api.py
- misc/python/materialize/buildkite_insights/buildkite_api/generic_api.py
- misc/python/materialize/buildkite_insights/cache/artifacts_cache.py
- misc/python/materialize/buildkite_insights/cache/generic_cache.py
- misc/python/materialize/buildkite_insights/util/data_io.py
- misc/python/materialize/util.py
ecf71f09a1 python: add zstandard lib for decompressing zst files
f007c80f80 python: add utility function to decompress zst files
74744becde buildkite insights: extract get request function
e0c9f8bceb buildkite insights: raise error when response status code is not 200
652ad98b99 buildkite artifact search: include zst artifacts
791ba8774c python: move ensure_dir_exists to utils
> buildkite artifact search: support compressed artifacts

- src/mysql-util/src/decoding.rs
@rjobanp this is a strict reduction in the number of allocations. The TODO's describe even more improvements we can make in addition to these.
-
> storage: reduce allocations in mysql row packing

- src/storage/src/source/generator/key_value.rs
- src/storage/src/source/mysql/replication.rs
- src/storage/src/source/mysql/replication/events.rs
Blocker on https://github.com/MaterializeInc/materialize/pull/26606
As @petrosagg said:
> This is an anti-pattern and must be fixed if it's the case. We used to do that in the pg source but I fixed it recently. I'm not aware of other cases. We should rely on it as an assumption for this PR
This removes our uses of `give_container` in the source data production side. It leaves it in upsert/decode/persist_sink/remap/source_render, which all appear to process data generally in the same batch as the input.
-
> storage: avoid give_container in production of source data

- doc/user/layouts/partials/sql-grammar/create-managed-cluster.svg
- doc/user/sql-grammar/sql-grammar.bnf
Specifying at least one option is nonoptional.
- n/a
> doc/user: fix create cluster diagram

- src/adapter/src/catalog/migrate.rs
#27040 had a bug in it that it both tried to migrate system object's IDs and expressly forbid migrating system object's IDs. This resulted in:
```
upgrade-check-9n29n-0-9pffq 2024-05-11T18:16:52.842864Z  INFO catalog::initialize_state: mz_adapter::catalog::migrate: migrating from catalog version Version { major: 0, minor: 98, patch: 6 }
upgrade-check-9n29n-0-9pffq thread 'main' panicked at src/adapter/src/catalog/migrate.rs:204:13:
upgrade-check-9n29n-0-9pffq cannot assign new ID to non-user ID System(1877)
```
The correct fix is to only try to fix the `GlobalId` ordering of user objects.
This commit will be made into v0.99.2
-
> adapter: do not attempt to migrate the GlobalId of system objects in v0.99

- misc/python/materialize/output_consistency/enum/enum_operation_param.py
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fenum-param-null
> output consistency: add NULL as constant param

- doc/developer/design/20240117_decoupled_storage_controller.md
[Rendered](https://github.com/aljoscha/materialize/blob/design-cleave-apart-storage-controller/doc/developer/design/20240117_decoupled_storage_controller.md)
As part of the platform v2 work (specifically use-case isolation) we want to
develop a scalable and isolated serving layer that is made up of multiple
processes that interact with distributed primitives at the moments where
coordination is required.
The way the compute controller and storage controller work currently will not
work well for that, because they're coupled together inside one process.
> doc/design: modularized/decoupled storage controller

- src/storage/src/upsert.rs
This PR renders an operator that discards updates that are known to not affect the outcome of upsert in a streaming fashion. For each distinct `(key, time)` in the input it emits the `value` with the highest `from_time`. Its purpose is to thin out data as much as possible before exchanging them across workers which is beneficial for flow control in the presence of skew.
-
> storage/upsert: thin out data before exchange

- test/mysql-cdc/alter-source.td
Follow-up to https://github.com/MaterializeInc/materialize/pull/27063#discussion_r1599436008.
> tests: mysql-cdc: remove outdated comment

- src/testdrive/src/action.rs
- src/testdrive/src/action/consistency.rs
- src/testdrive/src/action/fivetran.rs
- src/testdrive/src/action/kafka/verify_data.rs
- src/testdrive/src/action/kafka/verify_topic.rs
- src/testdrive/src/action/psql.rs
- src/testdrive/src/action/set.rs
- src/testdrive/src/action/skip_if.rs
- src/testdrive/src/action/sql.rs
- src/testdrive/src/action/version_check.rs
- src/testdrive/src/action/webhook.rs
9fbacdb33b testdrive: extract MaterializeState
9699caa22f testdrive: move materialize_state declaration up
d50fefad99 testdrive: extract create_materialize_connection
> testdrive: minor refactorings

- test/canary-load/mzcompose.py
Improving error handling based on observations in https://buildkite.com/materialize/qa-canary/builds/102#018f7468-c7db-4280-a86c-beb7c223ea3a.
> qa canary: error handling

- misc/python/materialize/output_consistency/execution/test_summary.py
- misc/python/materialize/output_consistency/runner/test_runner.py
Nightly: https://buildkite.com/materialize/nightly/builds/7776
> output consistency: improve warnings

- misc/python/materialize/version_consistency/validation/version_consistency_error_message_normalizer.py
- misc/python/materialize/version_consistency/version_consistency_test.py
https://github.com/MaterializeInc/materialize/pull/27104/commits/8a77be51f9165a20400b5ff4104edd054f3b09e3 should fix https://buildkite.com/materialize/nightly/builds/7779#018f7c07-ac3f-4434-b971-224b4316b065. https://github.com/MaterializeInc/materialize/pull/27104/commits/887efa9d3485f955ff790219642d38dac7bbc778 easens debugging.
> version consistency: fix error msg normalization

- misc/python/materialize/output_consistency/data_type/data_type_category.py
- misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/uuid_operations_provider.py
- misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
- misc/python/materialize/output_consistency/input_data/params/uuid_operation_param.py
- misc/python/materialize/output_consistency/input_data/return_specs/uuid_return_spec.py
- misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
- misc/python/materialize/output_consistency/input_data/types/uuid_type_provider.py
- misc/python/materialize/output_consistency/input_data/values/all_values_provider.py
- misc/python/materialize/output_consistency/input_data/values/uuid_values_provider.py
Nightly: https://buildkite.com/materialize/nightly/builds/7780
> output consistency: add UUID type

- misc/python/materialize/cli/ci_annotate_errors.py
> ci error reporting: minor

- doc/user/content/releases/v0.99.md
- doc/user/content/sql/system-catalog/mz_internal.md
**WIP** Release notes for v0.99. 🌻 
@doy-materialize @petrosagg: this covers the step of bumping the release version in the docs.
> doc/user: polish v0.99 release notes

- misc/python/materialize/cloudtest/k8s/environmentd.py
- src/adapter/src/flags.rs
- src/orchestrator-kubernetes/src/lib.rs
- src/orchestrator/src/lib.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
As part of our security posture improvement plan (https://github.com/MaterializeInc/cloud/issues/8166) , we want to ensure each service has the minimal capabilities. This PR ensures that `clusterd` instances are started with minimal capabilities such that they conform to (and are allowed by)  the [Restricted PodSecurityStandard guidelines](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).
-
> drop capabilities, don't allow running as root

- Cargo.lock
- src/balancerd/Cargo.toml
- src/catalog-debug/Cargo.toml
- src/clusterd/Cargo.toml
- src/environmentd/Cargo.toml
- src/persist-client/Cargo.toml
- src/testdrive/Cargo.toml
> release: bump to version v0.100.0-dev

- src/environmentd/src/http/sql.rs
- test/copy-to-s3/http/setup.td
- test/copy-to-s3/mzcompose.py
Fixes https://github.com/MaterializeInc/materialize/issues/27114
-
> Allow copy to s3 in the websocket API

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses: https://buildkite.com/materialize/nightly/builds/7787#annotation-018f812e-0dd8-4a56-974d-ecece9d2f871-error
> postgres consistency: add ignore for UUID error with zero rows

- misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Nightly: https://buildkite.com/materialize/nightly/builds/7790
> postgres consistency: change exclusion to ignore

- misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/special_operations_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
https://buildkite.com/materialize/nightly/builds/7809
> output consistency: add pg_typeof function

- doc/user/content/get-started/quickstart.md
> doc: fix typo in quickstart guide

- test/upsert/mzcompose.py
Fixes https://github.com/MaterializeInc/materialize/issues/27145
I inadvertently renamed a failpoint from `fail_merge_snapshot_chunk` to `fail_consolidate_snapshot_chunk` in https://github.com/MaterializeInc/materialize/pull/27064/ and forgot to update this test file. 
-
> test/upsert: Fix test reference to renamed failpoint

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses issues seen in https://buildkite.com/materialize/nightly/builds/7810#018f8653-f802-45de-8633-d32c01d92cf8.
> postgres consistency: add ignores for pg_typeof

- doc/user/content/free-trial-faqs.md
Change trial duration from 14 to 7 days in docs.
> Update free-trial-faqs.md 

- misc/python/materialize/parallel_workload/action.py
Seen in https://buildkite.com/materialize/nightly/builds/7828#018f9aed-fc40-4a91-8361-8a76c8e675b4.
> parallel workload: add error to ignore

- src/compute/src/render/join/linear_join.rs
- src/compute/src/render/join/mz_join_core.rs
Changes without reformatting: https://github.com/MaterializeInc/materialize/pull/27198/commits/e729535a3ce3e50bb80195d23a661703dfa4bf99
> compute: return StreamCore in mz_join_core

- misc/python/materialize/checks/all_checks/materialized_views.py
Second try: This addresses https://buildkite.com/materialize/nightly/builds/7832 because https://github.com/MaterializeInc/materialize/pull/27197 did not fix the issue.
> platform checks: fix upgrade checks

- src/storage/src/source/source_reader_pipeline.rs
This is entirely replaced by https://github.com/MaterializeInc/materialize/pull/27058, but I am putting it up separately so we can break up this dependency.
This is required for the "suspendable-scopes"-style flow control to work in storage
I will run nightly after ci passes
-
> storage: make reclock run-to-completion

- src/storage/src/source/postgres/replication.rs
Suppose the capabilities were `data_cap = 50` and `upper_cap = 50` and the replication stream contained the following events:
```
Transaction(commit_lsn = 100)
PrimaryKeepalive(wal_end = 100)
```
The previous version of the code would:
1. Go in the first iteration of the loop and set `new_upper = data_cap = 50`
2. Process the transaction and:
1. Set `new_upper = commit_lsn + 1 = 101`
2. Downgrade the upper capability to 101, so `upper_cap = 101`
4. Check if the stream is about to yield and find out that it's not, because there is another event ready to go
5. Go in the second iteration of the loop and set `new_upper = data_cap = 50`
6. Process the keepalive and:
1. Set `new_upper = max(new_upper, keepalive.wal_end) = 100`
7. Check if the stream is about to yield and find out that it is, …
> storage/pg: fix bug with capability handling

- misc/python/materialize/postgres_consistency/execution/pg_dialect_adjuster.py
This addresses https://buildkite.com/materialize/nightly/builds/7832#018f9c35-4603-4714-806e-77677fdb96b5.
> postgres consistency: fix

- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/parallel_workload/parallel_workload.py
- misc/python/materialize/parallel_workload/worker.py
- misc/python/materialize/parallel_workload/worker_exception.py
This improves the annotation in https://buildkite.com/materialize/nightly/builds/7836#annotation-018fa012-3722-47f7-ab7c-22b446f75529-error.
> parallel workload: collect exception of all types

- Cargo.lock
- misc/cargo-vet/audits.toml
- misc/cargo-vet/imports.lock
> protobuf-src: 2.0.0+26.1 -> 2.0.1+26.1

- doc/user/content/releases/v0.100.md
doc/user: polish v0.100.1 release notes
> doc/user: polish v0.100.1 release notes

- src/orchestrator-kubernetes/src/lib.rs
This message runs ~once per minute per cluster which makes our logs pretty spammy. Lowering to debug level
-
> orchestrator: lower disk capacity message to debug

- src/txn-wal/src/txn_read.rs
`TxnsRead` maintains a `Vec` of subscriptions over data shards. Any time an update is made to the txn shard, `TxnsRead` updates all subscriptions via a channel. If the receiver of the channel is closed, the subscription is cleaned up.
Previously, we cleaned up the subscriptions via the `drain_filter_swapping` method. This method creates an iterator which only removes the element lazily as the iterator is processed. Unfortunately, the iterator was immediately dropped and never actually cleaned up subscriptions.
This commit fixes the issue by using `retain` to clean up subscriptions, which is not an iterator and removes elements immediately.
Fixes #27305
> txn-wal: Fix subscription leaks in TxnsRead

- bin/lint-test-history-versioning
- ci/test/lint-main/checks/check-test-history-versioning.sh
- misc/python/materialize/test_analytics/versioning/check_versioning.py
- misc/python/materialize/test_analytics/versioning/versioning_config.py
- misc/python/materialize/util.py
This is the base for https://github.com/MaterializeInc/materialize/pull/27310.
> lint: check file hash versions

- misc/python/materialize/buildkite_insights/annotation_search/annotation_match.py
- misc/python/materialize/buildkite_insights/annotation_search/annotation_search_presentation.py
- misc/python/materialize/buildkite_insights/artifact_search/artifact_search_presentation.py
- misc/python/materialize/buildkite_insights/buildkite_api/annotations_api.py
- misc/python/materialize/buildkite_insights/buildkite_api/artifacts_api.py
- misc/python/materialize/buildkite_insights/buildkite_api/buildkite_config.py
- misc/python/materialize/buildkite_insights/buildkite_api/buildkite_constants.py
- misc/python/materialize/buildkite_insights/buildkite_api/builds_api.py
- misc/python/materialize/buildkite_insights/buildkite_api/generic_api.py
- misc/python/materialize/buildkite_insights/cache/annotations_cache.py
- misc/python/materialize/buildkite_insights/cache/artifacts_cache.py
- misc/python/materialize/buildkite_insights/cache/builds_cache.py
- misc/python/materialize/buildkite_insights/cache/cache_constants.py
- misc/python/materialize/buildkite_insights/cache/generic_cache.py
- misc/python/materialize/buildkite_insights/costs/extract_stats.py
- misc/python/materialize/buildkite_insights/steps/build_step.py
- misc/python/materialize/buildkite_insights/util/data_io.py
- misc/python/materialize/buildkite_insights/util/search_utility.py
- misc/python/materialize/test_analytics/versioning/versioning_config.py
These files are not Python entry points.
> python: remove superfluous shebang lines

- doc/user/content/ingest-data/network-security/privatelink.md
- doc/user/content/ingest-data/postgres/amazon-rds.md
- doc/user/content/ingest-data/postgres/self-hosted.md
- doc/user/content/ingest-data/redpanda-cloud.md
- doc/user/content/manage/terraform.md
- doc/user/content/sql/create-connection.md
- doc/user/content/sql/create-source/kafka.md
- doc/user/content/sql/create-source/postgres.md
- doc/user/content/sql/system-catalog/mz_catalog.md
The tasks to promote to GA are done, time to remove the labels. Figure I'd get the ball rolling here.
https://github.com/MaterializeInc/materialize/issues/25503
-
> remove public preview warnings for privatelink connections

- test/kafka-rtr/mzcompose.py
- test/kafka-rtr/resumption/ingest-data.td
- test/kafka-rtr/resumption/mz-reset.td
- test/kafka-rtr/resumption/mz-setup.td
- test/kafka-rtr/resumption/toxiproxy-close-connection.td
- test/kafka-rtr/resumption/toxiproxy-limit-connection.td
- test/kafka-rtr/resumption/toxiproxy-restore-connection.td
- test/kafka-rtr/resumption/toxiproxy-setup.td
- test/kafka-rtr/resumption/toxiproxy-timeout-hold.td
- test/kafka-rtr/resumption/toxiproxy-timeout.td
This extends tests for https://github.com/MaterializeInc/materialize/pull/25195.
> tests: add reworked RTR resumption tests

- misc/python/materialize/buildkite_insights/cache/artifacts_cache.py
- misc/python/materialize/buildkite_insights/cache/builds_cache.py
- misc/python/materialize/test_analytics/versioning/check_versioning.py
- misc/python/materialize/test_analytics/versioning/versioning_config.py
- misc/python/materialize/util.py
This extends https://github.com/MaterializeInc/materialize/pull/27309.
> lint: check version skew (2)

- misc/python/materialize/output_consistency/execution/test_summary.py
- misc/python/materialize/output_consistency/operation/operation.py
- misc/python/materialize/output_consistency/output/output_printer.py
- misc/python/materialize/output_consistency/runner/test_runner.py
```
--- Operation and function statistics
-- * function 'abs($)': 6 top level, 1 nested, 0 generation failed
-- * function 'acos($)': 0 top level, 1 nested, 0 generation failed
-- * function 'acosh($)': 1 top level, 1 nested, 0 generation failed
-- * function 'age($, $)': 5 top level, 1 nested, 0 generation failed
-- * function 'array_agg($ ORDER BY row_index)' (comment: with ordering): 9 top level, 0 nested, 0 generation failed
-- * function 'array_agg($)' (comment: without ordering): 10 top level, 0 nested, 0 generation failed
-- * function 'ascii($)': 1 top level, 1 nested, 0 generation failed
[...]
```
https://buildkite.com/materialize/nightly/builds/7918
> output consistency: print operation and function statistics

- doc/user/content/releases/v0.101.md
doc/user: polish v0.101 release notes
> doc/user: polish v0.101 release notes

- Cargo.lock
- misc/bazel/Cargo.crates_io.lock
This should address the failure in https://buildkite.com/materialize/nightly/builds/7923#018fc6b4-139c-4740-95ab-995fefe87110.
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Abazel%2Ffix-failure ✅
> bazel: fix failure

- Cargo.lock
- Cargo.toml
- src/workspace-hack/Cargo.toml
> deps: update mysql_async

- misc/python/materialize/buildkite_insights/annotation_search/README.md
- misc/python/materialize/buildkite_insights/annotation_search/annotation_search.py
- misc/python/materialize/buildkite_insights/cache/generic_cache.py
- misc/python/materialize/buildkite_insights/util/data_io.py
This helps debugging when results are unexpected.
5ee48d2d27 buildkite-search: add verbose mode
a6f2e8c2fc buildkite insights: extract functions
14b5b1c076 buildkite insights: improve error handling
7148096862 buildkite insights: more logging
> buildkite-search: add verbose mode

- test/canary-load/mzcompose.py
Since we keep running into https://github.com/MaterializeInc/materialize/issues/22576
See for example https://buildkite.com/materialize/qa-canary/builds/122#018fdb6a-9ce4-4058-9ae9-021250cfedab
Test run: https://buildkite.com/materialize/qa-canary/builds/123
-
> qa canary: Ignore non-positive multiplicity

- .github/CODEOWNERS
> bazel: Update CODEOWNDERS

- src/ore/src/region.rs
Switch the reserve path to a fast check and a non-inlined reserve function
to permit callers to inline the check but do not require them to inline
the whole logic to allocate new memory.
-
> Make reserve path cold in lgalloc region

- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/postgres/snapshot.rs
> storage/pg: run SHOW command from normal connection

- test/sqllogictest/transform/fold_vs_dataflow/4_text_dataflow.slt
Follow-up to https://github.com/MaterializeInc/materialize/pull/27415, was only half-way fixed. Seen in https://buildkite.com/materialize/slt/builds/5945#018fdef3-ab0a-49c0-b458-2997853ca9c5
-
> slt: Adapt 4_text_dataflow.slt explain

- misc/python/materialize/version_ancestor_overrides.py
See https://github.com/MaterializeInc/materialize/issues/27425
-
> feature benchmark: Ignore ParallelIngestion memory regression

- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
> Remove dead code

- src/adapter/src/catalog/apply.rs
Previously, the state update sorting code was responsible for two things:
1. Sorting state updates by dependency.
2. Grouping/separating state updates that will be batched when applied.
This was a bit confusing and broke the principle of single responsibility. This commit simplifies the code by making the sorting function only sort the updates. Group and batching is now the responsibility of the function that applies the updates.
> catalog: Simplify bootstrap update sorting

- misc/dbt-materialize/CHANGELOG.md
> dbt-materialize changelog: Fix PR reference

- misc/python/materialize/cli/ci_annotate_errors.py
Seen in https://buildkite.com/materialize/nightly/builds/7978
Colored deviations were introduced in https://github.com/MaterializeInc/materialize/pull/27431
-
> ci annotation: Filter out colors

- misc/python/materialize/data_ingest/workload.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- test/testdrive/session.td
Verification: https://buildkite.com/materialize/nightly/builds/7979
-
> tests: Add RTR testing for data-ingest/parallel-workload

- misc/python/materialize/buildkite.py
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/test_analytics/config/mz_db_config.py
- misc/python/materialize/test_analytics/config/test_analytics_db_config.py
- misc/python/materialize/test_analytics/connection/test_analytics_connection.py
- misc/python/materialize/test_analytics/data/build_data_storage.py
- misc/python/materialize/test_analytics/setup/structures/00-database.sql
- misc/python/materialize/test_analytics/setup/structures/01-base-tables.sql
- misc/python/materialize/test_analytics/setup/structures/02-base-views.sql
- misc/python/materialize/test_analytics/setup/test_analytics_setup.py
- misc/python/materialize/test_analytics/test_analytics_db.py
a13531cd86 buildkite: add environment variables
1a6723e600 test history: add data structures
2f8d017e2b test history: add config
1745286aba test history: add setup logic
267a3aae7b test history: add connectivity
e670a541f4 test history: add build data storage
366de15f0c test history: add nullability constraints to tables
57b0dc1b56 test history: rework and adjust database config
6752163dd6 ci: annotate test-history upload failures
This is the base for
* https://github.com/MaterializeInc/materialize/pull/27434
* https://github.com/MaterializeInc/materialize/pull/27433
> test analytics: prepare base for uploading results

- src/storage/src/storage_state.rs
The command sequencer is behind an `Rc<RefCell<_>>` and is shared by both the worker and the dataflows. In #27445 we discovered that there are cases where the operators need to use the sequencer during their first schedule, which happens synchronously as part of rendering.
This means that we must make sure to not keep a `borrow_mut` active in an earlier stack frame so that operators can take the borrow.
Fixes #27445
-
> storage: ensure command Sequencer is borrowed briefly during rendering

- test/cloud-canary/mzcompose.py
Seen in https://buildkite.com/materialize/nightly/builds/7989#018fe858-b9e7-49fd-b915-9b4b153cc5aa
```
> local version: v0.103.0-dev (0c78f604a) is not identical to cloud version: v0.103.0-dev (c112c56fa)
```
See https://hub.docker.com/r/materialize/environmentd/tags?page=&page_size=&ordering=&name=devel-0c78f604a4340a0cdd28cfb215907125c2534c4a and https://hub.docker.com/r/materialize/environmentd/tags?page=&page_size=&ordering=&name=devel-c112c56fa96b850d7caca1d7a11e265ad3d70fe4
In the first build:
> Successfully tagged materialize/environmentd:mzbuild-YRLVFRJZ7GRIOJY7ZC53AMM5JWCDRF3T
Second build:
> materialize/environmentd:mzbuild-YRLVFRJZ7GRIOJY7ZC53AMM5JWCDRF3T already exists
-
> canary-deploy: Fix version check

- src/persist-client/src/iter.rs
Required > 2400 seconds in https://buildkite.com/materialize/nightly/builds/8003
-
> miri: Disable mz-persist-client iter::tests::consolidation

- test/cluster/index-source-stuck/run.td
- test/cluster/mzcompose.py
See discussion [on Slack](https://materializeinc.slack.com/archives/C01LKF361MZ/p1717761754524879).
-
> Re-enable `test-refresh-mv-restart` and `test-index-source-stuck`

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Release `dbt-materialize` `v1.8.1`. See `CHANGELOG.md` for an overview of the release.
> dbt-materialize: release v1.8.1

- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner/peek.rs
- src/adapter/src/statement_logging.rs
- test/cluster/statement-logging/statement-logging.td
> adapter: add optimization finished lifecycle event

- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/sequencer/inner/peek.rs
- src/adapter/src/coord/sequencer/inner/subscribe.rs
- src/adapter/src/coord/timestamp_selection.rs
- src/adapter/tests/timestamp_selection.rs
> adapter: remove needless asyncs

- bin/ci-annotate-errors
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/test_analytics/config/test_analytics_db_config.py
- misc/python/materialize/test_analytics/data/build_annotation/build_annotation_storage.py
- misc/python/materialize/test_analytics/data/build_data_storage.py
- misc/python/materialize/test_analytics/setup/structures/20-build-annotation.sql
- test/feature-benchmark/mzcompose.py
- test/get-cloud-hostname/mzcompose.py
- test/scalability/mzcompose.py
This requires https://github.com/MaterializeInc/materialize/pull/27546.
As a follow-up, I will try to upload annotations without markdown. This might require some refactorings.
Demo: https://buildkite.com/materialize/test/builds?branch=nrainer-materialize%3Atest-analytics%2Fstore-build-annotations-demo
> test analytics: store build annotations

- src/adapter/tests/timestamp_selection.rs
> adapter: remove unused import

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/github.py
- misc/python/materialize/observed_error.py
Demo: https://buildkite.com/materialize/test/builds?branch=nrainer-materialize%3Atest-analytics%2Frefactor-annotations-demo
Additionally conducted some local testing with downloaded artifacts.
> ci: annotation upload: refactor annotations, separate markdown

- misc/python/materialize/cli/ci_annotate_errors.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/27586.
> ci: annotation upload: fixes

- misc/python/materialize/test_analytics/config/sandbox_db_config.py
- misc/python/materialize/test_analytics/config/test_analytics_db_config.py
> test analytics: add sandbox db config

- misc/python/materialize/test_analytics/config/sandbox_db_config.py
> test analytics: rename sandbox database

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/test_analytics/data/build_data_storage.py
This is based on https://github.com/MaterializeInc/materialize/pull/27619.
> test analytics: always upload build step

- src/txn-wal/src/operator.rs
Previously, the `as_of_until` test in txn-wal was asserting a specific downgrade behavior when writing/reading to a data shard. Shards do not guarantee a specific downgrade behavior and may change that behavior for performance reasons. If the downgrade behavior ever changes, then that test will start failing. This commit fixes the issue by not asserting on specific downgrade behavior and only asserting on actual data messages.
> txn-wal: Fix as_of_until test downgrade assertion

- misc/python/materialize/cli/ci_annotate_errors.py
Seen missing in https://buildkite.com/materialize/test/builds/83862
-
> ci: Add location-url back into annotations

- Cargo.lock
- misc/cargo-vet/audits.toml
- src/postgres-util/src/tunnel.rs
- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
> source/pg: retrieve and log our backend PID and wal_sender_timeout

- doc/user/content/sql/alter-sink.md
- doc/user/content/sql/create-sink/kafka.md
- doc/user/layouts/partials/sql-grammar/alter-sink.svg
- doc/user/sql-grammar/sql-grammar.bnf
> doc: documentation for ALTER SINK

- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
Once upon a time, returning a `ComputeControllerResponse` from `Instance::handle_response` was the only way for the controller to surface responses to its clients. Later the `response_{rx,tx}` channel and `Instance::deliver_response` were introduced to enable delivery of responses outside of `handle_response`. Now we were left with two ways for the controller to surface responses, which made things somewhat confusing.
This PR removes the old way of returning responses from `Instance::handle_response`. All `ComputeControllerResponse`s are now surfaced through `deliver_response`. Apart from streamlining things this also has the potential benefit that `deliver_response` now sees all responses returned to controller clients, so that method can be a place to install hooks that want to act on …
> compute: unify controller response delivery

- misc/python/materialize/test_analytics/data/build_data_storage.py
> ci: Fix typo in build_data_storage

- src/storage-controller/src/lib.rs
I discovered a critical bug in the `ALTER SINK` implementation during the analysis of this nightly test failure [1]. Even though the controller was creating a read hold for the new collection I simply forgot to store it in the sink metadata and was instead dropping on the floor. Unfortunately this wasn't caught during review nor other tests.
The end result is that if a user runs `ALTER SINK` with the current version of the code they end up with a state where the controller ensures the frontier of the *old* collection follows the progress of the sink with the *new* collection. This behavior continuous until environmentd restart, at which point the controller grabs the correct read holds.
However, if the new sink starts falling behind nothing will ensure that the read frontier of the new …
> storage: install read hold for new collection

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/measurement.py
- misc/python/materialize/feature_benchmark/measurement_source.py
- misc/python/materialize/feature_benchmark/scenario.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
Nightly build: https://buildkite.com/materialize/nightly/builds/8148
> feature benchmark: improve code readability, expose wallclock unit

- src/ore/src/process.rs
I wanted to make this part of https://github.com/MaterializeInc/materialize/pull/27705 but then just forgot to push it 🙈 
* This PR adds a clarifying comment.
- N/A
> ore: explain use of `_exit` in `halt!`

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/materialize/test_analytics/setup/tables/00-config.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
This is based on https://github.com/MaterializeInc/materialize/pull/27732.
> test analytics: prevent writes from outdated versions

- misc/python/materialize/test_analytics/test_analytics_db.py
The method invocation call got lost on a rebase.
> test analytics: fix upload prevention

- misc/python/materialize/buildkite.py
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/test_analytics/data/build/build_data_storage.py
- misc/python/materialize/test_analytics/data/build_annotation/build_annotation_storage.py
- misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
- misc/python/materialize/test_analytics/data/scalability_framework/scalability_framework_result_storage.py
- misc/python/materialize/test_analytics/setup/cleanup/remove-build.sql
- misc/python/materialize/test_analytics/setup/tables/00-config.sql
- misc/python/materialize/test_analytics/setup/tables/02-build-step.sql
- misc/python/materialize/test_analytics/setup/tables/10-feature-benchmark.sql
- misc/python/materialize/test_analytics/setup/tables/11-scalability-framework.sql
- misc/python/materialize/test_analytics/setup/tables/20-build-annotation.sql
- misc/python/materialize/test_analytics/setup/views/02-build-job.sql
- misc/python/materialize/test_analytics/setup/views/10-feature-benchmark.sql
- misc/python/materialize/test_analytics/setup/views/100-data-integrity.sql
- misc/python/materialize/test_analytics/setup/views/11-scalability-framework.sql
- misc/python/materialize/test_analytics/setup/views/20-build-annotation.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
- test/feature-benchmark/mzcompose.py
- test/scalability/mzcompose.py
9fb6d944f3 test analytics: identify build jobs by their job id: adjust tables
58f126cc30 test analytics: identify build jobs by their job id: adapt views
fbea3191d2 test analytics: identify build jobs by their job id: adjust code
ce7a2fdb88 test analytics: increase current and minimal supported data version
> test analytics: reference build job id instead of the build step id

- src/adapter/src/coord/sequencer/inner.rs
- src/buf.yaml
- src/proto/src/lib.rs
- src/sql/src/pure.rs
- src/storage-types/src/sinks.proto
- src/storage-types/src/sources/mysql.proto
- src/storage-types/src/sources/mysql.rs
- src/storage/src/source/mysql.rs
- src/storage/src/source/mysql/replication.rs
- src/storage/src/source/mysql/snapshot.rs
- test/mysql-cdc/alter-source.td
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/27468
-
> storage/mysql: Use a separate initial_gtid_set per subsource to allow alter source workflows

- test/sqllogictest/map.slt
https://buildkite.com/materialize/slt/builds/5958
> tests: disable failing SLT test

- misc/python/materialize/checks/all_checks/top_k.py
This adds (migration) tests for https://github.com/MaterializeInc/materialize/pull/27766.
Nightly: https://buildkite.com/materialize/nightly/builds/8181
> tests: extend platform check with limit and offset

- doc/user/content/sql/explain-filter-pushdown.md
- doc/user/layouts/partials/sql-grammar/explain-filter-pushdown.svg
- doc/user/sql-grammar/sql-grammar.bnf
Followup to https://github.com/MaterializeInc/materialize/issues/24498.
Things I'd especially like feedback on:
- Do I have the right style / tone?
- Is this at a reasonable level of abstraction for an external user?
-
> [explain] Add an EXPLAIN FILTER PUSHDOWN doc

- ci/builder/requirements.txt
The original packages were unable to compile on my m2 mac with python 3.12, bumping them worked and it seems easier than digging in to some clang errors.
-
> bump fastavro and matplotlib requirements

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/materialize/test_analytics/data/build/build_data_storage.py
- misc/python/materialize/test_analytics/data/build_annotation/build_annotation_storage.py
- misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
- misc/python/materialize/test_analytics/data/scalability_framework/scalability_framework_result_storage.py
- misc/python/materialize/test_analytics/test_analytics_db.py
- test/feature-benchmark/mzcompose.py
- test/scalability/mzcompose.py
This requires https://github.com/MaterializeInc/materialize/pull/27791.
4ca391d1ee test analytics: submit updates at once
0d30418a50 test analytics: move unsupported data version check
5e7ceb5c9a test analytics: defer connection creation
6538688005 test analytics: rename insert methods
c0f6a0d3e5 test analytics: simplify error handling
> test analytics: collect data and perform upload at the end

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/27828, which did not fix the problem.
> test analytics: fix transaction handling

- src/timely-util/src/operator.rs
> timely-util: make `StreamExt` generic over the container

- test/mysql-cdc-resumption/create-source.td
- test/mysql-cdc-resumption/mzcompose.py
- test/mysql-cdc-resumption/verify-mysql-source-select-all.td
Nightly: https://buildkite.com/materialize/test/builds?branch=nrainer-materialize%3Atests%2Fmysql-cdc-resumption-explicitly-list-tables
> tests: mysql-cdc resumption: explicitly list tables

- bin/ci-builder
> rust: Downgrade nightly version to 2024-04-28

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
Since it's always at the end, can be distracting from the actual issue
-
> ci: Collapse "Updates to test analytics database" step

- misc/python/materialize/version_ancestor_overrides.py
This adds an ignore entry for https://github.com/MaterializeInc/materialize/pull/26807.
> feature benchmark: add ignore entry for PR#26807

- src/storage/src/sink/kafka.rs
Improve error message when a sink times out reading from progress topic
Knowing how far the sink has read would have been valuable troubleshooting a recent customer incident: https://materializeinc.slack.com/archives/C04DJT084KA/p1717506209729339?thread_ts=1717502577.196419&cid=C04DJT084KA
-
> Improve error message when sink times out reading from progress topic

- src/timely-util/src/containers/stack.rs
> timely-util: enable `ExchangeData` for `StackWrapper`

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
> test analytics: timeout: fix

- misc/python/materialize/cli/run.py
The changes in 035b7dd resulted in Ctrl-C no longer working when bin/environmentd was wrapped in a shell script.
The issue was that, when bin/environmentd is run from a noninteractive shell[^1], the shell won't spawn a dedicated process group for the wrapper Python script, and so calling `os.setpgid` would cause the process to no longer be the foreground process group, which means it would no longer receive signals like SIGINT.
The fix is to bring back a piece of the process management approach from before 035b7dd. We fork a *new* process to run the child in and assign *that* process a dedicated process group. The parent bin/environmentd process remains in the foreground process group and thus receives signals, and so can tell the child process and all descendent processes to exit when …
> bin/environmentd: fix Ctrl-C in noninteractive shells

- misc/dbt-materialize/tests/adapter/test_deploy.py
> dbt-materialize: Add retry to deploy tests

- src/storage-client/src/storage_collections.rs
@bkirwi @aljoscha any suggestions on how to test this? 
----
In incident 68, we observed that the current shard finalization implementation could result in a pileup of shard finalization tasks and runaway CPU usage.
Previously, each call to `finalize_shards()` would spawn tasks to finalize all outstanding shards. The storage controller's background task would call `finalize_shards()` every 5s.  Environments with many hundreds of shards to finalize would not be able to finalize all oustanding shards in under 5s, and so over time thousands of shard finalization tasks would get spawned.
This commit refactors the shard finalization implementation to drive finalization from a single background task. When there are no shards to finalize, the background task checks for new shards to finalize …
> storage-client: drive shard finalization from a single task

- src/sqllogictest/src/bin/sqllogictest.rs
- src/sqllogictest/src/runner.rs
Having the actual failures is more useful than the summary. See also https://materializeinc.slack.com/archives/C01LKF361MZ/p1719579151967129
Before:
After:
-
> sqllogictest: Full failure text in junit output

- misc/python/materialize/test_analytics/data/build/build_history_analysis.py
- misc/python/materialize/test_analytics/setup/views/02-build-job.sql
This replaces https://github.com/MaterializeInc/materialize/pull/27860.
> test analytics: views: use materialized view for v_build_job_success

- misc/kind/cluster-node-recovery-test.yaml
- misc/kind/cluster.yaml
1.26.6 is over a year old, and 1.26 has been EOL for a while. 
-
> update kindtest to 1.28

- test/source-sink-errors/mzcompose.py
> source-sink-errors-test: Allow specifying disruptions to run

- test/0dt/mzcompose.py
> tests: Add Kafka/Pg/MySQL sources to 0dt test

- misc/python/materialize/test_analytics/setup/views/02-build-job.sql
This is in particular necessary for builds on main branch. Without this change, the current build will be resolved as the most recent build as soon as its first step completed.
> test analytics: views: fix v_most_recent_build_job

- misc/python/materialize/output_consistency/operation/operation.py
Nightly: https://buildkite.com/materialize/nightly/builds/8328
> output consistency: improve operation description

- misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
- misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
- misc/python/materialize/output_consistency/input_data/return_specs/array_return_spec.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Farray-type-operations
> output consistency: array type: add operations

- misc/python/materialize/output_consistency/data_type/data_type_category.py
- misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/record_operations_provider.py
- misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
- misc/python/materialize/output_consistency/input_data/params/record_operation_param.py
- misc/python/materialize/output_consistency/input_data/return_specs/record_return_spec.py
- misc/python/materialize/output_consistency/input_data/return_specs/undetermined_return_spec.py
- misc/python/materialize/output_consistency/input_data/types/all_types_provider.py
- misc/python/materialize/output_consistency/input_data/types/record_types_provider.py
Nightly: https://buildkite.com/materialize/nightly/builds/8358
> output consistency: support record type

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Nightly: https://buildkite.com/materialize/nightly/builds/8356
This also uncovered a panic: https://github.com/MaterializeInc/materialize/issues/28035
> version consistency: add ignore for contains on list and array

- misc/python/materialize/checks/all_checks/cluster.py
- misc/python/materialize/checks/checks.py
Testing `SHOW CREATE CLUSTER` of https://github.com/MaterializeInc/materialize/issues/15435 additionally in platform checks.
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcluster
> platform checks: show create cluster, alter cluster to managed

- misc/python/materialize/output_consistency/expression/expression_with_args.py
https://buildkite.com/materialize/nightly/builds/8391
> output consistency: fix determine storage layout

- src/adapter/src/catalog/open.rs
Previously, read-only catalogs would skip migrations. However,
read-only catalogs are not supported at versions higher than the
current catalog. So this commit updates read-only catalogs, so that
they DO attempt migrations and fail with a non-writable error if those
migrations are non-empty.
This PR fixes an unrecognized bug.
> catalog: Fix read-only migration write attempts

- doc/user/content/support.md
* This PR adds known-desirable documentation.
- n/a
> doc/user: spell out how to file support ticket

- src/transform/src/lib.rs
This makes `Fixpoint` detect such infinite loops where we reach a plan that we've seen before, e.g. , when we are oscillating between 2 plans, such as in https://github.com/MaterializeInc/materialize/issues/27954, and return with an `Ok` result.
But we still do a `soft_panic`, because we'd like to eventually fix the root cause of these infinite loops.
Kinda addresses:
- https://github.com/MaterializeInc/materialize/issues/27954
- https://github.com/MaterializeInc/materialize/issues/24327
- https://github.com/MaterializeInc/materialize/issues/18409
It doesn't really address the root cause, but will at least make us not error out the query. Not erroring is ok, because the plans are still mostly ok in the cases that we've seen so far. (Also, this can't cause a correctness issue, only a …
> Detect loops in `Fixpoint`

- doc/developer/design/20240609_error_handling.md
- doc/user/content/sql/create-source/kafka.md
- doc/user/layouts/partials/create-source/envelope/upsert/syntax.html
- doc/user/layouts/partials/sql-grammar/create-source-kafka.svg
- doc/user/sql-grammar/sql-grammar.bnf
> storage/kafka/source: Add documentation for ENVELOPE UPSERT (VALUE DECODING ERRORS = INLINE)

- misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
- misc/python/materialize/output_consistency/input_data/types/array_type_provider.py
- misc/python/materialize/output_consistency/input_data/values/array_values_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Ffix-array-type
> output consistency: fix array type

- misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
https://buildkite.com/materialize/nightly/builds/8479
> output consistency: map type: adjust operation specifications

- misc/python/materialize/output_consistency/validation/error_message_normalizer.py
This addresses https://buildkite.com/materialize/nightly/builds/8508#0190a422-818d-46b8-a947-0a34bf98e1dd.
> output consistency: record type: fix error message normalization

- src/catalog/src/durable/persist.rs
> catalog: Improve doc-comments

- src/repr/src/row/encoding2.rs
This PR closes out some TODOs in `encoding2.rs`.
Close out TODOs
- N/a
> persist: Close out some TODOs in `encoding2.rs`

- src/storage-types/src/stats.rs
Adds a `soft_panic_no_log!(...)` when downcasting stats, so we can be sure CI will fail if we ever get the downcasting wrong. Seems useful since we've been iterating in this space lately.
* Complain loudly so we can catch issues in CI
- N/a
> persist: Soft panic on unexpected stats

- misc/python/materialize/output_consistency/enum/enum_constant.py
- misc/python/materialize/output_consistency/expression/expression.py
- misc/python/materialize/output_consistency/expression/expression_with_args.py
- misc/python/materialize/output_consistency/validation/result_comparator.py
- misc/python/materialize/output_consistency/validation/validation_message.py
- misc/python/materialize/output_consistency/validation/validation_outcome.py
This helps debugging when ignore patterns do not match.
> output consistency: introduce expression hash

- src/storage/src/render/sources.rs
This PR removes a forced exchange of data in the storage pipeline. Exchanges can cause a particular worker to get overwhelmed with the work exchanged to it and OOM since we don't have any mechanism to signal an upstream operator in a different worker to slow down.
Beyond that, source operators are in a better position to figure out whether an exchange is needed.
-
> storage: don't force exchange data

- doc/user/content/_index.md
- doc/user/content/get-started/_index.md
- doc/user/content/get-started/quickstart.md
- [Commit 1](https://github.com/MaterializeInc/materialize/pull/28246/commits/78d3b57ca3fb288b3428e1a2fef514975a4828c5): Align definition of Materialize.
- [Commit 2](https://github.com/MaterializeInc/materialize/pull/28246/commits/942a0f63d3db21f86c38fafec25e3dece3fce5b5): Mention non-materialized views + index in the What is materialized page, section Incremental Updates section.
> docs: use uniform  Materialize definition

- misc/python/materialize/output_consistency/expression/expression_characteristics.py
- misc/python/materialize/output_consistency/input_data/types/number_types_provider.py
- misc/python/materialize/output_consistency/input_data/values/number_values_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Fextend-double-values
> output consistency: add infinity value to double type

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
- misc/python/materialize/output_consistency/runner/test_runner.py
- misc/python/materialize/output_consistency/status/test_summary.py
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Finoperable-functions
> output consistency: address inoperable functions

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Seen in https://buildkite.com/materialize/nightly/builds/8544.
> postgres consistency: add ignore entry

- src/compute/src/logging/initialize.rs
Reachability logging currently logs a `null` Timestamp for recursive queries with multi-dimensional timestamps. This PR changes that to always log the first dimension. 
Fixes #21725
> compute: log timestamps from recursive queries

- src/adapter/src/coord/ddl.rs
Since dropping replication slots may rely on those secrets still being present.
Fix #28217.
- n/a
> adapter: drop secrets after replication slots

- misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
- misc/python/materialize/test_analytics/setup/tables/10-feature-benchmark.sql
- misc/python/materialize/test_analytics/setup/views/10-feature-benchmark.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
- test/feature-benchmark/mzcompose.py
https://buildkite.com/materialize/nightly/builds/8597
> test analytics: feature benchmark: scenario group

- misc/python/materialize/checks/all_checks/cluster.py
- test/testdrive/system-cluster.td
This tests new options introduced with v0.106.0.
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atest%2Fmz-cluster-introspect
> tests: cluster introspection configuration

- misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
This addresses the version inconsistency reported in https://buildkite.com/materialize/nightly/builds/8599#0190bc9a-0597-4d97-85b0-ca00d0e90f22.
This was changed with https://github.com/MaterializeInc/materialize/pull/28144#issuecomment-2232764474.
> version consistency: add ignore

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/8583#0190bb4f-b1af-47af-8506-301787807d94.
Issues:
* https://github.com/MaterializeInc/materialize/issues/28300
> postgres consistency: add ignore: ALL and ANY with NULL or empty array

- src/service/src/grpc.rs
This PR makes sure disconnects of the GRPC connection maintained by `GrpcServer` are always logged. Previously, there was a log line at the end of the `ResponseStream` returned by `forward_bidi_stream`, but that was often not executed on a disconnect because the stream gets droppped and therefore aborted on disconnects. To always log a message, we need to instead give the stream a `Drop` impl to do the logging.
GRPC servers log when clients connect, but not when the connection ends.
Apparently this is the correct way to do this. At least according to the comments here: https://github.com/hyperium/tonic/issues/196
- N/A
> cluster: log disconnects of the GrpcServer

- src/adapter/src/coord/sequencer/inner.rs
This ensures that, during a 0dt deployment, the old environment does not attempt to register a table with a timestamp greater than the timestamps claimed by the new environment.
This is possibly a fix for #28216 and #28220.
* This PR might fix a recognized bug.
- n/a
> adapter: during table creation, confirm leadership after acquiring write ts

- misc/python/materialize/output_consistency/common/configuration.py
- misc/python/materialize/output_consistency/data_type/data_type_with_values.py
- misc/python/materialize/output_consistency/data_value/data_value.py
- misc/python/materialize/output_consistency/generators/expression_generator.py
- misc/python/materialize/output_consistency/input_data/test_input_data.py
- misc/python/materialize/output_consistency/input_data/test_input_operations.py
- misc/python/materialize/output_consistency/input_data/test_input_types.py
- misc/python/materialize/output_consistency/output_consistency_test.py
- misc/python/materialize/postgres_consistency/postgres_consistency_test.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
- misc/python/materialize/version_consistency/version_consistency_test.py
dde428eb23 postgres consistency: rework input data filtering
92969e7e3e postgres consistency: rename compatibility flag on data value
430e0fcddc postgres consistency: filter input data
76c33e94a1 version consistency: store used versions
37ca5c3779 version consistency: remove unsupported operations early
b6088d41bb output consistency: specify dependencies between steps
daff768c00 output consistency: expression generator: add assertions
https://buildkite.com/materialize/nightly/builds/8636
> output consistency: rework input data filtering

- test/sqllogictest/mzcompose.py
Reported by Frank in https://materializeinc.slack.com/archives/C01LKF361MZ/p1721310849254009
I'll remove the second commit if it succeeds in showing both failures. Edit: Works:
-
> SLT: Run all commands before failing and generate multiple junit reports

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/8641#0190c59c-589a-4196-aaa7-ea73c0e37c30 in the latest nightly.
> postgres consistency: extend ignore entry

- src/repr/src/adt/jsonb.rs
This uses the shared row to decode jsonb data instead of allocating a new
row. The effect is that we do not need to reallocate a row as we're
decoding. We don't know the size of the decoded row beforehand, so using
the shared row in the limit avoids reallocating.
-
> Use SharedRow in Jsonb::from_slice

- doc/user/content/ingest-data/postgres/alloydb.md
- doc/user/content/ingest-data/postgres/amazon-aurora.md
- doc/user/content/ingest-data/postgres/amazon-rds.md
- doc/user/content/ingest-data/postgres/azure-db.md
- doc/user/content/ingest-data/postgres/cloud-sql.md
- doc/user/content/ingest-data/postgres/debezium.md
- doc/user/content/ingest-data/postgres/self-hosted.md
- doc/user/layouts/shortcodes/postgres-direct/ingesting-data/allow-materialize-ips.html
- doc/user/layouts/shortcodes/postgres-direct/ingesting-data/use-ssh-tunnel.html
Just adding section headings.  This will make it easier going forward to update the contents on these pages (particularly, as some steps (like the create a cluster/connection) can be more easily performed in the console.
> docs: Add section headings to ingest data postgres pages

- src/environmentd/tests/server.rs
Seen again in https://materializeinc.slack.com/archives/C01LKF361MZ/p1721340744190879?thread_ts=1721318334.448959&cid=C01LKF361MZ
-
> cargo test: Temporarily disable test_max_request_size

- doc/developer/guide.md
- misc/nix/shell.nix
* Update CLion -> RustRover
* Add info about git submodules
* Mention more dependencies for lint checks
* Update nix-shell code. Tested on both Linux and macOS. 
* I removed the RUSTFLAGS that were causing errors.
* I'll rebase the commits after addressing any feedback.
-
> Modernize developer guide and nix-shell code

- test/aws/mzcompose.py
This addresses https://buildkite.com/materialize/nightly/builds/8668#0190cc13-d73d-498b-aeb9-034bf06c7187 and extends https://github.com/MaterializeInc/materialize/pull/28105.
Slack: https://materializeinc.slack.com/archives/C01KV5PEZ9R/p1721483273178059
https://buildkite.com/materialize/nightly/builds/8682
> tests: aws-real: also delete jump role after test

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Seen in https://buildkite.com/materialize/nightly/builds/8674.
> postgres consistency: add ignores

- Cargo.lock
- misc/python/materialize/mzcompose/__init__.py
- src/storage-types/src/configuration.rs
- src/storage-types/src/dyncfgs.rs
- src/storage/Cargo.toml
- src/storage/src/source/source_reader_pipeline.rs
- src/storage/src/source/types.rs
- src/storage/src/storage_state.rs
- src/storage/src/storage_state/async_storage_worker.rs
- src/timely-util/src/reclock.rs
The last time we attempted to merge the new reclock operator we started seeing some strange failures in CI (see https://github.com/MaterializeInc/materialize/issues/27455). I finally got to the bottom of them and it turns out that there was a bug in the reclock operator that could only be triggered when it was holding onto deferred updates, those updates were stored into two separate batches that had to merged, and during merge one of those updates consolidated to zero.
The second commit of this PR has the fix and a unit test.
Only the second commit really needs to be reviewed. 
-
> Reapply "storage: wire up new reclock implementation"

- src/storage-client/src/storage_collections.rs
This is working around in a quirk in how we chose the as_of of indexes when bootstrapping, which can lead to indexes that can't hydrate in reaad-only mode.
The problem, in a nutshell: sometimes (quite often) some indexes on the system cluster never hydrate, meaning we never report all clusters as hydrated. It’s actually two things that conspire to make this happen:
- When re-creating storage collections, including tables, we initialize their upper based on the data shard upper. For tables, this is often quite a bit less (couple of seconds) than the logical upper of a table, which is always the upper of the txn shard.
- When we bootstrap/re-create indexes/dataflows, we pick an as_of based on the least upper of all inputs and the compaction …
> adapter,storage: forward upper of tables to upper of txn shard

- doc/developer/guide.md
- doc/developer/mzcompose.md
> dev docs: Mention installing docker

- ci/builder/requirements.txt
This should fix the deploy job: https://buildkite.com/materialize/deploy/builds/15114#0190deeb-93bd-4fa1-bb02-843d93ebc09b
> python: upgrade docker package

- src/transform/src/equivalence_propagation.rs
An oversight called out by https://github.com/MaterializeInc/materialize/pull/28332, the `EquivalencePropagation` transform did not optimize the `group_key` and `aggregates` fields of `Reduce`. These can both be optimized as a function of the equivalences ensured of their inputs, and .. we should do that!
-
> Apply EQProp optimizations to Reduce group keys and aggregates

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
> test analytics: Print last executed SQL nicer

- misc/python/materialize/buildkite_insights/annotation_search/README.md
- misc/python/materialize/buildkite_insights/artifact_search/README.md
- misc/python/materialize/buildkite_insights/artifact_search/artifact_search.py
- misc/python/materialize/buildkite_insights/step_analysis/README.md
- misc/python/materialize/buildkite_insights/step_analysis/analysis.py
> buildkite-tools: Renamed buildkite-step-insights

- .gitignore
> gitignore: Ignore all /bazel-* directories

- src/storage-controller/src/lib.rs
> storage: don't run exports/sinks in read-only mode

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
Observed:
* https://materializeinc.slack.com/archives/C05CQUVHY48/p1721820903825059
* https://materializeinc.slack.com/archives/C05CQUVHY48/p1721828863291669
> test analytics: update statement timeout for DML statements

- misc/python/materialize/version_ancestor_overrides.py
For https://github.com/MaterializeInc/materialize/issues/28455
> feature benchmark: add ignore for ManyKafkaSourcesOnSameCluster

- src/adapter/src/catalog/migrate.rs
Clean up of migrations that no longer appear necessary
-
> adapter: Remove older migrations

- src/persist-client/src/cli/inspect.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/read.rs
- src/persist-client/src/stats.rs
- src/persist-types/src/lib.rs
- src/persist-types/src/txn.rs
- src/txn-wal/src/txn_read.rs
Small fixes found or invented while working on the new columnar format; PRed separately so they don't get lost.
The first commit adds a new bound to an existing trait, which may be controversial? Otherwise I think these are pretty straightforward.
-
> [persist] Minor codec/schema cleanups from a branch

- test/0dt/mzcompose.py
I wish there was a way to still have a view that gets updates to verify that the sink wouldn't write it out, but all tables/mvs/sources are already in read-only mode.
-
> 0dt tests: Sinks with read-only mode and 0dt deployment

- ci/mkpipeline.py
> ci: Don't build with Bazel when source code hasn't changed

- doc/user/data/sql_funcs.yml
Add documentation for pg_size_pretty introduced in #28205.
> doc/user: add documentation for pg_size_pretty

- ci/test/pipeline.template.yml
> ci: Automatically retry replica isolation test

- bin/version-consistency-explain-test
- misc/python/materialize/output_consistency/common/configuration.py
- misc/python/materialize/output_consistency/execution/query_execution_manager.py
- misc/python/materialize/output_consistency/execution/query_output_mode.py
- misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
- misc/python/materialize/output_consistency/output/base_output_printer.py
- misc/python/materialize/output_consistency/output/output_printer.py
- misc/python/materialize/output_consistency/output/reproduction_code_printer.py
- misc/python/materialize/output_consistency/output_consistency_test.py
- misc/python/materialize/output_consistency/query/query_result.py
- misc/python/materialize/output_consistency/query/query_template.py
- misc/python/materialize/output_consistency/validation/result_comparator.py
- misc/python/materialize/output_consistency/validation/validation_message.py
- misc/python/materialize/postgres_consistency/postgres_consistency_test.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
- misc/python/materialize/version_consistency/version_consistency_test.py
- test/output-consistency/mzcompose.py
- test/postgres-consistency/mzcompose.py
- test/version-consistency/README.md
- test/version-consistency/mzcompose.py
ed46f617e8 output consistency: query template: extract db_object_name determination
2f0d05b4bd output consistency: output printer: rename variable
5d6e64ee99 output consistency: explain plan: add test support
067a091dd4 output consistency: explain plan: allow configuring
36a83845f6 output consistency: explain plan: result comparator
d05e303752 output consistency: explain plan: ignore filter
a264585ea2 version consistency: fix name in args parser
de2c41e712 version consistency: explain plan: add entry point
b5dd08ce23 version consistency: explain plan: README
a3346019cd version consistency: explain plan: add ignore
3cf9267a64 version consistency: support EXPLAIN PHYSICAL as well
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aversion-consistency%2Fexplain-plans …
> version consistency: test explain plans

- test/sqllogictest/aggregates_2.slt
- test/sqllogictest/explain/aggregates.slt
- test/sqllogictest/explain/physical_plan_aggregates.slt
This addresses https://materializeinc.slack.com/archives/C0761MZ3QD9/p1721267616770529.
> tests: add additional SLT (explain) tests for aggregations

- doc/user/assets/sass/_base.scss
- doc/user/assets/sass/_content.scss
- doc/user/assets/sass/_layout.scss
- doc/user/assets/sass/_mixins.scss
- doc/user/assets/sass/_nav.scss
- doc/user/content/_index.md
Cherry-pick css changes only from older PRs 
- https://github.com/MaterializeInc/materialize/pull/22247
- https://github.com/MaterializeInc/materialize/pull/24656
> Docs Nissar's css changes

- src/adapter/src/catalog/open/builtin_item_migration.rs
> catalog: Improve panic msg

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
> test-analytics: autocommit first

- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/deployment/state.rs
- src/environmentd/src/lib.rs
Make it easier to test 0dt deployments by waiting to report the "IsLeader" deployment status until the deployment is willing to accept queries as the leader.
Previously, 0dt deployments would report "IsLeader" and *then* restart, which made it hard for 0dt tests to know when it could start issuing queries to the deployment after a successful promotion.
Part of #27406.
- n/a
> environmentd: don't declare `IsLeader` before restart

- test/0dt/mzcompose.py
Observed in https://buildkite.com/materialize/nightly/builds/8814#0190ec3b-efb4-4069-9886-ce67d27e6025.
> tests: fix 0dt test

- bin/ci-annotate-errors
More a temporary thing to understand what we get exactly in this case: https://materializeinc.slack.com/archives/C057X0NG91B/p1721914973133919
> ci: fix host name resolution

- misc/python/materialize/test_analytics/data/build/build_data_storage.py
- misc/python/materialize/test_analytics/setup/tables/01-build.sql
- misc/python/materialize/test_analytics/setup/tables/02-build-job.sql
Follow-up to https://github.com/MaterializeInc/materialize/pull/28524.
> test analytics: fix remarks column removal

- misc/python/materialize/checks/mzcompose_actions.py
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/data_ingest/transaction_def.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/services/materialized.py
- misc/python/materialize/parallel_workload/action.py
- test/0dt/mzcompose.py
> 0dt tests: Add webhook source

- .github/ISSUE_TEMPLATE/04-epic.md
See updated project management plan for August: https://www.notion.so/materialize/Project-Management-b3d2da90abbf4dce8483484eb3788496
> Update Github Epic template based on new project management plan for August

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/measurement.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
Addressing https://materializeinc.slack.com/archives/C01LKF361MZ/p1722002482703419.
Nightly: https://buildkite.com/materialize/nightly/builds/8851
> feature benchmark: fix specified unit

- src/adapter/src/coord/appends.rs
- src/adapter/src/coord/command_handler.rs
Before, we had `buffer_or_write_table_update`, and had to be careful to use it in all relevant places.
Now we teach `BuiltinTableAppend`/`builtin_table_update` itself to do the right thing in read-only mode, so all usage sites now do the correct thing.
Fixes #28575
I wanted to call out that all of the `BuiltinTableAppend` methods are "lying", in a way: the future completes without the write actually having happened, in read-only mode. This was also the case with `buffer_or_write` before, but now it's happening one level deeper.
-
> adapter: handle read-only table writes one layer deeper

- misc/python/materialize/mzbuild.py
The CargoBuild.prepare_batch function is where we invoke `cargo build` to actually do the build, so it's also where we should re-invoke with `--message-format=json` to get the machine readable output.
If we defer the JSON-formatted invocation to CargoBuild.run, we may end up triggering a recompilation due to different features being enabled, which can be quite slow.
* This PR fixes a glitch reported by @danhhz on Slack: https://materializeinc.slack.com/archives/C0246GEHL8N/p1722270862997909
- n/a
> mzbuild: get machine-readable Cargo output in prepare_batch

- src/environmentd/src/deployment/preflight.rs
> adapter: in preflight checks, retry fencing when doing 0dt deployment

- doc/user/content/releases/v0.109.md
> doc/user: polish v0.109 release notes

- misc/python/materialize/test_analytics/config/mz_db_config.py
- misc/python/materialize/test_analytics/config/sandbox_db_config.py
- misc/python/materialize/test_analytics/config/test_analytics_db_config.py
- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/materialize/test_analytics/data/base_data_storage.py
22fb56d9ec test analytics: connection: logging
04b41cc215 test analytics: connection: move cluster to config
c60ed44617 test analytics: connection: move statement timeout to config
> test analytics: minor improvements

- misc/python/materialize/feature_benchmark/aggregation.py
- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/comparator.py
- misc/python/materialize/feature_benchmark/measurement.py
- misc/python/materialize/feature_benchmark/measurement_source.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
- test/feature-benchmark/mzcompose.py
Demo: https://buildkite.com/materialize/nightly/builds/8871
> feature benchmark: print measurement unit

- doc/user/content/sql/alter-system-set.md
Removed one more outdated example of enabling/disabling RBAC
> docs: rm enable RBAC from alter-system-set

- src/adapter/src/coord/introspection.rs
- test/cluster/mzcompose.py
This PR changes how introspection subscribes are reinstalled when the target replica disconnects (but is not dropped). Rather than immediately clearing the data produced by the subscribe from its target storage collection, the delete is deferred until a new batch of data arrives for the reinstalled subscribe.
The intention of this change is to better handle situations were the target replica needs a long time to reconnect and produce the subscribe snapshot (e.g. because it is unresponsive). Before this change, there would be no introspection data for this replica. This could be confusing, especially since the user is probably not aware of the fact that the replica disconnected. With this change, the old data is kept around until there is new data to replace it.
* This PR fixes a …
> adapter: defer deletes on introspection subscribe reinstalls

- doc/user/content/releases/v0.110.md
> doc/user: polish v0.110 release notes

- doc/user/assets/sass/_base.scss
- doc/user/assets/sass/_content.scss
- doc/user/assets/sass/_layout.scss
- doc/user/assets/sass/_mixins.scss
- doc/user/assets/sass/_nav.scss
- doc/user/assets/sass/_railroad_diagrams.scss
- doc/user/layouts/partials/head.html
- doc/user/layouts/partials/sidebar.html
Add kapa.ai widget to docs. Supersedes https://github.com/MaterializeInc/materialize/pull/26747.
> docs: Add kapa.ai to docs

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/comparator.py
This is a step towards https://github.com/MaterializeInc/materialize/issues/28713.
It is unclear which measurement causes the problem.
> feature benchmark: unit mingling: improve observability

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/8947#01911d2a-e643-4789-b87a-4a3c033193aa.
> postgres consistency: add ignore for floor return type

- misc/python/materialize/feature_benchmark/aggregation.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/comparator.py
- test/feature-benchmark/mzcompose.py
This should fix https://github.com/MaterializeInc/materialize/issues/28713, which was again observed with more log output in https://buildkite.com/materialize/nightly/builds/8947#01911d2a-e5cc-4c9e-9fe8-68f9fd74ea76.
> feature benchmark: fix unit mismatch

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
Nightly: https://buildkite.com/materialize/nightly/builds/8939
> feature benchmark: execution logic: improve readability

- .github/workflows/cla.yml
> new CLA Assistant

- src/storage-controller/src/lib.rs
- src/storage-controller/src/rehydration.rs
- src/storage/src/storage_state.rs
This PR replaces some panics and asserts in storage code with soft panics/asserts. It does this for panics related to observing storage commands/responses and read hold downgrades for collections that do not exist. These observations indicate bugs in our code and so should be reported, but continuing afterwards does not compromise correctness, so we don't want to crash in production.
Note that the storage code contains panics in a lot of other places. It's likely that many of these should be downgraded to soft panics as well, but it's not always obvious which ones are essential to uphold correctness.
Limits the impact of #28784.
-
> storage: panic less in production

- src/orchestrator-process/src/secrets.rs
This will help us confirm whether the error in #28570 is missing secrets or something else.
* This PR will help us track down a bug.
> orchestrator-process: add context to secrets errors

- misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Nightly: https://buildkite.com/materialize/nightly/builds/8957
> output consistency: regex flag n

- test/testdrive/github-26353.td
This addresses https://buildkite.com/materialize/nightly/builds/8987#01912c9e-6cff-4a01-b817-1d13524ca426.
Required since https://github.com/MaterializeInc/materialize/commit/7c8b4e4891b13f77afac1e19bcf9faa81f1f85ce.
> tests: fix github-26353.td

- test/aws-localstack/mzcompose.py
This test was relying on defects in the original orphaned secrets cleanup logic. Those defects were fixed in
MaterializeInc/materialize#28830, so adjust the test to match.
* This PR fixes a test failure.
> test/aws-localstack: fix for improved orphaned secrets cleanup

- doc/user/content/sql/system-catalog/mz_catalog.md
- src/adapter/src/catalog/builtin_table_updates.rs
- src/catalog/src/builtin.rs
- src/catalog/src/memory/objects.rs
- test/sqllogictest/autogenerated/mz_catalog.slt
- test/sqllogictest/mz_catalog_server_index_accounting.slt
- test/testdrive/kafka-avro-sinks.td
Fixes https://github.com/MaterializeInc/materialize/issues/28789
> Add key_format and value_format fields to mz_sinks catalog table

- ci/test/check-merge-with-target.sh
See: https://materializeinc.slack.com/archives/C01LKF361MZ/p1723127178705329
> ci: merge skew check: run cargo check with --tests

- src/transform/src/analysis/equivalences.rs
In the course of mining "things that `ColumnKnowledge` does", one is understanding that a collection of constant values not all of which are equal, but all of which are non-null, still results in a fact that they are all non-null. Introducing this information seems to be pretty disruptive (in a possibly good way) in the one file I was looking at, so let's take more of a peek to see what moves around (or .. potentially find that it's a bug).
-
> Teach `Equivalences` to mine `Constant` for non-nullability information

- doc/user/content/manage/monitor/grafana.md
Update grafana.md to use latest config.yml example
This PR fixes an outdated link reference in the doc
> Update grafana.md to use latest config.yml example

- doc/user/content/manage/monitor/datadog.md
- doc/user/content/manage/monitor/grafana.md
Changed to point to materializeincLab repo example
> docs: update sample sql_exporter config.yml.example link

- doc/user/content/releases/v0.111.md
- doc/user/content/releases/v0.113.md
Zaktualizuj informacje o wydaniu dla wersji 0.111
> doc/user: polish v0.111 release notes

- src/transform/src/canonicalization.rs
`ReduceScalars` had a bug for `Join` where it would `reduce` it relative to its *output* type rather than *input* type. The nullability of columns may have changed between the two, and they may be a consequence of the join constraints. As such, it is appropriate to use this information in optimizing them, as we may optimize out the very test that produces that information.
> Correct join scalar reduction

- src/storage-controller/src/instance.rs
This PR fixes high CPU usage observed in `Instance::recv`, apparently caused by the use of `FuturesUnordered`. Using a `select_all` instead fixes it.
Fixes #28941
I must admit I don't understand this fix at all. Is creating a `FuturesUnordered` just really expensive? The documentation doesn't mention anything like this. Plus we use it in a bunch of other places (`StorageController::recv`, compute's `Instance::recv`) and it doesn't seem to cause any problems there?
[Relevant Slack thread.](https://materializeinc.slack.com/archives/CMH6PG4CW/p1723484666151749)
> storage: fix high CPU usage in `Instance::recv`

- ci/mkpipeline.py
> ci: fix branch not existing in mkpipeline

- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
> controller,0dt: in caught-up check, ignore transient collections

- misc/images/materialized/entrypoint.sh
- misc/python/materialize/mzcompose/services/materialized.py
- test/0dt/mzcompose.py
> 0dt tests: Check reconciliations after forced migration

- misc/python/materialize/output_consistency/input_data/operations/string_operations_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9067#01914b81-7875-456a-b787-b523ea9f07e1.
> postgres consistency: extend ignore

- ci/mkpipeline.py
- ci/test/pipeline.template.yml
> ci: Combine pipeline and step priority

- test/0dt/mzcompose.py
> 0dt test: Add SUBSCRIBE

- misc/python/materialize/buildkite.py
I'm not sure if this lets us prevent duplicate posts
> ci: Reenable QA notification (a bit more carefully)

- ci/test/build.py
- misc/python/materialize/spawn.py
Temporary network problems caused build failure in https://buildkite.com/materialize/test/builds/88142#019149a4-83fa-438f-9a32-55203e878ce0
> build: Retry parca-debuginfo upload

- src/adapter/src/coord.rs
- src/environmentd/src/bin/environmentd/main.rs
- src/environmentd/src/lib.rs
This commit does the following w.r.t. startup timing logs:
- Remove/condense granular timings that take less than 100 ms in cloud.
- Within a function, ensure that all lines are covered by some timeing logging.
Works towards resolving #28722
> envd: Clean up startup timing logs

- src/repr/src/row/encoding2.rs
This is defined to have the same representation, but is better-supported in practice.
https://github.com/apache/arrow/blob/main/format/Schema.fbs#L117-L145
Support for #24830 - in particular, maps are not sortable via any of the built-in sorting utils, including `lexsort` and `arrow-row`. Switching this over is much cheaper than building upstream support. (And if upstream develops support it should be equally straightforward to switch back.)
I've added a clause to the proptests that ensures the data is sortable via `arrow-row`. This fails before this PR and seems to pass afterwards.
> [persist] Switch to list-of-structs encoding of maps

- src/repr/src/row/encoding2.rs
- src/storage-types/src/sources.rs
Followup to https://github.com/MaterializeInc/materialize/pull/28916
* Add `proptest` to assert the DataType of the resulting Arrow Array does not change based on what values were encoded
* Fix encoding for `ScalarType::Array` so the newly added test passes
Fix an existing bug
> persist: Fix nullability in DatumColumnEncoder part 2

- misc/python/materialize/release/auto_cut_release.py
Motivation: automating the release cut process
> Add step to auto cut release script that creates the next release version docs file if it doesn't exist

- doc/user/content/concepts/clusters.md
@kay-kim: mostly wanted to fix the unrendered links. Feel free to ignore the other suggestions.
> doc/user: minor patches to cluster concepts page

- doc/user/content/releases/v0.114.md
- misc/python/materialize/git.py
- misc/python/materialize/release/auto_cut_release.py
Existing script creates but does not commit the doc file for the next release.
Tested on my fork.
> release: git commit the newly created doc files

- ci/nightly/pipeline.template.yml
> ci: More disk for legacy upgrade test

- src/storage/src/render/sinks.rs
Fixes https://github.com/MaterializeInc/materialize/issues/29042
Details are in attached issue ^
> storage/sinks: Remove unnecessary warn logs from envelope debezium sinks with no keys

- doc/user/config.toml
- doc/user/content/administration/billing.md
- doc/user/content/concepts/clusters.md
- doc/user/content/sql/create-cluster.md
- doc/user/content/sql/create-source/kafka.md
Just some initial documentation of things may affect your cost.
> docs: initial billing page

- test/canary-environment/tests/all_replicas_ready.sql
Follow-up to https://github.com/MaterializeInc/materialize/pull/28907.
> release verification: adapt all_replicas_ready.sql

- misc/images/materialized/README.md
add license and privacy policy disclaimers to docker image readme
> add disclaimers to docker image

- misc/python/materialize/output_consistency/data_value/data_column.py
- misc/python/materialize/output_consistency/data_value/data_value.py
- misc/python/materialize/output_consistency/enum/enum_constant.py
- misc/python/materialize/output_consistency/execution/evaluation_strategy.py
- misc/python/materialize/output_consistency/execution/query_execution_manager.py
- misc/python/materialize/output_consistency/expression/constant_expression.py
- misc/python/materialize/output_consistency/expression/expression.py
- misc/python/materialize/output_consistency/expression/expression_with_args.py
- misc/python/materialize/output_consistency/generators/query_generator.py
- misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
- misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
- misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
- misc/python/materialize/output_consistency/output/reproduction_code_printer.py
- misc/python/materialize/output_consistency/query/query_result.py
- misc/python/materialize/output_consistency/query/query_template.py
- misc/python/materialize/output_consistency/selection/column_selection.py
- misc/python/materialize/output_consistency/selection/row_selection.py
- misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Just a minor refactoring I did not want to put into the other already large PR.
> output consistency: refactoring: split file

- misc/python/materialize/feature_flag_consistency/input_data/feature_flag_configurations.py
This requires https://github.com/MaterializeInc/materialize/pull/28995.
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Afeature-flag-consistency%2Fadd-flags-for-joins-w-join (w/ https://github.com/MaterializeInc/materialize/pull/28995)
> feature flag consistency: add flags for joins

- src/compute/src/compute_state.rs
- src/compute/src/metrics.rs
Adds a metric to capture the duration it takes to handle commands in a
replica, represented as a histogram per worker and command kind.
We might consider adding the same as a introspection source.
> Metric to capture command handling duration

- doc/user/content/sql/create-connection.md
- doc/user/layouts/shortcodes/private-preview.html
Missed some feedback for https://github.com/MaterializeInc/materialize/pull/29066
> docs: address feedbacks from PR

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9209#019174b7-b9f2-46b3-965c-9eece001c49a.
Filed issue:
* https://github.com/MaterializeInc/materialize/issues/29143
> postgres consistency: add ignore for unnest on array

- src/frontegg-mock/src/lib.rs
Fixing a small bug where the `tenant_id` in the scim configuration should not be expected as payload but be extracted from the access token itself.
This was noticed while switching mock service for the Terraform provider tests in here: https://github.com/MaterializeInc/terraform-provider-materialize/pull/634
> frontegg-mock: extract tenant id from claims

- misc/python/materialize/data_ingest/executor.py
Easier to guarantee correctness during retries. Seen in https://buildkite.com/materialize/nightly/builds/9175#01916b31-7cf6-426f-ac04-790659ef2c64
> data-ingest: Get rid of manual commits

- ci/mkpipeline.py
Temporary network errors can cause our agents to get lost: https://buildkite.com/materialize/nightly/builds/9216
Buildkite starts considering an agent as lost very quickly, this might explain why we are seeing increased agent timeouts since February: https://buildkite.com/changelog/222-lower-agent-timeouts
In this case we should automatically retry the test to save developer time.
> ci: Retry on agent lost

- src/compute-client/src/metrics.rs
This PR improves on the existing dataflow wallclock lag metric by making three changes:
* Drops the `avg` aggregation in favor of total sum and total count.
* Adjusts the metric names to immitate the summary metric type. We cannot use an actual summary metric because the `prometheus` crate doesn't support those.
* Changes the aggregation approach to exposing the min/max value over the sliding window of the most recent 60 samples, instead of updating the metric values once per minute.
For the last part, a `MinMax` datastructure is introduced to efficiently keep track of the min/max values are the sample window slides. Some care is taken to reduce the memory usage of that datastructure to roughly 750 bytes per compute collection.
Part of #28097 
See …
> compute: wallclock lag summary metric

- src/adapter/src/coord.rs
The `Coordinator` keeps the `Catalog` behind an `Arc` reference. It occasionally hands out references to the `Catalog` by cloning the `Arc`. When it wants to mutate the `Catalog` it calls `Coordinator::catalog_mut()`, which under the hood calls `Arc::make_mut()`. This function will clone the catalog iff any other `Arc` references to the catalog exists.
During startup the `Coordinator` was accidentally creating a reference to the catalog and then immediately calling `catalog_mut()` for every index and materialized view. As a result, the catalog was cloned once per index and materialized view.
This commit drops the reference to the catalog before calling `catalog_mut()` preventing the catalog from being cloned. Locally this causes each call to `catalog_mut()` to speed up from 20-30 ms to …
> adapter: Avoid necessary catalog clones

- src/cluster/src/server.rs
This PR fixes a cancel safety bug: Previously, the `ClusterClient` would `take` the `TimelyContainer` out of the `Arc`-shared state and then await a response from a channel. If the GRPC client disconnected while that await was still pending, the `ClusterClient` would be dropped and with it the `TimelyContainer`. Dropping a `TimelyContainer` makes is synchronously block on the Timely workers to finish, which never happens, so the entire tokio thread becomes blocked forever.
The fix implemented here if to never move the `TimelyContainer` out of its `Arc`. Additionally, we add a panicking `Drop` impl for `TimelyContainer`, to ensure we can quickly diagnose similar bugs in the future.
This is only a quick-fix. Notably, it doesn't ensure that the stream created by `forward_bidi_stream` is …
> cluster: avoid accidentally dropping TimelyContainer

- Cargo.lock
- src/frontegg-mock/Cargo.toml
- src/frontegg-mock/src/main.rs
- src/frontegg-mock/src/middleware.rs
- src/frontegg-mock/src/middleware/logging.rs
- src/frontegg-mock/src/server.rs
Adding a logging middleware for easier debugging as per the Frontegg improvements tracking issue here: https://github.com/MaterializeInc/terraform-provider-materialize/issues/461
> frontegg-mock: add logging

- src/storage-controller/src/persist_handles/read_only_table_worker.rs
Fixes #29217
Before, it could happen that the upper we get from the txn shard is actually _behind_ the current shard upper. I think this is an artifact of how we create those new tables and how we bump their upper on bootstrap.
fyi @def-, since you reported the bug
> 0dt: in read-only mode, check new upper when advancing upper of migrated tables

- Cargo.lock
- src/frontegg-mock/BUILD.bazel
- src/frontegg-mock/Cargo.toml
- src/frontegg-mock/tests/local.rs
Adding tests for the Frontegg Mock service as per the Frontegg Mock epic: https://github.com/MaterializeInc/terraform-provider-materialize/issues/461
> frontegg-mock: add tests

- src/frontegg-mock/tests/local.rs
Adding some more extra tests for the Frontegg Mock service as per the Frontegg Mock epic: https://github.com/MaterializeInc/terraform-provider-materialize/issues/461
> frontegg-mock: add additional tests

- src/frontegg-mock/BUILD.bazel
Seen in https://buildkite.com/materialize/test/builds/89308#019199a7-1936-47cc-8413-4579b8b0e421
> Fix merge skew in Bazel files on main

- test/lang/js/params.test.ts
Seen failing in https://buildkite.com/materialize/nightly/builds/9303#01919b56-9410-4fe2-8859-ca8a2e297495
Follow-up to https://github.com/MaterializeInc/materialize/pull/29250
> js test: Fix formatting

- doc/user/content/get-started/install-materialize-emulator.md
- misc/images/materialized/README.md
changes:
readme:
- docker run command to remove volume, use latest image, and run in background.
- logs instructions based on running in background.
docs cc @kay-kim 
- docker run command to remove volume, use latest image, and run in background.
- logs instructions based on running in background.
> update docker run command

- src/adapter/src/coord.rs
Storage usage pruning blocks startup, but the time spent pruning was hidden from the `envd_start_duration` metric by being in `coord.serve` rather than `coord.bootstrap`.
We would prefer to move this to a background task that's kicked off by `serve`, but there are complications with running this in the background, and moving it from `bootstrap` to `serve` later is not the hard part.
* This PR fixes a bug @jkosh44 noted on Slack.
> adapter: move storage usage pruning to bootstrap

- doc/user/content/get-started/install-materialize-emulator.md
- doc/user/content/get-started/quickstart.md
Additional clarification between Mat Console and Emulator.
> docs: tweaks to quickstart for docker

- ci/nightly/pipeline.template.yml
- misc/python/materialize/buildkite.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/util.py
- test/parallel-benchmark/mzcompose
- test/parallel-benchmark/mzcompose.py
Example run: https://buildkite.com/materialize/nightly/builds/9354#0191a800-eb79-45b2-b657-7a8f9990f3e5
> tests: Introduce new Parallel Benchmark

- src/ore/src/panic.rs
Before:
cluster-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.cluster-s1-replica-s1-gen-0: 2024-09-03T22:07:21.654804Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "h2 protocol error: error reading a body from connection", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
After:
cluster-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cluster-materialized-1  | cluster-s1-replica-s1-gen-0: 2024-09-03T22:07:21.654804Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "h2 protocol error: error reading a body from …
> ore: newline at the end of panic handler

- src/adapter/src/coord/sequencer.rs
- src/sql/src/rbac.rs
This avoids a `BTreeMap` allocation during plan sequencing, which we don't need for most plans. Instead, we defer the lookup to a `FnOnce` closure that does a linear search instead of forming a new map.
The implementation is different if there are two connections with the same ID. Previously, it would return the last entry, while now it returns the first entry. This can only happen if there are collisions on the primary ID dimension, which seems to be bug elsewhere.
> Avoid unconditional allocation during sequencing

- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Add InsertsSelects and InsertWhereNotExists scenarios

- misc/python/materialize/output_consistency/execution/query_execution_manager.py
- misc/python/materialize/output_consistency/generators/query_generator.py
- misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py
- misc/python/materialize/output_consistency/query/additional_data_source.py
- misc/python/materialize/output_consistency/query/additional_source.py
- misc/python/materialize/output_consistency/query/query_template.py
- misc/python/materialize/output_consistency/selection/row_selection.py
This addresses https://buildkite.com/materialize/nightly/builds/9389#0191bcd1-8c03-476f-9242-56d04c8397f3. It should also fix issues in https://buildkite.com/materialize/nightly/builds/9386#0191bc39-6600-484c-8b48-ee026721201b.
f366c7f717 output consistency: characteristics: ensure that all expressions are considered
1c7a57bc67 output consistency: row selection: trim after data source minimization
ceb3d383f7 output consistency: query generator: fix query template cloning
03cf29fc56 output consistency: query generator: introduce clone method
44e4700b29 output consistency: data sources: rework
08ba471899 output consistency: query generator: refactoring to simplify code
2fc2521358 output consistency: query generator: fix source minimization
5f9d828187 output consistency: data source: rename …
> output consistency: source handling fixes

- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Implement overwriting and linear regression

- src/catalog/src/durable/transaction.rs
This commit provides two optimizations to durable catalog transactions.
The first is to return early from functions that update many objects,
but are provided an empty collection. For example, if `update_items` is
passed an empty map. These functions can be O(n^2) on the number of
objects in the catalog. So returning early for no-ops can save a lot of
time.
The second optimization is to make `uniqueness_violation` an `Option`.
`uniqueness_violation` is a function that is called on every pair of
objects during the `verify` method. Often `uniqueness_violation` is
hard coded as a function that always returns `false`. So we'd often
uselessly iterate over all pairs of objects (which is O(n^2)), doing
nothing. Now we only iterate over the objects when
`uniqueness_violation` is `Some`.
Works …
> catalog: Optimize durable transaction operations

- src/catalog/src/durable/transaction.rs
When updating an in-progress durable catalog transaction, we need to
verify that we're not violating the uniqueness constraint, if one
exists. Previously, we would modify the transaction and then check all
items against every other item so see if anything violates the
constraint. This is O(n^2) and can be fairly slow when there are a lot
of items. Additionally, the catalog changes are usually small and so
it's wasteful to always compare every item against every other item.
This commit adds a new method that only checks the newly inserted
items against all other items. This is O(n * k), where n is the number
of items and k is the number of new items. This commit also updates all
callers of the old method to switch to the new method.
Works towards resolving #28722
This PR adds a …
> catalog: Optimize uniqueness violation check

- src/catalog/src/durable/transaction.rs
This commit adds the following methods to durable catalog transactions:
- `update_by_key`
- `update_by_keys`
- `delete_by_key`
- `delete_by_keys`
These methods allow callers to update/delete entries by passing in one
or more keys for the modified entries. The existing methods, `update`
and `delete`, use a closure that's passed in as an argument. That
closure is run on every single entry and returns some result that
indicates whether the entry should be updated/deleted. That is
needlessly expensive since we almost always know the keys of the
entries to modify apriori. The new methods can directly modify the
desired entries, without having to check all entries.
This commit also updates the majority of `update` and `delete` callers
to use the new methods. The remaining callers could also be …
> catalog: Optimize transaction update and delete

- doc/user/assets/sass/_base.scss
- doc/user/assets/sass/_layout.scss
- doc/user/assets/sass/_nav.scss
- doc/user/config.toml
- doc/user/layouts/partials/banner.html
- doc/user/layouts/partials/header.html
- doc/user/layouts/partials/toc.html
Will revert on Oct 3 (well, the changes for the height adjustments will be reverted.  will keep the banner.html and related css).
> docs: add workshop banner

- src/buf.yaml
- src/storage-types/src/sources.proto
Clean up a buf breaking annotation needed on a previous PR
> storage/sources: Remove old buf breaking annotation

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Allow comparing against older versions

- test/testdrive/source-tables.td
> testdrive: Skip new source-tables.td file

- misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
- misc/python/materialize/output_consistency/validation/validation_message.py
This addresses https://buildkite.com/materialize/nightly/builds/9450#0191c863-6cfc-47db-a0e0-07e5a589cfb0.
> output consistency: add error message ignore

- misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
https://buildkite.com/materialize/nightly/builds/9469
> output consistency: fix list_agg and change it to use order

- misc/nix/shell.nix
> misc/nix: add bazel dependency

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9477#0191d7dc-966f-4375-87d1-aee339c84f0d and others.
> version consistency: add ignore for unnest

- misc/python/materialize/test_analytics/data/parallel_benchmark/parallel_benchmark_result_storage.py
- misc/python/materialize/test_analytics/setup/cleanup/remove-build.sql
- misc/python/materialize/test_analytics/setup/tables/12-parallel-benchmark.sql
- misc/python/materialize/test_analytics/setup/views/100-data-integrity.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
- test/parallel-benchmark/mzcompose.py
Worked: https://buildkite.com/materialize/nightly/builds/9483#0191d8ad-4bea-42ba-9aa6-11fccf3dc5a9
> parallel-benchmark: Upload results

- src/transform/src/literal_constraints.rs
This is in the context of robustifying the optimizer. The situation before this PR was a bit spooky, because if some other transforms didn't properly clean up after `LiteralConstraints` created an `IndexedFilter` Join with an empty `possible_vals`, then we'd panic, because the protobuf serialization was assuming that this field is a non-empty Vec. This panic was fortunately never actually happening, because other transforms always clean up properly. But still, it's easy to just create an empty constant, and then we have one less brittle interaction between different transforms.
The new code is exercised by several existing tests in `literal_constraints.slt`.
The then branch is new, the else branch is just code motion.
-
> Make `LiteralConstraints` specially handle empty `possible_vals`

- doc/developer/guide-testing.md
- src/adapter/src/catalog.rs
- src/adapter/src/coord/peek.rs
- src/adapter/src/coord/sequencer/inner/peek.rs
- src/adapter/src/optimize/peek.rs
- src/adapter/src/optimize/subscribe.rs
- src/expr/src/relation.rs
- src/transform/src/canonicalize_mfp.rs
- src/transform/src/dataflow.rs
- src/transform/src/join_implementation.rs
- test/sqllogictest/postgres/subselect.slt
This is a large number of trivial comment fixes. (Partially split off from an other PR.)
> Some trivial comment fixes

- misc/python/materialize/cli/ci_annotate_errors.py
For https://github.com/MaterializeInc/materialize/issues/29496
> ci: add error entry regarding source dropping

- misc/python/materialize/data_ingest/executor.py
Don't use pg8000's identifiers, which are different from MySQL's
Seen in https://buildkite.com/materialize/nightly/builds/9518#0191eb29-df8e-41e9-a8db-b1105d7c820c
Noticed because https://github.com/MaterializeInc/materialize/pull/29179 bumped pg8000
> data-ingest: Fix mysql sources

- src/compute-client/src/controller/instance.rs
This PR downgrades the asserts that verify that dropped compute instances are empty to soft asserts. Dropped instances still having replicas and collections is unexpected but likely not serious enough to crash the entire environment.
This PR also adds more logging about the stray replicas/collections, to increase our chances of successfully debugging these errors when they happen.
Part of #29528
> compute: downgrade asserts and add more logging

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9517#0191e958-12e4-47e6-9009-7bbba1660229.
> postgres consistency: add regex ignore

- src/adapter/src/catalog/migrate.rs
Remove two migrations applied in previous releases
> adapter: Remove applied migrations for sources and subsource statements

- test/feature-benchmark/mzcompose.py
This fault was introduced with 36123b02 on July 24th. It caused no regressions to be reported since then.
> feature benchmark: fix regression reporting

- misc/python/materialize/checks/all_checks/load_generator.py
- misc/python/materialize/checks/all_checks/mysql_cdc.py
- misc/python/materialize/checks/all_checks/pg_cdc.py
- misc/python/materialize/checks/all_checks/source_errors.py
- misc/python/materialize/checks/all_checks/ssh.py
- misc/python/materialize/mzcompose/__init__.py
- test/pg-cdc/subsource-resolution-empty.td
- test/testdrive/tpch.td
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source-checks
> tests: platform checks: create table from source

- misc/python/materialize/mzcompose/__init__.py
- src/sql-parser/tests/testdata/ddl
- test/pg-cdc/subsource-resolution-empty.td
- test/testdrive/source-tables.td
- test/testdrive/tpch.td
> tests: create table from source: miscellaneous test extensions

- src/expr/src/scalar/func.rs
This makes `TextConcat` monotonic in its second argument. See reasoning in the added code comment.
* This PR adds a known-desirable feature: https://github.com/MaterializeInc/materialize/issues/29507
* But note that the user wanted `try_parse_monotonic_iso8601_timestamp(left(json_data -> 'ts_field', -1) || '.000Z')`, which still won't be covered, because we'd need monotonicity in the first argument of text concatenation, but we don't have that. (`left` would also be needed.)
Please very carefully check my reasoning in the code comments.
> Adjust monotonicity of `TextConcat`

- misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9578#0192010a-c9c8-49b9-82f6-cd61538876f1.
> output consistency: extend ignore entry

- src/orchestrator-kubernetes/src/cloud_resource_controller.rs
The other one was closed as duplicate
> comment: Change reference to issue

- test/limits/mzcompose.py
Nightly: https://buildkite.com/materialize/nightly/builds/9606
> tests: create table from source: product limits

- src/sql/src/pure/error.rs
- src/sql/src/pure/mysql.rs
- src/sql/src/pure/postgres.rs
- test/mysql-cdc/alter-source.td
- test/mysql-cdc/mysql-cdc.td
Minor error output fixes related to source versioning, caught by testing team
Fixes https://github.com/MaterializeInc/materialize/issues/29504
Fixes https://github.com/MaterializeInc/materialize/issues/29567
Fixes https://github.com/MaterializeInc/materialize/issues/29586
> storage/sources: Fix some error messages related to source versioning work

- src/orchestrator-kubernetes/src/lib.rs
Propagate owner references from the environmentd pod to objects created by the Kubernetes orchestrator. This ensures that if the cloud orchestration layer tears down environmentd (say, due to a failed deployment), any services created by that environmentd are torn down as well.
Fix https://github.com/MaterializeInc/materialize/issues/28729.
> orchestrator-kubernetes: add owner references

- test/testdrive/coord-read-holds.td
Seen failing in https://buildkite.com/materialize/nightly/builds/9633#0192077a-afbd-4457-bf41-cb4b61a12732
> testdrive: Fix coord-read-holds in 4 replica test

- misc/python/materialize/output_consistency/validation/error_message_normalizer.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9640#01920a0d-7ab3-400d-ab7e-639507f68d2c and https://buildkite.com/materialize/nightly/builds/9640#01920a0d-7ab1-4645-85ba-1393ac69b123.
> output consistency: error message matching

- doc/developer/feature-benchmark.md
- misc/python/materialize/feature_benchmark/benchmark_result.py
- misc/python/materialize/feature_benchmark/benchmark_result_selection.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/report.py
- test/feature-benchmark/mzcompose.py
This implements #29590.
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Afeature-benchmark%2Frepeated-scenario-runs
> feature benchmark: repeated scenario runs

- test/canary-load/mzcompose.py
- test/cloud-canary/mzcompose.py
- test/limits/mzcompose.py
Seen in https://buildkite.com/materialize/nightly/builds/9659
> tests: Fix various nightly test failures

- src/dyncfg-launchdarkly/src/lib.rs
- ensures the client is started
- keeps trying if initial ld sync fails
balancer LD sync was completely broken
> fix balancer ld sync

- misc/python/materialize/github.py
> ci: Use database-issues repository for ci annotations

- misc/python/materialize/cloudtest/k8s/environmentd.py
- test/cloudtest/test_egress_ips.py
This is needed for upgrade checks and addresses https://buildkite.com/materialize/nightly/builds/9684#019223cd-8e71-4214-86c8-cbf5e540b1cd.
Related PR: https://github.com/MaterializeInc/materialize/pull/29578
https://buildkite.com/materialize/nightly/builds/9705
> tests: fix cloudtest upgrade test

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9695#01922665-8d12-4745-96e4-ead5ed03b96b.
The behavior changed with https://github.com/MaterializeInc/materialize/pull/29454.
The precision increased in this case:
```
CONTENT_MISMATCH: Value differs at row index 0, column index 6.
Expression: var_pop(sin(real_val))
Value 1 (Constant folding v0.118.0-dev.0 (ace96ed78)): '0.14535977026281247' (type: <class 'float'>)
Value 2 (Constant folding v0.118.0-dev.0 (deb8beb77)): '0.1453597702628124' (type: <class 'float'>)
Query 1: SELECT bool_and((varchar_8_val NOT LIKE 'a?c')), avg(int4_val), jsonb_object_agg(real_val, decimal_39_0_val ORDER BY row_index, real_val, decimal_39_0_val), var_pop(double_val), sum(decimal_39_8_val), sum(int2_val), var_pop(sin(real_val)) FROM …
```
> version consistency: add ignore for floating precision

- Cargo.lock
- src/balancerd/BUILD.bazel
- src/balancerd/Cargo.toml
- src/catalog-debug/BUILD.bazel
- src/catalog-debug/Cargo.toml
- src/clusterd/BUILD.bazel
- src/clusterd/Cargo.toml
- src/environmentd/BUILD.bazel
- src/environmentd/Cargo.toml
- src/persist-client/BUILD.bazel
- src/persist-client/Cargo.toml
- src/testdrive/BUILD.bazel
- src/testdrive/Cargo.toml
> release: bump to version v0.119.0-dev.0

- test/sqllogictest/audit_log.slt
- test/sqllogictest/github-19273.slt
- test/sqllogictest/github-19290.slt
- test/sqllogictest/object_ownership.slt
- test/sqllogictest/rename.slt
- test/sqllogictest/retain_history.slt
<s>Merge blocked by https://github.com/MaterializeInc/database-issues/issues/8545 ⚠️ </s>
https://buildkite.com/materialize/slt/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source-slt
* https://github.com/MaterializeInc/database-issues/issues/8545
> tests: create table from source: slt

- ci/release-qualification/pipeline.template.yml
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
- test/postgres/Dockerfile
Nightly: https://buildkite.com/materialize/nightly/builds/9747
> postgres: upgrade version

- doc/user/content/ingest-data/mysql/amazon-aurora.md
- doc/user/content/ingest-data/mysql/amazon-rds.md
- doc/user/content/ingest-data/mysql/azure-db.md
- doc/user/content/ingest-data/mysql/google-cloud-sql.md
- doc/user/content/ingest-data/mysql/self-hosted.md
- doc/user/content/ingest-data/postgres/alloydb.md
- doc/user/content/ingest-data/postgres/azure-db.md
- doc/user/content/ingest-data/postgres/cloud-sql.md
- doc/user/content/ingest-data/postgres/neon.md
- doc/user/content/ingest-data/postgres/self-hosted.md
- doc/user/layouts/shortcodes/mysql-direct/ingesting-data/allow-materialize-ips.html
- doc/user/layouts/shortcodes/mysql-direct/ingesting-data/use-ssh-tunnel.html
- doc/user/layouts/shortcodes/postgres-direct/ingesting-data/use-ssh-tunnel.html
Skipped the mysql/debezium file  since will wait after https://github.com/MaterializeInc/materialize/pull/29150
> docs: Add section headings to ingest-data/mysql pages

- doc/user/content/integrations/_index.md
> doc/user: minor page to integrations overview

- doc/user/content/ingest-data/mysql/amazon-aurora.md
- doc/user/content/ingest-data/mysql/amazon-rds.md
- doc/user/content/ingest-data/mysql/azure-db.md
- doc/user/content/ingest-data/mysql/google-cloud-sql.md
- doc/user/content/ingest-data/mysql/self-hosted.md
Some stragglers related to https://github.com/MaterializeInc/materialize/pull/29807 ?
> docs: update ingest-data MySQL pages to public preview

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/all_checks/optimizer_notices.py
- misc/python/materialize/checks/all_checks/owners.py
- misc/python/materialize/checks/all_checks/statement_logging.py
- misc/python/materialize/checks/mzcompose_actions.py
> tests: checks in parallel

- misc/python/materialize/buildkite_insights/costs/extract_stats.py
> buildkite-insights: New instance types

- test/debezium/postgres/24-types-money.td
- test/debezium/postgres/40-truncate-table.td
- test/persistence/kafka-sources/kafka-counters-after.td
- test/persistence/kafka-sources/kafka-counters-before.td
Renamed three test files to re-enable (two of) them.
> tests: re-enable files

- doc/user/config.toml
- doc/user/layouts/partials/head.html
- doc/user/layouts/partials/toc.html
Oh ... actually -- there is a 404 with loading css, which won't be resolved by this pr.  😞 drat.
But ... might as well clean these up anyways.
- Removed the deeplink logic as I don't think this works
- Also, check that offsets[].id is defined.  <<-- Hope to remove this whole offset thing in Oct.
> docs: fix jquery error + remove warnings

- src/storage-controller/src/lib.rs
This commit removes the remaining async work from
`register_introspection_collection`. This likely has modest speedups,
but also helps prevent expensive work from sneaking in in the future.
Works towards resolving MaterializeInc/database-issues#8384
> controller: Remove async from register

- test/canary-environment/models/loadgen/schema.yml
- test/canary-environment/models/mysql_cdc/schema.yml
- test/canary-environment/models/pg_cdc/schema.yml
- test/canary-environment/models/tpch/schema.yml
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax
Based on https://github.com/MaterializeInc/materialize/pull/29497.
> canary environment: dbt: migrate syntax regarding tests

- misc/python/materialize/feature_flag_consistency/ignore_filter/feature_flag_consistency_ignore_filter.py
- misc/python/materialize/output_consistency/query/query_result.py
- misc/python/materialize/output_consistency/query/query_template.py
This addresses https://buildkite.com/materialize/nightly/builds/9806#0192564d-be14-4ea7-aa02-dc0a1ae748c5.
> feature flag consistency: add ignore regarding floating ops with enable_eager_delta_joins

- src/adapter/src/coord.rs
> coord: Update log contents

- misc/bazel/cargo-gazelle/src/bin/main.rs
Changes `cargo-gazelle` to copy the temp files into place instead of moving, this should support multi volume setups like some of our CI machines have. A downside is the swapping in of the temp file isn't necessarily atomic, but that shouldn't matter here.
Fix a nightly build
> bazel: `cargo-gazelle` copy files instead of moving

- src/storage-controller/src/lib.rs
During startup some environments take a significant amount of time
opening their critical since handles to persist shards; roughly 2-3
seconds.
Empirically we've found that connecting to each shard in the background
before opening since handles can speed this process up to ~900ms. This
commit adds the background task to warm up persist state for each
shard.
Works towards resolving #8384
> storage: Warm up persist during startup

- misc/python/materialize/checks/all_checks/upsert_unordered_key.py
- src/storage/src/upsert.rs
- test/testdrive/kafka-debezium-sources-compound-key.td
Fixes MaterializeInc/database-issues#8622
> upsert: respect the order of key indices when computing the key hash

- src/storage-operators/src/s3_oneshot_sink.rs
Putting this up to get some CI reps and see if we can get evidence that a worker other than worker 0 is handling batch 0.
----
Ensure that the COPY TO S3 operation is aborted if we ever see evidence that data batches are not assigned to the worker we expect (`batch_id % num_workers`).
This is important because we force worker 0 to create an empty file for batch 0 even if no data is present.
> storage/s3-oneshot: check exchange assumption

- misc/images/materialized/entrypoint.sh
- test/limits/mzcompose.py
- test/sqllogictest/github-17808.slt
> emulator: Link to GitHub discussions instead of issues

- misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
This addresses https://buildkite.com/materialize/nightly/builds/9878#01927496-9536-4d8d-9b2a-0274ef7f1f2c.
> postgres consistency: more lenient number comparison

- README.md
I'm not sure about the exact wording we want
> README: Switch from data warehouse to data store

- src/transform/src/analysis/equivalences.rs
This is optimizing another thing that showed up prominently in PolarSignals' CPU profile when the optimizer was stuck during incident-217. We make class unification linear with the total number of expressions (ignoring log factors from the BTreeMap) instead of quadratic with the number of classes times quadratic with class sizes.
If stacked on top of https://github.com/MaterializeInc/materialize/pull/29936, this gives another ~40% end-to-end optimizer speedup (in debug mode, on my laptop) on the ["small repro" of incident-217](https://docs.google.com/document/d/10GuKeUcmK-LIRWc4EEro7jZHz5v1z-MwhQOB4PXOzK8/edit?usp=sharing).
(There is an old comment on top of the code block about the possibility of making use of sortedness, but that looked like a larger/riskier change, so I haven't done it …
> Asymptotically faster class unification in `EquivalenceClasses::minimize_once`

- misc/python/materialize/mzcompose/composition.py
Makes it easier to interpret output
> tests: Buildkite section for running workflows

- src/catalog/src/durable/persist.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/internal/trace.rs
Fixes https://github.com/MaterializeInc/database-issues/issues/8530.
See the long comment on the diff for why this works!
> [persist] Push empty batch when adding fuel

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9955#019285ab-5146-4c63-b45a-3f3ac6db5c3f.
> postgres-consistency: add ignore

- misc/python/materialize/output_consistency/generators/query_generator.py
- misc/python/materialize/output_consistency/output/output_printer.py
- misc/python/materialize/output_consistency/runner/test_runner.py
- misc/python/materialize/output_consistency/status/test_summary.py
This helps should help identifying unused ignore entries.
> output consistency: print used ignore entries

- misc/python/materialize/data_ingest/workload.py
> data-ingest: Disable RTR

- ci/test/build.py
This might address https://github.com/MaterializeInc/database-issues/issues/8664.
> debug symbols: upload debug infos for balancerd

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
> postgres consistency: extend ignore regarding jsonb object generation

- doc/user/config.toml
- doc/user/content/manage/dbt/_index.md
ported from https://github.com/MaterializeInc/materialize/pull/29150
> docs: tweak dbt page to highlight indexes

- .gitignore
- ci/plugins/mzcompose/hooks/pre-exit
- misc/python/materialize/parallel_benchmark/framework.py
- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Flesh out sqlite support further

- Cargo.lock
- misc/cargo-vet/audits.toml
Fixes: MaterializeInc/database-issues#8604
> *: upgrade postgres dependency

- misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
This addresses https://buildkite.com/materialize/nightly/builds/10022#01929a41-885a-47c4-a658-1f07844b0376.
> postgres consistency: improve function definition regarding sort order

- src/timestamp-oracle/src/postgres_oracle.rs
> stop logging postgres config during tsoracle init

- test/mysql-cdc-old-syntax/table-in-mysql-schema.td
- test/pg-cdc-old-syntax/alter-source.td
- test/pg-cdc-old-syntax/pg-cdc.td
- test/pg-cdc-old-syntax/subsource-resolution-empty.td
> pg cdc tests: Fix error messages

- misc/python/materialize/mzbuild.py
Fixes downloading images from Dockerhub with CI_BAZEL_BUILD=0 locally
> mzbuild: Always consider Bazel files as inputs

- src/catalog/src/builtin.rs
- test/cluster/pg-snapshot-resumption/03-ensure-source-down.td
- test/testdrive/distinct-arrangements.td
- test/testdrive/source-tables.td
Events for 'source tables' were already being reported in `mz_internal.mz_source_status_history`, so this PR updates the `mz_source_statuses` view to include a row for each source table's latest status, in addition to the subsource and source statuses already reported in the view.
Fixes https://github.com/MaterializeInc/database-issues/issues/8511 (this is the last task to complete the work outlined in https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20240625_source_versioning__table_from_sources.md#system-catalog--introspection-updates)
> Reflect source table statuses in mz_internal.mz_source_statuses

- src/adapter/src/catalog/open.rs
This commit accomplished two things. First, it panics with a helpful
error if there's ever two builtin objects with identical descriptions.
Second, it makes it much more obvious that the amount of new IDs
allocated is equal to the amount of new builtin objects.
Review with whitespace hidden
> adapter: Cleanup builtin migration ID allocation

- src/compute/src/render/continual_task.rs
It never needed to be async, I'm just more familiar with those, so it was easier to type that way when prototyping. This also replaces the disconnected input with a summary.
https://github.com/MaterializeInc/database-issues/issues/8427
I'm not totally sure of myself here, so definitely look at this with a careful eye!
> ct: rewrite step_forward as a normal (non-async) timely operator

- misc/python/materialize/zippy/debezium_actions.py
- misc/python/materialize/zippy/debezium_capabilities.py
- misc/python/materialize/zippy/mysql_cdc_capabilities.py
- misc/python/materialize/zippy/pg_cdc_capabilities.py
- misc/python/materialize/zippy/sink_actions.py
- misc/python/materialize/zippy/source_actions.py
- misc/python/materialize/zippy/source_capabilities.py
- misc/python/materialize/zippy/table_capabilities.py
- misc/python/materialize/zippy/view_actions.py
- misc/python/materialize/zippy/view_capabilities.py
- misc/python/materialize/zippy/watermarked_object_capabilities.py
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source-kafka-zippy
> tests: create table from kafka source: zippy

- misc/python/materialize/checks/all_checks/alter_connection.py
- misc/python/materialize/checks/all_checks/alter_index.py
- misc/python/materialize/checks/all_checks/debezium.py
- misc/python/materialize/checks/all_checks/error.py
- misc/python/materialize/checks/all_checks/identifiers.py
- misc/python/materialize/checks/all_checks/json_source.py
- misc/python/materialize/checks/all_checks/kafka_formats.py
- misc/python/materialize/checks/all_checks/kafka_protocols.py
- misc/python/materialize/checks/all_checks/multiple_partitions.py
- misc/python/materialize/checks/all_checks/ranges.py
- misc/python/materialize/checks/all_checks/rename_source.py
- misc/python/materialize/checks/all_checks/retain_history.py
- misc/python/materialize/checks/all_checks/sink.py
- misc/python/materialize/checks/all_checks/ssh.py
- misc/python/materialize/checks/all_checks/top_k.py
- misc/python/materialize/checks/all_checks/upsert.py
- misc/python/materialize/checks/all_checks/upsert_enrich.py
- misc/python/materialize/checks/all_checks/upsert_many_columns.py
- misc/python/materialize/checks/all_checks/upsert_many_rows.py
- misc/python/materialize/checks/all_checks/upsert_many_updates.py
- misc/python/materialize/checks/all_checks/upsert_shrink_grow.py
- misc/python/materialize/checks/all_checks/upsert_unordered_key.py
- misc/python/materialize/checks/all_checks/upsert_wide.py
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source-kafka-checks ✅ 
Blocked by:
* https://github.com/MaterializeInc/database-issues/issues/8607
* https://github.com/MaterializeInc/database-issues/issues/8606
* https://github.com/MaterializeInc/database-issues/issues/8611
> tests: create table from kafka source: platform checks

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- misc/python/materialize/feature_benchmark/scenarios/concurrency.py
- misc/python/materialize/feature_benchmark/scenarios/subscribe.py
- misc/python/materialize/parallel_benchmark/scenarios.py
- test/0dt/mzcompose.py
- test/bounded-memory/mzcompose.py
- test/cloudtest/test_compute_shared_fate.py
- test/cloudtest/test_crash.py
- test/cloudtest/test_disk.py
- test/cloudtest/test_smoke.py
- test/cloudtest/test_storage_shared_fate.py
- test/cluster-isolation/mzcompose.py
- test/limits/mzcompose.py
- test/pubsub-disruption/mzcompose.py
- test/restart/mzcompose.py
- test/source-sink-errors/mzcompose.py
- test/storage-usage/mzcompose.py
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source-kafka-py
> tests: create table from kafka source: other checks

- test/testdrive/source-tables.td
Re-enable these tests to see if they occur on any smaller replica sizes. I've been unable to repro this issue https://github.com/MaterializeInc/database-issues/issues/8515 except on replica size `8` and very infrequently, even with that argument.
> Re-enable tests in source-tables.td on all but the largest replica size

- ci/nightly/pipeline.template.yml
- ci/test/cargo-test/mzcompose.py
- misc/python/materialize/checks/backup_actions.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/services/postgres.py
- misc/python/materialize/zippy/backup_and_restore_actions.py
- test/0dt/mzcompose.py
- test/backup-restore-postgres/mzcompose.py
- test/cloud-canary/mzcompose.py
- test/cluster/mzcompose.py
- test/data-ingest/mzcompose.py
- test/launchdarkly/mzcompose.py
- test/output-consistency/mzcompose.py
- test/platform-checks/mzcompose.py
- test/postgres-consistency/mzcompose.py
- test/postgres/pg_hba.conf
- test/restart/mzcompose.py
- test/retain-history/mzcompose.py
- test/sqllogictest/mzcompose.py
- test/txn-wal-fencing/mzcompose.py
Fixes: https://github.com/MaterializeInc/database-issues/issues/8659
> backup+restore tests: Basic Postgres support

- misc/python/materialize/checks/all_checks/kafka_formats.py
- test/0dt/mzcompose.py
- test/kafka-resumption/sink-networking/setup.td
- test/kafka-resumption/sink-queue-full/during.td
- test/kafka-resumption/sink-queue-full/setup.td
- test/kafka-rtr/mzcompose.py
- test/kafka-rtr/resumption/mz-setup.td
- test/kafka-rtr/simple/mz-setup.td
- test/kafka-rtr/simple/verify-rtr.td
- test/rtr-combined/rtr/mz-setup.td
- test/testdrive/audit-log.td
- test/testdrive/connection-alter.td
- test/testdrive/connection-create-drop.td
- test/testdrive/github-12005.td
- test/testdrive/kafka-data-formats.td
- test/testdrive/kafka-exactly-once-sink.td
- test/testdrive/kafka-include-key-sources.td
- test/testdrive/kafka-sinks.td
- test/testdrive/regex-sources.td
- test/testdrive/source-statistics.td
Part of https://github.com/MaterializeInc/database-issues/issues/8549. Additional statements that required https://github.com/MaterializeInc/database-issues/issues/8597.
Nightly: https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source-other-formats ✅
> tests: create table from kafka source: other formats

- doc/user/assets/sass/_base.scss
- doc/user/assets/sass/_content.scss
- doc/user/layouts/shortcodes/private-preview.html
Increasing contrast for preview in dark mode + update where we send people when they contact us.
> docs: public preview callout css updates

- misc/python/materialize/parallel_benchmark/framework.py
- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Support graphing for long-running tests

- src/catalog-debug/src/main.rs
This commit makes the following two clean-ups to the catalog debug tool:
- Remove the `--organization-id` argument because it's redundant with the `--environment-id` argument.
- Only require the `--secrets` argument when performing an upgrade check.
> catalog-debug: Clean up debug tool arguments

- src/orchestratord/src/controller/materialize/resources.rs
Reduces scope of orchestratord-installed NetworkPolicies.
Following up on https://github.com/MaterializeInc/materialize/pull/30154#discussion_r1813278965
> Reduce scope of orchestratord-installed NetworkPolicies

- src/adapter/src/coord/sequencer/inner/create_continual_task.rs
- test/sqllogictest/ct_transform.slt
- test/sqllogictest/ct_various.slt
Adapts my demo script to be an slt test and fixes the bug found along the way.
Closes https://github.com/MaterializeInc/database-issues/issues/8697
There's a tiny bit of polish left to be done here, but I have a hard stop today and wanted to get a CI run in. Feel free to take a look though!
> ct: fix bugs for the demo

- ci/release-qualification/pipeline.template.yml
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/test_analytics/data/product_limits/product_limits_result_storage.py
- misc/python/materialize/test_analytics/setup/cleanup/remove-build.sql
- misc/python/materialize/test_analytics/setup/tables/14-product-limits.sql
- misc/python/materialize/test_analytics/setup/views/100-data-integrity.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
- test/limits/mzcompose.py
Fixes: https://github.com/MaterializeInc/database-issues/issues/8658
> limits test: Try finding new limits, record wallclock and explain wallclock times

- src/environmentd/tests/sql.rs
This commit removes a test that is testing a feature which has bene removed.
Resolves #MaterializeInc/database-issues/issues/8667
> tests: Remove old test

- src/adapter/src/coord/sequencer/inner.rs
- test/testdrive/insert-select.td
- test/testdrive/update.td
Fixes https://github.com/MaterializeInc/database-issues/issues/8692
> adapter: Fix read-then-write dependency checks for source tables

- ci/nightly/pipeline.template.yml
- test/bounded-memory/mzcompose.py
Searching the limit for materialized memory works rather well; only clusterd memory causes issues.
> bounded memory: improve search

- src/catalog/src/durable/persist.rs
Previously, when the durable catalog would apply updates, it would first read all available updates from persist, then deserialize all updates, then apply all updates. This would cause deserialization errors in the following scenario:
1. Catalog `A` is running on version `v`.
2. Catalog `B` starts on version `v+1`.
3. Catalog `B` writes a fence token to the catalog.
4. Catalog `B` writes an update to the catalog in a format that cannot be deserialized by version `v`.
5. Catalog `A` reads both the fence token and the new update.
6. Catalog `A` attempts to deserialize the fence token and the new update, but fails to deserialize the new update and panics.
This commit fixes the issue by deserializing and applying updates in batches, by timestamp. The fence token is always written at a …
> catalog: Avoid deserialization errors on fence

- test/sqllogictest/transform/fold_vs_dataflow/7_window_agg_dataflow.slt
Follow-up to https://github.com/MaterializeInc/materialize/pull/30103
Noticed in https://buildkite.com/materialize/slt/builds/6078
> slt: Update explain plan for window functions

- src/controller/src/clusters.rs
Fixes MaterializeInc/database-issues#8656
Before, the adapter would learn about replica-processes of older generations going down, and erroneously report those replicas as offline.
> adapter: in cluster controller, filter out events from past replicas

- src/sql/src/plan/query.rs
This PR changes the planning of `DISTINCT FROM` to avoid the conditional evaluation construct `If`, which is challenging to work around, due to its soft requirements around conditional evaluation. Instead, we plan `a IS DISTINCT FROM b` as 
```
(a != b OR a IS NULL OR b IS NULL) AND (a IS NOT NULL OR b IS NOT NULL)
```
The belief is that this produces comparable results, by the reasoning of the comments of the PR.
> Alter planning of `DISTINCT FROM` to avoid `If`

- misc/python/materialize/cli/ci_closed_issues_detect.py
See https://materializeinc.slack.com/archives/C01LKF361MZ/p1730147503499899.
Nightly: https://buildkite.com/materialize/nightly/builds/10180 ✅
> closed issues: improve detection of ambiguous issue references

- misc/python/materialize/cli/ci_closed_issues_detect.py
This improves https://github.com/MaterializeInc/materialize/pull/30234.
Nightly: https://buildkite.com/materialize/nightly/builds/10185 ✅
> closed issues: improve detection of ambiguous issue references (2)

- src/catalog/src/builtin.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/select
- src/sql-parser/tests/testdata/show
- src/sql/src/plan/statement/show.rs
- test/sqllogictest/mz_catalog_server_index_accounting.slt
- test/testdrive/source-tables.td
* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/database-issues/issues/8689
functionally equivalent to the existing `SHOW SUBSOURCES ON source_name;`
> Introduce a 'SHOW TABLES ON source_name' statement

- doc/developer/design/20240625_source_versioning__table_from_sources.md
> Update source versioning design doc with migration guide

- src/transform/src/analysis/equivalences.rs
This PR improves the performance of `Equivalences::union`, and potentially alters its outputs (on non-canonical inputs).
Superficially, there is now a method `union_many` that accepts multiple equivalences to merge, and which `union` just calls. This allows our variadic `Union` stages to call this once, rather than a sequence of rebuilds. This also reduces a fair bit of cloning. I did not measure how impactful this step is in isolation.
More importantly, the implementation is changed from quadratic all-pairs set intersection to a map based approach that intersects the keys of two maps, and builds equivalence classes from the results. If an expression maps to `foo` and `bar` under the two maps, then a class `(foo, bar)` is created, and assigned a new class identifier. This new identifier …
> Improve `Equivalences::union` implementation performance

- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
- misc/dbt-materialize/tests/adapter/test_deploy.py
See [Slack thread](https://materializeinc.slack.com/archives/C06SXUZ77QF/p1730242003602489).
> dbt-materialize: patch cluster privilege copy

- doc/user/content/manage/access-control/invite-users.md
There was a user question about what **Pending Approval** meant. While updating the page, figured I'd surface it to be in the left-hand nav.
> docs: invite-users - add to nav and tweak

- misc/python/materialize/test_analytics/setup/tables/00-config.sql
- test/canary-environment/mzcompose.py
> tests: Update references to QA devs

- test/limits/mzcompose.py
> limits test: Fix MAX_COUNT logic

- src/compute-client/src/as_of_selection.rs
Stepping back the as-of for dataflows with persisted outputs relies on the compute controller holding back input collections for these dataflows accordingly. This is currently not guaranteed during a release upgrade, as the holding-back was introduced at the same time as the stepping-back in as-of selection.
To avoid panicking in upgrade tests, this PR makes the stepping-back a soft as-of constraint. It is still required for the correctness of CTs so we need to revert this PR in a follow-up. This should be safe to do after at least one Mz version was released with the new holding-back behavior, and will definitely be safe to do once the old holding-back behavior has rotated out of our upgrade tests.
Fixes …
> compute: make as-of back-stepping a soft constraint

- src/catalog/src/durable/persist.rs
> startup: Add logs to catalog init

- src/catalog/src/durable/persist.rs
> catalog: Make read-only commit error more obvious

- src/catalog/src/expr_cache.rs
This commit separates the `Expression` struct, which is cached in the expression cache, into two separate structs. The `LocalExpressions` struct stores a local optimization of an expression and the `GlobalExpressions` struct stores a global optimization of an expression. Each expression type is stored as a separate entry in the cache.
Certain object types only have a local optimization in the catalog, others only have a global optimization, and others have both representations. Storing the different expression types separately makes working with the different object types easier.
While we're changing the cache structure, we also remove the `notices` field, which is actually just a denormalized view of the `dataflow_metainfos` field.
Works towards resolving …
> catalog: Split local and global expression cache

- src/expr/src/relation.rs
Fix the join case in `try_visit_scalars_1` by including the `implementation` field, similarly to 29952397b22688fa12efbc73dc4e4fa2841a931d.
I didn't write a regression test, because the current state is probably not causing an actual issue, because currently we call this method (I think) only on joins that have no implementation filled in yet. But this might change at any moment. (Note that 29952397b22688fa12efbc73dc4e4fa2841a931d did fix an actually occurring bug.)
> More join visitation fix

- doc/user/content/get-started/quickstart.md
- doc/user/content/transform-data/idiomatic-materialize-sql/top-k.md
Mention idiomatic materialize sql for top-k and add link
> docs: add link to idiomatic materialize sql

- misc/python/materialize/cli/run.py
> run: Print notice for CRDB/Postgres when not running

- doc/user/content/sql/create-sink/kafka.md
> Document tiered storage recommendations

- src/storage-client/src/storage_collections.rs
Before, it could happen that we try and await progress when the upper is already empty. In that case we would wait forever.
> storage: in StorageCollections, fix leaking upper futures

- src/orchestratord/src/controller/materialize/resources.rs
the balancers will panic if they can't resolve the backend service they are configured to talk to, which makes it hard to tell when real problems are happening
> don't create the balancers until after the environment is running

- .config/nextest.toml
> Minor cargo test and SLT fixes

- doc/user/assets/sass/_content.scss
| - | - |
| ![image](https://github.com/user-attachments/assets/459ca648-2bbc-4544-bfeb-0f6ca08d1540) | ![image](https://github.com/user-attachments/assets/34a98602-1ca7-4396-8bc9-d705f7bcf892) |
> fix the scrollable table thead bg color for dark mode.

- doc/user/content/sql/alter-cluster.md
> fix partial sentence in graceful reconfig doc

- src/adapter/src/coord/caught_up.rs
Before, we would try and compute.collection_hydrated() on _all_ collections, which would error for storage collections. This does not happen in production, because we have 0dt disabled for sources, but I noticed this failing when testing locally.
> adapter,0dt: in caught_up.rs, fix hydration check

- doc/user/content/sql/show-clusters.md
- doc/user/content/sql/system-clusters.md
> docs: quickstart cluster has size of 25cc

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
> docs: tweak operational guidelines for helm/sh installs

- misc/bazel/README.md
Add some docs for running Rust tests with Bazel
Help folks use Bazel!
> bazel: Add docs for running tests

- src/storage/src/render/persist_sink.rs
- src/storage/src/render/sources.rs
- src/storage/src/source/reclock.rs
- src/storage/src/source/reclock/compat.rs
- src/storage/src/source/source_reader_pipeline.rs
Closes materializeinc/database-issues#8609
> storage: in reclocking, obey read-only flag

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/templates/networkpolicies.yaml
use the latest console, and clean up a few final issues
> few final helm chart tweaks

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
ensure doc versions stay synced, and remove some unnecessary configuration settings
> a few more doc tweaks

- bin/bump-version
- bin/helm-chart-version-bump
- ci/builder/Dockerfile
- ci/builder/requirements.txt
- ci/test/lint-main/checks/check-helm-docs.sh
- ci/test/lint-slow.sh
- misc/helm-charts/operator/README.md
- misc/python/materialize/cli/helm_chart_version_bump.py
- misc/python/materialize/cli/orchestratord.py
> Bump versions in helm chart on each (Cloud) release

- src/cloud-resources/src/crd/materialize.rs
this should allow users to use an arbitrary name for the materialize cr, while still letting environmentd use a uuid (which is required in some places)
this will autogenerate a default value for this field if unset, but will allow us to set it manually for things like our cloud environment
> configure the environment id as part of the materialize cr

- src/environmentd/tests/server.rs
Fixes #MaterializeInc/database-issues/8743
> test: fix flake

- test/cluster/mzcompose.py
`test-github-8734` is flaky, as discovered by @antiguru [here](https://buildkite.com/organizations/materialize/pipelines/test/builds/95043/jobs/0193458c-d694-4f1f-845c-11a7878caca7/log).
> test/cluster: fix flaky stuck frontier check

- test/cluster/mzcompose.py
Change retry to 2 seconds. https://materializeinc.slack.com/archives/C01LKF361MZ/p1732114012367649?thread_ts=1732109946.944959&cid=C01LKF361MZ
* This PR fixes a potential test issue.
> test/cluster: another attempt to fix flaky stuck frontier check

- src/transform/src/analysis/equivalences.rs
The `Equivalences::project` code is potentially cubic, and .. that's bad. There is an open issue https://github.com/MaterializeInc/database-issues/issues/8755 that this is slow and it is bad. The logic has several challenges, but one is that it does look-ups using sequential scans rather than maps, and .. this PR fixes that. Having fixed that, it allows us to remove some fraught helper methods.
Ideally there are no negative implications, though the logic is technically different: the old code would update the replacement options mid-loop, whereas this new code stays stable within an iteration.
> Improve performance of `Equivalences::project`

- src/postgres-util/src/replication.rs
The drop of a replication slot happens concurrently with an ingestion dataflow shutting down, therefore there is the possibility that the slot is still in use. We really don't want to leak the slot and not forcefully terminating the dataflow's connection risks timing out. For this reason we always kill the active backend and drop the slot.
Fixes MaterializeInc/database-issues#8756
> source/pg: kill active reader before dropping the slot

- src/transform/src/analysis/equivalences.rs
This PR attempts to allow `Equivalences` to "saturate" with new equivalence class information. Our current implementation is based on term minimization, which does store equivalences in a compact representation, but is challenged to develop new information in a manner that certainly stabilizes, as the new information may be transiently non-minimal, for long enough that we propose the same information again, ad infinitum.
The proposed approach is to iteratively propose new information, then minimize it iteratively, judging the stability of the overall iteration by stability of `self.remap`. It's a bit of an experiment at the moment, so the certainty around what requirements there might be to ensure convergence are still up in the air. For example, it is possible that we could invent new …
> Prototype equivalence saturation

- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- misc/helm-charts/testing/environmentd.yaml
As discussed, restructuring the Helm chart values a little bit so that they make more sense in particular around the cloud provider-specific configurations.
Open to suggestions!
> helm-chart: reorganize the helm chart values

- src/transform/src/analysis.rs
> transform: some typos and redundant return values

- ci/builder/Dockerfile
- ci/nightly/pipeline.template.yml
- ci/plugins/cloudtest/hooks/command
- ci/plugins/mzcompose/hooks/pre-exit
- ci/plugins/scratch-aws-access/README.md
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
- misc/python/materialize/mzcompose/service.py
- misc/python/materialize/mzcompose/services/testdrive.py
- test/terraform/.gitignore
- test/terraform/aws/main.tf
- test/terraform/aws/simple.tf
- test/terraform/mzcompose
- test/terraform/mzcompose.py
Finally green:
```
==> mzcompose: test case workflow-default succeeded
```
Green run in CI: https://buildkite.com/materialize/nightly/builds/10534
> Terraform + helm-chart e2e test

- ci/deploy/pipeline.template.yml
- ci/mkpipeline.py
- ci/mkpipeline.sh
- ci/nightly/pipeline.template.yml
- ci/qa-canary/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/slt/pipeline.template.yml
- ci/test/pipeline.template.yml
If the build is still failing here: https://buildkite.com/materialize/test/builds/95535#01937744-347f-4b3a-83dc-81809bf51a49
> Temporarily disable bazel (revert me after fix)

- src/durable-cache/src/lib.rs
Previously, when syncing with the persist shard, the durable cache would apply each batch from `ListenEvent::Updates` to a map in memory as it received them. While applying the updates, the durable cache would assert that each retraction had a matching addition and that each addition didn't already exist in the cache.
Subscribe does not guarantee that a single `ListenEvent::Updates` will contain all the updates of a single timestamp or that the updates within a single timestamp will arrive in any particular order. This could cause the durable cache to incorrectly panic thinking there's an invalid update.
For example, consider the following sequence of updates:
1. `ListenEvent::Updates([((k, v), ts, -1)])`
2. `ListenEvent::Updates([((k, v), ts, +1)])`
While processing (1), the durable …
> durable-cache: Fix partial application of times

- doc/user/content/sql/system-catalog/mz_internal.md
> user/doc: Fix typo in mz_index_advice

- src/storage/src/source/kafka.rs
This PR makes the Kafka source's `fetch_partition_info` method use the `offsets_for_times` API instead of `fetch_watermarks`, for topics with more than one partition. The benefit is that the former can fetch offsets for multiple partitions in a single request, whereas the later issues one request per partition. If there are many partitions, `offsets_for_times` should therefore be much more efficient.
> storage/kafka: more efficient fetch_partition_info

- test/balancerd/mzcompose.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/30678
Seen failing in https://buildkite.com/materialize/nightly/builds/10604#01938f14-f9aa-44e7-ad13-16d109e67828
> balancerd test: Fix plaintext tests

- src/adapter/src/coord/message_handler.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/history.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/controller.proto
- src/storage-types/src/controller.rs
- src/storage/src/source/reclock.rs
- src/storage/src/storage_state/async_storage_worker.rs
Statuses are now populated by the controller so that field was dead code
> storage: delete status shard from metadata collection

- doc/user/content/_index.md
- doc/user/content/releases/previews.md
- doc/user/content/sql/create-connection.md
@kay-kim: marking the Preview page as draft since there's some inaccuracies and we're going to revisit our feature lifecycle next week. I can work it back in after that meeting takes place.
> doc/user: promote AWS connections to GA

- test/terraform/aws/simple.tf
- test/terraform/mzcompose.py
Currently blocked by https://materializeinc.slack.com/archives/C07PN7KSB0T/p1732746103751019
Edit: Works now.
> terraform e2e test: Add balancerd

- test/canary-load/mzcompose.py
See https://github.com/MaterializeInc/database-issues/issues/8737
> canary load: Workaround for hanging http connections

- ci/nightly/pipeline.template.yml
- test/sqllogictest/introspection/attribution_sources.slt
- test/terraform/mzcompose.py
- test/testdrive-old-kafka-src-syntax/indexes.td
- test/testdrive/kafka-recreate-topic.td
See individual commits, pretty messy currently
> Nightly fixes (December 7)

- doc/user/content/transform-data/patterns/temporal-filters.md
- Per discussion yesterday, added mention of Materialize maintaining future retractions for temporal filters.
- Tweaked surrounding sentences to shoehorn in the aforementioned sentence.
https://preview.materialize.com/materialize/30761/transform-data/patterns/temporal-filters/
> docs: temporal filters maintain future retractions

- doc/user/content/get-started/_index.md
> doc/user: patch typo

- test/terraform/mzcompose.py
Seen in https://buildkite.com/materialize/nightly/builds/10651#0193a8d4-9fe8-451c-b2dd-33c83d975dd4
> error: unable to forward port because pod is not running. Current status=Pending
Running locally to verify
> terraform test: Fix waiting for balancerd to be up

- doc/user/content/sql/explain-plan.md
- doc/user/data/explain_plan_operators.yml
- doc/user/layouts/partials/explain-plans/operator-table.html
- doc/user/layouts/shortcodes/explain-plans/operator-table.html
https://preview.materialize.com/materialize/30751/sql/explain-plan/#reference-plan-operators
> docs: explain plan operators - memory usage/expansive annotation

- test/sqllogictest/introspection/attribution_sources.slt
Fixes: https://github.com/MaterializeInc/database-issues/issues/8824
> attribution_sources.slt: Bump sleep times

- src/adapter/src/coord/appends.rs
> adapter: Decrease group commit log noisiness

- src/persist-client/src/schema.rs
As part of https://github.com/MaterializeInc/materialize/pull/30205 we check if a new `arrow::DataType` is "at least as nullable" as the previous type, and if so we update the registered data type in-place.
This check failed to account for the change we made a little while ago where were use `arrow::DataType::List` for `ScalarType::Map`, instead of `arrow::DataType::Map`.
Fixes https://github.com/MaterializeInc/database-issues/issues/8834
> persist: fix schema stability migration

- doc/user/config.toml
- doc/user/content/ingest-data/kafka/_index.md
For now, a barebones landing page for kafka.
> docs: add landing page for kafka

- src/catalog/src/durable/persist.rs
The audit log entries take a unique path through the catalog as a
performance optimization. As a result, they were skipping the path
that updates the collection count for each catalog collection. This
commit fixes that issue by manually updating the audit log collection
entries metric.
> catalog: Fix audit log collection metrics

- doc/developer/bazel.md
Very important. Adds the Bazel logo.
[**Preview**](https://github.com/ParkMyCar/materialize/blob/bazel/logo-in-docs/doc/developer/bazel.md)
Fun
> bazel: super important (not really though) docs change

- misc/helm-charts/operator/CONTRIBUTING.md
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
- misc/helm-charts/operator/values.yaml
As discussed adding an ignore for the huge `operator.clusters.sizes` value and also adding the `# --` syntax to all of the comments so the description field gets populated.
> helm-chart: update readme description fields

- src/compute-client/src/controller/instance.rs
This PR makes the compute controller exclude transient collections (one-off select indexes and subscribe) from the wallclock lag introspection. Reporting their lags is generally less useful than reporting the lags of catalog objects. On the other hand, in an unhealthy system large numbers of one-off select collections can accumulate, blowing up the size of `mz_wallclock_lag_history` and thereby the size of the system indexes based off it. Excluding transient collections thus makes the resource usage more predictable.
If a cluster is unhealthy and doesn't respond to SELECT queries, the controller may accumulate a large amount of collections for these SELECT queries. Writing theirs lag values to wallclock lag introspection provides an opportunity …
> compute: don't report wallclock lag for transient collections

- doc/user/layouts/partials/head.html
- doc/user/layouts/partials/sidebar.html
https://preview.materialize.com/materialize/30862
> docs: left hand kapa Search by default, ctrl+k also search by default

- src/cloud-api/src/client/region.rs
we're changing the cloud api for environment deletion, so this brings the mz binary into sync with that
going to wait for the cloud pr to merge first, but i'm not super concerned with migration or backwards compatibility because this endpoint is only usable by materialize employees
> update mz binary for new region deletion api

- src/storage/src/source/kafka.rs
This PR refactors the Kafka source from a single source operator into two operators, a reader and a metadata fetcher. Splitting out the metadata fetcher allows having only a single thread running metadata requests against Kafka, instead of one per worker, reducing networking overhead and load on the upstream system. This is particularly important with the RLU reclocking scheme, where we make one metadata request per second, instead of one every 30s as with the current RIU scheme.
Part of https://github.com/MaterializeInc/database-issues/issues/7020
I suggest looking at the commits separately. The first commit is mostly code movement, to ensure the diff for the second one remains manageable. The second commit has the actual functional changes. …
> kafka-source: split out metadata fetcher

- doc/user/content/integrations/_index.md
> docs: mark mysql as ga

- doc/user/content/sql/explain-timestamp.md
Reported on [Slack](https://materializeinc.slack.com/archives/C05EF5QV93M/p1734184138074609).
> doc/user: patch `EXPLAIN TIMESTAMP` example

- misc/python/materialize/mzcompose/composition.py
> misc: fix environment variable typo

- src/compute/src/sink/copy_to_s3_oneshot.rs
The `ResponseProtocol` is not shared state anymore, so no reason to wrap it into an `Rc<RefCell>`.
This simplification became possible thanks to https://github.com/MaterializeInc/materialize/pull/30844 and https://github.com/MaterializeInc/materialize/pull/30909.
> compute: minor copy-to sink cleanup

- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/error
- test/sqllogictest/errors.slt
- test/testdrive/temporary.td
> parser: improve error message for `CREATE` statements

- Cargo.lock
- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
> update postgres dependency

- src/catalog/src/durable/persist.rs
Previously, we were resetting all catalog collection entries after setting the initial audit log count. So the metrics would only display audit log entries created after the last restart.
This commit fixes the issue by resetting all catalog collection entries before setting the initial audit log count.
> catalog: Fix audit log metrics tracking

- doc/user/assets/sass/_layout.scss
Addresses https://materializeinc.slack.com/archives/CU7ELJ6E9/p1736449308954709: 
https://github.com/user-attachments/assets/00180fe7-91b5-43bf-b581-a35a56ac70c3
> fix the scroll.

- doc/user/content/sql/explain-plan.md
> docs: tweak explain plan

- src/storage/src/storage_state/async_storage_worker.rs
Previously, async storage workers would calculate the as_of of a dataflow from the since of the dataflow's output's remap shards. If there was more than one distinct remap shard among the outputs, then the storage worker would panic. It's expected that the only collection that will ever have a remap shard is the ingestion collection itself.
Furthermore, we are planning to remove the ingestion collection from the outputs of the dataflow (in fact there's already a feature flag that does this). If the ingestion is removed from the outputs, then no output will have a remap shard, and the as_of will always be empty.
This commit simplifies the existing as_of calculation and fixes the as_of calculation when the ingestion collection is removed from the outputs. It does this by calculating the …
> storage: Simplify dataflow as_of computation

- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- test/bounded-memory/mzcompose.py
- test/testdrive-old-kafka-src-syntax/primary-key-optimizations.td
- test/testdrive-old-kafka-src-syntax/source-linear-operators.td
Follow-up to https://github.com/MaterializeInc/materialize/pull/30983
Noticed in https://buildkite.com/materialize/nightly/builds/10865#01946761-a0cc-43a1-9b38-dd0abc0c6526
Test run: https://buildkite.com/materialize/nightly/builds/10868
> testdrive: Fix some plans

- doc/user/content/installation/install-on-local-kind.md
- doc/user/content/installation/install-on-local-minikube.md
Corresponds to the docs changes related to https://github.com/MaterializeInc/materialize/pull/31056
> docs: change environmentd.yaml to materialize.yaml

- src/sql/src/plan/transform_expr.rs
This commit fixes a lint by removing an impl block from inside a function. It is only code movement.
> plan: Fix lint associated with nested impl

- src/ore/src/url.rs
these may be being passed in via environment variables coming in through kubernetes secrets, so it's not necessarily the case that someone with access to the command output should also have access to the secret values
> don't display sensitive urls during argument parsing

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Cutting a new release to ship the latest bugfix.
> dbt-materialize: release v1.9.1

- doc/user/assets/sass/_base.scss
> fix the select. (#31090)

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Cutting a new release to ship the latest bugfix.
> dbt-materialize: release v1.9.2

- doc/user/content/installation/install-on-aws.md
In prep for https://github.com/MaterializeInc/terraform-aws-materialize/pull/15
> docs: update self-managed install-on-aws to use terraform for everything

- src/storage-operators/src/oneshot_source.rs
Currently when ingesting a large CSV file on a small cluster we OOM. I realized this is because a previous refactor I did caused us to buffer all of the receiving rows from a CSV file into a single Vec before giving them to the downstream timely operator that will stage them in Persist.
Fix bug that caused OOMs in `COPY FROM S3`
> [copy_from] Fix bug that preventing streaming data into Persist

- src/catalog/src/expr_cache.rs
> adapter: Improve expr cache error log

- misc/python/materialize/version_ancestor_overrides.py
Tracked in https://github.com/MaterializeInc/database-issues/issues/8916
> feature-benchmark: Ignore SwapSchema regression

- doc/user/content/releases/v0.130.md
- doc/user/content/releases/v0.131.md
These fix an issue with memory usage: see #31207.
> doc/user: bump to latest emulator patch releases

- src/orchestrator-kubernetes/src/lib.rs
This PR fixes a bug in `ScaledQuantity::try_to_integer`, which would previously ignore the `base` value and always use base 2 for positive exponents.
Fixes https://github.com/MaterializeInc/database-issues/issues/8912
> k8s: fix quantity parsing

- src/sql/src/session/vars/definitions.rs
> rbac: Update TODO comment

- .github/CODEOWNERS
Given that my last day will be 1/31.
> CODEOWNERS: remove self from ownership

- test/replica-isolation/mzcompose.py
Noticed in https://materializeinc.slack.com/archives/C08ACQNGSQK/p1738168087934519 that this is currently hard to parse when you have dozens of IDs and only a few are missing.
> replica-isolation test: Only print missing IDs

- doc/user/content/installation/install-on-local-kind.md
- doc/user/content/installation/install-on-local-minikube.md
- doc/user/content/release-notes.md
- doc/user/layouts/shortcodes/self-managed/self-managed-details.html
> Bump version to v25.1.1

- src/adapter/src/coord/sequencer/inner/cluster.rs
- test/cluster/mzcompose.py
`sequence_alter_cluster_stage` had a couple paths where the supplied workload class was not applied to the controller. As a result, metrics for production clusters sometimes didn't get their `workload_class` label applied correctly. This is fixed in this commit by making sure the workload class is always updated in the controller, even when a cluster finalization is needed.
Looks like this got broken a while ago in https://github.com/MaterializeInc/materialize/pull/27904.
Fixes https://github.com/MaterializeInc/database-issues/issues/8941
> adapter: always apply workload class on ALTER CLUSTER

- doc/user/content/administration/billing.md
https://preview.materialize.com/materialize/31184/self-managed/v25.1/administration/billing/
> placeholder for usage and pricing

- test/lang/js/yarn.lock
Fixes: https://github.com/MaterializeInc/materialize/security/dependabot/103
> build(deps): bump js test dependencies

- test/lang/csharp/csharp-npgsql6.csproj
Fixes https://github.com/MaterializeInc/materialize/security/dependabot/82
> build(deps): bump npgsql in test/lang/csharp

- doc/user/content/sql/create-source/mysql.md
- doc/user/data/sql_funcs.yml
Minor documentation change to support #31097.
> doc/user: add `bit` to list of supported types

- misc/helm-charts/testing/README.md
In the local test instructions, updating the steps for the metrics-server to simplify installation and configuration by using Helm instead of manual kubectl apply and deployment edits.
> helm-chart: Replace metrics-server kubectl install with Helm

- src/cluster/src/server.rs
This PR changes `ClusterClient::build` to first send new channels to all workers and then wait to get their activators back, instead of doing these things in lockstep. This ensures all workers always receive their channels, even if one of them is stuck (e.g. waiting for other workers to make progress). In particular, this avoids the stall described in https://github.com/MaterializeInc/database-issues/issues/8957.
Fixes part of https://github.com/MaterializeInc/database-issues/issues/8957
> cluster: avoid workers becoming stalled after reconnect

- src/storage/src/source/postgres/replication.rs
This PR moves the postgres source's periodic schema validation onto a separate task and gives it a separate upstream client. The intention is to avoid that (potentially slow) fetching of schema information stalls the progress of the replication reader, leading to responsiveness regressions for consumers of the source.
Fixes https://github.com/MaterializeInc/database-issues/issues/8945
I recommend reviewing with whitespace disabled!
> source/postgres: move schema validation onto a separate task

- test/sqllogictest/freshmart.slt
The Freshmart demo involves some complex queries. We should add them to our tests, to make sure we compile them well!
Copied from <https://github.com/nstewart/freshmart-evolution>.
> [testing] add `EXPLAIN` of freshmart queries

- src/environmentd/BUILD.bazel
Follow-up to https://github.com/MaterializeInc/materialize/pull/31460
> lints: Fix check-bazel lint

- src/compute/src/compute_state.rs
- src/compute/src/metrics.rs
- test/cluster/mzcompose.py
This commit adds a replica metric, `mz_compute_collection_count`, that tracks how many compute collections are installed on each replica, split up by type and hydration status. The metric enables tracking hydration progress during 0dt deployments as the percentage of hydrated collections can be derived from it.
[Slack thread.](https://materializeinc.slack.com/archives/C08ACQNGSQK/p1738774881494979)
Part of https://github.com/MaterializeInc/database-issues/issues/8948
> compute: add mz_compute_collection_count metric

- test/sqllogictest/freshmart.slt
Per conversation with @sjwiesman, the indexes were not in the right place in the SLT file---and so the `EXPLAIN` output was not correct (and didn't look great). This PR should resolve that.
> [testing] fix index placement in freshmart queries

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
https://github.com/MaterializeInc/cloud/issues/10804
not tested yet, i'll test tomorrow
> expose balancerd and console node selectors in helm

- doc/user/content/installation/install-on-aws.md
- doc/user/content/installation/install-on-azure.md
- doc/user/content/installation/install-on-gcp.md
- doc/user/content/installation/install-on-local-kind.md
- doc/user/content/installation/install-on-local-minikube.md
- doc/user/content/installation/troubleshooting.md
- doc/user/layouts/shortcodes/self-managed/troubleshoot-console-mz_catalog_server_blurb.md
Given we're changing the default catalog server size to 25cc https://github.com/MaterializeInc/materialize/pull/31539, I thought it'd be a good idea to add documentation on how a user can actually increase the size of `mz_catalog_server`. 
There are some things that are kind of unresolved:
- Hashtags aren't working properly in the dev build, e.g.`/self-hosted/troubleshooting/#troubleshooting-console-unresponsiveness`. I'm assuming it has something to do with the aliases but wondering if this is a bug or if I'm doing something wrong @kay-kim 
- It feels kind of sketchy telling users to use the internal sql port. I also don't know how this plays out with TLS and auth... I'd wanna get @alex-hunt-materialize's opinions on this 
@kay-kim Feel free to move things around / change the wording of …
> Add console troubleshooting section

- src/catalog/src/durable/persist.rs
> adapter: clarify naming in catalog version check, add commentary

- src/storage/src/storage_state/async_storage_worker.rs
Fixes https://github.com/MaterializeInc/database-issues/issues/8898
> storage: pick largest possible `as_of` frontiers for ingestions

- LICENSE
Our license currently prohibits the use of multiple clusters, which prevents folks from using Materialize in our recommended configurations, and to experience some of the cool features. Change the license to instead constraint the total resources consumed by Materialize across any number of clusters.
> Update `LICENSE` to allow cluster use

- src/storage/src/render/sources.rs
- src/storage/src/source/reclock/compat.rs
- src/storage/src/source/source_reader_pipeline.rs
Before, we were panic'ing in some places: rendering remap operator and rendering the persist_source for UPSERT, while for exports/sinks we used suspend-and-restart.
Now, we also use suspend-and-restarts in those two other places.
> storage: use suspend-and-restart to recover from errors

- misc/helm-charts/operator/templates/deployment.yaml
- misc/images/materialized-base/Dockerfile
- misc/images/materialized-base/console_nginx.template
Tested on local kind and it works!
Preparation for self managed
> Bump console image tag to 25.2.0

- doc/user/content/installation/install-on-gcp.md
corresponds to https://github.com/MaterializeInc/terraform-google-materialize/pull/18 changes
> docs: google install use prefix, rm password

- doc/user/content/installation/install-on-aws.md
Per https://github.com/MaterializeInc/terraform-aws-materialize/pull/34
> docs: remove database_password from tfvars file

- src/metrics/src/lib.rs
Follow-ups from reviews. Add documentation, make code structure clearer. No
behavior changes expected.
> Minor improvements for mz-metrics

- src/compute-client/src/controller/instance.rs
- src/compute-client/src/metrics.rs
- test/cluster/mzcompose.py
The metric was quite buggy, reporting useless times after a successful compute reconciliation. It has been superseded by two (hopefully less buggy) metrics:
* a promsql-exporter metric based on `mz_compute_hydration_times` that reports the hydration time for each collection in the read/write environment
* a clusterd-exported metric, `mz_compute_collection_count`, that reports the number of hydrated collections in all environments (including read-only ones)
Closes https://github.com/MaterializeInc/database-issues/issues/8948
> compute: rip out the mz_dataflow_initial_output_duration_seconds metric

- doc/user/content/manage/dbt/development-workflows.md
Adding a small note to mention the required permissions when using RBAC.
> doc: add rbac note in dbt blue/green guide

- doc/user/content/serve-results/looker.md
Updating the Looker guide to include the possible known limitation around symmetric aggregates
> doc: update Looker known limitations

- Cargo.lock
- src/kafka-util/Cargo.toml
- src/kafka-util/src/admin.rs
This reverts commit b9917cda27d9d3cc39dda880005d0c8f1f21f2ad.
`#incident-437`
> Revert "Attempt to fetch existing topics' configuration in ensure_topic"

- doc/user/content/sql/system-catalog/mz_internal.md
- misc/python/materialize/checks/all_checks/source_errors.py
- src/adapter/src/catalog.rs
- src/catalog/src/builtin.rs
- src/storage-client/src/client.proto
- src/storage-client/src/client.rs
- src/storage-client/src/healthcheck.rs
- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/instance.rs
- src/storage-controller/src/lib.rs
- src/storage/src/healthcheck.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/consistency.rs
- test/sqllogictest/autogenerated/mz_internal.slt
- test/sqllogictest/distinct_arrangements.slt
- test/sqllogictest/explain/optimized_plan_as_text.slt
- test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
- test/sqllogictest/mz_catalog_server_index_accounting.slt
- test/sqllogictest/system-cluster.slt
- test/testdrive-old-kafka-src-syntax/mzcompose.py
- test/testdrive-old-kafka-src-syntax/status-history.td
- test/testdrive/kafka-recreate-topic.td
- test/testdrive/status-history.td
Implements MaterializeInc/database-issues#8974
> storage: add replica_id to mz_source_status_history

- src/storage-controller/src/history.rs
This fixes another fix, which was correct but too conservative. The storage protocol isn't flattened (at least until we land #31261), so we don't just have to count the commands after compaction, but the semantic commands. For example, `AllowCompaction` can contain main commands, and we need to count them as such. Otherwise, we'll compact too frequently, showing in CPU profiles when we host many storage objects.
> Properly compute storage reduced count

- doc/user/content/installation/install-on-aws/_index.md
- doc/user/content/installation/install-on-aws/upgrade-on-aws.md
- doc/user/content/installation/install-on-azure/_index.md
- doc/user/content/installation/install-on-azure/upgrade-on-azure.md
- doc/user/content/installation/install-on-gcp/_index.md
- doc/user/content/installation/install-on-gcp/upgrade-on-gcp.md
- doc/user/layouts/shortcodes/self-managed/terraform-disclaimer.html
- doc/user/layouts/shortcodes/self-managed/tutorial-disclaimer.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-aws-terraform-repo.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-azure-terraform-repo.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-google-terraform-repo.html
- Updated disclaimer that they should fork the Terraform repo.
- Make forking the repo a step in the tutorial.
> docs: Fork the terraform repo

- src/persist-client/src/internal/machine.rs
This PR is fixing a subtle performance problem that arises from short-lived instances of the `FuturesUnordered` type. The high CPU load was observed by @antiguru when instatiating a very large number of sources.
When a future registered with a `FuturesUnordered` instance is woken it enters a ready queue. Then, when the `FuturesUnordered::poll_next` method is called each future from the ready queue is popped and polled. Ideally one of the futures resolves and `poll_next` returns with `Poll::Ready(_)`. If no future is ready the entire `FuturesUnordered` returns `Poll::Pending`.
One thing that can happen, especially if many futures are registered, is that while polling a future in the ready queue another previously polled future gets woken, re-entering the ready queue. When a large number of …
> persist-client: avoid short-lived `FuturesUnordered`

- src/storage-controller/src/instance.rs
- src/storage-controller/src/lib.rs
Before, we were tracking active replicas in the main storage controller.
Now that Instance is tracking which replica is active, and now that it is actually more correct for single-replica ingestions, we us it as the source of truth when dropping an object.
> storage: rely on active_replica tracking in Instance

- src/adapter/src/coord/sequencer/inner/cluster.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
- test/cloudtest/test_managed_cluster.py
- test/cluster/mzcompose.py
Implements MaterializeInc/database-issues#8983
> storage: include storage collections in hydration check for ALTER CLUSTER

- src/cluster/src/communication.rs
- src/orchestrator-process/src/lib.rs
- src/persist-client/src/internal/machine.rs
This PR is removing another instance of short-lived `FuturesUnordered` an also refactors some instances of `FuturesUnordered` that were leading to boxed futures into non-boxed ones, encoding more information in the types.
> tidying up some more instances of `FuturesUnordered`

- test/terraform/azure-temporary/main.tf
- test/terraform/azure-temporary/simple.tf
Bumping the Azure terraform module version to the latest one.
> self-hosted: Azure Terraform module v0.2.0 bump

- src/testdrive/src/action/sql.rs
Prints the latency of the last command in testdrive.
> Testdrive: print command latency

- doc/user/content/installation/install-on-aws/_index.md
- doc/user/content/installation/install-on-aws/upgrade-on-aws.md
- doc/user/content/release-notes/_index.md
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-aws-terraform-repo.html
companion to https://github.com/MaterializeInc/terraform-aws-materialize/commit/788ec31c012c9bf4b5c6faff9d9caa79d19b32b2
- Converted to draft so as not to merge until we release the Terraform.
- Once we have the other cloud providers, can add a blurb to the various ingest pages to mention the load balancers.
> docs: AWS terraform v0.3.0 ingress/nlbs

- misc/python/materialize/feature_flag_consistency/input_data/feature_flag_configurations.py
- src/compute-types/src/plan.rs
- src/expr/src/linear.rs
- src/repr/src/optimize.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/session/vars/definitions.rs
> Remove feature flags for #31806

- test/terraform/gcp-temporary/main.tf
Bumping the GCP terraform module version to the latest one.
> self-hosted: GCP Terraform module v0.2.0 bump

- doc/user/content/installation/install-on-azure/_index.md
- doc/user/content/installation/install-on-azure/appendix-azure-provider-configuration.md
- doc/user/content/installation/install-on-azure/upgrade-on-azure.md
- doc/user/layouts/shortcodes/self-managed/azure-terraform-configs.html
- doc/user/layouts/shortcodes/self-managed/azure-terraform-upgrade-notes.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-azure-terraform-repo.html
https://github.com/MaterializeInc/terraform-azurerm-materialize/pull/21
> docs: Azure terraform v0.2.0 network_config is required

- doc/user/content/installation/install-on-aws/_index.md
- doc/user/content/installation/install-on-aws/appendix-aws-provider-configuration.md
- doc/user/content/installation/install-on-aws/upgrade-on-aws.md
- doc/user/content/installation/operational-guidelines.md
- doc/user/content/release-notes/_index.md
- doc/user/layouts/shortcodes/self-managed/aws-recommended-instances.html
- doc/user/layouts/shortcodes/self-managed/aws-terraform-upgrade-notes.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-aws-terraform-repo.html
Prep for next materialize on aws terraform release
> docs: self-managed aws terraform release prep branch

- ci/nightly/pipeline.template.yml
- test/terraform/azure-temporary/main.tf
- test/terraform/mzcompose.py
Test run: https://buildkite.com/materialize/nightly/builds/11610#0195cf69-783d-42a2-8c2f-88a06176a69b
> terraform test: Retry terraform apply on Azure and rename

- doc/user/content/sql/create-connection.md
The syntax was wrong, this pr corrects it.
> fix bad create secret syntax in create aws connection

- src/self-managed-debug/src/docker_resource_dumper.rs
- src/self-managed-debug/src/main.rs
* PR #31859:
`main` ← `jun/#8908/dump-catalog-2`
* PR #31976:
`jun/#8908/dump-catalog-2` ← `jun/#8908/dump-catalog-4`
* **PR #32007 (THIS ONE)**:
`jun/#8908/dump-catalog-4` ← `jun/#8908/emulator-support`
This is just to get the base of emulator support going. Things TODO are:
- Allowing catalog scraping via a connection URL
- Modifying the UI to separate self-managed from the emulator
You can see the full list in the linked ticket!
See commit messages for details
MaterializeInc/database-issues#8908
considered. ([trigger-ci for additional test/nightly
runs](https://trigger-ci.dev.materialize.com/))
doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md),
is a design doc …
> Dump docker debug info for emulator

- doc/user/content/manage/access-control/_index.md
One more follow up to https://github.com/MaterializeInc/materialize/pull/32029
> docs: remove straggler private preview on network policies

- doc/user/content/sql/show-network-policies.md
remove preview notice on one more network policy item now that it's GA
> remove preview on SHOW NETWORK POLICIES

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Preparing this release to ship @josharenberg's fix from https://github.com/MaterializeInc/materialize/pull/32086
> dbt-materialize: release `v1.9.4`

- misc/python/materialize/mzcompose/composition.py
> tests: Remove debug blob store output

- src/storage/src/upsert/types.rs
> storage: fix typo in Debug impl

- src/compute/src/row_spine.rs
Extract a container from `DatumContainer` that can be safely used for arbitrary byte slices, rather than only for `Row`-encoded byte slices.
> Extract `BytesContainer` from `DatumContainer`

- doc/user/content/installation/install-on-aws/_index.md
- doc/user/data/self_managed/aws_terraform_versions.yml
- doc/user/data/self_managed/azure_terraform_versions.yml
- doc/user/data/self_managed/gcp_terraform_versions.yml
- doc/user/data/self_managed/materialize_operator_chart_parameter.yml
- doc/user/data/self_managed/self_managed_operator_compatibility.yml
- doc/user/layouts/shortcodes/self-managed/versions/curl-sample-files-local-install.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-aws-terraform-repo.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-azure-terraform-repo.html
- doc/user/layouts/shortcodes/self-managed/versions/step-clone-google-terraform-repo.html
- doc/user/layouts/shortcodes/self-managed/versions/step-install-helm-version-local-kind-install.html
- doc/user/layouts/shortcodes/self-managed/versions/step-install-helm-version-local-minikube-install.html
- doc/user/layouts/shortcodes/self-managed/versions/upgrade/upgrade-steps-cloud.html
- doc/user/layouts/shortcodes/self-managed/versions/upgrade/upgrade-steps-local-kind.html
- doc/user/layouts/shortcodes/self-managed/versions/upgrade/upgrade-steps-local-minikube.html
- orchestratord from 130.4 to 138.0
- helm from 25.1.2 to 25.1.5
- envd from 0.130.4 to 0.130.7
> Bump self managed version in docs

- test/terraform/aws-temporary/main.tf
- test/terraform/azure-temporary/main.tf
- test/terraform/gcp-temporary/main.tf
- test/terraform/mzcompose.py
Bumping the Terraform modules versions for all cloud providers to the latest ones. With the latest versions, we have:
- TLS enabled by default for all
- NLB support enabled by default for all
- lgalloc support for AWS enabled by default
> Self hosted bump terraform module versions

- doc/user/content/sql/create-connection.md
We took IAM auth for RDS MySQL straight to GA, we can promote the auth for MSK
> remove preview from MSK IAM auth

- ci/mkpipeline.py
Getting 403 errors with long selection strings, Buildkite has kindly disabled the check until the end of the month but then trigger-ci without an auth token will break again. See https://materializeinc.slack.com/archives/C01LKF361MZ/p1743080295750679?thread_ts=1743080063.984339&cid=C01LKF361MZ
> ci: Shorter test selection for trigger-ci

- ci/nightly/pipeline.template.yml
- ci/plugins/mzcompose/hooks/pre-exit
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- misc/python/materialize/git.py
- test/terraform/aws-upgrade/main.tf
- test/terraform/aws-upgrade/simple.tf
- test/terraform/mzcompose.py
Green run: https://buildkite.com/materialize/nightly/builds/11698
> Terraform upgrade test

- ci/deploy_mz-debug/pipeline.template.yml
- ci/deploy_mz_lsp_server/pipeline.template.yml
> ci: Improve pipelines for deploy steps

- ci/mkpipeline.py
- misc/python/materialize/mzbuild.py
Noticed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1744627370990529
Also made the check run in parallel since it's pretty slow to run sequentially.
> ci: Make cargo-test depend on builds when necessary

- src/compute/src/row_spine.rs
> Maintain `BytesContainer` length rather than recompute

- doc/user/content/sql/create-source/webhook.md
- doc/user/sql-grammar/sql-grammar.bnf
- Make `IN CLUSTER` optional and replace rr-diagram with copyable syntax form.
> docs: create-source-webhook: update syntax

- src/adapter/src/catalog/open.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/src/durable/upgrade/v73_to_v74.rs
I missed this in the previous PR
Fixes: https://github.com/MaterializeInc/database-issues/issues/9179
> Properly migrate roles from v73 to 74

- src/transform/src/join_implementation.rs
As it says on the tin.
Note that this is on top of https://github.com/MaterializeInc/materialize/pull/32205, so only the last commit is for this PR.
> Eliminate a deprecated `visit_mut_pre_post` call

- Cargo.lock
- src/cloud-resources/Cargo.toml
- src/environmentd/Cargo.toml
- src/http-util/Cargo.toml
- src/mz-debug/Cargo.toml
- src/orchestrator-kubernetes/Cargo.toml
- src/orchestratord/Cargo.toml
- src/orchestratord/src/controller/materialize/environmentd.rs
- src/sqllogictest/Cargo.toml
- src/workspace-hack/Cargo.toml
> upgrade the kubernetes crates

- doc/user/content/integrations/_index.md
- doc/user/content/integrations/mz-debug/_index.md
- doc/user/content/integrations/mz-debug/emulator.md
- doc/user/content/integrations/mz-debug/self-managed.md
- doc/user/data/mz-debug/docker_resource_files.yml
- doc/user/data/mz-debug/emulator_options.yml
- doc/user/data/mz-debug/kubernetes_resource_files.yml
- doc/user/data/mz-debug/mz_debug_option.yml
- doc/user/data/mz-debug/self_managed_options.yml
- doc/user/layouts/shortcodes/integrations/mz-debug/system-catalog-files.md
> cherry-pick mz-debug docs

- doc/user/content/sql/begin.md
- doc/user/content/sql/commit.md
- doc/user/content/sql/rollback.md
- doc/user/layouts/shortcodes/txns/txn-details.html
- doc/user/layouts/shortcodes/txns/txn-insert-only.html
- doc/user/sql-grammar/sql-grammar.bnf
https://preview.materialize.com/materialize/32321/sql/begin/
https://preview.materialize.com/materialize/32321/sql/commit/
https://preview.materialize.com/materialize/32321/sql/rollback/
> docs: update begin/commit/rollback sql ref pages

- src/storage/src/upsert.rs
- src/storage/src/upsert/types.rs
- src/storage/src/upsert_continual_feedback.rs
> storage: add some extra logging

- doc/user/content/manage/dbt/_index.md
- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/impl.py
- misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
- misc/dbt-materialize/tests/adapter/fixtures.py
- misc/dbt-materialize/tests/adapter/test_custom_materializations.py
Fixes https://github.com/MaterializeInc/database-issues/issues/9238
> dbt-materialize: add support retain_history config for materialized_view

- ci/deploy_website/website.sh
This has been broken for a bit
cc @emilyblackMZ
> update Slack referral link

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Preparing this release to ship the new support  for `retain_history` config for materialized views https://github.com/MaterializeInc/materialize/pull/32376
> dbt-materialize: release `v1.9.5`

- doc/user/data/self_managed/latest_versions.yml
> docs: Bump latest versions

- Cargo.lock
- deny.toml
- src/balancerd/Cargo.toml
- src/clusterd/Cargo.toml
- src/environmentd/Cargo.toml
- src/environmentd/src/http.rs
- src/environmentd/src/http/sql.rs
- src/environmentd/tests/server.rs
- src/environmentd/tests/sql.rs
- src/frontegg-auth/Cargo.toml
- src/frontegg-auth/src/client/tokens.rs
- src/frontegg-mock/Cargo.toml
- src/frontegg-mock/src/server.rs
- src/http-util/Cargo.toml
- src/metabase/src/lib.rs
- src/mz/Cargo.toml
- src/orchestratord/Cargo.toml
- src/persist-cli/Cargo.toml
- src/prof-http/Cargo.toml
- src/prof-http/src/lib.rs
- src/storage/Cargo.toml
- src/workspace-hack/Cargo.toml
Causes problems for cloud: https://materializeinc.slack.com/archives/CL68GT3AT/p1746558678350149
> build(deps): Downgrade axum-extra and axum

- doc/user/content/_index.md
- doc/user/content/integrations/_index.md
- doc/user/content/integrations/llm.md
Preview: https://preview.materialize.com/materialize/32426/integrations/llm/
> Document Materialize MCP Server

- src/persist-client/src/schema.rs
Projection pushdown can generate data that has no explicit schema, but we can still migrate it fine. Only generate the warning for data that had an older schema id to fall back to...
Spotted these scary-but-fine logs in a recent investigation.
> [persist] only log on the actual fallback path

- src/sql/src/plan/hir.rs
Minor fixes addressing @antiguru 's comments on https://github.com/MaterializeInc/materialize/pull/32443#pullrequestreview-2827731238
> Cosmetic fixes in `OFFSET` handling

- test/terraform/aws-persistent/main.tf
- test/terraform/aws-temporary/main.tf
- test/terraform/aws-upgrade/main.tf
- test/terraform/azure-temporary/main.tf
- test/terraform/gcp-temporary/main.tf
> terraform tests: Bump to latest terraform versions

- misc/helm-charts/publish.sh
> helm-chart release: Add $CI_DRY_RUN

- ci/builder/requirements.txt
- ci/nightly/pipeline.template.yml
- test/testdrive/introspection-sources.td
Seen in https://buildkite.com/materialize/nightly/builds/12003
> ci: Nightly fixes (2025-05-13)

- doc/user/content/concepts/sinks.md
- doc/user/content/ingest-data/_index.md
- doc/user/content/manage/operational-guidelines.md
Small tweaks per slack convos.
> docs: tweak sinks and hydration

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/all_checks/pg_cdc.py
- misc/python/materialize/checks/all_checks/sink.py
- test/cloud-canary/mzcompose.py
> Nightly fixes (2025-05-19)

- test/canary-load/mzcompose.py
Seen in recent QA canary load runs: https://buildkite.com/materialize/qa-canary/builds?branch=main
> QA canary load: Handle further temporary errors

- src/ore/src/panic.rs
On the current `main`, if there are nested calls to `catch_unwind`, it stops working when we return from an inner call of `catch_unwind`, in the sense that the outer `catch_unwind` is not catching any more panics. This is because `CATCHING_UNWIND` is set to false when the nested call returns, and then the panic handler no longer knows that we are still inside the outer `catch_unwind`. This PR fixes this by making `CATCHING_UNWIND` a counter, keeping track of how many nesting levels are we in.
This bug made us not catch the panic of https://github.com/MaterializeInc/database-issues/issues/9285, because https://github.com/MaterializeInc/materialize/pull/32209/commits/07e92888c2cc477e3deefe6b290fb988d50bdaa6 introduced a nested `catch_unwind` call, because `normalize_lets` is called when we …
> ore: Fix nested `catch_unwind`

- ci/deploy_mz-debug/README.md
We were getting some errors due to stale references of git tags. This updates documentation to prevent this in the future
> docs: Update README.md with versioning guidelines for git tags

- src/repr/src/relation.rs
Improve the implementation of ColumnType::union to avoid cloning if not needed. Also, make the code more readable by destructing tuples into their components. No functionality changes expected otherwise.
> Improve ColumnType::union

- src/metrics/src/lgalloc.rs
At the moment, clippy complains on mac that the lgalloc metrics collection task has unused variables. To avoid this, we scope the metrics collection more narrowly.
> Fix clippy on Mac

- doc/user/content/manage/access-control/_index.md
- doc/user/content/manage/access-control/invite-users.md
- doc/user/content/manage/access-control/manage-privileges.md
- doc/user/content/manage/access-control/manage-roles.md
- doc/user/content/manage/access-control/rbac-terraform-tutorial.md
- doc/user/content/manage/access-control/rbac-tutorial.md
- doc/user/content/manage/access-control/rbac.md
- doc/user/content/manage/dbt/_index.md
- doc/user/content/manage/monitor/datadog.md
- doc/user/content/manage/monitor/grafana.md
- doc/user/content/manage/terraform.md
- doc/user/content/sql/system-catalog/mz_internal.md
Partial revert of commit d1934d56cb100d8e2288f7c11cff7e0edfc20a81.
> Revert "docs: self-managed access control (#31153)"

- doc/user/content/concepts/_index.md
- doc/user/content/concepts/reaction-time.md
- doc/user/content/sql/create-index.md
- doc/user/content/sql/create-materialized-view.md
The primary change is adding a dedicated cocnept page describing freshness, query latency, and reaction time. Which is a fundamental concept of Materialize. We then tie references to freshness in the index and mat view pages explaining that these are mechansims to provide access to fresh transformed data. We also add some more explicit language around materialized view refresh strategies that it is a mechanism to purposefully degrade freshness.
> Document Freshness

- src/persist-client/src/internal/apply.rs
- src/persist-client/src/read.rs
We currently panic in a case that's known to be possible when a lease expires. (A batch where the since is past the current since frontier of a listen - should be prevented when a lease is active, but can happen when that lease expires.)
We now check whether the lease has expired, and if so, trigger a less noisy restart. Ideally, we'd percolate the error up so that we could do something like restart a dataflow when that's possible... but we've got a lot of callers here, and the particular case that we're running into on the txns shard would need to halt anyways.
https://github.com/MaterializeInc/database-issues/issues/9286
> [persist] halt! when a lease expires in an acceptable way

- src/compute/src/render.rs
- test/sqllogictest/introspection/attribution_sources.slt
`mz_lir_mapping` didn't properly render `Let`/`LetRec`. This PR fixes the rendering.
@kay-kim do you think it's worth updating docs for this?
https://github.com/MaterializeInc/database-issues/issues/8993
Look at the big added LDBC WMR query to see the output.
> [EXPLAIN] properly render Let and LetRec in `mz_lir_mapping`

- test/limits/mzcompose.py
Seen in https://buildkite.com/materialize/release-qualification/builds/880#01978b53-097e-476f-8c79-dfd920533529
> limits test: Redact password (auto-generated one so nothing leaked)

- src/sqllogictest/src/runner.rs
The following fails on the current `main`:
```
bin/sqllogictest -- -v test/sqllogictest/github-3963.slt test/sqllogictest/github-4336.slt test/sqllogictest/github-5126.slt
```
This seems to be because https://github.com/MaterializeInc/materialize/pull/32203 removed some code that used to reset the replicas of the quickstart cluster if an slt (such as `github-3963.slt`) drops it. This PR puts back the code that was removed from `reset_database`. I'm not sure why the code was removed, so it's possible that this PR does something incorrect.
I'll open a slack thread about some additional problem around whether `RunConfig.replicas` means replication factor or replica size, which we should fix in a later PR. Edit: https://materializeinc.slack.com/archives/C01LKF361MZ/p1750514085398339
* This PR …
> test: reset replicas after slts

- src/orchestrator-kubernetes/src/cloud_resource_controller.rs
This PR makes the cloud resource controller retry k8s API requests, to handle transient errors gracefully. In contrast to the `OrchestratorWorker` it doesn't retry forever but only for a limited amount of times (10 minutes currently).
Fixes https://github.com/MaterializeInc/database-issues/issues/9253
I chose the 10 minute timeout out of fear that we'll start hanging somewhere indefinitely and that this might be worse than crashing envd (or whatever else happens when the cloud resource controller returns an error). The fear might be unfounded and maybe we should retry forever, lmk your thoughts!
> k8s: retry API requests in the cloud resource controller

- src/persist-client/src/cfg.rs
Adds 147 as new self-managed version
> add new sm version to persist-client cfg.rs

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/state.proto
- src/persist-client/src/internal/state.rs
- src/persist-client/src/internal/state_serde.json
Towards: https://github.com/MaterializeInc/database-issues/issues/9194
> Uniquely identified runs with UUIDs

- misc/helm-charts/operator/templates/deployment.yaml
- misc/images/materialized-base/Dockerfile
> Bump console version to 25.2.2

- src/sql/src/optimizer_metrics.rs
Optimizations are much slower in debug builds, so this PR increases the slow optimization warning threshold in debug builds, to not spam people screens with the big warnings. ([slack discussion](https://materializeinc.slack.com/archives/C08ACQNGSQK/p1750844468500809?thread_ts=1750844293.433969&cid=C08ACQNGSQK))
> Increase threshold for slow optimization warning in debug builds

- test/cluster/mzcompose.py
This PR improves the test-github-3553 cluster test in two ways:
* Pulls the table creation out of the timing measurement. This should make the test less flaky.
* Improve the assert message by (a) mentioning the correct timeout and (b) showing the elapsed time.
Hopefully fixes https://github.com/MaterializeInc/database-issues/issues/9412
> test: improve test-github-3553

- src/sql/src/optimizer_metrics.rs
Minor follow-up on
https://github.com/MaterializeInc/materialize/pull/32838#discussion_r2166698098
> Change slow optimization warning threshold from soft_assertions_enabled to cfg!(debug_assertions)

- Cargo.lock
- src/ore/src/overflowing.rs
- src/repr/Cargo.toml
- src/repr/src/row.rs
- src/repr/src/timestamp.rs
- src/workspace-hack/Cargo.toml
Add missing columnar implementations
> Add missing Columnar implementations

- misc/python/materialize/cli/ci_annotate_errors.py
Noticed in https://buildkite.com/materialize/test/builds/105466
> ci: Deduplicate panics by removing timestamps

- test/testdrive-old-kafka-src-syntax/load-generator-key-value.td
- test/testdrive/load-generator-key-value.td
Fixes https://github.com/MaterializeInc/database-issues/issues/9440
> tests: fix load-generator tests that use source statistics

- doc/user/content/support.md
- doc/user/layouts/shortcodes/materialize-postgres-compatibility.html
Adding new instructions for getting Materialize support with Intercom
> Update support docs for Intercom

- doc/user/content/support.md
- doc/user/layouts/shortcodes/materialize-postgres-compatibility.html
- doc/user/layouts/shortcodes/self-managed/self-managed-editions-table.html
- port over support changes from `main` branch (https://github.com/MaterializeInc/materialize/pull/32806)
- add tweaks for self-managed. https://github.com/MaterializeInc/materialize/pull/32824/commits/1bd94fd53561dbe151005a69bdca19f392743c4d
> Docs self managed intercom

- bin/ci-annotate-errors
- ci/plugins/cloudtest/hooks/command
- ci/plugins/mzcompose/hooks/command
- misc/python/materialize/cli/ci_annotate_errors.py
> ci: Speed up annotations

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/cfg.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/write.rs
- src/storage/src/render/persist_sink.rs
https://github.com/MaterializeInc/database-issues/issues/9275
see also: https://github.com/MaterializeInc/materialize/pull/32509
> [storage] add bulk writing to persist

- ci/builder/Dockerfile
> ci-builder: Update cargo tool versions

- ci/mkpipeline.py
> ci: Refactor mkpipeline.py a bit

- .config/nextest.toml
- ci/mkpipeline.py
- ci/test/pipeline.template.yml
- test/pg-cdc-old-syntax/two-destination-schemas.td
- test/pg-cdc/two-destination-schemas.td
Build on top of https://github.com/MaterializeInc/materialize/pull/32989
> ci: Finer stuck detection in mkpipeline

- src/persist-client/src/internal/state.rs
> persist: proptest RunID roundtripping

- test/mysql-cdc-old-syntax/statistics.td
- test/mysql-cdc/statistics.td
- test/pg-cdc-old-syntax/statistics.td
- test/pg-cdc/statistics.td
Fixes https://github.com/MaterializeInc/database-issues/issues/9469
It's quite a bit more verbose now, but I think more correct, and I got to remove some of the `SUM`, which were a bit of a smell, I feel like.
> tests: fix multiple statistics.td files to be multi-replica aware

- doc/user/content/sql/alter-cluster.md
- doc/user/shared-content/alter-cluster-wait-until-ready-note.md
Following up on https://github.com/MaterializeInc/materialize/pull/32960#discussion_r2197928198
> doc/user: add re-usable note for WAIT UNTIL READY

- test/sqllogictest/explain/pushdown.slt
- test/testdrive/introspection-sources.td
> test flakiness fixes

- src/ore/src/future.rs
- src/persist/src/mem.rs
This PR moves persist's `yield_now` implementation into `mz-ore`, making it available to other crates.
I'm planning to use this in compute!
> persist: move `yield_now` into `mz-ore`

- src/ore/src/retry.rs
This PR unflakes the two `max_duration` retry tests in `mz-ore`. They were flaky because they expect to sleep for some amount of backoff time, but on a busy system their thread/task might be awoken significantly later than what they requested. As a result, the tests can sometime skip the second retry, if there isn't enough time left.
Rather than bumping the backoff times (as we did once before) and hope that the system is never busy enough to also flake under the bumped durations, this commit makes the tests instead accept that one retry might be skipped.
Fixes https://github.com/MaterializeInc/database-issues/issues/7441
Fixes https://github.com/MaterializeInc/database-issues/issues/9482
> ore: unflake retry max_duration tests

- misc/mcp-materialize/pyproject.toml
> release mcp server 0.3

- src/persist-cli/src/maelstrom/txn_list_append_single.rs
- src/persist-client/src/read.rs
Chasing down a very rare flake in a maelstrom test. The cause appears to be the test harness attempting to start a listen operation at a time earlier than the since hold it's obtained on the shard... so if the since of the shard is downgraded aggressively, the listen may work at first but then fail.
IMO it would be good to change the API so that we disallow reads before the since we've obtained, but that has the risk of causing errors for calls that currently work, so for now let's add a soft assert and tweak the test to avoid this case.
https://github.com/MaterializeInc/database-issues/issues/9400
> [persist] Fix a frontier issue in maelstrom test

- misc/python/materialize/mzbuild.py
Still required for pushing, but that only happens in CI
Noticed by @doy-materialize  in https://materializeinc.slack.com/archives/C0246GEHL8N/p1753132292043999
> mzbuild: Make docker buildx optional

- doc/user/layouts/shortcodes/postgres-direct/ingesting-data/allow-materialize-ips.html
Updates the link for the DROP SUBSOURCE instructions on the ingest pg shortcode
> Update DROP SUBSOURCE link

- ci/test/cargo-test/mzcompose.py
- misc/python/materialize/mzcompose/services/azurite.py
- misc/python/materialize/mzcompose/services/materialized.py
- misc/python/materialize/mzcompose/services/testdrive.py
- test/azurite/Dockerfile
- test/azurite/mzbuild.yml
- test/data-ingest/mzcompose.py
- test/feature-benchmark/mzcompose.py
- test/parallel-benchmark/mzcompose.py
- test/parallel-workload/mzcompose.py
- test/platform-checks/mzcompose.py
- test/secrets-logging/mzcompose.py
- test/testdrive-old-kafka-src-syntax/mzcompose.py
- test/testdrive/mzcompose.py
- test/txn-wal-fencing/mzcompose.py
- test/zippy/mzcompose.py
https://materializeinc.slack.com/archives/C01LKF361MZ/p1753434743943129
```
Error response from daemon: pull access denied for mcr.microsoft.com/azure-storage/azurite, repository does not exist or may require 'docker login': denied: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { …
```
> tests: Mirror Azurite on DockerHub

- ci/mkpipeline.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/33118
> mkpipeline: Fix detection for available images

- doc/user/content/integrations/_index.md
- doc/user/content/integrations/fdw.md
- doc/user/content/integrations/http-api.md
- doc/user/content/integrations/websocket-api.md
- doc/user/content/serve-results/_index.md
- doc/user/content/serve-results/fdw.md
- doc/user/shared-content/fdw-setup-intro.md
- doc/user/shared-content/fdw-setup-postgres.md
- doc/user/shared-content/fdw-setup-prereq.md
Added to both serve results section and integrations section:
https://preview.materialize.com/materialize/33186/serve-results/fdw/
https://preview.materialize.com/materialize/33186/integrations/fdw/
> docs: add foreign data wrapper instructions

- Cargo.lock
- doc/user/layouts/shortcodes/sql-server-direct/ingesting-data/use-aws-privatelink.html
- src/ore/src/netio.rs
- src/ore/src/netio/dns.rs
- src/postgres-util/src/tunnel.rs
- src/sql-server-util/BUILD.bazel
- src/sql-server-util/Cargo.toml
- src/sql-server-util/src/config.rs
- src/sql-server-util/src/lib.rs
- src/sql/src/plan/statement/ddl/connection.rs
- src/storage-types/src/connections.rs
https://github.com/MaterializeInc/database-issues/issues/9204
> sql_server: add support for aws private link

- test/data-ingest/mzcompose.py
- test/limits/mzcompose.py
> tests: Fix sharding for limits & data-ingest

- doc/developer/guide.md
> dev docs: Advertise eatmydata

- test/sqllogictest/cardinality.slt
It was still flaky even with the raised timeout.
https://materializeinc.slack.com/archives/C01LKF361MZ/p1753969714759999?thread_ts=1753969599.148499&cid=C01LKF361MZ
> Skip cardinality.slt

- bin/doc
- test/cluster/mzcompose.py
> doctests: Retry if incremental build fails & cluster tests: Fix refresh-mv-restart

- ci/deploy/pipeline.template.yml
- ci/test/pipeline.template.yml
- misc/python/materialize/git.py
- misc/python/materialize/mzcompose/__init__.py
- test/sql-server-cdc/mzcompose.py
> ci: Test, Nightly, Deploy pipeline fixes/improvements

- src/compute-types/src/explain/text.rs
- src/compute-types/src/plan.rs
- src/compute-types/src/plan/interpret/api.rs
- src/compute-types/src/plan/interpret/physically_monotonic.rs
- src/compute-types/src/plan/lowering.rs
- src/compute-types/src/plan/render_plan.rs
- src/compute/src/render.rs
- src/compute/src/render/flat_map.rs
- src/compute/src/render/reduce.rs
- test/sqllogictest/explain/default.slt
- test/sqllogictest/explain/physical_plan_aggregates.slt
- test/sqllogictest/explain/physical_plan_as_json.slt
- test/sqllogictest/explain/physical_plan_as_text.slt
- test/sqllogictest/explain/physical_plan_as_text_redacted.slt
- test/sqllogictest/github-2746.slt
- test/sqllogictest/outer_join.slt
- test/sqllogictest/reduce_mfp.slt
- test/sqllogictest/transform/literal_constraints.slt
- test/sqllogictest/transform/normalize_lets.slt
- test/sqllogictest/transform/relax_must_consolidate.slt
- test/sqllogictest/window_funcs.slt
This is a simple refactoring just to make the code and EXPLAIN easier to read. (The default EXPLAIN is not modified, because that is tuned already; only the verbose physical plan EXPLAIN and the json LIR EXPLAIN are modified.) The touched LIR nodes are FlatMap, Reduce, ArrangeBy.
> Reorder the fields of LIR nodes to the order they happen

- ci/nightly/pipeline.template.yml
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/cloudtest/k8s/testdrive.py
- misc/python/materialize/cloudtest/util/common.py
- misc/python/materialize/mzcompose/composition.py
- test/0dt/mzcompose.py
- test/cloudtest/test_managed_cluster.py
- test/sql-server-cdc/mzcompose.py
> tests: Nightly fixes (2025-08-12 edition)

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/catalog/migrate.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/show.rs
- src/sql/src/pure.rs
- test/sqllogictest/retain_history.slt
This reverts commit 8651738a6497f096607b8b990d1d0a2e6bd4c65c.
Fixes #9570
> Revert "sql: propagate retention windows by persisting them in SQL"

- src/timely-util/src/reclock.rs
The `reclock` logic drains progress updates and eagerly applies them to a maintained mutable antichain. This has the potential to be quadratic if the operator falls behind once it has been presented with many distinct times, and is then shown many updates that each nudge the frontier forward; each will require a recomputation, each of which will take linear time.
This PR consolidates all progress updates and then applies them once, protecting against that overload scenario.
> Introduce overload protection for `reclock` progress updates

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
- misc/python/materialize/cli/ci_annotate_errors.py
- src/materialized/ci/Dockerfile
- test/testdrive-old-kafka-src-syntax/monotonic.td
Based on https://buildkite.com/materialize/nightly/builds/12859
> tests: Nightly fixes (2025-08-15 edition)

- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
- src/controller/src/clusters.rs
- src/orchestrator-kubernetes/src/lib.rs
- src/orchestrator/src/lib.rs
Makes it a bit easier to search for cluster replica pods.
> add replica name annotations to replica statefulset

- Cargo.lock
- doc/user/content/releases/v0.155.md
- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- misc/helm-charts/testing/materialize.yaml
- src/balancerd/BUILD.bazel
- src/balancerd/Cargo.toml
- src/catalog-debug/BUILD.bazel
- src/catalog-debug/Cargo.toml
- src/clusterd/BUILD.bazel
- src/clusterd/Cargo.toml
- src/environmentd/BUILD.bazel
- src/environmentd/Cargo.toml
- src/materialized/BUILD.bazel
- src/materialized/Cargo.toml
- src/orchestratord/BUILD.bazel
- src/orchestratord/Cargo.toml
- src/persist-client/BUILD.bazel
- src/persist-client/Cargo.toml
- src/testdrive/BUILD.bazel
- src/testdrive/Cargo.toml
- **release: bump to version v0.155.0-dev.0**
- **release: create doc file for v0.155**
> Bump to v0.155.0-dev

- src/storage-controller/src/collection_mgmt.rs
Previously, the `update_tx.send` calls could fail because we were not holding the `{differential,append_only}_collections` lock anymore when performing them, making it possible for the writer task to be shut down in the time between the sender acquired the channel and the send. This PR avoids this by making sure the corresponding lock is held across each `send` call.
Fixes https://github.com/MaterializeInc/database-issues/issues/9590
> collection_mgmt: hold lock for while sending writes

- doc/user/content/manage/disaster-recovery/_index.md
> fix msk reference to be eks

- src/persist-client/benches/benches.rs
- src/persist-types/src/timestamp.rs
The previous implementation allows + and - in the numeric sections, which we shouldn't.
> [persist] Don't delegate to rust's integer parsing in try-parse-monotonic fn

- src/storage-client/src/storage_collections.rs
Reverts MaterializeInc/materialize#33435
Seeing lots of panicking nightlies: https://materializeinc.slack.com/archives/C01LKF361MZ/p1756412760576399
Nightly run to verify that this fixes it: https://buildkite.com/materialize/nightly/builds/13015
> Revert "storage: register collections in the order provided"

- src/timely-util/src/reclock.rs
Sources emit data close to their frontier and so even when a large number reclock bindings are stored in the remap trace the updates coming in will be reclocked after going over the first few bindings. The current operator continues to spin around the loop, computing every remaining binding even when there are no more updates to reclock, burning CPU time.
This PR changes the loop condition to check whether there are remaining updates to work on. This ought to fix most of the performance issues we see in prod where reclock operators are going over the entire remap trace over and over again.
> timely-util: stop early when there is no more work to do

- doc/user/content/ingest-data/monitoring-data-ingestion.md
- doc/user/content/ingest-data/postgres/alloydb.md
- doc/user/content/ingest-data/postgres/amazon-aurora.md
- doc/user/content/ingest-data/postgres/amazon-rds.md
- doc/user/content/ingest-data/postgres/azure-db.md
- doc/user/content/ingest-data/postgres/cloud-sql.md
- doc/user/content/ingest-data/postgres/faq.md
- doc/user/content/ingest-data/postgres/neon.md
- doc/user/content/ingest-data/postgres/self-hosted.md
- doc/user/content/ingest-data/troubleshooting.md
https://preview.materialize.com/materialize/33393/ingest-data/postgres/faq/
> docs: alternatives for replica full

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/all_checks/source_errors.py
- misc/python/materialize/sqlsmith.py
Based on https://buildkite.com/materialize/nightly/builds/13318
Test run: https://buildkite.com/materialize/nightly/builds/13320
> tests: Nightly fixes (2025-09-10)

- src/compute/src/logging/compute.rs
- test/sqllogictest/introspection/relations.slt
Switches the import frontier logging from vectors to columnar.
> Switch import frontier compute logging to columnar

- src/adapter/src/catalog/transact.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/validity.rs
- src/catalog/src/builtin.rs
- src/catalog/src/durable/initialize.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/tests/open.rs
- src/catalog/tests/read-write.rs
- src/sql/src/catalog.rs
- src/sql/src/plan.rs
- src/sqllogictest/src/ast.rs
- src/sqllogictest/src/parser.rs
- src/sqllogictest/src/runner.rs
- test/sqllogictest/role.slt
> Fix case where role modification can wipe out role password

- doc/user/content/sql/create-source/postgres.md
- doc/user/shared-content/postgres-considerations.md
- doc/user/shared-content/postgres-known-limitations.md
- doc/user/shared-content/postgres-remove-unused-replication-slots.md
- doc/user/shared-content/postgres-wal.md
https://preview.materialize.com/materialize/33546/ingest-data/postgres/#replication-slots
https://preview.materialize.com/materialize/33546/sql/create-source/postgres/#postgresql-replication-slots
> docs: single-source postgres replication slots considerations

- Cargo.lock
- WORKSPACE
- ci/test/lint-main/checks/check-copyright.sh
- misc/bazel/c_deps/patches/snappy-config.patch
- src/rocksdb/Cargo.toml
- src/storage/Cargo.toml
- src/workspace-hack/Cargo.toml
> Update RocksDB to 0.24

- src/transform/src/predicate_pushdown.rs
I broke them in a previous change.
> Fix doc tests

- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/binary.rs
- src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_timestamp_interval.snap
- src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_timestamp_tz_interval.snap
- src/expr/src/scalar/snapshots/mz_expr__scalar__func__sub_timestamp_interval.snap
- src/expr/src/scalar/snapshots/mz_expr__scalar__func__sub_timestamp_tz_interval.snap
Not wired up yet, but tested. Next PR will wire it up.
> Sqlfunc for {add,sub}_timestamp{tz}_interval

- src/adapter/src/error.rs
- src/postgres-util/src/replication.rs
- src/sql/src/plan/error.rs
- src/sql/src/plan/explain/text.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/sql/src/pure/error.rs
- src/sql/src/pure/postgres.rs
- src/storage-client/src/storage_collections.rs
- src/storage-types/src/connections.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/sources/sql_server.rs
- src/storage/src/source/sql_server.rs
- src/storage/src/source/sql_server/progress.rs
- src/storage/src/source/sql_server/replication.rs
- src/storage/src/storage_state/async_storage_worker.rs
- test/pg-cdc-old-syntax/override/insufficient-wal-level.td
- test/pg-cdc-old-syntax/override/replication-disabled.td
- test/pg-cdc-old-syntax/override/replication-slots.td
- test/pg-cdc-old-syntax/privileges.td
- test/pg-cdc/override/insufficient-wal-level.td
- test/pg-cdc/override/replication-disabled.td
- test/pg-cdc/override/replication-slots.td
- test/pg-cdc/privileges.td
The diff is entirely code movement. The commits are:
1. Simple struct rename to match the naming scheme of the other connections
2. Pure code movement, splits the creation of a `GenericSourceConnection` struct in the planner into a separate function. This will eventually be used in purification to delete a lot of duplicated code there.
3. More code movement of validation logic that was done ad-hoc during purification into the connection validation functions. This has the side benefit that users get error messages from validation earlier (during `CREATE CONNECTION`) rather than getting surprised during `CREATE SOURCE`.
> storage: quality of life refactors (part 2)

- doc/user/content/ingest-data/sql-server/self-hosted.md
- doc/user/content/sql/create-source/sql-server.md
- doc/user/layouts/shortcodes/sql-server-direct/ingesting-data/allow-materialize-ips.html
- doc/user/shared-content/sql-server-considerations.md
- Updates to docs
- Removed private preview flags
- Fixed typos
> Docs changes for Sql Server launch

- ci/nightly/pipeline.template.yml
- misc/python/materialize/zippy/scenarios.py
> ci: Nightly fixes (2025-09-24)

- doc/user/content/release-notes/_index.md
> Self managed 25.8 release notes

- doc/developer/best-practices.md
- doc/developer/style-informal.md
- doc/developer/style.md
Introduce a informal style guide separate to the more SQL- and Rust-oriented guides.
> Informal style guide

- src/proto/Cargo.toml
Seen in https://buildkite.com/materialize/nightly/builds/13629#_
> ci: Ignore unused deps warning

- doc/user/content/sql/select/_index.md
> docs: Fix OPTIONS clause typo

- test/terraform/mzcompose.py
> terraform tests: fix new line for consistency
