MaterializeInc/materialize

- ci/builder/requirements.txt
To fix deploy step: https://buildkite.com/materialize/deploy/builds/15131#0190e31e-0836-48f3-a33b-1f0b7ad34349
cryptography.utils.CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
Will require a paramiko upgrade to accomodate the new cryptography version
-
> ci-builder: Downgrade cryptography again

- doc/user/content/integrations/sql-clients.md
By default, DBeaver hides system objects in the database explorer. This
includes tables, views, and other objects that start with `pg_` or `mz_`.
Adding instructions on how to show those.
> doc: DBeaver guide show system objects

- misc/python/materialize/cli/bazel.py
This PR switches from using bazel to run `bin/bazel gen` to cargo since there are some issues to workout with the setup on Linux
Unbreaks `bin/bazel gen`
- N/a
> bazel: Use cargo to run `bin/bazel gen`

- bin/ci-builder
- ci/test/lint-main/checks/check-bazel.sh
Came out of trying out bazel: https://materializeinc.slack.com/archives/CM7ATT65S/p1721819297335879?thread_ts=1721794029.046489&cid=CM7ATT65S
```
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1
fatal: not a git repository: /home/deen/git/materialize/.git/worktrees/materialize3
```
-
> ci-builder: Support git worktrees

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
> test-analytics: Ignore network error during upload

- .bazelrc
- ci/test/pipeline.template.yml
- misc/bazel/c_deps/BUILD.openssl.bazel
- misc/bazel/c_deps/repositories.bzl
`openssl 1.1.1w` was removed from upstream repositories, also the Cargo build already depends on openssl3
Fix Bazel
- N/a
> bazel: Upgrade to openssl 3.3.1

- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/iter.rs
Fixes: https://github.com/MaterializeInc/materialize/issues/26170
This inversion dates way back, and has survived several refactorings. Not great!
The first commit fixes the bug, and tries two things to make it less likely to have similar issues in the future:
- Renames the method etc. to `wrong_sort` instead of `maybe_unconsolidated`. (I suspect part of the confusion is that maybe-unconsolidated is a weirdly negated name, making it less likely to notice that we had it backwards.)
- Adds a metric; hard to imagine this would have lasted as long as it did with proper visibility.
-
> [persist] Fix a flipped conditional and try not to do it again

- src/persist-types/build.rs
- src/persist-types/src/arrow.proto
- src/persist-types/src/arrow.rs
- src/persist-types/src/lib.rs
- src/repr/src/relation.rs
- src/repr/src/row/encoding2.rs
- src/storage-types/src/sources.rs
This PR adds `ProtoArray`, which is a protobuf encoded Arrow array that includes the column name and nullability info.
In memory we have Apache Arrow arrays, to S3 we write Parquet, and now for inline writes to consensus we will write `ProtoArray`. We could instead use Parquet or the Arrow IPC format but inline writes are particularly space sensitive and both of these formats include data that we don't need and thus would be wasteful to store.
Progress towards: https://github.com/MaterializeInc/materialize/issues/24830
- N/a
> persist: add `ProtoArray`, protobuf encoded Arrow data

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
Trying to trace down the failure `encoding with 'idna' codec failed` observed in https://buildkite.com/materialize/test/builds/86741#0190e89e-758c-43f7-ae74-1c9191590130:
```
File "/var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0f89f4771e00c06c4-1/materialize/test/misc/python/materialize/test_analytics/connector/test_analytics_connector.py", line 65, in create_connection
connection = pg8000.connect(
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pg8000/__init__.py", line 111, in connect
return Connection(
^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pg8000/legacy.py", line 443, in __init__
super().__init__(*args, **kwargs)
File "/usr/local/lib/python3.11/dist-packages/pg8000/core.py", line 312, in __init__
self.channel_binding, self._usock …
```
> test analytics: add more logging on connection failure

- ci/plugins/cloudtest/hooks/post-command
- misc/python/materialize/buildkite.py
- misc/python/materialize/test_analytics/config/mz_db_config.py
- misc/python/materialize/test_analytics/config/sandbox_db_config.py
- misc/python/materialize/test_analytics/config/test_analytics_db_config.py
- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/stubs/pg8000/__init__.pyi
> ci: Also print QA-relevant failures & other improvements

- ci/plugins/mzcompose/hooks/post-command
Seems to work fine for cloudtest so far
-
> ci: Also upload separate ci-annotate-errors.log for mzcompose

- misc/nix/shell.nix
Some more packages needed to make `nix-shell --pure` work.
> nix-shell: add more dependencies

- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/cluster.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
- src/adapter/src/flags.rs
- src/catalog/src/builtin.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/protocol/command.proto
- src/compute-client/src/protocol/command.rs
- src/compute/src/compute_state.rs
- src/compute/src/metrics.rs
- src/controller/src/clusters.rs
- src/ore/src/metrics.rs
- test/cluster/mzcompose.py
This commit attaches a `workload_class` label whenever a metric is
associated with a workload with a known class (e.g., production,
staging). Relevant metrics are identified as followed:
* All metrics in a `clusterd` process inherit the workload class of
the cluster.
* All metrics in an `environmentd` process that have an `instance_id`
label inherit the workload class of the identified compute instance
(cluster).
This will allow us to filter our monitoring based on workload class.
The implementation introduces a new API to the metrics registry called a
"postprocessor", which can mutate the state of all metrics on every call
to `MetricsRegistry::gather`. This was the most efficient implementation
available. In the future, we may want to consider a more explicit
approach of plumbing the …
> adapter,compute,controller: attach workload_class label to relevant metrics

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/materialize/test_analytics/data/base_data_storage.py
> test-analytics: Run SETs only once per connection

- src/catalog/src/durable/upgrade/v60_to_v61.rs
Having a no-op migration was wrong, we need to explicitly change all cluster entries in the catalog to have the `workload_class` field.
Fixes https://github.com/MaterializeInc/materialize/issues/28519
- N/A
> catalog: fix v61 migration

- misc/python/materialize/parallel_workload/parallel_workload.py
- src/adapter/src/coord/command_handler.rs
In some rare cases the serialized ddl lock could be owned by a session and then that session tries to execute another statement without clearing its transaction state (which release the lock). As a workaround, detect this and fail the second statement instead of deadlocking.
This is not a full fix because we should never be entering this state, but will suffice as a workaround and unblock the release.
See #28400
- n/a
> adapter: detect when a serialized ddl deadlock would occur

- src/transform/src/analysis/equivalences.rs
It is important to minimize equivalence classes before applying the `project` action (which drops columns, but finds surrogate expressions). Failing to do this results in a confused equivalence class, which results in a more conservative output than is needed. We are unable to re-minimize as we execute, because we do not maintain a canonical form in this code (we are not looking for "canonical" terms, but ones that are supported by the columns supplied to the `project` call).
This enables predicates to survive the `Project` and `Reduce` operators, and most clearly make their way through grouping expressions. Although simplification "just happens" in non-recursive queries, recursive queries end up failing to determine that the predicates hold across iterations, because even if true in the …
> Minimize equivalence classes before applying projection analysis

- src/adapter/src/optimize/copy_to.rs
- src/adapter/src/optimize/dataflows.rs
- src/adapter/src/optimize/index.rs
- src/adapter/src/optimize/materialized_view.rs
- src/adapter/src/optimize/peek.rs
- src/adapter/src/optimize/subscribe.rs
- src/transform/src/analysis.rs
- src/transform/src/analysis/monotonic.rs
- src/transform/src/dataflow.rs
- src/transform/src/monotonic.rs
Refactor the Monotonicity transforms to use the Analysis framework, helping separate the derivations from the transforms.
* `MirRelationExpr::Constant { rows: Err(_), .. } => false,` needs a discussion.
* Opened #28499 for now.
> transform: port Monotonicity to the Analysis framework

- src/transform/src/analysis.rs
We would do two passes in order to more robustly implement analyses. We only need to do that when `LetRec` exists in the tree, and so we can track that as we go and avoid a second pass when it does not exist.
Fixes #28520.
-
> Avoid second analysis passes in the absence of `LetRec`

- src/transform/src/analysis.rs
While working on #28375, it was noticed that the wrong `Option` was being unwrapped. `depends` should definitely have the binding information, but `results` might be missing. The current code unconditionally tries to access the later, and presumably we never hit the case where it is missing.
This PR makes sure to use unwrap correctly.
This is potentially a change in earlier behaviour, although if the above assumptions are correct, the change should be OK.
> transform: fix array access to results

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/all_checks/sink.py
- misc/python/materialize/checks/mzcompose_actions.py
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/checks/scenarios_zero_downtime.py
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/data_ingest/executor.py
- misc/python/materialize/data_ingest/transaction_def.py
- misc/python/materialize/data_ingest/workload.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- misc/python/materialize/parallel_workload/database.py
- misc/python/materialize/parallel_workload/executor.py
- misc/python/materialize/parallel_workload/parallel_workload.py
- test/0dt/mzcompose.py
- test/data-ingest/mzcompose.py
- test/parallel-workload/mzcompose.py
- test/platform-checks/mzcompose.py
Currently blocked on https://github.com/MaterializeInc/materialize/issues/28216
-
> parallel-workload: Add 0dt deploy scenario, platform-checks: Enable read-only mode during upgrades, data-ingest: 0dt deployment disruptions

- src/persist-client/src/batch.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/stats.rs
- src/persist-types/src/columnar.rs
- src/persist/src/indexed/columnar.rs
- src/persist/src/indexed/columnar/arrow.rs
- src/persist/src/indexed/columnar/parquet.rs
- src/repr/src/row/encoding2.rs
- Add a couple codec-to-structured helpers.
- Remove an unnecessary option. (In practice data written to `ColumnarRecordsStructuredExt` is always `Some`.)
- Use the new helpers in `encode_updates`, avoiding some unnecessary re-encoding of data.
Support for #24830 - aside from the modest amount of work this currently saves, it's needed to avoid re-encoding structured data here once compaction is producing it directly.
`schema2_to_codec` is not used in this PR, but it's useful for roundtrip testing and for the next step in the migration - when the structured data becomes the canonical representation.
-
> [persist] Avoid re-encoding structured data when possible

- Cargo.lock
- src/balancerd/Cargo.toml
- src/catalog-debug/Cargo.toml
- src/clusterd/Cargo.toml
- src/environmentd/Cargo.toml
- src/persist-client/Cargo.toml
- src/testdrive/Cargo.toml
Bump version to v0.111.0-dev.
-
> release: bump to version v0.111.0-dev

- misc/python/materialize/checks/mzcompose_actions.py
- misc/python/materialize/data_ingest/transaction_def.py
> 0dt tests: IsLeader tells us when ready

- misc/python/materialize/data_ingest/workload.py
- misc/python/materialize/parallel_workload/action.py
- misc/python/materialize/parallel_workload/database.py
Seen in https://buildkite.com/materialize/nightly/builds/8814#_
-
> parallel-workload: Fix calling data-ingest workloads

- src/compute-client/src/metrics.rs
- src/ore/src/metrics.rs
- src/ore/src/metrics/delete_on_drop.rs
- src/persist-client/src/internal/metrics.rs
- src/rocksdb/tests/basic.rs
- src/service/src/grpc.rs
- src/storage-client/src/metrics.rs
- src/storage/src/metrics.rs
- src/storage/src/metrics/sink/kafka.rs
- src/storage/src/metrics/source.rs
- src/storage/src/metrics/source/kafka.rs
- src/storage/src/metrics/source/mysql.rs
- src/storage/src/metrics/source/postgres.rs
- src/storage/src/metrics/upsert.rs
- src/storage/src/statistics.rs
This PR cleans up the implementation of the delete-on-drop metrics by replacing the previous three specialized implementations (`DeleteOnDropCounter`, `DeleteOnDropGauge`, `DeleteOnDropHistogram`) with a single `DeleteOnDropMetric` type. The previous three types still exist but are now aliases that pin the concrete `MetricVec` type of the `DeleteOnDropMetric`.
The result is less redundancy in the implementation of the delete-on-drop wrappers, and more uniformity at the usage sites.
This is originally motivated by the #28097 work, for which I wanted to add a way to change the labels of delete-on-drop metrics and was annoyed by having to implement that functionality three times, for each of the three `DeleteOnDrop*` types. We are using a different approach …
> ore: consolidate `DeleteOnDrop*` metrics types

- .bazelrc
- ci/builder/Dockerfile
Quick experiment:
$ wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz
$ time tar xf clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz
36.30s user 10.79s system 123% cpu 38.096 total
$ time XZ_OPT=-T0 tar xf clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz
51.04s user 13.14s system 646% cpu 9.921 total
This doesn't seem to work in Bazel though, @ParkMyCar: Any idea? I remember you talked about using zstd instead of xz for Bazel, extracting seems to be very slow indeed and single-threaded
-
> bazel/ci-builder: Faster uncompression

- ci/nightly/pipeline.template.yml
- ci/plugins/mzcompose/hooks/post-command
Strange timeout seen in https://buildkite.com/materialize/nightly/builds/8822#0190eecf-4a9e-4666-805e-322a1850044b
-
> parallel-workload: Longer timeout, more post-command printing

- src/expr/src/relation.rs
- test/sqllogictest/cte_lowering.slt
- test/sqllogictest/explain/decorrelated_plan_as_json.slt
- test/sqllogictest/explain/decorrelated_plan_as_text.slt
- test/sqllogictest/github-17616.slt
- test/sqllogictest/outer_join_lowering.slt
- test/sqllogictest/window_funcs.slt
Some MIR constructors could have been smarter, and in the absence of this smartness they produced somewhat noisy plans.
-
> Improve several MIR constructors

- misc/python/materialize/buildkite.py
- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
> ci: Ignore further occurrences of #28472

- src/adapter/src/client.rs
- src/adapter/src/command.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/sql.rs
Both the HTTP and pgwire protocols automatically commit implicit transactions by calling AdapterClient::end_transaction which sends a Command::Commit to the Coordinator. That command produced a Plan::CommitTransaction (equivalent to the user typing `COMMIT`). Since this was a normal plan, the same as if it came from a SQL statement, the RBAC checks run. One of the checks verifies that the user's role still exists (regardless of the statement being executed). It is thus possible for the Plan::CommitTransaction to fail and not sequence its plan (in this case `sequence_end_transaction`). However, both the AdapterClient (and HTTP and pgwire protocols) had assumed that Command::Commit would always clean up the session's transaction state. But since the cleanup action happens in …
> adapter: add guarantees for AdapterClient::end_transaction

- ci/nightly/pipeline.template.yml
Seen failing in https://buildkite.com/materialize/nightly/builds/8815#_
Apparently too much load on Materialize
-
> ci: Go easier on parallel-workload DDL

- src/transform/src/analysis/equivalences.rs
- test/sqllogictest/outer_join_simplification.slt
Incorporate nullability information into `Equivalences` from `Get::typ` information, and harden the equivalence class minimization to avoid using nullability information from the input types, as this causes its *deletion* from the equivalence classes.
The `Equivalences` analysis did not introduce nullability statements when made by `Get` nodes, and it was unfortunately deleting nullability information when performing expression minimization: `expr.reduce(&types)` will now (as of https://github.com/MaterializeInc/materialize/pull/28018) optimize **away** expressions based on the nullability information in `types`. Independent of whether this is intended behavior generally, we can harden the code here to remove any nullability statements surfaced through the type, in order to prevent their …
> Incorporate non-null information, and prevent its deletion

- Cargo.lock
- src/adapter/src/catalog.rs
- src/catalog/Cargo.toml
- src/catalog/src/builtin.rs
- src/environmentd/src/bin/environmentd/main.rs
This commit adds a CLI argument to environmentd that can trigger builtin migrations. Usually builtin migrations can only be triggered by modifying builtin item definitions that are compiled into the binary, making them extremely difficult to test. The CLI arg added in this commit "tricks" environmentd into thinking that builtin tables are migrated making it much easier to test.
> catalog: Add env arg to trigger builtin migration

- ci/plugins/mzcompose/hooks/post-command
> Don't upload artifacts twice in mzcompose-based workflow

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/services/balancerd.py
- misc/python/materialize/zippy/all_actions.py
- misc/python/materialize/zippy/backup_and_restore_actions.py
- misc/python/materialize/zippy/balancerd_actions.py
- misc/python/materialize/zippy/crdb_actions.py
- misc/python/materialize/zippy/debezium_actions.py
- misc/python/materialize/zippy/framework.py
- misc/python/materialize/zippy/kafka_actions.py
- misc/python/materialize/zippy/minio_actions.py
- misc/python/materialize/zippy/mysql_actions.py
- misc/python/materialize/zippy/mysql_cdc_actions.py
- misc/python/materialize/zippy/mz_actions.py
- misc/python/materialize/zippy/peek_actions.py
- misc/python/materialize/zippy/pg_cdc_actions.py
- misc/python/materialize/zippy/postgres_actions.py
- misc/python/materialize/zippy/replica_actions.py
- misc/python/materialize/zippy/scenarios.py
- misc/python/materialize/zippy/sink_actions.py
- misc/python/materialize/zippy/source_actions.py
- misc/python/materialize/zippy/storaged_actions.py
- misc/python/materialize/zippy/table_actions.py
- misc/python/materialize/zippy/view_actions.py
- test/zippy/mzcompose.py
> zippy tests: Add 0dt deploys

- misc/python/materialize/parallel_workload/action.py
Seems not to occur anymore
Fixes: #28219 
-
> parallel-workload: Remove ignore for #28219

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/scenarios_zero_downtime.py
- test/platform-checks/mzcompose.py
> platform-checks: Reenable 0dt X-4 scenario

- misc/python/materialize/buildkite.py
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/output_consistency/output_consistency_test.py
- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/materialize/test_analytics/setup/tables/00-config.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
- test/feature-benchmark/mzcompose.py
- test/scalability/mzcompose.py
I propose to make it configurable whether to notify QA about issues going wrong on non-main branches. I learnt that If something breaks, it takes long until the fix is propagated to most feature branches.
b91eb8d472 test analytics: qa notification: refactoring
d3d3066dca qa notifications: move restriction to default branch
3f40dd8f5d test analytics: cache settings
e267dc3f65 test analytics: expose settings
bb63f05530 test analytics: settings: add only_notify_about_communication_failures_on_main
4e37ad8437 test analytics: qa notifications: consider only_notify_about_communication_failures_on_main
> test analytics: configurable QA notifications

- ci/plugins/cloudtest/hooks/post-command
- ci/plugins/mzcompose/hooks/post-command
Seen failing in https://buildkite.com/materialize/nightly/builds/8852#0190fe42-2d65-441c-8a9c-721d65c9d16a and caused us to not have logs for an interesting failure
-
> ci: Continue when ci-annotate-errors fails

- misc/python/materialize/test_analytics/setup/tables/01-build.sql
Lack of it causes slowness in `INSERT INTO build ... SELECT ... WHERE NOT EXISTS ...`
Verified its usage with `EXPLAIN PLAN`:
```
Explained Query:
Project (#1..=#7, #0, #8, #9) // { arity: 10 }
Map (2024-07-29 13:37:23.198 UTC, "release-qualification", 559, "0190f863-e476-46fa-8f83-35b2d5407830", "v0.110.1", "6bb4a5f1a20024e7d48c7938248443c3d64e9629", "6cfefe42fce15783876941ac124870ac4c1359f7", "v0.110.1", 12, null) // { arity: 10 }
Union // { arity: 0 }
Negate // { arity: 0 }
Distinct project=[] // { arity: 0 }
Project () // { arity: 0 }
ReadIndex on=raw.test_analytics.build build_build_id_idx=[lookup value=("0190f863-e476-46fa-8f83-35b2d5407830")] // { arity: 12 }
Constant // { arity: 0 }
- ()
Used Indexes:
- raw.test_analytics.build_build_id_idx (lookup)
Target cluster: test_analytics …
```
> Add index for build (build_id)

- misc/python/materialize/version_ancestor_overrides.py
> feature-benchmark: Ignore OptbenchTPCH regressions

- misc/python/materialize/buildkite.py
> QA notifications: Remove ignores

- src/adapter/src/error.rs
- src/adapter/src/session.rs
- src/storage-client/src/controller.rs
- test/sqllogictest/transactions.slt
Previously, we disabled write transactions that try to write to more than one table. The reason was that we had no way of atomically writing to multiple tables. With the introduction of txn-wal we do have a method of writing to multiple tables atomically and in fact all writes in a single group commit are written atomically in a single txn-wal transaction.
This commit removes the restriction on multi table transactions, because it is now safe.
Resolves #14567
- Allow write transactions to write to multiple tables.
> adapter: Allow multi table write transactions

- src/controller/src/lib.rs
- src/storage-client/src/storage_collections.rs
- src/storage-client/src/storage_collections/metrics.rs
* This PR addresses issues discovered while investigating MaterializeInc/incidents-and-escalations#37.
- n/a
> storage-controller: further shard finalization improvements

- test/mysql-cdc/alter-table-after-source.td
> mysql cdc tests: Disable alter-table-after-source.td

- misc/python/materialize/buildkite.py
- misc/python/materialize/test_analytics/data/build/build_history_analysis.py
main is a branch, not a pipeline?
Introuced in https://github.com/MaterializeInc/materialize/pull/28592
-
> test-analytics: Remove pipeline == main check

- misc/python/materialize/checks/all_checks/load_generator.py
- misc/python/materialize/checks/all_checks/mysql_cdc.py
- misc/python/materialize/checks/all_checks/pg_cdc.py
- src/adapter/src/catalog/migrate.rs
- src/adapter/src/catalog/open.rs
- src/catalog/src/durable/transaction.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/names.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/show.rs
- src/sql/src/plan/with_options.rs
- src/sql/src/pure.rs
- src/sql/src/pure/mysql.rs
- src/sql/src/pure/postgres.rs
- src/storage-types/src/sources.proto
- src/storage-types/src/sources.rs
- src/storage-types/src/sources/load_generator.proto
- src/storage-types/src/sources/mysql.proto
- src/storage-types/src/sources/mysql.rs
- src/storage-types/src/sources/postgres.proto
- src/storage-types/src/sources/postgres.rs
- test/legacy-upgrade/create-in-v0.108.0-sources.td
- test/legacy-upgrade/mzcompose.py
- test/mysql-cdc/30-text-columns.td
- test/mysql-cdc/35-ignore-columns.td
- test/mysql-cdc/alter-source.td
- test/pg-cdc/alter-source.td
- test/pg-cdc/pg-cdc.td
Fixes https://github.com/MaterializeInc/materialize/issues/28491
This is prep work for accomplishing https://github.com/MaterializeInc/materialize/issues/28451
I initially wrote a PR that does both tasks together but found it too big to review, so if you'd like to see where this is going you can check out that draft PR here: https://github.com/MaterializeInc/materialize/pull/28453
In that PR we drop the fields in each top-level source `details` option that are now stored on each subsource `details` option instead. And we can remove a lot of the extra work we have to do in sequencing to merge those details values when an `ALTER SOURCE ADD SUBSOURCES` statement happens. And we get rid of the index-based approach of mapping values in the details …
> storage/sources: Copy subsource-specific option values to `CREATE SUBSOURCE` statements

- src/adapter/src/config/backend.rs
@jkosh44  & @benesch What do you think of this one? I changed it because it showed up as a sentry issue, which can be misleading: https://materializeinc.sentry.io/issues/5647730831/?project=6780145&referrer=github_integration
-
> adapter: downgrade "cannot update system variable" to info! for read-only error

- src/adapter/src/catalog/open/builtin_item_migration.rs
This commit optimizes 0dt builtin item migrations by only writing to the migration shard when there is a migration. Previously, the migrations would always write to the migration shard, and commit an empty write if there are no migrations. Additionally, removing the empty write reduces some contention on the migration shard, for example when a read-only instance is starting up at the same time as a writeable instance.
Resolves #28605
This PR fixes a CI flake.
> catalog: Optimize 0dt builtin item migrations

- ci/test/build.py
- misc/python/materialize/ci_util/__init__.py
- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/mzbuild.py
- misc/python/materialize/ui.py
In #22989, we got nice collapsible section headers in buildkite. This
had to be reverted in #24504 because it made some usages spammy. Recover
the ability by adding a new method and selectively opt-in useful and
non-spammy spots.
Example effect on build x86_64
-
> buildkite: recover buildkite section headers

- src/adapter/src/coord/sequencer/inner.rs
- test/sqllogictest/updates.slt
Although the `selection` part of the RTW plan supported `now()` (because it goes through the normal peek pipeline which resolves those), the `assignment` part did not. Add scalar prep to support this.
Fixes #28561
- Support functions like `now()` in `SET` clauses of `UPDATE`: `UPDATE t SET x = now()`
> adapter: support unmaterializeable fns in ReadThenWrite plans

- WORKSPACE
- ci/mkpipeline.py
- ci/test/pipeline.template.yml
- misc/bazel/toolchains/rust.bzl
This PR changes our Bazel setup to fetch the Rust toolchain from our [toolchains](https://github.com/MaterializeInc/toolchains) repo that has been recompressed with zstd. `zstd` decompresses _maaaany_ times faster than `lzma2` which is the algorithm traditionally used in `.tar.xz` packages. For example, [Arch Linux](https://archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/) made the switch and saw a 1300% speedup in decompression.
It also changes the CI setup to re-run the Bazel builds if anything related to the Bazel setup changes.
Reduce the time it takes for Bazel to startup
- N/a
> bazel: Use Rust toolchain re-compressed with zstd

- src/catalog/src/builtin.rs
- test/testdrive/hydration-status.td
This PR tries to reduce the chance of having FPs for the hydration status of sinks in `mz_hydration_statuses` by also requiring their frontiers to be greater than the minimum. The proper fix would be to have actual hydration reporting for sinks (#28459), but that's more effort to implement.
Misconfigured sinks can show as hydrated. Reported by @SangJunBak in [Slack](https://materializeinc.slack.com/archives/C0761MZ3QD9/p1721677761289059).
@MaterializeInc/testing I'm not sure how to test this. I tried adding this to `hydration-status.td`:
```sql
> CREATE TABLE schema1 (a int)
> CREATE TABLE schema2 (a text)
> CREATE SINK snk_schema1
IN CLUSTER test
FROM schema1
INTO KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-snk_schema1-${testdrive.seed}') …
```
> adapter: reduce the chance of sink hydration FPs

- src/persist-client/src/batch.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/project.rs
- src/persist/BUILD.bazel
- src/persist/build.rs
- src/persist/src/indexed/columnar.rs
- src/persist/src/persist.proto
- src/repr/src/row/encoding2.rs
- src/storage-types/src/sources.rs
This PR adds the new `ProtoArrayData` type from https://github.com/MaterializeInc/materialize/pull/28354 to `ProtoColumnarRecords` so we can include structured data in inline batch parts.
I really need to figure out the story for estimating the encoded size of arrow data, with `ProtoArrayData` it should be fairly straight forward. For now if structured data is enabled we halve the threshold for inline parts as an estimate.
Technically completes the implementation for https://github.com/MaterializeInc/materialize/issues/24830
- N/a
> persist: Add structured data to inline writes

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/measurement.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
- misc/python/materialize/test_analytics/test_analytics_db.py
This removes the obscure `NANOSECONDS / 3` and changes the optbench unit to `NANOSECONDS`.
This will require a migration in the test analytics database:
```
UPDATE feature_benchmark_result SET wallclock = wallclock * 3 WHERE build_job_id IN (SELECT build_job_id FROM build_job bj INNER JOIN build b ON bj.build_id = b.build_id WHERE b.data_version < 19) AND scenario_name LIKE 'OptbenchTPCHQ%';
UPDATE feature_benchmark_discarded_result SET wallclock = wallclock * 3 WHERE build_job_id IN (SELECT build_job_id FROM build_job bj INNER JOIN build b ON bj.build_id = b.build_id WHERE b.data_version < 19) AND scenario_name LIKE 'OptbenchTPCHQ%';
```
> feature benchmark: measure duration for OptBench in nanoseconds

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
- test/kafka-rtr/mzcompose.py
Reduce Short Zippy actions
- Since Mz0dtDeploys take a few minutes each and we are sometimes bumping against the 30 min timeout. We don't want to run for longer since this runs on each PR. Seen in https://buildkite.com/materialize/test/builds/87122#019100f5-0255-4ad5-9b77-061f71fdf8c8
Also move explicit 0dt test back to test pipeline, it's been green for a while.
Fix pg-cdc-resumption test to shard properly instead of running the same set in each test.
Add sharding to kafka-rtr test since it is the slowest now.
-
> ci: Minor fixes to test pipeline

- test/testdrive/distinct-arrangements.td
While it uses mz_arrangement_sharing, it doesn't actually care about the sharing of arrangements, just their existence
-
> testdrive: Rename mz-arrangement-sharing.td

- misc/python/materialize/parallel_workload/action.py
- misc/python/materialize/parallel_workload/parallel_workload.py
Noticed in https://github.com/MaterializeInc/materialize/issues/28182#issuecomment-2257973674
Fixes: https://github.com/MaterializeInc/materialize/issues/28182
-
> parallel-workload: Prevent deadlocks when swapping

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- test/feature-benchmark/mzcompose.py
Avoid that all failing rows are listed under all scenarios.
> feature benchmark: error annotation: only include matching matching scenario

- src/persist-cli/src/maelstrom/txn_list_append_multi.rs
- src/persist-cli/src/maelstrom/txn_list_append_single.rs
- src/persist-client/src/cache.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/cli/args.rs
- src/persist-client/src/internal/cache.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/rpc.rs
- src/persist/src/cfg.rs
- src/persist/src/metrics.rs
- src/persist/src/s3.rs
- src/storage-operators/src/persist_source.rs
This is how the `DynamicConfig` that it's replacing works, we don't need mutable access, and this will save a good amount of BTreeMap copies.
Happened to notice this while I was working on #28539.
-
> persist: wrap PersistConfig's ConfigSet in an Arc

- ci/plugins/cloudtest/hooks/post-command
- ci/plugins/mzcompose/hooks/post-command
- misc/python/materialize/cli/ci_annotate_errors.py
> ci: Properly handle ci-annotate-errors failing

- src/adapter/src/catalog/apply.rs
> catalog: Actually improve error message

- doc/user/content/sql/create-role.md
Remove the RBAC enable statement.  The page has privileges section.
> docs: rm obsolete RBAC enable statement

- ci/plugins/cloudtest/hooks/post-command
- ci/plugins/mzcompose/hooks/post-command
- misc/python/materialize/cli/ci_annotate_errors.py
Print failure to stderr so we still see it in normal output
Kind of messy again, starts to feel like we need a test for our testing infrastructure.
-
> ci: Annotations have to be uploaded before ci-annotate-errors

- misc/python/materialize/git.py
> tests: Fix git fetch to ignore .git ending

- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
- src/storage-controller/src/persist_handles.rs
This PR adds a new method, `alter_table_desc(...)` to the `StorageController` and `StorageCollections` to support updating the `RelationDesc` of a table. It also implements a `todo!(...)` in `txn-wal` to support updating the `WriteHandle` for a managed collection. 
Progress towards: https://github.com/MaterializeInc/materialize/issues/28082
Two things I'm unsure about and would love feedback on:
1. How does this fit with Pv2? I saw there is a "can_write" when creating collections that I didn't consider here.
2. How do the timestamps for forgetting and registering in txn-wal look? It's easy enough to plumb in another timestamp if necessary.
- N/a
> storage: Support updating the `WriteHandle`/`RelationDesc` for a table owned by txn-wal

- src/compute-client/src/controller/replica.rs
- src/storage-controller/src/rehydration.rs
We're occasionally seeing connection errors in production that report only "transport error", which is not enough information to track down the error. Use anyhow's alternate formatting to print the full cause chain for these errors, which should help track down the issue.
* This PR will help us track down a bug occurring in production.
- n/a
> compute,storage: include cause chain on connection errors

- src/sql-pretty/src/doc.rs
Was showing up with leading space.
- n/a
> sql-pretty: fix create source format printing

- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
Fixes #28634
Apparently, this can happen! But when the upper is empty, we don't really care about what dependency since we get: we don't write anymore.
-
> storage: relax check on dependency since when upper.is_empty()

- src/expr/src/scalar.rs
- src/transform/src/analysis/equivalences.rs
Our `MirScalarExpr::reduce` function uses the nullability in column types provided as inputs. However, this nullability information is not certain to remain true as we reshape the expression (specifically our nullability information feeding in to types depends on whether things are joins or filters, whether `Get::typ` information has been recently refreshed).
This adds a method `MirScalarExpr::reduce_safely` that does not rely on this information (or rather, unsets the information before calling in to `reduce`). This function should be safe to call in any context, even if the input type nullability changes.
-
> Introduce `MirScalarExpr::reduce_safely`

- src/catalog/src/durable/persist.rs
This commit improves the error message that is returned when a read only catalog attempts to commit a write by including the contents of the write in the error.
> catalog: Improve error message in read-only write

- src/persist-client/src/critical.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/read.rs
- src/persist-client/src/write.rs
As the comment mentions, these existed because of the Drop impl. I feel silly that I didn't think of this technique earlier, but instead of having the various K, V, T, D, bounds on Drop, we can store the expire logic as a `BoxFuture<'static, ()>` at handle construction time.
I don't remember the exact history of this, but it's some combination of:
- Persist was not originally async
- Persist did not originally have auto-expire Drop impls for the handles
- I was still skilling up on async
- I have a tendency to avoid allocs when even remotely possible, even when it doesn't matter (as is the case here)
Pure refactor, no behavior change, modulo one alloc when constructing a read or write handle.
-
> persist: clean up K, V, T, D bounds on Read + Write + Since handles

- test/legacy-upgrade/mzcompose.py
To make CI green until we have a proper fix
-
> legacy-upgrade test: Disable catalog store validation

- misc/dbt-materialize/dbt/include/materialize/macros/materializations/test.sql
- misc/dbt-materialize/tests/adapter/test_clusters.py
`dbt test` picks up the `cluster` configuration from `dbt_project.yml`, if it exists, but otherwise defaults to `quickstart` if no cluster is specified. Although we can't enforce that a valid cluster is specified, we should fall back to the cluster specified in `profiles.yml` in that scenario.
Reported on [Slack](https://materializeinc.slack.com/archives/C077R8Z9XGC/p1721926079069049).
> dbt-materialize: handle absence of default cluster in data tests

- misc/python/materialize/mzbuild.py
Spammy in https://buildkite.com/materialize/nightly/builds/8897#01910db5-66b1-4789-9121-f3abb1fcddd2
Follow-up to https://github.com/MaterializeInc/materialize/pull/28615
-
> mzbuild: Switch Acquiring to header instead of section

- misc/python/materialize/version_ancestor_overrides.py
> feature-benchmark: Ignore another set of optbenchtpch regressions

- Cargo.lock
- misc/cargo-vet/audits.toml
- misc/cargo-vet/imports.lock
- src/persist-client/benches/plumbing.rs
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-types/Cargo.toml
- src/persist-types/src/parquet.rs
- src/persist/Cargo.toml
- src/persist/src/indexed/columnar/parquet.rs
- src/persist/src/indexed/encoding.rs
- src/storage-types/src/sources.rs
- src/workspace-hack/Cargo.toml
This PR adds two dyncfgs for Parquet encoding, one to enable dictionary encoding and a second to enable compression.
Parquet supports dictionary encoding and compression which can both seriously reduce the size of the encoded data. We need to run benchmarks to determine if we should enable these features, adding these dyncfgs is the first step in doing that.
- N/a
> persist: Wire Parquet dictionary encoding and compression to `LaunchDarkly`

- doc/user/layouts/partials/head.html
- doc/user/layouts/partials/sidebar.html
- Removing the ai widget wholesale.   Although we could keep it on the lower-bottom corner, not a great experience right now and undermine confidence when it's fixed and we release.
- Put back previous search.
> docs: remove kapa ai widget

- Cargo.lock
- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/explain/insights.rs
- src/adapter/src/optimize.rs
- src/adapter/src/optimize/copy_to.rs
- src/adapter/src/optimize/index.rs
- src/adapter/src/optimize/materialized_view.rs
- src/adapter/src/optimize/peek.rs
- src/adapter/src/optimize/subscribe.rs
- src/adapter/src/optimize/view.rs
- src/sql/Cargo.toml
- src/sql/src/lib.rs
- src/sql/src/optimizer_metrics.rs
- src/sql/src/plan/lowering.rs
- src/sql/src/plan/lowering/variadic_left.rs
- src/sql/src/plan/statement/dml.rs
To aid the planning of work on outer joins, this PR adds a metric that counts each of the cases of outer join lowering.
The first commit just moves `OptimizerMetrics` to `mz_sql`. This is somewhat unfortunate, but I didn't see a better way to make it available in the lowering. I'm open to ideas. (In the long run, I guess it would be great to have an `mz_optimizer` crate, which would include the stuff that is currently in `mz_transform`, and also the lowering, and maybe some other minor things.)
The second commit was a lot of typing, but very straightforward: just wires the `OptimizerMetrics` to every part of the lowering. (I couldn't just wire it to a smaller subset of functions, because all of these many functions are co-recursively calling each other.)
The third commit is the main …
> Add metrics for outer join lowering cases

- src/sql/src/plan/lowering.rs
- src/sql/src/plan/lowering/variadic_left.rs
Follow-up to #28688, see https://github.com/MaterializeInc/materialize/pull/28688#discussion_r1700432239
~The first 6 commits are in #28688.~ Edit: That one merged in the meantime, so rebased this on main.
-
> Refactor the passing around of metrics and Config in the HIR lowering

- Cargo.lock
- misc/python/materialize/mzcompose/__init__.py
- src/balancerd/Cargo.toml
- src/catalog-debug/Cargo.toml
- src/clusterd/Cargo.toml
- src/environmentd/Cargo.toml
- src/persist-client/Cargo.toml
- src/testdrive/Cargo.toml
The edge case on the persist_schema_register check (which use of this dyncfg is gated behind) was wrong, and so we thought this was running on main, but it wasn't. The release process caused it to find the cursed txn-wal TODO. Reverting until we fix the problematic callers.
-
> persist: turn off persist_schema_require in CI

- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/open/builtin_item_migration.rs
This commit fixes an issue with 0dt builtin item migrations. Materialize determines if a builtin item is migrated by comparing a compiled in fingerprint with a durably stored fingerprint. Previously, the 0dt builtin item migrations did not update the durably stored fingerprint after migrating an item. This commit fixes that issue.
Resolves #28636
> catalog: Store fingerprints in 0dt migrations

- src/storage/src/source/kafka.rs
- test/testdrive/kafka-recreate-topic.td
Fixes https://github.com/MaterializeInc/incidents-and-escalations/issues/98.
We've seen this issue twice in the last couple of weeks and believe it was introduced by this PR: https://github.com/MaterializeInc/materialize/pull/28058 
The Sentry [logs](https://materializeinc.sentry.io/issues/5655610932/?project=6780145&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&stream_index=0) indicate that we saw a message from an offset we had already seen prior to the panic, and that PR removed the seek-forwarding of the consumer group offset that previously prevented us from downgrading to a frontier we'd already moved beyond:
This PR allows the downgrade to fail using `try_downgrade` to account for this case when we are simply …
> storage/sources/kafka: Avoid a panic when downgrading to an offset we've already seen

- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/mzcompose/composition.py
- test/legacy-upgrade/mzcompose.py
And disable 0dt system parameter explicitly when not running 0dt upgrades to make sure we still exercise the old path fully
-
> legacy upgrade test: 0dt upgrades

- src/adapter/src/catalog/migrate.rs
When validating the v0.111.1 release we discovered that some subsource statements use an `of_source` with a `RawItemName::Name` reference to their source, rather than a `RawItemName::Id` reference that can easily be looked up in the list of AST items.
This PR adjusts the migration to use a mapping of names to statements to look up the source for each subsource statement that uses the named reference.
This is a stop-gap fix to allow the release to proceed. The correct long-term fix is to figure out why some subsources use named-only references, and to fix that and migrate them all to use id-based references. 
Would disable whitespace, a lot of the diff is just an indentation change
-
> migrations: Fix subsource migration that assumed all source references would use GlobalIds

- misc/python/materialize/data_ingest/transaction_def.py
- test/data-ingest/mzcompose.py
Would require setting the correct deployment generation, may be fenced out already. Seen failing in https://buildkite.com/materialize/nightly/builds/8911#01911067-9409-407c-a2eb-9e5796ab351c
-
> data-ingest: Disable sanity restart

- src/storage-types/src/sources.rs
It turns out we mis-diagnosed the testdrive kafka failures that Parker was seeing as being caused by the txn-wal TODO. They were actually caused by shard finalization's placeholder schema, which was fixed in the #28454 schema registry PR.
This should be enough to get CI green with the desired assertion. However, since there's a known second occurrence of the bad schema behavior, keep it as a soft_assert to prevent it from regressing in CI but also eliminate the possibility for it to cause issues in prod.
Touches #28146
-
> persist: re-enable now fixed schema assertion

- doc/user/content/concepts/indexes.md
- doc/user/content/concepts/views.md
- doc/user/content/get-started/_index.md
- doc/user/content/get-started/quickstart.md
- doc/user/content/sql/create-index.md
- doc/user/content/sql/create-materialized-view.md
- doc/user/content/sql/create-view.md
Added behavior w.r.t. preserving monotonicity (indexes) and not (materialized views).
- Added a second patch to raise awareness of indexing a non-mat view to the create mat view page.   (generally don't mix separate changes like this, but since small).
> docs: indexes and mat views - monotonicity behavior diffs

- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
Removes the old `REHYDRATION TIME ESTIMATE` option, which is superseded by `HYDRATION TIME ESTIMATE` (with the same meaning). This is a private preview feature, and the two users who have it are using it through dbt, which already redirects both versions to `HYDRATION TIME ESTIMATE`. Also note that they were forced to switch to the new dbt version. (Forcing them to the new dbt version was an accident, and quite unfortunate in general, but good for making sure that we can remove the old option in a timely manner, before anyone else starts using it.)
- Removing a deprecated version of a feature: #28140
-
> Remove deprecated `REHYDRATION TIME ESTIMATE`

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/transact.rs
- src/catalog/src/durable/error.rs
This commit adds a safeguard to error if we every try and commit an item to the catalog that depends on an item with a larger `GlobalId`. `GlobalId` ordering needs to match dependency ordering, otherwise the catalog will become corrupt.
> catalog: Add safeguard for corrupt catalogs

- test/testdrive/alter-sink.td
> test: Add test for ALTER SINK

- misc/python/materialize/mzcompose/__init__.py
- src/persist-cli/src/maelstrom/txn_list_append_multi.rs
- src/persist-client/src/batch.rs
- src/persist-client/src/internal/state.rs
- src/persist-client/src/write.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/sources.rs
- src/txn-wal/src/lib.rs
- src/txn-wal/src/txn_write.rs
- src/txn-wal/src/txns.rs
This closes the "cursed txn-wal TODO" \o/!
Before, we would sometimes fall back to a default "placeholder" schema
in txn-wal (in prod, an empty RelationDesc), but this causes issues with
the soon-to-be-rolled out persist columnar work (see #28146).
Now, we make sure to keep track of data shard write handles that are
handed directly to `register` and use only those for `commit` calls.
This ensures that only a real schema is used to encode batches.
For additional sanity, when applying a batch, use the matching schema by
fetching it from persist if necessary. This fixes issues with background
compaction work spawned as a result of the CaA call.
Closes #28146
-
> txn-wal: fix persist schema hygiene

- misc/python/materialize/cli/ci_annotate_errors.py
This had confused me when looking into an occurrence of
> +++ ci-annotate-errors failed, which indicates that an unknown error was found
> ci: annotate errors: return code handling

- misc/python/materialize/checks/all_checks/sink.py
Seen in https://buildkite.com/materialize/test/builds/87438
-
> platform-checks: Fix alter sink flake

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/comparator.py
```
NAME                                | TYPE            |      THIS       |      OTHER      |  UNIT  | THRESHOLD  |  Regression?  | 'THIS' is:
------------------------------------------------------------------------------------------------------------------------------------------------------
CrossJoin                           | wallclock       |           1.123 |           1.170 |   s    |    10%     |      no       |  4.0 pct   faster
CrossJoin                           | memory_mz       |        3067.017 |        2947.807 |   MB   |    10%     |      no       |  4.0 pct   more
CrossJoin                           | memory_clusterd |         391.102 |         395.679 |   MB   |    10%     |      no       |  1.2 pct   less
```
```
+++ Benchmark Report for cycle 1:
NAME …
```
> feature benchmark: improve output

- deny.toml
This addresses:
```
✗ check-cargo.sh
--- bin/lint-cargo
--- cargo --locked fmt -- --check
--- cargo --locked deny check licenses bans sources
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
┌─ /Users/nrainer/Workspaces/mz-repo/deny.toml:254:1
│
254 │ copyleft = "deny"
│ ━━━━━━━━
2024-08-03 08:00:03 [ERROR] failed to validate configuration file /Users/nrainer/Workspaces/mz-repo/deny.toml
^^^ 🚨 Failed: cargo --locked deny check licenses bans sources
--- cargo hakari generate --diff
info: 
--- original
+++ modified
--- cargo hakari manage-deps --dry-run
info: no operations to perform
--- cargo deplint Cargo.lock ci/test/lint-deps.toml
```
https://github.com/EmbarkStudios/cargo-deny/pull/611
> lint: fix deprecation warning

- .github/pull_request_template.md
- doc/user/content/releases/v0.102.md
- doc/user/content/releases/v0.103.md
- doc/user/content/releases/v0.104.md
- doc/user/content/releases/v0.105.md
- doc/user/content/releases/v0.106.md
- doc/user/content/releases/v0.107.md
- doc/user/content/releases/v0.109.md
- doc/user/content/releases/v0.110.md
- doc/user/content/releases/v0.111.md
- doc/user/content/releases/v0.112.md
- doc/user/layouts/shortcodes/version-list.html
- doc/user/layouts/shortcodes/warn-if-unreleased-inline.html
- doc/user/layouts/shortcodes/warn-if-unreleased.html
We've had a few releases recently with no detailed release notes. Link these releases to the changelog rather than an empty page for a smoother user experience.
- n/a
> doc/user: link to changelog when no release notes

- src/persist/src/location.rs
This should fix the deploy job observed failing in https://buildkite.com/materialize/deploy/builds/15335#019118b4-bb90-42b7-8d96-292bbd9848b0.
```
error: unportable markdown
--> src/persist/src/location.rs:373:5
|
373 | /     /// Return `limit` versions of data stored for this `key` at sequence numbers
374 | |     /// >= `from`, in ascending order of sequence number.
375 | |     ///
376 | |     /// Returns an empty vec if `from` is greater than the current sequence
377 | |     /// number or if there is no data at this key.
| |__________________________________________________^
|
= help: confusing block quote with no space after the `>` marker
```
> persist: fix rustdoc

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/test_analytics/data/build/build_history_analysis.py
- misc/python/materialize/test_analytics/setup/views/02-build-job.sql
From 5.35 GB to 54 MB
Proof that this still works: https://buildkite.com/materialize/test/builds/87398#_
-
> test-analytics: Reduce memory for mv_recent_build_job_success_on_main

- misc/python/materialize/output_consistency/execution/evaluation_strategy.py
- misc/python/materialize/output_consistency/execution/multi_mz_executors.py
- misc/python/materialize/output_consistency/execution/query_execution_manager.py
- misc/python/materialize/output_consistency/execution/sql_executor.py
- misc/python/materialize/output_consistency/output/reproduction_code_printer.py
- misc/python/materialize/output_consistency/output_consistency_test.py
- misc/python/materialize/output_consistency/status/test_summary.py
- misc/python/materialize/postgres_consistency/postgres_consistency_test.py
- misc/python/materialize/version_consistency/execution/multi_version_executors.py
- misc/python/materialize/version_consistency/version_consistency_test.py
- test/output-consistency/mzcompose.py
- test/postgres-consistency/mzcompose.py
- test/version-consistency/mzcompose.py
This is the base for https://github.com/MaterializeInc/materialize/pull/28439.
3475f94dd9 output consistency: provide mz_system connection
7a6d173753 output consistency: trigger events around query execution
1fb942c7dc output consistency: move creation of SqlExecutors
8bb89546e9 output consistency: reproduction code printer: add assertion
79ce0c3e6b output consistency: reproduction code printer: allow including further infos
fc79c7ade8 output consistency: allow overriding desired runtime
f8e3039c42 output consistency: allow merging test summaries
d27dc7a5cb version consistency: move evaluation strategy constants
c6b5e287e4 version consistency: extract evaluation strategy creation
d56893b22e version consistency: generalize MultiMzSqlExecutors …
> feature-flag consistency test: preparations

- Cargo.toml
- misc/python/materialize/cli/gen-lints.py
- misc/wasm/Cargo.toml
This should fix https://buildkite.com/materialize/deploy/builds/15342#01912114-aee8-476a-8140-fdac2e7ee221 by allowing us footnotes in rustdoc:
```
error: unportable markdown
--> src/compute-types/src/plan/reduce.rs:374:69
|
374 |     /// More details in the monotonic one-shot `SELECT`s design doc.[^1]
|                                                                     -^^^
|                                                                     |
|                                                                     help: if it should not be a footnote, escape it: `\`
|
= note: `-D rustdoc::unportable-markdown` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(rustdoc::unportable_markdown)]`
```
> cargo: allow unportable_markdown in rustdoc

- misc/python/materialize/parallel_workload/action.py
> parallel-workload: Try enabling ALTER SINK again

- .github/workflows/cla.yml
Switch to using [the GitHub Actions based version](https://github.com/contributor-assistant/github-action) of the CLA Assistant that we have been using.
The [hosted version of the CLA Assistant](https://cla-assistant.io/) has been flaky recently. We will use the Actions version instead, configured to write the signatures into a new public repo: https://github.com/MaterializeInc/cla
Once this PR is pushed we will see if we can merge the existing signatures into the signature file. 
-
> new CLA assistant

- doc/user/content/sql/create-sink/kafka.md
As is, the statement would throw the following error:
```sql
Error: Expected a list of columns in parentheses, found identifier "k"
```
> doc: fix typo in create sink statement

- src/sql/src/plan/statement/ddl.rs
- test/testdrive/kafka-avro-sinks.td
- test/testdrive/kafka-sink-errors.td
As noticed in #28726, the current brevity of the  error messages made it hard to realize when an `ALTER SINK` command is failing due to the new `FROM` relation missing columns referenced by the sink's `KEY` clause.
* This PR improves error messages to make it easier to diagnose test failures.
> sql: improve errors for sink KEY clause

- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
Certain DDL statements can trigger an extended DDL transaction, when
run in a multi-statement transaction. These extended DDL
multi-statement transactions have special handling at all stages,
including when they attempt to acquire the DDL lock.
Previously, when executing a statement and acquiring the DDL lock, we
would try and deduce if we are in an extended DDL transaction, by
looking at the type of statement being executed. This is not a robust
check, because those statement that trigger an extended DDL transaction
in multi-statement transactions do not trigger an extended DDL
transaction in single-statement transactions. Currently, the statements
that can trigger an extended DDL transaction are renames and swaps. As
a consequence of this behavior, when a rename or swap are executed in …
> adapter: Fix concurrent DDL

- src/orchestrator-process/src/secrets.rs
Follow-up to https://github.com/MaterializeInc/materialize/pull/28812
> orchestrator-process: Fix context for reading secret

- misc/dbt-materialize/dbt/adapters/materialize/connections.py
When connecting to Materialize using the dbt adaapter, we should pass an additional argument that specifies the application name. This is useful for telemetry.
Fixes #28804
> dbt-materialize: add dbt version to application_name

- src/compute-client/src/metrics.rs
Turns out that not having a 10s bucket is very confusing in practice because the human brain just assumes it must exist. Add that bucket to give our brains some slack.
[Relevant Slack thread.](https://materializeinc.slack.com/archives/C073FCHFWV6/p1722518350885899)
* This PR refines an internal metric.
> compute: 10s bucket for wallclock lag metric

- src/adapter/src/catalog.rs
- src/adapter/src/coord.rs
- src/catalog/src/durable.rs
The existing code to cleanup orphaned secrets during coordinator bootstrap was not properly handling 0dt deployments, and could inappropriately remove secrets that were added by the old environment during the deployment process. The race worked like this:
* New 0dt deployment created.
* New envd begins booting in read-only mode.
* New envd loads catalog and begins bootstrapping coordinator.
* Old envd creates a secret.
* New envd finishes bootstrapping.
* New envd cleans up orphaned secrets based on now-stale catalog and removes the secret that the old envd just added.
This patch adds two safeguards:
1. The orphaned secrets cleanup is careful to never delete secrets that have a global ID that is larger than the largest global ID known to the catalog.
This protects not just against the …
> adapter: handle 0dt deploys in orphaned secrets cleanup

- src/sql/src/session/vars/value.rs
- Adds GMT to support PG switch from UTC to GMT for FDW in https://github.com/postgres/postgres/commit/a3021aafcecbc5225bf99f235db4130546d543c1
Materialize no longer worked with pg foreign data wrapper because it does not support SET TIMEZONE GMT.
I don't know the implications of adding GMT
-
> add gmt timezone to fix pg_fdw

- bin/feature-flag-consistency-test
- ci/nightly/pipeline.template.yml
- misc/python/materialize/feature_flag_consistency/execution/multi_config_executors.py
- misc/python/materialize/feature_flag_consistency/feature_flag/feature_flag.py
- misc/python/materialize/feature_flag_consistency/feature_flag_consistency_test.py
- misc/python/materialize/feature_flag_consistency/ignore_filter/feature_flag_consistency_ignore_filter.py
- misc/python/materialize/feature_flag_consistency/input_data/feature_flag_configurations.py
- test/feature-flag-consistency/README.md
- test/feature-flag-consistency/mzcompose
- test/feature-flag-consistency/mzcompose.py
This is based on https://github.com/MaterializeInc/materialize/pull/28752.
9dd936d872 feature-flag consistency: add test
d987e96981 feature-flag consistency: specify flag configurations
5e954cc432 feature-flag consistency: add mzcompose
40c107dc72 feature-flag consistency: use mz as started when running outside mzcompose
cbf465776c feature-flag consistency: remove feature flag configuration check
6122c0bdba feature-flag consistency: add README
4874ff9f82 ci: add feature-flag consistency test to nightly
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Aoutput-consistency%2Ffeature-flags
Once joins are supported by the test framework (https://github.com/MaterializeInc/materialize/issues/19825), configure
* `enable_outer_join_null_filter`
* …
> feature-flag consistency test

- misc/python/materialize/buildkite.py
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/git.py
- misc/python/materialize/version_list.py
Previously if you picked a commit on main it would use the common-ancestor, which is the commit itself, and thus compare against itself, rendering the test run useless.
-
> feature-benchmark: Pick a better version to compare against

- doc/user/content/integrations/_index.md
- doc/user/content/manage/dbt/development-workflows.md
- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_await.sql
- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
- misc/dbt-materialize/dbt/include/materialize/macros/utils/await_cluster_ready.sql
- misc/dbt-materialize/dbt/include/materialize/macros/utils/is_cluster_ready.sql
- misc/dbt-materialize/tests/adapter/test_deploy.py
This PR introduces a new `lag_tolerance` argument to the `deploy_promote` and `deploy_await` operations in the db adapter. This allows users to specify a custom maximum acceptable lag duration when waiting for deployment readiness, providing a better control over the deployment process.
Fixes #28831
> dbt-materialize: add lag tolerance arg to dbt deploy

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Release dbt-materialize v1.8.4 to pick up https://github.com/MaterializeInc/materialize/pull/28832
> dbt-materialize: release v1.8.4

- misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/8987#01912c9e-6d7f-4b94-ad4d-3d80dfc8e831.
> postgres consistency: ignore to account for different evaluation order

- src/ore/src/tracing.rs
This should allow us to use semantic versioning to compare releases: https://docs.sentry.io/platforms/rust/configuration/releases/
> Semantic Versioning: package@version or package@version+build (for example, my.project.name@2.3.12+1234)
> We automatically detect whether a project is using semantic or time-based versioning based on:
> If ≤ 2 releases total: we look at most recent release.
> If 3-9 releases (inclusive): if any of the most recent 3 releases is semver, project is semver.
> If 10 or more releases: if any of the most recent 3 releases is semver, and 3 out of the most recent 10 releases is semver, then the project is semver.
I decided against using clusterd@v0.111.0, environmentd@v0.111.0 because we already have the binary information and they are all released in unison.
Should …
> tracing: Use package@version

- doc/user/content/sql/create-sink/kafka.md
- src/adapter/src/catalog/migrate.rs
- src/sql/src/kafka_util.rs
- test/legacy-upgrade/check-from-v0.111.0-kafka-sink.td
- test/legacy-upgrade/create-in-v0.111.0-kafka-sink.td
- test/testdrive/kafka-compression.td
Per Confluent best practice and user request.
This patch is a bit complicated so that we can preserve the existing
`COMPRESSION TYPE = NONE` setting for sinks that already exist.
Forcing all *new* sinks to default to LZ4 unless explicitly configured
seems safe enough (i.e., no need to slow roll this to certain customers)
because compression is very well tolerated in the Kafka ecosystem.
Fix https://github.com/MaterializeInc/materialize/issues/25242.
> adapter: default Kafka sink compression to LZ4

- README.md
* We no longer use Github milestones. Is there a better link instead?
* PostgreSQL **features** doesn't sound completely correct (?), but a word still feels missing here.
>  Remove old info from README

- doc/user/content/sql/types/_index.md
This is not a real alias that exists.
Fix #28854.
* This PR fixes a recognized documentation bug.
> doc/user: remove nonexistent uint alias

- Cargo.lock
- src/aws-secrets-controller/Cargo.toml
- src/aws-secrets-controller/src/lib.rs
We have some evidence that reading secrets from AWS might stall indefinitely. Add a basic log line that indicates when an AWS secret read starts and ends to prove or disprove this hypothesis if it occurs again in production.
We log at an `info!` level so that we have visibility into every secrets read. These are relatively infrequent, so this shouldn't be a meaningful increase in log volume. We don't want to log at a lower level because the hang has only occured rarely, so we want the logs on by default for when it happens next.
Fix #27933.
None.
> aws-secrets-controller: basic logging for secret reading time

- doc/developer/testdrive.md
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/checks/scenarios_zero_downtime.py
- misc/python/materialize/cli/run.py
- misc/python/materialize/cloudtest/k8s/environmentd.py
- misc/python/materialize/data_ingest/transaction_def.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/services/materialized.py
- misc/python/materialize/mzcompose/services/sql_logic_test.py
- misc/python/materialize/parallel_workload/action.py
- misc/python/materialize/parallel_workload/parallel_workload.py
- misc/python/materialize/zippy/backup_and_restore_actions.py
- misc/python/materialize/zippy/framework.py
- misc/python/materialize/zippy/mz_actions.py
- test/0dt/mzcompose.py
- test/data-ingest/mzcompose.py
- test/legacy-upgrade/mzcompose.py
Outside of 0dt tests
https://materializeinc.slack.com/archives/C01LKF361MZ/p1723047398367089
Review with https://github.com/MaterializeInc/materialize/pull/28858/files?w=1
> tests: Reenable persist_use_criticial_since_(snapshot|source)

- src/adapter-types/src/dyncfgs.rs
- src/adapter/src/coord.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
Behind multiple LD configration flags.
One problem with this is that newly migrated tables will not have their upper/write frontier continually advanced, meaning dataflows based on them will eventually not pass the are-we-caught-up check, even though they might initially pass that check while other, larger, dataflows are still hydrating.
Additionally, when there is no "old" envd deployment running that is continually pushing uppers forward, the new envd deployment would also eventually report that it's not caught up.
@benesch & @jkosh44 We might want to instead compare against `boot_ts` instead of `now()`. This way, we would not run into problems when there's no old `envd` deployment or when we have migrations. Wdyt?
> adapter,0dt: new rehydration check that compares collection upper against allowed lag

- src/adapter/src/catalog/open.rs
- src/adapter/src/coord.rs
- src/environmentd/src/bin/environmentd/main.rs
- src/environmentd/src/lib.rs
> envd: Add more logs with timings of envd startup

- src/storage/src/storage_state.rs
- test/cluster/mzcompose.py
This PR fixes two issues found with storage reconciliation:
* When sources are dropped during reconciliation, the replica encounters a (soft) panic because we remove the source IDs from `reported_frontiers` and then produce `AllowCompaction` commands for the same frontiers, which the command handler checks against `reported_frontiers`.
* When the client disconnects during reconciliation, _before_ we have received the `InitializationComplete` command, we will still perform a full reconciliation based on the commands received so far. This might cause us to discard storage state we should not discard.
The second issue has an obvious fix, aborting reconciliation when the client disconnects.
~~The first issue only seems to have annoying fixes. I went with introducing another field in …
> storage: reconciliation fixes

- src/cluster-client/src/client.rs
- src/storage-client/src/client.rs
- src/storage-client/src/metrics.rs
- src/storage-controller/src/history.rs
- src/storage-controller/src/instance.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/parameters.rs
- test/sqllogictest/github-28166.slt
This PR makes the storage controller connect to all replicas in each instance, rather than just the one most recently added. This solves two bugs around replica connections (https://github.com/MaterializeInc/materialize/issues/28046, https://github.com/MaterializeInc/materialize/issues/28166), prepares the storage controller code for active replication support, and makes the two controllers function more similarly. Note that it is still not allowed to run sources or sinks on clusters that have more than one replica, and the new code asserts this.
The implementation is copied from/heavily inspired by the compute controller implementation. The storage controller now gets an `Instance` struct that manages communication with the replicas in a cluster. Each `Instance` keeps track of its …
> storage: connect to all replicas

- misc/python/materialize/output_consistency/expression/expression_with_args.py
- misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
- misc/python/materialize/output_consistency/input_data/operations/all_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/string_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/table_operations_provider.py
- misc/python/materialize/output_consistency/input_data/params/enum_constant_operation_params.py
- misc/python/materialize/output_consistency/operation/operation.py
- misc/python/materialize/output_consistency/validation/result_comparator.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
- misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
7175982905 output consistency: mark table functions
5b5ad6936d output consistency: add table functions
13a2585ca1 output consistency: rename enum constant params
439d3ce867 output consistency: allow ignoring row order
6038acac09 output consistency: fix column sorting
f23e701481 output consistency: disable generate_series on date-time parameters
56617732f1 output consistency: expression matcher: add matcher argument_has_any_characteristic
a474b1212b version consistency: simplify ignore
b7edb0d2f5 postgres consistency: add ignore entries
1611254017 postgres consistency: ignore row order when table functions are involved
4f364dd955 postgres consistency: add ignore entry when sort order cannot be guaranteed
* https://github.com/MaterializeInc/materialize/issues/28806
* …
> output consistency: add table functions

- src/storage-controller/src/history.rs
This PR fixes merge skew introduced by #26423 and #28380.
* This PR fixes merge skew.
> fix merge skew on main

- src/persist-client/src/schema.rs
We construct the only write handles to the "catalog" and "txns" shards before syncing dyncfgs from LD (and before getting the previously saved values in the catalog), so those are the last two holdouts in staging/prod from being in the schema reg. Feels worthwhile to keep the momentum going on this and get every shard opted into it.
This PR means we'd have to build a patch release if any issues crop up during the rollout, but the uses of these two shards are much less varied than other shards, so I'm more comfortable saying that CI would shake out any issues (plus we'll see staging first). And worst case, it's just the extra cmd on writer registration and a sentry error, still no panics for more than one schema.
> persist: enable schema reg flags by default

- bin/bazel-temp
This will hopefully make it easier to see where time is going.
> bazel: make INFO logs into sections in CI

- ci/test/pipeline.template.yml
- misc/python/materialize/parallel_workload/action.py
- src/storage-controller/src/history.rs
- test/replica-isolation/mzcompose.py
Both closed by https://github.com/MaterializeInc/materialize/pull/28380
> Reenable tests for #28166 and #28046

- ci/nightly/pipeline.template.yml
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cloudtest/k8s/debezium.py
- test/kafka-matrix/mzcompose.py
Seems to be green now with https://github.com/MaterializeInc/i2/pull/2065
Doing another round of reruns in https://buildkite.com/materialize/nightly/builds/9009#_
> ci: Reenable Cloudtest on Hetzner

- doc/user/layouts/partials/head.html
Enable `cmd+k` for opening the modal.
> docs: enable cmd+k for kapa widget

- misc/images/materialized/entrypoint.sh
- misc/python/materialize/mzcompose/services/materialized.py
Since we're bringing this back as a supported method for trying Materialize. The idea here is to have a Segment key in the Docker image that we use by default.
Touches https://github.com/MaterializeInc/materialize/issues/28876.
@def-: anywhere else I should disable telemetry so that CI doesn't generate a bunch of noise?
@matthelm: this is going to flow into a new database in Snowflake called `self_hosted`. Schema matches `cloud_production`, but the cloud provider is `docker` and the cloud region is `container`. 
> materialized: add telemetry to Docker image

- ci/nightly/pipeline.template.yml
This reverts commit 09afd4c3a1bf3e7d2955d1a917d8e721cfe16ed2.
Has apparantely not worked, I am currently out of ideas. What I tried:
- Switch from Ubuntu to Fedora
- Disable systemd-resolved
- Set DNS servers manually
- Pass in systemd-resolved resolv.conf via kind
Maybe someone will have another idea: https://materializeinc.slack.com/archives/C01LKF361MZ/p1723140526811439
> Revert "ci: Reenable Cloudtest on Hetzner"

- Cargo.lock
- src/dyncfg/Cargo.toml
- src/dyncfg/src/lib.rs
This commit adds the functionality for a `Config` struct to parse a string into the correct `ConfigVal`. One potential use case for this feature, and the motivation of this commit, is to pass in default values for a `ConfigSet` via CLI arguments.
> dyncfg: Add parse functionality

- src/cluster/src/server.rs
- src/compute-client/src/controller/replica.rs
- src/compute-client/src/controller/sequential_hydration.rs
- src/compute-client/src/service.rs
- src/service/src/client.rs
- src/service/src/grpc.rs
- src/service/src/local.rs
- src/storage-client/src/client.rs
@petrosagg's comments on https://github.com/MaterializeInc/materialize/pull/28380 made me realize that `SequentialHydration::recv` was not cancel safe: Observing received responses might lead to more dataflows getting scheduled, which requires sending commands to the replica, but `GenericClient::send` is not required to be cancel safe.
This is fixed now by introducing a forwarder task that does the direct interaction with the wrapped client. `SequentialHydration` now only needs to send commands to a channel connected to that forwarder, which is non-async and therefore cancel safe.
A slightly annoying bit is that send errors aren't directly returned from `SequentialHydration::send` anymore, since that call is not waiting for the send to be successful. Instead they are returned on the next …
> compute: make `SequentialHydration::recv` cancel safe

- Cargo.lock
- src/balancerd/BUILD.bazel
- src/balancerd/Cargo.toml
- src/balancerd/src/dyncfgs.rs
- src/balancerd/src/lib.rs
- src/balancerd/src/main.rs
- src/balancerd/src/service.rs
- src/balancerd/tests/server.rs
- src/dyncfg-launchdarkly/src/lib.rs
- src/ore/src/tracing.rs
This commit adds dynamic configuration parameters to balancerd that can
control tracing.
> balancer: Add tracing dynamic config parameters

- src/compute-types/src/plan/flat_plan.rs
- src/compute/src/render.rs
- src/compute/src/render/context.rs
Add rendering regions around dataflow "objects to build" as well as both `Let` ~and `LetRec`~ values and bodies. NB: No `LetRec`: Rust gets angry.
The intended outcome is that it becomes easier to map dataflow operator addresses back to LIR/MIR fragments by way of their CTE identifiers. Prior to this PR, all were in one scope and were undifferentiated, which meant one needed to understand the union of all CTEs rather than just one at a time.
cc: @sthm 
-
> Render regions for object build and let bindings

- ci/nightly/pipeline.template.yml
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/fetch.rs
- src/persist-proc/src/lib.rs
This is done in a way that  relies on the Codec data still being
populated (i.e. for the consolidate optimization above it). Eventually
we'll have to rewrite this path to work entirely without Codec data, but
in the meantime, putting in here allows us to see the performance impact
of decoding entirely from arrow instead of Codec.
Plus, it'll likely be easier to port all the logic here to work solely
on arrow data once we finish migrating things like the
ConsolidatingIter.
Touches https://github.com/MaterializeInc/materialize/issues/24830
-
> persist: hook up decoding from only the structured arrow data

- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/iter.rs
- src/persist-client/src/read.rs
- src/persist/src/indexed/columnar.rs
- src/persist/src/indexed/encoding.rs
Two major changes to consolidation:
- Adds a method that applies timestamp rewriting / truncation directly to the columnar data. (Instead of incrementally while streaming it out.) 
- Reworks consolidation to thread indices through along with the actual keys and values. (If two updates have identical key-value pairs, the choice is arbitrary.)
These changes let us use `arrow::compute::interleave` to construct the output key/value arrays from the set of inputs to the consolidating iterator. This is particularly important for our new structured data - since there's no way to pass around a specific row of an arbitrary `ArrayRef`, it's important to do those manipulations by index.
Support for #24830.
Two things to sort out from nightlies:
-
> [persist] Switch the Consolidator to a more-columnar style

- src/adapter/src/catalog/migrate.rs
- src/storage-types/src/sources/mysql.proto
- src/storage-types/src/sources/mysql.rs
- src/storage-types/src/sources/postgres.proto
- src/storage-types/src/sources/postgres.rs
Removes the migration introduced in #28491 now that it's been applied
> storage/adapter: Remove subsource statement option migration

- doc/user/content/sql/system-catalog/mz_internal.md
- src/catalog/src/builtin.rs
- test/sqllogictest/autogenerated/mz_internal.slt
I recently added cluster_id to `mz_objects`, it would also be useful in `mz_object_fully_qualifed_names`.
> catalog: Add cluster_id to mz_object_fully_qualifed_names

- doc/user/content/releases/v0.113.md
- doc/user/content/sql/system-catalog/mz_catalog.md
- doc/user/content/sql/system-catalog/mz_internal.md
- src/catalog/src/builtin.rs
- test/sqllogictest/autogenerated/mz_catalog.slt
- test/sqllogictest/autogenerated/mz_internal.slt
- test/sqllogictest/information_schema_tables.slt
- test/sqllogictest/mz_catalog_server_index_accounting.slt
- test/sqllogictest/mz_recent_storage_usage.slt
- test/storage-usage/mzcompose.py
- test/testdrive/catalog.td
The view caused no performance issues in production, so stabilize it. The motivation for the fast stabilization is our new philosophy around stabilizing early and often so that users don't depend on mz_internal relations that can break at any time. The columns here are a subset of the already stable mz_storage_usage view, so there wasn't much to derisk besides the performance implications.
* This PR stabilizes a known-desirable feature.
> adapter: stabilize the mz_recent_storage_usage view

- misc/images/materialized/entrypoint.sh
- src/environmentd/src/bin/environmentd/main.rs
- src/environmentd/src/lib.rs
- src/environmentd/src/test_util.rs
- src/segment/src/lib.rs
- src/sqllogictest/src/runner.rs
Segment only records IPs for events on the server if the events originate from a "client-side library" (e.g., a library that runs in the user's browser). Segment determines the origin of an event based on the `context.library.name` field. So, add an optional flag to environmentd that causes our Segment client to emulate the Analytics.js library. This flag is on by default in the evalution Docker image (materialize/materialized).
Touches #28876.
> environmentd: enable client-side mode in Segment client

- misc/python/materialize/parallel_workload/action.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9023#0191330b-b56a-42d1-817d-bb76a81a9124
Verification: lhttps://buildkite.com/materialize/nightly/builds/9035
> parallel-workload: Don't alter sink based on webhook source

- ci/nightly/pipeline.template.yml
Seen in https://buildkite.com/materialize/nightly/builds/9034
Not sure yet if there is a regression in the product, seems suspicious. Checking
> ci: Bump some timeouts in nightly

- misc/python/materialize/version_ancestor_overrides.py
Seen in https://buildkite.com/materialize/nightly/builds/9034#_
@frankmcsherry is this expected?
```
ffcafa5b5c3e83845a868cf6103048c045b4f155 is the first bad commit
commit ffcafa5b5c3e83845a868cf6103048c045b4f155
Author: Frank McSherry <fmcsherry@me.com>
Date:   Fri Aug 9 13:05:14 2024 -0400
Render regions for object build and let bindings (#28307)
Add rendering regions around dataflow "objects to build" as well as both
`Let` ~and `LetRec`~ values and bodies. NB: No `LetRec`: Rust gets
angry.
The intended outcome is that it becomes easier to map dataflow operator
addresses back to LIR/MIR fragments by way of their CTE identifiers.
Prior to this PR, all were in one scope and were undifferentiated, which
meant one needed to understand the union of all CTEs rather than just
one at a time. …
```
> feature-benchmark: Ignore messages regression in many scenarios

- src/storage-controller/src/lib.rs
- src/storage-controller/src/persist_handles.rs
- src/storage-controller/src/persist_handles/read_only_table_worker.rs
This makes it so that shards of migrated builtin tables remain
readable at a recent timestamp. We have to treat them separately because
we cannot yet register them in txns.
Importantly, we are careful not to advance the upper further than the
upper of the txn shard because those tables will have to be registered
in txns once a new deployment restarts in read-write mode.
I recommend reviewing this commit by commit!
> storage: continually advance upper of migrated builtin tables to track txns upper

- src/storage-controller/src/lib.rs
The key schema for the txn shard is `TxnsCodecRow::desc()`, not an empty relation description.
This is merge skew introduced by the combination of #28877 and #28856.
Fixes: https://github.com/MaterializeInc/materialize/issues/28922
* This PR fixes a panic on main.
> storage-controller: fix key schema for txn shard

- misc/python/materialize/version_ancestor_overrides.py
> scalability framework: Ignore regressions

- deny.toml
This is extremely scary to me, why can we not fix it in abomonation?! https://rustsec.org/advisories/RUSTSEC-2021-0120
> This transmute is at the core of the abomonation crates. It's so easy to use it to violate alignment requirements that no test in the crate's test suite passes under miri. The use of this transmute in serialization/deserialization also incorrectly assumes that the layout of a repr(Rust) type is stable.
I feel like this could be causing some of the mystery segfaults we keep seeing in CI, for example https://github.com/MaterializeInc/materialize/issues/24644
> cargo security: Ignore abomonation being unsound

- ci/cleanup/pipeline.template.yml
- ci/deploy/pipeline.template.yml
- ci/deploy_mz/pipeline.template.yml
- ci/deploy_mz_lsp_server/pipeline.template.yml
- ci/deploy_website/pipeline.template.yml
- ci/license/pipeline.template.yml
- ci/mkpipeline.py
- ci/mkpipeline.sh
- ci/nightly/pipeline.template.yml
- ci/qa-canary/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/security/pipeline.template.yml
- ci/slt/pipeline.template.yml
- ci/test/pipeline.template.yml
- test/pg-cdc/mzcompose.py
This reverts commit 1ab980f411006c99df669b1f6cdc80fc1849911b.
Verification runs:
https://buildkite.com/materialize/security/builds/1278
https://buildkite.com/materialize/release-qualification/builds/568 & https://buildkite.com/materialize/release-qualification/builds/569
https://buildkite.com/materialize/test/builds/87931 & https://buildkite.com/materialize/test/builds/87944 & https://buildkite.com/materialize/test/builds/87955 & https://buildkite.com/materialize/test/builds/87980 & https://buildkite.com/materialize/test/builds/88051 & https://buildkite.com/materialize/test/builds/88077
> CI: Switch further tests to Hetzner

- doc/user/content/get-started/quickstart.md
- doc/user/content/sql/create-source/load-generator.md
- doc/user/content/sql/create-source/mysql.md
- doc/user/content/sql/create-source/postgres.md
- doc/user/content/sql/show-sinks.md
- doc/user/content/sql/show-sources.md
- misc/python/materialize/checks/all_checks/identifiers.py
- src/catalog/src/builtin.rs
- src/sql/src/plan/statement/show.rs
- test/mysql-cdc/mysql-cdc.td
- test/mysql-cdc/subsource-resolution-duplicates.td
- test/pg-cdc/pg-cdc.td
- test/pg-cdc/subsource-resolution-duplicates.td
- test/sqllogictest/materialized_views.slt
- test/sqllogictest/mz_catalog_server_index_accounting.slt
- test/sqllogictest/source_sizing.slt
- test/sqllogictest/system-cluster.slt
- test/sqllogictest/transactions.slt
- test/testdrive/catalog.td
- test/testdrive/distinct-arrangements.td
- test/testdrive/get-started.td
- test/testdrive/kafka-avro-sources.td
- test/testdrive/kafka-sinks.td
- test/testdrive/load-generator.td
- test/testdrive/materializations.td
- test/testdrive/quickstart.td
- test/testdrive/rename.td
- test/testdrive/tables.td
- test/testdrive/tpch.td
Since it doesn't make much sense now that we've removed linked clusters.
This is technically a backwards compatible change, but one we've decided we're comfortable with--see 25953.
Fix #25953.
> sql: remove size column from SHOW {SOURCES | SINKS}

- src/persist-cli/src/maelstrom/txn_list_append_multi.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/schema.rs
- src/persist-client/tests/machine/regression_listen_compaction
- src/persist-proc/src/lib.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
- src/txn-wal/src/lib.rs
- src/txn-wal/src/txns.rs
As of the release currently being qualified, these are on for all of staging and prod and we don't intend to turn them off. Use the new knowledge to clean up a TODO in txn_wal and remove a sus `RelationDesc::empty()`.
> persist: remove schema reg dyncfgs

- src/mysql-util/src/lib.rs
- src/mysql-util/src/schemas.rs
- src/ore/src/iter.rs
- src/sql/src/pure/mysql.rs
- src/storage/src/source/mysql.rs
- src/storage/src/source/mysql/replication.rs
- src/storage/src/source/mysql/replication/context.rs
- src/storage/src/source/mysql/replication/events.rs
- src/storage/src/source/mysql/schemas.rs
- src/storage/src/source/mysql/snapshot.rs
Implements https://github.com/MaterializeInc/materialize/issues/28435 for MySQL Sources
There aren't any added tests since we still restrict subsources from being added with the same external-reference at the SQL planning layer. This is intentional -- we don't plan to enable this capability for subsources, since those will be removed very soon. Instead the new `CREATE TABLE .. FROM SOURCE` statements will be allowed to reference the same external-reference and we will need to add tests then to validate that they function correctly.
You might note that this looks very different than previous implementation attempts and designs for 'subsource demuxing'. I took this approach of completely separating things by `SourceExport` rather than demuxing using …
> storage/sources: Handle SourceExports with the same external reference (upstream table) in MySQL sources

- ci/nightly/pipeline.template.yml
- misc/python/materialize/parallel_workload/action.py
Based on failures in https://buildkite.com/materialize/nightly/builds/9049
> ci: Make nightly greener again

- ci/mkpipeline.py
- ci/test/pipeline.template.yml
To increase developer velocity when all agents are busy
> ci: Lower priority on main branch compared to PRs

- src/persist-client/src/internal/compact.rs
- src/persist-client/src/iter.rs
We're getting input data with heterogenous array types, and arrow::compute::interleave can't handle it! Switch back to the old version until we've got a migration story.
Avoids a bug with interleaving arrays of different types - see https://github.com/MaterializeInc/materialize/pull/28914. This should help unblock running with structured data in CI.
> [persist] Temporarily switch back to the non-chunked iter in compaction

- misc/python/materialize/version_list.py
- test/legacy-upgrade/mzcompose.py
- test/skip-version-upgrade/mzcompose.py
Noticed by @sdht0 in https://materializeinc.slack.com/archives/CTESPM7FU/p1723491877661829?thread_ts=1723471217.547279&cid=CTESPM7FU
Fallout from https://github.com/MaterializeInc/materialize/pull/28860 (where I only considered the legacy upgrade test)
> skip version upgrade test: Consider released flag

- src/storage-controller/src/persist_handles/read_only_table_worker.rs
Should be an easy stamperoni! Follow up from PR review.
> storage: in read-only table worker, clean up boxed() calls

- misc/python/materialize/checks/all_checks/identifiers.py
- misc/python/materialize/parallel_workload/action.py
- test/limits/mzcompose.py
- test/testdrive/dataflow-dependencies.td
Based on failures in https://buildkite.com/materialize/nightly/builds/9061
Verification: https://buildkite.com/materialize/nightly/builds/9064 (green)
> ci: Get nightly greener (again)

- misc/python/materialize/mzcompose/__init__.py
- src/compute-client/src/controller/instance.rs
instead of continuing with promotion when it never becomes ready
Although I would prefer a mode for testing that panics when it is not ready, allows us to retain logs and wastes fewer resources than timing out.
> 0dt tests: Wait 100 days and time out tests

- src/storage-controller/src/lib.rs
Should help with diagnosing https://github.com/MaterializeInc/materialize/issues/28885
> storage: more context in dependency since assertion

- src/repr/src/row/encoding2.rs
Currently, we set the `nullability` of the field in a struct array based on whether / not the array contains any nulls. This means that two arrays generated by the same encoder may not have the same type, which limits our ability to eg. concatenate / consolidate them together later. (And concretely, this causes problems for the new consolidation code, which calls `interleave`, which expects all arrays to have the same type.)
Two ideas for fixes in separate commits:
- Third commit: we could just say every column is nullable. AFAICT this is fine and causes no problems. 
- Last commit: we could thread the nullability info from the RelationDesc through to the individual field.
Either seems basically fine to me, but I suspect the last commit is slightly more in line with the rest of our …
> [persist] Fix nullability in DatumColumnEncoder

- doc/user/content/sql/system-catalog/mz_internal.md
- misc/python/materialize/mzcompose/composition.py
- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/notice.rs
- src/catalog/src/builtin.rs
- src/orchestrator-kubernetes/src/lib.rs
- src/orchestrator-process/src/lib.rs
- src/orchestrator/src/lib.rs
- test/cloudtest/test_replica_restart.py
- test/ldbc-bi/q04.sql
- test/sqllogictest/mz_catalog_server_index_accounting.slt
- test/testdrive/distinct-arrangements.td
moves ready/not-ready to online/offline
in order to avoid conflation with a future
hydration status ready status
> change ready status to "online/offline"

- src/catalog/src/durable/objects/serialization.rs
- src/catalog/src/durable/objects/state_update.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/upgrade.rs
- src/catalog/src/durable/upgrade/tests.rs
This commit cleans up the catalog state update naming and documentation in an attempt to make it more understandable.
This is all renaming and adding docs, no logic has changed.
> catalog: Clean up state update docs and name

- Cargo.lock
- src/ore/Cargo.toml
- src/ore/src/netio.rs
- src/ore/src/netio/dns.rs
- src/storage-types/src/errors.rs
- test/mysql-cdc/mysql-cdc.td
- test/pg-cdc/pg-cdc.td
- test/ssh-connection/ssh-connections.td
- test/testdrive/connection-create-external.td
Unfortunately there doesn't seem to be a way to add a `hint()` method to this error enum that would actually be used anywhere, since each of the `Connection` implementations that use this convert all errors to an `anyhow::Error` and hide the underlying type behind that opaque type. I tried to make the display message as informative as possible.
> Update netio dns error to be more informative

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/parallel_workload/executor.py
- misc/python/materialize/parallel_workload/parallel_workload.py
> parallel-workload: More logging to figure out #28983

- misc/python/materialize/cloudtest/k8s/redpanda.py
- misc/python/materialize/mzcompose/services/redpanda.py
- test/kafka-matrix/mzcompose.py
- test/kafka-resumption/mzcompose.py
Redpanda v24.2 includes a fix that allows our sinks to restart after a Redpanda broker failure without waiting out the full transaction timeout (often 10m+).
For details about the original issue and the fix in Redpanda, see:
* redpanda-data/redpanda#19889
* MaterializeInc/incidents-and-escalations#33
Fix MaterializeInc/incidents-and-escalations#33.
> test: upgrade to Redpanda v24.2.2

- src/sql/src/plan/query.rs
- test/sqllogictest/cte_lowering.slt
- test/sqllogictest/explain/view.slt
- test/sqllogictest/joins.slt
This resolves an old, minor todo in join planning: The old code used to start every join condition with `true AND`. Once I tried to get rid of this when I introduced variadic AND, but this would have regressed some plans at the time, due to some weird reasons. So, at that time I only added a todo. However, now I again tried removing this `true AND`, and fortunately we are no longer seeing regressions. It seems that the lowering and/or the optimizer became more robust in the meantime.
> Remove the `true and` from HIR join conditions

- misc/python/materialize/buildkite.py
> qa notifications: Use BUILDKITE_LABEL

- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
- src/controller/src/lib.rs
- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/read_holds.rs
The PR moves the compute controller from manually manipulating collection's `read_capabilities` to using `ReadHold` objects instead. The result of this is significantly simplified code, since the various places that maintain read holds are now immediately recognizable by grepping for uses of the `ReadHold` type, and downgrading a read hold is now a single method call, rather than a multi-line `ChangeSet` application. Another benefit is now that parts that need to keep read holds are no longer tightly coupled to the `Instance` state, as they don't need access to `Instance::update_read_capabilities` anymore. This, for example, opens up the opportunity to attempt to factor out the replication logic in a follow up.
Another cool thing is that for debugging frontier issues, we can now use the …
> compute: use `ReadHold` in the controller

- misc/python/materialize/output_consistency/data_type/data_type_with_values.py
- misc/python/materialize/output_consistency/data_value/data_value.py
- misc/python/materialize/output_consistency/expression/constant_expression.py
- misc/python/materialize/output_consistency/generators/expression_generator.py
- misc/python/materialize/output_consistency/generators/query_generator.py
- misc/python/materialize/output_consistency/input_data/constants/constant_expressions.py
- misc/python/materialize/output_consistency/input_data/operations/equality_operations_provider.py
- misc/python/materialize/output_consistency/output_consistency_test.py
- misc/python/materialize/output_consistency/query/query_template.py
- misc/python/materialize/output_consistency/runner/test_runner.py
This is a preparation for the join support to avoid that the other PR gets too large.
034e9dfb96 output consistency: expressions: add ConstantExpression
0789670391 output consistency: expressions: add TRUE, FALSE, and NULL
c35ac964fa output consistency: operations: extract equality operation
caff6f8463 output consistency: expression generator: add generate_leaf_expression
220b9194e0 output consistency: expression generator: add generate_equals_expression
25fab112e8 output consistency: expression generator: rename method
ec51ed884d output consistency: expression generator: add variants
c0e11fac16 output consistency: query: move where condition creation
287733bcd9 output consistency: query: remove unused code
7ed4de1c8d output consistency: data value: mark NULL value
> output consistency: minor extensions as preparation for join support

- src/compute-types/src/dataflows.rs
- src/compute/src/metrics.rs
- src/compute/src/server.rs
- test/cluster/mzcompose.py
This PR fixes a bug in compute reconciliation, which would reuse dataflows even when dataflows they were reading from had been replaced. This behavior was undesirable because the reused dataflows would keep discarded dataflows alive, and the installed dataflows wouldn't match the ones requested by the controller anymore.
To fix this we tweak the reconciliation logic to also replace dataflows that depend on replaced dataflows.
Fixes #28961
> compute: replace dependants of replaced dataflows

- misc/python/materialize/parallel_workload/action.py
- misc/python/materialize/parallel_workload/executor.py
- misc/python/materialize/parallel_workload/parallel_workload.py
> parallel-workload: Improve logging for 0dt

- ci/plugins/mzcompose/hooks/command
> ci: Prune older docker images

- ci/plugins/mzcompose/hooks/post-command
- misc/python/materialize/mzcompose/composition.py
Docker Compose is strange here, restore order
If this doesn't work, the cleaner solution is to use a proper logging driver: https://docs.docker.com/engine/logging/configure/
> ci: Fix services.log sorting

- misc/python/materialize/mzcompose/composition.py
We should wait forever, but then we don't get logs in CI
> 0dt tests: Bump timeout when waiting for status

- misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
Fix to better narrow expression characteristics.
> output consistency: expression matcher: limit characteristics to row selection

- bin/cut-release
- misc/python/materialize/git.py
- misc/python/materialize/release/auto_cut_release.py
- misc/python/materialize/release/cut_release.py
Add a script to the repository that automatically kicks off a new minor
release series by:
1. Tagging the .0 release.
2. Bumping the version on main to the next development version.
> release: add scripts for automatic weekly release cuts

- misc/python/materialize/cli/ci_annotate_errors.py
to find similar issues in previous CI runs quickly.
> ci-annotations: Link to CI Failures

- ci/test/build.py
- misc/python/materialize/mzbuild.py
- misc/python/materialize/spawn.py
> mzbuild: Also use run_with_retries

- ci/test/pipeline.template.yml
- test/mysql-cdc-resumption/mzcompose.py
One side was taking 35 min, the other 12 min: https://buildkite.com/materialize/test/builds/88321#019154ab-9c90-4ba7-add5-88686d89cd53
> mysql cdc resumption tests: Shard better

- ci/plugins/mzcompose/hooks/post-command
Should only respect the part after "|"
Example line:
```
parallel-workload-zookeeper-1  | 2024-08-15T00:40:05.757842411Z uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
```
> ci: Fix sorting

- test/pg-cdc/mzcompose.py
> pg-cdc tests: Disable silent-connection-drop workflow

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/mzcompose_actions.py
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/checks/scenarios_zero_downtime.py
Useful in general, might help with #29015
> platform-checks: Add 0dt restart scenario with forced migrations

- misc/python/materialize/parallel_workload/parallel_workload.py
> parallel-workload: Ignore unstopped threads in 0dt scenario

- misc/python/materialize/parallel_workload/action.py
> parallel-workload: Change issue number to track

- bin/pydoc
- ci/builder/requirements.txt
- misc/python/materialize/__init__.py
- misc/python/materialize/cargo.py
pdoc3 has broken parsing for multiple of our (valid) Python files. While checking how to fix that I found out that the there is a pdoc project as well, which works better and is less controversial: https://github.com/mitmproxy/pdoc?tab=readme-ov-file#pdoc-vs-pdoc3
Before:
After:
> python docs: Switch to pdoc

- ci/nightly/pipeline.template.yml
https://github.com/MaterializeInc/materialize/pull/28914 enabled structured data in Persist for all of CI, so this special Nightly run is no longer needed.
Remove unnecessary test
> ci: Delete unnecessary testdrive run

- misc/python/materialize/mzcompose/__init__.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-proc/src/lib.rs
Further validate the structured data in customer environments by writing some random small percentage of parts with both_v2. Doing this for all parts is probably too expensive, particularly on read where we'd ~double data volumes.
Then we'll turn on the row_with_validate to ensure that everything round-trips losslessly though the new format. We should be able to do this for 100% of parts that are written with both_v2, even in prod, because there will be a small number of them.
Touches #24830
> persist: build percentage based dyncfg for structured part rollout

- bin/pydoc
Failed: https://buildkite.com/materialize/deploy/builds/15531#0191566a-3c8a-486f-8f69-f39e2b2a8666
> RuntimeWarning: The default value of misc.python.materialize.mzcompose.DEFAULT_CLOUD_REGION matches the $AWS_DEFAULT_REGION environment variable. To prevent accidental leakage of secrets, the default value is not displayed. Disable this behavior by setting PDOC_DISPLAY_ENV_VARS=1 as an environment variable.
In this case harmless, since it's just us-east-1, but we might accidentally leak other variables, so that was a good call by pdoc!
Follow-up to https://github.com/MaterializeInc/materialize/pull/29021
> pydoc: Don't leak environment variables

- src/storage/src/source/generator.rs
The code was previously only using the main output of the loadgen source to decide where it can resume from but that is incorrect if the main output has progressed more than the subsources and can further lead to negative accumulations since some parts of the subsource outputs will be skipped.
> storage/loadgen: take all subsources into account for resume_upper

- ci/test/build.py
- misc/python/materialize/mzbuild.py
- misc/python/materialize/spawn.py
This reverts commit e8ff2349e3d2c72834f565cfbe9895c48a8ea590.
Seen failing materialize/rqg in https://buildkite.com/materialize/nightly/builds/9115#01915669-0a0a-452c-a746-1a44ed56b139
> Revert "mzbuild: Also use run_with_retries"

- .github/CODEOWNERS
Switching ownership of `doc/user` to the Docs team (which I'm also in)!
cc @kay-kim
> CODEOWNERS: s/morsapaes/docs

- doc/user/content/releases/v0.112.md
While we don't publish release notes anymore, for the time being, we still need a file in `doc/user/content/releases/` for each release that identifies the release date, patch no, and what date it was released. This file already exists for `v0.112`, so I just need to update that it's been released and the patch no.
> Mark v0.112.2 as released in the docs

- doc/user/content/sql/show-columns.md
This command does not apply to sinks.
> doc/user: remove sink mentions from `SHOW COLUMNS` page

- bin/ci-builder
- misc/python/materialize/release/auto_cut_release.py
To make the misc/python/materialize/release/auto_cut_release.py script work - needed to push up commits.
> Pass github user env vars into the ci-builder

- ci/plugins/mzcompose/hooks/command
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
Currently resource-constrained on Hetzner and these jobs often take a long time since there are so few of them, so chance of having an agent is low.
We have better pruning with https://github.com/MaterializeInc/i2/pull/2094 now
> ci: No pruning, switch x86-64 back to AWS

- misc/python/materialize/mzcompose/composition.py
Should fix issues where the yaml file is incompletely written, which apparently leads to errors like this:
$ docker compose up -d --scale default=0 default
no such service: default
Seen in https://buildkite.com/materialize/test/builds/88330#01915444-bfb1-494a-89a9-a172ed73347a
Happens more often with Hetzner, but totally timing dependent. I guess having faster disk/OS layer makes it more likely.
> mzcompose: Flush temporary yaml file

- misc/python/materialize/parallel_workload/action.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/29002
> parallel-workload: Fix toggling persist flags

- misc/python/materialize/cli/ci_annotate_errors.py
I somehow pushed a half-finished state before, oops
> ci-annotations: Fix links

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/scenarios.py
Similar motiviation to https://github.com/MaterializeInc/materialize/pull/29023
> ci: Remove unnecessary platform-checks run

- misc/python/materialize/cloudtest/k8s/redpanda.py
testdrive/github-26353.td:23:1: error: Admin operation error: InvalidPartitions (Broker: Invalid number of partitions)
Seen failing in https://buildkite.com/materialize/nightly/builds/9127#01915864-3592-4b6c-9bac-1d3b68bac1b0
Follow-up to https://github.com/MaterializeInc/materialize/pull/28968
> testdrive: Fix running in cloudtest

- ci/plugins/mzcompose/hooks/command
- misc/python/materialize/mzcompose/composition.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/29041
Verified that this is the cause by adding a sleep:
```diff
diff --git a/misc/python/materialize/cli/mzcompose.py b/misc/python/materialize/cli/mzcompose.py
index 3a2f5dbb81..a9cf23cc04 100644
--- a/misc/python/materialize/cli/mzcompose.py
+++ b/misc/python/materialize/cli/mzcompose.py
@@ -24,6 +24,7 @@ from __future__ import annotations
import argparse
import inspect
+import time
import json
import os
import shlex
@@ -319,6 +320,7 @@ class ListWorkflowsCommand(Command):
composition = load_composition(args)
for name in sorted(composition.workflows):
print(name)
+            time.sleep(10)
```
> ci: Real fix for `no such service: default`

- misc/python/materialize/output_consistency/input_data/operations/generic_operations_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
- misc/python/materialize/postgres_consistency/validation/pg_result_comparator.py
This addresses issues observed in https://buildkite.com/materialize/nightly/builds/9127#01915864-3615-4762-9fbd-d1037caeac05.
5065533482 output consistency: operations: improve definition
bf8c2efd94 postgres consistency: move ignore to also apply to operations
014277cbe9 postgres consistency: result comparator: extend timestamp pattern
> postgres consistency: adjust ignores

- bin/pydoc
Seen failing in https://buildkite.com/materialize/deploy/builds/15554#019159b8-354e-4fbb-9672-314a89816ea3
> pydoc: pyactivate requires MZ_DEV_CI_BUILDER env var

- misc/python/materialize/cli/ci_annotate_errors.py
> ci-annotate: Fix filters

- src/storage-types/src/sources.rs
Reduces the number of rows generated in the test to reduce flakiness
Fixes https://github.com/MaterializeInc/materialize/issues/29071
> persist: Reduce num rows in `arrow_datatype_consistent` test

- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- test/testdrive/session.td
Renames the unclear field of "internal" to "user_visible", flips existing values for internal, and marks all feature flags as "user_visible: false".
Slack convo: https://materializeinc.slack.com/archives/C0761MZ3QD9/p1723436590306659?thread_ts=1723258258.809039&cid=C0761MZ3QD9
> sql: Rename `internal` on `VarDefinition`, make feature flags always internal

- doc/user/content/_index.md
- doc/user/content/get-started/_index.md
- doc/user/content/get-started/quickstart.md
Changed Operational Data Warehouse to the Cloud Operational Data Store and copied blurb from homepage to be aligned.  Emily will get back to me if there is a preferred sentence, but figured I'd have the PR ready.
> docs: Update Materialize definition

- src/adapter/src/catalog/migrate.rs
- test/legacy-upgrade/create-in-v0.108.0-sources.td
There was a subtle bug in the migration in `v0.111` and `v0.112` that made an incorrect assumption about the format of the 'text columns' `UnresolvedItemName` stored on each Postgres `CREATE SOURCE` statement, such that we never ended up copying the relevant 'text columns' for Postgres sources to each `CREATE SUBSOURCE` statement:
https://github.com/MaterializeInc/materialize/blob/a8ac55c46319446b404ba12761f90992a226500d/src/adapter/src/catalog/migrate.rs#L491-L503
For postgres sources, the `UnresolvedItemName` is actually (database, schema, table, column).
This PR reintroduces a very similar migration that only applies to Postgres `CREATE SUBSOURCE` statements to fix the issue by copying the relevant text columns from the top-level source, again. Luckily we kept the text columns option …
> adapter/migrations: Fix previous migration bug on Postgres subsources with text-columns

- src/persist-client/src/internal/state.rs
- src/persist-client/src/stats.rs
- src/persist-types/src/codec_impls.rs
- src/persist-types/src/columnar.rs
- src/persist-types/src/part.rs
- src/persist-types/src/stats.rs
- src/persist-types/src/stats2.rs
- src/repr/benches/row.rs
- src/repr/src/row/encoding2.rs
- src/repr/src/stats2.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/stats.rs
- Clean up some now-unused incremental stats building methods.
- Add a new `stats()` method to `ColumnDecoder`, which calculates stats for already-written data. This is a more-or-less copy-and-paste of the encode-time stats.
- Switch batch write to use this new method. (This is particularly useful in the case of compaction, where we might never otherwise re-encode the user types.)
- Remove the now-unneeded encode-type stats. (This is optional, but nice to tidy up.)
For #24830: this allows us to collect stats without having to do a full decode-and-re-encode, which has been a big significant CPU burn in the past few months. (Though we'll still need to pay that cost until I land the structured-data support in compaction.)
Maybe it's surprising to put this as a method on `ColumnDecoder`? This …
> [persist] Allow stats collection on already-written arrays

- doc/user/content/sql/create-source/load-generator.md
- doc/user/layouts/partials/sql-grammar/create-source-load-generator.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/sql/src/session/vars/definitions.rs
- src/storage-types/src/sources/load_generator.proto
- src/storage-types/src/sources/load_generator.rs
- src/storage/src/source/generator.rs
- src/storage/src/source/generator/clock.rs
- test/testdrive/load-generator.td
Add a load generator that is periodically updated to reflect the current time.
```
materialize=> CREATE SOURCE clock FROM LOAD GENERATOR CLOCK (TICK INTERVAL '1s');
CREATE SOURCE
materialize=> select * from clock;
time      
---------------
1718817919000
(1 row)
materialize=> copy(subscribe to (select time::timestamp from clock)) to stdout;
1718817931178	1	2024-06-19 17:25:29
1718817932000	-1	2024-06-19 17:25:29
1718817932000	1	2024-06-19 17:25:30
1718817933000	1	2024-06-19 17:25:31
1718817933000	-1	2024-06-19 17:25:30
1718817934000	1	2024-06-19 17:25:32
1718817934000	-1	2024-06-19 17:25:31
1718817935000	1	2024-06-19 17:25:33
1718817935000	-1	2024-06-19 17:25:32
1718817936000	1	2024-06-19 17:25:34
1718817936000	-1	2024-06-19 17:25:33
```
Inspired by [this blog …
> [skunk] Add a CLOCK load generator

- src/adapter/src/catalog.rs
- src/transform/src/notice.rs
- src/transform/src/notice/index_already_exists.rs
- src/transform/src/notice/index_key_empty.rs
- src/transform/src/notice/index_too_wide_for_literal_constraints.rs
- test/sqllogictest/transform/notice/index_already_exists.slt
- test/sqllogictest/transform/notice/index_key_empty.slt
- test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt
We have a bug around dropping objects with optimization notices, where some notices seem to be leaking somehow (https://github.com/MaterializeInc/materialize/issues/24884). This is turning out to be very tough to debug. This PR just adds a bunch of tests, asserts, and debug info in the critical assert's msg.
> More asserts and tests and debug info around optimization notice dropping

- misc/python/materialize/version_list.py
Otherwise breaks 0d tests because of new restart behavior
Since https://github.com/MaterializeInc/materialize/pull/29025 did not make it into v0.113.1, but is in v0.113.0 and v0.113.2
See https://materializeinc.slack.com/archives/C01LKF361MZ/p1723843931523169
> tests: Mark v0.113.1 as a bad release

- ci/plugins/mzcompose/hooks/command
- ci/plugins/mzcompose/hooks/post-command
Panics in Rust cause SIGABRT, which creates coredumps If a test panic-loops this can take the entire disk space quickly
> ci: No coredump on panic

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/scalability/scalability_versioning.py
> ci: Switch benchmarks back to AWS for now

- test/testdrive/load-generator.td
Query execution can be slow in CI. Failed in https://buildkite.com/materialize/nightly/builds/9154
> testdrive: Fix flaky load-generator.td test

- ci/mkpipeline.py
- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
Makes https://github.com/MaterializeInc/i2/pull/2103 more efficient
> ci: Bump priority for agents with multiple queues

- misc/python/materialize/version_consistency/validation/version_consistency_error_message_normalizer.py
This addresses https://buildkite.com/materialize/nightly/builds/9154#01915d87-fc42-4e36-b85d-a7c6d6c8b760:
```
ValidationErrorType.ERROR_MISMATCH: Error message differs.
Expression: pow(log(generate_subscripts(multi_dim_text_array_two_elem, int2_max), uint4_max), list_length(list_agg(uint4_one)))
Value 1 (Constant folding v0.114.0-dev (e488dfc57)): 'column "table_func_f93e2875-e70a-42d3-9701-474f28806339" does not exist' (type: <class 'str'>)
Value 2 (Constant folding v0.113.2 (e9f403526)): 'column "table_func_8ab9ea9d-340c-45c2-967d-65118d6c979b" does not exist' (type: <class 'str'>)
```
> version consistency: normalize table function error messages

- ci/nightly/pipeline.template.yml
Should no longer be necessary since we filter SIGABRT coredumps out before writing them to disk
This reverts commit 3859540d5ab94d3def38ff0042082192b0db2959.
> Revert "ci: More disk for legacy upgrade test"

- doc/user/content/ingest-data/postgres/amazon-aurora.md
- doc/user/content/ingest-data/postgres/amazon-rds.md
- doc/user/content/ingest-data/postgres/neon.md
Hi - this PR adds a guide for setting up a Neon postgres database as ingestion source to Materialize. 
Please let me know if this needs more work.
(I work on technical content for Neon)
> doc/user: add ingestion guide for Neon Postgres

- misc/wasm/Cargo.lock
- misc/wasm/src/sql-lexer-wasm/Cargo.toml
- misc/wasm/src/sql-pretty-wasm/Cargo.toml
Bring our WASM crates up-to-date. The lol-allocator changes this brings in should slightly reduce the resultant bundle size.
I tested this by building the packages using: `bin/ci-builder run stable bin/pyactivate -m ci.deploy.npm --build-id 2 --no-release` and then linking them into a local version of Console via
```shell
yarn add @materializeinc/sql-lexer@portal:/path/to/materialize/misc/wasm/src/sql-lexer-wasm/pkg/
yarn add @materializeinc/sql-pretty@portal:/path/to/materialize/misc/wasm/src/sql-pretty-wasm/pkg/
```
This is fairly low-risk. We can further validate this after by upgrading Console to a dev version (which is published by CI/CD off `main`). If we see issues, we can either fix forward or roll back before the next stable trunk release is …
> wasm: upgrade WASM crate deps to latest versions

- src/adapter/src/coord.rs
This will help diagnose https://github.com/MaterializeInc/materialize/issues/29091.
> adapter: in dataflow bootstrapping, more context around mv asserts

- doc/user/content/sql/create-cluster.md
We recently stopped making a distinction between hydration and rehydration for anything user-facing.
> doc/user: minor patch to `CREATE CLUSTER` reference page

- src/postgres-util/BUILD.bazel
- src/postgres-util/build.rs
- src/postgres-util/src/lib.rs
- src/postgres-util/src/tunnel.proto
- src/postgres-util/src/tunnel.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/ddl/connection.rs
- src/sql/src/plan/statement/show.rs
- src/sql/src/pure.rs
- src/sql/src/session/vars/definitions.rs
- src/storage-types/build.rs
- src/storage-types/src/connections.proto
- src/storage-types/src/connections.rs
- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/postgres/snapshot.rs
Beyond the syntax level changes the underlying source machinery remains identical. The connection gained a `flavor` field that is used to track whether we should expect a PostgreSQL or Yugabyte server on the other side and is meant to be used by the actual operator to modify its behavior accordingly.
The new syntax is guarded by a feature flag that we can enable for everyone once all the pieces are in place.
> sql: add support for `YUGABYTE` connections and sources

- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/postgres/snapshot.rs
- test/pg-cdc/mzcompose.py
Implements https://github.com/MaterializeInc/materialize/issues/28435 for Postgres Sources
equivalent PR to the MySQL one: https://github.com/MaterializeInc/materialize/pull/28671
See the notes on the MySQL PR https://github.com/MaterializeInc/materialize/pull/28671 since they apply here too
-
> storage/sources: Handle SourceExports with the same external reference (oid) in Postgres sources

- src/storage/src/render/sinks.rs
- src/storage/src/sink/kafka.rs
- test/testdrive/kafka-sink-headers.td
Due to a bug in the initial implementation of the `HEADERS` option for Kafka sinks, we were not properly attaching headers to tombstones (i.e., messages with a `NULL` value).
The fix is to defer the final envelope encoding step until later in the sink pipeline, so that the code that determines what headers to apply can see the `before` value for tombstones.
This is a prerequisite to supporting custom partitioning (https://github.com/MaterializeInc/materialize/issues/28837).
* This PR fixes a previously unreported recognized bug.
The first two commits are pure refactoring, and the third is the actual behavior change. The diff may look scarier than the change actually is, so just shout if it'd be easier if I gave y'all a verbal explainer!
> storage/sinks/kafka: attach headers to tombstones

- src/transform/src/fusion/join.rs
- src/transform/tests/testdata/join-implementation
- test/sqllogictest/github-28174-29110.slt
This fixes the correctness issue https://github.com/MaterializeInc/materialize/issues/29110
Additionally to fixing the `inputs.len() == 0` case, it also improves the `inputs.len() == 1` case. This one didn't have a bug, but we can do more there.
Note that if equivalences is empty, then the added `.filter` call won't actually add a `Filter`, so there can't be any optimizer regression due to an extra `Filter` appearing.
I've put the test into an existing slt, where the setup is the same as for this one.
See an example showing how this actually looks in a real plan [here](https://github.com/MaterializeInc/materialize/issues/29110#issuecomment-2296818981).
* This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/issues/29110
> Fix join fusion when there are only constant singleton inputs

- src/adapter-types/src/compaction.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/consistency.rs
- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/read_policy.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/sequencer/inner/create_index.rs
- src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
- src/adapter/src/coord/timeline.rs
- src/adapter/src/coord/timestamp_selection.rs
- src/adapter/src/lib.rs
- src/adapter/tests/timestamp_selection.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
This PR moves the coordinator to use `ReadHold`s for taking read holds on storage/compute collections everywhere. This removes the need for separate read capability tracking that duplicates the logic already present in the controller, thus greatly simplifying the coordinator code dealing with read holds.
I've split the PR into digestible commits, recommend reviewing those separately!
> adapter: use controller `ReadHold`s everywhere

- ci/release-qualification/pipeline.template.yml
Seen in https://buildkite.com/materialize/release-qualification/builds/574#01915cd4-d7a1-433c-a7c2-b40b78911cfc
> ci: Smaller Zippy in release qualification

- misc/kind/cluster-node-recovery-test.yaml
- misc/kind/cluster.yaml
- src/cloud-resources/Cargo.toml
- src/orchestrator-kubernetes/Cargo.toml
- src/orchestrator-kubernetes/src/lib.rs
- src/workspace-hack/Cargo.toml
Bumps k8s-openapi feature to v1_29 and kind nodes to v1.29.7.
Update to match our production clusters.
Not a release blocker, but we will also follow up with bumping this in cloud.
No user-facing behavior changes.
> bump k8s-openapi feature to v1_29 and kind nodes to v1.29.7

- misc/python/materialize/mzcompose/__init__.py
For lower disk/memory usage, especially during long-running Zippy runs that went out of disk/memory. But should also make other tests a bit zippier. See discussion in https://materializeinc.slack.com/archives/CTESPM7FU/p1724161918033919?thread_ts=1724106368.546619&cid=CTESPM7FU
Follow-up to https://github.com/MaterializeInc/materialize/pull/28914
> ci: Decrease persist_batch_columnar_format_percent

- src/cluster/src/server.rs
- src/cluster/src/types.rs
- src/compute/src/server.rs
- src/storage/src/server.rs
- src/storage/src/storage_state.rs
Previously, the channel through which cluster workers would return dataflow activators to the tokio tasks managing client connections was a sync channel. When the connection tasks called `recv` on them, that call would synchronously block, stalling the current thread and even the entire tokio runtime if it was single-threaded.
The fix is to use an async channel instead.
> cluster: use async channel to return activators

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/connections.py
- misc/dbt-materialize/dbt/adapters/materialize/impl.py
- misc/dbt-materialize/dbt/adapters/materialize/relation.py
- misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
- misc/dbt-materialize/dbt/include/materialize/macros/materializations/seed.sql
- misc/dbt-materialize/dbt/include/materialize/macros/materializations/test.sql
- misc/dbt-materialize/dbt/include/materialize/macros/utils/generate_cluster_name.sql
- misc/dbt-materialize/tests/adapter/test_deploy.py
Seeds are broken in `dbt-materialize` in a couple of different ways:
* **Repeated runs:** when a user runs `dbt seed` for a non-existent object, the command succeeds, but on subsequent runs, the command might fail if the default cluster for the connecting user is either an invalid cluster or `mz_catalog_server` (from which it isn't possible to query user data). Under the hood, the adapter runs a `DELETE FROM` operation against the table ([source]()), which requires a valid cluster.
* **Full refreshes:** when a user runs `dbt seed` with the [`--full-refresh` flag](https://docs.getdbt.com/reference/resource-configs/full_refresh) (or the `full_refresh` configuration), dbt will try to drop the existing relation [(source)](https://github.com/dbt-labs/dbt-adapters/blob/f1987d4313cc94bac9906963df …
> dbt-materialize: fix `dbt seed` command

- Cargo.lock
- src/balancerd/Cargo.toml
- src/balancerd/tests/server.rs
- src/environmentd/tests/auth.rs
- src/environmentd/tests/server.rs
- src/frontegg-mock/src/lib.rs
Transferring over the last batch of endpoints from the Golang Frontegg mock service as per the discussion here: https://github.com/MaterializeInc/terraform-provider-materialize/issues/461
```
/identity/resources/users/api-tokens/v1" (GET)
/identity/resources/users/api-tokens/v1/{id}" (DELETE)
/identity/resources/tenants/api-tokens/v1" (GET, POST)
/identity/resources/tenants/api-tokens/v1/{id}" (DELETE)
```
> frontegg-mock: additional api token endpoints

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Release `dbt-materialize` v1.8.5. See `CHANGELOG.md` for an overview of the release.
> dbt-materialize: release v1.8.5

- ci/test/pipeline.template.yml
Let's see if this fixes it, I've been unable to reproduce the issue (or high memory consumption) locally.
Fixes: #29072
> cloudtest: Bump agent size

- doc/user/assets/sass/_layout.scss
- doc/user/layouts/partials/sidebar.html
- doc/user/static/images/icon_sidebar_expander.svg
- As an aside: In the future, may want to swap out the svg with something else, but for now, just incremental changes. 
- Got rid of the left hand grey border because if a nav item A is right below another nav item Z that contains children, the line can sometimes makes it A look like a child of Z.
> docs: make left-hand nav top-level items collapsible

- doc/user/content/sql/create-role.md
- Updated to mention that we don't support `Set Role` + clarify `INHERIT` is inherently on.  
- Refactored the content for readability. 
However, recognizing that, with the refactor, it's clear that the content is mostly a distinction between materialize's SET ROLE vs postgres.  But, definitely on the radar that we'll have to do a pass through the reference docs.
> docs: Update create-role sql page

- Cargo.lock
- ci/deploy/docker.py
- ci/deploy/npm.py
- ci/test/dev_tag.py
- doc/user/content/releases/v0.111.md
- misc/python/materialize/ci_util/__init__.py
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/docker.py
- misc/python/materialize/mz_version.py
- misc/python/materialize/mzcompose/services/materialized.py
- misc/python/materialize/release/auto_cut_release.py
- misc/python/materialize/scalability/regression_assessment.py
- misc/python/materialize/scalability/scalability_versioning.py
- misc/python/materialize/version_list.py
- src/balancerd/Cargo.toml
- src/catalog-debug/Cargo.toml
- src/catalog/src/durable/persist/tests.rs
- src/clusterd/Cargo.toml
- src/environmentd/Cargo.toml
- src/persist-client/Cargo.toml
- src/testdrive/Cargo.toml
- test/feature-benchmark/mzcompose.py
- test/testdrive/session.td
Historically, we've tagged Docker images for PRs and builds directly from main, respectively, like so:
devel-3d565dd11ba1224a41beb6a584215d99e6b3c576
unstable-3d565dd11ba1224a41beb6a584215d99e6b3c576
This makes it impossible for our cloud infrastructure to do version compatibility checks based on Docker tags alone.
This commit changes our prerelease tagging scheme to the following:
v0.114.0-dev.0--pr.g3d565dd11ba1224a41beb6a584215d99e6b3c576
v0.114.0-dev.0--main.g3d565dd11ba1224a41beb6a584215d99e6b3c576
The tags now include a SemVer version (v0.114.0-dev.0 in this case), followed by build metadata indicating whether the image was generated by a build for a PR or for main and the specific commit hash used for the build. We use `--` to separate the build metadata rather than the …
> ci: tag non-release Docker images with prerelease version

- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/operators/shard_source.rs
- src/persist-client/src/read.rs
I've continually put off on typing this PR up because I've been letting perfect be the enemy of the good. I'd really love to totally rework the BatchPartFetchMetrics, but in the meantime, what I have here plus prominent display in the persist dash would have led us to immediately diagnose at least 3 issues that otherwise took much longer to sus out.
> persist: add imperfect metric tracing unindexed persist_source reads

- misc/python/materialize/docker.py
Can happen when the same commit hash is built on main and in a PR
Seen in https://buildkite.com/materialize/test/builds/88880#019176bc-ff7d-45b8-80d7-ca0b7b29eeef
Related to https://github.com/MaterializeInc/materialize/pull/29097
> tests: Ignore multiple images for same commit hash

- src/expr/BUILD.bazel
- src/expr/build.rs
- src/expr/src/scalar.proto
- src/expr/src/scalar.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/format.proto
- src/expr/src/scalar/func/format.rs
- src/expr/src/scalar/func/impls/timestamp.rs
- test/sqllogictest/timestamp.slt
- test/sqllogictest/timestamptz.slt
This PR introduces unary `ToCharTimestamp` and `ToCharTimestampTz` variants that differ from their binary counterparts in that they have the format string already precompiled into a `DateTimeFormat`. This lets us skip the per-datum compilation in cases where the format string is statically known.
Closes #29068 
I'm pretty unfamiliar with the code I touched here. Definitely check my work!
Most of the diff is adding protobuf support for `DateTimeFormat`.
Should we do more to test this? AFAICT most/all of the `to_char` uses in tests already supply a static format, so it seems that test coverage should already be good for this change.
> expr: optimize `to_char` for static format

- src/transform/src/analysis/equivalences.rs
- src/transform/src/fusion/join.rs
- src/transform/tests/testdata/join-implementation
This fixes a minor regression introduced here: https://github.com/MaterializeInc/materialize/pull/29117#pullrequestreview-2246459785
> Make `unpack_equivalences` sort each equivalence class by expression complexity

- src/adapter/src/coord.rs
- src/adapter/src/coord/appends.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/metrics.rs
Dequeues batches of messages at a time when possible to amortize the cost
of calling into select. Not all components are able to provide batches of
messages, specifically the controller-ready response is message-at-a-time.
Workload: (The exact view definition is pretty irrelevant, just a leftover from a previous experiment.)
```
duration = 120s
[setup]
query=create materialized view if not exists test2 as select generate_series as x from generate_series(1, 100)
query=create view if not exists tempview1 as select * from test2 where x % 2 = 1
query=create default index on tempview1
[teardown]
query=drop materialized view test2 cascade
[loadtest]
query=select * from tempview1
concurrency=128
start=5s
```
Before:
```
2024/08/15 13:33:23 loadtest: 167229 transactions (1453.389 TPS), latency …
```
> coordinator: Dequeue batches of messages

- ci/test/pipeline.template.yml
- test/cloudtest/test_metrics.py
Since we run with faster CI machines now
> cloudtest: Disable test_replica_metrics and reduce parallelism

- src/adapter/src/client.rs
- src/adapter/src/config/backend.rs
- src/adapter/src/coord/validity.rs
- src/adapter/src/session.rs
- src/balancerd/src/lib.rs
- src/environmentd/src/http.rs
- src/pgwire/src/protocol.rs
- src/pgwire/src/server.rs
- src/server-core/src/lib.rs
Use the connection UUID added in 3b42b8ec3, which tracks connections across balancerd and environmentd processes, as the session UUID. Then show the session UUID in the welcome message.
This will make it easier to correlate particular connections with their environmentd and balancerd logs.
* This PR works towards fixing a recognized bug.
> adapter,pgwire: use conn UUID as session UUID; display in welcome message

- src/orchestrator-tracing/src/lib.rs
It's almost never what you want. What you want instead if `--system-parameter-default=log_filter=<filter>`.
* This PR improves documentation.
> orchestrator-tracing: warn people off of startup-log-filter arg

- src/compute-client/src/controller/instance.rs
- src/compute-client/src/metrics.rs
This PR replaces the experimental `mz_dataflow_wallclock_lag_metric` with three alternative experimental metrics that expose per-minute min/max/avg aggregations of observed wallclock lag.
The assumption is that these aggregations are more useful than a low-res histogram because (a) they allow us to see precise maximum values, rather than ranges and (b) they provide insight into lag values above 30s. We lose the ability to inspect sub-minute lag distribution, but this ability didn't turn out to be particularly useful for judging cluster health.
Part of #28097 
This is an attempt of validating the min/max/avg format before we consider exposing it to users.
I decided to have three metrics, rather than a single one with an `aggregation = …
> compute: min/max/avg wallclock lag

- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/message_handler.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/sql/src/pure/mysql.rs
- src/sql/src/pure/postgres.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/sources/mysql.proto
- src/storage-types/src/sources/postgres.proto
- test/testdrive/source-tables.td
Fixes https://github.com/MaterializeInc/materialize/issues/28942
Best reviewed commit-by-commit, since the second commit is just refactoring existing subsource purification code so it can be reused.
Since planning is still not implemented for these statements (will be in the [next PR](https://github.com/MaterializeInc/materialize/pull/28954)) I'm not able to add any tests here. So this temporarily adds a chunk of uncovered code as a tradeoff for smaller review sizes, but feel free to push back if you disagree.
> storage/sources: Implement purification for CREATE TABLE .. FROM SOURCE statements

- ci/mkpipeline.sh
- test/tracing/mzcompose.py
Some more money saving, runs fast.
> ci: Switch mkpipeline to Hetzner

- bin/pre-push
As requested in https://materializeinc.slack.com/archives/C01LKF361MZ/p1724333103274449
> bin/pre-push: Add bin/doc --document-private-items

- test/cloud-canary/mzcompose.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9212#01917600-be47-4b38-9e47-99a35fe152a9
Follow-up to https://github.com/MaterializeInc/materialize/pull/29097
> cloud-canary: Adapt to new version format

- ci/nightly/pipeline.template.yml
- misc/python/materialize/parallel_workload/action.py
- src/persist-proc/src/lib.rs
This PR adds the `persist_encoding_enable_dictionary` flag to a few CI builds to get coverage on it.
Get CI coverage so we're comfortable testing it more broadly
> persist: Enable dictionary encoding for some CI builds

- src/persist-client/src/cli/bench.rs
It was computing the start time once, instead of once-per-iter.
While I'm in here, update the "decode" naming to "parse" to match what I'm trying to establish as the jargon: fetch (s3 -> bytes), parse (bytes -> arrow), decode (arrow -> row).
> persist: fix bug in `persistcli bench s3-fetch`

- src/balancerd/BUILD.bazel
- src/catalog-debug/BUILD.bazel
- src/clusterd/BUILD.bazel
- src/environmentd/BUILD.bazel
- src/persist-client/BUILD.bazel
- src/testdrive/BUILD.bazel
- test/legacy-upgrade/mzcompose.py
Seen in https://buildkite.com/materialize/test/builds/88980#01917bb5-6a3f-49c8-b6a3-886f4a00ef4a
I think the release script has to be adapted to run `bin/bazel gen`, I'll try to find where that happens. Edit: https://github.com/MaterializeInc/materialize/pull/29190
> Fix bazel files for v0.115.0

- src/balancerd/BUILD.bazel
- src/catalog-debug/BUILD.bazel
- src/clusterd/BUILD.bazel
- src/environmentd/BUILD.bazel
- src/persist-client/BUILD.bazel
- src/testdrive/BUILD.bazel
- test/legacy-upgrade/mzcompose.py
Seen failing in https://buildkite.com/materialize/test/builds/88984#01917be2-4686-42af-8a7e-289a904efdd2
> legacy-upgrade-materialized-1     | environmentd: fatal: incompatible persist version 0.115.0-dev.0, current: 0.114.0, make sure to upgrade the catalog one version forward at a time
> legacy-upgrade-materialized-1     | thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:604:9: environmentd: fatal: incompatible persist version 0.115.0-dev.0, current: 0.114.0, make sure to upgrade the catalog one version forward at a time
> legacy-upgrade test: Don't bring up old Mz

- Cargo.lock
- src/storage-types/Cargo.toml
- src/storage-types/src/errors.rs
- src/storage/src/decode.rs
- test/testdrive/avro-decode-mismatched-columns.td
- test/testdrive/avro-decode.td
- test/testdrive/kafka-upsert-sources.td
- test/testdrive/protobuf-corrupted.td
- test/testdrive/protobuf-evolution.td
- test/testdrive/protobuf-import.td
- test/testdrive/source-format-json.td
Our previous error message would include the string that failed to decode but hide the actual error message.
We also probably can get rid of the `DecodeErrorKind` enum at some point, since there is no functional difference in `DecodeErrorKind::Bytes` and `DecodeErrorKind::Text` anywhere I can see
> Improve error message for json source decoding failures

- bin/bump-version
- misc/python/materialize/cli/ci_annotate_errors.py
Would have prevented https://github.com/MaterializeInc/materialize/pull/29189
> release process: Automatically generate bazel files

- ci/plugins/mzcompose/hooks/post-command
I'm in talks with Buildkite, there are elevated "502 Bad Gateway" errors. Example failure: https://buildkite.com/materialize/release-qualification/builds/576#01917bd4-02e2-45db-80d0-2e22054de2fc
> ci: Workaround for current timeouts during services.log upload

- ci/test/pipeline.template.yml
- test/cloudtest/test_secrets.py
> cloudtest: Disable flaky test_missing_secrets

- test/cloud-canary/mzcompose.py
https://github.com/MaterializeInc/materialize/pull/29177 didn't work
> cloud-canary: Second fix attempt

- ci/nightly/pipeline.template.yml
Since https://github.com/MaterializeInc/materialize/issues/27954 will take a while to get fixed and we have no good way of silencing the failures in CI (panic + test failure)
> ci: Disable RQG simple-aggregates

- misc/python/materialize/cli/ci_annotate_errors.py
Until we have a better solution, so devs are not confused by hundreds of panics.
> ci: Ignore 0dt catalog forward panic

- bin/bump-version
- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/actions.py
- misc/python/materialize/checks/scenarios_zero_downtime.py
Helps finding issues like https://github.com/MaterializeInc/materialize/issues/29199 earlier.
Works: https://buildkite.com/materialize/nightly/builds/9232
> platform-checks: Add ZeroDowntimeBumpedVersion scenario

- misc/python/materialize/cli/ci_closed_issues_detect.py
As suggested in https://materializeinc.slack.com/archives/CPNFV9CVB/p1724433400504749?thread_ts=1724429667.230919&cid=CPNFV9CVB
> ci: Detect further doc references to issues

- WORKSPACE
- bin/bazel-temp
- misc/bazel/git_submodules/BUILD.bazel
- misc/bazel/git_submodules/BUILD.fivetran_sdk.bazel
- src/build-tools/src/lib.rs
- src/fivetran-destination/BUILD.bazel
- src/fivetran-destination/Cargo.toml
- src/fivetran-destination/build.rs
- src/testdrive/BUILD.bazel
- src/testdrive/Cargo.toml
- src/testdrive/build.rs
This PR adds the `fivetran-sdk` submodule as a Bazel repository which is necessary to access the protobuf files from the submodule. Doing this allows us to build the crates that depend on these protos, namely the `fivetran-destination` and `testdrive`.
Progress towards https://github.com/MaterializeInc/materialize/issues/26796
> bazel: Support building the `fivetran-destination` and `testdrive`

- Cargo.lock
- src/repr/Cargo.toml
As it says on the tin
Fix nightlies
> tests: Nightly fix unused deps

- ci/release-qualification/pipeline.template.yml
Based on results in https://buildkite.com/materialize/release-qualification/builds/576
> ci: Reduce scale for release qualification

- bin/cloud-push
Rather than using a random tag, use a tag that includes the current version from Cargo.toml. That way, the cloud orchestration layer will be able to understand precisely what features (e.g., CLI arguments) this custom build supports.
(Of course, if the custom build adds *new* features that are meant to be understood by the cloud orchestration layer, that will require bumping the version in Cargo.toml; that's fundamental to this approach of using prerelease versions to gate features that impact the cloud orchestration layer, though.)
This will make the cloud version detection logic (https://github.com/MaterializeInc/cloud/pull/9978) work better  when someone is using `bin/cloud-push` to push up custom images to staging.
> bin/cloud-push: use proper prerelease versions

- misc/python/materialize/release/util.py
Introduced in ea49fa32411cdf0afd1f803f38a53bdc8df5e4d9
Seen in https://buildkite.com/materialize/test/builds/89108#019187f5-9456-41fd-bcf3-a5acdadcd7fa
> Fix lint for release/util.py

- doc/user/content/ingest-data/postgres/amazon-aurora.md
- doc/user/content/ingest-data/postgres/amazon-rds.md
- doc/user/content/ingest-data/postgres/self-hosted.md
- doc/user/content/ingest-data/redpanda-cloud.md
- doc/user/layouts/shortcodes/network-security/privatelink-kafka.md
- doc/user/layouts/shortcodes/network-security/privatelink-postgres.md
> docs: SELECT principal only returns principal

- src/adapter/src/catalog.rs
- src/adapter/src/coord/message_handler.rs
- src/catalog/src/durable.rs
Previously, when collection n storage usage events, we'd perform n catalog transactions to allocate an ID for each event. This commit optimizes the code by performing a single transaction to allocate n IDs.
> adapter: Improve storage usage collection perf

- src/persist-client/src/internal/apply.rs
- src/persist-client/src/internal/metrics.rs
Discovered this hole in our persist introspection while debugging an increase in the number of consensus_scan calls in the latest release candidate.
> persist: add metrics tracking fetch_upper calls

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/comparator.py
- misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
- misc/python/materialize/test_analytics/setup/tables/10-feature-benchmark.sql
Not to be used as regression markers but for us to continuously monitor performance and find interesting trends
> feature-benchmark: Record min/max/mean/variance of wallclock

- src/compute-client/src/metrics.rs
- src/ore/src/stats.rs
This PR moves the `MinMax` type supporting the compute controller metrics into the mz-ore crate, as it might be generally useful. The type is also renamed to `SlidingMinMax` to make its purpose more obvious outside the a metrics context.
> Move `MinMax` type into mz-ore

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/open/builtin_item_migration.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/error.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/persist/tests.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/tests/debug.rs
- src/catalog/tests/open.rs
- src/catalog/tests/read-write.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
Previously, the durable catalog could be fenced by one of the
following ways:
- It tried to listen to the durable catalog and saw a higher epoch.
- It tried to listen to the durable catalog and saw a higher binary
version.
- It tried to write to the durable catalog and had an upper
mismatch.
- It tried to write to the catalog migration shard and had an upper
mismatch.
These would either result in a non-descriptive
`DurableCatalogError::Fence` error or a
`DurableCatalogError::IncompatiblePersistVersion` error. Additionally,
if multiple of these conditions happened at the same time, it was
non-deterministic which error would be returned.
This commit modifies the conditions for when the durable catalog can be
fenced to the following conditions:
- It tried to listen to the durable catalog and …
> catalog: Improve fencing

- src/adapter/src/coord/message_handler.rs
The variable changed in this PR is supposed to track the shortest wait needed for the time to advance to the time of the timestamp oracle. It is updated as part of processing the list of requests by continually adjusting it via `shortest_wait = min(shortest_wait, wait)`. Unfortunately since the value was initialized at the minimum value (instead of the MAX) this code would always calculate a duration of zero, and therefore if it somehow triggered the database would spin as fast as possible generating requests for linearization which in some tests would take minutes to clear, all while being totally unresponsive.
The fix is to initialize the variable to the maximum duration.
> adapter: correctly calculate the minimum wait time

- src/persist-client/src/cfg.rs
- src/persist-client/src/lib.rs
- src/repr/src/row.rs
This PR does two things:
1. Allows pushing `Datum::Null` onto Codec Row data when columns are missing
2. Gates Persist schema evolution, specifically `compare_and_evolve_schema`, behind a scary dyncfg.
We should _**never**_ enable this dyncfg in staging or prod until compaction can handle data that is written in different schemas, but I'm putting it up because it helps me test `ALTER TABLE` end-to-end. @danhhz and I chatted about this [here](https://materializeinc.slack.com/archives/C03P1EGB7A7/p1724710976316039?thread_ts=1724709020.644259&cid=C03P1EGB7A7)
Small progress towards `ALTER TABLE`
> persist: Allow appending Datum::Null to Codec Row data

- misc/python/materialize/parallel_workload/action.py
- src/persist-client/build.rs
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/cli/inspect.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/datadriven.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/state.proto
- src/persist-client/src/internal/state.rs
- src/persist-client/src/internal/state_diff.rs
- src/persist-client/src/internal/state_serde.json
- src/persist-client/src/internal/trace.rs
- src/persist-client/src/internals_bench.rs
- src/persist-client/src/read.rs
- src/persist-client/src/write.rs
- src/persist-proc/src/lib.rs
- src/proto/src/lib.rs
- test/persistence/mzcompose.py
We'd like to store the ordering metadata for #23942.
This is logically a run-level thing, and we've hit a couple cases recently where we similarly wanted run-level metadata; this gives us a way to store that. I've added the schema id for now, since that may also be relevant to my work soon, but we can imagine migrating a few other things there.
Nightlies: https://buildkite.com/materialize/nightly/builds/9221
Pulled out of my larger ordering PR in the hopes of landing for this week's release; let me know if you'd like any additional context.
> [persist] Store run-level metadata in hollow batches, including order

- src/persist-client/src/batch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-types/src/lib.rs
- src/repr/src/row/encoding.rs
- src/storage-types/src/sources.rs
- src/storage/src/source/reclock.rs
This doesn't seem to be happening on the original data write path,
thankfully. However, last week I did end up finding and fixing one known
and one unknown spot where a placeholder schema `RelationDesc::empty`
was used for an empty CaA, which resulted in compaction work being
spawned with the wrong schema. Given that correct schemas are about to
become necessary with the columnar batch work, this will hopefully
prevent regressions.
It's probably too expensive to do this in prod, but seems like a good
idea to catch if any schema shenanigans are happening in CI.
Touches #24830
I think there's a couple of mis-uses in reclocking unit tests that I'll fix up once CI finds them again for me.
-
> persist: validate that schemas match values in batch construction in CI

- bin/ci-builder
- misc/python/materialize/redpanda_cloud.py
- test/cloud-canary/canary-kafka-sources.td
- test/cloud-canary/canary-redpanda-privatelink-sources.td
- test/cloud-canary/canary-redpanda-sources.td
- test/cloud-canary/mzcompose.py
Fixes: https://github.com/MaterializeInc/cloud/issues/9721
Nightly run: https://buildkite.com/materialize/nightly/builds/9274
> canary-cloud: Use Redpanda Cloud

- src/compute/src/server.rs
- src/storage/src/storage_state.rs
If the `ClusterClient` shuts down before it has accepted the Timely activator, the Timely worker will fail to send the activator through the `activator_tx`. Handle such send failures gracefully, rather than panicking.
Fixes #29241
> cluster: don't panic on activator_tx send failure

- src/pgwire/src/protocol.rs
- test/lang/js/params.test.ts
See comment within for justification.
In particular, this fixes a hang when using Node.js's pg-query-stream library with Materialize to submit a query that experiences an error, either during the parsing, planning, or execution phase of the query.
Plausibly related to MaterializeInc/incidents-and-escalations#92.
> pgwire: eagerly flush after writing an error

- src/adapter/src/metrics.rs
Add all default buckets for capturing the coordinator message handling duration histogram. At the moment, we only distinguish values starting from 128ms, which means that we cannot observe durations below this value. However, since all of these are blocking, even smaller durations contribute to client-observed latency, so we should be able to attribute which commands cause observable latency.
Fixes #29236.
> More buckets for coordinator message handling

- ci/test/pipeline.template.yml
This should make it such that we capture `bazel-explain.log` as a build artifact which will help us debug builds in CI.
Note: Soon we'll turn off explains by default because it seems to contribute to non-trivial amount of time to the build
Progress towards https://github.com/MaterializeInc/materialize/issues/26796
> bazel: capture `bazel-explain.log` as a build artifact

- src/catalog/src/durable/error.rs
- src/catalog/src/durable/persist.rs
- src/catalog/tests/debug.rs
- src/catalog/tests/open.rs
- src/environmentd/src/deployment/preflight.rs
da7c2af16a3ad1a1a7454ea4ecc2eb55e645dc89 incorrectly asserted that the catalog debug tool does not fence out other writers when performing writes. The catalog debug tool does in face increment the epoch on every write, fencing out all other catalogs.
As a result, it's not possible for a process to write to the catalog without also fencing out all other catalog processes. Therefore, whenever a process encounters an upper mismatch error on write, there is always a more descriptive fencing error that could be returned.
This commit removes the `FenceError:Upper` variant and returns a more
descriptive error instead. Additionally, it adds some tests to validate
this behavior.
> catalog: Remove upper fence error

- src/adapter/src/coord/statement_logging.rs
- src/adapter/src/metrics.rs
This PR adds the `mz_statement_logging_record_count` prometheus metric to track the total number of statements we record in the recent activity log, and whether or not that statement was actually sampled.
Chatted about this in the incident response working group, if we change the sampling rate for a user we want a more concrete way to see that the change took effect.
> adapter: add `mz_statement_logging_record_count` metric

- .github/workflows/slack_notify_sql_parser.yml
As it says on the tin, filters out `BUILD.bazel` and `Cargo.toml` files from the change detection.
Cut down on noise for the SQL council.
> sql_council: Filter out build files for Slack notifier

- .bazelrc
After experiments with @danhhz these are the tweaks we needed to get remote caching working.
* Always set `-mmacosx-version-min` C flag
* Comment out bazel explains for now. This one wasn't actually needed but is something I've been meaning to do
Progress towards https://github.com/MaterializeInc/materialize/issues/26796
> bazel: tweak `.bazelrc` for better remote caching

- src/frontegg-mock/tests/local.rs
Seen failing in https://buildkite.com/materialize/nightly/builds/9287#_
> ci: Disable frontegg-mock tests in miri

- test/cloud-canary/canary-redpanda-privatelink-sources.td
Seen failing in https://buildkite.com/materialize/nightly/builds/9303
@bobbyiliev @jubrad Do you know if this is expected not to work immediately? If not, I'll open an issue
> canary cloud test: Increase sleep before creating privatelink source

- ci/test/cargo-test/mzcompose.py
- ci/test/coverage_report.sh
- misc/python/materialize/mzcompose/composition.py
- test/cluster/mzcompose.py
- test/sqllogictest/updates.slt
Seen failing in https://buildkite.com/materialize/coverage/builds/438
> ci: Minor coverage fixes

- src/adapter/src/catalog.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/persist/tests.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/src/durable/upgrade.rs
- src/catalog/tests/debug.rs
- src/catalog/tests/open.rs
- src/catalog/tests/read-write.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
This commit removes some necessary arguments from catalog methods.
> catalog: Clean up method args

- src/persist-client/src/batch.rs
- src/persist-client/src/stats.rs
- src/persist-proc/src/lib.rs
- src/persist-types/src/codec_impls.rs
- src/persist-types/src/columnar.rs
- src/persist-types/src/stats.rs
- src/repr/src/row/encoding2.rs
- src/repr/src/stats.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/stats.rs
`encode_updates` returned an `Err` if either it was unable to encode the data into structured arrow data OR if it was unable to turn the stats into a non-nullable `StructStats`. It turns out that all persist unit tests were returning an unexpected stats type, and so we essentially had much less test coverage than we thought. We were logging an `error!` (thankfully, it doesn't seem to be showing up in sentry), but this wasn't loud enough that we noticed until now.
So, replace the error log with a `soft_assert_or_log!` so that tests (and CI) fail loudly when something unexpected happens. Then fix the new failures :). We could make non-struct stats roundtrip, but it'd be Work and Code and unused in production, so instead require `ColumnDecoder` implementations to figure out how to map …
> persist: fix bug where non-struct stats caused us to skip columnar data

- src/adapter/src/catalog/open.rs
- src/catalog/src/builtin.rs
- src/catalog/src/builtin/notice.rs
- src/catalog/src/durable/objects/state_update.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/upgrade/tests.rs
- src/compute-client/src/logging.rs
- src/interchange/src/avro.rs
- src/repr/src/lib.rs
- src/repr/src/relation.rs
- src/repr/src/relation_and_scalar.proto
- src/repr/src/row/encoding.rs
- src/repr/src/row/encoding2.rs
- src/repr/src/stats.rs
- src/sql/src/catalog.rs
- src/sql/src/plan/side_effecting_func.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/plan/statement/scl.rs
- src/sql/src/plan/statement/show.rs
- src/storage-client/src/healthcheck.rs
- src/storage-client/src/statistics.rs
- src/storage-types/src/controller.rs
- src/storage-types/src/sources/encoding.rs
- src/storage-types/src/sources/kafka.rs
- src/storage-types/src/sources/load_generator.rs
- src/storage-types/src/sources/mysql.rs
- src/storage-types/src/sources/postgres.rs
- src/storage-types/src/stats.rs
- src/storage/src/source/reclock.rs
- src/testdrive/src/action/persist.rs
This PR refactors `RelationDesc` to support adding columns to tables, it does a few things:
1. Creates a `RelationDescBuilder` and moves a few methods, namely `with_column(...)` onto the new builder. The goal here was to disambiguate adding a column to a new version of the `RelationDesc` and the initial construction of a `RelationDesc`.
2. Refactors the internals of `RelationDesc` from a `Vec<ColumnName>` to a `BTreeMap<ColumnIndex, ColumnMetadata>`. There are two primary things this enables:
1. Stable tracking of column positions with `ColumnIndex`
2. `ColumnMetadata` tracks the version at which a column was added and optionally dropped.
Progress towards https://github.com/MaterializeInc/materialize/issues/28082
These changes are split into two separate commits:
1. Adding …
> adapter: Refactor `RelationDesc`

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
- src/catalog-debug/src/main.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
This PR adjusts the 0dt hydration check to exclude newly created builtin objects. These objects are sometimes not able to hydrate because neither the old nor the new environment is writing to them. Excluding them from the check is fine: Clients connected to the old environment don't know of their existence, so no downtime is induced when they are not immediately hydrated after the cutover.
I've rebased https://github.com/MaterializeInc/materialize/pull/29254 on top of this PR, to verify that this indeed fixes the problem with failing 0dt upgrades when there is are new builtin objects.
The 0dt checks in CI fail on PRs that introduce a new indexed `BuiltinSource`.
[See Slack thread.](https://materializeinc.slack.com/archives/C071VTZS1M5/p172485562 …
> adapter,controller: exclude new builtins from hydration check

- src/catalog/src/durable/persist/tests.rs
- src/catalog/tests/open.rs
Previously, a lot of catalog tests had copy and pasted `NOW_ZERO()` as
the clock and a comment explaining why we were using that clock. The
comment is not actually valid for the majority of the tests, so this
commit removes the comment and switches to `SYSTEM_CLOCK()` which is
what the catalog uses in production.
> catalog: Clean up some tests

- ci/nightly/pipeline.template.yml
Somehow not very consistent, timed out in https://buildkite.com/materialize/nightly/builds/9306#01919de7-58c1-47cd-a682-3b07d6f8e297
> ci: Bump platform checks runtimes

- src/adapter/src/optimize.rs
- src/compute-types/src/plan/reduce.rs
- src/compute/src/render/reduce.rs
- src/expr/src/relation.proto
- src/expr/src/relation.rs
- src/expr/src/relation/func.rs
- src/expr/src/scalar/func/impls/record.rs
- src/repr/src/optimize.rs
- src/repr/src/scalar.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/statement.rs
- src/sql/src/plan/expr.rs
- src/sql/src/plan/lowering.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/plan/transform_expr.rs
- src/sql/src/session/vars/definitions.rs
- test/sqllogictest/window_funcs.slt
This adds the fusion optimization for value window functions (`lag`, `lead`, `first_value`, `last_value`), which is badly needed by https://github.com/MaterializeInc/accounts/issues/3
The point is that it amortizes the various overheads of window functions (e.g., the wrapping/unwrapping of other columns, which gets quadratically big with the number of window functions) by performing the MIR window function pattern only once for a group of window functions.
I've added this as an HIR transform, because an MIR transform would have needed to recognize and manipulate the complicated MIR window function pattern.
See the doc comment on `fuse_window_functions` for how we choose the groups of window functions to be fused.
I've added a new value window function called `Fused`, and implemented the …
> Window function fusion

- src/expr/src/relation/func.rs
- test/sqllogictest/window_funcs.slt
Fixes https://github.com/MaterializeInc/materialize/issues/29243
Look at the commits separately:
1. Fixes a bug with negative offsets.
2. lag/lead IGNORE NULLS: panic on 0 offset instead of an infinite loop. Started a Council thread on what should actually be the result for this: https://materializeinc.slack.com/archives/C063H5S7NKE/p1724962369706729 In the meantime, panicking is better than freezing.
3. Split IGNORE NULLS true/false code paths into separate functions. This is a preparation before making the IGNORE NULLS case more complicated.
4. Refactor to step over a run of nulls in an isolated loop. This is another preparatory step for the main commit, which will eliminate this loop.
5. The main commit: step over a run of nulls in constant time. This unblocks …
> Fix ignore nulls performance problem with long runs of nulls

- ci/plugins/cloudtest/hooks/post-command
- ci/plugins/cloudtest/hooks/pre-exit
- ci/plugins/mzcompose/hooks/pre-exit
This stopped working anyway:
> /var/lib/buildkite-agent/builds/hetzner-aarch64-4cpu-8gb-e32bf9b3/materialize/coverage/ci/plugins/mzcompose/hooks/pre-exit: line 19: kill: 2813 2789: arguments must be process or job IDs
We have more reliable methods of regaining disk space. Reverts https://github.com/MaterializeInc/materialize/pull/22131
> ci: Don't terminate buildkite-agent after failed job

- ci/test/pipeline.template.yml
> ci: Bump agent size for RTR with all sources test

- src/repr/src/relation.rs
Seen in https://buildkite.com/materialize/nightly/builds/9315#01919f30-925b-428b-b112-56a530b8ab91
Caused by https://github.com/MaterializeInc/materialize/pull/29231
> miri test: Disable tests not supported anymore

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
Seen in https://buildkite.com/materialize/nightly/builds/9322#0191a02e-85c1-4bb2-b014-9e14158714e5
> feature-benchmark: Fix comparison

- misc/python/materialize/cli/ci_annotate_errors.py
Trim them instead, timeouts seen today in multi-MB log lines
> ci: Don't match regex on huge error lines

- src/buf.yaml
- src/storage-types/src/sinks.proto
- src/storage-types/src/sources.proto
- src/storage-types/src/sources.rs
- src/storage-types/src/sources/kafka.proto
- src/storage-types/src/sources/kafka.rs
- src/storage/src/source/kafka.rs
* This PR adds a known-desirable feature. Fixes https://github.com/MaterializeInc/materialize/issues/29209
Note that this PR just enables the kafka source to output it's raw data to multiple source export streams. The work beyond this PR will allow us to modify encoding and envelope's on a per-source-export basis:  https://github.com/MaterializeInc/materialize/issues/29225
> storage/sources: Allow kafka sources to export to multiple source exports

- src/expr/src/relation/func.rs
- test/sqllogictest/window_funcs.slt
This addresses review comments from https://github.com/MaterializeInc/materialize/pull/29287, and adds more slt tests.
> `lag`/`lead` `IGNORE NULLS` refactoring and more tests

- doc/user/layouts/shortcodes/version.html
The version shortcode was outdated. Teach it to filter to only published releases, and to stitch in the patch field if set.
> doc/user: fix version shortcode

- doc/user/content/get-started/install-materialize-emulator.md
Can put back with https://github.com/MaterializeInc/materialize/pull/29305 fix. (had accidentally squashed the patches together, so couldn't just do a revert).
> docs: revert removal of image version

- misc/python/materialize/cli/ci_annotate_errors.py
Does not fix, but works around #24088
So that we can at least ignore known panics relatively reliably and don't fail tests for them.
> ci: Handle panics and logging interleaving

- src/adapter/src/coord.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
This commit speeds up the startup process by fetching snapshots of all builtin tables in parallel instead of sequentially.
Works towards resolving #28722
> adapter: Fetch table snapshots in parallel

- bin/ci-builder
- ci/builder/Dockerfile
This was broken in https://github.com/MaterializeInc/materialize/pull/28370
But we didn't notice because the bazel files touched didn't cause a rebuild of ci-builder, so fixing that too. @ParkMyCar Are these the correct files to monitor or do we need more?
Seen failing in https://buildkite.com/materialize/test/builds/89528
> bazel: Fix checksums

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9339
> feature-benchmark: Fix variance calculation

- misc/python/materialize/cli/ci_annotate_errors.py
Seen in https://buildkite.com/materialize/nightly/builds/9341#0191a459-8f0a-4e20-b147-66dc0f86756f
We can only actually remove the ignore when version X-4 has the fix.
> ci: Remove issue reference for catalog fatals

- src/compute-client/src/controller/sequential_hydration.rs
> progress record fetch (60s) less than transaction timeout (600s), defaulting to transaction timeout 600s
Responsible for 60k events in the last 30 days: https://materializeinc.sentry.io/issues/5512940900/
> error on receive
Responsible for 7k events: https://materializeinc.sentry.io/issues/5706103329/
If something more seriously is wrong, or this is a user setup problem, we should fix it there instead.
> cluster: Remove unnecessary errors

- src/adapter/src/coord.rs
- src/compute-client/src/as_of_selection.rs
- src/compute-client/src/lib.rs
This PR is a refactor of the as-of bootstrapping process. Currently that logic resides in the coordinator and is split between two methods, `collect_dataflow_storage_constraints` and `bootstrap_dataflow_as_of`, and has some issues:
* It's hard to follow because as-of constraints apply in both directions (downstream and upstream) but `bootstrap_dataflow_as_of` only receives dataflows one at a time, in dependency order. `collect_dataflow_storage_constraints` exists to work around this limitation, supplying information about downstream constraints.
* It is not always able to select as-ofs at which the respective dataflows can hydrate immediately (#28440). This follows directly from the limited insight in constraints imposed by downstream objects and is an issue for 0dt.
* It's implemented in …
> adapter,compute: improved dataflow as-of bootstrapping

- WORKSPACE
Failed in https://buildkite.com/materialize/test/builds/89599
Someone updates the files uploaded in
https://github.com/MaterializeInc/toolchains/releases/tag/clang-18.1.8 yesterday, since
https://github.com/MaterializeInc/materialize/pull/29320 is actively being worked on, I guess @ParkMyCar updated it accidentally without bumping the version. I'd suggest to disallow overriding artifacts if that can be configured.
> bazel build: Update hashes for Clang

- src/kafka-util/src/client.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
The code as it was would produce an error report if someone set the kafka transaction timeout to a value that is above the default progress record fetch timeout, even though it's the system that chose the problematic default in the first place. So in some sense, it was complaining about a problem it caused to itself.
This PR makes it so that configurations whose defaults are derived from other values have an `Option<_>` type so that we can differenciate between "the user does not have an opinion" and the "the user has an opinion". We then only produce an error if the user had the wrong opinion.
> kafka-util: only complain when true misconfiguration happens

- Cargo.lock
- misc/cargo-vet/audits.toml
- src/storage/src/sink/kafka.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/kafka.rs
- src/testdrive/src/action/kafka/delete_records.rs
- test/testdrive/kafka-sink-empty-progress-topic.td
Previously, Kafka sinks would wedge on startup if their progress topic was empty but had a nonzero low water mark. It's extremely difficult for a progress topic to get into this state (you need to write one or more messages to the progress topic and then somehow delete *all* of those messages), but we've observed at least one progress topic in this state in the wild.
So, this commit teaches Kafka sinks to handle this case without wedging, and adds a test case to prevent future regressions. See the comments within the patch and the test case for details.
* This PR fixes an issue reported by a customer on Slack.
> storage/sinks/kafka: don't wedge on empty progress topics

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
Move some to Release Qualification
Seen causing timeouts, for example in https://buildkite.com/materialize/nightly/builds/9334
Verification: https://buildkite.com/materialize/release-qualification/builds/579 & https://buildkite.com/materialize/nightly/builds/9344
> ci: Parallelize platform-checks in Nightly

- test/testdrive/kafka-sink-empty-progress-topic.td
with `--kafka-default-partitions 5`
Seen failing in https://buildkite.com/materialize/nightly/builds/9364#0191b3ce-8119-4260-920e-c1895e58fb2b
```
cluster-u1-replica-u1-gen-0: 2024-09-02T18:19:23.249860Z  INFO mz_storage::healthcheck: Health transition for sink u1169: Some(Running) -> Some(Stalled { error: "kafka: Progress topic testdrive-empty-at-zero-3107866228 should contain a single partition, but instead contains 5 partitions", hints: {}, namespaced_errors: {Kafka: "Progress topic testdrive-empty-at-zero-3107866228 should contain a single partition, but instead contains 5 partitions"} })
```
Just introduced in https://github.com/MaterializeInc/materialize/pull/29321
> testdrive: Fix new kafka-sink-empty-progress-topic.td

- ci/test/pipeline.template.yml
> ci: Disable combined RTR test

- ci/release-qualification/pipeline.template.yml
Seen in https://buildkite.com/materialize/release-qualification/builds/578#0191ac6f-5224-4691-819b-bb64d19b7690
Run succeeded: https://buildkite.com/materialize/release-qualification/builds/580#0191ac75-01ef-4110-9bc6-476da7d392fc
> ci: Larger agent for backup&restore test

- misc/python/materialize/docker.py
Can sometimes fail, currently defaults to no retries in feature-benchmark for example: https://buildkite.com/materialize/test/builds/89615#0191b332-48ad-4c56-9704-c4cf6c457a51
> tests: Retry docker hub searches

- src/adapter/src/catalog.rs
Unfortunately, https://github.com/MaterializeInc/materialize/issues/24884 is still happening, even after I thought I fixed it. At the moment, there are more urgent things to do, so I'll just downgrade this `soft_panic` to an `error!` log to stop flaking CI. We can get back to this when we get back to adding notices.
> Downgrade the `soft_panic` in `drop_plans_and_metainfos` to an error log

- misc/images/materialized-base/Dockerfile
- misc/images/materialized/entrypoint.sh
- misc/python/materialize/mzcompose/services/cockroach.py
Seen failing in https://buildkite.com/materialize/test/builds/89635#0191b6d7-9684-4202-87b2-f88668b59fce
> ci: Bump cockroach version and add workaround

- src/environmentd/tests/sql.rs
Timed out twice in a row: https://buildkite.com/materialize/test/builds/89641
> cargo test: Disable test_utilization_hold

- bin/pydoc
Seen failing in https://buildkite.com/materialize/deploy/builds/15751#0191a1ab-ca1f-4a32-a402-541ff7457a55
> deploy: Fix devsite deploy

- misc/python/materialize/cli/ci_annotate_errors.py
Disable this error cause, which became unreliable.
This addresses errors like
```
-- * function 'row(AnyOperationParam)': 3 top level, 0 nested, 0 generation failed, not included in any query that was successfully executed in all strategies (possibly invalid operation specification)!
```
observed for example in https://buildkite.com/materialize/nightly/builds/9341#0191a459-8f9f-460e-919d-2035c2d9422f.
> output consistency: do not fail on "possibly invalid operation specification"

- Cargo.lock
- Cargo.toml
- misc/cargo-vet/audits.toml
- misc/cargo-vet/imports.lock
- src/environmentd/tests/pgwire.rs
- src/pgtest/src/lib.rs
- src/sqllogictest/src/runner.rs
- src/storage/Cargo.toml
- src/storage/src/source/postgres/replication.rs
- src/workspace-hack/Cargo.toml
I tidied up our `rust-postgres` fork and also brought in all changes from upstream. This PR brings in those changes. The highlight of those changes is that logical replication support is now a clean extension of the low level `CopyBoth` mechanism exposed by this upstream PR https://github.com/sfackler/rust-postgres/pull/778
> *: upgrade postgres crates

- misc/python/materialize/output_consistency/output/reproduction_code_printer.py
Observed in https://buildkite.com/materialize/nightly/builds/9341#0191a459-8f9f-460e-919d-2035c2d9422f.
For queries like
```
SELECT convert_from(sha256(s0.bytea_val), 'utf8')
FROM t_dfr_vert_0 s0
INNER JOIN t_dfr_vert_1 s1 ON (NOT (s1.bool_val))
INNER JOIN t_dfr_vert_2 s2 ON TRUE::BOOL
ORDER BY s0.row_index ASC, s1.row_index ASC, s2.row_index ASC
OFFSET 4;
```
`t_dfr_vert_2` is unused (not referenced) but can still influence the result (e.g., in particular when the join condition is `FALSE::BOOL`).
> output consistency: reproduction printer: do not remove data sources that are unreferenced but needed

- ci/nightly/pipeline.template.yml
- ci/plugins/cloudtest/hooks/command
- ci/release-qualification/pipeline.template.yml
- test/cloudtest/test_full_testdrive.py
- test/limits/mzcompose.py
> ci: Parallelize nightly to run in ~1 hour

- .bazelrc
- WORKSPACE
- bin/bazel-temp
This PR adds a Bazel config named `release` that is the same as our existing release configuration. It also adds a `x-lang-lto` config that enables cross language inlining, which is now possible since all of our C dependencies are built with clang.
Fixes: https://github.com/MaterializeInc/materialize/issues/27033
> bazel: Release configuration

- .bazelrc
- WORKSPACE
- misc/bazel/c_deps/BUILD.jemalloc.bazel
- misc/bazel/c_deps/BUILD.openssl.bazel
- misc/bazel/c_deps/BUILD.zlib.bazel
- misc/bazel/c_deps/extra_setup.bzl
- misc/bazel/c_deps/rust-sys/BUILD.decnumber.bazel
- misc/bazel/c_deps/rust-sys/BUILD.librdkafka.bazel
- misc/bazel/c_deps/rust-sys/BUILD.psm.bazel
- misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel
- misc/bazel/toolchains/rust.bzl
This PR does several things to add support for cross compilation and better remote caching for Linux.
1. It adds a Linux sysroot so we no longer depend on any libraries from the host
1. This should also allow us to slim down the ci_builder Docker image
2. Makes a few changes to the `BUILD` files for C dependencies to support cross compiling
1. `rocksdb`
2. `jemalloc`, we now also link the Bazel built `jemalloc` instead of relying on `tikv-jemalloc-sys` crates build script
3. `openssl`
4. [`psm`](https://crates.io/crates/psm) the Rust crate used to grow the stack
3. General cleanup of `BUILD` files. Instead of specifying `-Lnative=<path>` and `-lstatic=<libname>` linker flags for Rust system crates, we add them as `deps` to the corresponding Rust crate where `rules_rust` will add these …
> bazel: add a Linux sysroot and support cross compilation

- doc/user/layouts/partials/sql-grammar/subscribe-stmt.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- test/sqllogictest/subscribe_outputs.slt
The "output options" for `SUBSCRIBE` (i.e., the `ENVELOPE` and `WITHIN TIMESTAMP ORDER BY` clauses) were jammed in at the end of the statement, as in:
SUBSCRIBE t WITH (SNAPSHOT) AS OF 1 UP TO 2 ENVELOPE UPSERT KEY (a)
This was inconsistent with our other SQL statements. In particular, CREATE SOURCE and CREATE SINK always put the WITH options at the very end of the statement:
CREATE SINK ... WITH (SNAPSHOT)
And SELECT always puts the AS OF clause at the very end of the statement:
SELECT * FROM t WHERE ... AS OF 1
This commit restores the consistency that used to be present in `SUBSCRIBE` by moving the output options to *before* the `AS OF`, `UP TO`, and `WITH` options:
SUBSCRIBE t ENVELOPE UPSERT KEY (a) WITH (SNAPSHOT) AS OF 1 UP TO 2
The old syntax remains supported for backwards …
> sql-parser: align SUBSCRIBE syntax with CREATE SINK/SELECT

- ci/nightly/pipeline.template.yml
- misc/python/materialize/scalability/executor/benchmark_executor.py
- misc/python/materialize/scalability/scalability_versioning.py
- test/data-ingest/mzcompose.py
- test/limits/mzcompose.py
- test/txn-wal-fencing/mzcompose.py
Based on the results from https://buildkite.com/materialize/nightly/builds/9380/waterfall
> ci: Further nightly speedups

- ci/plugins/mzcompose/hooks/command
> ci: Also print env variables for parallelism

- misc/python/materialize/checks/mzcompose_actions.py
Fixes `bin/mzcompose --find platform-checks down && bin/mzcompose --find platform-checks run default --scenario=ZeroDowntimeRestartEntireMz --check=DebeziumPostgres` for me on macOS.
> platform-checks: Only read new version after promotion succeeded

- test/sqllogictest/cardinality.slt
Stats are sometimes timing out in CI; the `optimizer_oneshot_stats_timeout` is set to 20ms, which is apparently a little too low sometimes.
This PR sets the timeout to 100ms, which should avoid flakes.
#29352
> ci: avoid flakes due to slow stats

- doc/user/content/sql/show-role-membership.md
- src/sql/src/plan/statement/show.rs
- test/sqllogictest/rbac_views.slt
The documentation for `SHOW ROLE MEMBERSHIP` says that the `FOR <role_name>` filter does the following:
> Only shows role memberships granted directly or indirectly to
> role_name.
The implementation outputs these role memberships, but it also outputs role memberships where other roles are members of role_name. This makes the output confusing and not consistent with the documentation. This commit updates the implementation so that it's consistent with the documentation.
> sql: Fix SHOW ROLE MEMBERSHIP filter

- src/frontegg-mock/src/handlers/user.rs
- src/frontegg-mock/src/models/user.rs
- src/frontegg-mock/src/server.rs
- src/frontegg-mock/tests/local.rs
As discussed in #29331 adding an internal endpoint to allow us to get the user passwords for some internal testing.
To manually test the new endpoint using curl, you could use the following:
```sh
curl -X POST http://localhost:3000/api/internal-mock/user-password \
-H "Content-Type: application/json" \
-d '{"email": "mz_system"}'
```
Based on the user data you provided when starting the service, you should get a response like this:
```json
{
"email": "mz_system",
"password": "7e8f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b"
}
```
> frontegg-mock: add internal endpoint to get user passowrds

- src/persist-client/src/internal/trace.rs
In practice all batches are structured now, but we still see a small heartbeat of legacy-path applies in one env. I think this may be because I didn't swap out this default when I swapped out the default for the flag, and we're just applying diffs to some empty state.
I'd like to remove this path entirely soon - see https://github.com/MaterializeInc/materialize/pull/28254 - and this will make it easier to see in the metrics that it's safe to delete.
> [persist] Default to roundtrip_spine=true

- ci/test/pipeline.template.yml
Seen in https://buildkite.com/materialize/test/builds/89778#0191be22-b3c4-4d79-b1b2-741966167a7b
> ci: Bump cloudtest timeout

- misc/python/materialize/parallel_workload/action.py
Seen in https://buildkite.com/materialize/nightly/builds/9399#0191be17-1f4c-4321-9b51-edc4b08b71c5
> parallel-workload: Expect rtr error

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cli/ci_closed_issues_detect.py
- misc/python/materialize/github.py
Mainly motivated by https://github.com/MaterializeInc/incidents-and-escalations/issues/72 which would have silenced the parallel workload failure here: https://buildkite.com/materialize/nightly/builds/9405#0191bf60-478f-410d-bdba-693f97bee157
parallel-workload-materialized-1     | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-038ffe6283a5930a9-1/materialize/test/src/persist-client/src/internal/state.rs:1472:17: LeasedReaderId(r7ef9c21d-4778-4cbb-b24b-6e5e1258754f) was expired due to inactivity. Did the machine go to sleep?
> ci: Also check incidents-and-escalations for ci-regexp

- src/persist-client/src/internal/state_diff.rs
> cargo test: Disable test_state_sync test

- ci/release-qualification/pipeline.template.yml
See https://github.com/buildkite/agent/issues/2969
> tests: Move longer Zippys back to AWS

- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/introspection.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/statement_logging.rs
- src/compute-client/src/controller.rs
- src/controller/src/lib.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/collection_status.rs
- src/storage-controller/src/lib.rs
- src/storage-controller/src/statistics.rs
This PR makes converts the `Controller::process` method to a non-`async` one, removing one potential source of blocking from the coordinator main loop.
The most significant change here is making the channel on which updates are sent to the `CollectionManager` unbounded. This does introduce the risk of higher memory usage on envd. This is not the first use of an unbounded channel in envd and in the past it has actually been helpful seeing their memory usage grow to realize that something was wrong with the system. Anecdotically, we seem to be better at debugging increased memory usage than blockage in the coordinator loop.
The coordinator main loop can be blocked at various places if the channels feeding the `CollectionManager` run full.
> controller: make `Controller::process` non-`async`

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cli/ci_closed_issues_detect.py
- misc/python/materialize/github.py
Reverts MaterializeInc/materialize#29389
We probably have to give the token necessary permissions first, seems to cause CI failures.
> Uploading results failed! Bad return code from GitHub: 422
> Revert "ci: Also check incidents-and-escalations for ci-regexp"

- src/adapter/src/catalog/migrate.rs
This commit removes migrations that are older than 4 versions.
> catalog: Remove old migrations

- src/catalog/src/durable/objects.rs
- src/catalog/src/durable/persist.rs
This commit teaches the durable catalog to handle fences that result
from the new fence token update kind. Currently, no processes ever
actually writes this token so the code is technically unreachable.
However, this is need so that the next version can write a fence token
and correctly fence the current version.
> catalog: Add fence token handling

- src/persist-client/src/internal/state_diff.rs
This was an interesting test failure! Proptest was finding a sequence of changes that reliably hit the "slow path" state sync code, which involves rebuilding a trace from scratch. My recent change to make the default of trace structured meant that applying diffs also caused the follower to enable structured-data roundtripping, even if the upstream code had not, causing the two states to get out of sync.
This code explicitly sets the flag to match the input trace in the legacy path. (Which is in practice on this codepath always false.)
Fun fact: the smallest repro for this appears to be eight separate operations, including a mix of empty and non-empty appends and compactions. Property testing's great.
Fixes #29385.
In other circumstances I'd make a constructor that required you to specify …
> Fix legacy path and re-enable the test

- doc/user/content/sql/system-catalog/mz_catalog.md
- src/adapter/src/catalog/builtin_table_updates.rs
- src/catalog/src/builtin.rs
- test/sqllogictest/autogenerated/mz_catalog.slt
- test/sqllogictest/mz_catalog_server_index_accounting.slt
Implements some of the work towards https://github.com/MaterializeInc/materialize/issues/29373 with the goal of unblocking @bobbyiliev 's work on the terraform provider (https://github.com/MaterializeInc/terraform-provider-materialize/pull/645)
The introspection updates are described in the design doc PR https://github.com/MaterializeInc/materialize/pull/27907 - see here for rendered form: https://github.com/rjobanp/materialize/blob/subsource-deprecation-blue-green/doc/developer/design/20240625_source_versioning__table_from_sources.md#system-catalog--introspection-updates
> storage/adapter: Add source-id column to mz_catalog.mz_tables and add tables-from-sources to mz_internal source-reference tables

- ci/test/build.py
Accidentally left behind a `print(...)` from a previous PR
> build: cleanup print statement that made it in

- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/apply.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/paths.rs
- src/persist-client/src/internal/state.rs
- src/persist-client/src/internal/trace.rs
We've discussed wanting a similar thing a few times now.
This only works for shards that are regularly getting appends, since that's the only time we have the opportunity to generate merge reqs at the moment. I suspect we probably want a way to be even more aggressive, but all the ideas I have there are more invasive and need some team discussion, so I'd rather take them in a followup PR.
> [persist] Add a few more knobs to drive compactions

- src/adapter/src/coord/sequencer/inner.rs
- src/catalog/src/memory/objects.rs
- src/sql/src/catalog.rs
- src/sql/src/plan/statement/show.rs
While subsources with the same external reference are not officially supported, they are possible. (A side-effect of the source-versioning work to implement `CREATE TABLE .. FROM SOURCE` statements).
@def- noticed that the `SHOW CREATE SOURCE` might not accurately present the subsource references inside a `CREATE SOURCE` statement when multiple refer to the same upstream reference, so this is a fix for that. Note that this is all going to be deprecated soon once the work in #28430 is completed.
It also fixes a misnamed method on `CatalogEntry` to make it clear when the object is an actual subsource item or a source-export (either a subsource or a source-fed table).
> storage/sources: Fix SHOW SOURCE command for sources that may have multiple subsources with the same reference

- misc/python/materialize/mzbuild.py
Accidentally started defaulting to Bazel being on for all builds
Fix #29409.
> bazel: Fix accidental default

- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
- src/controller/src/lib.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
This PR changes the way frontier introspection (what populated `mz_frontiers` and `mz_cluster_replica_frontiers`) works for compute frontiers. Previously, the top-level `Controller` would wake up once a second, fetch the current global and replica frontiers from the compute controller, and send them to the storage controller, which would add its own frontiers and write everything to the introspection collections.
With this change, the top-level `Controller` still wakes up every second, but it now only tells the storage controller to record its own frontiers. The compute frontiers are now recorded inside the compute controller, using the existing infrastructure for maintaining introspection data (`CollectionIntrospection` and `introspecton_tx`). The reporting of storage frontiers can now …
> compute: decouple frontier introspection reporting

- src/storage-types/src/dyncfgs.rs
- src/storage/src/source/reclock.rs
- src/storage/src/source/source_reader_pipeline.rs
- src/storage/src/source/types.rs
This PR adds the infrastructure to support minting reclock bindings according to the latest probed upstream frontier. This lives side by side the current strategy which mints based on a local timer and the frontier we have ingested so far. Which one is used is controlled by an LD flag.
Note that this PR only implements the necessary plumbing to suppored probed frontier minting but no source is currently connected so turning the flag on will effectively result in no bindings to be minted. I will connect the sources to the mechanism introduced here in a follow up PR.
The way in which this is implemented is by removing the decision of the binding timestamps from the `ReclockOperator` which now expects them as an argument. Under the new semantics whoever is using calling the `mint` function …
> storage: infrastructure for reclocking to latest frontier

- test/parallel-workload/mzcompose.py
Seen in https://buildkite.com/materialize/nightly/builds/9428#0191c549-67b6-448a-859a-faeec9812da5
> parallel-workload: Don't wait for potentially hanging threads

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/indexes.rs
- src/adapter/src/coord/sequencer/inner/create_index.rs
- src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
- src/adapter/src/coord/sequencer/inner/create_view.rs
- src/adapter/src/optimize/dataflows.rs
- src/adapter/src/optimize/index.rs
- src/catalog/src/memory/objects.rs
Most of the cost of cloning the catalog come from cloning the HIR and MIR
plans for (materialized) views. To avoid the cost, we wrap them in an Arc.
Part of #28720.
> Arc cached plans in the catalog

- src/adapter/src/catalog/migrate.rs
- src/adapter/src/catalog/open.rs
Previously, loading user items into the catalog on startup looked something like this:
1. Apply AST migrations to the persisted CREATE SQLs for each item.
2. Load all user items into a temporary in-memory catalog.
3. Generate item migrations to all user items from the temporary in-memory catalog.
4. Drop the temporary catalog.
5. Load all migrated user items into the permanent in-memory catalog.
This process is unnecessarily expensive because we end up parsing, planning, and optimizing all user items twice.
This commit updates the process to look something like this:
1. Apply AST migrations to the persisted CREATE SQLs for each item.
2. Load all user items into the permanent in-memory catalog.
3. Generate item migrations to all user items from the permanent in-memory catalog.
4. Apply the …
> catalog: Optimize item loading on startup

- test/testdrive/materialized-view-refresh-options.td
Seen failing in https://buildkite.com/materialize/nightly/builds/9458#0191cc40-0a00-4dc7-8527-50f6250b367c
My best guess is that the system is just overloaded and would have finished after a while
> testdrive: Wait longer for cluster to turn off

- misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
- misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This replaces https://github.com/MaterializeInc/materialize/pull/29444 and addresses https://buildkite.com/materialize/nightly/builds/9456#0191c9b1-a3fa-44b9-a589-baeecb4e4723.
> output consistency: remove string_agg and array_agg without ordering

- src/compute-types/src/dyncfgs.rs
- src/compute/src/compute_state.rs
- src/compute/src/server.rs
Currently, the compute main loop performs maintenance whenever it loops. This can cause overhead in situations when we reasonably well know that there is no work to be done, but we still do it. This PR limits the rate at which we perform maintenance based on elapsed wall clock time. The implementation exposes a dyncfg to change the interval at runtime. Setting it to zero restores the current behavior to perform maintenance on every iteration.
In experiments, this reduces the cluster's CPU utilization to a level that I can't see much of it in perf anymore, but there's a risk I'm holding the tools wrongly.
> Limit compute maintenance based on elapsed time

- misc/python/materialize/checks/all_checks/source_tables.py
- test/testdrive/source-tables.td
https://buildkite.com/materialize/nightly/builds?branch=nrainer-materialize%3Atests%2Fcreate-table-from-source
> tests: create table from source: platform checks and testdrive

- doc/developer/design/20240625_source_versioning__table_from_sources.md
- doc/developer/design/20240625_subsource_deprecation_blue_green_sources.md
[Rendered](https://github.com/rjobanp/materialize/blob/subsource-deprecation-blue-green/doc/developer/design/20240625_source_versioning__table_from_sources.md)
-
> storage: Design doc for Source Versioning / Tables from Sources [ENG-TASK-15]

- src/adapter/src/coord.rs
- src/adapter/src/coord/introspection.rs
- src/adapter/src/coord/peek.rs
- src/adapter/src/coord/sequencer/inner/peek.rs
- src/adapter/src/coord/sequencer/inner/subscribe.rs
- src/adapter/src/util.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/error.rs
- src/compute-client/src/controller/instance.rs
Prior to this change, the controller API for creating a replica-targeted subscribe was:
* call `create_dataflow` to create the subscribe dataflow
* call `set_subscribe_target_replica` to point the dataflow at a replica
The second call would fail, for sanity reasons, if the subscribe already had responses received.
This API is annoying for compute controller decoupling, i.e., moving the `Instance` controllers into separate tasks. Decoupling will allow the `Instance` to start the subscribe dataflow as soon as the `create_dataflow` command is received, and there is no guarantee that the `set_subscribe_target_replica` command reaches the `Instance` task before the subscribe received its first response.
To avoid this issue, this PR changes the API to pass the target replica already in the …
> compute: remove separate `set_subscribe_target_replica` method

- src/compute/src/server.rs
Report the hydration status before reporting frontiers. Reporting frontiers also updates the collection frontiers, which can advance the frontiers to the empty frontier. If reporting hydration status afterwards, we might observe that the collection has advanced to the empty frontier and hence suppress the hydration update. The fix is to first report hydration status before reporting frontiers.
Fixes #29465.
This is an interim fix until the fix for #26682 changes this implementation again.
> Report hydration before frontiers

- doc/user/content/sql/create-source/mysql.md
- doc/user/layouts/partials/sql-grammar/create-source-mysql.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/adapter/src/coord/sequencer/inner.rs
- src/mysql-util/src/schemas.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/show.rs
- src/sql/src/pure.rs
- src/sql/src/pure/error.rs
- src/sql/src/pure/mysql.rs
- src/storage-types/src/sources/mysql.proto
- src/storage-types/src/sources/mysql.rs
- src/storage/src/source/mysql.rs
- src/storage/src/source/mysql/schemas.rs
- test/mysql-cdc/35-exclude-columns.td
- test/mysql-cdc/alter-source.td
We want to align this option with the forthcoming analogous option for sinks (#27758). In the context of sinks, "EXCLUDE" reads better than "IGNORE", because the columns aren't wholly ignored. Rather, they're allowed to be referenced in the PARTITION BY expression and the HEADERS option--they're just *excluded* from the final value.
EXCLUDE also nicely aligns with the `SELECT ... EXCLUDE` syntax that was recently added to DuckDB and Snowflake.
For backwards compatibility, the `IGNORE COLUMNS` option for the MySQL source continues to be accepted as an alias for `EXCLUDE COLUMNS`.
> sql: change IGNORE COLUMNS MySQL option to EXCLUDE COLUMNS

- Cargo.lock
- src/expr/Cargo.toml
- src/expr/benches/window_functions.rs
- src/expr/src/lib.rs
- src/expr/src/relation/func.rs
- src/repr/src/row.rs
This PR does a number of micro-optimizations in the window function code. https://github.com/MaterializeInc/accounts/issues/3 's new use case will push our window functions quite a bit, so we need all the performance we can get.
If this is deemed too many things in one PR, I could break it up!
~The 1st commit actually fixes a very minor bug, see commit msg.~ Edit: This was split off into a separate PR in the meantime: https://github.com/MaterializeInc/materialize/pull/29422
The ~2nd~ 1st commit adds a micro-benchmark, which can measure the effect of commits 3, 4, 5, ~6~. These commits give a ~6.5x~ 3.2x speedup in total on this benchmark. Edit: One of these commits were removed in the meantime, so there is 2x less speedup now.
Commits ~7, 8, 9~ 5, 6, 7 are just minor things (outside of …
> Micro-optimizations around window functions

- misc/python/materialize/cli/ci_upload_heap_profiles.py
- misc/python/materialize/parallel_workload/database.py
> ci: Fix heap profiles for clusterds & minor parallel-workload fixes

- doc/user/content/transform-data/patterns/top-k.md
- doc/user/content/transform-data/patterns/window-functions.md
Add order by clause and a small fix to the lag example suggestion to use RIGHT join instead of LEFT join.
- Also, small tweak to change `name` to `city` in the table.
> docs: tweak windows functions examples to include order by

- Cargo.lock
- src/balancerd/src/lib.rs
- src/dyncfg-launchdarkly/src/lib.rs
- src/dyncfg/src/lib.rs
- src/environmentd/src/lib.rs
- src/server-core/BUILD.bazel
- src/server-core/Cargo.toml
- src/server-core/src/lib.rs
Plumb a dyncfg `ConfigSet` into `mz_server_core::serve` so that changes to the graceful termination period are dynamically updated.
* This PR fixes a TODO flagged by @jubrad on Slack.
> balancerd: fix LaunchDarkly syncing

- src/controller/src/lib.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
This PR moves the timer that controls when storage frontiers should be recorded in their respective introspection collections from the top-level `Controller` into the storage controller. Since the reporting of compute frontiers has been moved fully into the compute controller (#29399), there is no reason anymore for the top-level `Controller` to be involved.
Inside the storage controller, this PR adds a `maintain` method, akin to the one the compute controller already has. Other periodic tasks can be invoked from there in the future as well. One likely candidate for such a task is wallclock lag reporting (#28097).
This PR also merges `record_frontiers` and `record_replica_frontiers` into one method, to avoid some duplicate work looping through storage collections.
* This PR adds a …
> controller: move frontier recording into storage controller

- Cargo.lock
- src/environmentd/Cargo.toml
- src/environmentd/src/test_util.rs
- src/persist-client/src/batch.rs
- src/persist-client/src/cache.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/apply.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/internal/state.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/operators/shard_source.rs
- src/persist-client/src/read.rs
- src/persist-client/src/schema.rs
- src/persist-client/src/stats.rs
- src/persist-client/src/usage.rs
- src/persist-client/src/write.rs
- src/persist-types/src/schema.rs
- src/persist/src/indexed/encoding.rs
We now have both a write schema and a read schema at read time. The
write schema is specified by an id which indexes into a map in durable
persist state, but is sometimes missing because of backward
compatibility. The read schema is always present but might be missing an
id (e.g. if we use this mechanism for projection pushdown, but also for
other various edge cases).
The vast majority common case is that these schemas will be the same and
no migration is necessary. If we're missing the write schema, we _have_
to use the legacy Codec to decode the data. If we have both and they're
not the same, construct (and cache) migration logic for converting from
the write schema to the read schema.
Note that, counter-intuitively, the write schema could be from "after"
the read schema. This is …
> persist: migrate structured arrow data as necessary on read

- src/adapter/src/util.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/error.rs
- src/catalog/src/durable/initialize.rs
- src/catalog/src/durable/persist.rs
- src/catalog/tests/debug.rs
- src/catalog/tests/open.rs
- src/catalog/tests/snapshots/debug__opened_trace.snap
- src/catalog/tests/snapshots/open__initial_snapshot.snap
- src/environmentd/tests/server.rs
This reverts commit fa2c41700e63f054e5bc48428b66a42a912e9ffe.
Fixes: #29432
I'm not sure if we want that.
> Revert "catalog: Combine epoch and deploy generation"

- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/lib.rs
Pure refactor, no behavior change.
> storage: remove some minor bits of duplication

- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- misc/python/materialize/test_analytics/data/build/build_data_storage.py
- misc/python/materialize/test_analytics/data/build/build_history_analysis.py
- misc/python/materialize/test_analytics/data/build_annotation/build_annotation_storage.py
- misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
- misc/python/materialize/test_analytics/data/known_issues/known_issues_storage.py
- misc/python/materialize/test_analytics/data/output_consistency/output_consistency_stats_storage.py
- misc/python/materialize/test_analytics/data/scalability_framework/scalability_framework_result_storage.py
- misc/python/materialize/test_analytics/search/test_analytics_search_source.py
- misc/python/materialize/test_analytics/setup/test_analytics_setup.py
> test-analytics: Sanitize literals everywhere

- misc/python/materialize/buildkite.py
- misc/python/materialize/test_analytics/data/build/build_data_storage.py
- misc/python/materialize/test_analytics/setup/tables/02-build-job.sql
- misc/python/materialize/test_analytics/test_analytics_db.py
Migration before merging:
* create `build_job_2`
* move data there
* cascade delete `build_job`
* create new `build_job`
* insert data from `build_job_2`
* recreated views that were dropped
* drop `build_job_2`
> test analytics: fix agent type

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/29519. This applies the ignore pattern also to errors of type `SUCCESS_MISMATCH` in addition to `ERROR_MESSAGE_MISMATCH`.
This addresses left-overs in https://buildkite.com/materialize/nightly/builds/9517#0191e958-12e6-4d37-b97a-e8f13052b4ab.
> version consistency: extend ignore to also apply for success mismatches

- .config/nextest.toml
Seen timing out in https://buildkite.com/materialize/test/builds/90318#0191e775-e18e-4711-95e0-1a69276f7ad8
> cargo-test: Bump timeout for long-running test_storage_usage_collection_interval

- misc/python/materialize/data_ingest/workload.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9527#0191edbd-745b-47da-b741-ce50564c8415
@petrosagg Is this the proper way to handle this?
> data-ingest: Longer RTR timeout

- misc/python/materialize/docker.py
Seen failing in https://buildkite.com/materialize/test/builds/90406#0191f461-746c-4b35-b28b-c903f9019852
> tests: Bump retries for docker hub searches

- ci/test/pipeline.template.yml
Seen timing out in https://buildkite.com/materialize/test/builds/90397#0191f16b-b001-4146-aed2-f71b7c3f225d
> ci: Bump parallelism for Checks without restart

- test/canary-load/mzcompose.py
> canary load: Remove constantly failing TPCH queries

- test/testdrive/wallclock-lag.td
Seen flaking in CI 6 times: https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%2C%7B%22id%22%3A%22content%22%2C%22value%22%3A%22wallclock-lag.td%3A%22%7D%5D
Was introduced in https://github.com/MaterializeInc/materialize/pull/29449
Edit: Even with 10 s I'm still seeing it fail locally:
```
wallclock-lag.td:70:1: error: non-matching rows: expected:
[["idx", "true", "true"], ["idx_const", "false", "true"], ["mv", "true", "true"], ["mv_const", "false", "true"], ["snk", "true", "true"], ["src", "true", "true"], ["src_progress", "true", "true"], ["tbl", "true", "true"]]
got:
[["idx", "true", "true"], ["idx_const", "false", "true"], ["mv", "true", "true"], ["mv_const", "false", "true"], ["snk", "true", …
```
> testdrive: Bump global wallclock lag in test

- test/rqg/Dockerfile
This replaces https://github.com/MaterializeInc/materialize/pull/28388 and https://github.com/MaterializeInc/materialize/pull/28343.
> rqg: update version

- test/replica-isolation/mzcompose.py
16 failures in CI is too much: https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%5D&tfGlobalFilter=Someone%20claimed%20to%20be%20us
> replica isolation test: Disable restart-replica disruption

- src/environmentd/src/test_util.rs
- src/environmentd/tests/sql.rs
> tests: create table from source: cargo tests

- test/parallel-benchmark/mzcompose.py
Plot CCDFs as part of the parallel benchmark framework.
> Plot CCDFs in parallel-benchmark

- WORKSPACE
- ci/test/build.py
- misc/bazel/tools/BUILD.bazel
- misc/python/materialize/mzbuild.py
This PR makes some of the tools from our Clang toolchain more easily accessible so things like `mzbuild` can use them. It also updates `mzbuild.py` to use these tools when Bazel is enabled.
Exposing the necessary tools from Bazel will allow us to remove them from the CI builder image and slim it down.
> bazel: Expose tools from the Clang toolchain, add `darwin-x86_64` toolchain

- .config/nextest.toml
Seen in https://buildkite.com/materialize/test/builds/90445
Mistakenly used the wrong order in https://github.com/MaterializeInc/materialize/pull/29534
> cargo test: Fix nextest.toml order

- ci/deploy/docker.py
- ci/deploy_mz/docker.py
- ci/deploy_mz/linux.py
- ci/deploy_mz_lsp_server/linux.py
- ci/mkpipeline.py
- ci/mkpipeline.sh
- ci/nightly/pipeline.template.yml
- ci/qa-canary/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/slt/pipeline.template.yml
- ci/test/build.py
- ci/test/dev_tag.py
- ci/test/pipeline.template.yml
- misc/python/materialize/benches/avro_ingest.py
- misc/python/materialize/cloudtest/app/application.py
- misc/python/materialize/cloudtest/app/cloudtest_application_base.py
- misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
- misc/python/materialize/mzbuild.py
This PR makes a few changes to fixup the build pipeline.
* rename `CI_BUILD_WITH_BAZEL` to `CI_BAZEL_BUILD` to align better with `CI_BAZEL_REMOTE_CACHE`
* plumb to all other callers of `Repository(...)`
* add `CI_BAZEL_BUILD: 1` to `mkpipeline.sh`
Fix the build pipeline
> bazel: Fixup build pipeline

- .bazelrc
- WORKSPACE
- misc/bazel/toolchains/rust.bzl
This PR adds nightly Rust to our Bazel toolchain, you can use it by specifying `--config=rust-nightly`. This is the first step to getting sanitzers working in Bazel.
Support building with Nightly Rust in Bazel.
> bazel: Add nightly Rust toolchain

- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/coord/ddl.rs
- src/sql/src/ast/transform.rs
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/materialize/issues/29496
Also fixes https://github.com/MaterializeInc/materialize/issues/29562 and fixes https://github.com/MaterializeInc/materialize/issues/29503 and fixes https://github.com/MaterializeInc/materialize/issues/29564
We were error logging whenever source tables were dropped after their corresponding source which was always happening when they are dropped together in a transaction due to the implicit ordering in `src/adapter/src/coord/ddl.rs`. There isn't an actual bug in dropping out-of-order so I could have just removed the error log but I thought that it would be better to keep it since it might be useful in any future issue around dependency ordering.
The error log happens here: …
> storage/sources: Minor fixes for source table objects

- ci/plugins/cloudtest/hooks/command
- ci/test/pipeline.template.yml
Broken in https://github.com/MaterializeInc/materialize/pull/29345
> ci: Fix cloudtest parallelism

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- misc/python/materialize/checks/all_checks/source_tables.py
> platform-checks: Mark checks as non-idempotent

- src/repr/src/row.rs
Removes the if-condition on the consistency check when decoding a `ProtoRow` so we always validate the number of datums == the number of columns.
Closes https://github.com/MaterializeInc/materialize/issues/28146
> persist: Try removing condition

- src/persist-types/src/arrow.rs
Arrow types are recursive, and they're present at all levels of a hierarchical data type. For example, if I have a struct array, I'll have a list of fields which include the data types of each child... and a separate list of children, each of which track their own datatype.
In general this doesn't explode in size for arrow because many types contain `Arc`s and can be shared. But we lose this sharing when encoding to proto.
This changes our encoding to pass an "expected" type to encoding and decoding. Encoding is allowed to omit the type if it matches the expected type, and decoding is allowed to assume an omitted type is the expected type. In practice this means that we only need to include the type info at the top level.
This can be very significant for small arrays. For example, some …
> [persist] Only include the Arrow DataType info at the top level in proto

- src/persist-client/src/schema.rs
I only hooked it up for the migrations cache initially because my mental
model was that the schema cache would be tied to the process lifetime.
But, of course, that's only true if there's a long lived handle. Hooking
this up allows us to correct the graph for the total number of entries
in the cache.
> persist: hook up dropped metric for schema cache, too

- src/environmentd/tests/sql.rs
Seen failing in https://buildkite.com/materialize/test/builds/90515 and https://buildkite.com/materialize/test/builds/90530
@danhhz This seems to have started with https://github.com/MaterializeInc/materialize/pull/29574 being merged
> cargo test: Bump timeout in test_timeline_read_holds

- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
Seen in https://buildkite.com/materialize/release-qualification/builds/600#0191f45f-70e2-4251-a5b7-e980ba841ea0
> ci: Speed up cloudtest & large-scale backup+restore

- misc/python/materialize/buildkite.py
- misc/python/materialize/parallel_benchmark/framework.py
- misc/python/materialize/parallel_benchmark/scenarios.py
- misc/python/materialize/util.py
- test/parallel-benchmark/mzcompose.py
Way higher performance, removes bottleneck from testing, don't have to investigate pg8000 weirdness with many connections (sudden network errors)
If this works well, I think we should consider using psycopg everywhere, we had other mystery network errors before, and more performance doesn't hurt. I didn't realize we already had psycopg as a dependency anyway.
Replaces: https://github.com/MaterializeInc/materialize/pull/29573
> parallel-benchmark: Switch to psycopg instead of pg8000

- src/expr/src/scalar/func.rs
Why think of counterexamples when the computer can do it?
(We could also add more functions to the abstract interpreter tests, which cover this codepath... but we can test this directly more cheaply for more functions, and this keeps any test failures closer to the problematic code.)
Inspired by: https://github.com/MaterializeInc/materialize/pull/29514
This sadly produces a counterexample for `left` when passed a negative argument... `'a' < 'aa' < 'z'` but `left(_, -1)` returns `'' < 'a' > ''`. Concat seems fine in the second arg however!
> [expr] Add a proptest for the is_monotone annotations

- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/statement_logging.rs
Avoid an allocation when packing an update, remove redundant check for
sending builtin table updates in read-only mode.
> Minor code improvements

- misc/python/materialize/mzcompose/__init__.py
- src/adapter-types/src/dyncfgs.rs
- src/adapter/src/catalog/transact.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/initialize.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/transaction.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
Add a feature flag, `0dt_deployment_panic_after_timeout`, that causes environmentd to panic if the 0dt maximum wait time is reached and preflight checks have not succeeded.
This will be enabled in 0dt tests, to make the cause of test failures more obvious.
Fix #29328.
> environmentd: allow panicking on failed 0dt deployment

- ci/mkpipeline.py
Since we upload the Bazel result to Dockerhub now.
> ci: Only build once with bazel when multiple pipelines are running

- misc/python/materialize/test_analytics/setup/tables/00-config.sql
- misc/python/materialize/test_analytics/setup/tables/01-build.sql
- misc/python/materialize/test_analytics/setup/tables/02-build-job.sql
- misc/python/materialize/test_analytics/setup/tables/10-feature-benchmark.sql
- misc/python/materialize/test_analytics/setup/tables/11-scalability-framework.sql
- misc/python/materialize/test_analytics/setup/tables/12-parallel-benchmark.sql
- misc/python/materialize/test_analytics/setup/tables/20-build-annotation.sql
- misc/python/materialize/test_analytics/setup/tables/40-issues.sql
- misc/python/materialize/test_analytics/setup/tables/50-output-consistency-stats.sql
- misc/python/materialize/test_analytics/setup/views/01-build.sql
- misc/python/materialize/test_analytics/setup/views/02-build-job.sql
- misc/python/materialize/test_analytics/setup/views/10-feature-benchmark.sql
- misc/python/materialize/test_analytics/setup/views/100-data-integrity.sql
- misc/python/materialize/test_analytics/setup/views/11-scalability-framework.sql
- misc/python/materialize/test_analytics/setup/views/20-build-annotation.sql
- misc/python/materialize/test_analytics/setup/views/30-ci-failures.sql
- misc/python/materialize/test_analytics/setup/views/31-ci-issues.sql
- misc/python/materialize/test_analytics/setup/views/50-output-consistency-stats.sql
> test-analytics: Add qa group, grant it ownership of all tables and views

- deny.toml
https://rustsec.org/advisories/RUSTSEC-2023-0086
Seen in https://buildkite.com/materialize/security/builds/1306#01920049-5920-416c-b917-7067acf48669
> security: Ignore lexical-core advisories

- src/expr/src/scalar/func.rs
Seen failing in https://buildkite.com/materialize/nightly/builds/9578#0192010a-c915-440e-90ee-da5605b6a3dc
> miri: Ignore test_is_monotone

- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose/services/yugabyte.py
- src/adapter/src/coord/ddl.rs
- src/postgres-util/src/replication.rs
- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/postgres/snapshot.rs
- src/testdrive/src/action/sql.rs
- test/yugabyte-cdc/mzcompose
- test/yugabyte-cdc/mzcompose.py
- test/yugabyte-cdc/yugabyte-cdc.td
This PR changes the way we snapshot tables in the postgres operator such that it uses the main replication slot for setting the transaction snapshot. Doing it this way means that we can successfully snapshot and replicate from Yugabyte since no temporary replications slots are created.
Beyond that this PR adjust a couple more parts to behave slightly differently when we talk to a Yugabyte source and also sets up an mzcompose functional test that goes over the most common patterns.
The first commit contains the code changes and the second commit contains the tests
> storage: support ingesting from yugabyte

- misc/python/materialize/cli/ci_annotate_errors.py
Seen in https://github.com/MaterializeInc/materialize/pull/29604#issuecomment-2358763716
> ci: Ignore another fencing error

- misc/python/materialize/mzcompose/__init__.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9613
> ci: Bump with_0dt_deployment_max_wait

- misc/python/materialize/mzcompose/composition.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9604#019204f3-0998-4164-a1e2-a52fc807a916
The yaml file seems to have been half-written:
> yaml: line 2: did not find expected comment or line break
> mzcompose: fsync temporary yaml file

- src/storage/src/render.rs
- src/storage/src/source/generator.rs
- src/storage/src/source/generator/key_value.rs
- src/storage/src/source/kafka.rs
- src/storage/src/source/mysql.rs
- src/storage/src/source/mysql/statistics.rs
- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/source_reader_pipeline.rs
- src/storage/src/source/types.rs
This PR makes it so whenever an upstream source is probed for its write frontier we propagate that to the reclock binding minting operator. If the `storage_reclock_to_latest` feature flag is enabled then that stream of updates is used to mint bindings instead of the frontier we've ingested so far.
> storage: wire up upstream probes to reclock binding generation

- misc/python/materialize/checks/all_checks/mysql_cdc.py
- misc/python/materialize/checks/all_checks/pg_cdc.py
Broke with https://github.com/MaterializeInc/materialize/pull/29601 being merged
> platform-checks: Fix PgCdc and MysqlCdc checks

- misc/python/materialize/checks/all_checks/mysql_cdc.py
- misc/python/materialize/checks/all_checks/pg_cdc.py
- test/testdrive/kafka-source-errors.td
Sometimes responds:
> Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure): BrokerTransportFailure (Local: Broker transport failure)
Seen in https://buildkite.com/materialize/nightly/builds/9614
@rjobanp @petrosagg Is this an expected change?
> testdrive: Fix kafka-source-errors.td

- test/cluster/upsert/01-create-sources.td
- test/cluster/upsert/02-after-clusterd-restart.td
- test/testdrive/copy-to-s3-minio.td
This fixes two tests to not rely on unstable Row ordering, see discussions [here](https://materializeinc.slack.com/archives/C01LKF361MZ/p1725905144170379) and [here](https://materializeinc.slack.com/archives/C01LKF361MZ/p1725910128130889). In the cluster test, I've split the `dbzupsert` topic into two topics, so that the two errors can be tested separately.
This PR is split off from https://github.com/MaterializeInc/materialize/pull/29454. That PR changes the row ordering, and these tests were failing without this PR.
* This PR fixes a test issue.
> Fix some tests to not rely on unstable Row ordering

- src/persist-client/src/internal/state.rs
`StateCollections::compare_and_downgrade_since` would return `Ok` if the shard is finalized or the expected opaque value matches the actual opaque value. However, the opaque value was only updated to the new opaque value iff the expected opaque value matched the actual opaque value, AND the shard was not finalized, AND the actual since was less than or equal to the new since.
Many callers, including `SinceHandle::compare_and_downgrade_since`, assumed that if `StateCollections::compare_and_downgrade_since` returned `Ok`, then the opaque value would be updated. This assumption is not always true, as described above.
This commit updates `StateCollections::compare_and_downgrade_since`, so that the opaque value is always updated if the expected opaque value matches the actual opaque value and …
> persist: Always update opaque value on success

- src/buf.yaml
- src/compute-types/src/explain/text.rs
- src/compute-types/src/plan/lowering.rs
- src/compute-types/src/plan/reduce.proto
- src/compute-types/src/plan/reduce.rs
- src/compute/src/render/flat_map.rs
- src/compute/src/render/reduce.rs
- src/expr/src/linear.rs
- src/expr/src/relation/func.rs
- src/repr/src/optimize.rs
- src/repr/src/row.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/statement.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/session/vars/definitions.rs
- test/sqllogictest/explain/physical_plan_aggregates.slt
- test/sqllogictest/explain/physical_plan_as_text.slt
- test/sqllogictest/explain/physical_plan_as_text_redacted.slt
- test/sqllogictest/window_funcs.slt
- test/testdrive/negative-multiplicities.td
This PR implements fusing `Reduce` with `FlatMap UnnestList`, to improve window function performance (https://github.com/MaterializeInc/materialize/issues/29426) to unblock https://github.com/MaterializeInc/accounts/issues/3.
The first two commits are just minor refactorings in preparation for the main thing.
The third commit adds a feature flag (but doesn't wire it up to any actual functionality yet).
The fourth commit is the main thing.
We'll probably want to backport this to the release that is coming out this Thursday, because https://github.com/MaterializeInc/accounts/issues/3 is [quite blocked](https://materializeinc.slack.com/archives/C04SN4BEQ0N/p1726241272433609?thread_ts=1725913543.246879&cid=C04SN4BEQ0N) at the moment.
* This PR fixes a recognized bug: …
> Window functions: `Reduce` - `FlatMap UnnestList` fusion

- doc/user/content/sql/system-catalog/mz_catalog.md
- doc/user/content/sql/system-catalog/mz_internal.md
- src/adapter/src/catalog/migrate.rs
- src/catalog/src/builtin.rs
- test/sqllogictest/autogenerated/mz_catalog.slt
- test/sqllogictest/autogenerated/mz_internal.slt
- test/sqllogictest/information_schema_tables.slt
- test/testdrive/catalog.td
- test/testdrive/controller-frontiers.td
- test/testdrive/github-15095.td
This was on our list of relations to promote in August, but it requires a bit of special care due to the way the relation is used by the 0dt machinery.
Fix (eventually) #29233 (leaving issue open to track the removal of the migration).
* This PR adds a known desirable feature.
> adapter: promote mz_cluster_replica_frontiers

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
This is a follow-up to https://github.com/MaterializeInc/materialize/pull/29591 and addresses https://buildkite.com/materialize/nightly/builds/9634.
c98eaa987a postgres consistency: adapt error matching to adapt to move to psycopg
b53026bf27 version consistency: add ignore
> output consistency: adapt to psycopg and byte array changes

- misc/python/materialize/data_ingest/workload.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/29452
> data-ingest: Remove workaround for RTR

- src/storage-controller/src/instance.rs
- src/storage-controller/src/lib.rs
Switch storage replicas to use a shared channel for sending responses back to the controller. This avoids the need for `FuturesUnordered` to select across a dynamic set of channels.
Part of #28720.
> Avoid futures unordered to receive replica updates

- test/testdrive/wallclock-lag.td
Apparently sources can sometimes have a frontier that's in advance of the wallclock time (and my guess is that this is also true for other objects). Unflake the test by allowing a zero lag for all objects, not just constant collections.
> test: fix wallclock lag tests for sources

- test/cloud-canary/mzcompose.py
> cloud-canary test: Fix new return type with psycopg3

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
- test/version-consistency/mzcompose.py
This addresses version consistency failures of https://buildkite.com/materialize/nightly/builds/9640#01920a0d-7ab5-46c8-99a3-23162bb1fb9b.
Explanation of the fix: The ancestor override caused a comparison of v0.118.0.x with v0.118.0.y instead of v0.**117**.0.x with v0.118.0.y so that another ignore entry did no longer match.
```
Value 1 (Dataflow rendering v0.118.0-dev.0 (2f57a6fa7)): '{n=>"\\x68656c6c6f20f09f918b"}' (type: <class 'str'>)
Value 2 (Dataflow rendering v0.118.0-dev.0 (53becb0a7)): '{n=>\x68656c6c6f20f09f918b}' (type: <class 'str'>)
```
> version consistency: fix ignore

- doc/developer/design/20320328_persist_columnar.md
[Rendered](https://github.com/ParkMyCar/materialize/blob/columnar/design-doc/doc/developer/design/20320328_persist_columnar.md)
Design for https://github.com/MaterializeInc/materialize/issues/24830
-
> design: Columnar Encodings for Persist

- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/catalog/migrate.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/catalog/transact.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/sequencer/inner/secret.rs
- src/catalog/src/memory/objects.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql-parser/tests/testdata/error
- src/sql/src/catalog.rs
- src/sql/src/plan.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/ddl/connection.rs
- src/sql/src/plan/statement/validate.rs
- src/sql/src/rbac.rs
- src/ssh-util/src/keys.rs
- test/sqllogictest/audit_log.slt
- test/ssh-connection/ssh-connections.td
This removes one usage of the WeirdBuiltinTableUpdates, which is another step towards the multi-subscriber catalog.
The approach taken is to introduce PUBLIC KEY 1 and PUBLIC KEY 2 options for SSH tunnel connections. Users cannot specify these options directly; rather the the planner automatically injects them with the public keys it generates during planning. These keys can then flow through the normal builtin table update channel, where they get reflected in the mz_ssh_tunnel_connections table.
Private keys, which are sensitive, continue to be handled via the secrets controller, external to the catalog.
Fix #28796.
> sql: store SSH TUNNEL public keys in create SQL

- src/adapter/src/coord.rs
This commit removes the log for timing storage usage pruning, since it happens in the background.
> adapter: Remove old log line

- misc/python/materialize/mzcompose/__init__.py
- test/feature-benchmark/mzcompose.py
- test/parallel-benchmark/mzcompose.py
- test/scalability/mzcompose.py
> benchmarks: Disable persist_catalog_force_compaction_fuel

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/github.py
In anticipation of the move to private database-issues
It doesn't yet have the necessary permissions.
> ci: Use private-repo enabled github token for annotations

- src/orchestrator-kubernetes/src/cloud_resource_controller.rs
I'm not sure if more has to be done to actually set the correct values. @pH14 @benesch Can you please check?
Follow-up to #29614
> orchestrator-kubernetes: Remove TODO about owner_references

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
- misc/python/materialize/version_consistency/version_consistency_test.py
This happened due to an entry in `ANCESTOR_OVERRIDES_FOR_CORRECTNESS_REGRESSIONS`.
This change is another, more reliable fix.
> version consistency: improve version matching in ignore filter

- src/compute/src/render/continual_task.rs
- src/compute/src/sink.rs
- src/compute/src/sink/correction.rs
CTs probably want pretty similar behavior around increasing and shrinking capacity to the MV correction buffer, so reuse it.
Touches #28899
> ct: reuse ConsolidatingVec in the continual task sink

- src/adapter/src/coord.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
> controller: Remove unnecessary `mut`s

- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/error.rs
- src/catalog/src/memory/objects.rs
- src/environmentd/src/http/sql.rs
- src/expr/src/scalar.proto
- src/expr/src/scalar.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/array.rs
- src/expr/src/scalar/func/impls/date.rs
- src/expr/src/scalar/func/impls/time.rs
- src/expr/src/scalar/func/impls/timestamp.rs
- src/interchange/src/confluent.rs
- src/repr/src/explain.rs
- src/sql/src/lib.rs
- src/sql/src/plan/error.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/storage-types/src/errors.rs
- test/sqllogictest/alter.slt
- test/testdrive/protobuf-import.td
In some cases, I first added a new discussion item to track the feature request and then updated the error message to reference the discussion item.
In other cases, I removed the issue reference if it wasn't useful anymore or something that users are likely to ask for.
* This PR refactors existing code. In service of the plans to make Github issues private, and use Github discussions for public tracking instead.
> Change all references in user-facing error messages to point to discussions instead of issues

- ci/test/lint-main/checks/check-mzcompose-files.sh
- misc/python/materialize/lint/lint.py
By sorting them it's very easy to see which lint actually contributed to the huge runtime, both locally and in CI. `--no-print-duration` can be specified if you really don't want it. Example output:
```
1 check in ci/test/lint-main/before
✓ [ 0.01s] can-lint.sh
16 checks in ci/test/lint-main/checks
✓ [ 0.01s] check-rust-version.sh
✓ [ 0.10s] check-python-discouraged.sh
✓ [ 0.20s] check-test-history-versioning.sh
✓ [ 0.61s] check-mzcompose-files.sh
✓ [ 1.49s] check-generation.sh
✓ [ 3.81s] check-python-docs.sh
✓ [ 3.84s] check-python-formatting.sh
✓ [ 4.52s] check-shell-files.sh
✓ [ 5.24s] check-rust-test-attributes.sh
✓ [ 8.16s] check-bazel.sh
✓ [ 8.70s] check-cargo.sh
✓ [ 9.97s] check-new-line.sh
✓ [10.00s] check-copyright.sh
✓ [13.09s] check-protobuf.sh
✓ [14.96s] check-python-files.sh …
```
> lint: Print durations by default and sort them

- test/cloudtest/test_replica_restart.py
> cloudtest: Reenable test_crash_clusterd

- misc/python/materialize/checks/mzcompose_actions.py
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/checks/scenarios_zero_downtime.py
- misc/python/materialize/mzbuild.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/service.py
- misc/python/materialize/mzcompose/services/materialized.py
They won't succeed anyway, better to fail the test than time out while uselessly building. Seen in https://buildkite.com/materialize/test/builds/90870
Also retry longer (~1 minute) and not just with a 1s sleep inbetween
> mzbuild: Don't try to build on non-builder CI machines

- src/adapter/src/coord/peek.rs
- src/expr/src/explain/text.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/string.rs
- src/ore/src/str.rs
- src/repr/src/scalar.rs
- test/sqllogictest/regex.slt
Update string formatting to also escape new lines and tabs, such that these characters are not rendered as is.
Fixes #27355. Note the resulting change in the test outputs.
* Added a new String wrapper variant `EscapedStr`. Open to other names for this Struct.
* The `pattern.escaped()` changes should only affect humanized output.
* The change for rending `Datum::String` is more contentious and might have a risk of a backward incompatible change.
* From a cursory look, Datum::String.to_string() is only used in tests and error messages.
* The important uses directly access the inner `str` without using `to_string()`.
* Worth taking a good second look here.
> *: escape new lines and tabs in humanized output

- doc/user/content/sql/create-source/mysql.md
- doc/user/layouts/partials/sql-grammar/create-source-mysql.svg
- doc/user/sql-grammar/sql-grammar.bnf
The preferred EXCLUDE COLUMNS syntax is now released to all regions, so we can clean up the conditional logic in the docs for the old IGNORE COLUMNS syntax.
Circling back on @morsapaes's request in https://github.com/MaterializeInc/materialize/pull/29438#discussion_r1752081437.
> doc/user: remove all references to deprecated IGNORE COLUMNS syntax

- src/compute-types/src/dyncfgs.rs
- src/compute/src/sink/persist_sink.rs
Read-only mode has been working stably in production for several months now.
Touches #27413.
> compute: remove compute_persist_sink_obey_read_only flag

- src/adapter/src/coord.rs
- src/adapter/src/coord/caught_up.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
- src/adapter/src/coord/timestamp_selection.rs
- src/adapter/tests/timestamp_selection.rs
- src/cluster-client/src/lib.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/error.rs
- src/compute-client/src/controller/instance.rs
- src/compute-client/src/controller/replica.rs
- src/compute-client/src/protocol/command.rs
- src/controller/src/lib.rs
This PR moves the compute instance controllers into their own tokio tasks, to decouple the bulk of the compute controller's processing from the coordinator. The top-level `ComputeController` becomes a fat client for the `Instance` tasks that is mostly concerned with pre-validation of controller commands, but is also responsible for acquiring read holds.
To actually decouple the compute controller's processing from the coordinator, it is important that the coordinator doesn't need to block waiting for an `Instance` to process and respond to its commands. This is achieved in a couple ways:
* caching in the `ComputeController` for state that can be inferred solely by observing create/drop commands
* pre-validation, for commands that require waiting only to learn about usage errors
* sharing …
> coord,compute: decoupled compute controller

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenario.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
Commonly seeing them being broken now: https://github.com/MaterializeInc/materialize/pull/29637
> feature-benchmark: Bump threshold limits

- .github/workflows/cla.yml
This breaks Shepherdly, and is not worth the marginal reduction in risk of someone editing away their CLA declaration after the PR is merged. GitHub stores revision history anyway.
By request of @mgreene and @umanwizard.
> cla: don't lock PRs after merge

- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9682#0192213e-a8da-439f-b4d9-060069a4097a.
> version consistency: add ignore regarding timestamp casting

- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Log scale for timeline

- misc/python/materialize/output_consistency/common/configuration.py
- misc/python/materialize/output_consistency/output_consistency_test.py
- misc/python/materialize/output_consistency/runner/test_runner.py
- misc/python/materialize/output_consistency/status/test_summary.py
This should reduce the noise when things break.
Nightly: https://buildkite.com/materialize/nightly/builds/9691
> output consistency: abort run after reaching a certain number of failures

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner/create_continual_task.rs
- src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
- src/adapter/src/optimize.rs
- src/adapter/src/optimize/dataflows.rs
- src/adapter/src/optimize/index.rs
- src/adapter/src/optimize/materialized_view.rs
- src/adapter/src/optimize/subscribe.rs
This will help with continual tasks, which need to inject an entry for
the CT itself before it exists in the catalog, but also it gets us one
step closer to pulling the optimizer into its own crate.
I also switched over a few more `adapter::optimize::*::Optimizer`
structs, but had to leave a few because it gets tricky with
`ExprPrepStyle::OneShot` and `eval_unmaterializable_func`.
> adapter: extract an OptimizerCatalog trait

- .bazelrc
- ci/mkpipeline.py
- ci/mkpipeline.sh
- ci/nightly/pipeline.template.yml
- ci/qa-canary/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/slt/pipeline.template.yml
- ci/test/build.py
- ci/test/pipeline.template.yml
- misc/python/materialize/mzbuild.py
- misc/python/materialize/xcompile.py
This PR improves the speed of builds by reducing the amount of debug info we keep for non tagged builds. Instead of [full debug info](https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo) we generate `line-tables-only`. 
~~I also tried using `/dev/shm` (a temporary filesystem on top of a Ramdisk) for the Bazel sandbox, which improves the startup speed for Bazel actions. While this works when I test on the same EC2 instances it fails in CI. Presumably because CI instances have more running and thus less RAM available.~~ I was able to enable `/dev/shm`, it turns out the CI Builder Docker image by default only mounts a ramdisk with 64MB of space, tuning this fixed the issue.
Improves speed of CI
Review only the last …
> bazel: Tweak build settings, reduce debug info for non-tagged builds

- bin/ci-builder
- misc/python/materialize/test_analytics/config/test_analytics_db_config.py
- misc/python/materialize/test_analytics/test_analytics_db.py
And remove non-existant PRODUCTION_ANALYTICS_MZ_CLI_APP_PASSWORD
> test analytics: Print error message when running locally

- misc/python/materialize/mzcompose/services/clusterd.py
- src/clusterd/ci/entrypoint.sh
- src/clusterd/src/bin/clusterd.rs
- src/service/src/grpc.rs
- test/cluster/mzcompose.py
- test/replica-isolation/mzcompose.py
In the clusterd GRPC server, validate the process' hostname against the hostname in the request URI. This detects cases where the controller connects to a wrong process due to a stale hostname-IP mapping.
Fixes [#28997](https://github.com/MaterializeInc/database-issues/issues/8448)
> grpc: validate hostname

- .bazelrc
Currently broken, workaround suggested by Parker
Failed on main: https://buildkite.com/materialize/test/builds/91125
> bazel: Disable pipelined compilation

- Cargo.lock
- src/balancerd/BUILD.bazel
- src/balancerd/Cargo.toml
- src/catalog-debug/BUILD.bazel
- src/catalog-debug/Cargo.toml
- src/clusterd/BUILD.bazel
- src/clusterd/Cargo.toml
- src/environmentd/BUILD.bazel
- src/environmentd/Cargo.toml
- src/persist-client/BUILD.bazel
- src/persist-client/Cargo.toml
- src/testdrive/BUILD.bazel
- src/testdrive/Cargo.toml
Since we created the v0.118.0 for the in-between release tag, we need to bump this version to keep the Nightly upgrade tests working.
Bumping to v0.118.1-dev.0, rather than v0.119.0-dev.0 because we still want to release v0.118.1 next week.
> release: bump to version v0.118.1-dev.0

- ci/deploy/pipeline.template.yml
Previously the job that would tag Docker images with official version releases was still using tagging Cargo based images. This PR switches them to Bazel.
Use Bazel builds in Prod
> bazel: Switch Deploy job over to use Bazel

- misc/python/materialize/release/cut_release.py
Without this fix:
```bash
bin/cut-release --sha HEAD --version v0.117.2 --remote origin
usage: cut_release [-h] --sha SHA --version VERSION --remote REMOTE
cut_release: error: argument --version: invalid parse value: 'v0.117.2'
```
> cut-release: allow leading 'v' in version strings

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
> ci: Move cloudtest from test to nightly pipeline

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Release `dbt-materialize` v1.8.6. See `CHANGELOG.md` for an overview of the release.
> dbt-materialize: release v1.8.6

- bin/bump-version
This is to make the wildcard also recognize versions of the `*-dev.N` form.
> Fix dev version wildcard in bump-version

- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/lib.rs
Previously, during startup the controller would sequentially truncate
the append-only status history introspection collections. This process
would block startup and take a non-trivial amount of time.
This commit moves the process of truncating some of the status
metrics history introspection sources into the append only background
write task. This truncation no longer blocks startup and happens
completely in the background. This commit also lays the foundation to
move status history truncation into the background.
The remaining two status history introspection sources rely on shared
state with the controller and can't as easily be moved into the
background.
Works towards resolving MaterializeInc/database-issues#8384
> controller: Truncate status history in background

- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/lib.rs
Previously, during startup the controller would sequentially prepare
the differential introspection collections. This process would block
startup.
This commit moves the process of preparing differential introspection
collections into the differential background write task.
Works towards resolving MaterializeInc/database-issues#8384
> controller: Prepare diff collection in background

- ci/builder/requirements.txt
https://github.com/paramiko/paramiko/issues/2419 was fixed and released in Paramiko 3.3.2 and 3.4.1.
> python: update cryptography, paramiko

- bin/ci-builder
- ci/plugins/mzcompose/hooks/post-command
- ci/qa-canary/pipeline.template.yml
- misc/python/materialize/parallel_benchmark/framework.py
- misc/python/materialize/parallel_benchmark/scenarios.py
- misc/python/materialize/util.py
- test/canary-load/mzcompose.py
- test/parallel-benchmark/mzcompose.py
For now there are no guarantees, I want to first see if this works at all and is reasonably stable. Also some extensions still planned.
TODO: Retrigger when i2 has the app password
> parallel-benchmark: Long-running against QA Benchmarking Staging env

- src/catalog/src/durable/persist.rs
Previously, the catalog required a deploy generation when opening in savepoint mode. However, the upgrade checker has no access to a deploy generation and was failing to open a savepoint catalog. Ideally, the upgrade checker would have a deploy generation so that it can test the exact code path that an upgrade would take. For now, we're removing the requirement to unblock the upgrade checker.
> catalog: Remove deploy gen req from savepoint

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/state.rs
- src/persist-proc/src/lib.rs
This flag has been rolled out to 100% in Staging and Prod for a while now and we no longer need it.
Note: This flag will remain in LaunchDarkly until this PR gets released to all environments.
Clean up feature flags.
> persist: Remove 'persist_batch_record_part_format' dyncfg

- ci/mkpipeline.py
- ci/mkpipeline.sh
Noticed not working in https://buildkite.com/materialize/test/builds/91197#01922c2c-3419-4bd1-89f6-d2979f77e033
> ci: Try to fix trimming bazel builds

- misc/python/materialize/mzcompose/__init__.py
- src/ore/src/lgbytes.rs
- src/persist/src/cfg.rs
- src/persist/src/s3.rs
As we chatted about offline, this PR should use just a single `lgalloc` allocation for the entirety of a part in a multi-part GET request, instead of creating new allocations for each chunk of bytes that comes off the wire. This should result in using larger lgalloc size classes and fewer allocations in general.
There's a dyncfg `persist_enable_one_alloc_per_request` which we can disable if something goes wrong, but it defaults to `true`.
Improve memory usage in Persist
Fixes https://github.com/MaterializeInc/database-issues/issues/8516
> persist: Reduce the number of lgalloc allocations in `S3Blob`

- src/adapter/src/coord/caught_up.rs
- src/controller-types/src/dyncfgs.rs
- src/storage-client/src/client.proto
- src/storage-client/src/client.rs
- src/storage-client/src/controller.rs
- src/storage-client/src/metrics.rs
- src/storage-controller/src/history.rs
- src/storage-controller/src/instance.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/sources/kafka.rs
- src/storage-types/src/sources/load_generator.rs
- src/storage-types/src/sources/mysql.rs
- src/storage-types/src/sources/postgres.rs
- src/storage/src/storage_state.rs
Add a new feature flag called `enable_0dt_deployment_sources` which
controls whether 0dt deployment is attempted for source types that
support it.
To start, only Kafka sources will support 0dt deployments. The rationale
is twofold:
* Kafka does not have a notion of replication slots, so it's easy to
have multiple processes reading from the same Kafka topic.
* Only Kafka sources support the upsert envelope, which is the only
source operator that has a meaningful rehydration time. Other source
types (e.g., PostgreSQL) effectively already support 0dt upgrades
because they can do a cold restart from where they left off nearly
instantaneously.
This commit does not begin to tackle the hard parts of 0dt deployments
for Kafka upsert sources (read-only mode for the persist sink,
self-correcting …
> adapter,storage-controller: lay down 0dt scaffolding for sources

- misc/python/materialize/cli/ci_closed_issues_detect.py
Verified that it's green: https://buildkite.com/materialize/nightly/builds/9742
> ci: Don't check issue number in closed issue detection

- misc/python/materialize/parallel_benchmark/framework.py
- misc/python/materialize/parallel_benchmark/scenarios.py
Noticed in https://buildkite.com/materialize/nightly/builds/9738#0192386b-5997-4785-9597-078f07fba6f9
Green run: https://buildkite.com/materialize/nightly/builds/9741
> parallel-benchmark: Fix disabling

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
- test/legacy-upgrade/mzcompose.py
- test/pg-cdc-old-syntax/mzcompose.py
- test/pg-cdc/mzcompose.py
Since it was slow and hasn't been failing recently.
I checked all tests that ran >= 19 minutes, the goal is now for every test to be done in 18 min max. (when having to pull dependencies from dockerhub)
> ci: Parallelize test pipeline more, move one test to nightly

- WORKSPACE
Adds a new sysroot for macOS Bazel builds. The new sysroot is the minimum required set of files necessary to build Materialize and greatly improves sandbox performance by reducing the number of files in the sysroot from ~40,000 to ~4,000, and thus the number of symlinks Bazel needs to create.
Note: the new `-min` sysroot is still created by our toolchains repo, it was added in https://github.com/MaterializeInc/toolchains/commit/4e085a332a4b2efc8042257fbffe1e8d208ddb7f.
Improve the performance of Bazel builds on macOS
> bazel: use minimum sysroot for macOS

- ci/release-qualification/pipeline.template.yml
Seen in https://buildkite.com/materialize/release-qualification/builds/618
Triggered a run for verification: https://buildkite.com/materialize/release-qualification/builds/619
> ci: Work around release qualification errors

- CONTRIBUTING.md
We missed updating our contribution guide after migrating the issues to a private repository. A user was misled by the contribution guide [here](https://github.com/MaterializeInc/materialize/discussions/29786), so updating it to point to GH discussions instead.
@chaas, not sure it makes much sense to encourage contributions (other than bug reports) now that we don't have "good first issues", but maybe you have some more context for future plans that I'm missing.
> Update contribution guidelines to point to GH discussions

- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/state.rs
- src/persist-client/src/iter.rs
- src/persist-client/src/read.rs
- src/persist-types/src/columnar.rs
- test/sqllogictest/persist-fast-path.slt
Part of MaterializeInc/database-issues#7411 - allows reading back data in the structured-data order.
Before this change, we could configure Persist to compact data in the new structured-data order, but when we were consolidating at read time we'd reorder it back to the codec order. This is inefficient, and we'd like to allow callers to rely on the sorted order of data in the future for things like `PARTITION BY`.
This uses the same ordering flag as the compaction side, which is a little weird: when we first flip the flag, we'll start using the new order for the fast-path peeks before there's any meaningful percentage of batch parts in the new order. It's possible we'll want to add fancier knobs for the true rollout, but this is enough to toggle things in CI / staging for now.
> [persist] Allow reading back data in structured order

- src/cluster-client/build.rs
- src/cluster-client/src/client.rs
- src/compute-client/src/controller/instance.rs
- src/compute-client/src/controller/replica.rs
- src/compute-client/src/metrics.rs
- src/ore/src/channel.rs
- src/ore/src/metrics/delete_on_drop.rs
- test/cluster/mzcompose.py
Avoid the use of FuturesUnordered in the compute controller for gathering
responses from replicas. Instead, share a channel with each replica task.
Fixes MaterializeInc/database-issues#8587
> Avoid FuturesUnordered in compute controller

- src/catalog/src/builtin.rs
- test/sqllogictest/privilege_grants.slt
we want to be able to run internal analytics queries on mz_recent_activity_log_redacted
> give mz_analytics select access to a few more builtin views

- doc/user/content/sql/create-sink/kafka.md
- doc/user/content/sql/create-source/kafka.md
Works: https://preview.materialize.com/materialize/29800/sql/create-source/kafka/
> docs: Fix Kafka page having menu on left side open

- src/adapter/src/flags.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/parameters.proto
- src/storage-types/src/parameters.rs
- Extends `partially_truncate_status_history` to truncate via a retention window config variable instead of a `..._last_n` config variable. 
Fixes [#8596](https://github.com/MaterializeInc/database-issues/issues/8596)
Wasn't too sure how to create a test for this since it requires a restart of envd _I think_. I was considering something similar to [the test we use for cluster_replica_metrics](https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/tests/sql.rs#L1383) but I saw it's flakey. Is there a way to create one via `testdrive`?
Here's how I manually tested it:
1. Boot up envd locally as `mz_system` and make sure `mz_cluster_replica_status_history` as entries older than a minute via `select * from …
> storage/adapter: Truncate mz_cluster_replica_status_history via retention window instead of last n entries

- doc/user/content/ingest-data/network-security/privatelink.md
- doc/user/content/integrations/_index.md
- doc/user/content/sql/create-connection.md
- doc/user/content/sql/create-source/mysql.md
The MySQL source is ready for Public Preview, so promoting it in the documentation as a first step. Also documenting support for AWS PrivateLink connections in the source, which was blocked on adding automated cloud tests (now ✅).
@bobbyiliev: could you add the shortcode with the instructions for AWS RDS MySQL (similar to [this one](https://github.com/MaterializeInc/materialize/blob/main/doc/user/layouts/shortcodes/network-security/privatelink-postgres.md))?
> doc/user: promote MySQL to Public Preview

- src/sql/src/pure.rs
- test/testdrive/kafka-alter-source.td
- test/yugabyte-cdc/yugabyte-cdc.td
We can't alter a yugabyte source for now.
Fixes MaterializeInc/database-issues#8576
> storage: disallow ALTER SOURCE for yugabyte sources

- CONTRIBUTING.md
See the category here: https://github.com/MaterializeInc/materialize/discussions/categories/contribute-to-materialize
Part of the migration to github discussions for external tracking.
> Update CONTRIBUTING.md to reference the new Contribute to Materialize GH discussion category

- src/persist-types/src/arrow.rs
Part 2 of #29457 - now that all released versions can handle proto with type info only at the top level, write it in the more compact form.
The upgrade tests are important here - I'll get nightlies going.
> [persist] ProtoArrayData optimization - part two

- test/testdrive/wallclock-lag.td
Seen flaking in https://buildkite.com/materialize/test/builds/91457#0192497a-4937-434f-abe1-91178212bc72
> testdrive: Increase allowed lag for wallclock-lag test

- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/sql/src/pure/error.rs
- test/yugabyte-cdc/yugabyte-cdc.td
Fixes MaterializeInc/database-issues#8575
> storage: check that the connection type matches the source type

- Cargo.lock
- misc/cargo-vet/config.toml
- src/workspace-hack/Cargo.toml
See https://rustsec.org/advisories/RUSTSEC-2024-0376. All I ran was `cargo update --package tonic`
> build: Upgrade tonic dependency

- .bazelrc
`--test_env` and `--test_output` only applies to the test runner, but by gating them behind the `test` action invalidated the cache when switching between `bazel build` and `bazel test`
Better Bazel builds
> bazel: fix cache invalidations

- ci/qa-canary/pipeline.template.yml
Went OoM: https://buildkite.com/materialize/qa-canary/builds/252#0192403c-ffb5-4bc3-8806-98b67eecd87e
> ci: Increase agent size for QA Canary Parallel Benchmark

- doc/user/content/ingest-data/network-security/static-ips.md
We want to provide a list of our static egress IPs. This change adds the IPs directly to the docs, and also provides an example of fetching the IPS via an HTTP request.
Unfortunately we can't only return the results in this request, but it may still be useful. 
These IPs are static and therefore should be safe to put in documentation. 
I have used examples IPs for now rather than the real ranges as we discuss this change.
> add docs for new static ips cidrs

- misc/python/materialize/mzcompose/__init__.py
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/iter.rs
- test/testdrive/coordinator-multiplicities.td
Bundling together some small fixups - see the individual commits & code comments for motivation.
A few minor things as part of the rollout of: https://github.com/MaterializeInc/database-issues/issues/7411
> [persist] Minor structured-data fixes and improvements

- src/adapter/src/catalog/migrate.rs
The migration code made it into v0.118, so we no longer need to keep it around.
Fix #8479.
* This PR finishes adding a known desirable feature.
> adapter: finish migration for mz_cluster_replica_frontiers

- src/adapter/src/catalog/migrate.rs
Remove the SSH tunnel migration added in 3f18f464e, since it's now been present in a release of Materialize.
> adapter: remove SSH tunnel migration

- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/peek.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
- src/controller/src/lib.rs
Change how we forward peek responses from the compute instance to the task
handling the client's request. In the past, the peek needed to traverse
the coordinator's main task before it could be sent to the client. Now, it
is sent directly, and only the life cycle logging still happens on the
coordinator main thread.
Related to #29726, MaterializeInc/database-issues#8383
> Retire peeks independently of the coordinator thread

- ci/test/lint-main/checks/check-mzcompose-files.sh
Follow-up to https://github.com/MaterializeInc/materialize/pull/29819 because `MZ_DEV_CI_BUILDER` is not set locally.
> lint: fix command for local execution

- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner/peek.rs
- src/adapter/src/explain/insights.rs
- src/adapter/src/explain/optimizer_trace.rs
The insights context is only used in some situations, but unconditionally requires 3-4KiB space for the struct. Move it to the heap to half the size of peek-related closures and structs.
> Box insights contexts to save stack space

- misc/python/materialize/mzcompose/__init__.py
This appears to tickle a bug in arrow?
Should keep https://github.com/MaterializeInc/database-issues/issues/8615 from blocking CI - though we still need to track down the bug itself.
> [persist] Disable the lower calculation temporarily in CI

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/continual_task.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner/create_continual_task.rs
- src/adapter/src/lib.rs
- src/catalog/src/memory/objects.rs
This should be enough to get Dennis's initial tests passing.
On restart, we weren't replacing the MV sink with a CT one. We also
weren't swapping out the LocalId placeholders at the right time in an
upcoming PR to add a builtin CT.
Closes database-issues#8591
Touches database-issues#8427
> ct: fix restart bugs by sharing code

- src/compute-types/src/dataflows.rs
- src/compute-types/src/explain/text.rs
- src/compute-types/src/plan.rs
- src/compute-types/src/plan/flat_plan.rs
- src/compute-types/src/plan/interpret/api.rs
- src/compute-types/src/plan/lowering.rs
- src/compute-types/src/plan/transform/relax_must_consolidate.rs
- test/sqllogictest/explain/physical_plan_as_json.slt
In preparation for building the introspection views for attribution, I'm refactoring how we store `LirId`s to make things a bit more uniform.
LIR `Plan`s used to just be an enum where every variant had an `lir_id` field; a `Plan::lir_id()` would pull it out from the appropriate structure. This PR refactors the code so that a `Plan` is a struct holding a `PlanNode` (the old enum) and an `LirId`.
I tried to break up the commits logically, so it may make sense go commit by commit. (The first two are small.)
The third commit---the SLT rewrite---is easier to vet if you ignore whitespace changes.
> [compute] refactor LirId treatment

- misc/python/materialize/mzcompose/__init__.py
- src/compute/src/sink/persist_sink.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/lib.rs
- src/storage/src/render/persist_sink.rs
We're now relying on inline writes to make small batches cheap. This is
already turned off everywhere in staging/prod.
> storage,compute: remove small batch optimization in both persist_sinks

- Cargo.lock
- src/adapter/src/coord.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/error.rs
- src/environmentd/src/http.rs
- src/sql/Cargo.toml
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- src/sql/src/session/vars/value.rs
- test/restart/mzcompose.py
- test/testdrive/session.td
Introduces network policies to MZ via a
simple allow list of CIDRs stored as an SystemVar.
The policy is applied between the protocol layer (http/pgwire) and the adapter layer. PolicyDeny errors are pushed to the user as an L7 error.
> Network policies v0

- Cargo.lock
- misc/cargo-vet/audits.toml
- src/storage/src/sink/kafka.rs
As part of an earlier refactor of mine I switched Kafka sinks to the `BaseProducer` flavor of client which does not automatically poll the `librdkafka` client, a crucial task to ensure that messages like statistics don't pile up. At the same time I didn't ensure poll was called so a slow memory leak was introduced.
The leak is too slow to notice but we finally did notice and so this PR fixes this by switching back to the `ThreadedProducer` that spins up a background thread to take care of regular polls.
> sinks/kafka: use ThreadedProducer to regularly poll librdkafka

- test/canary-environment/macros/create_loadgen_source.sql
- test/canary-environment/models/loadgen/product_category_tbl.sql
- test/canary-environment/models/loadgen/product_tbl.sql
- test/canary-environment/models/loadgen/sales_product_product_category.sql
- test/canary-environment/models/loadgen/sales_tbl.sql
- test/canary-environment/models/loadgen/schema.yml
- test/canary-environment/models/mysql_cdc/mysql_people.sql
- test/canary-environment/models/mysql_cdc/mysql_relationships.sql
- test/canary-environment/models/mysql_cdc/mysql_wmr.sql
- test/canary-environment/models/mysql_cdc/schema.yml
- test/canary-environment/models/pg_cdc/pg_cdc.sql
- test/canary-environment/models/pg_cdc/pg_people.sql
- test/canary-environment/models/pg_cdc/pg_relationships.sql
- test/canary-environment/models/pg_cdc/pg_wmr.sql
- test/canary-environment/models/pg_cdc/schema.yml
- test/canary-environment/models/tpch/schema.yml
- test/canary-environment/models/tpch/tpch.sql
- test/canary-environment/models/tpch/tpch_customer.sql
- test/canary-environment/models/tpch/tpch_lineitem.sql
- test/canary-environment/models/tpch/tpch_orders.sql
- test/canary-environment/models/tpch/tpch_q01.sql
- test/canary-environment/models/tpch/tpch_q18.sql
> tests: create table from source: dbt

- test/canary-environment/models/table/table.sql
This fixes an issue in the dbt definition. It is actually not clear to me how this can ever have worked.
> canary environment: dbt: fix table

- src/adapter/src/coord/sequencer/inner/peek.rs
- src/sql/src/plan.rs
- src/sql/src/plan/statement/dml.rs
The SelectPlan struct optionally stores a copy of the select plan. The
SelectStatement struct is rather large (>2KiB), and because we're using
the SelectPlan struct in async state machines, we multiply the space
required to store the statement. This change boxes the select statement
so it doesn't need space on the stack.
A better implementation would be to conditionally store the statement if
it'll be needed based on the explains enabled. This is not as easy as
we're creating the plan before determining what explain modes are enabled.
w to determine the size of async closures
```
RUSTFLAGS=-Zprint-type-sizes cargo +nightly build -p mz-adapter > print-type-sizes.txt
grep awaitee print-type-sizes.txt | cut -c 45- | sort -n | less
```
Largest async closures before the change:
```
29856 …
```
> Box SelectPlan::select

- src/expr/src/relation/func.rs
- src/expr/src/scalar.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/string.rs
- src/expr/src/scalar/like_pattern.rs
- src/regexp/src/lib.rs
- src/repr/src/adt/regex.rs
- src/sql/src/func.rs
- src/sql/src/plan/statement/ddl.rs
IsLikeMatch stores the pattern next to the regex, but the regex also stores the pattern. Avoid duplication.
This is work towards reducing the size of scalar expressions, reachable here through unary functions.
> Reduce size of IsLikeMatch by 16 bytes

- src/expr/src/relation/func.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/record.rs
- src/interchange/src/avro/schema.rs
- src/interchange/src/envelopes.rs
- src/interchange/src/protobuf.rs
- src/lowertest-derive/src/lib.rs
- src/lowertest/src/lib.rs
- src/pgrepr/src/types.rs
- src/proto/src/lib.rs
- src/repr/src/relation.rs
- src/repr/src/row/encoding2.rs
- src/repr/src/scalar.rs
- src/sql/src/plan/expr.rs
- src/sql/src/plan/lowering.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/typeconv.rs
- src/storage-types/src/sources/envelope.rs
- src/storage-types/src/sources/kafka.rs
Reduce the size of the ScalarType struct from 40 bytes to 32 bytes by boxing a vector. This reduces the size of the largest variant, Record, by 8 bytes with minimal changes to the rest of the system.
Before:
```
print-type-size type: `mz_repr::ScalarType`: 40 bytes, alignment: 8 bytes
print-type-size     variant `Record`: 40 bytes
print-type-size         field `.custom_id`: 16 bytes
print-type-size         field `.fields`: 24 bytes
```
After:
```
print-type-size type: `mz_repr::ScalarType`: 32 bytes, alignment: 8 bytes
print-type-size     variant `List`: 32 bytes
print-type-size         padding: 8 bytes
print-type-size         field `.custom_id`: 16 bytes, alignment: 8 bytes
print-type-size         field `.element_type`: 8 bytes
print-type-size     variant `Record`: 32 bytes …
```
> 32 byte ScalarType

- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/sequencer/inner/create_continual_task.rs
- src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
The `DataSource::Other(DataSourceOther)` variant was meant to house all data sources that were not "managed" by the storage controller. However:
* Collections with a data source of `DataSourceOther::TableWrites` are *very much* managed by the storage controller. They have a special background worker that handles registering them with the txns system and incoming write requests.
* Collections with a data source of `DataSourceOther::Compute` are indeed unmanaged by the storage controller, but the name is overly restrictive. Collections registered as `DataSourceOther::Compute` could just as well be managed by adapter or any other component of the system.
So this commit does away with the `DataSourceOther` type. Instead, we add a top-level `DataSource::Table` variant, for the collections that …
> storage-controller: flatten DataSourceOther

- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/record.rs
- src/proto/src/lib.rs
- src/sql/src/plan/typeconv.rs
Reduce the size of the `CastRecord1ToRecord2` struct from 64 to 56 bytes
by converting the `cast_expres` field from `Vec<_>` to a boxed slice. This
benefits the size of `UnaryFunc` and in turn `MirScalarExpr`.
Before:
```
print-type-size type: `scalar::func::impls::record::CastRecord1ToRecord2`: 64 bytes, alignment: 8 bytes
print-type-size     field `.return_ty`: 40 bytes
print-type-size     field `.cast_exprs`: 24 bytes
```
After:
```
print-type-size type: `scalar::func::impls::record::CastRecord1ToRecord2`: 56 bytes, alignment: 8 bytes
print-type-size     field `.return_ty`: 40 bytes
print-type-size     field `.cast_exprs`: 16 bytes
```
> Reduce the size of CastRecord1ToRecord2 to 56 bytes

- doc/user/config.toml
- doc/user/content/integrations/_index.md
Currently, selecting the page collapses the nav because we use config.toml instead of just adding the frontmatter to the page.
> docs: tools and integration overview page frontmatter fix

- src/proto/src/lib.rs
Between https://github.com/MaterializeInc/materialize/pull/29838 and https://github.com/MaterializeInc/materialize/pull/29854
> Fix merge skew in proto/src/lib.rs

- src/adapter/src/coord.rs
Seen in https://github.com/MaterializeInc/materialize/pull/29745#issuecomment-2394767892
> adapter: but but -> but

- Cargo.lock
- misc/bazel/c_deps/rust-sys/BUILD.protobuf-native.bazel
- misc/cargo-vet/audits.toml
- misc/cargo-vet/config.toml
- src/sql/Cargo.toml
This version of protobuf-native fixes a memory error that presents when compiling with libstdc++. We presently compile with libc++ rather than libstdc++, but better safe than sorry.
* This PR fixes a bug noticed by @ParkMyCar during the bazel migration.
> deps: upgrade to protobuf-native v0.3.2

- test/testdrive/get-started.td
- test/testdrive/materialization-lag.td
- test/testdrive/source-tables.td
See https://github.com/MaterializeInc/database-issues/issues/8625
> testdrive: Disable source-tables.td, get-started.td and end of materialization-lag.td

- ci/test/pipeline.template.yml
- src/proto/src/lib.rs
- test/feature-benchmark/mzcompose.py
Noticed in https://buildkite.com/materialize/test/builds/91713#01925854-db0a-4fcb-9203-5f118643b4a0
This prevents fixing merge skew
> feature-benchmark: Ignore merge skew in test pipeline

- misc/python/materialize/sqlsmith.py
Seen in https://buildkite.com/materialize/nightly/builds/9796
> sqlsmith: Expect new error

- misc/python/materialize/cli/ci_annotate_errors.py
> ci: Fix repo in annotations

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
Seen in https://buildkite.com/materialize/nightly/builds/9803 and https://buildkite.com/materialize/nightly/builds/9786
> feature-benchmark: Ignore optbench message regression

- src/cloud-api/src/client.rs
- src/cloud-api/src/client/cloud_provider.rs
- src/cloud-api/src/client/region.rs
- src/mz/src/bin/mz/command/region.rs
- src/mz/src/command/region.rs
- test/cloud-canary/mzcompose.py
- test/mz-e2e/mzcompose.py
The Cloud Region API will soon default to soft-deletion (deprovisioning). Provide support for existing use-cases by adding a `--hard` flag to the region `disable` subcommand.
[The cloud change](https://github.com/MaterializeInc/cloud/pull/10292) hasn't gone out yet, but since it's additive this won't impact anyone until the cloud change is deployed.
> mz: add support for hard region deletion

- misc/bazel/c_deps/rust-sys/BUILD.protobuf-native.bazel
We have an additive `BUILD.bazel` file for protobuf-native that runs `cxx`. There were some extra unused targets there from previous iteration that are now unused.
Cleanup dead code
> bazel: Small cleanup of protobuf-native `BUILD` file

- doc/user/content/sql/create-sink/kafka.md
- misc/python/materialize/checks/all_checks/sink.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/database.py
- src/sql/src/plan/error.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/scope.rs
- src/sql/src/plan/statement/ddl.rs
- src/storage/src/sink/kafka.rs
- test/testdrive/kafka-sink-partition-by.td
We initially disallowed mixing PARTITION BY with ENVELOPE DEBEZIUM because, when a message representing an update is processed, if columns referenced in the PARTITION BY expression change, it's not clear which partition to send the message to: the PARTITION BY expression could plausibly be computed on either the `before` values or the `after` values for the update.
However, it *is* clear which partition to send the message to if the PARTITION BY expression only refers to columns in the sink's key.  The key columns are, by definition, the same in both the `before` and the `after`.
So, this commit allows this behavior. See the docs and tests enclosed in the patch for details.
> sql,storage: allow using PARTITION BY with ENVELOPE DEBEZIUM

- src/storage-types/src/dyncfgs.rs
This has been the default in production for several months now, but I forgot to update the in-code default such that CI was running without it in most cases.
This was previously done in https://github.com/MaterializeInc/materialize/pull/29600 which was just reverted due to a performance [regression](https://github.com/MaterializeInc/database-issues/issues/8628), so I will also run the feature-benchmark to determine if this caused the memory increase or the speedup.
> storage/upsert: Default the upsert rocksdb merge operator flag to true

- src/adapter/src/coord.rs
- src/dyncfg/src/lib.rs
- Allow self to show up in `uses` for CTs, which can be self-referential (found in #29745).
- Support "on" and "off" as bool values in dyncfg. This seems to be what we're getting from LD on the initial parameter sync? This parse method is used in balancerd, but AFIAK not previously in environmentd/clusterd, so could just be an oversight
> ct: small bug fixes

- src/environmentd/src/bin/environmentd/main.rs
This commit adds a `--scratch-directory` argument to environmentd. This argument is currently unused but will eventually be used in the adapter for ephemeral storage. We're adding the unused argument to unblock cloud from wiring up storage on their side.
> adapter: Add scratch directory argument

- src/aws-util/Cargo.toml
- src/aws-util/src/s3_uploader.rs
- src/storage-operators/src/s3_oneshot_sink.rs
- src/storage-operators/src/s3_oneshot_sink/parquet.rs
- src/storage-operators/src/s3_oneshot_sink/pgcopy.rs
- test/testdrive/copy-to-s3-minio.td
This makes it easier to distinguish between when an export was successful but produced no rows and when an export failed.
Fix MaterializeInc/database-issues#8599.
> storage/copy-to-s3: emit empty file even if input is empty

- misc/python/materialize/output_consistency/ignore_filter/internal_output_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9850#0192685c-ce86-4c08-a4a0-4917cf830ac7.
```
ERROR_MISMATCH: Error message differs.
Expression: map_agg(chr(uint2_zero), justify_days(interval_min_val) ORDER BY row_index, justify_days(interval_min_val))
Value 1 (Dataflow rendering): '"-178956970 years -8 months -2147483648 days -2562047788:00:54.775808" interval out of range' (type: <class 'str'>)
Value 2 (Constant folding): 'null character not permitted' (type: <class 'str'>)
Query 1: SELECT map_agg(chr(uint2_zero), justify_days(interval_min_val) ORDER BY row_index, justify_days(interval_min_val)) FROM t_dfr_horiz;
Query 2: SELECT map_agg(chr(uint2_zero), justify_days(interval_min_val) ORDER BY row_index, justify_days(interval_min_val)) FROM v_ctf_horiz;
Expression hash: …
```
> output consistency: add ignore regarding evaluation order

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/9849#0192680a-0d37-4eea-8052-fa195d413a58.
```
CONTENT_MISMATCH: Value differs at row index 0, column index 2.
Expression: (row(bpchar_8_null) IS NULL)
Value 1 (Materialize evaluation): 'False' (type: <class 'bool'>)
Value 2 (Postgres evaluation): 'True' (type: <class 'bool'>)
Query 1: SELECT (bpchar_8_null IS NULL), mod(decimal_39_0_tiny, decimal_39_8_null), (row(bpchar_8_null) IS NULL), (uuid_val_3 <> uuid_val_3) FROM t_dfr_horiz;
Query 2: SELECT (bpchar_8_null IS NULL), mod(decimal_39_0_tiny, decimal_39_8_null), (row(bpchar_8_null) IS NULL), (uuid_val_3 <> uuid_val_3) FROM t_pg_horiz;
Expression hash: 14805525798944107227
```
Filed issues
* https://github.com/MaterializeInc/database-issues/issues/8632
> postgres consistency: add ignore for IS NULL on record with NULL value

- src/storage/src/render.rs
- src/storage/src/render/sources.rs
- src/storage/src/source/source_reader_pipeline.rs
Fixes a bug we discovered when working on https://github.com/MaterializeInc/materialize/pull/29600 but since that PR was reverted today for CI flakiness, this PR just re-introduces the fix for the bug.
The issue was that we always provided primary shard id to the persist source for every export of a source, which works when there is only ever one upsert source-export for a source but breaks as soon as more than one export is possible. The fix is to correctly provide the specific export's id to the persist source for each export dataflow.
> storage/sources: Fix source rendering persist source id argument bug

- src/storage/src/render/sources.rs
Before, we were using the overall ingestion CollectionMetadata, which is not correct. I noticed this while working on a branch that changes the upsert operator, and when working with the new CREATE SOURCE / CREATE TABLE FROM SOURCE syntax.
> storage: use per-export CollectionMetadata for source export

- doc/user/config.toml
- doc/user/content/_index.md
- doc/user/content/releases/previews.md
- doc/user/content/serve-results/s3.md
- doc/user/content/serve-results/snowflake.md
S3 bulk exports are ready for Public Preview, so promoting it in the documentation after enabling the feature flag across all environments.
> doc/user: promote bulk exports to Public Preview

- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/read.rs
- src/persist-client/src/usage.rs
- src/persist-client/src/write.rs
- src/persist-types/src/arrow.rs
- src/persist/src/indexed/columnar/arrow.rs
- src/persist/src/indexed/columnar/parquet.rs
- src/persist/src/metrics.rs
Workaround for https://github.com/MaterializeInc/database-issues/issues/8615 - see that issue for more details on the upstream bug.
I've rolled this into `realloc`, since that is already doing a deep traversal / replacement of the incoming data. If we're uncomfortable with that I could do something more targeted. (eg. a separate method that we only called on parquet reads and only touched the null buffer.)
As part of investigating this issue I noticed that we weren't reallocating our structured data in all cases. (As part of reallocation, we run validations that would have caught this bug much earlier!) I've added a second commit that performs the reallocation up front.
> [persist] Drop unnecessary null buffers while reallocating

- misc/python/materialize/parallel_benchmark/scenarios.py
- test/canary-load/mzcompose.py
This addresses
```
> SELECT COUNT(DISTINCT a_name) FROM qa_canary_environment.public_pg_cdc.wmr WHERE degree > 10 rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 111s 166s 101s ^^^ +++ 9:1: error: preparing query failed: db error: ERROR: unknown catalog item 'qa_canary_environment.public_pg_cdc.wmr': ERROR: unknown catalog item 'qa_canary_environment.public_pg_cdc.wmr'      |    8 |     9 | > SELECT COUNT(DISTINCT a_name) FROM qa_canary_environment.public_pg_cdc.wmr WHERE degree > 10      | ^ +++ !!! Error Report 1 errors were encountered during execution source: /var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-01444d5464d99fc66-1/materialize/qa-canary/test/canary-load/mzcompose. …
```
> canary environment: update queries

- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/catalog/consistency.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/catalog/transact.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/src/memory/objects.rs
This revisits the discussion from a previous PR here https://github.com/MaterializeInc/materialize/pull/29749#discussion_r1777169138 by switching back to storing the `source_references` map as its own `CatalogState` field rather than including as a sub-field of the relevant `Source` object. This now closely mirrors the durable catalog state which stores the `source_references` field separately, too.
The reason I switched back to this approach is that it's difficult to reason about this logic if the durable catalog structure is different than the in-memory catalog structure since it requires extra handling to ensure the source-field is kept in-sync with the durable catalog field.
It also resulted in broken catalog consistency checks whenever a source object was renamed, and I could have …
> adapter/catalog: Switch back to storing available source_references as separate in-memory catalog map

- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/read.rs
- src/persist-client/src/usage.rs
- src/persist-client/src/write.rs
- src/persist-client/tests/machine/empty_since
- src/persist-client/tests/machine/gc
- src/persist-client/tests/machine/regression_listen_compaction
- Add a metric for the number of parts written in each ordering.
- Add a flag for rolling out structured ordering shard-by-shard... might not need it but also it might be useful.
- Also removes the `writer_id` argument, which is long unused. (Probably should have been a separate commit...)
Useful for the rollout of: https://github.com/MaterializeInc/database-issues/issues/7411
Deployed to staging, and checked that the metrics show up and that changing the system var changes the ratio of codec-ordering to structured-ordering at write time.
> [persist] A couple useful features for the structured data rollout

- src/adapter/src/coord.rs
- src/adapter/src/coord/appends.rs
- src/adapter/src/coord/message_handler.rs
> adapter: Remove dead code

- src/compute/src/render/continual_task.rs
- test/sqllogictest/ct_liveness.slt
The `state.output_progress` field is meant to track the largest value
we've seen for the output shard's upper. This fixes two cases where this
was failing to happen (which was causing the hangs in my latest attempt
to get Dennis's initial tests passing):
- One if the write is before the current upper (received via pubsub from
the `shared_upper` call immediately before the loop).
- Another if we got an expectation mismatch.
The first two commits are the new tests added in #29745.
> ct: fix bug in sink impl

- ci/builder/requirements.txt
- ci/test/pipeline.template.yml
- misc/python/materialize/test_analytics/connector/test_analytics_connector.py
- test/balancerd/mzcompose.py
To get `https://github.com/psycopg/psycopg/pull/670`
> tests: Upgrade psycopg3 version

- src/sql/src/pure.rs
- src/storage/src/render/sources.rs
- src/storage/src/source/generator.rs
- src/storage/src/source/generator/key_value.rs
- src/storage/src/upsert.rs
- test/testdrive/source-tables.td
Reintroduces the key-value load-generator refactoring first introduced in https://github.com/MaterializeInc/materialize/pull/29600/
This also reintroduces *some* of the upsert operator refactoring from that PR. This refactoring was necessary to allow sources to have more than one export where at least one of them uses the upsert operator and resume at different resume_uppers.
However, that original PR did more than was actually necessary to make this work and it also introduced a memory regression.
The original PR refactored the source operator feedback control to use the `SignaledFuture` semaphore method, but that was not actually necessary for this change (though it is probably still worth doing, separately).
Instead, this PR just refactors the persist source feedback. The upsert …
> storage/sources: Refactor key-value load generator to support multiple source exports and upsert persist source feedback

- src/testdrive/src/bin/testdrive.rs
This was introduced in f59bb910850e6b8383e7ffb6e65c427cfabc367d, which doesn't mention "off" being particularly intentional. Start the game of whack-a-mole by turning this on to warn and seeing what spammy modules need to be overridden back to "off".
> testdrive: replace default "off" log filter with more targeted disables

- src/adapter/src/coord/sequencer/inner/create_continual_task.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement/ddl.rs
- test/sqllogictest/ct_errors.slt
The numbers correspond to which [milestone] that they need to be fixed by.
[milestone]: https://github.com/MaterializeInc/database-issues/issues/8427
The priority here is finding if there are any M1 items left, would love a second set of eyes on this in particular. Some of the M2 vs M3 decisions feel like they could go either way, definitely open to feedback.
> ct: triage all currently remaining TODO(ct)s in adapter

- src/expr/src/scalar.rs
- src/transform/src/analysis/equivalences.rs
In incident-217, PolarSignals showed that making the local copies in `reduce_safely` accounts for 80+% of CPU time during the optimizer hang. This PR pulls that out to the beginning of `minimize`, so that we do it only once per `minimize`, instead of once per `minimize_once` _and per class_. There were thousands of classes in the incident, so this reduces this overhead by several orders of magnitudes. On the ["smaller repro"](https://docs.google.com/document/d/10GuKeUcmK-LIRWc4EEro7jZHz5v1z-MwhQOB4PXOzK8/edit?usp=sharing), this results in a ~2x speedup end-to-end in debug mode on my laptop.
I wrote two versions. The one in the PR is slightly more complex, but it also incorporates the optimization from @antiguru, that we don't allocate a new Vec if everything is already nullable. This …
> Do the nullability tweaking in `EquivalenceClasses::minimize` only once

- src/aws-util/Cargo.toml
- src/aws-util/src/s3_uploader.rs
- src/storage-operators/src/s3_oneshot_sink.rs
- src/storage-operators/src/s3_oneshot_sink/parquet.rs
- src/storage-operators/src/s3_oneshot_sink/pgcopy.rs
- test/testdrive/copy-to-s3-minio.td
This reverts commit 27d38e9cad582f84585e87dfce362a760b0173ed.
Fixes MaterializeInc/database-issues#8634.
* This PR fixes a potential regression.
> Revert "storage/copy-to-s3: emit empty file even if input is empty"

- src/adapter/src/coord.rs
Previously, the adapter would block on cleaning up orphaned secrets during startup. This was unnecessary, so this commit moves the secret cleanup into the background.
Works towards resolving #MaterializeInc/database-issues/issues/8384
> adapter: Cleanup orphaned secrets in background

- src/adapter/src/coord.rs
This commit has a small optimization for `bootstrap_tables` that appends to tables and interacts with the timestamp oracle concurrently.
Works towards resolving #MaterializeInc/database-issues/issues/8384
> adapter: Optimize table bootstrapping

- src/adapter/src/coord/sequencer/inner.rs
- src/catalog/src/memory/objects.rs
- src/compute-client/src/as_of_selection.rs
- src/sql/src/catalog.rs
- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/lib.rs
Fixes https://github.com/MaterializeInc/database-issues/issues/8600
Fixes the above issue which occurs when a CSR / Schema Registry connection is altered and a reference to that connection is stored inside the `data_config` / `encoding` settings for a `CREATE TABLE .. FROM SOURCE .. FORMAT AVRO .. ` statement.
This connection change should trigger updates to the underlying ingestions in the Storage Controller to re-render any sources as necessary.
> storage: Correctly handle dependencies on CSR connections from source tables when a connection is altered

- misc/python/materialize/mzcompose/__init__.py
- src/adapter/src/coord.rs
- src/storage-controller/src/lib.rs
Hack to make as_of selection happy. It assumes that anything with a zero
upper has the since set to the initial as_of. Ideally we'd write this
down in the durable catalog, but that's hard because of boot ordering
and it's possible that a better long-term fix would be in as_of
selection itself.
Touches MaterializeInc/database-issues#8631
Full transparency, this is a bit [science dog](https://knowyourmeme.com/memes/i-have-no-idea-what-im-doing).
> ct: add hack to set an initial since for the builtin CT collection

- misc/python/materialize/mzcompose/__init__.py
- src/persist-client/src/internal/machine.rs
- src/persist-proc/src/lib.rs
Additional test coverage for https://github.com/MaterializeInc/database-issues/issues/7411.
> [persist] Structured testing update, round 2

- doc/developer/guide.md
- doc/user/content/get-started/install-materialize-emulator.md
- misc/images/materialized/README.md
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/service.py
- test/cluster/README.md
By default docker's port bindings will bind to all available network addresses (0.0.0.0). If you are running insecure services (as we are in testing) and there is no firewall in front of it, anyone can connect to those services. This does not affect our CI since we are blocking incoming connections there anyway, but can be relevant when you run tests locally.
> mzcompose: Only bind to localhost

- ci/nightly/pipeline.template.yml
Seen timing out in https://buildkite.com/materialize/nightly/builds/9927#01927a1f-4abc-4942-aa1c-f907df87eb89
> ci: Bump timeout for Kafka smoke test

- misc/python/materialize/cli/ci_coverage_pr_report.py
This should address
```
File "/var/lib/buildkite-agent/builds/hetzner-aarch64-16cpu-32gb-7bbedb06/materialize/coverage/misc/python/materialize/cli/ci_coverage_pr_report.py", line 99, in mark_covered_lines
assert result, f"Unexpected file {content}"
^^^^^^
AssertionError: Unexpected file bazel-out/aarch64-opt/bin/external/crates_io__chrono-tz-0.8.1/_bs.out_dir/timezones.rs
```
observed in https://buildkite.com/materialize/coverage/builds/445#019277ed-7c4d-4f2c-901a-527f73039a73.
https://buildkite.com/materialize/coverage/builds?branch=nrainer-materialize%3Acoverage%2Ffix-computation
> coverage: Adapt file paths to bazel

- src/adapter/src/coord.rs
- src/adapter/src/coord/appends.rs
- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/sql.rs
Previously, the adapter would block startup waiting for all updates to
builtin tables to complete. This commit moves this process to the
background and does not block waiting for the writes to complete.
However, we do block on applying the write timestamp with the timestamp
oracle. So anyone in Strict Serializable mode will have to wait until
the writes are complete to read the builtin tables. If someone is in
Serializable mode, they may be able to view the table in a state from
the previous version. This is technically correct, though maybe
slightly undesirable.
Works towards resolving #database-issues/issues/8384
> adapter: Update builtin tables in background

- misc/python/materialize/mzcompose/composition.py
(I shouldn't have just tested https://github.com/MaterializeInc/materialize/pull/29959 locally)
Proof:
> tests: Fix missing dash

- src/orchestratord/Cargo.toml
Seen in https://buildkite.com/materialize/nightly/builds/9938#01927c64-2ee4-4202-b1bb-75f7513fa51c
```
`mz-orchestratord v0.120.0-dev.0 (/var/lib/buildkite-agent/builds/hetzner-aarch64-8cpu-16gb-3baf4980/materialize/nightly/src/orchestratord)`
└─── dependencies
├─── "mz-alloc"
├─── "mz-alloc-default"
└─── "workspace-hack"
```
@doy-materialize Does this make sense?
Follow-up to https://github.com/MaterializeInc/materialize/pull/29922
> unused deps: Fix mz-orchestratord

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
Seen failing in https://buildkite.com/materialize/release-qualification/builds/627#01927989-33ea-448b-af26-6ef13de7d27e
Verifying: https://buildkite.com/materialize/release-qualification/builds/628
> feature-benchmark: fix message filtering, clusterd memory computation, ReplicaExpiration scenario

- ci/test/pipeline.template.yml
Seen failing in https://buildkite.com/materialize/test/builds/92257#019289c6-db00-450a-8759-8537965919ab
It appears to be OoM during `git clone` internal to `buf`. As an alternative we could run the checks in series instead of in parallel in CI, but I prefer to get results faster. The cost is negligible anyway for such a fast step.
> ci: Increase agent size for fast lint

- src/compute-client/src/protocol/history.rs
This PR replaces the `read_only` flag in the compute history, which tracks whether an `AllowWrite` command should be emitted after a reduction, with a `write_only` flag. This gives a slight readability improvement and consistency with the storage command history.
Follow-up from a discussion in https://github.com/MaterializeInc/materialize/pull/29699
> compute: history: flip read_only flag

- misc/python/materialize/output_consistency/data_value/data_column.py
- misc/python/materialize/output_consistency/data_value/data_value.py
- misc/python/materialize/output_consistency/expression/constant_expression.py
- misc/python/materialize/output_consistency/expression/expression.py
- misc/python/materialize/output_consistency/expression/row_indices_expression.py
- misc/python/materialize/output_consistency/generators/expression_generator.py
- misc/python/materialize/output_consistency/input_data/operations/aggregate_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/array_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/list_operations_provider.py
- misc/python/materialize/output_consistency/input_data/operations/map_operations_provider.py
- misc/python/materialize/output_consistency/input_data/params/row_indices_param.py
- misc/python/materialize/postgres_consistency/custom/predefined_pg_queries.py
Fix framework issue `column reference "row_index" is ambiguous` in generated queries:
```
SELECT
array_agg(s0.bpchar_8_val ORDER BY row_index, s0.bpchar_8_val)
FROM
<source>_vert_0 s0
FULL OUTER JOIN <source>_vert_3 s3
ON TRUE::BOOL
WHERE (s0.row_index IN (7, 9));
```
> output consistency: fix ambiguous row index

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/executor.py
- misc/python/materialize/feature_benchmark/measurement.py
- misc/python/materialize/feature_benchmark/scenario.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
- misc/python/materialize/test_analytics/data/feature_benchmark/feature_benchmark_result_storage.py
- test/feature-benchmark/mzcompose.py
Hasn't been very useful so far. Slack discussion: https://materializeinc.slack.com/archives/C01LKF361MZ/p1728891862180139
Previous instance where it wasn't particularly useful: https://github.com/MaterializeInc/database-issues/issues/7575
> feature-benchmark: Don't measure messages

- ci/nightly/pipeline.template.yml
Docker pull is still sometimes slow, seen in https://buildkite.com/materialize/nightly/builds/9951#01928084-3b54-4c94-8bf1-8e6ed1ed7d92
> ci: Bump some timeouts

- ci/test/pipeline.template.yml
- test/sqllogictest/materialized_views.slt
We had a few timeouts recently:
* https://buildkite.com/materialize/test/builds/92290
* https://buildkite.com/materialize/test/builds/92268
* https://buildkite.com/materialize/test/builds/92240
* https://buildkite.com/materialize/test/builds/92231
> ci: increase timeout of SLT logic tests

- Cargo.lock
- misc/cargo-vet/audits.toml
Updates to the latest versions of the dependencies. No functional changes included, which is why our code compiles unchanged.
Timely: https://github.com/MaterializeInc/timely-dataflow/commit/460f95b3dfb103f3fa444a4ef6eefb161a617c7e
Differential: https://github.com/MaterializeInc/differential-dataflow/commit/ea2e3e13bbd5cdd31f60f091a3625d954d7347f8
> Update timely and differential

- src/adapter/src/coord/caught_up.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
- src/compute/src/render/continual_task.rs
Turns out that we initialize the collection upper to the latest upper when bootstrapping, so the caught-up check would always see compute collections as caught up.
Now, we additionally check that they are hydrated, meaning that we have heard back at least one frontiers/uppers response back from the cluster/replicas.
> adapter/0dt: check hydration status in new-style caught-up check

- misc/python/materialize/test_analytics/data/parallel_benchmark/parallel_benchmark_result_storage.py
Can happen if only one query run. Seen in https://materializeinc.slack.com/archives/C05CQUVHY48/p1728968596628669
> parallel-benchmark: Ignore nan in standard deviation

- ci/test/pipeline.template.yml
Seen in https://buildkite.com/materialize/test/builds/92346#01928f18-740d-4ad7-a92d-09b353df7b46
> ci: Increase parallelism for Pg CDC resumption tests

- misc/python/materialize/parallel_workload/executor.py
Seen failing in https://buildkite.com/materialize/nightly/builds/9981#01928efa-83ec-4264-87ca-7e32abcd3c79
```
ValueError: too many values to unpack (expected 1)
```
> parallel-workload: Handle commit properly

- misc/python/materialize/output_consistency/validation/result_comparator.py
This addresses https://buildkite.com/materialize/nightly/builds/9971#01928d01-7df1-4708-8da2-ead1d2d46c45:
```
builtins.TypeError: '<' not supported between instances of 'dict' and 'dict'
```
> output consistency: fix value ordering error

- ci/plugins/mzcompose/hooks/command
Seen failing in https://buildkite.com/materialize/test/builds/92367#01928ff9-c031-4630-813f-0f648268bcd7
> ci: Retry first dockerhub pull for ci-builder

- src/sql/src/normalize.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement/ddl/connection.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/plan/statement/scl.rs
This PR updates the `generate_extracted_config!` macro so rust-analyzer no longer shows errors for invocations of the macro. The issue was rust-analyzer was resolving traits implementations incorrectly so we fully qualify some trait method calls to help it out. This makes the macro a bit less flexible by requiring the `value` field of a SQL `WITH` option be an `Option<WithOptionValue<T>>`, but all uses of it today are exactly that type, so I don't anticipate any issue.
rust-analyzer (used in IDEs) would show an error for invocations of this macro, even though the code compiled without issue.
> sql: Fix `generate_extracted_config!` macro for rust-analyzer

- doc/user/config.toml
- doc/user/content/ingest-data/mysql/_index.md
- doc/user/content/ingest-data/postgres/_index.md
In Ingest data, make MySQL and Postgres landing pages - instead of having separate Overview page.
Future work will involve making Ingest data also a landing page with meaningful content, instead of just a list of content.
> docs: tweak ingest-data menu for mysql/postgres

- doc/user/config.toml
Hugo defaults to creating Categories and Tags pages as part of its default taxonomies -- https://gohugo.io/content-management/taxonomies/#default-taxonomies -- which is what builds the following pages:
https://materialize.com/docs/tags/
https://materialize.com/docs/categories/
> docs: suppress default creation of Categories and Tags docs pages

- test/testdrive/materialization-lag.td
Fixes: https://github.com/MaterializeInc/database-issues/issues/8626
> testdrive: Revert limited load generator for materialization-lag.td

- test/testdrive/source-statistics.td
Caused failure in https://buildkite.com/materialize/nightly/builds/9968#01928c36-2385-4371-9f90-de38897767d4
```
source-statistics.td:119:1: error: non-matching rows: expected: [["auction_house_in_source_statistics_td", "true", "true", "false", "false", "true", "true"]] got:
[["auction_house_in_source_statistics_td", "true", "true", "false", "false", "true", "false"]]
```
> testdrive: No limit in source-statistics.td load gen

- src/catalog/src/memory/objects.rs
- src/sql/src/catalog.rs
- src/sql/src/plan/query.rs
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8640
We discovered this issue during the demo of `CREATE TABLE .. FROM SOURCE` statements today.
> adapter: Prevent DML statements on source tables

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/transact.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
Previously, creating a cluster collections would execute 3 catalog transactions. One to allocate the cluster ID, one to allocate the introspection source IDs, and to create the cluster. This commit combines the introspection source IDs transaction and cluster creation transaction into a single catalog transaction.
> catalog: Allocate intro sources IDs in single txn

- WORKSPACE
Previously we've seen the upstream GNU FTP server go down which breaks CI. This uses the new Mirror action in our [MaterializeInc/toolchains](https://github.com/MaterializeInc/toolchains/actions/workflows/mirror.yml) repo to mirror the source code.
Improve stability of CI
> bazel: Updates our version of `rules_foreign_cc` to include a mirror for the make-4.2 source

- misc/bazel/tools/repositories.bzl
We've been getting some flakes in CI recently for exit code 32 when trying to run `buildifier`. I asked about this in the [Bazel Slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1729021370076269) and figured in the meantime it wouldn't hurt to add a mirror for `buildifier`, in case the issue is being rate limited by upstream.
I added a new [Mirror action](https://github.com/MaterializeInc/toolchains/actions/workflows/mirror.yml) to our toolchains repo that powers this.
Stabilize CI
> bazel: Mirror `buildifier` the Bazel formatter

- src/sql-parser/src/ast/defs/ddl.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/pure.rs
When sinks learned to take separate key and value formats (#27982), the logic for purification didn't get wired up quite right for the case where both the key and value format required purification.
This is necessary prep work for supporting EXCLUDE COLUMNS for sinks (MaterializeInc/database-issues#8160).
The issues fixed here are such edge cases that I'm not fussed about adding test cases for them in this commit. I'll add some test cases in a future refaactoring PR to provide broad coverage of separate key/value formats.
* This PR refactors existing code in preparation for a new feature.
> sql: fix purification of sinks with separate key/value formats

- WORKSPACE
This accidentally got lost when we upgraded to `rules_rust v0.51.0`
Hermetic Bazel Builds
> bazel: Add integrity for `rules_rust`

- ci/test/pipeline.template.yml
Seen timing out in https://buildkite.com/materialize/test/builds/92404#01929122-b0ca-4678-88b6-0c07153b0f3f
> ci: Bump agent size for replica isolation

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
Also add logging to make it easier to find slow scenarios in the future
New run: https://buildkite.com/materialize/nightly/builds/9998
> feature-benchmark: Reduce scale of extremely slow scenarios

- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenario.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
Flaking in nightly and tests pipeline a lot, see for example: https://buildkite.com/materialize/nightly/builds/9997#0192913f-3e43-4d46-9fbd-d8b3c65a3cb3
Since we didn't measure clusterd memory at all before, this is still an improvement compared to last week
> feature-benchmark: Bump memory clusterd threshold

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
Timed out in https://buildkite.com/materialize/test/builds/92453#01929252-72e7-4efa-9385-25b8f809290d
> ci: Bump agent for pg cdc resumption test

- test/testdrive/alter-sink.td
Not happy with this solution, but there is no good way to wait for the event
Fixes: https://github.com/MaterializeInc/database-issues/issues/8636
> testdrive: Increase sleep for flaky alter-sink.td

- src/storage-types/src/connections.rs
This addresses https://github.com/MaterializeInc/database-issues/issues/8653.
Get rid of
```
[2m2024-10-11T06:09:53.863297Z[0m [31mERROR[0m [2mmz_adapter::catalog::builtin_table_updates[0m[2m:[0m failed writing row to mz_aws_connections table [3mid[0m[2m=[0ms759 [3me[0m[2m=[0minternal error: no AWS external ID prefix configured
```
> testdrive: get rid of failed writing row to mz_aws_connections table

- ci/qa-canary/pipeline.template.yml
- misc/python/materialize/parallel_benchmark/framework.py
- test/parallel-benchmark/mzcompose.py
Seems not to cause a performance difference, but lacks some features currently
> parallel-benchmark: Store data in SQLite for long runs

- src/adapter/src/coord.rs
- src/adapter/src/notice.rs
- src/orchestrator/src/lib.rs
This PR adds an new offline reason for cluster replicas of "initializing". When the DDL that creates a new cluster replica completes, that replica starts with a status of `offline` and a `reason: null`, once Kubernetes creates the replica it gets updates to a status of `online`.
This change should make that initializing period more obvious.
We recently saw an issue where the `mz_internal.mz_cluster_replica_statuses` history was incorrect, and I'm hoping this PR should help us debug the issue a bit further if we see it again. ([Slack](https://materializeinc.slack.com/archives/CTESPM7FU/p1728918400855429?thread_ts=1728914425.382739&cid=CTESPM7FU))
> adapter: Add `OfflineReason::Initializing` for cluster replicas

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/normalize.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- test/testdrive/source-tables.td
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8597
The issue above highlighted that the new `CREATE TABLE .. FROM SOURCE` statements did not allow the specification of column-names that we currently allow in `CREATE SOURCE` statements for some source types (Kafka sources and single-output load-generator sources).
This PR refactors our SQL parsing and purification/planning logic to accommodate this behavior.
> storage/sources: Allow user-specified column names in CREATE TABLE FROM SOURCE statements

- src/compute/src/render.rs
- src/compute/src/render/continual_task.rs
We we running the `step_backward` operator before
`suppress_early_progress`, which made the frontiers not directly
comparable to the `as_of` given to `suppress_early_progress`. Similarly,
we were reporting incorrect input frontiers (no idea what effect this
has).
This is the easy fix (swap `step_backward` to be later), but adding this
this to the increasing pile of evidence against the weirdness of the
`T-1` idea. While Jan was out, I had an idea for how to make this all
[more normal], but I've been holding off on doing anything it until he
was back. Probably time to hash that out, but since this fix is so
simple, I'd love to get it merged in the interim.
[more normal]: https://materializeinc.slack.com/archives/C075B00521K/p1727808293914569
Touches …
> ct: fix bugs in frontier reporting

- src/compute/src/sink/persist_sink.rs
- src/persist-client/src/internal/metrics.rs
This was left over after removing the small-batches optimization in #29846.
> compute/persist_sink: remove some dead code

- .bazelrc
- misc/bazel/cargo-gazelle/src/args.rs
- misc/bazel/tools/BUILD.bazel
- misc/python/materialize/cli/bazel.py
This PR switches `bin/bazel gen` to run cargo-gazelle with Bazel instead of Cargo. This should provide the following benefits:
* Faster linting in CI, `cargo-gazelle` can be pulled from the remote cache instead of built locally.
* More stable execution. Gets rid of the `HACK` to make sure `buildifier` was already downloaded, hopefully fixing the flakiness we've seen recently.
It also adds a config to our `.bazelrc` called `script` which reduces output and makes running Bazel actions less noisy.
Note: We already effectively ran `bin/bazel gen` with Bazel previously since we required it to run the BUILD file formatter, so I don't expect this to impact developers much if at all.
Linting has been flaking in CI lately, this should help stabilize it.
> bazel: Run `cargo-gazelle` with Bazel

- ci/mkpipeline.py
Everything uses the Bazel builds, so we can skip the Cargo builds, if no Sanitizer is specified.
Reduce cost of CI
> build: Trim the Cargo builds of Materialize if no Sanitizer is specified

- ci/test/build.py
Previously I switched our main `build.py` script that CI uses to call `llvm-dwarfdump` via `xcompile.py` or Bazel. What I didn't realize is `llvm-dwarfdump` isn't in our xcompile toolchain which prevents Cargo driven builds of Materialize from generating a source tarball. The fix is to just directly call `llvm-dwarfdump` which exists in the CI builder image.
Note: Primarily we use Bazel to build Materialize but Cargo builds still exist for when we want to build with Sanitizers
Fixes https://github.com/MaterializeInc/database-issues/issues/8652
> build: Fix `llvm-dwarfdump` usage

- src/compute-types/src/sinks.rs
- src/compute/src/render.rs
- src/compute/src/render/continual_task.rs
- src/compute/src/render/sinks.rs
The numbers correspond to which [milestone] that they need to be fixed by.
[milestone]: https://github.com/MaterializeInc/database-issues/issues/8427
The priority here is finding if there are any M1 items left, would love a second set of eyes on this in particular. Some of the M2 vs M3 decisions feel like they could go either way, definitely open to feedback.
> ct: triage all currently remaining TODO(ct)s in compute

- misc/images/materialized-base/Dockerfile
- misc/images/materialized/Dockerfile
- misc/images/materialized/entrypoint.sh
Creating the necessary PostgreSQL user/database when building the image simplifies the entrypoint script, since it can assume that these objects exist rather than needing to create them.
> images/materialized-base: simplify postgres database/user creation
