MaterializeInc/materialize

- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/mysql-util/src/schemas.rs
- src/sql/src/plan.rs
- src/sql/src/plan/error.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/sql/src/pure/mysql.rs
- src/sql/src/pure/postgres.rs
- src/sql/src/pure/references.rs
- src/storage-types/src/sources.rs
- test/mysql-cdc/table-in-mysql-schema.td
- test/mysql-cdc/temporary-tables.td
- test/mysql-cdc/views.td
- test/pg-cdc-old-syntax/pg-cdc.td
- test/pg-cdc-old-syntax/two-source-schemas.td
- test/pg-cdc/subsource-resolution-duplicates.td
- test/pg-cdc/two-source-schemas.td
- test/testdrive/load-generator.td
- test/testdrive/source-tables.td
- test/yugabyte-cdc/yugabyte-cdc.td
Fixes https://github.com/MaterializeInc/database-issues/issues/8376 (populate `mz_internal.mz_source_references`)
and Fixes https://github.com/MaterializeInc/database-issues/issues/8550 (refactor purification to simplify reference external resolution logic)
This PR was originally intended just to retrieve all available source references during purification of `CREATE SOURCE` statements, but expanded to refactor purification handling of external reference resolution, which is why it's a little long.
It aims to simplify things overall by centralizing the logic for resolving external references against the set of 'all available source references'.
The downside to this approach (as previously discussed) is that we will always retrieve _all_ upstream references first and then resolve the the …
> storage/sources: Refactor purification reference resolution and populate available source references table

- src/postgres-util/src/schemas.rs
- test/pg-cdc/pg-cdc.td
This PR excludes generated columns from the publication info we generate for an upstream table in a Postgres source. Generated columns are not included in the replication stream, nor in the `COPY` protocol that we use for the initial snapshot.
Allow users to depend on upstream tables that have generated columns
> sources: Ignored `GENERATED` columns for Postgres sources

- src/compute/src/logging/timely.rs
Use a boxed slice instead of a vector to maintain per-channel message counts. Not expecting a dramatic improvement, but it should shave two times eight bytes per channel, for the send and receive counts.
> Timely logging: Boxed slice to count messages

- test/testdrive/alter-sink.td
> testdrive: Disable flaky alter sink check

- ci/test/lint-main/checks/check-bazel.sh
- misc/shlib/shlib.bash
Seen in https://buildkite.com/materialize/test/builds/92661#019299fe-14a8-41dd-a101-3e426d0c4495
> lints: Retry bazel check on network errors

- misc/python/materialize/cli/run.py
PostgreSQL will automatically use the user name as the database if the database is omittted from the URL, so it's okay to omit it when running bin/environmentd against real PostgreSQL. CockroachDB has no such provisions, though, so we need to keep the restriction in place when running bin/environmentd against CockroachDB.
* This PR adds a feature @def- has found useful in local testing.
> bin/environmentd: allow omitting database when running against Postgres

- ci/nightly/pipeline.template.yml
- test/mysql-cdc-old-syntax/privileges.td
> ci: Adapt to changed error messages

- doc/developer/design/20240925_attribution_profiling.md
How should we attribute profiling information?
[Rendered markdown](https://github.com/MaterializeInc/materialize/blob/c378051875673a72fd28cceed760b60e8bcab474/doc/developer/design/20240925_attribution_profiling.md).
https://github.com/MaterializeInc/database-issues/issues/6551
> [design doc] attribution and profiling

- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
Do not create ClusterRoleBinding for environmentd in orchestratord.
This ClusterRole is only used by the init container to query node labels, and the init container is also not managed by orchestratord.
Part of https://github.com/MaterializeInc/cloud/issues/10285
Context discussion at https://materializeinc.slack.com/archives/CL68GT3AT/p1729163180743349
> Do not create ClusterRoleBinding in orchestratord

- src/adapter/src/coord/sequencer/inner/create_continual_task.rs
- src/adapter/src/optimize/materialized_view.rs
- src/compute-client/src/as_of_selection.rs
- src/compute-client/src/controller/instance.rs
- src/compute-types/src/dataflows.rs
- src/compute-types/src/sinks.proto
- src/compute-types/src/sinks.rs
- src/compute/src/render/sinks.rs
- src/compute/src/sink.rs
- src/compute/src/sink/materialized_view.rs
There are now two sinks that write to persist but with different behavior (conflict resolution, only at input times, etc). Rename PersistSink to something that reflects the differences.
> compute: rename PersistSink to MaterializedViewSink

- src/compute/src/render.rs
- src/compute/src/render/continual_task.rs
- test/sqllogictest/ct_errors.slt
- test/sqllogictest/ct_various.slt
It's unclear how valuable this is, we could also reasonably return an
error instead of panic. We can still decide to do the planning error too
later, but compute shouldn't panic when presented with a valid dataflow
description. The alternative would be to declare a dataflow description
for a CT that doesn't reference any inputs invalid, but doing that in
the type system seems difficult and doing it in a comment seems brittle.
> ct: fix panic when input is not referenced

- src/compute-client/src/controller.rs
- src/compute-client/src/controller/replica.rs
This way, it'll stay constant across replica restarts, which is the desired behavior.
> Move replica expiration to configuration

- Cargo.lock
- src/mysql-util/Cargo.toml
- src/mysql-util/src/lib.rs
- src/mysql-util/src/schemas.rs
- src/sql/src/pure.rs
- src/sql/src/pure/mysql.rs
- src/sql/src/pure/references.rs
- test/mysql-cdc/table-in-mysql-schema.td
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8624 and fixes https://github.com/MaterializeInc/database-issues/issues/8672
I had removed this ability during the refactoring done in https://github.com/MaterializeInc/materialize/pull/29857 with the intent to reintroduce it at some point in the future. However we discovered today that it broke some nightly tests, so here is the fix!
The downside to this solution is that when a user specifies a table to replicate within a mysql system schema, we will retrieve and store _all_ tables in all system schemas in our `mz_internal.mz_source_references' catalog table, which includes dozens of tables. However this seems like an acceptable tradeoff to avoid a more complicated approach.
> sources/mysql: Allow MySQL sources to reference tables in system schemas

- src/persist-client/src/internal/machine.rs
Motivation is for ease of local development (e.g. right now while I'm iterating on CT stuff and debugging some WIP local branch). This probably would have been there in the first place, except this log message long predates having the shard names plumbed around.
Really only doing this for the info logging in snapshot, but also include it for all the similar debug logs in snapshot and next_listen_batch.
> persist: include shard name (usually the GlobalId) in snapshot logging

- src/sql/src/pure/mysql.rs
- src/sql/src/pure/references.rs
- test/mysql-cdc-old-syntax/table-in-mysql-schema.td
https://github.com/MaterializeInc/materialize/pull/30064#issuecomment-2420156881
> storage/mysql: Don't error if no non-system tables are found when MySQL sources are created

- ci/mkpipeline.py
- misc/python/materialize/checks/all_checks/pg_cdc.py
This is not perfect, builds can be triggered quickly and we wouldn't notice. Successful test run with everything switched to AWS: https://buildkite.com/materialize/test/builds/92724 Nightly still running: https://buildkite.com/materialize/nightly/builds/10031
> ci: Switch jobs to AWS if Hetzner is overloaded

- misc/python/materialize/parallel_workload/executor.py
Rainer called correctly that this is brittle, failed in https://buildkite.com/materialize/nightly/builds/10035#01929cd3-69dd-4842-8173-9da8494ae03e
> parallel-workload: Fix commit detection

- doc/developer/design/20231127_pv2_uci_logical_architecture.md
[Rendered](https://github.com/aljoscha/materialize/blob/design-decoupled-coordinator/doc/developer/design/20231127_pv2_uci_logical_architecture.md)
Part of MaterializeInc/database-issues#6316 
-
> doc/design: platform v2, logical architecture of the query/control layer

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
Related to https://github.com/MaterializeInc/i2/pull/2232
> ci: Move further jobs to Hetzner now that we have more servers

- README.md
Follow up from the migration of Github issues -> private and using Discussions for public ticket tracking. `CONTRIBUTING.md` has already been updated.
> Update repo readme contribution guidelines to point to the Discussions section instead of issues

- doc/user/content/sql/system-catalog/mz_internal.md
- src/adapter/src/catalog/builtin_table_updates.rs
- src/catalog/src/builtin.rs
- src/catalog/src/memory/objects.rs
- test/sqllogictest/autogenerated/mz_internal.slt
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8613
Now that each individual export (table) of a Kafka source can have it's own envelope and/or encoding specified, these columns don't make much sense on the `mz_sources` catalog table. Instead, we decided to port them to the `mz_kafka_source_tables` catalog table -- see discussion in the referenced issue.
The large line diff in `src/catalog/src/memory/objects.rs` is just moving two methods from the `Source` type to the `DataSourceDesc` type for re-use
> Populate envelope/key-format/value-format columns on mz_kafka_source_tables table

- Cargo.lock
- misc/wasm/Cargo.lock
- src/adapter/src/coord.rs
- src/catalog-debug/src/main.rs
- src/environmentd/src/bin/environmentd/main.rs
- src/environmentd/src/lib.rs
- src/environmentd/src/test_util.rs
- src/ore/Cargo.toml
- src/ore/src/lib.rs
- src/ore/src/url.rs
- src/persist-cli/src/maelstrom.rs
- src/persist-cli/src/maelstrom/txn_list_append_multi.rs
- src/persist-cli/src/open_loop.rs
- src/persist-client/src/cache.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/cli/args.rs
- src/persist-client/src/cli/inspect.rs
- src/persist-types/src/lib.rs
- src/persist/src/cfg.rs
- src/persist/src/postgres.rs
- src/postgres-client/src/lib.rs
- src/sqllogictest/src/runner.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/history.rs
- src/storage-types/src/controller.rs
- src/storage/src/source/reclock.rs
- src/testdrive/src/action.rs
- src/testdrive/src/bin/testdrive.rs
- src/timestamp-oracle/src/postgres_oracle.rs
That automatically redacts passwords when displayed/debugged. This will
prevent us from revealing the password, if present, in
consensus/blob/timestamp oracle connection URLs.
* This PR addresses an incident.
> ore: introduce SensitiveUrl type

- misc/python/materialize/cli/run.py
Noticed by Dan in https://materializeinc.slack.com/archives/C01LKF361MZ/p1729266971048909
Diff is also by Dan
> slt: Allow overriding default system parameters while keeping the defaults

- test/testdrive/coord-read-holds.td
Keeps flaking: https://buildkite.com/materialize/nightly/builds/10054#_
> testdrive: Disable flaky part of coord-read-holds.td

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenario.py
- misc/python/materialize/feature_benchmark/scenarios/optbench.py
Not a real solution, just to unflake CI a bit. Example failures: https://buildkite.com/materialize/nightly/builds/10054 https://buildkite.com/materialize/nightly/builds/10052
> feature-benchmark: Bump threshold for clusterd memory even further

- misc/python/materialize/parallel_benchmark/framework.py
Seen failing in
https://buildkite.com/materialize/qa-canary/builds/277#01929cf0-282b-4c72-af50-0593d2d1e4e5
Green run: https://buildkite.com/materialize/qa-canary/builds/278#0192a1a7-0a51-42ff-b5c7-fc2ed2250314
> parallel-benchmark: Don't set autocommit twice

- misc/python/materialize/cli/ci_annotate_errors.py
Got lost in https://github.com/MaterializeInc/materialize/pull/30071, so submitting separately. Will wait for that PR to land first, then rebase.
This seems to find one occurrence: https://buildkite.com/materialize/nightly/builds/10042
```
feature-benchmark-materialized-1     | cluster-u4-replica-u4-gen-0: 2024-10-18T10:36:59.867267Z  INFO mz_storage::storage_state: reconcile: received RunIngestions command worker_id=0 ingestions=[RunIngestionCommand { id: User(21), description: IngestionDescription { desc: SourceDesc { connection: Kafka(KafkaSourceConnection { connection: KafkaConnection { brokers: [KafkaBroker { address: "kafka:9092", tunnel: Direct }], default_tunnel: Direct, progress_topic: None, progress_topic_options: KafkaTopicOptions { replication_factor: None, partition_count: …
```
> ci: Detect plain-text passwords in log files

- test/canary-load/mzcompose.py
Seen failing in https://buildkite.com/materialize/qa-canary/builds/277#01929cf0-2829-448b-b1f6-1878a16573af
New run without that failure: https://buildkite.com/materialize/qa-canary/builds/279#0192a1ba-2710-4842-9134-5a928f7d0e6e
> qa canary: Improve load test

- misc/python/materialize/test_analytics/setup/tables/12-parallel-benchmark.sql
> parallel-benchmark: Mark stddev as nullable

- src/adapter/src/command.rs
- src/adapter/src/coord/catalog_serving.rs
- src/adapter/src/coord/sequencer.rs
- src/sql/src/plan.rs
- src/sql/src/rbac.rs
As it says in the title!
Code cleanup
> adapter: Delete dead code

- test/mysql-cdc/alter-source.td
- test/mysql-cdc/mysql-cdc.td
- test/pg-cdc/alter-source.td
- test/pg-cdc/pg-cdc.td
- test/pg-cdc/statistics.td
- test/source-sink-errors/mzcompose.py
- test/ssh-connection/pg-source-after-ssh-restart.td
Since https://github.com/MaterializeInc/database-issues/issues/8511 has been fixed
> tests: Use introspection tables in new source table model

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/catalog/src/memory/objects.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql/src/plan.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- test/sqllogictest/retain_history.slt
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8649
The above bug demonstrated hung queries whenever using a `CREATE TABLE .. FROM SOURCE .. ENVELOPE MATERIALIZE` statement, since `ENVELOPE MATERIALIZE` (also known as `Envelope::CdcV2`) uses a non-default timeline by default.
This PR introduces the ability to set a custom timeline on `CREATE TABLE .. FROM SOURCE` and to correct the default timeline when using `ENVELOPE MATERIALIZE`, matching the existing timeline handling semantics of `CREATE SOURCE` statements.
The tests for this are in @nrainer-materialize 's PR https://github.com/MaterializeInc/materialize/pull/29801 and I tested this change on his branch locally to verify the fix.
> adapter/sources: Support custom timelines on source tables to handle CdCv2 envelope type correctly

- .github/workflows/slack_notify_mz_catalog_server.yml
Do this rename since the `mz_introspection` cluster was previously renamed to `mz_catalog_server`.
I will coordinate updating the channel name at the same time that this PR is merged.
> Rename rnd-mz-introspection-council slack channel to rnd-mz-catalog-server-council 

- src/compute/src/render.rs
- src/compute/src/render/continual_task.rs
- test/sqllogictest/ct_liveness.slt
This is part 1 of moving to the behavior described in the [third option]
of the "Read and Write Timestamps" open question. I'm splitting the work
up because this first bit fixes the vast majority of the wonky timestamp
behavior of CTs (including entirely removing the step_backward
operator).
[third option]: https://www.notion.so/materialize/Continual-Tasks-Decision-Log-7279978e873741ca83d0c2f8382dad5f
Summary is that all reads and writes occur at timestamp `T`, except
self-references, which must be handled differently. When computing the
proposed write to some output at `T`, we can only know the contents of
it through `T-1` (the exclusive upper is `T`).
We address this by initially assuming that the output contains no
changes at `T`, then evaluating each of the statements in order, …
> ct: rework timestamp behavior pt 1

- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- test/testdrive/source-tables.td
* This PR adds a known-desirable feature: Fixes https://github.com/MaterializeInc/database-issues/issues/8633
Also replaces https://github.com/MaterializeInc/materialize/pull/29923
> storage/adapter: Introduce 'ALTER SOURCE .. REFRESH REFERENCES' statement for refreshing available upstream refs

- src/adapter/src/coord/timeline.rs
- src/adapter/src/coord/timestamp_selection.rs
- src/compute-types/src/dataflows.rs
- src/compute/src/compute_state.rs
Log some basic information about why dataflow expiration was turned on or off.
The additional information will help understand why dataflow expiration is not enabled even if replica expiration is set.
Currently occurring in a customer's environment: https://github.com/MaterializeInc/database-issues/issues/8647
* What other information can we log that would be helpful in debugging?
> dataflow expiration: log on/off reason

- doc/developer/guide.md
- misc/editor/rustrover/run-bin-environmentd.run.xml
- misc/editor/rustrover/run-pre-push-lints.run.xml
Running the equivalent of `bin/environmentd --reset` is not simple in RustRover. Include example run configuration in the repo for new developers to easily get started.
> dev: include example RustRover run configurations, update nix-shell docs

- misc/python/materialize/mzcompose/service.py
- misc/python/materialize/mzcompose/services/clusterd.py
- misc/python/materialize/mzcompose/services/materialized.py
Seen failing in https://buildkite.com/materialize/release-qualification/builds/644#01929d98-489f-4cb5-86c7-1368f303e512
So far so good: https://buildkite.com/materialize/release-qualification/builds/657
> mzcompose: Higher stop grace periods for materialized/clusterd

- ci/test/build.py
- ci/test/pipeline.template.yml
- misc/python/materialize/ci_util/upload_debug_symbols_to_polarsignals.py
- misc/python/materialize/ci_util/upload_debug_symbols_to_s3.py
This addresses https://github.com/MaterializeInc/database-issues/issues/8617.
It is currently blocked by https://github.com/MaterializeInc/database-issues/issues/8652.
542e4b059e build: debug symbols: extract functions
f7691e6cfd build: debug symbols: add log output
49b08b934e build: debug symbols: extract upload to s3
**1f29b22035 build: debug symbols: extract and rework upload to PolarSignals
862ecd5c4f build: debug symbols: improve error handling and logging
af8d249e3f ci: add steps rust-upload-debug-symbols-x86_64 and rust-upload-debug-symbols-aarch64**
60279ee754 ci: depend on bazel build steps
> build: upload debug symbols to PolarSignals as separate step

- ci/release-qualification/pipeline.template.yml
Ran out of disk again in https://buildkite.com/materialize/release-qualification/builds/644#01929d98-48a5-417e-ae63-891a5f49ce74
> ci: Larger agents, fewer actions for backup&restore

- src/durable-cache/src/lib.rs
@jkosh44, can you look into this test whether it should work in Miri or whether we can make it work? It [failed in Nightly.](https://buildkite.com/materialize/nightly/builds/10074#0192b171-397d-4d40-b95a-232c862bbeac)
> tests: disable durable_cache in Miri

- test/bounded-memory/mzcompose.py
This addresses https://buildkite.com/materialize/nightly/builds/10077#0192b401-3942-4603-a0e4-ed829ef07cc7:
```
builtins.AssertionError: Service mz not found in SERVICES: ['materialized', 'testdrive', 'redpanda', 'postgres', 'mysql', 'clusterd']
```
caused by https://github.com/MaterializeInc/materialize/pull/30052.
> tests: bounded memory: fix

- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/statement_logging.rs
Observed while reading the implementation, avoids a clone of the parameters when running regular queries. Probably doesn't have a performance impact, but good to avoid.
> Avoid unnecessary clones of parameters

- src/sql/src/plan/query.rs
- src/sql/src/plan/statement/ddl.rs
- test/sqllogictest/ct_errors.slt
- test/sqllogictest/ct_various.slt
> ct: resolve another round of adapter TODOs

- src/durable-cache/src/lib.rs
This commit improves the API of the durable-cache as a result of
prototyping.
Works towards resolving #https://github.com/MaterializeInc/database-issues/issues/8384
The diff is much smaller if viewed with whitespace hidden.
> durable-cache: Improve API

- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
Fixes orchestratord helm chart resources specification.
1. Memory requests should always be equal to limits, as memory can generally not be reduced without killing the pod.
2. Limiting CPU is usually not useful, and prevents us from spiking briefly in periods of extremely rare load.
3. The indentation when templating the resources was a bit too deep.
Part of https://github.com/MaterializeInc/cloud/issues/10285
> fix orchestratord helm chart resources

- src/compute/src/render/continual_task.rs
In the previous impl, the split in the dataflow graph resulted in every row being cloned, just to be immediately thrown away. This is wasteful and potentially doubles the memory requirements. Instead use a custom 1-input 2-output operator (passing through the input).
While I'm in here, also resolve a TODO to switch the operators to extension traits on `Collection`.
Definitely review with hide whitespace changes on
> ct: don't clone every row when producing `ct_times`

- misc/bazel/cargo-gazelle/src/args.rs
- misc/bazel/cargo-gazelle/src/bin/main.rs
- misc/bazel/tools/BUILD.bazel
The tool we use to generate `BUILD.bazel` files from `Cargo.toml` files, calls `cargo` to get metadata about a crate. Across versions of Cargo the returned metadata can differ, e.g. `1.78.0` of cargo returned a library name with dashes, meanwhile `1.80.1` returned it with underscores. This PR has Bazel provide the `cargo` binary to `cargo-gazelle` so when running `bin/bazel gen` everyone is using the same version of Cargo.
Fixes an issue @bosconi ran into today with the release
> bazel: Use `bazel` provided `cargo` when generating BUILD files

- ci/test/cargo-test/mzcompose.py
- misc/python/materialize/mzcompose/services/postgres.py
- test/0dt/mzcompose.py
- test/cloud-canary/mzcompose.py
- test/cluster/mzcompose.py
- test/data-ingest/mzcompose.py
- test/launchdarkly/mzcompose.py
- test/output-consistency/mzcompose.py
- test/postgres-consistency/mzcompose.py
- test/restart/mzcompose.py
- test/retain-history/mzcompose.py
- test/sqllogictest/mzcompose.py
- test/txn-wal-fencing/mzcompose.py
> ci: Switch to CRDB on release branches

- src/sql/src/plan/statement/ddl.rs
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8687
Copies the same lines from `plan_create_source` to `plan_create_table_from_source`:
https://github.com/MaterializeInc/materialize/blob/3a80a3d73d587188ef644f5ebe934fe1b0f85715/src/sql/src/plan/statement/ddl.rs#L958-L961
Tests to cover this case are in https://github.com/MaterializeInc/materialize/pull/29801
> Fix create table from source planning to account for duplicate column names

- src/repr/BUILD.bazel
- src/repr/build.rs
- src/repr/src/catalog_item_id.proto
- src/repr/src/catalog_item_id.rs
- src/repr/src/lib.rs
As it says on the tin, adds a new type called `CatalogItemId` which will be used as a stable identifier for Catalog items.
Figured splitting this out into its own PR was a good first step.
Progress towards https://github.com/MaterializeInc/database-issues/issues/8233
> adapter: Add `CatalogItemId` type

- misc/python/materialize/mzcompose/services/postgres.py
> ci: Don't check for v prefix in BUILDKITE_TAG

- test/feature-benchmark/mzcompose.py
See https://materializeinc.slack.com/archives/C01LKF361MZ/p1729636270892819 for context
> feature-benchmark: git fetch less often

- misc/python/materialize/mzcompose/__init__.py
This should fix the platform checks failing in https://buildkite.com/materialize/nightly/builds/10094.
It is not fully clear to me what happened here. Was `enable_create_continual_task` renamed to `enable_continual_task_create` so that we need this line for upgrade checks?
Nightly: https://buildkite.com/materialize/nightly/builds/10105
> tests: continual tasks: fix activation

- .bazelrc
- .cargo/config.toml
- bin/ci-builder
- ci/builder/Dockerfile
- misc/python/materialize/checks/all_checks/sink.py
- misc/python/materialize/xcompile.py
Our current build is optimized for hardware we run in prod by using the `target_cpu` and `target_features` build flags. These flags can enable newer CPU instructions for better runtime performance, but these instructions are not necessarily portable and might break the Docker image/Emulator when run locally.
The better longer term fix is probably a specific build step (maybe update `CargoPreImage` in mzbuild?) that has a "portable" config. I made a quick attempt at this but it's a bit non-trivial.
Better portability of the Emulator
> build: Remove CPU specific build config for maximum compatibility

- .bazelrc
- WORKSPACE
As it says in the title, upgrade Bazel's `rules_rust` from `0.51` to `0.53` and re-enables pipelined compilation. 
Previously we disabled pipelined compilation because of some build failures, I wanted to try re-enabling it since there have been changes made to how build scripts work, which I think were causing the original failures.
Speed up CI
> bazel: Upgrade `rules_rust v0.53`, re-enable pipelined compilation

- misc/python/materialize/cli/ci_annotate_errors.py
Unfortunately failed again: https://buildkite.com/materialize/nightly/builds/10115#0192b926-306b-49aa-9654-1e10e0154aac
> ci: Disable password check for now

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
While writing the migration for `CREATE SOURCE` -> `CREATE TABLE .. FROM SOURE` statements for kafka sources, I realized that I had forgotten to add the `IGNORE KEYS` option to the table statements. This implements the option type so that we don't lose any option configuration during the migration.
> Copy over the 'IGNORE KEYS' option from CREATE SOURCE to CREATE TABLE FROM SOURCE statements

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
Adds network policy support to orchestratord
Adds basic support for running orchestatord in clusters with network policy enforcement.
> orchestratord network policies

- bin/pyactivate
- ci/builder/Dockerfile
> tests: Prefer uv over pip

- ci/test/pipeline.template.yml
Not strictly necessary because you anyway need to set a build tag but it confused me to have it listed in "Trigger CI builds".
> ci: skip "upload debug symbols" in coverage builds

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/10121#0192ba0a-b4d7-4213-91ad-5b098be0935a:
```
SUCCESS_MISMATCH: Outcome differs.
Expression: coalesce(array_agg(int2_null ORDER BY ARRAY[row_index]::INT[], int2_null), array_agg(decimal_39_8_max ORDER BY ARRAY[row_index]::INT[], decimal_39_8_max))
Value 1 (Materialize evaluation): 'QueryFailure' (type: <class 'str'>)
Value 2 (Postgres evaluation): 'QueryResult' (type: <class 'str'>)
Error 1: 'coalesce could not convert type numeric[] to smallint[]'
```
> postgres consistency: extend ignore entry

- test/sqllogictest/pretty.slt
This addresses https://buildkite.com/materialize/slt/builds/6075#0192b925-5c6a-4c13-8974-0bd776a5aa5e:
```
OutputFailure:test/sqllogictest/pretty.slt:71
expected: Values(["CREATE INDEX t_primary_idx IN CLUSTER [u1] ON [u2 AS materialize.public.t] (i);"])
actually: Values(["CREATE INDEX t_primary_idx IN CLUSTER [u1] ON [u18 AS materialize.public.t] (i);"])
actual raw: [Row { columns: [Column { name: "pretty_sql", table_oid: None, column_id: None, type: Text }] }]
```
> tests: fix pretty.slt

- src/compute-client/src/controller/instance.rs
The `ComputeController` provides a sync API for creating collections and taking out read holds on them, without waiting for the collection to be created in the `Instance`. Thus the `Instance` might see read hold changes for collections that haven't been created yet. Stash them for later application, instead of incorrectly panicking or ignoring the changes.
Part of https://github.com/MaterializeInc/database-issues/issues/8679
> controller/compute: defer application of early read hold changes

- doc/user/content/manage/dbt/_index.md
- doc/user/content/sql/create-materialized-view.md
Document the `refresh_interval` configuration in `dbt-materialize` that allows setting non-default refresh strategies for materialized views models.
> doc/user: add `refresh_interval` to dbt documentation

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/clusterrole.yaml
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
we want the helm chart to still use the balancer layer, because we have future plans of moving more logic into it
> also create balancers in orchestratord

- misc/helm-charts/environmentd/README.md
- misc/helm-charts/environmentd/templates/environmentd.yaml
- misc/helm-charts/environmentd/values.yaml
- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
simplify, and make this more flexible
> allow just setting the resource requirements directly

- .bazelrc
- misc/python/materialize/cli/bazel.py
Compliments of @antiguru, this PR adds a cargo check like behavior to our Bazel build. Users can now run either `bin/bazel check <target>` which de-sugars to `bazel build --config=check <target>`
Improve our Bazel setup
> bazel: Add a `cargo check` like behavior

- doc/developer/design/20241015_add_columns_to_tables.md
Adds the design doc that was previously discussed in [Notion](https://www.notion.so/materialize/Adding-Columns-to-Tables-in-Materialize-11213f48d37b806280cbf2d9aa4b5f9a?pvs=4).
> alter_table: Add design doc

- bin/ci-builder
- ci/test/pipeline.template.yml
- misc/python/materialize/cli/run.py
> cargo-test: Bump RUST_MIN_STACK

- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
This addresses https://buildkite.com/materialize/nightly/builds/10152#0192c376-f152-481a-a4c1-360fb1b091e8:
```
SUCCESS_MISMATCH: Outcome differs.
Expression: jsonb_object_agg(s0.uuid_val, (UUID 'invalid_value_123') ORDER BY ARRAY[s0.row_index]::INT[], 0, s0.uuid_val, (UUID 'invalid_value_123'))
Value 1 (Materialize evaluation): 'QueryResult' (type: <class 'str'>)
Value 2 (Postgres evaluation): 'QueryFailure' (type: <class 'str'>)
Error 2: 'invalid input syntax for type uuid: "invalid_value_123"'
```
> postgres consistency: add ignore for evaluation shortcut

- src/testdrive/src/bin/testdrive.rs
- src/testdrive/src/error.rs
- src/testdrive/src/util/text.rs
We have had reports of devs being confused by errors in testdrive output not lining up with the normal output. This fixes it both in CI and locally (if it ever happened there).
An alternative would be to add a flag `--stdout-only` and use that in CI, while keeping stderr locally.
> testdrive: Print everything to stdout

- src/adapter/src/coord/ddl.rs
- src/compute-types/src/dataflows.rs
- test/testdrive/controller-frontiers.td
This PR fixes two issues around CTs I discovered while poking at them. See commit messages for details.
Two bugs: 
* Frontiers for CTs are reported twice in `mz_frontiers` and `mz_cluster_replica_frontiers`.
* `DROP CONTINUAL TASK` only partially drops the CT state.
> adapter,compute: fixes for continual tasks

- src/adapter/src/optimize.rs
- src/compute-types/src/plan/reduce.rs
- src/compute/src/render/reduce.rs
- src/expr/src/relation.proto
- src/expr/src/relation.rs
- src/expr/src/relation/func.rs
- src/repr/src/optimize.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/statement.rs
- src/sql/src/plan/expr.rs
- src/sql/src/plan/lowering.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/plan/transform_expr.rs
- src/sql/src/session/vars/definitions.rs
- test/sqllogictest/transform/fold_constants.slt
- test/sqllogictest/window_funcs.slt
This is the promised follow-up to https://github.com/MaterializeInc/materialize/pull/29276. That PR created an infrastructure for fusing groups of window functions, but implemented actual fusion only for value window functions. The current PR implements fusion also for window aggregations.
The HIR representation for fused window aggregations is somewhat different from fused value window functions, because window aggregations don't have an enum like `ValueWindowFunc`. I decided to add a fused variant to HIR's `AggregateFunc`. (Note that there are two `AggregateFunc`: one for HIR and one for MIR. MIR's `AggregateFunc` was also extended, but there is nothing surprising there.) I can't say that this is an elegant representation (especially since it's not possible to implement `identity_datum` …
> Window aggregation fusion

- src/sql-parser/src/parser.rs
- test/testdrive/timelines.td
- test/testdrive/timestamps-debezium-kafka.td
* This PR fixes a recognized bug. Fixes https://github.com/MaterializeInc/database-issues/issues/8693
I added the ability to plan a custom timeline on source tables here https://github.com/MaterializeInc/materialize/pull/30013 but forgot to add the relevant parsing code, which made it impossible to update these tests. This fixes that and the tests.
> adapter: Fix missing parser option for specifying timeline on source tables

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/build.rs
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/cli/bench.rs
- src/persist-client/src/cli/inspect.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/datadriven.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/gc.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/internal/restore.rs
- src/persist-client/src/internal/state.proto
- src/persist-client/src/internal/state.rs
- src/persist-client/src/internal/state_versions.rs
- src/persist-client/src/iter.rs
- src/persist-client/src/read.rs
- src/persist-proc/src/lib.rs
- src/persist-types/src/arrow.rs
See comments in https://github.com/MaterializeInc/database-issues/issues/7975 for important background and design.
The core change in this PR is
[Add RunPart enum and HollowRuns](https://github.com/MaterializeInc/materialize/pull/30094/commits/e0214a95d4d500f10b2fd72e12baad9b897a860e), which:
- Adds a new `HollowRun` type with a list of parts, and a `HollowRunRef` type with a pointer and a small amount of denormalized metadata.
- Adds a `RunPart` enum with variants for that and the existing `BatchPart` enum.
- Adapts ~all of persist to handle the new variant, including adapting many iterators to streams and otherways async-ifying things.
Implements: https://github.com/MaterializeInc/database-issues/issues/8401
It's a big PR! I attempted to split up a few chunkier changes into their own …
> [persist] Spill long runs to separate blobs in S3

- misc/python/materialize/cli/ci_annotate_errors.py
- src/ccsr/tests/client.rs
Seen in https://buildkite.com/materialize/test/builds/93379 The test itself succeeds, but we are failing because of the unexpected logging. This currently makes the tests pipeline red on main.
I'm guessing this might have started with https://github.com/MaterializeInc/materialize/pull/30163 @ParkMyCar @jkosh44 Is it ok to just ignore this? I'm assuming an old environmentd gets fenced with some different timing now.
Previous similar issue: https://github.com/MaterializeInc/database-issues/issues/8525
> ci: Ignore halts: fenced by envd @ PersistEpoch(Some(6)). ours = PersistEpoch(Some(4))

- src/catalog/src/expr_cache.rs
Seen failing in https://buildkite.com/materialize/nightly/builds/10166#0192cdc4-2a25-429d-ac7b-c1b669755989
> miri test: Disable expression_cache test

- test/parallel-benchmark/mzcompose.py
> parallel-benchmark: Fix off-by-one printing

- test/canary-environment/mzcompose.py
Seen failing in
https://buildkite.com/materialize/qa-canary/builds/292#0192d073-ec4c-4821-8231-de67790d2979 after recreating the objects:
> The 'dennis.felsing@materialize.com' role needs SELECT privileges on TABLE "qa_canary_environment.public_table.table": ERROR: permission denied for TABLE "qa_canary_environment.public_table.table"
> canary envrionment: Grant privileges on table

- test/feature-benchmark/mzcompose.py
We keep having flaky failures in Nightly, I don't think 3 is enough. Examples:
https://buildkite.com/materialize/nightly/builds/10166 https://buildkite.com/materialize/nightly/builds/10165
I'll check how long it runs now before submitting.
> feature-benchmark: Bump the number of runs per scenario to 5

- test/canary-environment/mzcompose.py
> canary-environment: Add a hint for how to drop the replication slot

- Cargo.lock
- misc/cargo-vet/audits.toml
- misc/cargo-vet/config.toml
- misc/cargo-vet/imports.lock
This is to get the connect timeout from https://github.com/MaterializeInc/rust-eventsource-client/pull/3
* This PR updates a dependency.
> Update eventsource-client to latest version

- src/persist-client/src/internal/state_versions.rs
As of recently, we've started writing down batches that are "instantaneous", which means that it's possible for two batches to be totally identical. (Which is useful for the new force-compaction machinery - it wants to trigger compaction like adding a normal batch would, but without advancing the frontier.) However, a debug-time state validation assumed all batches were unique.
Ideally we could thread through the spine id and preserve uniqueness here, but since this isn't the essential part of the validation, it's much easier to just check that the duplicate batch is of the expected sort.
Fixes: https://github.com/MaterializeInc/database-issues/issues/7460
(Debatable, since the first instance of this error was from February, long before the empty-batch change. But this does fix the repro …
> [persist] Exception for empty batches in the debug validator

- src/orchestratord/src/controller/materialize.rs
This adds local.mtrlz.dev:3000 as a default origin to support local development of the console.
This change facilitates the deprecation of HTTP on materialize.com by providing an alternative localhost origin in DNS.
> Add local.mtrlz.dev:3000 as default origin for local development

- test/testdrive-old-kafka-src-syntax/catalog.td
- test/testdrive-old-kafka-src-syntax/distinct-arrangements.td
- test/testdrive-old-kafka-src-syntax/indexes.td
Seen failing in https://buildkite.com/materialize/nightly/builds/10187
This really shows why we don't want to have these duplicated tests for a longer period of time, it will be a mess to keep them in sync since they are not running in the Test pipeline.
> testdrive: Adapt old syntax tests to new CT/Network Policy objects

- test/cluster/statement-logging/statement-logging.td
Seen failing in https://buildkite.com/materialize/test/builds/93457#0192d458-72b1-42b4-9dfd-512c1c0e1692
> cluster test: Fix statement-logging.td

- test/testdrive-old-kafka-src-syntax/source-tables.td
- test/testdrive/source-tables.td
To unflake https://github.com/MaterializeInc/database-issues/issues/8703
> testdrive: Disable status check in source-tables.td

- test/testdrive-old-kafka-src-syntax/source-tables.td
- test/testdrive/source-tables.td
Related to discussion in https://github.com/MaterializeInc/database-issues/issues/8526
> testdrive: Try reenabling source-tables.td in td SIZE=8

- src/compute-client/src/as_of_selection.rs
- src/compute-client/src/controller/instance.rs
- src/sql/src/plan/statement/ddl.rs
When rehydrating, CT dataflows need to be able to observe changes at there previous upper (i.e. the current write frontier of the output shard), to produce the correct output for this time. That means they need to start reading from their sources (with snapshot excluded) as of `upper - 1`, and the controller needs to set the dataflow `as_of` accordingly.
This PR ensures this by (a) adjusting how the compute controller downgrades read frontiers for write-only collections and (b) the bootstrap as-of selection process.
Fixes https://github.com/MaterializeInc/database-issues/issues/8699
> compute: step back as-ofs of write-only collections

- misc/python/materialize/feature_benchmark/benchmark_versioning.py
- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
See also https://github.com/MaterializeInc/database-issues/issues/8705
See https://buildkite.com/materialize/release-qualification/builds/667 for a failure in Release Qualification.
> feature-benchmark: Reduce scale of ExactlyOnce sink scenario

- test/limits/mzcompose.py
Timed out in https://buildkite.com/materialize/release-qualification/builds/664#_
> product-limits: Exclude another generator

- src/adapter/src/coord.rs
We decided that this was a reasonable [long term fix], so remove the TODO and stop calling it a hack. Plus add a bit more detail.
[long term fix]: https://github.com/MaterializeInc/database-issues/issues/8631#issuecomment-2420596296
> ct: update comment about as_of selection for builtin CTs

- src/orchestratord/src/controller/materialize.rs
local.mtrlz.dev will not work for testing HTTP connections to the console hosted at localhost due to *.dev being in the HSTS preload list.
> Replace local.mtrlz.dev with local.mtrlz.com as an allowed host

- src/adapter/src/optimize/dataflows.rs
- src/catalog/src/memory/objects.rs
- src/sql/src/plan/error.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- src/sql/src/pure/mysql.rs
- src/sql/src/pure/postgres.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/history.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/sources.rs
- test/testdrive/session.td
- test/testdrive/source-tables.td
Fixes https://github.com/MaterializeInc/database-issues/issues/8678
This uses the same `force_source_table_syntax` flag introduced in the migration PR https://github.com/MaterializeInc/materialize/pull/30168 . This will completely restrict the use of statements using the 'old' source syntax and stop outputting data to the primary collection for kafka and single-output load generator sources, such that everything should be using tables only.
> adapter/storage: Disallow old source statement usage based on migration feature flag

- src/storage/src/source/kafka.rs
- test/restart/mzcompose.py
- test/testdrive/kafka-recreate-topic.td
Fixes https://github.com/MaterializeInc/database-issues/issues/8621 and fixes https://github.com/MaterializeInc/database-issues/issues/8691
Also reverts some of the test changes made in https://github.com/MaterializeInc/materialize/commit/3027f6c363b688e52966d3e938a8370928730a90 to match the expected correct behavior.
@petrosagg it's somewhat unclear to me when we should output errors to each output vs only the primary source output. For example, I've left 'connection' / ssh errors to only be reported to output 0, but now all others will be reported to each output. Would appreciate any context you have on this.
> storage/sources: Ensure we propagate kafka source errors to all source outputs

- src/catalog/src/expr_cache.rs
- src/durable-cache/src/lib.rs
Previously, when interacting with the durable cache, entries would have
roughly the following lifecycle:
1. Encode `(key, value)` to `(encoded_key, encoded_value)`.
2. Write down in persist `((encoded_key, encoded_value), ts, 1)`.
3. Read `(encoded_key, encoded_value)` from persist.
4. Decode `(encoded_key, encoded_value)` into
`(decoded_key, decoded_value)`.
5. Re-encode `(decoded_key, decoded_value)` into
`(re_encoded_key, re_encoded_value)`.
6. Write down in persist
`((re_encoded_key, re_encoded_value), ts, -1)`.
In order for compaction to work correctly, `encoded_key` must match
`re_encoded_key` byte for byte and `encoded_value` must match
`re_encoded_value` byte for byte. However, many serialization formats
do not provide this guarantee.
To resolve this issue, the durable cache keeps …
> durable-cache: Ensure retractions match insertion

- test/limits/mzcompose.py
> product-limits: Still measure wallclock and explain wallclock

- ci/release-qualification/pipeline.template.yml
Another out of disk seen: https://buildkite.com/materialize/release-qualification/builds/667#0192d502-24a9-4e1f-badc-6fc2095d26e7
> tests: Reduce Zippy w/ complex dataflows further

- deny.toml
- misc/cargo-vet/audits.toml
We have no transitive dependency on it anymore, so remove all mentions from our repo.
> Remove last traces of abomonation

- src/catalog/src/durable/objects/state_update.rs
- src/catalog/src/expr_cache.rs
- src/repr/src/adt/jsonb.rs
When the `JsonbPacker` was first implemented in
c8fa525c6df8bad86a46353208743d2c06466d92, the `JsonbPacker` would serialize integers by first converting them to an `f64`. If the integer didn't fit into an `f64`, then an error was returned. Many of the Jsonb serialize and deserialize methods include a comment of the form:
/// Errors if any of the contained integers cannot be represented exactly as
/// an [`f64`].
Later b7b1816eb9eeceafbf79603be4db1de5a3d35ba3, updated the serialization format to store all numbers as numerics, which have enough precision for all accepted integer types. As a result, the comment about integers and `f64` was no longer accurate, however, the comment was not removed.
This commit removes the outdated comment about integers and `f64`. It's very possible that some …
> repr: Remove outdated jsonb packer comments

- ci/nightly/pipeline.template.yml
Not actionable in PRs, only relevant for QA
> ci: Don't detect closed issue references outside of main branch

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/actions.py
- misc/python/materialize/checks/all_checks/sink.py
- misc/python/materialize/checks/scenarios_zero_downtime.py
Should unflake them: https://buildkite.com/materialize/nightly/builds/10187 and https://buildkite.com/materialize/nightly/builds/10179
```
thread 'timely:work-0' panicked at src/persist-client/src/internal/state.rs:1842:17: LeasedReaderId(r136e0830-75d8-4385-914c-cca1bc0e0f8b) was expired due to inactivity. Did the machine go to sleep?
```
> ci: Parallelise platform-checks 0dt scenarios

- misc/dbt-materialize/Dockerfile
- misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
- misc/dbt-materialize/tests/adapter/test_run_hooks.py
In #28990, we missed adding a `cascade` to the `materialize__drop_relation` macro for the `table` relation type. This causes seed full refreshes to fail if there are downstream dependencies, as reported by @matthelm [on Slack](https://materializeinc.slack.com/archives/C06SXUZ77QF/p1729282078737079).
> dbt-materialize: cascade drop seeds on `--full-refresh`

- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/mzbuild.py
Convenient for local debugging
> mzcompose: Improved sql command

- test/testdrive/continual-tasks.td
Failed with wrong results before https://github.com/MaterializeInc/materialize/pull/30219
> testdrive: Add CT append-only test

- src/catalog/src/durable/persist.rs
- src/durable-cache/src/lib.rs
> durable-cache: Add critical since to cache

- src/balancerd/src/lib.rs
Currently balancer uses a `cloud_provider` context with a key of the cloud provider which means all balancers use the same key `aws`. This seems to break LD contexts for the balancers and goes against the docs. dyncfg works with the current setup, but LD just won't recommend all keys/regions when create or updating a rule. 
https://docs.launchdarkly.com/sdk/features/context-config
> Keys must be a string type. Keys must be unique, deterministic, and should not contain personally identifiable
> information (PII). Keys must be consistent, which means the same person must correspond to the same key across > different services to contribute to consistent flag evaluations. You can use a primary key or a hash, as long as the
> same person always has the same key. We recommend using a hash if …
> fix balancer ld context

- ci/deploy/pipeline.template.yml
Timed out in https://buildkite.com/materialize/deploy/builds/16536#0192e0f7-92ec-4650-beac-7f4d62e79b93
> ci: Increase timeout for devsite deploy

- test/testdrive/continual-tasks.td
Seen failing in https://buildkite.com/materialize/nightly/builds/10218#0192dfc5-f058-4d4f-9810-dd927ff8dcd9
> testdrive: Unflake new append-only CT test

- misc/python/materialize/output_consistency/input_data/operations/jsonb_operations_provider.py
Hard to keep track of where differences come from after having concatenated the results. Seen failing because of a precision difference: https://buildkite.com/materialize/nightly/builds/10218#0192dfc5-f0ef-4f63-acf5-3a1b807c5c10
> output-consistency: Remove jsonb with geo data

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/all_checks/sink.py
- misc/python/materialize/cli/ci_annotate_errors.py
See https://github.com/MaterializeInc/database-issues/issues/8704
> platform-checks: Parallelism didn't help, adapt timeouts and ignore panic instead

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/project.rs
- src/persist-proc/src/lib.rs
- src/persist-types/src/arrow.rs
- src/persist/src/indexed/columnar.rs
- src/persist/src/indexed/encoding.rs
- src/repr/src/row/encode.rs
Remove the `record_run_meta` flag, since it's enabled very widely.
Since it was previously enabled in only some tests, this causes test coverage of the structured order code to go up and exposes some test failures. 😬 Fixes include:
- Fix a bug affecting structured data / inline writes. (Since user parts never have structured data currently - it normally gets first added at encode time - this hasn't come up outside unit tests AFAICT.)
- Add a `goodbytes` method, and use it instead of `get_buffer_memory_size` when estimating part size.
AFAICT these only show up in the unusual configs or small limits that we run our unit tests with, and not real environments or CI more broadly... but anyways best to fix.
https://github.com/MaterializeInc/database-issues/issues/7411
May be easiest to review …
> [persist] Bugfix and cleanup for removing run meta

- misc/python/materialize/cli/ci_annotate_errors.py
> ci: Remove outdated ignore for panic

- src/compute-client/src/controller/replica.rs
- src/compute-types/src/dyncfgs.rs
- test/testdrive-old-kafka-src-syntax/replica-expiration.td
Implement a main switch to disable replica expiration globally, even without re-creating replicas.
> Main switch to disable replica expiration

- src/adapter/src/optimize.rs
- src/ore/src/panic.rs
- src/ore/tests/panic.rs
Today `ore::panic::catch_unwind` returns a `Box<dyn Any>` which isn't useful to callers since the `Debug` format when printing is just `Any`. This PR adds a new methond `catch_unwind_str` that tries downcasting to a `&'static str` or `String` which is the type of the returning object should be, and is the panic message.
Happened upon this while talking to @frankmcsherry
> ore: Add new `ore::panic::catch_unwind_str` function

- doc/developer/design/20240925_network_policies.md
Design doc for network policies.
https://github.com/MaterializeInc/database-issues/issues/4637
> design doc for network policies

- src/sql/src/names.rs
- src/sqllogictest/src/runner.rs
- test/sqllogictest/ct_various.slt
This happens because, unlike other things, the CT name is represented on the statement as a `T::ItemName` instead of `UnresolvedItemName` (so that we can sniff out the assigned LocalId). There are probably other ways to fix this, but I don't have enough context to have an opinion on which is the best.
Test and bug find courtesy of Dennis.
> ct: fix bug where CT name was not escaped in `create_sql`

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/continual-task
- test/sqllogictest/ct_liveness.slt
This allows us to pull more common code out in `AstDisplay`, which will hopefully help prevent bugs like MaterializeInc/database-issues#8719.
> ct: move WITH options to a consistent location in the syntax

- src/adapter/src/coord/indexes.rs
While I'm in here, fix this match to list the enum variants, so this sort of bug wouldn't happen again.
Not particularly sure how to add a regression test for this, though. :(
> ct: fix `EXPLAIN TIMESTAMP` for `SELECT FROM continual_task`

- ci/test/pipeline.template.yml
Broken in https://github.com/MaterializeInc/materialize/pull/29961 (and correctly identified there by @antiguru)
Test run with a tag: https://buildkite.com/materialize/test/builds/93866
Test run without a tag: https://buildkite.com/materialize/test/builds/93868
> build: Fix PolarSignals upload when build tag is set

- ci/builder/requirements.txt
Fixes devsite deploy: https://buildkite.com/materialize/deploy/builds/16642#0192f47f-84a7-4a77-81a1-b88d392baed9
> build(deps): downgrade pydantic, bump pdoc

- test/limits/mzcompose.py
Noticed in https://buildkite.com/materialize/release-qualification/builds/674#0192e5b1-6619-4752-b50d-06b8e248678c
> limits test: Fix MAX_COUNT usage

- src/compute/src/render/continual_task.rs
- test/sqllogictest/ct_various.slt
The CT sink would end up in a state where it had enough information to finalize the output (advance the upper to empty), but it would get stuck waiting for operator input. Fix by repeatedly calling `process()` until there's no work to do before looping back to wait on inputs.
Test and bug find courtesy of Dennis.
> ct: fix dataflow hang for constant MV input

- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
using the environmentd iam role as the connection role was actually just wrong, and in a setup where a user is running their own orchestratord, it will probably be a lot easier to get started if they create a separate iam role per environment (because using a single iam role requires wiring up a lot of oidc stuff in order to restrict things via iam policy variables)
> make it more straightforward to configure environmentd's iam roles via orchestratord

- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
we'll need to revisit the design of this once a few more things are fixed up
> for now, disable tls entirely for things created by orchestratord

- doc/user/content/transform-data/dataflow-troubleshooting.md
Direct users to the Cluster Overview page instead.
> docs: rm reference to memory debugging dashboard

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
removing one more bit of hardcoded configuration
> make the ephemeral storage class to use configurable

- src/expr/src/relation.rs
- src/sql/src/plan/lowering.rs
Before this PR, we had `let_in` and `let_in_fallible`. Most call sites were already calling `let_in_fallible`. This PR ports the last few call sites to `let_in_fallible` and makes some more functions fallible. Then, it deletes `let_in` and renames `let_in_fallible` to simply `let_in`.
I suggest reviewing the commits one by one.
> Make all `let_in`s fallible

- src/adapter/src/coord.rs
- src/adapter/src/coord/appends.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/message_handler.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/error.rs
- src/adapter/src/session.rs
- src/sql/src/session/vars/definitions.rs
- test/testdrive/session.td
This PR removes the global write lock we currently maintain in the Coordinator, and replaces it with table level locks. This allows concurrent writes to different tables.
The Coordinator maintains two new maps:
1. `write_locks: BTreeMap<GlobalId, Arc<tokio::sync::Mutex<()>>>`
2. `deferred_write_ops: BTreeMap<ConnectionId, DeferredWriteOp>`
The `write_locks` map maintains the table level locks and the `deferred_write_ops` map tracks all ops that have been deferred because they're waiting on a lock. When running a read then write plan, or when committing a transaction, we attempt to acquire all of the necessary locks via `WriteLocksBuilder`. This new type asserts we either get all locks or none of them, this helps prevents two sessions deadlocking. When we fail to acquire a lock we spawn a …
> adapter: Remove the global write lock

- test/testdrive-old-kafka-src-syntax/controller-frontiers.td
- test/testdrive/controller-frontiers.td
> testdrive: Disable flaky check temporarily

- ci/nightly/pipeline.template.yml
- misc/python/materialize/cloudtest/k8s/testdrive.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/version_ancestor_overrides.py
- misc/python/materialize/version_list.py
- src/storage-types/src/dyncfgs.rs
- src/storage/src/lib.rs
- src/storage/src/render/sources.rs
- src/storage/src/upsert.rs
- src/storage/src/upsert/types.rs
- src/storage/src/upsert_continual_feedback.rs
- test/kafka-rtr/simple/verify-rtr.td
- test/platform-checks/mzcompose.py
- test/testdrive-old-kafka-src-syntax/explain-timestamps.td
- test/testdrive-old-kafka-src-syntax/mzcompose.py
- test/testdrive-old-kafka-src-syntax/pr-24663-regression.td
- test/testdrive/explain-timestamps.td
- test/testdrive/mzcompose.py
- test/testdrive/pr-24663-regression.td
- test/upsert/rehydration/03-after-rehydration.td
- test/zippy/mzcompose.py
A new upsert operator that never updates its state based on the source
input but instead continually listens to updates from its own backing
persist shard to update its upsert map.
This allows multiple operator instances to run concurrently but still
emit changes that are consistent with the global state of the shard.
> [!IMPORTANT]  
> As is, this is presented as a diff on the regular upsert operator, to help reviewing. In addition to the new operator impl in it's own file. Once reviewed, I will revert the implementation in `upsert.rs` back to what it was before, so we can actually switch implementations using the dyncfg.
NOTE: This is missing the (load-bearing) optimization that we emit partial updates while we have not yet seen all updates of a timestamp, when ingesting the initial …
> storage: continual feedback upsert operator

- Cargo.lock
- misc/helm-charts/environmentd/templates/environmentd.yaml
- misc/helm-charts/environmentd/templates/secret.yaml
- misc/helm-charts/environmentd/tests/environmentd_test.yaml
- misc/helm-charts/environmentd/values.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- src/cloud-resources/Cargo.toml
- src/cloud-resources/src/crd/materialize.rs
- src/environmentd/src/bin/environmentd/main.rs
- src/orchestrator-kubernetes/src/lib.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
Prefix kubernetes object names with `mz{resource_id}-` based on a randomly generated string stored in the Materialize CR status.
Eventual support for multiple Materialize CRs in a single namespace. We need to avoid name collisions, and we need something short and consistently starting with a letter to avoid DNS-1035 issues.
Originating slack discussion: https://materializeinc.slack.com/archives/CL68GT3AT/p1730717511313559
> prefix with mz{resource_id} from Materialize CR status

- src/cloud-resources/src/crd/materialize.rs
Move rand::distribution::Uniform import to top level.
Requested in a review of https://github.com/MaterializeInc/materialize/pull/30343#discussion_r1829613285, but I forgot to push this commit before merging.
> Move rand Uniform import to top level

- src/catalog/src/durable/objects/state_update.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/upgrade.rs
- src/repr/src/adt/jsonb.rs
An unopened catalog caches the fence token, configs collection, and
settings collection. Previously, in order to do this it would clone all
catalog updates, attempt to deserialize them, and then check if it was
one of those three cached update kinds. This was hugely wasteful
because the cached updates makes up a tiny portion of all updates.
This commit fixes the issue, by first peeking into the JSON of the
serialized updates, and only deserializing the updates that are one of
the cached updates. The process of peeking into the JSONB is a bit
scary and may break some abstraction boundaries, but is hopefully worth
it for the performance improvements.
Works towards resolving #MaterializeInc/database-issues/8384
> catalog: Optimize catalog opens

- src/transform/src/analysis.rs
- src/transform/src/lib.rs
- src/transform/src/will_distinct.rs
- test/sqllogictest/advent-of-code/2023/aoc_1205.slt
- test/sqllogictest/advent-of-code/2023/aoc_1216.slt
- test/sqllogictest/advent-of-code/2023/aoc_1220.slt
- test/sqllogictest/advent-of-code/2023/aoc_1223.slt
- test/sqllogictest/cardinality.slt
- test/sqllogictest/ldbc_bi.slt
- test/sqllogictest/ldbc_bi_eager.slt
- test/sqllogictest/transform/fold_constants.slt
- test/sqllogictest/transform/literal_lifting.slt
- test/sqllogictest/transform/reduce_elision.slt
- test/sqllogictest/transform/redundant_join.slt
- test/sqllogictest/transform/threshold_elision.slt
- test/testdrive/introspection-sources.td
This PR does a very preliminary job of removing `Distinct` operators that are in the shadow of another distinct operator. This happens commonly in SQL when one chains `UNION` clauses:
```sql
SELECT * FROM foo
UNION
SELECT * FROM bar
UNION
SELECT * FROM baz
```
This is naively planned as a stack of binary `Distinct { Union { .. } }` operators, which includes in the example above two `Distinct` operators, one of which (the innermost one) is redundant in the presence of the outermost one.
One can detect this by moving down the AST keeping notes on whether there is a pending outer `Distinct` (and on which columns), and if one finds an inner `Distinct` (on the same columns) one can prune that `Distinct` (well, replace by a projection to put the right columns in place).
-
> Redundant Distinct elision

- src/compute-types/src/plan/lowering.rs
`Threshold`'s MIR-to-LIR lowering had some copy-pasted lines that don't fit there. This PR deletes these lines. They were probably copied from lowerings of other operators, which need an unarranged (i.e., raw) input. However, `Threshold` needs an arranged input, so these lines are unnecessary.
Actually, the deleted lines could have caused a panic if we had an input that was already arranged, and not available in raw form: This is because the subsequent lines, which aim to create an arrangement if necessary, were not actually testing the latest form of the input (i.e., the form that the deleted lines were producing), because `keys` was valid only before the deleted lines. Therefore, if we had an input that was already arranged the right way for the `Threshold`, the deleted lines would have …
> compute: Fix Threshold lowering's ArrangeBy

- src/compute/src/compute_state.rs
Fixes a bug where we could not disable lgalloc if it was previously enabled.
> Properly disable lgalloc

- misc/helm-charts/environmentd/values.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/templates/storageclass.yaml
- misc/helm-charts/operator/tests/storageclass_test.yaml
- misc/helm-charts/operator/values.yaml
One thing that this PR is missing is to actually bootstrap and set up LVM on all nodes. I've got this working with the following Daemon Set, but will need to come up with a more robust solution:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: lvm-setup
namespace: openebs
spec:
selector:
matchLabels:
app: lvm-setup
template:
metadata:
labels:
app: lvm-setup
spec:
initContainers:
- name: lvm-setup
image: ubuntu:latest
securityContext:
privileged: true
command:
- /bin/bash
- -c
- |
apt-get update
apt-get install -y lvm2
nvme_dev="/dev/nvme0n1"
if [ -e "$nvme_dev" ]; then
if ! pvs | grep -q "$nvme_dev"; then
pvcreate "$nvme_dev"
fi
if ! vgs | grep -q "instance-store-vg"; then
vgcreate instance-store-vg "$nvme_dev"
fi
fi
containers:
- name: pause
image: k8s.gcr.io/pause:3.7 …
```
> helm-chart: add openebs

- src/persist-client/src/rpc.rs
- src/storage-client/src/storage_collections.rs
The previous implementation of the shard frontier watcher task in `StorageCollections` could skip over frontier advancements. This is particularly problematic if the skipped advancement was to the empty frontier because the storage controller would never learn about the fact that the collection had reached the empty frontier in this case.
This PR fixes the watcher issue and also re-enables the persist pubsub same-process delegation, which was previously disabled because it surfaced this issue.
Fixes https://github.com/MaterializeInc/database-issues/issues/8725
Fixes https://github.com/MaterializeInc/database-issues/issues/8721
Not sure if this is the best fix. I'm pretty sure it works, but having to add a large explanatory comment feels a bit bad. I was …
> storage-client: fix frontier watching

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/client.rs
- src/adapter/src/config/backend.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/statement_logging.rs
- src/adapter/src/coord/validity.rs
- src/adapter/src/optimize/dataflows.rs
- src/adapter/src/session.rs
- src/balancerd/src/lib.rs
- src/build-info/src/lib.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/config.rs
- src/clusterd/src/bin/clusterd.rs
- src/environmentd/src/bin/environmentd/main.rs
- src/environmentd/src/http.rs
- src/environmentd/src/lib.rs
- src/environmentd/src/test_util.rs
- src/orchestratord/src/bin/orchestratord.rs
- src/pgwire/src/protocol.rs
- src/pgwire/src/server.rs
- src/prof-http/src/bin/fgviz.rs
- src/sql/src/catalog.rs
- src/sql/src/session/vars.rs
- src/sqllogictest/src/runner.rs
See https://materializeinc.slack.com/archives/CQM08AP9V/p1729875799567639 for context
> envd: Pass in self-hosted version, print in mz_version() (only)

- src/compute-client/src/logging.rs
While writing up some documentation in Notion, I realized that the operator span columns are listed as nullable but will in fact never be null ([see `compute.rs`](https://github.com/mgree/materialize/blob/lir-mapping-non-nullable-span/src/compute/src/logging/compute.rs#L460)).
> [introspection] schema fix: operator spans are never null

- src/adapter/src/catalog/consistency.rs
Spotted by @ggevay, we were missing the `object_dependencies` field in the `is_empty(...)` check.
Catalog consistency checks didn't check everything we thought they did
> catalog: Fix consistency checks

- test/cluster/blue-green-deployment/setup.td
See https://github.com/MaterializeInc/database-issues/issues/8728
We should still investigate where this flake came from
> blue-green-deployment test: Reduce strictness of readiness

- src/storage/src/source/source_reader_pipeline.rs
When the bindings frontier advances, the `reclock_committed_upper` operator collects bindings that are made ready by this. It needs to use the new upper frontier for this, but previously it incorrectly used the old one.
> storage: fix comparison with an outdated upper frontier

- misc/dbt-materialize/dbt/adapters/materialize/impl.py
- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
- misc/dbt-materialize/tests/adapter/test_deploy.py
When working with users, it is often useful to understand which version of their code is deployed, when it was deployed, and who deployed it. 
This commit adds comments to each schema managed by a deploy_promote with the user and time of deployment, and optionally adds the commit sha if part a git repo. 
Example Comment: 
```
Deployment by seth@materialize.com on 2024-11-06 20:40:00.798+00 | Commit Sha d0527093d6a0c754e9c9d11feb22f2ed761633b2
```
> Add release information when running a dbt deploy_promote

- doc/user/content/sql/copy-to.md
Missed patching the `COPY TO` page in #29907.
> doc/user: patch bulk export feature lifecycle stage

- src/balancerd/src/bin/balancerd.rs
- src/balancerd/src/lib.rs
- src/balancerd/tests/server.rs
- test/balancerd/mzcompose.py
Adds an arg to toggle internal TLS in balancers.
We had to revert the TLS support in the cloud repo, so this allows us to run newer balancerds there.
It may also be useful for self-hosted, as it allows them to run without certs for environmentd.
> Add arg to toggle internal TLS in balancers

- src/catalog/src/expr_cache.rs
- src/compute-types/src/dataflows.rs
- src/compute-types/src/sinks.rs
- src/expr/src/lib.rs
- src/expr/src/relation.rs
- src/expr/src/scalar.rs
This commit adds an Arbitrary implementation on most of the structs
used in the expression cache. The one exception is
`DataflowDescription<mz_compute_types::plan::Plan>`, which is saved for
future work.
This has helped us identify existing issues with the serialization requiring
us to ignore some of the existing tests until it is fixed.
Additionally, if serialization/deserialization fails in production,
then we log an error and move on instead of panic. The cache is purely
an optimization, so we don't want some runtime error to bring down all
Works towards resolving #MaterializeInc/database-issues/8384
> catalog: Implement Arbitrary on expression types

- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/metrics.rs
This PR updates compaction to use the most recent schema from the batch of Runs that we're currently compacting. This should prevent `Compactor`s that were created before the schema of a shard was evolved, from "de-evolving" a structured Part by trying to migrate backwards.
Included is a CYA dyncfg to disable this behavior, although it's defaulted to `true`
Stabilize schema evolution in Persist
> persist: Use the most recent schema of a batch of Runs for compaction

- .config/nextest.toml
- misc/python/materialize/postgres_consistency/ignore_filter/pg_inconsistency_ignore_filter.py
- test/limits/mzcompose.py
> Nightly fixes (November 8)

- Cargo.lock
- bin/bump-version
- src/orchestratord/BUILD.bazel
- src/orchestratord/Cargo.toml
> releases: Bump orchestratord version too

- misc/bazel/README.md
While waiting for tests to run I took a pass at the existing Bazel docs.
Improve docs so more folks can use Bazel.
> bazel: Improve the documentation

- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/templates/deployment.yaml
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
pass the helm chart version through to environmentd, and keep appVersion in sync with the orchestratord version we're running
> helm version improvements

- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
we'll need this on the cloud side for things like the launchdarkly sdk key
see https://github.com/MaterializeInc/cloud/pull/10428
> add environmentd_extra_env to the materialize crd

- ci/release-qualification/pipeline.template.yml
Timeout seen in https://buildkite.com/materialize/release-qualification/builds/675#019309c1-7e6b-441d-b436-c2e112cfd044
> ci: Bump Release Qualification timeouts

- test/cluster/blue-green-deployment/deploy.td
- test/cluster/blue-green-deployment/setup.td
Follow-up to https://github.com/MaterializeInc/materialize/pull/30368
Seen failing in https://buildkite.com/materialize/test/builds/94332#0193186c-c516-4075-bdaf-586e7455b554
> blue-green-deployment test: Another strictness reduction

- src/storage/src/storage_state.rs
When a replica becomes idle (i.e. all its dataflows advance to the empty frontier), there might remain pending storage statistics that haven't been reported yet because the reporting interval hasn't been reached. When the worker thread then gets parked for an indefinite amount of time, those statistics also don't get reported for an indefinite amount of time.
This PR ensures that pending storage statistics always get reported by imposing a limit on the time a worker thread is allowed to park, ensuring it wakes up again when the stats collection interval has elapsed.
[Relevant Slack thread.](https://materializeinc.slack.com/archives/C0761MZ3QD9/p1730729374523079)
Part of https://github.com/MaterializeInc/database-issues/issues/7020
> storage: ensure stats are reported on idle replicas

- src/adapter/src/catalog/transact.rs
- src/adapter/src/coord/cluster_scheduling.rs
- src/audit-log/src/lib.rs
- src/buf.yaml
- src/catalog/build.rs
- src/catalog/protos/hashes.json
- src/catalog/protos/objects_v70.proto
- src/catalog/src/durable/objects/serialization.rs
- src/catalog/src/durable/upgrade.rs
- src/catalog/src/durable/upgrade/v69_to_v70.rs
- src/repr/src/refresh_schedule.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- test/sqllogictest/materialized_views.slt
- test/testdrive-old-kafka-src-syntax/materialized-view-refresh-options.td
- test/testdrive/materialized-view-refresh-options.td
Fixes the issue that Persist compaction doesn't work for `REFRESH` MVs, because the refresh cluster is shut off immediately after each write (i.e., after refreshes), and therefore we don't have time for compaction.
The approach is what we discussed [here](https://materializeinc.slack.com/archives/C053EPHMU05/p1731085425910589?thread_ts=1731054046.650189&cid=C053EPHMU05): We implement an LD-configurable time interval for which we'll keep refresh clusters online after each refresh completes. (In the long term, we'll make this dynamic by asking Persist whether compaction is complete, but this is out of scope for this PR, because we'd need new Persist API for this.)
I've set the default interval to 20 minutes. We can tune this later.
(Tagged @ParkMyCar for review, as …
> Fix Persist compaction for `REFRESH` MVs

- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- misc/helm-charts/testing/console.yaml
- misc/helm-charts/testing/environmentd.yaml
Bumping the default envd image to the latest one from main and also adding a simple example for the console deployment.
> helm-chart: add console deployment example

- src/transform/src/cse/anf.rs
- src/transform/src/normalize_lets.rs
- src/transform/tests/test_transforms/anf.spec
- src/transform/tests/test_transforms/relation_cse.spec
- test/sqllogictest/advent-of-code/2023/aoc_1203.slt
- test/sqllogictest/advent-of-code/2023/aoc_1204.slt
- test/sqllogictest/advent-of-code/2023/aoc_1205.slt
- test/sqllogictest/advent-of-code/2023/aoc_1209.slt
- test/sqllogictest/advent-of-code/2023/aoc_1210.slt
- test/sqllogictest/advent-of-code/2023/aoc_1212.slt
- test/sqllogictest/advent-of-code/2023/aoc_1215.slt
- test/sqllogictest/advent-of-code/2023/aoc_1216.slt
- test/sqllogictest/advent-of-code/2023/aoc_1217.slt
- test/sqllogictest/advent-of-code/2023/aoc_1220.slt
- test/sqllogictest/advent-of-code/2023/aoc_1222.slt
- test/sqllogictest/advent-of-code/2023/aoc_1223.slt
- test/sqllogictest/advent-of-code/2023/aoc_1225.slt
- test/sqllogictest/cardinality.slt
- test/sqllogictest/ldbc_bi.slt
- test/sqllogictest/ldbc_bi_eager.slt
- test/sqllogictest/transform/relation_cse.slt
Currently, within `LetRec` blocks we only perform relation CSE within each binding. We do not optimize across bindings, nor do we take advantage of bindings outside the `LetRec` region. This PR addresses this with extended code for the `LetRec` case that both references `LetRec`-external bindings, and shares across `LetRec`-internal bindings.
There are some potential gotchas, documented in the code:
1. References to `LetRec` bindings should not be equated across the moment the binding is refreshed. Each binding has a "before" identifier and an "after" identifier, and this is sufficient to avoid unintentionally equating the two.
2. The `body` should not borrow much from within the scope. Although all terms are available for use, the current suffix of the optimizer pipeline goes sideways if …
> Relation CSE within WMR blocks

- src/catalog/src/expr_cache.rs
> catalog: Deflake rust test

- src/compute-client/src/controller.rs
- src/storage-controller/src/lib.rs
Previously, the controllers would reset the maintenance ticker after every finished maintenance. So maintenance technically wouldn't be performed once per second, but once per (1s + maintenance duration). The skew caused by this is tiny, but still enough that it produces visible sawtooth patterns in the reported wallclock lag metric when viewed over hours.
This PR removes the ticker reset, so controller maintenance is now performed roughly once per second again, without any inherent skew. The expectation is that this makes the system slightly more predictable and removes skew from metrics that are refreshed during maintenance.
[Slack thread](https://materializeinc.slack.com/archives/C073FCHFWV6/p1731337394420349)
The reported wallclock lag …
> controller: don't reset the maintenance ticker

- deny.toml
> cargo deny: Add new exceptions

- src/repr/src/lib.rs
- src/repr/src/row/encode.rs
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/session/vars/definitions.rs
- test/testdrive/partition-by.td
Add a new `PARTITION BY` clause on materialized views. (Behind a flag!)
This has no effect besides asserting that the new "structured" ordering we're using for Persist data will match the SQL-level ordering on those columns. See the design doc for more details.
Issue: https://github.com/MaterializeInc/database-issues/issues/7188
Draft design: https://www.notion.so/materialize/PARTITION-BY-13413f48d37b8099aaaac45902ffdb75
This is prototype syntax, behind a flag! Please direct thoughts on the supported syntax to the design doc - we're collecting opinions there.
> [persist] PARTITION BY for Persist-backed collections

- src/catalog/src/durable/debug.rs
- src/catalog/tests/debug.rs
- src/persist-client/src/cli/admin.rs
Previously, `test_persist_debug` was comparing two unsorted catalog traces. Catalog traces do not provide any guarantee about sort order and the two traces just happened to be in the same order. This commit fixes the issue by sorting the two traces before comparing.
Fixes #MaterializeInc/database-issues/8742
> test: Fix non-deterministic debug catalog test

- src/environmentd/tests/server.rs
- src/repr/src/row/encode.rs
See https://github.com/MaterializeInc/database-issues/issues/8744 and https://github.com/MaterializeInc/database-issues/issues/8743
Failures seen in https://buildkite.com/materialize/test/builds/94424 and https://buildkite.com/materialize/test/builds/94431
> cargo test: Temporarily disable two flaky tests

- src/catalog/src/durable/upgrade/v70_to_v71.rs
Fix https://github.com/MaterializeInc/database-issues/issues/8745, which was due to a bad rebase, see https://materializeinc.slack.com/archives/CTESPM7FU/p1731419781461869?thread_ts=1731394194.513409&cid=CTESPM7FU
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/8745
> Fix v70_to_v71.rs

- src/persist-client/BUILD.bazel
- src/persist-client/Cargo.toml
Not totally positive but this might be the cause of the pipelined compilation failures we've been seeing with Bazel. Will disable it here and then daily drive pipelined compilation locally for a while to make sure it's stable before enabling in CI.
Improve Bazel compilation speed
> bazel: disable pipelined compilation for `persist-client`

- src/catalog/src/durable/upgrade/v70_to_v71.rs
Very small tweak, OIDs should never change but ideally this migration is fully hermetic.
Make catalog migration totally hermetic
> catalog: Make v70 to v71 migration hermetic

- src/transform/src/analysis.rs
- src/transform/tests/test_transforms/types.spec
- test/sqllogictest/advent-of-code/2023/aoc_1203.slt
- test/sqllogictest/advent-of-code/2023/aoc_1212.slt
- test/sqllogictest/advent-of-code/2023/aoc_1214.slt
- test/sqllogictest/advent-of-code/2023/aoc_1215.slt
- test/sqllogictest/advent-of-code/2023/aoc_1222.slt
- test/sqllogictest/ldbc_bi.slt
- test/sqllogictest/ldbc_bi_eager.slt
- test/sqllogictest/transform/column_knowledge.slt
Our `RelationType` analysis was pessimistic, and wouldn't produce great nullability information going around `LetRec`s. This fixes that, in order to unblock #30429.
As it turns out, this unlocks more plan improvements than realized. Many instanced of column nullability were not being discovered, I suppose because our transforms trusted `Get` and didn't reconsider the possibility non-nullability? I'm not entirely sure, and perhaps we should carefully double check to make sure that we believe the changes (all "good", if correct).
> Extend `RelationType` analysis to optimistic `LetRec`

- src/repr/proptest-regressions/row/encode.txt
- src/repr/src/row/encode.rs
It looks like Persist and Adapter disagree on how to sort -0.0. Let's opt floats out of preserves-ordering for now.
Fixes https://github.com/MaterializeInc/database-issues/issues/8744
> [adapter] Opt floats out of preserves_order for now

- misc/bazel/README.md
Discovered by @mgree when he tried to set these settings.
> bazel: Fix docs, replace a `-` with an `_`

- src/storage/src/render/persist_sink.rs
Closes MaterializeInc/database-issues#8583
The second commit is not strictly related to this, but it felt incorrect how we updated those metrics before.
> storage: in persist_sink, obey read-only flag

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/console.rs
- src/orchestratord/src/controller/materialize/resources.rs
console support for orchestratord
i can access the console on localhost when i run this, but it doesn't appear to work very well - i think @SangJunBak mentioned that this is currently expected, though?
> make orchestratord also create console pods

- src/orchestratord/src/controller/materialize/console.rs
make the console pod become ready sooner
> improve console pod probes

- src/buf.yaml
- src/repr/src/relation_and_scalar.proto
- src/storage-types/src/connections.proto
- src/storage-types/src/sinks.proto
- src/storage-types/src/sources/kafka.proto
- src/storage-types/src/sources/mysql.proto
- src/storage-types/src/sources/postgres.proto
`buf` is a bit aggressive in what it considers breaking. Some changes I merged in https://github.com/MaterializeInc/materialize/pull/30189 were not wire breaking but `buf` thought they were. To prevent needing a force push to main I marked them as temporarily ignored for breaking changes, this PR unignores them.
Re-enable protobuf linting on temporarily ignored files.
> proto: unignore breaking changes

- src/storage/src/source/generator.rs
- src/storage/src/source/generator/key_value.rs
- src/storage/src/source/kafka.rs
- src/storage/src/source/mysql.rs
- src/storage/src/source/postgres.rs
- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/source_reader_pipeline.rs
- src/storage/src/source/types.rs
This PR introduces the ability for source operators to omit returning a probe stream. This is appropriate for sources that don't support probing the upstream system. This ability is then made use of for load generators and Yugabyte sources. 
The "latest" reclocking mode still expects to receive probes, so the reader pipeline synthesizes a probe stream from source progress events and uses that in cases where the source doesn't support probing. This is the same approach previously used by the load generators, just centralized in a single place.
Part of https://github.com/MaterializeInc/database-issues/issues/7020
@petrosagg This is different from what we discussed last week where you suggested synthesizing the probes in the existing …
> storage: optional probe streams from source operators

- src/adapter/src/catalog/open.rs
- src/catalog/src/config.rs
- src/catalog/src/durable/initialize.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
Fixes a bug where we'd use the default replica sizes during bootstrap instead of the ones supplied by the user.
Cleans up the code around converting replica sizes to allocations.
> Use user-supplied replica sizes during boostrap

- ci/test/pipeline.template.yml
Seen timing out in https://buildkite.com/materialize/test/builds/94537#019325cd-afed-405e-afbe-bbed26d9d2bf
> ci: Increase agent size and bump timeout for Merge skew cargo check

- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
the aws secrets backend is not going to work without a lot of extra configuration
> make the secrets manager default to kubernetes in orchestratord

- Cargo.toml
- WORKSPACE
- bin/ci-builder
- bin/lint-versions
- misc/bazel/rust_deps/cxxbridge-cmd/Cargo.cxxbridge-cmd.lock
- src/adapter/src/coord/appends.rs
We saw serious compile time regressions with `v1.82.0`, while we try to determine the root cause and file an issue upstream with the Rust project, we'll revert back to `v1.80.1` which we were using before the upgrade.
Improve compile times.
> rust: downgrade back to `v1.80.1`

- .bazelrc
- misc/python/materialize/mzbuild.py
This PR adds a new Bazel build config called `release-local` which does not enable LTO. This offers a significant compile time improvement which is nice for local release builds which generally never need LTO.
Improve iteration speed of local release builds
> bazel: Add 'release-local' config to decrease compile times for local release builds

- src/persist-client/src/cli/admin.rs
Previously the only way to request a compaction was by throwing the `CompactReq` in a queue... but now there is a second way, and our requested and performed metrics see some drift.
Previously-unreported bug - came up in some internal conversation.
> Increment the compactions-requested metric in exert

- src/catalog/src/durable/upgrade.rs
Super small change, but I realized while working on https://github.com/MaterializeInc/materialize/pull/30468 that I would love to be able to see in logs what catalog upgrades we ran for a given deploy.
Better observability into catalog upgrades
> catalog: Add log line for version upgrades

- .github/CODEOWNERS
Notable changes:
* Add @ParkMyCar/testing as the owner of various CI related crates.
* Migrate the orchestrator crates to the cloud team.
* Migrate the ccsr crate to joint ownership of the cluster and adapter teams.
* Migrate the walkabout crate to the adapter team (as it's essentially just part of the SQL parser).
@MaterializeInc/cloud any concerns about taking ownership of the orchestrator crates? I'm trying to divest myself of individual crate ownership, and y'all have been getting closer to the orchestrator crates with the latest self-hosted push.
@def- added @MaterializeInc/testing to a few CI related crates, but @ParkMyCar has volunteered to help with ownership on these crates too. Let me know if any concerns!
> CODEOWNERS: update for current org structure

- src/storage/src/source/source_reader_pipeline.rs
This commit enables changing the source reclock strategy, through the `storage_reclock_to_latest` flag, of a source without having to restart the source dataflow. The intention is to derisk the production rollout by having a way to quickly revert to the old behavior without causing downtime.
This change mostly consists of moving the check of the dyncfg into the remap loop. However, changing the reclock mode at runtime can result in a temporary regression of both the binding ts and the observed source upper, so the remap operator now also has to deal with that possibility and ensure that no regressing bindings are minted.
Part of https://github.com/MaterializeInc/database-issues/issues/7020
I don't know for a fact that minting regressing bindings …
> storage: enable changing reclock mode without restart

- src/compute-client/src/as_of_selection.rs
This reverts #30284. Now that a release has happened with the updated controller logic that holds back the inputs of MVs/CTs to `upper.step_back()`, as-of selection should always be able to select that frontier as the initial as-of.
Fixes https://github.com/MaterializeInc/database-issues/issues/8699
Note that production still could have MVs that didn't have their write frontier advanced during the last release(s), e.g., because they are installed on zero-replica clusters. For these the hard constraint re-introduced here will still fail to apply, but that only results in a logged error because hard constraint application fails with a soft panic. As-of bootstrapping will still proceed to select the correct as-of (i.e. the output shard's `upper`) in this …
> Revert "Merge pull request #30284 from teskje/as-of-step-back-migration"

- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/templates/networkpolicies.yaml
- src/cloud-resources/src/crd/materialize.rs
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/console.rs
- src/orchestratord/src/controller/materialize/resources.rs
we were previously testing in kind clusters which had a blanket policy of allowing all network traffic, and this caused a lot of the network policies we were writing to be incorrect. i fixed the setup for cloud's kind cluster in https://github.com/MaterializeInc/cloud/pull/10444 and with these changes i was able to successfully run several environments via orchestratord, both in the same namespace and in multiple different namespaces.
> fix network policies installed by orchestratord

- src/compute-types/src/plan/flat_plan.rs
- src/compute/src/render.rs
- src/transform/src/normalize_lets.rs
Our implementation of `promote_let_rec` incorrectly fused `LetRec` blocks that it should not have. In fact, it really shouldn't be fusing *any* of these blocks, but due either to a bug or unwarranted optimism, it did. This was an error for blocks under `Let` bindings, where the sequencing is important, and .. to be honest I have no idea how it didn't crash.
An example problematic query was
```sql
create table foo (a int);
create view bar as
with mutually recursive 
bar(a int) as ( 
select * from bar union select * from foo 
)
select * from bar;
create view baz as
with mutually recursive 
baz(a int) as ( 
select * from baz except select * from bar 
)
select * from baz;
explain select * from baz;
```
Here the sequencing means that `baz` should evolve only ever using the final value of …
> Correct `promote_let_rec`

- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/open.rs
The apply step of the catalog takes in a list of durable catalog updates and does two things with them. It inserts/removes the updates into/from the in-memory catalog, and it generates builtin table updates. At the start of the apply step, updates must be sorted so that they're added in memory in the correct order.
Audit logs are not stored in memory, so the first part of the apply step is a no-op. Audit logs are also append only, so for many environments they are extremely large. Sorting all the audit logs can be extremely expensive and is not actually required.
This commit separates the loading of audit logs during startup, so that they bypass the apply step and instead directly generate builtin table updates.
Works towards resolving #MaterializeInc/database-issues/8384
This PR adds a …
> catalog: Optimize loading audit logs on startup

- test/0dt/mzcompose.py
Noticed in https://buildkite.com/materialize/test/builds/94685#01932ba5-dae3-4588-bb6e-bbc812308133
> 0dt tests: handle another error

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cli/mzcompose.py
- src/testdrive/src/bin/testdrive.rs
- src/testdrive/src/error.rs
Noticed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1731536333820569
Broke in https://github.com/MaterializeInc/materialize/pull/30176
> ci: Fix junit report in testdrive

- misc/python/materialize/mzcompose/__init__.py
Only a first step, seems green so far. Will add the actual tests next.
> ci: Try enabling enable_0dt_deployment_sources in new versions

- .bazelrc
- .cargo/config.toml
- ci/builder/Dockerfile
- misc/python/materialize/xcompile.py
While we are trying things I thought I'd also give this a go. It only has a relatively small effect. environmentd: 347 MB -> 331 MB
> ci: Try zstd compression for debug sections

- bin/orchestratord
- misc/python/materialize/cli/orchestratord.py
make it easier to develop against the current state of the repository in a local kind cluster
i've tested this against the cloud kind cluster by overriding the `--postgres-url` and `--s3-bucket` arguments, but i haven't tried working with the materialize repo kind cluster or any of the testing infrastructure there, so i'm not sure what actually makes sense to use for `DEFAULT_POSTGRES` and `DEFAULT_MINIO` - i'd be interested in thoughts there.
otherwise, i just ran `bin/kind-create` in the cloud repo, and then `bin/orchestratord --kind-cluster-name=mzcloud run --dev` and `bin/orchestratord --kind-cluster-name=mzcloud environment --dev --postgres-url='postgres://region-controller:password@cockroachdb-public.cockroachdb.svc.cluster.local:26257/postgresdb?sslmode=require' …
> add a script for developing via orchestratord

- .bazelrc
- Cargo.toml
About halfs our binary sizes. For example environmentd: 713 MB -> 347 MB
I'm still seeing working symbols in panics:
```
thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:635:9:
environmentd: fatal: creating kubernetes orchestrator: failed to infer config: in-cluster: (failed to read an incluster environment variable: environment variable not found), kubeconfig: (failed to load current context: minikube)
5: rust_begin_unwind
at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
6: core::panicking::panic_fmt
at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
7: main
at src/environmentd/src/bin/environmentd/main.rs:635:9
8: call_once<fn(), ()>
at …
```
> builds: Switch to line-tables-only, even for tagged builds

- src/compute-types/src/dyncfgs.rs
- src/compute/src/sink.rs
- src/compute/src/sink/correction.rs
- src/compute/src/sink/materialized_view.rs
- src/compute/src/sink/materialized_view_v2.rs
- test/testdrive/github-3955.td
This PR contains a rewrite of the materialized view sink (previously known as "the compute persist_sink"), in an attempt to make it easier to reason about and more efficient. The main improvement over the existing MV sink is that only a single batch description is assumed to be valid at any given time. As a result, the various operators (a) don't have to reason about handling multiple description simultaneously and (b) can aggressively discard state maintained for previous batch descriptions when they see a new one.
This touches https://github.com/MaterializeInc/database-issues/issues/8464 in that it simplifies reasoning about times in the correction buffer that can be consolidated, and introduces a `Correction::lower` that a disk-backed correction buffer will likely also need.
The new MV …
> compute: MV sink refresh

- test/kafka-auth/test-schema-registry-mssl.td
Failed 16 times in CI: https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%2C%7B%22id%22%3A%22content%22%2C%22value%22%3A%22files%20involved%3A%20test-schema-registry-mssl.td%22%7D%5D
I'm not sure if this indicates something worse or is just an inconsistent error message.
> kafka auth test: Handle different error

- .cargo/config.toml
- ci/builder/Dockerfile
- misc/python/materialize/xcompile.py
Fails locally with:
```
rust-lld: error: --compress-debug-sections: LLVM was not built with LLVM_ENABLE_ZSTD or did not find zstd at build time
```
Follow-up to https://github.com/MaterializeInc/materialize/pull/30496
> build: Keep non-bazel builds on zlib for now

- src/environmentd/src/environmentd/main.rs
- src/environmentd/src/test_util.rs
- src/orchestrator-kubernetes/src/lib.rs
- src/orchestrator-kubernetes/src/secrets.rs
- src/service/src/secrets.rs
- src/sqllogictest/src/runner.rs
now that we are defaulting to the kubernetes secret provider, we need to make sure that secrets from different environments in the same namespace don't conflict
> also prefix the names of kubernetes secrets

- misc/helm-charts/operator/templates/deployment.yaml
- misc/python/materialize/cli/orchestratord.py
- src/orchestratord/src/controller/materialize.rs
this will make version bumps easier
> set a default for the console image tag to use

- src/expr/src/relation/canonicalize.rs
- src/expr/src/scalar.rs
- src/sql/src/plan/lowering.rs
- src/transform/src/column_knowledge.rs
- src/transform/src/nonnullable.rs
- src/transform/src/predicate_pushdown.rs
Instances of explicit construction of `Datum::True` and `Datum::False` literals are replaced with the existing `literal_true` and `literal_false` methods.
> Use provided methods to construct literals

- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- misc/helm-charts/testing/environmentd.yaml
sync the versions used in the helm chart with the actual database release
we're working on automating this in #30493 for future releases, but this should at least move us toward how we want this to be managed
this isn't going to quite work as-is, because #30512 added a new command line flag to the helm chart that didn't exist in v0.125.0, but i think this is just a thing we're going to have to deal with (i'm pretty sure that everything that currently tries to use the helm chart explicitly sets the orchestratord version to use, and we don't have any external users yet).
> bump the helm chart version

- ci/test/pipeline.template.yml
Seen failing in https://buildkite.com/materialize/test/builds/94819#019330ec-ff9d-47b6-9890-b04487e671ae
> ci: Paralelize pg cdc resumptions tests more

- .config/nextest.toml
- misc/python/materialize/cli/ci_annotate_errors.py
Seen failing in https://buildkite.com/materialize/test/builds/94836#019331c8-c12c-407e-8280-50e6c2d542b3
:rust: Cargo test: Uploading results failed! 'NoneType' object has no attribute 'replace'
Saw another timeout: https://github.com/MaterializeInc/database-issues/issues/8739
> ci: Fix annotation for empty message

- misc/helm-charts/operator/README.md.gotmpl
- misc/helm-charts/testing/README.md
> helm charts: Minor documentation updates

- test/limits/mzcompose.py
Flaked in https://buildkite.com/materialize/release-qualification/builds/678#01931c3f-de6d-4476-bfc5-8469d6e570b0
> product-limits test: Reduce MAX_COUNT further

- misc/python/materialize/version_ancestor_overrides.py
- src/catalog/src/expr_cache.rs
- test/limits/mzcompose.py
> Various CI fixes (November 18)

- src/adapter/BUILD.bazel
- src/adapter/Cargo.toml
- src/expr/BUILD.bazel
- src/expr/Cargo.toml
- src/repr/BUILD.bazel
- src/repr/Cargo.toml
I actually know how to debug this issue now ([steps](https://github.com/bazelbuild/rules_rust/issues/1584#issuecomment-2483313847)), and I figured out that something in the `adapter` crate is non-deterministic, although I'm not sure what. For now I turned off pipelined compilation for the `adapter` crate and will dogfood this locally for a few days before turning it on for CI.
Bazel improve compile times.
> bazel: Fix pipelined compilation, take 3

- doc/user/content/get-started/_index.md
- doc/user/content/support.md
- doc/user/content/transform-data/_index.md
- doc/user/layouts/partials/toc.html
- doc/user/layouts/shortcodes/materialize-postgres-compatibility.html
Small tweaks to Postgres compatibility "strive for compatibility" blurb
> docs: tweak postgresql compatibility blurbs

- misc/python/materialize/cli/ci_annotate_errors.py
Noticed in https://buildkite.com/materialize/nightly/builds/10428#01933f66-82aa-4543-9a0b-14b3a57929e6 that these are currently not printed out as an annotation.
> ci: Annotate unexpected crashes

- Cargo.lock
- src/persist/Cargo.toml
- src/persist/src/cfg.rs
aws s3 only uses alphanumeric client id/secret here, but other s3 compatible systems might not
i'm not actually sure if this is sufficient or if there are other places that might need fixes here - let me know
> urldecode the username/password in s3 urls

- misc/python/materialize/cli/run.py
- misc/python/materialize/cloudtest/k8s/environmentd.py
- misc/python/materialize/cloudtest/k8s/testdrive.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/mzcompose/services/materialized.py
- misc/python/materialize/mzcompose/services/testdrive.py
- src/adapter/benches/catalog.rs
- src/adapter/src/catalog.rs
- src/adapter/src/catalog/state.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/config.rs
- src/catalog/src/durable.rs
- src/environmentd/src/environmentd/main.rs
- src/environmentd/src/test_util.rs
- src/materialized/ci/entrypoint.sh
- src/sqllogictest/src/runner.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/consistency.rs
- src/testdrive/src/bin/testdrive.rs
- test/testdrive/github-3955.td
- test/testdrive/system-cluster.td
Tests define their cluster replica sizes without relying on the builtin defaults.
This allows us to decouple the builtin sizes in the materialize binary to differ from what tests require. It's a step towards a better emulator experience.
This PR turned out bigger than expected because we'd use the builtin defaults in places where we shouldn't. Tracing the places is hard, often because the place where the defaults are used is separated from where we encounter potential inconsistencies. To avoid the issues going forward, this PR changes the way we handle default cluster replica sizes: It's not an optional parameter anymore but all callers need to provide it to environmentd and testdrive. Only sqllogictest still uses the default.
The PR adjusts all entrypoints within the materialize repo to …
> Tests define custom cluster replica sizes

- misc/python/materialize/cli/ci_annotate_errors.py
Seen in https://buildkite.com/materialize/nightly/builds/10439
> ci: Ignore qemu segfaults for now

- src/storage-types/src/sources/load_generator.rs
- src/storage/src/source/generator.rs
As an additional change, this changes when we report a load-generator source as running:
We need this to figure out whether a load-generator source has hydrated
or not, for 0dt upgrades. It turns out that there are load-generator
sources out there in the wild that take multiple minutes to go through
their prefix, that is before they arrive at a point where they produce
new data.
We consider them to be hydrated once their offset is beyond the
resume_offset.
> storage: enable read-only rehydration for load-generator

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
Make operator readme requests.cpu a string.
```
Invalid value: "integer": spec.environmentdResourceRequirements.requests.cpu in body must be of type string: "integer"
```
https://materializeinc.slack.com/archives/C07PN7KSB0T/p1731987619354859
> Make operator readme requests.cpu a string.

- misc/helm-charts/testing/minio.yaml
Move minio bucket creation to postStart hook.
Having this creation in an init container can never work, as minio doesn't start until after the init container is up.
Additionally, the myminio alias relied on a service which would not become ready until after the postStart hook, so changing to just point at localhost.
Testing minio.yaml fails to come up.
https://materializeinc.slack.com/archives/C07PN7KSB0T/p1731989611785929
> Move minio bucket creation to postStart hook.

- src/adapter/src/coord/caught_up.rs
- src/storage-client/src/controller.rs
- src/storage-controller/src/lib.rs
This was somewhat annoying to fix because metrics/stats reporting was busted for UPSERT/sources (and potentially other things). The first commit fixes that.
Fixes https://github.com/MaterializeInc/database-issues/issues/8746
> storage,adapter: in caught_up.rs, add hydration check for storage collections

- src/timely-util/src/operator.rs
Replica expiration: downgrade an error to a warning
Instead of logging an error, we print a warning when the replica expiration stream operator reaches an unexpected frontier. Considering the alternatives, this seems to be the best approach at the moment.
* Logging an error produces false-positives during dataflow shutdown. Dropping the token can race with dataflow shutdown, for example if the last remaining upstream capability is on a different worker. The local worker then could first see the dataflow shutting down before the worker gets to dropping the token. We do not want to log an error in this case.
* Once we reach the state where the frontier has advanced too far, but the token hasn't been dropped, we've either encountered a bug, or a racy shutdown, but we cannot distinguish the …
> Replica expiration: downgrade error to warning

- misc/python/materialize/mzcompose/__init__.py
The default interval makes tests that use `mz_source_statistics_raw` painfully slow.
> tests: speed up tests that rely on storage statistics

- src/compute-client/src/controller/instance.rs
- test/cluster/mzcompose.py
This PR makes the compute controller advance the write frontier of new storage sink collections (MVs, CTs) to the write frontier of the target storage collection.
Previously it didn't do that, which is normally fine because once a replica has installed the dataflow it will send a `Frontiers` response to bump the write frontier in the controller. However, if the cluster has no replicas (e.g. because it is paused between MV refreshes) this doesn't happen. In this case, the write frontier would get stuck at dataflow creation time, which made the implied capability get stuck at the same time too, which in turn held back compaction of the dataflow inputs to the same time. If the write frontier of the target storage collection is significantly in the future, this holding back is undesired, as …
> compute: properly initialize uppers of storage sinks

- misc/python/materialize/cli/orchestratord.py
argument parsing becomes a bit annoying otherwise
> make the subcommand for bin/orchestratord required

- Cargo.lock
- src/orchestratord/BUILD.bazel
- src/orchestratord/Cargo.toml
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
- src/sql/src/catalog.rs
Adds preliminary support for other cloud providers to orchestratord.
Does not add any special handling of them, but accepts GCP, Azure, and Generic cloud providers.
In the future, we may want to expand our support for these to include their equivalent of IAM roles, to support advanced features such as non-password-based access to persist buckets or assuming roles, but that is all out of scope for now.
With self-hosted, our customers may run this in other cloud providers.
> Add preliminary support for other cloud providers to orchestratord

- misc/python/materialize/cli/run.py
Set `--boostrap-cluster-replica-size` in `bin/environmentd` and related.
Fixes a bug reported on Slack: https://materializeinc.slack.com/archives/CM7ATT65S/p1732029052219219
> Set boostrap replica size in cli

- misc/python/materialize/mzcompose/composition.py
Reported by Parker in https://materializeinc.slack.com/archives/CM7ATT65S/p1732031036476939?thread_ts=1732029052.219219&cid=CM7ATT65S
> mzcompose: Only pass extra args as -e, don't overwrite environment

- src/catalog/src/expr_cache.rs
- src/expr/src/relation.rs
Previously, the expression cache tests were timing out because of how long they spent generating random expressions. This commit tries to resolve the issue by
- Simplifying the random expression generator.
- Adding timeouts and retries if an expression is taking too long generate.
Resolves #8739
> test: Prevent timeout in expr cache tests

- test/kafka-rtr/mzcompose.py
See https://github.com/MaterializeInc/database-issues/issues/8657
> kafka-rtr test: Disable multithreaded test for now

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/coord.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/config.rs
- src/testdrive/src/action.rs
- src/testdrive/src/action/consistency.rs
This commit disables the expression cache in testdrive during catalog
consistency checks. We were noticing elevated CPU usage in testdrive
after merging the expression cache during catalog consistency checks.
The expression cache is still used by environmentd during testdrive
tests unless it's disabled.
Additionally, this commit disables the expression cache when 0dt
upgrades are disabled. Certain upgrade tests that have 0dt disabled do
not increment the deploy generation between versions which breaks the
expression cache. 
Resolves #MaterializeInc/database-issues/issues/8759
> testdrive: Disable expr cache in consistency check

- ci/slt/pipeline.template.yml
The tests have become slower but I've failed to find a culprit so far. Timeout occurred in https://buildkite.com/materialize/slt/builds/6097#_
> slt: Bump timeout

- src/adapter/src/coord/caught_up.rs
- test/cloudtest/test_disk.py
- test/upsert/mzcompose.py
This fixes a problem that came from the combination of two changes:
- In https://github.com/MaterializeInc/materialize/pull/30518 we
introduced a hydration check for sources
- In https://github.com/MaterializeInc/materialize/pull/30536 we
introduced re-hydration of load-generator sources in read-only mode
Load-generator sources have a tendency to be finished, that is their
write frontier goes to `[]` (the empty antichain). In those cases,
storage will not render any ingestion dataflow and we would therefore
wait indefinitely for one to be hydrated.
The fix is to treat collections whose write frontier is the empty
antichain as caught up.
I stacked this on top of https://github.com/MaterializeInc/materialize/pull/30577, which fixes other nightly failures that other changes of mine …
> 0dt: fix caught-up check for empty write frontiers

- src/storage/src/upsert.rs
- src/storage/src/upsert/autospill.rs
- src/storage/src/upsert/memory.rs
- src/storage/src/upsert/rocksdb.rs
- src/storage/src/upsert/types.rs
- src/storage/src/upsert_continual_feedback.rs
- test/upsert/mzcompose.py
For our purposes, an ingestion spike is a large batch of updates (from
the external source) at the same timestamp that we need to ingest. And
specifically we want to make the feedback UPSERT operator robust in
terms of memory/storage usage. Below, I'll first explain the behavior of
the classic UPSERT operator and the feedback UPSERT operator as they are
before this change, and later describe the behavior of the feedback
UPSERT operator after this here change.
We differentiate between costs in terms of memory, which is strictly
talking about RAM, and storage, which is talking about upsert state
being stored in the upsert state backend. The upsert state backend can
(currently) either be storing state in memory or on disk (rocksdb).
As an side, ingestion spikes occur a) when ingesting an …
> storage: make feedback UPSERT robust against ingestion spikes

- src/transform/src/analysis/equivalences.rs
- src/transform/src/equivalence_propagation.rs
- test/sqllogictest/advent-of-code/2023/aoc_1212.slt
- test/sqllogictest/explain/optimized_plan_as_json.slt
- test/sqllogictest/explain/optimized_plan_as_text.slt
- test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
- test/sqllogictest/github-2799.slt
- test/sqllogictest/joins.slt
- test/sqllogictest/ldbc_bi.slt
- test/sqllogictest/ldbc_bi_eager.slt
We recently learned to incorporate nullability information from types into `Equivalences`, automatically. This had a curious outcome, which is that `Join` terms would inherit this information presented as constraints, essentially adding the constraints that various columns and expressions and such be non-null. This was largely fine, because we prune away redundant constraints in subsequent passes, ... unless we don't. Some of the conclusions were too clever for our clean-up pass, which doesn't reason as deeply as `Equivalences`.
The fix is to make sure the nullability information is included early, which it is by virtue of the input equivalence classes containing the information, and to then reduce the join equivalences in light of the input equivalences, and then *do not re-introduce the …
> Tidy `Join` logic in `EquivalencePropagation`

- src/adapter/src/coord/statement_logging.rs
- src/environmentd/tests/server.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
We decided in the flex-deployment sync that it'd be okay to create a system variable for enabling statement logging for system users for flex deployment https://materializeinc.slack.com/archives/C07PN7KSB0T/p1731602524871939. Wondering if it's even worth it to create a launch darkly flag for this?
> Add system variable for enabling statement logging for system users

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- misc/python/materialize/cli/orchestratord.py
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/console.rs
- src/orchestratord/src/controller/materialize/resources.rs
- src/sql/src/catalog.rs
it adds complexity and doesn't really do anything useful
> remove the --local-development flag from orchestratord

- src/repr/src/optimize.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- src/transform/src/lib.rs
- src/transform/src/reduce_reduction.rs
- test/sqllogictest/attributes/mir_arity.slt
- test/sqllogictest/attributes/mir_column_types.slt
- test/sqllogictest/autogenerated/all_parts_essential.slt
- test/sqllogictest/explain/aggregates.slt
- test/sqllogictest/explain/physical_plan_aggregates.slt
- test/sqllogictest/explain/physical_plan_as_json.slt
- test/sqllogictest/explain/physical_plan_as_text.slt
- test/sqllogictest/explain/physical_plan_as_text_redacted.slt
- test/sqllogictest/not-null-propagation.slt
- test/sqllogictest/privilege_checks.slt
- test/sqllogictest/simple_multiline.slt
- test/sqllogictest/system-cluster.slt
- test/sqllogictest/transform/aggregation_nullability.slt
- test/testdrive/distinct-arrangements.td
- test/testdrive/session.td
This is an experimental PR where we break apart `Reduce` operators that would be rendered with the `Collation` plan into atomic `Reduce` operators that are joined together instead. This has the potential to be (much) better than the collation plan, or .. to be worse. If we put an `ArrangeBy` at the end it wouldn't be worse, but it could be much better.
This PR is mostly to look at some plans and see what changes and how.
Edit: More explanation here: https://materializeinc.slack.com/archives/C02PPB50ZHS/p1673028168703109
Edit2: Slack message copy/pasted for visibility:
> Other Reduce thought: We have various flavors of reduce plans, roughly three (accumulable, hierarchical, and "generic"). We collate these together with another reduce though .. we should just use a delta join. All of the …
> Break complex `Reduce` operators into simpler ones

- src/compute-client/src/protocol/command.rs
- src/compute/src/server.rs
Introduce InstanceConfig::compatible_with to check if two configurations
are compatible. Two configurations are considered compatible iff the
logging configuration is equal and the expiration offset of the other
configuration is stricter than or equal to the current one.
Addresses a concern with replica expiration that didn't allow us to
strengthen the value without risking replica restarts in case of envd
restarts. This doesn't solve the problem of relaxing the expiration, which
would still cause replica restarts -- there doesn't seem to be a good
alternative because the replicas aren't actually compatible.
> Instance config with stricter offset is compatible

- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/merge.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/usage.rs
- src/persist-client/src/write.rs
In https://github.com/MaterializeInc/materialize/pull/30094, we added the ability to spill very long runs out to external state, to limit the amount of data we needed to keep in memory at once. However, there is another way that state can grow large: by appending individual batches with many runs. (Those runs will ~eventually get compacted together, but the state will be large in the meantime.)
This PR adds a new limit to the number of runs that a batch builder will produce. It does this by triggering background compactions whenever the number of runs grows large: so a source that is accumulating a large snapshot, for example, will start consolidating the data in the background as it's being built up.
https://github.com/MaterializeInc/database-issues/issues/8401
Should review fine …
> [persist] Bound the number of runs a batch builder generates

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- test/testdrive/partition-by.td
Including "source tables". (But not subsources - I think the syntax there is less obvious, and IIUC they're already on their way out.)
Followup to https://github.com/MaterializeInc/materialize/pull/30355 -- see that PR for more details.
> [persist / adapter] PARTITION BY for tables

- test/limits/mzcompose.py
Seen in https://buildkite.com/materialize/nightly/builds/10480#01935148-e8bb-4d83-b55c-53e17e0075fa
> limits: Bump limits up again

- src/storage/src/source/kafka.rs
`GlueConsumerContext::activate` is invoked by rdkafka's "queue nonempty callback" and is responsible for waiting up the source operator when new upstream data is available to ingest. It does so through a `tokio::sync::Notify`. Previously, it would call `notify_waiters`, which is documented to only wake up existing waiters. So in cases where the source operator was not currently waiting (e.g. because it was still busy processing the last batch of upstream updates), we could lose notifications. This is avoided by using `notify_one` instead, which stores a permit that ensures that the source operator gets immediately woken up when it starts waiting on the `Notify` next.
> storage/kafka: avoid dropping rdkafka activations

- test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
This might have changed in https://github.com/MaterializeInc/materialize/pull/17013 or https://github.com/MaterializeInc/materialize/pull/30583
Seen failing in https://buildkite.com/materialize/slt/builds/6101
> SLT: Fix two test failures

- misc/python/materialize/checks/all_checks/sink.py
Seen timing out in https://buildkite.com/materialize/nightly/builds/10480#01935148-e946-45d7-8f71-8908de83f91c
> platform-checks: Increase timeout in SinkPartitionByDebezium check

- src/persist-types/src/stats2.rs
- src/repr/src/row/encode.rs
- src/repr/src/stats2.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/stats.rs
Many of our stats abstractions date to when we calculated stats both incrementally and in batch, but we only do the latter now... which means we can tidy up quite a bit of structure that we no longer need.
Previously-unspecified refactoring. (This code came up in a recent incident, and while I don't think this refactoring has removed any bugs, I think it does make it more straightforward to follow.)
Split into small commits to make it easier to digest!
> [persist] Clean up some unused / restrictive code in stats

- test/limits/mzcompose.py
Seen in https://buildkite.com/materialize/release-qualification/builds/682#_
> product limits test: Some further timeouts

- .bazelrc
- Cargo.toml
This reverts commit 933ddba7314c5dc9493e9ab7087abfa80eacc7b8.
This is not great for debugging, see https://materializeinc.slack.com/archives/C049UQ3RSF4/p1732282239435699
> Revert "builds: Switch to line-tables-only, even for tagged builds"

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
Sometimes runs slowly, hasn't found issues recently
See for example https://buildkite.com/materialize/test/builds/95252#019357ee-9d4c-47df-8483-b7ddd4dc0d5c
> ci: Move replica isolation to nightly

- src/compute-types/src/plan/render_plan.rs
The `Arbitrary` impl of `Plan` can return plans with invalid binding structure, making the `Arbitrary` impl of `RenderPlan` panic. Filter out invalid `Plan`s instead.
Fixes https://github.com/MaterializeInc/database-issues/issues/8785
> compute: fix RenderPlan's Arbitrary impl

- ci/test/pipeline.template.yml
- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- misc/python/materialize/feature_benchmark/scenarios/scale.py
For context see https://materializeinc.slack.com/archives/C0761MZ3QD9/p1732280715336919
Successful nightly: https://buildkite.com/materialize/nightly/builds/10501
Release qualification with known regression: https://buildkite.com/materialize/release-qualification/builds/688
> feature-benchmark: Increase scale of fast scenarios, reduce retries

- Cargo.lock
- misc/cargo-vet/config.toml
- src/compute/Cargo.toml
- src/metrics/Cargo.toml
- src/metrics/src/lgalloc.rs
- src/ore/Cargo.toml
- src/timely-util/Cargo.toml
See https://materializeinc.slack.com/archives/C07PN7KSB0T/p1732360387888179
> build(deps): Bump lgalloc to 0.4.0

- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/cli/admin.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/gc.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/state_versions.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/read.rs
- src/persist-client/src/usage.rs
These weren't actually configurable without a code change!
Previously unreported: we wanted to tweak these during a recent escalation and found them disconnected.
> [persist] Switch the last Persist dynamic configs to dyncfg

- src/adapter/src/config/frontend.rs
we're seeing this timeout during environmentd startup in cloud sometimes and it doesn't seem to be all that useful
> remove Drop impl for SystemParameterFrontend

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/values.yaml
make things easier to install into an empty cluster - if the user needs to configure network policies, they'll know
> default to not installing network policies

- src/transform/src/equivalence_propagation.rs
Our rules for expression substitutability in `EqProp` are more conservative than they may need to be. This was observed in attempts to remove `ColumnKnowledge`: in at least one case we avoid performing literal substitution because the result does not simplify to a literal, but .. it is just as fine to perform a substitution of a fragment of an expression by a literal, as far as we know (the constraints are imposed by other transforms that require idiomatic expressions).
This PR extracts the "acceptability" logic into a separate function, that for the moment accepts an expression if for each AST node it either matches, or replaces it with a literal. We perform this test before expression simplification to have a better view of  the substitution performed, as expression reduction may …
> Adjust rules for EqProp expression substitutability

- misc/python/materialize/cli/ci_annotate_errors.py
Fixes: https://github.com/MaterializeInc/database-issues/issues/8749
> k8s recovery test: Ignore leadership panic on old envd

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose/composition.py
- test/0dt/mzcompose.py
> 0dt source rehydration testing: Postgres, MySQL, Kafka

- test/0dt/mzcompose.py
Seen failing in https://buildkite.com/materialize/test/builds/95306#019363ab-7327-443e-9824-d431600db62f
> 0dt test: Unflake by waiting for sink to create kafka topic

- .bazelrc
- misc/bazel/README.md
Along with a max size for the disk cache (which already exists) this PR also sets a max age for local artifacts at 14 days.
Improve the Bazel experience
> bazel: Small tweak to disk cache

- ci/mkpipeline.py
Seen in https://buildkite.com/materialize/test/builds/95282#01936060-5ef7-45cc-83f8-4fcde49bd839
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 4115 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
> ci: Automatically retry on temporary github issues

- src/transform/src/equivalence_propagation.rs
Although `EquivalencePropagation` was reducing expressions relative to its equivalences, it was not reducing expressions in the context of their input types, which is what does things like constant folding and other inherent simplification. The `reduce` function requires type information, so the `Equivalences` reduction cannot do this by itself (it doesn't have type information).
> Have `EqProp` reduce expressions more

- src/transform/src/lib.rs
- src/transform/src/normalize_lets.rs
- test/sqllogictest/not-null-propagation.slt
- test/sqllogictest/transform/fold_constants.slt
This PR refactors how we run `FoldConstants` in the first commit, and then does some minor cleanups in subsequent commits. (It's best to review it commit-by-commit.)
As discussed in https://github.com/MaterializeInc/database-issues/issues/5346, the problem with the current way we call `FoldConstants` is that `FoldConstants` can't inline Lets, which can instead be done by `NormalizeLets`. Therefore, this PR's first commit creates a function that bundles together `FoldConstants` with `NormalizeLets` into a fixpoint loop, so they can alternate when needed, and thus run the constant folding to completion. This new function is now called every time where the old code used to just call `FoldConstants`.
Additionally, the PR also adds `ReduceScalars` in the same fixpoint loop, because that …
> Refactor how we run `FoldConstants`

- Cargo.lock
- src/adapter/src/catalog.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
- src/adapter/src/config/backend.rs
- src/adapter/src/coord.rs
- src/adapter/src/error.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/config.rs
- src/environmentd/src/http.rs
- src/environmentd/src/lib.rs
- src/environmentd/tests/server.rs
- src/pgwire-common/Cargo.toml
- src/pgwire-common/src/conn.rs
- src/pgwire-common/src/lib.rs
- src/pgwire/src/protocol.rs
- src/pgwire/src/server.rs
- src/sql/src/session/user.rs
- src/sql/src/session/vars.rs
This PR refactors our max connection handling in a few ways:
1. It pulls the logic out of the `sql` crate and moves it into the `pgwire_common` crate. AFAICT this logic lived in the `sql` crate so it could be updated via `SystemVars`.
2. Refactors `SystemVars` to contain a generic set of callbacks so anyone can register to be notified about changes to a system variable, not just connection handling.
It also fixes a bug that has occurred in production. Previously if the max connection limit dropped below the number of current connections (e.g. reducing the LaunchDarkly flag) we could panic.
Fixes a known [panic](https://materializeinc.sentry.io/auth/login/materializeinc/?next=%2Fissues%2F5979946058%2Fevents%2Fff772de8c8b34c3bb11b240b93745222%2F%3Fproject%3D6780145) and refactors the code. …
> adapter: refactor max connection handling

- src/transform/src/equivalence_propagation.rs
- src/transform/src/lib.rs
- src/transform/tests/test_runner.rs
- src/transform/tests/test_transforms.rs
- src/transform/tests/test_transforms/column_knowledge.spec
- test/sqllogictest/advent-of-code/2023/aoc_1219.slt
- test/sqllogictest/record.slt
- test/sqllogictest/transform/column_knowledge.slt
- test/sqllogictest/transform/join_index.slt
- test/sqllogictest/transform/literal_constraints.slt
The `ColumnKnowledge` transform is largely dominated by `EquivalencePropagation`, to the extent that we now have no tests that observe the absence of `ColumnKnowledge` when replaced by `EquivalencePropagation`.
This PR has some additional tidying that we'll want (various references to this transform, and the file itself still included in the repo), but ideally we should be able to agree on the shape of that without much iteration.
> Replace `ColumnKnowledge` with `EquivalencePropagation`

- doc/user/assets/sass/_layout.scss
- doc/user/config.toml
- doc/user/layouts/partials/banner.html
- doc/user/layouts/partials/toc.html
@nisarhassan12: would you mind adjusting the CSS so the header doesn't eat into the sections below because of the added banner?
> doc/user: add self-managed banner

- src/transform/src/equivalence_propagation.rs
We recklessly substitute expressions in `TopK::limit`, but should guard this behavior by only performing substitutions that result in literals replacing expressions. This avoids the peril of introducing expressions referencing non-key columns, which results in catastrophic failure.
> Guard `TopK::limit` substitution

- src/persist-client/src/batch.rs
- src/persist-client/src/internal/compact.rs
When we added the hollow-run change recently to spill long run metadata to S3, we explicitly overrode it for unordered data... because we want to split up all unordered data into single-part runs. However, I also accidentally removed that override as part of a large refactoring last week. 😅 This triggered a known limitation in the compaction code, which wasn't prepared to run into hollow runs in an order that doesn't match the desired order.
This fixes the issue two ways: it restores the override, and it removes the limitation in the compaction code.
https://github.com/MaterializeInc/database-issues/issues/8766
I've tested that each of these commits is enough to make the repro in the linked issue succeed. I'll also get a full nightly run going on this branch...
> [persist] Fix regression in the batch-builder refactoring

- test/terraform/mzcompose.py
environmentd is reported as "Running" in kubectl before it is actually listening on its ports
Seen failing in https://buildkite.com/materialize/nightly/builds/10541#01936b08-6eb4-49de-a7c8-2b102b7f6733
```
E1127 00:48:20.551735    2205 portforward.go:406] an error occurred forwarding 6875 -> 6875: error forwarding port 6875 to pod 487c65896791af9e19f77eaaed22bcf62281e447c5b20257c3fab99ece85ede7, uid : failed to execute portforward in network namespace "/var/run/netns/cni-b7379791-8739-599d-2a1f-6717e8afb3f9": failed to connect to localhost:6875 inside namespace "487c65896791af9e19f77eaaed22bcf62281e447c5b20257c3fab99ece85ede7", IPv4: dial tcp4 127.0.0.1:6875: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
```
@doy-materialize Is there something we …
> terraform e2e test: Fix flakiness by sleeping longer

- misc/python/materialize/feature_benchmark/scenarios/concurrency.py
Thanks to @teskje for noticing: https://materializeinc.slack.com/archives/C01LKF361MZ/p1732700985898469
Had to bump the version since this will change performance of the scenario (it was basically broken before)
> feature-benchmark: Create index on table, not source

- src/kafka-util/src/client.rs
- src/storage/src/sink/kafka.rs
- test/ssh-connection/kafka-sink.td
The code correctly set the desired transaction timeout value when instantiating the producer but then incorrectl used the socket timeout as the limit for the commit call. This led the `librdkafka` client to stop trying after 60 seconds, which is the default value of the socket timeout.
This PR instead sets the timeout to `Timeout::Never` which according to the `librdkafka` documentation automatically sets the timeout to the remaining transaction time based on the transaction_timeout_ms setting.
> sink/kafka: actually use the configured tx timeout

- doc/user/data/sql_funcs.yml
As reported in the community Slack, it looks like that `COUNT()` is documented to return an `int`, but in reality returns a `bigint`
> docs: change count() signature to bigint

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
Recently we had a bug that only appeared when writing many parts, and we don't have great CI coverage of those.
This configures the batch size to be smaller by default, and possibly vary, during CI tests. This shouldn't have a big impact on performance for CI-type workloads - most writes should still fit in a single part - but it gives us more coverage of the "long run" cases than we'd otherwise have.
> [persist] Reduce the max-batch-size config in CI

- ci/nightly/pipeline.template.yml
Keeps popping up on main and in PRs, until https://github.com/MaterializeInc/database-issues/issues/8366 is fixed
> ci: Disable another flaky RQG test for now

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
Since it's very similar to another one in nightly, so unlikely to find extra bugs
Green runs:
https://buildkite.com/materialize/nightly/builds/10552
https://buildkite.com/materialize/release-qualification/builds/689
https://buildkite.com/materialize/nightly/builds/10550
> ci: Switch a few nightly jobs over to Hetzner, move one to Release Qualification

- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- misc/python/materialize/version_ancestor_overrides.py
- src/catalog/src/expr_cache.rs
> feature-benchmark: Two fixes for nightly (November 28)

- .bazelrc
This reverts commit e39999ca84c6d176665b01c7a9e875106dc0a44b.
Checked locally if this helps with file/line numbers in panics, and it does indeed. Before this PR:
```
./materialized
thread 'main' panicked at src/materialized/src/bin/materialized.rs:18:18:
Unknown executable: Some("materialized2")
stack backtrace:
[hangs indefinitely!]
```
Sometimes the backtrace is printed correctly but without file/line:
```
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: materialized::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
With this PR works reliably:
```
thread 'main' panicked at src/materialized/src/bin/materialized.rs:18:18:
Unknown executable: Some("materialized")
stack backtrace:
0: rust_begin_unwind
at …
```
> Revert "ci: Try zstd compression for debug sections"

- src/storage/src/source/postgres/replication.rs
We've encountered at least one issue in local testing where the upstream Postgres DB's `wal_sender_timeout` is low enough that the timeout elapses before any of our existing inputs trigger a keepalive message to be sent.
This PR adds a `tokio::Interval` to the existing loop so we can make sure we are sending a standby update/keepalive at least a healthy interval.
Fix an issue we've encountered in local testing with Neon.
Related to: https://github.com/MaterializeInc/incidents-and-escalations/issues/146
This is my first foray into storage code! It's a relatively simple change, but there could be nuances with control flow that I'm missing
> storage/postgres: Always send `keepalives` for the replication slot with a `tokio::interval`

- .github/workflows/slack_notify_labeled.yml
Noticed in https://materializeinc.slack.com/archives/CTESPM7FU/p1732818066822189
> slack: Notify on release blocker PRs

- ci/plugins/cloudtest/hooks/command
- misc/python/materialize/version_ancestor_overrides.py
- test/cluster/blue-green-deployment/deploy.td
- test/cluster/blue-green-deployment/setup.td
> CI test failure fixes (November 29)

- .bazelrc
Seen failing in v0.126.0 x86-64 build: https://buildkite.com/materialize/test/builds/95517#019376c0-e43d-4fb4-9420-46ccb4c95d9d
Successful x86-64 build on v0.126.0 state: https://buildkite.com/materialize/test/builds/95523#019376d7-b606-4a7f-a726-0ef02aa562ef
> bazel: Try disabling in-memory sandbox stash

- .bazelrc
- doc/user/content/releases/v0.126.md
This should fix feature benchmark in test pipeline
Also reverted the one Bazel change I tried, which had no effect (v0.126.1 with it still failed to build)
> docs: Bump v0.126 patch version to 2

- src/repr/src/stats2.rs
Failed 3 times before: https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%2C%7B%22id%22%3A%22content%22%2C%22value%22%3A%22proptest_uuid_sort_order%22%7D%5D
> miri test: Disable slow proptest_uuid_sort_order

- bin/gen-completion
- misc/completions/zsh/_scratch
- misc/python/materialize/cli/scratch/forward.py
- misc/python/materialize/cli/scratch/push.py
- misc/python/materialize/cli/scratch/sftp.py
- misc/python/materialize/cli/scratch/ssh.py
- misc/python/materialize/scratch.py
We expect most users to have at most one scratch machine at any time. This makes it a little easier to manipulate that specific machine without having to copy the id around.
Internal discussion!
I've done some manual testing, including with >1 and <1 instance, but I'm not sure there's any reasonable way to write automated tests here. I think that's probably okay for a dev script?
> Allow specifying `mine` in bin/scratch commands

- misc/python/materialize/version_ancestor_overrides.py
See https://github.com/MaterializeInc/database-issues/issues/8801
Test runs:
https://buildkite.com/materialize/nightly/builds/10573
https://buildkite.com/materialize/release-qualification/builds/697
> feature-benchmark: Ignore regression in InsertMultiRow

- misc/python/materialize/version_ancestor_overrides.py
- src/storage/src/source/kafka.rs
In the Kafka source, give the metadata thread its own consumer so it doesn't get blocked by fetches concurrently performed by the reader thread.
Fixes https://github.com/MaterializeInc/database-issues/issues/8751
The diff is nicer with whitespace changes hidden.
There is a 1s regression in Kafka source startup time that's expected. See [this Slack thread](https://materializeinc.slack.com/archives/C0761MZ3QD9/p1732280715336919) for details.
The 1s regression can also cause larger regressions in our feature benchmarks, caused by load getting shifted into the measurement period where it was previously happening in the setup period. These are not actual regressions but artifacts of the way we measure runtime in the feature benchmarks. See [this Slack …
> storage/kafka: use separate consumer for metadata probing

- bin/ci-builder
- ci/builder/Dockerfile
Noticed in https://buildkite.com/materialize/test/builds/95579#01938475-432c-424d-a738-fcbda4a4f283
> ci-builder: Fix build with Rust 1.80.1 and detect WORKSPACE changes

- ci/release-qualification/pipeline.template.yml
- misc/python/materialize/version_ancestor_overrides.py
- test/limits/mzcompose.py
Seen in https://buildkite.com/materialize/release-qualification/builds/696
> ci: Make release qualification green (hopefully)

- test/upsert/autospill/03-rocksdb.td
See https://github.com/MaterializeInc/database-issues/issues/8802
> upsert test: Workaround for bug

- .bazelrc
- ci/deploy/pipeline.template.yml
- ci/mkpipeline.py
- ci/mkpipeline.sh
- ci/nightly/pipeline.template.yml
- ci/qa-canary/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/slt/pipeline.template.yml
- ci/test/pipeline.template.yml
Enable verbose failures for Bazel builds in CI so it's easier to debug issues.
Also reverts #30657 
Make it easier to fix build failures when they arise
> bazel: enable verbose failures

- src/adapter/src/coord.rs
> adapter: convert panic to terminate

- .bazelrc
I've actually figured out how to debug build failures when they occur, and I've also been dogfooding pipelined compilation locally with great success. Figured we might as well give it a shot in CI.
Make Bazel builds faster.
> bazel: re-enable pipelined compilation

- src/adapter/src/catalog.rs
- src/adapter/src/coord.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/objects/state_update.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/persist/tests.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/src/durable/upgrade.rs
- src/catalog/tests/debug.rs
- src/catalog/tests/open.rs
- src/catalog/tests/read-write.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
This commit optimizes the startup process to deserialize the audit log
in the background. Opening the durable catalog involves deserializing
all updates, migrating them, and then storing them in memory. Later the
in-memory catalog will take each update and generate a builtin table
update and apply that update in-memory. Throughout the startup process
audit logs are heavily special cased and only used to generate builtin
table updates. Additionally, audit logs are by far the largest catalog
collection and can take a long time to deserialize.
This commit creates a new thread at the beginning of the startup
process that deserializes all audit log updates. A handle for the
thread is plumbed throughout startup and then joined only when we
actually need the builtin table updates. By …
> catalog: Deserialize audit log in background

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
we want to be able to log in as the materialize user on the balancer port, and this should work until we actually get a working authentication story for the self-hosted materialize
> allow disabling rbac in orchestratord

- test/0dt/mzcompose.py
Seen flaking in https://buildkite.com/materialize/nightly/builds/10591#01938824-b5dc-4a21-ad87-ee36696458e0
> builtins.AssertionError: Took 2.73917555809021s to SELECT on Kafka source after 0dt upgrade, is it hydrated?
I checked the logs but can't find anything strange, here are some durations:
- coordinator init: timestamp oracle init complete in 128.129425ms
- coordinator init: catalog open: expr cache open complete in 116.069545ms
- coordinator init: catalog open complete in 963.663792ms
- controller init: complete in 465.730237ms
- storage collections init complete in 442.866092ms
- optimize dataflow plans complete in 5.831978ms
- coordinator init: bootstrap: dataflow as-of bootstrapping complete in 10.08686ms
- coordinator init: bootstrap: postamble complete in 17.997937ms
- …
> 0dt test: Increase allowed time for SELECT after rehydration

- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- src/adapter/src/catalog/state.rs
- src/adapter/src/client.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/adapter/src/coord/sequencer/inner/explain_timestamp.rs
- src/adapter/src/optimize.rs
- src/adapter/src/optimize/view.rs
- src/transform/src/lib.rs
This PR fixes this regression in INSERT performance: https://github.com/MaterializeInc/database-issues/issues/8801
It adds a new, very simple optimizer pipeline, whose job is just to take care of constant INSERTs.
The test that regressed in the issue by 10-20% compared to v0.125.3 is now 30-40% faster compared to v0.125.3:
https://buildkite.com/materialize/nightly/builds/10584
* This PR fixes a recognized performance regression: https://github.com/MaterializeInc/database-issues/issues/8801
The first commit is just some trivial cleanup, can be reviewed separately.
> Create a special optimizer pipeline for constant INSERTs

- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- test/limits/mzcompose.py
> Nightly fixes (December 3)

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
Orchestratord enable_internal_statement_logging by default.
https://github.com/MaterializeInc/cloud/issues/10504
> Orchestratord enable_internal_statement_logging

- doc/user/content/releases/previews.md
- doc/user/content/sql/comment-on.md
- doc/user/content/sql/system-catalog/mz_internal.md
@ParkMyCar: it seems like the remaining task is to stabilize `mz_comments`. Marked that as a TODO under [#8394](https://github.com/MaterializeInc/database-issues/issues/8394).
> doc/user: promote COMMENT ON to GA

- src/adapter/src/explain.rs
- src/adapter/src/explain/mir.rs
- src/expr-parser/src/parser.rs
- src/expr/src/explain/text.rs
- src/repr/src/explain.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/tests/testdata/explain
- src/sql/src/plan/statement/dml.rs
- src/transform/src/analysis.rs
- src/transform/src/analysis/equivalences.rs
- src/transform/tests/test_runner.rs
- test/sqllogictest/explain/optimized_plan_as_text.slt
We have a bunch of EXPLAIN options to show the results of various Analyses. These are quite useful for debugging. This PR adds an EXPLAIN option for the `Equivalences` Analysis. This makes the behavior of the `Equivalences` Analysis easier to understand, especially for people who are not already familiar with all its details.
* This PR adds a known-desirable feature: https://github.com/MaterializeInc/database-issues/issues/8805
The first 2 commits just do very minor refactorings. The main thing is in the 3rd commit.
> Add an EXPLAIN option to show the `Equivalences` Analysis

- src/environmentd/src/environmentd/main.rs
- src/environmentd/src/lib.rs
Remove balancer ports from environmentd.
Removes some legacy unused ports which made configuring things much more complicated, especially in self-hosted.
https://github.com/MaterializeInc/cloud/pull/10507
> remove balancer ports from environmentd

- src/orchestratord/src/controller/materialize/resources.rs
Fix internal TLS from balancerd to environmentd, by setting the appropriate arg when orchestratord spawns balancerd.
We changed which port we are pointing at. The old port never had TLS, but the new one optionally does.
I can't test this in the console until some other issues are fixed.
https://materializeinc.slack.com/archives/C07PN7KSB0T/p1733229779920169
> orchestratord fix internal TLS from balancerd to environmentd

- src/catalog/src/durable/persist.rs
This commit adds logic to avoid cloning every audit log entry on startup.
Works towards resolving #MaterializeInc/database-issues/issues/8384
> catalog: Avoid cloning audit log

- src/storage/src/source/postgres/snapshot.rs
This fixes a bug where only one worker released the slot_ready capability which meant that the replication operator would be blocked until all non-leader workers finished snapshotting before it could start downgrading its frontier. That in turned would cause all the data produced by the snapshot to be buffered in the reclock operator, since downgrading the frontier is what drives generation of reclock bindings.
> source/pg: release the slot capability from all workers

- ci/nightly/pipeline.template.yml
- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/cloudtest/k8s/redpanda.py
- misc/python/materialize/mzcompose/services/cockroach.py
- misc/python/materialize/mzcompose/services/redpanda.py
- test/kafka-matrix/mzcompose.py
Cockroach issue: https://github.com/cockroachdb/cockroach/issues/136678
See https://materializeinc.slack.com/archives/CTESPM7FU/p1733228518997239
Should fix the failure seen in https://buildkite.com/materialize/nightly/builds/10595#01938b85-c061-425b-967b-c70bff89ace2
Running full nightly to make sure no regressions: https://buildkite.com/materialize/nightly/builds/10600
> Fix s3 connection in cockroach for backup tests, new Redpanda versions

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/resources.rs
bringing in line with the emulator
> enable telemetry by default in the helm chart

- test/cluster/mzcompose.py
Seen failing in https://buildkite.com/materialize/test/builds/95694#01938bf0-ee1b-4e81-aa50-c152e46867ce
@teskje Is this fine or something to be worried about?
> cluster test: Allow higher times in test_optimizer_metrics

- src/storage/src/source/postgres/replication.rs
This PR fixes a long-standing bug of postgres sources that was a result of using owned capabilities in an async operator. Fallible async operators use the standard Rust `?` operator to encode erroring control flow. Unfortunately this doesn't play well with the rest of the timely integration since when `?` is executed on an error the entire stack of local variables will be destructed. If that stack contains capabilities then timely will be notified about frontier updates that are incorrect, and if the timing is right it might have enough to persist those incorrect results to persist.
As a workaround the API for fallible async operators passes the initial capabilites through a reference to operator implementation with the expectation that the operator only uses those capabilties to …
> storage/pg: don't rely on owned capabilities

- src/transform/src/analysis.rs
- src/transform/src/analysis/equivalences.rs
Our analysis framework allows you to build on various other analyses, but to access them you need to probe the collection to get the results, and .. potentially they might not exist (due to a logic bug). There is nothing to do other than panic, and all the "user" code immediately panics with the same messages: "Analysis FOO was required, but is missing".
This PR moves those panics into the analysis container, indicating that some methods may panic when invoked with arguments that cannot be found, not unlike array out of bounds access or key not found errors.
> Move analysis panics into `Derived*`

- src/transform/src/analysis.rs
Seen failing in https://buildkite.com/materialize/test/builds/95791#01939264-eef7-4ac1-99f6-7389fa781c05
Merge skew from https://github.com/MaterializeInc/materialize/pull/30634 and https://github.com/MaterializeInc/materialize/pull/30690
Verified locally:
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 6m 04s
```
> Fix build from merge skew

- src/clusterd/src/lib.rs
- src/compute/src/compute_state.rs
- src/environmentd/src/environmentd/main.rs
- src/environmentd/src/lib.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/metrics.rs
- src/storage/src/storage_state.rs
This PR disables Persist's compaction when environmentd or clusterd are in read-only mode. As part of https://github.com/MaterializeInc/materialize/pull/30205 we discovered that during a 0dt deployment the read-only instance of Materialize was scheduling compaction requests which was causing it to write data.
We disable compaction by adding a `process_compaction_requests: Arc<AtomicBool>` to the `PersistConfig`, and when setting it to `true` when `clusterd` receives the already existing `AllowWrites` command. Also included is a CYA dyncfg that gates whether or not we check the flag, it's set to `true` by default.
I also added a Prometheus metric to count the number of requests dropped because compaction is disabled, a unit test to exercise the basic enable/disable behavior, and manually …
> persist: disable compaction in read-only mode

- doc/user/config.toml
Heh ... the force-push on https://github.com/MaterializeInc/materialize/pull/30726 undid the change 🤣 
https://github.com/MaterializeInc/materialize/compare/6d98e84a51f90778e50c346f4b4752dee8c63573..179fa3cb2235dcaa0011a8704774ec183de48c69
> docs: fix releases left-hand menu

- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/console.rs
- src/orchestratord/src/controller/materialize/tls.rs
* Supports configuring TLS for the console.
* Changes default console HTTP port to 8080.
* Configures console nginx listen port and service to both use the same configured HTTP port.
* Changes certificate private key algorithm from Ed25519 to RSA, due to lack of browser support for certificates signed with Ed25519.
Completes configuration of TLS of the console.
Depends on https://github.com/MaterializeInc/console/pull/3560, so this may need a new console image tag.
This is marked as a draft waiting on the console change, but is otherwise ready to review.
> Orchestratord to configure Console TLS

- .bazelrc
- Cargo.toml
- ci/test/build.py
- misc/python/materialize/cli/run.py
- misc/python/materialize/cloudtest/app/cloudtest_application_base.py
- misc/python/materialize/cloudtest/k8s/api/k8s_resource.py
- misc/python/materialize/mzbuild.py
Motivation is to have a build that is fast for local iteration, especially incremental builds, but still has more runtime performance than debug builds.
My test case to measure incremental build time after touching a single file:
```
$ cargo build --profile optimized --bin materialized
$ touch src/adapter/src/lib.rs
$ cargo build --profile optimized --bin materialized
Finished `optimized` profile [optimized] target(s) in 18.89s
```
vs release:
```
$ cargo build --release --bin materialized
$ touch src/adapter/src/lib.rs
$ cargo build --release --bin materialized
Finished `release` profile [optimized + debuginfo] target(s) in 7m 08s
```
vs dev:
```
$ cargo build --bin materialized
$ touch src/adapter/src/lib.rs
$ cargo build --bin materialized
Finished `dev` profile [unoptimized + …
```
> build: Introduce optimized profile (20x faster incremental build, 20-50% slower runtime performance compared to Release)

- src/storage-client/src/storage_collections.rs
- test/testdrive/github-8809.td
CDCv2 collections are in their own timeline, not in the EpochMilliseconds timeline, and have no need for the reclocking information it contains. It should not be necessary to hold back the read frontier of the progress collection for CDCv2 exports, and it would be wrong to initialize the `since` of CDCv2 exports to the `since` of their progress collection.
> storage: make CDCv2 ingestions not depend on progress collections

- .bazelrc
- misc/python/materialize/mzbuild.py
Tunes the `optimized` build profile introduced in https://github.com/MaterializeInc/materialize/pull/30730, and gets rid of the `release-local` profile since they are essentially the same.
Unfortunately Bazel doesn't support Rust incremental builds, although there's an issue to change `rustc` so it could. See https://github.com/rust-lang/rust/issues/132132
Otherwise the biggest change this makes is to not embed LLVM bitcode which is only used for LTO. Cargo automatically does this when LTO is disabled, but Bazel does not.
Faster "optimized" builds
> bazel: tune the "optimized" build

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/values.yaml
it doesn't actually work with authentication enabled yet, so this is a better default.
additionally, move the helm chart configuration around to avoid confusion between kubernetes rbac and environmentd rbac
> disable authentication by default in the helm chart

- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/balancer.rs
- src/orchestratord/src/controller/materialize/console.rs
- src/orchestratord/src/controller/materialize/environmentd.rs
otherwise the console pods will crashloop for a bit on startup
this involved a bit of refactoring to be able to be able to handle the balancer resources separately, but it should be pretty straightforward moving things around, and i think the end result is pretty easy to understand
> don't create console pods until the balancer service is healthy

- src/adapter/src/catalog/open.rs
> adapter: improve expr cache log

- Cargo.lock
- deny.toml
- misc/cargo-vet/config.toml
- src/prof/Cargo.toml
See https://rustsec.org/advisories/RUSTSEC-2024-0408
Noticed via https://buildkite.com/materialize/security/builds/1366#01939756-58d4-4c0a-86f7-a776304c7560
> build(deps): Update pprof to 0.14.0

- misc/python/materialize/mzcompose/composition.py
- misc/python/materialize/version_ancestor_overrides.py
- src/compute/src/sink/materialized_view_v2.rs
- test/testdrive/github-3955.td
This PR changes the way the MV sink produces updates to the shared sink frontier. Previously it would inspect the `persist` stream and forward that stream's frontier. The issue with this approach is that, in the face of ingestion spikes, the `persist` stream could fall behind, which would also make the MV sink's reported write frontier fall behind.
This led to a regression in the `CrossJoin` feature benchmark. In this benchmark, a large constant MV is created. As soon as the MV dataflow has produced its snapshot and has reported the empty frontier, the controller instructs the replica to drop it. If the reporting of the empty frontier is delayed because the MV sink is busy reading back the entire snapshot from persist, the controller's drop command also gets delayed. The result is that …
> compute: feed MV sink frontier from persist write handle

- ci/test/pipeline.template.yml
- misc/helm-charts/operator/tests/deployment_test.yaml
Broken in https://github.com/MaterializeInc/materialize/pull/30727
Test didn't run, fixing that by considering the misc/helm-charts as input
Seen in https://buildkite.com/materialize/test/builds/95866#01939798-4a11-4849-b2b6-b815244c5455
> Fix helm unittest

- misc/python/materialize/mzcompose/__init__.py
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/session/vars/definitions.rs
- test/legacy-upgrade/create-in-v0.68.0-comment.td
- test/sqllogictest/comment.slt
- test/sqllogictest/ct_various.slt
- test/testdrive-old-kafka-src-syntax/github-7822.td
- test/testdrive/github-7822.td
- test/testdrive/kafka-avro-sinks-doc-comments.td
Removes the `enable_comment` flag since `COMMENT ON` has been released to GA
Fixes https://github.com/MaterializeInc/database-issues/issues/8808
> adapter: remove the `enable_comment` flag

- src/orchestratord/src/controller/materialize.rs
we were accidentally always creating all network policies because apparently setting any value for a bool flag is read as true
> fix default values for orchestratord network policy flags

- src/orchestrator-kubernetes/src/lib.rs
This PR makes the Kube Service created for each cluster `headless` (https://kubernetes.io/docs/concepts/services-networking/service/#headless-services), which I believe was always the intent. This should ensure that DNS resolution of `pod.service.namespace` works when `envd` looks up each `clusterd`.
I believe we've been relying on our Kube clusters' DNS implementations generating pod-specific records even when also assigning a cluster IP, which as far as I can tell from the docs, is not strictly part of the spec.
DNS resolution between `envd` and `clusterd` is broken in some Kube clusters, specifically GKE Autopilot.
> make clusterd service actually headless to ensure direct pod access

- ci/deploy/pipeline.template.yml
- ci/mkpipeline.py
- ci/nightly/pipeline.template.yml
- ci/qa-canary/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
- misc/bazel/README.md
- misc/python/materialize/build_config.py
- misc/python/materialize/cli/bazel.py
- misc/python/materialize/config.py
- misc/python/materialize/teleport.py
This PR makes it easy for developers to start using the Bazel remote cache when running Bazel locally. Namely it does a few things:
1. Adds a `TeleportProxy` class in Python to spawn a proxy using `tsh`, this allows developers to connect to the remote cache running in our infra.
2. Adds the concept of a Materialize Build Config which allows developers to specify the Teleport app to use for the bazel remote cache.
3. Wires these two things in `bin/bazel` to automatically spawn a teleport proxy.
4. Changes CI to use our "prod" Bazel remote cache for builds on `main` or tagged builds.
5. Updates the Bazel docs to specify how users can set this up.
Unfortunately I've identified a few areas where the build config doesn't allow for perfect cache re-use, but this is a step in the right …
> bazel: enable remote caching for developers

- doc/user/content/sql/system-catalog/mz_internal.md
Per @teskje's feedback.
* This PR refactors existing docs.
> doc/user: attempt to clarify source stats semantics

- misc/python/materialize/mzbuild.py
Previously if you tried to specify `--optimized` when using `mzcompose` you would still get the release profile. 
This is because the `--dev` flag is set as `store_false` which creates a default value of `True`, and it's destination was named `release`. So if you only specified `--optimized` both `args.release` and `args.optimize` would be `True` and then we default to `Profile.RELEASE`.
> build: tweak the `--dev`, `--optimized`, and `--release` flags

- misc/helm-charts/operator/templates/deployment.yaml
- misc/python/materialize/parallel_workload/executor.py
- test/terraform/mzcompose.py
1st commit:
> parallel-workload: Fix rollback error
> 
> [worker_2] Query failed: rollback; too many values to unpack (expected 1)
> 
> Seen in https://buildkite.com/materialize/nightly/builds/10631#01939961-e109-456f-b890-eaa7f7f0a11e
2nd commit:
> Fix helm chart deployment template
> 
> Following https://github.com/MaterializeInc/materialize/pull/30728
> 
> Seen failing in https://buildkite.com/materialize/nightly/builds/10631#01939961-e0e3-4196-888e-426667aa97e2
> 
> > error: The value 'true' was provided to '--network-policies-internal-enabled' but it wasn't expecting any more values
We should probably run the terraform e2e test in a PR when something in misc/helm-charts is touched, I'll try to come up with a good way.
> Nightly test fixes (December 6)

- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/open.rs
Previously, the adapter would update it's dyncfg values only in the
following scenarios:
- When retrieving the current compute configuration.
- When retrieving the current storage configuration.
- When receiving periodic configuration updates from launch darkly.
Importantly dyncfgs are un-intuitively not updated as a direct result
of a system configuration parameter changing. One specific consequence
of this is that when starting up, all dyncfgs contain their default
values until the first launch darkly sync or when first retrieving
storage/compute configurations, whichever happens first.
This commit explicitly updates the adapter dyncfg values after any
system configuration parameter is changed. This makes it much more
obvious that the system configuration parameters and dyncfg values …
> adapter: Update dyncfgs with system parameters

- misc/python/materialize/zippy/scenarios.py
- src/storage/src/source/postgres/replication.rs
- test/pg-cdc-resumption/mzcompose.py
- test/pg-cdc/dropped-slot-errors.td
The source would previously select a resumption point based on the resumption points of its outputs (which is correct) advanced by the resumption point available upstream (which is incorrect).
The reason is that if the upstream slot gets dropped and recreated or somehow compacts further that it should we lose the ability to read updates at the LSN offsets we need. When that happens it is crucial to detect that and put the source in an errored state, otherwise we risk presenting incorrect to the user.
This PR tightens our reasoning for choosing the expected resumption point such that the advancement that would previously be done unconditionally is only performed for outputs that have not been ingested yet.
Fixes MaterializeInc/database-issues#8669
> source/pg: detect replication slot overcompaction

- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- test/limits/mzcompose.py
Based on failures in https://buildkite.com/materialize/release-qualification/builds/699#_
> tests: Limit release qualification scenarios

- ci/nightly/pipeline.template.yml
- src/transform/src/equivalence_propagation.rs
The `soft_assert_or_log` that signals when `ColumnKnowledge` does work after `EquivalencePropagation` has been unexpectedly happening a lot in CI. We have enough examples to start fixing the issue, and we don't want to keep CI flaky while we do so. Therefore, this PR downgrades this assert to just a `tracing::error!`. This way, it won't fail CI, but it will still emit a Sentry error when it happens on staging or production.
Additionally, the PR also:
- Includes the dataflow's ID in the error msg.
- Fixes plan tracing, so that we can separately observe the result of EQProp before CK happens.
> Downgrade EQProp-ColumnKnowledge soft_assert

- Cargo.lock
- deny.toml
- misc/cargo-vet/audits.toml
- misc/cargo-vet/imports.lock
- src/workspace-hack/Cargo.toml
Bumps the `url` crate from 2.5.0 to 2.5.4.
When updating the `idna_adapter` dependency, the version chosen is 1.1.0 rather than the latest 1.2.0, as the version is a workaround for global mutually exclusive features https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618 . Version 1.1.0 pulls in `unicode` deps (most of which we already have), rather than `icu4x` deps pulled in by 1.2.0 (most of which would be new).
See https://docs.rs/crate/idna_adapter/latest for more details.
Adds Unicode-3.0 to our allowed license list. Approved in slack https://materializeinc.slack.com/archives/CL68GT3AT/p1733761846039479?thread_ts=1733758324.136849&cid=CL68GT3AT
RUSTSEC-2024-0421
`idna` 0.5.0 and earlier accepts Punycode labels …
> bump url to 2.5.4

- Cargo.lock
- misc/cargo-vet/imports.lock
- src/workspace-hack/Cargo.toml
To get a newer idna library version, see https://rustsec.org/advisories/RUSTSEC-2024-0421
Noticed in https://buildkite.com/materialize/security/builds/1369
> build(deps): bump aws-config version to v1.2.1

- src/adapter/src/coord.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/objects/state_update.rs
- src/catalog/src/durable/persist.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
On startup the adapter reconciles the contents of most builtin tables
via the following procedure:
1. Read in the updates from the relevant durable catalog collection.
2. Generate builtin table updates from the updates.
3. Read in the current contents of the builtin table.
4. Generate builtin table retractions from the current contents.
5. Consolidate the two sets of builtin tables updates.
6. Append the consolidated builtin table updates to the builtin
table.
The audit log is extremely large and deserializing all updates in step
(1) can take an extremely long time. Previously, this deserialization
was done in a background thread to try and hide some of the latency.
The audit log is append only and un-migratable, so the above process is
very wasteful. We know that most of the updates from …
> adapter: Lazily deserialize the audit log

- src/adapter/src/catalog.rs
- src/adapter/src/coord/peek.rs
- src/buf.yaml
- src/compute-types/src/explain/text.rs
- src/compute-types/src/plan.rs
- src/compute-types/src/plan/join.rs
- src/compute-types/src/plan/join/delta_join.rs
- src/compute-types/src/plan/join/linear_join.rs
- src/compute-types/src/plan/lowering.rs
- src/compute-types/src/plan/reduce.rs
- src/compute-types/src/plan/threshold.proto
- src/compute-types/src/plan/threshold.rs
- src/compute/src/render/reduce.rs
- src/compute/src/render/sinks.rs
- src/expr/src/linear.rs
- src/expr/src/scalar.rs
- src/transform/src/join_implementation.rs
- test/sqllogictest/explain/physical_plan_as_json.slt
We use a `BTreeMap<usize, usize>` for the "permutation" from concatenated `[key, val]` columns, when it appears it can always be a `Vec<usize>`: each output column must identify an input column. This also hints that this isn't really a permutation as much as a projection. More generally both of these could be `Vec<MirScalarExpr>` if we ever plan to be so bold (and perhaps this is an opportunity to abstract the specifics away, so that everyone's signatures don't change in the future). For example, various `permute` functions could/should be `pre-mfp` where you hand over perhaps a `Vec<MirScalarExpr>` that *could* be column references, or more general expressions. E.g. if we form a key using a cast, we cannot represent the operation that just un-casts it (in some cases) and that would be …
> Rationalize type of `(key, val)` to `row` mapping

- src/catalog/src/builtin.rs
With source versioning, because we use SUBSCRIBE to power our source statistics in the Console, we need 'mz_tables' to be a retained metrics object.
> Allow mz_tables to retain metrics

- src/adapter/src/coord/appends.rs
- src/adapter/src/coord/command_handler.rs
Logging for https://github.com/MaterializeInc/database-issues/issues/8821
as discussed at
https://materializeinc.slack.com/archives/C0761MZ3QD9/p1733845868029119?thread_ts=1733597183.408179&cid=C0761MZ3QD9
so that we'll have more info the next time it happens in CI.
The placement of the log in `appends.rs` is @jkosh44's suggestion on Slack.
> Add some logging to debug timestamp selection for REFRESH MVs

- ci/test/pipeline.template.yml
- misc/python/materialize/feature_benchmark/scenarios/benchmark_main.py
- misc/python/materialize/feature_benchmark/scenarios/scale.py
This reverts commit 1e694aa37551d86e4203adacb47130b7725d4dfd.
Runtime of feature-benchmark seems to have increased too much
> Revert "feature-benchmark: Increase scale of fast scenarios, reduce retries"

- misc/python/materialize/xcompile.py
```
$ bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive --dev run default
$ echo >> src/materialized/src/bin/materialized.rs
$ bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive --dev run default
[...]
Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.35s
```
Before this PR:
```
$ bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive --dev run default
$ echo >> src/materialized/src/bin/materialized.rs
$ bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive --dev run default
[...]
Finished `dev` profile [unoptimized + debuginfo] target(s) in 6m 35s
```
@teskje Can you try if this works for you?
Independently of this, we should also bump the crosstools-ng and the software it pulls it to get parity with …
> Use lld when building with mzcompose on macOS

- src/compute/src/sink/correction.rs
- src/compute/src/sink/materialized_view_v2.rs
- test/0dt/mzcompose.py
This PR makes the MV sink always perform a consolidation of (the relevant parts of) the correction buffer after it has received all updates for the snapshot, both from `desired` and `persist`. We know that these updates will cancel out, so we have an opportunity to shed a large amount of memory by forcing a consolidation at this time. This is especially important in read-only mode when the MV sink does not produce any batches, which is the process that normally forces consolidation to happen.
[Slack thread for context.](https://materializeinc.slack.com/archives/C077SARJZ45/p1733491638706019)
Fixes https://github.com/MaterializeInc/database-issues/issues/8814
There might be more general approaches that force consolidation not only after the snapshot but …
> compute/mv-sink: force consolidation after the snapshot

- src/persist/src/error.rs
- src/persist/src/location.rs
- src/persist/src/s3.rs
- Preserve the error chain when converting between error types
- Preserve the actual error types in our S3 binding (including causes!) instead of string-formatting it away.
This would have made https://github.com/MaterializeInc/materialize/pull/30795 trivial to diagnose.
> [persist] Improve our S3-related error reporting

- test/balancerd/mzcompose.py
- test/limits/mzcompose.py
Seen failing in https://buildkite.com/materialize/nightly/builds/10667#0193b848-0b1d-44ea-9c8f-af671467f357
Follow-up to https://github.com/MaterializeInc/materialize/pull/30799
In our tests we have to pass both the cancellation-resolver-dir and frontegg-resolver-template.
> Fix balancerd tests

- src/persist/src/s3.rs
The S3 `create_multipart_upload` call is a POST request, and it appears [GCP's load balancers require POST requests to have a `Content-Length` header](https://stackoverflow.com/questions/73903875/how-to-allow-empty-post-bodies-avoid-411) which is not being set by our AWS Rust SDK, so calls to GCS's S3 shim fail
> gcs: explicitly set content-length to 0 for create multipart call

- misc/python/materialize/version_ancestor_overrides.py
- test/terraform/mzcompose.py
> Nightly fixes (December 11/12)

- Cargo.lock
- misc/cargo-vet/audits.toml
- test/testdrive/kafka-recreate-topic.td
This PR updates rdkafka to the latest commit available in our fork, to pull in https://github.com/MaterializeInc/librdkafka/pull/1, fixing a possible metadata cache corruption.
Fixes https://github.com/MaterializeInc/database-issues/issues/8823
> Update rdkafka to remove a segfault

- src/catalog/src/expr_cache.rs
- src/persist-types/src/codec_impls.rs
This commit adds a native Bytes codec to persist and uses this codec
in the expression cache. While there's still a fair bit of copying in
the persist codec, persist callers can more easily pass around Bytes
and avoid copying byte vecs.
> persist/adapter: Add Bytes codec

- src/storage-types/src/dyncfgs.rs
- src/storage/src/sink/kafka.rs
In the Kafka `sink_collection` operator we re-use two `Vec`s to buffer messages, but never shrink them. So it's possible for a large update to blow up the size of these `Vec`s and then we're stuck holding the heap allocation for a while.
Possibly fix an issue we've been seeing.
> storage/kafka: Shrink buffers in `sink_collection` operator

- misc/python/materialize/version_ancestor_overrides.py
See https://github.com/MaterializeInc/database-issues/issues/8832
> feature-benchmark: Ignore TPCHQ01 regression

- doc/user/content/self-managed/installation/install-on-local-kind.md
- doc/user/content/self-managed/installation/install-on-local-minikube.md
- doc/user/data/self_managed/materialize_operator_chart_parameter.yml
- also, for now, going back to http://localhost (since we're sharing the docs)
> docs: self-managed update-image-tag to v0.127.0

- src/storage-controller/src/lib.rs
The controller was previously generating synthetic StorageResponses for itself via a channel in order to delay shard finalization. However, shard finalization is no longer performed by the storage controller (looks like it moved to StorageCollections). So this PR removes this mechanism and instead drops the state immediately.
> storage: use StorageResponse only for cluster protocol

- src/balancerd/src/bin/balancerd.rs
- src/catalog-debug/src/main.rs
- src/cloud-resources/src/vpc_endpoint.rs
- src/clusterd/src/lib.rs
- src/environmentd/src/environmentd/main.rs
- src/mz/src/bin/mz/mixin.rs
- src/orchestrator-tracing/src/lib.rs
- src/persist-cli/src/open_loop.rs
- src/s3-datagen/src/main.rs
- src/server-core/src/lib.rs
- src/sqllogictest/src/bin/sqllogictest.rs
- src/storage-types/src/connections.rs
- src/testdrive/src/bin/testdrive.rs
Fixes most uses of deprecated clap configurations.
There is still one left that I don't know how to fix, where we add `MZ_` prefixes to all arg env vars, where we call `O::command().args_override_self(true)`. It is unclear to me what this does, or if it is safe to replace with the recommended `ArgAction::Set`. Some of our parsers use other `ArgAction`s, so that probably isn't safe.
We've been a major version behind for literal years now, and we can't upgrade without fixing these.
> Fix most uses of deprecated clap configurations

- doc/user/content/self-managed/installation/install-on-local-kind.md
- doc/user/content/self-managed/installation/install-on-local-minikube.md
- doc/user/layouts/shortcodes/note.html
We extend the existing port forward to retry on failure.
Fixes https://github.com/MaterializeInc/console/issues/3582
> Fix console port forward step

- misc/python/materialize/checks/all_checks/webhook.py
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/create
- src/sql/src/normalize.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/session/vars.rs
- src/sql/src/session/vars/definitions.rs
- test/testdrive/session.td
- test/testdrive/webhook.td
This PR implements support for the `CREATE TABLE ... FROM WEBHOOK` syntax which is needed for the larger "Source Versioning" project, if the `enable_create_table_from_source` feature flag is enabled. This change is purely adding support for parsing the syntax and nothing about planning or sequencing changes.
One oddity is `CREATE TABLE ... FROM SOURCE` does not support specifying `IN CLUSTER`, the dataflow that writes data into the table gets installed on the same cluster the `SOURCE` is installed on. Webhooks don't get installed on a cluster today so not supporting `CREATE TABLE ... FROM WEBHOOK IN CLUSTER ...` doesn't lose any functionality, but it is the one difference between this new and the existing syntax.
Closes https://github.com/MaterializeInc/database-issues/issues/8494
> sql: add support for CREATE TABLE ... FROM WEBHOOK

- doc/user/content/sql/select/recursive-ctes.md
Update the docs to reflect that fact that recursive CTE's have GA'd.
> recursive CTEs have GA'd

- src/persist-client/src/cli/inspect.rs
- src/persist-client/src/internal/paths.rs
- src/persist-client/src/usage.rs
Since we never write blobs with the writer id prefix anymore, all blobs with that prefix are either present in the state or leaked. Here we simplify some checks and update some tests to use the simpler writer key comparison.
(We're thinking about changing the writer key format yet again; nice to clean up some logic related to the old format before possibly adding another one!)
> [persist] Remove some usage logic that depends on the writer id

- src/sqllogictest/src/bin/sqllogictest.rs
- src/sqllogictest/src/runner.rs
Right now on main `sqllogictest` is broken with an error like:
```
assertion `left == right` failed: Argument `verbosity`'s selected action Count contradicts `value_parser` (ValueParser::other(usize))
left: u8
right: usize
```
Fix issue with sqllogictest
> sqllogictest: switch `verbosity` argument from `usize` to `u8`

- doc/developer/bazel.md
- doc/developer/guide.md
- misc/bazel/README.md
This PR does two things:
1. Moves `misc/bazel/README.md` to `doc/developer/bazel.md` so it's more discoverable.
2. Adds a new section to the Bazel docs on adding a new crate.
Improve Bazel docs
> bazel/docs: Make docs more visibile, add section on adding a new crate

- Cargo.lock
- src/adapter/src/catalog/apply.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
- src/catalog-protos/BUILD.bazel
- src/catalog-protos/Cargo.toml
- src/catalog-protos/src/serialization.rs
- src/compute-client/src/controller.rs
- src/compute-types/src/config.rs
- src/compute-types/src/lib.rs
- src/controller/src/clusters.rs
While working in the `storage-controller` crate I noticed I would have to rebuild the `catalog-protos` crate, because `catalog-protos` depends on `compute-client` for a single type `ComputeReplicaLogging`.
This PR moves the `ComputeReplicaConfig` and `ComputeReplicaLogging` types to `mz_compute_types` crate to reduce the chances of needing to rebuild `catalog-protos`.
Faster builds
> compute: move some types to `mz_compute_types`

- ci/test/pipeline.template.yml
As part of Linting we run `bin/bazel gen`/cargo gazelle to make sure our `BUILD` files are up-to-date. Currently these jobs run on Hetzner which doesn't have access to the Bazel Remote cache and thus has to re-build `cargo-gazelle` every run.
This PR switches Linting jobs to AWS so we can access the Bazel remote cache and pull down the already built binary.
Make the Lints CI job faster
> ci: use `linux-aarch64-small` so Linting uses the Bazel cache

- src/transform/src/demand.rs
- src/transform/src/lib.rs
- test/sqllogictest/advent-of-code/2023/aoc_1210.slt
- test/sqllogictest/transform/demand.slt
This PR should make the occurrences of
```
protobuf decoding found Dummy datum
```
go to 0, thereby solving https://github.com/MaterializeInc/database-issues/issues/8837 and https://github.com/MaterializeInc/database-issues/issues/6471.
The assert in those issues will now give us an actual signal about how much `ProjectionPushdown` covers `Demand`, which will be interesting to know for our efforts to unify these two transforms.
Plus, I think another reason why we originally added that assert is that [we are not 100% sure that the only way a dummy can appear is through an optimization hiccup such as the above, or there are other sneaky ways in which dummies permeated environments](https://github.com/MaterializeInc/database-issues/issues/6471#issuecomment-2369843378). If the Sentry errors …
> Add ProjectionPushdown call after Demand in physical_optimizer

- src/storage-client/src/statistics.rs
- src/storage/src/statistics.rs
- test/cluster/storage/01-create-sources.td
- test/cluster/storage/02-after-environmentd-restart.td
- test/testdrive/source-statistics.td
- test/testdrive/statistics-maintenance.td
Storage dataflows (computing sources and sinks) may be recreated for various reasons (ingestion errors, addition of new source exports, ALTER SINK, ...). When a storage dataflow is recreated, its statistics epoch is increased, as a means of differentiating statistics collected for the old dataflow instance from statistics collected for the new dataflow instance.
Prior to this change, increasing the epoch would reset all collected statistics and cause all in-flight statistics with the old epoch to be ignored. For gauge statistics that report a current point-in-time value this is the correct behavior as values emitted by the old dataflow might be wrong for the new dataflow. However, for counter statistics that keep track of the number of events of a certain type that have occurred so far, …
> storage: retain counter statistics across epochs

- src/orchestrator-kubernetes/Cargo.toml
- src/orchestrator-process/Cargo.toml
- src/orchestrator-tracing/BUILD.bazel
- src/orchestrator-tracing/Cargo.toml
- src/orchestrator/Cargo.toml
- src/ore/BUILD.bazel
- src/ore/Cargo.toml
- src/ore/src/lib.rs
- src/service/Cargo.toml
- src/tracing/Cargo.toml
Many crates do not build without default features enabled, and this breaks downstream importers of these crates.
Still trying to import orchestratord in the cloud repo.
> Fix broken features

- src/orchestratord/src/controller/materialize/environmentd.rs
make the create cluster page work in self-hosted (cc/ @SangJunBak )
> set allowed_cluster_replica_sizes by default in self-hosted

- src/sql-parser/src/ast/defs/query.rs
We attach SQL statements to spans in `coord::handle_execute_inner`, using `stmt.to_ast_string_redacted()`. In the case of a query with 100000 numbers in a `VALUES` clause, we'll log 100000 redacted numbers.
There's no point in recording that many redacted values. When we're doing redaction, we'll only log the first 20 values, leaving a comment indicating how many more there ought to be.
(This could be refined: if there are 21 `VALUES` that are meaningful, non-redacted expressions, we'll drop the last one. We could instead render the first 20 _redacted values_, and drop them after that. Such a policy would require a bit more nuance than this PR.)
https://github.com/MaterializeInc/database-issues/issues/8832#event-15647939462
> [logging] Don't render large VALUES when redacting

- src/expr/src/scalar.rs
- src/transform/src/lib.rs
- src/transform/src/typecheck.rs
Following up on https://github.com/MaterializeInc/materialize/pull/30851, the final `Typecheck` pass (at the end of the physical optimizer) will signal error if any `Dummy` values have persisted.
NB that errors in `Typecheck` do _not_ prevent running the query itself, but will simply mean logging an error.
The test run is green, with no evidence of the error firing in sqllogictest or the testdrive tests. Watching for this error will let us identify the queries that have been having `Dummy` values---or, at least, those queries that are going through the main MIR optimizer.
https://github.com/MaterializeInc/database-issues/issues/8837
https://github.com/MaterializeInc/database-issues/issues/6471
> [optimizer] Signal a typechecking error when Dummy escapes MIR

- src/storage/src/sink/kafka.rs
- test/cluster/mzcompose.py
When a sink dataflow is installed, it can happen that the `resume_upper` is determined to be the empty frontier, e.g. when the sink has previously produced all its output already. In this case we immediately shut down the sink dataflow. Prior to this change, we'd do so without updating the shared sink frontier, so neither the `StorageState` nor the controller would learn about the fact that the sink dataflow has shut down. This is fixed in this PR.
Part of https://github.com/MaterializeInc/database-issues/issues/8842
> storage: fix reporting of empty sink frontiers

- src/storage/src/statistics.rs
- src/storage/src/storage_state.rs
- test/testdrive/github-8810.td
When a source dataflow is restarted, it's necessary to reset its source statistics metadata, to ensure the reported rehydration latency will be correct.
Fixes https://github.com/MaterializeInc/database-issues/issues/8810
> storage: fix rehydration latency on source restarts

- doc/user/content/customer-responsibilities.md
Adds a matrix view of the shared responsibility model and correct a misspelling in the same doc.
A customer suggested that we provide this information in a matrix form.
> add customer responsibility matrix to docs

- src/transform/src/lib.rs
#30806 adds some metrics on transforms, but the work of hashing is non-trivial on very large queries. We can reduce hashing by half: store the previous hash in `TransformCtx`. (Using `TransformCtx` is @ggevay's idea; I was going to do something much more invasive.)
This shows a ~3s speedup on the `InsertMultiRow` benchmark on my machine (8s -> 5s).
https://github.com/MaterializeInc/database-issues/issues/8832
> [optimizer] cache the previous hash in `TransformCtx`

- test/testdrive/github-8810.td
`github-8810.td` currently breaks the Nightly job "🏎️ testdrive 4 replicas" because it doesn't consider that the default cluster could have more than one replica. That is fixed here.
* This PR fixes a nightly test.
> test: make github-8810.td work with `--replicas 4`

- src/persist-client/src/batch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/write.rs
- src/persist-client/tests/machine/compaction_bounded
- src/persist/src/indexed/encoding.rs
- Set some structured-data configs by default.
- Encode to both codec and structured data when building user batches.
This is a nice milestone: it's the last codepath that could only handle codec data; now both are always handled in parallel. However, we don't allow disabling codec-data writes yet!
Part of: https://github.com/MaterializeInc/database-issues/issues/7411
Lots of code movement... might be easiest to follow commit-by-commit.
> [persist] Prioritize structured data in the batch builder

- src/transform/src/reduction_pushdown.rs
Part of MirRelationExpr::typ() cleanup.
Skip a call to `typ()` that is only for arity.
Motivation
https://github.com/MaterializeInc/database-issues/issues/2488
https://github.com/MaterializeInc/database-issues/issues/3779
https://github.com/MaterializeInc/database-issues/issues/4959
> [optimize] MRE::typ(): remove call in ReductionPushdown

- src/orchestratord/src/controller/materialize/environmentd.rs
Make orchestratord environmentd resources public, so that they may be accessed by the environment-controller for comparison before the migration to orchestratord.
We want to have environment-controller compare the resources it is creating with the resources orchestratord would generate, so we can make them the same before cutting over to orchestratord.
> Make orchestratord environmentd resources public

- doc/user/layouts/partials/explain-plans/operator-table.html
There are extra 'the's that don't parse for me.
**typo fix**
> [docs] typo fix

- doc/user/content/concepts/indexes.md
- doc/user/content/transform-data/faq.md
- doc/user/content/transform-data/optimization.md
- doc/user/data/index_usage_key_quantity.yml
- doc/user/data/index_usage_key_quantity_price.yml
- doc/user/layouts/partials/index-usages-tables/table-index-usage-queries.html
- doc/user/layouts/shortcodes/index_usage/index-ordering.html
- doc/user/layouts/shortcodes/index_usage/index-usage-table.html
For the new year.
Updates from the indexes 101 meeting.
- To the Indexes concepts page, fashioned the findings into how indexes are used (scanned/point lookups) in Materialize
- To the Optimization page, fashioned the findings into how to create indexes to support point lookups.
- Added an initial FAQ page (because sooner or later, we'll need them).
The other tweaks from that meeting's findings: https://github.com/MaterializeInc/materialize/pull/30404/
> docs: indexes -- point lookup vs scans

- src/adapter/src/coord/sequencer/inner.rs
If the named connection already exists when running a CREATE CONNECTION IF NOT EXISTS command, emit a notice indicating the existing connection.
This brings CREATE CONNECTION IF NOT EXISTS into alignment with the behavior of all other CREATE ... IF NOT EXISTS commands, which all emit notices. Somehow connections were overlooked.
> adapter: emit existence notice in CREATE CONNECTION IF NOT EXISTS

- deny.toml
- src/sql/src/func.rs
Showd up since it's closed: https://buildkite.com/materialize/nightly/builds/10732#01940587-8d35-4d45-a5a1-d8aa0c0f0554
https://github.com/MaterializeInc/materialize/pull/7572
> comments: Change wording on references to PR 7572

- src/postgres-util/src/schemas.rs
When fetching schema info from PostgreSQL, the PostgreSQL source currently issues a query that's known to be compatible only with recent versions of PostgreSQL.  If the query fails, the source retries with a version of the query that's compatible with older versions of PostgreSQL.
While this works fine for customers running versions of PostgreSQL before v15, it has an annoying side effect: those customers can observe the failed queries in their PostgreSQL log files. This has led to confusion and complaints from at least two customers.
This commit changes the PostgreSQL source to do eager server version sniffing and issue a query that's known to be compatible with the announced server version. This should avoid leaving failing queries in the upstream PostgreSQL server's logs, and hopefully …
> storage/sources/postgres: avoid metadata queries that are expected to fail

- test/cluster/storage/01-create-sources.td
Flaky, see https://github.com/MaterializeInc/database-issues/issues/8848
> cluster tests: Disable another part of source stats tests

- misc/python/materialize/output_consistency/ignore_filter/expression_matchers.py
- misc/python/materialize/parallel_benchmark/scenarios.py
- misc/python/materialize/version_consistency/ignore_filter/version_consistency_ignore_filter.py
- src/testdrive/src/action.rs
This is fallout introduced by 34e78364. Three changes:
* Teaching the output consistency checks to ignore changes to the private preview message wording when `timezone` or `AT TIME ZONE` is called.
* Ignoring failures in testdrive when unsafe functions can't be enabled because the server is running in safe mode.
* Adjusting the parallel benchmark to use a non-renamed feature flag for the benchmark that tests the performance impact of toggling a feature flag. (I could have alternatively added conditional logic to choose the right name for the version, but just using a different flag seemed easier.)
> Fix nightlies after private preview message rewording

- test/cloud-canary/mzcompose.py
- test/mz-e2e/mzcompose.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/30867
Seen failing in https://buildkite.com/materialize/nightly/builds/10732
Test run: https://buildkite.com/materialize/nightly/builds/10740
> e2e tests: Adapt to new mz region deletion api

- src/compute/src/sink/copy_to_s3_oneshot.rs
- src/storage-types/src/sinks/s3_oneshot_sink.rs
This commit addresses feedback from @teskje's post-merge review of
https://github.com/MaterializeInc/materialize/pull/30844.
> storage: address review feedback on copy to s3 sink

- ci/builder/requirements.txt
Reverts https://github.com/MaterializeInc/materialize/pull/30911
Also upgrades pdoc, but unfortunately newest version of pdoc still fails
Seen failing in https://buildkite.com/materialize/deploy/builds/17206#019414f3-9a6e-4a27-b030-76d435115a0d
> build(deps): Downgrade pydantic again

- src/ore/src/cli.rs
- src/testdrive/src/bin/testdrive.rs
Remove deprecated clap `args_override_self`.
This is the last remaining instance of deprecated clap calls.
The most likely issues with this will be from us supplying the same argument multiple times, but not using a collection type (ie: Vec). Previously the last supplied value would have "won", but now that results in an error.
I have added special handling in places where we were passing the same argument multiple times in testdrive, but I think these should probably be considered bugs in the tests. CC @def-
> Remove deprecated clap args_override_self

- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose/composition.py
- test/mysql-cdc-old-syntax/mzcompose.py
- test/mysql-cdc/mzcompose.py
- test/pg-cdc-old-syntax/mzcompose.py
- test/pg-cdc/mzcompose.py
- test/postgres/Dockerfile
Noticed by Nikhil in https://materializeinc.slack.com/archives/C01LKF361MZ/p1735098133262889
This never worked before based on what I can tell.
Also update all versions we test against while at it.
Postgres 11/12 don't work with non-localhost auth, so removed for now. MySQL 5.7 requires way more memory, so bumped it.
> pg-cdc+mysql-cdc tests: Fix old version passing

- test/mysql-cdc-old-syntax/mzcompose.py
- test/mysql-cdc/mzcompose.py
- test/pg-cdc-old-syntax/mzcompose.py
- test/pg-cdc/mzcompose.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/30903
> cdc tests: Remove out of date comments

- test/testdrive-old-kafka-src-syntax/statistics-deletion.td
- test/testdrive/statistics-deletion.td
See https://github.com/MaterializeInc/database-issues/issues/8848
Noticed in https://buildkite.com/materialize/nightly/builds/10749#01941a20-f3a3-44af-9cb3-1eb9555d4dc2
> testdrive: Remove another source stats flaky test

- misc/python/materialize/cli/ci_annotate_errors.py
- misc/python/materialize/mzcompose/services/clusterd.py
- misc/python/materialize/mzcompose/services/materialized.py
- test/data-ingest/mzcompose.py
- test/upsert/mzcompose.py
Follow-up for https://github.com/MaterializeInc/materialize/pull/30895
Alternative to https://github.com/MaterializeInc/materialize/pull/30923
Noticed in https://buildkite.com/materialize/nightly/builds/10749
Test run: https://buildkite.com/materialize/nightly/builds/10752
> tests: Fix duplicate argument passing

- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose/composition.py
- test/kafka-rtr/mzcompose.py
- test/source-sink-errors/mzcompose.py
See discussion in https://github.com/MaterializeInc/materialize/pull/30895
We still can't remove the duplicate argument handling because testdrive's usage is a bit convoluted. We create containers with a set of defaults, and then sometimes have to invoke it with different parameters through run_testdrive_files etc.
> testdrive: Some fixes for duplicate args

- src/aws-secrets-controller/Cargo.toml
- src/cloud-resources/Cargo.toml
- src/lowertest/Cargo.toml
- src/orchestrator-kubernetes/Cargo.toml
- src/orchestrator-process/Cargo.toml
- src/orchestrator-tracing/Cargo.toml
- src/persist-types/Cargo.toml
- src/pgtz/Cargo.toml
- src/repr/Cargo.toml
- src/secrets/Cargo.toml
- src/service/Cargo.toml
- src/sql-parser/Cargo.toml
- src/tracing/Cargo.toml
Disable many default features, so we don't pull in workspace-hack in the cloud repo when importing orchestratord.
Don't pull in unneeded dependencies, especially workspace-hack, when importing orchestratord in the cloud repo.
> Disable many default features

- src/environmentd/src/environmentd/main.rs
we provide defaults for these in the environmentd dockerfile entrypoint
another followup to https://github.com/MaterializeInc/materialize/pull/30895
not sure if there's a better fix for this?
> allow specifying listen args more than once

- test/testdrive-old-kafka-src-syntax/statistics-maintenance.td
See https://github.com/MaterializeInc/database-issues/issues/8848
Noticed in https://buildkite.com/materialize/nightly/builds/10760#0194246d-b7de-4481-a6bb-aab5f27f40c4
> testdrive: Remove further source stats flakiness

- test/sqllogictest/temporal.slt
Replace usages of `mz_now` with a hard-coded timestamp to remove flakiness
> test: Fix temporal test

- bin/ci-builder
Follow-up to https://github.com/MaterializeInc/materialize/pull/30872 (where this same nightly version was set for Bazel only)
Noticed in https://buildkite.com/materialize/deploy/builds/17226#019427a7-9f03-4ce4-bac9-16c6ab9a3bff
> ci-builder: Bump nightly rust version to be 1.83.0 compatible

- src/adapter/src/coord/timeline.rs
- src/catalog/src/durable/transaction.rs
- src/expr/src/explain/text.rs
- src/pgwire-common/src/codec.rs
- src/repr/src/explain.rs
- src/sql-pretty/src/util.rs
- src/sql/src/catalog.rs
- src/sql/src/names.rs
- src/sql/src/pure/references.rs
- src/storage-types/src/stats.rs
- src/walkabout/src/ir.rs
After the upgrade to the new Rust version, a lot of warnings of the
form "warning: elided lifetime has a name" were appearing. This commit
resolves those warnings by adding explicit lifetime names.
> lint: Fix lint from new Rust version

- src/metrics/src/rusage.rs
On macOS, the ru_maxrss value is for some reason in bytes, not in KiB.
On macOS, the value of the `mz_metrics_libc_ru_maxrss_bytes` metric is off by a factor of 1024.
> metrics: fix the maxrss metrics on macOS

- misc/python/materialize/version_ancestor_overrides.py
- src/persist-client/src/internal/merge.rs
- test/testdrive/statistics-maintenance.td
Seen in https://buildkite.com/materialize/nightly/builds/10769
> ci: Nightly fixes (January 3)

- doc/developer/upgrade-rust.md
Update the instructions to include running Nightly
> docs: upgrade Rust instructions

- src/expr/src/relation.rs
That's the whole point of `keys_with_input_keys` that we already have the input key available, so we don't need to call `.typ()` to get the key of an input. So, this PR substitutes the `typ` call with `input_keys.next().unwrap()` (which is a pattern that already occurs several times in `keys_with_input_keys`).
* This PR refactors existing code, similar to https://github.com/MaterializeInc/materialize/pull/30876 and https://github.com/MaterializeInc/materialize/pull/30871
> Eliminate unnecessary `.typ()` call from `keys_with_input_keys`

- src/compute-types/src/plan/lowering.rs
More `typ()` call elimination, similar to https://github.com/MaterializeInc/materialize/pull/30878
Also eliminates an `arity` call, since the arity can be seen from the type.
> Eliminate some typ() calls and an arity() call from MIR lowering

- src/expr/src/explain.rs
- src/expr/src/relation.rs
- src/transform/src/canonicalization/flatmap_to_map.rs
- src/transform/src/canonicalization/topk_elision.rs
- src/transform/src/equivalence_propagation.rs
- src/transform/src/fold_constants.rs
- src/transform/src/fusion/top_k.rs
- src/transform/src/non_null_requirements.rs
- src/transform/src/predicate_pushdown.rs
More `typ()` call elimination, similar to e.g. https://github.com/MaterializeInc/materialize/pull/30878
This one goes after various `take_safely` calls, where we know the type already, so no need to call `.typ()`.
Also, this makes `take_safely()` give a better key and nullability to the constant, making use of the fact that we have an empty collection, so we have the keys `[[]]` and nothing is nullable.
* This PR fixes a previously unreported bug: `take_safely` was often not giving the best possible key to the constant. Ideally, the keys that are recorded on a `MRE::Constant` should be the same as if we were to call `keys_with_input_keys` on it, so that we don't have anomalies such as `create_fast_path_plan` needing to `// For best accuracy, we need to recalculate typ.`. This PR moves one …
> Sometimes we can give the type to MRE::take_safely

- src/persist-client/src/batch.rs
Calling `mark_consumed` drops all the parts in the batch, so the rest of this method's logic didn't do anything.
Bug! First reported [in Slack](https://materializeinc.slack.com/archives/C06V70RE7SN/p1727361839440419).
The slack thread also suggests that `compare_and_append_batch` should take ownership of the data. I've taken a look at this, but it's going to be a more substantial change... still seems worth doing, but better as a followup.
This also includes a simple regression test.
> [persist] Don't discard parts that should be deleted

- test/cluster/storage/01-create-sources.td
- test/cluster/storage/02-after-environmentd-restart.td
- test/cluster/storage/03-while-clusterd-down.td
- test/cluster/storage/04-after-clusterd-restart.td
- test/testdrive-old-kafka-src-syntax/statistics-deletion.td
- test/testdrive-old-kafka-src-syntax/statistics-maintenance.td
- test/testdrive/statistics-deletion.td
- test/testdrive/statistics-maintenance.td
This PR restores and fixes storage statistics tests that use the new `CREATE TABLE ... FROM SOURCE` syntax. This syntax recreates the source dataflow, which can lead to the loss of `updates_committed` counts. Tests checking for `updates_committed > 0` need to insert new updates after the dataflow was recreated, to avoid flakes.
Fixes https://github.com/MaterializeInc/database-issues/issues/8848
> test: unflake source statistics tests

- ci/nightly/pipeline.template.yml
In the last few months it only had false positives and known issues, my attempts to fix them were successful, but more and more keep popping up. Recent one: https://materializeinc.slack.com/archives/C01LKF361MZ/p1736269975845669
> ci: Turn off output consistency for now

- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/transact.rs
- src/catalog/src/durable/transaction.rs
Previously, only a subset of the catalog object migrations would delete system catalog objects from the durable catalog after they've been removed from `builtin.rs`. The rest of the catalog object migrations would leak the objects in the durable catalog and never use them. This commit updates all catalog object migrations so that system catalog objects are removed from the durable catalog once they've been removed from `builtin.rs`.
> catalog: Clean up old objects in migrations

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/compute-types/src/dyncfgs.rs
- src/compute/src/render.rs
- src/compute/src/sink/materialized_view.rs
- src/compute/src/sink/materialized_view_v2.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/metrics.rs
- src/persist-client/src/schema.rs
- src/persist-types/src/codec_impls.rs
- src/persist-types/src/columnar.rs
- src/persist-types/src/schema.rs
- src/repr/src/lib.rs
- src/repr/src/relation.rs
- src/repr/src/row.rs
- src/repr/src/row/encode.rs
- src/storage-operators/src/persist_source.rs
- src/storage-types/src/dyncfgs.rs
- src/storage-types/src/sources.rs
- src/storage-types/src/stats.rs
- src/storage/src/render/sinks.rs
- src/storage/src/render/sources.rs
Continuation of https://github.com/MaterializeInc/materialize/pull/29539
Implements a limited form of projection pushdown by applying the `demands` of a `MapFilterProject` onto the `RelationDesc` of a collection, and using the resulting `RelationDesc` in `shard_source`. All of the columns will still be fetched from S3, but when decoding structured data we'll drop the unneeded columns, and decoding `ProtoRow` data we'll skip the unneeded `Datum`s.
Progress towards: https://github.com/MaterializeInc/database-issues/issues/8402
Fixes https://github.com/MaterializeInc/database-issues/issues/8825
The implementation for the feature is in the first commit, and can be reviewed on its own. The later commits add testing and metrics and theoretically could be their own PRs, so it might be nice to …
> persist/storage: communicate projection pushdown via `shard_source`

- src/adapter/src/catalog.rs
- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/sequencer/inner/cluster.rs
- test/cluster/resources/resource-limits.td
we already only look at user clusters when determining the current consumption rate, so this just makes the logic consistent when looking at newly created clusters
> only consider user clusters when validating max_credit_consumption_rate

- ci/mkpipeline.py
- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
Kept sporadically forgetting it
> ci: Automatically append %N in parallel tests

- Cargo.lock
- src/adapter/tests/timestamp_selection.rs
- src/compute-client/Cargo.toml
- src/compute-client/src/as_of_selection.rs
- src/compute-client/src/controller.rs
- src/compute-client/src/controller/instance.rs
- src/environmentd/tests/server.rs
- src/storage-client/src/storage_collections.rs
- src/storage-types/src/read_holds.rs
Changes to `ReadHold`s on compute collections are now sequenced through the `command_{tx,rx}` channels of the respective `Instance` controllers. This ensures that `Instance`s observe read hold changes always after they have observed the creation of the affected collection, which wasn't the case previously.
The implementation includes a change to the `ReadHold` type, which now contains a sender closure, rather than a channel sender directly. The closure enables the construction of `ReadHold`s that communicate changes on a channel with an item type different from `(GlobalId, ChangeBatch)`.
Fixes https://github.com/MaterializeInc/database-issues/issues/8679
This PR required touching a lot more parts than I initially expected, so it ended up quite busy. I …
> controller/compute: sequence external read hold changes

- src/storage/src/source/kafka.rs
- test/testdrive-old-kafka-src-syntax/kafka-recreate-topic.td
- test/testdrive/kafka-recreate-topic.td
This PR moves detection of topic recreation from the reader operator into the metadata fetcher. This is done to make the metadata fetcher aware of the unrecoverable error so it can seal the collection by emitting a probe with an empty upstream frontier. Prior to this change, the collection wouldn't be sealed under the reclock-to-latest scheme, and a replica restart could cause it to receive new, incorrect updates.
Apart from fixing the sealing bug, this commit makes two functional changes:
* It adds detection of topic deletion. That was easy to add and not having it seemed like an oversight.
* It omits the "high watermark regressed"/"partition count regressed" detail in the "topic recreated" error. It didn't feel like a useful piece of information and omitting it simplifies the code a …
> kafka-source: detect topic deletion in metadata fetcher

- src/storage/src/upsert/types.rs
Before, we were using the wrong assumption that the new feedback UPSERT operator could not yield finalized tombstone values, because it only writes finalized values that "exist". But it can happen that `ensure_decoded` puts in place a finalized tombstone when state values consolidate to a diff of zero.
We say "can happen" above, because `merge_update` returns whether or not a merged value can be deleted, and this returns true when the diff_sum is zero. So in most cases the finalized tombstone would be cleaned up right away. However, not all callers immediately (or at all) act on this "can delete" information, which leads to finalized tombstones actually existing in state.
Fixes https://github.com/MaterializeInc/database-issues/issues/8864
> storage: in upsert StateValue allow converting finalized tombstones

- .bazelrc
Chatted about this in [Slack](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1736243826039879), as-is we only see non-inlined functions which makes it hard to follow timely operators. This PR bumps our debuginfo from line-tables to limited, let's see if it helps.
Better debug info
> build: Use "limited" debug info instead of "line-tables"

- misc/python/materialize/bazel.py
- misc/python/materialize/cli/bazel.py
- misc/python/materialize/cli/run.py
This PR refactors the `run.py` script to use Bazel remote caching. FWIW `run.py` was the first thing adapted to use Bazel, so this is catching it up to other advances we've made more recently.
It also changes the `bin/environmentd --release` flag to use the Bazel "optimized" config which is better for local development.
Improve developer experience
> bazel: Refactor `run.py` so `bin/environmentd` uses Bazel remote caching

- test/testdrive/source-statistics.td
- test/testdrive/statistics-deletion.td
- test/testdrive/statistics-maintenance.td
Fixes source statistics test flakes observed https://buildkite.com/materialize/nightly/builds/10798.
In particular, when we ingest extra updates to work around `CREATE TABLE ... FROM SOURCE` recreating the dataflow and dropping statistics on the floor while doing so, that ingest races with the dataflow recreation and it's possible that the old dataflow is alive long enough to commit the data, which is the opposite of what we want. To fix this, we can select from the created table once, making sure that the table dataflow exists.
Fixes more source statistics test flakes.
> test: unflake source statistics tests more

- ci/nightly/pipeline.template.yml
- misc/python/materialize/mzcompose/services/materialized.py
- test/emulator/mzcompose
- test/emulator/mzcompose.py
Regression test for https://github.com/MaterializeInc/materialize/pull/30964
This is only to make sure we don't shoot ourselves into the foot by setting non-functional defaults.
Green test run: https://buildkite.com/materialize/nightly/builds/10806
This has the side effect that every nightly run will upload telemetry now. Disabling telemetry is not an option, because it was exactly the telemetry default that was breaking the emulator.
> tests: Add simplest possible emulator test

- misc/helm-charts/operator/templates/deployment.yaml
- misc/images/materialized-base/Dockerfile
Bumps console image to one that doesn't run as root, and enables security contexts.
Better security for our users, and is one of the differences between SaaS and self-hosted.
> bump console image and enable security contexts

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
Allow specifying the secrets controller in the orchestratord helm chart.
Part of the migration to orchestratord in SaaS. We use aws-secrets-manager there.
> orchestratord helm chart set secrets controller

- src/storage-types/src/dyncfgs.rs
- src/storage/src/source/postgres/replication.rs
- test/pg-cdc-old-syntax/alter-source.td
- test/pg-cdc-old-syntax/alter-table-after-source.td
- test/pg-cdc/alter-source.td
- test/pg-cdc/alter-table-after-source.td
The PostgreSQL logical replication protocol only notifies us that a table has changed schema if that table participates in a transaction *after* the schema change has occured.
This is problematic because until that table participates in a transaction Materialize will keep advancing the upper frontier of the table, asserting that everything is fine and potentially revealing invalid data.
This PR puts an upper bound on this window of invalidity by proactively re-validating the schema of all tables in an ingestion in a cadence. The interval is set to 15s by default but configurable through LD.
> source/pg: proactively validate schemas

- doc/user/content/self-managed/_index.md
- doc/user/content/self-managed/installation/_index.md
- doc/user/content/self-managed/installation/install-on-aws.md
- doc/user/content/self-managed/installation/install-on-gcp.md
- doc/user/content/self-managed/installation/install-on-local-kind.md
- doc/user/content/self-managed/installation/install-on-local-minikube.md
- doc/user/layouts/shortcodes/important.html
- doc/user/layouts/shortcodes/self-managed/requirements-list.html
- doc/user/layouts/shortcodes/self-managed/terraform-disclaimer.html
- doc/user/layouts/shortcodes/tip.html
https://preview.materialize.com/materialize/30846/self-managed/installation/install-on-aws/  
- running from module at root.  The examples/simple requires couple of more changes (updates to the versions file, some node ami and instance types - to use the ARM one, etc). 
https://preview.materialize.com/materialize/30846/self-managed/installation/install-on-gcp/ 
- running from examples/simple, but assumes some changes in the examples/simple module.  To test (need to change machine_type), locally added the following config to the main.tf materialize module block:
```none
gke_config = {
node_count     = 1
machine_type   = "e2-standard-4"
disk_size_gb   = 50
min_nodes      = 1
max_nodes      = 2
node_locations = []
}
```
Future updates:
- Per …
> docs: update aws and gcp self-managed page with terraform instructions

- src/transform/src/semijoin_idempotence.rs
Ensures we only call `MRE::typ()` twice, rather than six times, in `attempt_join_simplification`. Changes the interface of `distinct_on_keys_of` to just take a `RelationType`, which should offer some additional savings.
> [optimizer] Reduce MRE::typ() calls in SemijoinIdempotence

- doc/user/content/sql/system-catalog/mz_internal.md
Noticed while looking things up: a few typos and some word duplication.
> [docs] typo fixes, wordsmith

- src/orchestratord/src/controller/materialize/environmentd.rs
Add additional prometheus scrape annotations for secondary metrics paths on envronmentd.
```
materialize.prometheus.io/mz_usage_path
materialize.prometheus.io/mz_frontier_path
materialize.prometheus.io/mz_compute_path
materialize.prometheus.io/mz_storage_path
```
Resolves https://github.com/MaterializeInc/cloud/issues/10608
> Add additional prometheus scrape annotations for envronmentd.

- doc/user/content/transform-data/troubleshooting.md
- doc/user/data/query_attribution_computation_time_output.yml
- doc/user/data/query_attribution_memory_usage_output.yml
- doc/user/data/query_attribution_memory_usage_w_hint_output.yml
- doc/user/data/query_attribution_topk_hints_output.yml
- doc/user/data/query_attribution_worker_skew_output.yml
- doc/user/layouts/partials/yaml-tables/generic-table.html
- doc/user/layouts/shortcodes/yaml-table.html
Documents the LIR mapping introspection source (https://github.com/MaterializeInc/materialize/pull/29848).
Preview at [https://preview.materialize.com/materialize/30899/transform-data/troubleshooting/](https://preview.materialize.com/materialize/30899/transform-data/troubleshooting/).
https://github.com/MaterializeInc/database-issues/issues/6551
> [docs] document LIR attribution

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
- test/legacy-upgrade/mzcompose.py
Causing PRs to be blocked from merging for a second time. We will ignore this specific failure in Test pipeline now, but still report it in Nightly so that we don't miss it.
(This is not a very elegant solution but should unblock us quickly enough.)
Context: https://materializeinc.slack.com/archives/CMH6PG4CW/p1736491884771329?thread_ts=1736427104.795249&cid=CMH6PG4CW
Noticed in https://buildkite.com/materialize/test/builds/96952
> legacy upgrade test: Ignore missing version in Test pipeline

- src/compute/src/sink/correction.rs
- src/compute/src/sink/materialized_view_v2.rs
- test/sqllogictest/github-8867.slt
This PR fixes a bug in the MV sink v2 where the `write` operator would discard valid batch descriptions as outdated, based on an incorrect view of the persist frontier. The fix is to simply remove this particular validity check, which also requires adapting some surrounding code.
Fixes https://github.com/MaterializeInc/database-issues/issues/8867
Fixes https://github.com/MaterializeInc/database-issues/issues/8821
The `mint` operator gets the correct persist shard write frontier by instantiating a separate write handle and polling that. Thus, an alternative fix would have been to also give the `write` operator such a handle, or share the frontier stream between the two operators. But then the `write` operator would need to start reasoning about two …
> mv-sink: stop discarding valid batch descriptions

- src/compute-types/src/plan/lowering.rs
- src/expr/src/explain.rs
- src/expr/src/linear.rs
- src/expr/src/relation.rs
- src/sql/src/plan/lowering.rs
- src/transform/src/canonicalization/flatmap_to_map.rs
- src/transform/src/canonicalization/topk_elision.rs
- src/transform/src/demand.rs
- src/transform/src/equivalence_propagation.rs
- src/transform/src/fold_constants.rs
- src/transform/src/fusion/top_k.rs
- src/transform/src/literal_constraints.rs
- src/transform/src/non_null_requirements.rs
- src/transform/src/predicate_pushdown.rs
This is on top of https://github.com/MaterializeInc/materialize/pull/30881, because it relies on the new variations of `take_safely`.
Nightly (subset): https://buildkite.com/materialize/nightly/builds/10717
> Eliminate more `typ` and `arity` calls

- src/sql/src/session/vars/value.rs
@frankmcsherry I was reminded of this while we were chatting about box clone.
Fix TODO
> adapter/docs: Add TODO doc for the `AsAny` trait

- src/storage/src/upsert.rs
- src/storage/src/upsert_continual_feedback.rs
Before, while working off the "upsert commands" (aka. input) we were
taking the existing value out of `command_state` when processing and we
were only putting in a new value when processing commands with
`DrainStyle::AtTime`. This is problematic when processing commands of
multiple timestamps in one invocation of `drain_staged_input`:
processing the first update for a key `k` at timestamp `t` takes away
any value that we might have retrieved from state, then when processing
another update for key `k` at timestamp `t+1`, we think there is no
previous value and don't emit a retraction. Meaning we suddely have
multiple values for the same key in our collection, which is not legal.
Now, we just don't take away the state value without putting something
back.
The astute reader might now wonder …
> storage: in feedback upsert, fix handling of existing state values

- misc/scratch/ci-x86_64-large.json
Was useful for debugging a build failure, I figured it would be good to have
> scratch: Add profile for x86_64 CI runner

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
- test/legacy-upgrade/mzcompose.py
This reverts commit 9b0c0bbda45591a6b62cd90f7ebb11975aabcc8a, reversing changes made to 769f82228ad6f3f6b9eef1c465b08a2f4ce9ce13.
x86_64 builds should be working again, let's restore the Legacy Upgrade Tests to how they used to be.
Revert temporary patch because of build failures.
> Revert "Merge pull request #30994 from def-/pr-legacy-upgrade-unblock"

- WORKSPACE
- misc/bazel/c_deps/rust-sys/BUILD.libz.bazel
Previously we were linking the zlib built by Bazel, which might not be the same version specified by the `libz-sys` crate. Now we build the version of `zlib` included by the `libz-sys` crate.
Make our build easier to reason about.
> bazel: make sure to build zlib from `libz-sys` crate source

- ci/nightly/pipeline.template.yml
- test/0dt/mzcompose.py
Compared to parallel-workload
Can be used as a regression test once https://github.com/MaterializeInc/database-issues/issues/8798 is fixed
Since https://github.com/MaterializeInc/materialize/pull/30811 is not reliable enough
CI run: https://buildkite.com/materialize/nightly/builds/10772
> Reproduce 0dt upsert source panic in more deterministic workflow

- WORKSPACE
- misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel
- misc/bazel/toolchains/BUILD.bazel
- misc/bazel/toolchains/rust.bzl
- misc/images/bazel/Dockerfile
This PR makes our Bazel build fully hermetic, mainly by refactoring how we built the `librocksdb-sys` crate. Previously we had to rely on some hacks because `librocksdb-sys` uses bindgen which was tricky to get working.
Specifically the changes this PR makes are:
* upgrades to [`clang 18.1.8-5`](https://github.com/MaterializeInc/toolchains/releases/tag/clang-18.1.8-5)
* upgrades to newer version of `toolchains_llvm` that includes an [upstream fix](https://github.com/bazel-contrib/toolchains_llvm/pull/438)
* adds `rust_bindgen` toolchains with new `libclang` package from our toolchains repo
* refactors the rocksdb build to be hermetic
Improves the quality of our build, allows us to move to a "minimum" CI builder image for faster build times
> bazel: make build fully hermetic

- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/helm-charts/operator/values.yaml
Add support to the helm chart for alternative kubernetes schedulers.
Part of the migration to using orchestratord in SaaS. We use a custom scheduler there.
> orchestratord support alternative schedulers

- test/pg-cdc-old-syntax/alter-source.td
Follow-up to https://github.com/MaterializeInc/materialize/pull/30807
Seen in https://buildkite.com/materialize/nightly/builds/10822#01944f9a-9738-4aa8-a012-bc111a2660ae
@petrosagg Is this expected? Feels like it could also be a bug since we can now still ingest a value after having dropped the column.
> pg-cdc old syntax: Fix test failure

- bin/ci-builder
- ci/builder/Dockerfile
- ci/mkpipeline.sh
- ci/nightly/pipeline.template.yml
- ci/release-qualification/pipeline.template.yml
- ci/test/pipeline.template.yml
Adds a "min" flavor of the CI builder image which is ~1/10th the size of the full image. Because our Bazel build is fully hermetic, it already pulls in the necessary toolchains and thus the image we use can be quite small. The "min" image can be fetched in ~30 seconds, whereas the full image takes ~2 minutes and 30 seconds. This should save about 4 minutes end-to-end in CI because both the initial mkpipeline step and the Build steps will each save 2 minutes.
Similarly most CI jobs just run other Docker images built by the initial step, so they also can use this "min" image, which should save another 2 minutes.
Reduce CI time by ~4 minutes
> build: Introduce "min" version of CI builder

- .bazelrc
Sets `--nobuild_runfile_links` for our build which skips building the symlink forest for Bazel's "runfiles", unless it's required.
This is a small change but it reduces the amount of I/O Bazel needs to do. I've been dogfooding it locally for months and haven't run into any issues so it should be good to go. The reason this isn't the default in Bazel is because some legacy rules rely on the old behavior.
Less I/O in the Bazel build
> bazel: skip building symlink forest for runfiles, i.e. set  `--nobuild_runfile_links`

- misc/python/materialize/mzbuild.py
Just removes the word "cargo" from a log when the build can be Cargo or Bazel.
Something that's bugged me for a little while and I keep forgetting to fix it
> build: Tiny change to log

- misc/python/materialize/mzbuild.py
Proof that this works:
```python
import subprocess
push = subprocess.Popen("ls asd | cat", shell=True)
print(push.wait()) # 0
push = subprocess.Popen("ls asd", shell=True)
print(push.wait()) # 2
push = subprocess.Popen(["/bin/bash", "-c", "set -o pipefail; ls asd | cat"])
print(push.wait()) # 2
```
Context: https://materializeinc.slack.com/archives/CM7ATT65S/p1736789270342329
Crazy that we never noticed this before! Dockerhub must be pretty reliable. I could not find another usage of us using this pattern in our code.
I'll remove the last commit before submitting.
> mzbuild: Don't ignore return code of `docker push`

- src/persist-client/src/internal/gc.rs
- src/persist-client/src/internal/machine.rs
A quick Friday triage pass at some old bugs. (One was purely an assertion issue; the other I'm not sure about, but we might as well strengthen our assertions for.)
Fixes: https://github.com/MaterializeInc/database-issues/issues/8675
Adds logging for: https://github.com/MaterializeInc/database-issues/issues/7888
> [persist] Follow up on some outstanding bugs

- misc/python/materialize/mzcompose/__init__.py
- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cfg.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/iter.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/read.rs
- src/persist-client/src/stats.rs
- src/persist-client/tests/machine/batch
- src/persist-proc/src/lib.rs
- src/persist-types/src/columnar.rs
- src/persist-types/src/part.rs
- src/persist/src/indexed/columnar.rs
- src/persist/src/indexed/columnar/arrow.rs
- src/persist/src/indexed/columnar/parquet.rs
- src/persist/src/indexed/encoding.rs
- test/sqllogictest/persist-fast-path.slt
What it says on the tin.
Notably: this does _not_ allow writing structured-only data to disk: we will always generate the codec-encoded columns before writing the part. I've left a couple `expect`ations in the code that would panic if this was ever not true: to be cleaned up in the next PR.
Part of the work that we need to do to allow writing _only_ structured data.
This is a somewhat ugly interstitial state. I'm trying to resist doing too much cleanup of code that we don't expect to live for too long... but however if you think anything's too sketchy to live in main for even a short time I can try and tackle that up front!
> [persist] Add a structured-only update set type, and use it in the builder

- test/limits/mzcompose.py
Took > 12 hours in https://buildkite.com/materialize/release-qualification/builds/716#01945f4e-9045-460c-b2fe-44caa0839e0f
> limits test: Limit Release Qualification run for KafkaPartitions generator

- test/terraform/aws/main.tf
- test/terraform/aws/simple.tf
Things are fixed and we want to test against the latest state to find regressions as quickly as possible
> terraform aws test: Don't use old reference

- src/storage/src/render.rs
Halting health status updates are only expected to be produced for the root source, not subsources/exports, and there is an assert that checks that.
In a [Nightly CI run](https://buildkite.com/materialize/nightly/builds/10839#019460a7-6c8e-4ba0-a339-09604aaf1bc7) we observed a panic "subsources should not produce halting errors".
> storage: use root source for halting health status

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
- misc/dbt-materialize/setup.py
- misc/dbt-materialize/tests/adapter/test_run_hooks.py
As per the upgrade guide for the newly released dbt-core v1.9.0: https://github.com/dbt-labs/dbt-core/discussions/11125
> dbt-materialize: upgrade to dbt-postgres v1.9.0

- src/ore-build/Cargo.toml
Seen in https://buildkite.com/materialize/nightly/builds/10849#0194623b-320f-4104-9ebf-f57edc024a83
Follow-up to https://github.com/MaterializeInc/materialize/pull/31013
> ore-build: Ignore unused workspace-hack dependency

- doc/user/content/sql/functions/substring.md
- doc/user/sql-grammar/sql-grammar.bnf
The substring function page did not reflect the different signatures listed on the [sql/functions/](https://materialize.com/docs/sql/functions/#substring) page.
> docs: update substring function signatures

- bin/ci-builder
I don't think anything in the `WORKSPACE` file should impact what gets included in the `ci-builder` image, and when we do include it, small changes like adding a new crate result in re-building the image.
@def- can you remember why we made this change? It wasn't immediately obvious to me from the original PR https://github.com/MaterializeInc/materialize/pull/30674.
Less frequent rebuilds of the CI builder image.
> build: remove `WORKSPACE` from `ci-builder` calculation

- WORKSPACE
Upgrades our C toolchain to `clang 19.1.6`, the latest stable release.
Upgrade Clang, unblocks cross language LTO
> build: Upgrade to clang 19

- src/compute/src/compute_state.rs
- src/compute/src/extensions/arrange.rs
- src/compute/src/logging/compute.rs
- src/compute/src/logging/differential.rs
- src/compute/src/logging/timely.rs
- src/compute/src/render.rs
This is in preparation to derive Columnar for all events. At the moment, columnar doesn't support deriving for enums with struct members, but each member needs to be a tuple. No functional changes otherwise.
> Split ComputeEvent into an enum of structs

- misc/python/materialize/checks/all_checks/webhook.py
- src/adapter/src/catalog/state.rs
- src/adapter/src/coord/command_handler.rs
- src/adapter/src/coord/consistency.rs
- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/catalog/src/memory/objects.rs
- src/sql/src/plan.rs
- src/sql/src/plan/statement/ddl.rs
- src/storage-controller/src/lib.rs
- test/testdrive/webhook.td
Some refactoring in the Adapter to treat objects created by `CREATE TABLE ... FROM WEBHOOK` actually as tables. This way they show up when querying `mz_tables`, you can run `SHOW CREATE TABLE ...`, etc.
Fixes https://github.com/MaterializeInc/database-issues/issues/8862
> adapter: actually treat `CREATE TABLE ... FROM WEBHOOK` as a Table

- src/storage/src/source/source_reader_pipeline.rs
This is a slight oversight in #30858 that switched from the async operator builder that drops capabilities when it exits to the timely rc operator builder where capabilities need to dropped manually.
Fixes https://github.com/MaterializeInc/database-issues/issues/8880
> storage: make sure the health capability is dropped

- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/transact.rs
- src/adapter/src/coord.rs
- src/adapter/src/coord/caught_up.rs
- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/read_policy.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/compute-client/src/as_of_selection.rs
- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/collection_mgmt.rs
- src/storage-controller/src/lib.rs
Work towards implementing https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20240117_decoupled_storage_controller.md. This design document is nice and small, and should help to explain the long-term motivations for those changes.
Prompted by a recent PR from @petrosagg (https://github.com/MaterializeInc/materialize/pull/30729), I went back to implement some of the easier changes I had in mind for moving towards the design linked above.
> storage: move methods from StorageController to StorageCollections

- ci/deploy/pypi.py
A follow up to https://github.com/MaterializeInc/materialize/pull/31036
Fixing a type where the release build env var was not passed correctly to the build stage.
> dbt-materialize: correctly pass RELEASE_BUILD to build stage

- src/storage-types/src/errors.rs
Previously, we'd create a new box from bytes, which allocates. Instead, we should use the same pointer to create the box.
> Avoid memory leak in BoxStrStack

- Cargo.lock
- src/repr/Cargo.toml
- src/repr/src/row.rs
With no functional changes, this PR adds a `Columnar` implementation for `Row`. It's not used yet, but will be in subsequent changes. The implementation follows the `String` implementation in columnar, both types are very similar.
> Provide a columnar implementation for Row

- ci/test/pipeline.template.yml
Normally doesn't run that slowly, but the results were rather flaky in this run: https://buildkite.com/materialize/test/builds/97121#019465c5-1ab1-425d-8f3c-2ff3195792d2
> Feature benchmark: Increase timeout

- doc/developer/testdrive.md
Since the clap update values are not implicitly converted to booleans anymore. This leads to a bunch of inconsistency. For example `MZ_UNSAFE_MODE` and `MZ_ALL_FEATURES` require `true`, but `MZ_SOFT_ASSERTIONS` and `RUST_BACKTRACE` work with `1`.
> dev docs: MZ_ALL_FEATURES=true

- ci/nightly/pipeline.template.yml
- test/0dt/mzcompose.py
Seen running OoM in https://buildkite.com/materialize/nightly/builds/10849#0194623b-329d-4ea9-9ffa-7371e0c4967a and https://buildkite.com/materialize/nightly/builds/10836#01945f52-6951-497e-aa58-a250c5dce0bc
This is just a flaky test introduced by my new workflow: https://github.com/MaterializeInc/materialize/pull/30820
> 0dt test: Fix flaky tests

- bin/ci-builder
- ci/deploy_website/pipeline.template.yml
- ci/deploy_website/website.sh
- ci/test/pipeline.template.yml
- doc/user/content/versions.json
- doc/user/layouts/partials/sidebar.html
Context: https://materializeinc.slack.com/archives/C07PN7KSB0T/p1736830571054569
Test run on the [self-managed-docs/v25.1 branch](https://github.com/MaterializeInc/materialize/tree/self-managed-docs/v25.1) I have created for now to test this: https://buildkite.com/materialize/test/builds/97158
> Support deploying self-managed docs

- doc/user/content/versions.json
> docs: Fix prefix for self-managed version links

- doc/user/content/versions.json
- doc/user/layouts/partials/sidebar.html
Fall back to local versions.json when global one is missing.
Concatenate paths for links correctly
I have tested this locally with `hugo serve` and `hugo serve --baseURL localhost/docs/self-managed/v25.1` and it seems to work fine.
> docs: Fix version selector for self-managed versions

- doc/user/layouts/partials/sidebar.html
To prevent sudden jumps in the size when the json is loaded asynchronously, see attached video:
https://github.com/user-attachments/assets/0f3e7fbc-7789-4618-b2e4-834b17a6478e
> docs: Fixed size of version selector

- ci/mkpipeline.py
For when the QA team is not around to figure things out quickly.
Review without whitespace: https://github.com/MaterializeInc/materialize/pull/31064/files?w=1
> ci: Add env variable and comment for how to switch to AWS

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/apply.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/state.rs
Internally, the catalog models an update by a retraction followed by an
insert. Items are represented internally by their CREATE SQL string. So
when processing an item update, we first remove the existing item,
then parse, plan, and optimize the new SQL string, and then finally
insert the new item.
Parsing, planning, and optimization can be expensive, so we first check
if the CREATE SQL of the addition of an item matches the CREATE SQL of
the retraction of an item. If so, we can skip parsing, planning, and
optimization and just copy the old item. This can happen, for example,
when updating the privileges of an item, because the privileges are not
stored in the item AST.
Sometimes, when objects are renamed, the CREATE SQL string of an item
may change, but it ends up producing the same HIR …
> catalog: Skip item optimization for renames

- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/compact.rs
- src/persist-client/src/iter.rs
- src/persist-client/src/read.rs
Trying to wrap up some structured migration work in advance of the flexible deployments release.
> [persist] Prep for structured-only serialized format

- ci/nightly/pipeline.template.yml
Seen timing out in https://buildkite.com/materialize/nightly/builds/10889#019471ae-58ac-425f-a958-f559ab67b4f4
> ci: Bump timeout for platform-checks 0dt

- test/canary-environment/models/loadgen/large_sales_product_product_category.sql
- test/canary-environment/models/loadgen/sales_large.sql
- test/canary-environment/models/loadgen/sales_large_tbl.sql
- test/canary-environment/models/loadgen/schema.yml
Currently growing at 33 KB/s, the old one was at 1.5 KB/s. The datagen runs on our own QA infrastructure, not in field eng. Long term plan is to move more there.
Motivation is to have a larger upsert source to find problems with long rehydration. Follow-up to the v0.128 Postmortem
> QA canary: Introduce a larger/faster growing upsert source

- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql
- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_permission_validation.sql
- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
Updating the dbt blue-green deployment actions so that the `adapter.generate_final_cluster_name` is used consistently when checking source clusters to respect customer-defined cluster naming logic using `generate_cluster_name` in their projects.
This allows us to use a correct cluster validation when users override the `generate_cluster_name` macro.
> dbt-adapter: normalize cluster name generation in deploy operation

- src/adapter/src/coord.rs
- src/adapter/src/coord/message_handler.rs
While investigating some spikes in p99 message duration in the Coordinator, I noticed that we currently block on a builtin table write when receiving a status update for a cluster.
This PR refactors the code so we wait for the builtin write to complete in a `tokio::task`, and then notify sessions.
Improve P99 latencies for Coordinator messages
> adapter: don't block the Coordinator on cluster status events

- src/persist-client/src/batch.rs
Enabled widely by default with zero consequences so far.
This has been baking in staging etc. widely with no issues for quite a while, and it's nice to clean up after oneself.
> [persist] Follow through on requested batch deletes by default

- ci/nightly/pipeline.template.yml
Don't need an explicit %N anymore
(This seems to have gotten lost in https://github.com/MaterializeInc/materialize/pull/30817 with Paul and me pushing into the same PR)
> ci: Fix names in nightly pipeline

- ci/deploy/npm.py
Noticed in https://buildkite.com/materialize/test/builds/97356#019475be-f236-4d68-b50f-3cf6017b33f7
> wasm build: Fix CI step in self-managed

- ci/release-qualification/pipeline.template.yml
Seen failing in https://buildkite.com/materialize/release-qualification/builds/719#01947235-b61a-4862-ab56-bbf3580f1284
Green run: https://buildkite.com/materialize/release-qualification/builds/720
> ci: Bump Release qualification 0dt checks timeout too

- misc/python/materialize/cli/run.py
Broken in https://github.com/MaterializeInc/materialize/pull/30817
Noticed by Gabor in https://materializeinc.slack.com/archives/CM7ATT65S/p1737202942223419
> bin/environmentd: Fix default blob path

- ci/nightly/pipeline.template.yml
See https://github.com/MaterializeInc/database-issues/issues/8892
Proof of green-ness: https://buildkite.com/materialize/nightly/builds/10916
> ci: Switch Data Ingest test to minio again

- src/sqllogictest/src/parser.rs
- test/sqllogictest/mztimestamp.slt
- test/sqllogictest/with_mutually_recursive.slt
The first commit adds a WMR test, drawing an ASCII art of the Mandelbrot set. The query is based on an [SQLite example](https://www.sqlite.org/lang_with.html#outlandish_recursive_query_examples), pointed out by @umanwizard.
Had to tweak the query a bit:
- `WITH MUTUALLY RECURSIVE` instead of `WITH RECURSIVE`
- explicit types for each CTE
- `least` instead of `min` (`min` is the aggregation function in Materialize)
- `string_agg` instead of `group_concat`
- `chr(10)` instead of `x'0a'`
- added `ORDER BY` to the `string_agg`, because otherwise Materialize chooses a non-useful order inside each group.
The second commit fixes a bug in sqllogictest: When the expected output starts with a space, the `trim_start()` used to eat this. The `trim_start` was there, because the …
> Add Mandelbrot set to WMR slt

- ci/test/pipeline.template.yml
Noticed a timeout while docker pulling in https://buildkite.com/materialize/test/builds/97430#01948309-08e1-4fe7-9d3b-195a4ad94675
> ci: Bump some low timeouts

- ci/deploy/npm.py
- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
We are planning to get these two features into v0.130.1 today:
- Blob deletion and columnar data CC @bkirwi : https://materializeinc.slack.com/archives/C07PN7KSB0T/p1736888847015789
- Azure blob storage CC @pH14 : https://github.com/MaterializeInc/materialize/pull/30817
Then we should bump the version here to v0.130.1 and put this out. @bobbyiliev @doy-materialize Does this work for you? Did I miss anything important?
@kay-kim Does this fit with our docs? I guess we have to update things like "Check out the v0.127.0 tag." to "Check out the lts-v0.130 branch"
Discussion on Slack: https://materializeinc.slack.com/archives/C07PN7KSB0T/p1737110822978439
> self-managed: Set helm-chart version v25.1 to correspond to Materialize v0.130.0

- misc/helm-charts/publish.sh
> helm-chart publish: Fix materialize repo url

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_promote.sql
- misc/dbt-materialize/tests/adapter/test_deploy.py
Fixing an error where tagging deployed schemas fails when there are multiple schemas to be tagged, eg:
```
18:15:45  Tagging schema: public
18:15:45  Tagging schema: public_some_other_schema
18:15:45  Encountered an error while running operation: Database Error
COMMENT ON SCHEMA public IS '
Deployment by mz_system on 
| Commit SHA: 887865b83604850812f67d43134c84808965ac2c
' cannot be run inside a transaction block
```
> Dbt adapter deploy promote tag schemas

- src/catalog/src/builtin.rs
Subsources move from starting to running lazily once they see a record flow through, even though they are online and healthy. This has been repeatedly brought up as confusing by users. So now, if the parent source is running, and the subsource is starting, we override its status to running to relfect its healthy status.
> manually correct subsource status from starting to running

- src/storage/src/healthcheck.rs
No functional changes, removes unused async from the HealthOperator trait.
> Remove unused async from storage health check

- misc/python/materialize/cli/bazel.py
Wrap the call to `subprocess` in a try-catch so when a Bazel build fails or is canceled we don't print the Python backtrace.
Makes `bin/bazel` a little nicer.
> bazel: tidy up `bin/bazel` invocations a bit

- doc/user/content/installation/install-on-local-kind.md
- doc/user/content/installation/install-on-local-minikube.md
In prep for release, using `v25.1.0` instead of `v25.1.0-beta.1`
> docs: update local install to use published helm charts

- ci/publish-helm-charts/pipeline.template.yml
- ci/test/pipeline.template.yml
There is no way to currently automatically determine when to run the publish step, tag is not the correct one, main isn't either
> ci: Add separate publish_helm_charts pipeline

- test/mysql-cdc-old-syntax/empty-table.td
Follow-up to https://github.com/MaterializeInc/materialize/pull/31096
Failed in nightly: https://buildkite.com/materialize/nightly/builds/10932#01948b6e-1c55-4c39-b126-7cb45d3cb699
> mysql test: Fix source status message

- ci/nightly/pipeline.template.yml
- ci/publish-helm-charts/pipeline.template.yml
A bit too late, but as a precaution
> ci: Trigger nightly when publishing helm chart

- misc/python/materialize/mzcompose/__init__.py
- src/storage/src/source.rs
- src/storage/src/source/kafka.rs
- src/storage/src/source/mysql/statistics.rs
- src/storage/src/source/postgres/replication.rs
- src/storage/src/source/probe.rs
- test/testdrive/source-timestamps.td
This PR ensures that probe timestamps, and therefore timestamps used for minting new bindings, are rounded down to the probe interval (typically 1s). This is to reduce the amount of distinct timestamps flowing through a dataflow joining multiple sources. Each distinct timestamp induces some amount of overhead, so forcing the timestamps of individual sources to the same values is more efficient.
Closes https://github.com/MaterializeInc/database-issues/issues/8885
> storage: round probe timestamps to the probe interval

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/include/materialize/macros/adapters.sql
The underlying logic to rebuild seeds didn't take into account the scenario where users provide a `generate_cluster_name ` macro override.
Using the new logic, if a custom `generate_cluster_name` macro is provided when running against a target named `dev`:
```sql
{% macro generate_cluster_name(custom_cluster_name) -%}
{%- if target.name == 'prod' -%}
{{ custom_cluster_name }}
{%- else -%}
{{ target.name }}_{{ custom_cluster_name }}
{%- endif -%}
{%- endmacro %}
```
```sql
14:22:50  On seed.mz_get_started.test_29324: /* {"app": "dbt", "dbt_version": "1.9.1", "profile_name": "mz_get_started", "target_name": "dev", "node_id": "seed.mz_get_started.test_29324"} */
set cluster = dev_quickstart;
14:22:50  Opening a new connection, currently in state closed
```
If `generate_cluster_name` is not …
> dbt-materialize: make seeds aware of user-defined cluster naming logic

- src/sql/src/func.rs
- src/sql/src/plan.rs
- src/sql/src/plan/hir.rs
- src/sql/src/plan/lowering.rs
- src/sql/src/plan/lowering/variadic_left.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/scope.rs
- src/sql/src/plan/transform_hir.rs
- src/sql/src/plan/typeconv.rs
- src/sql/src/pure/postgres.rs
A continuation of https://github.com/MaterializeInc/materialize/pull/31124. We have lots of `expr`s throughout our codebase, so it's better to explicitly mention HIR.
Also, slightly tweaks the comment at the top of the file.
> Rename `sql/src/plan/expr.rs` to `hir.rs`

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/dbt/adapters/materialize/__version__.py
- misc/dbt-materialize/setup.py
Release `dbt-materialize` v1.9.3 with a minimal fix in seed consecutive run logic.
> dbt-materialize: release `v1.9.3`

- src/sql/src/plan/hir.rs
- src/sql/src/plan/lowering.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/transform_hir.rs
The `Visit` trait is the way to do visitations nowadays. MIR is already using it everywhere (except where it has a hand-rolled traversal), but HIR still has a lot of old visitation code. This PR removes some of it. 
(There is plenty deprecated HIR visitation code left. We could probably easily remove a lot more, I just wanted to wrap this up for today. There is also some HIR visitation code that will be harder to remove, because of having meaningful extra functionality compared to the `Visit` trait, such as keeping track of subquery nesting depth while doing the visitation.)
* This PR refactors existing code to remove deprecated code.
A lot of the change is just whitespace, due to having to add `Ok(())` after some `match` clauses, where the `match` used to be the only thing in a closure, …
> Remove some deprecated HIR visitation functions

- doc/user/layouts/partials/sql-grammar/copy-from.svg
- doc/user/sql-grammar/sql-grammar.bnf
In https://github.com/MaterializeInc/materialize/pull/30959 we added support for the optional `INTO` keyword, e.g. `COPY INTO <table> FROM ...`
Update docs for existing feature.
> [copy_from] Docs for `COPY (INTO)?`

- Cargo.lock
- Cargo.toml
- src/compute-types/Cargo.toml
- src/compute-types/src/plan.rs
- src/compute-types/src/plan/lowering.rs
- src/compute/Cargo.toml
- src/compute/src/compute_state.rs
- src/compute/src/extensions/arrange.rs
- src/compute/src/logging.rs
- src/compute/src/logging/compute.rs
- src/compute/src/logging/differential.rs
- src/compute/src/logging/initialize.rs
- src/compute/src/logging/reachability.rs
- src/compute/src/logging/timely.rs
- src/compute/src/render.rs
- src/compute/src/server.rs
- src/compute/src/sink/copy_to_s3_oneshot.rs
- src/compute/src/typedefs.rs
- src/repr/Cargo.toml
- src/repr/src/global_id.rs
- src/repr/src/timestamp.rs
- src/timely-util/Cargo.toml
- src/timely-util/src/containers.rs
- src/timely-util/src/operator.rs
Convert logging dataflows to columnar
The aim of this PR is to convert some of the logging dataflows to use columnar data on dataflow edges, wherever it makes sense to do so. It introduces building blocks that we need to move columnar data across dataflow edges, and feed them into merge batchers to create arrangements from columnar data.
The PR is rather large, and it is best viewed file-by-file. The rough structure is:
* containers in timely-util to support columnar data on dataflow edges and as input to arrangements.
* Each of the log dataflows separately.
* Improvement of the `consolidate_pact` function.
* Introduction of `consolidate_and_pack` to simplify adding new introspection sources.
The goal of this PR is to show how we can use columnar data in Materialize as a replacement for …
> Columnar in logging dataflows

- Cargo.lock
- src/arrow-util/Cargo.toml
- src/arrow-util/src/lib.rs
- src/arrow-util/src/reader.rs
- src/repr/src/row.rs
- src/workspace-hack/Cargo.toml
This PR implements an `ArrowReader` in the `mz_arrow_util` crate. It's intended to be used with `COPY ... FROM ... (FORMAT PARQUET)`.
We don't currently support all Arrow Types, but so far this has been sufficient for testing and I figured with how large the change already is this was a good place to start.
Progress towards https://github.com/MaterializeInc/database-issues/issues/6575
> [copy_from]: Arrow/Parquet Reader

- src/ore-build/BUILD.bazel
- src/ore-build/Cargo.toml
the cloud repo is failing to build
> allow disabling workspace-hack in ore-build

- src/arrow-util/src/reader.rs
Seen failing in https://buildkite.com/materialize/nightly/builds/10942#01949094-85e8-40d8-8b5f-ed1eeda571d8
Follow-up to https://github.com/MaterializeInc/materialize/pull/30958
> miri test: Ignore 3 new unit tests

- src/compute-types/src/dyncfgs.rs
- src/compute/src/render/continual_task.rs
- src/compute/src/sink/correction.rs
- src/compute/src/sink/materialized_view.rs
- src/compute/src/sink/materialized_view_v2.rs
The growth of `ConsolidatingVec` was by doubling, which meant that we can end up with substantially more memory use than we really need. This PR attempts to make this configurable, growing by a smaller factor determined by a positive integer `slop`. If the result of consolidation is (1 - 1/slop)-full, we grow the vector by a factor of 1 + 1/(slop-1). These relationships were chosen to match the 2x behavior, but it's possible that they are imperfect.
I'm not certain how to test the impact of this, and whether we have "MV rehydration memory" tests, but that would be the right way to see if this is helpful. It comes at the potential expense of CPU.
> Slow the rate of growth in `ConsolidatingVec`

- test/testdrive/force-source-tables.td
Kafka sources do not work without a primary export, see https://github.com/MaterializeInc/database-issues/issues/8909. So this commit comments out the test that tests Kafka sources without a primary export.
Comment out tests that test a broken feature.
> storage: Disable broken Kafka source tests

- src/environmentd/src/http/sql.rs
Currently we prohibit all `COPY FROM` statements from running via HTTP because traditionally you need to stream data in via `stdin`. With `COPY FROM <url>` we download a file from a remote server which can be run via the HTTP protocol, and thus the web console.
Fixes a bug where `COPY FROM <url>` wouldn't work via the web console.
> [copy_from] Allow running `COPY FROM <url>` via HTTP

- src/environmentd/src/lib.rs
There are some server configuration parameters that we need during
startup, before the catalog has been fully opened. To get the current
value we manually look at the current value in LaunchDarkly (which is
confusingly returned as `None` if it matches the default value in the
code), then we manually look in the catalog, then we manually look in
the server parameter default override CLI arg map.
Previously, for some of the parameters, if we weren't able to find the
value in any of those places, then we hard-code in the value false.
This is not correct, and instead we should fall back to their default
value, which is sometimes true. This commit fixes the issue by falling
back to their default values.
> adapter: Fix startup parameter default values

- ci/test/pipeline.template.yml
- src/ore/src/lib.rs
I've been iterating on some changes in Staging recently and realized the step to tag developer Docker images uses the 'full' CI builder image meanwhile it could use the 'min' builder.
Save ~2 minutes when getting Docker images pushed
> build: Use the `min` CI builder image for Tag Docker Images

- src/compute-client/src/as_of_selection.rs
Failing to apply soft constraints is quite common, particularly with new envs that don't yet have 30 days worth of retained metrics, making it impossible to apply the 30-day compaction windows. It's unhelpful and quite noisy to log a warning in this case, so downgrade the log to info level.
* This PR removes noise from our logging.
> as-of-selection: downgrade the log emitted on soft constraint violation

- ci/mkpipeline.py
This caused https://materializeinc.slack.com/archives/C01LKF361MZ/p1737663072464569
> ci: Fix typos in AWS agents, bump number of agents before considering Hetzner overloaded

- test/testdrive/mzcompose.py
> testdrive: Remove debugging prints

- src/adapter/src/coord/ddl.rs
- src/adapter/src/coord/sequencer/inner.rs
- src/storage-client/src/client.rs
- src/storage-client/src/controller.rs
- src/storage-client/src/storage_collections.rs
- src/storage-controller/src/history.rs
- src/storage-controller/src/lib.rs
- src/storage-types/src/sinks.proto
- src/storage-types/src/sinks.rs
- src/storage/src/internal_control.rs
- src/storage/src/render.rs
- src/storage/src/render/sinks.rs
- src/storage/src/sink/kafka.rs
- src/storage/src/storage_state.rs
Some minor drive-by as I've been reading through the storage controller.
The first commit is inspired by a recent incident: we saw a bunch of Persist memory on the stack of an environment, some of which was allocated by this warmup code. Far from a smoking gun... but in general it feels wise to not attempt unbounded concurrent work, especially for an optimization like this one.
The others are hopefully self-explanatory, but let me know if anything seems odd!
> [storage] Minor controller cleanups and refactoring

- src/sql/src/plan/statement/scl.rs
- test/sqllogictest/shard_errors.slt
Previously, INSPECT SHARD would panic if it was given an ID that didn't belong to any item. This commit fixes the issue by returning an error instead.
Fixes #MaterializeInc/database-issues/issues/8910
> sql: Valid IDs in INSPECT SHARD

- src/storage/src/source/generator.rs
- test/testdrive/force-source-tables.td
This commit fixes the key-value load generator source when the primary
export is removed via the force_source_table_syntax flag.
Fixes #MaterializeInc/database-issues/issues/8904
> source: Fix key-value load gen w/o primary export

- ci/release-qualification/pipeline.template.yml
- test/mysql-cdc/mzcompose.py
- test/pg-cdc/mzcompose.py
- test/upsert/mzcompose.py
and enable in release qualification pipeline (weekly)
> tests: Add large-scale mysql/pg/upsert test

- src/storage/src/source/kafka.rs
- test/testdrive/force-source-tables.td
Before, when we had zero outputs, we would repeatedly try and create a partition queue for the same partition, because our `self.last_offsets` is empty. The existing early exit would never trigger because it only works when there is _some_ output state.
Now, we always early exit when we know we don't have any outputs.
@jkosh44 This fixes the panic in `force-source-table.td`, which have been disabled in #31159  
Fixes MaterializeInc/database-issues#8909
> storage: make Kafka sources work with zero exports

- ci/nightly/pipeline.template.yml
Have been flaky before
Test run: https://buildkite.com/materialize/nightly/builds/10958
Fixes: https://github.com/MaterializeInc/database-issues/issues/8915
> ci: Use dedicated CPU machines for limits tests

- test/terraform/aws/main.tf
- test/terraform/mzcompose.py
Upgrading the Terraform AWS Materialize module to v0.2.0 which now includes the namespace and environment variables are used to construct the names of the resources:  e.g. ${namespace}-${environment}-eks and etc.
> ci: upgrade Terraform AWS Materialize module to v0.2.0

- src/expr/src/explain/text.rs
- src/transform/src/analysis.rs
- src/transform/tests/test_transforms/humanized_exprs.spec
- test/sqllogictest/explain/optimized_plan_as_text.slt
- test/sqllogictest/explain/optimized_plan_as_text_redacted.slt
- test/sqllogictest/ldbc_bi.slt
- test/sqllogictest/ldbc_bi_eager.slt
- test/sqllogictest/limit_expr.slt
- test/sqllogictest/outer_join_lowering.slt
- test/sqllogictest/tpch_create_index.slt
- test/sqllogictest/tpch_create_materialized_view.slt
- test/sqllogictest/tpch_select.slt
1-liner fix for https://github.com/MaterializeInc/database-issues/issues/8094, correcting column name printing for Project. When looking up a column name from a column number, the code used to refer to the column names of the _output_ of Project, but we actually want to refer to the column names of the input to the Project, because the column numbers make sense only in that context.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/8094
> Fix EXPLAIN column names for Project

- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cli/inspect.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/state.proto
- src/persist-client/src/lib.rs
- src/persist-client/src/schema.rs
- src/persist/src/indexed/columnar/arrow.rs
- src/persist/src/indexed/columnar/parquet.rs
- src/persist/src/indexed/encoding.rs
Adds a new on-disk file format for Persist - the non-dual-write structured-data-only version.
We'd like this format to be supported in our on-prem releases, so folks aren't stuck with the migration midpoint.
I've intentionally left this off in CI, out of the parallel workload. For our existing cloud envs I think it's most important to verify that the (substantial) refactorings here don't cause any regression for existing flag settings. However, it is enabled in parallel workload so we should be able to spot any bugs. (And empirically those tests are good at finding bugs in this corner of Persist.)
> [persist] Structured file format

- misc/python/materialize/parallel_workload/action.py
- src/persist-client/src/batch.rs
- src/persist-client/src/cli/inspect.rs
- src/persist-client/src/fetch.rs
- src/persist-client/src/internal/encoding.rs
- src/persist-client/src/internal/machine.rs
- src/persist-client/src/internal/state.proto
- src/persist-client/src/lib.rs
- src/persist-client/src/schema.rs
- src/persist/src/indexed/columnar/arrow.rs
- src/persist/src/indexed/columnar/parquet.rs
- src/persist/src/indexed/encoding.rs
> [dnr] perf testing

- src/compute/src/logging.rs
- src/compute/src/sink/copy_to_s3_oneshot.rs
- src/storage-operators/src/s3_oneshot_sink.rs
- src/timely-util/src/operator.rs
Instead of flattening the outputs of consolidate, provide the output as a
whole batch, encoded as an `Stream<_, Vec<C>>`. This allows downstream operators
to act on a whole batch at once, without relying on undocumented properties
of how Timely channels behave. For operators that need to flatten the
output need slightly different logic.
> Consolidate produces batch of data

- src/materialized/ci/mzbuild.yml
The materialized binary generates massive debuginfo: 8GB with full debuginfo and 3.5GB with limited debuginfo. (This is not the compressed size of the debuginfo on disk, but the amount of memory required to load the debuginfo into memory so that backtraces can be symbolized.)
We've historically shipped the materialized binary with full debuginfo, so that we get rich backtraces for any crashes users run into when running the emulator. Unfortunately, the full debuginfo is so large that it is itself the *cause* of OOMs [0], which is unacceptable. (When a console query encounters certain routine errors, like a connection failing to validate, the adapter attempts to log a backtrace, which requires loading the debuginfo.) Even the limited debuginfo size (3.5GB) is unacceptable for a Docker …
> materialized: strip debuginfo

- doc/user/content/ingest-data/troubleshooting.md
- doc/user/content/sql/system-catalog/mz_internal.md
I realized the `paused` status was undocumented.
> doc: document source status paused

- src/adapter/src/catalog/migrate.rs
- src/adapter/src/catalog/open.rs
- src/catalog/src/durable/transaction.rs
- src/catalog/src/expr_cache.rs
The expression cache caches optimized expressions in a persist shard. It uses the environment's deploy generation as part of the key for the cache. The assumption was that two environments with the same deploy generation would always have the same binary version. This assumption would allow two environments with the same deploy generation to safely deserialize each other's expressions, without worrying about backwards and forwards compatibility.
This assumption was not correct. Two environments with different binary version can use the same deploy generation as long as one environment never fully completed a deployment. This is especially bad because the expression cache is written to and read from in read-only mode, before a deployment is complete.
This commit updates the key of the …
> catalog: Key expression cache by binary version

- src/storage/src/healthcheck.rs
- src/storage/src/internal_control.rs
- src/storage/src/render.rs
- src/storage/src/render/sinks.rs
- src/storage/src/storage_state.rs
The Timely `Sequencer` doesn't behave well when different workers instantiate their parts at points in time that are sufficiently spread apart. It delays commands by that creation time difference and is prone to spinning the CPU at 100%.
To work around these issues, this PR replaces the `Sequencer` used in storage for broadcasting internal commands with a dataflow that sequences by sending all commands through a single worker.
First commit introduces a simple version of the sequencer dataflow that assumes deterministic ordering of data sent through Timely channels. The second commit removes that assumption by explicitly keeping track of the command order and waiting for outstanding commands.
Fixes …
> storage: use exchange-based sequencing to broadcast internal commands

- src/adapter/src/catalog/apply.rs
In a previous version of Materialize, the legacy builtin item migration framework would allocate new IDs for introspection source indexes when they needed to be migrated. As of
14cc787db3b2cefddc4b356a76d238135271ec94, introspection source index IDs are deterministic, so even when they're migrated using the legacy builtin item migration framework, they don't receive new IDs.
This commit updates the legacy implementation of builtin item migrations for introspection sources indexes to account for the deterministic IDs.
Fixes #MaterializeInc/database-issues/issues/8921
> catalog: Fix introspection source index migration

- src/compute-types/src/dyncfgs.rs
- src/compute/src/sink.rs
- src/compute/src/sink/correction.rs
- src/compute/src/sink/correction_v2.rs
- src/compute/src/sink/materialized_view.rs
- src/compute/src/sink/materialized_view_v2.rs
- src/timely-util/src/containers/stack.rs
This PR introduces a "correction v2" buffer that differs from the existing one in that it stores data in columnated regions that can be spilled to disk. It follows the general design of the arrangement merge batcher, with the major difference that it sorts updates by time first, in an attempt to more efficiently deal with the presence of updates in
the future (commonly introduced by temporal filters).
The new correction buffer can be switched on through a feature flag, `enable_compute_correction_v2`, and is switched off by default. The plan is to keep it disabled in production but have it available for emergencies where replicas fail to hydrate due to the MV memory spike. Eventually we'll want to make the new correction buffer the default, but we should do more performance testing before …
> compute: spillable MV correction buffer

- doc/developer/design/20241008_expression_cache.md
- src/adapter/src/catalog/open.rs
- src/catalog/src/expr_cache.rs
- src/durable-cache/src/lib.rs
This commit updates the expression cache design doc to match the changes from 5df1932649885bc5417142daef16afc5cdf0e76b.
> doc: Update expr cache design doc

- src/catalog/src/expr_cache.rs
Follow up to 5df1932649885bc5417142daef16afc5cdf0e76b to update comments to reference build version instead of deploy generation.
> catalog: Update deploy generation comments

- src/environmentd/src/lib.rs
> adapter: Improve startup log

- ci/nightly/pipeline.template.yml
- misc/python/materialize/checks/scenarios_upgrade.py
- misc/python/materialize/version_list.py
- src/persist-client/src/cfg.rs
- src/persist-client/src/internal/encoding.rs
- test/legacy-upgrade/mzcompose.py
lts releases are going to be on their own versioning scheme, and so we need to define the relationship between those versions and the existing weekly release versions to allow self-hosted users to upgrade and allow us to test the upgrade process between lts releases.
i'm a bit nervous about this change because it is pretty critical to correctness - definitely open to better ideas around testing here (i wrote some more tests for the valid upgrade check but it's not super clear to me where tests should go for the catalog compatibility check).
> loosen version upgrade checks to allow for lts version upgrades

- src/persist/src/azure.rs
This refactors the impl of `Blob` for Azure in a way that should be faster. The `BlobClient` we use from the `azure_storage_blob` crate returns a `Stream` that when `await`-ed sends a ranged GET request for a chunk of a blob. This PR refactors our impl so we await each ranged request in a `tokio::task` which increases the concurrency at which we fetch chunks of a `Part`.
It also refactors how we handle the case when the `content-length` header is missing, and adds metrics so we can track how often this occurs.
Maybe progress against https://github.com/MaterializeInc/database-issues/issues/8892
> [persist] refactor Blob impl for Azure for higher performance

- src/adapter/src/catalog/migrate.rs
- src/adapter/src/catalog/open/builtin_item_migration.rs
- src/adapter/src/coord.rs
- src/catalog/src/config.rs
- src/catalog/src/durable/transaction.rs
The builtin migration shard is a persist shard used during version
upgrades. It uses the environment's deploy generation as part of the
key for the values. The assumption was that two environments with the
same deploy generation would always have the same binary version. This
assumption would allow all migration steps of two environments with the
same deploy generation to be idempotent.
This assumption was not correct. Two environments with different binary
version can use the same deploy generation as long as one environment
never fully completed a deployment. This is especially bad because the
migration shard is written to and read from in read-only mode, before
a deployment is complete.
This commit updates the key of the builtin migration shard to
explicitly use the binary version of …
> catalog: Key migration shard by binary version

- test/canary-load/mzcompose.py
Context: https://materializeinc.slack.com/archives/CL68GT3AT/p1738136577471549
> canary load: Retry frontegg auth

- ci/plugins/mzcompose/hooks/pre-exit
Cancellation happened in https://buildkite.com/materialize/nightly/builds/10992#0194ae51-f610-4440-84f7-84fb30f17361 which resulted in leftover state making https://buildkite.com/materialize/nightly/builds/10995#0194ae83-c4ed-475a-8309-e8e6a5b80a02 not run
The usual cleanup logic can't be run even though it's in a `finally` block in our Python test code. The `pre-exit` hook is still being run.
> ci: Clean up potentially leftover state in case job was cancelled

- ci/nightly/pipeline.template.yml
Works now, doesn't have to run on PRs
> ci: Enable branch filter for GCP terraform+helm chart test

- src/adapter/src/catalog.rs
- src/adapter/src/catalog/open.rs
- src/adapter/src/catalog/open/builtin_item_migration.rs
- src/adapter/src/coord.rs
- src/catalog-debug/src/main.rs
- src/catalog/src/config.rs
- src/compute-client/src/as_of_selection.rs
- src/storage-client/src/storage_collections.rs
Previously, the adapter maintained two different implementations of the
builtin item migration framework. One that was used before 0dt and one
that was used with 0dt. The 0dt implementation still works when 0dt is
turned off, but we wanted to keep the legacy implementation around
while the 0dt implementation was still new. The 0dt implementation has
been around long enough in production to prove that it works. On the
other hand, the legacy implementation has not been tested in production
in a long time.
This commit removes the legacy implementation and always uses the new
implementation. This should reduce the maintenance burden of builtin
item migrations.
In the future, the builtin item migration framework should be
completely removed and replaced with `ALTER TABLE`.
This PR refactors …
> adapter: Remove legacy builtin item migrations

- Cargo.lock
To pull in https://github.com/rust-lang/cmake-rs/pull/229, which caused a major regression in Mz build times.
* This PR updates a dependency.
> *: update cmake to 0.15.3

- src/environmentd/build.rs
- src/environmentd/src/http/root.rs
- src/http-util/src/lib.rs
- src/npm/src/lib.rs
- src/prof-http/build.rs
- src/prof-http/src/lib.rs
This PR fixes our flamegraph rendering with our builtin memory and CPU profiling. Previously the vendored JS and CSS artifacts were not getting properly included into our build because the Cargo Build script that is responsible for downloading them gets run in a different sandbox than the action that builds the library.
Now the `npm::ensure(...)` call optionally takes an `OUT_DIR` param that it will copy the artifacts into and thus they will get included as part of the Bazel build. I manually built the `materialized` Docker image with Bazel and confirmed the flamegraphs worked!
Fix our builtin memory and CPU profiling
> [build] Get the `npm` crate working with Bazel

- Cargo.lock
- src/adapter/src/coord/sequencer.rs
- src/adapter/src/coord/sequencer/inner/copy_from.rs
- src/aws-util/Cargo.toml
- src/aws-util/src/s3.rs
- src/sql-lexer/src/keywords.txt
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/copy
- src/sql/src/plan.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/rbac.rs
- src/storage-operators/Cargo.toml
- src/storage-operators/src/oneshot_source.rs
- src/storage-operators/src/oneshot_source/aws_source.rs
- src/storage-operators/src/oneshot_source/http_source.rs
- src/storage-types/src/oneshot_sources.proto
- src/storage-types/src/oneshot_sources.rs
- src/storage/src/render.rs
_Stacked on top of_: https://github.com/MaterializeInc/materialize/pull/30956
This PR implements a new AwsS3 `OneshotSource` that allows copying in files from S3, e.g.
```
COPY INTO my_table FROM 's3://my-test-bucket' (FORMAT CSV, FILES = ['important.csv']);
```
Along with `FILES = [<files>]` we also support a `PATTERN = <glob>` option which allows copying multiple files all at once.
Fixes https://github.com/MaterializeInc/database-issues/issues/8860
Fixes https://github.com/MaterializeInc/database-issues/issues/8855
Review only the final commit, the one titled "start, implementation of an S3 oneshot source"
> [copy_from] AWS source

- src/transform/src/lib.rs
- test/sqllogictest/github-8906.slt
Fixes https://github.com/MaterializeInc/database-issues/issues/8906
`TransformCtx` gives `Transform`s the hash of the plan that is the input to the transform. The hash that `TransformCtx` gives out is the one stored in `last_hash` (the "cached hash"), which has to be updated at various moments. We forgot about one such moment: `Fixpoint` sometimes jumps back to the beginning as part of its cycle detection mechanism (which, somewhat confusingly, also involves hashing, but is not currently connected to the `last_hash` mechanism). Therefore, in this case, `Transform::transform`'s `soft_assert_eq_no_log!` detects the wrong hash and reports a "cached hash clash". (And if we were to go through this `soft_assert_eq_no_log!` in prod, then the wrong hash would lead to wrong values for the …
> Fix cached hash clash in `Fixpoint`

- src/compute-types/src/explain/text.rs
- src/sql/src/plan/explain/text.rs
- test/sqllogictest/cte_lowering.slt
- test/sqllogictest/explain/physical_plan_aggregates.slt
- test/sqllogictest/explain/physical_plan_as_text.slt
- test/sqllogictest/explain/physical_plan_as_text_redacted.slt
- test/sqllogictest/explain/raw_plan_as_text.slt
- test/sqllogictest/github-2746.slt
- test/sqllogictest/outer_join.slt
- test/sqllogictest/scalar_subqueries_select_list.slt
- test/sqllogictest/tpch_create_materialized_view.slt
- test/sqllogictest/tpch_select.slt
- test/sqllogictest/transform/literal_constraints.slt
- test/sqllogictest/transform/relax_must_consolidate.slt
- test/sqllogictest/window_funcs.slt
This is a follow-up to https://github.com/MaterializeInc/materialize/pull/30983, which changed CTE order in MIR EXPLAIN. This PR does the same for HIR and LIR. Additionally (2nd commit), it also makes the HIR EXPLAIN print CTE names. (Names are still available at the HIR level.)
(The RQG fail in Nightly is unrelated, and is fixed in https://github.com/MaterializeInc/materialize/pull/31140 )
Same as https://github.com/MaterializeInc/materialize/pull/30983, this PR eliminates the surprising CTE order in EXPLAIN. Also, it makes the CTE order consistent across HIR, MIR, and LIR.
> Change HIR's and LIR's EXPLAIN CTE order

- src/adapter/src/catalog/builtin_table_updates.rs
- src/adapter/src/coord/statement_logging.rs
- src/adapter/src/optimize/dataflows.rs
- src/expr/src/relation/func.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/array.rs
- src/expr/src/scalar/func/impls/string.rs
- src/pgcopy/src/copy.rs
- src/pgrepr/src/value.rs
- src/repr/src/row.rs
- src/repr/src/row/encode.rs
- src/repr/src/scalar.rs
- src/sql/src/plan/hir.rs
Attempt to make CSV decoding faster by avoiding ephemeral allocations and copying where possible.
Copying about 760MiB of data into Materialize:
Before:
```
materialize=> \COPY tuple FROM 'data.csv' WITH (FORMAT csv, HEADER true,NULL '\N');
COPY 11010101
Time: 335687.917 ms (05:35.688)
```
After:
```
materialize=> \COPY tuple FROM 'data.csv' WITH (FORMAT csv, HEADER true,NULL '\N');
COPY 11010101
Time: 317502.991 ms (05:17.503)
```
Well, not a substantial improvement!
> Attempt to make csv decoding faster

- doc/user/content/releases/_index.md
Now that we have zero-downtime deployments, we no longer need to publish the maintenance window timing. Instead, document the small period of unavailability that occurs during the weekly upgrade.
Part of MaterializeInc/database-issues#8095.
> doc/user: remove maintenance window

- ci/test/pipeline.template.yml
Failed in https://buildkite.com/materialize/test/builds/97929#0194b4df-3fd8-4e61-b10f-1586a213578d
Follow-up to https://github.com/MaterializeInc/materialize/pull/31079
> ci: Disable skip-version-upgrade test for now

- ci/nightly/pipeline.template.yml
- test/replica-isolation/mzcompose.py
- test/testdrive/alter-sink.td
- test/testdrive/introspection-sources.td
From Nightly failures today and yesterday.
We have too many flakes currently, making Nightly annoying to use. The fact that I'm disabling some tests now is also pretty bad since we have reduced test coverage, I'd appreciate any progress on:
- https://github.com/MaterializeInc/database-issues/issues/8637 @bkirwi 
- https://github.com/MaterializeInc/database-issues/issues/8932 Already pinged in https://materializeinc.slack.com/archives/C08ACQNGSQK/p1738168087934519
- https://github.com/MaterializeInc/database-issues/issues/8636 @petrosagg
> ci: Disable some tests and work around recent flakes

- misc/python/materialize/cli/ci_annotate_errors.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/31140
Seen the annotation in https://buildkite.com/materialize/test/builds/97932
> ci: Stop annotating expected fixpoint errors

- Cargo.lock
- deny.toml
- src/adapter/src/catalog/open.rs
- src/build-info/Cargo.toml
- src/build-info/src/lib.rs
The expression cache uses the build version as part of the key to ensure that a materialize instance only tries to deserialize expressions that were serialized using the same version of the code. However, a single dev build version can be used for many different builds, which can lead to errors in deserialization when running locally. This commit fixes the issue by enriching dev build versions with build metadata containing the build ID.
Note: we could enrich all build versions with build ID metadata without any correctness issues. However, the ID is fairly long and must be stored for each expression. Since we already have the guarantee that a prod build version is only ever used with a single build, it would be wasted space for prod build versions.
Fixes …
> adapter: Enrich expr cache version in dev

- doc/user/content/transform-data/optimization.md
When a relation is joined with different relations on different keys, then separate indexes should be created for each of these keys. Kapa is insisting on adding a wrong index in this case, so this PR is making this fact more prominent in the docs.
> docs: Add an important note about index keys

- src/persist/src/cfg.rs
azure blob storage for persist currently only works on azurite. This fixes the syntax in detecting azure blob store when actually working with azure.
> fix error detecting azure blobstore scheme

- doc/user/layouts/partials/head.html
https://preview.materialize.com/materialize/31202/
(the Documentation Cloud is set up on Kapa side as well so that it excludes docs/self-managed/)
> docs: kapa.ai exclude self-managed sources in cloud docs

- src/storage-operators/src/oneshot_source.rs
- src/storage-operators/src/oneshot_source/aws_source.rs
- src/storage-operators/src/oneshot_source/http_source.rs
- src/storage-operators/src/oneshot_source/util.rs
_Stacked on top of_ https://github.com/MaterializeInc/materialize/pull/31144
This PR refactors ranged get requests so the logic for forming the header value is shared for both the HTTP and S3 source. It also fixes a bug where sometimes `HEAD` requests (which we use to get metadata for a file) are not supported, so we fallback to a `GET` request but quickly drop the body.
Fix a bug in ranged HTTP requests I found in the demo today
review only the final commit, the one titled "start, fix ranged requests"
> [copy_from] Refactor ranged requests, fix HTTP source

- doc/user/content/sql/system-catalog/mz_internal.md
- src/catalog/src/builtin.rs
- test/sqllogictest/privilege_grants.slt
As it says in the title!
Fixes https://github.com/MaterializeInc/database-issues/issues/8938
> query_history: Reduce amount of indexed data down to 1 day

- ci/nightly/pipeline.template.yml
Seen failing in https://buildkite.com/materialize/nightly/builds/11019#0194ba4f-8dc1-4c30-8021-3de1725733b9
> fatal: Failed to upload and process pipeline: Pipeline upload rejected: One of the steps you provided was invalid: The reason provided to `skip` is too long. The maximum length is 70 characters
> ci: Fix too long skip message

- misc/python/materialize/source_table_migration.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/30483
Failed in https://buildkite.com/materialize/nightly/builds/11022
```
pg-cdc-old-syntax-materialized-1  | environmentd: fatal: incompatible persist version 0.131.0, current: 0.133.0-dev.0, make sure to upgrade the catalog one version forward at a time
```
Test run: https://buildkite.com/materialize/nightly/builds/11029
> tests: Fix latest version in migration tests

- test/replica-isolation/mzcompose.py
We noticed that the check for `AllowCompaction` commands flakes. Fix an incorrect check to disable introspection subscribes.
Fixes MaterializeInc/database-issues#8932
> Properly disable introspection subscribes in replica isolation test

- src/storage/src/source/source_reader_pipeline.rs
- src/timely-util/src/reclock.rs
The `reclock` operator accepts and enqueues all remap updates, and requires memory proportional to the number of updates supplied. This has the potential to be much larger than required if the updates when advanced using `as_of` would consolidate to a much smaller collection.
This PR advances all inbound times using `as_of`, and consolidates them before enqueueing them in the heap-based holding pen. This does not guarantee that they will fully consolidate, as it depends on non-determinism of data arrival, and a more thorough solution might look more like DD's `MergeBatcher` that uses a continual merge sort to maintain consolidated priority order. Ideally this temporary fix relieves some pressure, though.
> Advance and consolidate remap updates

- src/compute/src/arrangement/manager.rs
- src/compute/src/compute_state.rs
- src/compute/src/render.rs
- src/compute/src/render/context.rs
- src/compute/src/render/join/delta_join.rs
- src/compute/src/render/join/linear_join.rs
- src/compute/src/render/reduce.rs
- src/compute/src/render/threshold.rs
- src/repr/src/fixed_length.rs
Removes the MzArrangement, MzArrangementImport, SpecializedTraceHandle, and FromDatumIter types. They were mostly boilerplate that didn't add much value, or were enums with a single variant.
> Remove redundant types in compute

- src/storage/src/source/generator.rs
- src/storage/src/source/generator/key_value.rs
- src/storage/src/source/kafka.rs
- src/storage/src/source/mysql.rs
- src/storage/src/source/postgres.rs
- src/storage/src/source/source_reader_pipeline.rs
- src/storage/src/source/types.rs
This PR makes the simple load generators export a progress stream, giving the remap operator the ability to mint bindings earlier, thus allowing the reclock operator to pass through snapshot updates instead of stashing them all. The effect of this that load generators now need constant memory during hydration, instead of memory proportional to the snapshot size.
Before this PR, an SF10 TPCH load generator required a `200cc` instance to successfully hydrate. With this PR it hydrates on a `25cc`.
This PR also makes the progress-stream non-optional in source rendering, to avoid pitfalls like this in the future.
Hydrating load generators requires memory proportional to their snapshot size.
> storage: make loadgens export a progress stream

- doc/user/content/sql/explain-plan.md
- doc/user/content/transform-data/optimization.md
- doc/user/data/explain_plan_operators.yml
- Update example output for fast path EXPLAIN
- CTE correspondence
- MIR Union text tweak:
- Only _some_ Union stages force consolidation.
- Eliminate "stage" terminology, because this is an internal-only terminology (coming from the dataflow world). Also, it's easy to confuse it with "EXPLAIN stages", which is a completely different thing, referring to the stages of compiling a query.
- Note that it corresponds to UNION DISTINCT.
- Join
- Correct mem usage, and link to the Optimization page.
- Correct RAW PLAN example.
- Various tweaks for Reduce.
- Change the order of the "Plan operators" table, to have the default EXPLAIN first.
- I removed the "**Private preview**" marker from "filter pushdown". I'm pretty sure this is enabled globally for everybody, and is turned on by default.
- …
> docs: Improvements in EXPLAIN docs

- bin/cut-self-managed-release
- misc/python/materialize/cli/helm_chart_version_bump.py
- misc/python/materialize/release/cut_self_managed_release.py
To automate what I've been doing manually for v25.1.0 and v25.1.1
> self-managed: Introduce script to cut releases

- misc/helm-charts/operator/Chart.yaml
- misc/helm-charts/operator/README.md
- misc/helm-charts/operator/README.md.gotmpl
- misc/python/materialize/version_list.py
> self-managed mz: Prepare for v25.1.1

- ci/builder/Dockerfile
crosstool-ng.org does not belong to crosstool-ng anymore
> ci-builder: Fix crosstool link

- src/storage/src/sink/kafka.rs
> storage: downgrade noisy log

- ci/nightly/pipeline.template.yml
- test/limits/mzcompose.py
> Minor nightly fixes (February 4)

- ci/plugins/mzcompose/hooks/pre-exit
> ci: Force-destroy terraform only in terraform tests

- doc/user/content/ingest-data/postgres/amazon-rds.md
- doc/user/layouts/shortcodes/network-security/privatelink-kafka.md
Adding a small note to point out that misalignment between ports and broker addresses will result in connectivity issues.
> doc: add ports aliugment note in Kafka privatelink guide

- src/compute-types/src/dyncfgs.rs
- src/compute/src/compute_state.rs
- src/compute/src/render.rs
- src/compute/src/render/context.rs
- src/compute/src/render/flat_map.rs
- src/compute/src/render/join/linear_join.rs
- src/compute/src/render/sinks.rs
- src/compute/src/render/top_k.rs
- src/compute/src/sink/materialized_view_v2.rs
Adds fueling to `as_specific_collection` by calling into `flat_map` instead
of `as_collection`. Add a flag to restore the previous behavior.
> Fueled as_specific_collection

- src/compute/src/render/join/linear_join.rs
Change `try_from_str` to not allocate. No behavior change, just noticed this looking at related code.
> Non-allocating YieldSpec::try_from_str

- misc/python/materialize/source_table_migration.py
> tests: Keep source table migration tests around for now

- src/timely-util/src/reclock.rs
Unit test the logic added in #31248. The tests tests two extreme scenarios. In the first scenario a single big batch of unconsolidated bindings are presented to the operator. In the second scenario tiny batches of the same number of uncompacted bindings are presented to the operator over multiple steps.
> timely-util: reclock: test binding consolidation

- test/cloudtest/test_full_testdrive.py
- test/mysql-cdc-old-syntax/mzcompose.py
- test/pg-cdc-old-syntax/mzcompose.py
- test/pg-cdc/mzcompose.py
- test/testdrive-old-kafka-src-syntax/mzcompose.py
Noticed and fixed for one test by Marty in https://github.com/MaterializeInc/materialize/pull/31239
Nightly run to verify: https://buildkite.com/materialize/nightly/builds/11050
> tests: Fix glob root dir to respect MZ_ROOT

- test/testdrive/source-statistics.td
Same cause as [previous flakes](https://github.com/MaterializeInc/database-issues/issues/8848) in `updates_committed` counts, same fix as well.
Fixes https://github.com/MaterializeInc/database-issues/issues/8943
> test: fix another flake in source statistics tests

- src/materialized/ci/entrypoint.sh
Suggested by Moritz in https://materializeinc.slack.com/archives/C07FX1W1Y03/p1738762660566029
> Mz emulator: Disable statement logging by default

- test/terraform/aws/main.tf
As per the suggestion [here](https://github.com/MaterializeInc/terraform-aws-materialize/issues/17#issuecomment-2632764448), disabling S3 bucket versioning and encryption to improve the S3 bucket deletion time in tests.
> ci: improve aws terraform module test s3 bucket deletion

- misc/helm-charts/operator/values.yaml
Removing the C size clusters from the default cluster sizes map for self-hosted.
> helm-chart: remove C size clusters from values file

- misc/python/materialize/checks/all_checks/mysql_cdc.py
Seen failing in https://buildkite.com/materialize/nightly/builds/11061#0194d7d7-4721-4741-8e43-668699fa5696
Should have rebased the original PR before adding this, then we would have noticed on the PR's run already.
> platform-checks: Bump minimum version for invisible columns

- doc/user/content/releases/v0.131.md
- doc/user/content/releases/v0.132.md
- doc/user/content/releases/v0.133.md
Because we have moved the release to a week later, but the automatic script still ran and broke things: https://github.com/MaterializeInc/materialize/commit/06f1447ba69ae38df36ca8024d6d245476e09eab
Seen failing in https://buildkite.com/materialize/test/builds/98190#0194d8ea-f70a-4d6d-9379-5b2080ffe748
Related to https://github.com/MaterializeInc/release/pull/138
This code is wrong:
https://github.com/MaterializeInc/release/blob/2ac7a35bce12c13f3a6f464650aa48a2a3320534/release/scripts/complete_release.py#L52
It should fail when the prefix is not what it expects, I'll provide a fix. Edit: https://github.com/MaterializeInc/release/pull/139
> Fix botched release docs

- test/pg-cdc/mzcompose.py
OoM seen in https://buildkite.com/materialize/release-qualification/builds/739#0194d56a-9bde-4ca9-9ed4-836dc886ad44
> pg-cdc test: Reduce size for large scale workflow

- test/mysql-cdc-old-syntax/invisible-columns.td
Noticed in https://buildkite.com/materialize/nightly/builds/11064#0194d8ae-2f77-487b-b6fc-ec78a95aaaef
Nightly run to verify: https://buildkite.com/materialize/nightly/builds/11066
Follow-up to https://github.com/MaterializeInc/materialize/pull/31239
> mysql old syntax test: Invisible columns supported

- src/ore/src/panic.rs
Would have been useful for https://materializeinc.slack.com/archives/C08ACQNGSQK/p1738835651328899
Example:
```
$ target/debug/environmentd --environment-id cloudtest-test-00000000-0000-0000-0000-000000000000-0 --orchestrator kubernetes --persist-blob-url http://asd --clusterd-image clusterd --bootstrap-default-cluster-replica-size 1 --cluster-replica-sizes 1
2025-02-06T15:42:23.573696Z  INFO environmentd::run: mz_environmentd::environmentd::main: startup: envd init: beginning
2025-02-06T15:42:23.573745Z  INFO environmentd::run: mz_environmentd::environmentd::main: startup: envd init: preamble beginning
2025-02-06T15:42:23.577135Z  thread 'main' panicked at src/environmentd/src/environmentd/main.rs:626:9:
environmentd: fatal: creating kubernetes orchestrator: failed to infer config: …
```
> mz-ore: Add timestamp to panic messages

- misc/wasm/Cargo.lock
https://github.com/MaterializeInc/materialize/security/dependabot/105
What I ran:
```bash
cd misc/wasm
cargo update --precise 2.5.4 url
cargo update --precise 1.0.3 idna
```
> build(deps): Upgrade idna in wasm

- src/storage-client/src/storage_collections.rs
Left behind after some ALTER TABLE work
Code cleanup
> [adapter] Remove left over log line

- .github/dependabot.yml
I don't see a reason to limit it that much
Failed here for example: https://github.com/MaterializeInc/materialize/network/updates/957451269
> dependabot: Allow opening more PRs

- ci/mkpipeline.py
Context: https://materializeinc.slack.com/archives/C01KV5PEZ9R/p1738920801246719?thread_ts=1738920703.879989&cid=C01KV5PEZ9R
> ci: Disable bazel remote cache temporarily

- Cargo.lock
- Cargo.toml
- deny.toml
- src/mysql-util/Cargo.toml
- src/sql/Cargo.toml
- src/storage-types/Cargo.toml
- src/storage/Cargo.toml
- src/testdrive/Cargo.toml
- src/workspace-hack/Cargo.toml
The released version contains our patches.
> Switch to official mysql_async

- ci/mkpipeline.py
This reverts commit 52e56da8cdefca71726c42f6c6734dea68d33cb2.
When remote cache is fixed
> Revert "ci: Disable bazel remote cache temporarily"

- test/mysql-cdc-old-syntax/invisible-columns.td
The newly introduced migration tests run from the previous Mz version and test that we can migrate the source when running a new version. (Does this even make sense or can we just use a new version for both? Unfortunately Joe left so I can't ask him what the original motivation for that was)
For now we can skip the td file when it's starting in an older version.
Failure seen in https://buildkite.com/materialize/nightly/builds/11076#0194ddd4-9f47-4888-bbaa-89ddfbc86da8
> migration test: Skip invisible columns in old version

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
Discussion: https://materializeinc.slack.com/archives/CM7ATT65S/p1738925417904019
Currently blocking PRs with ~6 builds per hour and only one Mac agent available.
> ci: Move macOS clippy to Nightly for now

- test/upsert/rehydration/03-after-rehydration.td
See https://github.com/MaterializeInc/database-issues/issues/8802
Failure seen in https://buildkite.com/materialize/nightly/builds/11076#0194ddd4-9f35-4f61-b235-39905f0238cc
> upsert test: Disable another flaky source stats query

- ci/nightly/pipeline.template.yml
OoM seen in https://buildkite.com/materialize/nightly/builds/11085#0194e147-33e8-4a37-b476-2b1edbf5ba35
> ci: Larger agent for SQLancer QueryPartitioning

- ci/README.md
- ci/builder/requirements-core.txt
> Adapt comment in ci builder to consult testing, not Nikhil

- misc/python/materialize/cli/ci_annotate_errors.py
Follow-up to https://github.com/MaterializeInc/materialize/pull/31306
Noticed in https://buildkite.com/materialize/test/builds/98593#0194e64e-542f-403e-85a8-cf8f7b4d5362
> ci: Detect new panic pattern

- ci/nightly/pipeline.template.yml
> cloudtest: Try to reenable disabled test

- misc/python/materialize/cli/run.py
At the moment, we're exposing the default DB port 6876 only to localhost,
but the internal one to all addresses. This makes it difficult to test the
console locally because it needs access to 6876, and running it on the
host's network can cause other port collisions.
For this reason, open up connections to 6876 to all hosts. This is not a
security regression as we're already opening the internal endpoint to all
addresses.
> Listen on 0.0.0.0:6876 through cli

- src/timely-util/src/activator.rs
- src/timely-util/src/builder_async.rs
- src/timely-util/src/containers.rs
- src/timely-util/src/containers/array.rs
- src/timely-util/src/containers/stack.rs
- src/timely-util/src/event.rs
- src/timely-util/src/operator.rs
- src/timely-util/src/pact.rs
- src/timely-util/src/replay.rs
Some files were licensed under the BSL, although the intention was to
license the files under the Apache license. This change aligns all files
in the mz-timely-util crate to use the same license.
> Correct license of timely-util

- .github/dependabot.yml
to have fewer open PRs at a time. Suggested by @doy-materialize : https://materializeinc.slack.com/archives/C08ACQNGSQK/p1738940883162109?thread_ts=1738871426.623379&cid=C08ACQNGSQK
Let's see how this goes, might require more manual work in case one dependency causes errors/lint failures, but doesn't overload our CI as much.
> dependabot: group updates for minor and patch versions

- src/storage/src/render.rs
- src/storage/src/storage_state.rs
Before, we would purely pump upgrades from running dataflows over to the
controller. Which would make it so that when a controller re-connects it
doesn't get status messages for the latest state.
Now, we track the latest status update, per object, and also what has
been reported, per object. And on re-connect we clear out what has been
reported, which makes it so that we report the latest status when a
reconnect happens.
> storage: track latest reported status and report on reconnect

- ci/test/pipeline.template.yml
Timeout seen in https://buildkite.com/materialize/test/builds/98655 and https://buildkite.com/materialize/test/builds/98666
> ci: Increase parallelism/agent size for SLT and Testdrive

- misc/python/materialize/cli/ci_annotate_errors.py
- src/adapter-types/src/dyncfgs.rs
- src/adapter/src/catalog/transact.rs
- src/catalog/src/durable.rs
- src/catalog/src/durable/initialize.rs
- src/catalog/src/durable/persist.rs
- src/catalog/src/durable/transaction.rs
- src/environmentd/src/deployment/preflight.rs
- src/environmentd/src/lib.rs
- test/0dt/mzcompose.py
Before, a hydrating read-only environment would read a catalog snapshot on bootstrap and then not subscribe to further changes. This means that we would not be hydrating collections/replicas that are created in the old version that is still running, and those would then have to be hydrated after cutting over to the new version.
With this change, we periodically check if new collections/replicas where created and we also check right before announcing as ready to promote. When we _do_ notice there was relevant DDL, we halt. This will make it so we're restarted in read-only mode again, and can now read an up-to-date catalog snapshot.
It's important to note that any running clusters are not restarted, so any work that has already gone into hydration will not be lost.
I think there's no one …
> 0dt: in preflight checks, notice DDL changes and restart read-only envd

- src/adapter/src/explain/insights.rs
- src/expr/src/relation.rs
- src/sql/src/func.rs
- test/sqllogictest/explain/optimized_plan_as_text.slt
See https://github.com/MaterializeInc/database-issues/issues/8831#issuecomment-2643526472
The first commit is just a 1-liner fix for the bug (and adding tests), while the second commit is a bit of refactoring to simplify some related code.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/8831#issuecomment-2643526472
> Fix a minor EXPLAIN bug around `count(*)`

- misc/helm-charts/operator/templates/deployment.yaml
- misc/helm-charts/operator/tests/deployment_test.yaml
- misc/images/materialized-base/Dockerfile
- src/orchestratord/src/controller/materialize.rs
- src/orchestratord/src/controller/materialize/environmentd.rs
Was able to test this by using `bin/mzimage acquire orchestratord` to get a new image then pointing the helm chart at it
Fixes https://github.com/MaterializeInc/cloud/issues/10755
Dependent on https://github.com/MaterializeInc/console/pull/3683 being merged and the tag being pushed
> Disable activity log for self managed

- ci/nightly/pipeline.template.yml
> ci: Skip copy-to-s3 since it's currently broken

- ci/nightly/pipeline.template.yml
- ci/test/pipeline.template.yml
Follow-up to https://github.com/MaterializeInc/materialize/pull/31404
This gives us a faster signal without costing any extra resources. With nightly we might have broken main for 1 day, the Mac agent is idling anyway.
> ci: Move macOS clippy to Tests, but don't run on PRs
