MaterializeInc/materialize

src/ore/Cargo.toml
src/ore/src/panic.rs

Adds conditional compilation for `chrono` in `mz-ore` crate.
cargo buid/test failures
```
error[E0432]: unresolved import `chrono`
--> src/ore/src/panic.rs:31:5
|
31 | use chrono::Utc;
|     ^^^^^^ use of undeclared crate or module `chrono`
For more information about this error, try `rustc --explain E0432`.
error: could not compile `mz-ore` (lib) due to 1 previous error
```

mz-ore: conditional compilation for chrono

---

ci/mkpipeline.py

Priority becomes high again if someone manually adds a commit to a dependabot PR

ci: Lower priority for dependabot

---

ci/test/pipeline.template.yml

ci: Move slow lints to Hetzner

---

src/adapter/BUILD.bazel
src/adapter/Cargo.toml

I've been dogfooding this one for a while now, I think after https://github.com/MaterializeInc/materialize/pull/31016 we've removed the last source of non-determinism in the build which allows pipelining to work for the adapter crate!
Faster builds

bazel: enable pipelining for the `adapter` crate

---

src/adapter/src/catalog/transact.rs
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/util.rs
src/catalog/src/memory/objects.rs
src/storage-client/src/controller.rs
src/storage-client/src/storage_collections.rs
src/storage-controller/src/history.rs
src/storage-controller/src/lib.rs
src/storage-types/src/controller.rs
src/storage-types/src/sinks.proto
src/storage-types/src/sinks.rs
src/storage/src/sink/kafka.rs
src/storage/src/storage_state.rs
test/cluster/mzcompose.py
test/testdrive-old-kafka-src-syntax/controller-frontiers.td
test/testdrive/controller-frontiers.td

Design sketch is here: https://github.com/MaterializeInc/database-issues/issues/8603#issuecomment-2611104841
Fixes https://github.com/MaterializeInc/database-issues/issues/8603
Adding a collection for sinks makes them much more like other types of things that the storage controller manages, which allows (and forces) us to handle them as a type of collection instead of a separate thing. Reworking this is much of the size of the diff - though the net result is slightly less / more uniform controller code, which is nice.
I've left a number of `// TODO(sinks)` todos for possible followups that I didn't want to bite off here.

[storage] Add a progress shard for sinks and skip the snapshot when possible

---

src/adapter/BUILD.bazel
src/adapter/Cargo.toml

This reverts commit 361b5c10448a10b906af27825e96a7c245358298.
Turns out the build still isn't deterministic yet, see https://buildkite.com/materialize/test/builds/98823#_

Revert "bazel: enable pipelining for the `adapter` crate (#31458)"

---

src/persist-client/src/cli/admin.rs

Was chatting with @frankmcsherry and @kay-kim, when reading through logs to debug an issue folks get misled by the "dangerous" term in this log line and it can leave folks confused as to whether or not this log line is indicative of an issue or not.
Make logs less misleading

logs: remove the term 'dangerous_force_compaction...'

---

misc/python/materialize/mzcompose/__init__.py
src/persist-client/src/cfg.rs
src/persist-client/src/internal/cache.rs

This PR introduces a dyncfg that allows us to tune the size of the in-mem blob cache based on the number of threads in the current process. Specifically it adds two new flags:
* `persist_blob_cache_scale_with_threads: bool` - enables this new sizing. default is `false`
* `persist_blob_cache_scale_factor_bytes: usize` - scaling factor, the number of bytes we'd size for the cache, pre-thread in the process. default is `32MiB`
The default scaling factor is less than the current static size of the cache (128MiB) so to prevent regressing the size of the cache on small clusters we use the static size as a minimum.
No concrete ask but seems like a useful knob to have

[persist] Scale the size of the in-mem blob cache based on number of threads

---

misc/python/materialize/mzcompose/__init__.py
src/compute/src/sink/correction_v2.rs
src/timely-util/src/containers/stack.rs

This PR extends the `CorrectionV2` data structure with a `Stage` that accumulates inserted updates before they get inserted into the sorted chains. This significantly reduces the amount of chain merges that need to be done in workloads that trickle in large amounts of updates in small batches, greatly speeding up these workloads.
For some reason, the memory tests introduced in https://github.com/MaterializeInc/materialize/pull/31267 are such a workload. Brief testing reveals that this PR speeds up the MV hydration in the `-800mb` test, when pointed against `CorrectionV2`, by roughly an order of magnitude, from ~300s to ~30s.
Note that this change doesn't have much impact when running locally on macOS. For some reason the batch sizes entering the MV sink are much smaller when running in …

compute/correction-v2: introduce a Stage to speed up small inserts

---

src/adapter/src/active_compute_sink.rs
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner/copy_from.rs
src/storage-client/src/client.proto
src/storage-client/src/client.rs
src/storage-client/src/controller.rs
src/storage-controller/src/history.rs
src/storage-controller/src/lib.rs
src/storage/src/storage_state.rs

This PR fixes the `TODO(cf1)` related to canceling oneshot ingestions. It adds a `StorageCommand::CancelOneshotIngestion` that `reduce`s/compacts away a corresponding `StorageCommand::RunOneshotIngestion`, much like `ComputeCommand::Peek` and `ComputeCommand::CancelPeek`.
We send a `StorageCommand::CancelOneshotIngestion` whenever a user has canceled a `COPY FROM` statement, but also the storage controller will send one whenever a `RunOneshotIngestion` command completes.
Fix `TODO(cf1)` related to cancelation

[copy_from] Proper cancelation via `CancelOneshotIngestion` message

---

test/sqllogictest/advent-of-code/2023/aoc_1201.slt
test/sqllogictest/advent-of-code/2023/aoc_1202.slt
test/sqllogictest/advent-of-code/2023/aoc_1203.slt
test/sqllogictest/advent-of-code/2023/aoc_1204.slt
test/sqllogictest/advent-of-code/2023/aoc_1205.slt
test/sqllogictest/advent-of-code/2023/aoc_1206.slt
test/sqllogictest/advent-of-code/2023/aoc_1207.slt
test/sqllogictest/advent-of-code/2023/aoc_1208.slt
test/sqllogictest/advent-of-code/2023/aoc_1209.slt
test/sqllogictest/advent-of-code/2023/aoc_1210.slt
test/sqllogictest/advent-of-code/2023/aoc_1211.slt
test/sqllogictest/advent-of-code/2023/aoc_1212.slt
test/sqllogictest/advent-of-code/2023/aoc_1213.slt
test/sqllogictest/advent-of-code/2023/aoc_1214.slt
test/sqllogictest/advent-of-code/2023/aoc_1215.slt
test/sqllogictest/advent-of-code/2023/aoc_1216.slt
test/sqllogictest/advent-of-code/2023/aoc_1217.slt
test/sqllogictest/advent-of-code/2023/aoc_1218.slt
test/sqllogictest/advent-of-code/2023/aoc_1219.slt
test/sqllogictest/advent-of-code/2023/aoc_1220.slt
test/sqllogictest/advent-of-code/2023/aoc_1222.slt
test/sqllogictest/advent-of-code/2023/aoc_1223.slt
test/sqllogictest/advent-of-code/2023/aoc_1224.slt
test/sqllogictest/advent-of-code/2023/aoc_1225.slt

Adds more options to the EXPLAINs in the Advent of Code slts.
My main motivation for this is that I'd like to see the details of join plan changes in https://github.com/MaterializeInc/materialize/pull/31281
Also, it's better to be uniform across our slts, and tpch as well as ldbc slts already use these options that I'm adding in this PR for aoc.

Tweak aoc slts to use more EXPLAIN options

---

src/adapter/src/catalog/builtin_table_updates.rs
src/adapter/src/catalog/builtin_table_updates/notice.rs
src/adapter/src/catalog/open.rs
src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/compute-client/src/as_of_selection.rs
src/storage-client/src/client.rs
src/storage-client/src/storage_collections.rs
src/txn-wal/src/txn_cache.rs
src/txn-wal/src/txn_write.rs

This PR refactors Coordinator startup, specifically `bootstrap_tables()` to stream our retractions into a Persist `BatchBuilder` instead of buffering them in-memory. It also makes two `txn-wal` related fixes that were required to get this passing. A more detailed explanation of them is in a comment below.
Fix/reduce a memory spike we've seen at startup.

[adapter] Stream BuiltinTable retractions at bootstrap

---

misc/python/materialize/mzcompose/__init__.py
src/adapter-types/src/dyncfgs.rs
src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord.rs
src/adapter/src/coord/appends.rs
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/message_handler.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/metrics.rs
src/adapter/src/session.rs
src/ore/src/assert.rs
src/ore/src/stats.rs

This PR does two things:
1. Changes explicitly triggered group commits (e.g. a write to `mz_sessions`) to have a minimum batching interval. Today when we trigger a group commit we only allow 1 to be in-flight at a time, this allows pending writes to naturally batch. But if the write is small there's a good chance Persist will inline it and it will take low 10s of milliseconds. Added in this PR is a dyncfg `group_commit_batch_duration` which ensures we will wait X duration before running the next group commit. The default value is 100ms.
2. When starting a `Session`/connection we have to update the `mz_sessions` table. Waiting for this write to complete has been moved to when a Session receives a query, and if that query reads from the `mz_sessions` table. This means starting a `Session` …

[adapter] don't block on builtin table write in `Session` creation

---

src/compute-client/src/metrics.rs
src/compute/src/arrangement/manager.rs
src/compute/src/compute_state.rs
src/compute/src/metrics.rs
src/compute/src/server.rs

The compute metrics code, on the replica side, has become somewhat inconsistent, with only some of the per-worker metrics reflected in the `WorkerMetrics` type, while others are still updated by passing a `worker_id` explicitly every time. This PR attempts to clean up the metrics code by:
* Making all compute metrics per-worker metrics. `timely_step_duration_seconds` and `persist_peek_seconds` weren't before, but I think they should be, for consistency and to allow detecting worker skew.
* Making all metrics accessible through `WorkerMetrics`.
* Making the `Worker` and `ComputeState` methods only use `WorkerMetrics`, instead of both `ComputeMetrics` and `WorkerMetrics`.
* Removing the `TraceMetrics` type and replacing its usage with `WorkerMetrics` too.

compute: clean up metrics code

---

doc/developer/design/20250127_multi_replica_scheduling_singleton_sources.md

Rendered: https://github.com/aljoscha/materialize/blob/design-multi-replica-singleton-sources/doc/developer/design/20250127_multi_replica_scheduling_singleton_sources.md

design: multi-replica scheduling for singleton sources (aka hot standby)

---

Cargo.lock
src/adapter-types/Cargo.toml
src/adapter/Cargo.toml
src/catalog/Cargo.toml
src/cluster/Cargo.toml
src/compute-client/Cargo.toml
src/compute-types/Cargo.toml
src/compute/Cargo.toml
src/controller/Cargo.toml
src/durable-cache/Cargo.toml
src/environmentd/Cargo.toml
src/expr/Cargo.toml
src/interchange/Cargo.toml
src/persist-cli/Cargo.toml
src/persist-client/Cargo.toml
src/persist-types/Cargo.toml
src/persist/Cargo.toml
src/repr/Cargo.toml
src/service/Cargo.toml
src/storage-client/Cargo.toml
src/storage-controller/Cargo.toml
src/storage-operators/Cargo.toml
src/storage-types/Cargo.toml
src/storage/Cargo.toml
src/timely-util/Cargo.toml
src/timely-util/src/containers.rs
src/transform/Cargo.toml
src/txn-wal/Cargo.toml

The columnar crate had some breaking changes, which we're fixing as part of this change.

Update Timely, Differential, Columnar

---

ci/test/pipeline.template.yml
src/aws-util/src/s3_uploader.rs
src/persist/src/s3.rs
src/storage-operators/src/s3_oneshot_sink/pgcopy.rs

Test run: https://buildkite.com/materialize/test/builds/98983#0194febb-f78c-4a9b-9c49-b0614e8472fa
28 min vs 37 min on main

ci: Move cargo test to Hetzner (and disable real-S3 tests)

---

src/sql-parser/src/ast/defs/statement.rs

Was forgotten in https://github.com/MaterializeInc/materialize/pull/31185
> 3c1c409 changes the default for a bare EXPLAIN to use EXPLAIN PHYSICAL PLAN. But I only changed the default in order to catch every bare EXPLAIN, and I change the default back in c97eb41.
@mgree This is a good argument for at least having one test remaining that has a bare `EXPLAIN` I guess ;)
Noticed by @ggevay in https://materializeinc.slack.com/archives/C08ACQNGSQK/p1739461427061339

explain: Switch default to global plan instead of physical plan

---

src/sql/src/plan.rs
src/sql/src/plan/statement/ddl.rs
test/cloudtest/test_managed_cluster.py

The check for sources was missed in graceful reconfig leading to panics. We should make sure we're checking and returning appropriate errors.

fixes issue where we panic when gracefully altering cluster with sources

---

ci/test/pipeline.template.yml

timeouts seen in https://buildkite.com/materialize/test/builds/99011#01950008-bcb2-4ac8-a4c1-3442f949bd64 (of course it happens right after merging instead of in my PR)

ci: Bump agent size for cargo test

---

src/storage-controller/src/lib.rs
src/storage-types/src/dyncfgs.rs

Discussed live: easy and possibly useful.
Note that this doesn't allow disabling the creation etc. of the new shard or the writes in the Kafka sink itself, since that involves wider changes to the controller that are hard to separate out. Still, this may be useful in the case where that stuff is fine but the actual optimization itself is unsafe...
I still have a couple TODOs I'd like to get to ~soonish, but I'll split those out to a separate PR to increase the odds this one merges by the release cut.

[persist] Allow disabling the sink progress collection optimization

---

src/catalog/src/builtin.rs

Chatted with @frankmcsherry @bosconi and @SangJunBak about this, we think it should be fairly safe. If not I will cut a patch release!
Fixes https://github.com/MaterializeInc/database-issues/issues/8965

adapter: remove problematic function from `mz_cluster_replica_history`

---

test/cluster/mzcompose.py

So that we can get a signal on whether https://github.com/MaterializeInc/materialize/pull/31489 worked

cluster tests: Reenable test-github-8734

---

src/environmentd/tests/server.rs

Two occurrences yesterday, seems quite likely to keep flaking
See https://github.com/MaterializeInc/database-issues/issues/8967

cargo test: Disable two very flaky tests

---

test/pg-cdc-old-syntax/alter-table-after-source.td
test/pg-cdc/alter-source.td
test/pg-cdc/alter-table-after-source.td

See https://github.com/MaterializeInc/database-issues/issues/8883

tests: Adapt to new reality when table in Pg source was dropped

---

test/cluster/mzcompose.py

This reverts commit 5ea8129354faeea0d04601f51fcc64c30d09c2f0.
Still failing: https://buildkite.com/materialize/test/builds/99068 & https://buildkite.com/materialize/test/builds/99066

Revert "cluster tests: Reenable test-github-8734"

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/version_ancestor_overrides.py

Seen in https://buildkite.com/materialize/nightly/builds/11127

feature-benchmark: Ignore new regressions

---

test/cloudtest/test_managed_cluster.py

Seen in https://buildkite.com/materialize/nightly/builds/11143#019501e1-d6ce-478c-af92-a951f1d1da0e
Follow-up to https://github.com/MaterializeInc/materialize/pull/31399

cloudtest: Fix expected error message

---

test/cluster/mzcompose.py

From: https://github.com/MaterializeInc/database-issues/issues/8963
> I'm pretty sure I know what's happening, and don't think this is a release blocker.
>
> When connecting to Materialize/starting a new session we update the `mz_sessions` table. Previously we would block the connection startup on this write finishing, but https://github.com/MaterializeInc/materialize/pull/31309 changed this behavior where we return the connection immediately, queuing a background append, and only blocking if that session tries to query the `mz_sessions` table before the said background write has completed.
>
> Also for context, all tables has a single logical frontier, appending to one table will bump the write frontier (and thus read frontier) for all tables.
>
> I believe that the now failing …

test: bump delay for observing `mz_frontiers` from 2 to 3

---

ci/nightly/pipeline.template.yml
test/limits/mzcompose.py

Somehow creating objects has gotten much slower, I'm still investigating: https://github.com/MaterializeInc/database-issues/issues/8970
Fixes: https://github.com/MaterializeInc/database-issues/issues/8970

limits test: Bump some statement timeouts and increase agent size

---

src/adapter/src/coord.rs
src/adapter/src/coord/timeline.rs
src/environmentd/BUILD.bazel

Before, we were ignoring the "advance timelines" ticker, meaning we would not initiate group commits. Normally, as part of group commit, we call `advance_timelines`, which is what downgrades read holds.
Now, when in read-only mode, we instead call `advance_timelines` directly, and make sure that it is aware of read-only mode.
Fixes MaterializeInc/database-issues#8940

adapter: downgrade read-holds in read-only mode

---

misc/python/materialize/checks/all_checks/alter_table.py

platform-checks: Disable flaky AlterTableAddColumn check for now

---

src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/lib.rs
src/persist-client/src/read.rs

- Include more debugging info in the handle-expiry message.
- Remove a panic when attempting to downgrade the since of a handle that is expired.
https://github.com/MaterializeInc/incidents-and-escalations/issues/170
Silencing the error here might be controversial? My thinking is roughly:
- In theory: semantically, we generally treat an expired handle as one that has had its frontier advanced all the way, so this is in line with some existing behaviour.
- In practice: this should never lead to incorrectness that wasn't already possible, because extending the lease never guaranteed that it would be present for any particular future operation... just more likely. It does increase the risk that we'll hit some other panic down the line, but that should only happen in cases where this would …

[persist] Remove the "gone to sleep" panics

---

test/terraform/aws-persistent/main.tf
test/terraform/aws-temporary/main.tf
test/terraform/gcp-temporary/main.tf

Follow-up to https://github.com/MaterializeInc/materialize/pull/31452. Some testdrive tests require these clusters to be usable.
Seen failing in https://buildkite.com/materialize/nightly/builds/11143#019501e1-d68b-407e-8801-4a60b5a18f5d
Green test run: https://buildkite.com/materialize/nightly/builds/11151

terraform tests: Set default replication factors

---

Cargo.lock
src/persist/Cargo.toml
src/workspace-hack/Cargo.toml

Follow-up to https://github.com/MaterializeInc/materialize/pull/31453
Seeing build failures in the 0dt bump test: https://buildkite.com/materialize/nightly/builds/11138#019500e5-e622-409a-97d3-bfc1a23179f3
We already have many reqwest versions in our code, maybe we should not add more
This fixes the issue for me locally: Edit: Green nightly run too: https://buildkite.com/materialize/nightly/builds/11150#_
```
$ bin/mzcompose --find platform-checks down && CI_BAZEL_BUILD=1 bin/mzcompose --find platform-checks --dev run default --scenario=ZeroDowntimeBumpedVersion --check=BooleanType
==> mzcompose: test case workflow-default succeeded
```
I don't really understand the root cause though, and especially why it only happens when we bump the version and rebuild on Hetzner, and not in the normal …

build(deps): Use older version of reqwest in persist

---

misc/python/materialize/parallel_workload/parallel_workload.py

It seems that dropping objects now fails more often
Failure seen in https://buildkite.com/materialize/nightly/builds/11127#0194fcbb-11fa-4b32-884d-9f3de1b2bfbf
I'm thinking this is fallout from https://github.com/MaterializeInc/materialize/pull/31309

parallel-workload: Deal with changes in parallelism handling

---

misc/python/materialize/version_ancestor_overrides.py

See https://github.com/MaterializeInc/database-issues/issues/8972

feature-benchmark: Ignore new regression

---

src/compute/src/sink/correction_v2.rs

This commit fixes a bug in size metrics tracking for the `CorrectionV2` stage. In `consolidate_before`, we would call `stage.flush()` and if this returned no updates we would assume that the stage had been empty and immediately return without updating the metrics. However, `stage.flush()` performs a `consolidate`, which can cancel out updates, and we would miss recording these deletions in the metrics.
This fix chosen here is to perform the emptiness checking and early return before calling `stage.flush()`. I find this more obvious than to keeping the current flow and adding a second `update_metrics` to `consolidate_before`, but both would work.
Fixes https://github.com/MaterializeInc/database-issues/issues/8971

compute/correction_v2: fix stage size tracking

---

misc/python/materialize/mzcompose/__init__.py
src/compute-types/src/dyncfgs.rs
src/compute/src/compute_state.rs
src/orchestrator-process/src/lib.rs
src/ore/src/region.rs
test/testdrive/cc_cluster_sizes.td
test/testdrive/disk-feature-flag.td

Modernize the infrastructure around lgalloc. In the past, it needed to be explicitly enabled, but now it needs to be disabled and is on by default. This reflects our current setup better where we expect to have access to lgalloc if we have disk. The setting still serves as a switch to disable it in case it is needed.
Introduces a new setting `enable_lgalloc` that gates access to lgalloc as a whole. The old `enable_columnation_lgalloc` controls the behavior of `Region::new_auto` instead, which is closer to the name.

Always enable lgalloc, unless disabled

---

Cargo.lock
deny.toml
src/balancerd/Cargo.toml
src/clusterd/Cargo.toml
src/clusterd/src/lib.rs
src/environmentd/Cargo.toml
src/environmentd/src/environmentd/main.rs
src/kafka-util/Cargo.toml
src/orchestrator-process/Cargo.toml
src/persist-cli/Cargo.toml
src/persist-client/Cargo.toml
src/rocksdb/Cargo.toml

At the moment, we cannot distinguish tokio thread names in Linux because they're longer than the limit, cutting off their end. With this change, we do the same we do in environmentd, which is to supply a custom thread name function and construct the builder manually.
Updates `num_cpus` to the latest version.

Force tokio thread names to fit Linux limits

---

test/replica-isolation/mzcompose.py

The `mz_cluster::server` module has been renamed to `mz_cluster::client` in https://github.com/MaterializeInc/materialize/pull/31514, so we need to update the log filter in the replica-isolation test accordingly.

test: fix log filter in replica-isolation tests

---

src/storage-client/src/storage_collections.rs

This avoids a possible race in the storage controller, where a downgrade of our read capability can race the selection of new capabilities for a new version of the table. (More detail in a comment downthread.)
We instead switch to:
- using the frontiers of the old version directly;
- doing the frontier selection and the state update atomically while holding the lock;
...which together should avoid this particular race. 
https://github.com/MaterializeInc/database-issues/issues/8952
This bug is quite tricky to reproduce, so I'm not 100% confident that this is the issue we're seeing in CI. Happy to take suggestions for improving the tests! But also please check my logic below: that it sounds like an accurate description of the current behaviour, and that the particular interleaving of events …

[storage] Atomic alter table in the storage controller

---

src/persist/src/azure.rs
src/persist/src/location.rs

Observed these were missing while debugging.
The core issue is that the `anyhow!("context: {}", e)` formatting approach does not preserve error causes. ~`e.context("context")` just converts an error type to anyhow's error and tacks on some context, so it will preserve the chain of sources.~ Turns out azure has its own context-preserving mechanism, so I'm just using that and then converting to anyhow directly.

[persist] Preserve causal chain for azure errors

---

misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/mzcompose/__init__.py

Fixes: https://github.com/MaterializeInc/database-issues/issues/8972

ci: Fail CI when an unknown system parameter is set

---

misc/python/materialize/checks/all_checks/alter_table.py

Fixes: https://github.com/MaterializeInc/database-issues/issues/8952

platform-checks: Reenable AlterTableAddColumn

---

test/cloudtest/test_compute.py
test/cloudtest/test_disk.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/31511/
Failure seen in https://buildkite.com/materialize/nightly/builds/11196#019519fc-29b8-48ac-87db-4cb4c19b0758

cloudtest: Fix test_disk_label

---

ci/nightly/pipeline.template.yml
test/cluster/mzcompose.py

Since https://github.com/MaterializeInc/incidents-and-escalations/issues/72 is closed
Noticed in https://buildkite.com/materialize/nightly/builds/11203#01951ba1-ed91-4a34-8d84-43ea6d2075dd

ci: Reenable incident-70 test

---

src/storage/src/storage_state.rs
test/0dt/mzcompose.py

This makes it so that status updates from the latest deployment, for example when coming out of read-only mode, sort last in mz_source/sink_status_history, so get surfaced as the latest status in mz_source/sink_statuses.
This fixes (or makes less likely) a bug where a failing/stalled source/sink in the old deployment would crowd out the running status of objects in the new deployment.
This fix work, but doesn't feel ideal. A problem is that the raw status collections are append-only collections, so `envd` will simply append status updates to the end. One could argue that the smarts should be in `envd`/the controller. But ultimately, it would also have to append a status update that "trumps" the earlier updates, so would do the same thing that we're achieving with this change.
Fixes …

storage: when envd reconnects, report current status at latest timestamp

---

test/balancerd/mzcompose.py

Seen in https://buildkite.com/materialize/nightly/builds/11203#01951ba1-ee2a-4483-9b01-d20a385ba232

balancerd test: Accept new error message too

---

src/adapter/src/coord/sequencer/inner.rs
src/sql/src/plan/statement/ddl.rs

Fixes MaterializeInc/database-issues#8973
@def- This might not fix the test, but it would show what type of source is trying to be created. And we don't panic anymore but report a regular error back to the client.

adapter: report error instead of panic'ing when checking for multi-replica sources

---

src/orchestrator-kubernetes/src/lib.rs

https://github.com/MaterializeInc/cloud/issues/10806
orchestratord already handles this correctly

use the last path component for finding the image name

---

misc/helm-charts/operator/README.md
misc/helm-charts/operator/values.yaml

We've discussed that we want to halve the size of `mz_catalog_server` https://github.com/MaterializeInc/cloud/issues/10285. I've tested this on local-kind with few "realistic" dataflows https://www.notion.so/materialize/DDL-for-Mocking-Realistic-Use-cases-19e13f48d37b8092ab3fd66cea453b05 and the Console seems to be working well. Planning to stress test with this new size too when scraping the catalog using the debug tool. Also added a section in our docs https://github.com/MaterializeInc/materialize/pull/31545 on how to actually increase the cluster size if push comes to shove.

Change catalog server default size to 25cc

---

test/sqllogictest/introspection/attribution_sources.slt

Follow-up to https://github.com/MaterializeInc/materialize/pull/31473
Failure seen in [SQL logic tests 5](https://buildkite.com/materialize/nightly/builds/11217#019520c5-52dd-4290-a641-24359ab41d57)

slt: Fix query in attribution_sources.slt

---

src/adapter/src/catalog.rs
src/adapter/src/coord/timestamp_selection.rs
src/compute-types/src/explain/text.rs
src/expr-parser/src/catalog.rs
src/expr-test-util/src/lib.rs
src/expr/src/scalar/func/impls/string.rs
src/repr/src/explain.rs
src/sql/src/func.rs
src/sql/src/plan/hir.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/typeconv.rs
src/sql/src/pure/postgres.rs
src/transform/src/typecheck.rs
test/sqllogictest/array_fill.slt
test/sqllogictest/char.slt
test/sqllogictest/cockroach/aggregate.slt
test/sqllogictest/github-5536.slt
test/sqllogictest/map.slt
test/sqllogictest/tpch_create_materialized_view.slt
test/sqllogictest/tpch_select.slt
test/sqllogictest/type-promotion.slt
test/testdrive/char-varchar-distinct.td

Char and Varchar can involve a length. Additionally, the cast functions `text_to_char` and `text_to_varchar` involve a `fail_on_len` option. We were not printing these extra fields in EXPLAIN and in error msgs, causing confusion in various situations, e.g.,
https://github.com/MaterializeInc/database-issues/issues/8807#issuecomment-2518662460
https://github.com/MaterializeInc/database-issues/issues/1291
https://github.com/MaterializeInc/materialize/pull/27029
The first commit attends to `text_to_varchar` and `text_to_char`.
The second commit attends to the type names, changing them in EXPLAIN, error msgs, and `pg_typeof`.
The third commit reverts the change for `pg_typeof`, to keep Postgres compatibility.
Nightly: https://buildkite.com/materialize/nightly/builds/11207
* This PR fixes a …

Fix EXPLAIN around Char and Varchar

---

ci/nightly/pipeline.template.yml
src/persist-cli/src/maelstrom/txn_list_append_single.rs

- We assert that since < upper-1 on the next trip through the loop, but if we don't obtain the two frontiers atomically, so it's possible for the since to be larger than the write frontier if it takes a while to fetch. Now we fetch them in the other order.
- `compare_and_downgrade_since` is not _actually_ idempotent! If we're trying to compare and downgrade changing the token from X to Y, it's possible to succeed, changing the token to Y, but fail with some indeterminate error... and then a retry will fail since the token is already Y. This doesn't actually affect our real-life usage, but it does affect the particular expectation in `advance_since`. Now we check whether the since has advanced unexpectedly no matter what the latest version of the opaque was.
Fixes: …

[persist] Fix up the Persist malestrom test

---

ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/pre-exit
ci/test/pipeline.template.yml
test/terraform/aws-persistent/main.tf
test/terraform/aws-temporary/main.tf
test/terraform/gcp-temporary/main.tf
test/terraform/mzcompose.py

terraform test: New version with local helm chart support

---

doc/user/content/releases/v0.132.md
doc/user/content/releases/v0.133.md

Fixes the docs for v0.132 and v0.133
Fix docs

docs: Update release docs to callout recently released versions

---

misc/python/materialize/release/cut_self_managed_release.py

Edit: Now only sets the tag:
Tag for self-managed code: `self-managed-v25.1.0` (before: none)

self-managed: Add tags

---

src/repr/src/global_id.rs

Our documentation for `GlobalId` implied that one could rely on the `Ord` implementation for dependence order, but this is neither part of `formalism.md` nor accurate about the current codebase. Correct the documentation.

Clarify properties of GlobalIds

---

ci/nightly/pipeline.template.yml

Follow-up to https://github.com/MaterializeInc/materialize/pull/31513
Noticed in https://buildkite.com/materialize/nightly/builds/11226#019525eb-dd0e-4855-96e2-14ccb54528cc

ci: Reenable copy to s3 tests

---

ci/nightly/pipeline.template.yml

Follow-up to https://github.com/MaterializeInc/materialize/pull/31541
Seen timing out in https://buildkite.com/materialize/nightly/builds/11226#019525eb-dd5b-44e5-aa4f-a1bc602fecc8

ci: Bump timeouts for Maelstrom tests

---

ci/nightly/pipeline.template.yml

Went OoM in https://buildkite.com/materialize/nightly/builds/11223#019524a5-b21c-45bd-8927-83bd6916f3de
We still have other Azurite-based tests, but because of Azurite's low performance and https://github.com/MaterializeInc/database-issues/issues/8892 we can't use it for as many scenarios as initially hoped
An alternative would be to increase the agent size further for these, but I'm not sure if there is enough value to justify.

ci: Disable some Azurite-based tests

---

Cargo.lock
src/self-managed-debug/Cargo.toml

Follow-up to https://github.com/MaterializeInc/materialize/pull/31282
Seen in https://buildkite.com/materialize/nightly/builds/11226#019525eb-dd0e-4f66-8213-4e91673256b7

build: Remove unused tabled dependency in self-managed-debug

---

ci/release-qualification/pipeline.template.yml

Failure seen in https://buildkite.com/materialize/release-qualification/builds/748#01952cb8-b4e3-467e-8aea-cfc77dbf325e

ci: Bump parallelism for platform-checks in release qualification

---

src/storage/src/upsert.rs

It cannot be used when there are concurrent ingestion pipelines. And we have 0dt for sources enabled in production now, which does this. And want to roll out multi-replica source clusters next, which also needs this.

storage: disable classic UPSERT operator

---

bin/bump-version

To prevent lints from failing
See https://materializeinc.slack.com/archives/CTESPM7FU/p1740412689912119 for context

bump-version: Make sure correct helm-docs version is used

---

src/catalog/src/durable/persist.rs
src/expr/src/explain/text.rs
src/ore/src/assert.rs
src/persist-client/src/batch.rs
src/repr/src/explain.rs
src/sql/src/plan/statement/dml.rs

Recently, https://github.com/MaterializeInc/materialize/pull/31309 added a function for checking whether soft assertions are enabled, and called it in one place. There are many other places where we are doing the same check, so this PR modifies these places to also call this function.
I also added `#[inline(always)]` to `soft_assertions_enabled()` to avoid accidentally regressing performance by switching to function calls.

Refactor soft assertion enablement checks

---

bin/bump-version

bump-version: Fix helm-docs version

---

src/adapter/src/optimize/view.rs
src/catalog/src/memory/objects.rs
test/sqllogictest/explain/locally_optimized_plan.slt
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/explain/raw_plan_as_text.slt
test/sqllogictest/explain/view.slt

The first commit fixes `EXPLAIN LOCALLY OPTIMIZED PLAN` (https://github.com/MaterializeInc/database-issues/issues/8985).
The second commit renames `explain/view.slt` to `explain/locally_optimized_plan.slt`, because now the file is explaining not just views. Also, it moves out the one `EXPLAIN RAW PLAN` statement from it to `explain/raw_plan_as_text.slt`.
The third commit is somewhat unrelated: just adds a test for `EXPLAIN` without an explicit stage or format, so that we test the default. (Currently defaults to `EXPLAIN OPTIMIZED PLAN AS TEXT FOR`.) This is to prevent issues like the one fixed in https://github.com/MaterializeInc/materialize/pull/31482 (cc @def-, @mgree)
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/8985

Fix `EXPLAIN` for constant views

---

test/canary-environment/models/loadgen/schema.yml

Related to https://materializeinc.slack.com/archives/C08AENAP691/p1740405815492579

canary-environment: index removed

---

misc/python/materialize/parallel_workload/action.py

From our docs:
> When using the Avro format with a schema registry, the generated Avro schema for the new relation must be compatible with the previously published schema. If that’s not the case, the ALTER SINK command will succeed, but the subsequent execution of the sink will result in errors and will not be able to make progress.
And the avro docs:
> [...] if both are records: the ordering of fields may be different: fields are matched by name.
So to check compatibility, we should check by name instead of by order.
Fixes: https://github.com/MaterializeInc/database-issues/issues/8445
I've opted out JSON from any checks, since I don't think any rules are enforced for that type of sink, and that should help get our test coverage up.

[storage] Fix and re-enable alter sink tests

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/persist-client/src/batch.rs
src/persist-client/src/cfg.rs
src/persist-client/src/internal/state.rs
src/persist/src/cfg.rs
src/persist/src/s3.rs

This PR removes a few dyncfgs/LaunchDarkly flags that have been enabled for multiple months and are no longer needed.
Code cleanup

persist: Cleanup some long enabled LD flags

---

misc/python/materialize/checks/all_checks/sink.py

Failure seen in https://buildkite.com/materialize/nightly/builds/11269#01953fab-4258-4a58-a258-8b4c79fecfa7
@petrosagg @bkirwi  I feel like there should be a better way to check that we have cut over, just sleeping longer and longer will make our tests run slow, and still flaky.

platform-checks: Bump sleep duration in ALTER SINK ... SET FROM

---

src/storage-types/src/dyncfgs.rs

This matches the default we now have in LD, plus the current upsert code is hardwired to use feedback upsert.

storage: set default of storage_use_continual_feedback_upsert to true

---

src/expr/src/relation.rs
src/sql/src/func.rs
src/sql/src/plan/hir.rs
test/sqllogictest/explain/raw_plan_as_text.slt

Does the same for HIR as what https://github.com/MaterializeInc/materialize/pull/31402 did for MIR...
First commit just fixes the bug and adds tests, while the second commit is a minor refactoring to shorten the code and make it more uniform between HIR and MIR, and extend a comment to mention HIR.

Fix HIR explain's `count(*)` handling

---

misc/python/materialize/checks/all_checks/sink.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/31625, as Petros suggested

platform-checks: Better ALTER SINK testing

---

doc/developer/mzcompose.md
doc/developer/platform-checks.md
doc/developer/zippy.md
misc/python/materialize/checks/all_checks/load_generator.py
misc/python/materialize/zippy/__init__.py
misc/www/index.html

Follow-up to https://github.com/MaterializeInc/materialize/pull/31227

platform-checks: Add basic check for load generator with multiple replicas

---

misc/python/materialize/cli/orchestratord.py

Add support for helm values files to bin/orchestratord.
Makes it easier to run orchestratord without needing to manually edit the helm values.yaml file. Instead, you can define the overrides in a separate yaml file.

Add support for helm values files to bin/orchestratord

---

ci/nightly/pipeline.template.yml

Flake seen in https://buildkite.com/materialize/nightly/builds/11274
Green run: https://buildkite.com/materialize/nightly/builds/11311

0dt test: Switch to dedicated CPUs

---

src/expr/src/explain/text.rs
src/transform/src/analysis.rs
src/transform/src/analysis/equivalences.rs
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/explain/optimized_plan_as_text_redacted.slt

Fixes https://github.com/MaterializeInc/database-issues/issues/8987, by wiring up the humanization infrastructure to the printing of the `Equivalences` analysis. (Besides fixing the redaction issue, the humanization also adds column names when available.)
The first commit is a minor refactoring, and the second commit is the actual fix.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/8987

Fix EXPLAIN's humanization/redaction of the equivalences analysis

---

.github/dependabot.yml

Too many dependencies, timeout seems to be fixed to 55 min: https://github.com/MaterializeInc/materialize/actions/runs/13487319380/job/37680155878

dependabot: Don't group cargo updates for /

---

ci/test/lint-slow.sh
misc/python/materialize/zippy/scenarios.py

Failure seen in https://buildkite.com/materialize/deploy/builds/17842
It seems to be a pydoc bug, missing imports which aren't even required in the file
By running pydoc in the lints we will prevent this from happening in the future.

ci: Fix pydoc and make sure it doesn't break again

---

ci/builder/requirements.txt

Thanks to https://github.com/MaterializeInc/materialize/pull/31672 we won't be able to merge this dependabot upgrade in the future anymore
Seen failing in https://buildkite.com/materialize/test/builds/99761

build(deps): Downgrade pydantic

---

ci/builder/requirements.txt
ci/nightly/pipeline.template.yml
test/data-ingest/mzcompose.py

See https://github.com/MaterializeInc/database-issues/issues/8990

data ingest test: Use one replica for now, but remind us to enable more in the future

---

test/cloudtest/test_privatelink_connection.py

Seen flaking in https://buildkite.com/materialize/nightly/builds/11319#0195469f-7f0b-4291-9360-ad92e541c16a

cloudtest: Unflake privatelink test

---

Cargo.lock
src/compute-types/src/dyncfgs.rs
src/compute/Cargo.toml
src/compute/src/compute_state.rs
src/metrics/Cargo.toml
src/ore/Cargo.toml
src/timely-util/Cargo.toml

Updates the lgalloc dependency to 0.5, and exposes lgalloc's new parameters
as dyncfgs. Specifically, it allows us to set the local_buffer_bytes and
the file_growth_dampener. The first is the size of the per-thread per-size-
class buffer, the second is a dampener controlling how files per size class
grow as we need more capacity.
The default values correspond to lgalloc's own defaults.

Update lgalloc to 0.5, expose new parameters

---

src/adapter/src/coord/sequencer/inner/create_materialized_view.rs

We also need to fix the reason for this panic, but a bug in our SQL round-tripping should not cause environmentd to panic.
Fix a known panic

fix: return an `AdapterError::Internal` instead of panicking

---

src/regexp/src/lib.rs
src/timely-util/src/reclock.rs

Seen in https://buildkite.com/materialize/nightly/builds/11319#019544d1-81e2-4fcb-bc05-c65190632661

miri test: Disable two unit tests because of timeouts

---

test/terraform/aws-persistent/main.tf
test/terraform/aws-temporary/main.tf
test/terraform/azure-temporary/main.tf
test/terraform/gcp-temporary/main.tf
test/terraform/mzcompose.py

ci: Bump all terraform versions

---

test/testdrive-old-kafka-src-syntax/kafka-sink-multi-partition.td

Follow-up to https://github.com/MaterializeInc/materialize/pull/31463
Failed in https://buildkite.com/materialize/nightly/builds/11337#019549f8-14e1-4c1c-a3cb-750331f8518f
My interpretation is that the PR was merged too late and we were already on version 0.134.0-dev by that time, so it's expected for the test not to work when migrating from an older version. @martykulma Does this track?

testdrive: Bump version for kafka-sink-multi-partition.td

---

doc/user/content/installation/install-on-aws.md
doc/user/content/installation/install-on-azure.md
doc/user/content/installation/install-on-gcp.md
doc/user/content/installation/install-on-local-kind.md
doc/user/content/installation/install-on-local-minikube.md

Noted by Marty in https://materializeinc.slack.com/archives/C07PN7KSB0T/p1740756550623179?thread_ts=1740756449.640289&cid=C07PN7KSB0T

docs: Get errors in kubectl port-forward loop

---

src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select
test/sqllogictest/arrays.slt
test/sqllogictest/list.slt

This is an alternative approach for solving the problem mentioned in https://github.com/MaterializeInc/materialize/pull/31696. The advantages of this approach are:
- Roundtrips through the parser even if the cast is not to a list or array type. [Details.](https://github.com/MaterializeInc/materialize/pull/31696/files#r1975213111)
- Does not break the abstraction of `AstInfo::DataType`. ([Breaking into `AstInfo::DataType` might be non-trivial for arrays.](https://github.com/MaterializeInc/materialize/pull/31696/files#r1975238697))
- Future-proof against the same problem occurring again if we add subscripting for more types at some point.
- ([The same approach can be used to solve the `needs_wrap` roundtripping problem](https://github.com/MaterializeInc/materialize/pull/31696/files#r19753212 …

sql: Wrap subscripted expression in parens when it ends with a type name

---

misc/python/materialize/cli/run.py
misc/python/materialize/mzcompose/services/sql_logic_test.py

Sqllogictest uses the temp directory to create the scratch directories. On
some Linux distributions, it's mounted as a tmpfs file system, which
apparently isn't 100% compatible with lgalloc. Until lgalloc supports it,
disable lgalloc in sqllogictest.
Fixes MaterializeInc/database-issues#8989

Disable lgalloc in sqllogictest

---

Cargo.toml

This doesn't seem to increase build times much, but comes with a dramatic
speed up of sqllogictest:
main:
```
bin/sqllogictest --build-only
3677.11s user 382.87s system 1402% cpu 4:49.48 total
bin/sqllogictest test/sqllogictest/introspection
1088.87s user 97.06s system 421% cpu 4:41.33 total
```
this:
```
bin/sqllogictest --build-only
3906.03s user 390.20s system 1444% cpu 4:57.37 total
bin/sqllogictest test/sqllogictest/introspection
206.07s user 5.38s system 260% cpu 1:21.13 total
```

Optimize some local crates

---

src/clusterd/src/lib.rs
src/environmentd/src/environmentd/main.rs
src/ore/src/metrics.rs
src/persist-client/src/async_runtime.rs
src/persist-client/src/cache.rs
src/persist-client/src/cli/admin.rs
src/persist-client/src/cli/inspect.rs

Specifically:
- Capturing for both the "main" and isolated Persist runtimes. (Some other binaries use Tokio, but I think we only care for `envd` and `clusterd`, so I have left the others alone.)
- Capturing only metrics that boil down to a single u64, partly for convenience and partly to limit cardinality. This excludes a bunch of per-worker metrics and some histograms, both of which are possible to support with some slightly more invasive code. (Let me know if [anything I'm missing](https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html) seems worth the effort?)
https://github.com/MaterializeInc/incidents-and-escalations/issues/194
This crate exists: https://crates.io/crates/tokio-metrics-collector
This didn't seem substantial enough to warrant a dependency, and I'm unsure …

Add a bunch of tokio metrics to prometheus

---

test/terraform/azure-temporary/main.tf
test/terraform/mzcompose.py

Might fix https://github.com/MaterializeInc/database-issues/issues/8998

terraform: Use new version for Azure

---

test/terraform/azure-temporary/main.tf

Thanks @bobbyiliev for fixing and tagging a new version so quickly

terraform: Switch back to tagged version for Azure

---

doc/developer/fast-compiles.md

Otherwise compilation can fail, see https://materializeinc.slack.com/archives/CM7ATT65S/p1740776443473949

dev docs: Update RUSTFLAGS with --cfg tokio_unstable

---

ci/release-qualification/pipeline.template.yml

Seen failing in https://buildkite.com/materialize/release-qualification/builds/753
Locally it's fine, so this is my best guess
Green run: https://buildkite.com/materialize/release-qualification/builds/754

ci: Bump parallelism for Checks + multiple backups/restores

---

ci/nightly/pipeline.template.yml

Seen flaking in https://buildkite.com/materialize/nightly/builds/11346
Azurite is slower and uses more memory than Minio
Green run: https://buildkite.com/materialize/nightly/builds/11350

ci: Bump two azure test parallelisms

---

src/storage/src/source/reclock/compat.rs
src/storage/src/storage_state.rs

As the comment describes, this is a race condition that is expected to happen and it's better to suspend rather than bring down the whole cluster, which causes pain for customers/the oncall.
@def- This fixes the panic of incident-360
Fixes https://github.com/MaterializeInc/incidents-and-escalations/issues/173
Fixes https://github.com/MaterializeInc/database-issues/issues/8936

storage: in remap, when since is empty, suspend instead of panic'ing

---

Cargo.lock
src/cloud-resources/Cargo.toml
src/orchestrator-kubernetes/Cargo.toml
src/orchestratord/Cargo.toml
src/self-managed-debug/Cargo.toml
src/workspace-hack/Cargo.toml

Bump k8s-controller to 0.4.0 and k8s-openapi feature to v1_30
We're running Kubernetes 1.30 in production now, and 1.29 leaves support in a few days.
Version 0.4.0 of k8s-controller no longer depends directly on k8s-openapi, so allows us to independently update the k8s-openapi feature.

Bump k8s-controller to 0.4.0 and k8s-openapi feature to v1_30

---

misc/python/materialize/checks/all_checks/sink.py

Seen failing in https://buildkite.com/materialize/nightly/builds/11337#019549f8-14ed-4564-97cd-25993208f2be
@petrosagg Maybe this approach is not perfect somehow?

platform-checks: Try waiting longer in alter sink tests

---

src/ore/src/metrics.rs

Make local dev a little easier, if a bit less representative.

[core] Conditionally compile unstable metrics

---

about.toml

It was already in deny.toml since https://github.com/MaterializeInc/materialize/pull/30780 but forgotten in about.toml. This causes the test and deploy pipeline to fail:
https://buildkite.com/materialize/test/builds/100138#01955e7c-99ef-46a6-a33a-28d9894fadc5
https://buildkite.com/materialize/deploy/builds/17944#01955e97-2e2a-44bd-a297-d5d445c7da4f

deploy: Add Unicode-3.0 license to about.toml too

---

ci/builder/Dockerfile

Hopefully fixes new TOML parse error: https://buildkite.com/materialize/test/builds/100140#01955fc2-e0ca-46c1-a204-77de86e0d01c
```
'Unicode-3.0' is not a valid SPDX licensee: Unicode-3.0
```
Edit: Verified locally that the old version has this bug and the new version has fixed it

ci-builder: Bump cargo-about version

---

WORKSPACE
src/compute/BUILD.bazel
src/compute/Cargo.toml
src/transform/BUILD.bazel
src/transform/Cargo.toml

Replicate changes from https://github.com/MaterializeInc/materialize/pull/31707 to the Bazel build
Better builds

build: apply optimizations to local crates in Bazel

---

src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs

NOTE: This is now a whole bunch of other cleanups that were enabled/or made feasible by this initial change to eagerly clean out state and update builtin collections 
Before this change, we had a more sequentialized/blocking protocol for
dropping sources (and other collections):
1. envd receives DDL that drops source
2. envd releases read holds and sends AllowCompaction to clusterd
3. clusterd drops source and sends back a DroppedId message
4. envd cleans up it's collection state and updates builtin collections:
- updating mz_storage_shards (the global id -> shard id mapping)
- updating source/sink status to "dropped"
- removing statistics tracking
Especially the transition between 3. and 4. can block a while if a
cluster is unresponsive.
Plus, in some situations we don't get DroppedId …

storage: when dropping objects, eagerly clean up state and update builtins

---

src/compute/src/command_channel.rs
src/compute/src/compute_state.rs
src/compute/src/lib.rs
src/compute/src/server.rs

This PR makes the compute workers reuse their broadcast command channels across client reconnects, rather than creating a new ones for each connection. Doing so avoids bugs caused by workers rendering the channel dataflow with different operator IDs upon reconnecting multiple times.
The change only applies to the compute cluster, so the `ClusterClient`, which is shared between both compute and storage, still retains its previous behavior of using a new set of channels for each client connection. To interface between the `ClusterClient` and the compute workers, a "channel adapter" is introduced to bridge between the two.
Now that compute's internal command channel isn't recreated for each client connection anymore, we need something else to distinguish client connections and know when a …

compute: persistent worker command channel

---

test/limits/mzcompose.py

Seen failing in https://buildkite.com/materialize/release-qualification/builds/753#01954d6f-70b8-4b8e-be05-a8b9c0e22cfe
> 1010:1: error: db error: FATAL: creating connection would violate max_connections limit (desired: 1005, limit: 1004, current: 1004)

limits test: Bump max_connections for Connections scenario

---

src/storage-client/src/metrics.rs

This metric is unused as nobody writes it.
Looks like it was originally added to track something about the on-startup cleanup of the statement log, but we are not truncating the statement log nowadays.
* This PR removes dead code code.

storage: remove mz_storage_startup_prepared_statements_kept metric

---

misc/python/materialize/mzcompose/__init__.py
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/sequencer/inner/peek.rs
src/adapter/src/explain/mir.rs
src/adapter/src/optimize/materialized_view.rs
src/compute-client/src/as_of_selection.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/protocol/history.rs
src/compute-types/src/dataflows.proto
src/compute-types/src/dataflows.rs
src/compute-types/src/dyncfgs.rs
src/compute-types/src/explain.rs
src/compute-types/src/plan.rs
src/compute/src/render.rs
src/compute/src/render/continual_task.rs
src/compute/src/render/sinks.rs
src/compute/src/sink/copy_to_s3_oneshot.rs
src/compute/src/sink/materialized_view.rs
src/compute/src/sink/subscribe.rs
src/timely-util/src/probe.rs
src/transform/src/dataflow.rs
test/bounded-memory/mzcompose.py

Logical back pressure for dataflows.
This PR implements logical backpressure for dataflows. Logical backpressure is a mechanism that holds back time (not data), and reveals time stepwise as the downstream dataflow makes progress.
The implementation is conservative in what times it holds back. We cannot hold back all times because joins release resources as time ticks forward, and holding back time longer than necessary can cause regressions against current state. For this reason, we only hold back times until the input's write frontier (upper) at the time of creating the dataflow, but not beyond. This will allow us to apply logical backpressure while a dataflow is catching up, but it will not hold back any times in steady-state.
It is important that we do not hold back times in …

Logical per-dataflow backpressure

---

src/storage-controller/src/history.rs
src/storage-controller/src/lib.rs
test/cluster/mzcompose.py

This PR makes the controller drop its collection state for non-primary tables and MVs, rather than leaking it. This may or may not fix all such collection state leaks.
Also adds a test for storage controller metrics and fixes two other bugs around command history metrics tracking found by this test.
Fixes https://github.com/MaterializeInc/database-issues/issues/8984

storage-controller: leak less collection state

---

src/frontegg-auth/src/client/tokens.rs

Trying to debug some high latencies with our auth provider Frontegg. This PR just adds a bit of debug logging (off by default) to report the latencies of requests with the "frontegg-trace-id" header.
Debug auth latencies

adapter: add some debug logging for requests to get their latency

---

.config/nextest.toml

Seen failing in https://buildkite.com/materialize/test/builds/100257#01956d28-094e-4394-8930-92ac62870537

cargo test: Bump timeout for all_datums_produce_valid_stats

---

src/mysql-util/src/aws_rds.rs

Seen failing in https://buildkite.com/materialize/nightly/builds/11400#01956e04-8161-495a-9d19-dfb48444618a
Follow-up to https://github.com/MaterializeInc/materialize/pull/31689

miri test: Disable aws_rd::test::test_signature

---

src/environmentd/tests/testdata/http/post
src/environmentd/tests/testdata/http/ws
src/sql-parser/src/ast/defs/expr.rs
src/sql-parser/src/lib.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/sqlparser_common.rs
src/sql-parser/tests/testdata/select
src/sql-pretty/src/doc.rs
test/sqllogictest/cast.slt

This is a follow-up to https://github.com/MaterializeInc/materialize/pull/31705. When working on that PR, we noticed that if we fix precedence issues by adding parenthesis during the _printing_ of the AST, then the problem is that the AST won't roundtrip in parser tests. Therefore that PR fixed a precedence issue during AST parsing instead of printing. However, even before that PR, the AST printing already had an earlier precedence fix during printing. This was not causing a problem so far only because we hadn't had a parser test for it. So this PR moves that precedence fix also to the parsing, and adds a parser test for it. This is in the second commit.
The first commit is a related refactoring in the parser tests: When there was a parser roundtrip problem in tests, it would often …

[parser] Refactor the handling of complex expressions in casts

---

ci/nightly/pipeline.template.yml
test/0dt/mzcompose.py

Seen in https://buildkite.com/materialize/nightly/builds/11391#01956ba2-01d0-4f24-a2aa-2c11f8420c71
@aljoscha I'm not really happy with just bumping this. Do you have any idea what's making this flaky recently?
According to https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%2C%7B%22id%22%3A%22content%22%2C%22value%22%3A%22kafka-source-rehydration%3A%22%7D%5D there were 6 failures since March 4.

0dt test: Bump timeout for Kafka source rehydration

---

test/sqllogictest/introspection/attribution_sources.slt

Without the `reset-server` the introspection sources queried in this file show different things based on which slt files we run before it.

[tests] Add `reset-server` to `attribution_sources.slt`

---

Cargo.lock
src/workspace-hack/Cargo.toml

Failure seen in https://buildkite.com/materialize/security/builds/1433#0195711f-93aa-48db-80ad-5a0545ac899b
Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0009

build(deps): bump ring from v0.17.11 to v0.17.13

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml

Since https://github.com/MaterializeInc/database-issues/issues/7046 is fixed
Test runs: https://buildkite.com/materialize/nightly/builds/11419 & https://buildkite.com/materialize/release-qualification/builds/756

ci: More joins in SQLsmith

---

test/testdrive/avro-resolution-no-publish-writer.td

See https://github.com/MaterializeInc/database-issues/issues/9049, currently main is very red because of this.

testdrive: Temporarily disable test fragment in avro resolution

---

Cargo.lock
deny.toml

Seen in https://buildkite.com/materialize/nightly/builds/11424#0195732a-dad9-49e5-89df-c8125d121f01

cargo deny: Ignore recent RUSTSEC advisories

---

src/persist-client/src/cfg.rs
src/persist-client/src/fetch.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/write.rs
src/persist-types/src/lib.rs

The "tricky part" is that our append API accepts multiple batches, but we need to generate a new part (or set of parts) that contain a subset of the data from all of them, and has a lifecycle that many not match any of them. 
I considered moving the batch-merging to the caller when it is required, but that requires some changes to the sink logic that increased the blast radius of this change. (Probably still a good idea, but harder to timebox.)
We instead deal with this by creating a new batch with a lifeycle bound by the individual compare-and-append call, stuffing all our inline parts in there, and flushing that batch instead. 
Partially addresses: https://github.com/MaterializeInc/incidents-and-escalations/issues/191
Discussed here: …

[persist] Flush inline parts to a single blob when possible

---

doc/user/content/ingest-data/postgres/amazon-aurora.md

Adding a small note about a known issue with Aurora PostgreSQL 16.1 that affects logical replication:
> https://repost.aws/questions/QU4RXUrLNQS_2oSwV34pmwww/error-could-not-map-filenumber-after-aurora-upgrade-to-16-1
I've wrapped this in a warning tag, but I'm open to suggestions if we should use a different formatting approach or tag type for this information.

doc: add note about Aurora PostgreSQL 16.1 logical replication bug

---

Cargo.lock
src/self-managed-debug/Cargo.toml
src/self-managed-debug/src/k8s_resource_dumper.rs
src/self-managed-debug/src/main.rs
src/self-managed-debug/src/system_catalog_dumper.rs

- Add `system_catalog_dumper.rs` module for internal SQL port forwarding
- Update `Cargo.toml` to include `tokio-postgres`
- Modify `main.rs` to include new command-line arguments and initial port forwarding call
- Implement `spawn_internal_sql_port_forwarding_process` function for Kubernetes port forwarding
TODO: Spawn tasks to scrape the catalog using tokio-postgres
Part of https://github.com/MaterializeInc/database-issues/issues/8908

self-managed-debug: Add port forwarding functionality

---

src/catalog/src/builtin.rs

Our built in view for `mz_dataflow_operator_reachability_per_worker` had a join condition in a `CASE` statement. By pulling the equivalence out of the case statement, and making it equate a value that is a `CASE` statement, the join planner can recognize it as an equijoin.
As a result, queries to `mz_dataflow_operator_reachability_per_worker` and derived views take substantially less time (from minutes to seconds).
Issue https://github.com/MaterializeInc/database-issues/issues/9055 describes automating this transformation.

Rework `mz_dataflow_operator_reachability_per_worker` join condition to be more clearly an equivalence

---

src/storage/src/source/source_reader_pipeline.rs
test/testdrive/frontier-rounding.td

This PR fixes an oversight where the `probe::Ticker` that produces upstream probe timestamps rounded to seconds wasn't used for synthesized probes, so frontiers of loadgens wouldn't tick at second boundaries.

storage: round synthesized probe timestamps

---

src/expr/src/scalar/func/impls/uint64.rs

Our `uint2` and `uint4` types convert to `numeric` with a method that has their names in it, but our `uint8` type names its conversion `bigint_to_numeric`, which seems wrong. It may be for a reason, but putting this up to get ahead of the case that there is not a reason. The reverse cast is already named `numeric_to_uint8` so .. probably just a glitch.

Change `CastUint64ToNumeric` `Display` impl to track other unsigned types

---

src/expr/src/scalar.rs
test/sqllogictest/filter-pushdown.slt

When we have an expression `IF <cond> THEN e1 ELSE e2`, where `e1` and `e2` are the same operator except for one argument (e.g. the same unary operator, or the same binary operator and one input matches), we can push the condition into the non-matching branch. We can actually do this more generally, always pushing the condition down when the operators match, but it's less certainly a win in those cases.
One case that the conservative approach will miss is `IF <cond> THEN a = b ELSE c = d`. This could be planned as
```
(IF <cond> THEN a ELSE c) = (IF <cond> THEN b ELSE d)
```
which presents as an equivalence, for join purposes, in a way that the `IF`-wrapped expression does not.
This is equivalent to hoisting some logic out of the `If`, though it is logic evaluated in both branches, which …

Push `MSE::If` into expressions

---

src/storage-controller/src/history.rs

We never set the `reduced_count` to the last reduced length, causing us to
reduce the storage command history every time we'd push a command to it.
The fix is simple: set the reduced count at the end of the reduce function.
It's hard to measure the impact of this because we limit the number of storage objects to a low two-digit (base 10) number. In local tests, this problem caused environmentd's coordinator thread to spend more than half its time in reducing the storage history.
Related: MaterializeInc/incidents-and-escalations#211

Set reduced_count in storage command history

---

src/storage-types/src/dyncfgs.rs
src/storage/src/storage_state.rs

Similarly to what compute has been doing for a while, introduce a
maintenance interval in the storage server to rate limit specific tasks.
At the moment, this only covers reporting frontiers to the controller. The
downside is that we might delay reporting frontier updates by the
maintenance interval.
At the moment, the maintenance interval is set to 10ms, the same as used by
compute. The largest expected frontier reporting regression is thus 10ms.
Related: https://github.com/MaterializeInc/incidents-and-escalations/issues/211

Maintenance interval to rate-limit expensive tasks

---

src/storage-client/src/storage_collections.rs
src/storage/src/render/sources.rs
src/storage/src/source/generator.rs
src/storage/src/source/generator/key_value.rs
src/storage/src/source/kafka.rs
src/storage/src/source/mysql.rs
src/storage/src/source/postgres.rs
src/storage/src/source/source_reader_pipeline.rs
src/storage/src/source/types.rs

Addresses some performance issues observed in local testing and generally
good hygiene. Cloning `RawSourceCreatingConfig` is potentially expensive
because it sits on a lot of data and collections. Both cloning and dropping
the data costs time.
Observed via #31805.

Clone less

---

Cargo.toml
misc/python/materialize/cli/gen-lints.py
misc/wasm/Cargo.toml
src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/timeline.rs
src/adapter/src/optimize.rs
src/adapter/src/session.rs
src/catalog/src/durable/initialize.rs
src/catalog/tests/debug.rs
src/expr-test-util/src/lib.rs
src/frontegg-mock/src/handlers/user.rs
src/lsp-server/tests/test.rs
src/mz/src/config_file.rs
src/persist-client/src/rpc.rs
src/prof-http/src/lib.rs
src/secrets/src/cache.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/storage/src/source/mysql/replication.rs
src/storage/src/source/mysql/snapshot.rs

This PR enables a new clip lint, [borrow_interior_mutable_const](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_interior_mutable_const). This lint would have been useful in finding https://github.com/MaterializeInc/materialize/pull/31594 before it was merged, rather than only after the canary deploy.
This PR also fixes a bunch of other likely wrong usages of `const` (all only performance-impacting afaict), as well as a bunch of other clippy errors one gets on the recent Rust version.

*: enable borrow_interior_mutable_const clippy lint

---

src/catalog/src/builtin.rs
test/sqllogictest/distinct_arrangements.slt

We use this query in the Console to power the Environment Overview page and cluster replica graphs for the 14 day time period.
Sibling PR to https://github.com/MaterializeInc/console/pull/3733. Query should reflect the duplicate code there
Gabor noticed the utilization graphs being broken for clusters with multiple processes. 
https://materializeinc.slack.com/archives/CU7ELJ6E9/p1741596295446089
I've tested this manually, but I added a unit test in https://github.com/MaterializeInc/console/pull/3733

Aggregate multiprocess replica metrics for console overview view

---

Cargo.lock
src/kafka-util/Cargo.toml
src/kafka-util/src/admin.rs

Attempt to fetch the config of already-existing topics, so we can confirm that the configs match what we'd expect.
https://github.com/MaterializeInc/database-issues/issues/9032
I'd prefer to have `ensure_topic` actually attempt to update the configuration of the topic when it can, because I'd expect that to make the overall system easier to reason about. However, we don't necessarily have the right permissions to do that... and this should give us a better sense of how urgent that work might be.

[sinks] Config checks for progress topics

---

src/repr/src/optimize.rs
src/sql-lexer/src/keywords.txt
src/sql-parser/src/ast/defs/statement.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
src/transform/src/lib.rs
src/transform/src/movement/projection_pushdown.rs
test/sqllogictest/advent-of-code/2023/aoc_1207.slt
test/sqllogictest/advent-of-code/2023/aoc_1210.slt
test/sqllogictest/advent-of-code/2023/aoc_1214.slt
test/sqllogictest/advent-of-code/2023/aoc_1220.slt
test/sqllogictest/autogenerated/all_parts_essential.slt
test/sqllogictest/chbench.slt
test/sqllogictest/explain/aggregates.slt
test/sqllogictest/explain/physical_plan_aggregates.slt
test/sqllogictest/joins.slt
test/sqllogictest/ldbc_bi.slt
test/sqllogictest/ldbc_bi_eager.slt
test/sqllogictest/system-cluster.slt
test/sqllogictest/timedomain.slt
test/sqllogictest/tpch_create_index.slt
test/sqllogictest/tpch_create_materialized_view.slt
test/sqllogictest/tpch_select.slt
test/sqllogictest/transactions.slt
test/sqllogictest/transform/join_fusion.slt
test/sqllogictest/transform/join_index.slt
test/sqllogictest/transform/relation_cse.slt
test/testdrive-old-kafka-src-syntax/source-linear-operators.td
test/testdrive/source-linear-operators.td

_**Edit: I've added the `lts-backport-v25.1` label, but if this turns out to be too annoying to cherry-pick, then it's ok to skip this, as it's just a performance improvement.**_
This adds a call to `ProjectionPushdown` after the last call to `RelationCSE`. As explained in a code comment:
```
// `RelationCSE` can create new points of interest for `ProjectionPushdown`: If an MFP
// is cut in half by `RelationCSE`, then we'd like to push projections behind the new
// Get as much as possible. This is because a fork in the plan involves copying the
// data. (But we need `ProjectionPushdown` to skip joins, because it can't deal with
// filled in JoinImplementations.)
```
Slack discussion here:
https://materializeinc.slack.com/archives/C07SUTL7JMQ/p1741358397379089?thread_ts=1741341927.561309&ci …

Run `ProjectionPushdown` after the last `RelationCSE`

---

src/storage-types/src/dyncfgs.rs
src/storage/src/sink/kafka.rs

https://github.com/MaterializeInc/database-issues/issues/9032#issuecomment-2711978494
This behaviour is difficult to meaningfully test. I've tried to isolate the semantic changes as much as possible... consider reviewing commit-by-commit to be convinced of this.

[sinks] Iteratively search through the progress topic

---

src/postgres-util/src/schemas.rs
src/sql/src/pure/references.rs
src/storage/src/source/postgres/replication.rs
src/storage/src/source/postgres/snapshot.rs

Improve the scalability of `publication_info`, which fetches schema information from postgres. It not accepts a parameter for which schemas it should fetch, and is rewritten to avoid fetching data in a loop. Instead, it fetches the information for all OIDs in a single SQL query.
For pulling the schema of 1k tables, this reduces the time from about 1s to <10ms in local tests.
Related: MaterializeInc/incidents-and-escalations#211

Scalable schema fetching from postgres

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/migrate.rs
src/adapter/src/catalog/open.rs
src/adapter/src/coord/sequencer/inner.rs
src/catalog/src/durable.rs
src/catalog/src/durable/transaction.rs
src/storage-client/src/storage_collections.rs

Improve subsource planning by making various parts of the adapter more scalable.
This PR includes changes to:
* The *durable transaction* implementation to improve updates and validity checks. Updates are more efficient by cloning less and passing references where possible. Validity checks are more efficient by converting some that assert on name equality to a $n\cdot\log n$, where it previously was $n^2$.
* *Planning subsources* is more efficient by allocating all IDs in one operation rather than one-by-one.
* Avoiding *computing trace data* in the storage client when the level isn't high enough.
Takes planning 10k subsources from I-terminated-it-after-one-hour to around one minute.

Improve subsource planning

---

misc/python/materialize/cli/ci_annotate_errors.py

Noticed in https://github.com/MaterializeInc/database-issues/issues/9083 that we don't detect this log line that is causing clusterd to exit hard

ci: Add detection for memory allocation failure

---

test/0dt/mzcompose.py

See https://github.com/MaterializeInc/database-issues/issues/9084
Keeps failing in Nightly (I'd prefer for us to figure out the reason)

0dt tests: Disable kafka-source-rehydration check

---

.github/dependabot.yml

Maybe that is fast enough to run in < 1 hour

dependabot: Try grouping only patch version updates

---

clippy.toml

As seen in incident-437, the value returned by these methods can panic when formatted more than once... and tracing macro calls can end up formatting multiple times depending on configuration.
So: risk of misuse is significant and the functionality is easy to replace. Seems worth a ban.

Ban a couple of panicky itertools APIs

---

src/ore/src/bytes.rs

Don't import parquet in ore without parquet feature.
Parquet is optional, yet we're importing things from it.
```
error[E0433]: failed to resolve: use of undeclared crate or module `parquet`
--> vendor/materialize/src/ore/src/bytes.rs:30:5
|
30 | use parquet::errors::ParquetError;
|     ^^^^^^^ use of undeclared crate or module `parquet`
```

Don't import parquet in ore without parquet feature.

---

misc/python/materialize/parallel_workload/action.py

Since the associated issue has been closed
Seen in https://buildkite.com/materialize/nightly/builds/11474#0195a14d-2d4d-4344-a5e2-3ba10e2b647b

parallel-workload: Reenable two checks in backup&restore

---

doc/user/content/sql/show-create-connection.md
doc/user/content/sql/show-create-index.md
doc/user/content/sql/show-create-materialized-view.md
doc/user/content/sql/show-create-sink.md
doc/user/content/sql/show-create-source.md
doc/user/content/sql/show-create-table.md
doc/user/content/sql/show-create-view.md
doc/user/data/show_create_redacted_option.yml
src/sql-parser/src/ast/defs/statement.rs
src/sql-parser/src/ast/display.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/show
src/sql/src/plan/statement/show.rs
test/sqllogictest/redacted.slt

Add redacted counterparts to various `SHOW CREATE ...` statements. We need this for redaction in the self-managed debug tool (through `mzexplore`).
The first commit just tweaks some comments, while the second commit is the actual thing.
* This PR adds a known-desirable feature: https://github.com/MaterializeInc/database-issues/issues/9077

Implement `SHOW REDACTED CREATE ...`

---

Cargo.lock
src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord/sequencer/inner/copy_from.rs
src/aws-util/src/s3.rs
src/pgwire/src/protocol.rs
src/sql/src/plan.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/rbac.rs
src/storage-operators/Cargo.toml
src/storage-operators/src/oneshot_source.rs
src/storage-operators/src/oneshot_source/aws_source.rs
src/storage-operators/src/oneshot_source/http_source.rs
src/storage-types/src/oneshot_sources.proto
src/storage-types/src/oneshot_sources.rs
src/testdrive/Cargo.toml
src/testdrive/src/action.rs
src/testdrive/src/action/file.rs
src/testdrive/src/action/s3.rs
test/testdrive/copy-from-s3-minio.td

This PR adds support for specifying a column mapping and filling in default values for `COPY ... FROM <url>` (aka `OneshotSource`).
Let's say we ran `CREATE TABLE t1 (c1 text, c2 text, c3 text DEFAULT 'apple')`, so our table has 3 columns, but the file we're copying into Materialize only has 2 columns. After this PR you could run `COPY INTO t1 (c2, c1) FROM <url>` and it would map the first column of the data to `t1.c2`, the second column to `t1.c1`, and it would fill in the default value of `'apple'` for all values in `t1.c3`.
We do this by planning a `MapFilterProject`, converting it into a `SafeMfpPlan`, and then in `clusterd` when decoding data evaluating the `SafeMfpPlan` for every row.
Fixes https://github.com/MaterializeInc/database-issues/issues/8858
There are no tests in this PR, …

[copy_from] Support specifying a column map in `COPY ... FROM <url>`

---

src/storage/src/source/postgres/replication.rs
test/bounded-memory/mzcompose.py

This PR changes the Postgres source to emit an initial upstream probe immediately after the creation of the replication slot. The purpose of this is to produce the first timestamp binding (under RLU) as early as possible, so it can be used to reclock the snapshot updates rather than buffering them in the reclock operator.
Prior to this change, the first probe would only be emitted after the snapshot had been fully processed, which meant that that all snapshot updates needed to be buffered in the reclock operator, making the Postgres source require memory proportional to the size of the snapshot.
Fixes https://github.com/MaterializeInc/database-issues/issues/9061

storage/pg: emit an early probe during snapshotting

---

doc/user/content/releases/previews.md
doc/user/content/sql/alter-cluster.md
doc/user/content/sql/create-cluster.md
src/adapter/src/coord/sequencer/inner/cluster.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/session/vars/definitions.rs
test/cloudtest/test_managed_cluster.py
test/cluster/mzcompose.py
test/sqllogictest/managed_cluster.slt

Resolves https://github.com/MaterializeInc/database-issues/issues/9080
We also go ahead and change mentions in code, including tests.
For the docs changes: @kay-kim, and @sjwiesman and @josharenberg so you know for field-eng. Would be good if one of you could stamp this. 🙏

docs,etc: in ALTER CLUSTER docs, rename graceful -> zero downtime

---

ci/test/pipeline.template.yml

Lots of timeouts in CI recently, I haven't investigated what got slower yet

ci: Bump some agents and parallelism

---

src/adapter/src/coord/caught_up.rs
src/adapter/src/coord/sequencer/inner.rs
src/sql/src/plan/statement/ddl.rs
src/storage-client/src/controller.rs
src/storage-controller/src/history.rs
src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs
src/storage-types/src/sources.rs
src/storage-types/src/sources/kafka.rs
src/storage-types/src/sources/load_generator.rs
src/storage-types/src/sources/mysql.rs
src/storage-types/src/sources/postgres.rs

Implements https://github.com/MaterializeInc/database-issues/issues/9079
Per the design in https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20250127_multi_replica_scheduling_singleton_sources.md
There's now an issue around tracking "active replicas" in the storage controller, for the purposes of tracking `DroppedId` messages. I have a good idea how to fix it but wanted to get this out for review now.

storage: allow singleton sources on multi-replica clusters

---

.github/CODEOWNERS
src/sqllogictest/src/ast.rs
src/sqllogictest/src/parser.rs
src/sqllogictest/src/runner.rs
test/sqllogictest/slt.slt

The first commit changes the CODEOWNERS of `/src/sqllogictest` from `@MaterializeInc/adapter` to `@MaterializeInc/testing`. (But let me know if there was a good reason to have the Adapter team be the owner.) Edit: Also added myself, as discussed in DMs.
The second commit fixes a minor bug in space handling in slt in `colnames`.
The third commit is the main thing, which adds newline handling to slt result values, even when `multiline` is not specified. We use the replacement character trick to avoid newlines inside result values conflicting with newlines that are for field or row separation: when rewriting, we replace newlines with ⏎; when parsing, we replace ⏎ with newlines.
The motivation is that I'd like to have this feature for my next PR, which will make `SHOW CREATE ...` pretty-print …

tests: Add newline handling to slt when `multiline` is not specified

---

src/compute-types/src/dyncfgs.rs
src/compute/src/sink/materialized_view.rs

This PR converts the MV sink's `append` operator from a single-worker operator into a multi-worker operator, to share the work of appending batches, as well as maintaining the output persist shard, between all workers. The goal is to avoid skew in multi-process replicas where one process has to perform an outsized amount of work compared to the others.
The implementation extends the `BatchDescription` type by an `append_worker` field that specifies the worker responsible for appending the described batch and is chosen by the `mint` operator in round-robin fashion. The `append_worker` index is then used in the `append` operator to (a) route incoming batches to the responsible workers and (b) ignore batch descriptions meant for other workers.
Note that we broadcast all batch descriptions to …

mv-sink: spread append work between all workers

---

src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/replica.rs
src/compute-client/src/metrics.rs
src/ore/src/metrics.rs
src/storage-client/src/metrics.rs
src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs
test/cluster/mzcompose.py

This PR adds a set of replica collection metrics, tracking reconnects of both compute and storage replicas. The hope is to improve observability into issues caused by unstable connections between the controller and its replicas.
Closes https://github.com/MaterializeInc/database-issues/issues/4895.
The issue is about compute only, but the observability is useful for storage replicas as well.

compute,storage: replica connection metrics

---

misc/bazel/cargo-gazelle/src/bin/main.rs

In a few cases we need to manually maintain `BUILD.bazel` files because they require tricky semantics. This PR makes it such that we always print a log line when skipping the generation of these files to make it more obvious to the end user.
```
info: skipping generation of '/Users/parker.timmerman/Development/materialize/src/alloc/Cargo.toml' because `skip_generating = True` was set
```
Make generating `BUILD.bazel` files better

bazel: always print a log line when we skip generating a `BUILD.bazel`

---

src/storage-client/src/storage_collections.rs

Previously, the implementation had a potentially expensive trace statement that was always partially evaluated. With this change, it's fenced against the right logging level.
Related: MaterializeInc/incidents-and-escalations#211

Speed up setting read policies

---

doc/developer/design/20250307_column_names.md

Design doc for improving column names in `EXPLAIN` output.
[Rendered text](https://github.com/MaterializeInc/materialize/blob/design-doc-sql-hir-mir-column-names/doc/developer/design/20250307_column_names.md).
https://github.com/MaterializeInc/database-issues/issues/8960

[design] better column names

---

src/adapter/src/coord/caught_up.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs
src/storage/src/upsert_continual_feedback.rs
test/0dt/mzcompose.py

A couple of critical fixes around 0dt upgrades and UPSERT operators. Please see individual commits for a description.
Fixes https://github.com/MaterializeInc/database-issues/issues/9084
NOTE: This doesn't work yet, still working on the fix!

storage,0dt: fix overall hydration check and UPSERT hydration check

---

src/license-keys/Cargo.toml

Seen failing in https://buildkite.com/materialize/nightly/builds/11474#0195a14d-2d4e-42e3-9e71-4c6077af92fb

build: Remove unused deps in mz-license-keys

---

src/environmentd/tests/sql.rs

This was probably always racy based on timestamp selection and compaction. This removes the racy parts and will be followed up with a PR to actually plan queries correctly with an index over a history retained view.
Closes https://github.com/MaterializeInc/database-issues/issues/7450

Fix the test_retain_history test

---

ci/nightly/pipeline.template.yml

Should tell us if the issue is fixed with the crossbeam downgrade

ci: Reenable data ingest test with multiple replicas

---

src/storage/src/source/source_reader_pipeline.rs

We used to have a usecase for rendering a timely operator with many inputs and many outputs connected in a complicated way but after #31260 this usecase no longer exists.
This PR removes the fat operator in favor of many smaller operators with simple connectivity.

storage: avoid rendering fat timely operator

---

test/legacy-upgrade/check-from-v0.27.0-database-schema.td
test/legacy-upgrade/check-from-v0.27.0-kafka-sink.td
test/legacy-upgrade/check-from-v0.27.0-secrets.td
test/legacy-upgrade/check-from-v0.27.0-table.td
test/legacy-upgrade/check-from-v0.45.0-kafka-progress.td

legacy-upgrade test: Try removing version checks in check-from files

---

ci/nightly/pipeline.template.yml

@bobbyiliev Do we have an issue for the Azure problem? I'm afraid that we won't have e2e helm-chart + terraform coverage for Azure now.

ci: Disable two failing tests in nightly

---

src/orchestratord/src/controller/materialize/console.rs

Set console's pod security context fs_group to 101, as we use an nginx-unprivileged container that runs as uid/gid 101, and our TLS certificate mount was previously unreadable by that user.
TLS doesn't work with the console ever since we stopped running as root.

Set console's pod security context fs_group to 101

---

Cargo.lock
src/kafka-util/Cargo.toml
src/kafka-util/src/admin.rs
src/storage-client/src/sink.rs
src/storage-types/src/dyncfgs.rs
src/storage/src/sink/kafka.rs
src/testdrive/src/action/kafka/create_topic.rs
test/test-util/src/kafka/kafka_client.rs
test/testdrive/kafka-sink-topic-config.td

This reverts commit 0fe9cb1ad43e15d0224d4ee7fc18ddd23df590ba with the logging issue fixed.
This also allows us to attempt reconfiguring the topic if the configuration doesn't match. 
https://github.com/MaterializeInc/database-issues/issues/9032

[sinks] Attempt to fetch (and optionally alter) topic config

---

misc/python/materialize/mzcompose/services/clusterd.py
misc/python/materialize/mzcompose/services/materialized.py
test/limits/mzcompose.py

Fixes: https://github.com/MaterializeInc/incidents-and-escalations/issues/211
If I made no mistakes this run should tell us the limits for old and new syntax: https://buildkite.com/materialize/release-qualification/builds/757 (for a 16 core/32 GB RAM arm64 machine)
Locally I'm running it with 1000 tables:
```
$ bin/mzcompose --find limits down && bin/mzcompose --find limits run main --scenario=PostgresTables
$ bin/mzcompose --find limits --project-name limits2 down && bin/mzcompose --find limits --project-name
limits2 run main --scenario=PostgresTablesOldSyntax
```

limits test: Add 2 scenarios for number of Pg tables

---

ci/test/lint-main/checks/check-whitespace.sh

Since it checks both newlines and whitespace at the end of lines
Noticed by Frank in https://materializeinc.slack.com/archives/C0246GEHL8N/p1742490674279589

lints: Rename check-new-line to check-whitespace

---

src/catalog-debug/src/main.rs

Add some more debug info for what Persist shard we're checking the schema of
Help debug upgrade check failures

catalog-debug: add debug line to print Persist schemas

---

src/repr/src/optimize.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
src/transform/src/equivalence_propagation.rs

[We have a CPU profile](https://pprof.me/631f3c6fd71e6b13baf0e7b2c1505b7e/) where [a user](https://github.com/MaterializeInc/accounts/issues/3) running some very complex ad-hoc queries made envd quite busy with optimization. ([Slack discussion](https://materializeinc.slack.com/archives/C03R1QZ101Z/p1742565209009279?thread_ts=1742550520.344209&cid=C03R1QZ101Z).) The profile is showing that most of the time is spent in `MirScalarExpr::reduce` calls from `EquivalencePropagation`.
This PR modifies `EquivalencePropagation` to call `reduce` only if there was a recent change in the expression. Specifically, all of EQProp's calls to `reduce` are just after a `reduce_expr`, which conveniently returns a bool that indicates whether it made any changes.
There are no EXPLAIN changes across all of our …

optimizer: Make `EQProp` call `MSE::reduce` only after a change in `reduce_expr`

---

src/persist-client/src/cfg.rs
src/persist-client/src/rpc.rs

https://github.com/MaterializeInc/database-issues/issues/9074
Configuring these doesn't _really_ fix the issue, but it would have helped debug and mitigate it, and anyways we prefer as many configs to be dynamic as possible.
I expect to follow up with a second fix for the actual bug, but this seemed pretty separable and the rest of it may take longer, so...

[persist] Shift all pubsub configs over to dyncfg

---

src/compute-types/src/plan/join.rs
src/compute/src/compute_state.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/reduce.rs
src/expr/src/linear.rs
src/storage-operators/src/oneshot_source.rs

Instead of eagerly cloning the row in MFP evaluations, return a reference to the row containing the result. This allows columnar operators to absorb the output without cloning.
No behavior change expected, it is only code movement.

MFP evaluation returns reference to row

---

doc/user/content/installation/install-on-aws/_index.md
doc/user/content/installation/install-on-aws/upgrade-on-aws.md
doc/user/content/installation/operational-guidelines.md
doc/user/content/release-notes/_index.md
doc/user/layouts/shortcodes/self-managed/aws-recommended-instances.html
doc/user/layouts/shortcodes/self-managed/aws-terraform-upgrade-notes.html
doc/user/layouts/shortcodes/self-managed/versions/step-clone-aws-terraform-repo.html

FYI - the tag doesn't have to be v0.3.1 -- just using it as a placeholder.

docs: AWS terraform v0.3.1 enable  disk support

---

misc/helm-charts/operator/README.md
misc/helm-charts/operator/tests/deployment_test.yaml
misc/helm-charts/operator/values.yaml

Bump orchestratord to v0.138.0 to fix TLS for the console.
TLS support for the console was previously broken. We failed to test it when changing the console to not run as root, and the certificate mounts were not readable by the new lower-privileged user.

Bump orchestratord v0.138.0

---

Cargo.lock
src/self-managed-debug/Cargo.toml
src/self-managed-debug/src/main.rs
src/self-managed-debug/src/system_catalog_dumper.rs

* PR #31859:
`main` ← `jun/#8908/dump-catalog-2`
* **PR #31951 (THIS ONE)**:
`jun/#8908/dump-catalog-2` ← `jun/#8908/dump-catalog-3`
See commit messages for details
https://github.com/MaterializeInc/database-issues/issues/8908

Scrape mz_introspection data as CSVs per cluster replica

---

misc/helm-charts/operator/templates/deployment.yaml
misc/images/materialized-base/Dockerfile

- Removes disk graphs from self managed and emulator
- Fix graphs for multi-replica clusters
- Debounce fast subscribe  results in the Shell
- Fix bug where shell prompt clears when disconnected
Everything should be backwards compatible.
Tested locally in kind and tested on the emulator. Didn't test the helm chart integration

Bumps console version

---

src/expr/src/scalar/func.rs

At the moment, `error_if_null` evaluates both its input, and in most cases discards the error input. This causes us to do a lot of unnecessary work in the common case.
Instead, only evaluate the error expression (second input) if the first one evaluates to null.
Related: MaterializeInc/database-issues#9125

error_if_null: Lazily evaluate error

---

src/compute/src/server.rs

Previously the compute command channel adapter assumed that it is impossible to receive responses with epoch values greater than the channel adapter's current epoch. This assumption is wrong because the Timely cluster-side of workers learns about new connection epochs by observing commands from worker 0, which can be ahead of other workers' epochs.
This PR removes the assumption and instead makes the channel adapter handle responses with future epochs by stashing them until sufficiently many client reconnects have been observed.
Fixes https://github.com/MaterializeInc/database-issues/issues/9124
I've tried to write a regression test using mzcompose and toxiproxy, spawning a multi-process cluster and resetting its controller connection in a loop. Didn't …

compute: handle future epochs in channel adapter

---

misc/python/materialize/cli/run.py

Reported by Michael in https://materializeinc.slack.com/archives/CU7ELJ6E9/p1743013487929999

slt: Work when run from another directory

---

src/storage/src/source/postgres/replication.rs

The postgres replication implementation represented rows of data as `Vec<Option<Vec<u8>>>`, which is accurate but potentially inefficient.
Instead, we switch to `Row` containing `Datum::String` or `Datum::Null`. This causes us to do less work in total, with a slight caveat that it is _different_ work on the replication worker. I'm not sure if cloning Bytes into the nested vector is more work than constructing a `Row`, but there is a possibility for performance changes. A `Row` certainly is more compact in memory.
Related: MaterializeInc/database-issues#9125
Fixes: MaterializeInc/database-issues#9123

postgres replication: Eager string decoding

---

doc/user/content/manage/access-control/manage-network-policies.md
doc/user/content/sql/alter-network-policy.md
doc/user/content/sql/create-network-policy.md
doc/user/content/sql/drop-network-policy.md

GA network policies

---

misc/python/materialize/checks/all_checks/materialized_views.py
test/0dt/mzcompose.py
test/pg-cdc-old-syntax/pg-cdc.td
test/testdrive-old-kafka-src-syntax/kafka-progress.td
test/testdrive-old-kafka-src-syntax/load-generator.td

Follow-up to https://github.com/MaterializeInc/materialize/pull/27815
Failure seen in https://buildkite.com/materialize/nightly/builds/11639

tests: Fix nightly for new EXPLAIN TIMESTAMP output

---

src/adapter/src/catalog.rs
src/adapter/src/catalog/open.rs
src/catalog/src/builtin.rs
src/catalog/src/builtin/notice.rs
test/legacy-upgrade/check-from-v0.68.0-comment.td
test/sqllogictest/alter-table.slt
test/sqllogictest/comment.slt
test/sqllogictest/transactions.slt

Motivated by a recent slack discussion on the topic.
This PR tidies up some aspects of builtin objects definitions. Specifically, builtin views must now declare their expected schema and a test is added that verifies that the schema produced by planning the view definition corresponds to the declared schema.
Additionally, I have automatically ported all of the column documentation from our docs into SQL column comments. Our documentation includes markdown links in the docs of various fields. I have used a markdown parser to turn them into `psql` friendly text.
The commits that have been automatically generated are marked by `[codegen]` and don't need to be reviewed.

adapter: support specifying column comments for builtin objects

---

ci/nightly/pipeline.template.yml
test/race-condition/README.md
test/race-condition/mzcompose
test/race-condition/mzcompose.py

The current state reproduces https://github.com/MaterializeInc/materialize/pull/31226 locally, I'll rebase it and see what it finds with the fix.
This is currently failing because of https://github.com/MaterializeInc/database-issues/issues/9048 Edit: Fixed.
Test runs: https://buildkite.com/materialize/nightly/builds/11652 & https://buildkite.com/materialize/nightly/builds/11651 & https://buildkite.com/materialize/nightly/builds/11650

Race Condition Test Framework

---

src/catalog-debug/src/main.rs

This PR fixes the Catalog Upgrade Checker to handle the scenario when builtin tables and sources are either updated (e.g. a column is added) or newly created.
Fix the catalog upgrade checker so we get better validation of upgrades

[catalog] Fix upgrade checker to handle changes to Builtin Tables and Sources

---

Cargo.lock
src/sql-server-util/Cargo.toml
src/sql-server-util/examples/cdc.rs
src/sql-server-util/src/cdc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs

This PR adds a new `mz_sql_server_util::cdc` module that provides helpers to easily capture a stream of change events from a specific SQL Server "capture instance".
`mz_sql_server_util::Client` grows a new `fn cdc(capture_instance) -> CdcStream` method, where `CdcStream` can be turned into a `futures::Stream` that essentially returns `(Lsn, Vec<Changes>)` pairs. We use the well documented SQL Server CDC methods, all of the actual queries are in `mz_sql_server_util::inspect` module. SQL Server doesn't have a notification API so we poll the upstream for changes at a defined interval (default is 1 second).
Also included is an example! In `sql-server-util/examples/cdc.rs` you can see how these new types are intended to be used.
Progress towards …

[sql_server]: Add helper to easily get a stream of CDC changes

---

doc/user/content/transform-data/patterns/percentiles.md

This commit makes a number of improvements to the percentile queries in our docs, specifically the ones using HDR histograms.
* Fixes handling of 0 input values, which previously would cause the `hdr_histogram` view to error because `log(2, 0)` is undefined.
* Fixes handling of negative values, which previously would end up in positive (and duplicate) buckets because the sign was applied twice.
* Makes the `hdr_histogram` view contain bucket values instead of `(sign, mantissa, exponent)` triples.
* Makes use of CTEs to give names to things and improve readability.
* Removes an `ORDER BY` clause from the `hdr_distribution` definition where it had no effect.
The HDR histogram queries in our docs didn't handle zero and negative input values …

doc/user: improve percentile queries

---

doc/user/layouts/shortcodes/postgres-direct/right-size-the-cluster.html

The Postgres source guide initially suggests a `50cc` size but later on talks about a `200cc` which is not mentioned in the doc.

doc: Adjust cluster size in Postgres source guide

---

doc/user/content/manage/dbt/development-workflows.md

This whole page needs to be rewritten, but for now I am fixing the RBAC header so it doesn't break up the dbt blue / green section in the side bar.

fix dbt header

---

Cargo.lock
src/sql-server-util/Cargo.toml
src/sql-server-util/examples/cdc.rs
src/sql-server-util/src/cdc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs

This PR does a few things:
1. Refactors `mz_sql_server_util::Client` to use `SqlServerError` everywhere instead of `anyhow::Error` and refactors transaction support to work better.
2. Adds a `Client::query_streaming(...)` method that returns a `Stream<Row>` instead of `SmallVec<Row>`
3. Adds a `CdcStream::snapshot` method so we can snapshot and then subscribe to a list of changes for a given table.
Each of these changes are made in separate commits, it might be nice to review the commits independently

[sql_server]: Refactor `Client` and add `CdcStream::snapshot` method

---

src/buf.yaml
src/expr-test-util/tests/testdata/scalar
src/expr/src/interpret.rs
src/expr/src/scalar.proto
src/expr/src/scalar/func.rs
src/expr/tests/testdata/interpret
src/expr/tests/testdata/reduce
src/sql/src/func.rs
src/sql/src/plan/query.rs
test/sqllogictest/distinct_arrangements.slt

Some of the jsonb functions can be used in contexts where the output is either jsonb or strings. Previously, we'd encode this as part of the function call by supplying a `bool` field. This is an abstraction leak and instead it would be better to have separate functions.
This change absorbs the `stringify` parameter into different functions. No behavior change expected.

Turn jsonb stringify functions into separate functions

---

src/persist-client/src/internal/merge.rs

This switches our merge tree to store data as a `Vec<T>` instead of a `Vec<Vec<T>>`... a bit more memory-efficient, and lets us expose a slightly more flexible interface.
"Just for fun" - I don't think this type is currently used heavily enough that this matters very much. But, might as well... and there are some possible futures where this merge tree gets stressed more heavily and this sort of thing is important.
I appreciate this makes the code a little bit more fiddly, so I've added a bit to the exhaustive property test at the bottom. Let me know if there's any more checks there that would be useful!

[persist] Optimizations for the merge tree

---

doc/user/content/installation/install-on-aws/_index.md
doc/user/content/installation/operational-guidelines.md
doc/user/data/self_managed/aws_terraform_deployed_components.yml
doc/user/data/self_managed/aws_terraform_versions.yml
doc/user/layouts/shortcodes/self-managed/port-forwarding-handling.html
doc/user/layouts/shortcodes/self-managed/versions/step-clone-aws-terraform-repo.html
doc/user/layouts/shortcodes/tab.html

Converted to draft since won't merge until next Terraform version.
Oh, just saw the slack message about enabling TLS by default. Will update a patch.

docs: aws terraform supports tls

---

src/adapter/src/coord/sequencer/inner.rs
src/sql/src/plan/statement/ddl.rs
src/storage-controller/src/instance.rs

This PR extends the approach of
https://github.com/MaterializeInc/materialize/pull/31890 to the case of sinks. The handling is identical to that of single replica sources.

storage: allow sinks on multi-replica clusters

---

doc/user/content/transform-data/troubleshooting.md

Our introspection query for computation time reports an elapsed time (`duration`) that has a few flaws, deriving from the use of histograms: the numbers are off by up to 2x (due to binning), and the aggregation should scale each contribution by the `count` to tall up correctly. Instead, use independent subqueries one against `mz_scheduling_elapsed` to get precise duration information.

[docs] Improve accounting of computation time

---

src/adapter/src/coord/sequencer/inner/peek.rs

The `let optimization_finished_at = (now)();` line was after the `let pipeline =` line. However, the `let pipeline =` just creates a closure, which we then ran after the `let optimization_finished_at = (now)();` line. This PR fixes the order of things.

Fix OptimizationFinished in the statement lifecycle

---

misc/python/materialize/mzcompose/__init__.py
src/adapter-types/src/dyncfgs.rs
src/adapter/src/coord/peek.rs
src/adapter/src/explain/insights.rs
src/adapter/src/optimize.rs
src/adapter/src/optimize/peek.rs
src/compute/src/compute_state.rs
src/repr/src/row/encode.rs
src/storage-operators/src/stats.rs
test/sqllogictest/persist-fast-path.slt
test/sqllogictest/transform/column_knowledge.slt

Now that we've finished switching all users over to write data using the new ordering, we can rely on that ordering to optimize some queries. In particular:
- If we're fetching data for a specific key, and that key is a prefix of the Persist columns, we can push down that filter to get just the relevant part from each run.
- We used to ignore any `LIMIT` query with an ordering clause, since the Persist data wasn't in any user-meaningful order... but now we can allow ordering clauses where the order matches.
Aside from any possibility of bugs, this might not give a speedup on poorly-compacted datasets. Hopefully should be pretty rare... but in any case I've added a dyncfg so we can opt out environments as needed.
This is related to #30485, but not dependent on it. (The PARTITION BY syntax …

[adapter] Allow Persist fast-path peeks when ordering matches

---

Cargo.lock
src/sql-server-util/Cargo.toml
src/sql-server-util/examples/cdc.rs
src/sql-server-util/src/cdc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs

This PR refactors the recently added APIs in the `mz_sql_server_util::CdcStream` type to support snapshotting and streaming changes from multiple upstream "capture instances", aka multiple upstream tables. Most of the changes here are just operating over a collection of instances as opposed to a single instance.
Note: this should be the last PR, w.r.t. interacting with SQL Server, to getting a SQL Server source working in Materialize.
It might help to view without whitespace changes

[sql_server] Refactor `CdcStream` API to handle multiple "capture instances"

---

src/ore/src/process.rs

panic! already uses an exit code of 2, and it would be useful for us to be able to differentiate between these cases (because halt! is used for situations which aren't actually real errors, they should just trigger retries)

make halt! use an exit code of 166

---

misc/dbt-materialize/dbt/include/materialize/macros/deploy/deploy_init.sql

fix copying default privs for blue/green

---

src/expr/src/scalar/func.rs
src/sql/src/func.rs
test/sqllogictest/string.slt

fixes non string handling in string_to_array. currently causing panics.
errors in buildkite: https://buildkite.com/materialize/nightly/builds/11690#annotation-0195f3b5-b1bd-440b-8c7e-a445219baf63-error

fix string_to_array handle non string delimiter

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/persist-client/src/batch.rs
src/persist-client/src/cfg.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/iter.rs
src/persist-client/src/read.rs
src/persist-client/src/write.rs
src/persist-client/tests/machine/batch_key_lower_truncate
src/persist-client/tests/machine/caa_idempotent
src/persist-client/tests/machine/empty_since
src/persist-client/tests/machine/empty_upper
src/persist-client/tests/machine/gc
src/persist-client/tests/machine/gc_rollups
src/persist-client/tests/machine/regression_gc_behind
src/persist-client/tests/machine/regression_listen_compaction
src/persist-client/tests/machine/restore_blob
src/persist-proc/src/lib.rs
src/persist-types/src/arrow.rs
src/persist-types/src/part.rs
src/persist/src/indexed/encoding.rs
test/sqllogictest/explain/pushdown.slt
test/sqllogictest/persist-fast-path.slt

Followup to https://github.com/MaterializeInc/database-issues/issues/7411
- Remove a number of write-time flags that we no longer intend to use, along with the code perviously needed to support them.
- Update the remaining tests that are expressed in terms of codec data to expect structured data.
- Switch more of the internal logic over to work in terms of `Part` - the structured-only equivalent of `ColumnarRecords`.
This is only partially run through - in particular, I think we can probably do away with `ColumnarRecords` entirely. But it seemed like quite large enough for a first review. (Though possibly not quite as large as it looks... there are a number of mechanical and test changes that inflate the diff size.)
I think most changes are separated commit-by-commit, though there's …

[persist] Remove some old codec write-path code

---

misc/python/materialize/mzcompose/__init__.py
src/environmentd/src/environmentd/main.rs

bin/environmentd is failing to run

fix some issues with license keys during development

---

src/repr/src/optimize.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
src/transform/src/normalize_lets.rs
src/transform/tests/test_transforms.rs

Remove the defensive feature flag for #30974, which seems to have landed without incident.

Remove feature flag for #30974

---

src/transform/Cargo.toml

We need `Semigroup for Overflowing<$t>` when `fold_constants.rs` calls `differential_dataflow::consolidation::consolidate(rows);`
I'm not sure how this was even able to compile without this at all. Strangely, even without this, it compiles for me too when just starting up envd, but it doesn't compile if I want to run `cargo test` in `src/transform/tests/test_transforms`. Also, CI was somehow able to compile even the tests. Maybe the feature somehow gets pulled in when you compile not just this crate, but all crates.
* This PR fixes the build for `mz-transform`.

Make `transform` import `ore` with the `differential-dataflow` feature

---

Cargo.toml
WORKSPACE
misc/bazel/c_deps/BUILD.bazel
misc/bazel/c_deps/extra_setup.bzl
misc/bazel/c_deps/repositories.bzl
misc/bazel/c_deps/rust-sys/BUILD.protobuf-native.bazel
misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel
misc/bazel/rust_deps/cxxbridge-cmd/Cargo.cxxbridge-cmd.lock
misc/bazel/rust_deps/cxxbridge-cmd/include.BUILD.bazel
misc/bazel/rust_deps/repositories.bzl
misc/bazel/toolchains/BUILD.bazel
misc/python/materialize/cargo.py
src/build-tools/BUILD.bazel
src/build-tools/Cargo.toml
src/build-tools/src/lib.rs
src/testdrive/ci/BUILD.bazel

This PR upgrades our use of `rules_rust` to `v0.59.3`, which is a custom version I released on our [fork](https://github.com/MaterializeInc/rules_rust/releases/tag/mz-0.59.3). As described on the release, it's a fork of the upstream `v0.59.2` and includes two PRs I made upstream:
1. https://github.com/bazelbuild/rules_rust/pull/3386
2. https://github.com/bazelbuild/rules_rust/pull/3387
In addition to `rules_rust` we upgrade (out of necessity)
* `rules_cc` - rules for building C/C++ dependencies
* `protobuf` - required by the upgrade of `rules_cc`
* `bazel_skylib` - stdlib like Bazel rules
Note: This regresses our support for Apple x86_64 because I didn't have a machine I could use to rebuild the `cargo-bazel` binary. But AFAIK everyone using a Macbook now has an ARM based machine so this …

bazel: Upgrade `rules_rust` and a few other rule sets

---

test/cloud-canary/mzcompose.py

Old one doesn't exist anymore: https://buildkite.com/materialize/nightly/builds/11711#0196084e-eb09-405a-8c84-382b4c3028b7

cloud canary test: Bump throughput_tier version

---

Cargo.lock
src/workspace-hack/Cargo.toml

See https://rustsec.org/advisories/RUSTSEC-2025-0022
Noticed in https://buildkite.com/materialize/nightly/builds/11711#0196084e-eaa7-4228-8f77-e01d425004d0

build(deps): Bump openssl from 0.10.71 to 0.10.72

---

src/metrics/src/lgalloc.rs

The lgalloc metrics task tries to extract some information from `/proc/numa_maps`, which only exists on Linux. We're also using lgalloc on Mac, but don't support reading all stats. The current metrics update task notices the failure and prints a warning. With this change, it will swallow the not-found error but still propagate all other errors on Mac.

Filter not-found errors in lgalloc metrics task

---

Cargo.lock
src/sql-server-util/BUILD.bazel
src/sql-server-util/Cargo.toml
src/sql-server-util/examples/cdc.rs
src/sql-server-util/src/config.rs
src/sql-server-util/src/lib.rs
src/testdrive/Cargo.toml

This PR updates the `mz_sql_server_util::Client` to have initial support for tunneling by introducing our own `mz_sql_server_util::Config` type that wraps a `tiberius::Config`. Currently the only tunneling supported is SSH, AWS PrivateLink is left as a TODO.
Nothing functionally changes yet, nor is the SSH tunneling testing, but it aligns our SQL Server Client with the Clients we use for Postgres and MySQL.
Progress towards: https://github.com/MaterializeInc/database-issues/issues/8762

[sql_server] Update the `mz_sql_server_util::Client` to support tunneling

---

misc/bazel/c_deps/rust-sys/BUILD.protobuf-native.bazel

Missed some formatting in https://github.com/MaterializeInc/materialize/pull/32098

[bazel] run `bin/fmt`

---

src/expr/src/scalar.proto
src/expr/src/scalar.rs
src/expr/src/scalar/func.rs
test/sqllogictest/regex.slt

Simplify regexp replace handling by using a literal error
Instead of encapsulating a result, replace the function call by a literal error. The hope is that this is semantically equivalent to the existing implementation.
Part of MaterializeInc/database-issues#9138

Simplify regexp replace handling

---

src/balancerd/src/dyncfgs.rs
src/balancerd/src/lib.rs

There appears to be a delay in deleting balancerd pods (issues sigterm and closes server listening)  and the removal of the balancer from services/lb target groups. This adds a delay after receiving sigterm in the hopes that they're removed from LBs before they stop listening. 
We'd discussed just removing the connection closed entirely and more or less ignoring sigterm... this ended up being a bit simpler to add and a bit more flexible.
**tested manually**  we weren't testing the old sig term behavior so I'm not sure adding a test is required here.

add listener wait for balancerd sigterm handling

---

src/sql-server-util/src/cdc.rs

This PR changes the implementation of `mz_sql_server_util::cdc::CdcStream` to emit not only changes to upstream tables, but also "progress" events. Specifically the `CdcEvent` type is now an enum, `CdcEvent::Data` and `CdcEvent::Progress`. This matches TimelyDataflow semantics, and makes it easier to integrate into our Source pipeline.
Progress towards: https://github.com/MaterializeInc/database-issues/issues/8762

[sql_server] Update `CdcStream` to emit `CdcEvent::Progress`

---

misc/bazel/tools/BUILD.bazel

These paths changed when upgrading to the newer `rules_rust`
Fix `bin/lint`

[bazel] fix paths for `cargo` tool

---

Cargo.lock
src/workspace-hack/Cargo.toml

See https://rustsec.org/advisories/RUSTSEC-2025-0023
Seen in https://buildkite.com/materialize/nightly/builds/11736#0196129b-d8c2-4597-8929-889e34e4c7f4

build(deps): Bump tokio v1.44.1 -> v1.44.2

---

src/timely-util/Cargo.toml
src/timely-util/src/containers.rs

The implementation of `Column::clone` for the `Align` variant would first allocate a zero-filled region with `alloc_aligned_zeroed`, and then attempt to _append_ the bytes from the original region to its end using `Region::extend_from_slice`. The correct thing to do is to `copy_from_slice` instead, overwriting the zeroes.
Furthermore, the `Column` implementation calls `copy_from_slice` on a region returned by `alloc_aligned_zeroed` in a couple places. The returned region can be larger than the requested length, in which case `copy_from_slice` would panic because it expects both source and destination to have the same length. This is fixed here by slicing the destination to the source length.
Fixes …

timely-util: fix cloning `Column::Align`

---

doc/user/assets/sass/_content.scss
doc/user/content/sql/explain-plan.md
doc/user/content/sql/subscribe.md
doc/user/sql-grammar/sql-grammar.bnf

- Replaced the `EXPLAIN PLAN` railroad diagram with tabbed syntaxes per object being explained. I did have to move up a table ... and make into a list.  Otherwise, left the page alone. (think breadth first instead of depth first).
- Small fix to the SUBSCRIBE syntax. (A bit more could be done here to fix but for now, just a little bandaid).

docs: replace explain plan syntax railroad diagram

---

src/mz-debug/README.md
src/mz-debug/src/main.rs

- Added a section in `README.md` detailing how to run the `mz-debug` tool locally with an example command.
- required_if_eq wasn't working for default values. Chaining required_unless_present fixes this
- Makes 'dump-system-catalog' a global flag

Fix interface bugs for mz-debug

---

src/adapter/src/coord.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/introspection.rs
src/controller/src/lib.rs
src/storage-client/src/controller.rs
src/storage-controller/src/collection_mgmt.rs
src/storage-controller/src/lib.rs

This PR fixes a bug where certain types of introspection updates (frontiers and wallclock lag) would be reported with a 1s delay, causing confusion particularly around comparing compute with storage frontiers.
The bug was caused by the compute controller only reporting frontier advancements to the storage controller once per second. Frontier introspection is also produced once per second, but by the per-instance controllers, and the compute controller couldn't wait on the instance controllers because it had no way to know when they finished emitting frontier updates.
The fix implemented here is to have a "compute introspection sink" task that continually reads from the compute controller-internal `introspection_rx` and pushes the introspection updates to the storage controller. This task …

controller: report compute introspection updates promptly

---

misc/python/materialize/mzcompose/__init__.py
test/cluster/mzcompose.py

Follow up to #32028 to enable panics on overflow in CI.

Enable diff overflows in CI

---

.gitignore
misc/python/materialize/mzcompose/services/materialized.py

To prevent half-written files, doesn't fix https://github.com/MaterializeInc/database-issues/issues/9159 but is still a legitimate issue that could cause similar CI failures.

mzcompose: Atomically write license_key file

---

src/license-keys/src/lib.rs

Hopefully helps with https://github.com/MaterializeInc/database-issues/issues/9159, but more of a bandaid to get CI to be less flaky.

license keys: Remove initial anyhow! call

---

src/adapter/src/coord.rs
src/compute-client/src/as_of_selection.rs
src/storage-client/src/storage_collections.rs
test/zippy/mzcompose.py

When the Coordinator starts we list the entire contents of each builtin table and retract them to make table migrations easier. This PR changes the retractions to operate on a consolidated snapshot as opposed to an unconsolidated one. 
We've observed (https://github.com/MaterializeInc/database-issues/issues/9155) that after restarting Materialize a number of times in a row (>100) startup becomes very slow and we suspect this is because when Materialize is restarted in a loop we never get a chance to consolidate the builtin shards.
Fixes https://github.com/MaterializeInc/database-issues/issues/9155

[adapter] use a `SnapshotCursor` and consolidated snapshot for builtin table retractions

---

misc/python/materialize/mzbuild.py

I think this fixes https://materializeinc.slack.com/archives/C01LKF361MZ/p1744204953464749

mzbuild: Fix additive files for bazel build

---

doc/developer/design/20250226_postgres_style_explain.md

An outline of how to implement the last stage of https://github.com/MaterializeInc/database-issues/issues/8889.
[Rendered document](https://github.com/mgree/materialize/blob/explain-postgres-syntax/doc/developer/design/20250226_postgres_style_explain.md).

[design doc] `EXPLAIN` in Postgres syntax

---

src/license-keys/src/lib.rs

https://github.com/MaterializeInc/materialize/pull/32117#discussion_r2034905183

add some simple license key revocation

---

ci/plugins/cloudtest/hooks/command
ci/plugins/cloudtest/hooks/pre-exit
ci/plugins/mzcompose/hooks/command
ci/plugins/mzcompose/hooks/pre-exit

So that we will get results faster. Ideally this would be happening in between runs without counting to any, but that's not easy, it would require us to pause the agent temporarily, run the cleanup, and then resume it: https://buildkite.com/docs/agent/v3/pausing-and-resuming

ci: Move cleanup to end instead of beginning

---

src/sql/src/catalog.rs

Noticed in https://buildkite.com/materialize/deploy/builds/18278#01961c74-2a08-41d7-90fc-4f843818b59d
Follow-up to https://github.com/MaterializeInc/materialize/pull/31574

docs: Fix deploy step

---

ci/builder/Dockerfile

Seen failing in https://buildkite.com/materialize/nightly/builds/11783#01961ce8-bb55-4dce-9cc5-079e5639a001
Follow-up to https://github.com/MaterializeInc/materialize/pull/31574

ci: Bump cargo udeps version

---

test/limits/mzcompose.py

Otherwise there is a discrepancy between persist and crdb state:
```
limits-materialized-1     | environmentd: 2025-04-09T16:07:42.449535Z  WARN environmentd::run:environmentd::serve:new: mz_persist_client::internal::state_versions: fetch_current_state refetch expects earliest live diff to advance: v1 vs v1. In dev and testing, this happens when persist's Blob (files in mzdata) is deleted out from under it or when two processes are talking to different Blobs (e.g. docker containers without it shared).
```
Noticed in https://buildkite.com/materialize/release-qualification/builds/776
I'm still bisecting when this started occurring, but if it's just a test issue, then not that important anyway.
Edit: Started with my change https://github.com/MaterializeInc/materialize/pull/31805
Test run for …

limits test: Also restart cockroach

---

ci/nightly/pipeline.template.yml

Seen failing in https://buildkite.com/materialize/nightly/builds/11783#01961ce8-bbdf-4aee-ae13-b73d0d0c05f4
```
local-path-storage/local-path-provisioner-888b7757b-mprxv[local-path-provisioner]: E0410 00:36:47.675551       1 controller.go:1481] delete "pvc-3e293334-ae62-486e-9446-706693d5a42d": volume deletion failed: failed to delete volume pvc-3e293334-ae62-486e-9446-706693d5a42d: failed to delete volume pvc-3e293334-ae62-486e-9446-706693d5a42d: create process timeout after 120 seconds
```

cloudtest: Bump agent size for k8s recovery test

---

doc/user/data/sql_funcs.yml

incorrect signature, great catch @ggevay

fix string_to_array signature incorrect

---

src/compute/src/row_spine.rs
src/repr/src/row.rs

The way we parse rows as `&[u8]` to form `Datum` elements uses a bunch of `offset: &mut usize` to think about where we are in the parsing. It seems like it can be replaced with slices, using `bytes: &mut &'a [u8]` as the primary argument and advancing it as we read, rather than advancing the `offset`. This simplifies a fair bit of code, and potentially removes any number of bounds checks where the slice carries the information about its validity. E.g. several `data[*offset .. *offset + len]` things turn in to `data.split_at(len)`.

Prefer slices to offsets in `Row` parsing

---

src/adapter/Cargo.toml
src/adapter/src/coord/statement_logging.rs
src/balancerd/Cargo.toml
src/balancerd/src/lib.rs
src/ore/Cargo.toml
src/ore/src/now.rs
src/workspace-hack/Cargo.toml

we want to use a uuid that is ordered based on a time to improve sorting of the statement log indexes.
https://github.com/MaterializeInc/database-issues/issues/8937

adapter: refactor statement logging to use time ordred uuid

---

src/sql-parser/Cargo.toml
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/source
src/sql-server-util/src/desc.proto
src/sql-server-util/src/desc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs
src/sql/src/plan/error.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/references.rs
src/sql/src/pure/sql_server.rs

This PR implements "purification" in the Adapter for a SQL Server source. For folks unfamiliar, purification is a step during object creation where we query external systems for any necessary information, with the goal of making our persisted SQL "pure".
During purification of a SQL Server source we do the following:
1. Ensure CDC is enabled for the current database
2. Ensure snapshot isolation is enabled for the current database
3. List all tables that currently have CDC enabled, and their capture instances
* The specified capture instance for each subsource is then persisted in `PurifiedExportDetails
Left as a TODO is implementing support for `CREATE TABLE ... FROM SQL SERVER`. Nothing blocks our implementation of this feature although because it's not released yet I opted out of …

[sql_server] Implementent purification for SQL Server Source

---

misc/python/materialize/cli/helm_chart_version_bump.py

As noticed by Kay: https://github.com/MaterializeInc/materialize/pull/32154#discussion_r2038710869

helm-chart publish: Fix arg name

---

misc/python/materialize/cli/helm_chart_version_bump.py

Our release cut script is failing. Last night's run:
```
File "/home/runner/work/release/release/materialize/misc/python/materialize/cli/helm_chart_version_bump.py", line 42, in <lambda>
lambda docs: docs[0].update({"appVersion": args.version}),
^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'version'
```
https://github.com/MaterializeInc/materialize/pull/32162 was meant to fix the arg name in `helm_chart_version_bump.py`, but the new run now failed with:
```
File "/home/runner/work/release/release/materialize/misc/python/materialize/cli/helm_chart_version_bump.py", line 42, in <lambda>
lambda docs: docs[0].update({"appVersion": args.environmentd_version}),
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'environmentd_version'. Did you mean: …
```

Fix positional argument name in `helm_chart_version_bump.py`

---

src/persist-client/src/fetch.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/schema.rs
src/persist-client/src/write.rs

When creating a `PartMigration` if we don't have a `schema_id` but we do have structured only data, we'll fallback to the `deprecated_schema_id` field because this indicates the `persist_record_schema_id` and `persist_batch_columnar_format` flags did not propagate properly.
Fix an issue at least one customer has run into.

[persist] Be defensive when we have structured only data

---

src/sql-server-util/src/cdc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs

This PR changes the `CdcStream::into_stream` method use a streaming query so we no longer buffer an entire change set into memory and instead everything should be streamed in constant memory, with back pressure, from the network and to our caller.
It also removes `mark_complete` field on `CdcEvent::Data`, after chatting with Petros we'll handle cleaning up data in a slightly different way.
Fixes a `TODO(sql_server1)`

[sql_server] Refactor `CdcStream::into_stream` to better stream changes

---

misc/helm-charts/operator/README.md
misc/helm-charts/operator/tests/deployment_test.yaml
misc/helm-charts/operator/values.yaml

See https://materializeinc.slack.com/archives/C07PN7KSB0T/p1743231538417009
Do we want to bump this version manually? We are also using it for our self-managed releases from main now.

helm-charts: Bump orchestratord version to v0.141.0

---

ci/nightly/pipeline.template.yml
test/cloudtest/test_upgrade.py

Seen failing in https://buildkite.com/materialize/nightly/builds/11783#01961ce8-bbdc-41da-b266-10397ff883e9
```
Warning  FailedScheduling  82s (x18 over 9m49s)  default-scheduler  0/7 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 5 Insufficient memory. preemption: 0/7 nodes are available: 2 Preemption is not helpful for scheduling, 5 No preemption victims found for incoming pod.
```

cloudtest: Parallelize upgrade test

---

ci/plugins/mzcompose/hooks/pre-exit

Noticed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1744381055845859

ci: Improve binary collection for coredump analysis

---

Cargo.lock
misc/images/ubuntu-base/Dockerfile
src/balancerd/Cargo.toml
src/dyncfg-launchdarkly/Cargo.toml
src/frontegg-mock/Cargo.toml
src/persist-cli/Cargo.toml
src/persist-client/Cargo.toml
src/persist-client/src/read.rs
src/persist-types/Cargo.toml
src/persist/Cargo.toml
src/postgres-client/Cargo.toml
src/tls-util/Cargo.toml
src/workspace-hack/Cargo.toml

The `anyhow` crate automatically collects backtraces when creating `anyhow::Error`s if the `RUST_BACKTRACE=1` env variable is set, and uses them to enhance the errors' Debug representation. This is a feature we don't actively rely on but that comes with significant costs:
* Collecting backtraces significantly increases the memory and CPU costs of creating error values, which can be both expensive and surprising.
* In rare cases, collecting backtraces can deadlock the process, if jemalloc decides to collect a profiling sample at the same time.
This PR therefore disables backtrace collection in `anyhow` by setting `RUST_LIB_BACKTRACE=0`.
This also disables backtrace collection in all other libraries that use `std::backtrace::Backtrace::capture`, but I'm not aware of any we use. Sentry does …

Disable backtrace collection in `anyhow`

---

src/repr/src/adt/datetime.rs
src/repr/src/strconv.rs
test/sqllogictest/timestamp.slt

adds parsing and returning BC time stamps
https://github.com/MaterializeInc/database-issues/issues/8191

#8191: add support for BC and AD suffixes in timestamps

---

src/cloud-resources/src/crd/materialize.rs
src/orchestratord/src/controller/materialize.rs
src/orchestratord/src/controller/materialize/environmentd.rs

this allows us to choose how to resolve a rollout which is stuck or taking too long - we can either cancel the rollout (by resetting the reconciliation_id to the last reconciliation id from the status) or now force it to complete by setting force_promote to the reconciliation_id value.
not planning on porting this to the environment controller since it we're so close to getting rid of it

allow orchestratord to force a rollout to promote before it's ready

---

src/sql-server-util/src/cdc.rs
src/sql-server-util/src/desc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs
src/storage-types/src/dyncfgs.rs
src/storage-types/src/sources/sql_server.rs
src/storage/src/source/sql_server.rs
src/storage/src/source/sql_server/replication.rs
test/sql-server-cdc/mzcompose.py
test/sql-server-cdc/sql-server-cdc.td

This PR adds an MVP implementation of the `SourceRender` trait for the SQL Server source. It also adds a testdrive test that exercises replicating data from SQL Server into Materialize.
TODO(parkmycar): I need to add some more detail here

[sql_server] Initial implementation for Source Rendering

---

src/sql-server-util/src/inspect.rs

I thought this was included in a different PR, but must have gotten lost in splitting and rebasing.
This PR fixes the function we call to get the upstream `TABLE`s that are associated with the capture instances the source reads from. Previously if provided with an empty set of capture instances the query would error. Now we return early without issuing the query at all.
Fixes a known bug.

[sql_server] Fix bug with empty query

---

test/sql-server-cdc/mzcompose.py

Accidentally included this when I merged a previous PR. This is useful for me when I test locally but can cause flakes in CI
Keep CI stable

[sql_server] Remove default timeout from mzcompose

---

bin/bump-version
ci/nightly/pipeline.template.yml
misc/helm-charts/operator/README.md
misc/helm-charts/operator/tests/deployment_test.yaml
misc/helm-charts/operator/values.yaml
misc/python/materialize/cli/helm_chart_version_bump.py
test/terraform/aws-persistent/main.tf
test/terraform/aws-temporary/main.tf
test/terraform/azure-temporary/main.tf
test/terraform/gcp-temporary/main.tf
test/terraform/mzcompose.py

Discussed in https://materializeinc.slack.com/archives/C07PN7KSB0T/p1743231538417009
Green test run: https://buildkite.com/materialize/nightly/builds/11816

helm-chart: Bump orchestratord version automatically

---

ci/test/pipeline.template.yml

I don't understand why it has to compile the tool though

ci: Speed up mz-debug test

---

src/auth/Cargo.toml
src/auth/src/hash.rs

Follow-up to https://github.com/MaterializeInc/materialize/pull/32131
Failures seen in https://buildkite.com/materialize/nightly/builds/11825

Fix nightly failures from auth

---

ci/nightly/pipeline.template.yml

Noticed in https://buildkite.com/materialize/nightly/builds/11822#019633df-257d-4ea4-adb0-bb5ccdb1fd4f that it was still on
Follow-up to https://github.com/MaterializeInc/materialize/pull/32152

cloudtest upgrade test: Disable test parallelism

---

src/compute/Cargo.toml

Add the differential-dataflow feature to the mz-ore dependency. It's an oversight to not enable it.

Add a missing feature to mz-ore from compute

---

test/parallel-benchmark/mzcompose.py

Test runs: https://buildkite.com/materialize/release-qualification/builds/803, https://buildkite.com/materialize/release-qualification/builds/802, https://buildkite.com/materialize/release-qualification/builds/801
Maybe helps with https://github.com/MaterializeInc/database-issues/issues/9162 ? Based on discussion in https://materializeinc.slack.com/archives/CTESPM7FU/p1744619426495409

parallel-benchmark: Try cleaning up better

---

misc/python/materialize/cli/run.py

https://github.com/MaterializeInc/materialize/pull/31975#issuecomment-2802065144
let me know if you see any others

catch one more place that was expecting an exit code of 2

---

src/persist-client/src/fetch.rs
src/persist-client/src/schema.rs
src/storage-operators/src/persist_source.rs

Two related bugs:
- The new optimization path was creating a column for K=Row, not K=SourceData. This would never work, so the optimization wasn't kicking in.
- The "faked" data didn't have a schema id, which caused issues at part decoding. 
https://github.com/MaterializeInc/database-issues/issues/9174
There's some additional dedup and cleanup to be done here - I'll take that in a followup PR.

[persist] Fix a bug in the projection optimization refactoring 

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml
misc/python/materialize/checks/all_checks/alter_connection.py
misc/python/materialize/checks/all_checks/identifiers.py
misc/python/materialize/checks/all_checks/mysql_cdc.py
misc/python/materialize/checks/all_checks/pg_cdc.py
misc/python/materialize/checks/all_checks/sql_server_cdc.py
misc/python/materialize/checks/checks.py
misc/python/materialize/checks/features.py
misc/python/materialize/checks/mzcompose_actions.py
misc/python/materialize/checks/scenarios.py
misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/checks/scenarios_zero_downtime.py
test/cloudtest/test_upgrade.py
test/platform-checks/mzcompose.py

This PR enables SQL Server in platform checks by adding a new `--features` argument that supports "azurite" and "sql_server". Then we add new workflows in CI that run SQL Server on x86 which is the only arch that is supported by Microsoft's official SQL Server Docker image.
Test the SQL Server source with platform-checks

[sql_server] Enable platform checks

---

ci/qa-canary/pipeline.template.yml

ci: Disable some QA Canary jobs

---

src/sql/src/optimizer_metrics.rs

This PR makes the "slow optimization" log msgs easier to read and take up less space:
- Log micro-seconds instead of nano-seconds, so that 1) take up less space on the screen, 2) large ones stand out more. (Every number was large in nanoseconds, so it was hard to see at a glance which ones are the actually big ones.)
- Call out that it's μs by printing `transform_times_μs`, because sometimes I was forgetting what unit we were printing.
- Reorder fields to put the total duration at the beginning.

Declutter "slow optimization" log msg

---

Cargo.lock
src/sql-parser/src/ast/defs/ddl.rs
src/sql-parser/src/parser.rs
src/sql-server-util/Cargo.toml
src/sql-server-util/src/desc.proto
src/sql-server-util/src/desc.rs
src/sql-server-util/src/lib.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/pure.rs
src/sql/src/pure/error.rs
src/sql/src/pure/references.rs
src/sql/src/pure/sql_server.rs
src/storage-types/src/sources.rs
src/storage/src/source/sql_server/replication.rs
test/sql-server-cdc/10-sql-server-cdc.td
test/sql-server-cdc/20-column-options.td
test/sql-server-cdc/mzcompose.py

This PR updates the SQL Server source to support excluding columns or decoding them as text, specifically it does the following:
* Updates `SqlServerColumnDesc` to support representing unknown columns. This allows users to replicate tables with a column type we don't recognize and specify said column in `EXCLUDE COLUMNS`.
* Update `SqlServerRowDecoder` to support decoding from any type to text, adds some limited testing.
* Updates parsing and purification to include `TEXT COLUMNS` and `EXCLUDE COLUMNS` in both the primary `CREATE SOURCE` statement (for round-tripping) and the generated subsource statements.
I would start with `sql-server-util/src/desc.rs`, that's where the bulk of the changes are. This file contains the types that we use to represent columns and tables from SQL Server. …

[sql_server] Support `TEXT COLUMNS` and  `EXCLUDE COLUMNS`

---

doc/user/content/installation/install-on-gcp/_index.md
doc/user/content/installation/operational-guidelines.md
doc/user/data/self_managed/gcp_terraform_deployed_components.yml
doc/user/data/self_managed/gcp_terraform_versions.yml

reference docs update per https://github.com/MaterializeInc/terraform-google-materialize/pull/22

docs: google terraform storage bucket versioning

---

ci/plugins/mzcompose/hooks/pre-exit

Seen in https://buildkite.com/materialize/test/builds/102307#01963aa7-b9f0-487f-9798-4956671c67d0

ci: Improve cleanup handling in pre-exit hook

---

src/compute/Cargo.toml
src/compute/src/row_spine.rs
test/sqllogictest/introspection/attribution_sources.slt

At the moment, various types in row_spine re-compute their length whenever asked, and this can take a surprising amount of time to compute. So, stash it and assert its correctness in debug mode.

row_spine: Maintain separate counts

---

src/adapter/src/optimize.rs
src/sql/src/plan/explain.rs
src/transform/src/lib.rs
src/transform/src/normalize_lets.rs

EXPLAIN (and other things) call into the optimizer at many points, and not all of these have been wrapped into `catch_unwind` so far. This PR attends to some of these. More specifically:
- `normalize_lets` is called at some places outside the normal optimizer pipelines, e.g., it's called by EXPLAIN. Therefore, the PR adds a `catch_unwind` in `normalize_lets`, so that we catch panics even when `normalize_lets` is called not through the normal optimizer pipelines. (I noticed this problem when working on https://github.com/MaterializeInc/database-issues/issues/9156: normally, the panic was caught, but sometimes it caused an actual panic in EXPLAIN commands.)
- The PR adds `catch_unwind` to the `normalize_subqueries` call. (This is also in EXPLAIN.)
I suggest reviewing commit-by-commit:
1. …

Catch more panics when calling optimizer code

---

ci/plugins/mzcompose/hooks/pre-exit

ci: Only exit at the end of pre-exit hook

---

src/adapter/src/coord/sequencer/inner.rs
src/sql/src/plan.rs
src/sql/src/pure.rs
test/sql-server-cdc/10-sql-server-cdc.td
test/sql-server-cdc/30-add-subsource.td

This PR adds support for adding subsources to a `SQL SERVER` source. All of the changes are in Adapter during purification. We also add a new testcase to the `sql-server-cdc` mzcompose flow to exercise adding and dropping subsources.

[sql_server] support `ALTER SOURCE ... ADD SUBSOURCE`

---

src/transform/src/join_implementation.rs
test/sqllogictest/github-8261-8463-9156.slt

When `JoinImplementation` lifts an MFP from a join input to after the join (to be able to reuse an arrangement), it needs to permute the join equivalences by the projection of the lifted MFP. Moreover, it can happen that a column reference that we get from the permutation refers to a column that is built by a map expression of the MFP that is being lifted. This requires further treatment, because the lifted MFP will happen _after_ the equivalences, so the equivalences can't refer to a column that is built only in the MFP. What the code does (already before this PR) is simply inline the referred Map expression in place of the problematic column reference.
But, there was a bug in the inlining logic: After substituting a problematic column reference with a new expression, we have to look at …

optimizer: Fix JoinImplementation's MFP lifting's inlining

---

Cargo.lock
deny.toml

it's hard to find the actual errors when there is a bunch of warning output

clean up cargo deny warnings

---

src/expr/src/scalar.rs
test/sqllogictest/jsonb.slt

Fixes https://github.com/MaterializeInc/database-issues/issues/9182, which caused [incident-512](https://materializeinc.slack.com/archives/C08NDPVT8CT).
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/9182

optimizer: Guard `If` pushing by a type check

---

Cargo.lock
src/cluster-client/BUILD.bazel
src/cluster-client/Cargo.toml
src/cluster-client/src/lib.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs
src/controller/src/lib.rs
src/storage-controller/src/lib.rs
test/testdrive/wallclock-lag.td

This is to avoid the impression of having sub-second wallclock lag accuracy.
The lag values in the wallclock lag history have millisecond precision, even though they don't provide this kind of accuracy. See [Slack thread](https://materializeinc.slack.com/archives/C08AENAP691/p1744706310908609).
I made `WallclockLagFn` a struct akin to `NowFn`, mostly to have a place to put the comment about rounding up.

controller: round wallclock lag measurements to seconds

---

src/compute/src/render/context.rs
src/compute/src/render/join/linear_join.rs
src/pgcopy/src/copy.rs
src/repr/src/row.rs

The `RowArena` type has unsafe internals, and in particular wraps `Vec<u8>` stuffs with a `RefCell`, but wants to return `&'a [u8]` that outlives `borrow_mut()` calls. This works as long as we don't de/re-allocate the `Vec<u8>` for the lifetime of the type, because the `'a` comes from `&'a self`.
The `RowArena::clear` method upsets this, by deallocating the memory under a `&self` reference. If we change that to be a `&mut self` reference, it seems like this should be .. more safe, at least. The mutable reference should require that all borrowed references have expired.

Require `RowArena::clear` to take a `&mut self`

---

src/compute/src/render/context.rs
src/compute/src/render/reduce.rs
src/repr/src/datum_vec.rs

Decode rows in rendering up to a demand limit.
Add functionality to only decode a relevant prefix of rows based on what a map-filter-project demands. This can skip some work if all relevant columns are at the beginning of a row.
The PR has the downside that performance improvement isn't uniform. If we're demanding all columns of a row, we have to do the same work as today. If we're demanding no columns, or a column at the front of a row, we have to do less work. I think this change is worthwhile because it improves queries that are either not on index keys, or during hydration.
A follow-up change should apply the same pattern to peeks.

Only decode rows up to demand

---

src/sql-server-util/src/desc.proto
src/sql-server-util/src/desc.rs
src/sql/src/pure/error.rs
src/sql/src/pure/sql_server.rs
test/sql-server-cdc/50-unsupported-types.td

We can't support replication of certain datatypes, e.g. `text`, because they don't provide us with the "before" value when replicating. This used to work but I accidentally regressed the behavior in https://github.com/MaterializeInc/materialize/pull/32181.
This PR re-adds the check to ensure all columns we're intending to replicate are supported. Also an mzcompose testdrive case to exercise these unsupported types.

[sql_server] add negative tests to ensure we don't allow some data types

---

src/storage/src/source/sql_server.rs
src/storage/src/source/sql_server/replication.rs

This PR is a bit of plumbing that wires up the errors from the replication operator into the health status stream for the source.
FWIW it's the same pattern that Postgres ([code](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/source/postgres.rs#L220-L253)) and MySQL ([code](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/source/mysql.rs#L202-L232)) use.

[sql_server] Wire up replication errors to health status messages

---

src/persist-client/src/fetch.rs
src/persist/src/metrics.rs

removes a metric that does not appear to be used in any production dashboards. this is I believe the smallest possible changeset. but as noted below we may wish to follow up by removing other unused metrics and improving the performance of counter incrementing.
https://github.com/MaterializeInc/database-issues/issues/9196
I think we can actually remove a lot more stats. how much do we want to rip out?
also do we want to just improve our stat incrementing in general to minimise likelyhood of future contention?

persist: remove unused arrow decoding time metric

---

src/sql-server-util/examples/cdc.rs
src/sql-server-util/src/cdc.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs
src/storage-types/src/dyncfgs.rs
src/storage-types/src/sources/sql_server.rs
src/storage/src/source/sql_server.rs
src/storage/src/source/sql_server/progress.rs
src/storage/src/source/sql_server/replication.rs
test/sql-server-cdc/10-sql-server-cdc.td

This PR does a few things:
1. In the "replication" operator, emits `ProgressStatisticsUpdate::Snapshot` as we're snapshotting tables.
2. Adds a new "progress" operator which does the following:
a. On an interval configurable with dyncfg, probes the upstream SQL Server instance for the max LSN and emits `ProgressStatisticsUpdate::SteadyState` updates.
b. Tracks the `resume_uppers` stream and as we learn about newly committed data, we emit `ProgressStatisticsUpdate::SteadyState` updates and call the upstream SQL Server instance to cleanup the change tables. This behavior is gated behind a dyncfg which is enabled by default but added just in case we find issues when deploying to customers.

[sql_server] Report `ProgressStatisticsUpdate`s and cleanup committed data

---

src/sql/src/plan/statement/show.rs
test/sql-server-cdc/20-column-options.td
test/sql-server-cdc/mzcompose.py

[sql_server] support `SHOW CREATE SOURCE ...`

---

src/adapter/src/catalog/migrate.rs
src/sql-server-util/examples/cdc.rs
src/sql-server-util/src/config.rs
src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/ddl/connection.rs
src/sql/src/pure.rs
src/sql/src/pure/references.rs
src/sql/src/pure/sql_server.rs
src/storage-types/src/connections.rs
src/storage-types/src/sources/sql_server.rs
src/storage/src/source/sql_server/progress.rs
src/storage/src/source/sql_server/replication.rs
src/testdrive/src/action/sql_server/connect.rs

This PR fixes a `TODO(sql_server1)` related to our `mz_sql_server_util::Client` type and re-levels many of the existing `TODO(sql_server1)` notes to a better level. If folks feel like something should not be downgraded please feel free to say so!

[sql_server] Minor cleanups, readjust some `TODO(sql_server1)`

---

misc/python/materialize/mzcompose/__init__.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/32231
Seen failing in https://buildkite.com/materialize/nightly/builds/11875#01964617-522f-4da2-a427-d007eb65d95a
In general we have to wait until 4 versions are released before we can remove flags in CI (which is a bit awkward since no one remembers then)

ci: Keep enable_kafka_sink_partition_by for upgrade tests

---

src/sql-server-util/src/desc.rs

Seen in https://buildkite.com/materialize/nightly/builds/11875#01964617-51e7-4e50-bc45-41336f6ef2e4

miri test: Disable smoketest_numeric_conversion

---

src/storage-client/src/client.proto
src/storage-client/src/client.rs
src/storage-client/src/metrics.rs
src/storage-controller/src/history.rs
src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs
src/storage/src/storage_state.rs

Each commit flattens one variant

storage: flatten `StorageCommand` and `StorageResponse`

---

misc/python/materialize/mzbuild.py

Seen in https://buildkite.com/materialize/test/builds/102470#0196493a-146a-4b71-b10a-706d6b497262
Fixes a slight regression introduced by https://github.com/MaterializeInc/materialize/pull/32212

[build] fix `mzbuild` by skipping `DependencySet` check if there are no deps

---

src/sql/src/plan/statement/ddl/connection.rs

Still need to fix this further, but this is better than setting `None`.
Progress towards https://github.com/MaterializeInc/database-issues/issues/9205

[sql_server] change encryption to `Preferred`

---

doc/user/content/releases/v0.142.md
misc/helm-charts/operator/README.md
misc/helm-charts/operator/tests/deployment_test.yaml
misc/helm-charts/operator/values.yaml

See https://buildkite.com/materialize/test/builds/102470
This is currently causing some test failures since tests depend on the last version in docs to be on Dockerhub in order to test upgrades from it, see for example https://buildkite.com/materialize/nightly/builds/11886#01964b3d-6c92-4703-a14e-028653e9b20c

release: Move to v0.142.1 since v0.142.0 failed to get released

---

src/storage-client/src/client.proto
src/storage-client/src/client.rs
src/storage-controller/src/history.rs
src/storage-controller/src/lib.rs
src/storage/src/storage_state.rs

https://github.com/MaterializeInc/materialize/pull/31261 flattened most of the storage commands and responses, except for the oneshot-ingestion commands that were only added after that PR was opened. This PR flattens the two new command variants as well.

storage: flatten oneshot ingestion commands

---

misc/python/materialize/checks/all_checks/source_errors.py

platform-checks: Disable stall validation in SourceErrors check

---

doc/user/content/installation/install-on-gcp/_index.md
doc/user/content/installation/install-on-gcp/appendix-deployment-guidelines.md
doc/user/content/release-notes/_index.md
doc/user/data/self_managed/gcp_terraform_deployed_components.yml
doc/user/data/self_managed/gcp_terraform_versions.yml
doc/user/data/self_managed/latest_versions.yml

Draft until we cut a release with the feature.  Currently, using v0.3.5 as the release version placeholder, but can be anything.  Also, added https://github.com/MaterializeInc/terraform-google-materialize/pull/45 for the readme on the terraform repo.

docs: Updates for gcp lgalloc

---

ci/nightly/pipeline.template.yml

Seen failing in https://buildkite.com/materialize/nightly/builds/11892
Green run with this PR: https://buildkite.com/materialize/nightly/builds/11903

cloudtest: Bump agent size for platform checks

---

test/sql-server-cdc/mzcompose.py

Seen in https://buildkite.com/materialize/test/builds/102656#01965e29-e8b7-4a3c-9c3b-500122363b09

SQL Server tests: Clean up before starting test

---

test/terraform/gcp-temporary/main.tf

Bumping the Terrafrom GCP module version to v0.4.0, which supports lgalloc.

self-hosted: bump GCP terraform module verson to v0.4.0

---

ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/pre-exit
misc/python/materialize/mzcompose/services/testdrive.py
src/testdrive/src/action.rs
src/testdrive/src/action/consistency.rs
test/terraform/mzcompose.py
test/testdrive/github-6942.td
test/testdrive/webhook.td

terraform test: Add some interesting td files and make the cleanup more robust, speed up mz-debug build

---

Cargo.lock
src/compute-client/Cargo.toml
src/compute-client/src/controller/instance.rs
src/controller-types/src/dyncfgs.rs
src/storage-controller/src/lib.rs
test/testdrive/wallclock-lag.td

This PR makes both controllers emit their pending wallclock lag introspection updates when time passes a minute boundary, instead of emitting them at some random moment every minute. This is meant to synchronize the two controllers, reducing the chance of inconsistent introspection data where lag spikes of dependent collections (e.g. a source and an index) are reported at different minutes.
To simplify the implementation, this PR includes two changes to reduce the complexity of the wallclock lag tracking code:
* It merges the feature flags controlling the wallclock lag recording interval (first commit).
* It factors out wallclock lag recording (as opposed to updating the in-memory tracking) into a separate method.
The two controllers can emit …

controller: record wallclock lag at minute boundaries

---

misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/version_list.py
test/legacy-upgrade/mzcompose.py

So that we don't have to keep it up to date manually.

upgrade tests: Automatically fetch latest LTS versions

---

src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/session.rs
test/sqllogictest/transactions.slt

INSERTS of non-constant values internally get sequenced as read-then-write queries, which clear transaction ops so disable the checks we normally have in place about mixing reads and writes in transactions.
Now, we check that a transaction is in a valid state when sequencing a read-then-write.
@def- Tests didn't catch this before.

adapter: don't allow implicit read-then-write inside transactions

---

src/persist-client/src/cfg.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/operators/shard_source.rs
src/persist-proc/src/lib.rs

- In a recent refactoring, I changed where `part.maybe_optimize` was called to be _after_ `bytes` and `is_inline` were captured... which means that we were incrementing the wrong metric in some cases. Embarassing!
- The `persist_record_compactions` flag has been on for several months with no issues, and we're building on that pattern now. Remove it.
Small issues noticed today.
These are two logically separate changes; feel free to tell me to make two separate PRs if you don't like it this way!

[persist] Fix a metric issue and clean up a flag

---

src/cluster/src/communication_v2.rs

Seen failing in https://buildkite.com/materialize/test/builds/102628#01965bf5-7f8f-4a16-9517-7e3a14da2699
Follow-up to https://github.com/MaterializeInc/materialize/pull/31982

cargo test: Bump timeout for test_create_sockets

---

test/testdrive/github-6942.td
test/testdrive/webhook.td

Seen failing in https://buildkite.com/materialize/nightly/builds/11914#019664fd-9b58-4c90-a37c-ddadfba34360
Follow-up to https://github.com/MaterializeInc/materialize/pull/32228

testdrive: Fix default-storage-size parameter

---

misc/helm-charts/operator/templates/deployment.yaml
misc/helm-charts/operator/tests/deployment_test.yaml
src/environmentd/src/environmentd/main.rs
src/license-keys/src/lib.rs
src/orchestratord/src/controller/materialize.rs
src/orchestratord/src/controller/materialize/environmentd.rs

we may need to make a new lts release from main at some point soon, and license key issuing isn't ready yet
once we get license key issuing working, we can revert this

allow disabling license key checks for now

---

misc/helm-charts/publish.sh

Saves one step in https://www.notion.so/materialize/Flexible-Deployment-Release-Test-Strategy-12113f48d37b80bc94f2f3341063310d

publish helm chart: Verify that the chart has been published

---

misc/python/materialize/redpanda_cloud.py

Noticed by @antiguru in https://materializeinc.slack.com/archives/C01LKF361MZ/p1745566243299639

cloud canary test: Don't print tokens

---

src/ore/src/panic.rs

The enhanced panic handler had a bug where it would report the panic to Sentry only after spawning a thread that could abort the process before the Sentry call had a chance to run, causing panics to be missing from Sentry. The fix is to do the Sentry reporting earlier.
Panics sometimes don't show up in Sentry. See [thread](https://materializeinc.slack.com/archives/C04DJT084KA/p1745592445518599).

ore: report panics to Sentry before aborting

---

src/storage-operators/src/persist_source.rs

At the moment, the persist source would only retain a row allocation if it had an MFP. The MFP needs to write into a different allocation, so it makes sense to recycle the allocation here. The non-MFP path didn't retain the allocation. This is suboptimal because subsequently we have to right-size another row allocation to decode into, which can involve $log n$ reallocations, where $n$ is the size of the row. Instead, clone the output and retain the probably right-sized row allocation.

Persist source: retain row allocation

---

src/compute/src/render/reduce.rs

https://github.com/MaterializeInc/database-issues/issues/9230
see: https://github.com/MaterializeInc/materialize/blob/be719a21a61b56b4afe9ee2852b84cb2b28fbd1c/src/repr/src/row.rs#L291

refactor reductionmonoid prevent clone of row on clone_from

---

.bazelrc
misc/bazel/cargo-gazelle/BUILD.bazel
misc/bazel/cargo-gazelle/src/config.rs
misc/bazel/cargo-gazelle/src/lib.rs
misc/bazel/cargo-gazelle/src/targets.rs
misc/bazel/platforms/BUILD.bazel
src/balancerd/BUILD.bazel
src/catalog-debug/BUILD.bazel
src/clusterd/BUILD.bazel
src/environmentd/BUILD.bazel
src/fivetran-destination/BUILD.bazel
src/frontegg-mock/BUILD.bazel
src/interchange/BUILD.bazel
src/kafka-util/BUILD.bazel
src/lsp-server/BUILD.bazel
src/materialized/BUILD.bazel
src/mz-debug/BUILD.bazel
src/mz/BUILD.bazel
src/orchestratord/BUILD.bazel
src/persist-cli/BUILD.bazel
src/pgtest/BUILD.bazel
src/s3-datagen/BUILD.bazel
src/sqllogictest/BUILD.bazel
src/testdrive/BUILD.bazel
test/metabase/smoketest/BUILD.bazel

This PR enables cross language LTO for our release builds, meaning function calls from external C dependencies like `libdecimal` can potentially get inlined into Rust code.
The way this works is when building our final binaries, e.g. `environmentd` and `clusterd`, we specify the `-Clinker-plugin-lto` flag to `rustc` which has our linker (`lld`) run the LTO passes instead of `rustc`. At which point all of our Rust and C code has been compiled to LLVM bitcode so to `lld` is free to optimize across languages.
This only works when building for Linux. Arguments that `rustc` passes to the linker when targetting macOS don't seem to be supported by `ld64.lld`? See https://github.com/rust-lang/rust/issues/60059 for some more investigation.
Faster runtime performance. 
The commits are broken down …

[bazel] cross language LTO

---

doc/user/content/ingest-data/kafka/_index.md
doc/user/content/ingest-data/kafka/kafka-self-hosted.md
doc/user/content/ingest-data/redpanda/_index.md

Running older versions than this may work, but we don't test for it, and we may have to break compat in the future. Write a policy down!
In recent Kafka sink work, we lost some time to figuring out whether we needed to maintain support for very old Kafka versions. Having an explicit policy here should help us move faster and give users more confidence that their deployment is expected to work.
All our hosted service guides are for services that keep users on fairly recent versions, so I've only added the explicit version requirement on the self-hosted guide.
As usual, feel free to edit the prose if it doesn't match the overall style!

Mention the supported Kafka version in the docs

---

src/persist-client/src/cli/inspect.rs
src/persist-client/src/fetch.rs
src/persist-types/src/part.rs
src/persist/src/indexed/encoding.rs

Instead of threading around byte arrays, we need to thread around ArrayIdx.
This would panic on any recent part. We also want to reduce our dependence on some of these old records-only APIs...
There's more to do in this vein, but it may have to wait for the next skunkwork...

[persist] Decode structured data in inspection CLI

---

src/adapter/src/coord/statement_logging.rs

https://github.com/MaterializeInc/database-issues/issues/9242

fix prepared statements should get different ids

---

misc/python/materialize/parallel_workload/action.py

Seen in https://buildkite.com/materialize/nightly/builds/11939#0196890a-0af4-46f5-bb66-08c054b6ed62
Green nightly run: https://buildkite.com/materialize/nightly/builds/11957#01969dc8-3d9a-40fe-bccd-f00824dee33d

parallel-workload: Update error message for webhook source creation

---

test/terraform/mzcompose.py

A lot of code has turned out to be very similar across the cloud providers, so no good reason to keep them separate anymore.

terraform test: Refactor

---

Cargo.lock
ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml
misc/python/materialize/checks/features.py
src/persist-cli/BUILD.bazel
src/persist-cli/Cargo.toml
src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/src/cache.rs
src/persist-client/src/cli/args.rs
src/persist/src/cfg.rs
src/persist/src/postgres.rs
test/persist/mzcompose.py
test/platform-checks/mzcompose.py

This PR adds some new queries to `PostgresConsensus` that are tuned against vanilla postgres to obtain row level locks as opposed to the table level locks that the current queries get. These new queries are only used if `persist_use_postgres_tuned_queries` is set to true, __and__ we detect we're running against vanilla Postgres. 
Locks acquired on `main`
```
pid  |       mode       | granted
-------+------------------+---------
21004 | AccessShareLock  | t
21004 | RowExclusiveLock | t
```
Locks acquired with the new feature enabled
```
pid  |       mode       | granted
-------+------------------+---------
21004 | RowShareLock     | t
21004 | RowExclusiveLock | t
```
It's not entirely clear that this improves performance, but some simulation testing seems to indicate that it does.
Also …

[persist] Postgres specific consensus queries

---

doc/developer/design/20250321_password_authentication.md

WIP Password auth design doc

---

Cargo.lock
src/arrow-util/src/reader.rs
src/compute/src/metrics.rs
src/compute/src/render.rs
src/compute/src/render/context.rs
src/compute/src/render/flat_map.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/reduce.rs
src/expr/src/relation/func.rs
src/pgcopy/src/copy.rs
src/repr/Cargo.toml
src/repr/src/adt/jsonb.rs
src/repr/src/row.rs

This PR removes the Rc indirection for the shared row and simplifies the API by not requiring the caller to explicitly mutably borrow the RefCell.
The constructor of the `SharedRow` is documented to panic if more than one instance is constructed. This allows us to use a single `Cell<Option<Row>>` as the contents of the thread local that gets replaced with `None` when someone gets the shared row and is put back when the `SharedRow` value is dropped.
https://github.com/MaterializeInc/database-issues/issues/9232

repr: store thread-local shared row inline

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/features.py
misc/python/materialize/checks/mzcompose_actions.py
test/platform-checks/mzcompose.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/32389

platform-checks: Switch to CockroachOrPostgresMetadata

---

ci/test/pipeline.template.yml

It is often the slowest test, and also runs in Nightly. Let's see how often it falls over.

ci: Remove feature benchmark from test pipeline

---

src/persist/src/azure.rs
src/persist/src/location.rs

This means that we can retry past this error instead of bailing out early. We observe it when first starting an environmentd right as storage is being created...
https://github.com/MaterializeInc/database-issues/issues/9253
There may be more errors that need the same treatment, but I think this is likely to solve this particular problem.
I'll kick off the same nightly test, but this seems a bit flaky... let me know if there's other testing you'd like to do.

Mark some azure HTTP errors as determinate

---

src/ore/Cargo.toml

Fix a warning caused by requiring a non-existent feature.

Ore does not have feature derivative

---

src/repr/src/adt/datetime.rs
test/sqllogictest/timestamp.slt

https://github.com/MaterializeInc/database-issues/issues/9236
see pg docs for full spec: https://www.postgresql.org/docs/12/datetime-input-rules.html

fix failing to parse timezones correctly

---

ci/builder/Dockerfile
ci/builder/requirements.txt
ci/deploy/pypi.py

Update pypi deployment to support pyproject.toml and mcp-materialize

---

doc/user/data/self_managed/latest_versions.yml

self-managed docs: Bump terraform versions too

---

ci/test/pipeline.template.yml

So that we can upload debuginfo to Polar Signals without having to tag
Also reduced the agent size, this shouldn't require many CPU/memory resources.

ci: Introduce a CI_UPLOAD_DEBUG_SYMBOLS env variable

---

src/storage/src/upsert.rs
src/storage/src/upsert_continual_feedback.rs

This PR fixes the correctness issue observed during concurrent execution of two upsert sources on multi-replica clusters.
The issue stems from a violation of a correctness proprety of the `drain_staged_input` function, that this PR now documents.
The diff is meant to be minimal to aid quick review and backporting but it does not make any progress towards simplifying the overal logic, which will be subsequent work.
When `drain_staged_input` is called in `DrainStyle::ToUpper` mode it drains all the upsert commands that are exactly at the timestamp of `persist_upper` and for each key it:
1. Keeps the command with the highest offset
2. Retrieves the current state from RocksDB
3. Produces a retraction of the current value if it was set
4. Produces an insertion of the new value.
In this mode …

storage: document and uphold upsert correctness property

---

Cargo.lock
src/workspace-hack/Cargo.toml

Fixes MaterializeInc/database-issues#9225

deps: update `dec` crate to 0.4.11

---

misc/python/materialize/cli/helm_chart_version_bump.py

Noticed by Kay in https://github.com/MaterializeInc/materialize/commit/14c73a6f8e175b2b64214f02b665cc79458dc48b#r156529641

helm-chart: Bump version of orchestratord better

---

ci/plugins/mzcompose/hooks/pre-exit

So that we can catch them even if the test succeeds

terraform tests: Check logs for errors and panics

---

doc/developer/emulator.md

missing documentation for how to debug emulator locally whilst running in docker.

doc: add materialize emulator debugging document

---

src/environmentd/tests/pgwire.rs
src/expr/src/relation.rs
src/sql/src/plan/error.rs
src/sql/src/plan/explain/text.rs
src/sql/src/plan/hir.rs
src/sql/src/plan/lowering.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
test/sqllogictest/cockroach/aggregate.slt
test/sqllogictest/explain/optimized_plan_as_text.slt
test/sqllogictest/explain/raw_plan_as_json.slt
test/sqllogictest/explain/raw_plan_as_text.slt
test/sqllogictest/order_by.slt
test/sqllogictest/window_funcs.slt

This PR adds support for prepared statement parameters in `OFFSET` clauses. It follows a similar approach as https://github.com/MaterializeInc/materialize/pull/25221 did for `LIMIT` expressions: We make `RowSetFinishing` generic over the type of the offset, so that the planner can hold the finishing's offset as an `HirScalarExpr` long enough to call `bind_parameters` on it.
I suggest starting the review from `plan_query_inner` in `query.rs`, since that is the first thing that runs from among all the touched code. The other important thing is in `plan_select_inner`. And then all the other things are just in service of these two things.
For the type of the `OFFSET` clause's expression, I went with `ScalarType::Int64`, i.e., `bigint` for now, as [discussed on …

adapter: Support parameters in OFFSET clause

---

misc/python/materialize/checks/all_checks/alter_connection.py
src/adapter/src/catalog/apply.rs
src/catalog/src/memory/objects.rs
src/sql/src/names.rs

This PR fixes an issue with our `CONNECTION` objects. `CONNECTION`s can depend on one another and be `ALTER`-ed. This means that a connection can depend on another object with an ID greater than its own which breaks some of our assumptions
The fix here is to do a topological sort of `CONNECTION` objects when applying updates.
Fix a known panic.

catalog: fix the ordering of `CONNECTION` objects when bootstrapping

---

misc/python/materialize/checks/all_checks/alter_connection.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/32438
Seen failing in https://buildkite.com/materialize/test/builds/103327#0196b25b-e03c-4e3e-b6d8-c9aad8cff273

platform-checks : Fix AlterConnectionDependencyOrder

---

src/adapter/src/coord.rs

Add some additional logging to help diagnose a CI error.
https://github.com/MaterializeInc/database-issues/issues/9253
- In both examples of the linked logs, we get `startup: coordinator init: bootstrap: postamble beginning`, but never `postamble ending`, so we are highly likely to be hitting the error in this phase of bootstrap.
- The only operations that can return an err during the postamble are these VPC management APIs.
- The error log contains `ApiError`, which can be emitted by the kube client error handling; and `storage is (re)initializing`, which is a string found in the k8s source.
So I think it's pretty likely that the error is coming from around here. Hopefully the logs will help narrow it down.

Add some additional context to vpc endpoint errors

---

ci/test/pipeline.template.yml

Uses llvm-dwarfdump which requires a lot of memory
Seen in https://buildkite.com/materialize/test/builds/103333#0196b647-0dfc-4130-958f-286040d2036f
Regression introduced in https://github.com/MaterializeInc/materialize/pull/32433
Verified that we have enough memory now: https://buildkite.com/materialize/test/builds/103379

ci: Bump agent size for debug symbol upload

---

ci/nightly/pipeline.template.yml
test/limits/mzcompose.py

Seen in https://buildkite.com/materialize/nightly/builds/12000
Nothing too concerning, a flaky OoM and query timeout.

ci: Fix nightly failures (2025-05-12)

---

src/environmentd/tests/pgwire.rs
src/sql/src/plan/hir.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs

This PR is a little bit of spring cleaning: It removes `bind_parameter` calls and related wiring from the planning of statement types that can't be made into prepared statements (DDL and EXPLAIN TIMESTAMP). Note that Postgres also doesn't support preparing DDL.
However, even for these statements, we still need to check that there are no parameters in them. E.g., if the user writes
```
CREATE VIEW v AS SELECT $1
```
then we need to do _something_ about that `$1`. That something used to be `bind_parameters` complaining that `there is no parameter $1`. After the PR we print a more specific error msg: `views cannot have parameters`.
Additionally, the PR removes the `bind_parameters` fn from `AggregateExpr`, because it was unused, and I can't imagine a use for it.
* Spring cleaning, but I also …

Remove `bind_parameter` calls from statement types that don't support `PREPARE`

---

src/adapter/src/error.rs
src/environmentd/tests/pgwire.rs
src/sql/src/plan/error.rs
src/sql/src/plan/hir.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs

As it says on the tin.
* This PR fixes a recognized bug: an old TODO in a code comment, see diff. Also, part of https://github.com/MaterializeInc/database-issues/issues/4468

Use `SqlState::UNDEFINED_PARAMETER` for certain parameter errors

---

src/sql/src/plan/query.rs
src/sql/src/plan/statement/dml.rs
test/sqllogictest/prepare.slt

This PR makes us support prepared statement parameters in `RETURNING`.
There is a `prepare.slt` that we inherited from Cockroach, but the whole test file is currently turned off, because there are too many things there that we don't support. I've been trying to see what it would take to turn it on, and parameters in `RETURNING` is one of the unsupported things, and it seemed easy enough to add support for, so I did it quickly. 

adapter: Allow parameters in `RETURNING`

---

src/expr-parser/src/parser.rs
src/expr/src/scalar/func.rs
src/expr/src/scalar/func/binary.rs
src/expr/src/scalar/snapshots/mz_expr__scalar__func__decode.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__left.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__like_escape.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__mz_acl_item_contains_privilege.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__parse_ident.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__position.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__pretty_sql.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__right.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__starts_with.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__text_concat_binary.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__timezone_offset.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__trim.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__trim_leading.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__trim_trailing.snap

Includes:
* Decode
* Left
* LikeEscape
* MzAclItemContainsPrivilege
* ParseIdent
* PrettySql
* Right
* StartsWith
* TextConcat
* TimezoneOffset
* Trim{Leading, Trailing, }
As usual, the new functionality is tested, but not yet used.

Convert more binary funcs to the sqlfunc macro

---

src/adapter/src/coord/sql.rs
src/adapter/src/coord/statement_logging.rs
src/adapter/src/session.rs
src/sql/src/plan.rs
src/sql/src/plan/error.rs
src/sql/src/plan/hir.rs
src/sql/src/plan/query.rs
src/sql/src/plan/side_effecting_func.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/dml.rs
test/sqllogictest/order_by.slt

This is on top of https://github.com/MaterializeInc/materialize/pull/32457.
I recommend reviewing the commits separately.
This PR makes us try to automatically cast prepared statement parameters that are passed to `EXECUTE`, the same way Postgres does (https://github.com/MaterializeInc/database-issues/issues/9266).
`plan_params` used to check for exact type equality. We now do a `plan_hypothetical_cast` in `plan_params`, then save both the actually passed type and the expected type. Then, `bind_parameters` actually plans the cast. For this, I needed to pass in the `StatementContext` and the `QueryLifetime` to `bind_params`.
* This PR addresses a Postgres incompatibility: https://github.com/MaterializeInc/database-issues/issues/9266

Automatically cast parameters of `EXECUTE`

---

src/cloud-resources/src/crd/materialize.rs

In the rare case that we can't parse a version from the image ref, log an error so we can debug the issue better.
I'm also happy to make this just a `tracing::warn!` if folks prefer, the `soft_assert` seemed nice though since this should(?) be rare.
Some minimum version checks are failing open and it would be nice to know if it's because the image ref can't be parsed.

[cloud-resources] soft assert we can parse image references

---

src/compute/src/server.rs

Reconciliation failures due to incompatible dataflow plans are sometimes hard to debug, so this PR adds a new log that dumps the full plans.
The specific motivation is debugging https://github.com/MaterializeInc/database-issues/issues/9273. If it turns out that the log is too noisy, e.g. because incompatible plans happen a lot in the wild for non-bug reasons, we may decide to remove it again.
* This PR helps investigating a recognized bug.
Advances https://github.com/MaterializeInc/database-issues/issues/9273

compute: more logging on dataflow reconciliation failures

---

src/expr/src/scalar.rs
test/sqllogictest/list.slt

Fixes a bug that @aljoscha [ran into](https://materializeinc.slack.com/archives/C08ACQNGSQK/p1747168112195079?thread_ts=1747159620.609509&cid=C08ACQNGSQK): When `reduce_list_create_list_index_literal` removes a literal index, it removes one layer of `ListCreate`s by partial evaluation, and thus all the outer `ListCreate`s lose one list layer, but this was not reflected in their types.

Fix types in `reduce_list_create_list_index_literal`

---

src/sql/src/plan/typeconv.rs
test/sqllogictest/prepare.slt

Fixes a panic when `plan_coerce` is called twice on a parameter. This typically happens when there is a function call whose more than one argument involves the same prepared statement.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/9268

Don't panic when the same parameter is coerced twice

---

doc/user/content/sql/alter-cluster.md

Fix cost calculation rendering issue where it currently renders as shown in image below:
instead of `cluster size * replication factor`

docs: fix rendering issue

---

test/terraform/aws-persistent/main.tf
test/terraform/aws-temporary/main.tf
test/terraform/aws-upgrade/main.tf
test/terraform/azure-temporary/main.tf
test/terraform/gcp-temporary/main.tf

Manually because https://buildkite.com/materialize/publish-helm-charts/builds/46#0196d15d-62fc-4a0d-8475-feeadbaa113c failed

terraform tests: Bump to AWS v0.4.5, GCP v0.4.2, Azure v0.4.2

---

misc/helm-charts/publish.sh

Seen in https://buildkite.com/materialize/publish-helm-charts/builds/46#0196d15d-62fc-4a0d-8475-feeadbaa113c

helm-chart publish: Fix git push

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/all_checks/cluster.py

Based on failures in https://buildkite.com/materialize/nightly/builds/12017

ci: Nightly fixes (2025-05-15)

---

test/testdrive/introspection-sources.td

This PR fixes two sources of flakiness in `introspection-sources.td`:
* Removes exact checks for batch counts in `mz_arrangement_sizes`. The number of batches is a DD implementation detail that's subject to change. The affected tests really only care about the number of rows anyway.
* Removes an `UP TO` option that made a counter source shut down after some amount of time. The source shut down causes the source to advance to the empty frontier, which causes the operators of downstream indexes to shut down, which removes these indexes from `mz_dataflow_arrangement_sizes`, making queries for them fail.
Fixes https://github.com/MaterializeInc/database-issues/issues/9261

test: reduce flakiness in introspection-sources.td

---

src/controller/src/clusters.rs
src/storage-client/src/controller.rs
src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs

Due to an oversight the controller would initialize the state tracked for new compute clusters with the known workload class, but omit doing the same for storage clusters. As a result, metrics and wallclock lag measurements would sometimes miss their `workload_class` annotations after an envd restart.

controller: initialize workload class for new storage clusters

---

Cargo.lock
doc/user/data/mz-debug/emulator_options.yml
doc/user/data/mz-debug/mz_debug_option.yml
doc/user/data/mz-debug/self_managed_options.yml
src/mz-debug/BUILD.bazel
src/mz-debug/Cargo.toml
src/mz-debug/src/docker_dumper.rs
src/mz-debug/src/internal_http_dumper.rs
src/mz-debug/src/k8s_dumper.rs
src/mz-debug/src/kubectl_port_forwarder.rs
src/mz-debug/src/main.rs
src/mz-debug/src/system_catalog_dumper.rs
src/mz-debug/src/utils.rs

See commit messages for details
"Scrape prometheus metrics" and "Scrape profiling" from https://github.com/MaterializeInc/database-issues/issues/8908

Add internal profiling to debug tool

---

src/adapter/src/optimize/copy_to.rs
src/adapter/src/optimize/materialized_view.rs
src/adapter/src/optimize/peek.rs
src/adapter/src/optimize/subscribe.rs
src/adapter/src/optimize/view.rs
src/transform/src/fusion/filter.rs
src/transform/src/lib.rs
src/transform/src/predicate_pushdown.rs
src/transform/tests/test_runner.rs
src/transform/tests/test_transforms.rs

This PR makes us do typechecking also in local optimization. Not doing this earlier was the reason that we did not catch https://github.com/MaterializeInc/materialize/pull/32486.
(Normally, `optimize_dataflow_relations` sets the `GlobalId` in the `TransformCtx`, but `optimize_dataflow_relations` is not involved in the local optimization.)
This should now produce errors in `list.slt` (because https://github.com/MaterializeInc/materialize/pull/32486 is not fixed on this branch), but I'm not sure if this will fail CI. Running CI with the PR in draft to find out. I'm also running all slts locally with an explicit panic instead of the error, and with https://github.com/MaterializeInc/materialize/pull/32486 cherry-picked, to see if any other type errors show up due to doing typechecking in more …

optimizer: Typecheck also in local optimization

---

ci/builder/requirements.txt

This reverts https://github.com/MaterializeInc/materialize/pull/32342
Reported by @SangJunBak  in https://materializeinc.slack.com/archives/C01LKF361MZ/p1747316191235699
Medium term we'll get rid of the agent, most likely.

build(deps): Downgrade pyarrow to 19.0.1 again

---

src/ore/src/future.rs

Trying to display a `TimeoutError::Inner` value causes a stack overflow due to infinite recursion in the `Display` implementation.

ore: fix infinite recursion in TimeoutError Display impl

---

misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/git.py
misc/python/materialize/version_list.py
test/legacy-upgrade/mzcompose.py

Seen failing in https://buildkite.com/materialize/nightly/builds/12016

upgrade tests: Fix upgrade tests on old versions

---

src/transform/src/typecheck.rs

We were invoking `tracing::error!` rathe than `soft_panic_or_log!`. @ggevay and I couldn't reconstruct why that is: the penultimate commit of #18666 turned a soft panic into an error message under the auspices of simplifying error messages.
The fix for #32486 somehow didn't fail in CI, leading us to discover this oversight.

[optimizer] typechecking errors should panic in CI

---

src/persist-client/src/batch.proto
src/persist-client/src/fetch.rs
src/persist-client/src/internal/encoding.rs
src/persist-client/src/lib.rs
src/persist-client/src/operators/shard_source.rs
src/persist-client/src/read.rs
src/storage-operators/src/persist_source.rs

This bundles together a few related cleanups for the leased part:
- We had a few proto types that were only useful for short-lived exchanges in the source. We encode those with serde now. (While continuing to encode long-lived data like the hollow batch as proto.)
- As part of the batch fetching, we created leased parts that didn't actually have leases attached, then consumed them immediately. This switches the fetching code to use the exchangeable part instead and makes leases required in all other cases.
Previously-unspecified cleanup.

[persist] Lease cleanup

---

src/sql-server-util/src/desc.proto
src/sql-server-util/src/desc.rs
src/sql-server-util/src/inspect.rs
src/sql/src/pure/error.rs
src/sql/src/pure/sql_server.rs
test/sql-server-cdc/25-constraints.td

This PR updates the metadata we fetch for SQL Server tables to include which columns are primary keys and plumb this information into Materialize.
While Materialize does not enforce primary keys, we can trust the upstream system and having the Unique constraint in Materialize can improve query planning
Fixes https://github.com/MaterializeInc/database-issues/issues/9210

[sql_server] handle primary keys from SQL Server

---

ci/mkpipeline.py
ci/nightly/pipeline.template.yml
misc/bazel/platforms/BUILD.bazel

Taken from https://github.com/MaterializeInc/materialize/pull/32499

ci: Add ASan build in nightly and fix sanitizer agent scaling

---

WORKSPACE

This PR updates the `clang` toolchain we use to `19.1.6-2` which statically links `libxml` to reduce the number of dynamically linked dependencies and thus makes the toolchain more portable.
Before:
```
$ ldd lld
linux-vdso.so.1 (0x00007c8767a3d000)
libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007c876121e000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007c876793e000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007c8767910000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007c8761000000)
/lib64/ld-linux-x86-64.so.2 (0x00007c8767a3f000)
libicuuc.so.74 => /lib/x86_64-linux-gnu/libicuuc.so.74 (0x00007c8760c00000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007c87678f2000)
liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007c87678c0000) …
```

bazel: Use `clang 19.1.6-2`

---

src/ore/src/netio/socket.rs

This PR adds support for splitting `mz_ore::netio::Stream` into a read and a write half, so reading from and writing to a connection can be done independently.
Split out of the work that adds the new cluster transport protocol (https://github.com/MaterializeInc/materialize/pull/32330). 
Part of https://github.com/MaterializeInc/database-issues/issues/5038

ore/netio: support splitting streams into tx/rx halves

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
ci/test/pipeline.template.yml

Saves us some money for CI runs without much of a downside, tests didn't seem noticably slower, but maybe a few will still need larger agents.

ci: Half the agent sizes (using new zram)

---

doc/developer/guide.md

Noticed by Frank in https://materializeinc.slack.com/archives/C0246GEHL8N/p1747843735990399

dev docs: Make it clear that submodules are required

---

ci/plugins/cloudtest/hooks/pre-exit
ci/plugins/mzcompose/hooks/pre-exit
misc/python/materialize/cli/ci_annotate_errors.py

Demo run: https://buildkite.com/materialize/test/builds/103821
This allows us to use https://ci-failures.dev.materialize.com/?key=test-failures to find patterns in timeouts.

ci: Annotate timeouts

---

src/storage-types/src/dyncfgs.rs

RLU is now switched on everywhere (CI, staging, prod), so update the config defaults to make sure its also switched on by default locally.
* This PR brings the local config closer to the prod config.

storage: update RLU dyncfg defaults

---

ci/release-qualification/pipeline.template.yml

Based on failures seen in https://buildkite.com/materialize/release-qualification/builds/866
Follow-up to https://github.com/MaterializeInc/materialize/pull/32553
Test run: https://buildkite.com/materialize/release-qualification/builds/867

ci: Bump some agent sizes in release qualification

---

test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_dataflow.slt
test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_folding.slt

It's not clear what this test was supposed to test, and is flaky.
https://materializeinc.slack.com/archives/CTESPM7FU/p1748365186543639?thread_ts=1748363700.222229&cid=CTESPM7FU
cc @def-

tests: Skip `5_repeat_row_dataflow.slt` and `5_repeat_row_folding.slt`

---

doc/user/content/ingest-data/_index.md
doc/user/content/ingest-data/troubleshooting.md
doc/user/shared-content/resize-cluster-for-snapshotting.md
doc/user/shared-content/snapshotting-cluster-size-postgres.md

Add answer to common questions about snapshotting

Snapshot FAQ update

---

.bazelrc
misc/python/materialize/mzbuild.py

The x86 ASan build is currently broken because it OOMs. For CI builds we use a RAM backed temp filesystem for the Bazel sandbox to get maximum performance, but the intermediate artifacts for the ASan build appear to large to fit in RAM.
Fix x86 ASan

[bazel] move sanitizer builds off the RAM backed FS

---

src/adapter/src/catalog/builtin_table_updates.rs
src/arrow-util/src/reader.rs
src/compute/src/render/sinks.rs
src/interchange/src/encode.rs
src/interchange/src/json.rs
src/repr/src/relation.rs
src/repr/src/stats.rs
src/sql/src/plan/error.rs
src/sql/src/plan/notice.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/typeconv.rs
src/sqllogictest/src/runner.rs

ColumnName currently owns a string, but doesn't need mutable access in all but one places. This change alters it to a boxed str, which reduces the size from 24 to 16 bytes. It also adds a deref implementation, which allows us to remove some of the `as_str` calls.
No urgency to merge it, just capturing what I found in my local changes.

ColumnName wraps boxed string

---

src/catalog/src/builtin.rs
src/cluster-client/src/metrics.rs
src/compute-client/src/controller/instance.rs
src/ore/src/cast.rs
src/storage-client/src/controller.rs
src/storage-client/src/healthcheck.rs
src/storage-controller/src/lib.rs
test/testdrive/wallclock-lag.td

This PR changes the wallclock lag measurement logic in the two controllers to emit "undefined" lag measurements for collections that are unreadable, i.e., contain no readable times. The intention is to avoid glitches where wallclock lag for unhydrated collections is nonsensical (e.g. 55 years).
The "undefined" value is represented differently for introspection and for Prometheus metrics. For introspection, we can use the SQL `NULL` value, but Prometheus metrics values are integers, so we have to use `u64::MAX` instead.
Note that this changes the schema of a builtin source and deploying it will truncate any existing wallclock lag measurements. The current thinking is that this is fine and it's not worth spending time on implementing a proper migration. Feel free to weigh in on [this Slack …

controller: emit undefined lag for unreadable collections

---

misc/python/materialize/cloudtest/k8s/minio.py

The kubernetes examples repo moved almost everything into an `_archived` directory https://github.com/kubernetes/examples/commit/3ae9fb0d13e8c9c952c862d38dfbc03a85ecb7c6 .
This PR locks our minio install yamls to the commit before they were moved.
We should eventually swap to some supported yamls and/or reevaluate our use of minio, but for now this should fix the nightly tests.
Many nightly tests are failing.
```
failed on setup with "subprocess.CalledProcessError: Command '['kubectl', '--context', 'kind-mzcloud', '--namespace', 'default', 'create', '-f', 'https://raw.githubusercontent.com/kubernetes/examples/master/staging/storage/minio/minio-standalone-deployment.yaml']' returned non-zero exit status 1."
```

Lock minio install yamls to commit before they moved

---

src/transform/src/equivalence_propagation.rs
test/sqllogictest/transform/column_knowledge.slt

Fixes https://github.com/MaterializeInc/database-issues/issues/9319
`literal_domination` is called on pairs of expressions where `MSE::reduce` was called on the first one to get the second one. `MSE::reduce` can easily change the number of arguments to a variadic function call, e.g., for `coalesce`  https://github.com/MaterializeInc/materialize/blob/4f729296d579c940eb04fd40bbdc7009b7e7ae4d/src/expr/src/scalar.rs#L1205-L1214
This PR adds an extra check for this situation.

optimizer: Fix `literal_domination` when `MSE::reduce` changes the number of args of a variadic call

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/persist-client/src/internal/compact.rs
src/persist-types/src/txn.rs
src/txn-wal/src/txn_cache.rs

- Make the code more robust to aggressive compaction limits. (Instead of panicking, we fall back to the already-existing code for when we can't fit two runs in memory.)
- Exercise a wider range of configs in CI.
- Fix a `txn-wal` bug, which could be triggered when data had undergone compaction but wasn't globally consolidated. (Which can happen when memory limits are too small to compact all parts in one go.)
Turns out we're missing some test coverage in this area!
I'd love a review from a `txn-wal` expert, since I'm not that familiar with the code there.

[persist] Lower some thresholds for persist in CI

---

src/compute-client/src/service.rs
src/storage-client/src/client.rs

Resetting the `PartitionedComputeState` upon seeing a `CreateTimely` command is not necessary. Both sides of the controller-replica connections throw away their existing partitioned state and create a new instance when the connection fails, implicitly resetting the state.
Pulled out from https://github.com/MaterializeInc/materialize/pull/31710.

compute: don't reset PartitionedComputeState

---

ci/deploy_website/website.sh

Noticed in https://materializeinc.slack.com/archives/CL6H464R4/p1748891975438179
I believe this never worked and we just didn't notice.

website deploy: Fix shortlink overrides

---

misc/bazel/c_deps/rust-sys/BUILD.librdkafka.bazel

[librdkafka uses asserts to handle runtime errors.](https://github.com/confluentinc/librdkafka/issues/5099) If asserts are disabled, runtime errors can turn into memory safety bugs instead, which is something we should avoid.
Fixes https://github.com/MaterializeInc/database-issues/issues/9313

build: don't disable asserts in librdkafka

---

src/compute/src/compute_state.rs
src/compute/src/compute_state/peek_result_iterator.rs

The original motivation for this is so that the code that extracts peek results can be re-used in
https://github.com/MaterializeInc/database-issues/issues/9180, where we want to use a different transport for sending back peek responses but still need to read them out of arrangements the same way.
The nice side effect is that we separate extracting the result from the logic that accumulates it in a response for sending it back. Which leads to clearer separation.
Work towards https://github.com/MaterializeInc/database-issues/issues/9180

compute: factor out PeekResultIterator

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
ci/test/pipeline.template.yml

Undoes part of https://github.com/MaterializeInc/materialize/pull/32553 based on remaining flakes uncovered last week
@ggevay Sorry for all the test failures last week!

ci: Further changes as follow up to smaller agents

---

src/storage/src/source/postgres/snapshot.rs

Compiler infers i32 as the target type for the parse command, but it should be i64 (bigint).
fixes https://github.com/MaterializeInc/incidents-and-escalations/issues/268

Explicitly parse row estimate count as i64

---

misc/python/materialize/checks/all_checks/pg_cdc.py

This PR adds some negative accumulation checks in a flaking test, so that we can narrow down where the problem is. If it is inside the sources, then the newly added check will fail.
See
https://materializeinc.slack.com/archives/C08ACQNGSQK/p1748952911361349?thread_ts=1748947701.910469&cid=C08ACQNGSQK

tests: Add check for negative accumulations in `pg_cdc.py`

---

misc/images/ubuntu-base/Dockerfile

Noticed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1748528935835869

mzbuild: Fix ubuntu mirror replacement

---

src/storage/src/source/postgres/snapshot.rs

Our default snapshot size determination strategy is to use the table statistics in pg instead of performing a `SELECT COUNT(*)` on the table.
This saves resources from the upstream database since it only reads a couple of rows from the statistics table at the expense of accuracy.
This PR silences an error that only makes sense when the `COUNT(*)` strategy is used.

storage/pg: only report snapshot size error in strict mode

---

test/zippy/mzcompose.py

Previously we always used seed=1, nightly run: https://buildkite.com/materialize/nightly/builds/12188

zippy: Use random seeds

---

misc/python/materialize/checks/all_checks/sink.py

Seen flaking in https://buildkite.com/materialize/nightly/builds/12186#_

platform-checks: Bump sleep in sink test

---

src/adapter/src/catalog/builtin_table_updates.rs
src/catalog/src/config.rs
src/controller/src/clusters.rs
src/orchestrator-kubernetes/src/lib.rs
src/orchestrator/src/lib.rs

Add a `memory_request` property to replica allocations. While we normally set request to the limit to enforce guaranteed QoS scheduling, setting a separate request would allow us to switch to a lower QoS that would be compatible with swap.
Fixes MaterializeInc/database-issues/issues/9328
Context: https://kubernetes.io/blog/2025/03/25/swap-linux-improvements/

Add memory-request replica property

---

src/adapter/src/metrics.rs
src/pgwire/src/protocol.rs
test/cluster/mzcompose.py

This PR implements the next part of https://github.com/MaterializeInc/materialize/pull/32504, namely the following two metrics:
- parsing time
- processing time for the various pgwire messages to cover the Extended Query flow.
(I'm planning one more PR, which would add a metric for time between first result byte sent and last result byte sent. That one is somewhat less important, so I'd like to get just the above two merged first.)

Metrics for query lifecycle

---

Cargo.toml
WORKSPACE
bin/lint-versions
misc/bazel/c_deps/rust-sys/BUILD.rocksdb.bazel
misc/bazel/rust_deps/cxxbridge-cmd/Cargo.cxxbridge-cmd.lock
misc/python/materialize/cli/gen-lints.py
misc/wasm/Cargo.toml
src/frontegg-auth/src/auth.rs
src/persist-client/src/internal/state.rs

This PR upgrades Materialize to use Rust 1.87 ~~and a recent nightly~~, and fixes the resulting clippy lint errors.
Note that Rust 1.87 is particularly exciting because it fixes [the channel use-after-free bug that Petros found](https://materialize.com/blog/rust-concurrency-bug-unbounded-channels/).
* This PR updates our Rust version.

Upgrade to Rust 1.87

---

doc/user/content/sql/execute.md

This goes with
https://github.com/MaterializeInc/materialize/pull/32463 (already released) and
https://github.com/MaterializeInc/www/pull/1459

docs: Mention `EXECUTE` parameter casting

---

src/sql/src/plan/typeconv.rs

We detect a few scalar types that can convert into jsonb's numeric representation, but types we don't explicitly match are converted to strings.
Todo:
1. add tests that cover these cases. The user reported error was for `select jsonb_build_object('data', count(*)) from ..`.
2. add exhaustive matches, to avoid missing cases like this in the future.
Putting up without this work to raise for discussion. Specifically, the code comments say
```
///   * All numeric types are converted to `Float64`s, then become JSON numbers.
```
which .. isn't actually what happens (they are directly converted to `Numeric { max_scale: None }`). If it is important that something very close to that happens we should discuss, but we already convert `Numeric`, which subsumes all of our integer types, into `Numeric` …

Broaden types converted to jsonb numeric

---

ci/builder/Dockerfile
doc/developer/cloudtest.md
misc/kind/cluster.yaml
misc/scratch/provision.bash

* Bumps kind to v0.29.0.
* Sets all kind node images to v1.31.x to match cloud.
This is needed to handle newer kind versions, which will use a newer version for the nodes without a version set.
There is no version that supports both v0.29.x and v0.33.x nodes.
Keep up to date.
Users with newer kind releases cannot run cloudtest, as our kind cluster.yaml does not specify versions for all nodes. Nodes that are unspecified will use the latest version supported by kind, which is not compatible with other nodes on 1.29. Version 1.29 is also out of support, and our cloud product is mostly on 1.31, so lets use that one. The v0.14.0 kind is ancient, and doesn't support 1.31, so we also need to bump that.

Bump kind to v0.29.0 and set all node images to v1.31.x

---

ci/test/pipeline.template.yml

See https://materializeinc.slack.com/archives/C01LKF361MZ/p1749544311836399

ci: Always upload debug symbols

---

src/orchestrator-kubernetes/src/lib.rs

The new code for collecting disk metrics from orchestrated processes is too liberal in its use of unwraps. Specifically, it is possible for the get-service call to fail, in which case the unwrap on that call would panic environmentd.
This is fixed by returning an error instead. The `get_disk_metrics` function contained two additional unwraps, which are replaced as well. They might be fine, but better to be safe than sorry.
Fixes https://github.com/MaterializeInc/database-issues/issues/9364
There are a bunch of other unwraps in the orchestrator code. They are probably fine, based on that we don't see them triggering in production. But they subconsciously encourage use of unwraps in adjacent code where they might not be fine, so we should consider removing …

k8s: don't unwrap when getting disk metrics

---

misc/python/materialize/checks/all_checks/sink.py
misc/python/materialize/checks/all_checks/webhook.py
misc/python/materialize/parallel_workload/action.py
src/adapter/src/coord/sequencer/inner.rs
src/sql/src/plan/statement/ddl.rs
test/testdrive/webhook.td

The restriction was artificial, webhooks don't actually run on clusters.
Implements https://github.com/MaterializeInc/database-issues/issues/9181
@def- Do we want more than this in terms of testing?

adapter,storage: allow webhook sources on multi-replica clusters

---

misc/kind/cluster-node-recovery-test.yaml

Follow-up to https://github.com/MaterializeInc/materialize/pull/32694 Failures seen in https://buildkite.com/materialize/nightly/builds/12268#01975c36-7adf-4ace-9e81-67d43af9c4f8
> this version of kubeadm only supports deploying clusters with the control plane version >= 1.32.0. Current version: v1.29.7
Test run: https://buildkite.com/materialize/nightly/builds/12271

k8s recovery tests: Bump kindest/node to v1.33.1

---

test/terraform/mzcompose.py

Always use latest orchestratord version
Failure seen in https://buildkite.com/materialize/nightly/builds/12268#01975c2f-c9c9-4bbd-93ea-ec42d60726bc
```
$ kubectl logs -n materialize pod/aws-upgrade-dev-materialize-operator-77557b756-qrvzr --all-containers=true
error: unexpected argument '--disable-license-key-checks' found
```
Test run: https://buildkite.com/materialize/nightly/builds/12272

terraform test: Fix upgrade test

---

misc/kind/cluster-node-recovery-test.yaml

Explicitly set the node image for all kind nodes in the cluster node recovery tests.
If not specified, kind will choose the latest node image supported by that kind version. This is a moving target if developers have different versions of kind, and can just fail if we set the node image for some nodes but not others. If the version set for some nodes is old, the auto-selected version for the nodes not set may be more than one minor version newer than the one that was explicitly set, which is not supported by kubeadm (the kubeadm version is chosen by kind to be the version of the highest node version in the cluster).
This is a follow up to https://github.com/MaterializeInc/materialize/pull/32710 which should prevent this failure in the future …

Cluster node recovery test, set kind node image for all nodes.

---

src/compute/src/extensions/arrange.rs
src/compute/src/extensions/reduce.rs
src/compute/src/render.rs
src/compute/src/render/context.rs
src/compute/src/render/errors.rs
src/compute/src/render/flat_map.rs
src/compute/src/render/join/delta_join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/join/mz_join_core.rs
src/compute/src/render/reduce.rs
src/compute/src/render/sinks.rs
src/compute/src/render/threshold.rs
src/compute/src/render/top_k.rs
src/compute/src/typedefs.rs

Introduce `MzData` complementing other data traits, and constraining implementors to support columnation and columnar, with the right constraints on the GATs. Introduce a `MzTimestamp` extending `MzData`. This allows us to clean up and simplify some type definitions used throughout rendering.

Clean up type constraints in compute, introduce wrapper traits

---

ci/test/dev_tag.py
ci/test/pipeline.template.yml

Required for https://materializeinc.slack.com/archives/C0914BQ0H5G/p1749718347200649
Test run: https://buildkite.com/materialize/test/builds/104643

ci: Tag sanitizer builds too

---

src/orchestratord/src/controller/materialize/environmentd.rs

Removes duplicate license key volume.
We duplicated this code somehow, and this one doesn't even have the correct `if` statement.
The correct code is at [line 1249](https://github.com/MaterializeInc/materialize/pull/32724/files#diff-4882726600268ef946ee674ccfd290e9af8f8a7ff0cf8b7f4da2287eee7bc68fR1249-R1277).
Orchestratord testing is out of scope for this PR. Discussion about how to test it better at https://materializeinc.slack.com/archives/C07PN7KSB0T/p1749639293686619

Remove duplicate license key volume

---

ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml

Based on recent runs: https://buildkite.com/materialize/test/builds/104624 & https://buildkite.com/materialize/nightly/builds/12300

ci: Disable some further steps during sanitizer runs

---

misc/python/materialize/mzcompose/services/redpanda.py
test/kafka-matrix/mzcompose.py

Failure seen in https://buildkite.com/materialize/nightly/builds/12296#01976155-4cbe-49db-a288-dd7b1b357f0b
Test run: https://buildkite.com/materialize/nightly/builds/12303

kafka tests: Update available versions for Redpanda and CP

---

test/bounded-memory/mzcompose.py

Follow up to persist incident, we have large ingestions and restarts in this test
Test run: https://buildkite.com/materialize/nightly/builds/12292

bounded-memory test: Check table from persist too, not just indexed view

---

src/adapter/src/flags.rs
src/sql/src/session/vars.rs
src/sql/src/session/vars/definitions.rs
src/storage-types/src/parameters.proto
src/storage-types/src/parameters.rs
src/storage/src/metrics/source/postgres.rs
src/storage/src/source/postgres/snapshot.rs

We have recently seen cases where the exact count of rows is problematic when the target table contains many rows. The value of this exact count is not worth the resources spent since the result only informs the snapshot progress reporting.
This PR changes the logic to always collect the estimated number of rows first and if it's below a threshold (currently one million) attempt an exact count as well. Otherwise we just use the estimate.
I retained the flag to compeltely disable exact counting in case the current threshold is problematic.
This PR also removes the assertion that the total number of ingested rows match the number of counted rows. This assertion effectively checks that PostgreSQL transactions work, which doesn't seem very useful and due to other reasons cause CI flakes. See …

storage/pg: attempt exact snapshot count only when estimate is low enough

---

misc/python/materialize/mzcompose/__init__.py

Otherwise some tests get wrong results
Fixes: https://github.com/MaterializeInc/database-issues/issues/9378

tests: Reduce source interval ranges

---

WORKSPACE
bin/ci-builder

Pulls in the double-free fix for `std::sync::mpsc` unbounded channels.

build: upgrade to Rust nightly 2025-06-04

---

ci/test/pipeline.template.yml

Follow-up to https://github.com/MaterializeInc/materialize/pull/32732

ci: Reenable PG Resumption test

---

ci/mkpipeline.py

Also use information from less important jobs. Hetzner is still struggling with aarch64 availability.

ci: Consider queues stuck faster

---

src/controller/src/clusters.rs
src/orchestrator-kubernetes/src/lib.rs
src/orchestrator-process/src/lib.rs
src/orchestrator-tracing/src/lib.rs
src/orchestrator/src/lib.rs

This PR changes the orchestrator to support initializing the Timely runtime at clusterd process creation. These changes have been pulled out of https://github.com/MaterializeInc/materialize/pull/31710, to make that PR more digestible.
The main thing that changes here is that the orchestrator now also passes the listen addresses of peer processes to the `args` closure used to construct the process command line arguments. This change requires some restructuring in the process orchestrator, which is also included here (commits 1 and 2).
I recommend reviewing the commits separately.

orchestrator: prepare for initializing Timely at process creation

---

src/orchestratord/src/controller/materialize/environmentd.rs

apparently we also use them for sentry tagging

always pass --opentelemetry-resource args

---

ci/nightly/pipeline.template.yml
misc/python/materialize/parallel_workload/action.py
test/sqlsmith/mzcompose.py

tests: Make changes for dataflow cancellation being available

---

src/storage-controller/src/lib.rs

If a oneshot ingestion is canceled in the storage controller, the controller may still observe a response for it subsequently. If this happens, we should not error but instead ignore the response.
Fixes https://github.com/MaterializeInc/database-issues/issues/9095
We also have the option to only remove the entry in `pending_oneshot_ingestions` when we see the response to it. I decided to take the other approach because (a) it's easier to implement and (b) it's what compute does for peeks.

storage-controller: don't error on missing oneshot ingestions

---

ci/nightly/pipeline.template.yml

Follow-up to https://github.com/MaterializeInc/materialize/pull/32744

ci: Reenable testdrive 4 replicas

---

Cargo.lock
src/environmentd/Cargo.toml
src/environmentd/src/http.rs
src/environmentd/tests/server.rs
src/fivetran-destination/Cargo.toml
src/storage-operators/Cargo.toml
src/testdrive/Cargo.toml
src/workspace-hack/Cargo.toml

This PR adds support for compressed webhook bodies using the decompression layers in `tower_http`. It also adds a test to ensure the decompression actually works.
More advance support for webhook bodies.

[webhooks] Decompress request bodies

---

misc/shlib/shlib.bash

Seen in https://buildkite.com/materialize/test/builds/104871

ci: Improve trufflehog workaround

---

src/compute/src/render/continual_task.rs
src/compute/src/sink/materialized_view.rs
src/durable-cache/src/lib.rs
src/persist-client/src/batch.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/write.rs
src/storage-controller/src/collection_mgmt.rs
src/storage/src/render/persist_sink.rs
src/txn-wal/src/lib.rs
src/txn-wal/src/operator.rs
src/txn-wal/src/txns.rs

https://github.com/MaterializeInc/database-issues/issues/9275
see also: https://github.com/MaterializeInc/materialize/pull/32509

persist: add param to disable validation in compare and append

---

src/orchestrator-kubernetes/src/util.rs
test/cloudtest/test_metrics.py

The [default timeouts](https://docs.rs/kube-client/latest/src/kube_client/config/mod.rs.html#387-390) for the k8s client are:
* connect:  30s
* read:    295s
* write:   295s
We always connect to a k8s cluster that's running in the same region as we do, so there is no reason we'd need such long timeouts.
Reducing them lets us react faster to network issues, by retrying the request. In particular, it seems to fix a test flake where sometimes the command to create the service for a new cluster would get stuck until the test timed out.
Fixes MaterializeInc/database-issues#8472

k8s: reduce client timeouts

---

ci/test/lint-main/checks/check-trufflehog.sh
ci/test/pipeline.template.yml
misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/mzcompose/composition.py
misc/shlib/shlib.bash
test/secrets-logging/kafka-commit.td
test/secrets-logging/mysql-cdc.td
test/secrets-logging/mzcompose
test/secrets-logging/mzcompose.py
test/secrets-logging/objects.td
test/secrets-logging/pg-cdc.td

Writes an apparent token as content so that trufflehog will complain if we accidentally log user data.

tests: Add trufflehog canary

---

ci/mkpipeline.py
ci/mkpipeline.sh

To work around aarch64 availability being limited for a few days now: https://materializeinc.slack.com/archives/C01KV5PEZ9R/p1750206711215029

ci: Switch mkpipline jobs to x86-64

---

src/environmentd/tests/server.rs

This PR makes two improvements to the statement logging tests (see commit descriptions) that hopefully will make them stop flaking.
Fixes https://github.com/MaterializeInc/database-issues/issues/8665
Fixes https://github.com/MaterializeInc/database-issues/issues/8666
Fixes https://github.com/MaterializeInc/database-issues/issues/8967
I let the statement logging tests run on my local machine for half an hour and they didn't fail with this change. Previously I could at least reproduce the statement reordering bug. I never reproduced the bug where statements where missing, but it makes sense that this would be caused by not waiting long enough.

unflake statement logging tests

---

src/adapter/src/metrics.rs
src/pgwire/src/protocol.rs

This is on top of https://github.com/MaterializeInc/materialize/pull/32668
This is for investigating the spikes in the processing time of simple pgwire messages, e.g., `parse`. Discussed with @aljoscha on zoom.

Add `pgwire_ensure_transaction_seconds` metric

---

misc/shlib/shlib.bash

Seen in https://buildkite.com/materialize/test/builds/105006#01978f32-ffd8-46ca-958a-d15c87bde2b7

ci: Ignore ExpirationReaper in secrets

---

ci/plugins/cloudtest/hooks/pre-exit
ci/plugins/mzcompose/hooks/pre-exit
misc/python/materialize/cli/ci_annotate_errors.py
test/terraform/mzcompose.py

Seen in https://buildkite.com/materialize/release-qualification/builds/880#01978bad-eed6-4317-af44-dbd9991f715b and https://buildkite.com/materialize/nightly/builds/12385#01978faf-5059-4f58-918e-7f427fc27a60

tests: Recent nightly/RQ fixes

---

src/sqllogictest/src/bin/sqllogictest.rs
src/sqllogictest/src/runner.rs
test/sqllogictest/mzcompose.py

https://github.com/MaterializeInc/database-issues/issues/9402
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/9402

test: Fix naming of slt's replica size config

---

test/testdrive/frontier-rounding.td

This PR unflakes `frontier-rounding.td` by disabling the tests that check for frontier rounding _not_ working correctly. These tests were meant to document the status quo but they aren't that useful, especially when they are flaky.
As to why `frontier-rounding.td` was flaky before, I didn't manage to reproduce it but it can randomly happen for a collection with non-rounded frontiers to have a frontier that looks like it has been rounded.
Fixes https://github.com/MaterializeInc/database-issues/issues/9403

test: unflake `frontier-rounding.td`

---

ci/nightly/pipeline.template.yml
misc/python/materialize/checks/scenarios_upgrade.py
misc/python/materialize/version_list.py
test/terraform/mzcompose.py

Test runs: https://buildkite.com/materialize/nightly/builds/12425 & https://buildkite.com/materialize/nightly/builds/12430

tests: Add self-managed upgrades from 2 versions back

---

src/adapter/src/client.rs
src/environmentd/src/telemetry.rs

As the comment in code explains, we would previously immediately cancel
the query before we have a chance to run the peek or read the results.
This went unnoticed because this code path is only used in our
telemetry/segment reporting, which we only do in production. I'm adding
a follow-up commit that enables at least some form of telemetry
reporting in testing.

adapter: in support_execute_one drop SessionClient only after receiving result rows

---

src/persist-client/src/cli/admin.rs
src/persist-client/src/internal/compact.rs

This is a precursor to incremental compaction https://github.com/MaterializeInc/database-issues/issues/9194

Refactor compaction to use a stream

---

test/testdrive/upsert-source-race.td

Follow-up to https://github.com/MaterializeInc/materialize/pull/31243#pullrequestreview-2954659560
I tried enabling it and it didn't do anything of interest, other than causing an OoM: https://buildkite.com/materialize/nightly/builds/12432

testdrive: Remove comment in upsert source race test

---

misc/python/materialize/feature_benchmark/scenarios/scale.py
misc/python/materialize/mzcompose/services/clusterd.py
src/controller-types/src/dyncfgs.rs
test/cluster-isolation/mzcompose.py
test/cluster/github-cloud-7998/setup.td
test/cluster/mzcompose.py
test/kafka-resumption/mzcompose.py
test/limits/mzcompose.py
test/replica-isolation/mzcompose.py
test/upsert/mzcompose.py
test/zippy/mzcompose.py

This PR enables initialization of the Timely runtimes at process startup, by flipping the default value of the corresponding feature flag. It then adjusts all test code using unorchestrated replicas accordingly, by applying the Timely cluster configuration as env variables to the clusterd processes, instead of specifying them in the `CREATE CLUSTER REPLICA` command.
I strongly recommend reviewing the diff with whitespace ignored. It gets much smaller this way. For many tests I had to add additional service overwrites, which add one level of indentation.
Also note that I'm not yet removing the `STORAGE ADDRESSES`/`COMPUTE ADDRESSES`/`WORKERS` options from `CREATE CLUSTER REPLICA` commands, as they are currently still expected by Materialize and are …

Initialize Timely runtimes at clusterd process startup by default

---

ci/test/pipeline.template.yml
src/environmentd/tests/server.rs
test/pg-cdc-old-syntax/mzcompose.py
test/pg-cdc/mzcompose.py

Seen in https://buildkite.com/materialize/test/builds/105312#0197ac7d-6f96-42e1-bd12-90476f657edc because of a 502

ci: Increase timeout for uploading debug symbols

---

ci/plugins/cloudtest/hooks/command
ci/plugins/mzcompose/hooks/command
src/environmentd/tests/server.rs
src/environmentd/tests/sql.rs

Seen a false positive in https://buildkite.com/materialize/nightly/builds/12452#0197a91a-771f-4e3f-b553-9922232f41f2

ci: Exclude snykkey detector in trufflehog

---

Cargo.lock
src/adapter-types/Cargo.toml
src/adapter/Cargo.toml
src/catalog/Cargo.toml
src/cluster/Cargo.toml
src/compute-client/Cargo.toml
src/compute-types/Cargo.toml
src/compute/Cargo.toml
src/controller/Cargo.toml
src/durable-cache/Cargo.toml
src/environmentd/Cargo.toml
src/expr/Cargo.toml
src/interchange/Cargo.toml
src/persist-cli/Cargo.toml
src/persist-client/Cargo.toml
src/persist-types/Cargo.toml
src/persist/Cargo.toml
src/repr/Cargo.toml
src/service/Cargo.toml
src/sql-server-util/Cargo.toml
src/storage-client/Cargo.toml
src/storage-controller/Cargo.toml
src/storage-operators/Cargo.toml
src/storage-types/Cargo.toml
src/storage/Cargo.toml
src/timely-util/Cargo.toml
src/txn-wal/Cargo.toml
src/workspace-hack/Cargo.toml

No functional changes in this release relevant for Materialize (yet).

Update Timely to 0.21.3

---

test/terraform/mzcompose.py
test/testdrive/get-started.td
test/testdrive/quickstart.td

Seen failing in https://buildkite.com/materialize/nightly/builds/12471#0197af60-8a3a-4bbe-b8f2-95b739f9fef9
and disable quickstart.td since it uses a separate cluster

terraform tests: Enable creating table from source

---

test/cluster/mzcompose.py

We need to make sure the `CREATE CLUSTER` config matches the command line provided config.
The test-clusterd-death-detection test is flaky: https://github.com/MaterializeInc/materialize/pull/32860

test: fix test-clusterd-death-detection

---

misc/python/materialize/mzcompose/composition.py
misc/python/materialize/mzcompose/services/sql_server.py

Not sure yet how happy CI will be with this.

tests: Try removing some workarounds to get SQL Server working on macOS

---

src/environmentd/src/http.rs

* Redirect HTTP to HTTPS instead of returning unauthorized.
* Allow basic auth for `AuthenticatorKind::Password`. We still support sessions, but they are no longer the only way to authenticate. At present, this doesn't initiate a session.
* Selectively add the `www-authenticate` header to only some `AuthError`s. This may be an incomplete list, and it feels a bit gross to do additional path comparisons in the auth functions, but it should unblock access to the debug pages without spamming other pages with login boxes.
* Renamed `AuthError::InvalidLogin` to `AuthError::RoleDisallowed` for clarity.
The debug pages have no way of logging in with `AuthenticatorKind::Password`.
Discussion at https://materializeinc.slack.com/archives/C07PN7KSB0T/p1750849485776399
Redirecting HTTP to HTTPS is a …

Selective www authenticate header

---

src/persist-client/src/critical.rs
src/persist-client/src/internal/encoding.rs
src/persist-client/src/internal/paths.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/read.rs
src/persist-client/src/write.rs

I had originally used prefix `r` before realizing I was overloading an existing prefix. When I changed it to `ri` I forgot to fix it everywhere. Allowing multi character prefixes requires a small change to the parse_id function signature but it is a trivial one.

Fix RunId parsing

---

ci/nightly/pipeline.template.yml
test/rqg/Dockerfile

With the most recent change to RQG that changes the WMR grammar to use `UNION` instead of `UNION ALL` the overflow panics seem to have stopped, so we can enable the workload again.
Fixes https://github.com/MaterializeInc/database-issues/issues/7433

test: enable RQG WMR workload in CI

---

ci/nightly/pipeline.template.yml
misc/python/materialize/cli/ci_annotate_errors.py
test/pg-cdc-old-syntax/statistics.td
test/pg-cdc/statistics.td
test/testdrive-old-kafka-src-syntax/indexes.td
test/testdrive/alter-sink.td
test/testdrive/indexes.td

Based on https://buildkite.com/materialize/nightly/builds/12514 and https://buildkite.com/materialize/nightly/builds/12503
Verification: https://buildkite.com/materialize/nightly/builds/12515

ci: Adapt to recent nightly failures (July 1, 2)

---

ci/nightly/pipeline.template.yml
test/rqg/Dockerfile
test/rqg/mzcompose.py

Fixes https://github.com/MaterializeInc/database-issues/issues/9439
This PR uses https://github.com/MaterializeInc/RQG/pull/7
My understanding is that `t1` was missing when running the query, thus it failed, causing RQG to recreate the table, thus causing the apparent wrong results in the other running threads. In the end this seems to be badly designed in RQG, but I'm not that familiar with the design to fix it in another way.

RQG: Don't use serializable transaction isolation in WMR

---

doc/developer/design/20250415_large_select_result_size.md

Rendered: https://github.com/aljoscha/materialize/blob/adapter-lift-max-result-size-limitation/doc/developer/design/20250415_large_select_result_size.md
Design doc for https://github.com/MaterializeInc/database-issues/issues/9180

design: large SELECT result size

---

test/testdrive/copy-to-s3-minio.td

Fails when the day changes during test execution. This PR decreases the likelihood of that.
Seen in https://buildkite.com/materialize/nightly/builds/12524#0197cd7a-df08-41a9-8495-08ef240134e0

testdrive: Fix test writing to file with current day

---

ci/mkpipeline.py
ci/test/pipeline.template.yml

Runtime improves from 03:24 -> 02:19

ci: Add more debugging prints to mkpipeline & speed up worst offenders

---

misc/python/materialize/feature_benchmark/measurement_source.py
src/testdrive/src/action/sql.rs

Seen failing here: https://buildkite.com/materialize/nightly/builds/12530
Follow-up to https://github.com/MaterializeInc/materialize/pull/32907

testdrive: Don't remove too many lines

---

ci/nightly/pipeline.template.yml

See https://materializeinc.slack.com/archives/CTESPM7FU/p1751616654554169?thread_ts=1751615491.331219&cid=CTESPM7FU

0dt test: Dedicated CPU agents

---

misc/kind/cluster-node-recovery-test.yaml
misc/python/materialize/cloudtest/k8s/environmentd.py
test/cloudtest/node_recovery/test_k8s_node_recovery.py

Overriding the target cluster for each SELECT is too brittle, as it's easy to miss queries. Instead, we can schedule the quickstart cluster on a node with a different AZ than any node we are going to suspend, ensuring queries always run on a healthy cluster that way.
Fixes https://github.com/MaterializeInc/database-issues/issues/9406

test: second attempt at unflaking node recovery

---

misc/python/materialize/mzcompose/__init__.py

5ms is way too short. It's quite surprising that the tests were still that reliable tbh!
This was introduced in https://github.com/MaterializeInc/materialize/pull/32752, I assume it was an oversight.
Replicas reconnect suspiciously often in CI.

ci: set gRPC keepalive timeout to 5s instead of 5ms

---

ci/plugins/cloudtest/hooks/command
ci/plugins/mzcompose/hooks/command

Seen in https://buildkite.com/materialize/test/builds/105830#0197ef0f-734f-463a-99f2-639c009a76d9
This approach is not ideal. If we generate too many random strings we'll keep running into issues like this.

trufflehog: Exclude another detector

---

ci/nightly/pipeline.template.yml
misc/python/materialize/cli/mzcompose.py

Extracted from https://github.com/MaterializeInc/materialize/pull/32949
Test run: https://buildkite.com/materialize/nightly/builds/12562

ci: Fix RQG build

---

ci/test/pipeline.template.yml
src/compute/src/memory_limiter.rs

Seen in https://buildkite.com/materialize/test/builds/105909#0197f3c0-31e9-483e-bee5-b03c2cea4f23
Follow-up to https://github.com/MaterializeInc/materialize/pull/32939

Fix memory limiter build on macOS and bring back macOS clippy

---

doc/developer/ci-regexp.md
misc/python/materialize/cli/ci_annotate_errors.py
misc/python/materialize/github.py

Required for https://github.com/MaterializeInc/database-issues/issues/9470 to not match too many kinds of assertions

ci: Implement ci-location for ci-regexp

---

src/sql/src/plan/error.rs
src/sqllogictest/src/runner.rs
test/sqllogictest/regex.slt
test/sqllogictest/schemas.slt

[As reported by](https://materializeinc.slack.com/archives/CU7ELJ6E9/p1752205511184339) @jubrad: `InvalidSchemaName`'s error msg no longer fits its usage. It says
> no schema has been selected to create in
but it's currently also used for various statement types other than CREATEs. This PR fixes the error msg, and also adds a hint.
* This PR fixes a recognized bug: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1752205511184339

adapter: Fix error msg for `InvalidSchemaName`

---

doc/developer/testdrive.md

This is to prevent people from thinking that they are doing something wrong, see
https://materializeinc.slack.com/archives/C08AXPDBPH7/p1752158187078249
"Spent 30 minutes trying to figure out why --rewrite-results in testdrive wasn’t working. Maybe we should remove it from our testdrive readme?"
cc @SangJunBak 
(Also, fix some typos that were highlighted by my IDE.)

Mention in testdrive.md that `--rewrite-results` is currently buggy

---

ci/mkpipeline.py

Follow-up to https://github.com/MaterializeInc/materialize/pull/32990

ci: Fix check in mkpipeline.py

---

src/compute-client/src/controller/instance.rs
src/compute-client/src/controller/replica.rs
src/compute-client/src/protocol/history.rs
src/compute/src/compute_state.rs
src/compute/src/server.rs
test/cluster/mzcompose.py

https://github.com/MaterializeInc/materialize/pull/32959 introduced an optimization where after a replica connection was made, the ReplicaTask would first reduce the received commands as much as possible, before sending them on to the replica. Unfortunately, this broke frontier tracking in the controller because the ReplicaTask could reduce away dataflow creations, without sending back the expected "drop command".
The proper fix is https://github.com/MaterializeInc/database-issues/issues/9483, but putting out a revert here first so we can backport it into the release.
Fixes https://github.com/MaterializeInc/database-issues/issues/9471
Fixes https://github.com/MaterializeInc/database-issues/issues/9477
This requires an ugly workaround for the memory …

revert: Compact command history when client connects

---

ci/test/pipeline.template.yml

ci: Don't rebuild wasm all the time

---

ci/mkpipeline.py

ci: Fix bazel_lto check in mkpipeline

---

clippy.toml

Allow invalid clippy paths for tokio Builder::spawn* methods.
The cloud repo inherits lints from here, and we don't use tokio_unstable, so clippy complains about invalid paths.

Allow invalid clippy paths for tokio Builder::spawn* methods.

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/adapter-types/src/dyncfgs.rs

The old name had a space, which means that we can't toggle the flag (neither through LD, nor through ALTER SYSTEM SET). https://materializeinc.slack.com/archives/C04DJT084KA/p1752581301959399?thread_ts=1752524062.165129&cid=C04DJT084KA
Full Nightly: https://buildkite.com/materialize/nightly/builds/12608 (I'm a slightly bit worried about upgrade paths when changing a flag name, so especially interested in what the upgrade tests will say.)

adapter: Fix the name of `PLAN_INSIGHTS_NOTICE_FAST_PATH_CLUSTERS_OPTIMIZE_DURATION`

---

misc/python/materialize/mzcompose/__init__.py
test/testdrive/replica-expiration.td

Disable `enable_compute_temporal_bucketing` in CI because it causes performance regressions.

Disable temporal buckets in CI

---

bin/ci-builder
ci/mkpipeline.py
misc/python/materialize/mzbuild.py
misc/python/materialize/mzcompose/composition.py

Test run here: https://buildkite.com/materialize/test/builds/106253
We can remove some i2 code in return: https://github.com/MaterializeInc/i2/pull/2694
This will speed up the test pipeline in PRs by 1-4 minutes when a build has to happen.

ci: Start up tests immediately so they can prepare before build is available

---

misc/python/materialize/cloudtest/util/wait.py

this is necessary if we want to use a local kind kubeconfig from within a docker container, since the kubeconfig written by kind will point at localhost, but localhost won't be accessible inside the container
this is used in the cloud e2e test suite

allow overriding the kubernetes api endpoint when calling kubectl

---

test/restart/mzcompose.py

This test gets confused by the presence of persist shards created by previous tests, so make sure it starts from a clean slate.
Fixes https://github.com/MaterializeInc/database-issues/issues/9484

test: unflake the storage-managed-collections restart test

---

src/compute-types/src/explain/text.rs
src/compute-types/src/plan.rs
src/compute-types/src/plan/lowering.rs
src/compute-types/src/plan/render_plan.rs
src/compute/src/render/context.rs
test/sqllogictest/explain/default.slt
test/sqllogictest/explain/physical_plan_as_text.slt
test/sqllogictest/explain/physical_plan_as_text_redacted.slt
test/sqllogictest/github-2746.slt
test/sqllogictest/introspection/singlereplica_attribution_sources.slt

Per @ggevay, the LIR `PlanNode::ArrangeBy` was reporting _all_ arrangements, not just the new ones. This PR changes it so that it only reports new ones.
Gevay 2025, personal communication.

[EXPLAIN] Better `Arrange` output

---

src/storage-types/src/sources/sql_server.rs

https://github.com/MaterializeInc/database-issues/issues/9491

[sql_server] refactor disable cdc cleanup as requires db_owner permissions

---

ci/mkpipeline.py
misc/python/materialize/cli/ci_annotate_errors.py

All found while investigating https://materializeinc.slack.com/archives/C01LKF361MZ/p1752695001558709

ci: Fix annotation problems

---

ci/builder/Dockerfile
misc/python/materialize/cli/ci_annotate_errors.py

See https://materializeinc.slack.com/archives/C01LKF361MZ/p1752501828435169 for context
Currently not used in any tests, causes sporadic segfaults

ci: Remove qemu

---

ci/mkpipeline.py
ci/nightly/pipeline.template.yml
misc/python/materialize/cli/mzcompose.py
misc/python/materialize/mzcompose/composition.py
misc/python/stubs/junit_xml.pyi
src/orchestratord/src/bin/orchestratord.rs

All based on https://buildkite.com/materialize/nightly/builds/12630
The orchestratord change is a follow-up to https://github.com/MaterializeInc/materialize/pull/32850 @alex-hunt-materialize Is it fine to make the new `--additional-crd-columns` optional?

ci: Fixes for nightly (2025-07-17)

---

ci/plugins/cloudtest/hooks/command
ci/plugins/mzcompose/hooks/command

Seen in https://buildkite.com/materialize/nightly/builds/12627#019813d5-5d2b-4449-beeb-10c4761b190a

trufflehog: Add another exclude

---

src/adapter/src/explain/insights.rs
src/repr/src/optimize.rs
src/sql/src/plan/statement/ddl.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/session/vars/definitions.rs
test/sqllogictest/explain/plan_insights.slt

[As discussed on slack](https://materializeinc.slack.com/archives/C08A62E0751/p1752773251219519?thread_ts=1752669414.112509&cid=C08A62E0751), this PR just adds a feature flag to have a more targeted mitigation for #incident-646. Currently, it's being mitigated by turning off all plan insight notices for the affected user. After the PR, we can turn off only the problematic notices. (In fact, it will be turned off by default for all users, not just the affected user, which is what we want, because the problem might strike other users, albeit with a lower chance, because the affected user has much more clusters than other users.)
(I've opened an issue for properly fixing `compute_fast_path_clusters`, https://github.com/MaterializeInc/database-issues/issues/9492, and have put it in backlog, …

Add feature flag for `compute_fast_path_clusters`

---

doc/user/content/manage/dbt/blue-green-deployments.md

doc fix for b/g deployments

---

misc/python/materialize/checks/all_checks/sink.py
misc/python/materialize/mzcompose/services/testdrive.py
test/kafka-auth/mzcompose.py
test/kafka-auth/test-schema-registry-ssl-basic.td
test/mysql-cdc-old-syntax/alter-source.td
test/mysql-cdc-old-syntax/alter-table-after-source.td
test/mysql-cdc/alter-source.td
test/mysql-cdc/alter-table-after-source.td
test/pg-cdc-old-syntax/alter-source.td
test/pg-cdc-old-syntax/alter-table-after-source.td
test/pg-cdc/alter-source.td
test/pg-cdc/alter-table-after-source.td
test/pubsub-disruption/mzcompose.py
test/source-sink-errors/mzcompose.py
test/ssh-connection/kafka-sink-after-ssh-failure.td
test/ssh-connection/kafka-source-after-ssh-failure.td
test/testdrive-old-kafka-src-syntax/connection-alter.td
test/testdrive-old-kafka-src-syntax/github-7242.td
test/testdrive-old-kafka-src-syntax/kafka-source-errors.td
test/testdrive/connection-alter.td
test/testdrive/github-6335.td
test/testdrive/github-7242.td
test/testdrive/introspection-sources.td
test/testdrive/kafka-source-errors.td
test/testdrive/materialized-view-refresh-options.td
test/testdrive/metrics-cluster.td
test/testdrive/mz-sinks.td
test/testdrive/quickstart.td
test/yugabyte-cdc/yugabyte-cdc.td

As suggested by @ggevay , I tried first with 10s, fixed all the failures in the CI runs, and then increased the limit to 20s. Hopefully this will not cause further CI flakiness. The advantage of this PR is that we will get results faster if a test fails instead of having to wait 6 minutes for the result to converge.

testdrive: Lower default timeout to 20s

---

.gitignore
bin/ci-builder
ci/builder/Dockerfile
ci/mkpipeline.py
ci/mkpipeline.sh
ci/test/cargo-test/mzcompose.py
ci/test/check-merge-with-target.sh
ci/test/lint-clippy.sh
ci/test/lint-doc.sh
ci/test/lint-fast.sh
ci/test/pipeline.template.yml
misc/python/materialize/mzbuild.py

Works together with https://github.com/MaterializeInc/i2/pull/2699
`git restore-mtime` turned out not to be a sane approach, since cargo seems to only use the modification time and not check hashes at all!

ci: Remove git restore-mtime & mzcompose: Add local cache for docker availability

---

src/persist-cli/src/maelstrom/txn_list_append_multi.rs
src/persist-cli/src/maelstrom/txn_list_append_single.rs
src/persist-client/benches/benches.rs
src/persist-client/src/async_runtime.rs
src/persist-client/src/cfg.rs
src/persist-client/src/cli/admin.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/read.rs
src/persist-client/src/usage.rs

We believe this is a contributing factor to https://github.com/MaterializeInc/database-issues/issues/9472, by way of https://sourceware.org/bugzilla/show_bug.cgi?id=19951.
Based on that upstream report, we believe that spawning fewer threads will make this issue less likely - both because having fewer threads means fewer chances to observe the issue, and because we may be less likely to fill the cache and trigger the issue in the first place.
It's also unnecessary to spawn so many threads in a test, especially since nextest will generally run many tests concurrently...
We also discussed adding a timeout to shutdown, but it turns out that the timeout only applies to the blocking thread pool, and the isolated runtime interface doesn't allow spawning blocking threads... so we wouldn't expect …

[persist] Run fewer background threads in tests

---

doc/user/content/ingest-data/sql-server/self-hosted.md
doc/user/layouts/shortcodes/sql-server-direct/ingesting-data/use-ssh-tunnel.html

https://github.com/MaterializeInc/database-issues/issues/9409

doc: fix sql server clunky language on SSH tunnels

---

bin/ci-builder
misc/images/jobs/Dockerfile
misc/python/materialize/mzbuild.py
src/testdrive/ci/Dockerfile

Speed up builds in CI a bit more

---

src/adapter/src/coord/sequencer/inner/peek.rs

It's not clear to me why `cargo fmt` was not fixing this automatically. It might be because of the long line involving `PLAN_INSIGHTS_NOTICE_FAST_PATH_CLUSTERS_OPTIMIZE_DURATION`, but even if I further shorten that line by choosing a shorter name for the `let`, `cargo fmt` still refuses to deal with this.

Fix indentation in `peek_optimize`

---

test/testdrive/introspection-sources.td

Some import frontier queries in that file expected to observe only the import frontiers of dataflows for objects they previously installed, but could also observe the import frontiers of the query dataflows. This is fixed by filtering to non-transient dataflows.
Fixes https://github.com/MaterializeInc/database-issues/issues/9500

test: unflake introspection-sources.td

---

src/adapter/src/coord.rs
src/adapter/src/coord/message_handler.rs
src/controller/src/lib.rs

This is so we can attribute better where time on the coordinator main loop is going.

adapter/controller: for controller_ready metrics, differentiate between controllers

---

misc/images/materialized-base/Dockerfile
misc/python/materialize/mzcompose/services/materialized.py
src/materialized/ci/Dockerfile
src/materialized/ci/entrypoint.sh
test/sqllogictest/cardinality.slt

Local run with `bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive run default`. Before:
```
✔ Container testdrive-materialized-1          Healthy    61.3s
```
With this PR
```
✔ Container testdrive-materialized-1          Healthy    10.7s
```
Another example: `bin/mzcompose --find balancerd down && bin/mzcompose --find balancerd run default`. Before:
```
✔ Container balancerd-materialized-1   Healthy  39.6s
```
After:
```
✔ Container balancerd-materialized-1   Healthy   5.6s
```

docker: Speed up startup of the materialized container

---

src/persist/src/azure.rs
src/testdrive/src/action/sql.rs

And make a warning when re-creating the emulator container less scary.
https://github.com/MaterializeInc/database-issues/issues/9503

Add webhook sources to the list of unretryable commands

---

doc/user/content/ingest-data/postgres/amazon-aurora.md
doc/user/content/ingest-data/postgres/amazon-rds.md
doc/user/content/ingest-data/postgres/azure-db.md
doc/user/content/ingest-data/postgres/neon.md
doc/user/content/ingest-data/postgres/self-hosted.md

This PR cleans up a few lingering references to deprecated syntax `DROP SUBSOURCE`.

Docs - remove references to DROP SUBSOURCE

---

src/persist-client/src/cli/admin.rs
src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/machine.rs
src/persist-client/src/internal/state.rs
src/persist-client/src/internal/state_diff.rs
src/persist-client/src/internal/state_serde.json
src/persist-client/src/internal/trace.rs

Persist: Add new API for run based spine replacement

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/compute-types/src/dyncfgs.rs
src/compute/src/extensions/temporal_bucket.rs
src/compute/src/render.rs
src/timely-util/src/temporal.rs
test/testdrive/replica-expiration.td

Updates the temporal bucketing logic to only store data in the bucket chain that is likely not to be revealed soon, as far as it's possible to determine this locally. The condition we implement determines a upper frontier based on the as-of of the dataflow, the current input frontier, and a summary. It computes the join of the input frontier and the as-of, and applies the summary to the result. The summary is configurable and defaults to the equivalent of two seconds.
This results in a frontier that is always ahead of the input frontier, causing the operator to release and pass through a configurable amount of future updates, saving the cost associated with inserting and extracting the data from the bucket chain.
This addresses the performance concerns for dataflows without future …

Temporal bucket: pass through data close to frontier

---

src/adapter/src/optimize/dataflows.rs
src/adapter/src/optimize/index.rs
src/adapter/src/optimize/materialized_view.rs
src/adapter/src/optimize/subscribe.rs

MVs and subscribes need the same expression preparation as indexes. This PR makes the name cover these as well.

Rename `ExprPrepStyle::Index`, because we are using it for MVs and subscribes too

---

Cargo.toml
ci/mkpipeline.py
ci/nightly/pipeline.template.yml
ci/test/pipeline.template.yml
misc/python/materialize/mzbuild.py
src/balancerd/ci/mzbuild.yml

Much faster incremental recompilation: 45s vs 4min with Bazel (doesn't support incremental)
Example run: https://buildkite.com/materialize/test/builds/106761 incremental build + tests in 8 min total:
Larger build with tests in 11 min: https://buildkite.com/materialize/test/builds/106768
Builds for actual releases are still switched over to Bazel + LTO, example build: https://buildkite.com/materialize/test/builds/106769

ci: Use incremental cached Cargo builder instead of Bazel for test pipeline

---

src/compute/src/extensions/arrange.rs

The arrangement size logging only records batches that are in the trace, but not the ones that have been sent down the stream and that someone might still hold on to. This change corrects this.
Note that we do not account for the size of arrangements that we currently merge, we only account for the inputs but not the output. Differential doesn't offer an API to observe the state of the newly formed batch.

Arrangement size logging: observe more batches

---

ci/plugins/cloudtest/hooks/command
ci/plugins/mzcompose/hooks/command
misc/python/materialize/mzcompose/composition.py

Seen in https://buildkite.com/materialize/nightly/builds/12662#0198399f-b86f-4d59-8073-90b7e50d861a

trufflehog: Another ignore & don't print full certificates in test logs

---

src/sql/src/plan/statement/dml.rs
test/sqllogictest/introspection/singlereplica_attribution_sources.slt

We previously aggregated data across equal LIR IDs, missing that they're scoped per global ID. This change fixes it by grouping by global ID in addition to the LIR ID.
Fixes https://github.com/MaterializeInc/database-issues/issues/9130

Include global_id in explain analyze's join

---

.github/dependabot.yml
misc/python/materialize/mzcompose/services/ssh_bastion_host.py
test/ssh-bastion-host/Dockerfile
test/ssh-bastion-host/mzbuild.yml

https://materializeinc.slack.com/archives/C01LKF361MZ/p1753461350615199

mzbuild: Mirror ssh-bastion-host from quay.io to Dockerhub

---

doc/user/content/sql/system-catalog/mz_introspection.md
src/adapter/src/catalog.rs
src/catalog/src/builtin.rs
test/sqllogictest/autogenerated/mz_introspection.slt
test/testdrive/introspection-sources.td

Include all operators that might have a size in the arrangement size tracking. Not ideal because it could be operators without arrangements, but better than what we have now, and I don't want to rework the operator size tracking at this point.
Best viewed with white space hidden.
Related: https://github.com/MaterializeInc/database-issues/issues/9452

Operator size tracking

---

src/compute/src/compute_state.rs
src/compute/src/compute_state/peek_stash.rs
src/expr/src/relation.rs

Fixes https://github.com/MaterializeInc/database-issues/issues/9511 as discussed with @aljoscha here: https://materializeinc.slack.com/archives/C08JWHM837U/p1753437243688499?thread_ts=1753369592.747059&cid=C08JWHM837U
I've tested this by setting a low `PEEK_RESPONSE_STASH_THRESHOLD_BYTES` and running all slts like that. [Plus I think Nightly also tests with setting `PEEK_RESPONSE_STASH_THRESHOLD_BYTES` to 0.](https://github.com/MaterializeInc/materialize/blob/a048f88ed6cbd5601febe1a4ad23b40b8eef53e9/misc/python/materialize/mzcompose/__init__.py#L183) Nightly: https://buildkite.com/materialize/nightly/builds/12684
* This PR fixes a recognized bug: https://github.com/MaterializeInc/database-issues/issues/9511

Short circuit at LIMIT+OFFSET in peek stash

---

Cargo.lock
src/ore/src/netio.rs
src/ore/src/netio/timeout.rs
src/service/BUILD.bazel
src/service/Cargo.toml
src/service/src/lib.rs
src/service/src/transport.rs
src/service/src/transport/metrics.rs
src/service/tests/transport.rs

This PR adds the implementation of a new cluster transport protocol (CTP) that's meant to replace gRPC as the message fabric for the compute and storage protocols (and perhaps others in the future). The protocol has all the features we need from it, but the keep the scope manageable actually wiring it up in Mz is left to [a future PR](https://github.com/MaterializeInc/materialize/pull/32897).
Part of https://github.com/MaterializeInc/database-issues/issues/5038
The diff is quite large, but 50% of it consists of tests and there are plenty of code comments. Individual commits are meaningful and self-contained. If people prefer, I can split the PR into smaller ones that each only contain a subset of the commits, just lmk!

Cluster transport protocol

---

src/testdrive/ci/Dockerfile

I was trying to execute
```
bin/mzcompose --dev --find cluster run test-refresh-mv-restart
```
locally, but was getting the following error:
```
Step 3/12 : COPY testdrive protobuf-bin /usr/local/bin
When using COPY with more than one source file, the destination must be a directory and end with a /
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/gabor/materialize/misc/python/materialize/cli/mzcompose.py", line 935, in <module>
main(sys.argv[1:])
File "/home/gabor/materialize/misc/python/materialize/cli/mzcompose.py", line 157, in main
args.command.invoke(args)
File "/home/gabor/materialize/misc/python/materialize/cli/mzcompose.py", line 253, in invoke
self.run(args)
File …
```

Fix testdrive's Dockerfile

---

ci/test/pipeline.template.yml
test/mysql-cdc-old-syntax/alter-table-after-source.td
test/mysql-cdc/alter-table-after-source.td

tests: Disable two very flaky tests

---

src/environmentd/src/http.rs

This PR fixes a bug in the `init_ws` logic where we would wait for an initial authentication message in the loop, skipping over ping messages, but forgetting to actually read a new message on each loop iteration. As a result, if the first received message was a ping message, we would busy-loop forever, potentially stalling out the entire process by blocking the tokio runtime.
See [incident-659](https://materializeinc.slack.com/archives/C0981AETN69).

envd/ws: fix reception of initial websocket message

---

.bazelrc
bin/ci-builder
ci/test/cargo-test/mzcompose.py
misc/python/materialize/cli/run.py
src/adapter/src/catalog.rs
src/environmentd/src/test_util.rs
src/timestamp-oracle/src/postgres_oracle.rs

bin/environmentd: Support METDATA_BACKEND_URL properly

---

src/mysql-util/src/decoding.rs
test/mysql-cdc/20-source-replication.td
test/mysql-cdc/types-enum.td

https://github.com/MaterializeInc/database-issues/issues/9528

mysql: fix allow for cdc replication of 0 value enum variants

---

src/compute-client/src/controller.rs
src/compute-client/src/controller/instance.rs

This PR removes `Instance::replica_epochs`, a map that tracks the per-replica epochs. A defect with this map is that we never remove entries from it, so it leaks some state whenever a replica is dropped. We can fix this by observing that the `ReplicaState` for each replica already contains the current epoch, and there is no need to store it twice. We can thus delete the `replica_epochs` map.

controller/compute: remove `replica_epochs` map

---

misc/helm-charts/operator/templates/deployment.yaml
misc/helm-charts/operator/tests/deployment_test.yaml
src/environmentd/src/environmentd/main.rs
src/orchestratord/src/controller/materialize/environmentd.rs

license keys will be required in the next self-managed release

remove the ability to disable license keys

---

ci/plugins/mzcompose/hooks/command
misc/python/materialize/mzbuild.py

Thanks to @SangJunBak for reporting: https://materializeinc.slack.com/archives/C0246GEHL8N/p1754001167046539
Broken in https://github.com/MaterializeInc/materialize/pull/33118

mzbuild: Fix tools on macOS & ci: Fix terraform cleanup

---

.gitignore
.gitmodules
misc/python/materialize/cli/run.py
test/sqllogictest/mzcompose.py

I bet most people never use it and it's pretty huge: 431 MiB locally vs 196 MiB for the Materialize repo. Opinions?

Remove test/sqllogictest/sqlite submodule

---

doc/user/content/concepts/reaction-time.md
doc/user/content/sql/system-catalog/mz_internal.md

In the docs we don't say anywhere that wallclock lag has anything to do with freshness.

[doc] clarify that wallclock lag measures freshness

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/mzcompose/services/clusterd.py
misc/python/materialize/parallel_workload/action.py
src/clusterd/src/lib.rs
src/compute-client/src/controller.rs
src/compute-client/src/controller/replica.rs
src/compute-client/src/metrics.rs
src/compute-client/src/protocol/response.rs
src/controller-types/src/dyncfgs.rs
src/controller/src/clusters.rs
src/expr/src/row/collection.rs
src/service/src/grpc.rs
src/storage-client/src/controller.rs
src/storage-client/src/metrics.rs
src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs
test/cluster/mzcompose.py

This PR starts making use of the Cluster Transport Protocol introduced in #32330, to replace gRPC in both the compute and the storage protocol. CTP has been designed with that use case in mind, so the amount of required changes is relatively low.
To de-risk the rollout, we want to be able to fall back to gRPC for now. To this end, a feature flag, `enable_ctp_cluster_protocols` is introduced and wired through the controller. Replicas need to select the controller protocol at startup and they do so using a new clusterd command line flag, `--use-ctp`.
Part of https://github.com/MaterializeInc/database-issues/issues/5038.

cluster: use CTP as the transport for compute and storage protocol connections

---

ci/test/cargo-test/mzcompose.py

Noticed in https://buildkite.com/materialize/test/builds/107366#_

cargo test: Fix target dir in CI

---

test/testdrive/replica-expiration.td

Correct the replica expiration test such that it again tests what it is supposed to test. We achieve this by increasing the amount of data to process.
The test ensures that replica expiration drops data that's further out than the replica expiration. It stopped doing so after introducing (and enabling) temporal bucketing. Temporal bucketing serves as another merge batcher. The merge batcher first stages data in a chunker, and when full, inserts the data in a chain.
We had so little data that it would remain in the chunker, causing us to never reveal it in the operator/arrangement size tracking. Increasing the data volume surfaces the data that we weren't tracking.

Correct replica expiration test

---

misc/python/materialize/mzcompose/services/sql_server.py
src/testdrive/src/action/sql.rs
src/testdrive/src/action/sql_server/execute.rs

Noticed in https://github.com/MaterializeInc/materialize/pull/33250
Less controversial than the rest of that PR, so split them out

sql server tests & testdrive: Improvements

---

src/materialized/ci/Dockerfile

Seen in https://buildkite.com/materialize/test/builds/107434#01988262-f51c-46c1-9683-5103676fb135

materialized container: Time out when initializing fails

---

src/sql-server-util/src/inspect.rs
src/sql-server-util/src/lib.rs
src/sql/src/pure/sql_server.rs
test/sql-server-cdc/20-column-options.td
test/sql-server-cdc/21-privileges.td

* This PR adds a known-desirable feature. https://github.com/MaterializeInc/database-issues/issues/9208

sql_server: add checking permissions for all instances and tables in one query

---

ci/mkpipeline.py
ci/plugins/cloudtest/hooks/command
ci/plugins/mzcompose/hooks/command
ci/test/coverage_report.sh
misc/images/mz/Dockerfile
misc/python/materialize/cli/ci_coverage_pr_report.py
misc/python/materialize/cli/mzcompose.py
misc/python/materialize/cli/run.py
misc/python/materialize/git.py
misc/python/materialize/mzcompose/services/mz.py
misc/python/materialize/mzcompose/services/testdrive.py
src/persist-cli/ci-base/Dockerfile
src/persist-cli/ci/Dockerfile
test/persist/mzcompose.py

All noticed while trying to run https://github.com/MaterializeInc/materialize/pull/33245
Green nightly with the relevant tests: https://buildkite.com/materialize/nightly/builds/12796

ci+tests: Fixes for coverage

---

misc/python/materialize/buildkite.py
misc/python/materialize/git.py

See https://materializeinc.slack.com/archives/C01LKF361MZ/p1754597953979529?thread_ts=1754595718.702039&cid=C01LKF361MZ
> fatal: couldn't find remote ref origin/main
Nightly run with benchmarks: https://buildkite.com/materialize/nightly/builds/12808

benchmarks: Fix finding ancestor

---

src/sql-parser/src/ast/defs/query.rs
src/sql-parser/src/parser.rs
src/sql-parser/tests/testdata/select
test/sqllogictest/table_func.slt

Fix https://github.com/MaterializeInc/database-issues/issues/9551
(Nightly upgrade tests: https://buildkite.com/materialize/nightly/builds/12813 )

Fix parse order of WITH ORDINALITY and table alias

---

ci/test/cargo-test/mzcompose.py
misc/python/materialize/mzbuild.py
misc/python/materialize/mzcompose/composition.py
misc/python/materialize/mzcompose/services/sql_server.py
test/mssql-server/Dockerfile
test/mssql-server/mzbuild.yml
test/mz-debug/mzcompose.py

Seen in https://buildkite.com/materialize/test/builds/107511#0198895a-e09b-44ab-84f8-5fda1c12fe38

mzcompose: Don't wait on user input for docker pull & mirror mssql-server

---

misc/helm-charts/publish.sh
test/terraform/mzcompose.py

Seen in https://buildkite.com/materialize/publish-helm-charts/builds/53#019885cd-bbef-4363-951e-08446dfd5c80

terraform tests: No authenticatorKind for v25.1.*

---

ci/mkpipeline.py

This helps with reproducing some bugs for example. In addition I sometimes like to run CI with very low priority and without parallelization on a PR when I'm just testing something unimportant and very slow, like a regular coverage or sanitizer run.

ci: Introduce CI_UNPARALLELIZE

---

test/cluster-isolation/mzcompose.py

The initial timestamp for the sink depends on the timestamps available for its inputs, not the global clock. 
Fixes: https://github.com/MaterializeInc/database-issues/issues/7611
Ran into this while working on something else.

[sinks] Don't assume sinks start from the latest time in cluster isolation test

---

ci/mkpipeline.py

Noticed in https://materializeinc.slack.com/archives/C01LKF361MZ/p1754921945758739

ci: Switch to LTO on non-PR branches too

---

misc/images/ubuntu-base/Dockerfile
misc/python/materialize/mzbuild.py
misc/python/materialize/mzcompose/composition.py
misc/python/materialize/scalability/endpoint/endpoints.py
test/feature-benchmark/mzcompose.py
test/parallel-benchmark/mzcompose.py

See https://materializeinc.slack.com/archives/C01LKF361MZ/p1754937684311829?thread_ts=1754921945.758739&cid=C01LKF361MZ

benchmarks: Assert that build profile is consistent

---

src/repr/src/scalar.rs

A very minor inconsistency, just hard to not fix once seen. We would panic on `Datum::Dummy` only for some of the types we would check (specifically, not for `JSONB`).

Consistently error on `Datum::Dummy` in `Datum::is_instance_of`

---

src/sql-lexer/src/keywords.txt
src/sql-parser/src/parser.rs

This is just a stub to support future iceberg parsing in a followup PR.

refactor sink parsing to be generic over sink type

---

src/cloud-provider/src/lib.rs
src/cloud-resources/src/crd/materialize.rs
src/orchestratord/src/controller/materialize.rs
src/orchestratord/src/controller/materialize/environmentd.rs

Allow setting service account name in Materialize CR.
Also makes the `environmentd_iam_role_arn` optional in AWS.
Allow setting service account name in Materialize CR.
Requested in https://materializeinc.slack.com/archives/C07PN7KSB0T/p1754915398825409

Allow setting service account name in Materialize CR

---

src/expr/src/relation/func.rs
src/expr/src/scalar.rs
src/transform/src/canonicalization/flat_map_elimination.rs
src/transform/tests/test_transforms/flat_map_elimination.spec
test/sqllogictest/table_func.slt
test/sqllogictest/window_funcs.slt

This is on top of https://github.com/MaterializeInc/materialize/pull/33291.
Rewrites `FlatMapElimination` to simplify and generalize it. It used to check for several specific table functions. @petrosagg noticed that it could instead just execute any table function whose arguments are all literals, and then check whether it has at most 1 rows, and if yes, then transform away the table function. The only table function where we still need a special check is `Wrap`: we can eliminate it in some cases even when not all arguments are literals. (I've removed the `WITH ORDINALITY` handling for `Wrap`, because these never actually appear together, because `Wrap` is a thing that users don't call, but we insert it ourselves.)
The new code is simpler, and also fires for more table functions, e.g., …

Rewrite `FlatMapElimination`

---

src/catalog/src/builtin.rs
src/clusterd/src/usage_metrics.rs
src/compute/src/memory_limiter.rs
src/orchestrator-kubernetes/src/lib.rs
test/sqllogictest/system-cluster.slt

This PR adds swap usage reporting to the cluster and kubernetes orchestrator, that works the same way as the existing disk usage reporting. In the orchestrator, both disk and swap usage are simply summed up. We expect replicas to either use an explicit disk or swap, so no information is lost this way.
As a result of this change, swap usage is now reported through `mz_cluster_replica_metrics`. Note that the swap limit is not yet written to `mz_cluster_replica_sizes`, so percentage based utilization is still broken for swap replicas.
Needs a change in the console to not break the UI in environments that run swap replicas: https://github.com/MaterializeInc/console/pull/3866
Part of https://github.com/MaterializeInc/database-issues/issues/9366

cluster,orchestrator-k8s: report swap usage

---

misc/helm-charts/operator/templates/deployment.yaml

Set a restrictive security context for orchestratord.
Good security practice, and requested by a customer.
We already do this for all the things spawned by orchestratord and environmentd, we just missed it for orchestratord itself.

Set a restrictive security context for orchestratord

---

test/pg-cdc-old-syntax/mzcompose.py
test/pg-cdc-old-syntax/status/04-drop-publication.td
test/pg-cdc/mzcompose.py
test/pg-cdc/status/04-drop-publication.td

See https://github.com/MaterializeInc/database-issues/issues/7611
Follow-up to https://github.com/MaterializeInc/materialize/pull/33277

tests: Reenable 2 disabled tests since 7611 is fixed

---

src/compute-types/src/explain/text.rs
src/compute-types/src/plan.proto
src/compute-types/src/plan.rs
src/compute-types/src/plan/lowering.rs
src/compute-types/src/plan/reduce.rs
src/compute-types/src/plan/threshold.rs
test/sqllogictest/explain/default.slt
test/sqllogictest/explain/materialized_view.slt
test/sqllogictest/explain/physical_plan_aggregates.slt
test/sqllogictest/explain/physical_plan_as_json.slt
test/sqllogictest/explain/physical_plan_as_text.slt
test/sqllogictest/explain/physical_plan_as_text_redacted.slt
test/sqllogictest/github-16036.slt
test/sqllogictest/github-2746.slt
test/sqllogictest/outer_join.slt
test/sqllogictest/transform/literal_constraints.slt
test/sqllogictest/transform/normalize_lets.slt
test/sqllogictest/transform/predicate_pushdown.slt
test/sqllogictest/transform/relax_must_consolidate.slt
test/testdrive/monotonic.td

Our LIR types had space for optional types that were meant to inform specialization. There is no specialization and no concrete plans to implement such from type information. In particular, the type system itself may evolve, and until it stabilizes it makes some sense to extract these and re-introduce them once we have a clearer sense of what they would be for (vs maintaining them).

Remove optional types from LIR

---

ci/release-qualification/pipeline.template.yml
misc/python/materialize/ci_util/__init__.py
misc/python/materialize/source_table_migration.py
test/mysql-cdc-old-syntax/mzcompose.py
test/pg-cdc-old-syntax/mzcompose.py
test/pg-cdc/alter-source.td
test/testdrive-old-kafka-src-syntax/mzcompose.py
test/testdrive/unified-compute-introspection.td
test/upsert/mzcompose.py

Based on failures in https://buildkite.com/materialize/release-qualification/builds/908 and https://buildkite.com/materialize/nightly/builds/12844

tests: Nightly/RQ fixes (2025-08-13 edition)

---

ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/command
ci/test/pipeline.template.yml
misc/python/materialize/cli/ci_annotate_errors.py
src/sqllogictest/ci/Dockerfile
test/sqllogictest/mzcompose.py

Demo run, see annotation: https://buildkite.com/materialize/test/builds/107791 (I have fixed the text after that run to include `--rewrite-results`)
Motivated by https://materializeinc.slack.com/archives/C01LKF361MZ/p1755031723538639

SLT: Print instructions for how to rewrite results as well as the diff

---

test/sql-server-cdc/10-sql-server-cdc.td
test/sql-server-cdc/11-sql-server-cdc-ssl.td
test/sql-server-cdc/15-expose-progress.td
test/sql-server-cdc/20-column-options.td
test/sql-server-cdc/25-constraints.td
test/sql-server-cdc/30-add-subsource.td
test/sql-server-cdc/40-data-types.td
test/sql-server-cdc/50-unsupported-types.td
test/sql-server-cdc/source-tables.td

sql server is enabled by default
small set of refactors to the sql server cdc tests following updates in: https://github.com/MaterializeInc/materialize/pull/33265

[sql_server] remove enabling sql server in test as defaults to enabled

---

ci/test/pipeline.template.yml

24 min run seen here: https://buildkite.com/materialize/test/builds/107844#0198a9f2-7d9c-4184-828a-dd405a56ee5f

ci: Move macOS clippy to aarch64 (much faster)

---

ci/plugins/cloudtest/hooks/command
ci/plugins/mzcompose/hooks/command
src/adapter/src/session.rs
src/build-tools/src/lib.rs
src/cloud-api/src/lib.rs
src/controller/src/lib.rs
src/fivetran-destination/src/lib.rs
src/frontegg-client/src/error.rs
src/interchange/src/avro/decode.rs
src/ore/src/cast.rs
src/sql-parser/src/ast/defs/name.rs
src/storage/src/source/generator/auction.rs
src/storage/src/source/generator/counter.rs
src/storage/src/source/generator/datums.rs
src/storage/src/source/generator/marketing.rs
src/storage/src/source/generator/tpch.rs

Seen in https://buildkite.com/materialize/deploy/builds/19309#_
Follow-up to https://github.com/MaterializeInc/materialize/pull/33290
Reproducer: `rustup run nightly bin/doc --document-private-items`

Fix cargo docs following new nightly version

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/adapter-types/src/dyncfgs.rs
src/adapter/src/coord/caught_up.rs

We already have logic in the caught-up check that tries to exclude collections whose frontier is too far behind current wall-clock time, but that doesn't catch cases where a replica is "limping" along and sometimes makes process. This has made the release tedious at times, where we had to wait a long time for cutting over.
This is a more explicit approach where we straightaway ignore clusters that only have crash-looping replicas. We don't consider and wait for them before cutting over in a 0dt deployment.
@ggevay and @teskje , you might be interested to review, I think you have most acutely felt the pain of this recently. 🕊️

adapter: exclude crash-looping clusters from 0dt caught up checks

---

misc/python/materialize/cli/orchestratord.py
src/orchestratord/src/controller/materialize/environmentd.rs

the first commit is just a bug fix for how we determine whether license keys should be used, the others are improvements to bin/orchestratord to make it easier to run different versions

some more fixes for running environmentd via orchestratord

---

src/adapter/src/coord/command_handler.rs
src/adapter/src/coord/ddl.rs
src/adapter/src/coord/sequencer/inner/create_index.rs
src/adapter/src/coord/sequencer/inner/create_materialized_view.rs
src/adapter/src/coord/timestamp_selection.rs

`least_valid_read` doesn't need access to any `Catalog` state; it can be done simply on `ReadHolds`. This PR modifies all call sites of `Catalog::least_valid_read` to instead call `ReadHolds::least_valid_read` directly, and deletes `Catalog::least_valid_read`. This makes the code at these call sites easier to use from outside the Coordinator, and thus works towards the [Small Coordinator vision](https://github.com/aljoscha/materialize/blob/design-small-coordinator/doc/developer/design/20250717_a_small_coordinator_more_scalable_isolated_materialize.md#processing-selects), specifically https://github.com/MaterializeInc/database-issues/issues/9593.

Do `least_valid_read` on `ReadHolds` instead of `Catalog`

---

ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/command
test/terraform/aws-persistent/main.tf
test/terraform/aws-temporary/main.tf
test/terraform/aws-upgrade/main.tf
test/terraform/azure-temporary/main.tf
test/terraform/gcp-temporary/main.tf

Seen in https://materializeinc.slack.com/archives/C07PN7KSB0T/p1755682291053539
@doy-materialize Is it fine to change this globally? The terraform test just uses the default values.yaml without modifying it. If this is not fine, I'll have to pass it in specifically for the test.

terraform tests: Default to enableLicenseKeyChecks: true

---

ci/test/pipeline.template.yml

See https://materializeinc.slack.com/archives/C01LKF361MZ/p1755787897161519

ci: Make sure macOS clippy doesn't run out of disk

---

src/persist-client/src/batch.rs
src/persist-client/src/write.rs
src/storage/src/render/persist_sink.rs

Persist: simplify logic for validating part bounds on write

---

ci/nightly/pipeline.template.yml
misc/python/materialize/cli/ci_closed_issues_detect.py

Based on https://buildkite.com/materialize/nightly/builds/12938

ci: Fixes for nightly (2025-08-22)

---

test/sql-server-resumption-old-syntax/sql-server-restart-dummy-writing.td

we don't use db test and have a built in delay before we attempt to enable the ticker that should allow test to become available.
https://github.com/MaterializeInc/database-issues/issues/9611

sql_server: fix requiring test in connection

---

src/sql-server-util/src/desc.rs
src/sql-server-util/src/inspect.rs
src/sql/src/pure/references.rs
test/sql-server-cdc/80-deterministic-capture-instance-selection.td

https://github.com/MaterializeInc/database-issues/issues/9607
There are a variety of fields on `cdc.change_tables`. we want to pick one that is strictly increasing so that we can pick the newest change table/capture instance. we want to pick the newest change table when a source is created to make sure we are getting the latest schema changes. change tables in SQL server reflect the schema of the source table when the change table was created. notably though change tables do not afaict have any of the constraints of source tables.
fields:
- object_id - the id of the change table is not guaranteed to be strictly increasing.
- create_date - should be, assuming monotonic clock, strictly increasing. but if clock skews then we no longer have a strictly …

sql_server: add deterministic capture instance selection

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/compute-types/src/dyncfgs.rs
src/compute/src/render/join.rs
src/compute/src/render/join/linear_join.rs
src/compute/src/render/join/mz_join_core.rs
src/compute/src/render/join/mz_join_core_v2.rs

This PR introduces `mz_join_core_v2`, an evolution of `mz_join_core` that's meant to resolve a long-standing performance issue around processing input batches with a large number of distinct times. `mz_join_core`'s match generation is quadratic in the number of distinct times, which often causes dataflows to struggle when they are expected to join collections with deep histories.
DD's join implements a more efficient match generation strategy that's linear in the number of distinct times. The reason `mz_join_core` doesn't employ that too is that `mz_join_core` wants to yield often to ensure responsiveness, which would require keeping self-referential state between operator invocations, a thing that's notoriously difficult to do in Rust.
`mz_join_core_v2` extends `mz_join_core` by DD's the …

mz_join: efficient linear scan through times

---

src/storage-controller/src/collection_mgmt.rs

We've observed high memory use from the collection data that's temporarily fully snapshotted in memory, and there's no reason we can't just stream out an updated batch as we go.
Part of https://github.com/MaterializeInc/incidents-and-escalations/issues/286
My first version used the unconsolidated stream, but that could cause exponential growth in the data size in some bad cases - if we called this method frequently without having compaction run in the background. Using the consolidated snapshot should use no more memory than the current version, but typically less, and doesn't have the risk of exponential data growth.

[controller] Stream through retractions instead of snapshotting

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/adapter-types/src/dyncfgs.rs
src/adapter/src/catalog/open.rs

To allow a slow rollout of swap for cc sizes via LD, this PR introduces a `force_swap_for_cc_sizes` dyncfg. If enabled, this config on envd startup patches the replica size definitions to ensure swap is always enabled for cc sizes.
Once the rollout is complete the plan is to change the externally provided cc size definitions to enable swap directly, and remove the dyncfg again.
Part of https://github.com/MaterializeInc/database-issues/issues/9416

adapter: add dyncfg to force swap for cc sizes

---

test/ssh-connection/kafka-source-after-ssh-failure-restart-replica.td
test/ssh-connection/kafka-source-after-ssh-restart.td

Fixes: https://github.com/MaterializeInc/database-issues/issues/9533
As Marty noted in https://github.com/MaterializeInc/database-issues/issues/9533#issuecomment-3224982736
I thought 20 s would be plenty, but apparently not!

ssh connection test: bump timeouts to 60s

---

ci/nightly/pipeline.template.yml
misc/python/materialize/feature_benchmark/scenarios/optbench.py

Based on https://buildkite.com/materialize/nightly/builds/12975

ci: Nightly fixes (2025-08-27)

---

src/sql/src/func.rs
src/sql/src/plan/query.rs
src/sql/src/session/vars/definitions.rs
test/sqllogictest/cockroach/rows_from.slt
test/sqllogictest/github-2996.slt
test/sqllogictest/regex.slt
test/sqllogictest/table_func.slt

WITH ORDINALITY was recently rewritten, but the new implementation can't be used for some table functions, see https://github.com/MaterializeInc/database-issues/issues/9598. These cases are probably rare, so this PR just disables WITH ORDINALITY for these cases for now. I've checked that no customer is using WITH ORDINALITY with these problematic window functions currently: In the release that was rolled out today to customers, there is a Sentry error that would show if anyone is using the problematic combination, and this Sentry error didn't happen.
(We can fix https://github.com/MaterializeInc/database-issues/issues/9598 later. It's not too hard to do, it's just not worth it for now, because it's probably a rare setup.)

Disable the legacy WITH ORDINALITY implementation fallback

---

test/sql-server-resumption-old-syntax/populate-tables.td
test/sql-server-resumption-old-syntax/verify-data.td

https://github.com/MaterializeInc/database-issues/issues/9573
we differ from pg and mysql in that we just handle row decoding failures instead of actively monitoring for schema changes in the upstream tables using something like:
https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/cdc-ddl-history-transact-sql?view=sql-server-ver17
I wrote a different version of this that refactored to use an error message that matched the other sources but by updating the error message it would force all existing SQL Server sources to need to be dropped and recreated.
we can still make that change pre GA but it seems unnecessary

sql_server: add failing the source for incompatible schema changes

---

misc/python/materialize/zippy/mz_actions.py
test/zippy/mzcompose.py

The old approach doesn't work, see https://materializeinc.slack.com/archives/C01LKF361MZ/p1756218890810319
Currently testing with: `bin/mzcompose --find zippy down && CI_MZ_SYSTEM_PARAMETER_DEFAULT="enable_rbac_checks=false;enable_statement_lifecycle_logging=false" bin/mzcompose --find zippy run default --scenario=KafkaSources`

zippy: Support system params via CI_MZ_SYSTEM_PARAMETER_DEFAULT

---

doc/user/layouts/shortcodes/self-managed/versions/upgrade/upgrade-steps-cloud.html
doc/user/layouts/shortcodes/self-managed/versions/upgrade/upgrade-steps-local-kind.html
doc/user/layouts/shortcodes/self-managed/versions/upgrade/upgrade-steps-local-minikube.html

There is also `kubectl -n materialize-environment get pods -o name | grep balancerd` instead of `kubectl -n materialize-environment get pods --no-headers | grep balancerd  | awk '{print $1}'`

docs: Shorter kubectl commands in upgrade steps

---

src/adapter/src/coord/sequencer/inner.rs
src/storage-client/src/controller.rs
src/storage-controller/src/lib.rs

storage: remove alter_ingestion_source_desc

---

misc/python/materialize/cli/orchestratord.py
src/orchestratord/src/controller/materialize.rs
src/orchestratord/src/controller/materialize/balancer.rs
src/orchestratord/src/controller/materialize/console.rs

https://github.com/MaterializeInc/database-issues/issues/9639

clean up balancer and console resources if they are disabled

---

ci/test/pipeline.template.yml
misc/wasm/Cargo.lock
misc/wasm/src/sql-lexer-wasm/Cargo.toml

Seen in https://buildkite.com/materialize/test/builds/108792#01991053-7d96-44ed-b3d2-4c310a295496
Follow-up to https://github.com/MaterializeInc/materialize/pull/33460

Fix wasm build and run wasm build on PRs when anything in src changed

---

src/compute-types/src/explain/text.rs
test/sqllogictest/explain/default.slt

There's been some confusion about `Fused ...` in the new EXPLAIN output. I propose changing it to say either `Fused with Parent` (for pre-processing MFPs in `ArrangeBy`) or `Fused with Child` (for post-processing MFPs in a variety of operators).
While I'm in there, I made `Fused with Parent` display projects, like all of the other MFPs.
https://materializeinc.slack.com/archives/C0246GEHL8N/p1756217688424869?thread_ts=1756216828.219839&cid=C0246GEHL8N https://materializeinc.slack.com/archives/C08A62E0751/p1752091227806479

[EXPLAIN] clarify direction of operator fusion

---

Cargo.lock
doc/user/content/sql/prepare.md
src/adapter/src/catalog.rs
src/adapter/src/catalog/state.rs
src/adapter/src/client.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner.rs
src/adapter/src/coord/sql.rs
src/adapter/src/error.rs
src/adapter/src/session.rs
src/adapter/src/util.rs
src/environmentd/src/http/sql.rs
src/pgrepr/Cargo.toml
src/pgrepr/src/value.rs
src/pgwire/src/codec.rs
src/pgwire/src/protocol.rs
src/sql-parser/src/parser.rs
src/sql/src/catalog.rs
src/sql/src/plan/error.rs
src/sql/src/plan/statement/scl.rs
test/sqllogictest/transactions.slt

This is on top of https://github.com/MaterializeInc/materialize/pull/33471, because of using `PREPARE FETCH` for easier testing.
This fixes https://github.com/MaterializeInc/database-issues/issues/9634: It adds a `state_revision` field to `Session`, and uses this in `verify_statement_revision` in a similar way as `catalog_revision`. We do this for both prepared statements and portals, as the bug can manifest for both, see the added tests.
Note that the original bug was for prepared statements, but portals have the same problem. This PR fixes both. It was natural to fix in the same PR, because `verify_statement_revision` overlaps between the two code paths (`verify_prepared_statement` and `verify_portal`).
A somewhat inelegant part is `get_portal_unverified_mut`, where I needed to add a …

Check session state in `verify_statement_revision`

---

misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/executor.py
misc/python/materialize/sqlsmith.py
test/sqlsmith/Dockerfile

Motivated by https://materializeinc.slack.com/archives/CU7ELJ6E9/p1756852503595199
Finds two mz_now bugs reliably now.

sqlsmith: Update version & run in parallel-workload again

---

misc/python/materialize/zippy/scenarios.py

Noticed in https://buildkite.com/materialize/release-qualification/builds/937#019917d9-e07f-4172-bcf7-9a7c97a67137
Follow-up to https://github.com/MaterializeInc/materialize/pull/33414
Test run: https://buildkite.com/materialize/release-qualification/builds/938

zippy: Add forgotten SqlServerCdcLarge scenario

---

misc/python/materialize/sqlsmith.py
misc/shlib/shlib.bash

Based on https://buildkite.com/materialize/nightly/builds/13173
Test run: https://buildkite.com/materialize/nightly/builds/13195

ci: Fix nightly failures (2025-09-06)

---

src/adapter/src/client.rs
src/adapter/src/command.rs
src/adapter/src/coord/sequencer.rs
src/adapter/src/coord/sequencer/inner/copy_from.rs
src/pgwire/src/protocol.rs
src/sql/src/plan.rs
src/sql/src/plan/error.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement.rs
src/sql/src/plan/statement/dml.rs
src/sql/src/rbac.rs

It was panicking if the table was dropped at a bad moment (either while COPY FROM is reading from stdin or before the `ExecuteResponse::CopyFrom` comes back from the Coordinator).
Writing an automated test specifically for this seems complicated. I'm open to ideas, but maybe the manual testing that I did is enough, given that this is a small and straightforward change. Also, Parallel Workload would hopefully notice this again, if it regresses in the future.
(I've also manually tested (with sleeps) what happens if the table goes away after taking that catalog snapshot that the `try_get_item` looks into. In this case, the `try_get_item` still succeeds, but then we [later throw a graceful error from](https://github.com/MaterializeInc/materialize/blob/cc1d7672ff899f233badb4db65fc00168d94bb69/s …

adapter: Don't panic when COPY FROM's target table is dropped

---

src/compute/src/logging/compute.rs
src/compute/src/render/join/delta_join.rs
src/timely-util/src/operator.rs
test/sqllogictest/introspection/relations.slt

Switches the dataflow operators maintaining the dataflow exports to columnar, both on the edge and in the arrangement preparation.
This is a step toward using columnar in more places.

Switch export dataflow operators to columnar

---

src/expr/src/scalar/func.rs
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_time_interval.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__div_interval.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__mul_interval.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__sub_time_interval.snap

See https://github.com/MaterializeInc/database-issues/issues/9301 for a long description of the trouble with multiplication and division.
See https://github.com/MaterializeInc/database-issues/issues/9656 for a probably-related CI failure with adding times and intervals.
I haven't reproduced the second issue above, so I haven't proved that this change fixes it. But time+interval is definitely non-monotone, and it does seem to come up in the linked PR...

Mark some interval-related functions as non-monotone

---

src/compute/src/row_spine.rs

Noticed in performance profiles that it didn't get inlined where I'd expect it to.

Inline BytesBatch::index

---

src/adapter/src/optimize/copy_to.rs
src/adapter/src/optimize/peek.rs
test/sqllogictest/filter-pushdown.slt
test/sqllogictest/mztimestamp.slt
test/sqllogictest/persist-fast-path.slt
test/sqllogictest/temporal.slt

This is fixing https://github.com/MaterializeInc/database-issues/issues/9645 by moving unmaterializable function evaluation (`prep_relation_expr`/`prep_scalar_expr`) earlier in peek sequencing. It also does the same move in COPY TO sequencing. Even though fast path is not a thing there, so the above issue can't occur, we'd still like to avoid unnecessary divergence between the peek sequencing and the COPY TO sequencing codes.
Also note that even independently from https://github.com/MaterializeInc/database-issues/issues/9645, it seems generally better to do `mz_now()` (and other unmaterializable func) evaluation before optimization, because constants are easier to work with during optimization than function calls. This is demonstrated by a few (somewhat contrived) tests flipping from slow …

`prep_relation_expr` earlier in peek sequencing

---

bin/bump-version
bin/ci-builder
misc/python/materialize/release/cut_release.py

Verified locally on macOS with `bin/cut-release --sha HEAD --version v0.157.1 --remote origin`

cut-release: Reenable sbom generation

---

src/compute/src/logging/compute.rs
test/sqllogictest/introspection/relations.slt
test/testdrive/introspection-sources.td
test/testdrive/mzcompose.py

This reverts commit 42a54337981637bedd903d3c3dfacaf4f49bcba9.

Revert "Switch arrangement size logging to columnar (#33559)"

---

bin/ci-builder
ci/nightly/pipeline.template.yml
ci/plugins/mzcompose/hooks/command
doc/user/content/sql/functions/_index.md
doc/user/content/sql/functions/cast.md
doc/user/data/sql_funcs.yml
misc/python/materialize/data_ingest/data_type.py
misc/python/materialize/data_ingest/executor.py
misc/python/materialize/data_ingest/workload.py
misc/python/materialize/parallel_workload/action.py
misc/python/materialize/parallel_workload/column.py
misc/python/materialize/parallel_workload/database.py
misc/python/materialize/parallel_workload/executor.py
misc/python/materialize/parallel_workload/expression.py
misc/python/materialize/parallel_workload/parallel_workload.py
misc/python/materialize/parallel_workload/settings.py
misc/python/materialize/sqlsmith.py
test/parallel-workload/mzcompose.py
test/sqlsmith/mzcompose.py

Motivated by https://materializeinc.slack.com/archives/CU7ELJ6E9/p1756852503595199
I always knew we'd need more general expressions, so finally got around to implementing them (and removing all the TODO comments).
That reproduces the original issue easily in 4/9 runs: https://buildkite.com/materialize/nightly/builds/13133
> +++ [worker_8] Query failed: INSERT INTO "db-pw-1757078559-0"."s-0"."t-1" ("c-0-bigint", "c-1-mz_timestamp") VALUES (-1154873474221047172, MZ_TIMESTAMP '19317-9-27'), (-9223372036854775808, MZ_TIMESTAMP '66822-9-13'), (9223372036854775807, MZ_TIMESTAMP '17235-10-21'), (-4665962949847538769, MZ_TIMESTAMP '69332-6-15'), (8444606562024686967, MZ_TIMESTAMP '71526-12-6'), (6100859744477175015, MZ_TIMESTAMP '96494-10-12'), (-9223372036854775808, MZ_TIMESTAMP '59117-4-1'), …

parallel-workload: Use more interesting expressions in SELECT, views and conditions; support COPY FROM STDIN; prepared statements; run 10x faster

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/compute-client/src/controller/instance.rs
src/compute-types/src/dyncfgs.rs
src/compute/src/sink/materialized_view.rs
src/controller-types/src/dyncfgs.rs
src/storage-controller/src/lib.rs

This PR removes two dyncfgs that were added to de-risk feature rollout and are not needed anymore now:
* enable_compute_mv_append_smearing
* enable_wallclock_lag_histogram_collection

compute: remove unneeded dyncfgs

---

src/adapter/src/coord/caught_up.rs
src/storage-client/src/controller.rs
src/storage-controller/src/instance.rs
src/storage-controller/src/lib.rs

Before, we were erroneously only including the "root" ingestion objects and not any of their subsource/tables in hydration checks.
@def-  I believe this should fix https://github.com/MaterializeInc/database-issues/issues/9687, but I haven't yet tried running that using the `--release` nightly config.

storage,0dt: include source exports (aka. subsources) in hydration checks

---

misc/python/materialize/parallel_workload/action.py
src/compute/src/extensions/temporal_bucket.rs

We need to exchange data to avoid one worker maintaining positive diffs and another maintaining negative diffs that would otherwise cancel.

Partition data for temporal bucketing

---

bin/bump-version
doc/user/content/releases/v0.128.md
doc/user/content/releases/v0.143.md
doc/user/content/releases/v0.145.md
doc/user/content/releases/v0.148.md
doc/user/content/releases/v0.152.md
misc/helm-charts/operator-weekly/Chart.yaml
misc/helm-charts/publish-weekly.sh
misc/helm-charts/publish.sh
misc/python/materialize/cli/helm_chart_version_bump.py
misc/python/materialize/release/mark_release_complete.py

https://www.notion.so/materialize/Weekly-cloud-Self-Managed-Release-Schedule-26913f48d37b80708ddad0dea3d62aac
Still missing: Docs for self-managed weekly

helm-chart: Prepare weekly releases of self-managed

---

src/environmentd/src/environmentd/main.rs
src/license-keys/src/lib.rs

https://materializeinc.slack.com/archives/CU7ELJ6E9/p1758216047458169

disable license key checks in the emulator

---

src/catalog/src/builtin.rs

According to my high school maths knowledge, these two divisions cancel out, but I might be missing something!

catalog: remove unneeded division in `mz_console_cluster_utilization_overview`

---

src/compute/src/render/top_k.rs
src/expr-parser/src/parser.rs
src/expr/src/interpret.rs
src/expr/src/relation/join_input_mapper.rs
src/expr/src/scalar/func.rs
src/expr/src/scalar/func/binary.rs
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_float32.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_float64.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_int16.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_int32.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_int64.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_uint16.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_uint32.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__add_uint64.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__eq.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__gt.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__gte.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__lt.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__lte.snap
src/expr/src/scalar/snapshots/mz_expr__scalar__func__not_eq.snap
src/sql/src/func.rs
test/sqllogictest/explain/decorrelated_plan_as_json.slt
test/sqllogictest/explain/optimized_plan_as_json.slt
test/sqllogictest/explain/physical_plan_as_json.slt
test/sqllogictest/explain/raw_plan_as_json.slt

Switch some variants of `BinaryFunc` to use the `LazyBinaryFunc` trait's implementation.
Adds missing `negate` properties to negatable binary functions.

Switch to binary func trait for some variants

---

Cargo.lock
src/compute-types/Cargo.toml
src/compute-types/src/dataflows.rs
src/compute-types/src/plan.rs
src/compute-types/src/plan/join.rs
src/compute-types/src/plan/join/delta_join.rs
src/compute-types/src/plan/join/linear_join.rs
src/compute-types/src/plan/reduce.rs
src/compute-types/src/plan/threshold.rs
src/compute-types/src/plan/top_k.rs
src/compute-types/src/sinks.rs
src/compute-types/src/sources.rs

(First commit is from https://github.com/MaterializeInc/materialize/pull/33638 and can be ignored here.)
Now that the expr_cache tests don't rely on these `Arbitrary` impls anymore, they can be deleted.

compute-types: remove remaining proptest boilerplate

---

misc/images/materialized-base/Dockerfile

I was getting the following error:
```
Step 5/9 : COPY postgresql.conf pg_hba.conf /etc/postgresql
When using COPY with more than one source file, the destination must be a directory and end with a /
```

Fix COPY command in materialized-base Dockerfile

---

src/storage-client/src/storage_collections.rs

This is just a minor optimization that I noticed while working on the peek sequencing. These methods lock `self.collections`, plus `StorageCollections::acquire_read_holds` does lots of other things. We can avoid all this when the input vec of collection ids is empty.
An example situation when there are no ids is when `Coordinator::acquire_read_holds` is used in a fast path peek, in which case `desired_storage_holds` will be empty, so `StorageCollections::acquire_read_holds` is called with an empty vec.
* This PR does a minor optimization.

Early exit from `StorageCollections::acquire_read_holds` and `collections_frontiers`

---

doc/user/content/sql/execute.md
doc/user/content/sql/subscribe.md
src/adapter/src/coord/sequencer/inner/subscribe.rs
src/adapter/src/coord/timestamp_selection.rs
src/adapter/src/optimize/dataflows.rs
src/adapter/tests/timestamp_selection.rs
src/sql/src/plan.rs
src/sql/src/plan/error.rs
src/sql/src/plan/hir.rs
src/sql/src/plan/query.rs
src/sql/src/plan/statement/dml.rs
test/sqllogictest/as_of.slt
test/sqllogictest/subscribe_error.slt
test/testdrive/fetch-tail-as-of.td

This is a preparatory PR for the peek sequencing work: For that, the point of this PR is the removal of the `&self` parameters from `determine_timestamp_classical` and `determine_timestamp_via_constraints`.
But I think this is a beneficial refactoring even independently from the peek sequencing work. The `AS OF` / `UP TO` evaluation belongs in planning in my opinion. This way, we can re-use the standard casting code, instead of having bespoke casting code in `evaluate_when`.
Nightly: https://buildkite.com/materialize/nightly/builds/13470

Move `AS OF` / `UP TO` evaluation from sequencing to planning

---

test/testdrive/divergent-dataflow-cancellation.td

This test is sometimes flaky, presumably because the queries that are supposed to ensure that all Timely dataflow state has been dropped get confused by the ad-hoc dataflows created for said queries.
Joining against other introspection sources to find and filter ad-hoc dataflows is unreliable, because the different introspection sources are not necessarily in sync. For example, it can happen that a dataflow's entries in `mz_arrangement_batches_raw` stay around for longer than its entries in `mz_dataflow_operators_per_worker`, making it impossible to identify the dataflow these arrangement batches belong to.
Instead this PR attempts to fix the flaking by making sure all introspection queries performed in the test are fast-path queries. Those don't create ad-hoc dataflows, so no confusion …

test: try to unflake `divergent-dataflow-cancellation.td`

---

doc/user/content/ingest-data/sql-server/self-hosted.md
doc/user/content/sql/create-source/sql-server.md
doc/user/layouts/shortcodes/sql-server-direct/ingesting-data/allow-materialize-ips.html

- Updates to docs
- Removed private preview flags
- Fixed typos

Docs changes for Sql Server launch

---

src/catalog/src/durable/upgrade/v76_to_v77.rs

Because the initial role attribute has login set to false, we were deactivating login for all roles on migration.
Equivalent backport commit https://github.com/MaterializeInc/materialize/pull/33655/commits/e3954561cc1426df937d481d187076ee3dd4bc94 (only difference is v74 instead of v76)
For the test, I plan on making a platform test that asserts against an upgrade of v147.1 to v147.15 (the upcoming patch release). However for that test to even pass, the backport needs to be merged.

Don't default to initial role attributes

---

doc/user/content/sql/explain-analyze.md
src/sql/src/plan/statement/dml.rs
test/sqllogictest/introspection/singlereplica_attribution_sources.slt

The range query in operator IDs was leading to a cross join with a filter; using `generate_series` we can get a proper equijoin.
https://github.com/MaterializeInc/database-issues/issues/9658

[EXPLAIN] remove cross join from EXPLAIN ANALYZE

---

ci/nightly/pipeline.template.yml

As suggested by Frank in https://materializeinc.slack.com/archives/C01LKF361MZ/p1758721653052059

ci: Build with Rust Nightly in Nightly test pipeline

---

ci/deploy/devsite.sh

dev docs: Don't index, don't follow

---

ci/nightly/pipeline.template.yml
ci/release-qualification/pipeline.template.yml
test/cluster-spec-sheet/mzcompose.py

Fixes: https://github.com/MaterializeInc/database-issues/issues/9654
Test run: https://buildkite.com/materialize/release-qualification/builds/954
Triggered the other e2e tests in the middle of it: https://buildkite.com/materialize/nightly/builds/13579 & https://buildkite.com/materialize/nightly/builds/13554#01997d8d-fede-4bb0-a1c3-4463b27b989c

Cluster Spec Sheet: Move to another region so we don't conflict with other tests

---

src/cloud-resources/src/crd/materialize.rs
src/orchestratord/src/controller/materialize/balancer.rs
src/orchestratord/src/controller/materialize/console.rs
test/orchestratord/mzcompose.py

Support configuring replicas for balancerd and console in the Materialize CR, and default to two pods each.
Resolves https://github.com/MaterializeInc/cloud/issues/11619

support configuring replicas for balancerd and console in MZ CR

---

test/orchestratord/mzcompose.py

Remove duplicate get_console_data function from orchestratord tests.
Fix merge skew duplicate function. This is already defined a few lines above this one.

remove duplicate get_console_data function

---

ci/deploy/devsite.sh

Still failing unfortunately: https://buildkite.com/materialize/deploy/builds/19691#01998083-b58a-4617-a671-3fd35f46d8e1

dev docs: Restore previous state

---

Cargo.lock
src/adapter/Cargo.toml
src/adapter/src/catalog/migrate.rs

The
[SASL/SCRAM](https://github.com/MaterializeInc/materialize/pull/33468)
PR introduces the need for some stable, cluster wide, cryptographically
random key material. We use this material to be able to present
deterministic challenges for even users that don't exist to guard
against enumeration attacks. 
However that PR made a bad assumption that the initialize step of
catalog opening would always add this new key. But old versions that
have already been initialized wouldn't have it! This PR add code to
generate it for old versions
Fixes https://github.com/MaterializeInc/database-issues/issues/9724

Catalog: add migration for mock_authentication_nonce setting

---

src/adapter/src/catalog/state.rs
test/cluster/mzcompose.py

This PR changes the meaning of the existing `disk` field in `mz_clusters` and `mz_cluster_replicas` from "whether this cluster/replica has a disk or swap" to "whether this cluster/replica has a disk". I.e. the change is that the field shows `false` for swap-enabled clusters/replicas.
The motivation is two-fold:
* Whether a replica gets swap or not depends on the node it gets scheduled on. Pretending that swap-enabled replicas always get swap would be lying.
* More importantly, the console needs a way to know which clusters still use the old way of spilling to disk, to adjust its metrics UI accordingly. This change provides that way.
Part of https://github.com/MaterializeInc/database-issues/issues/9692
See [Slack …

adapter: set `mz_cluster{_replica}s.disk` to false with swap

---

misc/python/materialize/mzcompose/services/sql_server.py
misc/python/materialize/zippy/scenarios.py

My only explanation so far is that CI is just slower than local runs. I haven't managed to reproduce the failure yet with this, did 10 runs.
Fixes: https://github.com/MaterializeInc/database-issues/issues/9624

sql server: Try 5 min start_period

---

misc/python/materialize/test_analytics/data/cluster_spec_sheet/cluster_spec_sheet_result_storage.py
misc/python/materialize/test_analytics/setup/cleanup/remove-build.sql
misc/python/materialize/test_analytics/setup/tables/15-cluster-spec-sheet.sql
misc/python/materialize/test_analytics/setup/views/100-data-integrity.sql
misc/python/materialize/test_analytics/test_analytics_db.py
test/cluster-spec-sheet/mzcompose.py

Test run: https://buildkite.com/materialize/release-qualification/builds/959

cluster spec sheet: Store results in test analytics db

---

ci/nightly/pipeline.template.yml

Seen in https://buildkite.com/materialize/nightly/builds/13598#01998336-c808-426a-8214-fd019a458875

rust build: Don't overwrite default rust version

---

misc/python/materialize/checks/actions.py
misc/python/materialize/checks/all_checks/table_data.py
misc/python/materialize/checks/checks.py
misc/python/materialize/checks/executors.py

Based on https://materializeinc.slack.com/archives/C01LKF361MZ/p1758875954008029
This allows us to keep state around in checks.

platform-checks: Enable python-based actions

---

misc/python/materialize/mzcompose/__init__.py
misc/python/materialize/parallel_workload/action.py
src/adapter-types/src/dyncfgs.rs
src/adapter/src/catalog/open/builtin_item_migration.rs
src/catalog/src/durable.rs
test/0dt/mzcompose.py

This PR starts using persist schema evolution for builtin item migration. For each builtin storage collection to migrate, we first attempt to perform a schema evolution. The attempt may fail, if persist considers the new schema not compatible with the old one, in which case the existing shard replacement approach is performed as a fallback.
If there are any unexpected errors encountered during schema evolution, we abort the builtin migration process, to avoid accidentally losing data by running the shard replacement process for a builtin we didn't intend to replace. A dyncfg flag is introduced that makes it possible to skip schema evolution, giving us a way to force shard replacement in such cases, if we deem that the correct response.
Part of …

adapter: use persist schema evolution for builtin migration

---

test/cluster/mzcompose.py

The check was already waiting for _any_ results to appear, to work around the fact that `mz_frontiers` is not linearizable. However, it didn't consider the situation where only some of the requested frontiers were missing.
Fixes https://github.com/MaterializeInc/database-issues/issues/9743

test: fix read-frontiers-not-stuck check

---

src/repr/src/global_id.rs

Seen in https://buildkite.com/materialize/deploy/builds/19714#01999ba2-112a-4344-9006-ad0e8a3998b1
Follow-up to https://github.com/MaterializeInc/materialize/pull/33735

ci: Fix deploy step

---

src/repr/src/strconv.rs

Avoids reallocating the output vector.

Preallocate output in parse_bytes_traditional

---

ci/nightly/pipeline.template.yml
ci/test/rust-beta-build.sh

Seen in https://buildkite.com/materialize/nightly/builds/13629#01999cf6-b084-4764-94c9-05ef8c9487e7

ci: Clean up Rust after beta run

---

doc/developer/emulator.md
doc/developer/guide.md
src/materialized/ci/README.md

Otherwise you can end up any old version you previously pulled on your system.

emulator docs: Mention `docker pull --no-cache`

---

misc/python/materialize/cli/orchestratord.py
src/adapter/src/coord.rs
src/adapter/src/coord/ddl.rs

https://github.com/MaterializeInc/database-issues/issues/9708
not sure if there are other limits we want to check on startup, but this one is an important one to start with
we probably also want tests for this, but i'm about to head out for vacation for a week, so figured i would at least get this up before i left

also check credit consumption limit on environmentd startup

---

src/persist-client/src/internal/compact.rs
src/persist-client/src/internal/datadriven.rs
src/persist-client/tests/machine/compaction_bounded

Previously, we had two separate steps here: "flattening" turned the set of input batches into a set of runs, and "chunking" grouped those runs into sets of runs that could be compacted together without either violating requirements on our batch boundaries or our memory budget. This separation made sense historically, but recent changes made those requirements less trivial and the separation less useful... so this collapses the two methods together and then does a bunch of straightforward refactoring to simplify the logic.
This is mostly a noop, but it does have one useful effect for empty batches. Previously, those were discarded in the first step, but for incremental compaction it's useful to explicitly include those empty inputs in other chunks so incremental compaction will remove them …

[persist] Simplify compaction chunking logic (and support empty batches)

---

doc/user/content/sql/create-connection.md

Mainly based on the discussion [here](https://materializeinc.slack.com/archives/C08ACQNGSQK/p1759849905672599?thread_ts=1759836368.968969&cid=C08ACQNGSQK). Open to suggestions on the exact workding @kay-kim!
Also open to suggestions if it is worth updating the individual create connection examples to also include the region as well? Eg like so, or would it be an overkill?

docs: clarify default behavior for REGION in AWS connections
