MaterializeInc/materialize

- src/testdrive/src/lib.rs
Spawning a new task is no longer necessary to use
tokio::spawn::block_in_place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5336)
> testdrive: resolve a todo re: tokio::spawn::block_in_place

- misc/kafka-util/scripts/archive_topics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5348)
> Fixup logger name for archive topics

- doc/user/content/sql/types/_index.md
- doc/user/content/sql/types/list.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5364)
> docs: further explain custom type polymorphism

- misc/tb/README.md
Reported by @shamrin (thank you!).
Fixes #5354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5365)
> Fixup typo in tb README

- play/wikirecent/app/src/serve.py
- play/wikirecent/app/src/templates/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5369)
> Minor fixups to wikirecent play app

- src/dataflow/src/source/kafka.rs
This fixes the kafka statistics logging that is enabled by
`statistics_interval_ms`.
rdkafka has an internal event queue used for communicating back to the
application (variously referred to as rep, the main queue, etc.)
In the refactor ~8 months ago that split kafka sources into a single
consumer with separate queues for partitions we neglected to continue
polling the main queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5338)
> periodically poll rdkafka's event queue

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5378)
> Prepare v0.6.2 dev

- Cargo.lock
- src/materialized/Cargo.toml
- src/pgtest/Cargo.toml
- src/sql-parser/Cargo.toml
- src/transform/Cargo.toml
- src/walkabout/Cargo.toml
this lets us include https://github.com/justinj/datadriven/pull/4 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5379)
> bump justinj/datadriven to v0.5.0

- doc/developer/guide.md
Update the installation instructions for 2021, and update the list of
external repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5383)
> doc/developer: update developer guide

- src/coord/src/catalog/builtin.rs
I realized `list` types weren't included in the `pg_type` views, and when I added them the catalog went from 1s to open to 24s.
```diff
diff --git a/src/coord/src/catalog/builtin.rs b/src/coord/src/catalog/builtin.rs
index 672f82214..dfba0d804 100644
--- a/src/coord/src/catalog/builtin.rs
+++ b/src/coord/src/catalog/builtin.rs
@@ -1027,6 +1027,7 @@ pub const PG_TYPE: BuiltinView = BuiltinView {
CASE
WHEN EXISTS (SELECT 1 FROM mz_catalog.mz_array_types WHERE type_id = mz_types.id) THEN 'a'
WHEN EXISTS (SELECT 1 FROM mz_catalog.mz_base_types WHERE type_id = mz_types.id) THEN 'b'
+        WHEN EXISTS (SELECT 1 FROM mz_catalog.mz_list_types WHERE type_id = mz_types.id) THEN 'l'
WHEN EXISTS (SELECT 1 FROM mz_catalog.mz_map_types WHERE type_id = mz_types.id) THEN 'm'
END AS typtype, …
```
> catalog: refactor pg_type view definition

- doc/user/content/ops/diagnosing-using-sql.md
In the spirit of getting users to become self-sufficient, instead of directing them to `mz_dataflow_operator_dataflows`,
* explained how `mz_dataflow_operator_addresses` works
* put in a query that uses only sources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5081)
> Doc: Add query for finding an operator's dataflow name and id.

- src/expr/src/relation/func.rs
- src/sql-parser/src/ast/defs/expr.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan/func.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/transform_ast.rs
- test/sqllogictest/arrays.slt
This PR also implements `unnest()` for arrays.
Fixes #4828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5334)
> Full support for ANY/SOME/ALL for ARRAY and LIST

- src/materialized/src/bin/materialized/main.rs
MZ_THREADS has been deprecated for nearly six months, so it's time to
stop respecting it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5389)
> materialized: remove deprecated MZ_THREADS check

- misc/python/materialize/cli/mzcompose.py
Docker Compose has inconsistent rules about when it will restart
containers whose definition has changed. Specifically
docker-compose up -d SERVICE
will restart any of SERVICE's dependent containers, if they've changed.
But
docker-compose run SERVICE [ARGS...]
will not.
Paper over this irritating behavior by teaching mzcompose's run command
to rewrite `./mzcompose run SERVICE` to:
docker-compose up -d --scale=SERVICE=0 SERVICE \
&& docker-compose run SERVICE [ARGS...]
This will restart/rebuild any of SERVICE's dependencies before running
the command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5387)
> mzcompose: fix behavior of run command when dependent service changes

- src/coord/src/coord.rs
- src/materialized/tests/sql.rs
When creating a sink based on an unmaterialized object, the coordinator
intends to choose the minimum possible `AS OF` time, so that the sink
includes all updates that could possibly be emitted from that object.
The determine_frontier previously used timestamp 0 for this purpose,
but this was rather defective, as timestamp 0 might be before the
"since" frontier of involved sources. The ship_dataflow method would
notice this defective situation and complain about it, then fast-forward
the time to a valid time.
This resulted in a lot of ugly error messages about a situation that is
not actually problematic. So this commit changes determine_frontier to
choose a valid timestamp, and teaches ship_dataflow to return an error
message to the user rather than logging an error message. Now the …
> coord: consult since frontier when choosing timestamps for sinks

- play/wikirecent/app/src/templates/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5386)
> Fixup the chart variable name in the wikirecent app

- src/sql/src/plan/statement/ddl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5398)
> sql: fix minor import style glitches

- src/coord/src/coord.rs
- src/coord/src/session.rs
- src/pgwire/src/protocol.rs
- test/pgtest/portals.pt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5346)
> pgwire: improve portal close semantics and errors

- test/testdrive/monotonic.td
Closes #5403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5405)
> testdrive: Fix monotonic testdrive test to use monotonic aggregations

- doc/user/content/known-limitations.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5411)
> doc/user: fix gh shortcode syntax

- doc/user/content/cli/_index.md
- doc/user/content/release-notes.md
- doc/user/content/sql/alter-index.md
- doc/user/content/sql/alter-rename.md
- doc/user/content/sql/close.md
- doc/user/content/sql/create-sink.md
- doc/user/content/sql/create-type.md
- doc/user/content/sql/declare.md
- doc/user/content/sql/fetch.md
- doc/user/content/sql/insert.md
- doc/user/content/sql/join.md
- doc/user/content/sql/select.md
- doc/user/content/sql/show-create-index.md
- doc/user/content/sql/system-catalog.md
- doc/user/content/sql/types/array.md
- doc/user/content/sql/types/interval.md
- doc/user/content/sql/types/list.md
- doc/user/content/sql/types/map.md
- doc/user/content/sql/types/record.md
- doc/user/layouts/shortcodes/version-added.html
- doc/user/layouts/shortcodes/version-changed.html
Don't review yet. I haven't done copyediting yet, nor fleshed out the docs for the new timezone support. But wanted to get this out to avoid duplicating effort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5415)
> doc/user: polish v0.6.1 release notes

- src/dataflow/src/server.rs
We would previously take `(row, count)` information from differential dataflow and expand it out to `count` copies of `row`. While this might be needed, when we have a `LIMIT` set, we can restrict `count` down to that limit. This change is relevant because DD is capable of efficiently producing and compactly maintaining rows with great counts, and we risk falling over in a situation where we don't have to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5420)
> Limit copies of results before they are copied

- src/dataflow/src/render/mod.rs
- test/testdrive/consolidation.td
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5430)
> dataflow: consolidate data flowing into TAIL sinks

- misc/dbt-materialize/README.md
- misc/dbt-materialize/setup.py
Replaces @jwills information with Materialize's support information.
Thanks again, @jwills!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5451)
> dbt-materialize: update author and author_email

- play/wikirecent/app/Dockerfile
- play/wikirecent/app/requirements.txt
The Dockerfile was (poorly) duplicating logic already present in pip --
let pip do the git clone, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5453)
> Simplify psycopg3 install for wikirecent demo

- demo/chbench/bin/generate_snapshot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5463)
> fixup! Archive the entire kafka directory in chbench (#5457)

- Cargo.lock
- src/aws-util/src/aws.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/plan/statement/with_options.rs
- src/testdrive/Cargo.toml
- src/testdrive/src/action.rs
- src/testdrive/src/action/s3.rs
- src/testdrive/src/error.rs
- src/testdrive/src/lib.rs
- src/testdrive/src/main.rs
- src/testdrive/src/util/postgres.rs
- test/testdrive/esoteric/s3.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5465)
> s3 sources: Add testdrive support for S3 and related tests

- Cargo.lock
- doc/user/content/release-notes.md
- doc/user/layouts/partials/create-source/connector/file/details.html
- doc/user/layouts/partials/create-source/connector/file/syntax.html
- doc/user/layouts/partials/sql-grammar/create-source-csv-file.svg
- doc/user/layouts/partials/sql-grammar/create-source-text.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/avro/src/decode.rs
- src/coord/src/timestamp.rs
- src/dataflow-types/src/types.rs
- src/dataflow/Cargo.toml
- src/dataflow/src/source/file.rs
- src/sql-parser/Cargo.toml
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- src/testdrive/Cargo.toml
- src/testdrive/src/action/file.rs
- test/testdrive/source-compression.td
Fixes #4861
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5392)
> Support gzipped file sources

- test/lang/csharp/mzcompose.yml
See NuGet/Home#10491.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5487)
> test/lang/csharp: work around NuGet certificate error

- doc/user/content/sql/tail.md
- test/lang/csharp/SmokeTest.cs
- test/lang/csharp/csharp-npgsql4.csproj
- test/lang/csharp/csharp-npgsql5.csproj
- test/lang/csharp/test.sh
Verify npgsql changes by making the smoke tests match the doc.
Fixes #5483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5488)
> doc: update TAIL docs to match current best practices

- src/materialized/src/http/sql.rs
Decimals were previously just the significand i128 + "dec". In order to
correctly display these we need a Decimal, not a Significand type. So,
we need to get the scale out of the column types so we know where to
put the decimal point and correctly convert to string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5494)
> materialized: fix decimal json serialization

- test/lang/csharp/SmokeTest.cs
Add some extra stuff to the end to assert the copy is complete and we
can issue other statements on the connection. Use that to also clean up
the table so the tests can execute in any order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5493)
> test: add back csharp copy test

- src/kafka-util/src/bin/kgen.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5512)
> improve kgen error messages

- src/expr/src/scalar/func.rs
- src/sql/src/plan/func.rs
- test/sqllogictest/funcs.slt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5538)
> Add support for `array_length()`

- doc/user/README.md
CC @benesch you said you want to get pinged when I wish there had been more docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5525)
> Add some links pointing to different parts of the create-source docs

- Cargo.lock
- Cargo.toml
- test/performance/s3-datagen/Cargo.toml
- test/performance/s3-datagen/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5503)
> A script that can create arbitrary amounts of s3 data for benchmarks

- src/pgwire/src/protocol.rs
Previously if the connection was closed while the state machine was
trying to read the next message in advance_ready, the error path would
avoid calling terminate and could leave portals open. This could cause
a file descriptor leak since dataflow uses sockets for communication.
See #5543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5550)
> pgwire: call Terminate even at connection error

- src/testdrive/src/main.rs
- src/testdrive/tests/cli.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5518)
> testdrive: Add details to some comments and add a debug print

- ci/test/mkpipeline.py
@philip-stoev what do you think about this? 
This is an alternative to #5556. The idea is that when anything about
the CI configuration itself changes, we ought not attempt to trim any
jobs from the CI pipeline, and just run everything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5560)
> ci: test everything when glue code changes

- ci/test/mkpipeline.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5566)
> ci: have_paths_changed now takes a single iterable

- doc/user/content/sql/create-source/_index.md
- doc/user/content/sql/create-source/csv-s3.md
- doc/user/content/sql/create-source/json-s3.md
- doc/user/content/sql/create-source/text-s3.md
- doc/user/layouts/partials/aws-credentials-with-options.html
- doc/user/layouts/partials/create-source/connector/kinesis/with-options.html
- doc/user/layouts/partials/create-source/connector/s3/details.html
- doc/user/layouts/partials/create-source/connector/s3/syntax.html
- doc/user/layouts/partials/create-source/connector/s3/with-options.html
- doc/user/layouts/partials/sql-grammar/create-source-s3-csv.svg
- doc/user/layouts/partials/sql-grammar/create-source-s3-json.svg
- doc/user/layouts/partials/sql-grammar/create-source-s3-text.svg
- doc/user/sql-grammar/sql-grammar.bnf
- test/testdrive/esoteric/s3.td
First pass at #5414, but definitely needs wordsmithing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5524)
> Initial pass at S3 source documentation

- test/benchmark/avro-upsert/create_views/create_views
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5582)
> avro-upsert: update for new required materialize user

- doc/user/content/sql/create-sink.md
- doc/user/layouts/partials/sql-grammar/create-sink.svg
- doc/user/layouts/partials/sql-grammar/sink-kafka-connector.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5595)
> document upsert sinks

- test/benchmark/avro-upsert/generator/distributions/benchmark/value-distribution.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5606)
> bench/avro-upsert: tweak generator to send larger payloads

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5590)
> Prepare v0.7.1 dev

- test/benchmark/avro-upsert/create_views/views/insert_views.sql
- test/benchmark/avro-upsert/create_views/views/upsert_views.sql
- test/benchmark/avro-upsert/generator/distributions/benchmark/key-distribution.json
- test/benchmark/avro-upsert/generator/distributions/benchmark/key-schema.json
- test/benchmark/avro-upsert/generator/distributions/benchmark/value-distribution.json
- test/benchmark/avro-upsert/generator/distributions/benchmark/value-schema.json
- test/benchmark/avro-upsert/generator/distributions/small/key-distribution.json
- test/benchmark/avro-upsert/generator/distributions/small/key-schema.json
- test/benchmark/avro-upsert/generator/distributions/small/value-distribution.json
- test/benchmark/avro-upsert/generator/distributions/small/value-schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5629)
> Simplify column names in Avro Upsert benchmark

- doc/user/content/get-started.md
Add a username to a connection string in the docs that was missed in
the transition to requiring valid user names.
Fix #5631.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5633)
> doc/user: add username to connection string

- Cargo.lock
- LICENSE
- doc/user/config.toml
- doc/user/content/connect/cli.md
- doc/user/content/release-notes.md
- doc/user/content/sql/create-role.md
- doc/user/content/sql/create-user.md
- doc/user/content/sql/drop-role.md
- doc/user/content/sql/drop-user.md
- src/coord/src/catalog/storage.rs
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5671)
> Mark v0.7.0 as released

- doc/user/content/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5675)
> Next version is 0.7.1

- doc/user/content/sql/create-table.md
Rework the CREATE TABLE doc to change the messaging of tables around. In
particular, this commit removes any references to tables as
"non-streaming data sources", as in Materialize a core tenent is that a
table is just a realization of a stream at a particular moment in time.
Also stress that most users should use sources in almost all cases, and
explicitly explain the pitfalls of tables, particularly around memory
usage.
Related to #5611 and #5627.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5634)
> doc/user: rework table overview and restrictions

- doc/user/content/overview/what-is-materialize.md
Replaces Kafka-specific explanation with a more general one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5234)
> docs: update How does Materialize work?

- doc/user/CONTRIBUTING.md
- doc/user/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/4980)
> docs: add CONTRIBUTING.md

- .github/ISSUE_TEMPLATE/release.md
so they can prepare an appropriate comms plan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5692)
> include marketing in release process

- src/sql-parser/src/ast/defs/query.rs
- src/sql/src/plan/query.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5696)
> Add some comments describing the name resolution pass

- src/sql/src/ast/mod.rs
- src/sql/src/lib.rs
- src/sql/src/names.rs
- src/sql/src/normalize.rs
- src/sql/src/parse.rs
- src/sql/src/plan/statement.rs
- src/sql/src/pure.rs
Add a brief overview of the sql crate to its module docs. Supersedes
PR #2961 very belatedly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5693)
> sql: improve module docs

- src/expr/src/scalar/mod.rs
- test/testdrive/date_func.td
Sorry, @philip-stoev, I didn't manage to actually write test cases for this yet. I'll do it tomorrow unless for some reason you are excited enough about this fix that you do it first!
Fix #5521.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5700)
> expr: propagate errors when reducing date_{part,trunc}

- src/materialized/src/bin/materialized/main.rs
This was meant to be the format of the PR, git failed me or I failed git.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5710)
> panic: fix panic location message

- src/dataflow/src/source/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5716)
> Add an error message if partition metrics do not exist

- doc/user/content/sql/functions/cast.md
- doc/user/content/sql/types/_index.md
- doc/user/content/sql/types/bytea.md
- doc/user/layouts/partials/sql-grammar/type-bytea-esc.svg
- doc/user/layouts/partials/sql-grammar/type-bytea-hex.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5731)
> 5344: documentation of bytea data type

- src/dataflow/src/render/join/delta_join.rs
This PR refactors delta join rendering into a planning stage and a rendering stage. This is mostly a refactor, but it does clarify which steps can be performed in the absence of a rendering scope, and hoists them out into independent logic. The intent is that this might help testing. The potential risk is that it ossifies join planning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5707)
> Stage deltajoin planning and rendering

- play/wikirecent/app/utils/async_tail.py
- play/wikirecent/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5742)
> Convert psycopg3 example to use stream method

- src/dataflow/src/render/upsert.rs
This PR disables linear operators from executing before the upsert operator. It fixes some issues with both temporal predicate pushdown as well as filters that error (of which temporal predicates were a special case). We can introduce it back again, but this should remove some wonkiness seen in the wild.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5750)
> Disable linear operators before upsert

- src/coord/src/coord.rs
- test/sqllogictest/transactions.slt
Fixes #5725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5734)
> coord: verify diff target exists on commit

- Cargo.lock
- src/aws-util/Cargo.toml
- src/aws-util/src/lib.rs
- src/aws-util/src/sqs.rs
- src/dataflow-types/src/types.rs
- src/dataflow/Cargo.toml
- src/dataflow/src/source/s3.rs
- src/dataflow/src/source/s3/notifications.rs
- src/expr/src/id.rs
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql/src/plan/statement/ddl.rs
This implements the "quick" version of #5502.
Part of #4914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5569)
> s3 sources: Support reading new keys from S3 SQS Notifications

- src/dataflow/src/source/s3.rs
- src/dataflow/src/source/s3/metrics.rs
Per-bucket metrics on objects discovered and downloaded, and bytes/lines read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5740)
> Add S3-specific Prometheus metrics

- doc/user/layouts/partials/create-source/connector/s3/details.html
- doc/user/layouts/partials/create-source/connector/s3/syntax.html
- doc/user/layouts/partials/create-source/connector/s3/with-options.html
- doc/user/layouts/partials/sql-grammar/create-source-s3-csv.svg
- doc/user/layouts/partials/sql-grammar/create-source-s3-json.svg
- doc/user/layouts/partials/sql-grammar/create-source-s3-text.svg
- doc/user/sql-grammar/sql-grammar.bnf
Docs for the related PR #5569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5724)
> s3 sources: SQS notifications docs

- src/dataflow/src/operator.rs
This improves release dataflow builds by about 10% for me (about 15s). Not a lot, but it's an easy change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5784)
> [dataflow] Box closure to reduce compilation

- doc/user/content/release-notes.md
I forgot to credit @andrioni for the cbrt implementation when I merged
PR #5763.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5787)
> doc/user: attribute cbrt to @andrioni

- src/materialized/src/bin/materialized/sys.rs
If we segfault while panicking because of a segfault, do something
smarter than trying to panic *again*. Usually the issue is a stack
overflow in the memory allocator, which corrupts the memory allocator
heap, which means the panic handler is hosed because it allocates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5790)
> materialized: better handling of double segfaults

- src/materialized/src/http.rs
- src/pgwire/src/server.rs
This ensures the client sees the handshake error. Fix #5778.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5786)
> materialized,pgwire: flush stream after TLS handshake error

- doc/user/content/cli/_index.md
- src/materialized/src/bin/materialized/main.rs
- test/kafka-krb5/mzcompose.yml
- test/kafka-sasl-plain/mzcompose.yml
- test/kafka-ssl/mzcompose.yml
- test/metabase/mzcompose.yml
- test/testdrive/mzcompose.yml
@frankmcsherry I didn't do a great job on the documentation. Let me know if you have better copy.
Fix #5775.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5793)
> doc/user: rename --logging-granularity to --introspection-frequency and document it

- doc/user/layouts/partials/aws-credentials-with-options.html
Thanks to @quodlibetor we now support more than just Kinesis!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5795)
> doc: update AWS credentials block

- src/dataflow/src/render/mod.rs
- src/dataflow/src/render/reduce.rs
this pr is an attempt at splitting out the reduce rendering code into two phases:
1. a "planning" phase that decides what is going to be rendered and produces a `LIrReduceExpr` that we can print out and in the future, assert against in test
and
2. a "building" phase that goes out and builds the dataflow(s).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5600)
> LIRR: Low level IR for Reduce

- src/materialized/tests/tls.rs
@elindsey I'm now convinced that we're not doing anything wrong, but this solution is not particularly satisfying. But seemed like the best available option. Let me know what you think.
Thanks again for the help debugging earlier today!
----
This will put a stop to the test_tls flakes for once and all. TLS v1.3
produces bad, flaky error messages because failing to present a client
certificate errors on the first attempt to read from the connection,
*not* during the TLS handshake. Neither `hyper` nor `postgres`
produces a stable error message in these situations; the error message
that gets produced depends on the timing of various sends/recv during
the startup of their respective protocols.
See: https://github.com/openssl/openssl/issues/11118
---
This change is [<img …
> materialized: use TLS v1.2 in tests

- doc/user/content/release-notes.md
- src/coord/src/catalog/migrate.rs
- test/catalog-compat/catcompatck/catcompatck
Fixes #5808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5813)
> coord: fix migration of sinks using `WITH SNAPSHOT AS OF`

- doc/developer/fast-compiles.md
Per the eagle-eyed @andrioni.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5819)
> doc/developer: correct models in fast-compiles.md

- Cargo.lock
- src/dataflow/src/source/s3.rs
- src/testdrive/Cargo.toml
- src/testdrive/src/action.rs
- src/testdrive/src/action/s3.rs
- src/testdrive/src/action/sleep.rs
- src/testdrive/src/lib.rs
- test/testdrive/esoteric/s3.td
- test/testdrive/mzcompose.yml
Testdrive changes to support a new set of tests in SQS.
The very last test fails in LocalStack but succeeds in AWS, currently I'm not considering that a blocker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5723)
> Add tests for S3 SQS notifications

- doc/user/config.toml
- doc/user/content/sql/create-source/_index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5820)
> docs: refactor link to create sources under connect

- doc/user/content/sql/create-source/_index.md
- doc/user/content/sql/create-source/json-file.md
- doc/user/layouts/partials/create-source/format/bytes/details.html
- doc/user/layouts/partials/create-source/format/bytes/syntax.html
- doc/user/layouts/partials/create-source/format/json-bytes/details.html
- doc/user/layouts/partials/create-source/format/json-bytes/syntax.html
- doc/user/layouts/partials/sql-grammar/create-source-json.svg
- doc/user/sql-grammar/sql-grammar.bnf
@awang just a ping that I integrated your feedback into some docs changes to give folks wanting to use local JSON files a little more help
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5824)
> docs: refactor JSON-formatted sources

- Cargo.lock
- src/materialized/Cargo.toml
- src/materialized/src/version_check.rs
A new token is created every time materialized is restarted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5823)
> Add Session ID to telemetry data

- src/coord/src/catalog.rs
- src/coord/src/catalog/metrics.rs
- src/coord/src/coord.rs
- src/coord/src/coord/metrics.rs
This adds total number of user-defined sources/sinks (by type) and views.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5822)
> Add some catalog information to Prometheus metrics

- src/coord/src/coord/metrics.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5832)
> Fix merge skew with new postgres source type

- demo/chbench/mzcompose.yml
- test/chaos/mzcompose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5834)
> get rid of restart: always

- src/sql/src/plan/error.rs
- src/sql/src/plan/statement/ddl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5835)
> Don't allow upsert sinks without a key

- doc/developer/fast-compiles.md
Reviewed as https://github.com/MaterializeInc/materialize/pull/5853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5856)
> Add a "Hosted machine" section to fast-compiles.md

- src/dataflow/src/render/mod.rs
- src/dataflow/src/render/sinks.rs
- src/dataflow/src/render/sources.rs
This PR does nothing except extract the `import_source` and `export_sink` methods into their own files, so that their complexity can be isolated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5867)
> Extract source and sink creation

- Cargo.lock
- src/dataflow/src/arrangement/manager.rs
- src/dataflow/src/server.rs
- test/testdrive/github-5774.td
This collects an updated DD that fixes #5774, and addresses several method calls that have been deprecated.
fixes #5774.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5857)
> Collect updated differential; update deprecated calls

- src/testdrive/src/action.rs
- src/testdrive/src/action/postgres.rs
This will facilitate writing testdrive tests for the new PostgreSQL
source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5858)
> testdrive: learn to query an arbitrary PostgreSQL instance

- src/sql/src/normalize.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5869)
> with_options!: Document that the struct field types are Option-ized

- doc/developer/mzbench.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5886)
> Better documentation for mzbench

- play/wikirecent-dbt/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5892)
> play: add materialize user to dbt config

- misc/dbt-materialize/README.md
- misc/dbt-materialize/dbt/include/materialize/sample_profiles.yml
I added [`dbt-materialize` to PyPi](https://pypi.org/project/dbt-materialize/0.18.1/)!   🎉 
Wanted to make a few changes to `dbt-materialize`'s `README` to make it more PyPI-friendly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5893)
> dbt-materialize: update README for PyPI

- src/testdrive/src/action/s3.rs
This commit investigates whether the flakiness in our S3 SQS tests is due to a
race in AWS, where the configuration for SQS notifications does not fully take
effect immediately.
To ensure that that is not the case, we don't allow testdrive to continue on
from notification configuration until it has observed at least one valid
"object has been created" message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5897)
> s3-sqs: Wait for a notification when configuring S3 SQS

- src/dataflow/src/source/s3.rs
- test/testdrive/mzcompose.yml
In concert with #5897 this is intended to help diagnose exactly where SQS messages are not
appearing or are being dropped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5898)
> Add and enable some logs to investigate SQS test flakiness

- doc/user/content/sql/create-type.md
- doc/user/content/sql/drop-type.md
- doc/user/content/sql/show-types.md
- doc/user/layouts/partials/sql-grammar/drop-index.svg
- doc/user/layouts/partials/sql-grammar/drop-type.svg
- doc/user/layouts/partials/sql-grammar/show-types.svg
- doc/user/sql-grammar/sql-grammar.bnf
Open questions:
* How do you list all custom data types? 
* The Postgres version of this drops dependent tables, functions, and operators as well as types; do we?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5847)
> (doc) DROP TYPE and SHOW TYPES

- doc/user/content/release-notes.md
I forgot to add this in https://github.com/MaterializeInc/materialize/pull/5877
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5878)
> add release note for idempotent kafka sinks

- doc/user/content/versions.md
- misc/www/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5910)
> doc/user,www: use HTTPS for all tarball download links

- Cargo.lock
There is a good chance that this fixes builds on Apple silicon.
~Touches #5915.~ Confirmed by @JakeMakesStuff to fix #5915.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5916)
> deps: upgrade to latest cc

- src/materialized/tests/sql.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5920)
> Manually time out in test_no_block

- doc/developer/guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5921)
> Clarify Confluent Platform instructions

- bin/check
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5927)
> Add a bunch of lints

- doc/developer/guide-testing.md
- doc/developer/guide.md
- doc/developer/setup-mysql-debezium.md
- doc/developer/setup-postgres-debezium.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5922)
> docs: update developer guide for latest confluent platform

- src/materialized/tests/sql.rs
This test is sporadically failing, apparently not due to any problem in Materialize, but because of Kafka flakiness. Comment it out to unblock CI for now.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5947)
> Comment out test_no_block

- src/materialized/tests/sql.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5951)
> Uncomment test_no_block, and `#[ignore]` it instead.

- misc/monitoring/dashboard/conf/grafana/dashboards/overview.json
- misc/python/materialize/cli/dashboard_clean.py
This incorporates all the changes we've made since the last update to the dashboard, in particular the query changes required by #5940.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5957)
> Update grafana dashboard for new metrics

- Cargo.lock
- ci/test/cargo-test/mzcompose.yml
- src/materialized/Cargo.toml
- src/materialized/tests/sql.rs
- src/sql/src/kafka_util.rs
- src/sql/src/pure.rs
Fix #5949. Also a bunch of other cleanup that I noticed while I was in the area. See commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5954)
> Deflake and re-enable test_no_block

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5961)
> Prepare v0.7.2 dev

- doc/developer/guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5924)
> doc: add crates.io and PyPI notes

- misc/python/materialize/mzcompose.py
- test/benchmark/avro-upsert/mzcompose.yml
Split off from #5958 because it's worth merging independently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5976)
> Add a mzcompose lint requiring MZ_DEV=1 in the environment

- doc/developer/guide-testing.md
The timestamp assignment code now lives in coord, not dataflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5980)
> doc/developer: update location of timestamp assignment in testing guide

- doc/developer/diagnostic-questions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5979)
> Developer doc: Add tips for making joins smaller.

- doc/developer/mzbuild.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5969)
> Document --mz-build-mode flag to mzcompose

- test/lang/js/babel.config.js
- test/lang/js/params.test.ts
- test/lang/js/test.sh
- test/lang/js/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6000)
> Get JS formatting fixed and a bit more stable

- src/ore/Cargo.toml
- src/ore/src/ascii.rs
- src/ore/src/assert.rs
- src/ore/src/cast.rs
- src/ore/src/cli.rs
- src/ore/src/collections.rs
- src/ore/src/env.rs
- src/ore/src/fmt.rs
- src/ore/src/future.rs
- src/ore/src/hash.rs
- src/ore/src/hint.rs
- src/ore/src/iter.rs
- src/ore/src/lib.rs
- src/ore/src/netio/async_ready.rs
- src/ore/src/netio/framed.rs
- src/ore/src/netio/mod.rs
- src/ore/src/netio/read_exact.rs
- src/ore/src/netio/stream.rs
- src/ore/src/option.rs
- src/ore/src/panic.rs
- src/ore/src/result.rs
- src/ore/src/retry.rs
- src/ore/src/stats.rs
- src/ore/src/str.rs
- src/ore/src/sync.rs
- src/ore/src/test.rs
- src/ore/src/thread.rs
- src/ore/src/vec.rs
Arjun said this is OK in slack: https://materializeinc.slack.com/archives/CM7ATT65S/p1614611559124500?thread_ts=1614390722.111700&cid=CM7ATT65S
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6003)
> state that ore is licensed under Apache 2.0

- src/avro/src/writer.rs
- src/ccsr/src/tls.rs
- src/coord/src/catalog.rs
- src/coord/src/client.rs
- src/coord/src/command.rs
- src/coord/src/session/vars.rs
- src/dataflow/src/operator.rs
- src/dataflow/src/server/metrics.rs
- src/dataflow/src/source/mod.rs
- src/expr/src/relation/mod.rs
- src/interchange/src/avro.rs
- src/kafka-util/src/admin.rs
- src/materialized/src/lib.rs
- src/metabase/src/lib.rs
- src/ore/src/future.rs
- src/ore/src/iter.rs
- src/repr/src/adt/jsonb.rs
- src/repr/src/row.rs
- src/repr/src/scalar.rs
- src/repr/src/strconv.rs
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql/src/catalog.rs
- src/sql/src/func.rs
- src/sql/src/plan/expr.rs
- src/testdrive/src/format/protobuf.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6009)
> *: fix some rustdoc warnings

- test/testdrive/github-5873.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6020)
> Test case for crash fixed by #5873

- src/testdrive/src/action/s3.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6013)
> td: Improve and correct progress messages in s3 sqs notification test

- src/expr/src/scalar/func.rs
- test/sqllogictest/jsonb.slt
- test/sqllogictest/map.slt
- test/sqllogictest/type-promotion.slt
- test/testdrive/types.td
fixes #5829
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6016)
> expr: don't silently convert invalid json to Null

- doc/user/content/sql/tail.md
- src/pgwire/src/protocol.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6005)
> doc: tail warnings

- doc/user/config.toml
- doc/user/content/connect/materialize-cdc.md
- doc/user/content/overview/what-is-materialize.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6036)
> (doc) Move CDC doc underneath Connect menu

- misc/python/materialize/mzcompose.py
- test/kafka-matrix/kafka-matrix.td
- test/kafka-matrix/mzcompose
- test/kafka-matrix/mzcompose.yml
This tests binary, avro and CVS sinks with multiple Kafka versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6038)
> Matrix smoke test against various Kafka versions #5968

- doc/developer/design/00000000_template.md
- doc/developer/design/20200520_exactly_once_kafka.md
- doc/developer/design/README.md
This is a draft of a lightweight design/review process. Some aspects were cribbed from Java's JEP process and Cockroach's RFCs. It includes two prior examples in the same spirit (though not using the exact same template).
Roughly, these are my principles that went into the draft:
1. As little process as necessary. More structure can be added later if it's useful, but best to arrive there gradually and grudgingly.
2. Deep ownership by the author
3. Explicit communication, especially around things we are choosing _not_ to do
It's opinionated, and I'd like to hear everyone else's opinions/input as well so we can land on something useful. Comment away! 🙂
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> draft of design doc process

- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose.py
- test/persistent-tables/after-restart.td
- test/persistent-tables/before-restart.td
- test/persistent-tables/mzcompose
- test/persistent-tables/mzcompose.yml
Reviewed already at https://github.com/ruchirK/materialize/pull/18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6061)
> Simple test for table persistence

- doc/developer/design/00000000_template.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6065)
> add title section to design doc

- src/dataflow/src/decode/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6067)
> Binding by-ref and by-move in the same pattern is now stable

- doc/developer/guide-testing.md
Most of it was updated in https://github.com/MaterializeInc/materialize/pull/5969 but I stumbled across these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6095)
> doc/developer: update remaining instances of BUILD_MODE

- src/testdrive/src/action/s3.rs
- test/testdrive/esoteric/s3.td
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6099)
> Fix testdrive S3 parameter name

- Cargo.lock
- deny.toml
These bumps remove a few duplicate dependencies from the tree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6103)
> deps: bump some minor versions

- src/testdrive/src/action.rs
- src/testdrive/src/action/sql.rs
@philip-stoev sorry for not getting you this feedback on the review! Been swamped lately. Happened to be in the area so whipped this up.
"SQLContext" is more properly spelled "SqlContext", per Rust style
guides. Also take the opportunity to rename SqlContext::sql_timeout to
SqlContext::timeout to avoid the stutter. Finally, tweak the building of
the set-regex action to not panic of the provided string is not a valid
regex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6108)
> testdrive: tweak some names

- doc/user/content/release-notes.md
- doc/user/content/sql/functions/jsonb_agg.md
- doc/user/content/sql/functions/jsonb_object_agg.md
- doc/user/data/sql_funcs.yml
- src/dataflow/src/render/reduce.rs
- src/expr/src/relation/func.rs
- src/sql/src/func.rs
- src/sql/src/plan/expr.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/jsonb.slt
Fix #3875.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6111)
> sql: add the jsonb_object_agg function

- Cargo.lock
- src/materialized/Cargo.toml
- src/materialized/src/bin/materialized/main.rs
Fix #6117.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6119)
> materialized: don't emit colored log output to stderr if not tty

- src/coord/src/timestamp.rs
- src/dataflow/src/sink/kafka.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6116)
> coord,dataflow: downgrade misleading error logs

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/coord/src/catalog.rs
- src/coord/src/catalog/config.rs
- src/coord/src/client.rs
- src/coord/src/coord.rs
- src/materialized/src/lib.rs
- src/materialized/src/version_check.rs
- src/pgrepr/src/oid.rs
- src/sql/src/catalog.rs
- src/sql/src/func.rs
- src/sql/src/plan/statement/ddl.rs
- test/testdrive/system-functions.td
See individual commits for details!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6110)
> sql: add several system information functions

- play/wikirecent-dbt/README.md
Updates demo README to include more explicit guidance for those
using Docker. Updates crafted from [user feedback](https://github.com/sungchun12/materialize/commit/1d44cfba9a406052da67f782f0928b2a7316242f#diff-53c2db9b18436fdd1ae9a43e45cc531c533efe15dab4e4f3363973ec9bf236cfR128).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6139)
> wikirecent-dbt: update demo README

- doc/user/content/release-notes.md
- src/sql/src/plan/query.rs
- test/sqllogictest/order_by.slt
Fix #6021.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6146)
> sql: fix off-by-one with DISTINCT and ORDER BY

- test/atp/driver/docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6150)
> Proper docker-compose.yml for the atp driver

- src/transform/src/column_knowledge.rs
This PR is dual to #6141 and *fixes* `column_knowledge.rs` rather than disabling it. In particular, it *weakens* the analysis, not applying any optimizations to the `cond` member of `MirRelationExpr::If`, as this has the potential to incorrectly specialize the conditional evaluation of the expression (incorrect, in that should the relationship of the expression and whatever other expressions provided the signal for optimization change, it would be wrong).
This leaves us in a state where expressions are still allowed to migrate arbitrarily throughout the plan, and certain optimizations are increasingly absent as a consequence. Introducing a "physical optimization" pass would allow us to recover these.
cc @philip-stoev if you are interested to try this out, I'd be curious. I think something …
> Fix column knowledge

- src/coord/src/catalog.rs
- src/coord/src/catalog/migrate.rs
- src/coord/tests/testdata/t
- src/materialized/tests/server.rs
- src/sql-parser/src/ast/display.rs
- src/sql-parser/src/parser.rs
- src/sql/src/normalize.rs
- src/sql/src/plan.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement/show.rs
- src/symbiosis/src/lib.rs
- test/catalog-compat/catcompatck/Dockerfile
- test/catalog-compat/catcompatck/catcompatck
- test/sqllogictest/cockroach/case_sensitive_names.slt
- test/sqllogictest/id.slt
- test/sqllogictest/types.slt
This PR currently has a few issues: first, there's an error message I
throw away because we currently detect it by looking at what names we
have. Not sure how to recover that. Second, there's currently a failing
test in the TLS code that I don't know how to debug, but am going to
dive into a bit later.
I also do not have the most confidence that this doesn't break things,
so I need to go through and give it all another testing pass. Throwing
it up to get some eyes on it to see if there are any obvious big
problems I'm missing!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/5816)
> sql: resolve names as part of normalization

- src/dataflow/src/source/file.rs
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/kinesis.rs
- src/dataflow/src/source/mod.rs
- src/dataflow/src/source/s3.rs
- src/expr/src/id.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6169)
> dataflow: Refactor PartitionMetrics to live under SourceMetrics

- .vscode/settings.json
- doc/user/content/sql/show-tables.md
- src/sql/src/plan/statement/show.rs
- test/testdrive/catalog.td
I saw the other ones are pretty similar. But not sure if this one is the right way to implement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6159)
> Support SHOW EXTENDED TABLES

- doc/developer/observing_materialize.md
- doc/user/content/release-notes.md
- doc/user/content/sql/system-catalog.md
- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6193)
> Document mz_kafka_consumer_statistics

- doc/user/layouts/partials/create-source/envelope/upsert/details.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6140)
> add benefits+tradeoffs for upsert envelope

- doc/user/content/sql/system-catalog.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6209)
> Document mz_source_info

- src/ore/src/retry.rs
- src/testdrive/src/action/sql.rs
In the typical CREATE -> inject -> SELECT pattern, it takes
several seconds for the SELECT to return the right result because
the retry strategy is not aggressive enough and quickly begins to
perform multi-second sleeps.
Modify retry.rs to allow for a custom exponential factor to be
specified so that testdrive can use factor 1.5 and a starting backoff
value of 50ms.
This change alone shaves a second or more from each eligible SELECT. This should make for faster builds and also benefit the ATP testing effort as the tests will be more "stressful" overall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6198)
> testdrive: more aggressive retry of SQL statements

- src/dataflow/src/server.rs
(small thing I noticed while reading this code)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6231)
> dataflow: remove duplicate let binding

- src/dataflow/src/render/reduce.rs
Per discussion in #6217. I'm not sure whether this actually makes things
clearer, but wanted to submit for evaluation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6230)
> dataflow: factor out total field in reduce accumulator

- src/coord/src/command.rs
- src/coord/src/coord.rs
- src/coord/src/session.rs
- src/pgwire/src/message.rs
- src/pgwire/src/protocol.rs
- test/pgtest/transactions.pt
@JLDLaughlin My second PR 😄 
I added this warning feature and tested by building a binary to try it out. I wonder how I can add some unit test to this feature?
Thank you!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6220)
> Output warning for duplicated BEGIN transaction

- doc/user/content/sql/create-source/csv-s3.md
- doc/user/content/sql/create-source/json-s3.md
- doc/user/content/sql/create-source/text-s3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6227)
> docs: Make it clearer that S3 objects can contain multiple records

- Cargo.lock
- LICENSE
- doc/user/config.toml
- src/materialized/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6216)
> Mark v0.7.1 as released

- doc/user/content/release-notes.md
- doc/user/content/sql/functions/timezone-and-at-time-zone.md
- doc/user/content/sql/types/timestamp.md
- doc/user/data/sql_funcs.yml
- doc/user/layouts/partials/sql-grammar/drop-type.svg
- doc/user/layouts/partials/sql-grammar/func-at-time-zone.svg
- doc/user/layouts/partials/sql-grammar/func-timezone.svg
- doc/user/sql-grammar/sql-grammar.bnf
Fixes #5481 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6069)
> document new `AT TIME ZONE` operators

- src/dataflow/src/decode/metrics.rs
- src/dataflow/src/decode/mod.rs
- src/dataflow/src/render/sources.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6263)
> debezium-upsert: Track the size of the tracking state in prometheus

- src/dataflow/src/render/sources.rs
- src/expr/src/id.rs
Word-wrap a couple and convert a non-doc-comment into a docco
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6265)
> Format some comments

- demo/chbench/mzcompose.yml
Introduced in e88f89beec2903dfe5ee2b01c518ecd9ecf98226.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6266)
> Fixup typo in chbench mzcompose.yml

- src/materialized/src/http.rs
- src/ore/src/future.rs
An HTTP connection that closes at the wrong time can cause Materialize
to panic. The cause is that Hyper was drops HTTP connection handler
futures when the client goes away, in an effort to avoid doing
unnecessary work. But we have important cleanup work that must be
performed when a connection closes; failing to do that work is in fact
panicworthy.
Unfortunately Hyper does not allow you to request that all futures be
polled to completion, even if the client goes away.  So this commit
fixes the bug by introducing a new `spawn_if_canceled` future
combinator. The idea is that we can use the `Drop` implementation of
this combinator to call `tokio::spawn` to poll the original future to
completion. It's a bit weird, but it seems to work well.
An alternative solution is to use an …
> materialized: fix panic with closed HTTP connections

- src/testdrive/src/action.rs
- src/testdrive/src/main.rs
In particular, some of the comments about the AWS credential handling
were changed to be incorrect in b9aabee. No behavior changes; just some annoying rustfmt noise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6324)
> testdrive: improve and copyedit some commentary

- ci/nightly/pipeline.yml
- misc/python/materialize/mzcompose.py
- src/testdrive/src/action/kafka/create_topic.rs
- src/testdrive/src/action/kafka/verify.rs
- test/kafka-multi-broker/01-init.td
- test/kafka-multi-broker/02-after-leave.td
- test/kafka-multi-broker/03-after-join.td
- test/kafka-multi-broker/mzcompose
- test/kafka-multi-broker/mzcompose.yml
- test/kafka-ssl/mzcompose.yml
- test/kafka-ssl/smoketest.td
- test/testdrive/testdrive.td
This has been reviewed as https://github.com/MaterializeInc/materialize/pull/6259, so this PR is just for merging purposes.
> Merge PR: Multi-broker, multi-partition Kafka test #5968

- doc/user/content/sql/drop-index.md
- doc/user/content/sql/drop-schema.md
- doc/user/content/sql/drop-source.md
- doc/user/content/sql/drop-table.md
- doc/user/content/sql/drop-type.md
Tbh, I think it looks better without them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6288)
> (docs) Add bullets before code sample alternatives in DROP <ITEM> 

- doc/user/content/known-limitations.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6298)
> (doc) Add lack of support for window functions to known limitations.

- test/performance/perf-kinesis/mzcompose.yml
- test/performance/perf-kinesis/src/main.rs
For IAM permissions changes in https://github.com/MaterializeInc/infra/pull/895
> Fix perf-kinesis CI test

- doc/user/content/sql/functions/extract.md
- doc/user/layouts/partials/sql-grammar/func-extract.svg
- doc/user/sql-grammar/sql-grammar.bnf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6287)
> (docs) Add supported units to EXTRACT.

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
This is part of the release process in #6347.
> Prepare v0.7.2-rc1 & v0.7.3 dev

- doc/developer/README.md
> remove broken url

- doc/user/content/overview/volatility.md
Iterate on some wording improvements that didn't make the deadline for
#6320.
@sploiselle @msudberg it would be great to get a review of this whole doc more thoroughly here, too. I rushed #6320 out the door to unblock the cloud product, and I'm definitely looking to slow things down here to make sure y'all are happy with the docs.
> doc/user: improve volatility docs

- doc/developer/sqllogictest.md
> Developer doc: Add instructions on testing with primary keys.

- deny.toml
See comment within for justification.
> sec: ignore irrelevant vulnerability in parse_duration

- src/sqllogictest/src/main.rs
- src/sqllogictest/src/runner.rs
This modifies the message in both the buildkite log and the archived file, but we could move the sed to the end of the pipeline to only modify it in the buildkite UI.
> slt: Make it obvious that some failures are skipped

- Cargo.lock
- LICENSE
- doc/user/config.toml
- src/materialized/Cargo.toml
> Continue v0.7.3 dev

- src/coord/src/coord.rs
This will allow us in the future to use !Send types in the
coordinator.
> coord: don't move across thread boundary

- misc/python/materialize/cli/mzcompose.py
Before this, running `mzcompose --help` only printed the docker-compose
help, and it errored if you weren't already in a directory containing an
mzcompose.yml.
With this, the mzcompose help text is printed, in addition to the
docker-compose help text.
Example text:
```
$ mzcompose --help
usage: mzcompose.py [--mz-quiet] [--mz-find MZ_FIND] [--mz-build-mode {dev,release}] [-f FILE]
[--project-directory PROJECT_DIRECTORY] [--help]
[command] [ARG...] ...
positional arguments:
command               All docker-compose commands, plus: web, lint, list-compositions
ARG...
ARG...
optional arguments:
--mz-quiet
--mz-find MZ_FIND     Find a composition by directory name
--mz-build-mode {dev,release}
-f FILE, --file FILE  Explicitly disallowed, use --mz-find
--project-directory PROJECT_DIRECTORY …
```
> mzcompose: Include the argparse help text when --help is passed

- src/dataflow/src/server.rs
- src/dataflow/src/source/timestamp.rs
> dataflow: cleanup some aspects of timestamp determination in preparation for RT ts persistence

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/pure.rs
If specified all sub-sources will become materialized.
> sql: support MATERIALIZED modifier for CREATE SOURCES

- Cargo.lock
- Cargo.toml
- demo/debezium/loadgen/Cargo.toml
- demo/debezium/loadgen/ci/.gitignore
- demo/debezium/loadgen/ci/Dockerfile
- demo/debezium/loadgen/ci/mzbuild.yml
- demo/debezium/loadgen/src/bin/debezium-mysql-gen.rs
- demo/debezium/mzcompose.yml
- deny.toml
Create mysql-debezium example load generator
The idea behind this load generator is a generate a number of random
transactions and see how the Debezium topics look after replicating
these transactions.
We will be scanning these topics to look for invariants that expect
from Debezium.
> Add utility to generate random mysql transactions against Debezium demo database

- src/pgwire/src/protocol.rs
Previously send_rows would modify a batch variable before a loop and
then at the end because the first batch would verify the row shape
matched what was expected. If we move the verification logic to
instead check each batch we can simplify things and make the logic
much easier to understand.
> pgwire: simplify send_rows batching

- src/postgres-util/src/lib.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- test/pg-cdc/pg-cdc.td
Part of https://github.com/MaterializeInc/materialize/issues/5971.
> sql: support primary keys for Postgres replication sources

- demo/debezium/loadgen/src/bin/debezium-mysql-gen.rs
We can't retry all, since they'll just deadlock with each other.
I'm hoping this creates a more interesting binlog for MySQL.
> Randomly retry some conflicting transactions

- doc/user/content/known-limitations.md
- doc/user/content/ops/deployment.md
- doc/user/content/ops/monitoring.md
- doc/user/content/overview/what-is-materialize.md
- doc/user/content/sql/create-source/csv-s3.md
- doc/user/content/sql/create-source/json-s3.md
- doc/user/content/sql/create-source/text-s3.md
- doc/user/content/sql/join.md
- doc/user/content/sql/types/interval.md
- doc/user/content/third-party/docker.md
A few of these headings were in violation of our style guide.
> doc/user: sentence case some headings in the docs

- src/dataflow/src/source/kafka.rs
With the BrokerWindow stats, we implemented two functions over the stats
object that simplifies the KafkaSourceReader get_next_message and drop
methods. Do this for PartitionStats as well.
Remove the unnecessary Clone and Copy traits on BrokerWindow by having
negate take a reference to self.
> Simplify update of Kafka Consumer Partition stats

- ci/test/cargo-test/image/mzbuild.yml
- demo/billing/ci/mzbuild.yml
- demo/debezium/loadgen/ci/mzbuild.yml
- doc/developer/mzbuild.md
- misc/python/materialize/mzbuild.py
- play/mbta/ci/mzbuild.yml
- src/kafka-util/ci/mzbuild.yml
- src/materialized/ci/mzbuild.yml
- src/peeker/ci/mzbuild.yml
- src/sqllogictest/ci/mzbuild.yml
- src/testdrive/ci/mzbuild.yml
- test/antithesis/materialized/.gitignore
- test/antithesis/materialized/Dockerfile
- test/antithesis/materialized/mzbuild.yml
- test/antithesis/testdrive/mzbuild.yml
- test/chaos/ci/mzbuild.yml
- test/correctness/ci/mzbuild.yml
- test/metabase/smoketest/ci/mzbuild.yml
- test/performance/perf-kinesis/ci/mzbuild.yml
- test/performance/perf-upsert/ci/mzbuild.yml
- test/smith/ci/mzbuild.yml
Some additional fixes to get stuff running on Antithesis's testing platform.
> test/antithesis: additional fixes

- doc/user/content/sql/create-sink.md
- doc/user/layouts/partials/create-source/connector/kafka/details.html
- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
Align CREATE SINK and CREATE SOURCE WITH options, add some missing options.
> Align CREATE SINK and CREATE SOURCE WITH options for Kerberos

- src/repr/src/row.rs
This matches the implementation for `DatumList`, etc.
> Better debug implementation for DatumMap

- doc/developer/mzbuild.md
- misc/python/materialize/cli/mzcompose.py
Details in individual commits!
> mzcompose: refine help + fix argparse bug

- ci/test/pipeline.template.yml
- test/debezium-avro/03-drop-not-null-column.td
Let's see if this mitigates the flakiness.
> bump timeout on 03-drop-not-null-column.td

- src/coord/src/coord.rs
Remove the requirement of `--experimental` from temporal filters.
This probably requires some documentation (@msudberg; lmk how I can help).
> Stabilize temporal filters

- src/avro/src/schema.rs
> Allow non-number floats and doubles (NaN, Infinity, -Infinity) in default schema chunks

- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- test/testdrive/temporary.td
Addressing this comment: https://github.com/MaterializeInc/materialize/pull/6679#discussion_r629539802
> Refactor CREATE statement parsing

- src/expr/src/linear.rs
This PR tidies up recent work on inlining temporal expressions (#6700) with some more defensive practices. It 1. inlines all expressions that depend on temporal expressions, so that even column references to temporal expressions will be inlined, and 2. invokes the inlining at two locations that seem to be the moments when these expressions need to be removed from the set of standard expressions (`extract_temporal` and `MfpPlan::create_from`).
I suspect (1.) may not fix any observable problems, in that we have some pre-filtering on expressions we allow to be introduced, which probably prevents any functions *of* temporal expressions, making it much less likely that we could have observed anything other than direct uses of temporal operators.
The tests that might have failed before that are …
> Tidy up temporal inlining

- src/interchange/src/avro/schema.rs
Instead of returning a failure on the first attempt to resolve a Schema
from the schema registry, retry for up to 30 seconds on the condition
that the schema registry may be restarting.
Fixes #6185
---------------------------------------------------------------------------------------------------
Thoughts when writing this PR:
1. If this fails, even with the additional retry logic, then the source will be permanently errored. However, we don't have an easy way to map "schema registry requests" back to rows that have presented source errors. My thinking is that adding a 30 second retry is better than nothing, we can easily increase this timeout if we feel like it's too small and that mapping resolution errors back to source errors is likely a fair amount of work.
2. I didn't add a test for …
> Retry schema registry requests for up to 30 seconds

- doc/user/content/sql/copy-from.md
- doc/user/layouts/partials/sql-grammar/copy-from.svg
- doc/user/sql-grammar/sql-grammar.bnf
- src/coord/src/client.rs
- src/coord/src/command.rs
- src/coord/src/coord.rs
- src/pgtest/src/lib.rs
- src/pgwire/src/codec.rs
- src/pgwire/src/message.rs
- src/pgwire/src/protocol.rs
- src/sql/src/plan.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement.rs
- src/sql/src/plan/statement/dml.rs
- test/pgtest/copy-from-2.pt
- test/pgtest/copy-from-fail.pt
- test/pgtest/copy-from.pt
This PR adds support for COPY FROM STDIN.
Currently only text format is 
Task list
> Support for COPY FROM STDIN

- src/postgres-util/src/lib.rs
- test/pg-cdc/pg-cdc.td
> pg-cdc: parse type modifier for numeric columns

- src/coord/src/catalog/builtin.rs
- src/pgrepr/src/types.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/query.rs
- src/symbiosis/src/lib.rs
- test/pg-cdc/pg-cdc.td
- test/testdrive/types.td
> sql: support bpchar syntax for char columns

- src/pgwire/src/message.rs
- test/pgtest/copy-from-null.pt
> copy: support empty string as the NULL marker

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/pure.rs
- test/pg-cdc/pg-cdc.td
> pg-cdc: allow disambiguating upstream and local schemas

- doc/user/content/sql/functions/now_and_mz_logical_timestamp.md
- doc/user/content/sql/select.md
- doc/user/data/sql_funcs.yml
Also added some incidental formatting corrections to SELECT doc.
> Explain the difference between now() and mz_logical_timestamp()

- doc/developer/design/20210504_manage_external_state.md
[**View rendered.**](https://github.com/jldlaughlin/materialize/blob/postgres-state-doc/doc/developer/design/20200504_manage_external_state.md)
First pass at a design doc to decide how we should create and destroy external state from Materialize, details within!
> doc: design for managing external state in Materialize

- src/coord/src/coord.rs
Previously if ship_dataflow errored (the only way was for the as_of to
be < since, but I found this due to another commit that would have added
another error path), it would leave the catalog in an unsafe state. The
catalog entries would exist with no index, and materialized would crash
when attempting to use the indexes. This happened because catalog_transact
is almost always called before ship_dataflow.
Remove the error return from ship_dataflow to prevent this. The only
current error is due to a bad as_of, but I'm not aware of a way to
trigger that path.
> coord: prevent ship_dataflow from erroring

- src/sql/src/plan/statement/ddl.rs
> Reject non-Avro Debezium sources early in planning

- ci/nightly/pipeline.yml
- test/kafka-matrix/mzcompose.yml
Breakage here: https://buildkite.com/materialize/nightlies/builds/321
> Update some testdrive paths in the nightly kafka-matrix test

- src/dataflow/src/render/sources.rs
@frankmcsherry Any idea on how to test this change? Afaict the conventional way would have been with a small `*.td` test, but if I'm not mistaken users are not able to actually run into a problematic situation currently.
> dataflow: respect `Context::as_of_frontier` in `SourceConnector::Local`

- doc/user/content/cli/_index.md
Note that we plan to collect IP in addition to the existing data. Also
reword things a bit, to a) avoid passive voice, and b) clarify that the
data is anonymous only if you're not using our cloud offering.
> Update telemetry documentation

- src/dataflow/src/source/postgres.rs
> pg-cdc: proactively send keepalives to prevent timeouts

- src/postgres-util/src/lib.rs
- test/pg-cdc/pg-cdc.td
> pg-utils: handle columns with spaces

- Cargo.lock
- demo/billing/Cargo.toml
- src/coord/Cargo.toml
- src/dataflow/Cargo.toml
- src/materialized/Cargo.toml
- src/peeker/Cargo.toml
- src/pgrepr/Cargo.toml
- src/pgtest/Cargo.toml
- src/pgwire/Cargo.toml
- src/postgres-util/Cargo.toml
- src/sql/Cargo.toml
- src/sqllogictest/Cargo.toml
- src/symbiosis/Cargo.toml
- src/testdrive/Cargo.toml
- test/correctness/Cargo.toml
- test/metabase/smoketest/Cargo.toml
- test/performance/perf-kinesis/Cargo.toml
- test/performance/perf-upsert/Cargo.toml
- test/smith/Cargo.toml
- test/test-util/Cargo.toml
This version includes https://github.com/sfackler/rust-postgres/pull/777 which fixes #6836
> deps: update rust-postgres to mz-0.7.2

- ci/test/pipeline.template.yml
- test/pg-cdc/create-table-after-source.td
- test/pg-cdc/create-views-from-source-in-schema.td
- test/pg-cdc/create-views-from-source-with-schema.td
- test/pg-cdc/data-utf8.td
- test/pg-cdc/pg-cdc.td
- test/pg-cdc/publication-for-table.td
- test/pg-cdc/publication-with-publish-option.td
- test/pg-cdc/replica-identity-default-nothing.td
- test/pg-cdc/truncate-table.td
- test/pg-cdc/two-publications-one-table.td
- test/pg-cdc/two-source-schemas.td
- test/pg-cdc/two-sources-one-publication.td
- test/pg-cdc/types-boolean.td
- test/pg-cdc/types-bytea.td
- test/pg-cdc/types-character.td
- test/pg-cdc/types-decimal.td
- test/pg-cdc/types-double.td
- test/pg-cdc/types-enum.td.gh6818
- test/pg-cdc/types-hstore.td.gh6818
- test/pg-cdc/types-integer.td
- test/pg-cdc/types-interval.td
- test/pg-cdc/types-json.td
- test/pg-cdc/types-money.td.gh6819
- test/pg-cdc/types-numeric-arbitrary-precision.td.gh6821
- test/pg-cdc/types-serial.td
- test/pg-cdc/types-temporal-with-tz.td
- test/pg-cdc/types-temporal.td
Those are all the non-network-failure tests that I have so far. This is mostly JFYI, but I am open to suggestions about writing additional tests and/or checking anything that you think is suspicious and should be tested.
A separate PR will follow with tests that tests network other such errors.
> pg-cdc: A test suite for testing Postgres direct CDC replication

- src/coord/src/sink_connector.rs
- src/coord/src/timestamp.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/sink/kafka.rs
- test/testdrive/consolidation.td
I'm extracting the first three relatively no-brainer commits from #6532 to get those merged first / make for a smoother reviewing experience
> Small prework for exactly once sinks

- src/repr/src/strconv.rs
- test/sqllogictest/apd.slt
> sql: convert -0 input for apd  to 0

- src/sql/src/func.rs
- test/sqllogictest/apd.slt
@philip-stoev If you have suggestions for tests that spam fewer (or better) lines of code, would be very glad to amend this PR.
> sql: support equality operators for apd

- src/testdrive/src/main.rs
Used in concert with --shuffle-tests, this option can be used
to replace a single testdrive run with many shorter ones.
---
Antithesis have requested this option as it will allow them to fire testdrive multiple times in quick succession rather than do a single longer run. They say this execution style is better suited for their platform.
> testdrive: Add --max-tests option

- src/coord/src/client.rs
- src/coord/src/command.rs
- src/materialized/src/http/static/js/memory.jsx
- src/materialized/tests/server.rs
- src/materialized/tests/tls.rs
Use in /memory page for consistent results.
> materialized: support multiple queries in /sql endpoint

- src/dataflow/src/source/postgres.rs
Fell through the cracks from here https://github.com/MaterializeInc/materialize/pull/6898#discussion_r643061388
> pg-cdc: recover on too many connections error

- src/coord/src/coord.rs
- src/coord/src/timestamp.rs
> coord: name spawned threads

- src/dataflow/src/render/context.rs
- src/dataflow/src/render/mod.rs
- src/dataflow/src/render/sinks.rs
- src/dataflow/src/render/sources.rs
Attempted re-organization to group render state by its function.
> Render cleanup

- src/dataflow/src/source/postgres.rs
- src/postgres-util/src/lib.rs
Fixes https://github.com/MaterializeInc/materialize/issues/6907.
Updates `drop_replication_slots` to avoid a race condition between
the calls to `pg_terminate_backend` and `pg_drop_replication_slot`.
This is fixed by using a replication connection and executing
`DROP_REPLICATION_SLOT WAIT`, instead.
> postgres-util: drop_replication_slots race condition

- demo/http_logs/apps/requirements-loadgen.txt
Reverts MaterializeInc/materialize#6910
> Revert "build(deps): bump urllib3 from 1.25.8 to 1.26.5 in /demo/http_logs/apps"

- src/testdrive/src/action.rs
- src/testdrive/src/action/schema_registry.rs
- src/testdrive/src/action/sql.rs
- test/debezium-avro/03-drop-not-null-column.td
- test/debezium-avro/04-drop-column-nullable.td
- test/debezium-avro/06-add-column-with-update.td
- test/debezium-avro/07-add-column-with-delete.td
- test/debezium-avro/11-change-date-timestamp.td
- test/debezium-avro/12-change-decimal.td
- test/debezium-avro/21-types-boolean.td
- test/debezium-avro/22-types-double.td
- test/debezium-avro/23-types-decimal.td
- test/debezium-avro/24-types-enum.td
- test/debezium-avro/26-types-bytea.td
- test/debezium-avro/27-types-hstore.td
- test/debezium-avro/28-types-uuid.td
- test/debezium-avro/33-toasted-values.td
- test/debezium-avro/34-replica-identity-default.td
- test/debezium-avro/90-decimal-handling-mode.td
- test/debezium-avro/91-hstore-handling-mode.td
Signed-off-by: Petros Angelatos <petrosagg@gmail.com>
> testdrive: run DDL statements only once

- src/coord/src/catalog.rs
- src/coord/src/catalog/error.rs
- src/coord/src/coord.rs
- test/testdrive/github-6950.td
> coord: match the exact error when processing `IF NOT EXISTS`

- doc/developer/overview.md
This document means to frame the architectural components of Materialize, the properties they require, and the guarantees they provide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/6308)
> Architecture overview document

- doc/user/content/release-notes.md
- doc/user/content/sql/types/array.md
- doc/user/content/sql/types/jsonb.md
- doc/user/layouts/shortcodes/json-operators.html
- src/expr/src/scalar/func.rs
- src/repr/src/strconv.rs
- src/sql/src/func.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/arrays.slt
- test/sqllogictest/jsonb.slt
- test/sqllogictest/map.slt
> sql: support the jsonb #> and #>> operators

- doc/developer/design/20210413_source_sink_resource_sharing.md
**[View rendered.](https://github.com/MaterializeInc/materialize/blob/6fec61979854bf1a08382b4df0630dd74573f737/doc/developer/design/20210413_source_sink_resource_sharing.md)**
Propose a design for improving the steady-state efficiency of the system
via dynamic resource sharing in sources and sinks.
> doc/design: dynamic resource sharing for sources and sinks

- .github/dependabot.yml
Customize the labels and reviewers.
> deps: update dependabot configuration

- misc/python/materialize/cli/mzbench.py
Just code movement for now, but should get us closer towards being able to write benchmarks that don't follow the exact expected format.
> [mzbench] Refactor benchmarking logic into a class

- Cargo.lock
- src/dataflow/Cargo.toml
- src/expr/Cargo.toml
- src/interchange/Cargo.toml
- src/pgrepr/Cargo.toml
- src/repr/Cargo.toml
- src/repr/src/row.rs
- test/sqllogictest/apd.slt
- test/testdrive/apd-sum.td
Fixes #6877, #6912
Closes #6883
> sql: pack apd datums into rows using raw parts + the reverse

- src/dataflow/src/server.rs
- test/kafka-exactly-once/after-restart.td
- test/kafka-exactly-once/before-restart.td
- test/kafka-exactly-once/mzcompose.yml
> test: temporarily disable rt EOS tests

- src/sql/src/plan/statement/ddl.rs
These closures started pretty small but are now their own 200 lines of
interleaved code that was inside an already huge 500-line function.
> Extract the `get_encoding` closures into their own functions

- doc/user/data/sql_funcs.yml
- src/expr/src/scalar/func.rs
- src/pgrepr/src/oid.rs
- src/repr/src/lib.rs
- src/repr/src/row.rs
- src/sql/src/func.rs
- test/sqllogictest/funcs.slt
> sql: support pg_column_size

- Cargo.lock
- LICENSE
- doc/user/config.toml
- doc/user/content/release-notes.md
- src/materialized/Cargo.toml
> Integrate the v0.8.0 release into main

- src/coord/src/coord.rs
> [coord] use preferred default keys for SELECT statements

- src/expr/src/scalar/func.rs
- src/expr/src/scalar/mod.rs
- src/sql/src/func.rs
- test/sqllogictest/apd.slt
- test/sqllogictest/funcs.slt
> sql: exponential functions for apd

- src/persist/benches/writer.rs
- src/persist/src/file.rs
Fixes https://buildkite.com/materialize/tests/builds/18215#dbc8bb44-220b-4d3a-a75c-b29da2318407
> fix merge skew in copyright header lint

- doc/user/content/install.md
Discussed on Slack: https://materializeinc.slack.com/archives/C015RHB3LDR/p1623790505116300?thread_ts=1623790219.114700&cid=C015RHB3LDR
> Add note to call attention to the changed instructions

- doc/user/content/sql/create-sink.md
AS OF sinks were temporarily removed in https://github.com/MaterializeInc/materialize/pull/5866
> remove AS OF from example

- src/sql-parser/src/ast/defs/value.rs
- src/sql-parser/tests/testdata/scalar
> sql-parser: correctly serialize map casts

- src/coord/src/catalog/storage.rs
- test/kafka-exactly-once/after-restart.td
- test/kafka-exactly-once/before-restart.td
* need to only delete bindings when we have newer bindings to replace them
> coord,dataflow: fix issues with rt eos sinks

- src/coord/src/sink_connector.rs
- test/kafka-exactly-once/before-restart.td
- test/testdrive/kafka-exactly-once-sink.td
the first few commits are from other prs, the only commit that matters is the last one
> Let users specify exact name for exactly once sink kafka topics

- ci/slt/pipeline.yml
- ci/slt/slt.sh
- test/sqllogictest/mzcompose.yml
make a dedicated workflow in test/sqllogictest/mzcompose.yml
the way one existed for the sql-fast test
> sqllogictest: Fix the Nightly SLT test

- src/expr/src/relation/mod.rs
- test/sqllogictest/transform/lifting.slt
I used the ticket to familiarize myself a bit with the transform crate. I didn't get far or feel less confused than when I started, so I'll spend some more time on it after the PR.
> expr: count(null) is constant

- src/dataflow/src/decode/mod.rs
> decoder: Log successes correctly

- doc/user/content/sql/functions/csv_extract.md
> doc/user: fix csv_extract example

- doc/user/data/sql_funcs.yml
> doc: document unnest function

- doc/user/content/release-notes.md
- doc/user/content/sql/tail.md
- src/materialized/tests/sql.rs
- src/sql/src/plan/statement/dml.rs
- test/testdrive/consolidation.td
> sql: add mz_ to TAIL columns

- misc/python/materialize/mzcompose.py
This fixes a spurious failure observed in CI. Some VMs were bind
containers to both IPv4 and IPv6 ports on the host, which was confusing
the code that expected a service to have only one host port.
Unclear why only some CI agents were failing this way, but since
mzcompose is also used in demos on user machines where IPv6 is a real
possibility, better to just handle this case than disable IPv6 in CI.
> mzcompose: don't crash when ports are duplicated across IPv4/IPv6

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/sql/src/plan/transform_ast.rs
- test/testdrive/system-functions.td
> sql: support current_role alias for current_user

- src/sql/src/plan/statement/ddl.rs
There doesn't seem to be a good reason for having this option be parsed on a connector by connector basis. I also accidentally missed it and postgres sources don't support it, so this PR will make sure any source understands this option
> sql: handle `timestamp_frequency_ms` for all sources

- test/testdrive/avro-cdcv2.td
This was mostly done to satisfy some worries of mine. Apparently it works correctly. :+1:
> tests: add test for resilience to duplicate times for cdcv2 source

- doc/user/content/release-notes.md
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
> sql: de-experimentalize postgres sources

- Cargo.lock
- demo/billing/Cargo.toml
- deny.toml
- play/mbta/Cargo.toml
- src/avro/Cargo.toml
- src/avro/src/codec.rs
- src/aws-util/Cargo.toml
- src/build-info/Cargo.toml
- src/ccsr/Cargo.toml
- src/coord/Cargo.toml
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/expr/Cargo.toml
- src/expr/src/scalar/func.rs
- src/interchange/Cargo.toml
- src/kafka-util/Cargo.toml
- src/materialized/Cargo.toml
- src/materialized/src/telemetry.rs
- src/ore/Cargo.toml
- src/ore/src/future.rs
- src/pgwire/Cargo.toml
- src/sql/Cargo.toml
- src/sqllogictest/Cargo.toml
- src/testdrive/Cargo.toml
- test/chaos/Cargo.toml
- test/correctness/Cargo.toml
- test/performance/perf-kinesis/Cargo.toml
- test/performance/perf-upsert/Cargo.toml
- test/performance/s3-datagen/Cargo.toml
- test/smith/Cargo.toml
Aggregate the recent dependabot updates, and then add a few more bumps to remove duplicate dependencies.
> deps: aggregate dependabot updates

- src/dataflow/src/sink/avro_ocf.rs
All the writing of a Avro OCF sink happens from one worker. However,
before this change all workers would open a file, with the same file
name even.
This changes two things:
- We make it explicit that we route all messages to one worker
- We lazily create the Avro Writer when we receive the first messages
The type of avro_writer (Option<Result<>>) is a bit awkward, but it
reflects that fact that we try creating the writer once, and that can
result in an error. Before, we would try creating the writer outside the
sink function, and then inside check whether it was succesful.
The previous code would silently "continue" with the sink, only logging
and error once, when creating the writer failed. Now, we log an error
every time we try and receive the created writer, which will make the
error …
> sinks,avro-ocf: create Avro Writer/open File only when needed

- doc/user/content/sql/create-source/json-file.md
> Fix JSON file source example echo command

- doc/user/content/sql/create-source/json-s3.md
reported by Zoheb Jamal: https://materializecommunity.slack.com/archives/C015KDVS7EV/p1625474171127300
> doc: fix s3 json example

- doc/user/content/release-notes.md
- doc/user/content/sql/system-catalog.md
- src/dataflow-types/src/logging.rs
- src/dataflow/src/logging/materialized.rs
- src/dataflow/src/source/kafka.rs
> Kafka: Record the initial high watermark

- misc/python/materialize/scratch.py
allow customizing of storage size, as well as assigning a private network interface. Also fixes a bug in `mkrepo`.
> various changes to scratch.py

- src/coord/src/coord.rs
Previously tables would check to see if they needed a manual advancing
(not triggered by `need_advance`) on each Coordinator message. While
not expensive to performance, it was confusing to know exactly what was
going on and why.
After some investigation and discussion, it seems that the original reason
for this is perhaps gone. When tables were added, there were no internal
system tables, and so something needed to advance table timestamps if
there were no table operations, which led to the logging_granularity
stuff. Now there are some system tables that are updated each second,
rendering this manual update needless (I think). Thus it seems that we
can remove the manual table advance.
If we discover some negative user experience or flakey tests then we
can add this back, but with …
> coord: remove table granularity logging

- src/sql/src/plan/typeconv.rs
- test/sqllogictest/arrays.slt
- test/sqllogictest/coercion.slt
- test/sqllogictest/list.slt
> sql: Consider type hint when checking for coercion type

- src/dataflow/src/render/reduce.rs
This tweaks a few types, so that `consolidate_stream` can be applied a little earlier. This results in a 20% perf improvement for `COUNT(*)` for me, just because fewer records hit the `ok_err` operator.
> [dataflow] move up consolidate_stream in reduce

- src/persist/src/operators/input.rs
Before this commit, each of N workers would replay the entire persisted
data, creating N copies. This hasn't been caught before because all our
other tests are single-worker, so it happened to work. For now, do the
simple thing and replay all the data from worker 0 (and nothing from the
others). We'll make this smarter and balance the work out later.
> persist: only replay data once (instead of once per worker)

- src/persist/src/indexed/runtime.rs
- src/persist/src/operators/input.rs
This is in prep for #7283. The implementation of the method is sadly
still blocking, but after attempting a few fixes, I don't have anything
workable. If possible, would like to merge this as-is and fix the
blocking bit in a followup.
> persist: make signature of StreamWriteHandle::write asynchronous

- src/expr/src/scalar/func.rs
- test/sqllogictest/apd.slt
> sql: properly constrain return values for apd_pow

- src/coord/src/timestamp.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/render/sources.rs
- src/sql/src/plan/statement/ddl.rs
- src/testdrive/src/action/kafka/ingest.rs
- src/testdrive/src/action/sql.rs
- src/testdrive/src/format/protobuf.rs
- src/testdrive/src/format/protobuf/simple.proto
- test/testdrive/kafka-include-key-sources.td
Support inserting Kafka Key fields into Dataflows using the new `INCLUDE KEY` syntax
Design doc #6661
Resolves #5863
> Kafka Keys in dataflows

- src/dataflow/src/render/mod.rs
Name regions with the dataflow's name.
> dataflow: name regions

- doc/user/layouts/partials/create-source/connector/s3/details.html
> Improve S3 documentation around object discovery strategies

- src/persist/src/indexed/encoding.rs
Noticed this today while I was poking around related code
> persist: properly enforce uniqueness in futures/traces

- src/persist/src/indexed/encoding.rs
> persist: fix build break

- src/persist/src/indexed/encoding.rs
Previously, we required that all updates in a trace batch have times between
[lower, upper). This invariant is overly restrictive with respect to compaction
policy, and in this commit we relax it to match differential's semantics.
Now, updates in a batch can have times in advance of upper if the since
frontier is in advance of upper. They cannot, however, have times in advance of
the since frontier.
> persist: relax BlobTraceBatch invariants to match differential.

- src/interchange/src/avro/decode.rs
- src/interchange/src/avro/envelope_debezium.rs
- test/debezium-avro/60-concurrent-insert-same.td
- test/debezium-avro/60-update-pk-values.td
- test/debezium-avro/61-concurrent-insert-multi.td
- test/debezium-avro/62-concurrent-update-nopk.td
- test/debezium-avro/63-concurrent-update-pk.td
- test/debezium-avro/64-concurrent-delete-same.td
- test/debezium-avro/65-concurrent-delete-multi.td
- test/debezium-avro/70-insert-delete.td
- test/debezium-avro/71-update-update.td
- test/testdrive/github-5668.td
Uses the newly added sequence field (DBZ-2911) for Debezium Postgres
sources.
> interchange: use sequence field for Debezium Postgres sources

- src/dataflow/src/render/mod.rs
This PR changes the rendering of `Constant` collections to advance times to the `as_of` boundary for the dataflow. Collections that are not so advanced cause computation to happen prior to any time that we will observe, and unfortunately cause errors in that regime when other parts of the dataflow imagine that they will not happen (as was the case in #7472, with optimized delta join loading).
Fixes #7472
> Advance times in constant collections to as_of

- Cargo.lock
- src/persist/Cargo.toml
- src/persist/benches/snapshot.rs
- src/persist/benches/writer.rs
- src/persist/src/file.rs
- src/persist/src/mem.rs
- src/persist/src/nemesis/direct.rs
- src/persist/src/nemesis/generator.rs
- src/persist/src/nemesis/mod.rs
- src/persist/src/nemesis/validator.rs
- src/persist/src/operators/input.rs
- src/persist/src/operators/stream.rs
- src/persist/src/unreliable.rs
> persist: various nemesis work

- src/sql/src/func.rs
This saves a little typing now, but will save even more typing when adding char and varchar, which I intend to do soon
> sql: allow defining functions with ScalarBaseTypes as params

- src/persist/src/indexed/encoding.rs
- src/persist/src/indexed/future.rs
This change is in preparation for upcoming Future compaction.
> persist: refactor Future batch metadata

- src/dataflow/src/sink/avro_ocf.rs
- src/dataflow/src/sink/kafka.rs
- src/interchange/src/avro.rs
- src/interchange/src/avro/encode.rs
- src/interchange/src/encode.rs
- src/interchange/src/json.rs
- src/sql/src/plan/statement/ddl.rs
Creates a new generic Encoder Trait that will be implemented by
multiple encoder types (Avro, JSON, etc.).
> interchange: refactor Avro Encoder

- src/coord/src/sink_connector.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/sink/kafka.rs
- src/sql/src/plan/statement/ddl.rs
Updates existing Kafka sink informational structs to be more
extensible to different encoding formats in the future.
> dataflow-types: refactor Kafka connector information

- src/persist/benches/snapshot.rs
- src/persist/src/indexed/encoding.rs
- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
- src/persist/src/lib.rs
- src/persist/src/nemesis/direct.rs
- src/persist/src/nemesis/mod.rs
- src/persist/src/operators/input.rs
- src/persist/src/operators/stream.rs
> persist: various prep for #7283

- doc/user/data/sql_funcs.yml
I believe this definition is correct
> small doc fix for 'ceil' function

- .gitignore
- bin/xcompile
- ci/nightly/coverage.py
- ci/nightly/pipeline.yml
- ci/test/cargo-test/mzcompose.yml
- demo/billing/mzcompose.yml
- demo/chbench/mzcompose.yml
- demo/simple/mzcompose.yml
- misc/load-tests/mzcompose.yml
- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/mzbuild.py
- misc/python/materialize/mzcompose.py
- play/mbta/mzcompose.yml
- test/bench/aggregations/mzcompose.yml
- test/bench/avro-insert/mzcompose.yml
- test/bench/avro-upsert/mzcompose.yml
- test/bench/kafka-sink-avro-debezium/mzcompose.yml
- test/catalog-compat/mzcompose.yml
- test/chaos/mzcompose.yml
- test/debezium-avro/mzcompose.yml
- test/kafka-exactly-once/mzcompose.yml
- test/kafka-krb5/mzcompose.yml
- test/kafka-matrix/mzcompose.yml
- test/kafka-multi-broker/mzcompose.yml
- test/kafka-sasl-plain/mzcompose.yml
- test/kafka-ssl/mzcompose.yml
- test/performance/perf-upsert/mzcompose.yml
- test/testdrive/mzcompose.yml
- test/upgrade/mzcompose.yml
> Code coverage

- src/coord/src/timestamp.rs
- test/testdrive/kafka-avro-sources.td
- test/testdrive/kafka-time-offset.td
tests: bump topic_metadata_refresh_interval_ms on some Kafka tests
The hope is that this removes the flakiness reported in #7488
>  tests: bump topic_metadata_refresh_interval_ms on some Kafka tests

- doc/developer/testdrive.md
BUILD_MODE does not have an effect anymore.
> docs,testdrive: change mentions of BUILD_MODE to --mz-build-mode

- src/materialized/src/http/static/js/memory.jsx
Adding a checkbox to include the `mz_catalog` dataflows in the memory analysis page.
This is the first time I've been in touch with React, so please let me know of any stylistic problems!
> Add option to include mz_catalog in http memory page

- misc/python/materialize/cli/mkrelease.py
`latest_version` tests should always be converted to their actually released
version as soon as that version is released.
In the spirit of eventually getting the release process fully automated, or
at least not regressing the amount of work we need to do as part of it,
this automates the update.
This code is potentially pretty fragile since it expects exact strings
inside the modified yaml file. That said, expecting exactly those strings
and the current structure of the file does allow the script to at least
correctly error if the file changes in a suprising way. Additionally, this
is sort of a best-effort change with a low blast radius/risk profile. If the
modifications fail catastrophically it should be caught either in code
review or by the tests to merge the changes, and in that case …
> mkrelease: Update upgrade tests as part of finishing the release

- doc/user/layouts/partials/create-source/connector/s3/details.html
> Document that we are improving the SQS Notifications interface

- misc/python/materialize/cli/scratch.py
- misc/python/materialize/ui.py
- src/materialized/src/lib.rs
Use SSM by default, push local ~/.ssh/id_rsa.pub key, improve logging, remove some traces of printf debugging.
> Various improvement to scratch.py script

- src/coord/src/timestamp.rs
Session timeouts, together with consumer-group re-arrangement, combined
with the fact that we don't commit read offsets for the BYO consumer can
lead to cases where an existing consumer starts reading the consistency
topic from the beginning, after a connection outage.
We now protect against this by manually keeping track of the offset of
consistency records that we have processed so far, to filter out
duplicates.
When running the reproduction example from @philip-stoev you can now see the `DEBUG` statements in the log instead of test failures.
> coord,sources: don't publish duplicate consistency information in BYO kafka connector

- src/materialized/src/http/prof.rs
- src/materialized/src/http/templates/prof.html
> Retrieve jemalloc stats through http GET

- doc/user/content/release-notes.md
opening a new PR was nominally faster than setting up your fork as a remote; lmk if there are any issues with this, @awang
> doc: add release note for #7467

- src/persist/src/indexed/mod.rs
- src/persist/src/nemesis/direct.rs
- src/persist/src/nemesis/generator.rs
- src/persist/src/nemesis/mod.rs
- src/persist/src/nemesis/validator.rs
> persist: various nemesis additions

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/musing.md
- .github/ISSUE_TEMPLATE/refactoring.md
- .github/ISSUE_TEMPLATE/release.md
- Updated scratchpad description (was over maximum character limit)
- Added documentation description
> Update issue templates

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/dataflow/src/render/reduce.rs
- src/expr/src/relation/func.rs
- src/repr/src/scalar.rs
- src/sql/src/func.rs
- src/sql/src/plan/expr.rs
- test/sqllogictest/arrays.slt
- test/sqllogictest/cockroach/aggregate.slt
> sql: support array_agg

- misc/python/materialize/mzcompose.py
- misc/shlib/shlib.bash
- src/sqllogictest/ci/Dockerfile
- test/sqllogictest/mzcompose.yml
- test/sqllogictest/mzworkflows.py
Use the new Python-based workflow support in the sqllogictest
composition.
> sqllogictest: port to Python workflows

- src/coord/src/catalog.rs
- src/coord/src/catalog/config.rs
- src/coord/src/coord.rs
- src/coord/src/persistcfg.rs
- src/persist/Cargo.toml
- src/persist/benches/snapshot.rs
- src/persist/src/indexed/cache.rs
- src/persist/src/indexed/encoding.rs
- src/persist/src/indexed/future.rs
- src/persist/src/indexed/metrics.rs
- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
- src/persist/src/indexed/trace.rs
- src/persist/src/mem.rs
- src/persist/src/nemesis/direct.rs
This certainly contains some we won't end up needing and also doesn't
contain some we will, but gotta start somewhere.
Closes #4025
> persist: add initial attempt at monitoring metrics

- src/interchange/src/avro/envelope_debezium.rs
- test/testdrive/kafka-avro-sources.td
> allow null sequence field in dbz sources

- misc/python/materialize/mzcompose.py
If a wait-for step fails, the most valuable thing to do is to check the logs of
the thing that we didn't find the port for, but experience shows that that
isn't necessarily obvious, and it can be tedious.
This implementation shows the most recent 20 lines of logs from a service that
mzcompose couldn't connect to. Even if it's not enough to debug the issue, it
at least is enough to point out that users should investigate those logs.
> mzcompose: Print some service logs when wait-for-<service> fails

- misc/dbt-materialize/CHANGELOG.md
- misc/dbt-materialize/setup.py
Follow up to https://github.com/MaterializeInc/materialize/pull/7836!
> dbt-materialize: bump to version 0.20.1.post1

- doc/user/content/sql/show-sources.md
- src/sql/src/plan/statement/show.rs
- test/testdrive/catalog.td
- test/testdrive/materializations.td
> sql: show connector type in SHOW FULL SOURCES

- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/create
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan/statement/ddl.rs
- test/testdrive/unsupported.td
> Provide a better error message for DROP MATERIALIZED VIEW

- src/coord/src/coord.rs
- test/sqllogictest/table_func.slt
> coord: err instead of panic when we have a negative multiplicity in constant result

- src/coord/src/coord.rs
> coord: report total insert row diffs as affected

- src/dataflow/src/source/s3.rs
Primarily this adds source_id in a uniform place in (almost) all log messages,
which helps with sqs interleaving debugging.
> s3 source: Improve logging

- demo/chbench/chbench/src/materialized.cc
- src/coord/src/coord.rs
- src/coord/src/error.rs
- src/pgwire/src/message.rs
- test/test-util/src/mz_client.rs
> coord: assign error code to "no complete timestamps" error

- doc/user/content/release-notes.md
- doc/user/content/sql/functions/string_agg.md
- doc/user/data/sql_funcs.yml
- src/dataflow/src/render/reduce.rs
- src/expr/src/relation/func.rs
- src/sql/src/func.rs
- src/sql/src/plan/expr.rs
- test/sqllogictest/cockroach/aggregate.slt
- test/sqllogictest/cockroach/subquery_correlated.slt
> sql: support string_agg function

- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
- src/persist/src/indexed/trace.rs
- src/persist/src/nemesis/direct.rs
So we can use it to issue multiple allow_compaction operations at once
in coord and avoid the overhead of a request per. It doesn't matter so
much with only 2 tables, but it will add up once we're doing this for
all user tables.
> persist: wire up MultiWriteHandle::allow_compaction

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/dataflow/src/render/flat_map.rs
- src/expr/src/relation/func.rs
- src/sql/src/func.rs
- src/transform/src/reduction.rs
- src/transform/tests/testdata/nonnull-requirements
- test/sqllogictest/table_func.slt
- test/sqllogictest/transform/lifting.slt
This is required for https://github.com/MaterializeInc/materialize/issues/4506.
> sql: support generate_series(start, stop, step)

- misc/python/materialize/mzbuild.py
The cross-compiling toolchain that bin/xcompile installs on macOS
doesn't support lld, so don't attempt to use it when xcompiling on
macOS.
> mzbuild: don't use lld when xcompiling on macOS

- deny.toml
> deny: explicitly ban thiserror per our unwritten policy

- src/coord/src/coord.rs
> coord/broadcast: Avoid clone for last worker

- src/persist/src/error.rs
- src/persist/src/indexed/cache.rs
- src/persist/src/indexed/metrics.rs
- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
- src/persist/src/indexed/trace.rs
- src/persist/src/indexed/unsealed.rs
These have come out of investigations in #7902.
> persist: add a batch of new monitoring metrics

- src/persist/src/operators/source.rs
We were previously crashing on startup dude to an invalid attempt to downgrade
a capability at some time T to a time less than T (often less by 50 - 100 ms).
This happened because in the persisted source operator we:
- register a listener
- read a snapshot
- downgrade the capability to the snapshot's sealed frontier
- listen for updates
The last step now becomes a problem because we registered the listener before
taking the snapshot so theres a potential for some seal / data notifications to
come in even though they are not in advance of the snapshot's sealed frontier.
We also can't register the listener after taking the snapshot because there's
no guarantee that there won't be arbitrary delay between those two operations
which would cause us to lose data.
Instead, we simply need to check …
> persist: ignore seal notifications before the snapshot in listen_source

- src/persist/src/indexed/trace.rs
The first commit is Dan's changes to metrics to make this easier to debug and understand.
The second commit changes the compaction level assignment to only increment the compaction level when the new batch is larger than both of its parents. This change much more tightly bounds the size of the trace to the unsealed size.
^this graph is from just the first commit. Write amplification improves with this too, specifically the spikes in trace writes are less bad. This change doesn't affect the steady state write amplification
The third commit changes runtime to only drain unsealed to trace once per second. This should let us retain our fast response latencies while easing up on the write pressure downstream. This significantly improved the write amplification at steady state and at peak. 
I …
> persist: better compaction policy

- Cargo.lock
- ci/test/pipeline.template.yml
- deny.toml
- doc/developer/testdrive.md
- misc/python/materialize/mzcompose.py
- src/testdrive/Cargo.toml
- src/testdrive/src/action.rs
- src/testdrive/src/action/sql_server.rs
- src/testdrive/src/action/sql_server/connect.rs
- src/testdrive/src/action/sql_server/execute.rs
- test/debezium-avro/mzworkflows.py
- test/debezium-avro/sql-server/10-configure-sql-server.td
- test/debezium-avro/sql-server/20-populate-delete.td
- test/debezium-avro/sql-server/20-populate-smoke.td
- test/debezium-avro/sql-server/20-populate-transactions.td
- test/debezium-avro/sql-server/20-populate-types.td
- test/debezium-avro/sql-server/20-populate-update.td
- test/debezium-avro/sql-server/30-configure-debezium.td
- test/debezium-avro/sql-server/40-check-delete.td
- test/debezium-avro/sql-server/40-check-smoke.td
- test/debezium-avro/sql-server/40-check-transactions.td
- test/debezium-avro/sql-server/40-check-types.td
- test/debezium-avro/sql-server/40-check-update.td
This PR enables the following:
- an end-to-end test for SQL Server and Debezium using a containerized SQL server
- testdrive commands that allow connections to be opened and commands to be issued against SQL server
I am going to document the new testdrive commands shortly and will extend the contents of the actual test.
> debezium: A end-to-end test with SQL Server and Debezium

- doc/user/content/cli/_index.md
- doc/user/content/release-notes.md
- src/coord/src/coord.rs
- src/coord/src/coord/prometheus.rs
- src/materialized/src/bin/materialized/main.rs
- src/materialized/tests/util.rs
- test/testdrive/mzcompose.yml
> metrics scraping: Increase default to 30s

- test/pgtest/affected.pt
I wrote this, but forgot to add it to the git commit, in #7952.
> coord: test INSERT affected rows

- doc/user/content/sql/join.md
> docs: fix typo in join doc

- misc/python/materialize/benches/avro_ingest.py
Previously we were printing them cumulatively since the beginning of time.
> Correctly report CPU totals for each trial in avro_ingest.py

- doc/user/content/release-notes.md
> Add some missed features to release notes

- misc/tb/pom.xml
- misc/tb/src/TB.java
Resubmission of #8039 with whitespace fixed.
> tb: bump dependencies and add mysql 8 parameter

- src/transform/src/canonicalize_mfp.rs
- src/transform/tests/test_runner.rs
- src/transform/tests/testdata/canonicalize_mfp
This PR fixes a recognized bug. #8235
Filters canonicalized in CanonicalizedMfp may refer to intermediate expressions.
- [fix for non-released code] This PR adds a release note for any user-facing behavior changes.
Fixes #8235
> fix crash in CanonicalizeMfp transform

- doc/user/content/release-notes.md
- doc/user/layouts/partials/sql-grammar/format-spec.svg
- doc/user/sql-grammar/sql-grammar.bnf
Updates the format diagram and adds a release note.
This PR adds documentation (release note and diagram update) for a [previous change](https://github.com/MaterializeInc/materialize/pull/8084).
The updated railroad diagram looks like:
> doc: CSR + Protobuf support for sources

- doc/user/content/cloud/_index.md
- doc/user/content/cloud/account-limits.md
- doc/user/content/cloud/cloud-deployments.md
- doc/user/content/cloud/create-deployments.md
- doc/user/content/cloud/destroy-deployments.md
- doc/user/content/cloud/get-started-with-cloud.md
- doc/user/content/cloud/settings.md
- doc/user/content/cloud/update-deployments.md
Some Cloud doc cleanup, mostly language, a little removing features not yet supported
> Cloud doc cleanup

- doc/user/content/sql/tail.md
> How to distinguish between no data and a timeout

- doc/user/content/sql/begin.md
- doc/user/content/sql/commit.md
- doc/user/content/sql/rollback.md
- doc/user/layouts/partials/sql-grammar/begin.svg
- doc/user/layouts/partials/sql-grammar/commit.svg
- doc/user/layouts/partials/sql-grammar/rollback.svg
- doc/user/sql-grammar/generate.sh
- doc/user/sql-grammar/sql-grammar.bnf
This PR documents guarantees and functionality of transactions.
Fixes #8205
> doc: document transactions: BEGIN, COMMIT, ROLLBACK

- src/expr/src/relation/func.rs
> expr: make `csv_extract` return an Iterator

- misc/python/materialize/cli/mkrelease.py
* This PR fixes a recognized bug. [discussed in Slack](https://materializeinc.slack.com/archives/CTESPM7FU/p1631716029045100)
> add --env option to mkrelease dashboard_links

- src/expr-test-util/src/lib.rs
- src/expr-test-util/tests/testdata/rel
This PR adds a known-desirable *test* feature.  #7657
```
New accepted syntax is:
(constant_err <eval error> <relation type>)
```
- [nothing user-visible here This PR adds a release note for any user-facing behavior changes.
> expr-test-util: add support for constant error relations

- doc/developer/mzworkflows.md
* This PR updates docs.
I went over the docs added in https://github.com/MaterializeInc/materialize/pull/8294. The docs are really helpful and I'm confident that I can port an existing test/create a new test using `mzworkflows.py` after reading it.
Still, @philip-stoev asked for all my nits, so here we go. 😄
> doc: fix nits in mzworkflows.md

- doc/developer/guide.md
* This PR fixes a recognized bug. #8268
The [features arg](https://doc.rust-lang.org/cargo/reference/features.html) is meant for cargo, not materialized.
cc @mkysel
> doc: fix order of dev-web feature

- doc/developer/guide-changes.md
Bit of a starting point - any thoughts?
> add a pr feedback suggestions section to dev guide

- misc/python/materialize/cli/mkrelease.py
Discussion in Slack: https://materializeinc.slack.com/archives/CTESPM7FU/p1631805310118700
> Change "biweekly" string to "weekly", to match new release cycle

- src/dataflow/src/render/upsert.rs
We plan to implement a generic persisting upsert operator in the persist
crate that has the same interface. Then dataflow, i.e. upsert.rs, can
use either, depending on what is required/configured.
Though this helps with code structure in general. That one big method in
upsert.rs becomes a bit easier to follow.
This is a refactoring. No functionality is changed, though the method signature now more clearly expresses what is going on.
This has the potential to affect runtime, because there are now closures for extracting the key/value, and encoding the final result. I ran the `avro-upsert` benchmark multiple times, performance seems to be within %1 of the original code, though there seems to be a very slight degradation. These are the results from one set of runs:
``` …
```
> dataflow: in upsert.rs factor out core upsert logic

- play/nix/shell.nix
At least a couple of people in the company are developing on nix so it makes sense to share our configuration
> play: add shell.nix file

- Cargo.lock
- LICENSE
- doc/user/config.toml
- src/materialized/Cargo.toml
> release: v0.9.5

- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/float.rs
- src/sql/src/func.rs
- src/sql/src/plan/typeconv.rs
Now that the infrastructure of `sqlfunc!` has landed this PR just ports a lot more float functions into it
> Port a lot more float funcs under `sqlfunc!`

- doc/user/content/release-notes.md
Just adding a release note here to avoid another trip through CI
> docs: release note for #8021 fix

- doc/developer/design/20210910_include_kafka_metadata.md
[Rendered](https://github.com/quodlibetor/materialize/blob/design-include-metadata/doc/developer/design/20210910_include_kafka_metadata.md)
This is a detailed overview of possible resolutions to a couple more parts of #1577
> Add design doc for user access to Kafka metadata

- src/materialized/tests/server.rs
Just adding a test that should have been in #8389
> test: ensure server can cancel long-running queries

- src/coord/src/coord.rs
- src/coord/src/error.rs
- src/sqllogictest/src/runner.rs
- test/sqllogictest/github-8241.slt
- test/sqllogictest/transactions.slt
* This PR adds a known-desirable feature. https://github.com/MaterializeInc/materialize/pull/8355#discussion_r712192064
Use the detail field to list timedomain error names.
> coord: add details to timedomain error

- .github/ISSUE_TEMPLATE/release.md
- ci/deploy/pipeline.yml
This eliminates a small amount of manual work from the release process.
> release: Automatically trigger Full SLTs for RCs

- Cargo.lock
- LICENSE
- doc/user/content/release-notes.md
- src/materialized/Cargo.toml
> Prepare 0.9.7-dev

- Cargo.lock
- LICENSE
- doc/user/config.toml
- src/materialized/Cargo.toml
> release: v0.9.6

- doc/user/content/sql/select.md
Which of the following best describes the motivation behind this PR?
Documentation update.
xref SELECT docs to TAIL.
> Add TAIL xref to SELECT doc.

- doc/user/content/release-notes.md
- doc/user/content/sql/functions/_index.md
See title.  These were not added in https://github.com/MaterializeInc/materialize/pull/8455.
> documentation and release notes for #8455

- doc/user/content/overview/what-is-materialize.md
Updating overview to mention Postgres and S3!
> doc: quickfix - Add S3 and Postgres mention to overview

- doc/developer/arrangements.md
Previously in #6797, I catalogued what arrangements are created for each type of aggregation: accumulable, hierarchical, and other. I am now adding what additional arrangements are created if the aggregation is on distinct values.
> Developer doc: Include math on arrangements of aggregations on distinct values

- test/kafka-matrix/kafka-matrix.td
Fixes the [breaking nightly test](https://materializeinc.slack.com/archives/CM7ATT65S/p1633002726125700).
This is not an ideal fix! It's a bandaid for testdrive, which can't currently handle record types. (I'm looking at that now, but didn't want to cause the nightlies to fail again.) We test that records are properly formed in [other tests](https://github.com/MaterializeInc/materialize/blob/main/test/testdrive/proto-billing.td#L38).
> kafka-matrix: fix record type in nightly test

- src/coord/src/sink_connector.rs
This comment is outdated - we scan from beginning, not end -1.
> remove outdated/misleading comment in eos sinks

- src/transform/src/dataflow.rs
- test/testdrive/source-linear-operators.td
The predicates pushed down to sources were displayed in an unpredictable order. 
Spotted while working on #8542
> reliable order of pushed down predicates

- src/transform/src/column_knowledge.rs
The ColumnKnowledge implementation requires a stack to determine its
DatumKnowledge. The stack is a vector that starts empty and might be
reallocated several times while optimizing the expression.
With this change, the transformation re-uses the same allocation, which
saves new allocations and re-allocations. There is no downside besides
increased code complexity because the maximum amount of memory consumed
by the knowledge_stack remains the same, and the memory is only retained
for the duration of transform call.
> transform: Reuse knowledge_stack allocation

- test/limits/mzworkflows.py
Extend the limits test to create arrangements with many rows (usually 10M)
and then run queries on them that would cause various dataflow operators
to come into play.
> test: Extend the limits test to the dataflow operators

- src/coord/src/coord.rs
Previously callers to sequence_end_transaction_inner would have to
duplicate (or quadruple) any common logic that needed to happen
after it. Improve this situation by always converting results of
sequence_end_transaction_inner into a Future that we always spawn a
task for.
> coord: simplify return paths in end transaction logic

- src/coord/src/coord.rs
Further simplify session end transaction handling. This was meant to be in #8865 but I forgot to amend the commit.
> coord: simplify session txn cleanup more

- src/persist/src/operators/stream.rs
Before, we would synchronously block on the seal future using recv().
This meant that we block the timely worker thread far longer than we
need to.
Now, we convert it into a "real" Future and poll it asynchronously.
Additionally, we simplify capability handling/downgrading by switching
to a `CapabilitySet`.
The test needed to be adapted for this, because the results are not
deterministic anymore. Now, we assert on the ordering properties that we
want to have.
Closes #8812
I'm opening this PR now, because it's separately reviewable. However, I would like to merge it after the main parts of the persistent Kafka source are merged. That way, I can run a quick benchmark on the code in `main` before this change, and record it in the commit description.
- [N/A] This PR adds a release note for …
> persist: in conditional_seal() operator, don't block on seal futures

- src/persist/src/operators/stream.rs
persist: in persist() operator, don't block on write futures
Before, we would synchronously block on the write future using recv().
This meant that we block the timely worker thread far longer than we
need to.
Now, we convert it into a "real" Future and poll it asynchronously.
We are also removing an inefficiency, where we would wait for the
frontier to advance beyond the timestamp of a write future, before
blocking on it. Now, we just hold on to capabilities for the timestamp
of the written data until the write future is done, making the operator
both simpler and more aggressive in allowing the frontier to advance,
because the tracking is now more fine-grained.
Closes #8813
- [ N/A ] This PR adds a release note for any
[user-facing behavior …
> persist: in persist() operator, don't block on write futures

- doc/developer/filepoints.md
Document failpoints, a feature used for testing.
> Failpoints documentation

- src/persist/src/operators/stream.rs
With `conditional_seal()` only one operator is active and doing any
sealing. The other operators just pass through data.
Before this fix, we held on to a capability on all workers, meaning that
we would block downstream frontier progress for non-active workers. Now,
we correctly only hold on to a capability for the active worker.
- [N/A] This PR adds a release note for any
> persist: fix conditional_seal() operator

- src/dataflow/src/render/sources.rs
This brings the behaviour on line with what we wanted to have for the
initial implementation. It's not wrong to forward updates to dataflow
early, while holding on to the frontier.
This approach is the most conservative option, where we absolutely make
sure that no-one can see updates downstream until we persisted them.
> dataflow,persist: wait for updates to be persisted before forwarding from source

- doc/user/content/ops/memory.md
- doc/user/content/ops/troubleshooting.md
Fix Hugo aliases (to support deprecated URLs)
* This PR fixes a previously unreported bug. 
> Fix aliases

- src/coord/src/timestamp.rs
- src/dataflow-types/src/types.rs
- src/dataflow/src/render/sources.rs
- src/sql-parser/src/ast/defs/ddl.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/normalize.rs
- src/sql/src/plan/statement/ddl.rs
- src/sql/src/pure.rs
- test/testdrive/kafka-include-key-sources.td
Part of the implementation of #1577 (design doc at #8239)
* This PR works towards a known-desirable feature
> Syntax changes for multiple Kafka metadata items

- src/persist/benches/writer.rs
Previously, the write benchmarks were using a lot of memory because Criterion
wants, for each benchmark to fit as many samples (where a sample is a run of
N iterations of the function being benchmarked) within 5 seconds, with a
minimum of 100 samples.
The mapping from samples is a little bit opaque, but it seems like
at a minimum under default settings, Criterion wants to do 200 - 300
iterations no matter what. This starts to become nontrivial memory utilization
for e.g. the benchmarks that test writing unsealed batches to BlobCache since
each write is ~40 MB, and for MemBlobs its stored in memory twice, once in
the blob implementation and once in the blob cache. It's also reasonable
to assume that there's some amortized vec resizing memory overhead and
some allocator overhead so at 200 …
> persist: limit write benchmarks resource utilization.

- src/materialized/tests/sql.rs
The fact that we're not doing this might be what's confusing reqwest. Worth a shot.
> Read the full request before responding in test_no_block

- src/ccsr/src/client.rs
- src/ccsr/tests/client.rs
As title
Groundwork for #8720.  Separated out to make easier to review.
> ccsr: Add ability to get subject and all dependencies

- src/interchange/src/avro.rs
- src/interchange/src/avro/envelope_debezium.rs
- src/interchange/src/avro/envelope_debezium/deduplication.rs
As per the comment, this code is no longer used after the orthogonality work
> interchange: remove debezium dead code

- src/dataflow/src/server.rs
Which of the following best describes the motivation behind this PR?
* This PR fixes a recognized bug: #8994
This may fix the issue, which only presents in stressful situations (not locally for me). Ideally, @antiguru can run it through his problematic setting and see if it presents again!
> Wake worker threads after dropping LocalClient connections

- doc/user/CONTRIBUTING.md
- doc/user/README.md
fixed two typos (well, one of them wasn't really a typo, but is undocumented, so I fixed it) and added two links for convenience
* This PR fixes typos/inconsistencies and adds convenience.
> docs: small fixes, update link checking instructions

- doc/user/content/release-notes.md
- src/sql/src/plan/query.rs
- src/sql/src/plan/scope.rs
- test/sqllogictest/cockroach/with.slt
- test/testdrive/delete-using.td
- test/testdrive/duplicate-table-names.td
- test/testdrive/kafka-stats.td
- test/testdrive/rename.td
- test/testdrive/subquery-scalar-errors.td
- test/testdrive/testdrive.td
> sql: disallow ambiguous table references

- doc/user/content/sql/copy-from.md
> docs: Fix formatting issue in `COPY FROM`

- doc/user/data/sql_funcs.yml
- test/sqllogictest/window_funcs.slt
> sql: window function test and doc nits

- Cargo.lock
- src/sql/Cargo.toml
main got broken due to merge skew from these two PRs:
https://github.com/MaterializeInc/materialize/pull/8976
https://github.com/MaterializeInc/materialize/pull/8801
> sql: re-add datadriven crate

- src/persist/src/indexed/mod.rs
- src/persist/src/operators/source.rs
- src/persist/src/operators/stream.rs
- src/persist/src/pfuture.rs
Context is the upcoming work to clean up Indexed state: https://github.com/danhhz/materialize/commits/persist_indexed_state
- [N/A] This PR adds a release note for any
> persist: a few small cleanups

- ci/nightly/pipeline.yml
> test: increase the timeout for the product limits test

- test/antithesis/driver/docker-compose.yml
Reduce the verbosity of the logging for the time being until
a situation arises where the additional logging would be useful.
> antithesis: reduce logging verbosity

- src/coord/src/coord.rs
In some scenarios tables don't close their timestamps even while data
is expected from them. As an adequate workaround, spawn a task that does
this manually.
* This PR fixes a recognized bug. #8425
> coord: actively close table timestamps each second

- src/persist/src/indexed/runtime.rs
use tokio and async in persistence handles
Internal refactoring and code cleanup
> persist: use tokio and async in persistence handles

- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose.py
- src/coordtest/src/lib.rs
- src/dataflow/src/server.rs
- src/dataflowd/ci/.gitignore
- src/dataflowd/ci/Dockerfile
- src/dataflowd/ci/mzbuild.yml
- src/dataflowd/src/lib.rs
- src/dataflowd/src/main.rs
- src/materialized/ci/coordd/.gitignore
- src/materialized/ci/coordd/Dockerfile
- src/materialized/ci/coordd/mzbuild.yml
- src/materialized/src/bin/coordd.rs
- src/materialized/src/lib.rs
- test/cluster/insert-select.td
- test/cluster/mzcompose
- test/cluster/mzworkflows.py
**This PR adds a feature #3457** It adds support for running `coordd` and `dataflowd` in clustered mode. It also adds a CI test to ensure that the functionality doesn't break.
Fixes #3457.
~Most of the changes in `materialized` relate from extracting functionality that's shared between `materialized` and `coordd`.~ Updated to minimize the changes on `materialized`.
> Enable dataflowd/coord to work in clustered mode

- src/persist/src/indexed/runtime.rs
For debugging and possibly for use by the persist operators (maybe we
remove the explicit names in a followup?).
> persist: expose external name on read and write handles

- src/coord/src/coord.rs
Adds some documentation to convince myself (and maybe others) of what `since` and `upper` mean.
I have been trying to more thoroughly understand how Materializes uses "time"––in the broad sense that naive users will use it. The first thing I ran into was `since` and `upper`, which have some documentation, but I didn't feel confident in my understanding after reading it. This PR is an attempt to enhance the existing docs to make these concepts more approachable.
Note that this does not aim to be comprehensive, but simply iteratively improve the state of the coord's documentation.
There is a lot of noise here caused by wrapping the text to 80 chars. The only additions begin at line `## Frontiers another way`.
Pinging a few folks here …
> coord: add simplified explanation of frontiers to docs

- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose.py
- src/coordtest/src/lib.rs
- src/dataflow/src/server.rs
- src/dataflowd/ci/.gitignore
- src/dataflowd/ci/Dockerfile
- src/dataflowd/ci/mzbuild.yml
- src/dataflowd/src/lib.rs
- src/dataflowd/src/main.rs
- src/materialized/ci/coordd/.gitignore
- src/materialized/ci/coordd/Dockerfile
- src/materialized/ci/coordd/mzbuild.yml
- src/materialized/src/bin/coordd.rs
- src/materialized/src/lib.rs
- test/cluster/insert-select.td
- test/cluster/mzcompose
- test/cluster/mzworkflows.py
Some tiny improvements to dataflowd to improve its reliability/efficiency.
> dataflowd: minor improvements

- src/persist/src/indexed/mod.rs
- src/persist/src/mem.rs
This introduces a performance and write amplification optimization
that avoids writing out to META if what we're writing matches what's
already in storage.
indexed_write_drain/file_sorted/23000000
time:   [171.36 ms 172.77 ms 173.90 ms]
thrpt:  [126.14 MiB/s 126.96 MiB/s 128.00 MiB/s]
change:
time:   [-23.877% -22.099% -20.431%] (p = 0.00 < 0.05)
thrpt:  [+25.677% +28.368% +31.367%]
Performance has improved.
indexed_write_drain/file_unsorted/23000000
time:   [185.01 ms 190.43 ms 197.72 ms]
thrpt:  [110.94 MiB/s 115.18 MiB/s 118.56 MiB/s]
change:
time:   [-22.737% -19.014% -15.377%] (p = 0.00 < 0.05)
thrpt:  [+18.171% +23.478% +29.428%]
Performance has improved.
I ran the background persisted system tables test with and without this …
> persist: avoid overwriting meta in storage with exactly the same bytes

- src/testdrive/src/action/sql.rs
Since the transaction is aborted if the first COMMIT fails, subsequent
attempts to retry that statement will result in a success, which is
misleading, since a new transaction context is now in effect.
This causes testdrive to output a bogus and confusing 'query succeeded,
but expected error' message.
Fix by adding a "should retry" check to the code that executes
SQL statements that are expected to fail and have the check return
false for COMMIT and ROLLBACK.
People are being confused when testdrive retries COMMIT statements that are expected to fail.
I just copied over the mechanism used for non-failing SQL statements and applied it to failing ones.
> testdrive: do not retry COMMIT and ROLLBACK on error

- doc/user/content/sql/create-sink.md
The railroad diagram was updated; examples are now out of date.
> update create sink with consistency topic examples

- src/coord/src/catalog/builtin.rs
Needed for Metabase. Created as an empty view, since we do not have
constraints right now.
* This PR adds a known-desirable feature. #7783
> coord: add pg_constraint

- src/persist/src/indexed/encoding.rs
This invariant was always required (previously enforced write-once with
allow-overwrite=false). Ideally, we could test the stronger invariant that "all
keys ever used are only used once", but this will have to do for now.
> persist: add invariant that blob keys are globally unique.

- doc/user/content/guides/reuse-topic-for-kafka-sink.md
> docs: Update `CREATE SINK` syntax in EO guide

- doc/user/content/sql/functions/array_agg.md
- doc/user/content/sql/functions/filters.md
- doc/user/content/sql/functions/jsonb_agg.md
- doc/user/content/sql/functions/jsonb_object_agg.md
- doc/user/content/sql/functions/list_agg.md
- doc/user/content/sql/functions/string_agg.md
- doc/user/layouts/partials/sql-grammar/aggregate-with-filter.svg
- doc/user/layouts/partials/sql-grammar/array-agg.svg
- doc/user/layouts/partials/sql-grammar/jsonb-agg.svg
- doc/user/layouts/partials/sql-grammar/jsonb-object-agg.svg
- doc/user/layouts/partials/sql-grammar/list-agg.svg
- doc/user/layouts/partials/sql-grammar/string-agg.svg
- doc/user/sql-grammar/sql-grammar.bnf
Explain the `filter` modifier for aggregations.
> doc: Add FILTER to aggregate functions

- doc/user/content/overview/arrangements.md
> Fix truncated sentence

- doc/user/content/known-limitations.md
- doc/user/content/sql/functions/now_and_mz_logical_timestamp.md
Update links from temporal filters blog post to temporal filters guide (more recent)
Which of the following best describes the motivation behind this PR?
* This PR fixes a previously unreported bug. 
> doc: Update links for temporal filters guide

- Cargo.lock
- LICENSE
- doc/user/config.toml
- src/materialized/Cargo.toml
> Continue 0.9.14 dev

- doc/user/content/sql/create-sink.md
* This PR fixes a recognized bug. [9040] 
> Update reuse-topic example with new syntax

- doc/user/content/release-notes.md
- src/materialized/tests/server.rs
- src/sql/src/plan/statement/ddl.rs
- test/pg-cdc/pg-cdc.td
- test/testdrive/create-views.td
- test/testdrive/joins.td
- test/testdrive/kafka-avro-sinks.td
- test/testdrive/kafka-json-sinks.td
- test/testdrive/multijoins.td
- test/testdrive/rename.td
- test/testdrive/render-delta-join.td
- test/testdrive/tables.td
- test/testdrive/temporal.td
- test/testdrive/timelines.td
- test/testdrive/timestamps-debezium-kafka.td
This PR fixes a recognized bug. Fixes #9158
> sql: prevent creating views with duplicate column names

- src/sql/src/plan/transform_ast.rs
A general stack guard for the walkabout visit generator was more complicated than I had hoped, so just implement the normal guard here.
Fixes #9124
* This PR fixes a recognized bug. #9124
> sql: allow the Desugarer to grow its stack

- test/sqllogictest/github-9027.slt
> dataflow: test for github issue #9027, PR #9047

- doc/user/content/release-notes.md
- doc/user/content/sql/create-materialized-view.md
- doc/user/content/sql/create-view.md
- doc/user/layouts/partials/sql-grammar/create-materialized-view.svg
- doc/user/layouts/partials/sql-grammar/create-view.svg
- doc/user/sql-grammar/sql-grammar.bnf
Meant to include this in #9162
> docs: add supporting docs for unique view column name requirement

- src/dataflow/src/source/mod.rs
- src/dataflow/src/source/timestamp.rs
Before, we would restore bindings that are beyond the common seal
timestamp but not keep the information that we know of the partition.
This would lead to panics when trying to add the binding to
`timestamp_histories` at the call site of restore().
Now, we record that we know of a partition without restoring the offset,
by returning a Some/None for the restored offsets from restore().
@philip-stoev I didn't manage to reproduce the issue on `main`, but this definitely fixes an issue that is apparent from looking at the code and matches the error message you got.
Fixes #8909
- [N/A] This PR adds a release note for any
> persist: fix source bindings restore

- src/ore/src/stack.rs
@petrosagg tracked down why several functions have such massive stacks
in debug builds. Details within the patch, but the tl;dr is that the
large match statements can result in huge stack frames when compiler
optimizations are disabled.
So, this commit increases the `STACK_RED_ZONE` and `STACK_SIZE` values
in debug builds. That way `stack::maybe_grow` actually has a chance to
notice when the stack is running low on space in debug builds.
Note that we don't intend to worry much about excessively nested SQL
queries causing stack overflows in debug builds, since e.g. the lack of
tail call optimization can cause auto generated `Clone` implementations
to overflow. But this particular issue was causing very reasonable SQL
statements (see #9121) to overflow the stack in debug builds.
* This PR …
> ore: tolerate larger stacks in debug builds

- Cargo.lock
https://buildkite.com/materialize/security/builds/549
> bump tokio for security advisory

- src/coord/tests/sql.rs
- src/sql/src/func.rs
- src/sql/src/normalize.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement.rs
- src/sql/src/plan/typeconv.rs
- src/sql/src/query_model/test.rs
- src/symbiosis/src/lib.rs
I noticed this Rc is never used
> sql: remove unecessary Rc wrapper

- src/sql/Cargo.toml
Building materialized through `cargo build -p materialized` is broken on main
> sql: add missing aws_util feature

- ci/load/pipeline.yml
Once we actually want to do something with this we can put it back
> get rid of periodic chbench test since we don't look at it

- src/dataflow-types/src/plan/mod.rs
* This PR fixes a recognized bug. #9121
> dataflow: grow the stack in from_mir

- test/sqllogictest/pgcli.slt
Add a query that `pgcli` uses to get a collection of tables to enable autocompletion. Test it so it doesn't regress.
> test: verify pgcli query using regtype::text works

- src/materialized/src/bin/materialized/main.rs
This is occasionally useful for debugging
> Show number of timely workers in startup log

- src/persist/benches/writer.rs
- src/persist/src/golden_test.rs
- src/persist/src/indexed/columnar.rs
- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
Details in the commit messages.
This grabs the commit from #8551 and then builds on top of that in a separate commit, for ease of review.
> persist: columnar representation for unsealed batches

- doc/user/content/cloud/account-limits.md
- Update Cloud sizes
- Update Cloud regions
Reviewed by trippy at https://github.com/MaterializeInc/cloud-docs/pull/22
* This PR adds a known-desirable feature. #8858 
> doc: Update Cloud sizes and available regions

- src/transform/src/lib.rs
- src/transform/tests/test_runner.rs
This reverts commit 8e16a05c444fe38eefb5c95430605b4a706730d7.
Making them consts prohibited holding state in the transforms which made it impossible to have a recursion limit guard in them.
> Revert "transform: make all optimizer types const"

- ci/README.md
- ci/deploy/macos.py
- ci/deploy/pipeline.yml
* This PR adds a known-desirable feature. #5917
> ci: build native ARM binaries for macOS

- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/datum.rs
- src/expr/src/scalar/func/impls/int16.rs
- src/expr/src/scalar/func/macros.rs
- src/repr/src/lib.rs
- src/repr/src/scalar.rs
More transformed SQL functions
> expr: allow borrowed types when defining SQL functions

- ci/deploy/macos.py
* This PR fixes a previously unreported bug I introduced in #9294.
> deploy/macos: preserve environment when invoking cargo

- ci/deploy/deploy_util.py
- ci/deploy/macos.py
Shave the next few yaks for cross compiling macOS release binaries.
> ci/deploy: further tweak macos deployment env vars

- doc/developer/testdrive.md
fix runaway apostrophe and add oxford comma.
> doc: fix `testdrive` developer docs

- src/ccsr/Cargo.toml
- src/ccsr/src/client.rs
- src/ccsr/tests/client.rs
- src/sql/src/pure.rs
Just some small documentation and naming updates I happened across. Further bikesheds welcome. Should be no semantic changes at all.
> ccsr: minor cleanups

- src/dataflow/src/render/sources.rs
- src/persist/src/operators/stream.rs
We hold on to capabilities by storing them along with the seal futures
in `pending_futures`. This blocks the downstream frontier from advancing
while we are still waiting for a seal to be successful.
Before, we were letting go of the capability both when the future
finishes sucessfully and when it errored. This is incorrect because a
failed seal should not allow downstream progress.
Now, we retry a seal when it fails, with the same timestamp.
Additionally, we remove pending seal futures when they are superseded by
a successful seal for a later timestamp. The motivation behind this
latter part is that it can happen that a seal will never succeed,
because it is "before" the timestamp up to which the collection has
already been sealed. Eventually, some later seal will succeed and we can
then …
>  persist: seal errors must not allow the frontier to advance

- src/coord/src/coord.rs
Coordinator was instructing dataflow to drop timestamping for a non-existent source.
> coord: don't call sources-only code when dropping tables

- src/persist/src/operators/stream.rs
- src/persist/src/operators/upsert.rs
Before, we would write retractions individually and block on the write.
This was very slow when retracting larger amounts.
Now, we instead write retractions in batches and asynchronously wait for
the write futures to complete, similarly to how we do it in the
`persist()` operator.
Fixes #9123
@philip-stoev What should I do about the test case? We change the `--timestamping-frequency` for all tests, so probably can't leave that as is. WDYT?
We want to fix the aforementioned #9123.
The code is almost the same as for `persist()`, except that persist, well, persists all messages and forwards all of them while this operator "persists" a retraction for messages that are not beyond the given filter timestamp and forwards the rest.
- [N/A] This PR adds a release note for any
[user-facing behavior …
> persist: asynchronously retract in filter_and_retract_future_updates()

- doc/user/content/sql/copy-from.md
- doc/user/layouts/shortcodes/cloud-connection-details.html
- Updated Cloud connection instructions with Tailscale
- Added link to Tailscale docs to Privacy & Security settings description
- Added Tailscale VPN to security features
* This PR adds a known-desirable feature. [#8860]  
You can see how this will look to users by going to the Conversation tab, expanding the Tests section, and clicking "Details" next to the Netlify Build test.
- [] This PR adds a release note for any
> doc: Tailscale connection instructions

- ci/deploy/linux.py
- demo/chbench/mysql/Dockerfile
- misc/python/materialize/mzbuild.py
This PR fixes some bugs in various build and CI infrastructure. Details in commit messages.
> Various CI and build bugfixes

- .github/pull_request_template.md
Remove annoying linebreak in PR template and replace two '.' by ':'.
> github: Improve pull request template

- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
A refinement of #8777.
This allows getting a _differential_ `Description` of a persisted
stream.
This will be useful (needed even) when trying to determine a common
restore timestamp for multiple entangled streams backing a source and
when determining if the `since` of a stream is adequate for what the
rest of the dataflow needs.
On this question in the original PR:
> Second, and I'm less sure this is a good idea, I was considering the idea to making this call always return a map of external stream name -> [since, upper) for every non-destroyed persisted collection. This would (1) allow us to introspect into the set of collections being persisted, which is useful in tests and possibly other places, and (2) allow us to call this once at startup instead of once per stream. It's possible …
> persist: add get_description()

- src/testdrive/src/action/sql.rs
> testdrive: Don't truncate SQL queries

- README.md
> Update careers link (404).

- test/cluster/README.md
To share with prospects who are interested in clustering.
> test/cluster: write up instructions for manual clustering demo

- bin/crate-diagram
- doc/developer/guide.md
- misc/python/materialize/cli/crate_diagram.py
Designed for interactive use, it allows exploring the relationship between
various of our crates, and in particular zooming in on a subset of the graph by
specifying roots.
This replaces #6075
> Create a crate dependency diagram script

- src/persist/src/operators/stream.rs
`retract_unsealed` was previously almost an exact replica of `persist`, with some
application specific logic tweaks. That logic has now been lifted into other,
pre-existing timely operators (namely, partition, and map), to simplify the
overall code.
> persist: build retract_unsealed out of persist and other timely operators.

- doc/user/content/sql/create-source/postgres.md
- doc/user/layouts/partials/sql-grammar/create-source-postgres.svg
- doc/user/sql-grammar/sql-grammar.bnf
Document `timestamp_frequency_ms` option for Postgres source.
* This PR fixes a recognized bug: [#9410]
> Add timestamp_frequency_ms option to Postgres.

- src/expr/src/relation/mod.rs
- src/transform/tests/testdata/typ
- test/sqllogictest/scalar_subqueries_select_list.slt
- test/sqllogictest/uniqueness_propagation_filter.slt
Fixes #9397.
Use equality predicates to refine and extend the unique keys reported by `Filter`s.
> Improve key information for Filter

- Cargo.lock
> Fix for security advisory

- .github/ISSUE_TEMPLATE/release.md
- misc/python/materialize/cli/mkrelease.py
Update the release checklist for the new versioning scheme and the
bin/scratch script.
> .github: update release checklist

- src/expr/src/linear.rs
- test/sqllogictest/github-9504.slt
This PR fixes a recognized bug: #9504
> linear: Fix permutation for lower/upper bounds

- doc/user/content/release-notes.md
- doc/user/content/sql/deallocate.md
- doc/user/content/sql/execute.md
- doc/user/content/sql/prepare.md
- doc/user/layouts/partials/sql-grammar/deallocate.svg
- doc/user/layouts/partials/sql-grammar/execute.svg
- doc/user/layouts/partials/sql-grammar/prepare.svg
- doc/user/sql-grammar/sql-grammar.bnf
Document PREPARE, EXECUTE, and DEALLOCATE. Cross-reference with EXPLAIN.
* This PR adds a known-desirable feature: [#9085 ]
> doc: PREPARE/EXECUTE/DEALLOCATE

- src/expr-test-util/src/lib.rs
- src/expr-test-util/tests/test_runner.rs
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls.rs
- src/expr/src/scalar/func/impls/byte.rs
- src/expr/src/scalar/func/impls/date.rs
- src/expr/src/scalar/func/impls/interval.rs
- src/expr/src/scalar/func/impls/time.rs
- src/expr/src/scalar/func/impls/timestamp.rs
- src/expr/src/scalar/func/impls/uuid.rs
- src/expr/src/scalar/func/impls/varchar.rs
- src/repr/src/adt/datetime.rs
- src/sql/src/func.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/github-9027.slt
Just tinkering with the framework.
> sql: move more unary funcs to new framework

- misc/python/materialize/xcompile.py
@guswynn found a newer set of cross-compiling toolchains for macOS that
support the aarch64 architecture. This makes using mzcompose on M1 Macs
much faster since compilations no longer occur in Docker for Mac, which
has painfully slow I/O.
> xcompile: use a host toolchain on M1 Macs too

- doc/user/content/release-notes.md
@guswynn @mkysel just wanted to make sure y'all have had a chance to read the [release note style guide](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#how-to-write-a-good-release-note). Sorry to be a pest, but sadly no `cargo fmt` for the English language yet.
> doc: copy edit release notes

- ci/builder/README.md
- rust-toolchain.toml
- src/coord/src/catalog/error.rs
- src/coord/src/client.rs
- src/dataflow/src/activator.rs
- src/dataflow/src/operator.rs
- src/dataflow/src/render/sinks.rs
- src/dataflow/src/source/kinesis.rs
- src/dataflow/src/source/mod.rs
- src/expr-test-util/tests/test_runner.rs
- src/expr/src/relation/func.rs
- src/expr/src/scalar/mod.rs
- src/interchange/src/avro.rs
- src/interchange/src/avro/envelope_cdc_v2.rs
- src/materialized/src/http.rs
- src/materialized/src/lib.rs
- src/ore/src/stack.rs
- src/persist/src/nemesis/direct.rs
- src/pgtest/src/lib.rs
- src/transform/src/nonnullable.rs
- src/transform/src/union_cancel.rs
new rust toolchains catch more bugs, build faster, produce faster code, and open up new features.
this is almost entirely cleaning up new lints clippy found
> Upgrade to rust 1.57

- test/testdrive/kafka-include-key-sources.td
I was trying to add tests to the end of a file and wanted to do things faster,
this should never have been committed.
> Uncomment debug-disabled tests

- Cargo.lock
- demo/chbench/mzcompose.yml
- doc/user/content/demos/business-intelligence.md
- doc/user/content/third-party/metabase.md
- src/metabase/Cargo.toml
- src/metabase/src/lib.rs
- test/metabase/mzcompose.yml
- test/metabase/smoketest/src/main.rs
I wanted to get test/metabase switched to the unforked version of Metabase before I forgot, and figured I'd take a stab at the docs updates while I was in the area. 
----
Update docs, demos, and tests for our new compatibility with unforked
Metabase.
Fix #9571.
Fix #9572.
> doc/user,demo/chbench: update for unforked metabase

- doc/user/content/release-notes.md
- test/sqllogictest/table_func.slt
add tests to confirm multi-dimensional generate_subscripts
This is a follow up to #9472
> sql: add tests to confirm multi-dimensional generate_subscripts

- test/performance/perf-upsert/src/config.rs
- test/performance/perf-upsert/src/main.rs
This PR refactors to remove code that is no longer needed.
> perf/upsert: remove outdated source persistence options

- src/sql/src/query_model/dot.rs
- src/sql/src/query_model/hir.rs
- src/sql/src/query_model/lowering.rs
- src/sql/tests/querymodel/basic
- src/sql/tests/querymodel/lowering
> Support for scalar subqueries in QGM

- Cargo.lock
- LICENSE
- doc/user/content/release-notes.md
- src/materialized/Cargo.toml
> Prepare 0.13.1 dev

- src/persist/src/s3.rs
I don't have a good way of testing this. @danhhz wdyt?
----
The AwsConfig type is now immutable, to match the upstream type, so
constructing the AssumeRoleProvider in persist initialization has to be
rejiggered a bit.
This PR fixes merge skew.
> persist: fix merge skew with AWS configuration

- doc/user/content/release-notes.md
Add release notes for a few unmentioned optimizer bugfixes. Also move
some release notes that were incorrectly listed in the v0.12 section.
> doc/user: polish release notes for v0.13

- .gitignore
- ci/builder/requirements-dev.txt
- doc/developer/feature-benchmark.md
- misc/python/materialize/feature_benchmark/aggregation.py
- misc/python/materialize/feature_benchmark/benchmark.py
- misc/python/materialize/feature_benchmark/comparator.py
- misc/python/materialize/feature_benchmark/executor.py
- misc/python/materialize/feature_benchmark/filter.py
- misc/python/materialize/feature_benchmark/measurement_source.py
- misc/python/materialize/feature_benchmark/scenario.py
- misc/python/materialize/feature_benchmark/termination.py
- misc/python/materialize/mzcompose.py
- test/feature-benchmark/mzcompose
- test/feature-benchmark/mzworkflows.py
- test/feature-benchmark/scenarios.py
Rendered version of the documentation:
https://github.com/philip-stoev/materialize/blob/feature-benchmark/doc/developer/feature-benchmark.md
> Feature benchmark

- src/sql/src/query_model/dot.rs
- src/sql/src/query_model/hir.rs
- src/sql/src/query_model/lowering.rs
- src/sql/src/query_model/mod.rs
> qgm: don't leak `RefCell<*>` outside QGM models

- doc/user/content/release-notes.md
- doc/user/content/sql/select.md
- src/ore/src/iter.rs
- src/sql-parser/src/ast/defs/query.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql-parser/tests/testdata/select
- src/sql/src/func.rs
- src/sql/src/plan/error.rs
- src/sql/src/plan/explain.rs
- src/sql/src/plan/expr.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/scope.rs
- src/sql/src/plan/transform_ast.rs
- src/sql/src/plan/transform_expr.rs
- src/sql/src/plan/typeconv.rs
- src/sql/src/query_model/hir.rs
- src/sql/tests/querymodel/basic
- src/sql/tests/querymodel/dotformat
- test/sqllogictest/order_by.slt
- test/sqllogictest/scoping.slt
- test/sqllogictest/table_func.slt
Details in commit messages and release notes. A few commits are just cleanups and are noted as such. Let me know if it'd be helpful to submit this in chunks; unfortunately it's all massively interdependent.
> sql: squash a pile of bugs

- src/materialized/src/bin/materialized/main.rs
Extracted from #9665.
The idea here is to perform the filtering specified by the
`--log-filter` argument at the last possible moment, right before the
message is emitted to disk. This ensures that other log messages (e.g.,
trace and debug logs) are available to other parts of the logging
subsystem that may want to do something smart with them.
This already pays dividends in that the mz_log_message_total metric can
keep track of the log messages that don't get written out to the file.
It also paves the way for integrations with e.g. the Tokio console (see
> materialized: perform log filtering on the fmt layers

- src/sql/src/query_model/hir.rs
- src/sql/src/query_model/lowering.rs
- src/sql/src/query_model/mod.rs
- src/sql/src/query_model/scalar_expr.rs
- src/sql/tests/querymodel/basic
- src/sql/tests/querymodel/lowering
Closes #9132
Closes #9133
This PR adds a known-desirable feature
> qgm: support for `Distinct` and `Reduce`

- misc/python/materialize/xcompile.py
We're now building our own cross-compiling toolchains for macOS in
MaterializeInc/homebrew-crosstools. Switch xcompile over to using those.
This is a bit safer, as we're no longer downloading random binaries from
the internet, and also lets us control our own destiny, e.g., if we ever
want to update the version of binutils/GCC/glibc/Linux in the toolchain.
I'm running tests on these manually now!
> xcompile: use first-party cross-compiling toolchains on macOS

- misc/python/materialize/cli/mzcompose.py
Make mzcompose even smarter about handling `docker-compose run` so that
invocations like
$ ./mzcompose run --entrypoint bash testdrive
are correctly forwarded to Docker Compose.
> mzcompose: handle run arguments properly

- src/persist/src/indexed/mod.rs
- src/persist/src/indexed/runtime.rs
- src/persist/src/operators/source.rs
- src/persist/src/operators/stream.rs
Previously, we allowed users to pass an arbitrary callback as the argument to listen.
This was nonideal for several reasons:
1. A user could inadvertently inject CPU intensive work into notifying listeners.
2. All existing listeners really wanted to send either all of the data or a subset
of the data somewhere else via a channel.
3. This structure made it more difficult to e.g. move listener notification
onto a different thread.
This commit changes the behavior of listen to instead return a Receiver<ListenEvent>
that the user can do whatever they want with.
> persist: have listen take a Sender for events instead of a callback

- play/mbta/.gitignore
- play/mbta/doc/mbta-setup.md
- play/mbta/mzcompose.yml
- play/mbta/mzworkflows.py
> play/mbta: convert to mzworkflows.py

- ci/builder/requirements-dev.txt
- ci/builder/requirements.txt
- misc/python/materialize/mzcompose.py
Extracted from #9824 so that it can be merged sooner and used in other
PRs.
> mzcompose: add Workflow.run_sql convenience method

- ci/test/pipeline.template.yml
Since #9771 these are no longer necessary.
> ci/test: remove IDs from jobs

- src/persist/benches/writer.rs
- src/persist/src/indexed/arrangement.rs
- src/persist/src/indexed/background.rs
- src/persist/src/indexed/cache.rs
- src/persist/src/indexed/encoding.rs
> persist: prep for upcoming changes to data blob encoding format

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
> Prepare 0.15.1 dev

- misc/python/materialize/mzcompose.py
> mzcompose: add kgen as a python service

- doc/user/content/sql/tail.md
- src/coord/src/client.rs
- src/coord/src/command.rs
- src/coord/src/coord.rs
- src/coord/src/lib.rs
- src/dataflow/src/source/s3.rs
- src/materialized/tests/sql.rs
- src/pgwire/src/protocol.rs
- src/transform/tests/testdata/union_cancel
- test/lang/csharp/SmokeTest.cs
Discussed on Slack, where a poll came out in favor of "canceled"
over "cancelled": https://materializeinc.slack.com/archives/CM7ATT65S/p1641250834441600
(Vacuously)
> Use American spelling of "canceled" throughout the codebase.

- src/coord/src/coord.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/query_model/dot.rs
- src/sql/src/query_model/mod.rs
- test/sqllogictest/query_graph.slt
Add `EXPLAIN QUERY GRAPH FOR` subcommand. Currently it outputs the graphviz representation of the query graph.
Extracted from #9689.
> EXPLAIN QUERY GRAPH FOR <query/view>

- doc/user/content/release-notes.md
> doc/user: assemble v0.15 release notes

- doc/user/config.toml
> Continue 0.15.1 dev

- doc/developer/feature-benchmark.md
Adds docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9932)
> doc,feature-benchmark: Add documentation on how to perform bisection

- src/repr/src/scalar.rs
`base_eq` was incorrectly taking nullability into account when comparing records.
* This PR fixes a recognized bug: https://github.com/MaterializeInc/materialize/pull/9940#pullrequestreview-847089086
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9942)
> repr: ignore nullability in base_eq for Records

- ci/builder/requirements-core.txt
- ci/builder/requirements-dev.txt
- ci/builder/requirements.txt
Amalgamates Python dependency bumps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9974)
> Python dependency bump 2022-01-10

- Cargo.lock
- src/aws-util/Cargo.toml
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/persist/Cargo.toml
- src/s3-datagen/Cargo.toml
- src/testdrive/Cargo.toml
- src/testdrive/src/action/s3.rs
- test/perf-kinesis/Cargo.toml
* Dependency bump amalgamation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9970)
> deps: upgrade to latest AWS SDK

- src/avro/src/reader.rs
Fixes #8669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9983)
> avro: initialize buffer to avoid potential UB

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9986)
> Prepare 0.16.1 dev

- src/sqllogictest/src/runner.rs
- Add the missing code that allows --rewrite-results to perform
in-place update of SLT lines of the following form:
```
query I
SELECT ...
----
NN values hashing to MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
```
- abstract some duplicate code in a separate function
This PR would allow auto-generated SLT files containing "hashing to" lines to be automatically rewritten by sqllogictest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9998)
> sqllogictest: Allow --rewrite-results to process hash results

- src/sql/src/func.rs
Point users to the document explaining this error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/10003)
> sql: link now() error to docs explainer

- doc/user/content/sql/tail.md
Improve docs for TAIL to list and link to the transaction limits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/10004)
> doc: describe and link to TAIL transaction limits

- test/feature-benchmark/scenarios.py
Benchmark the performance of ORDER BY within dataflows
> feature-benchmark: Add scenario for ORDER BY within dataflows

- deny.toml
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).
> deny: describe RUSTSEC-2021-0122 mitigation

- doc/user/config.toml
> Update released versions to include v0.16.0

- src/persist/README.md
- src/persist/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/7356)
> persist: update README with latest thinking

- .github/ISSUE_TEMPLATE/05-release.md
Just two small things I noticed in the release today. More details in each commit
> issue_templates: two small edits to the release template

- src/materialized/src/bin/materialized/main.rs
exact same as https://github.com/MaterializeInc/materialize/pull/9915
I accidentally overwrote this in https://github.com/MaterializeInc/materialize/pull/9990
fixes: https://github.com/MaterializeInc/materialize/issues/10048
> filter MetricsRecorderLayer with the same filter as the fmt layer

- test/feature-benchmark/scenarios.py
Benchmark the performance of exactly-once sinks
A scenario with sinks was needed in the feature benchmark.
> feature-benchmark: Add senario for exactly-once sinks

- src/coord/src/sink_connector.rs
- src/kafka-util/src/client.rs
- src/sql/src/kafka_util.rs
Move another function that's not mz-specific to the new `kafka_util` crate.  I'm pulling this out of a PR I have in the works that refactors kafka sinks.
Only functional change is that the function now takes a generic `Client` instead of requiring that the `Client` be a `Consumer`
> [sql] move get_partitions to kafka_util

- doc/user/content/release-notes.md
- src/expr/src/scalar/like_pattern.rs
- src/sql/src/func.rs
- test/sqllogictest/cockroach/like.slt
Details in commit messages.
* This PR fixes recognized bugs.
> sql: fix bugs in LIKE

- rust-toolchain.toml
- src/dataflow/src/source/postgres.rs
- src/expr-test-util/tests/test_runner.rs
- src/expr/src/id.rs
- src/expr/src/relation/mod.rs
- src/expr/tests/test_runner.rs
- src/lowertest/src/lib.rs
- src/lowertest/tests/test_runner.rs
- src/persist/src/indexed/columnar.rs
- src/repr-test-util/src/lib.rs
- src/sql-parser/tests/sqlparser_common.rs
- src/testdrive/src/action/kafka/create_topic.rs
- src/testdrive/src/action/kafka/verify.rs
- src/testdrive/src/action/sql.rs
- src/walkabout/src/gen.rs
- test/perf-kinesis/src/kinesis.rs
new rust toolchains catch more bugs, build faster, produce faster code, and open up new features.
> upgrade to rust 1.58

- doc/user/content/release-notes.md
- doc/user/layouts/partials/create-source/connector/kafka/with-options.html
> doc/user: polish and complete release notes/docs for v0.17.0

- misc/python/materialize/cli/scratch/__main__.py
- misc/python/materialize/cli/scratch/sftp.py
- misc/python/materialize/scratch.py
I would find it useful for fetching files off instances.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).
> scratch: add 'sftp' command that connects via msftp

- misc/scratch/big-dev-box.json
Add a new "big-dev-box" alias for a machine that is identical to the one currently
used to run release tests, for one-off benchmarking and load testing.
> misc/scratch: add new alias for a big dev box

- doc/user/content/guides/node-js.md
There was a missing comma and extra braces in the example code.
Fixes code to do copy-paste and compile.
-
> doc/user: add comma and remove braces

- src/coord/src/coord.rs
- src/dataflow-types/src/client.rs
- src/dataflow/src/server.rs
- src/dataflow/src/server/metrics.rs
This PR factors `dataflow::Command` into COMPUTE and STORAGE variants, and then wraps each of the variants behind traits that provide methods that mint the correct commands. The externally visible effect is that `coord.rs` no longer has a `broadcast` method, and instead calls methods on `self.dataflow_client` other than `send`. The same has not yet been done with `recv`.
Details of the implementation of the COMPUTE and STORAGE protocols leaked all over the place, and this intends to put those concerns behind abstractions that can change without randomizing the users.
The only known behavioral change is for metrics reporting, which were locked in to the old representation of commands and needed to change. I removed `CommandKind` and made the metrics based …
> Platform commands

- Cargo.lock
- bin/pre-push
- misc/python/materialize/cargo.py
- src/aws-util/Cargo.toml
- src/aws-util/src/kinesis.rs
> misc: various little fixes

- doc/developer/guide.md
It's high time we added this, since the majority of new people tend to ask about it.
> Add note on recommended editors and IDEs to the developer guide

- src/persist/benches/writer.rs
- src/persist/src/client.rs
- src/persist/src/indexed/arrangement.rs
- src/persist/src/indexed/background.rs
- src/persist/src/indexed/cache.rs
- src/persist/src/indexed/mod.rs
- src/persist/src/operators/input.rs
- src/persist/src/operators/source.rs
- src/persist/src/runtime.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/materializeinc/materialize/9574)
> persist: split out a read-only runtime

- test/kafka-ingest-open-loop/mzcompose.py
./mzcompose run kafka-ingest-open-loop --s3-storage=dan-0000
If this is run from a bin/scratch instance, the permissions are already
set up. If we need to run it from elsewhere, we'll have to make this
more configurable.
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).
> test: hook s3 storage up in the kafka-ingest-open-loop benchmark

- ci/builder/Dockerfile
- doc/developer/guide.md
- doc/user/content/install.md
- misc/scratch/provision.bash
Account for issues building C++ outside of bin/xcompile that @danhhz noticed. Details in commit messages.
> Fix some C++ build issues 

- src/coord/src/coord.rs
- src/sql-parser/src/ast/defs/statement.rs
- src/sql-parser/src/parser.rs
- src/sql/src/plan/statement/dml.rs
- src/sql/src/query_model/mod.rs
- src/sql/src/query_model/rewrites/mod.rs
- src/sql/src/query_model/scalar_expr.rs
Closes #9143.
* Add one sample rewrite.
* Tests for the one sample rewrite.
Commit 1 is just a function to update box and quantifier ids so graphs print out more nicely after the rewrite process.
Commit 2 is the actual rewrite engine.
Commit 3 prints OPTIMIZED QUERY MODEL so we have some ability to test.
> QGM: Basic rewrite engine.

- test/feature-benchmark/scenarios.py
Merge skew. One of feature benchmark scenario  needs to be updated to the new syntax.
> feature-benchmark: Address merge skew

- test/testdrive/avro-cdcv2.td
Previously, this test tried to emulate a produce belatedly sending a stream of
data that CDCv2 should ignore, but it did not send exact copies of ((k, v) t, d)
as expected and instead forwarded the times to a later time. The test
also had two instances of the same ((k, v), t) in a batch which is not valid
CDCv2 input.
This commit fixes the test to emit actually previously emitted data that obeys
the requirement that CDCv2 batches are consolidated.
> test: fix test for cdcv2

- bin/check
- src/avro/src/schema.rs
- src/coord/src/client.rs
- src/coord/src/coord.rs
- src/coord/src/coord/antichain.rs
- src/coord/src/coord/arrangement_state.rs
- src/coordtest/src/lib.rs
- src/dataflow-bin/src/bin/dataflow-logview.rs
- src/dataflow/src/decode/mod.rs
- src/dataflow/src/render/mod.rs
- src/dataflow/src/render/sinks.rs
- src/dataflow/src/server.rs
- src/dataflow/src/sink/kafka.rs
- src/dataflow/src/sink/tail.rs
- src/dataflow/src/source/kafka.rs
- src/dataflow/src/source/timestamp.rs
- src/interchange/src/avro/envelope_cdc_v2.rs
- src/materialized/src/bin/materialized/main.rs
- src/materialized/src/mux.rs
- src/ore/src/metrics.rs
- src/persist/benches/writer.rs
- src/sql/src/kafka_util.rs
- src/sql/src/pure.rs
- src/testdrive/src/action/verify_timestamp_compaction.rs
As discussed, we think this lint is high enough value to be enabled repo-wide
- it builds
- N/A This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).
> Turn on clippy::clone_on_ref_ptr repo-wide

- bin/ci-builder
- ci/test/pipeline.template.yml
- misc/python/materialize/mzcompose/services.py
- src/testdrive/src/main.rs
- test/testdrive/mzcompose.py
Shard the testdrive job in CI to make it run faster.
Fix #7774.
> testdrive: shard

- src/coord/src/coord.rs
cc @cjubb39, thanks for spotting it!
> coord: remove leftover println!

- src/sql/src/query_model/rewrites/mod.rs
Changes the QGM rewrite engine API as follows:
- `Rule` declares an associated type `Rule::Match`.
- `Rule::check` returns `Option<Rule::Match>` to indicate a match.
- `Rule::rewrite` applies the rewrite parameterized by the returned `Rule::Match` to the `Model`.
The `ApplyRule` is a trait with blanket implementation that abstracts over the associated type `Rule::Match` in an `apply`
method. This is [the accepted solution](https://users.rust-lang.org/t/dynamic-dispatch-and-associated-types/39584) for using trait objects without fixing the associated type.
The proposed changes have the following benefits:
1. Better separation of concerns. Each rule implementation will consist of a single trait implementation (`Rule`) that defines the
business logic for …
> qgm: introduce `Rule::Match` and `ApplyRule`

- doc/developer/README.md
- doc/developer/reading.md
Document the required reading list. This can also serve as a place for non-required reading.
> doc: add required reading

- src/persist/src/runtime.rs
skewed with @danhhz's change
edit: not sure what pr it was that skewed
> fix spawn_named merge_skew

- src/testdrive/src/action.rs
- src/testdrive/src/main.rs
- test/kafka-ssl/jaas_config.conf
- test/kafka-ssl/multi.td
- test/kafka-ssl/mzcompose.py
- test/kafka-ssl/smoketest.td
- test/kafka-ssl/users.properties
- test/kafka-ssl/with-options-errors.td
> Ensure CCSR's basic_auth code is exercised in test/kafka-ssl/

- src/coord/src/coord.rs
When since_updates got split into index_since_updates and
source_since_updates, it looks like the ones persist was looking for
ended up in index_since_updates (the wrong one). This means the
compaction frontier for persisted tables never advances. Since we run a
background test of persist on two system tables, this means unbounded
storage (disk) usage, which is very much not correct. Putting this call
to persist back in as a workaround while we fix the bug the proper way,
which is making sure the messages end up in source_since_updates
instead.
Touches #10300
> persist: add temporary workaround for persisted table compaction bug

- doc/developer/platform/index.md
- doc/developer/platform/overview.md
- doc/developer/platform/sql-catalog.md
Counterpart to #10273.
* Colocate the Platform gists.
> doc/platform: describe candidate SQL catalog mapping

- doc/developer/platform/README.md
- doc/developer/platform/index.md
So that the GitHub web UI is useful.
> doc/platform: create a proper README

- Cargo.lock
- ci/builder/requirements-core.txt
- ci/builder/requirements-dev.txt
- ci/builder/requirements.txt
- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/feature_benchmark/scenario.py
- src/aws-util/Cargo.toml
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/persist/Cargo.toml
- src/s3-datagen/Cargo.toml
- src/testdrive/Cargo.toml
- test/perf-kinesis/Cargo.toml
> Dependabot amalgamation

- test/kafka-ingest-open-loop/mzcompose.py
This commit makes the open loop benchmark slightly easier to use by:
- adding an argument to vary the number of timely workers
- adding help strings for all arguments
- forbidding the use of --s3-storage without --enable-persistence
> kafka-ingest: small ergonomic cleanups.

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
> Prepare 0.19.1 dev

- src/persist/src/s3.rs
AWS advises concurrent byte-range downloads of large files[1]. We'll do
this soon, but initially I'm focused on tuning our steady state
ingestion and so am starting with uploads. The equivalent for uploads is
"multipart", which was recommended to me internally by Alessandro and
Nick. It's also recommended by AWS for "when your object size reaches
100 MB"[2], but after some experimentation, my read of this isn't "don't
bother with multipart until your files are > 100MB" but instead more
like "by the time your files are 100MB, you'd be silly not to have
started using multipart".
[1]: https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html
[2]: https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html
Some AWS SDKs will …
> persist: use s3 multipart uploads when appropriate

- doc/user/content/release-notes.md
- doc/user/content/sql/functions/date-bin-hopping.md
> doc/user: complete + polish release notes for v0.19.0

- misc/python/materialize/xcompile.py
Since 09b7f3e, bootstrapping needs to happen inside of `xcompile.cargo`
before we execute `cc -print-sysroot`.
> xcompile: fix bootstrap on darwin

- test/persistence/kafka-sources/start-offset-after.td
- test/persistence/kafka-sources/start-offset-before.td
Add topics with start_offset and kafka_time_offset to the persistence test
> persistence,test: Add start_offset and kafka_time_offset to tests

- doc/user/content/sql/system-catalog.md
- src/coord/src/catalog/builtin.rs
- test/sqllogictest/information_schema_columns.slt
- test/sqllogictest/information_schema_tables.slt
- test/sqllogictest/pg_catalog_attribute.slt
- test/sqllogictest/pg_catalog_proc.slt
- test/sqllogictest/pg_catalog_roles.slt
- test/sqllogictest/pg_catalog_views.slt
For some forthcoming simplifications to dbt-materialize.
* Go commit by commit.
> coord: add more compatibility shims to the system catalog

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/float64.rs
- src/expr/src/scalar/mod.rs
- src/sql/src/func.rs
- test/sqllogictest/funcs.slt
Was easy and is needed for dbt. Details in #10384
> sql: add inverse trigonometric functions

- src/dataflow/src/render/mod.rs
- src/dataflow/src/render/sources.rs
- src/dataflow/src/server.rs
- src/persist/src/client.rs
Alternative to #9981 that keeps handles that allow compaction in `StorageState`, and allows compaction on them right when `AllowSourceCompaction` comes in. We upper bound the allowed compaction by also looking at the sealed frontier, which we do using a `ProbeHandle`.
The compaction since of persisted sources is upper-bounded by two frontiers: a) the
compaction that the coordinator allows, and b) the seal frontier of the involved persistent
collections.
We need to obey a) because that's what the coordinator wants, and b) because if we persisted
past (or up to) the seal frontier we would not be able to distinguish between valid and
invalid updates based on the upper seal frontier when restarting.
We get the upper seal frontier using a probe handle, and we expect the coordinator to call …
>  persist,sources: allow compaction on persisted sources

- src/persist/src/operators/stream.rs
Previously, the conditional test would very rarely fail because the primary stream
had sealed to a time (4) that we did not explicitly ask it to.
This happened because:
- the timely::execute_directly command on drop closes all unclosed inputs and
runs the dataflow to completion.
- Progress information (including closure) doesn't travel through the dataflow
all at the same time, even if two inputs are both closed before calling step()
This lead to a situation where if the condition input had been advanced (and sealed)
through 4, and the primary input had been advanced and sealed through 3, the
primary seal operator (which sits downstream of both sources) could observe the
primary input's closure (ie that the primary input has the frontier []), before
it observes the condition input's …
> persist: fix flaky conditional_seal test

- doc/developer/guide.md
> Guide fixes

- doc/user/content/release-notes.md
- doc/user/data/sql_funcs.yml
- src/expr/src/scalar/func.rs
- src/expr/src/scalar/func/impls/float64.rs
- src/sql/src/func.rs
For use by materialize-dbt-utils.
> expr,sql: support `radians` and `degrees` functions

- src/dataflow-types/src/client.rs
- src/dataflow/src/source/timestamp.rs
Testing for a potential regression in the durability frontier of source timestamps.
> Test for regression in source durability frontier

- doc/developer/testdrive.md
- src/testdrive/src/action.rs
- src/testdrive/src/action/skip_if.rs
- src/testdrive/src/action/sql.rs
Apply some small cleanups from the review of #10361 that seem to have
gotten lost.
> testdrive: small cleanups to skip-if

- misc/python/materialize/cli/scratch/create.py
Motivation: attempt to fix high AWS bills
> Change bin/scratch default timeout

- src/coord/src/coord.rs
- src/dataflow-types/src/client.rs
- src/dataflow-types/src/client/controller.rs
- src/dataflow/src/server.rs
This is a reboot of https://github.com/MaterializeInc/materialize/pull/10373 which had conflicts in `coord.rs` I was not brave enough to resolve.
> Introduce compute instances to the coordinator

- src/dataflow/src/source/kafka.rs
The previous refactor of removing metadata fetching out of the
timestamper thread in the coordinator introduced an unintended change in
behaviour where kafka sources enter an errored state when we can't fetch
metadata.
This reverts the previous behaviour where we'll keep retrying to fetch
metadata and ignore any errors.
> kafka source: retry on metadata fetch errors

- ci/nightly/pipeline.yml
> Fix nightly test aws-config config

- ci/nightly/pipeline.yml
This scenario is no longer tenable after #10498
> test,nightly: remove the --workers 32 scenario

- test/persistence/mzcompose.py
This reverts commit 1d13e8254c166c282a607820ddaa34433c2b53b1.
> Revert "test/persistence: temporarily disable flaky test"

- src/coord/src/catalog.rs
- src/coord/src/coord/dataflow_builder.rs
- src/coord/src/error.rs
- test/persistence/kafka-sources/repeated-source-rendering-after.td
- test/persistence/kafka-sources/repeated-source-rendering-before.td
Fixes #9330
- [N/A] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).
> coord: only allow one materialization for persisted sources

- .gitignore
- bin/ci-builder
- ci/slt/slt.sh
- ci/test/cargo-test/mzcompose.py
- ci/test/slt-fast.sh
- misc/dbt-materialize/mzcompose.py
- misc/python/materialize/ci_util.py
- misc/python/materialize/cli/mzcompose.py
- misc/python/materialize/mzcompose/__init__.py
- misc/python/stubs/junit_xml.pyi
- src/sqllogictest/src/main.rs
- src/testdrive/src/main.rs
- test/proxy/mzcompose.py
- test/sqllogictest/mzcompose.py
- test/testdrive/mzcompose.py
This PR continues the work that @nharring-adjacent kicked off in #10574 and wires up the rest of CI to Buildkite Test Analytics.
> testdrive,sqllogictest,mzcompose: add basic test analytics integration

- ci/test/build.py
This PR adjusts the ci builder code to write the docker tags that it generates / uploads to dockerhub into an annotation on the build page.
This PR adds a feature that has not yet been specified
I would like to easily identify the docker tag that I need in order to spin up a container that can be tested (e.g. on mzcloud); the current way to do it, as far as I can tell, is to dig through a bunch of scrollback until you find https://buildkite.com/materialize/tests/builds/28518#907d38b3-4f7d-4210-b10b-1788aa6bb605
This PR's builds should in fact have an annotation! ...aaaand it does: https://buildkite.com/materialize/tests/builds/28606#annotation-default
> ci: Annotate each build with its docker image tags

- ci/test/mkpipeline.py
- ci/test/pipeline.template.yml
> ci/test: fix pipeline trimming with new analyze job

- ci/deploy/devsite.sh
> ci/deploy: fix devsite deploy

- ci/builder/requirements-core.txt
- ci/builder/requirements-dev.txt
- ci/builder/requirements.txt
* Weekly Python dependency bump.
> deps: weekly python dependency bump

- ci/nightly/pipeline.yml
- ci/nightly/trim_pipeline.py
> ci/nightly: permit skipping tests when manually triggering build

- doc/user/content/release-notes.md
- doc/user/content/sql/create-source/avro-kafka.md
- doc/user/content/sql/types/array.md
- doc/user/layouts/partials/specifying-aws-credentials.html
> doc/user: complete and polish release notes for v0.20.0

- doc/user/layouts/partials/specifying-aws-credentials.html
I failed to finish this thought in #10657.
* This PR fixes a bug.
> doc/user: fix typo in AWS credential docs

- test/feature-benchmark/scenarios.py
- a SELECT 1 query
- incoming SQL connection establishment
I wanted to make sure we do not regress by introducing any overhead in the coordinator which affects all queries or incoming SQL connections.
> feature-benchmark: Add scenarios around basic coordinator operations:

- .github/ISSUE_TEMPLATE/07-optimization.yml
The [proposed template for a new optimization](https://docs.google.com/document/d/1VoXjWKLttblT1vJo3AkEH3ZuY8ejwCul5mGuu2KEZxM/edit#heading=h.8sx109d6k7kb) has now been adapted to github issue template form! Past feedback should have been addressed!
Only the first section ("Elevator pitch") is strictly required.
@aalexandrov was wondering if the cost model could be omitted if the cost model would be as complicated or more complicated than the implementation of the optimization. After looking at #10500, I believe we should always fill out the cost model section if either the cost model or the implementation is not trivial because seeing a cost model just makes it so much easier to verify the correctness and usefulness of the optimization.
We may want a TODO to link to the template some …
> Add issue template for a proposal for a new optimization.

- ci/test/cargo-test/mzcompose.py
- misc/python/materialize/mzcompose/services.py
- src/coord/src/catalog.rs
- src/coord/src/catalog/builtin.rs
- src/pgrepr/src/oid.rs
- src/sql/src/func.rs
@mjibson are you up for sheparding this one the rest of the way through CI? I think there's maybe some pgtest work you want to push into this PR too?
----
And actually wire that test up in CI so that it doesn't break.
Touches #10681.
* This PR fixes part of a recognized bug
> coord: test that type OIDs match PostgreSQL

- src/coord/src/coord.rs
- src/dataflow-types/src/client.rs
> coord: add the Send bound only where needed

- test/feature-benchmark/scenarios.py
A scenario for the snapshot part already existed, so this commit
adds a scenario for measuring the performance of post-snapshot ingestion
This is needed to cover both aspects of Postgres CDC replication -- snapshot + streaming.
> feature-benchmark: Add scenario for Postgres CDC

- src/materialized/src/bin/materialized/main.rs
For consistency with all the other environment variables that are
correspond to CLI args.
> materialized: add missing "MZ_" prefix to new frontegg environment variables

- src/dataflow/src/source/timestamp.rs
More details in the commit messages
> dataflow: refactor PartitionTimestamps

- src/expr/src/scalar/func.rs
- src/sql-parser/tests/testdata/scalar
Some small fixes I missed in #10705
> misc: small misc. fixes overlooked in #10705 

- ci/test/cargo-test/image/Dockerfile
- ci/test/cargo-test/image/run-tests
- misc/python/materialize/mzcompose/services.py
- test/pgtest-mz/copy-from-csv.pt
So that test failures actually cause the build job to fail.
* This PR fixes a bug reported in Slack.
> ci/test: hoist ci_try out of subshell

- doc/user/content/sql/create-index.md
- doc/user/layouts/partials/sql-grammar/create-index.svg
- doc/user/sql-grammar/generate.sh
- doc/user/sql-grammar/sql-grammar.bnf
> doc/user: mention that arbitrary expressions are supported in CREATE INDEX

- test/persistence/mzcompose.py
This reverts commit b395db813580b3b557cc7b11599309105320632c.
> Revert "Revert "test/persistence: temporarily disable flaky test""

- ci/test/pipeline.template.yml
> ci/test: re-enable unused deps lint

- doc/developer/platform/architecture-db.md
Per the latest thinking. CONTROL does very little controlling, but
rather "adapts" the APIs of STORAGE and CONTROL according to user
desires.
* This PR refactors existing terminology.
> doc/platform: rename CONTROL to ADAPTER

- src/dataflow/src/source/kafka.rs
The metadata thread was previously checking whether the source it was
spanwed for was dropped as the first step in its polling loop.
Since the poll loop by default was 5 minutes it could cause a lot of
idle threads to linger around for a maximum of 5 minutes.
Now the thread parks itself with a timeout instead of sleeping and we
make sure to unpark it when the parent source is dropped. This way the
thread notices that it should exit immediately.
Fixes #10843
> kafka: immediately cleanup metadata threads on drop

- doc/user/content/connect/materialize-cdc.md
> Bump Materialize CDC back to "Connect"

- test/upgrade/README.md
Clarifying upgrade test behavior
- There are no user facing behavior changes.
> Clarify upgrade test README

- doc/developer/guide.md
Adds a section on some of the useful tools we have checked in to the repo. The shell completion bit will be real after https://github.com/MaterializeInc/materialize/pull/10609 is merged 😄 
I didn't find any reference to these when I was getting my environment set up
- [n/a] This PR has adequate test coverage / QA involvement has been duly considered.
- [n/a] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).
> document some useful dev tools in the repo

- test/kafka-resumption/mzcompose.py
Reverts MaterializeInc/materialize#10892
> Revert "[kafka resumption] More emphatically kill toxiproxy between failure modes"

- src/coord/src/coord/dataflow_builder.rs
> coord: fix merge skew

- src/repr/src/scalar.rs
Suggested by @jkosh44 in the review of #10899.
- N/A.
> repr: don't hardcode empty array and list rows

- Cargo.lock
- src/aws-util/Cargo.toml
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/persist/Cargo.toml
- src/s3-datagen/Cargo.toml
- src/testdrive/Cargo.toml
- test/perf-kinesis/Cargo.toml
* Amalgamates dependabot PRs.
- N/A
> deps: bump to latest AWS SDK

- doc/developer/platform/formalism.md
This PR introduces formalism for the STORAGE and COMPUTE layers in platform. The formalism is meant to describe the abilities and responsibilities, not prescribe implementation details or limit additional possibilities.
> Introduce formalism.md document

- test/antithesis/driver/docker-compose.yml
Antithesis have requested changes to the docker-compose.yml
> antithesis: Update docker-compose.yml

- src/coord/src/catalog.rs
- src/coord/src/coord.rs
This doesn't resolve #10582 on its own, but seems obviously worth doing.
* This PR works towards fixing a recognized bug.
- N/A
> coord: batch timestamp compactions in same transaction

- doc/developer/reading.md
> doc/dev: add COST paper to required reading

- doc/developer/design/20220214_create_cluster.md
@benesch Is this change more accurate? Just trying to clarify the work.
* This PR clarifies a design doc.
- there are no user-facing behavior changes
> doc/design: clarify cluster server/session variable plan

- src/coord/src/coord.rs
This fixes a memory leak and also prevents the coordinator from
attempting to call allow_compaction on sources/tables/indexes that have
been dropped.
Fix #9170.
- N/A
> coord: clean up since_handles

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
> Prepare 0.22.1 dev

- ci/deploy/website.sh
- doc/user/layouts/alias.html
> doc/user: render aliases as server-side redirects in production

- src/coord/src/coord.rs
- src/dataflow-types/src/client.rs
- src/dataflow-types/src/client/controller/storage.rs
- src/dataflow/src/server/storage_state.rs
In the current state of the code we can end up into an invalid state in
the storage controller were we have cleaned up all the state related to
the source due to its frontier advancing to the empty frontier but still
have its `TimestampBindingBox` lying around.
We currently assert that this never happens and can lead to crashes. I
have observed it once here:
https://buildkite.com/materialize/nightlies/builds/707#5b10bc37-be92-4c00-95d2-227296e3ecdb
This patch removes the independent `{Add,Drop}SourceTimestamping`
commands from the storage controller and handles setting up and tearing
down the associated state in exactly two places. Source state is set-up
during CreateSources and and is teared down when the frontier is
advanced to the empty frontier.
> storage: fold timestamp binding commands into CreateSources

- doc/user/content/release-notes.md
Weekly release notes PR.
* Skipped #10867, since it's been added to improve driver compatibility and the comment below makes me think it equates to something behind `--experimental`:
> I've intentionally left the `TimeZone` support relatively basic, as it will probably have to be changed substantially whenever we decide to add real support to timezones.
* Was eager to add #10764, but AFAIU it's been reverted in #10979, so the release note loses effect.
<hr>
~Side note: noticed that #10734 has been merged but the corresponding documentation PR (#10848) is still pending.~ (This has been merged!)
> doc/user: Polish release notes for v0.22.0

- src/dataflow-types/src/client/controller.rs
- src/dataflow-types/src/client/controller/compute.rs
This PR introduces to `Controller` an enum `ReadPolicy`, which allows the coordinator to indicate a policy the controller should use to automatically advance the read capability. There are two variants, `ValidFrom(frontier)` and `LagWriteFrontier(fn)`. The former fixes the read capability at `frontier`, and the latter applies `fn` each time the write frontier (`upper`) updates.
The current calls to `allow_compaction()` are translated into `ValidFrom` policies, which allow compaction up to the indicated frontiers. However, this may eventually be deprecated in favor of the new `set_read_policies` which allows you to do that, or to use the `LagWriteFrontier` variant to allow autocompaction, even while you are not looking.
None of this has been tested yet, as it needs the coordinator to opt …
> Introduce auto-compaction policies to Controller

- src/dataflow-types/src/client/controller.rs
- src/dataflow-types/src/client/controller/compute.rs
I made the changes @mjibson requested of https://github.com/MaterializeInc/materialize/pull/10999 but failed to push them before merging.
> Actually apply the changes requested of #10999

- src/sql/src/plan/query.rs
- src/sql/src/plan/typeconv.rs
- test/sqllogictest/map.slt
- test/sqllogictest/type-promotion.slt
See commits for details.
- N/A
> sql: tweak some char casting comments + code

- doc/user/content/release-notes.md
For consistency with the release notes from earlier versions.
- N/A
> doc/user: wrap v0.22 release notes to 80 characters

- src/coord/src/coord.rs
- src/coord/src/session.rs
Refactor `Session::get_transaction_timestamp` so that the method just
returns the transaction timestamp, rather than potentially *determining*
the timestamp with caller-supplied logic. The caller is now responsible
for setting the transaction timestamp if it comes back `None`.
There is only one caller, so this commit is straightforward code
movement. The motivation is easing some changes in #11019, which need to
make some `async` calls during transaction timestamp determination.
* This PR refactors existing code for the reasons described above.
* Suppress whitespace.
- N/A
> coord: declosureify Session::get_transaction_timestamp

- src/dataflow/src/server/storage_state.rs
This PR has the STORAGE layer respond to table timestamp advance commands with a statement that the table data are now definite through the corresponding time. This is not currently the case, as afaict nothing in STORAGE makes table data durable. However, STORAGE *should* do that, eventually, or at least be / reflect the source of truth on whether the data are definite, as it is responsible for advertising that information back through the controller.
Tables that are not instantiated in dataflows would not report progress of their definite write frontier. This resulted in non-compaction of tables that are not instantiated, and resource exhaustion generally.
cc: @benesch 
Does more need to be said about the durability issue? I can file a follow up issue, but I think it is probably the same …
> Have STORAGE advance table definite frontiers on input advance

- src/coord/src/coord.rs
Responses to remaining messes identified in the review of #11019.
Several nits that wanted fixing, but not additional CI round trips.
-
> Clean up left over #11019 messes

- src/coord/src/catalog.rs
- src/coord/src/coord.rs
- src/coord/src/coord/id_bundle.rs
Per review suggestion in #11043.
- N/A
> coord: rename IdBundle to CollectionIdBundle

- src/dataflow/src/render/sources.rs
Hoist some responsibilities out of `import_table` and into
`import_source`. @frankmcsherry, I think you wanted these hoisted into
`render`: suggestions on how to refactor `import_source` to accomplish
that?
> dataflow: hoist responsibilities out of import_table

- src/coord/src/coord.rs
- src/coord/src/coord/dataflow_builder.rs
- test/sqllogictest/pg_catalog_class.slt
- test/testdrive/catalog.td
This code was just massively misleading. `import_into_dataflow` already
handles this.
Only the last commit is meant to be reviewed here. The other commits are #11064.
- N/A
> coord: remove dead code from the dataflow builder

- test/persistence/compaction/compaction.td
> test/persistence: disable suddenly flaky part of compaction test

- src/dataflow-types/src/client/controller/compute.rs
Previous improvements allow validation now. The bug described in the
issue below was fixed as a side effect of those improvements.
Closes #10835
> dataflow-types: validate IDs during allow_compaction

- src/coord/src/coord/dataflow_builder.rs
Mysteriously, we have perhaps for some time only ever imported one index for each collection. It's hard to imagine, but certainly *at the moment* we only import one index for each collection. This means that e.g. delta joins would form their own arrangements privately, at some cost. This has the potential to substantially reduce the memory and compute costs for these queries.
@umanwizard I'm trying to grok where we should have panicked / `error!`d / etc when it turned out we were not provided the indexes we were promised. Any thoughts? I didn't do that checking here, just fixed the index addition.
-
> Add more than one index per collection

- src/dataflow/src/server/storage_state.rs
> dataflow: make TableState generic over T

- src/coord/src/catalog.rs
- src/coord/src/coord.rs
Inline Catalog::enable_index_ops into its one caller in the coordinator.
This avoids needing to look up the index by ID twice.
- N/A
> coord: simplify alter_index_enable

- src/walkabout/src/ir.rs
The `DateTimeField` type has been copied into the sql-parser crate, so
we no longer need to special case its primitiveness.
The rest of this diff is just whitespace changes; rustfmt really went to
town on reformatting this.
- N/A
> walkabout: remove hack

- src/sql-parser/src/keywords.txt
- src/sql-parser/src/parser.rs
Add support for SHOW SECRETS required for the platform. For the motivation see https://github.com/MaterializeInc/materialize/pull/11022
> sql-parser: support SHOW SECRETS

- src/materialized/src/bin/materialized/tracing.rs
Missed this in the original pr. Just following the docs requirements. Its not 100% clear to me if the docs mean `timeout` or `connect_timeout`, but reading the code appears to use `timeout`
see above
> opentelemetry: setup timeout correctly

- src/coord/src/coord.rs
- src/materialized/src/bin/materialized/main.rs
- src/materialized/src/lib.rs
- src/materialized/tests/util.rs
- src/sqllogictest/src/runner.rs
Improve now configuration and a bit of coord cleanup
> now config and coord cleanup

- src/dataflow-types/src/client.rs
- test/feature-benchmark/scenarios.py
Previously the inserts were partitioned by their position in the
command. This impeded compaction, because it was likely that the
retraction of a piece of data would land on a different worker than the
the original presentation of that data landed on.
This glitch was responsible for the ever-increasing time to `UPDATE` a
nonmaterialized table.
Fix #11071.
- [?] This PR has adequate test coverage / QA involvement has been duly considered.
- N/A
> dataflow-types: partition StorageCommand::Insert by hash of data

- doc/user/content/guides/php-pdo.md
> doc/user: Add PHP PDO guide

- src/dataflow/src/source/kafka.rs
- src/ore/src/thread.rs
This is a generally useful type that ought to live in ore where its
symmetry with the `JoinOnDropHandle` is obvious.
- N/A
> ore: absorb UnparkOnDrop thread handle from dataflow

- src/coord/src/session.rs
- src/coord/src/tail.rs
- src/pgwire/src/protocol.rs
This allows us to stop duplicating so much cancel/error logic. I think this gets us closer to fixing #10763 as well.
> pgwire: plumb full PeekResponseUnary to pgwire

- ci/builder/requirements-core.txt
- ci/builder/requirements-dev.txt
- ci/builder/requirements.txt
Amalgamates the dependabot dependency bumps from the last week.
* Weekly Python dependency bump PR.
- N/A
> deps: bump python dependencies

- src/coord/src/coord.rs
- src/materialized/tests/sql.rs
Force callers to specify exactly how to generate a next timestamp
instead of always adding 1. This allows us to incorporate `now()` into
new timestamp generation instead of having that be dependent on calling
fast_forward.
> coord: make the TimestampOracle generic

- doc/developer/testdrive.md
- src/testdrive/src/action/avro_ocf.rs
- src/testdrive/src/action/file.rs
- src/testdrive/src/action/set.rs
- test/testdrive/github-10587.td
See commits for details.
- N/A
> testdrive: various improvements

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
> Prepare 0.23.1 dev

- doc/developer/platform/README.md
Quick clarifying blurb in the platform `README.md` about how the excitement for performance and availability shouldn't come at the expense of correctness or consistency. Mostly in light of recent discussions about inherent trade-offs between the two, clarifying which ones win. :D
> Reaffirm values of correctness for platform

- doc/developer/reading.md
Add Martin Kleppmann's excellent post on how (not) to do distributed
locking to the required reading list.
* We're going distributed. Martin Kleppmann's blog post on distributed locking is one of the best available resources on how not to do distributed locking.
- N/A
> doc/developer: add blog post on distributed locking

- src/coord/src/coord.rs
Dropping instances needs to remove the catalog state, but also remove the
actual compute instance, which it did not in the past.
This PR fixes a recognized bug: Fixes #11278.
- N/A
> coord: Drop instance drops client

- src/coord/src/client.rs
- src/coord/src/coord.rs
- src/coord/src/session.rs
- src/materialized/tests/pgwire.rs
- src/pgtest/src/lib.rs
- src/pgtest/src/main.rs
- src/pgwire/src/protocol.rs
- test/pgtest-mz/desc.pt
- test/pgtest/desc.pt
Test and verify portals changing mid connection. 
* #11214.
* #11258.
- Fixes a bug where a statement descriptor could change before execution.
> coord: verify portals

- test/feature-benchmark/scenarios.py
The scenario was previously experiencing very large violatility.
To make the numbers stable, drop and re-create the table
prior to each measurement.
Sporadic false positives in Nightly.
> feature-benchmark: fortify the UpdateMultiNoIndex scenario

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
> Prepare 0.24.1 dev

- doc/user/content/guides/golang.md
[Preview Link](https://preview.materialize.com/11174/guides/golang)
This adds docs per #8457. 
I diverged a bit in structure from the Node.js guide. Let me know what you think @ruf-io.
> doc/user: add golang guide

- doc/user/content/release-notes.md
* Weekly release notes PR.
- N/A
> doc/user: add release notes for v0.24.0

- doc/user/config.toml
> Update released versions to include v0.24.0

- src/materialized/src/bin/materialized/tracing.rs
See https://github.com/MaterializeInc/materialize/pull/11378
-
> set the default service name

- src/dataflow-types/src/client.rs
- test/cluster/mzcompose.py
Previously, cancelling a `TcpClient::recv` future could result in
aborting an otherwise successful connection attempt, resulting in a
"wasted" connection that caused the receiving dataflowd process to
terminate. Rewrite `TcpClient::recv` in a state machine style that is
cancellation state.
This makes the cluster tests much more reliable. There are still some
outstanding issues with `test/cluster`, so I'm leaving the issue open
and the test marked as soft_fail.
In particular, there are probably other clients in the stack
(`ActiveReplication`?) that are not cancellation safe. I'm not sure that
making `Client::recv` cancellation safe is the right long-term plan, but
it's the shortest path I could envision to making the demo this week
somewhat reliable.
Touches #11390.
* This PR partially …
> dataflow-types: make TcpClient::recv cancellation safe

- Cargo.lock
- src/aws-util/Cargo.toml
- src/aws-util/src/config.rs
- src/dataflow-types/Cargo.toml
- src/dataflow/Cargo.toml
- src/persist/Cargo.toml
- src/s3-datagen/Cargo.toml
- src/testdrive/Cargo.toml
- test/perf-kinesis/Cargo.toml
* Amalgamates dependency bump PRs.
- N/A
> deps: upgrade to AWS SDK v0.9.0

- src/dataflow-types/src/client.rs
Currently, the state of a partition client is shared across all instances. This can cause cross-talk between instances, especially when dropping an instance causes all state to be reset. We avoid the problem by maintaining state per compute instance, which permits us to maintain the state with a finer granularity.
This PR fixes a recognized bug: #11431 
- N/A
> partitioned client: Partition state by instance

- src/dataflow/src/server/compute_state.rs
Sinks were not being correctly logged on creation, but were "correctly" unlogged when they are dropped. This resulted in some scary warnings showing up. I have left the warnings in place, but we could potentially consider making them hard errors (they are not unrecoverable, but just evidence that something unexplainable has happened; as long as we are diligent about watching for them we can track down the same number of errors).
We were seeing retractions for log elements that were never inserted, which were logged as non-fatal errors but not filed as an issue. …
> Correct sink logging

- src/coord/src/coord.rs
- src/coord/src/coord/dataflow_builder.rs
- src/sql-parser/tests/testdata/ddl
- src/sql/src/plan.rs
- src/sql/src/plan/query.rs
- src/sql/src/plan/statement/ddl.rs
- test/sqllogictest/secret.slt
- test/upgrade/create-in-current_source-secrets.td
Continued work on SECRETS.
This PR adds the evaluation of the AS expr.
This is a follow up to #11362.
This addresses @philip-stoev comment https://github.com/MaterializeInc/materialize/pull/11362#issuecomment-1078930522
> sql, coord: implement CREATE SECRET AS expr evaluation

- Cargo.lock
- LICENSE
- src/materialized/Cargo.toml
> Prepare 0.25.1 dev

- src/persist-client/src/impl/shard.rs
- src/persist-client/src/lib.rs
- src/persist-client/src/write.rs
I left some `TODOs` in the code. Check out #11393 to see it in action.
> persist-client: add compare_and_append(), a cas-esque operation

- misc/python/materialize/mzcompose/__init__.py
Allow the Testdrive container in mzcompose to run persistently.
Individual invocations of testdrive can then be performed without
spawning a new container. This reduces testdrive startup time and
avoids cluttering the "docker ps -a" report with terminated containers.
An example mzcompose.py is included in this commit for PR review purposes
but it will not be merged at the end.
Testing frameworks that rely on repeatedly running testdrive fragments are very slow due to the startup cost associated with using a new startup container every time.
@benesch I am not sure if this is clean enough separation-wise, but:
- docker-compose exec is broken for me, it does nothing and returns nothing. So I had to call `docker exec` directly
- to call docker, one …
> testdrive,mzcompose: Enable a persistent testdrive-svc container
